### ISSUE TITLE
Multi tenant direct line chat?

### ISSUE THREAD

**Issue by kofarrell1076** [Microsoft/BotFramework-WebChat#1000]
Hi all,
I have a directline chat up and running good.

Is there any support for multiple customers on the same bot? I want any customer to install on their website, add a custom id which we provide them and have all the messages come through our bot. We would then sort out where to send the message server side.

**Comment by billba** [comment]
The simplest way to do this is via the user id, e.g. `user: { id: 'Contoso/Fred', name: 'Fred' }`. Then on each message your bot could extract the customer id from the user id.

You could also send such a customer id at the beginning of a session via the backchannel.

One idea for a more robust solution would be for Direct Line to allow you to provide a string when requesting a token, then include that string with every activity sent to the bot. That way your service could provide an API to each customer to provide a token. Your API would pass the customer id to Direct Line when requesting the token, and your bot would read it from the activity when handling the message.

**Comment by kofarrell1076** [comment]
Ok thanks for that. I was looking at the user id so am on the right track. We do generate our own tokens which the customer can use so we'll take a look at sending these via the backchannel and see how it works.

thanks for the help
