### ISSUE TITLE
Carousel do not recalculate its size after window size change

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1004]
## Repro

1. Connect to MockBot
2. Type "carousel", wait until carousel of cards come in
3. Resize Web Chat programmatically (no `window.onresize` event will fire)

### Expected

Left/right flipper should be visible if not all the cards are shown.

### Actual

Left/right flipper are hidden forever, and no way to scroll the carousel.

## Notes

Also related to #997. If step 3 is hide/show Web Chat thru `display: none` or `hidden` attribute, measurement is postponed. But we did not reschedule the measurement.

## Potential fixes

1. Redo measurement from time to time
   * Currently, the measurement is flashy because it remove all activities, add a super-wide card for measurement, then show all activities
2. Not doing measurement
   * Can we not calculating the width of an activity? I suspect we have the calculation because the user may change their CSS. But we might be able to get around with it using other CSS layout strategies, like flex box

**Comment by Kartik1607** [comment]
Hi, I tried to replicate  the issue using code from master branch, but was unable to do so. Here is the [video](https://www.youtube.com/watch?v=aSn-q41twPk)

Is this specific to certain browser or am I doing something wrong?

**Comment by compulim** [comment]
Thanks @Kartik1607.

If I remember my repro correctly, I think I mean resizing it programmatically using JavaScript.

**Comment by compulim** [comment]
This is fixed in v4.
