### ISSUE TITLE
Readme anchor links have "webchat" instead of "web-chat"

### ISSUE THREAD

**Issue by AlexanderEllis** [Microsoft/BotFramework-WebChat#1006]
I noticed this when clicking around the Readme in between section.  Looks like when `webchat` was updated to be `web-chat` these were missed.

Added a PR here https://github.com/Microsoft/BotFramework-WebChat/pull/980 to update them.  Happy to make any necessary changes. Thanks!

**Comment by compulim** [comment]
It's in! Thanks for fixing it. 😉
