### ISSUE TITLE
Detect when all messages are loaded with jquery

### ISSUE THREAD

**Issue by serpino** [Microsoft/BotFramework-WebChat#1014]
I need to detect in some way, from javascript, when the chat has finished loading, whether it is a new conversation or if I retrieve messages from a previous conversation.

I'm using directLine and I've created one using a CSS, a bubble to fold and unfold the chat. What I want to do is that when a new message arrives to the chat if it is hidden, deploy it.

For this the idea is to assign to the chat an event that if a new message arrives it is displayed. The problem I have is that I have to assign it once I have loaded all the messages from the previous conversation, or if it is a new conversation, when I have finished loading the chat completely, but I do not know how I can know the moment with javascript .

Is there any way to know when I upload the chat completely?

The code js is:

`$('.wc-message-group-content').on("DOMNodeInserted", function(){
if (!$('#containerChat').hasClass('appear')){
				//If a message is received with the chat closed, I display it
				$("#messenger-button").click();
			}
		});`

I would also like to know when a new message arrives to the chat from javascript. In this way, if that message arrives with the folded chat, I can display it.

Is there an event in javascript like bot.on () or something like that, to detect when new messages arrive?

Thanks

**Comment by compulim** [comment]
You can look at our [backchannel sample](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/backchannel/index.html#L106) and you can use the same technique to watch the observable when a new message/activity had arrived.

**Comment by serpino** [comment]
Sorry, but that option is not worth it.
That only happens when you press a button. I already have that done for another case.

What I need now is to know when you have finished uploading the chat completely, and to know when a new message is received. all this from javascript.
