### ISSUE TITLE
Adding minimize/close button

### ISSUE THREAD

**Issue by abhishekkant** [Microsoft/BotFramework-WebChat#1015]
Hi 

I am looking to add button to close/ minimize web chat window in the top bar. Is there a setting that can be customized to include these buttons? 

I have seen some customization options of webchat e.g. changing the text in the top bar.. However, I believe that it may not be so simple to implement the buttons.

An illustration of what I am looking for is below:
<img width="379" alt="webchatdesired" src="https://user-images.githubusercontent.com/1725266/41158397-6018e27c-6b46-11e8-873b-7fd3cbdc6291.PNG">

Cheers
Abhishek Kant

**Comment by Kartik1607** [comment]
You would have to add this yourself. There is no predefined option to do so since chats can be fullscreen as well.

**Comment by compulim** [comment]
When working on the minimize function, because there is a bug on carousel, try not to use `display: none` or `hidden` attribute. Until that carousel is replace with a better component, please use `visibility: hidden`.

**Comment by corinagum** [comment]
This has been implemented in a sample! Please check it out [here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/minimize-mode)

**Comment by sanjeevgaut** [comment]
> This has been implemented in a sample! Please check it out [here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/minimize-mode)

link is not available, can you please help me with the correct link.

Thanks

**Comment by philipverlinden** [comment]
> > This has been implemented in a sample! Please check it out [here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/minimize-mode)
> 
> link is not available, can you please help me with the correct link.
> 
> Thanks

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat
