### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by jrios6** [Microsoft/BotFramework-WebChat#1027]
I followed the example by creating a html file with the following code:

<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
  </head>
  <body>
    <div id="bot"/>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>
      BotChat.App({
        directLine: { secret: ''},
        user: { id: 'userid' },
        bot: { id: 'botid' },
        resize: 'detect'
      }, document.getElementById("bot"));
    </script>
  </body>
</html>  

Upon launching this file, I received an Error during WebSocket handshake: Unexpected response code: 400. 

From the Azure Channel dashboard, it also shows There was an error sending this message to your bot: HTTP status code GatewayTimeout. 

How can I fix this?

**Comment by Kartik1607** [comment]
Does your bot work in Azure 'Test in Web Chat' ?

**Comment by jrios6** [comment]
HI @Kartik1607, it doesn't work for 'Test in Web Chat' as well. (with the same Websocket error on the Azure page). However, it works for the iFrame solution. Do you have any idea why it's failing?
