### ISSUE TITLE
Bug in the timeLine formatting for some languages

### ISSUE THREAD

**Issue by enessoylu** [Microsoft/BotFramework-WebChat#1029]
![bug](https://user-images.githubusercontent.com/20838344/42037315-c6874846-7af0-11e8-9385-099545a739c4.png)

There is an unwanted %2 on the timeline string.

https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L281

The code replaces %1 with the time string inside the language specific timeSent string. But for some languages the timeSent string has an extra %2 which is not handled.

https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Strings.ts#L392

**Comment by Kartik1607** [comment]
Strange. That file is the only place where %2 is used. It was added in [this](https://github.com/Microsoft/BotFramework-WebChat/commit/3eba711f9d8525cd0f3163020cd285ed5e8cb137#diff-7033d1b5b24001987e75925ebd825da1) commit. 

Thanks for pointing out the issue. It would be a quick fix.

**Comment by curia-damiano** [comment]
Hi Kartik1607,
I've already submitted the PR https://github.com/Microsoft/BotFramework-WebChat/pull/1140 to fix this issue in Portugese and other languages too.
Regards, Damiano

**Comment by compulim** [comment]
Fixed in #1269.
