### ISSUE TITLE
Any plans to upgrade to react16?

### ISSUE THREAD

**Issue by riteshbhoi** [Microsoft/BotFramework-WebChat#1032]
Team, our react app is react@16 and we are running into issues while integrating chat module, due to multiple package versioning issues. Do you have any plans to upgrade to react 16?

**Comment by Kartik1607** [comment]
What kind of issues are you facing? You can build the WebChat as a different project and then used the compiled botchat.js in your react 16 app.

**Comment by compulim** [comment]
Currently, for the current version of Web Chat (a.k.a. v3), there is no plan to upgrade to React 16. PR is always welcomed.

However, we are preparing the next version of Web Chat (a.k.a. v4), it will be running on React 16.5.0.
