### ISSUE TITLE
Unclear how to minify

### ISSUE THREAD

**Issue by kootenpv** [Microsoft/BotFramework-WebChat#1037]
I was expecting to get minified files when I use `npm run prepublish`.

EDIT: But it appears the current `npm run prepublish` does not work?

**Comment by Kartik1607** [comment]
No, I ran `npm run prepublish` on a fresh new clone.
`botchat.js -> 504KB`
`botchat-es5.js -> 590KB`
were produced.

**Comment by kootenpv** [comment]
I see!
