### ISSUE TITLE
Can't render adaptive card on Internet Explorer

### ISSUE THREAD

**Issue by gagana-hg** [Microsoft/BotFramework-WebChat#1044]
Hello Everyone,

I'm facing an issue in displaying adaptive card(date,time input) on internet explorer, but its working on other browsers . It is displaying **can't render cards**.
The below is the image in browser
**In Internet Explorer**

![image](https://user-images.githubusercontent.com/22505151/42675656-b0049710-8692-11e8-8beb-5e95bffd3631.png)
**In Chrome**

![image](https://user-images.githubusercontent.com/22505151/42675828-5a5c809c-8693-11e8-8554-21a750f98c25.png)

Thanks in advance

**Comment by compulim** [comment]
@corinagum can you see if there are any errors in F12?

**Comment by Kartik1607** [comment]
Internet explorer does not support input type date, which is why your adaptive card is not rendered. I am not aware if adaptive card uses any polyfill for this issue.

**Comment by compulim** [comment]
@corinagum please repro this on IE11 with a non-minified build so we can look into where we throw `Invalid argument`.

**Comment by compulim** [comment]
It is fixed in AC 1.0 but not 0.9. So people using our NPM/CDN build will not get an error for DatePicker. People who use <iframe> embed code will still get it because the <iframe> version is pretty old.

Closing this for now as it did not repro on AC 1.0 (latest build). Will notify when new Web Chat build lands on for <iframe> users.

**Comment by compulim** [comment]
Embed build should land this Friday (or earlier).

You will be able to use different versions of Web Chat in embed by appending `&v=0.14.0` to your query string.

For example, https://webchat.botframework.com/embed/YourBotName?s=your-secret&v=0.14.0, you will be talking to `YourBotName` using Web Chat 0.14.0.

All the versions can be found at our [NPM page](https://www.npmjs.com/package/botframework-webchat?activeTab=versions). Supported versions are:

* `0.11.0-0.11.8`
* >= `0.14.0`
* `master` (sync to GitHub master)
* `latest` (latest production build)
