### ISSUE TITLE
Welcome message and icon disappeared for Web Chat channel 

### ISSUE THREAD

**Issue by luciodale** [Microsoft/BotFramework-WebChat#1047]
The chat bot style on the web channel changed from this:
[https://i.imgur.com/1KoLLvv.png](https://i.imgur.com/1KoLLvv.png) (the left chat)
to this:
[https://i.imgur.com/vKTgQ3w.png](https://i.imgur.com/vKTgQ3w.png) (still the left one)

*to see the screenshots copy and paste manually in browser*

I do not know why but the web chat and direct line channels look the same now. **How do I get the welcoming message and the icon on top again?** This is the code in my html file:

`<iframe style="height: 500px; width:350px;" src='https://webchat.botframework.com/embed/BOT_NAME?s=SECRET_FROM_WEB_CHAT'></iframe>
`
In the portal I have the bot details saved like this:
[https://i.imgur.com/8tZBiyd.png](https://i.imgur.com/8tZBiyd.png)

Any idea? Maybe I changed something accidentally?

**Comment by billba** [comment]
That's the old Web Chat.

**Comment by luciodale** [comment]
@billba Thanks so much for the answer!
@compulim as long as I upgraded the JKD, the left look changed, as it was in an old version.
