### ISSUE TITLE
Speech feature is not working in case of cards (Adaptive Card & other cards)

### ISSUE THREAD

**Issue by UsamaAslam** [Microsoft/BotFramework-WebChat#1051]
Hi,

i am developing Bot in which user communicate to bot through speech . i use azure  text to speech  api. conversation work fine in text as well as speech but when card display speech don't work on card ..
can you help me please .
thanks

**Comment by Kartik1607** [comment]
Hi, can you please post a part of snippet for JSON of adaptive card you are using?

**Comment by UsamaAslam** [comment]
hello , i am using .net for adaptive card . can you share any documentation or link that can help me to find the solution for this problem ..


Is this possible ??

**Comment by corinagum** [comment]
Closing, but tracking this issue is available on https://github.com/Microsoft/BotFramework-WebChat/issues/894
