### ISSUE TITLE
IE11 issue: JS Error when using Webchat as Inline JS in Internet Explorer

### ISSUE THREAD

**Issue by electrobabe** [Microsoft/BotFramework-WebChat#1052]
## Issue Description
We integrated a webChat-version of a bot, once as iFrame and another as inline JS:
- IFrame https://albertbot.chatbotsagency.com/albertbot.html
- Inline JS https://albertbot.chatbotsagency.com/albertbot-inline.html

The later DOES not work in Internet Explorer, it throws a JS error:
> "object doesn't support property or method 'find'"

![screenshot of IE11 - sorry for the German...](https://user-images.githubusercontent.com/4595698/43014203-b6aa4376-8c4b-11e8-8da7-26c21f3fed75.png)

## Reproduction Steps
1. open https://albertbot.chatbotsagency.com/albertbot-inline.html in IE11

FYI *latest* botchat.js is used: https://cdn.botframework.com/botframework-webchat/latest/botchat.js is used

## Expected Behavior
chat starts with welcome message, such as with https://albertbot.chatbotsagency.com/albertbot.html

## Actual Results
JS error when opening the page in IE11

**Comment by Kartik1607** [comment]
You need to use botchat-es5.js

**Comment by electrobabe** [comment]
@Kartik1607 workaround fixes this problem. thanks

**Comment by compulim** [comment]
Looks like it's fixed, closing now.

**Comment by anandvardhandas** [comment]
Instead of using botchat.js, we can use botchat-es5.js for IE11. So similarly do we have a separate botchat.css version for IE11 compatibility because in IE11, Adaptive card contents are not loading in proper format and also in carousel adaptive card, left and right scroll is not working whereas all these things are working perfectly fine in Edge and chrome.

**Comment by Kartik1607** [comment]
@anandvardhandas could you please post screen shots for different browsers.

**Comment by anandvardhandas** [comment]
@Kartik1607  here you go .. now in IE11 left and right scroll is coming now but extra spaces is still coming. Help me remove that. No idea why its coming.
![ie11 compatibility](https://user-images.githubusercontent.com/3183088/44017376-adafedf4-9ef5-11e8-86eb-cbc195925c62.jpg)
![edge_no unnecessary spaces](https://user-images.githubusercontent.com/3183088/44017622-99a90966-9ef6-11e8-90fe-6a94059ad4f4.jpg)
