### ISSUE TITLE
Speech playback not functional on iOS Safari

### ISSUE THREAD

**Issue by egregius313** [Microsoft/BotFramework-WebChat#1056]
I have been working on adding speech recognition/playback to my project. Currently, the availability seems to be:

|                       | Chrome          | Firefox               | Edge               | Safari        |
|----------------|----------------|------------------|-----------------|-------------|
| Windows 10  |  Functional      | Functional*       | Functional       | n/a             |
| macOS          |  Functional       | Functional*       | n/a                  | Functional |
| iOS                |  not supported | not supported | not supported | Only input | 
| Android         | Functional        | -                       | -                      | n/a             |

\* _With [WebRTC shim](https://github.com/webrtc/adapter)_

From what I understand, on iOS web views can't access the microphone from JS-space, so I don't expect the browsers other than Safari on iOS to support the speech recognition/playback. However, the main issue I'm having is that Safari will accept speech recognition, but it will not play back the bot's responses as it does on Windows/macOS. To make it additionally odd, one of the phones we have tested with will playback the first response, and then nothing subsequent.

The mobile Safari versions I've tested are from iOS 11.3.1 and 11.4.1.

The code I use to render the bot (where `speech_is_enabled` is true, and `tokens` is an object which stores the necessary tokens and Azure/Bing subscription keys)
```javascript
const speechOptions = speech_is_enabled ? {
    speechRecognizer: new CognitiveServices.SpeechRecognizer({
        subscriptionKey: tokens.speech
    }),
    speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
        gender: CognitiveServices.SynthesisGender.Female,
        subscriptionKey: tokens.speech,
        voiceName: "Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)"
    })
} : undefined;

BotChat.App({
    directLine: { token: tokens.directline },
    user: { id: userId, name: username },
    bot: { id: tokens.appid },
    sendTyping: true,
    resize: 'detect',
    speechOptions: speechOptions
}, document.getElementById("bot"));
```

Any help is appreciated.

**Comment by compulim** [comment]
For iOS, Edge/Chrome (WebView) is not supported. For Safari, the user need to "prime" the WebRTC or `SpeechRecognition`/`SpeechSynthesis`, that means, it must be triggered from a manual user action.

More discussion and hack at #995.

We are working on the next version of Web Chat that will prime speech properly, until then, the priming hack from #995 should works.

**Comment by sgellock** [comment]
If the provided workaround doesn't address your issue, please open a new issue so we can consider how to help
