### ISSUE TITLE
SuggestedActions that are accidentally sent to the bot are being rendered for the user

### ISSUE THREAD

**Issue by stevengum** [Microsoft/BotFramework-WebChat#1057]
The v4 Emulator which uses [0.13.1-master.6da7b6c](https://github.com/Microsoft/BotFramework-Emulator/blob/v4/packages/app/client/package.json#L91) will show the user SuggestedActions that were sent to the bot. Testing this using the iFrame also renders the same result, SuggestedActions that should be only "seen" by the bot are showing for the user.

On other channels like Skype, if the suggestedAction `to` field is populated with the bot's id, the SuggestedActions do not render for the user. 

Example code from [**BB-Py #100**](https://github.com/Microsoft/botbuilder-python/issues/100):

```py
activity = Activity(
    type=ActivityTypes.message,
    channel_id=activity.channel_id,
    conversation=activity.conversation,
    from_property=activity.recipient,
    recipient=activity.from_property,
    service_url=activity.service_url
)

replies = [
    {
        "title": "Test1",
        "type": ActionTypes.im_back,
        "value": "Test1",
    },
    {
        "title": "Test2",
        "type": ActionTypes.im_back,
        "value": "Test2",
    }
]

activity.text = "My text"
# The following line is where the problem code in the bot exists: `to` uses
# `activity.from_property.id` instead of `activity.recipient.id`
activity.suggested_actions = SuggestedActions(actions=replies, to=[activity.from_property.id])
```

The activity's SuggestedActions show up for the user in WebChat and in the v4 Emulator, whereas this code sent to another channel would not work. Sending this activity to Skype results in the text, `"My text"` appearing, but not the SuggestedActions.

**Comment by compulim** [comment]
For activities with "receipient = bot" and contains suggested actions, Web Chat should not show suggested actions. Is that right?

### Notes to fixer

* [ ] Modify [`activityWithSuggestedActions.ts:10`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/activityWithSuggestedActions.ts#L10) to filter out activities not targeting the current user
   * The "from me" check can be found at [`History.tsx`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L214)
   * We need a "to me" check, and we may need to re-architect that code
* [ ] Add tests

**Comment by corinagum** [comment]
@tonyanziano hey are you working on this atm? Could you let us know your status? :)

**Comment by corinagum** [comment]
Note from Tony: this is already in codebase and test needs to be written. Leaving as 4.2
