### ISSUE TITLE
Mobile : Clicking Submit button hides soft keyboard.

### ISSUE THREAD

**Issue by Kartik1607** [Microsoft/BotFramework-WebChat#1058]
Clicking on submit button (not the enter key on keyboard, but the submit button in the shell component), hides the keyboard. To reply to new message, user would again need to tap on input field to show keyboard. This hinders the user chat experience. 
Instead, once a soft keyboard is shown, it should remain visible, unless user explicitly closes it.

**Comment by compulim** [comment]
### Notes to fixer

- [ ] Send focus back to textbox after click send
   - Check on iOS/Android to see if the soft keyboard flash or not
   - Send focus code can be found at [`Chat.tsx:168`](Chat.tsx#L168)
- [ ] Add test

**Comment by compulim** [comment]
Note to myself: check if this behavior is correct in v4 or not.

**Comment by compulim** [comment]
@seaen Verified this is fixed in v4. 😉
