### ISSUE TITLE
WebChat Browser Compatibility

### ISSUE THREAD

**Issue by JpEncausse** [Microsoft/BotFramework-WebChat#1059]
Hi,

Following this issue (2017)
https://github.com/Microsoft/BotFramework-WebChat/issues/422

Is there a browser compatibility chart (or best practices)? One of our customers use WebChat on a Mobile Web Site with issues on iOS/Android related to screenpixel to device pixel ratio. 

It can be fixed in CSS but I'l like to know if mobile web site (aka chrome/safari on iOS/Android) are targeted by BotFramework WebChat ?

(and if there is other fix to do ?)
Thanks

**Comment by compulim** [comment]
Mobile web site is important market for Web Chat.

We are building a new UI that is responsive and tested on mobile browsers intensively (including speech capability). Stay tuned.

**Comment by blrchen** [comment]
@compulim will current UI version still be maintained?

**Comment by compulim** [comment]
Unfortunately, the current UI will not be maintained.

Please follow [this](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples/custom-style-options) or [this sample](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples/custom-style-set) for styling Web Chat. The new UI also support deep-customization. You can follow [samples here](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples) to see how it can be customized. The most extreme sample we have is called [breakaway speech button](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples/breakaway-speech-button), which remove all UI and recompose Web Chat with 3 new UIs, with less than 100 lines of code..

Although we test Web Chat in multiple mobile browsers, if you see any issues, please capture a screenshot and post it here, along with OS version, etc.

We support all modern browsers (Chrome, Edge, Firefox, Safari, minus 2 versions), plus Internet Explorer 11, on desktop. And we support all default browsers on mobile platform (Safari on iOS and Chrome on Android, minus 2 versions).
