### ISSUE TITLE
Adaptive Card multiselect ChoiceSet

### ISSUE THREAD

**Issue by FilipFilipov** [Microsoft/BotFramework-WebChat#1062]
At the moment a ChoiceSet in an adaptive card with `isMultiSelect: true` is rendered as a group of checkboxes regardless of the `style` property. For `style:compact` shouldn't that be a `<select multiple>` instead?

**Comment by Kartik1607** [comment]
This is related to and should be raised at https://github.com/Microsoft/AdaptiveCards
Also, as a personal choice I prefer checkboxes that `select multiple`

**Comment by FilipFilipov** [comment]
Isn't card rendering implemented at the channel level?

**Comment by compulim** [comment]
@FilipFilipov the card is render at channel level. But unlike other Skype or other channels, Web Chat use the renderer written by Adaptive Cards team.

Can you repro the issue on [Adaptive Cards Visualizer](http://adaptivecards.io/visualizer/)? We use the same engine, just different `host config` file.

**Comment by Kartik1607** [comment]
@compulim even in visualizer they are rendered as check boxes

**Comment by compulim** [comment]
@corinagum can you check if this is related to the issue we talked about?

Also look at the documentation around [Input.ChoiceSet](https://adaptivecards.io/explorer/Input.ChoiceSet.html).

**Comment by compulim** [comment]
I think this one belongs to [Adaptive Cards repository](https://github.com/Microsoft/AdaptiveCards/).

Although Web Chat use renderer from Adaptive Cards, the settings on ChoiceSet is confusing (`style: "compact"` vs. `isMultiSelect: true`) and looks like the renderer they provided to Web Chat does not implement compact + multi-select via `<select multiple>`.

@FilipFilipov can you file a bug on Adaptive Cards instead?

**Comment by FilipFilipov** [comment]
Did it months ago.
https://github.com/Microsoft/AdaptiveCards/issues/1744

**Comment by compulim** [comment]
Looks like they have not change their mind yet, unfortunately.

IMO, using browser native controls and honoring them is important. For example, mobile phone can show up different UI that help the user to easily multiselect things.
