### ISSUE TITLE
iOS speech recognition stops after device is locked

### ISSUE THREAD

**Issue by rosskyl** [Microsoft/BotFramework-WebChat#1064]
In Safari on an iOS device, speech recognition stops working if the device is locked then unlocked. The mic button will still change to purple, but the browser will not actually record audio. Reloading the page does not fix it and only opening a new tab and navigating to the same page fixes it. I can tell it isn't actually recording audio because there is no red mic icon in the address bar like there is when it works.

I am using the following to register the bot:
```
const params = BotChat.queryParams(location.search);

const user = {
    id: document.getElementById("userId").value,
    name: document.getElementById("userName").value
};

const bot = {
    id: params['botid'] || 'botid',
    name: params['botname'] || 'botname'
};

window.botchatDebug = params['debug'] && params['debug'] === 'true';

var speechOptions;
if (Modernizr.speechsynthesis) {
    speechOptions = {
        speechRecognizer: new CognitiveServices.SpeechRecognizer({
            fetchCallback: function (authFetchEventId) { return getBingToken() },
            fetchOnExpiryCallback: function (authFetchEventId) { getBingToken() }
        }),
        speechSynthesizer: new BotChat.Speech.BrowserSpeechSynthesizer()
    };
}
else if (Modernizr.getusermedia) {
    speechOptions = {
        speechRecognizer: new CognitiveServices.SpeechRecognizer({
            fetchCallback: function (authFetchEventId) { return getBingToken() },
            fetchOnExpiryCallback: function (authFetchEventId) { getBingToken() }
        }),
        speechSynthesizer: null
    };
}
else {
    speechOptions = null;
}

var conversationId = getCookie("conversationId");
var botToken = getCookie("conversationToken");

var botConnection;
var sendInitialMessage = true;
if (conversationId == "" || botToken == "") {
    botConnection = new BotChat.DirectLine({
        domain: params['domain'],
        token: document.getElementById("directLineToken").value,
        webSocket: params['webSocket'] && params['webSocket'] === 'true' // defaults to true
    });
}
else {
    sendInitialMessage = false;
    console.log("resuming a conversation");
    botConnection = new BotChat.DirectLine({
        domain: params['domain'],
        token: botToken,
        webSocket: false,
        conversationId: conversationId
    })

    deleteCookie("conversationId");
    deleteCookie("conversationToken");
}

BotChat.App({
    bot: bot,
    locale: params['locale'],
    resize: 'detect',
    speechOptions: speechOptions,
    user: user,
    botConnection: botConnection
}, document.getElementById('BotChatGoesHere'));

var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);

function SpeakText() {
    var msg = new SpeechSynthesisUtterance();
    window.speechSynthesis.speak(msg);

    document.getElementsByClassName("wc-mic")[0].removeEventListener("click", SpeakText);
}

if (isSafari) {

    window.addEventListener("load", function () {
        document.getElementsByClassName("wc-mic")[0].addEventListener("click", SpeakText);
    });
}

// Needed to change between the two audio contexts
var AudioContext = window.AudioContext || window.webkitAudioContext;

// Sets the old style getUserMedia to use the new style that is supported in more browsers even though the framework uses the new style
if (window.navigator.mediaDevices.getUserMedia && !window.navigator.getUserMedia) {
    window.navigator.getUserMedia = function (constraints, successCallback, errorCallback) {
        window.navigator.mediaDevices.getUserMedia(constraints)
            .then(function (e) {
                successCallback(e);
            })
            .catch(function (e) {
                errorCallback(e);
            });
    };
}
```

**Comment by compulim** [comment]
@corinagum do you think it's related to #995? Let me know if you need any device to test it out.

**Comment by corinagum** [comment]
hi @rosskyl thank you for your patience during investigation of this issue. Unfortunately I have not been able to repro the problem that you describe - when using latest WebChat to enable speech on a bot, locking and re-locking iOS does not cause the microphone to stop working. Could you answer the following questions? 

- What version of WebChat is your bot utilizing?
- What device is this on? iPhone? iPad? etc.
- What version of iOS is the iPhone using?
- If you visit [this page](https://webrtc.github.io/samples/src/content/getusermedia/volume/) on iOS, are you able to repro the bug? If so, this would imply a browser issue as opposed to bot issue.

**Comment by rosskyl** [comment]
After updating to the most recent version of iOS I am unable to reproduce the issue. After a bit more investigation, I believe it was a but with safari as it wasn't just the web chat that this issue would show up on. This would've been on an iPad pro running iOS 11.3 with the most recent version of web chat at the time.

**Comment by corinagum** [comment]
Great, thanks for getting back to us. I'll close this issue as resolved.

**Comment by rosskyl** [comment]
I used the following to change the default voice for all of the browsers I tested. This only works for the browser speech recognizer.


```
var femaleVoice = null;

if (Modernizr.speechsynthesis) {
    var baseSpeechPrototype = SpeechSynthesisUtterance.prototype;
    SpeechSynthesisUtterance = function (msg) {
        var utterance = new baseSpeechPrototype.constructor(msg);

        if (femaleVoice != null)
            utterance.voice = femaleVoice;

        return utterance;
    }

    window.speechSynthesis.onvoiceschanged = function () {
        var voice = "Microsoft Zira";
        var safariVoice = "Samantha";

        var voices = window.speechSynthesis.getVoices();
        voices.forEach(function (v) {
            if (v.name.startsWith(voice))
                femaleVoice = v;
            else if (v.name == safariVoice && v.lang == "en-US")
                femaleVoice = v;
        })
    }
}
```

**Comment by Tamoormughal** [comment]
hi
thank you for your participation .. . but this code is not working on my
side . can you send me full page of the code i will be very thanks full to
you

**Comment by UsamaAslam** [comment]
same issue i have help us @rosskyl  @compulim @corinagum @peterblazejewicz

**Comment by Tamoormughal** [comment]
thanks this code is properly working on all end except i phone safari pick up male voice ... so how i can i change default voice male of safari iPhone?????
 this is the code
................................................................

        /*! modernizr 3.6.0 (Custom Build) | MIT *
        * https://modernizr.com/download/?-getusermedia-speechsynthesis !*/
        !function (e, n, s) { function i(e, n) { return typeof e === n } function o() { var e, n, s, o, a, f, d; for (var c in t) if (t.hasOwnProperty(c)) { if (e = [], n = t[c], n.name && (e.push(n.name.toLowerCase()), n.options && n.options.aliases && n.options.aliases.length)) for (s = 0; s < n.options.aliases.length; s++)e.push(n.options.aliases[s].toLowerCase()); for (o = i(n.fn, "function") ? n.fn() : n.fn, a = 0; a < e.length; a++)f = e[a], d = f.split("."), 1 === d.length ? Modernizr[d[0]] = o : (!Modernizr[d[0]] || Modernizr[d[0]] instanceof Boolean || (Modernizr[d[0]] = new Boolean(Modernizr[d[0]])), Modernizr[d[0]][d[1]] = o), r.push((o ? "" : "no-") + d.join("-")) } } var t = [], a = { _version: "3.6.0", _config: { classPrefix: "", enableClasses: !0, enableJSClass: !0, usePrefixes: !0 }, _q: [], on: function (e, n) { var s = this; setTimeout(function () { n(s[e]) }, 0) }, addTest: function (e, n, s) { t.push({ name: e, fn: n, options: s }) }, addAsyncTest: function (e) { t.push({ name: null, fn: e          }) } }, Modernizr = function () { }; Modernizr.prototype = a, Modernizr = new Modernizr, Modernizr.addTest("speechsynthesis", "SpeechSynthesisUtterance" in e), Modernizr.addTest("getUserMedia", "mediaDevices" in navigator && "getUserMedia" in navigator.mediaDevices); var r = []; o(), delete a.addTest, delete a.addAsyncTest; for (var f = 0; f < Modernizr._q.length; f++)Modernizr._q[f](); e.Modernizr = Modernizr }(window, document);

        // Necessary for safari
        // Safari will only speak after speaking from a button click
        var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
        const params = BotChat.queryParams(location.search);
        debugger;
        function SpeakText() {
            var msg = new SpeechSynthesisUtterance();
            window.speechSynthesis.speak(msg);

            document.getElementsByClassName("wc-mic")[0].removeEventListener("click", SpeakText);
        }

        if (isSafari) {

            window.addEventListener("load", function () {
                document.getElementsByClassName("wc-mic")[0].addEventListener("click", SpeakText);
            });
        }

        var femaleVoice = null;

        if (Modernizr.speechsynthesis) {
            var baseSpeechPrototype = SpeechSynthesisUtterance.prototype;
            SpeechSynthesisUtterance = function (msg) {
                var utterance = new baseSpeechPrototype.constructor(msg);

                if (femaleVoice != null)
                    utterance.voice = femaleVoice;

                return utterance;
            }

            window.speechSynthesis.onvoiceschanged = function () {
                var voice = "Microsoft Zira";
                var safariVoice = "Samantha";

                var voices = window.speechSynthesis.getVoices();
                voices.forEach(function (v) {
                    if (v.name.startsWith(voice))
                        femaleVoice = v;
                    else if (v.name == safariVoice && v.lang == "en-US")
                        femaleVoice = v;
                })
            }
        }

        //// Needed to change between the two audio contexts
        var AudioContext = window.AudioContext || window.webkitAudioContext;

        //// Sets the old style getUserMedia to use the new style that is supported in more browsers even though the framework uses the new style
        if (window.navigator.mediaDevices.getUserMedia && !window.navigator.getUserMedia) {
            window.navigator.getUserMedia = function (constraints, successCallback, errorCallback) {
                window.navigator.mediaDevices.getUserMedia(constraints)
                    .then(function (e) {
                        successCallback(e);
                    })
                    .catch(function (e) {
                        errorCallback(e);
                    });
            };
        }

        const bot = {
            id: params['botid'] || 'botid',
            name: params['botname'] || 'botname'
        };

        window.botchatDebug = params['debug'] && params['debug'] === 'true';

        var speechOptions;
        if (Modernizr.speechsynthesis) {
            speechOptions = {
                speechRecognizer: new CognitiveServices.SpeechRecognizer({
                    fetchCallback: function (authFetchEventId) { return getBingToken() },
                    fetchOnExpiryCallback: function (authFetchEventId) { getBingToken() }
                }),
                speechSynthesizer: new BotChat.Speech.BrowserSpeechSynthesizer()
            };
        }
        else if (Modernizr.getusermedia) {
            speechOptions = {
                speechRecognizer: new CognitiveServices.SpeechRecognizer({
                    fetchCallback: function (authFetchEventId) { return getBingToken() },
                    fetchOnExpiryCallback: function (authFetchEventId) { getBingToken() }
                }),
                speechSynthesizer: null
            };
        }
        else {
            speechOptions = null;
        }
        

        // for bot

        var botConnection = new BotChat.DirectLine({
            domain: params['domain'],
            //token: document.getElementById("directLineToken").value,
            secret: 'Secret',
            webSocket: params['webSocket'] && params['webSocket'] === 'true' // defaults to true
        });

       
            BotChat.App({
                sendTyping: true,
                locale: params['locale'],
                resize: 'detect',
                speechOptions: speechOptions,
                user: { id:'ID' name: "You" },
                bot: { id: 'Vera', name: "Vera" },
                botConnection: botConnection
            }, document.getElementById('BotChatElement'));


        function getBingToken() {
            // Normally this token fetch is done from your secured backend to avoid exposing the API key and this call
            // would be to your backend, or to retrieve a token that was served as part of the original page.
            return fetch(
                'https://api.cognitive.microsoft.com/sts/v1.0/issueToken',
                {
                    headers: {
                        'Ocp-Apim-Subscription-Key': 'Key'
                    },
                    method: 'POST'
                }
                //).then(res => res.text());
            ).then(function (res) { return res.text() });
        }

**Comment by UsamaAslam** [comment]
Thanks for your help @rosskyl . do you know how can we add custom speech (LUIS custom speech) in our code using the code you send me ?
I create custom speech using : https://westus.cris.ai/Home/CustomSpeech 
Now i want to add it and work like bing speech .

Do you have any details about this ?

Thank in advance .
