### ISSUE TITLE
IE : Adaptive Card Issue

### ISSUE THREAD

**Issue by CrazyGenexz** [Microsoft/BotFramework-WebChat#1067]
Hello
So, the problem is that my adaptive card shows normally in Chrome, Firefox and Edge, but when i use Internet Explorer the text displays like this: 
![captura](https://user-images.githubusercontent.com/42007541/43537956-52e5bfa2-9586-11e8-9592-41b476be61cf.jpg)
I need to use IE for my project unfortunately, so i would appreciate a lot the info (compatibility, code, etc.)

**Comment by corinagum** [comment]
@CrazyGenexz What version of webchat are you using currently?

**Comment by CrazyGenexz** [comment]
![frame1](https://user-images.githubusercontent.com/42007541/43593897-8fe25682-963e-11e8-9934-115fbb933a49.png)
![frame2](https://user-images.githubusercontent.com/42007541/43593899-90d39614-963e-11e8-8ec1-150249b2d70d.png)

**Comment by corinagum** [comment]
Hi @CrazyGenexz, thanks for the information. I'm actually hoping to find out what version of webchat you're using. Are you using a CDN? If yes, you can find the version you're using in the url: it might say *latest* like so:"https://cdn.botframework.com/botframework-webchat/latest/botchat.css". It might also be a number like this: 0.11.4 or 0.14.1. 
If you're using an embed, that means you're using the Azure portal webchat control. 

If you're not sure what version you're using, you can also take a look at [this comment](https://github.com/Microsoft/BotFramework-WebChat/issues/1001#issuecomment-409712858) by @compulim for more information.

**Comment by corinagum** [comment]
Closing due to lack of response.

**Comment by Al-mck** [comment]
Hi,

I have the same issue when I open the chat on IE. I using the v3. It's works on IE with v11 and document-modes = 11 or edge but when document-modes = 10, I have the same display like crazyGenexz.

**Comment by compulim** [comment]
Thanks @Al-mck, will investigate.

In short, I am unsure if we should continue to support IE10 (circa 2012). Do you think you can use <meta> tag to set document mode to 11?

**Comment by sgellock** [comment]
The team has made the decision not to support IE10.
