### ISSUE TITLE
How to finish my work with BotFramework (dot Net)? 

### ISSUE THREAD

**Issue by RafaelVenancioGD** [Microsoft/BotFramework-WebChat#1068]
Hi,

The simple question is, there is a way to publish my own version of Embed Web chat into Azure ? Let me explain my situation.

For the last month I've done all tasks needed to chatbot cicle, qnaMaker service, Luis integration, complete chat cicle, save and retrieve user data in azure cosmo DB. Actually I'm using Web chat channel (Embed) to test the bot, the only problem is the Iframe Layout, because I can't change with Dot Net project that I created and I only see tutorials with Node.js.

I need to change the layout of Web Chat to use in my website. If is not possible to use this Repo, how can I change or create the Iframe layout in Dot Net version in Azure ?

**Comment by pratyushdhanuka** [comment]
you can perhaps override the css by calling your own css after botchat.css file
this way perhaps you can custom all the css,

few inline css are created in botchat.js file
but that also can be over-ridden using important!

this is how I have done it for my project
though I have only changed very minor stuffs so far

**Comment by RafaelVenancioGD** [comment]
I've download the last version of botchat js and css to create my own version and publish in my Azure. Thanks for the help.
