### ISSUE TITLE
HTML code not rendered in Hero card

### ISSUE THREAD

**Issue by deepanigi** [Microsoft/BotFramework-WebChat#1070]
Hi All,

Previously 1 week ago the html code in subtitle of the Hero card was rendered perfectly in UI. But now it suddenly stopped working.Now the html tag "< ul >" and  "< li >" is not rendered on UI and displayed as it is.

`  
var capacity = "<ul><li>Expected </li><li>line 2</li></ul>"
var card = new builder.HeroCard(session)
                    .title(element.name)
                    .subtitle(capacity)
                    .images([builder.CardImage.create(session, url)])`

Bot library used :https://cdn.botframework.com/botframework-webchat/latest/botchat.js

**Comment by corinagum** [comment]
Hi @deepanigi 
HTML in Markdown was [disabled in July 2017](https://github.com/Microsoft/BotFramework-WebChat/pull/606) for a few reasons.

- Some channels don't render HTML in Markdown correctly, and disabling it creates a more consistent behavior across channels
- Some people were worried about HTML as a source of security breach, and removing it from Markdown reduces that security concern. 

If you would like to enable HTML in Markdown, you can fork WebChat and set[ this line to true](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/FormattedText.tsx#L30). `{ html: true }`
