### ISSUE TITLE
Update charset of webchat.js in all samples

### ISSUE THREAD

**Issue by JobaDiniz** [Microsoft/BotFramework-WebChat#1071]
The TypeScript [Strings.ts L188](https://github.com/Microsoft/BotFramework-WebChat/blob/v0.14.1/src/Strings.ts#L188) is correct: `timeSent: ' às %1'`. But the [transpiled version](https://cdn.botframework.com/botframework-webchat/0.14.1/botchat-es5.js) is not: 

![image](https://user-images.githubusercontent.com/165290/43855204-46d27684-9b1b-11e8-9a78-2bfd3efd637a.png)

**Comment by sgellock** [comment]
need to verify against v4 bits

**Comment by compulim** [comment]
Probably problem on the bundler. Checks if it is fixed in v4.

**Comment by compulim** [comment]
@JobaDiniz we verified our bit is encoded in UTF-8. When you are loading it, can you add `charset="utf-8"` to your script tag?

```html
<script src=".../botchat.js" charset="utf-8"></script>
```

Otherwise, this should have been fixed in v4.

**Comment by jiruss** [comment]
I am also having this problem in v4 of webchat from my local custom build and CDN. Adding the charset="utf-8" to the script tag "fixes" the issue but this isn't doc'd anywhere so we should at least add it to the docs please. 
![charproblemwebchat4](https://user-images.githubusercontent.com/20343098/51495668-292d3900-1d8b-11e9-8289-a9a37c0fb67a.PNG)


> @JobaDiniz we verified our bit is encoded in UTF-8. When you are loading it, can you add `charset="utf-8"` to your script tag?
> 
> ```
> <script src=".../botchat.js" charset="utf-8"></script>
> ```
> 
> Otherwise, this should have been fixed in v4.

**Comment by corinagum** [comment]
We will update our samples so that users do not hit this issue in the future. :)

**Comment by corinagum** [comment]
I found that `charset` in `<script>` is deprecated on [MDN script element page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Deprecated_attributes)

We will have to change server-side settings to set utf-8 during deployment.

**Comment by compulim** [comment]
Since blobxfer does not support setting `x-ms-blob-content-type` during upload, after deployment, we need to run an additional script to modify the content type for uploaded JavaScript files, setting it to `text/javascript; charset=utf-8` should work.

We can adopt the following code as the base of the script.

```js
require('dotenv/config');

const { BlobService } = require('azure-storage');
const { promisify } = require('util');

const {
  AZURE_STORAGE_ACCOUNT_NAME,
  AZURE_STORAGE_ACCOUNT_KEY,
  AZURE_STORAGE_CONTAINER
} = process.env;

(async function () {
  const blobService = new BlobService(AZURE_STORAGE_ACCOUNT_NAME, AZURE_STORAGE_ACCOUNT_KEY);
  const getBlobProperties = promisify(blobService.getBlobProperties.bind(blobService));
  const setBlobProperties = promisify(blobService.setBlobProperties.bind(blobService));

  const { contentSettings } = await getBlobProperties(AZURE_STORAGE_CONTAINER, 'webchat.js');

  await setBlobProperties('scroll-test', 'webchat.js', {
    ...contentSettings,
    contentType: 'text/javascript; charset=utf-8'
  });
})().catch(err => console.error(err));
```

**Comment by compulim** [comment]
Filed a bug to blobxfer team, https://github.com/Azure/blobxfer/issues/95.

In the meanwhile, we still need to update our deployment script to add `charset` to uploaded files.

**Comment by compulim** [comment]
Tested with the following code, which use the latest Azure Storage SDK.

```js
const {
  Aborter,
  BlobURL,
  ContainerURL,
  ServiceURL,
  SharedKeyCredential,
  StorageURL
} = require('@azure/storage-blob');

const ACCOUNT_NAME = '';
const ACCOUNT_KEY = '';
const CONTAINER_NAME = '';
const BLOB_NAME = 'webchat.js';

async function main() {
  const credential = new SharedKeyCredential(ACCOUNT_NAME, ACCOUNT_KEY);
  const pipeline = StorageURL.newPipeline(credential);
  const serviceURL = new ServiceURL(
    `https://${ ACCOUNT_NAME }.blob.core.windows.net`,
    pipeline
  );
  const containerURL = ContainerURL.fromServiceURL(
    serviceURL,
    CONTAINER_NAME
  );
  const blobURL = BlobURL.fromContainerURL(
    containerURL,
    BLOB_NAME
  );

await blobURL.setHTTPHeaders(
  Aborter.none,
  {
    blobContentType: 'text/javascript; charset=utf-8'
  }
);
}

main().catch(err => console.error(err));
```
