### ISSUE TITLE
Sample: Add markdown-it-emoji to automatically convert :) into 😄

### ISSUE THREAD

**Issue by JobaDiniz** [microsoft/BotFramework-WebChat#1072]
If my bot server sends a message `Hi :)`, the emotion :smile: will be rendered in _Facebook_ channel but not in _Web Chat_.
Is there a workaround?

**Comment by Kartik1607** [comment]
You would have to add markdown for emotions like :) 

Or you would have to replace the emotions with unicode representation

**Comment by compulim** [comment]
You could add emoji to Markdown-It via this [plugin](https://www.npmjs.com/package/markdown-it-emoji).

You can refer to [this sample](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples/minimal-bundle-with-markdown) to customize Markdown-It in Web Chat.

I am leaving this issue open, so we can add a new sample for [`markdown-it-emoji`](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples/minimal-bundle-with-markdown) in Web Chat. Feel free to contribute. :)

**Comment by compulim** [comment]
Since the `markdown-it-emoji` plug-in may not handle different skin colors and other selections, we need to document clearly that this sample is not a full replacement for emoji, but a quick-and-reduced substitute to OS emoji keyboard. The dev who adopt this sample will need to understand the reduced functionality.

**Comment by corinagum** [comment]
I built an unofficial sample showing users how to implement `markdown-it-emoji`. Please see the sample at my [WebChat-Samples repo](https://github.com/corinagum/WebChat-Samples/tree/master/emoji).

## Notes:

1. For now, this sample renders emoji in the transcript, both from the user and the bot.
2. Emoji working in the SendBox is TBD! Stay tuned. :)
