### ISSUE TITLE
Sample: Sound alert when new message come

### ISSUE THREAD

**Issue by iamgraviteja** [microsoft/BotFramework-WebChat#1073]
Is there a way to add tones for send/receive messages?

**Comment by Kartik1607** [comment]
Not implemented in current version, but you could modify the code and play a sound whenever an action for sending or receiving message is dissipated.

**Comment by iamgraviteja** [comment]
@Kartik1607 Do you've any links or resources ?

**Comment by Kartik1607** [comment]
@iamgraviteja I am able to follow you. What kind of resource do you need? Do you need help with implementation? You would have to create an epic in store.tsx which would be responsible for playing the audio.

**Comment by iamgraviteja** [comment]
Kind of approach. Like do I need to use a npm package or an audio tag to play sound when new messages are sent/received?

**Comment by sgellock** [comment]
We will consider providing a sample that will show how to implement this functionality

**Comment by CoHealer** [comment]
Removing @stevkan assignment as this is now an engineering work item for tracking

**Comment by compulim** [comment]
Unassigning myself, we only assign work items in current iteration. This is backlog.
