### ISSUE TITLE
Document Upload Issue: Multiple chat in Same window using different bot connection

### ISSUE THREAD

**Issue by narik1989** [Microsoft/BotFramework-WebChat#1076]
Hi,

I am trying to create an application where the user (Application 1) can be in chat with multiple users(Application 2) using directline bot js. I create a new connection for every individual chat with user. Say i am chatting with User 1 and User 2. If i send a message to any user the respective user receives it. When i try to send an image (or any document in this case) it is always going to first user that i initiated chat with. Is there something i am missing or sending the document always takes the first bot connection i created?

Can anyone please help me out on this.

Thanks

**Comment by compulim** [comment]
Currently, Bot Framework does not support multiple users.
