### ISSUE TITLE
Speech option is not working

### ISSUE THREAD

**Issue by narik1989** [Microsoft/BotFramework-WebChat#1077]
Hi,

I have hosted my application in one of the servers which does not have a SSL certificate. Hence the web site is HTTP protocol. I tried to integrate the speech options in that web site using directline framework. The speech is not working. This is the error i get. 

**error: Error occurred during microphone initialization: NotSupportedError: Only secure origins are allowed**

Can anyone help me on this.

Thanks

**Comment by compulim** [comment]
Browser limits what website can use microphone. I think all modern browsers now block microphone access on non-HTTPS website, there is no way to workaround browser security check.

To enable speech options, you will need to secure your website using HTTPS certificate. LetsEncrypt.org offer free SSL certificates you can use for your site.
