### ISSUE TITLE
`adaptiveCardsHostConfig` should be optional

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1079]
At [`src/Chat.tsx:18`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L18), we should not force everyone to pass `adaptiveCardsHostConfig` in.

`adaptiveCardsHostConfig` is optional as seen in [`src/Chat.tsx:70`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L70).

## Note to fixer

* [ ] Set `adaptiveCardsHostConfig: any` to `adaptiveCardsHostConfig?: any`.

**Comment by darrenj** [comment]
Workaround for now is to set adaptiveCardsHostConfig to null. This is working in my sample project.
