### ISSUE TITLE
Dial back Web Chat retries

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotFramework-WebChat#1080]
Web Chat aggressively retries under two conditions:

- When Web Chat is polling with GET and receives a 404, it continues polling. A 404 is unlikely to be resolved as the resource is gone.
- If Web Chat receives an HTTP 400 when opening a websocket connection, it retries very quickly

There may be other cases but these two should be reviewed and we should have a different retry policy -- either progressively back off the retry interval, or do not retry at all.

**Comment by compulim** [comment]
Will do.

Do we have 429 too?

**Comment by sgellock** [comment]
opening a new issue to track the specific 429 work, once the service supports it

**Comment by dandriscoll** [comment]
The service supports 429 already. We populate the retry-after header per the spec.
