### ISSUE TITLE
Empty half-size bubble show up on a message with empty string "text"

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1103]
```js
{
  type: "message"
  text: ""
}
```

This activity should not show up as a half-size bubble. The bug repro in Emulator. Need to check if it repro on Web Chat latest because we recently have a fix on it.

Also need to check if we filter them out correctly, so we don't accidentally filtered out suggested actions.

**Comment by compulim** [comment]
@corinagum, as bulleted tasks:

- Add `empty` command to MockBot to send `{ type: 'message', text: '' }`
   - Try to repro on
      - Emulator v4
      - Latest Web Chat (or `>=@0.12.1`)
      - Web Chat v4 (just hit the playground)
- Add `empty-with-suggested-actions` command (or `empty suggested-actions`, which is harder)
   - `{ type: 'message', text: '', suggestedActions: { actions: [{ type: 'imBack', title: 'Hello', value: 'Hello' }] } }`
   - It should show no bubble, but with suggested actions
   - Try to repro on
      - Emulator v4
      - Latest Web Chat (or `>=@0.12.1`)
      - Web Chat v4

**Comment by compulim** [comment]
We might already have this one fixed in v4. And we might already have this "empty-with-suggested-actions" command in MockBot.

**Comment by tonyanziano** [comment]
This is fixed in v4

**Comment by gouseshake0786** [comment]
![Bubble-Responsein Chatbot](https://user-images.githubusercontent.com/25403427/63826329-25ded900-c97c-11e9-9889-688770465c6c.PNG)
Can anyone suggest me how to remove that bubble activity text in chatbot window
