### ISSUE TITLE
OAuth card button does not work

### ISSUE THREAD

**Issue by Danieladu** [Microsoft/BotFramework-WebChat#1106]
OAuthCard's original button schema is :
```
{
            "title": "Login In",
            "type": "signin"
}
```

In Bot framework Emulator, an OAuthCard‘s button rendered as 
```
{
            "title": "Login In",
            "type": "openurl",
            "value": "Filled by BotFramework"
}
```

when I click the button, a window directed to "value" is opened. so I can get the token from callback.

But in webchat, I get the json data below:
```
{
            "title": "Login In",
            "type": "signin",
            "value": "Filled by BotFramework"
}
```

The type of the button is still "signin". When I click the button, also, a new window is opened. but the url is undefined. 

Modify the origin scheme to "openurl" does not work, the value of "value" could be null.

It makes me confused.

**Comment by compulim** [comment]
Do you mean the "Filled by BotFramework" is something like https://token.botframework.com/...?

When you send an OAuthCard over the wire, on the Web Chat side, it became:

```json
{
  "contentType": "application/vnd.microsoft.card.oauth",
  "content": {
    "text": "Sign into GitHub",
    "connectionName": "github-mockbot",
    "buttons": [
      {
        "type": "signin",
        "title": "Sign in",
        "value": "https://token.botframework.com/api/oauth/signin?settingId=...&redirectUri=https%3a%2f%2ftoken.botframework.com%2f..."
      }
    ]
  }
}
```

And after you click on the link, it will:
1. Open a new window without URL (about:blank)
2. Call `getSessionId()` on DirectLineJS, to get the URL out
3. Point the new window to the URL retrieved from step 2
4. The new window will navigate to your OAuth provider (e.g. GitHub or AAD)
5. After OAuth complete, it will redirect it to Bot Framework, depends on your flow
   - It will show magic code, that the user can copy and paste
   - It will complete the flow without magic code, the bot will have the OAuth access token thru an activity of `type === 'event' && name === 'tokens/response'`
6. (For magic code flow only) Your bot code need to pass the magic code (v4 SDK has `OAuthPrompt.recognize()` to do the trick), and the return of that call will have the OAuth token

Is it same on your side?

**Comment by Danieladu** [comment]
Thanks for your reply @compulim. 

This is exactly what we are confused about.

The difficulty is that we just use the iframe value from bot service of Azure. (Embed code from webchat channel). So botchat.js and directLine.js is loaded by <iframe> automatically.  

To us, webchat is a show window totally, not a developer tool. No code-writing and change would be made in it. 

Absolutely open a window with URL(https://token.botframework.com/....) is what we want. But, for step 2. Call `getSessionId()` and get URL out, If we don't customize it, we won't get this value. Is there any solution just open the window with URL and without calling API?

**Comment by compulim** [comment]
Looks like there are some fixes coming to fix the OAuth card in `<iframe>`. It's currently broken in `0.14.2`.

Can you try hit your bot using `<iframe src="https://webchat.botframework.com/embed/YOUR_BOT?s=YOUR_KEY&v=master">`?

The extra `&v=master` will point you to the latest `master` branch as on GitHub, which I verified it is working with OAuth card.

**Comment by Danieladu** [comment]
Thanks, @compulim.  It works. Maybe the latest version fixes this problem. I can get the magic code after login in.

**Comment by Danieladu** [comment]
#1104

**Comment by compulim** [comment]
Wonderful! Closing this for now.

Let us know what you think about the OAuth, we have more stories around authentication coming at Ignite conference next-next Monday.
