### ISSUE TITLE
Need for buttons which disappear on click.

### ISSUE THREAD

**Issue by sagarvadodaria** [Microsoft/BotFramework-WebChat#1109]
Its no surprise that we need buttons which disappear on click. Even telerik has something good as per this URL https://demos.telerik.com/kendo-ui/chat/travel. 

Is there a way to do this?

**Comment by EricDahlvang** [comment]
Suggested Actions provide this functionality: https://docs.botframework.com/en-us/channel-inspector/channels/WebChat/

https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-suggested-actions?view=azure-bot-service-3.0
