### ISSUE TITLE
how to hide directLine secret, user and bot id..

### ISSUE THREAD

**Issue by Primtek** [Microsoft/BotFramework-WebChat#1121]
Hi all,

referring to script below:

<script>
      BotChat.App({
        directLine: { secret: 'xxxxx},
        user: { id: 'mybot },
        bot: { id: 'mybot' },
        resize: 'detect'
      }, document.getElementById("bot"));
</script>

how to hide such info?

please help
..

thanks

**Comment by compulim** [comment]
For Direct Line secret, you will need to implement a server solution to exchange the secret into token. That's the only way to make sure the secret does not expose to the client.

For user ID, it is not able to hide. You should sign it to prevent forgery, this is very similar to how we usually handle user ID in HTTP cookies.

For bot ID, I need to double-check. But I think it is not sensitive so you should not need to hide it.

**Comment by Primtek** [comment]
@compulim 
Thanks for your reply!..
I am also looking for article how to implement server solution.. can you share it for me? and for the others that might need it..

thanks a lot in advance

**Comment by compulim** [comment]
You can find some of the token exchange/renewal code [here](https://github.com/compulim/BotFramework-Samples-Template/blob/master/packages/bot/src/index.js#L59). This repos is a Docker template we use to host both Bot.js and Web Chat on a single server.
