### ISSUE TITLE
Change webchat background to White

### ISSUE THREAD

**Issue by mareekuh** [Microsoft/BotFramework-WebChat#1124]
@compulim and @sgellock 

1. Please change the background of webchat windows to WHITE (Currently: gray).
2. Please also turn on a border for regular (typed) messages to light gray E6E6E6 which should be the same as all other borders. 

See attached. First image is desired. Second image is what's currently in build & visual spec (Jeremy's)
<img width="803" alt="screen shot 2018-08-30 at 9 46 22 am" src="https://user-images.githubusercontent.com/38053502/44866267-a075fb00-ac39-11e8-9c51-5798eac753c4.png">

**Comment by compulim** [comment]
Done.
