### ISSUE TITLE
Save chat history

### ISSUE THREAD

**Issue by Primtek** [Microsoft/BotFramework-WebChat#1134]
Hi,

is there any way to save chat history ?, so user close their browser incidentally, they just re-open their browser and the last chat history will shown..

need advise

thanks
Wil

**Comment by rosskyl** [comment]
You can do this with the directline. Essentially you need to save the conversation id and conversation token. If you are using events then you will also need the activity id. There is an example at #946.

**Comment by compulim** [comment]
Thanks @rosskyl.

Yea, in short, don't use the secret. Exchange Web Chat secret into a token first, and don't leak the secret to the client.

One more note (from ABS team):
- Within 24 hours of inactivity: activities will be sent back on connect
- 24h to 2 weeks: activities will not be sent back on connect
- 2 weeks+: conversation ID will be gone and cannot be reused
