### ISSUE TITLE
Speech recognition starts too fast 

### ISSUE THREAD

**Issue by erkkil** [Microsoft/BotFramework-WebChat#1138]
We have implemented webchat based chatbot solution which uses speech recognition and speech synthesis. 
The solution works fine except that if speech synthesis is playing relatively long text the speech recognition is switching on and listens the synthesis playback. 
It looks like that speech recognition starts automatically too early, it should wait untils syntesis is finished.
This problem does not happen with short syntehsis playback. 

How is it possible to have a longer waiting time before speech recognizer starts listening?

**Comment by Kartik1607** [comment]
Is the speech recognition event automatic? Or are you trigerring it by clicking mic button? 

Action to stop audio is sent when speech listen event is started. probably what is happening is speech recognition starts immediately while the event to stop audio takes a bit time. 

Instead of sending event to start recognition it should wait until audio has successfully stopped.

**Comment by erkkil** [comment]
Hi,

Recognition is triggered by clicking mic button. 
This is complete description.
1. Open Webchat with CognitiveServices speech recognition enabled
2. Click mic button 
3. Speak and mic recognition converts speak to text and sends the the text to bot app
4. Bot app replies with text reply 
5. The speech synthesis starts to speak the bot reply text
6. Before the synthesis finishes speaking the speech recognition activates the mic
7. Speech recognition recognities synthesis output and sends the recognized input to bot

So the speech reconizer should wait a bit longer before automatically stars listening.
We are using CognitiveServices.js for speech recognition and synthesis. 

I guess we need guidance how to modify/configure CognitiveService.js

**Comment by erkkil** [comment]
OK. Think I found the problem. Our bot is sending occasionally two separate answers. 
It seems that if there are more than one answer message the recognizer is activated too early. 

We will fix our bot to use one reply message in all situations.

**Comment by Kartik1607** [comment]
@erkkil the webchat auto listens when it finds that bot is awaiting reply. You can send multiple messages, just make sure that only last message awaits for user reply.
