### ISSUE TITLE
Herocards, and Thumbnails are VERY WIDE

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#114]
Herocards seem to be as wide as the widest single piece of text. Even on a wide screen I would expect a reasonable maximum width, but they just keep on going. I also expect that they would get narrower as I resize the browser down, but they don't.

Each card in a carousel is significantly wider than the widest single piece of text. They also do not get narrower as I resize the browser down, so I typically can't even see the ">" control without scrolling.

Thumbails aren't as bad, but they seem wider than necessary, and also do not get narrower as I resize the browser down.

Tested on Safari and Chrome on Mac.

**Comment by billba** [comment]
Okay now they are resizing down, which is much better. But they are still very large. This makes the hero and thumbnails merely ugly, but in the case of carousel it means you don't get to see many of the cards, and that means you have to do a lot of unnecessary scrolling.

**Comment by danmarshall** [comment]
Other than Carousel, most everything behaves well responsively even at very small sizes, like 100px wide. The Carousel is the bad player here, tracking this issue in #111

**Comment by billba** [comment]
Agreed on splitting off Carousel.

I agree the cards look fine at small sizes. I'm suggesting that we may want to have a maximum width, because they just look bad when wide.

**Comment by danmarshall** [comment]
I have a 320px max height for images, currently not setting a max width. I suppose it should be based on @media query breakpoints.

**Comment by billba** [comment]
I don't think the images are the culprit here. Look at "hero" in testbed. Little image, wide card.

**Comment by danmarshall** [comment]
@kevkor should we clamp down cards to a max-width like 640px or so?

**Comment by IanBoggs** [comment]
Sorry to ask, but is this still being looked at?
I'm still seeing the carousel being very wide and moving the user entered messages out of view to the right

**Comment by billba** [comment]
what do you mean about the user-entered messages? can you please post a screenshot and tell us which OS/browser?

this is on the list to fix but currently low priority

**Comment by IanBoggs** [comment]
Basically, this screen shot shows before the carousel is show to the user
![webchat1](https://cloud.githubusercontent.com/assets/18186052/20970161/1f2c480c-bc84-11e6-8357-2b068e37d674.png)

As you can see, the text entered by the user is shown in blue on the right hand side of the window. Then once the carousel is show this happens

![webchat2](https://cloud.githubusercontent.com/assets/18186052/20970162/1f4eebf0-bc84-11e6-8e50-15a143d24527.png)

The text entered by the users is now off the window to the right. I've had a look at the CSS in the borwser developer tools and it appears all the div tags starting 'wc-message' have had their width increased when the carousel is drawn. I'm not much of a CSS/javascript guy though so I'm having difficulty finding the issue

**Comment by billba** [comment]
Aha. Browser? OS?

**Comment by IanBoggs** [comment]
Client browser is Chrome (V54) and IE11  on Windows 7.
Also happens on Chrome and Safari on iPad
Web server is an Azure Web app and IISExpress (Visual Studio 2015 on Win7

The whole page is being hosted in an iframe

**Comment by danmarshall** [comment]
@IanBoggs is this from latest code? Can you pull from commit 2e867ef43b5b6c7c002d336448b3ef87058d95ca and see if this is a regression?

**Comment by IanBoggs** [comment]
Yes, it was from the latest code @danmarshall. I re-downloaded this morning.
I can pull from that commit tomorrow and check to see if it is a regression and will let you know

**Comment by IanBoggs** [comment]
I've pulled the 'public' folder from that commit and it appears to be doing the same thing. :-(

**Comment by danmarshall** [comment]
@IanBoggs can you share a sample of the cards to repro this?

**Comment by IanBoggs** [comment]
Sorry @danmarshall do you mean the Botframework code that is generating the cards ?

**Comment by danmarshall** [comment]
@IanBoggs anything to repro this bug. The JSON representation of your cards will suffice. Feel free to anonymize your data as long as it can repro the bug in the carousel.

**Comment by danmarshall** [comment]
@IanBoggs - actually it would be prefarable for you to open a new bug specifically for this, as this issue is tracking something separately. Thanks!

**Comment by IanBoggs** [comment]
@danmarshall sorry for the delay, I've raised a new issue for this, #230

**Comment by danmarshall** [comment]
@jecristi

**Comment by danmarshall** [comment]
@billba - can you add @jecristi (Jeremy) as a contributor?

**Comment by billba** [comment]
Much better now.
