### ISSUE TITLE
Pass logged in user details to the microsoft bot hosted in an application

### ISSUE THREAD

**Issue by JasmeetVirdi** [Microsoft/BotFramework-WebChat#1143]
My Webchat bot is hosted in an application in which the user is already logged in.I want to make a transaction for which the logged in user details are required but i dont want the user to log in again for the bot.So,how can i pass the logged in user information from the application to the bot.
I have searched alot for this and many articles are there but i am not able to find a clear solution.

**Comment by compulim** [comment]
In short, you will need to have the token on the bot side.

The right way to do it is thru OAuthCard. But I need to double-confirm if it is SSO or not. Using OAuthCard, you will get the access token that you can use on the server-side for many stuff.

Agree, although this path is supported, it's not clearly documented.

Let me know if you need some help on the code. You definitely use Web Chat with token exchange, i.e. you need to write your own web server to host Web Chat.

**Comment by JasmeetVirdi** [comment]
Thanx alot @compulim .Using OauthCard seems to be a good way.I will try that.
