### ISSUE TITLE
Speech is not working on Airwatch Mobile Browser

### ISSUE THREAD

**Issue by soso-maitha** [Microsoft/BotFramework-WebChat#1154]
Hello,

I managed to run Speech Recognition and Text to Speech successfully on the Bot WebChat using DirectLine. It works on Chrome Desktop. However, for mobile apps we are using Airwatch Mobile Browser, but unfortunately the mic icon is not appearing. I would like to ask if there is any solution or workaround to this problem or if Airwatch Mobile Browser is going to be one of the supported browsers with Bing Speech soon?

**Comment by compulim** [comment]
This is a limitation between Airwatch Mobile Browser and iOS.

iOS put a limitation on WebRTC or Web Speech API in third-party browsers. That means, on Chrome/Edge/Firefox on iOS, speech will not work. It will only works with Mobile Safari.

Not particular a limitation/bug on Web Chat side. It's an OS thing.
