### ISSUE TITLE
Store refresh token in a cookie

### ISSUE THREAD

**Issue by pedrosalider** [Microsoft/BotFramework-WebChat#1174]
Hello.

I am initializing the chat through a token obtained calling to DirectLine Api (POST/v3/directline/tokens/generate). I store this token in a cookie and use it to resume a conversation.
My problem is that the direct line automatically refreshes the token after 30 minutes and I didn't find a way to save the new token.
Does anyone know how I can save the new token?

Thanks in advance

**Comment by Kartik1607** [comment]
Hi, to resume a conversation you need to pass conversation id along with token and stream url. You can all these fields from conversation in a activity.
```
interface Conversation {
    conversationId: string,
    token: string,
    eTag?: string,
    streamUrl?: string,
    referenceGrammarId?: string
}
```

Once you generate a token by `POST/v3/directline/tokens/generate).` you **do not** need to save this. You only need to pass this token to [Directline JS library](https://github.com/Microsoft/BotFramework-DirectLineJS). The library will manage the refreshing of token.  What you do need to store is **conversation id** which you want to resume.

When you need to resume a conversation, you need to pass the **saved conversation id** along with a **newly generated token** and **stream url**

**Comment by Kartik1607** [comment]
Hi, to resume a conversation you need to pass conversation id along with token and stream url. 
To reconnect to a conversation you need to generate a new websocket url
```
GET https://directline.botframework.com/v3/directline/conversations/{conversationId}?watermark={watermark_value}
Authorization: Bearer SECRET_OR_TOKEN
```
 Then you can pass this token to [Directline JS library](https://github.com/Microsoft/BotFramework-DirectLineJS). The library will manage the refreshing of token.

```
const dl = new DirectLine({
    token: /* the token you retrieved while reconnecting */,
    streamUrl: /* the streamUrl you retrieved while reconnecting */,
    conversationId: /* the conversationid you stored from previous conversation */
});
```

**Comment by compulim** [comment]
According to [this line of code](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L305) in DirectLineJS, the `token` property is private and you may not able to retrieve it.

You can hack DLJS to make it public so you can steal it but it is unsupported. We are working on preserve history functionality and will revisit resume conversation story in DLJS soon.

I will leave this issue open until we have a good story on it.

**Comment by compulim** [comment]
Since this issue is related to DirectLineJS than Web Chat, I am closing this issue for now.

I created a new issue on DirectLineJS repository to track this issue.
