### ISSUE TITLE
Text to Speech not working

### ISSUE THREAD

**Issue by Toemsel** [Microsoft/BotFramework-WebChat#1179]
Web App Bot v3 doesn't speek out loud the text it is supposed to do.
Language German DE/AT on windows 10 installed. (Including the speech packages)
Tried on Edge and Chrome.

     <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>

    
    <script src="https://cdn.botframework.com/botframework-webchat/latest/CognitiveServices.js"></script>

      const speechOptions = {
        speechRecognizer: new CognitiveServices.SpeechRecognizer({ subscriptionKey: 'XXX', locale: 'de-DE' }),
        speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
          gender: CognitiveServices.SynthesisGender.Male,
          subscriptionKey: 'XXX',
          voiceName: 'Microsoft Server Speech Text to Speech Voice (de-DE, Stefan, Apollo)'
        })
      };`

      BotChat.App({
        bot: bot,
        locale: 'de-DE',
        resize: 'detect',
        // sendTyping: true,    // defaults to false. set to true to send 'typing' activities to bot (and other users) when user is typing
        speechOptions: speechOptions,
        user: user,

        directLine: {
          domain: params['domain'],
          secret: 'xxx',
          token: params['t'],
          webSocket: params['webSocket'] && params['webSocket'] === 'true' // defaults to true
        }
      }, document.getElementById('BotChatGoesHere'));

EDIT: I realized (by accident) that it ONLY works if I use the bot with Speech to text. (Voice input) With normal text input, it doesnt work...

**Comment by Kartik1607** [comment]
The bot only starts speaking if **lastInputViaSpeech** is true . It is **false** by default. You need to click microphone to send message to bot via speech to enable text to speech. Instead, if you want the bot to always speak you would have to update [this line](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Store.ts#L603) to true always.

**Comment by Toemsel** [comment]
How am I able to set this value? I use the DirectLine while including

    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/CognitiveServices.js"></script>

Couldn't find a reference in both scripts to this file.

**Comment by Toemsel** [comment]
Ok, I modified the **lastInputViaSpeech** value in the .js. Thanks for your help
