### ISSUE TITLE
How do I pass parameters to the Bot API using V4?

### ISSUE THREAD

**Issue by fberasategui** [Microsoft/BotFramework-WebChat#1180]
So, I'm currently using this:

```html
<!DOCTYPE html>
<html>
  <body>
    <div id="webchat"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/preview/botchat.js"></script>
    <script>
      window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ secret: 'YOUR_BOT_SECRET_FROM_AZURE_PORTAL' })
      }, document.getElementById('webchat'));
    </script>
  </body>
</html>
```

and it works fine, however I have multiple (user defined) bot and QnA configurations and I would like to pass a single string parameter which can be accessed by my code based on the Bot Framework API.

Is there any way to do that?

**Comment by compulim** [comment]
The easiest and supported way, use need multiple bot registrations and bot endpoints. You can still host bot on the single server with different routing.

Another way, shortly after starting a conversation, send an event to the bot to tell the bot what settings to load (a.k.a. "pseudo bot ID"). You keep this "pseudo bot ID" in bot state, so your bot code know what settings to load on every request. Remember, bot is stateless.

But this approach is experimental and may not work in all scenarios.

**Comment by fberasategui** [comment]
@compulim the problem is that it needs to be dynamic. Meaning people can register into our platform and configure their own bot, which means I'd have to create bot registrations dynamically on Azure. I don't know if that's possible.

As for the other approach, how do I send an event to the bot? you mean client side?
