### ISSUE TITLE
Bot answer with iframe

### ISSUE THREAD

**Issue by aaeeP** [Microsoft/BotFramework-WebChat#1181]
Hi, I would like to have a bot that can embeed content from other websites in the answers using iframes. Does anyone know if this is possible? I have done as is said in this post: https://blog.botframework.com/2017/09/07/html-not-supported-web-chat/ but I still can't use iframes. Anyone has done it or has a clue of how to do it? 

Any help is very appreciated. 

Thank you!

**Comment by sgellock** [comment]
@compulim can you provide a sample?

**Comment by compulim** [comment]
You can look at this sample to how to do it. In short, you can send a custom attachment and you can render it using `<IFRAME>`.

https://github.com/Microsoft/BotFramework-WebChat/blob/preview/samples/custom-attachment-github-repository/index.html
