### ISSUE TITLE
Sum up multiple messages

### ISSUE THREAD

**Issue by skandyrocks** [Microsoft/BotFramework-WebChat#1187]
we recognized that our customers often send more than one message to describe their intent.
So our idea was to sum up some message until the customer stops typing for about 3 seconds or so. We used the postActivity-Middleware to achieve this. So we are caching all messages that the customer sends and we want to send them in one message after he stopped typing. We recognized that we cannot post activities manually, but we cannot figure out why.

Here's our middleware code:
```
botConnection = new BotChat.DirectLine({
    secret: secret,
    conversationId: conversationId,
    webSocket: false
});

BotChat.App({
    botConnection: {
        ...botConnection,
        postActivity: activity => {
            if (activity.type === "message") {
                lastActivity = activity;
                text += text.length > 0 ? " " + activity.text : activity.text;
            }
            else {
                return botConnection.postActivity(activity);
            }
        }
    },
    user: { id: uuid, name: userName },
    bot: { id: 'webservicebottest' },
    resize: 'detect',
    locale: userLocale,
    sendTyping: true,
}, document.getElementById("bot"));
```

here is the code to send our accumulated messages:
```
setTimeout(sendActivitiesFromUser, 500);
$(".wc-shellinput").keydown(function(){
      lastTypingTimestamp = Date.now();
});

function sendActivitiesFromUser() {
    if (lastTypingTimestamp !== undefined && Date.now() - 3000 > lastTypingTimestamp && text !== undefined && text.length > 0) {
        lastActivity.text = text;
        botConnection.postActivity(lastActivity);
        text = "";
        lastActivity = undefined;
        lastTypingTimestamp = undefined
    }

    setTimeout(sendActivitiesFromUser, 500);
}
```

why can't we send the `lastActivity`? It seems that directline doesn't post the activity to the directline server.

directline executes the `postActivity` function but stops after the command `this.checkConnection(true)` and doesn't execute the flatMap command and so on

**Comment by sgellock** [comment]
The team has discussed and we are planning on adding multi-line support to help address this and related use cases
