### ISSUE TITLE
 Random positioning of the proactive message

### ISSUE THREAD

**Issue by Al-mck** [Microsoft/BotFramework-WebChat#1195]
Hello,

I am developing a chatbot. I want to integrate a welcome message so that the bot initiates the conversation but this message sometimes appears at the top of the chat :

![image](https://user-images.githubusercontent.com/16591957/46585011-38ea7100-ca6b-11e8-9c2c-c2c479b52bf4.png)
and sometimes at the bottom :
![bug](https://user-images.githubusercontent.com/16591957/46585120-e3af5f00-ca6c-11e8-8e17-9c7ee0d719c2.PNG)

When I send a message on the chat, automatically the greeting is positioned at the bottom. Have you ever seen this?

Thanks you for your help

**Comment by compulim** [comment]
We didn't observe this behavior. Which browsers are you using? For the padded space, can you inspect the DOM tree and see what is causing it?

**Comment by Al-mck** [comment]
Hello,

My bad, it happens that way because i call the client code without having created the display div.
Thanks you for you very nice work 👍
