### ISSUE TITLE
Virtual Assistant Web Chat Experience

### ISSUE THREAD

**Issue by darrenj** [Microsoft/BotFramework-WebChat#1207]
## Virtual Assistant Web Chat Experience 

Key features for the basic web-chat experience are below. 

- [ ]  Ability to "sign-in" using the built in website/ad signin capabilities (see linked accounts in the GitHub repo for an example. The UserId retrieved as part of this is set on the webChat. Example already done [here](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest/Assistant-WebTest)
- [ ]  Speech wired up (and ability to control voice-font-name/language in UX surfaced config setting
- [ ]  Ability to control the directLinesecret through same UX surfaced config setting (e.g. flyout pane)
- [ ]  Ability to control the locale through a UX surfaced setting somewhere (e.g. zh-cn) which is then set on the webchat and attached to all messages. This enables easy switching between languages.
- [ ]  Standard webchat control
- [ ]  Text boxes for lat/long which are populated based on in-built browser capabilities for location. Editable by the user. Button then sends an event via webchat (IPA.TimeZone) with a value of lat/long. See [here](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-events.md)
- [ ]  Dropdown list for Timezone which like above has a button which sends an event as per [here](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/docs/virtualassistant-events.md). Valid values can be found [here](https://stackoverflow.com/questions/7908343/list-of-timezone-ids-for-use-with-findtimezonebyid-in-c)
- [ ]  Button to restart webchat and create a new conversation (like in the emulator).
- [ ]  A panel to the side of the webchat which has the ability for us to show Navigation Destination, Temperature, Fan Setting
- [ ]  Slider for settings like cruise control allowing interactive control and sending of events
- [ ]  Code to "sink" events that come back from the Virtual Assistant and then in the case of navigation destination update the pane on the right when received, music playing, light-up park assist/traction control turned off
- [ ]  Debug Pane/window (which can be hidden) which shows what events have been received/sent
- [ ]  CI integration into GitHub.microsoft.com/ai
- [ ]  Documentation for how customers can take the code and deploy into their own environment
- [ ]  Resolve [259](https://github.com/Microsoft/AI/issues/259)

Repo is here: https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/testharnesses/assistant-WebTest

**Comment by ryanlengel** [comment]
For timezones, maybe a dropdown of all valid names that .NET accepts would be best.
https://stackoverflow.com/questions/7908343/list-of-timezone-ids-for-use-with-findtimezonebyid-in-c

**Comment by compulim** [comment]
I have split them up into multiple issues, please track them here:

https://github.com/Microsoft/BotFramework-WebChat/issues?q=is%3Aopen+is%3Aissue+label%3A%22Virtual+Assistant%22
