### ISSUE TITLE
Switch from Bing Speech API to Speech Services in Web Chat

### ISSUE THREAD

**Issue by thejasondt** [Microsoft/BotFramework-WebChat#1217]
I am using the following code in the webchat:

```
const speechOptions = {
    speechRecognizer: new CognitiveServices.SpeechRecognizer({ subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY' }),
    speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
      gender: CognitiveServices.SynthesisGender.Female,
      subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY',
      voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
    })
  };
```

from:

https://docs.microsoft.com/en-gb/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0

However, I have been told to switch from Bing Speech API to Speech Services API.

I am unsure where I can find documentation on how to do so in my bot service webchat.

I have tried using my new Speech Services API Key but it doesn't work.

Is there documentation on how to do so with the new API?

**Comment by compulim** [comment]
It's on roadmap, but it might not hit Web Chat v3. Speech Services team just GA and release their SDK on 9/24 and we are busy GA-ing Web Chat v4.

The missing piece: convert Speech Services SDK into W3C Web Speech API ponyfill, then consume it in Web Chat (targeting v4). Web Chat v4 support anything that is compliant to the W3C standard.

Since Web Chat v3 also support W3C Web Speech API, the ponyfill might just works in v3 too. But until the missing piece is done, I can't surely tell how it works in v3.

**Comment by thejasondt** [comment]
OK, will stick with Bing Speech API for now

**Comment by UsamaAslam** [comment]
I'm creating a bot which accept text and voice input and also can answer in both mode. The bot works really good but i have to click always the button of microphone to speak with the bot. Do you know it is possible to make microphone always on and to recognize the voice without clicking the button of microphone ?

@compulim @sgellock

**Comment by deva96** [comment]
Hey i cant even create a bing speech api service now ?

**Comment by stevkan** [comment]
@UsamaAslam, the 'always on' microphone feature is being reviewed. There is no ETA at this time. You can review the current discussion in issue [#859](https://github.com/Microsoft/BotFramework-WebChat/issues/859). Hopefully this answers some of your questions.

**Comment by corinagum** [comment]
This is being tracked over at #1336

**Comment by compulim** [comment]
@UsamaAslam we created a new issue #1401 for the "always-on microphone".

**Comment by saurav2107** [comment]
Hi Team,
Is there any update on using Speech Services in Web Chat v3, can you please point me to the solution.

**Comment by TestUsetGitHubUser** [comment]
@compulim is speech service now supported on Web Chat(directline) v4(or v3) using client side, if yes can we have any sample?

Thanks,

**Comment by soso-maitha** [comment]
> I am using the following code in the webchat:
> 
> ```
> const speechOptions = {
>     speechRecognizer: new CognitiveServices.SpeechRecognizer({ subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY' }),
>     speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
>       gender: CognitiveServices.SynthesisGender.Female,
>       subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY',
>       voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
>     })
>   };
> ```
> from:
> 
> https://docs.microsoft.com/en-gb/azure/bot-service/bot-service-channel-connect-webchat-speech?view=azure-bot-service-3.0
> 
> However, I have been told to switch from Bing Speech API to Speech Services API.
> 
> I am unsure where I can find documentation on how to do so in my bot service webchat.
> 
> I have tried using my new Speech Services API Key but it doesn't work.
> 
> Is there documentation on how to do so with the new API?

so is there any documentation for the steps to migrate from Bing Speech to new Speech Service? We have the same case and speech stopped working. 
We are using same javascript code, I created a new Speech Service and changed the keys but still not working.

Kindly advise as i need it importantly.

regards,

**Comment by corinagum** [comment]
@TestUsetGitHubUser, @soso-maitha, please take a look at our speech samples for Cognitive Services Speech Services implementation of Web Chat.
