### ISSUE TITLE
DirectLine token is getting expired and I'm not able to generate a new one(using websocket)

### ISSUE THREAD

**Issue by prajwalsimha94** [Microsoft/BotFramework-WebChat#1223]
I'm using BotFramework DirectLine websocket to post and receive messages with the bot. While it works fine, the directline token expires in about half hour, forcing my app to generate a new token. I'm using the following code to subscribe to "Token Expired" event:

```
directline.connectionStatus$
.subscribe(function(connectionStatus)) {
  switch(connectionStatus){
    case BotChat.ConnectionStatus.Uninitialized:
      //some code
      break;
    case BotChat.ConnectionStatus.Connecting:
      //some code
      break;
    case BotChat.ConnectionStatus.Online:
      //some code
      break;
   case BotChat.ConnectionStatus.ExpiredToken:
      // generate a new token and reconnect to the conversation
      break;
  }
}

```
The problem is, case "BotChat.ConnectionStatus.ExpiredToken" is not getting triggered even if the token is expired. But while using the POLLING approach the expired token event gets triggered.

Browser console throws error 403 forbidden when I try to post an activity after the token is expired. Any help would be appreciated. Thanks!

**Comment by sgellock** [comment]
This issue was moved to Microsoft/BotFramework-DirectLineJS#101
