### ISSUE TITLE
React component: "TypeError: Object doesn't support property or method 'map'"

### ISSUE THREAD

**Issue by alexdalecki** [microsoft/BotFramework-WebChat#1229]
I've created an app with create-react-app and included the Chat component. When I start the application, I get the following error:

```
TypeError: Object doesn't support property or method 'map'

updateSelectedActivityEpic
C:/Users/alexd/Sites/bot-site-2/node_modules/botframework-webchat/built/Store.js:664
  661 | };
  662 | 
  663 | var updateSelectedActivityEpic = function updateSelectedActivityEpic(action$, store) {
> 664 |   return action$.ofType('Send_Message_Succeed', 'Send_Message_Fail', 'Show_Typing', 'Clear_Typing').map(function (action) {
  665 |     var state = store.getState();
  666 | 
  667 |     if (state.connection.selectedActivity) {
```

**Comment by Kartik1607** [comment]
Can you please share some code and let us know how you are trying to integrate the component?

**Comment by alexdalecki** [comment]
Of course.

I just created a new CRA app, installed the botframework-webchat package and its peer dependencies, and edited App.js:

```
import React, { Component } from 'react';
import { Chat } from 'botframework-webchat';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <Chat directLine={{ secret: 'MY_SECRET' }} />
        </header>
      </div>
    );
  }
}

export default App;
```

MY_SECRET is of course just the placeholder for my real direct line secret.

Am I missing something or doing something wrong?

**Comment by sgellock** [comment]
this is a dup.  please refer to https://github.com/Microsoft/BotFramework-WebChat/issues/1229 for a workaround

**Comment by AntonLydike** [comment]
> this is a dup. please refer to #1229 for a workaround

But... **This** is issue #1229

Where's the workaround?

**Comment by sgellock** [comment]
@AntonLydike sorry Anton, it looks like I was closing this issue when I should have closed a different one.  @compulim can you help?

**Comment by AntonLydike** [comment]
Yeah, no worries mate. I just ran across this issue and was a little bit confused when I looked at this. For me, this happened because I missed a type check and called `.map` on a promise, so yeah. If anyone else comes across this, check yo types!

**Comment by sgellock** [comment]
@AntonLydike got it.  ok.  sounds like you're in good shape.  I'll close this issue then, sound ok?
