### ISSUE TITLE
Issue with custom events, using backchannel 

### ISSUE THREAD

**Issue by saurav2107** [Microsoft/BotFramework-WebChat#1240]
To open a Feedback survey, after an user is ideal for x minutes, I want to open up a feedback survey dialog.
I keep track of time on client side (html), and once x min is passed, I fire a custom event, using below code (which works fine)

`botConnection
                .postActivity({
                    from: 'me',
                    name: 'displayFeedbackDialog',
                    type: 'event',
                    value: ''
                })
                .subscribe(function (id) {
                    isFeedbackSent = true;
                });`

from by bot MessageController I read the event and open a feedback dialog, which has a choice prompt (which works fine)
**MessageController** 
`if (activity.GetActivityType() == ActivityTypes.Event)
                {
                    ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                    var eventActivity = activity.AsEventActivity();
                    if (string.Equals(eventActivity.Name, "displayFeedbackDialog", StringComparison.InvariantCultureIgnoreCase))
                    {
                        using (DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                        {
                            await Conversation.SendAsync(activity, () => new ExceptionHandlerDialog<object>(new FeedbackDialog(activity.Locale)), CancellationToken.None);
                        }
                    }
                }`

**Feedback Dialog**

` public Task StartAsync(IDialogContext context)
        {
            context.Wait(this.MessageReceivedAsync);
            return Task.CompletedTask;
        }
        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            this.FeedbackQuestionText = ConfigurationManager.AppSettings["FeedbackQuestionText"];
            var PromptOptions = new List<string>() { MicrosoftTranslator.Translate("Yes", this.Locale), MicrosoftTranslator.Translate("No", this.Locale) };
            PromptDialog.Choice(context, FeedbackPromptResponse, PromptOptions, MicrosoftTranslator.Translate(this.FeedbackQuestionText, this.Locale), promptStyle: PromptStyle.Auto);
        }
        private async Task FeedbackPromptResponse(IDialogContext context, IAwaitable<string> result)
        {
            this.FeedbackRespnseText = ConfigurationManager.AppSettings["FeedbackResponseText"];
            var Prompt = await result;
            string PromptString = Prompt.ToString().ToLower().Trim();
            if (PromptString.Length > 0)
            {
                if (MicrosoftTranslator.Translate(PromptString, this.Locale) == MicrosoftTranslator.Translate("yes", this.Locale))
                {
                    var properties = new Dictionary<string, string>
                    {
                        {"UserVote", "Yes" }
                    };
                    Log.Info(context, "BVBOT-UserFeedback", properties);
                }
                else
                {
                    // post feedback to App Insights
                    var properties = new Dictionary<string, string>
                    {
                        {"UserVote", "No" }
                    };
                    Log.Info(context, "BVBOT-UserFeedback", properties);

                }
                await context.PostAsync(MicrosoftTranslator.Translate(this.FeedbackRespnseText, this.Locale));
                context.Done<IMessageActivity>(null);
            }
            else
            {
                context.Done(true);
            }
        }`

But when i click on the choice button, the dialog loses context and goes to root dialog, as the activity type is message this time, and i get a response as sorry i am unable to understand.
Please help

**Comment by compulim** [comment]
@saurav2107 looks like you are asking questions about BotBuilder SDK (C#), instead of Web Chat.

Please file a bug to [`botbuilder-dotnet`](https://github.com/Microsoft/botbuilder-dotnet/issues/) repository. There are support people on that repository targeting SDK related questions.
