### ISSUE TITLE
Move rich card from Adaptive Cards to native HTML

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#1259]
# Background

We use Adaptive Cards to simplify composition of rich card. There are number of reasons we would like to move away from Adaptive Cards:

- Cosmetics
   - Adaptive Cards cannot be styled to remove pictures padding
- Users on minimal build will be able to use rich card
   - Minimal build does not contains Adaptive Cards, so they cannot use rich card too
- We have limited number of rich cards

# Note to fixer

- [ ] Animation card
- [ ] Audio card
- [ ] Hero card
- [ ] OAuth card (variation of sign-in card)
- [ ] Receipt card
- [ ] Sign-in card
- [ ] Thumbnail card
- [ ] Video card

**Comment by compulim** [comment]
Moved from P1 to P2 because without this feature, everything still works fine.

**Comment by compulim** [comment]
@corinagum should we reconsider this into 4.6 or 4.7 when Marc is redesigning our UI?

**Comment by corinagum** [comment]
@compulim Yeah, let's bring this up at our 4.6 planning meeting this week.
