### ISSUE TITLE
React warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#126]
Check the render method of `FormattedText`

**Comment by billba** [comment]
Not sure why this only started showing up when we bundled React, but there it is. Pretty sure this is your Markdown stuff.

**Comment by eanders-MS** [comment]
Ok, looks like I just need to assign keys to the sibling elements.

**Comment by earlyster** [comment]
Also noticing this for Carousel as well

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Carousel`. See https://fb.me/react-warning-keys for more information.
```

**Comment by billba** [comment]
Thanks @earlyster, I've been meaning to post those errors to this issue. I believe I have now fixed all of these except for FormattedText, which I simply don't understand well enough to fix. So it's back in @eanders-MS' court.

**Comment by eanders-MS** [comment]
@billba I will address this today.

**Comment by billba** [comment]
We are now free of this class of React warnings!
