### ISSUE TITLE
Bug: change the attachment icon from picture to a clip

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1264]
If it show a photo icon, the user should not be able to upload non-photo attachment, e.g. ZIP files.

![image](https://user-images.githubusercontent.com/1622400/47759174-97ba9900-dc6b-11e8-8dcd-926a20a58add.png)

## Comparison to v3

![image](https://user-images.githubusercontent.com/1622400/47759331-54acf580-dc6c-11e8-9ed0-b9edd30e3314.png)

**Comment by compulim** [comment]
v3 also use the same icon, for both photo and non-photo.

**Comment by corinagum** [comment]
@mewa1024 Not sure if this is a you or Marc request, he said he would touch base with you!

**Comment by DesignPolice** [comment]
ping

**Comment by mewa1024** [comment]
@DesignPolice paper clips seems fine to me. Looks like some messenging apps breakout all the files types, but that probably won't scale for Webchat.
