### ISSUE TITLE
Autoscroll does not handle very long messages

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#127]
1. make a skinny window
2. call testbot's "markdown" command 
3. chat is not scrolled to bottom of message

**Comment by billba** [comment]
This is because of the images in the markdown. We should be passing down onImageLoad as in AttachmentView so that we can autoscroll when each image finishes loading. I view this as a low priority bug.

**Comment by eanders-MS** [comment]
Agreed on the priority. I will get to it sometime soon.
