### ISSUE TITLE
Chat window showing empty message bubble on load

### ISSUE THREAD

**Issue by alexknipfer** [Microsoft/BotFramework-WebChat#1275]
Anybody ever had any issues of seeing an empty chat bubble when the chat first loads up (see screenshot below)? It goes away after ~1 sec or so then loads up our bot welcome message. However, if I clear cache and hard reload, this empty bubbly just stays there and the connection with the bot never seems to establish. Please let me know if there are any more details I can provide and if you have any suggestions as to why this may be happening.

Here is the behavior I am seeing:
<img width="512" alt="screen shot 2018-10-31 at 12 54 41 pm" src="https://user-images.githubusercontent.com/1299646/47808707-f3892e80-dd0c-11e8-81c5-4eaa947ccdf1.png">

**Comment by compulim** [comment]
@corinagum can you look at this one when you are working on #1103? Maybe they are dupe.

**Comment by compulim** [comment]
@alexknipfer do you know if the bot is sending any activities on first load? If you are on Chrome, you can go to Dev Tools > Network tab, there might be some activities information there.

**Comment by alexknipfer** [comment]
@compulim I apologize for not reporting back, I thought this was an issue related to the botframework code, but it was an issue on my end. I have resolved the issue and this can be closed, I don't believe this is related to #1103.

**Comment by corinagum** [comment]
@alexknipfer awesome! Glad you figured it out. Closing this issue, but you can always file a new one if a different problem arises. Happy bot-ing!

**Comment by alexknipfer** [comment]
@corinagum Great, thank you for your support!

**Comment by Nasreen094** [comment]
> @compulim I apologize for not reporting back, I thought this was an issue related to the botframework code, but it was an issue on my end. I have resolved the issue and this can be closed, I don't believe this is related to #1103.

@alexknipfer  I am currently facing this issue and couldn't find a way to resolve it. Could you please tell me how you fixed this issue from your side?
