### ISSUE TITLE
uncaught referenceerror botchat is not defined

### ISSUE THREAD

**Issue by Ryu0514** [Microsoft/BotFramework-WebChat#1282]
after v4.1.0 relaeased, my code return 
"uncaught referenceerror botchat is not defined".
I'm sure I've not made any change on my code.

Could you confirm which version is released on latest cdn?

previously, I use 
`<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js"></script>`

About 3 hours ago, it went wrong; cant initialize chat window with the error below.
"uncaught referenceerror botchat is not defined"

When I change the code to below, it got well.
`<script src="https://cdn.botframework.com/botframework-webchat/0.14.1/botchat-es5.js"></script>`

**Comment by compulim** [comment]
#1281, #1282, and #1283 are the same issue. We are aware of the issue and is fixed.

Please read the explanation at #1281 for details. Closing this due to dupe.
