### ISSUE TITLE
BotChat not defined error

### ISSUE THREAD

**Issue by maqankitat** [Microsoft/BotFramework-WebChat#1283]
Last checked : 12 hrs ago
It worked fine, now my code returned 
"uncaught referenceerror botchat is not defined"
I have not made any code changes
I tried: 
<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js"></script>
<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
Still it did not work

**Comment by Ryu0514** [comment]
seems relate to this, could you confirm it?
#1282

**Comment by compulim** [comment]
#1281, #1282, and #1283 are the same issue. We are aware of the issue and is fixed.

Please read the explanation at #1281 for details. Closing this due to dupe.
