### ISSUE TITLE
Sample: Text remaining 

### ISSUE THREAD

**Issue by parag-nikhal** [microsoft/BotFramework-WebChat#1289]
Wanted to show text remaining counter then user types anything in textbox. e.g. max text is 100 char is limit so if user type "hi" then text remaining should show 98 char

**Comment by rdosanjh** [comment]
I would like to take this if it's still relevent

**Comment by corinagum** [comment]
@rdosanjh sorry for the late reply! Please by all means implement a sample and share with the community. :) thank you!

**Comment by cwhitten** [comment]
Hello, we'll close this as we have no plans to implement and provide this sample.
