### ISSUE TITLE
Sample: Create a simple HTML/JS Sample to send a string via backchannel

### ISSUE THREAD

**Issue by 20112077** [Microsoft/BotFramework-WebChat#1298]

**Comment by compulim** [comment]
Before we implement the sample, you can look at this line to programmatically send an activity using JavaScript.

https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/09.customization-reaction-buttons/index.html#L69

**Comment by compulim** [comment]
@20112077 this is done. You can look at sample [15.c.programmatic-post-activity](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.c.programmatic-post-activity) for details.
