### ISSUE TITLE
Master branch does not compile

### ISSUE THREAD

**Issue by d0ggyRul3z** [Microsoft/BotFramework-WebChat#1300]
## Branch
**Master** latest commit - #1290

## Describe the bug
Master branch giving error during compile time

## To Reproduce
1. Get https://github.com/Microsoft/BotFramework-WebChat
2. Build solution but do not run "npm install". Note: see https://github.com/Microsoft/BotFramework-WebChat/issues/1299
3. Build errors at packages/component/src/Utils/AdapterCardBuilder.ts line 69

![image](https://user-images.githubusercontent.com/6459010/47947480-48c57a00-df71-11e8-873f-a4ffedab104e.png)

## Expected behavior
Solution builds when running "npm run build"

[bug]

**Comment by d0ggyRul3z** [comment]
@compulim

**Comment by compulim** [comment]
Can you try these steps after fresh clone?

```
npm install
npm run bootstrap
npm run build
```

If you need bundle (`*.js`), then you need few additional steps

```
cd packages/bundle
npm run prepublishOnly
```

If it doesn't work, can you send me a longer log?

**Comment by d0ggyRul3z** [comment]
hey @compulim , i tried the instructions as prescribed.

here are my steps
1. Git pull from Master branch into a new directory
2. ran "npm install" - ran to completion with 1 warning
3. ran "npm run bootstrap" - failed see below

![image](https://user-images.githubusercontent.com/6459010/47951724-bcd74080-dfb8-11e8-9bea-a50ec73593f4.png)

Hope this helps.

Kind regards
Zac

**Comment by d0ggyRul3z** [comment]
hey @compulim ,

As it turns out, a cold restart of my machine did the trick and the instructions that you prescribed worked a treat.

Kind regards
Zac

**Comment by compulim** [comment]
Thanks for your feedback. I have updated the [README.doc](https://github.com/Microsoft/BotFramework-WebChat/blob/master/README.md#building-the-project) in #1301 to include build steps.

**Comment by d0ggyRul3z** [comment]
hey @compulim , always happy to contribute.
Thanks for updating the documentations.
