### ISSUE TITLE
[Usable] Focus lands on "Upload File" button twice while navigating in scan mode.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1308]
**Actual Result:**
Focus lands on "Upload File" button twice while navigate in scan mode.

**Note** - Behavior is same with NVDA screen reader.

**Expected Result:**
Focus should not lands on "Upload File" button twice while navigate in scan mode.

**Repro Steps:**

 1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle](https://microsoft.github.io/BotFramework-WebChat/full-bundle ) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Open Narrator with Scan mode (Caps+Space).
4. Navigate to 'Upload File' button by using Up/Down arrow keys.
5. Observe that focus lands on "Upload File" button twice in scan mode.

**User Impact:**
Users who rely on screen readers may get confused and face difficulty if navigation is not correct or logical for the controls.

**Test Environment:**
**OS**: Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge
**Tool:** Narrator

**Attachment:**
[Usable_Focus lands 2 times in scan mode.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2547214/Usable_Focus.lands.2.times.in.scan.mode.zip)

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yUsable
