### ISSUE TITLE
Scroll selected message into view

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#131]
If we programmatically select a message, as from the Emulator, it would be nice to scroll the message into view.  Will be interesting to get the nuances of this right, as we don't distinguish between user selection and programmatic selection.

**Comment by danmarshall** [comment]
Good idea - perhaps autoscroll might use the same mechanism? I say this because I will also need something similar when animating the height of new messages.

**Comment by corinagum** [comment]
Related to and trackable on #1403
