### ISSUE TITLE
[Usable] Does not get the notification about 'Full screen to Exit full screen' action on video clip.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1310]
**Actual Result:**
Narrator does not provide information about 'Full screen to Exit full screen' action on video clip, Narrator is silent when select full screen button and exit full screen button.
Does not get the notification about 'Full screen to Exit full screen' action on video clip.

**Expected Result:**
Should get the notification about 'Full screen to Exit full screen' action on video clip.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Type 'accessibility' in the input control at the bottom of the screen and hit enter (or click on send button).
4. Page will upload, Navigate to Full Screen button on Video clip by using Tab key.
5. Open Narrator (Ctrl+Win.Key+Enter)
6. Observe that after perform the action 'Full screen to Exit full screen or visa versa', narrator not provide any information.

**User Impact:**
Users dependent on screen readers require all changes of the screen, otherwise user will not get the changes on screen.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge
**Tool:** Narrator

**Attachment:**
[Usable_Notification about the action.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2602953/Usable_Notification.about.the.action.zip)

**Comment by corinagum** [comment]
Confirmed as external by accessibility team

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yUsable
