### ISSUE TITLE
[Usable]Reading whole message in one go while navigate in the scan mode.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1317]
**Actual Result:**
Narrator is reading all information(which appears after hit the hi input) in one go while navigate in the scan mode.

**Note** - Same issue repro at - 
1. URL -> Help -> Show a reminder using Adaptive cards button -> New Content -> Showing Reminder Text - Narrator is reading whole information in one go while navigate in scan mode. Attachment **"Usable_reading whole message in one go".**
2. Help Message ->Show Bing Sports using Adaptive cards button ->New uploaded data ->7 - 40 data - Name is not reading in proper way when navigate in scan mode. Attachment **"Usable_7-40".**
3. Help Message ->Show Bing Sports using Adaptive cards button ->New uploaded data - Not reading data in proper way when navigate in scan mode. Attachment **"Usable_Reading continue".**
4. Help Message ->Show Flight Update using  Adaptive card button ->New uploaded data ->Flight Status Text -Not reading data in proper way when navigate in scan mode. Attachment **"Usable_Not reading properly".**
5. URL -> Help -> Show Restaurant information using  Adaptive card button -> New Content -> Showing restaurant Text - Narrator is reading whole information in one go while navigate in scan mode.(This issue repro at -Show Markdown using Adaptive cards button/Show a rich message using Adaptive cards button/Show breakfast review using  Adaptive card /Show Flight Track using  Adaptive card buttons)

**Expected Result:**
Narrator should not read the whole information in one go while navigate in the scan mode.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle](https://microsoft.github.io/BotFramework-WebChat/full-bundle ) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Type 'hi' in the input control at the bottom of the screen and hit enter (or click on the send button) 
4. New messages will appear on the screen.
5. Open Narrator with scan mode (Space + Caps).
6. Navigate to the message "Unknown command:Hi..." by using Down arrow key.
7. Observe that narrator is reading whole message in one go.

**User Impact:**
If narrator reads all control in one go then the user ,who is dependent on screen reader, will get confuse about the purpose of the controls.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge

**Attachment:**
1. [Usable_Message reading in One go.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2548326/Usable_Message.reading.in.One.go.zip)
2. [Usable_reading whole message in one go.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2571711/Usable_reading.whole.message.in.one.go.zip)
3. [Usable_7-40.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2571941/Usable_7-40.zip)
4. [Usable_Reading contunue.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2574815/Usable_Reading.contunue.zip)

**Comment by priysn** [comment]
Closing this bug as part of internal bugs review.

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yUsable

**Comment by pgopinadhu** [comment]
#A11yUsable;#A11ySev4;
