### ISSUE TITLE
Screen reader is not providing any information about 'Sent' message.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1318]
**Actual Result:**
After sending the "hi" message narrator is silent, not reading anything when message is in Sending state.
Narrator is not providing any information about the sent message.

**Note:** Same issue repro at -
Upload File button - After Uploading Image narrator not give information that Image has been uploaded. 
Attachment -"Usable_Image uploading Information".

**Expected Result:**
Narrator should provide the information about the sent message.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle](https://microsoft.github.io/BotFramework-WebChat/full-bundle ) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Open Narrator (Caps+Win. Key+Enter)
4. Type 'hi' in the input control at the bottom of the screen and hit enter (or click on the send button) .
5. Observe that Narrator not is not providing any information about 'Sent' message.
    
**User Impact:**
Users depending on screen reader might get confused as screen reader is not providing information about the action.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge
**Tool:** Narrator

**Attachment:**
1. [Usable_Messgae sending state.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2548363/MAS1.3.1_Messgae.sending.state.zip)
2. [Usable_Image uploading Information.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2604000/Usable_Image.uploading.Information.zip)

**Comment by compulim** [comment]
Add a screen reader only box that show the status.

`aria-live="polite"`
`aria-relevant="text"`

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG1.3.1
