### ISSUE TITLE
[Usable] Focus persist on the same control after activate "Accessibility" Group's button.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1319]
**Actual Result:**
After activate the "Accessibility Button" focus persist on the same control.
Focus does not land on the related content after perform the action.

**Note** - Same issue repro All buttons which are appears after hit the 'Help' message.
2. URL[https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2FBotFramework-WebChat%2Fspeech-cognitive-services-bing-speech%2F%3Fs%3D7c7dacfe04044f4f99a1edcf9b0e2ab9&data=02%7C01%7Cv-saugup%40microsoft.com%7C0f6f5e63167449daa46d08d65570f676%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636790341026155420&sdata=gcFq8JsflCLfUKAyw8f2A19aJcEQEFxGzjASMK9S59A%3D&reserved=0](https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2FBotFramework-WebChat%2Fspeech-cognitive-services-bing-speech%2F%3Fs%3D7c7dacfe04044f4f99a1edcf9b0e2ab9&data=02%7C01%7Cv-saugup%40microsoft.com%7C0f6f5e63167449daa46d08d65570f676%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636790341026155420&sdata=gcFq8JsflCLfUKAyw8f2A19aJcEQEFxGzjASMK9S59A%3D&reserved=0) -> Mic Button -> Say 'Accessibility' - Screen will not scrolled, Focus persist on the same place. Attachment "**Usable_Mic button say Acessibility**".

**Expected Result:**
After activate the "Accessibility Button" focus should not persist on the same control.
Focus should land on the related content after perform the action

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle](https://microsoft.github.io/BotFramework-WebChat/full-bundle) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Type 'help' in the input control at the bottom of the screen and hit enter (or click on the send button).
4. Content will upload, Navigate to "Accessibility" button by using Tab key and press Enter on it.
5. Observe that focus persist on the same control after activate the button.

**User Impact:**
If keyboard focus is not not logical and not lands on the related content after perform the action then the user who is dependent on keyboard will get confuse.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version**: 1803
**Browser**: Edge

**Attachment:**
1. [Usable_Focus persist on the same control after activate.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2584047/Usable_Focus.persist.on.the.same.controla.after.activate.zip)
2. [Usable_Mic button say Acessibility.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2628687/Usable_Mic.button.say.Acessibility.zip)

**Comment by corinagum** [comment]
This is not a user scenarios, and therefore will not fix (confirmed with accessibility team)

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yUsable

**Comment by pgopinadhu** [comment]
#A11yUsable;#A11ySev4;
