### ISSUE TITLE
SSML tags automatically added to Text to Speech payload

### ISSUE THREAD

**Issue by williamw2** [microsoft/BotFramework-WebChat#1322]
The SSML content for text to speech synthesis destined for the Bing Text to Speech API (Cognitive Services) is being automatically wrapped in a <speak>, <voice>, and <prosody> tag even when those tags already exist in the SSML content. This is resulting in SSML syntax errors. Is there any way to turn this off?

Using https://cdn.botframework.com/botframework-webchat/latest/webchat.js and window.WebChat.createCognitiveServicesWebSpeechPonyfillFactory() to create the webSpeechPonyfillFactory.

**Comment by compulim** [comment]
Synthesized text are no longer automatically wrapped in SSML if they looks like SSML.

This is fixed in #2243.
