### ISSUE TITLE
Latest WebChat : IE11 Compatibility

### ISSUE THREAD

**Issue by chinnivyshnavi** [Microsoft/BotFramework-WebChat#1326]
Hi

I am using the latest version of the webchat framework. I took the full-bundle sample from the github repository.

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Full-featured bundle</title>
  
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js"></script>
	<script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
    <style>
      html, body { height: 100% }
      body { margin: 0 }

      #webchat,
      #webchat > * {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat"></div>
    <script>	
	  
      (async function () {
        
        window.webchat.renderwebchat({
         directline: window.webchat.createdirectline({ token:"MY_DIRECTLINE_SECRET" })
        }, document.getelementbyid('webchat'));

        document.queryselector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>

This is my sample html that I am using. 
When I view the html in the IE11 it is showing blank screen with an error in the console

![image](https://user-images.githubusercontent.com/27405044/48180556-007bd280-e34a-11e8-9197-ce6af52e274a.png)

Please help me

**Comment by rosskyl** [comment]
It looks like to use IE11 you need to register it differently. Below is the sample from https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/es5-bundle/index.html

```
window.fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' })
.then(function (res) {
  return res.json();
})
.then(function (json) {
  const token = json.token;
  window.WebChat.renderWebChat({
	directLine: window.WebChat.createDirectLine({
	  token: token
	})
  }, document.getElementById('webchat'));
  document.querySelector('#webchat > *').focus();
});
```

**Comment by compulim** [comment]
@rosskyl Thanks for answering this, you are correct IE11 doesn't support `async` keyword and need to use thenable instead. 😉

@chinnivyshnavi You only need `webchat-es5.js`, not both `botchat-es5.js` and `webchat.js`.

**Comment by chinnivyshnavi** [comment]
Thank you guys... there are no errors in the IE console but the message is not posting in the conversation.

my updated code:
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Full-featured bundle</title>
  
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <style>
      html, body { height: 100% }
      body { margin: 0 }

      #webchat,
      #webchat > * {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat"></div>
    <script>	
	   window.fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' })
        .then(function (res) {
          return res.json();
        })
        .then(function (json) {
          const token = json.token;
          window.WebChat.renderWebChat({
            directLine: window.WebChat.createDirectLine({
              token:"MY_DIRECTLINE_SECRET"
            })
          }, document.getElementById('webchat'));
          document.querySelector('#webchat > *').focus();
        });      
    </script>
  </body>
</html>

![image](https://user-images.githubusercontent.com/27405044/48300211-52b22480-e4ff-11e8-82eb-8c8f19e73d66.png)

After typing the message, when I press the enter, the message is not posting to the bot

Thanks in advance

**Comment by corinagum** [comment]
@Support Could someone take over this issue? If the send button is disabled (as indicated in the screencap), there may be a JS error or the connection failed.

**Comment by Akkilz** [comment]
I need to enable webSpeechPonyfillFactory in es5, but the code is working fine in chrome and firefox not in IE.

Below is the code I am using, plz guide me to fix the issue in IE.
Code:
<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
 var webSpeechPonyfillFactory;
        var region = "westeurope";

        var authorizationToken;
        var directLineToken;


        window.fetch('/BotTest/GetBothToken', { method: 'POST' })
            .then(function (res) {
                return res.json();
            })
            .then(function (json) {
                authorizationToken = json.speechToken;
                directLineToken = json.directLineToken;

                window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({ authorizationToken: authorizationToken, region: region }).then(function (res) {
                    webSpeechPonyfillFactory = res;
                    return;
                }).then(function () {


                    window.WebChat.renderWebChat({
                        directLine: window.WebChat.createDirectLine({
                            token: directLineToken
                        }),
                        webSpeechPonyfillFactory: webSpeechPonyfillFactory
                    }, document.getElementById('webchat'));

                    document.querySelector('#webchat > *').focus();
                });
            });

**Comment by linuradu** [comment]
> Thank you guys... there are no errors in the IE console but the message is not posting in the conversation.
> 
> my updated code:
> 
> <title>Web Chat: Full-featured bundle</title>
> ```
> <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
> <style>
>   html, body { height: 100% }
>   body { margin: 0 }
> 
>   #webchat,
>   #webchat > * {
>     height: 100%;
>     width: 100%;
>   }
> </style>
> ```
> <script>	window.fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' }) .then(function (res) { return res.json(); }) .then(function (json) { const token = json.token; window.WebChat.renderWebChat({ directLine: window.WebChat.createDirectLine({ token:"MY_DIRECTLINE_SECRET" }) }, document.getElementById('webchat')); document.querySelector('#webchat > *').focus(); }); </script>
> ![image](https://user-images.githubusercontent.com/27405044/48300211-52b22480-e4ff-11e8-82eb-8c8f19e73d66.png)
> 
> After typing the message, when I press the enter, the message is not posting to the bot
> 
> Thanks in advance

I encountered the same issue and finally, I've remarked that the messages itself are shown in DOM but I cannot see them. The problem was when the `div` with the webchat id was included in another div.
 
Please find here a working example (if you uncomment the commented lines will see that will not work anymore):


```
<!DOCTYPE html>
<html lang="en-US">
<head>
    <script src="https://cdn.botframework.com/botframework-webchat/master/webchat-es5.js"></script>
    <style>
      html, body { height: 100% }
      body { margin: 0 }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>

</head>
<body>
    <!--<div class="chatbot-popup" id="chatbotForm">-->
        <div id="webchat"></div>
    <!--</div>-->

    <script type="text/javascript" language="JavaScript">
          var botConnection = new window.WebChat.createDirectLine({
            token: "myToken"
          });

          var styleOptions = {
            botAvatarInitials: 'IDA',
            userAvatarInitials: 'ME'
          };

          window.WebChat.renderWebChat({
            directLine: botConnection,
            styleOptions: styleOptions
          }, document.getElementById('webchat'));
    </script>
</body>
</html>
```
