### ISSUE TITLE
Speech: Microphone not respecting input hint

### ISSUE THREAD

**Issue by eljodon** [Microsoft/BotFramework-WebChat#1328]
The microphone keeps activating and listening after a message is received, ignoring the message input hint value. This behavior is happening in the latest Chrome and Edge browsers at least.

I am using the the latest full bundle:
https://cdn.botframework.com/botframework-webchat/latest/webchat.js

**Comment by compulim** [comment]
Got it, will work on it. 😉

**Comment by compulim** [comment]
More information about the input hint at https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#activity-object.

**Comment by corinagum** [comment]
@lauren-mills provided very helpful input that I will copy-paste below: (emphasis mine)

> The approach that seems to work best is that each message should be `IgnoringInput` except for the final message on a turn, **which should be `ExpectingInput` for prompts or `AcceptingInput` for other messages.** This approach prevents the bot from ever listening to itself and getting stuck in a feedback loop.
