### ISSUE TITLE
Plans on V3?

### ISSUE THREAD

**Issue by enessoylu** [Microsoft/BotFramework-WebChat#1329]
Hi @compulim,

What is your plan regarding the V3? Will there be any update like bug fixes, features, etc...

**Comment by compulim** [comment]
We are sunsetting v3.

Similar to other open source projects, we will continue to provide limited fixes, but there won't be any new features.

Let me know if there are anything that v4 couldn't work out for you. For example, if you don't know how to port some of your cool customizations from v3, let us know. We are happy to point you to sample or write some new samples so you can just copy-and-paste the code. 😉
