### ISSUE TITLE
Web Chat sample names are not informative 

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotFramework-WebChat#1332]
When jumping into Web Chat v4, it's difficult to tell (just based on names) what samples to use. Consider summarizing each sample and referencing them from the main Web Chat README.

(Edited by @compulim for branding corrections)

**Comment by corinagum** [comment]
reference: https://github.com/Microsoft/Botbuilder-samples table

**Comment by corinagum** [comment]
* [ ] Create list of which samples still need a README.md
* [ ] Write said README's
* [ ] Comb through samples to link external concepts (such as ponyfilling, redux, etc)
