### ISSUE TITLE
Adaptive Card not rendering correctly when showing images

### ISSUE THREAD

**Issue by djpirra** [Microsoft/BotFramework-WebChat#1333]
Web Chat control not rendering AdaptiveCard correctly when showing an image. 
When using the emulator and directline tests everything works fine.
![webcontrolproblem](https://user-images.githubusercontent.com/15980662/48309818-da00a600-e59a-11e8-9149-76472d137baf.JPG)

**Comment by djpirra** [comment]
This is the adaptive card schema I am using:

`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "size": "default",
      "text": "1. Right click on the report menu and select open from the task list:",
      "wrap": true,
      "maxLines": 0
    },
    {
      "type": "Image",
      "url": "https://********.azurewebsites.net/Images/Print1.JPG",
      "size": "auto",
      "horizontalAlignment": "center",
      "selectAction": "No"
    }
  ]
}`

**Comment by elena20ruiz** [comment]
Hi @compulim,  about adaptive card multi-choice, I am using v4, and tried with master version. But I will try to generate my own Adaptive Card Host Config file. Thanks.

**Comment by baldrin** [comment]
I'm having the same issue when creating either a ChoicePrompt or ConfrimPrompt in the v4 .Net Core C# SDK. Always get '(1) Yes (2) No' in the browser, but it works fine in the emulator.

**Comment by baldrin** [comment]
I was able to resolve my issue. In the v4 C# SDK.  After some debugging it appears the Choice.Style defaults to 'Auto'. The result is when using the directline channel it causes the choice to appear as '1) Yes 2) No'. I changed my code from 

`AddDialog(new ChoicePrompt(VerifyInfoPrompt));`
to
`AddDialog(new ChoicePrompt(VerifyInfoPrompt)
{
    Style = ListStyle.SuggestedAction,
});`

The above code makes the choices show up as buttons again. I'd like to take this moment to thank myself for my tenaciousness in trying to resolve this issue. :)

**Comment by compulim** [comment]
@baldrin that's a good one. I know that is a bug on the SDK but I never know it can be workaround-ed.

I always dig into the (JavaScript) source code whenever I hit some obstacles.

1. I am always the expert of my own problem
1. If I found the bug in the code, I can just point it to the authors and they can fix it right away
1. Talking in code is easier than talking in English, the "code -> English -> code" translation introduce lost in fidelity 🤣

Hope it isn't too difficult to debug into C# code.

**Comment by corinagum** [comment]
Need to investigate the JSON missing image problem.

**Comment by corinagum** [comment]
Hi @djpirra, sorry for the delay. We still need to do some investigation on this one. 

### To investigator:
 take adaptive card JSON that djpirra provided and test on MockBot

**Comment by corinagum** [comment]
@djpirra Sorry for the delay in getting back to you. I tested this Adaptive Card and I am able to get it to render normally on both v3 and v4 of Web Chat.

Are you using the Azure Portal `iframe` embed? If yes, one error I noticed is that you are using version 1.0 of Adaptive Cards, but v3 only supports up through 0.6.1 right now.  We are excited to update to Azure Portal with v4, and that progress can be tracked here: https://github.com/Microsoft/BotFramework-WebChat/issues/1086

If you need to use Adaptive Cards version 1.0 are willing to update to v4 (not using embed), it's possible that this issue may be resolved by bumping Web Chat.
here is my screencap: 
![image](https://user-images.githubusercontent.com/14900841/51151557-43fa2d80-1820-11e9-96a4-cb2eafffb738.png)

If you'd like to try out Web Chat v4, please take a look at our samples for how to get started. [01.a.getting-started-full-bundle](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.a.getting-started-full-bundle)
