### ISSUE TITLE
[MAS2.4.3] Focus is not landing on the interactive data on the page after activating the 'Show Bing Sports' using Adaptive cards button.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1335]
**Actual Result:**
Focus is not landing on the interactive data on the page after activating the 'Show Bing Sports' using Adaptive cards button.

**Expected Result:**
Focus should land on the all interactive data which appear on the page after activating the 'Show Bing Sports' using Adaptive cards button. 

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle](https://microsoft.github.io/BotFramework-WebChat/full-bundle)in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Type 'help' in the input control at the bottom of the screen and hit enter (or click on the send button).
4. Content will upload, Navigate to any "Show Bing Sports using Adaptive cards button " button by using Tab key and press Enter on it.
5. New data will upload, navigate to the data by using Tab key. 
6. Observe that focus is not landing on the all interactive data.

**User Impact:**
If keyboard focus is not not logical and not lands on the related content after perform the action then the user who is dependent on keyboard will get confuse.

**MAS Reference:**
[MAS2.4.3_Focs order.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2571908/MAS2.4.3_Focs.order.zip)

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge

**Attachment:**

**Comment by compulim** [comment]
This is by-design.

The card has 3 hot spots to click on:
- The whole container
- The left column (the panther and the word "CAR")
- The panther image

So the <kbd>TAB</kbd> is going thru correct tab order.

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG2.4.3
