### ISSUE TITLE
[Usable] 'Showing markdown' Content is not completely visible after navigating to "www.bing.com?.." link.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1338]
**Actual Result:**
'Showing markdown' Content is not completely visible after navigating to "www.bing.com?.." link.

**Expected Result:**
'Showing markdown' Content is not completely visible after navigating to "www.bing.com?.." link.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle](https://microsoft.github.io/BotFramework-WebChat/full-bundle) in Edge browser.
2. Notice 'Upload File' and 'Send' button icons present in bottom of screen.
3. Type 'help' in the input control at the bottom of the screen and hit enter (or click on the send button)
4. Content will upload, Navigate to any "Show Markdown using Adaptive cards button" button by using Tab key and press Enter on it.
5. New data will upload, navigate to the data by using Tab key.
6. Observe that when focus lands on the "www.bing.com?.." link then content is not properly visible .

**User Impact:**
If content of the page is not properly visible, User who is visually impaired will not able to understand the content and will get confuse.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge

**Attachment:**
[Usable_content of the page.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2574683/Usable_content.of.the.page.zip)

**Comment by compulim** [comment]
On `card markdown`, we clipped the content horizontally, need to fix the layout.

![image](https://user-images.githubusercontent.com/1622400/49110131-797f9300-f241-11e8-88cc-b0dfda06e947.png)

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yUsable
