### ISSUE TITLE
Need offline UI

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#135]

**Comment by danmarshall** [comment]
@billba can you work the logic on this and I can come back and add CSS.

**Comment by billba** [comment]
done.

**Comment by corinagum** [comment]
@mewa1024 Sorry for tagging and untagging you so many times -- (Can't find Marc to assign him). Do you think you or Marc may be able to address this?

**Comment by mewa1024** [comment]
Forwarding to mysterious Marc (until he gets set up with GitHub).

**Comment by compulim** [comment]
Marc is @designpolice.

**Comment by corinagum** [comment]
This needs to be split into multiple issues.

**Comment by corinagum** [comment]
This has been split into multiple issues. Closing.
