### ISSUE TITLE
Tool tip which appears on mouse hover (on controls of music bar) does not appear using keyboard.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1353]
**Actual Result:**
Tool tip which appears on mouse hover (on controls of music bar) does not appear using keyboard.

**Note** - Same issue repro on Video clips also.

**Expected Result:**
Tool tip which appears on mouse hover (on controls of music bar) should also appear using keyboard.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Navigate to 'Type your message' text box present in bottom of screen, type 'help' and press enter key.
3. Navigate to 'Show an audio attachment' button and activate it.
4. Navigate to every controls of music bar and observe if tool tips appears or not.

**User Impact:**
If tool tip does not appear on any control then the user who is visually impaired will not able to understand the purpose of that control.

**Test Environment:**
OS: Windows 10
OS Build: 17763.107
OS Version: 1809
Browser: Edge

**Attachment:**
[Usable_Tooltip.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2580761/Usable_Tooltip.zip)

**Comment by compulim** [comment]
We did not customize the playback controls from the browser. If this bug repro on Edge, this bug should goes to their bucket.

**Comment by corinagum** [comment]
Confirmed as external by accessibility team

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG2.1.1
