### ISSUE TITLE
In scan mode narrator focus gets lost after volume controller.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1355]
**Actual Result:**
In scan mode narrator focus gets lost after volume controller.

**Note:**
1. Narrator focus again moves back to music bar on forward navigation.
2. On backward navigation, correct name property is not defined for music bar and narrator focus jumps to time text present under 'audio'.

**Expected Result:**
In scan mode narrator focus should visible on every control.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Start Narrator by pressing "Ctrl + Win + Enter" key.
3. Navigate to 'Type your message' text box present in bottom of screen, type 'help' and press enter key.
4. Navigate to 'Show an audio attachment' button and activate it.
5. Navigate the music bar in scan mode with down arrow key.
6. Observe that if narrator focus gets lost after volume controller or not.

**User Impact:**
If narrator focus gets lost at the time of navigation then the user who use scan mode to navigate the page will get confuse as they think there are more controls are present on the page.

**Test Environment:**
OS: Windows 10
OS Build: 17763.107
OS Version: 1809
Browser: Edge

**Attachment:**
[Narrator_FocusLost.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2580805/Narrator_FocusLost.zip)

**Comment by compulim** [comment]
We did not customize the playback controls from the browser. If this bug repro on Edge, this bug should goes to their bucket.

Related to #1358.

**Comment by corinagum** [comment]
Confirmed as external by accessibility team

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG4.2.10
