### ISSUE TITLE
Focus does not remain on 'Full screen/Exit full screen' control after pressing enter key on it.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1365]
**Actual Result:**
Focus does not remain on 'Full screen/Exit full screen' control after pressing enter key on it.

**Expected Result:**
Focus should remain on 'Full screen/Exit full screen' control control after pressing enter key on it.

**Repro Steps:**
1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Navigate to 'Type your message' text box present in bottom of screen, type 'help' and press enter key.
3. Navigate to button of "Multiple media attachments" and activate it.
4. All multimedia will appear on the bottom of the screen.
5. Navigate to any video and press enter key on 'Full screen/Exit full screen' control two three times.
6. Observe if focus indicator remains on triggering control or not.

**User Impact:**
If focus indicator does not remain on triggering control then it will be very difficult for the keyboard dependent user to access that control.

**Test Environment:**
OS: Windows 10
OS Build: 17763.107
OS Version: 1809
Browser: Edge

**MAS Reference:**
[MAS 2.4.3 - Focus Order (05)](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9})

**Attachment:**
[MAS2.4.3_FocusOrder.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2588198/MAS2.4.3_FocusOrder.zip)

**Comment by compulim** [comment]
We don't customize the HTML5 `<video>` tag, we don't bring our own playback controls to it.

- [ ] Investigates if this is an Edge or Chrome bug

**Comment by compulim** [comment]
Reopening so we can confirm from the accessibility team.

**Comment by corinagum** [comment]
Confirmed with accessibility team as an Edge bug

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG2.4.3
