### ISSUE TITLE
[Usable] 'SurfacePro4 and Surface Pro 4 (2)' controls define as a button but visually looks like an Image on 'Receipt card' content. 

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1368]
**Actual Result:**
'SurfacePro4 and Surface Pro 4 (2)'  Buttons are visually looks like an Image but define as a button.

**Expected Result:**
'SurfacePro4 and Surface Pro 4 (2)'  Buttons should not be looks like an Image.

Repro Steps:

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Navigate to 'Type your message' text box present in bottom of screen, type 'help' and press enter key.
3. Navigate to  "Receipt card " button by using Tab key and press Enter on it to activate it.
4. New content will appear on the bottom of the screen. 
5. Navigate to 'SurfacePro4 and Surface Pro 4 (2)' controls.
6. Press F12 to open developer tool and check the role for SurfacePro4 and Surface Pro 4 (2)'
7. Observe that controls define as a button but looks like an image.

User Impact:
User will get confuse if controls define as a button but visually looks like an Image, User will not able to perform the action. 

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17763.107
**OS Version:** 1809
**Browser**: Edge
**Tool:** F12(Developer tool bar)

**Attachment:**
![usable_buttons present on the page visually looks like an image](https://user-images.githubusercontent.com/41668935/48615051-cea3e500-e9b5-11e8-83aa-f407e46a638c.png)

**Comment by compulim** [comment]
@priysn this is by design. It is designed to let the user to drill into individual receipt item.

What is your recommendation on allowing the user to drill into the individual item?

**Comment by compulim** [comment]
Reopening so we can confirm from the accessibility team.

**Comment by corinagum** [comment]
Confirmed with the Accessibility team that this is external and will inform the Adaptive Cards team.

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yUsable
