### ISSUE TITLE
'Blue', 'Red' and 'Green' button present on the page disappears after activating any button.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1369]
**Actual Result:**
'Blue', 'Red' and 'Green' button present on the page disappears after activating any button.

Note: Same issue repro at -
URL -> Help -> Postback messages Button -> + Im back as string button/ + Post back as string button/ + Post back as Jason button-> Select any button from them button - button present on the page disappears after activating any button. 

**Expected Result:**
'Blue', 'Red' and 'Green' button present on the page should not disappear after activating any button.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Navigate to 'Type your message' text box present in bottom of the screen, type 'help' and press enter key.
3. Navigate to button of 'Suggested actions' and activate it.
4. Navigate to any of 'Blue', 'Red' and 'Green' button present on the page and activate it.
5. Observe if mentioned button remains on the page or not.

**User Impact:**
If any control present on the  page disappears after activating then the user who is dependent on keyboard will get confuse when they try to access another control.

**Test Environment:**
OS: Windows 10
OS Build: 17763.107
OS Version: 1809
Browser: Edge

**Attachment:**
1. [Functional_Button.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2588888/Functional_Button.zip)
2. [Functional_Postback button.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2604081/Functional_Postback.button.zip)

**Comment by compulim** [comment]
@priysn This is expected behavior. Suggested actions are one-off button that is designed to go away after the user click on it or send a text message.

If we need the buttons to disappear, is there any ARIA tags that could help us in this scenario?

**Comment by corinagum** [comment]
After discussion with Accessibility, we have determined that this functionality is by design and does not create a different user experience for screen reader users.
