### ISSUE TITLE
Scan mode focus stay twice on video pane.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1376]
**Actual Result:**
Scan mode focus stay twice on video pane.

**Note:**
Same issue also reproducible for video slider bar, 'vimeo' link and 'Like' button.

**Expected Result:**
Scan mode focus should stay once on video pane.

**Repro Steps:**

1. Open URL [https://microsoft.github.io/BotFramework-WebChat/full-bundle/](https://microsoft.github.io/BotFramework-WebChat/full-bundle/) in Edge browser.
2. Start Narrator by pressing 'Ctrl + Win + Enter' key.
3. Navigate to 'Show a video attachment from Vimeo' button and activate it.
4. Video will appear at the bottom of the page.
5. Navigate the video pane in scan mode with down arrow key.
6. Observe if scan mode focus stay once or twice on video pane.

**User Impact:**
If focus stay twice on any control then the user who use scan mode to navigate the page will get confuse as they think there are more control present on that area of page.

**Test Environment:**
OS: Windows 10
OS Build: 17763.107
OS Version: 1809
Browser: Edge

**Attachment:**
[Usable_Twice.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2595049/Usable_Twice.zip)

**Comment by compulim** [comment]
This is not a bug from Web Chat. The video content is an IFRAME owned by Vimeo.

**Comment by compulim** [comment]
Reopening so we can confirm from the accessibility team.

**Comment by corinagum** [comment]
Confirmed with Accessibility as External

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG2.4.3
