### ISSUE TITLE
user id provided being ignored.

### ISSUE THREAD

**Issue by mrThirsty** [Microsoft/BotFramework-WebChat#1382]
When connecting to the bot via directline we set the user object with a custom ID as it is for logged in users. however, the chat bot always recieves the default values in the From tag, this means that we can't persist custom user data specific to the user logged in. 

Below is the JS we have on the page:

`var userId = "2D8E3603-62ED-E811-8154-5065F38B1651";
            var user = { id: userId, name: "Adriaan Van Niekerk" };
            var bot = { id: "BOT" };

            (async function(){
                const res = await fetch("https://botapi.azurewebsites.net/api/token", { method: 'POST', body: JSON.stringify({ UserID: userId }) });
                const { token } = await res.json();

                var botConnection = new window.WebChat.createDirectLine({
                    token: token
                });

                window.WebChat.renderWebChat({
                    directLine: botConnection,
                    user: user
                }, document.getElementById('BotChatGoesHere'));
            })().catch(err => console.error(err));`

no matter what I try to change in the above, the bot always receives "default-user" as the From detail on any activity.

**Comment by mrThirsty** [comment]
I managed to figure out how to set the user id:

`(async function(){
            const res = await fetch("https://botapi.azurewebsites.net/api/token", { method: 'POST', body: JSON.stringify({ UserID: userId }) });
            const { token } = await res.json();

            var botConnection = new window.WebChat.createDirectLine({
                token: token
            });

            window.WebChat.renderWebChat({
                directLine: botConnection,
                user: user,
                userID: userid
            }, document.getElementById('BotChatGoesHere'));
        })().catch(err => console.error(err));``

**Comment by pedrosalider** [comment]
> I managed to figure out how to set the user id:
> 
> `(async function(){
> const res = await fetch("https://botapi.azurewebsites.net/api/token", { method: 'POST', body: JSON.stringify({ UserID: userId }) });
> const { token } = await res.json();
> 
> ```
>         var botConnection = new window.WebChat.createDirectLine({
>             token: token
>         });
> 
>         window.WebChat.renderWebChat({
>             directLine: botConnection,
>             user: user,
>             userID: userid
>         }, document.getElementById('BotChatGoesHere'));
>     })().catch(err => console.error(err));``
> ```

Hi @mrThirsty I tried you suggestions and it isn't working for me. MY bot always receives "default-user" as the From detail.
