### ISSUE TITLE
No option to hide upload button in v4.1

### ISSUE THREAD

**Issue by xinfli** [Microsoft/BotFramework-WebChat#1383]
An option "showUploadButton" was added to hide upload button for issue [#883](https://github.com/Microsoft/BotFramework-WebChat/pull/883), but in v4.1.0 there is no such option.

So now is it possible to hide the upload button on rederWebChat()?

**Comment by vmunnuru** [comment]
Its possible with styling:

`import { createStyleSet } from 'botframework-webchat';

const styleSet = createStyleSet({});

styleSet.uploadButton = { ...styleSet.uploadButton,
  display: 'none'
};
(while returning send property to the component as)
styleSet={styleSet}`
