### ISSUE TITLE
Get URL Referer

### ISSUE THREAD

**Issue by pedrosalider** [Microsoft/BotFramework-WebChat#1391]
I'm using a directline inside my website and I was wondering if there is anyway to get the URL of the website inside my bot code. Previously, in v3, I was initializing the chat with:
```
    BotChat.App({
        directLine: { secret: "{directline_secret}" },
        user: { id: 'You', referrer: window.location.href},
        bot: { id: '{bot_id}' },
        resize: 'detect'
    }, document.getElementById("bot"));
```
and I was able to get the referrer with this line of code `activity.From.Properties["referrer"].ToString()`, but in v4 I can't find a way to get the referrer inside the bot.

**Comment by corinagum** [comment]
This issue has a solution that is pending in PR https://github.com/Microsoft/BotFramework-WebChat/pull/1286
Closing this issue, but you can track progress on https://github.com/Microsoft/BotFramework-WebChat/issues/1371
