### ISSUE TITLE
Enabling speech function on webchannel inside modern SharePoint Online

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotFramework-WebChat#1393]
I'm having this problem where I have my chatbot deployed and embedded in a modern SharePoint Online site. How do I enable the microphone so users can speak into? Most answers I find talk about using html and js to do it

**Comment by corinagum** [comment]
Yes, currently using js is the only way to implement speech. 
For security, we don't want the bot to have an exposed secret, and therefore we need an access token, which requires js to generate.

Previously many of our samples used secrets on the bot's web page, but we're doing our best to discourage this practice.
