### ISSUE TITLE
New speech feature from Cognitive Services Speech Services

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1400]
This is the work item for additional features from Speech Services. The original feature on-par work is #1336.

- [ ] P0: Custom speech
- [ ] P1: Reference grammar ID (for LUIS)
- [ ] P1: Biased word list (a.k.a. dynamic priming)
- [ ] P2: Custom voice font
- [ ] P2: Continuous mode
   - Blocked
- [ ] P2: Push-to-talk
   - `recognizeOnceAsync` do not have a cancellation mechanism, we need to investigate workarounds

**Comment by corinagum** [comment]
@seaen @sgellock Preference check: would you prefer these to be split into multiple bugs or kept as one?

**Comment by corinagum** [comment]
Closing as I have expanded this into multiple issues. Please see those issues for more information.
