### ISSUE TITLE
Dial back Web Chat retries (code 429)

### ISSUE THREAD

**Issue by seaen** [Microsoft/BotFramework-WebChat#1404]
Related to #1080 - focused on the remaining code 429

----------------- Original text ------------------
Web Chat aggressively retries under two conditions:

When Web Chat is polling with GET and receives a 404, it continues polling. A 404 is unlikely to be resolved as the resource is gone.
If Web Chat receives an HTTP 400 when opening a websocket connection, it retries very quickly
There may be other cases but these two should be reviewed and we should have a different retry policy -- either progressively back off the retry interval, or do not retry at all.

**Comment by cwhitten** [comment]
This is addressed in https://github.com/Microsoft/BotFramework-WebChat/pull/1544
