### ISSUE TITLE
Remove `npm-run-all` from v3

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1407]
For the recent [malicious script of `flatmap-stream`](https://www.npmjs.com/advisories/737), Web Chat v3 and v4 are *not* affected.

Web Chat v3 is using `npm-run-all` for its development toolchain. This package use an *unaffected* version of `event-stream@3.3.4` (via `ps-tree`). Although it is not affected, for precaution, we are removing `npm-run-all` from our v3 package. The package is used for "watch mode" during our development build to make our development more convenient. This package does not made itself into any of our production code.

As this tool is only used for build watch, the removal will not affect any production code and do not requires any redeployment.

### Note to fixer

- [ ] Remove scripts that use `npm-run-all`, they should be scripts for development use (not build pipeline)
- [ ] Remove dependency to `npm-run-all`, make sure to commit `package-lock.json`

**Comment by tonyanziano** [comment]
Addressed in #1446
