### ISSUE TITLE
[MAS4.1.2] Does not provide the information about the 'Mic' button that Mic has been activated.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1409]
**Actual Result:**
Does not give the information about the Mic button that Mic has been activated.
Narrator is reading complementary landmark after enable the 'Mic' button.

**Expected Result:**
Should give the information about the Mic button that Mic has been activated.

Repro Steps:

1. Open URL https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2FBotFramework-WebChat%2Fspeech-cognitive-services-bing-speech%2F%3Fs%3D7c7dacfe04044f4f99a1edcf9b0e2ab9&data=02%7C01%7Cv-saugup%40microsoft.com%7C0f6f5e63167449daa46d08d65570f676%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636790341026155420&sdata=gcFq8JsflCLfUKAyw8f2A19aJcEQEFxGzjASMK9S59A%3D&reserved=0 in Edge browser.
2. Notice 'Upload File' and 'Mic' button icons present in bottom of screen.
3. Open Narrator (Ctrl.+Win. Key+ Enter)
4. Navigate to mic button by using Tab key and press Enter to activate it.
5. Mic button will activate.
6. Observe that after activate the 'Mic' button, narrator is reading complementary landmark.

**User Impact:**
Screen reader users may get confuse if not give the complete information about the activated control.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge
**Tool:** Narrator

**Attachment:**
[MAS4.1.2_not give the information that mic button has been activated..zip](https://github.com/Microsoft/BotFramework-WebChat/files/2628446/MAS4.1.2_not.give.the.information.that.mic.button.has.been.activated.zip)

**Comment by corinagum** [comment]
aria-live = polite on the screen reader only status

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG4.1.2
