### ISSUE TITLE
https://unpkg.com/botframework-webchat/botchat.js and .css are not found

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/BotFramework-WebChat#1418]
https://unpkg.com/botframework-webchat/botchat.js and https://unpkg.com/botframework-webchat/botchat.css were previously valid urls.  They now redirect to https://unpkg.com/botframework-webchat@4.1.0 which is then not found:

> Cannot find "/botchat.js" in botframework-webchat@4.1.0

[bug]

**Comment by compulim** [comment]
This is by-design.

v3 is named as `botchat.js` (`< 1.0.0`). To prevent collision and make sure the user are aware of the API change, we name v4 as `webchat.js` (`>= 4.0.0`).

However, on https://cdn.botframework.com/botframework-webchat/latest/, user can specify `botchat.js` for v3, and `webchat.js` for v4.

**Comment by EricDahlvang** [comment]
This is a breaking change.  Existing sites, referred to by our docs, use this:

http://contososcubademo.azurewebsites.net

I would assume customers do also, considering this was once the suggested url.
