### ISSUE TITLE
Blue color of 'Retry' is not distinct as button on the page.

### ISSUE THREAD

**Issue by priysn** [Microsoft/BotFramework-WebChat#1426]
Actual Result:
'Retry' button look like as a link but define as a button.

Expected Result:
'Retry' button should not look like as a link.

Repro Steps:

1. Open URL [ https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2FBotFramework-WebChat%2Fspeech-cognitive-services-bing-speech%2F%3Fs%3D7c7dacfe04044f4f99a1edcf9b0e2ab9&data=02%7C01%7Cv-saugup%40microsoft.com%7C0f6f5e63167449daa46d08d65570f676%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636790341026155420&sdata=gcFq8JsflCLfUKAyw8f2A19aJcEQEFxGzjASMK9S59A%3D&reserved=0]( https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.github.io%2FBotFramework-WebChat%2Fspeech-cognitive-services-bing-speech%2F%3Fs%3D7c7dacfe04044f4f99a1edcf9b0e2ab9&data=02%7C01%7Cv-saugup%40microsoft.com%7C0f6f5e63167449daa46d08d65570f676%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636790341026155420&sdata=gcFq8JsflCLfUKAyw8f2A19aJcEQEFxGzjASMK9S59A%3D&reserved=0) in Edge browser.
2. Turn on airplane mode.
3. Navigate to 'Type your message' text box present in bottom of screen, type 'hi' and press enter key.
4. Observe that 'Retry' Text  is not distinct as button on the page.

User Impact:
If button is not discriminative to the normal text on the page, Keyboard user will face the difficulty to differentiate the normal text and link.

**Test Environment:**
**OS:** Windows 10
**OS Build:** 17134.345
**OS Version:** 1803
**Browser:** Edge

**Attachment:**
[MAS1.4.1_Use of color for retry button.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2647566/MAS1.4.1_Use.of.color.for.retry.button.zip)

**Comment by corinagum** [comment]
@priysn  can we confirm that the correct video is attached? The video currently attached doesn't appear to be Web Chat.

**Comment by priysn** [comment]
Closing this bug as per Jason's suggestion.

**Comment by Amit8527510735** [comment]
#HCL;#Accessibility;#HCL_BotFramework_WebChat;A11yMAS;WCAG1.4.1
