### ISSUE TITLE
Sample: Disable Adaptive Cards after submit/obsoleted

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#1427]
## Goals

- Write a new attachment renderer that will disable Adaptive Card interactivity if a certain condition is met
   - If the Adaptive Card is no longer the last visible activity sent from the bot, or there is a message sent by the user succeeding it, disable interactivity on the Adaptive Card
- There could be more than one Adaptive Card form available on the page
- Also consider, if "expand card" action button should be disabled or not. It was because "expand card" button should not be counted as "form submission", we might not want to disable expand/collapse feature
   - If implementer is not familiar with this feature, should consult the "Adaptive Card visualizer" page for details

## Non-goals

It should not use jQuery or any other DOM-manipulating libraries to achieve the goal. It must use pure React.

## Reference

We have a sample named "presentation mode". It showed the ability to disable interactivity of the whole Web Chat UI, including Adaptive Card content. The implementer can look into that to understand how to disable interactivity for just a specific attachment

**Comment by Unders0n** [comment]
will it also include disabling cards and buttons in it after submitting? Cos now its not very obvios after button click that it was actually cliked and if clicked twice by default we have 2 events and messages dublicated. There's a backend workaround for that: https://stackoverflow.com/questions/51701003/microsoft-bot-framework-webchat-disable-adaptivecards-submit-buttons-of-previou , but it seems very hacky. Thanks

**Comment by Naveenbc** [comment]
Is there any update on this? Because I am using adaptive cards inside waterfall dialog exactly like prompt choices, Once the button is clicked it has to be disabled or made obsolete. If there is an update please tell me how do I do it in node js. Also the above C# solution not working for me.

**Comment by vishmonne** [comment]
Any updated solution for disabling a adaptive card button totally once its clicked once ?

**Comment by NaveenGaneshe** [comment]
Any updates ?

**Comment by avilde** [comment]
The only way I found was to use a custom activityMiddleware where I draw my own message header and actions. As the web-chat component is written in React, I used class state to draw/not draw children (action buttons).
This however leads to manual parsing of adaptive cards from card attachments coming into activity middleware.

Documentation: https://github.com/microsoft/BotFramework-WebChat#web-chat-api-reference

**activityMiddleware** | A chain of middleware, modeled after Redux middleware, that allows the developer to add new DOM components on the currently existing DOM of Activities. The middleware signature is the following: options => next => card => children => next(card)(children).

**Comment by dkonyayev** [comment]
Hi, any updates on this feature. We have observed that users always try to scroll up to click on hero card buttons when the response is no longer expected. If would be great if hero card was disabled once it is not longer last activity element.

**Comment by corinagum** [comment]
Hi @dkonyayev, we do not have updates at this time. Others who are looking for this feature are welcome to add their +1 to increase traction.

**Comment by ManjulaMalaiarasan** [comment]
+1

**Comment by Naveenbc** [comment]
+1

**Comment by avilde** [comment]
In our project this was is a must have feature. 
We however made a workaround with our Redux store to save last message id (activity.id).In a React component we would check if it is the last message so we do not show the action buttons and those cannot be pressed twice (e.g. authentication).

**Comment by sw353552** [comment]
+1 
any update on this yet?

**Comment by Jhiertz** [comment]
+1

**Comment by sw353552** [comment]
@avilde Can u please show a sample of how u checked if the activity.id is the last message received?

In my case, I will have to only enable the last adaptive card received and disable all the others so that the user can't click on a previously rendered adaptive card and disturb the flow.

Thanks in advance.

**Comment by HesselWellema** [comment]
+1

**Comment by AndrewNagulyak** [comment]
+1

**Comment by MouadhDos** [comment]
+1

**Comment by Vimarech** [comment]
+1

**Comment by compulim** [comment]
Will do it this week. 😉

**Comment by avilde** [comment]
https://tenor.com/uuRX.gif :)

**Comment by compulim** [comment]
Teaser...

There are still some kinks but reasonable okay as this will be a sample, not production code. I want to spend some more time think about this approach.

![recording](https://user-images.githubusercontent.com/1622400/81153452-c9cf4a00-8f37-11ea-91f0-35d17ea94138.gif)

Kinks:

- We will also disable "show card" actions in Adaptive Cards
- To be fair, we would like to able to disable all legacy cards too, this includes hero card, audio card, video card, etc.
   - Only buttons in all legacy cards should be disabled
   - Animation, audio and video cannot be disabled (HTML also does not have `disabled` attribute on `<audio>`/`<video>` tag)
- Adaptive Cards
   - When a button is clicked and its value is submitted, the button don't highlight itself. This is by design of Adaptive Cards
   - The sample code hacked the card by setting `action.isPrimary` to `true` on submit

One primary goal in this sample, make sure keyboard focus is set correctly after buttons are disabled.

The sample code roughly looks like this and it requires the next version of Web Chat.

```js
const attachmentMiddleware = () => next => ({ activity, attachment, ...others }) => {
  const { activities } = store.getState();
  const messageActivities = activities.filter(activity => activity.type === 'message');
  const recentBotMessage = messageActivities.pop() === activity;

  switch (attachment.contentType) {
    case 'application/vnd.microsoft.card.adaptive':
      return <AdaptiveCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.animation':
      return <AnimationCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.audio':
      return <AudioCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.hero':
      return <HeroCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.oauth':
      return <OAuthCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.receipt':
      return <ReceiptCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.signin':
      return <SignInCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.thumbnail':
      return <ThumbnailCardContent content={attachment.content} disabled={!recentBotMessage} />;

    case 'application/vnd.microsoft.card.video':
      return <VideoCardContent content={attachment.content} disabled={!recentBotMessage} />;

    default:
      return next({ activity, attachment, ...others });
  }
};

const cardActionMiddleware = () => next => ({ cardAction, target, ...others }) => {
  target.isPrimary = true;

  return next({ cardAction, target, ...others });
};

// let styleSet = createStyleSet({ hideSendBox: true });
let styleSet = createStyleSet();

styleSet = {
  ...styleSet,
  adaptiveCardRenderer: {
    ...styleSet.adaptiveCardRenderer,
    '& .ac-pushButton:disabled:not(.primary)': { backgroundColor: '#F7F7F7', color: '#717171' },
    '& .ac-pushButton.primary:disabled': { backgroundColor: '#0078D7', color: 'White' }
  }
};

window.ReactDOM.render(
  <ReactWebChat
    attachmentMiddleware={attachmentMiddleware}
    cardActionMiddleware={cardActionMiddleware}
    directLine={window.WebChat.createDirectLine({ token })}
    store={store}
    styleSet={styleSet}
  />,
  document.getElementById('webchat')
);
```

**Comment by compulim** [comment]
Working on the tab order of "New message" button after the AC card is disabled. It's not trivial as we are not allowed to touch `tabindex`. We can only influence by reordering DOM nodes.

`tabindex` is global and introduce pollutions. tl;dr we are component, not app, so we don't own the global environment, we must not pollute it. One reason why components are much harder to write than apps.

p.s. love to see my customers are so excited when I am fixing bugs. The little 🚀 made my day.

**Comment by BeeMaia** [comment]
Hi compulim,

thank you very much for your work.
I have a question, is it possible to disable only some type of card action?
For example, if I want to keep enabled OpenUrl action because it doesn't change the flow.

Thanks a lot,
Andrea

**Comment by compulim** [comment]
@BeeMaia it will be quite difficult to do it today. Will you consider using Markdown to present an hyperlink to the user?

Are you rendering a hero card or Adaptive Cards?

**Comment by compulim** [comment]
I am still working on the tab order and completed the code to reorder DOM node. Scroll-to-bottom is difficult. 😑

### Good flow

![recording (2)](https://user-images.githubusercontent.com/1622400/81293439-3292f100-9022-11ea-9f0f-43c6b7029c4d.gif)

### Bad flow

The `New message` button didn't go away. I am working on this now. Chrome didn't fire `scroll` event when a new element is added, and the scroll-to-bottom component didn't update its saved `scrollHeight` value.

![recording (3)](https://user-images.githubusercontent.com/1622400/81293672-8b628980-9022-11ea-8952-6ce6e3c6c73e.gif)

**Comment by BeeMaia** [comment]
> 
> 
> @BeeMaia it will be quite difficult to do it today. Will you consider using Markdown to present an hyperlink to the user?
> 
> Are you rendering a hero card or Adaptive Cards?

@compulim we are using hero card and adaptive cards.

**Comment by compulim** [comment]
Still working on focus management, understanding cross browser behavioral differences to see if this sample will work on daily UX.

In the animation below, we will focus on the element but not clicking on them. Yellow indicate what elements has the focus. And we want to see:

- What element will get focused after the current one is disabled
- Which one will get focused after pressing <kbd>TAB</kbd>

Looks like we should disable only the non-selected buttons, and leave the button clicked continue to be enabled and focusable.

### Chrome 👍🏻

Chrome did remember the focus on the disabled element. So <kbd>TAB</kbd> will go to the next focusable element after the disabled element.

![recording (6)](https://user-images.githubusercontent.com/1622400/81375648-d5954a80-90b6-11ea-854d-df7a8491c03f.gif)

### Firefox 👎🏻

Firefox did not remember the focus of the disabled element. <kbd>TAB</kbd> will go to the first element in the parent container of the disabled element.

Also note that Firefox can <kbd>TAB</kbd> to the scroll view if it does not have `tabindex="-1"`. Scroll view in other browsers are not focusable.

![recording (9)](https://user-images.githubusercontent.com/1622400/81376504-87814680-90b8-11ea-8b45-8106fd011037.gif)

### Edge UWP 👎🏻

Edge UWP is similar to Firefox, did not remember the focus of the disabled element. But <kbd>TAB</kbd> will go to first focusable element after document root.

![recording (8)](https://user-images.githubusercontent.com/1622400/81375966-6e2bca80-90b7-11ea-951e-caaf82681ce5.gif)

**Comment by compulim** [comment]
Going to finish the day here. I think we go down the wrong path. In accessibility, disabled button should still be able to <kbd>TAB</kbd> to it, shouldn't lose focus.

**Comment by sw353552** [comment]
I would also upvote for @BeeMaia's idea not to disable OpenURL buttons in the adaptive card.

**Comment by anandk95** [comment]
I understood and got the solution. But can you explain how to do the same thing with Angular9, I'm tring to achive the same thing with Angular9 but getting nowhere.

**Comment by corinagum** [comment]
Update 05.l (L) sample

**Comment by arijitoptisol123** [comment]
is disabling the adaptive card buttons possible in python botframework? Please reply it's urgent.

**Comment by corinagum** [comment]
yes. Bot language does not affect the client behavior. Please use sample provided above.

**Comment by jayarau** [comment]
Hi @compulim, We are referring above sample link to disable adaptive card. But we are getting disabled card for recent message. and hence not able to fill details. 

Screenshot for reference:
![image](https://user-images.githubusercontent.com/73291456/119975419-7365fb00-bfd3-11eb-8584-f1be8c71b79c.png)

I have tried providing disabled={recentBotMessage} in element but after doing that card is not getting disabled.

 ```
<Components.AdaptiveCardContent actionPerformedClassName="card__action--performed"
                content={attachment.content}
                disabled={recentBotMessage}
                />
```

**Comment by Kaiqb** [comment]
@jayarau - In the sample, line 115 we have `disabled={!recentBotMessage}` but in your example you don't have the (!) in front of recentMessage. Could you recheck?

**Comment by jayarau** [comment]
Hi @Kaiqb, Yes we have tried with  disabled={!recentBotMessage} initially, but with that we are getting disabled card even for recent message and hence not able to fill card and submit it. As shown in screenshot above.

**Comment by jayarau** [comment]
Hi @compulim / @Kaiqb , do we have any update on this?

**Comment by compulim** [comment]
For everyone who is waiting for this, we will be in planning mode soon. We know this is what our customer want: using AC as an *one-off* input.

On the other hand, the root cause is in the AC library, https://github.com/microsoft/AdaptiveCards/issues/1512.

Will be great if everyone here could help sending feedbacks to the root cause to get it solved.

**Comment by jayarau** [comment]
> Hi @compulim, We are referring above sample link to disable adaptive card. But we are getting disabled card for recent message. and hence not able to fill details.
> botframework version we are using : 4.11
> 
> Screenshot for reference:
> ![image](https://user-images.githubusercontent.com/73291456/119975419-7365fb00-bfd3-11eb-8584-f1be8c71b79c.png)
> 
> I have tried providing disabled={recentBotMessage} in element but after doing that card is not getting disabled.
> 
> ```
> <Components.AdaptiveCardContent actionPerformedClassName="card__action--performed"
>                content={attachment.content}
>                disabled={recentBotMessage}
>                />
> ```
> 
> is anyone facing similar issue? or can help with this.

Update on this:
I am able to disable adaptive cards once action taken.
Solution:
function check(act){return (act.type === 'message'&&act.hasOwnProperty('attachments'))};
var { activities } = this.store.getState();
var messageActivities=activities.filter(check)
var recentBotMessage = messageActivities.pop() === activity;

return (     
                <Components.AdaptiveCardContent actionPerformedClassName="card__action--performed"
                content={attachment.content}
                disabled={!recentBotMessage}/>      
                );

**Comment by cobbie** [comment]
+1. How could this be implemented via Bot framework composer?

**Comment by smelgar-sage** [comment]
> +1. How could this be implemented via Bot framework composer?

Any updates about this?
