### ISSUE TITLE
Adding custom data to channel data.

### ISSUE THREAD

**Issue by ssong3k** [Microsoft/BotFramework-WebChat#1430]
Since the webchat has migrated to V4 I have not found any documentation to add custom data into messages using the embedded webchat.

My sample originally used the following code.

    const speechOptions = {
        speechRecognizer: new BotChat.Speech.BrowserSpeechRecognizer(),
        speechSynthesizer: new BotChat.Speech.BrowserSpeechSynthesizer()
    }

    var dl = new BotChat.DirectLine({ secret: 'YOUR_SECRET_HERE' });

    BotChat.App({
        botConnection: Object.assign({}, dl, {
            postActivity: activity => {
                var newActivity = Object.assign({}, activity, { ChannelData: { 'Channel': 'WebChat'} });
                return dl.postActivity(newActivity);
            }
        }),
        user: { id: 'userid' },
        bot: { id: 'botid' },
        resize: 'window',
        speechOptions: speechOptions
    }, document.getElementById("bot"));

Is there anyway to do something similar along the above line for V4?

**Comment by compulim** [comment]
We are building a sample and it is currently in PR #1331, got approved but need time to merge it in.

In short, we updated a line of production code to make the sample looks smoother. It should be in within days. Stay tuned!

**Comment by ssong3k** [comment]
Ah that's good to know I'm currently updating some older demos to match the new framework. Can I also ask if there is anyway to preserve the layout of the V3 UI? The V4 embedded webchat with window.WebChat.RenderWebChat does not having the input box fixed to the bottom of the div. I've been playing with CSS but it seems the way the divs are nested makes my approach much more difficult.

To give an idea of what I mean.
![v3](https://user-images.githubusercontent.com/10621422/49407907-7a1f9a00-f717-11e8-8501-48ee81bad197.png)

![v4](https://user-images.githubusercontent.com/10621422/49407909-7be95d80-f717-11e8-8d3e-359ee50451b4.png)

**Comment by ssong3k** [comment]
That should be a separate issue.
