### ISSUE TITLE
send failed: Missing 'Activity.From.Name' field

### ISSUE THREAD

**Issue by anvad** [Microsoft/BotFramework-WebChat#1436]
Looks like something changed at https://directline.botframework.com/v3/directline/conversations

I've been testing the BotFramework-WebChat over the last few days and I've suddenly started seeing `400 Bad Request` messages from that URL, with the body of the response containing the following json:
```JSON
{
    "error": {
        "code": "MissingProperty",
        "message": "Missing 'Activity.From.Name' field"
    }
}
```

Inspecting the request body shows that indeed the `From.Name` field is missing:
```json
{
    "text": "hi",
    "textFormat": "plain",
    "type": "message",
    "channelData": {
        "clientActivityID": "15439544427360.i778ojzgv5go"
    },
    "channelId": "webchat",
    "from": {
        "id": "default-user",
        "role": "user"
    },
    "locale": "en-US",
    "timestamp": "2018-12-04T20:14:25.533Z",
    "entities": [
        {
        "requiresBotState": true,
        "supportsListening": true,
        "supportsTts": true,
        "type": "ClientCapabilities"
        }
    ]
}
```
Looking at the code at GitHub- https://github.com/Microsoft/BotFramework-WebChat/blob/0d7107fc4076d2be065a0bc50539124ed486f9a8/packages/core/src/sagas/postActivitySaga.js#L56-L59

...shows that the Name field is not appended.

We can even reproduce this error from base code with no changes:
1. `cd c:\code`
2. `git clone https://github.com/Microsoft/BotFramework-WebChat.git`
3. `cd BotFramework-WebChat\samples\integrate-with-react\`
4. `npx serve`
5. Opened browser and navigated to url mentioned by `npx serve` command.
6. Tried to send message `help` and got the "Send failed, retry" message.

Nothing changed in the webchat client code, so I suspect something changed in the server side at https://directline.botframework.com/v3/directline/conversations

**Comment by compulim** [comment]
Just talked to our platform devs, there is an issue on the platform side and it's being addressed now. It's affecting West US data center for now.

I will forward this ticket to them and help you to track it here.

**Comment by compulim** [comment]
Forwarded.

I think the problem will be fixed within a few hours.

FYI, I hit by the same bug right now too. If you are in super urgent, please build your own Web Chat repo and workaround it by modifying `postActivitySaga.js:59`, then add `from: { ..., name: 'John Doe' }`.

This workaround is temporary, only needed for the next few hours until the get it fixed on platform side.

**Comment by compulim** [comment]
It's because Test in Web Chat on Azure Portal is using old Web Chat.

In Web Chat v4, since we don't show the user name (replaced with avatar initials and a timestamp from name), we removed user name from options. And since user name is remove from Web Chat options, we also don't "post activity" with a user name anymore.

![image](https://user-images.githubusercontent.com/1622400/49477578-30e05080-f7d2-11e8-86fc-764bbe04fa36.png)

Looks like it's fixed now. I am closing this bug.

Thanks for reporting.
