### ISSUE TITLE
Add Switch in Embedded WebChat control so user can pick websocket or polling to get conversation

### ISSUE THREAD

**Issue by JasonXuMSCSS** [Microsoft/BotFramework-WebChat#1443]
Currently, when users use embedded Webchat control as client, there is no control that whether Websocket or polling will be used. For each Bot, it is randomly picked on the Channel service side if webSocket or Polling will be used for that Bot. And it sticks once it is chosen.
This caused problem when Websocket or polling is needed for certain features. For example, typing activity requires Websocket. But if polling is picked on DirectLine service side, Typing activity will not work since no Websocket is used.

It is better to add a switch in embedded WebChat control to let use to choose which one to use.

**Comment by corinagum** [comment]
An update is planned for DirectLineJS that will enable automatic protocol fallback (WebSocket, then REST API) with manual override when users don't wish to use WebSocket. That issue can be tracked here: https://github.com/Microsoft/BotFramework-DirectLineJS/issues/88
