### ISSUE TITLE
Demonstrations listed on this site now returning 404

### ISSUE THREAD

**Issue by JerryMWeeks** [Microsoft/BotFramework-WebChat#1448]
One the 30th November these were working perfectly. 
But for example:
https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/minimize-mode
is now returning the GitHub 404 page. 
The same with 
https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/full-bundle/
The above URL is found in this text on the main page: 
See a working sample with full Web Chat bundle here.
Do the URLs need to be updated to:
https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/
and
https://microsoft.github.io/BotFramework-WebChat/1.a.getting-started-full-bundle/
etc?

**Comment by compulim** [comment]
Yes, they need to be updated. Where do you found the broken links? I thought we have changed them all but looks like we didn't.

**Comment by corinagum** [comment]
@JerryMWeeks Thank you for noting the oversight! Links on the README.md have now been fixed. :)
