### ISSUE TITLE
Web chat integration not working in IE

### ISSUE THREAD

**Issue by vaatsalya** [Microsoft/BotFramework-WebChat#1454]
I am developing a bot using sdk4 and nodejs. I wanted to integrate my bot in a webpage. So, I am using  webchat directline to integrate it into my webpage(index.html). I referred the sample [here ]([url](https://github.com/Microsoft/BotFramework-WebChat/blob/master/SAMPLES.md))for directline. In the sample it is referring to the script file shown below 
`<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>` .  I have embedded my direct line secret inorder to render the webchat. `window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ secret: 'YOUR_BOT_SECRET' })` . In chrome webchat is getting rendered fine but in ie webchat is not rendering. Also I tried calling this html from an iframe of another html page(i.e., my webpage index.html) as shown in the below code 
`<iframe src="webchat.html"/>`, it is working fine in chrome browser but not working in IE. Can anyone help on this issue? Is there any script file specific to IE?

**Comment by compulim** [comment]
You will need to use the ES5 bundle, which is named `webchat-es5.js`.

ES5 polyfills is required for IE11 because we are using modern features in JavaScript. We moved polyfills out to a separate bundle to reduce the file size. We believe most people are running modern browsers, but in case you want to run it under IE11, we included the ES5 polyfills.

Don't worry, IE11 is still supported. 😉

**Comment by vaatsalya** [comment]
@compulim  I have tried using botchat-es5.js available [here](https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js) It didn't work. Can you please provide me the link to webchat-es5.js so that I will try the way you suggested.

**Comment by corinagum** [comment]
@vaatsalya It looks like you're using Web Chat v4. In that case, you will need to use the updated v4 version of the polyfill: ```https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js```. 
Please refer to [es-5 bundle](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/1.b.getting-started-es5-bundle) to see how it is used. Hope that helps!

**Comment by vinayjayaram** [comment]
@corinagum i tried using the above es5.js file, Dint work for me on IE, It is still showing error while loading

**Comment by corinagum** [comment]
@vinayjayaram Could you share what your error is? It looks like our demo is functional.

**Comment by RamPrasadMeenavalli** [comment]
https://microsoft.github.io/BotFramework-WebChat/15.a.backchannel-piggyback-on-outgoing-activities/
This is not working in IE11
Any pointers to get this working.

**Comment by corinagum** [comment]
@RamPrasadMeenavalli That sample will not work on IE11 by default because it is not using the es5 polyfill. To test it in IE11, please change the CDN package being used in the `index.html` to the es5 polyfill. :)
