### ISSUE TITLE
WebChat new version (4.1.0) - upgrade

### ISSUE THREAD

**Issue by sreeharikm** [microsoft/BotFramework-WebChat#1455]
Hi,
I am using older version (v0.10.2) of web chat currently. Planning to do upgrade, mainly for the new features like text speech etc. Is there any easy way to upgrade the typescript based version into js based one? We have many customization in the ts files along with some additional files. Please share if there is any upgrade guides.

Thanks
Sreehari

**Comment by compulim** [comment]
If you forked our code and modified it, unfortunately, there are no ways to upgrade. And `0.10.2` looks pretty dated, it was released on 2017 March 8.

What kind of cool customizations did you do? We can point you to some of the customizations samples we did.
