### ISSUE TITLE
Cognitive speech service (speech to text) remove 15 second limitation

### ISSUE THREAD

**Issue by jawand** [Microsoft/BotFramework-WebChat#1457]
@compulim 

Currently there is 15 seconds limitation while recording and getting results from speech cognitive services.
Can we remove this limit ?

As per the documentation from Cognitive Service Team [need to use startcontinuousrecognitionasync method](https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/speechrecognizer?view=azure-node-latest#startcontinuousrecognitionasync-------void---e--string-----void-). 

Do you guys have any plans for this to include ?

Thanks

**Comment by compulim** [comment]
There are two modes in Cognitive Services, "recognizeOnceAsync" is called interactive mode, and "startContinouousRecognitionAsync" is called dictation mode.

Unfortunately, the dictation mode is buggy in the current SDK (1.1). We are waiting for a fix to unblock us for this work. The work is being tracked in this bug right now, https://github.com/Microsoft/BotFramework-WebChat/issues/1400.
