### ISSUE TITLE
Tap action on Hero card with the latest React web chat

### ISSUE THREAD

**Issue by vmunnuru** [Microsoft/BotFramework-WebChat#1458]
Do we have any option to make hero cards clickable, 
ex: location cards(hero cards) which resides in carousel.

**Comment by compulim** [comment]
Hero card is clickable. For example, you can set it to open a new URL when the user tap on it.

Please refer to the `tap` property in this article to see how it works, https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#herocard-object.
