### ISSUE TITLE
Web site data not sending to the bot framework for conversational update

### ISSUE THREAD

**Issue by deva96** [Microsoft/BotFramework-WebChat#1464]
Hey I am building my chat bot using bot framework v4
I am passing user data from the website by passing variables like this from web chat
**user: { id: model.id, name: model.userName, token:model.token,url:model.url, source: "SP"},**
The issue is i am not able to get this data before user sending a message.
for example:
in bot framework for (message.type == conversational update) I am sending welcome message.There i am not able to welcome the user using his name.
But i can use this name after user sends some query like for **hi!** I am able to send **hi username** welcome to our site.

**Comment by corinagum** [comment]
This is a known issue, thank you for sharing with us! A fix is already in the works. You can track that progress in #1286.
