### ISSUE TITLE
jQuery interact with WebChat

### ISSUE THREAD

**Issue by undead1102** [Microsoft/BotFramework-WebChat#1465]
I embed webchat.js into my page, when I use jquery to set value in messagebox like this:
`$("input[aria-label='Type your message']").val("test")`
There is no any response when I click send button.
How can I achieve this?
![image](https://user-images.githubusercontent.com/10411914/49786764-bd33cb80-fd1c-11e8-8128-092b582256e0.png)

**Comment by corinagum** [comment]
It looks like your jQuery is making DOM changes to the value but not emitting a change event.

We want to write a sample that will teach users how to programmatically send content to the bot, but unfortunately that sample doesn't exist yet. We'll use this issue to track the progress of that sample. :) 

In the meantime, you can drill into this sample: [redux actions](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/11.customization-redux-actions) to learn how to dispatch messages to the Redux store.

**Comment by undead1102** [comment]
@corinagum Thank you for your response, In fact I am not familiar with redux and react , I will try the way you mentioned. 
Hope the sample will be come soon.

**Comment by compulim** [comment]
@undead1102 we are cooking the sample and it is in PR #1568.
