### ISSUE TITLE
Will webchat v4.1 be compatible with botbuilder NodeJS SDK v3 ??

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotFramework-WebChat#1492]

**Comment by corinagum** [comment]
@stevengum do you have any insight here?

**Comment by stevengum** [comment]
Yes, the version of WebChat is not tied to the functionality within the BotBuilder SDKs, so v3 Node.js SDK will work with WebChat v4.1.

**Comment by bhushanvadgave** [comment]
Thank you.
