### ISSUE TITLE
how to optimize slider revolution of bot framework v4 C#

### ISSUE THREAD

**Issue by 1249682741** [Microsoft/BotFramework-WebChat#1502]
I use Card List to show the information.
Here is my code
````
List<Attachment> aList = new List<Attachment>();
for (int i = 0; i < 10; i++)
{
    HeroCard card = new HeroCard();
    card.Text = i.ToString();
    aList.Add(card.ToAttachment());
}
var reply = turnContext.Activity.CreateReply();
reply.AttachmentLayout = "carousel";
reply.Attachments = aList;
await turnContext.SendActivityAsync(reply, cancellationToken);
````
When i click the left/right button quickly, the slider will show like this.It cannot show the infomation completed
![image](https://user-images.githubusercontent.com/31991577/49994222-dca05200-ffc3-11e8-8023-76d4c7047534.png)

When i click the left/right button slowly.It can show the infomation completed
![image](https://user-images.githubusercontent.com/31991577/49994315-212bed80-ffc4-11e8-9f21-be1e68b96a42.png)

how to optimize slider revolution of bot framework
Thanks in advance

**Comment by compulim** [comment]
We updated the carousel flipper in v4 and it fixed most of quirks found in the older carousel.

Please update your Web Chat to v4 to get the fix.
