### ISSUE TITLE
Authenticate user in the bot using hosting page authentication

### ISSUE THREAD

**Issue by pedrosalider** [Microsoft/BotFramework-WebChat#1503]
I'm embedding a web bot in a page that requires authentication and I want to authenticate the bot using the hosting page authentication. Is there any way to do that?
At the moment, I need to login twice, one to authenticate the hosting page and another to authenticate the bot (I'm using OAuth Cards) and it doesn't seems good to me. Any help is welcome.

**Comment by compulim** [comment]
There are multiple ways to do that, I am outlining possibilities here.

Depends on your scenarios, if your bot is available for anonymous users, you also need to consider if you will allow the user to authenticate thru the bot, and send the auth token back to your page.

## Pre-authenticate with Direct Line user ID

As you know how to do OAuth cards, I would assume you are using a token server to distribute Direct Line access token.

On your server side, when you generate access token from your Direct Line secret, you can embed a user ID into the access token, the work is detailed in [this article](https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/). The user ID must prefixed with `dl_`.

So when you generate the token, you can associate the Direct Line user ID with your user database. So when the bot receives an activity from Web Chat, you can automatically load his profile from the database.

## Using your existing HTTP cookie

You can piggyback your HTTP cookie to every activity sent from Web Chat to your bot. If your HTTP cookie is accessible by JavaScript, you can grab it out and piggyback it into the outgoing activity using [this sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.backchannel-piggyback-on-outgoing-activities).

Note that some cookies are marked as `httponly` and cannot be accessible via JavaScript.

**Comment by pedrosalider** [comment]
Hi @compulim, thank you for your quick answer but unfortunately both options don't work for me, because I haven't access to the http cookie and I'm getting the direct line token via an ajax call to an api that is running in a different context than where I'm running the webchat control. 
At the moment, I'm looking now for a way to automatically trigger the login without clicking "Sign in" in the OAuth card. 
Do you think it is possible?

**Comment by compulim** [comment]
In Web Chat v4, there are ways to listen to incoming activities (from bot) in JavaScript. And then you can write some code in that event listener to help you clicking on the "Sign in" button.

But one thing you need to look at is, if the "Sign in" button open a new window, browsers may block it (no programmatic `window.open`).

We are cooking a sample #1516 that will help you to listen for incoming activities.
