### ISSUE TITLE
[Question] OAuth card customization

### ISSUE THREAD

**Issue by blrchen** [Microsoft/BotFramework-WebChat#1504]
I have two questions for web chat OAuth card

1. When clicking to sign in, user will redirected to a new browser tab. Can this be changed to small pop-up window instead?
2. After user clicks ‘accept’, user will be asked to enter a validation code in the chat window to continue. Is this also a necessary step? Any way to make it more concise?

**Comment by corinagum** [comment]
1. This will need a window.open ponyfill, which is not available yet. Please track this in #368. You will need to adjust how Web Chat handles URLs differently with the ponyfill.
2. Please refer to the comments on https://github.com/Microsoft/BotBuilder/issues/4632#issuecomment-441957719 to create a smoother experience without the validation code.
