### ISSUE TITLE
Clearing webchat window

### ISSUE THREAD

**Issue by dpollock** [Microsoft/BotFramework-WebChat#1505]
I'm needing to clear the messages out of the chatbot window (e.g. when the user logs out of our app). Is there an easy way to do this in v4?

I'm not needing to delete or update the activities, but just visually clear the messages.

**Comment by corinagum** [comment]
This is not available right now, so we will use this issue to track this feature. 

Right now, DirectLineJS does not support ending a conversation. This would have to be added on after DLJS undergoes a series of fixes, which can be tracked [here](https://github.com/Microsoft/BotFramework-DirectLineJS/issues/124).

After that, we will need @DesignPolice @mewa1024 to provide the design specs for how to handle a logout, which includes either resetting the conversation or removing the ability for new activities to be sent (disabled textbox, send button, etc).

**Comment by dpollock** [comment]
In my case - I'm needing to clear the chatbot visually. I'm not worried about ending the conversation. 

Right now - I'm doing this:

```js
const messages: any = document.querySelector("#bot").querySelectorAll('.content');
    for (var i = 0; i < messages.length; ++i) {
      messages[i].closest('li').textContent = '';
    }
```

Ugly hack, but works.  Basically find all the 'content' div's and then find their parent's <li> and clear the html.

**Comment by compulim** [comment]
@dpollock Do you think you can remove the DOM of Web Chat and re-instantiate a new one?

If you are using Web Chat in React, the unloading should be pretty clean (except DirectLineJS part, which we are fixing). But if you are on JavaScript, I think we need some work to make sure Web Chat can be cleanly unloaded.

If you cannot re-instantiate Web Chat or the UX is not feel right to you (flashy, losing some context, etc), could you tell us a bit more about it? We would love to know more about your scenarios to better suit Web Chat with customer-focused feature.

**Comment by corinagum** [comment]
We're going to combine this with #1293 in a single Sample.
