### ISSUE TITLE
Sample: Non-magic code flow for OAuth

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#1507]
Please refer to @compulim's comments here: https://github.com/Microsoft/BotBuilder/issues/4632#issuecomment-441957719

**Comment by blrchen** [comment]
Could you please share when will this sample be available?

**Comment by corinagum** [comment]
Unfortunately we don't have a timeline for this sample. We will be sure to update this issue with more information as it becomes available. Thanks for your patience! :)

**Comment by compulim** [comment]
@blrchen you can look at #1218 (which I accidentally closed), and the comment in [BotBuilder#4632](https://github.com/Microsoft/BotBuilder/issues/4632#issuecomment-441957719). It should explain how to prevent magic code from showing up.

**Comment by tdurnford** [comment]
Closing as https://github.com/microsoft/BotFramework-WebChat/issues/2343 is being used to track this issue
