### ISSUE TITLE
Localization language Bot Framework v4 C#

### ISSUE THREAD

**Issue by 1249682741** [Microsoft/BotFramework-WebChat#1508]
first of all, sorry because my englist is poor. so i hope you can understand what i say.
my code

````
ResourceManager rm =new ResourceManager("Resource.en-US.resx", Assembly.GetExecutingAssembly());
rm.GetString(strName);
````

when i debug it report:

```
{System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Resource.resx.resources" was correctly embedded or linked into assembly "BasicBot" at compile time, or that all the satellite assemblies required are loadable and fully signed.
```

What should I do to implement localized language?
Thanks in advance!

(Edited by @compulim for code formatting)

**Comment by compulim** [comment]
@1249682741 which SDK version are you using? It looks like a question on Bot Builder SDK.

**Comment by compulim** [comment]
@1249682741 Sorry missed your title it is a v4 issue. I will find the right guy to help you on this one.

**Comment by daveta** [comment]
Hi @1249682741 : You might want to take a look at [the enterprise sample](https://github.com/Microsoft/AI/tree/master/templates/Enterprise-Template/src/csharp/EnterpriseBotSample).  In the future, you might want to log these in stackoverflow.com.  If you have specific bugs for C#, please log in https://github.com/Microsoft/botbuilder-dotnet.
Thanks!
