### ISSUE TITLE
Embedding a "Title" in Markdown Link does not render correctly in Web Chat window

### ISSUE THREAD

**Issue by vbhatt** [Microsoft/BotFramework-WebChat#1512]
The WebChat window should render the "Title" correctly for Accessibility (ADA) compliance. See the example below.
[I'm an inline-style link with title](https://stackoverflow.com/help/how-to-ask "How to Home page")  does not get rendered correctly in Webchat window as the url get's mangled to create a bad link.

**Comment by compulim** [comment]
We are using Markdown-It and copying your Markdown to https://markdown-it.github.io/ looks good to me.

If `title` doesn't shows up, looks like there is a bug in Web Chat and we need to fix that asap.

**Comment by compulim** [comment]
@vbhatt Really thanks for your report.

We really love to make Web Chat accessible to all users, we have an accessibility push going out probably next week. If you think there are potential areas for improvements, please do let us know.
