### ISSUE TITLE
Speech: Custom Speech (CRIS)

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#1513]
This is the work item for additional features from Speech Services. The original feature on-par work is #1336. Expanding #1400 into multiple issues.

- [ ] Custom Speech

**Comment by corinagum** [comment]
This is pending an update from Speech Services, which according to their timeline will be available earliest by end of January, and latest by late February. This issue will need to be implemented before Speech UI changes are added to the Emulator (where user chooses the BF token or using their own), but otherwise I recommend we punt this to 4.4. @cwhitten, thoughts?

**Comment by cwhitten** [comment]
What update are we expecting from Speech Services?

**Comment by compulim** [comment]
We have few things to work on Speech Services:
- ✔ CRIS support, I think we have everything
- ✔ Voice font support, I think we have everything
- ✔ Package from NPM, we have it
- ❌ Grammar reference ID, pending from Speech team, earliest late Jan, latest late Feb
- ❌ Biased word list, pending, same schedule

The question is, should we start the work right now and do 2 releases, or everything in a single shot.

**Comment by cwhitten** [comment]
Ok. Let's pause for now and re-assess on the beginning on February.
