### ISSUE TITLE
Need offline UI: Meta-retry button

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-WebChat#1522]
Original issue is #135, which has been split into multiple issues. 

When reconnecting to the bot (after the connection has been interrupted), do we need to have a "meta-retry" button? The user can click on it and it will "retry" on all failed-to-send activities.

- Is this a feature that we need? (discuss!)
  - If yes, we will need:
    - [ ] Design specs
    - [ ] Acceptance criteria
    - [ ] T-Shirt Sizing, Priority (marked as P2 for now, please update as more information is available)
  - If no, we can close this bug.

**Comment by mewa1024** [comment]
@corinagum Again, sorry I didn't see this bug. Can we follow the instructions in #1521? I think you have designs from @DesignPolice, yeah? 

(unassigning myself)

**Comment by corinagum** [comment]
@mewa1024 sorry for the late reply - I don't have an example of a meta retry button. :D

If both of you agree this is not needed, I'm happy to close the issue!

**Comment by corinagum** [comment]
Closing this issue - there doesn't seem to be much interest in an implementation. :) We can always reopen if folks have a change of heart.
