### ISSUE TITLE
Need offline UI: Connection interrupted

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-WebChat#1523]
Original issue is #135, which has been split into multiple issues. 

We need UI specs and implementation for:
- When the bot connection has been interrupted.
  - Immediate interruption (including immediate reconnect?)
  - Non-immediate interruption (up to 2 mins)

### What we need
- [x] Design specs
- [x] Acceptance criteria
- [x] T-shirt sizing

-	Grey text
-	With spinner (spinner will be grey, small, size of icon in previous Offline UI items)
-	Text proposal: “Network interruption occurred. Reconnecting…”
-	This will show up as soon as an interruption has occurred, and either disappear (reconnect successful) or switch to “Web Chat is taking longer than usual to connect” after 15 seconds. (Will eventually turn to “Connection failed” if it fails completely)

**Comment by mewa1024** [comment]
@corinagum @DesignPolice @compulim sorry, I don't know why I didn't see this bug before. Can we use the same message design as in #1521 but instead of "Web Chat is unable to connect." say "Connection interrupted." ? Same rules about force retry apply as in that bug.

(unassigning myself)

**Comment by corinagum** [comment]
Tagged wrong issue :(
