### ISSUE TITLE
Need offline UI: Connecting for the first time

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-WebChat#1524]
Original issue is #135, which has been split into multiple issues. 

We need UI specs and implementation for:
- When connecting for the first time, before our "usual" threshold. Note in #1521: the 'longer than usual' threshold has not yet been defined. 

For Edge on accessibility, we hear "page loading", followed by "still loading".

### What we need
- [ ] Design specs
- [ ] Acceptance criteria
- [ ] T-shirt sizing

**Comment by mewa1024** [comment]
@compulim @corinagum @DesignPolice Can we do use the same message UI as in #1521 but change the message to "Connecting..." while Web Chat is trying to connect and then disppear when the connection is successful?
