### ISSUE TITLE
npm build fails at "npm run bootstrap"

### ISSUE THREAD

**Issue by sanoorvishwa** [Microsoft/BotFramework-WebChat#1543]

**Comment by sanoorvishwa** [comment]
I did a fresh clone and ran `npm install` This works fine now.

```
D:\Users\vishwanatha_s\Desktop\BotWebChat410\BotFramework-WebChat-master>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1031 packages from 547 contributors and audited 58567 packages in 153.329s
found 0 vulnerabilities

```However, the next command `npm run bootstrap` fails.

```
C:\Users\vishwanatha_s\Desktop\BotWebChat410\BotFramework-WebChat-master>npm run
 bootstrap

> botframework-webchat-root@4.2.1-0 bootstrap C:\Users\vishwanatha_s\Desktop\Bot
WebChat410\BotFramework-WebChat-master
> lerna bootstrap

lerna notice cli v3.4.0
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies

```
This runs for long time and ends up in error and pages of error messages.

```
npm WARN tar ENOENT: no such file or directory, open 'D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\rxjs-f5562b09\_esm5\internal\operators\map.js'
npm ERR! path D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\typescript-af58ea21\lib\tsc.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\typescript-af58ea21\lib\tsc.js'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\typescript-af58ea21\lib\tsc.js']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\typescript-af58ea21\lib\tsc.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'D:\\PM_Activity\\AVNET\\WebChatSource\\WebChatSourcePhase2-Dev-Upgrade\\BotFramework-WebChat-master\\packages\\core\\node_modules\\.staging\\typescript-af58ea21\\lib\\tsc.js' },
npm ERR!   stack:
npm ERR!    "Error: EPERM: operation not permitted, unlink 'D:\\PM_Activity\\AVNET\\WebChatSource\\WebChatSourcePhase2-Dev-Upgrade\\BotFramework-WebChat-master\\packages\\core\\node_modules\\.staging\\typescript-af58ea21\\lib\\tsc.js'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'D:\\PM_Activity\\AVNET\\WebChatSource\\WebChatSourcePhase2-Dev-Upgrade\\BotFramework-WebChat-master\\packages\\core\\node_modules\\.staging\\typescript-af58ea21\\lib\\tsc.js',
npm ERR!   parent: 'botframework-webchat-core' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm WARN tar ENOENT: no such file or directory, open 'D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\rxjs-f5562b09\_esm5\internal\operators\map.js.map'
npm WARN tar ENOENT: no such file or directory, open 'D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\core\node_modules\.staging\rxjs-f5562b09\_esm5\internal\operators\mapTo.js'

```
This is snippet from the error log
I also tried running npm command as system admin and still no luck.
Any insights?
Thanks in advance
Vishwa

**Comment by sanoorvishwa** [comment]
Additional messages.
```
lerna ERR! npm install exited 4294963248 in 'botframework-webchat-core'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963248
npm ERR! botframework-webchat-root@4.2.1-0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 4294963248
npm ERR!
npm ERR! Failed at the botframework-webchat-root@4.2.1-0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vishwanatha_s\AppData\Roaming\npm-cache\_logs\2018-12-26T17_23_45_851Z-debug.log
```

**Comment by compulim** [comment]
The error "code EPERM" on "unlink" means NPM got access denied when deleting (a.k.a. unlinking) a file.

Few things to check:
- Can you see if you are opening the project root in any IDE?
- Do you think you are using 3rd party antivirus that would lock the file for prolonged time? We use Windows Defender only (which is built into Windows)
- We are using NPM 6

On our machine (i7 + SSD), it would take about 3-5 minutes. `npm run bootstrap` actually do `npm install` on multiple folders, so it takes time to complete.

p.s. we build dev bits mostly on Windows, and production bits on Linux (on Travis CI), so I am pretty sure we are cross platform friendly.

**Comment by sanoorvishwa** [comment]
Hi Compulim,
Thanks a lot for the quick response.
I no more get the errors i got yesterday on `npm run bootstrap` command. I neither did make any system changes nor access related changes.

I was running the command under root folder in VS code IDE. I closed that and opened the root folder in command window as admin. The errors are same in both cases.
The antivirus we are using is Symantec. and NPM version is 6.4.1

I get different set of errors today.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@6.4.1
3 info using node@v11.4.0
4 verbose npm-session 0c18efeb5e7d064f
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall botframework-webchat@0.0.0-0
7 info lifecycle botframework-webchat@0.0.0-0~preinstall: botframework-webchat@0.0.0-0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 79ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 2744ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3900ms
18 timing stage:loadIdealTree Completed in 8047ms
19 silly currentTree botframework-webchat@0.0.0-0
20 silly idealTree botframework-webchat@0.0.0-0
20 silly idealTree +-- @babel/cli@7.1.2
20 silly idealTree +-- @babel/code-frame@7.0.0
20 silly idealTree +-- @babel/core@7.1.2
20 silly idealTree | +-- @babel/types@7.1.3
20 silly idealTree | +-- debug@3.2.6
20 silly idealTree | `-- ms@2.1.1
20 silly idealTree +-- @babel/generator@7.1.3
20 silly idealTree | `-- @babel/types@7.1.3
20 silly idealTree +-- @babel/helper-annotate-as-pure@7.0.0
20 silly idealTree +-- @babel/helper-builder-binary-assignment-operator-visitor@7.1.0
20 silly idealTree +-- @babel/helper-builder-react-jsx@7.0.0
20 silly idealTree +-- @babel/helper-call-delegate@7.1.0
.
.
.
.
.
Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
7472 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
7472 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
7472 verbose stack     at processImmediate (timers.js:632:19)
7473 verbose cwd D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\packages\bundle
7474 verbose Windows_NT 6.3.9600
7475 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
7476 verbose node v11.4.0
7477 verbose npm  v6.4.1
7478 error code E400
7479 error 400 Bad Request: typescript@3.1.6
7480 verbose exit [ 1, true ]

```

Thanks,
Vishwa

**Comment by sanoorvishwa** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bootstrap' ]
2 info using npm@6.4.1
3 info using node@v11.4.0
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle botframework-webchat-root@4.2.1-0~prebootstrap: botframework-webchat-root@4.2.1-0
6 info lifecycle botframework-webchat-root@4.2.1-0~bootstrap: botframework-webchat-root@4.2.1-0
7 verbose lifecycle botframework-webchat-root@4.2.1-0~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle botframework-webchat-root@4.2.1-0~bootstrap: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master\node_modules\.bin;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files\RSA SecurID Token Common;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\Git\cmd;C:\Program Files\PostgreSQL\9.6\bin;C:\Users\vishwanatha_s\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\vishwanatha_s\AppData\Local\Programs\Fiddler;C:\Users\vishwanatha_s\AppData\Roaming\npm
9 verbose lifecycle botframework-webchat-root@4.2.1-0~bootstrap: CWD: D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master
10 silly lifecycle botframework-webchat-root@4.2.1-0~bootstrap: Args: [ '/d /s /c', 'lerna bootstrap' ]
11 silly lifecycle botframework-webchat-root@4.2.1-0~bootstrap: Returned: code: 1  signal: null
12 info lifecycle botframework-webchat-root@4.2.1-0~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: botframework-webchat-root@4.2.1-0 bootstrap: `lerna bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid botframework-webchat-root@4.2.1-0
15 verbose cwd D:\PM_Activity\AVNET\WebChatSource\WebChatSourcePhase2-Dev-Upgrade\BotFramework-WebChat-master
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bootstrap"
18 verbose node v11.4.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error botframework-webchat-root@4.2.1-0 bootstrap: `lerna bootstrap`
22 error Exit status 1
23 error Failed at the botframework-webchat-root@4.2.1-0 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by compulim** [comment]
@sanoorvishwa For the first log, can you copy-and-paste the first error from the NPM log? The log copied here doesn't show any errors.

**Comment by compulim** [comment]
@sanoorvishwa If you take a look inside your log file, it looks like it have intermittent connectivity issues when trying to download some packages: 

- @babel/cli
- @babel/core
- @babel/preset-typescript
- react-redux
- ts-jest
- typescript

Could you try to download them manually to see if there are any network issues? If they are okay, could you try run `lerna bootstrap` again?

```cmd
C:\Users\Compulim\Downloads>npm view typescript@3.1.6 dist.tarball
https://registry.npmjs.org/typescript/-/typescript-3.1.6.tgz

C:\Users\Compulim\Downloads>curl -o typescript-3.1.6.tgz https://registry.npmjs.org/typescript/-/typescript-3.1.6.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7277k  100 7277k    0     0  7277k      0  0:00:01 --:--:--  0:00:01 18.2M

C:\Users\Compulim\Downloads>
```

**Comment by sanoorvishwa** [comment]
Thanks @compulim. Trying to download the individual module gave the hint on where the issue was. There was unwanted registry set at `C:\\Users\\vishwanatha_s\\AppData\\Roaming\\npm` and it was creating problem. `npm config delete registry` was not clearing it off. I manually cleared the .npmrc file at that location.
Now, all npm commands to create webchat*.js are running without issues.
