### ISSUE TITLE
React component not forwarding all activities to the activityMiddleware

### ISSUE THREAD

**Issue by DavidBurela** [Microsoft/BotFramework-WebChat#1547]
The React component seems to only forward activities that are `typing` or `message` to the activityMiddleware.  This means I can't write client side code to react to bot events.

Using bot v4, if I send an activity like this
```
await step.context.sendActivities([
    { type: 'typing' },
    { type: 'event' },
    { type: 'event', value: "my event args" },
    { type: 'customEvent' },
    { type: 'customEvent', value: "cool stuff" },
    { type: 'message', text: 'My message' }
    ]);
```

and in the client side, I hook in an activityMiddleware
```
activityMiddleware = () => next => card => {
    console.log(card.activity.type);
};

render() {
    return (
        <ReactWebChat activityMiddleware={this.activityMiddleware} directLine={this.directLine} userID="xxxx" />
    );
}
```

when I check the browser console, only the `typing` and `message` activities are sent through to the middleware. No other activities show up.

**Comment by corinagum** [comment]
Thanks for reporting this issue -- I am able to repro, and this will need to be fixed.

Notes to fixer:
`createCoreMiddleware.js` on line 28 simply returns the next activity if it's not of type `message` or `typing`. @cwhitten @compulim Do we want Web Chat to display anything when special activities are sent? Or can we just make sure that the middleware passes all activities on and leave it at that?

**Comment by cwhitten** [comment]
I agree that WebChat should have as little of opinion as reasonable on what activities get filtered.
