### ISSUE TITLE
auto scroll stoped working

### ISSUE THREAD

**Issue by vmunnuru** [Microsoft/BotFramework-WebChat#1550]
I am using latest version of bot, when i send or receive messages, 
1. the display does not scroll down to the latest one 
2. the entry bar is starting at the top of the window(not from the bottom of the window, attached image) not sure if this is the intended behaviour.

<img width="602" alt="screen shot 2019-01-03 at 11 29 22 am" src="https://user-images.githubusercontent.com/25169611/50625023-263ce680-0f4b-11e9-97b2-a862dbee7396.png">

**Comment by vmunnuru** [comment]
@compulim 
https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/BasicWebChat.js
I have seen TODO note over there, is this going to resolve auto scroll issue in React.

**Comment by corinagum** [comment]
Hi @vmunnuru, it looks like there might be a styling error on your page. Let's first try to get the send box to display as expected. If you take a look at our [samples](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/01.a.getting-started-full-bundle/index.html), there is currently need to specify your styles (sizing) for the #webchat div. The samples use the following:

```
#webchat > * {
   height: 100%;
   width: 100%;
}
```

Do you have any styling like the above, or something similar? If not, could you try adding the above and see what happens? Feel free to copy-paste your index.html and I can take a look.

**Comment by vmunnuru** [comment]
Hi @corinagum, thanks for your time. I have created new react project and rendering web chat like 
```
  class Layout extends Component {
  render() {
  return(
  <Aux>
    <main className="Container">
      <ReactWebChat
        botAvatarInitials= 'BOT'
        userAvatarInitials= 'USER'
        directLine={secret} 
        styleSet={styleSet}
      />
    </main>
  </Aux>
  )}}
```
I didn't provided any stylings like as you mentioned.

**Comment by vmunnuru** [comment]
I have tried applying styles like 
```
.Container {
  height: 100%;
  width: 100%;
  background-color: transparent
}
```
But no luck, send box starting from top and there is no change in behaviour. 

Could you please clarify the note at line number 106 in the below link pointing to the same issue in React(auto scrolling).

https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/BasicWebChat.js

**Comment by vmunnuru** [comment]
Fixed issue with stylings
```
<main className="Container">
   <div id="webchat">
      <ReactWebChat
        botAvatarInitials= 'BOT'
        userAvatarInitials= 'USER'
        directLine={secret} 
        styleSet={styleSet}
      />
    </div>
</main>

**CSS**
#webchat,
#webchat>* {
  height: 750px;
  width: 400px;
}
```
