### ISSUE TITLE
SAMPLE: (simple backchannel) - Show users how to send event activities

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotFramework-WebChat#1552]
As of now, there appears to be a backchannel sample that piggybacks on channelData. Sending data this way is predicated on already sending a message, but there are several valid reasons for sending a custom event as a backchannel message instead. In a true "backchannel" the client shouldn't need to render anything. 

This sample should demonstrate backchannel in both directions - the bot making changes to the client and the client sending events to the bot. There was a sample in the previous version of webchat that did this fairly well.

**Comment by corinagum** [comment]
(For reference): I believe you're talking about this sample: [14.customization-piping-to-redux](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/14.customization-piping-to-redux)

We have another issue https://github.com/Microsoft/BotFramework-WebChat/issues/1516 filed, which will show users who don't know Redux how to use event listeners. 

On top of that, we should add a new sample that shows users how to send activities of type `event` using a button click. Adding to 4.4 :)

**Comment by compulim** [comment]
@ryanvolum the sample is almost there, it is in PR #1568.
