### ISSUE TITLE
Sample: Ending a conversation

### ISSUE THREAD

**Issue by eskivelevolution** [microsoft/BotFramework-WebChat#1559]
Hello!

I'm using the new version of BotFramework-WebChat, it's in any time call the end conversation automatically?

Because some customers can't keep a conversation with the same conversationId after some time.

It's happen to me also, and I need to generate another conversationId.

Error 404
![image](https://user-images.githubusercontent.com/19326711/50830300-91f9c780-132e-11e9-837b-96cd0012af26.png)

Thank you.

**Comment by corinagum** [comment]
Hi @eskivelevolution, the ability to end the conversation is currently not available in DirectLineJS, and we want to implement this feature in our upcoming release.

The issue can be tracked here: https://github.com/Microsoft/BotFramework-DirectLineJS/issues/124.

I will keep this issue open for tracking the DirectLineJS issue and the creation of a Web Chat Sample that shows how to implement communication to DL.

**Comment by gabog** [comment]
With the previous webchat it was possible to dispose the webchat and recreate it on the page and that would generate a new conversationId, is this not possible with the new webchat? We need to be able to start a new conversation every time the webchat control is instantiated without having to refresh the page.

**Comment by Amintasn** [comment]
@gabog
"With the previous webchat it was possible to dispose the webchat and recreate it on the page and that would generate a new conversationId, is this not possible with the new webchat? We need to be able to start a new conversation every time the webchat control is instantiated without having to refresh the page." 
Do you happen to have any pointer or sample code that address the webchat disposal and recreation on Botframework V3?
Thx!

**Comment by cwhitten** [comment]
Closing as we have no plans to implement this sample. For the DirectLineJS issue, please see https://github.com/microsoft/BotFramework-DirectLineJS/issues/124
