### ISSUE TITLE
Sample: Add the ability to customize timestamps

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#1571]
Reference: #1556
We have had a few requests asking for the ability to customize the timestamp section of an activity, similar to how 4.2 version of Emulator says "Bot at (time)" with each activity.

![image](https://user-images.githubusercontent.com/14900841/50999851-2eaf9700-14e0-11e9-8f44-12a2ab45280f.png)

Please feel free to add +1 in the comments below if this is a feature you are looking for.

**Comment by FRANZKAFKA13** [comment]
+1

**Comment by raghukrishnamoorthy** [comment]
+1

**Comment by MickeyMehta** [comment]
+1

**Comment by slowtick** [comment]
+1

**Comment by Hrushikesh92** [comment]
+1

**Comment by CyberColsar** [comment]
+1

**Comment by narik1989** [comment]
+1

**Comment by RajneeshVerma** [comment]
+1

**Comment by narik1989** [comment]
Hi, 

Is there any timeline expected for this feature to be available? Also till then can someone please provide me some help on how to customize the middle-ware for timestamp. I want to change the time from 24 hr format to 12 hour format. Any help would be appreciated.

Thanks
Kiran

**Comment by compulim** [comment]
@narik1989 it is coming, #2788.

**Comment by amt-work** [comment]
@compulim Is there an ETA when this will be finished? Thanks!

**Comment by compulim** [comment]
This is on the final round of PR review, #2788. After merged in, you can try it out through daily build.

The next release train is on mid-March. This PR will be on that train.

**Comment by corinagum** [comment]
Closing as resolved; will be released mid-March.

**Comment by narik1989** [comment]
Hi,

I think this feature was released in 4.8.0, where can i find a sample to implement this in my Web Chat (not react app)

Thanks
Kiran

**Comment by DennyWithAnE** [comment]
I am just curious if the ability to customize the timestamps, would the devs be able to customize the timestamp to display above the chat bubbles like in V3?

**Comment by corinagum** [comment]
@DennyWithAnE Yes, you could build a custom transcript where the timestamp component is above the bubble(s). Take a look at our recomposing-ui samples :)

**Comment by DennyWithAnE** [comment]
@corinagum Thanks for the pointers, sorry if I have been asking the obvious with my past few questions. Appreciate the help 💯
