### ISSUE TITLE
mockbot not opening in IE

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotFramework-WebChat#1585]
Mockbot not working in IE

https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle

**Comment by corinagum** [comment]
Hi @ubreddy, to get Web Chat to work on Internet Explorer, please implement the sample with polyfill es5 here: [01.b.getting-started-es5-bundle](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle)
