### ISSUE TITLE
Initialize conversation

### ISSUE THREAD

**Issue by FRANZKAFKA13** [Microsoft/BotFramework-WebChat#1590]
Hi,

when testing my Chatbot in the Emulator, the welcome dialog is started as soon as the bot connects. I then deployed my bot to Azure and also deployed a website with the following index.html:

```
<!DOCTYPE html>
<html>
<body>


<div id="webchat" role="main"> </div>
<style type="text/css">html, body { height: 100% }
  
  body {
    margin: 0px;
    overflow:hidden;
  }

  #webchat, #webchat > * {
    height: 100%;
    width: 100%;
    margin-left: auto;
    margin-right: auto;
  }

  /* Custom scrollbar */
  ::-webkit-scrollbar {
    width: 10px;
  }
  /* Track */
  ::-webkit-scrollbar-track {
    background: #f1f1f1; 
  }
    /* Handle */
  ::-webkit-scrollbar-thumb {
    background: #888; 
  }
  /* Handle on hover */
  ::-webkit-scrollbar-thumb:hover {
    background: #555; 
  }

</style>
<script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script><script>
  // Style modifications
  const styleOptions = {

    // Colors
    bubbleBackground: 'rgba(217, 217, 217, 0.15)',
    bubbleFromUserBackground: 'rgba(0, 150, 130, 1)',
    bubbleFromUserTextColor: 'white',
    bubbleMaxWidth: 600, // maximum width of text message

    // Avatar
    //avatarSize: 100,
    //botAvatarImage: '',
    botAvatarInitials: 'Bot', 
    //userAvatarImage: '',
    userAvatarInitials: '', 

    // Send box
    hideSendBox: false,
    hideUploadButton: true,
    sendBoxButtonColor: '#767676', 
    sendBoxButtonColorOnDisabled: '#CCC',
    sendBoxButtonColorOnFocus: '#333',
    sendBoxButtonColorOnHover: '#333',
    sendBoxHeight: 30,

    // Suggested actions
    suggestedActionTextColor: 'black',
    suggestedActionBorder: `solid 2px #009682`,
    suggestedActionHeight: 30,

  };

  
  window.WebChat.renderWebChat({
    directLine: window.WebChat.createDirectLine({ secret: '-CIH_yAABIE.cwA.o2M.LLu9d2WRD4bPipq4hRnZ30keb7kiXU9ul42VFvER9oA' }),
    userID: '123',
    styleOptions,
    // store
  }, document.getElementById('webchat'));

  document.querySelector('#webchat > *').focus();
</script>

</body>
</html>
```

You can reach the site with this URL: https://ra-bot-ws-c.azurewebsites.net/

As you can see, the bot doesn't initialize the conversation. When you send an initial message, the main dialog, which is looped, appears twice. Seems like I have to manually post an activity from the client. I found the following code for a bot connected through directline:

```
<html>
<head>
<link href="./css/botchat_t1.css" rel="stylesheet" />
<meta charset="UTF-8">
<title> </title>
</head>
<body>
<div>
<div id="bot"></div>

<script src="./js/bot.js"></script>

<script>
var params = Bot.queryParams(location.search);
var user = {
id: params["userId"] || 'user',
name: 'Du'
};

var botConnection = new Bot.DirectLine({
token: 'TOKEN',
user: user
});

Bot.App({
    user: user,
    botConnection: botConnection,
    bot: { id: 'bot', name: 'Chatbot' },
    resize: 'detect',
    locale: 'de-de',
    showUploadButton: false
}, document.getElementById("bot"));

botConnection.postActivity({
    from: user,
    name: 'requestWelcomeDialog',
    type: 'event',
    value: ''
}).subscribe(function (id) {
    console.log('"trigger requestWelcomeDialog" sent');
});

</script>
</div>
</body>
</html>
```
Is there an equivalent way to implement the following excerpt from the DL code in my index.html code?

```
botConnection.postActivity({
    from: user,
    name: 'requestWelcomeDialog',
    type: 'event',
    value: ''
}).subscribe(function (id) {
    console.log('"trigger requestWelcomeDialog" sent');
});
```

Thank you in advance

Another general thing I don't really understand:
The directline seems to allow much more flexibility compare to the WebChat client (since it is under development). Are customizations like the avatar or chat message colors only possible with the WebChat client or as well with a directLine connection? If yes, what is the advantage of the WebChat client.

**Comment by corinagum** [comment]
The `ConversationUpdate` differences between the Emulator, Direct Line, and other channels are a known issue that is being tracked here: https://github.com/Microsoft/BotFramework-Emulator/issues/643. I'm actually still a little confused about the differences myself, but hopefully more information will roll out from other team members. :)

We have a relatively new sample [15.d.backchannel-send-welcome-event](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/15.d.backchannel-send-welcome-event) that shows how to implement the Emulator's version of welcome activity. Please try this out and let me know how it goes for you. :)

**Comment by FRANZKAFKA13** [comment]
Thanks for your thorough explanation @compulim. It is really good to know that your client enables me to use the directline object in the same fashion as in my second code example.

@corinagum Thank you! I will try to implement the welcome activity based on your new sample.

I already saw in some posts that there is no option yet to "end conversation" through your client. My next question would be if "ending conversation" is necessary for the following issue I face: 
Since I conduct a laboratory experiment on Chatbots, not every participant uses her or his own computer. We have 5 computers but about 200 participants that need to chat with the bot. My bot stores user input, such as name or gender. When I close the html site and open it again, the userdata is still saved. I need a way to be able to "clear" the saved information before conducting the experiment with the next participant on the same computer.

**Comment by FRANZKAFKA13** [comment]
Hi @corinagum,

the backchannel sample works and my bot's conversation now starts properly. Thank you!!!

I hope I can reopen this issue for the second part. Unfortunately, F5 doesn't work. The bot keeps information saved for a while (I don't know when, but at some point it resets).

Might it have something to do with the fact that I use the secret instead of tokens? When trying to use tokens, I get a 404 error.

This is my current code (with secret, not token):

```
<!DOCTYPE html>
<html>
<body>
<div id="webchat" role="main"> </div>

<style type="text/css">html, body { height: 100% }
  
  body {
    margin: 0px;
    overflow:hidden;
  }

  #webchat, #webchat > * {
    height: 100%;
    width: 100%;
    margin-left: auto;
    margin-right: auto;
  }

  /* Custom scrollbar */
  ::-webkit-scrollbar {
    width: 10px;
  }
  /* Track */
  ::-webkit-scrollbar-track {
    background: #f1f1f1; 
  }
    /* Handle */
  ::-webkit-scrollbar-thumb {
    background: #888; 
  }
  /* Handle on hover */
  ::-webkit-scrollbar-thumb:hover {
    background: #555; 
  }

</style>

<!-- Include webchat client functionality (https://github.com/Microsoft/BotFramework-WebChat) -->
<script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>


<script>
  // Style modifications
  const styleOptions = {

    // Colors
    bubbleBackground: 'rgba(217, 217, 217, 0.15)',
    bubbleFromUserBackground: 'rgba(0, 150, 130, 1)',
    bubbleFromUserTextColor: 'white',
    bubbleMaxWidth: 600, // maximum width of text message

    // Avatar
    //avatarSize: 100,
    //botAvatarImage: '',
    botAvatarInitials: 'Bot', 
    //userAvatarImage: '',
    userAvatarInitials: '', 

    // Send box
    hideSendBox: false,
    hideUploadButton: true,
    sendBoxButtonColor: '#767676', 
    sendBoxButtonColorOnDisabled: '#CCC',
    sendBoxButtonColorOnFocus: '#333',
    sendBoxButtonColorOnHover: '#333',
    sendBoxHeight: 30,

    // Suggested actions
    suggestedActionTextColor: 'black',
    suggestedActionBorder: `solid 2px #009682`,
    suggestedActionHeight: 30,

  };

  (async function () {


        // We are using a customized store to add hooks to connect event
        const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
          if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
            // When we receive DIRECT_LINE/CONNECT_FULFILLED action, we will send an event activity using WEB_CHAT/SEND_EVENT
            dispatch({
              type: 'WEB_CHAT/SEND_EVENT',
              payload: {
                // Event, das den Bot startet, ohne
                name: 'webchat/join',
                value: {}
              }
            });
          }
          return next(action);
        });

    // Create directline Object
    window.WebChat.renderWebChat({
      // Secret is permanent while token is only valid per conversation
      directLine: window.WebChat.createDirectLine({ secret: '-CIH_yAABIE.cwA.o2M.LLu9d2WRD4bPipq4hRnZ30keb7kiXU9ul42VFvER9oA' }),
      //directLine: window.WebChat.createDirectLine({ token }),
      userID: '123',
      styleOptions,
      store,
    }, document.getElementById('webchat'));



  document.querySelector('#webchat > *').focus();
})().catch(err => console.error(err));
</script>

</body>
</html>



```

**Comment by corinagum** [comment]
It sounds like you are using user state to save this information, is that correct? If so, you will need to create a new userID every time the page is refreshed. Please take a look at our [README](https://github.com/Microsoft/BotFramework-WebChat/blob/master/README.md). The first code snippet shows you how to create a new ID. Hope that helps!
