### ISSUE TITLE
Angular cannot pick up `mime` package before lacking of `.json` extension

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1596]
Angular CLI will fail when building any project with direct dependencies to `mime` package.

`mime` package have a file named `types/standard.json`. And in the code, it use `requires('./types/standard')`, and Angular CLI isn't working unless it changed to be `requires('./types/standard.json')`.

**Comment by cwhitten** [comment]
this is addressed in https://github.com/Microsoft/BotFramework-WebChat/pull/1686
