### ISSUE TITLE
SAMPLE: Web Speech and Bing/Speech services text-to-speech combination

### ISSUE THREAD

**Issue by erkkil** [Microsoft/BotFramework-WebChat#1597]
Hi,

In the v3 webchat it was possible to combine webspeech for speech to text and bing speech for text to speech in a one solution. 

I have tried to find a way how to do it in v4 but no luck so far.

Our basic requirement is to use 
- webspeech for speech recognition
- MS speech services or bing speech for text to speech synthesis
- also we have to be able to specify locale that is going to be used in both directions

I have looked the docs and samples but did not find any help

**Comment by corinagum** [comment]
- For mix and match, this would be a good sample to help out our users. We'll use this bug as tracking for that sample. :)
- Specifying the locale is not possible yet - we have an issue for tracking this feature: https://github.com/Microsoft/BotFramework-WebChat/issues/1529

Hope that helps!

**Comment by corinagum** [comment]
@compulim assigning you so you can add your input :)

**Comment by compulim** [comment]
@erkkil and @corinagum, I have filed a PR #1617 for the hybrid speech sample. Played with it and the sample looks awesome.
