### ISSUE TITLE
Using Cognitive Services Speech with React

### ISSUE THREAD

**Issue by FrederikHoffmann** [Microsoft/BotFramework-WebChat#1599]
I want to integrate the Cognitive Speech Services into the Webchat using React, but when I try to pass the CognitiveServicesSpeechServicesPonyfillFactory to the ReactWebChat component, I get "TypeError: webSpeechPonyfillFactory is not a function" in Composer line 384. There is a sample for using simple JS, but not for React. Can someone help me?

**Comment by compulim** [comment]
Hi @FrederikHoffmann,

The ponyfill factory (namely, `webSpeechPonyfillFactory` props) you are passing into `ReactWebChat` component must be a function that will create a [ponyfill](https://ponyfoo.com/articles/polyfills-or-ponyfills).

So in the [sample 06.c](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/06.c.cognitive-services-speech-services-js/index.html), line 43 is probably what you are looking for.

This code block, after `await`, will create a function that return a Web Speech API ponyfill and set it into `webSpeechPonyfillFactory` variable.

And after we pass this factory function into Web Chat, Web Chat will call this function to build a concrete ponyfill object that mimic the Web Speech API, i.e. an object that have `{ SpeechRecognition, SpeechGrammarList, speechSynthesis, SpeechSynthesisUtterance }` properties that conform to the web standard.

Please let us know if it solve your problem. Happy to help. 😃

**Comment by FrederikHoffmann** [comment]
Hi @compulin
Thank you for your quick reply.
I  used 
`this.webSpeechPonyfillFactory = createCognitiveServicesSpeechServicesPonyfillFactory(
            {
                region: 'westeurope',
                subscriptionKey: 'XXXXXXXXXXXXXXXXXXX',
            },
        );`

to create the Factory. Sorry if that wasn't clear in the original description.

**Comment by corinagum** [comment]
Jumping in - @FrederikHoffmann It looks like you need an await on the factor method -- this one is async :) 
Closing this issue - please feel free to comment if that did not solve your issue and I will reopen.

**Comment by FrederikHoffmann** [comment]
Thank you @corinagum,

That was my fault. For everyone with the same problem with createReactApp, you can just use the aysnc function componentDidMount() to create the function and save it in the state.

**Comment by omora** [comment]
Hi, I have the same problem can you add the final solution ... I am not a react programmer ... Thanks

**Comment by omora** [comment]
@FrederikHoffmann

**Comment by FrederikHoffmann** [comment]
Hi @omora,
as said by corinagum you have to wait for the factory-method to return a result. Since you can only use await in an async block, you can just put

`async componentDidMount() {
        const webSpeechPonyfillFactory: Function = await createCognitiveServicesSpeechServicesPonyfillFactory(
            {
                region: 'westeurope',
                subscriptionKey: '*************************************',
            },
        );
        this.setState({ webSpeechPonyfillFactory: webSpeechPonyfillFactory });
    }`

in the tsx file of the Component, if you are using createReactApp. You also have to declare the webSpeechPonyfillFactory as part of the Component's state. I am not much of a React Programmer myself, so I can not give you a lot more.

I hoped it helps anyway.
