### ISSUE TITLE
Feature Request: Formalized doc explaining differences between v3/v4 webchat (and a Roadmap)

### ISSUE THREAD

**Issue by stevengum** [microsoft/BotFramework-WebChat#1600]
## Background

With v4 WebChat being our GA offering, more customers are going to want to migrate from v3 WebChat to v4. While issue #1159 is great for explaining what the plan was and what most of the work that went into v4, there should be a formalized doc that we can point customers to that explains the new features and any deprecations when comparing v3 to v4.

Additionally, a Roadmap would be great.

Example [botbuilder-js roadmap](https://github.com/Microsoft/botbuilder-js/wiki/Roadmap)
Example [VSCode roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap)

@cwhitten as FYI

## Pitch of v4

(Please keep adding to the list below, will clean up later)

- Feature on-par with v3
- Brand new UI design
- Supports customization, no need to fork our code as forked code is not supported
- Supports 3 different speech engines out of the box: browser, Speech Services, and Bing Speech
- Adheres to latest Adaptive Cards (as of now, 1.1.2)
- Supports of hooking into various events, including incoming activity event
- Piggyback additional data on selective outgoing activities
- Carousel now support many different input devices, including keyboard, horizontal-scrolling mouse wheel, touch, precision touchpad, Xbox controller, etc
- Better accessibility support
- More options for timestamp grouping
- Supports bot/user avatar initials and images
- Supports custom rendering of activities and attachments
- Supports bot built by both BotBuilder SDK v3 and v4
- Supports custom Markdown engine
- Supports custom handling of card action
- Show errors on various connectivity issues

**Comment by corinagum** [comment]
(Removing 4.3 label, pending discussion with team. :) )

**Comment by compulim** [comment]
Please keep editing the first thread to aggregate the list.

For any public contributors, please comment here, we will copy it above. Maintainers, after copy, please edit and ~~crossout~~ contributors comments to indicate it has been copied.
