### ISSUE TITLE
Quotation marks around suggested action

### ISSUE THREAD

**Issue by FRANZKAFKA13** [Microsoft/BotFramework-WebChat#1602]
Hey,

when using the "master" branch, the suggested actions are suddenly surrounded by quotation marks. The functionality is the same, it's just a style issue.

![image](https://user-images.githubusercontent.com/43933363/51344326-aa898080-1a98-11e9-806e-9f17fd4c9380.JPG)

**Comment by corinagum** [comment]
Hi @FRANZKAFKA13, looks like you might have found a bug, thanks for the catch. Let me get back to you.
