### ISSUE TITLE
[Feature Request] CardFactory does not support AdaptiveCards v1.1

### ISSUE THREAD

**Issue by weiligao** [Microsoft/BotFramework-WebChat#1607]
BotBuilder JS SDK 4 CardFactory does not yet support AdaptiveCards v1.1 that has been published since Oct. 16. Is this planned for the feature, and if yes, when?

Possible workaround using AdaptiveCards npm package and Puppeteer, but requires a hack:
https://github.com/Microsoft/AdaptiveCards/issues/1012
https://github.com/Microsoft/AdaptiveCards/issues/1274
https://runkit.com/rcasto/adaptive-card-nodejs
https://github.com/GoogleChrome/puppeteer

**Comment by corinagum** [comment]
These changes are merged in on #1558 and will be released to production build on February 14. In the meantime, you are welcome to use the `master` build of Web Chat to utilize these features immediately.

**Comment by SwedhaBalasubramanian** [comment]
May I know when you will support AdaptiveCards for Facebook/ Workplace??

**Comment by corinagum** [comment]
I don't know that the Bot Framework team has any control over third party adaptation of Adaptive Cards. @craigjensen, do you have any information on supporting Adaptive Cards on third party channels?
