### ISSUE TITLE
Minimization sample is not working

### ISSUE THREAD

**Issue by Unders0n** [Microsoft/BotFramework-WebChat#1619]
This demo sample https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/ is not working now live, messages just not sending. Though it's working when deployed locally and configured with my own token.

**Comment by compulim** [comment]
Fix #1631 is on the way~~~

**Comment by Unders0n** [comment]
still not seems to be fixed? Btw 4.3 was planned for 14 feb but i stil can't see it in nuget updates, am i missing smth? thanks

**Comment by corinagum** [comment]
4.3 has been pushed back to March 4th. These changes are available in `/master/` bits but not `/latest/`.
