### ISSUE TITLE
Font Customization 

### ISSUE THREAD

**Issue by deva96** [Microsoft/BotFramework-WebChat#1622]
I am using web chat v4,I have created one dropdown there user can select font size/font weight for his/her convinence. I can't achieve two things.

- Cant change font size/font weight/font family for adaptive card/hero card/other attachments
- Cant change font family 

I am currently using jquery to perform button click change  using id "webchat".Code is below

```js
function font_size() {
    var e = document.getElementById("sizeselect");
    var value = e.options[e.selectedIndex].value;
    document.getElementById("webchat").style.fontSize = value;
}
```

similarly for font-weight,Help me achieve the two thing i mentioned

(Edited by @compulim for formatting)

**Comment by corinagum** [comment]
Hi @deva96, This is already a planned-for feature for Web Chat! Please track this issue on #1553.
I will close this issue as a dupe. If you have anything you'd like to add to the issue, please feel free to leave a comment over there.

**Comment by deva96** [comment]
@corinagum  hey ,the issue you mentioned is only for changing the font styles by developer.But i want to give the font customization ability to the user/customer.I have already able to give it to customer but i can't able to change font-family and font-styles for card response alone.For that i am asking suggestion/way

**Comment by compulim** [comment]
@deva96 are you talking about setting the font only for the card, but not the whole Web Chat?

For instance, are you talking about changing the font of the yellow part, without changing the font of green part?

![image](https://user-images.githubusercontent.com/1622400/51630232-7e3d8c00-1efe-11e9-81c3-537c31167e1f.png)

**Comment by ljubomirsinadinovski** [comment]
Check my comment here maybe it could help you out: https://github.com/Microsoft/BotFramework-WebChat/issues/1640#issuecomment-458491356

**Comment by corinagum** [comment]
Closing - stale.

**Comment by compulim** [comment]
#1670 might be fixing this.
