### ISSUE TITLE
Pass language to Cognitive Services Speech Services recognition

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/BotFramework-WebChat#1623]
Apparently the new Cognitive Services Speech Services has support for many languages, as stated [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support). I played a little bit with the `06.c.cognitive-services-speech-services-js` sample, however I couldn't get it working with any other language than `en-US` or `en-GB`. 

It looks like it will take the `lang` from the HTML element in [createSpeechRecognitionPonyfill.js](https://github.com/compulim/web-speech-cognitive-services/blob/038dccb6ed8946437183866607db8c986dda8b63/packages/component/src/SpeechServices/SpeechToText/createSpeechRecognitionPonyfill.js#L98),  however I tried setting that to `nl` and `nl-NL`.

```javascript
      this._lang = typeof window !== 'undefined' ? (window.document.documentElement.getAttribute('lang') || window.navigator.language) : 'en-US';
```

- Is it possible to use another language in the current implementation? If it is possible already, it would be great to have a sample.

**Comment by corinagum** [comment]
Hi @iMicknl, I believe we have an open issue related to yours, linked here:  https://github.com/Microsoft/BotFramework-WebChat/issues/1529
Our plan is to have a fix for this issue, not for the next release but for the one after that. Please feel free to add comments to that issue. I will be closing this one as dupe. :)

**Comment by iMicknl** [comment]
Thanks @corinagum, I missed the related issue! I will have to investigate of Dutch is supported at all, since the endpoint the WebChat is using doesn't support `nl`, so I guess it can differ in the SpeechServices functions.

**Comment by corinagum** [comment]
@iMicknl feel free to update #1529 with your findings. :)
