### ISSUE TITLE
Some timestamps stop updating

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#1627]
`activity.timestamp` is correct. Looks like some UI stopped from updating itself (thru `setInterval` or `setTimeout`). And there are no JavaScript errors.

![image](https://user-images.githubusercontent.com/1622400/51575801-759a7680-1e68-11e9-83de-9efe3336b163.png)

![image](https://user-images.githubusercontent.com/1622400/51575813-85b25600-1e68-11e9-8b53-38311a8a5324.png)

And after awhile, the timestamp still looks the same.

![image](https://user-images.githubusercontent.com/1622400/51575879-cb6f1e80-1e68-11e9-8add-8f24e43bafc0.png)

**Comment by galenguilbert** [comment]
I'm wondering if there's a time frame for this fix?

**Comment by corinagum** [comment]
Hi @galenguilbert, currently there is no time frame. Thank you for commenting, however! Customers adding their desire for these kinds of fixes puts them on our radar as something customers are looking for. I will add this to our discussion list for now. :)

**Comment by compulim** [comment]
Still seeing the bug as of today. Need to fix it in 4.5.
