### ISSUE TITLE
directline errors

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotFramework-WebChat#1638]
I keep getting directline errors once a while multiple times during the day....

e.g. 
getaddrinfo ENOTFOUND directline.botframework.com directline.botframework.com:443

and 
some errors like below
https://directline.botframework.com/v3/conversations/I02GjBASIPz4DOmNQeTxKL/activities/I02GjBASIPz4DOmNQeTxKL%7C0000000' failed: [503] Service Unavailable

https://directline.botframework.com/v3/conversations/6lg94qXdQbv6WOaUTf42YO/activities/6lg94qXdQbv6WOaUTf42YO%7C0000000' failed: [500] Internal Server Error

https://directline.botframework.com/v3/conversations/HBVeZlhbpVx1B1cjKD5QXS/activities/HBVeZlhbpVx1B1cjKD5QXS%7C0000000' failed: [502] Bad Gateway
Any reason why ? it stops our webchat conversation flow....

**Comment by cwhitten** [comment]
Hi @ubreddy, please direct issues with the DirectLine service to [BotBuilder](https://github.com/Microsoft/BotBuilder) project
