### ISSUE TITLE
Polling issues OPTIONS and GET on every call

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotFramework-WebChat#164]
Seems excessive to make both OPTIONS and GET calls for every request. Can the xhr be configured to do the OPTIONS call only once?

**Comment by billba** [comment]
I rewrote the GET loop late last week and now I'm seeing OPTIONS less often, but still after every fourth or fifth GET. I will have to delve into the RxJS ajax code to understand the underlying logic.

**Comment by billba** [comment]
This appears to be a browser thing. The default cache for a preflight in Chrome is 5 seconds. We poll every second, so for the same URL it’s going to call OPTIONS every fourth or fifth time, which is exactly what it’s doing right now.

Apparently you, meaning Direct Line, can return a header value called Access-Control-Max-Age, although there is still a browser-based ceiling of 10 minutes. Here’s a little discussion about this from StackOverflow: http://stackoverflow.com/questions/23543719/cors-access-control-max-age-is-ignored

**Comment by dandriscoll** [comment]
Dig. I'll start sending that.

**Comment by billba** [comment]
Now works beautifully.
