### ISSUE TITLE
How to customize HTML or add CSS class

### ISSUE THREAD

**Issue by dalvirsaini** [Microsoft/BotFramework-WebChat#1640]
Hi,  This is not an issue but I need to know if its supported here or not.
I saw that the webchat rendering html like following: 
```
<div id=webchat>
<div>
<div>**conversations are here**</div>
<div>**reply text box is here**</div>
</div>
</div>
```
I want this output to be customized like I want to render reply text box outside of webchatdiv. Or I want to add my own classes to these divs.. 
is it possible here?

**Comment by corinagum** [comment]
As for picking and choosing which components to use, we have a sample showing you how to do that, please check it out: 
[13.customization-speech-ui](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/13.customization-speech-ui)

You can use middleware to add DOM elements to your app. I suggest looking at samples 8-10:

- [08.customization-user-highlighting](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/08.customization-user-highlighting)  
- [09.customization-reaction-buttons](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/09.customization-reaction-buttons) 
- [10.customization-card-components](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/10.a.customization-card-components)
- [10.b.customization-password-input ](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/10.b.customization-password-input)

Hope that helps!

**Comment by ljubomirsinadinovski** [comment]
I am customizing it with manipulation of the CSS. For example if I want to change all the font I am using:
`.chat-wrapper-ljs * {
  font-family: "Ariel" !important;
}`
and I pass that as a className to the component:

` <ReactWebChat
        className="chat-wrapper-ljs"
        //write the rest of the props you need to pass here
}`

Also you can manipulate only paragraphs/input/labels with something like this (here I am selecting only the input elements): 
``.chat-wrapper-ljs input {
  font-family: "Ariel" !important;
}``

**Comment by corinagum** [comment]
Please note that the Web Chat team does not recommend using `!important`, since this can cause specificity overrides, and complications when making further styling adjustments on the app.

**Comment by ljubomirsinadinovski** [comment]
Fair enough, thank you for the advice. However I managed to overwrite some of your styling by using css attribute selectors (https://www.w3schools.com/css/css_attribute_selectors.asp) on the weird named classes ( `<div class="xzy2kds">` ). For example I was required to change the background of the adaptive card that I was receiving... what do you think about that approach @corinagum ???

**Comment by corinagum** [comment]
Web Chat uses CSS-in-JS, which automatically generates the classes into CSS. This is why the class names are nonsensical. If the features you want to change are not available in defaultStyleSetOptions (shown here:) https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/05.a.branding-webchat-styling, please use the idiosyncratic styling method here: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/05.b.idiosyncratic-manual-styling

**Comment by ljubomirsinadinovski** [comment]
The problem with idiosyncratic-manual-styling is that there is no list of available styles to overwrite. For example (as in sample/05.b) `styleSet.textContent = {..}` textContent is available, but how about the other style... for example the background of the adaptive cards, or the margin between the adaptive cards... etc... By my logic I found a list here: https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/createStyleSet.js however it didn't work for me. BTW CSS-in-JS (glamor I guess) always generates the same class names, so for now I am just overwriting them. If there is a better way for this, or if there is a list of available styles that can be overwritten please elaborate.

**Comment by compulim** [comment]
1. Adaptive Cards requires different way to style, so you will need to use [`AdaptiveCardHostConfig`](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config). But in our experience, styling is pretty limited with Adaptive Card
2. `glamor` uses the hash to generate the name and this is what we want to achieve too
   - We don't want to set CSS class name because we don't want to set an expectation that we won't change the class in the future. If we name something, the user will expect the name means the same thing in the future. We explicitly don't want this expectation
   - We prefer the user to use CSS selector for the specific DOM element, because in this way, they will be aware that the DOM could change from time to time
3. If there are anything that cannot be styled using the method described in `idiosyncratic-manual-styling` sample (other than Adaptive Cards), please let us know what you want to achieve, or file us a PR

**Comment by ljubomirsinadinovski** [comment]
@compulim I will write you a short mail now ^_^

**Comment by keshavnagpal** [comment]
![image](https://user-images.githubusercontent.com/10372931/52560560-ba3d8000-2e1e-11e9-9e40-3137b712a355.png)
image div inside the "ac-container" doesn't have a class
previously the div containing the image had "ac-image" class
but now div doesn't have that class and the img tag inside the div has the class="ac-image"
wouldn't it be better if div has the ac-image class?

i'm using master/webchat-es5.js
