### ISSUE TITLE
Creating the Header and customized text area in V4 Bot

### ISSUE THREAD

**Issue by SushanthMandarthi** [Microsoft/BotFramework-WebChat#1650]
Hi,

We have header and customized text area in v3, and now we are migrating those to v4. 
 
can any one help me for the below challenges we are facing while migrating-
1. How can I add a header to bot from outside the webchat as it was previously suggested to do any customizations outside webchat.
2. How can I customize my text area which contains **auto suggestion** for user input and there are few buttons in the text area which are used to update the redux store values . Even our text area can expand upto 4 line depending upon user input.

It will be very helpful if some one help to come over these obstacles soon.

Thanks, 
Sushanth

**Comment by sanoorvishwa** [comment]
@SushanthMandarthi Answer to additional questions in [#1639](https://github.com/Microsoft/BotFramework-WebChat/issues/1639) should clarify this.

**Comment by corinagum** [comment]
Hi @SushanthMandarthi, as @sanoorvishwa mentioned, please see my answer from #1639 :)
> You can check out [12.customization-minimizable-web-chat](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat) for a jumpstart on implementing a header for your Web Chat component. :)

> [13.customization-speech-ui](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/13.customization-speech-ui) - This tutorial will get you started on how to separate out and build your own individual components.
