### ISSUE TITLE
pass default value of 'meta' parameter as "keyword" in 'postActivity' function of postActivitySaga.js

### ISSUE THREAD

**Issue by neetu-das** [Microsoft/BotFramework-WebChat#1651]
Hi,
When I tried to add Minimizable Webchat from samples to my project, somehow it's not hitting the action '../actions/postActivity.js'.
So from below part of MinimizableWebChat.js
```
const store = createStore({}, ({ dispatch }) => next => action => {
      if (action.type === "DIRECT_LINE/CONNECT_FULFILLED") {
        setTimeout(() => {
          dispatch({
            type: "DIRECT_LINE/POST_ACTIVITY",
            payload: {
              activity: {
                name: "webchat/join",
                type: "event",
                value: {
                  language: window.navigator.language
                }
              }
            }
          });
        }, 1000);
      } else if (action.type === "DIRECT_LINE/INCOMING_ACTIVITY") {
        if (action.payload.activity.from.role === "bot") {
          this.setState(() => ({ newMessage: true }));
        }
      }

      return next(action);
    });
```

when the below action is dispatched:
```
dispatch({
            type: "DIRECT_LINE/POST_ACTIVITY",
            payload: {
              activity: {
                name: "webchat/join",
                type: "event",
                value: {
                  language: window.navigator.language
                }
              }
            }
          });
```
It does not have meta property set as default "keyword". Hence, this breaks when 'postActivity' method of postActivitySaga.js is hit. I am referring the below code:

```
function* postActivity(directLine, userID, numActivitiesPosted, { meta: { method } , payload: { activity } }) {
  const locale = yield select(languageSelector);.........

```
Now to fix this I am following two approaches:
1. Either dispatch action with meta property like below:
 ```
dispatch({
            type: "DIRECT_LINE/POST_ACTIVITY",
            meta: "keyword",
            payload: {
              activity: {
                name: "webchat/join",
                type: "event",
                value: {
                  language: window.navigator.language
                }
              }
            }
          });
```
2. Or give default value as "keyword" to the postActivity method of postActivitySaga.js as below:
```
 function* postActivity(directLine, userID, numActivitiesPosted, { meta: { method } = "keyword", payload: { activity } }) {
  const locale = yield select(languageSelector);.......
```

Please let me know which one is correct.

**Comment by compulim** [comment]
@neetu-das thanks for taking the time drilling into the code.

I think I fixed minimizable sample in https://github.com/Microsoft/BotFramework-WebChat/pull/1631/. We introduced `WEB_CHAT/SEND_EVENT` and it will use `postActivity` that will fill `action.meta.method` automatically.

The `method` is mainly to determine how the message is sent, e.g. is it from keyboard? Or is it from microphone?

And the primary usage of this `method` field is for messages that sent thru microphone, they will turn on speech synthesis engine on next incoming message from the bot.

I didn't think thru the `method` field complete yet. But I believe, people would love to use `postActivity` to send message "from JavaScript code". Then, `method` should by default be `javascript` or `code`. I didn't think thru how much value this `method` field would provide, other than turning on speech synthesizer.

Can you check if the latest minimizable Web Chat sample is working for you? You can look at the PR #1631 for the diff.

IMO, the "minimizable sample" is a very popular one, we should make it simpler and more intuitive to use and understand..

**Comment by neetu-das** [comment]
@compulim Thanks for the update. Yes PR  #1631 solved the problem.
