### ISSUE TITLE
Scroll to bottom feature does not differentiate between new messages and 'read' messages

### ISSUE THREAD

**Issue by xinfli** [microsoft/BotFramework-WebChat#1657]
The "New messages" always show when I scroll up, even I already read all messages.
Is it possible to mark all messages as read, or can I hide the "New messages"?
Thanks.

**Comment by corinagum** [comment]
Hi @xinfli, the "New messages" notification actually indicates there are new messages at the _bottom_ of the chat (most recent messages). Could you test and see if it disappears when you scroll to the bottom of the chat? Is this a feature you would still prefer to hide?

**Comment by xinfli** [comment]
Hi @corinagum Thanks, the notification works fine as design (When scroll to bottom, it will disapper), but not as I expected.
I think it should only indicate that there are new message UNREAD arrived, then I should scroll to bottom to read it;
But now the notification will always show when ever I scroll up, that makes us confused.
If this notification only indicate that I'm not reading the newest message, I think it should be renamed to "Go to bottom".

**Comment by mewa1024** [comment]
I think issue 2 above is accurate, and that this should be the behavior: "New messages" should disappear once the new/unseen message has scrolled into view, but it should not reappear when that message scrolls out of view again.

**Comment by DesignPolice** [comment]
I would agree with @mewa1024 as well.

**Comment by corinagum** [comment]
We've had more offline discussion -- this issue is related to https://github.com/compulim/react-scroll-to-bottom/issues/10 - both issues will need to be resolved at the same time. 

**We want to have a 'read' marker where all messages are marked as read when the user hits the bottom of the container.** 

I'm keeping this issue open for tracking both.

**Comment by xinfli** [comment]
Thanks all for your quick response 👍 
I'd like if there is a new feature to mark message as read, by now I will hide it in our product :-)

**Comment by compulim** [comment]
This is done in 4.8.0.
