### ISSUE TITLE
Disable Reply Text Field

### ISSUE THREAD

**Issue by dalvirsaini** [Microsoft/BotFramework-WebChat#1661]
Hi , 

I would like to disable the Reply text field if suggestion/option are already showing to the user. 
I want user to choose from there instead of typing in text area.
![image](https://user-images.githubusercontent.com/5260369/51963250-f1a84600-2488-11e9-83ae-c0f084bf50b5.png)

any help here?

**Comment by corinagum** [comment]
Hi @dalvirsaini 
This is possible by checking all incoming activities for a non-null value in `suggestedActions`. Then you can toggle a boolean to enable the disabled (`<input disabled />`)  attribute. Hope that helps!
