### ISSUE TITLE
Webchat doesn't fire conversation updated event until first message

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/BotFramework-WebChat#1665]
I expected my bot's code to behave as it does in the emulator when I deployed it to its App Service and tested it in webchat. However, I immediately noticed that it would not greet me as a user (following the greet the user sample) until I first sent it a message. Our emulator should emulate our channels more closely especially the channels we ship by default (webchat) and provide quick testing for in our portal.

**Comment by corinagum** [comment]
There an ongoing discussion about this and can be tracked here: https://github.com/Microsoft/BotFramework-Emulator/issues/643

I will leave this issue open for tracking purposes.

**Comment by ljubomirsinadinovski** [comment]
Accidentally I copied my logic in this issue, so I guess it can be re-used, it is much better approach: https://github.com/Microsoft/BotFramework-WebChat/issues/1630#issue-402333440 (this will fire the event in the background)

**Comment by corinagum** [comment]
`conversationUpdate` behaves differently between Emulator and Azure Bot Services.

It is suggested to send a custom event (as opposed to `conversationUpdate`) when Web Chat connects. You can find a [sample here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event).

The benefit for this approach is that you can pass extra arguments when you are sending the custom event, for example, browser language, browser capabilities (mobile/desktop), and the auth token for single-sign on.

**Comment by Slayouth** [comment]
Sorry @corinagum, but my exposed error, is not like this. Using https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/, you can see how, by an instant, while messages are sending, they shows up, over any previous sent message.
![Captura de pantalla (44)](https://user-images.githubusercontent.com/18583823/56056255-0bd88d00-5d32-11e9-9454-49436d950741.png)

**Comment by corinagum** [comment]
@Slayouth Thank you for the clarification. I will move your comment over to the original issue you filed and reopen because it looks your issue and this one are separate.
