### ISSUE TITLE
Teams channel registration completion page not useful

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/BotFramework-WebChat#1667]
After creating a Teams channel registration, the 'Messaging' page you end up on provides little value; there's no direction on how you then interact with the bot via Teams which would be helpful and add value here. Furthermore the 'learn more' link on this pane takes you to a Skype Bots page.

There should be guidance what's next after registration. Maybe a link to "start conversation" button.

**Comment by corinagum** [comment]
This is issue not related to Web Chat. Problems you are facing related to the Azure Portal should be brought up with Azure Support.
