### ISSUE TITLE
Webchat unreliable

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/BotFramework-WebChat#1668]
When going through deploying even a bare-bones Web App Bot from the Azure portal, there were times when webchat would report "failed to send - retry" when this was an out-of-the-box deployment.

**Comment by corinagum** [comment]
Because this regards an out-of-the-box deployment, I recommend also taking this issue to Azure Support. If you have Web Chat related error messages that you can provide to us, we can reopen this issue and explore how our team can help you.
