### ISSUE TITLE
Azure deployments unreliable

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/BotFramework-WebChat#1669]
Multiple times while trying to deploy a Bot Registration, App Service, or Web App Bot in Azure I ran in to "failed to get deployment status" resulting in an incomplete deployment of resources, or times when deployment would seemingly complete but not everything would be there.

**Comment by corinagum** [comment]
This is issue not related to Web Chat. Problems you are facing related to the Azure Portal should be brought up with Azure Support.

**Comment by brandonh-msft** [comment]
@corinagum instead of closing this issue, can we transfer it to the relevant repo where the pages/flows showing up in ABS are created? Thanks!

cc @cmayo, @sgellock, @ovishesh

**Comment by brandonh-msft** [comment]
@corinagum instead of closing this issue, can we transfer it to the relevant repo where these deployments are implemented (internal or external)? Thanks!

cc @cmayo, @sgellock, @ovishesh
