### ISSUE TITLE
Question: Do we have a c# sample with WebChat integration?

### ISSUE THREAD

**Issue by lieferanten** [Microsoft/BotFramework-WebChat#167]
Hi,

I am looking for a sample written in c# and using the WebChat. The "#### Inline in your non-React website" helps not so much.

Thanks for any Ideas or hints.
Holger

**Comment by billba** [comment]
Samples will come eventually, but please be aware that this is primarily a front-end technology. The only place you'd use C# would be to exchange the Direct Line secret for a token. The rest is all HTML and JavaScript which is why the existing (and admittedly terse) instructions focus there.
