### ISSUE TITLE
Tests occasionally fail on artificial scroll-to-bottom

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-WebChat#1677]
![stacked-js-stacked-with-avatar-initials-4-attachments-1-diff](https://user-images.githubusercontent.com/14900841/52078443-10214680-2548-11e9-82cc-9cfefafae34f.png)

We should wait a little bit longer before taking the screenshot.

**Comment by compulim** [comment]
#1725 probably fixed this. Will submit a new bug if we seeing something similar again.
