### ISSUE TITLE
code samples needed

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#168]
the existing instructions are... terse

**Comment by lieferanten** [comment]
Yes please, I didn't get this in a simple bot project running. Please make a simple application like an echoBot with a *.sln file in github. So that people without deep truescript knowhow can use this sample ;). Thanks Holger.

**Comment by billba** [comment]
@lieferanten You may be looking at the wrong project WebChat is not a way to make bots, it is a way to communicate with the bots you've already made.

**Comment by billba** [comment]
@samskhan That would not work. WebChat communicates with a bot solely through the Direct Line interface. As such, the bot must be registered at bots.botframeworks.com and either deployed in the cloud with a public URL or run locally with a proxied public URL using a service like [ngrok](https://ngrok.io).

I understand the desire for an end-to-end code sample, but implementing WebChat is completely decoupled from the act of creating and deploying a bot, for which there are already a number of good tutorials/samples.

**Comment by mcsee** [comment]
we have a regression bot with all functionalities.

Would share a link if you wish

**Comment by billba** [comment]
@mcsee I'm not sure what that means. Are you saying you have a bot that sends various different activities for test purposes? We have one of those too :-)

**Comment by mcsee** [comment]
@billba exactly.
In order to ensure regression is working

**Comment by iam-peekay** [comment]
@mcsee i'd love to see it
@billba is it also possible to integrate this into an exicting React Native app via a web view?

**Comment by billba** [comment]
@iam-peekay I don't see why not, but I don't know that much about React Native.

**Comment by iam-peekay** [comment]
@billba thank you! Also, can you share why you chose RxJS vs. other solutions for handling async?

**Comment by billba** [comment]
@iam-peekay I very much like functional programming. Have a look at https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/directLine.ts#L126 for an example of how a complex set of async operations get distilled to a very expressive, well, expression. Another simple but good example is https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L88

**Comment by iam-peekay** [comment]
@billba yes, im a FP fan too. I was poking around the source code and that's why I asked. I use functional programming but have used it mostly outside of JavaScript (eg. Elm) and am trying to bring more of those principles to my JavaScript code. Now I'm curious to learn RxJS -- so thank you for motivating me to learn it :)
