### ISSUE TITLE
How to use different language in speech synthesis

### ISSUE THREAD

**Issue by erkkil** [Microsoft/BotFramework-WebChat#1684]
Hi,

I tested the hybrid speech sample using webspeech for speech recognition and speech services for text to speech. 
The sample works fine in english but as we are not from english spoken country how it possible to use e.g. Finnish language in speech synthesis? 
The speech recognition side seems to work in Finnish.

Any samples would be appreciated.

**Comment by corinagum** [comment]
Hi @erkkil, I believe this is a known issue of Web Chat not sending the language to speech services, as detailed #1529 
@compulim can you confirm? If so I think we can close this as a duplicate.

**Comment by compulim** [comment]
Yes, this is a dupe.
