### ISSUE TITLE
Token issue with my Azure bot

### ISSUE THREAD

**Issue by sanoorvishwa** [Microsoft/BotFramework-WebChat#1688]
Hi,
From my local:3000, I am able to connect to the mock bot using 
```
    const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { 
      method: 'POST'
    });
```
and I am able to get the token.
But, if I change the url to connect to my dev bot on Azure, it is not connecting and throws error 
`POST https://directline.botframework.com/v3/directline/conversations 403                          tryCatch.js:9 `

Any idea what setup need to be done on my Azure dev bot to solve this?

Thanks,
Vishwa

**Comment by corinagum** [comment]
Hi @sanoorvishwa, Mock Bot is implemented with an API that allows fetching a token. This API is implemented per bot, and would need a separate implementation for your bot. We have an issue filed https://github.com/Microsoft/BotFramework-WebChat/issues/1534 to show users how to implement a token server. Please feel free to track that issue if you are interested! 

Although it hasn't been merged into code yet, @compulim also filed a PR for an unfinished sample that you can take a look at here: https://github.com/Microsoft/BotFramework-WebChat/pull/1218
