### ISSUE TITLE
Using the Redux store to store conversation history and then retrieve it

### ISSUE THREAD

**Issue by raghukrishnamoorthy** [Microsoft/BotFramework-WebChat#1690]
Hi,

I need to save the conversation history between bot being opened in different tabs. Something I'm considering right now is storing the result of store.getItem on to localstorage. This would store the result of store.getItem() onto the localstorage.

Now, when I open the bot in the subsequent tab, I would like to render the activities i have stored in localstorage. So that it looks like the conversation history is preserved.

How do I go about it?

**Comment by corinagum** [comment]
Hey @raghukrishnamoorthy! It looks like you've already found #365 and there is already some community participation -- I'm going to close this issue as a duplicate. For a Web Chat sample, please feel free to check out [17.chat-send-history](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/17.chat-send-history) to get started on storing history.
