### ISSUE TITLE
README is not clear about secrets/tokens

### ISSUE THREAD

**Issue by navzam** [Microsoft/BotFramework-WebChat#1693]
The README includes snippets containing lines like

`directLine: window.WebChat.createDirectLine({ secret: 'YOUR_BOT_SECRET_FROM_AZURE_PORTAL' })`
`directLine: window.WebChat.createDirectLine({ token: 'YOUR_BOT_SECRET' })`
`this.directLine = new DirectLine({ token: 'YOUR_BOT_SECRET' })`

but "bot secret" is misleading. There are a lot of secrets and tokens in Bot Framework: DirectLine secrets, DirectLine tokens, bot registration secrets, `.bot` file encryption secrets, etc. The snippets should be more clear about which secret they're referring to.

**Comment by compulim** [comment]
Will fix in #1695.
