### ISSUE TITLE
Wrapping input text

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#17]
The user may enter long text into the chat text box. Currently this will "side-scroll" but the textbox should become taller as if it were multi-line.

**Comment by danmarshall** [comment]
@billba can you assign this to me?

**Comment by compulim** [comment]
Prerequisite of #124.

**Comment by EdwinOtten** [comment]
Our team wanted to implement this ourselves, but we have put that on hold since it is included in milestone v4.4 (due on April 15th). 

Do you have an update whether this issue is still on schedule?

**Comment by corinagum** [comment]
@EdwinOtten we did a triage yesterday and unfortunately this has been moved to backlog. We will re-evaluate at the beginning of each milestone (next one is next month).

However if your team is able to implement this, we welcome PR's from the community! A PR from you in the next few weeks would make this available for 4.4. If you think you or a team member may be able to work on this feature, please feel free to contact me if you need any assistance with getting started or if you have questions on writing tests, building, etc.

**Comment by tdurnford** [comment]
@EdwinOtten I'm currently working on this feature request.
