### ISSUE TITLE
SEND_FAILED_KEY is not defined

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#1705]
Looks like related to offline UI change recently.

![image](https://user-images.githubusercontent.com/1622400/52381617-0192cd80-2a27-11e9-91fb-b02ce985b911.png)

![image](https://user-images.githubusercontent.com/1622400/52381643-20915f80-2a27-11e9-8341-09134b855644.png)

**Comment by corinagum** [comment]
:O

**Comment by corinagum** [comment]
Fixed by #1709
