### ISSUE TITLE
Carousel does not work when it contains a <ul>

### ISSUE THREAD

**Issue by GApaniagua** [Microsoft/BotFramework-WebChat#1707]
Hi, I'm having a problem with the displacement of the carousel with adaptive cards, inside the adaptive card, I have a **"TextBlock"** that is showing a list **'-'**. but when I try to change this card, I won't let you. This only happens when the list is a **'ul'** otherwise if I add a **'ol'** the scrolling works correctly, attached video of the problem.

[Error ul Video.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2841982/Error.ul.Video.zip)

**Comment by corinagum** [comment]
Hi @GApaniagua, thanks for reporting this. It looks like you're having this issue on iPhone simulation. Does this issue occur in other browsers or platforms?
Could you verify that you are using v3 of Web Chat? 

Are you able to share your carousel code so that we can test this?

**Comment by GApaniagua** [comment]
Hello @corinagum the problem occurs in any browser, I'm implementing the web chat in an html. the version I'm using is the latest, attached html and carousel.
[Files.zip](https://github.com/Microsoft/BotFramework-WebChat/files/2847274/Files.zip)

**Comment by corinagum** [comment]
Hi @GApaniagua, sorry for the late reply. I'm still having trouble reproing this problem. Could you tell me what commands I should type to prompt the carousel?

**Comment by compulim** [comment]
Web Chat UI is rendered by React. If you modify anything using DOM (`textContent` in your case), they will get reverted at random time.

And in this case, looks like you should use a custom attachment renderer to do the job. We have [a sample here](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/10.a.customization-card-components) that will teach you how to get it done. :)

**Comment by compulim** [comment]
For `ul` vs. `ol`, there is a bug on the carousel component, will fix it.

**Comment by jereh16** [comment]
The same problem seems to appear when using an Audio or Video card. E.g. a carousel containing (in this order) a HeroCard, VideoCard, HeroCard, HeroCard only scrolls to the VideoCard.

**Comment by compulim** [comment]
Will be fixed when we bump `react-film@1.2.0`.

@corinagum could you help on this?
