### ISSUE TITLE
hero card leaves empty space above button list

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#171]
Rendering a hero card with just buttons (as is commonly produced by Prompts.choice) leaves an empty space above the buttons. If there are no title, subtitle, images we should not show any space there

![screen shot 2016-11-24 at 8 05 37 am](https://cloud.githubusercontent.com/assets/11050679/20604782/11a6f9aa-b21d-11e6-9d3c-351fb60f33f1.png)

**Comment by danmarshall** [comment]
One might argue that this isn't a Hero Card. A "hero image" is the defining piece.

**Comment by eanders-MS** [comment]
By the way, I was just getting started implementing this new design for buttons.

Though it isn't clear how it should look in a filled-out hero card. I'll get more detail on that.


![webchat_inline_buttons](https://cloud.githubusercontent.com/assets/12176807/20851443/66a4bae0-b895-11e6-990d-4e70a4e8b146.png)

**Comment by billba** [comment]
The key point here is that a buttons-only hero card is what Prompts.choice spits out.

**Comment by eanders-MS** [comment]
Agreed, the cell at the top should not appear when it doesn't contain content. Whoever implements the new button layout could probably fix this at the same time (either Dan or I).

**Comment by billba** [comment]
This was fixed by https://github.com/Microsoft/BotFramework-WebChat/commit/41324c68cc3e3c41d90b31963bd009b4c6b3855f
