### ISSUE TITLE
Messages move from bottom to top

### ISSUE THREAD

**Issue by sanoorvishwa** [Microsoft/BotFramework-WebChat#1712]
Hi There,
The default framework implementation for stacking the messages on bot area is bottom to top. Is there any way or configuration to get the messages stacked from top to bottom for the size i setup for bot message area?
Thanks,,
Vishwa

**Comment by corinagum** [comment]
Hi @sanoorvishwa, this isn't a current feature of Web Chat, however, the building blocks of our app allow users to pick and choose which components they want to build, and if you would like you are welcome to create your own transcript display. For starters on how to detach components, please take a look at our sample [13.customization-speech-ui](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/13.customization-speech-ui). :)
