### ISSUE TITLE
Choice prompt UI changes depending on Text size?

### ISSUE THREAD

**Issue by Jhanbury** [Microsoft/BotFramework-WebChat#1716]
I have noticed that the Prompt UI changes based on the size of the option text:

- "Home" - is displayed fine

- "Do some other action that is bigger" - is displayed as a list in the response

In order for me to select the large option, the user must type out the text.
Is there already a workaround for this?

If not I think this would be a valuable feature to look at, let me know your thoughts

**Comment by corinagum** [comment]
@Jhanbury do you have screenshots or a working bot example that displays your issue? If you could provide code that creates this issue that would be great as well.

**Comment by Jhanbury** [comment]
@corinagum my apologies here is the UI results of what's happening:

Here is the normal scenario where the action text is under 20 characters:


![image](https://user-images.githubusercontent.com/11406932/52625649-5e6c0900-2ea9-11e9-8c8a-c668525f0768.png)


And here is the result of what happens when the action's text is > 20 characters:

![image](https://user-images.githubusercontent.com/11406932/52625568-2d8bd400-2ea9-11e9-8b7c-66997d28e084.png)

As you can see it now requires the user to input the text rather than the suggested actions.


#### Recreation

As for code Im simply adding the choices to the Choices property of PromptOptions

`           options.Choices.Add(new Choice { Value = "Home" });
`



Is this a setting I can modify?
Or is there a valid reason for why the action text cannot be more than 20 characters long, maybe for horizontal space?

**Comment by Jhanbury** [comment]
Could this be the source of the issue: 

[suggestedAction: Line 7](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/StyleSet/SuggestedActionsStyleSet.js)

What does the flipperSize represent?
Apologies I am not very familiar with the internals of the repository

**Comment by corinagum** [comment]
@Jhanbury Thanks for the details!

Looking at the [botbuilder code](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/choices/channel.ts#L93), it appears there is a 20 character max on suggested actions. I don't know of a workaround, but I have forwarded this issue to the SDK team for further insight. Hope that helps!

**Comment by stevengum** [comment]
@Jhanbury can you provide more code on how you're creating the prompt? If you change the `Style` attribute on your `ChoicePrompt` instance, you can specify SuggestedActions by using [ListStyle.SuggestedActions](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/ListStyle.cs#L35).

```cs
// Not a strong C# dev, but I believe this should work...
var choicePrompt = new ChoicePrompt("someId") {
    Style = ListStyle.SuggestedActions
}
```

Let me know if this solves the issue,, thanks!

**Comment by Jhanbury** [comment]
@stevengum your solution is correct,I was not explicitly setting the style.

The result is the actions buttons are displayed with a cut off as shown in the photo:

![image](https://user-images.githubusercontent.com/11406932/52697945-6e97ed00-2f6a-11e9-9f73-cb275b5348d5.png)

If you wish to see the full title you just have to hover over the button for the tooltip (nice feature).

Thanks @corinagum and @stevengum for your help

**Comment by Sata-Chakra** [comment]
How to solve this on MS teams ? A teams doesn't support suggested actions ?

Do you have a workaround for this on MS Teams ?
Right now we are using adaptive cards , but it has to be out under a textprompt , which is causing a host of other issues.

TIA
