### ISSUE TITLE
How do I pass a locale to webchat?

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-WebChat#1720]
Webchat seems to be taking the locale from the browser, is there a way of setting this in code like we used to be able to do in the previous version?

**Comment by corinagum** [comment]
Hi @gabog, 

You can indicate language by adding the locale key to your renderWebChat() implementation, like so:

```
window.WebChat.renderWebChat({
  directLine: window.WebChat.createDirectLine({ token }),
  locale: 'en-US'
 }
```

Our list of currently available languages can be found in our [Localization folder](https://github.com/Microsoft/BotFramework-WebChat/tree/master/packages/component/src/Localization)

If the language you are looking to use is not there or incomplete, we would LOVE to have community participation with PR's add to our list. :) If you are interested and need help setting that up please let me know!
