### ISSUE TITLE
How do I pass user ID and userName to webchat?

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-WebChat#1724]
Hi, what is the syntax to pass user ID and username to webchat using JS? 

I tried the following:

        window.WebChat.renderWebChat({
            directLine: bot, 
            userID: 'MyID',
            username: 'MyName',
            locale: 'en',
            botAvatarInitials: 'VA',
            userAvatarInitials: userInitials,
            webSpeechPonyfillFactory: speechFactory
        }, document.getElementById('webchat'));

But I only get the ID and role (no name) on my bot:

        "from": {
            "id": "MyID",
            "role": "user"
          },

**Comment by corinagum** [comment]
Hi @gabog, this is a recent issue that was merged [only a week ago](https://github.com/Microsoft/BotFramework-WebChat/pull/1682/files). Your implementation looks good to me. 

Are you using `/lastest/` webchat.js? If so, adding the username isn't available yet. If you need this immediately, feel free to use the `/master/` CDN. Otherwise this will be available at our next release.

**Comment by gabog** [comment]
Thanks @corinagum, the issue doesn't repro on master. Is there a place where I can subscribe when this gets released so I can switch back to latest?

**Comment by corinagum** [comment]
Unfortunately we don't have any kind of feed right now... That's one of the things that's marked in our backlog on https://github.com/Microsoft/BotFramework-WebChat/issues/1399. 
I can tell you that the release is currently scheduled for the end of February, so I would hope that if you check back on March 1st, the release of 4.3 will be published.

**Comment by gabog** [comment]
OK @corinagum , I'll check back at the end of the month.

**Comment by grkrama** [comment]
@corinagum thanks for input on #1748 .. one recommendation.. when you fix it for username , don't limit with username, allow to add more name:value pair, because there few things which would be helpful to pass the value from html to bot framework...

**Comment by alokraj68** [comment]
is there a way to pass on custom data through the user object like it was possible before in v3?
