### ISSUE TITLE
ConversationUpdate is sent three times by webchat (in master), 1 time in latest and 2 times from BF emulator

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-WebChat#1728]
Hello, we rely in conversationUpdate messages to determine when to display a startup dialog in a bot. 

When I use webchat from latest, I only get 1 conversation update from web chat when it is first instantiated and the next one comes in after the user replies to the bot (these conversationUpdate messages have the From.Id set to the conversation ID and my bot UserState doesn't initialize correctly)
    
This is the first one I get:

    {
      "type": "conversationUpdate",
      "id": "1h7J5qlalUW",
      "timestamp": "2019-02-14T04:57:04.8015595Z",
      "serviceUrl": "https://directline.botframework.com/",
      "channelId": "webchat",
      "from": {
        "id": "B4BRLkxLHNzHlKrWrgaS7V"
      },
      "conversation": {
        "id": "B4BRLkxLHNzHlKrWrgaS7V"
      },
      "recipient": {
        "id": "ggdebugbot@PRhfE5WcFpk",
        "name": "GGDebugBot"
      },
      "membersAdded": [
        {
          "id": "ggdebugbot@PRhfE5WcFpk",
          "name": "GGDebugBot"
        }
      ]
    }

And this is the one I get after the user says "hi" to the bot.

    {
      "type": "conversationUpdate",
      "id": "yLq6MQyyXl",
      "timestamp": "2019-02-14T04:57:51.9335913Z",
      "serviceUrl": "https://directline.botframework.com/",
      "channelId": "webchat",
      "from": {
        "id": "B4BRLkxLHNzHlKrWrgaS7V"
      },
      "conversation": {
        "id": "B4BRLkxLHNzHlKrWrgaS7V"
      },
      "recipient": {
        "id": "ggdebugbot@PRhfE5WcFpk",
        "name": "GGDebugBot"
      },
      "membersAdded": [
        {
          "id": "MyId"
        }
      ]
    }

When I use webchat from **master**, I get three conversationUpdate messages when webchat starts:
First

    {
      "type": "conversationUpdate",
      "id": "9jJfhyIJ2Xu",
      "timestamp": "2019-02-14T05:01:58.2108621Z",
      "serviceUrl": "https://directline.botframework.com/",
      "channelId": "webchat",
      "from": {
        "id": "6eYDl0hk5WSGnEZUIbHQ7V"
      },
      "conversation": {
        "id": "6eYDl0hk5WSGnEZUIbHQ7V"
      },
      "recipient": {
        "id": "ggdebugbot@PRhfE5WcFpk",
        "name": "GGDebugBot"
      },
      "membersAdded": [
        {
          "id": "ggdebugbot@PRhfE5WcFpk",
          "name": "GGDebugBot"
        }
      ]
    }

Second

    {
      "type": "conversationUpdate",
      "id": "KrbU3FdA132",
      "timestamp": "2019-02-14T05:01:58.4189387Z",
      "serviceUrl": "https://directline.botframework.com/",
      "channelId": "webchat",
      "from": {
        "id": "6eYDl0hk5WSGnEZUIbHQ7V"
      },
      "conversation": {
        "id": "6eYDl0hk5WSGnEZUIbHQ7V"
      },
      "recipient": {
        "id": "ggdebugbot@PRhfE5WcFpk",
        "name": "GGDebugBot"
      },
      "membersAdded": [
        {
          "id": "MyId",
          "name": "MyName"
        }
      ]
    }

Third

    {
      "type": "conversationUpdate",
      "id": "6eYDl0hk5WSGnEZUIbHQ7V|0000002",
      "timestamp": "2019-02-14T05:01:58.2782746Z",
      "serviceUrl": "https://directline.botframework.com/",
      "channelId": "webchat",
      "from": {
        "id": "MyId",
        "name": "MyName",
        "role": "user"
      },
      "conversation": {
        "id": "6eYDl0hk5WSGnEZUIbHQ7V"
      },
      "recipient": {
        "id": "ggdebugbot@PRhfE5WcFpk",
        "name": "GGDebugBot"
      },
      "membersAdded": [
        {
          "id": "MyId",
          "name": "MyName"
        }
      ],
      "locale": "en",
      "entities": [
        {
          "type": "ClientCapabilities",
          "requiresBotState": true,
          "supportsListening": true,
          "supportsTts": true
        }
      ],
      "channelData": {
        "clientActivityID": "15501205187010.2l0ssss5sp2"
      }
    }

So, we have several issues here:
1. The version in latest doesn't send the right From.Id until the user actually responds later on and it is keeping us from accessing the UserState in bot framework when the conversation starts.
2. The version in master sends what we eventually need in the third convesationUpdate messsage but I am not sure if this is the right behavior or not.
3. Master and Latest conversationUpdate messages are inconsistent with the bot BF Emulator sequence. Emulator sends two conversationUpdate messages, the first one with From.Id set to the conversation ID when the user is added to the conversation and the second one with From.Id set with the user ID when the bot is added to the conversation. 

The Emulator behavior works best for us but I think we can also work with the behavior we see from the Master branch but would like to know if we are seeing is right and that it will stay like that (3 conversationUpdate messages on startup).

Thanks

PS1: ping me internally if you need more info and I can share my desktop and walk you through the repro.
PS2: @darrenj, @ryanlengel & @lauren-mills FYI, this is why I believe webchat always displays the Onboarding dialog in VA, even when the user has already been initialized.

**Comment by corinagum** [comment]
@gabog, this is an ongoing discussion here: https://github.com/Microsoft/BotFramework-WebChat/issues/1371#issuecomment-461508847
Please feel free to bring your points up in that issue.

**Comment by compulim** [comment]
Background: in some points of time in `master` (not `latest`/`4.2.0`), we decided to synthesize a `conversationUpdate` so we believe it should fix some annoying issue. But last week, we discover it will create more confusion, and we are reverting our PR in #1685 (still open now, will merge very soon).

So in your 5 code snippets. Reverting our PR will cause the 5th snippet to go away. 1st to 4th snippet is from Direct Line platform and Web Chat has no control over them.

To answer your question:

1. The `from.id` is correct in `/latest/`. 1st-4th is from Direct Line platform, and the "from" is conversation ID, indicate this is a system message
2. We believe it is not a great idea. So we recommend people to use the method outlined in [sample 15.d](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event). It will send an event programmatically. On your bot side, you will receive a `from.id` that is usable for user state.
3. Yes. The behavior between Emulator and Direct Line is different. Emulator mimic Direct Line platform, and the issue is being tracked at [BotFramework-Emulator#643](https://github.com/Microsoft/BotFramework-Emulator/issues/643).
    a. In Direct Line spec, both behavior is correct (send early `conversationUpdate` and send later are both acceptable behavior)
    b. Direct Line platform behavior cannot be changed for some technical reason (I agree on you, aligning Direct Line platform is better)
    c. We will re-align Emulator behavior to reduce confusion
    d. Also on the spec, bot is supposed to dedupe `membersAdded`, but it is not obvious for most people, so we decided 3 `conversationUpdate` is not a great idea

Please do share your comment on #1371. We have lots of discussion recently on this issue.
