### ISSUE TITLE
How do I change the voice font to be used with WebChat?

### ISSUE THREAD

**Issue by gabog** [Microsoft/BotFramework-WebChat#1729]
In the previous version of webchat (v3), we were able to set the voice font the synthetizer would use ("Microsoft Server Speech Text to Speech Voice (en-US, Jessa24kRUS)", "Microsoft Server Speech Text to Speech Voice (en-US, Guy24kRUS)", etc.)

I don't seem to see that parameter in the current call to window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory in the new webchat.

How do I change the voice font?

**Comment by corinagum** [comment]
Hi @gabog, as far as I can tell this is a duplicate of your filed issue #1396. This feature is currently slated for our 4.4 release.

**Comment by gabog** [comment]
Hi @corinagum, #1396 is about the emulator, my request here was about webchat and JS, are these the same thing?

**Comment by corinagum** [comment]
@gabog, the changes will need to be made on Web Chat before they can be made on emulator. Thanks for asking. :)

**Comment by gabog** [comment]
ah, ok, thanks sorry for the noise, I see that both webchat and emulator are mentioned in the thread. Our main priority is emulator. 

Thanks
