### ISSUE TITLE
SEND_EVENT not working

### ISSUE THREAD

**Issue by xenflux** [microsoft/BotFramework-WebChat#1731]
Hello,

I am trying to trigger built-in welcome event when a user clicks chat button. I am using Dialogflow for the NLU platform. Latest webchat is not sending event request as shown in the sample. I followed [15.d.backchannel-send-welcome-event](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/15.d.backchannel-send-welcome-event/index.html) sample. Dialogflow has WELCOME event so I modifed the sample code as.

```
if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
    dispatch({
        type: 'WEB_CHAT/SEND_EVENT',
        payload: {
            name: 'WELCOME', //also tried webchat/welcome
            value: {
                language: window.navigator.language
            }
        }
    });
}
```

Also, i found directLine postActivity example which didn't work either (though i see trigger sent in console). Here is the postActivity code i am using,
```
directLine.postActivity({
        from: user,
        name: 'Welcome',
        type: 'event',
        value: ''
    })
    .subscribe(function(id) {
        console.log('"trigger requestWelcomeDialog" sent');
    });
```

Any suggestions?
**Note:** WEB_CHAT/SEND_MESSAGE is working fine.

**Comment by compulim** [comment]
Your code looks good to me. And I also tested sample `15.d` thru [the demo link](https://microsoft.github.io/BotFramework-WebChat/15.d.backchannel-send-welcome-event/) and looks good.

Few things to investigate:

1. Are you using `/master/webchat.js` build? The `SEND_EVENT` is not in `/latest/webchat.js` (production 4.2.0) yet. But only on `/master/`, a.k.a. dev build.
2. Open development tools, go to the network tab. Could you see a POST call to `/activities/` for your event activity?

**Comment by xenflux** [comment]
@compulim Thank you for the quick response. My responses below,
1. Yes, I tried both master and latest.
2. Yes, I see the POST call to /activities/. Here is the screenshot,
<img width="520" alt="screen shot 2019-02-14 at 12 13 06 pm" src="https://user-images.githubusercontent.com/47638187/52807850-3cfa5100-3052-11e9-82af-2c604700f93f.png">

Here is the network screenshot of the POST call,
<img width="862" alt="screen shot 2019-02-14 at 12 17 21 pm" src="https://user-images.githubusercontent.com/47638187/52808004-8ea2db80-3052-11e9-97b7-e171baa3ccd2.png">

**Comment by compulim** [comment]
Everything looks good to me too.

I assume one of the POST `/activities/` is your event, right?

Could you do 2 more investigations?

- Find the POST call that send the event. Could you screenshot/dump us the request payload?
- On your bot side, can you dump all activities in console.log to make sure it is not received?

**Comment by xenflux** [comment]
Right. 

- Here is the screenshot with request and response details for the POST sending event,

<img width="731" alt="screen shot 2019-02-14 at 12 46 21 pm" src="https://user-images.githubusercontent.com/47638187/52810025-3de1b180-3057-11e9-90e7-d49f3f6f53f3.png">

- Since I am using Dialogflow for the NLU platform, I can't access bot side code and can't see backchannel activities (as far as i know).

**Comment by compulim** [comment]
Sorry got caught from something this afternoon.

It seems this screenshot does not have the POST body. For example, this is one I captured from Chrome on my side.

![image](https://user-images.githubusercontent.com/1622400/52831012-d001ae00-3087-11e9-9f3c-59f2bb661b46.png)

I am new to Dialogflow for the NLU platform. Do you have any pointer I can take a quick look at it and understand the issue?

**Comment by xenflux** [comment]
@compulim No worries :) 

Sorry, Firefox shows it differently. Here is the screenshot with params captured on Firefox,

<img width="323" alt="screen shot 2019-02-15 at 9 24 17 am" src="https://user-images.githubusercontent.com/47638187/52866168-baca6500-3103-11e9-9ca7-f3a172b01528.png">

I understand. Here is the documentation on Dialogflow's events [Dialogflow Events](https://dialogflow.com/docs/events). Basically, I am trying to trigger Dialogflow's built-in WELCOME event. I was able to get the welcome event response via POST without using webchat but I don't know how to dump that into webchat (or if it is even possible). Here is the link to Dialogflow's API I used to send the event request outside webchat [Dialogflow API](https://cloud.google.com/dialogflow-enterprise/docs/reference/rest/v2/projects.agent.sessions/detectIntent?apix_params=%7B%22session%22%3A%22projects%2Fyullie%2Fagent%2Fsessions%2F12345678%22%2C%22resource%22%3A%7B%22queryInput%22%3A%7B%22event%22%3A%7B%22name%22%3A%22WELCOME%22%2C%22languageCode%22%3A%22en-US%22%7D%7D%7D%7D)

I am not sure if this will help you but I really like webchat and would like to see it working completely on more platforms other than Microsoft's native platform. Please let me know if you need further information. You're doing a great job. Keep it up :)

**Comment by xenflux** [comment]
Hi @compulim, were you able to find anything?

**Comment by compulim** [comment]
😵 Love to make it work. Challenge accepted. 💪

So, you want to send a custom POST request, via Web Chat, to Dialogflow API. And the POST request looks like,

```json
{
    "queryInput": {
        "event": {
            "name": "WELCOME",
            "languageCode": "en-US"
        }
    }
}
```

Is that correct?

I am a bit disconnected here. You want to use Web Chat to connect to Dialogflow platform, that talk a totally different protocol, right? And if they are different protocol, why "SEND_MESSAGE" currently work in your case?

If you want to use Web Chat to connect to third party services, the easiest way is to implement your own DLJS, and you need to implement [some API listed in this `interface`](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L381), minimally:
- `connectionStatus$` is an ES Observable (prefer `core-js` over `rxjs`)
   - 0 = Not connected
   - 1 = Connecting
   - 2 = Connected
- `activity$` is an ES Observable
   - When subscribed, start your connection
   - Emit activities when they arrive
- `end` is optional
- `referenceGrammarId`, is for speech, not used in your case
- `postActivity()` will return an ES Observable on send activity success
   - `{ id: "id-of-the-activity-sent" }`
   - Web Chat using different logic to measure if an outgoing activity successfully send or not
      - This observable must return positive result
      - The activity sent over the wire, will need to be echo-ed back from the remote service, and checked against the content of `channelData`
- `getSessionId()`, is for OAuth, not used in your case

**Comment by dividor** [comment]
@compulim Just to note - this feature works perfectly for me in the dev branch, thanks!  Looking forward to its release.

**Comment by xenflux** [comment]
@compulim I want the SEND_EVENT to work with Dialogflow, not send the POST request (POST was just an example to give you an idea on how i got the WELCOME event response). Everything on webchat seems to be working fine with Dialogflow except SEND_EVENT and i was wondering if you could find anything related to that.

So there is not possible? and no simple way to achieve this?

**Comment by xenflux** [comment]
@dividor What are you using for NLU platform? Is it Dialogflow?

**Comment by compulim** [comment]
Sorry I am completed booked until late April.

If anyone able to pick this one up, please investigate how to use Dialogflow with Bot Framework and Web Chat.

**Comment by imrankhankasim** [comment]
@compulim and @xenflux :- Exactly same am too expecting. (Dialogflow NLP and UI to be Microsoft Bot framework) But from my side I have been developed like this. Refer the link for your reference. 
https://typescript-v97enh.stackblitz.io/ 
But actual I need bot has to trigger first in the microsoft webchat where NLP is from Dialogflow.

If any one fixed please share me the information thanks.

**Comment by corinagum** [comment]
per @Kaiqb, I am closing this issue since we do not have a plan to support DialogFlow in the near future. Thank you!
