### ISSUE TITLE
Severe UI issues on Chrome and Safari

### ISSUE THREAD

**Issue by xenflux** [Microsoft/BotFramework-WebChat#1732]
Hello,
UI looks fine on Firefox but completely messed up on Chrome and Safari, I'm using latest webchat. Below are some of the examples with screenshots attached.

- **Type your message** text is not centered vertically which looks ok in Firefox but hides send box's top border in Chrome and Safari.

**Firefox screenshot**:
<img width="406" alt="firefox_type_your_message" src="https://user-images.githubusercontent.com/47638187/52802514-b6d80d80-3045-11e9-9e75-22a77f4183b7.png">
**Chrome screenshot**:
<img width="407" alt="chrome_type_your_message" src="https://user-images.githubusercontent.com/47638187/52802688-0e767900-3046-11e9-9f35-dd54a50142bb.png">

- Button looks fine in Firefox (default button background appear as white) but it is huge in Chrome and Safari (default button background appear as gray).

**Firefox screenshot**:
<img width="409" alt="screen shot 2019-02-14 at 10 39 13 am" src="https://user-images.githubusercontent.com/47638187/52802855-5eedd680-3046-11e9-9ee3-619228320a9f.png">
**Chrome screenshot**:
<img width="387" alt="screen shot 2019-02-14 at 10 40 23 am" src="https://user-images.githubusercontent.com/47638187/52802883-6a410200-3046-11e9-8283-6a0cbd793b1a.png">

I played a little with styles on Chrome and turning off `flex` seems to fix it as shown below,

<img width="646" alt="screen shot 2019-02-14 at 10 40 42 am" src="https://user-images.githubusercontent.com/47638187/52803213-37e3d480-3047-11e9-910c-0e9143ca9d0e.png">

Thoughts?

**Comment by corinagum** [comment]
Hi @xenflux, please see workaround at https://github.com/Microsoft/BotFramework-WebChat/issues/1228

**Comment by xenflux** [comment]
@corinagum Thanks. Seems like [#1228 ](https://github.com/Microsoft/BotFramework-WebChat/issues/1228) is for the button UI issue and doesn't mention 'Type your message' UI issue. I'll open another issue.
