### ISSUE TITLE
Duplicate welcome message for Direct Channel

### ISSUE THREAD

**Issue by andybeak** [Microsoft/BotFramework-WebChat#1734]
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 03.welcome-users

## Describe the bug
The problem described at https://blog.botframework.com/2018/07/12/how-to-properly-send-a-greeting-message-and-common-issues-from-customers/ occurs when using the sample code with the example provided at https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event

The effect of this is that the bot issues two welcome messages.

The problem is because DirectChannel sends two ConversationUpdate messages, which results in two welcome messages.  The local emulator squashes this.

## To Reproduce
1. Install the sample at https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event
2. Install 03.welcome-users
3. Connect via ngrok
4. See that you get two welcome messages when you load the html page

## Expected behavior
I expect to see just one welcome message displayed when loading the html page

## Additional context
I asked for help on StackOverflow (https://stackoverflow.com/questions/54443597/microsoft-botframework-webchat-is-getting-two-welcome-messages)

The advice given there is very difficult to fit into the pattern supplied in the samples.  I couldn't work out how to catch the event since my bot class does not have an "on" method.

## Workaround

Check for the presence of entities in the conversation update

`if (typeof turnContext.activity.entities != 'undefined') {`

Doing this breaks the view for the emulator, so you also need to check for an emulator specific channel:

`if (typeof turnContext.activity.entities != 'undefined' || turnContext.activity.membersAdded[0].name == 'User') {`

In context this looks like: 

```
if (turnContext.activity.membersAdded.length !== 0) {
    // Iterate over all new members added to the conversation
    for (var idx in turnContext.activity.membersAdded) {
        if (typeof turnContext.activity.entities != 'undefined' || turnContext.activity.membersAdded[0].name == 'User') {
            if (typeof turnContext.activity.entities != 'undefined') {
                // only users have got the entities key                            
                await dialogContext.beginDialog(MASTER_DIALOG)
            }
        }
    }
}
```

[bug]

**Comment by compulim** [comment]
Anyone free to pick up this one?

Investigate how our `15.d` interact with [Bot Builder sample `03`](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/03.welcome-users).

Because we have recently going back-and-forth about the topic (dupe `conversationUpdate` or not), so it might already fixed or not. If not, we probably need to update `03` to match the latest behavior (Web Chat should send an event to the bot to indicate Web Chat is connected, then the bot send welcome message, once.)

**Comment by cwhitten** [comment]
We believe this is addressed in https://github.com/Microsoft/BotFramework-WebChat/issues/1371. Please re-open if this is still an issue on WebChat >4.3.3
