### ISSUE TITLE
Message content scrollbars not appearing and input box disappearing off the bottom of the page

### ISSUE THREAD

**Issue by squarenotch** [Microsoft/BotFramework-WebChat#1738]
When using the sample code: 

```
<!DOCTYPE html>
<html>
  <body>
    <div id="webchat" role="main"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <script>
      window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ token: 'YOUR_DIRECT_LINE_TOKEN' }),
        userID: 'YOUR_USER_ID'
      }, document.getElementById('webchat'));
    </script>
  </body>
</html>
```
The scrollbars displayed are on the outside of the entire webchat and not just the messages window. Also the input box seems to be aligned to the top of the page and moves down with the messages until it disappears off the bottom of the page. [
![issue2](https://user-images.githubusercontent.com/16525324/52944398-35df8580-3367-11e9-8c30-d61c22d5d03a.png)
![issue1](https://user-images.githubusercontent.com/16525324/52944400-35df8580-3367-11e9-85e7-5de8d707c16e.png)

](url)

**Comment by corinagum** [comment]
@squarenotch could you share your #webchat container's css? Since you are using `/latest/` CDN, not assigning 100% height and width to the `<div>` may cause styling issues. 

If you don't mind, could you try temporarily changing to `/master/` bits and see if you still get the same errors? Please see this [related PR](https://github.com/Microsoft/BotFramework-WebChat/pull/1702). This version should have the fix in, but if not let's investigate further.

**Comment by squarenotch** [comment]
@corinagum Thank you! Setting the #webchat container to 100% width and height along with using the master branch fixes the problem! We would like to use the Microsoft CDN. Is there any estimation on when the latest version will be available?

**Comment by corinagum** [comment]
@squarenotch glad we figured it out. :) Our 4.3 release is scheduled for public availability at the beginning of March. We don't have a feed announcing our releases yet, but if you could check back March 1 or so, `/latest/` should be updated with the 4.3 release and the styling fixes linked above. 

Closing this issue, but please let me know if you have any questions.

**Comment by dnyati** [comment]
Facing the same issue. Is this resolved?
