### ISSUE TITLE
Suggested actions with image/icon

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/BotFramework-WebChat#1739]
Any way or plans to add images to suggested actions buttons?

Something similar to Facebook Quick Replies

![image](https://user-images.githubusercontent.com/7627975/52945248-2e20e080-3369-11e9-99b9-3ac39f0ec482.png)

Currently I'm trying to set the Image property of the CardActions given to the SuggestedActions but without success.

**Comment by corinagum** [comment]
Hey @AndreMantas, great question. I'm not actually sure -- [Mock Bot](https://github.com/compulim/BotFramework-MockBot/blob/master/src/commands/SuggestedActionsCard.ts#L43) has suggested actions with images but there is [no support to display them](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/SendBox/SuggestedActions.js#L49) on Web Chat. 
@compulim, do you have any insight?

**Comment by corinagum** [comment]
@AndreMantas, I had an offline conversation with @compulim about this - Web Chat does not currently support images in suggestedActions, but this is something that the team does want implemented. I'm going to use this issue to track the work for that. :) Please let us know if you have any questions.

**Comment by AndreMantas** [comment]
Awesome! When will we see this live?

**Comment by corinagum** [comment]
You can use this live immediately by switching to the `/master/` bits. If you'd prefer to wait for the official release, the next update is planned for end of April.
