### ISSUE TITLE
ScrollToEndButton causes page to refresh

### ISSUE THREAD

**Issue by Jhanbury** [Microsoft/BotFramework-WebChat#1741]
### Problem
I'm using the master build for web chat at the moment and I have noticed that clicking the ScrollToEndButton causes the parent webpage to refresh.

However, I cannot reproduce on 4.2.0, so I think its just affecting the master build.

![image](https://user-images.githubusercontent.com/11406932/53031044-f185df80-3463-11e9-8f18-14c41d49f0ef.png)

### Temporary Workaround
I have a workaround for now by doing the following:

        var parentContainer = document.getElementById('{webchatid}');

        parentContainer.addEventListener('click', (event) => {
            var isScrollToEndButton = event.target.nodeName === 'BUTTON' && event.target.className === '{scrolltoendclass}';
            if (isScrollToEndButton) {
                event.preventDefault();
            }
        });

However, I don't think this is a viable workaround going forward.

@compulim I see that the scrollToEndButton uses your react-scroll-to-bottom library for this feature.
What do you think?

**Comment by corinagum** [comment]
@Jhanbury thanks for filing this. :) It looks like the scrollToEndButton was missing a type="button" in PR https://github.com/Microsoft/BotFramework-WebChat/pull/1743
