### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by kevinclarkneudesic** [Microsoft/BotFramework-WebChat#1742]
This is 2019 and this is an official Microsoft library.  Why is it not written in TypeScript.  Especially if other pieces of your framework like botframework-directlinejs (https://github.com/Microsoft/BotFramework-DirectLineJS) are written in TypeScript.  This makes it much harder to integrate into a modern React/TypeScript project.  I actually have to go in your source code to see how to use different pieces of this library.  Thanks.

**Comment by kevinclarkneudesic** [comment]
Also all the demos are in vanilla JS...which is great if you know the library intimately or if there are a lot of comments in the code....which there AREN'T....it is no helpful having samples that only the writers of the code understand.  I.e. https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/13.customization-speech-ui/src

**Comment by compulim** [comment]
Few things:

- Although we are from Microsoft, that doesn't preclude us to use JavaScript
- Most packages we are using, UI or not UI, are not TypeScript with the exception of
   - `adaptivecards` is pure TypeScript, done by another Microsoft team
   - `microsoft-speech-browser-sdk` is pure TypeScript, also done by another Microsoft team
   - `typescript`, is of course, written in TypeScript
   - `redux-saga` is JavaScript, with manually written `.d.ts`
   - Only 3 out of 56 packages, we depends on, or 5.4%, are written in TypeScript
- We don't see a good number of UI projects, except Angular, that are using TypeScript intensively
- We are having ongoing discussions right now, on improvements we could make to our documentations
   - Internally, we are still deciding if we should go typing files (`.d.ts`), or write `README.md`/`API.md`

For samples, we have intensive documentations on `README.md` of each sample and intensive comments inside critical part of code. So I don't agree that "only the writers of the code understand." Specifically for sample 13, as you pointed out, there is [a README.md](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/13.customization-speech-ui) that can be printed into *8 pages of paper* and *12 code blocks with verbal explanations*. Not to mention, the `README.md` is not written by the original author of the sample code.

We are more than happy to discuss improvements to our samples if you have specific feedback.

**Comment by kevinclarkneudesic** [comment]
LOL.  All good dude... you are probably one of those JavaScript devs like Dan Abramov who have never even used TypeScript so you don't understand the benefits, ESPECIALLY when creating a library that is 3rd party.  Your own internal applications, go nuts, but when you are creating a library that is an official Microsoft library trying to get users to adopt the bot framework you should make it easier on the consumers.  Luckily I could avoid using this library by using Directline which is TypeScript with the Speech SDK (https://github.com/Microsoft/cognitive-services-speech-sdk-js/tree/master/src/sdk) which is also written in TypeScript.  

In terms of "* We don't see a good number of UI projects, except Angular, that are using TypeScript intensively" ...well, clearly you need to get outside of your bubble more often.  TypeScript with React or Preact is infinitely better, like I can't describe how nice it is having strongly typed JSX.  It's better than Angular who just uses HTML templating.  Anyways thanks for making me waste a few hours of my day trying to understand this train wreck of a library, peace

**Comment by pro-panda** [comment]
Hi @compulim,

Any updates on moving to / supporting TypeScript?

**Comment by kevinclarkneudesic** [comment]
> Hi @compulim,
> 
> Any updates on moving to / supporting TypeScript?
LOL judging by his response absolutely not.  I don't even care if they write it in TypeScript, but these days they need to provide  TypeScript defs or help the community to get them written.  @compulim  is in a bubble though, he probably has only used Flow.

**Comment by pro-panda** [comment]
@kevinclarkneudesic please be polite. You've directed the conversation off-topic.

@compulim let us know in case there are any future plans on this, Thanks
