### ISSUE TITLE
Passing User Data from HTML to chat bot

### ISSUE THREAD

**Issue by grkrama** [Microsoft/BotFramework-WebChat#1748]
hi, 
I am trying to pass few user specific value to bot framework.
except 'userID' I am not able to pass few other important user data to chat bot framework. 
In other directline i can send some thing like this 

user: { id: 'test', name: 'john doe', region: 'US'}

I may have miss some parameter, can you suggest is there anyway i can send it using this directline code. 
Also where can i find the list of parameter which can be passed from HTML to chat.

**Comment by corinagum** [comment]
userID, username and locale can be indicated within the rending of the Web Chat object.

```
window.WebChat.renderWebChat({
  username: 'John Doe',        
  userID: 'test',
  locale: 'en-US',
}, document.getElementById('webchat'));
```

You can take a look at #1724 for more information. This isn't on `/latest/` bits yet so you will need to use `/master/` Hope that helps!
