### ISSUE TITLE
how should we display attachmentLayout 'list'?

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#175]
attachmentLayout 'carousel' correctly displays attachments horizontally, but currently 'list' (which is the default) just appends them together into the message, wrapping as necessary. This is particularly ugly when an attachment is a non-displayable format, because we wrap the text "[File of type 'foo/bar']". Should the 'list' layout be strictly vertical?

**Comment by pfloresl** [comment]
where do i pass attachmentLayout to the iframe that's hosted in MS?.

**Comment by billba** [comment]
@pfloresl attachmentLayout is a property of messages sent by the bot.

**Comment by billba** [comment]
Each attachment wraps within the available space.
