### ISSUE TITLE
ChoicePrompt Slider Button causes page refresh

### ISSUE THREAD

**Issue by Jhanbury** [Microsoft/BotFramework-WebChat#1759]
## Issue

seems very similar to #1741 

The slider buttons for the choice options are causing the page to be refreshed.

![image](https://user-images.githubusercontent.com/11406932/53408818-66529f80-39b7-11e9-99f8-73aa67d67ebf.png)

I'm currently using the master branch.

**Comment by corinagum** [comment]
@Jhanbury thanks for reporting this! I'll investigate and get back to this issue asap.

**Comment by compulim** [comment]
Will be fixed when we bump to `react-film@1.2.0`.

@corinagum could you help?
