### ISSUE TITLE
Sample : Customization minimizable-web-chat Adaptive card Markdown issue

### ISSUE THREAD

**Issue by deepanigi** [Microsoft/BotFramework-WebChat#1761]
Hi All,

I am trying to run the sample minimizable react app in my local environment. I am getting the following error.

> Error: The processMarkdown event has been removed. Please update your code and set onProcessMarkdown instead.

![image](https://user-images.githubusercontent.com/31543067/53420784-bbed7300-39dc-11e9-910a-b3c32c7eb718.png)

How can I set the Markdown in this react app?

Sample link 

[https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat)

**Comment by corinagum** [comment]
Hi @deepanigi, 

Please see this issue: https://github.com/Microsoft/BotFramework-WebChat/issues/1722#issuecomment-465695873

This fix should now be released in the `/master/` bits. Please reply here if you find otherwise, and we can investigate further.
