### ISSUE TITLE
Words or links that are longer than the text box is wide don't wrap in message boxes

### ISSUE THREAD

**Issue by RAHarris** [Microsoft/BotFramework-WebChat#1774]
Repro steps: go to the demo page https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/ and for the user message type "https://subdomain.domain.com/pathname0/pathname1/pathname2/pathname3/pathname4/". The last part of the URL doesn't show up in the user or bot message boxes.

This could be fixed by adding "word-break: break-all;" as a style to .row.message elements

**Comment by corinagum** [comment]
Thanks for reporting this find. 

![image](https://user-images.githubusercontent.com/14900841/53987123-f047ea00-40d4-11e9-8be8-f2895ddc4240.png)

To clarify for the fixer, the string must have no spaces for it to repro on (a) word. There seems to be a max of about 70-80 characters before the string gets cut.

**Comment by compulim** [comment]
I tested the following HTML code:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
  </head>
  <body>
    <p>https://subdomain.domain.com/pathname0/pathname1/pathname2/pathname3/pathname4/</p>
  </body>
</html>
```

It is not wrapped, but scrolled/clipped. I would prefer to follow default behavior of HTML.

So I would prefer to either:

1. Keep it as-is (clipped)
2. Add a scroll bar inside the bubble

On the other hand, if you prefer `word-break: break-all`, you can set it thru `styleSet`.

**Comment by corinagum** [comment]
@mewa1024  and @DesignPolice, do we have a design preference on whether the text of URLs is clipped, scrolled, or wrapped? It looks like @compulim's preferred way is to keep it clipped.

**Comment by mewa1024** [comment]
@corinagum I don't have a strong preference off the top of my head, but I think enabling the user to word-break by customizing WebChat seems fine as a P1. Sometimes truncation has a tooltip that shows the full value, but that would only for links, not for reallylongwordsthatarenotlinksandthereforehavenohoverstatetooltips.

**Comment by corinagum** [comment]
Thanks for the input. Temporarily assigning @compulim so he can add in a rebuttal, if he wishes.

**Comment by compulim** [comment]
Agree with @mewa1024, tooltip is tricky here:

- Tooltip can be added everywhere in HTML using `<span title="This is tooltip">pneumonoultramicroscopicsilicovolcanoconiosis</span>`
- But we can't easily differentiate which area need to add tooltip (no clear boundary)
- Conclusion, can't add tooltip

I see Teams is also breaking up long words. Didn't check other messaging apps yet.

I am okay to add a `styleOptions`:

- `messageActivityWordBreak` can be set to `normal`, `break-all`, or `keep-all`,  based on the [equivalent CSS style](https://css-tricks.com/almanac/properties/w/word-break/). Default is `normal`.

**Comment by corinagum** [comment]
Going with `break-word` -- better experience overall
