### ISSUE TITLE
IFrame version of webchat provides the same user id

### ISSUE THREAD

**Issue by rosskyl** [Microsoft/BotFramework-WebChat#1775]
I am using the IFrame version of the web chat (https://webchat.botframework.com/embed/{bothandle}?s={secret}) and am trying to count the number of users. The messages always show that they are from the same user "LnCq57Xe5Zd".

**Comment by corinagum** [comment]
Hi @rosskyl, if a user id is not specified in the embed code, the user id will be generated and saved to the browser's cookies. The next time the bot is loaded in the browser, the user id will be recycled. If you need to work around this please feel free to generate a new user id every time.
```
BotChat.App({
    directLine: { secret: direct_line_secret },
    user: { id: generatedID },
}, document.getElementById("bot"));
```

**Comment by rosskyl** [comment]
How do I specify the user id with an iframe though? I am adding it using the below code.

`<iframe src="https://webchat.botframework.com/embed/mybot?t=mytoken"></iframe>`

**Comment by corinagum** [comment]
My apologies, I totally provided you the wrong code >.<

You can specify the user id through embed like so:

```
 <iframe src="https://webchat.botframework.com/embed/mybot?t=mytoken&username=rosskyl&userid=rosskyl123"></iframe>
```

Please keep in mind that for security reasons we don't recommend this since anyone could find the userID and impersonate the original user.

**Comment by rosskyl** [comment]
Thank you. I still feel this should be fixed. At least with v4 of webchat if you don't specify a user id it generates one randomly.

**Comment by corinagum** [comment]
If you are able to bump to v4 I absolutely recommend it! Please let us know if we can support you in doing so. 
Thanks for the feedback. Unfortunately v3 is in sunset right now, and most of our resources are being spent on improving v4.

**Comment by rosskyl** [comment]
Do you know if or when the iframe version will be switched to v4?

**Comment by corinagum** [comment]
That's one of our major ticket items for the next release. Please keep an eye on #1086 to track this issue. We're very excited about it!

**Comment by hshahbaz** [comment]
Has this issue been solved? @corinagum

**Comment by hshahbaz** [comment]
i am experiencing the same issue. I am saving user chat in a table and every time I get the User id hence it is difficult to differentiate between chats. I do not experience this issue if I use Direct Line
