### ISSUE TITLE
hideUploadButton=true does not work

### ISSUE THREAD

**Issue by wiazur** [Microsoft/BotFramework-WebChat#1776]
I confirmed with another developer in addition to my own experience, that this option does not work. All of my other style options do, though.

Sample usage:

```
      const styleSet = window.WebChat.createStyleSet({
        bubbleBackground: 'rgba(252, 229, 53, 1)',
        bubbleFromUserBackground: 'rgba(4, 234, 104, 1)',
        paddingRegular: 10,
        sendBoxHeight: 50,
        bubbleMinWidth: 400,
        bubbleMaxWidth: 700,
        microphoneButtonColorOnDictate: '#FF00FF',
        hideUploadButton: true
      });
```

**Comment by B7A9F** [comment]
I confirm also that hideUploadButton does not work.

However, the button may be hidden in the following way : 

`const styleSet = createStyleSet({
 });`

`styleSet.uploadButton = { ...styleSet.uploadButton,
  display: 'none'
};`
...
`render() {`
`    return (`
`      <ReactWebChat styleSet={styleSet}   directLine={ this.directLine } userID="" />);
`  
`}`

**Comment by xenflux** [comment]
@wiazur `hideUploadButton: true` is working fine for me (screenshot below). Are you using production build - /latest/webchat.js ? . It may not be in production build yet. Try using dev build - /master/webchat.js

<img width="402" alt="screen shot 2019-03-01 at 10 39 35 am" src="https://user-images.githubusercontent.com/47638187/53652537-c1320400-3c0e-11e9-941b-411a70eb7d9e.png">

**Comment by wiazur** [comment]
Thanks @xenflux that worked! It gott rid of my other webchat formatting, but this will be great until it reaches production. Do you know when that might be? I can share this with my team. Thanks.

**Comment by xenflux** [comment]
@wiazur Great! Glad that helped. Regarding when it'll be in production, that would be something @compulim or @corinagum can answer.

**Comment by corinagum** [comment]
This is now released in `/latest/`! Thanks for the help @xenflux

**Comment by cihadturhan** [comment]
Hi, this seems to be broken when I pull the script from 
`https://cdn.botframework.com/botframework-webchat/latest/webchat.js`

Can you reopen the issue?
