### ISSUE TITLE
Questions about translations

### ISSUE THREAD

**Issue by pekspro** [Microsoft/BotFramework-WebChat#1777]
I’m considering contribute with some translations but I’m having a couple of questions first:

* In which context are **Tax** and **VAT** used? Some samples would be appreciated. I’m a bit surprised finding strings like this in the project :-)
* Should the functions **botSaidSomething** and **userSaidSomething** be translated? I only see them used in [en-US.js](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Localization/en-US.js).
* Should **Adaptive Card parse error** and **Adaptive Card render error** be translated?
* Is **Right** used for the direction, or does it mean ‘Correct’?
* How is **Speak** used? Is this some trigger for a text-to-speech service, or is it a call to the user to say something?

**Comment by corinagum** [comment]
@pekspro Thanks for asking, we welcome localization support from our community, so please feel free to make a PR when you are ready!

- Tax/VAT (Value Added Tax) are used for receipts and monetary calculations that may include state/federal tax. I believe another term would be 'consumption tax'. I know that in some countries like in the tax is calculated into the price of the object and the calculation is not necessarily shown on the receipt.
- Yes, these are currently only available in `en-US`, but the will need to be localized into as many languages as possible! Any support you can provide in this area would be much appreciated. This is for accessibility - When Narrator reads out the content of the transcript, we override the somewhat confusing default spoken text and use these two strings instead.
- Yes - Even though there's only Russian and English right now, I believe these strings will still help a user figure out what's going on if there's an error.
-  This is 'Right' like 'Left and Right' - used by the narrator when focused on the carousel buttons
- Speak is similar to directly above - if the Narrator is focused on the Microphone button, the computer will say 'Speak button'

Hope that helps!

**Comment by pekspro** [comment]
Thanks for the clarifications. Translation was easy :-) Created #1797.
