### ISSUE TITLE
Is it possible to customize the color of the subtitle of a ThumbnailCard?

### ISSUE THREAD

**Issue by pekspro** [Microsoft/BotFramework-WebChat#1778]
I’m sending a **ThumbnailCard** to my users, with a title, subtitle and buttons. The title has the color defined in **bubbleTextColor**, but the subtitle always has color **rgb(102,102,102)**. Is it possible to change this? I have tried both **suggestedActionTextColor** and **suggestedActionDisabledTextColor** but these didn’t affect this. It not, I would prefer **bubbleTextColor** is used.

I’m using https://cdn.botframework.com/botframework-webchat/master/webchat.js

**Comment by corinagum** [comment]
Related to #1259

**Comment by corinagum** [comment]
I'm going to close this issue: Right now the team is in favor of moving Rich Cards away from Adaptive Cards. Please refer to #1259. Thank you!
