### ISSUE TITLE
Console errors while sending message from Microsoft Edge

### ISSUE THREAD

**Issue by abishekreddy** [Microsoft/BotFramework-WebChat#1791]
We see the following errors on the browser console while sending a message from Microsoft Edge:
1) Unable to get property 'isPersonal' of undefined or null reference
2) Unable to get property 'SavePersonalAndPaymentData' of undefined or null reference

Screenshot:

![image](https://user-images.githubusercontent.com/24618556/53789933-b0a1c680-3f4b-11e9-87c1-6faf33add58d.png)

Repro steps:
1) Open the mockbot on Microsoft Edge: https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/
2) Open developer tools > console.
3) Start typing something on the webchat.
4) You will see the "Unable to get property 'isPersonal' of undefined or null reference" error on the console.
5) Click send or press enter.
6) You will see the "Unable to get property 'SavePersonalAndPaymentData' of undefined or null reference" error on the console.

Note: 
1) We also see the errors while using the webchat-es5 cdn. 
2) We do not see these errors on Chrome.

**Comment by corinagum** [comment]
![image](https://user-images.githubusercontent.com/14900841/54623587-0fc20980-4a29-11e9-9521-9c827b5da1f0.png)

I believe this error is caused by the AutoFormFill extension in Edge, and not related to Web Chat.
