### ISSUE TITLE
Modify the payload to /directline/conversations/{id}/activities

### ISSUE THREAD

**Issue by thedrew12** [Microsoft/BotFramework-WebChat#1794]
I'm using the React component to work with the bot framework and I need to modify the `entities` array to send along more information when a user asks a question. Is this possible? I've been trying to work with the `activityMiddleware` prop, but that doesn't seem to work.

**Comment by thedrew12** [comment]
I found this example, https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/15.a.backchannel-piggyback-on-outgoing-activities/README.md, and that seems to work, but it seems like you should be able to tap into the `activityMiddleware` to do this instead of creating a store.

**Comment by corinagum** [comment]
Hey @thedrew12, `activityMiddleware` is for changing how Web Chat renders specific activities. This doesn't change how the activity is sent to the bot. Using 15.a.backchannel-piggyback-on-outgoing-activities and creating a new store is right. :)

**Comment by 576180** [comment]
hey, the community I am searching solution for an alternative to creating the store in piggy backing. I'm using react webchat speak service
