### ISSUE TITLE
How to handle Directline API errors

### ISSUE THREAD

**Issue by thedrew12** [Microsoft/BotFramework-WebChat#1796]
Occasionally I have gotten 500 errors from the directline API in regards to the bot has timed out or general error response. How do I go about handling those to display a helpful message to the user? I was thinking of tapping into this action `DIRECT_LINE/INCOMING_ACTIVITY`, but I don't know how the payload gets passed to the action.payload.activity. I'm using the ReactWebChat component to work with the bot.

**Comment by corinagum** [comment]
Hey @thedrew12 I think this is related to your other question where middleware only affects the rendering of activities, and doesn't affect how it's passed to the bot. So you could create UI for those errors but not affect how it is sent to the bot. Hope that makes sense, please feel free to add more questions and I can reopen this issue if necessary. :)
