### ISSUE TITLE
Stability issues with buttons

### ISSUE THREAD

**Issue by Carriebots** [Microsoft/BotFramework-WebChat#1799]
We are having problems with stability issues, where when clicking a button it 'sometimes' calls in another dialogue or fails completely. Buttons in cards and suggestion buttons. It is not replicable every time either. Any help or ideas would be greatly appreciated!

**Comment by corinagum** [comment]
Hi @Carriebots unfortunately we're going to need repro steps and / or screenshots or a video of the failure to help you out. What version of Web Chat are you using? Please provide as much detail as possible and we can try to help!

**Comment by Carriebots** [comment]
Hi @corinagum thanks for your response! We are using the latest version of web chat from CDN. I can't provide screenshots due to the confidential nature of the content within the bot, however, I hope the below helps explain a little better (see image attached too)!

The customer is in a dialogue and is presented with a carousel of cards. Each card has a button which will take the customer to the next step within the dialogue. However, sometimes we find that the button, when clicked, is calling a Q&A response. So it's like the text in the button, for example 'click here for more info' is being registered as user input and the bot is then searching through LUIS (failing) and going to Q&A rather than recognising it as a button instigating the next step in the dialogue. 

The bigger issue is, this is not replicated every time, maybe only one in 10 times!

Please let me know if you need anything else. Many thanks, greatly appreciate any help!
![Carousel card](https://user-images.githubusercontent.com/48440548/54447799-34c12e80-4742-11e9-803e-a2cbf074b8bd.jpg)

**Comment by Carriebots** [comment]
@corinagum here is a screenshot of an example of it failing again. 
![Button issue](https://user-images.githubusercontent.com/48440548/54449411-e4e46680-4745-11e9-9b1c-b4f16f0bb216.jpg)

**Comment by corinagum** [comment]
@Carriebots unfortunately this looks like a problem that we would need to dig into your code to figure out. If you are unable to share code publicly, are you willing to discuss this offline? Please feel free to email me v-corgum@microsoft.com
I will also be pulling @EricDahlvang in to help with this issue :) I can add him to our thread if I get an email from you. 

If you have App Insights on your bot that could also help a lot.

**Comment by Carriebots** [comment]
Hi @corinagum thank you so much for your response and offer to help. I have spoken with our dev and product owner, they think they may have had a breakthrough. However, if this doesn't work we'd love to see if you can help. Please leave it with me and I'll be in touch shortly. Many thanks again.

**Comment by corinagum** [comment]
Great, glad to hear the dev team got it figured out. Closing this issue.
