### ISSUE TITLE
How do I connect to a previous conversation

### ISSUE THREAD

**Issue by impactro** [Microsoft/BotFramework-WebChat#1800]
How do I connect to a previous conversation using the watermark?

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0

I need this to retrieve the conversation history that is always based on the same conversation.id

**Comment by corinagum** [comment]
Hi @impactro, unfortunately this isn't available quite yet -- the watermark and streamUrl parameters are missing in the DLJS constructor, but I have added them both in this PR: https://github.com/Microsoft/BotFramework-WebChat/pull/1817

Once the merge is in, please feel free to use it via `/master/` bits until our next release, 4.4 which is scheduled for mid-April. Thanks for reporting this one!
