### ISSUE TITLE
Can't get the chat window inside the main body

### ISSUE THREAD

**Issue by DanteNahuel** [Microsoft/BotFramework-WebChat#1807]
Hi
I'm trying to add the webchat in the main body but the chat window appears on top of the main body div's containers, overriding everything. The examples show how to use the bot code as a complete website, but I want to use it as a smaller chat popup window.
How should my HTML look like in order to fix this?

**Comment by corinagum** [comment]
Please take a look at our samples: [12.customization-minimizable-web-chat](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat)
