### ISSUE TITLE
es5 Cognitive speech in Bot Web chat not working in IE

### ISSUE THREAD

**Issue by Akkilz** [Microsoft/BotFramework-WebChat#1809]
Below code is working in Chrome not in IE, hope the my code is wrong...
Please guide me to resolve this issue.

Getting error in IE "Super expression must either be null or a function".

<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>

var webSpeechPonyfillFactory;
        var region = "westeurope";

        var authorizationToken;
        var directLineToken;

        window.fetch('/BotTest/GetBothToken', { method: 'POST' })
            .then(function (res) {
                return res.json();
            })
            .then(function (json) {
                authorizationToken = json.speechToken;
                directLineToken = json.directLineToken;

                window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({ authorizationToken: authorizationToken, region: region }).then(function (res) {
                    webSpeechPonyfillFactory = res;
                    return;
                }).then(function () {

                    window.WebChat.renderWebChat({
                        directLine: window.WebChat.createDirectLine({
                            token: directLineToken
                        }),
                        webSpeechPonyfillFactory: webSpeechPonyfillFactory
                    }, document.getElementById('webchat'));

                    document.querySelector('#webchat > *').focus();
                });
            });

**Comment by Akkilz** [comment]
My initial code was below but it was not working in both Chrome and IE

window.fetch('/BotTest/GetBothToken', { method: 'POST' })
            .then(function (res) {
                return res.json();
            })
            .then(function (json) {
                authorizationToken = json.speechToken;
                directLineToken = json.directLineToken;

                window.WebChat.renderWebChat({
                    directLine: window.WebChat.createDirectLine({
                        token: directLineToken
                    }),
                    webSpeechPonyfillFactory: window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
                        authorizationToken: authorizationToken,
                        region: region
                    })
                }, document.getElementById('webchat'));

                document.querySelector('#webchat > *').focus();
            });

Kindly please help me out to enable cognitive speech in es5 bundle.

**Comment by corinagum** [comment]
@Akkilz, I tried out the [Speech Services](https://microsoft.github.io/BotFramework-WebChat/06.c.cognitive-services-speech-services-js/) sample in IE by changing the CDN to `webchat-es5.js` with no problems. 
Could you verify you are using the correct speech token? Please keep in mind that Bing Speech and Speech Services are not compatible, and Bing Speech is deprecated. Therefore you will need to use Speech Services with v4 in order to have a speech bot.

**Comment by Akkilz** [comment]
Yes, I am using Cognitive Speech Service.

I am using windows 7 IE and this browser is not supported for speech but chat window should render.
Its not rendering due to js code break.

For now, have coded browser specific,  if its IE not enabling speech option, In chrome enabling the speech option.

which version of IE supports speech option ?

kindly let me know if any.

**Comment by corinagum** [comment]
Unfortunately we're only backwards compatible to Internet Explorer 11. Speech works on this version, but any version before that is not supported, whether speech or Web Chat in general.
