### ISSUE TITLE
Is it possible to disable text-to-speech while keeping speech-to-text?

### ISSUE THREAD

**Issue by Shariele** [Microsoft/BotFramework-WebChat#1816]
Hello!

I want to use speech-to-text in my webchat when pressing the microphone but not have it read out loud the answer from the bot. I have tried to delve into the code and customize what I think would change it but to no avail. Is there anyone with knowledge on the matter that can help me?

I provide an image below of the code I am using  to create the webchat, if you need something else please tell me. 

![code](https://user-images.githubusercontent.com/9655837/54440179-82d23400-473a-11e9-904a-91a8af2e77fd.png)

**Comment by Akkilz** [comment]
Even i am looking for the same, need to disable text reading (text to speech).
Kindly let me know if any options available.

**Comment by compulim** [comment]
Could you follow [the sample here (06.f)](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/06.f.hybrid-speech)?

This sample use browser-supported engine for speech-to-text, and Cognitive Services for text-to-speech.

In `index.html` line 54 and 55, instead of returning the engine/ponyfill, could you try to return a `null`/`undefined` instead?

If Web Chat is seeing a falsy value here, it should skip the text-to-speech part.

Please let us know if it works. Please also check if there are any JavaScript errors (it tries to speak with a `null` engine), if there are any, please capture and send it to us, it's a bug.

**Comment by Akkilz** [comment]
thanks for the suggestion, let me test and confirm you.
I am targeting in es5.js, hope it should work.

**Comment by Akkilz** [comment]
I am using es5.js and below code, not sure what I am missing..
Bot is rendering but no mike icon, looks like speech option is disabled.
Please guide me if I am doing wrong.

var webSpeechPonyfillFactory;
var createHybridPonyfillFactory = function () {

            return function (options) {
                // We are using two ponyfill factories to create two concrete ponyfills.
                var webSpeechPonyfill = webSpeechPonyfillFactory(options);
                // And we are merging the result from two different ponyfills.
                // We use browser-supported speech for speech-to-text, and Speech Services for text-to-speech.
                return {
                    SpeechGrammarList: webSpeechPonyfill.SpeechGrammarList,
                    SpeechRecognition: webSpeechPonyfill.SpeechRecognition,
                    speechSynthesis: null,
                    SpeechSynthesisUtterance: null
                };
            };
        };
var nonIECode = function () {

            webSpeechPonyfillFactory = window.WebChat.createBrowserWebSpeechPonyfillFactory();
            window.WebChat.renderWebChat({
                directLine: window.WebChat.createDirectLine({
                    secret: dlSecret
                }),
                webSpeechPonyfillFactory: createHybridPonyfillFactory
            }, document.getElementById('webchat'));

            document.querySelector('#webchat > *').focus();

        };

nonIECode();

**Comment by Shariele** [comment]
Thanks you! 
I will check it out and return at a later date when I've tested it thoroughly.

**Comment by Shariele** [comment]
@compulim Your solution works wonderfully. Thank you for your solution!

**Comment by corinagum** [comment]
Closing this as resolved. :) @Shariele if you have any tips or pointers for @Akkilz, please feel free to continue discussion here.

**Comment by Akkilz** [comment]
@Shariele : the above code is not working for me , es5.
Could you plz help me out with the code sample

**Comment by Shariele** [comment]
Hello @Akkilz. My code uses es6 but I will try to help you.

From the looks of it, you aren't providing an authorization token and region to the speech API. Perhaps that is the reason the microphone is not rendering since it can't authorize you using the speech services. 

I use the following code for creating the ponyfillfactory:


// hybrid speech 
async function createHybridPonyfillFactory({ authorizationToken, region }) {

    const speechServicesPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({ authorizationToken, region });
    const webSpeechPonyfillFactory = await window.WebChat.createBrowserWebSpeechPonyfillFactory();

    return options => {
      // We are using two ponyfill factories to create two concrete ponyfills.
      const speechServicesPonyfill = speechServicesPonyfillFactory(options);
      const webSpeechPonyfill = webSpeechPonyfillFactory(options);
      // And we are merging the result from two different ponyfills.
      // We use browser-supported speech for speech-to-text, and Speech Services for text-to-speech.
      return {
        SpeechGrammarList: webSpeechPonyfill.SpeechGrammarList,
        SpeechRecognition: webSpeechPonyfill.SpeechRecognition,
        // Turn text-to-speech on/off. Return null for off.
        // speechSynthesis: speechServicesPonyfill.speechSynthesis,
        // SpeechSynthesisUtterance: speechServicesPonyfill.SpeechSynthesisUtterance
        speechSynthesis: null,
        SpeechSynthesisUtterance: null
      }
    };
  };



And this code to render the webchat:

// Render web chat with microphone.

      window.WebChat.renderWebChat({
        webSpeechPonyfillFactory: await createHybridPonyfillFactory({ authorizationToken, region }),
        directLine: window.WebChat.createDirectLine({ token })
      }, document.getElementById('webchat'));


Which is basically the code you find in the sample compulin refered to.

**Comment by Akkilz** [comment]
I thought createCognitiveServicesSpeechServicesPonyfillFactory not required because, the aim is  
to disable the text to speech option.

It would be great If any options are available to specify in createBrowserWebSpeechPonyfillFactory, kindly let me know if any.

As you suggested I will try to do the same, the only problem is I have to use es5 (requirement).
Will update you after testing.

**Comment by Shariele** [comment]
Yes I tried disabling and also removing the synthesise options in createCognitiveServicesSpeechServicesPonyfillFactory in the webchat.js at first but didn't work. So maybe even if we use a SpeechServicesPonyfillFactory but don't provide the correct options it will run everything as default. So that is perhaps why returning null plays a part in this scenario.

**Comment by Akkilz** [comment]
I able to do this in es5 itself, thanks for the support and help.

**Comment by CKGrafico** [comment]
The easiest code that have worked for me
```
async createHybridPonyfillFactory({ subscriptionKey, region }) {
        const speechServicesPonyfillFactory = await createCognitiveServicesSpeechServicesPonyfillFactory({ subscriptionKey, region });

        return (options) => {
            const speech = speechServicesPonyfillFactory(options);

            return {
                SpeechGrammarList: speech.SpeechGrammarList,
                SpeechRecognition: speech.SpeechRecognition,
                speechSynthesis: null, // speech.speechSynthesis,
                SpeechSynthesisUtterance: null, // speech.SpeechSynthesisUtterance
            };
        }
    };
```

**Comment by steps371** [comment]
For future reference, the bot framework example that shows how to deal with this issue is here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/g.hybrid-speech
