### ISSUE TITLE
Move to functional components with React Hooks

### ISSUE THREAD

**Issue by Tosters** [microsoft/BotFramework-WebChat#1818]
Hi,
This is not really an issues, but is there any info on if there are plans to add react 17.0.0 dependency to webchat? As some of the lifecycle methods will be removed from react 17?
Thanks.

**Comment by corinagum** [comment]
Thanks for bringing this up! [Update on Async Rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

We actually have a note for this already in our code:  [`BasicWebChat.js`](https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/BasicWebChat.js#L39) but we can use this issue to track the topic as the team discusses it.

I did some research but haven't yet found a projected release date for React 17. However, `componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate` have already been introduced as 'unsafe' as of React 16.3.

**Comment by Tosters** [comment]
Hey, thanks for the reply.
I didn't quite understand if webchat itself will have dependency on react v17 (whenever it might be).
As it sounds more logical that you would follow react updates and won't stay on the 16.x.x version forever.

**Comment by corinagum** [comment]
We can do this at the same time we bump to React 17. :)

**Comment by corinagum** [comment]
List of update-able components:

| Component name                  | Class component    | Legacy lifecycle methods |
|---------------------------------|--------------------|--------------------------|
| AdaptiveCardAttachments         | :heavy_check_mark: |                          |
| AnimationCardAttachments        | :heavy_check_mark: |                          |
| CommonCard                      | :heavy_check_mark: |                          |
| HeroCardAttachment              | :heavy_check_mark: |                          |
| OAuthCardAttachment             | :heavy_check_mark: |                          |
| ReceiptCardAttachment           | :heavy_check_mark: |                          |
| ThumbnailCardAttachment         | :heavy_check_mark: |                          |
| FullReactWebChat                | :heavy_check_mark: |                          |
| BasicWebChat                    | :heavy_check_mark: | :heavy_check_mark:       |
| Composer                        | :heavy_check_mark: | :heavy_check_mark:       |
| Dictation                       | :heavy_check_mark: |                          |
| ConnectivityStatus              | :heavy_check_mark: |                          |
| UploadButton                    | :heavy_check_mark: |                          |
| CroppedImage                    | :heavy_check_mark: |                          |
| TimeAgo                         | :heavy_check_mark: | :heavy_check_mark:       |
| Timer                           | :heavy_check_mark: | :heavy_check_mark:       |
| Box                             | :heavy_check_mark: |                          |
| App.js                          | :heavy_check_mark: |                          |
| createDevModeActivityMiddleware | :heavy_check_mark: |                          |
| DebugAdaptiveCardAttachment     | :heavy_check_mark: |                          |
| JSONDebugView                   | :heavy_check_mark: |                          |
