### ISSUE TITLE
Need Help Connecting Bot and WebChat

### ISSUE THREAD

**Issue by forensicsguy20012004** [Microsoft/BotFramework-WebChat#182]
Just need some basic help. How do I hook up the WebChat with my bot? Currently for testing...my bot runs on [http://localhost:3978/api/messages] and I would like to point the WebChat to that location. How do I do that and what files do I need to configure this? Sorry...just getting up to speed with WebChat...so a noob. 

Thanks,
Matt

**Comment by forensicsguy20012004** [comment]
I can get the Bot Framework Emulator to interact with my bot but I want to do the same for the WebChat...I just do not know how to do it...again sorry for the ignorance.

**Comment by forensicsguy20012004** [comment]
Closing as it appears others are wanting the same thing an ngrok is the answer.

**Comment by billba** [comment]
I'll update the README to mention ngrok for the localhost case.

**Comment by forensicsguy20012004** [comment]
thank you so much

**Comment by forensicsguy20012004** [comment]
In the README or somewhere else...could you give an example of how to code that interaction with ngrok?

**Comment by billba** [comment]
I'll probably just link to this documentation in the bot tutorials: https://docs.botframework.com/en-us/node/builder/guides/core-concepts/

**Comment by forensicsguy20012004** [comment]
Cool that should work...if I run into something I always know where to come back for help :) 

thanks...matt
