### ISSUE TITLE
issues accessing the bot  directline, nothing happens when i run the index.html

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotFramework-WebChat#1821]
I followed the steps in the documentation, but when I tried to use it on my own published bot that is in Azure, nothing happens.

await fetch('https://mybot.azurewebsites.net/directline/token', { method: 'POST' });  

In fact I checked console and I got the following error messages:

Access to fetch at 'https://mybot.azurewebsites.net/directline/token' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

TypeError: Failed to fetch

**Comment by corinagum** [comment]
Hi @Rykimaruh, what documentation steps are you following? 

It looks like you are following the Web Chat example of creating a token server for your bot. Do you have that server implemented at the https://mybot.azurewebsites.net/directline/token API?

#1534 is a tracking issue for a sample that the team will implement to show users how to create the token server. In the mean time, you can take a look at our MockBot code to see how we implement the server. 
[`generateDirectLineToken.js`](https://github.com/compulim/BotFramework-MockBot/blob/master/src/generateDirectLineToken.js)
[`renewDirectLineToken.js`](https://github.com/compulim/BotFramework-MockBot/blob/master/src/renewDirectLineToken.js)
[`index.ts`](https://github.com/compulim/BotFramework-MockBot/blob/master/src/index.ts#L109)

**Comment by Rykimaruh** [comment]
@corinagum Following the documentation in this [link](https://github.com/Microsoft/BotFramework-WebChat)

> "Do you have that server implemented at the https://mybot.azurewebsites.net/directline/token API?"

No, I do not. I require to have a server for the custom webchat?

**Comment by corinagum** [comment]
If you wish to hide your secret and retrieve tokens via a token server to connect to Web Chat, then yes you do. Otherwise if you keep your secret on the bot-side of your code, you will not be presenting security issues. Please take a look at our [samples](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.a.getting-started-full-bundle) for more information.

**Comment by Rykimaruh** [comment]
@corinagum still get this error message, I don't know what it is.

**Comment by Rykimaruh** [comment]
@corinagum Checked up on the sample and tried to replicate it, but nothing. Still get the error messages:

POST https://mybot.azurewebsites.net/directline/SYah71uBb20.cwA.isk.THKguRBha4Un77U_Jh-Uz2TSxNxszLLvxu_24YV9D7Q 404 (Not Found)

indexchat.html:1 Access to fetch at 'https://mybot.azurewebsites.net/directline/SYah71uBb20.cwA.isk.THKguRBha4Un77U_Jh-Uz2TSxNxszLLvxu_24YV9D7Q' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
indexchat.html:26 TypeError: Failed to fetch

**Comment by mtmoreira98** [comment]
same issue, @Rykimaruh  did you find your issue?

**Comment by corinagum** [comment]
If you are running the Mock Bot samples, your deployed site is not on the listed of trusted origins, and therefore the bot will not run on that site. To run your own tests, please consider using a locally run bot or deploying your own resources to use for testing.
