### ISSUE TITLE
Issues having custom webchat work on Sharepoint Online site using IE11

### ISSUE THREAD

**Issue by Rykimaruh** [Microsoft/BotFramework-WebChat#1830]
I tried using the [es5 sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle) code to see if the bot works in the browsers, but I am getting issues with IE11.

My bot is in a SharePoint Online site. It works great on all browsers except IE11. Is there anything that could be causing this? Is it not compatible in sharepoint online with IE11? Actually the bot  itself works in IE11, but when I embed it in SharePoint Online site, it stops working...I only get a blank space in the area that the bot is in.

**Comment by jwiley84** [comment]
Is this related to https://github.com/Microsoft/BotFramework-WebChat/issues/1824?

**Comment by Rykimaruh** [comment]
@jwiley84 , it is...but because it was closed and didn't had the time to specify on what platform this was hosted on
