### ISSUE TITLE
Send box custom placeholder

### ISSUE THREAD

**Issue by jmurphyacc** [Microsoft/BotFramework-WebChat#1833]
I would like the ability to replace the "Type your message..." placeholder text with custom text of my choosing. I wasn't seeing this option in the JS settings. Thanks!

**Comment by jmurphyacc** [comment]
I would like the ability to replace the "Type your message..." placeholder text with custom text of my choosing. I wasn't seeing this option in the JS settings. Thanks!

**Comment by compulim** [comment]
I opened a new bug #1839. It is broader than this one by allowing developers to add new language and overriding existing one, that would include replacing "Type your message..." prompt.

**Comment by jmurphyacc** [comment]
Thank you. I will close our this issue and track 1839.

**Comment by Dpetters** [comment]
@compulim this item seems like it would be very cheap to implement, whereas the broader one, #1839 , is much bigger and is thus currently on the backlog. Is there any chance you guys would consider allowing the customization of the placeholder in a simple way sooner?

**Comment by Dpetters** [comment]
(gentle bump)

**Comment by corinagum** [comment]
@Dpetters sorry for the late reply. I think the scope of this piece of the project (customizing localization) is large enough that we will need to plan it out in tandem. Any people interested in this feature sooner should feel free to add their +1 here, and I will track popularity. :)

**Comment by amt-work** [comment]
@compulim @corinagum Has this been implemented yet? If so, how do we override it?

**Comment by collegewap** [comment]
+1

**Comment by ink169** [comment]
+1 please!!

**Comment by compulim** [comment]
This is done.

Please read this doc on how to overwrite the strings, https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/LOCALIZATION.md#overriding-localization-strings.
