### ISSUE TITLE
Error when using another module format

### ISSUE THREAD

**Issue by Maarten88** [Microsoft/BotFramework-WebChat#184]
I embedded the WebChat source components in my own webapp, which uses almost the same stack, except it uses webpack 2.1 beta (soon to be final), with a somewhat different configuration to achieve isomorphic rendering and tree shaking.

When testing I got this error, after typing the first message.

    FormattedText.tsx?366a:64 Uncaught TypeError: Marked is not a function(…)

It seems to be caused by webpack wrapping marked differently in my configuration. It does not like being used as a function:

    import * as Marked from 'marked';
    [...]
    const text = Marked(src, options);

I could fix this very easily by changing the line to 

    const text = Marked.parse(src, options);

which seems to be equivalent to the original. Everything else now works fine. Maybe it's a good idea to incorporate this small change to avoid others running into this.

**Comment by billba** [comment]
@eanders-MS will you please look into this?

**Comment by billba** [comment]
Fixed by #185
