### ISSUE TITLE
 failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by NoDirective** [Microsoft/BotFramework-WebChat#1845]
verison:
botframework-webchat@4.3.0
react@16.8.5
react-dom@16.8.5
react-scripts@2.1.8

error:
`WebSocket connection to 'wss://westus.stt.speech.microsoft.com/speech/recognition/interactive/cognitiveservices/v1?language=ja&format=detailed&Authorization=eyJhbGc........29' failed: Error during WebSocket handshake: Unexpected response code: 400`

microsoft.cognitiveservices.speech.sdk.bundle.js:3182

**Comment by corinagum** [comment]
Related to #1845, thanks for reporting.

**Comment by Akkilz** [comment]
<img width="645" alt="step 1" src="https://user-images.githubusercontent.com/11460269/55017156-6fec1900-4ff0-11e9-8549-88932983adc8.PNG">

**Comment by Akkilz** [comment]
<img width="959" alt="step 2" src="https://user-images.githubusercontent.com/11460269/55017180-7aa6ae00-4ff0-11e9-8bc2-94ce9d7ae075.PNG">

Plz find the network tab details,

**Comment by compulim** [comment]
Hi @Akkilz, for the second screenshot. Could you also dump the "Body" tab?

We want to know what exactly the HTTP 400 is talking about.

Thanks!

**Comment by Akkilz** [comment]
Request, response headers are available and response body is empty.

**Comment by NoDirective** [comment]
![image](https://user-images.githubusercontent.com/44224924/55044210-c1da8080-507c-11e9-9a93-504401f8534b.png)

**Comment by NoDirective** [comment]
![image](https://user-images.githubusercontent.com/44224924/55044225-d7e84100-507c-11e9-8e6c-9b63fa348c5b.png)

**Comment by corinagum** [comment]
Hi everyone, for organization purposes it would be great if everyone could post their images over on https://github.com/Microsoft/BotFramework-WebChat/issues/1823, where this bug was originally filed. I will be closing this issue and adding the images provided by @Akkilz and @NoDirective over there. Thank you!
