### ISSUE TITLE
DirectLine Custom user Properties as in V3

### ISSUE THREAD

**Issue by saravana13** [Microsoft/BotFramework-WebChat#1852]
Previously in V3 , when i initialise user object as below when calling BotChat.App

  var user = {
            id:  1,
            name: 'test',
            customName: 'testCustom'
}

I ll be able to access the CustomName in my Bot Code by accessing activity.From.Properties['customName']

Is it possible to do the samething in V4. ? Because there are some values which my bot need and those are already available when user logs into my web app, i dont want to ask them again.

Is there a way to do it in V4?

**Comment by EricDahlvang** [comment]
Yes, this still works with V4:
```js
let dl = window.WebChat.createDirectLine({ token: YourTokenValue });
let userId = getUserId();

window.WebChat.renderWebChat({
	userID: userId,
	directLine: dl
}, document.getElementById('webchat'));


dl.postActivity({
	from: {
		id: userId,
		name: 'User',
		customName: 'testCustom'
	},
	name: 'startConversation',
	type: 'event',
	value: ''
})
.subscribe(function (id) {
	console.log('trigger "startConversation" sent');
});
```

**Comment by corinagum** [comment]
Closing as resolved. Thanks for the assist, @EricDahlvang. 
@saravana13 please comment here if your question is not resolved and I can reopen. :)
