### ISSUE TITLE
Web Chat does not work for Azure Gov.  It 

### ISSUE THREAD

**Issue by fgarofalo56** [microsoft/BotFramework-WebChat#1855]
Web Chat does not work for Azure Government.  Token validation pulls from https://directline.botframework.com/v3/directline.   Azure Government needs to use:  https://directline.botframework.azure.us/v3/directline.

Is there an option to override for Azure Gov. Bot.

**Comment by compulim** [comment]
When you call `WebChat.createDirectLine({ ... })`, in the argument, add `domain: 'https://directline.botframework.azure.us/v3/directline'`, so it looks like

```js
WebChat.createDirectLine({
  domain: 'https://directline.botframework.azure.us/v3/directline',
  token: '...'
});
```

This will force DirectLineJS to talk to another server, instead of the default public endpoint.

**Comment by corinagum** [comment]
Reopening this for visibility until we document this. :)

**Comment by fgarofalo56** [comment]
This does work but only if you are using v4 SDK. I have yet to find a way
to get bot auth to point to Mag endpoints. I have created an issues on the
SDK v3 github for this piece.

**Comment by compulim** [comment]
Work to do: add documentation around talking to a different Direct Line endpoint.

**Comment by corinagum** [comment]
Documentation added to our API Reference. :)
