### ISSUE TITLE
UserID is not send to bot service in Webchat.js

### ISSUE THREAD

**Issue by Mironiny** [Microsoft/BotFramework-WebChat#1858]
Hi.
I'm using the latest version of webchat: https://cdn.botframework.com/botframework-webchat/latest/webchat.js. 

There is rendering: 

```            
            window.WebChat.renderWebChat({
                directLine: window.WebChat.createDirectLine({
                    token: '',
                    userID: 'myname',
                }),
                store,
                styleOptions
            },
```

But in my bot service I always get different Activity.From.Id even when sending from the chat still the same id.

**Comment by rosskyl** [comment]
Looking at the main page, it looks like you need to specify `userID` in `renderWebChat` and not `createDirectLine`. It should be:

    window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({
            token: ''
        }),
        userID: 'myname',
        store,
        styleOptions
    }

**Comment by Mironiny** [comment]
@rosskyl Ou, sorry... I've spent hours looking at it.

**Comment by corinagum** [comment]
Thank you @rosskyl for the assist! @Mironiny, I will close this as resolved but feel free to comment if you are still having trouble and I can reopen. :)
