### ISSUE TITLE
How to pass userid info thru Directline using  ReactJS

### ISSUE THREAD

**Issue by dharanidharan** [Microsoft/BotFramework-WebChat#1865]
Hi,

i have created voice chat bot, using "13.customization-speech-ui" web chat sample.  It working fine. 
Now, i have to pass the user id thru CreateDirectline. Am not able to get any user id variables in CreateDirectLine.Js; its contain below mentioned variable alone

domain: domain,
    fetch: fetch,
    secret: secret,
    token: token,
    webSocket: webSocket;

Am a .Net developer. its my first react app. Please suggest how to pass user id or user name in Directline react.

**Comment by cwhitten** [comment]
Hello @dharanidharan - please see the[WebChat README](https://github.com/Microsoft/BotFramework-WebChat#how-to-use) or the samples to see examples of passing a user id into WebChat. If you are using react, you can use the React component with the same api shown in what I linked.

**Comment by dharanidharan** [comment]
Hi @cwhitten, thanks for your reply.

Am using the below code.

Sample reference for Web Chat : "13.customization-speech-ui" 

import { Components, createDirectLine, createCognitiveServicesSpeechServicesPonyfillFactory } from 'botframework-webchat';

export default class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      directLine: null
    };
  }

async componentDidMount() {

    let search = window.location.search;
    let params = new URLSearchParams(search);
    let foo = params.get('psno');
    
    // const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
    // const { token } = await res.json();
    console.log(foo);
    this.setState(() => ({
      directLine: createDirectLine({
        secret: 'Secret Code',
        userID: '10009072',
        webSpeechPonyfillFactory: createCognitiveServicesSpeechServicesPonyfillFactory({
          region: 'westus',
          token: fetchSpeechServicesToken
        })
      })
    }));
  }

Am using above code. When am passing UserID its not accepting. after i have checked in createDirectLine.js; there is no properties for UserID.

![createDirectLine](https://user-images.githubusercontent.com/6276567/55531187-e5c64380-56c6-11e9-9c10-9223f8c1c6b8.PNG)

**Comment by mailforsachin** [comment]
@cwhitten Chris, could you explain this "If you are using react, you can use the React component with the same api shown in what I linked." I am using sample 12 and the react app is working as expected. But now, I need to pass the userid and password. How can I accomplish this? To give you a background, I have now hosted MSWebchat on ServiceNow portal page. I need some sort of SSO where I can pass on the user email and ID from the background/end ServiceNow page to the react application.
