### ISSUE TITLE
react how to use createStore 

### ISSUE THREAD

**Issue by NoDirective** [Microsoft/BotFramework-WebChat#1869]
version:   
  "botframework-webchat": "^4.3.0",
    "react": "^16.8.5",
    "react-dom": "^16.8.5",

I want to do the  post activity by react like blew

https://github.com/Microsoft/BotFramework-WebChat/blob/16e33e1660fee638717d2b3c1627f5f6a2474722/samples/15.c.programmatic-post-activity/index.html#L41

But compile error happened when I import it
`import  { createStore } from "botframework-webchat-core";`

**Comment by debasreedash** [comment]
Did you find an answer to this question?
