### ISSUE TITLE
Adaptive Card (Carousel) submit action error

### ISSUE THREAD

**Issue by marq47** [Microsoft/BotFramework-WebChat#1870]
We are trying to migrate our Web Chat to v4 but we want to continue using our bot without changes (botbuilder v3.15) if it is possible.

We are using a Carousel Adaptive Card with buttons to select an option among several. When the user clicks on a button we are getting the following error on browser console:

![issue-02](https://user-images.githubusercontent.com/49273695/55552080-a9054700-56dc-11e9-99ed-15bad67c0d6e.png)

Here you can see a portion of the card json:
.......
.......
```
"attachments": [
{
"contentType": "application/vnd.microsoft.card.adaptive",
"content": {
"type": "AdaptiveCard",
"version": "1.0",
"actions": [
{
"type": "Action.Submit",
"data": {
"__isBotFrameworkCardAction": true,
"type": "imBack",
"value": "Alergología"
},
"title": "Alergología"
},
{
"type": "Action.Submit",
"data": {
"__isBotFrameworkCardAction": true,
"type": "imBack",
"value": "Anatomía Patológica"
},
"title": "Anatomía \nPatológica "
},
.......
.......
```
Should we change the way we build the card? or which could be the problem?

Thanks in advance

**Comment by marq47** [comment]
Here you can see a portion of the card json:
.......
.......
"attachments": [
      {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
          "type": "AdaptiveCard",
          "version": "1.0",
          "actions": [
            {
              "type": "Action.Submit",
              "data": {
                "__isBotFrameworkCardAction": true,
                "type": "imBack",
                "value": "Alergología"
              },
              "title": "Alergología"
            },
            {
              "type": "Action.Submit",
              "data": {
                "__isBotFrameworkCardAction": true,
                "type": "imBack",
                "value": "Anatomía Patológica"
              },
              "title": "Anatomía \nPatológica "
            },
            .......
            .......

Should we change the way we build the card? or which could be the problem?

**Comment by corinagum** [comment]
`"__isBotFrameworkCardAction": true,` - this should not be added manually, this is added by the client when receiving Adaptive Cards. 

I'm not sure if `imback` is supported for Adaptive Cards. I will need to investigate this in Mock Bot.

**Comment by marq47** [comment]
Thanks, we'll try it.

**Comment by marq47** [comment]
We've try using postback and we're getting the same result (Chrome, Edge, Firefox) :

![issuePostback](https://user-images.githubusercontent.com/49273695/55789597-eee65480-5aba-11e9-9fbf-fed05a13bcff.jpg)

In all cases the browser says that cardAction is undefined.

Tell if you need more detail and what info could be usefull for you. 

Thank you very much.

**Comment by marq47** [comment]
We've solved the problem. We've found this:
_"The **data** property of the action may be a string or it may be an object. **A string is passed back to your bot as a Bot Builder SDK imBack activity**, and an object is passed as a postBack activity. Activities with imBack appear in the chat stream as a user-entered reply. The postBack activities are not displayed."_
 
So **using a string for the "data" parameter the click on the action executes without problem.** Example:
……..
……..
"attachments": [
      {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
          "type": "AdaptiveCard",
          "version": "1.0",
          "actions": [
            {
              "type": "Action.Submit",
              **"data": "Alergología",**
              "title": "Alergología"
            },
            {
              "type": "Action.Submit",
              **"data": "Anatomía Patológica",**
              "title": "Anatomía \nPatológica "
            },
……
……
