### ISSUE TITLE
Browser Speech for React

### ISSUE THREAD

**Issue by pradeeprajendran** [Microsoft/BotFramework-WebChat#1875]
Hello - is there a sample for using createBrowserWebSpeechPonyfillFactory in React? 

I tried adding it to the [12.customization-minimizable-web-chat](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat) but don't see a microphone option showing up

**Comment by corinagum** [comment]
We do not have a sample combining both features. If you think this is a bug please provide repro steps, your code, screencaps, and any console errors you are experiencing.

**Comment by pradeeprajendran** [comment]
Thanks for the response. Based on your response, looks like createBrowserWebSpeechPonyfillFactory is expected work in React as well. I will review my implementation again and will reopen this issue if I think it is a bug.
