### ISSUE TITLE
Failing to connect on IE11

### ISSUE THREAD

**Issue by dmaterowski** [Microsoft/BotFramework-WebChat#1878]
Hi all,
the webchat control doesn't work on IE11 for a portion of our users. The same people (tokens generated for each userId on a backend and advanced security turned on in the directline configuration) have no issues on other browsers. There is generally no errors, however from the network log in the browser I can see that:
POST https://directline.botframework.com/v3/directline/conversations return 307 temporary redirect
POST https://gateway.zscaler.net/<qparams> return 307 temporary redirect
POST "https://directline.botframework.com/v3/directline/conversations?_sm_au_=<something> return 307 temporary redirect
GET https://directline.botframework.com/v3/directline/conversations return 403 forbidden
After which no activities can be sent or received. 

directline is created with
```
this.directLine = createDirectLine({
      token: props.token,
    });
```
and webchat itself with
  ```
 <ReactWebChat
        className="webchat"
        userID={this.props.userId}
        directLine={this.directLine}
        store={this.store}
     />

```
Any ideas what may be causing that and how this can be fixed?

**Comment by dmaterowski** [comment]
One point that may be important is that the last GET call doesn't have Authorize header while all the other calls have it (and generally flow on other browsers and non-affected users is completely different but each request is authorized with the token)

**Comment by corinagum** [comment]
Are you using the [es5 bundle](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.b.getting-started-es5-bundle) of Web Chat?

**Comment by dmaterowski** [comment]
Using as react component from npm package and transpiling to IE11 compatible (+polyfilling). For most of the users it works, we verified that for people with exactly same OS and IE version it can work for one and not another.

**Comment by compulim** [comment]
@dmaterowski We never send/redirect our traffic to ZScaler. Do you think there is something to do with a browser add-ons in IE11 or a corporate proxy?

We are on HTTPS and ability to modify the HTTPS traffic seems weird to me.

**Comment by dmaterowski** [comment]
@compulim Yes! That was it. Zscaler has to be configured to allow directline calls. Thanks!
