### ISSUE TITLE
Hyperlinks starts on NewLine in Chat

### ISSUE THREAD

**Issue by wrende** [Microsoft/BotFramework-WebChat#1881]
Every link (hyperlink, email, ...) starts on a new line and ends with a new line.

Old Chat (Here it works, embedded code chat):
![image](https://user-images.githubusercontent.com/35459372/55728353-382f9900-5a14-11e9-924a-c771b994db22.png)

New Chat (v4.3.0):
![image](https://user-images.githubusercontent.com/35459372/55728334-2cdc6d80-5a14-11e9-9d0b-7157cecee4bb.png)

In the example above we used the same text with 2 different chats (old vs new). As you can see every link is encapsulated with a <a> tag and a new line before and after.

**Comment by corinagum** [comment]
- By old chat, do you mean Web Chat v3?
- Please provide your repro code so we can investigate this issue. A quick attempt at reproing this on Mock Bot did not create the same problem: 
![image](https://user-images.githubusercontent.com/14900841/55743566-7bbfde00-59e7-11e9-93c3-db6a5d0c44ff.png)

**Comment by wrende** [comment]
I think the old chat is webchat V3 I used the embedded code available from "Bot Channels Registration"
![image](https://user-images.githubusercontent.com/35459372/55784708-67481800-5ab1-11e9-9f03-eb581177e00d.png)

I used markdown:
![image](https://user-images.githubusercontent.com/35459372/55784956-e89faa80-5ab1-11e9-9d3b-738775694f9f.png)

You can simply test this with a send activity:

```csharp

string linkText = "!TEXT BEFORE! <[LINK](https://www.google.com/)> !TEXT BEHIND!";
await dc.Context.SendActivityAsync(linkText);

```

In the new webchat (V4.3.0) we get this result:
![image](https://user-images.githubusercontent.com/35459372/55785425-b2165f80-5ab2-11e9-8acf-e755ca6cd7c4.png)

In chat from "Bot Channels Registration" (This JS script is loaded '/scripts/webchat-stable/botchat.js'):
![image](https://user-images.githubusercontent.com/35459372/55785589-002b6300-5ab3-11e9-81d2-b7bfe7764817.png)

**Comment by wrende** [comment]
Found the issue, it was css conflict between bootstrap. 

By overriding the .indicators a block property we fixed the issue
