### ISSUE TITLE
Getting extra character when using speech API on webchat.

### ISSUE THREAD

**Issue by ParagHurkat** [Microsoft/BotFramework-WebChat#1887]
1. I am using the following link to use the speech API for webchat in the browser.

    https://github.com/Microsoft/BotFramework-WebChat

2. Once I use that, I am getting the speech icon. If the text contains ' character, it is not rendering properly as shown in the example below:

   Ok, letâ€™

3. Also, I am using some adaptive card and the text on that card contains ' character and it is not rendering that also properly.

4. Created another sample on my machine and I am also able to reproduce the problem. I added a ' character in my adaptive card and when I am using the speech for web-chat in the browser, it is not rendering it properly. I have added the screenshot for the same.  I observed that the javascript used is: https://cdn.botframework.com/botframework-webchat/master/webchat.js

Adding the Fiddler traces:
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
36	200	HTTP	localhost	/ws12-msg1	1,024		text/plain; charset=utf-8				
37	200	HTTP	localhost	/ws12-msg2	1,024		application/octet-stream				
38	200	HTTP	localhost	/ws12-msg3	192		application/octet-stream				
39	200	HTTP	localhost	/ws12-msg4	793		text/plain; charset=utf-8				
40	200	HTTP	localhost	/ws12-msg5	506		text/plain; charset=utf-8				

Frame 37 which shows the adaptive card response data:

ize": "default",
                "weight": "bolder",
                "text": "Welcome to the FactSet 'Support Desk Chatbot'! (v0.1 20181220)",
                "wrap": true,
                "maxLines": 0
              },
              {
                "type": "TextBlock",
                "size": "default",
                "isSubtle": "yes",
                "text": "BE THE ADVANTAGE.",
                "wrap": true,
                "maxLines": 0
              }
            ],
            "actions": [
              {
                "type": "Action.OpenUrl",
                "title": "Learn about FactSet",
                "url": "https://www.factset.com/"
              },
              {
                "type": "Action.OpenUrl",
                "title": "Learn about Microsoft",
                "url": "https://www.microsoft.com/en-us"
              },
              {
                "type": "Action.OpenUrl",
                "title": "Learn about Chatbots",
                "url": "https

The one that's getting rendered on webchat:

Welcome to the FactSet œSupport Desk Chatbotâ! (v0.1 20181220)

**Comment by corinagum** [comment]
I believe this is related to #1071, though with speech added as a factor we will need to investigate. Filing as Pending and possible Duplicate until further investigation can be made.

**Comment by tdurnford** [comment]
This appears to be resolved in master.

![image](https://user-images.githubusercontent.com/17039790/56246252-5588e680-6056-11e9-97da-b410d58d0f3d.png)

**Comment by corinagum** [comment]
Awesome. @ParagHurkat, please let us know if you are still experiencing this issue and we will reopen.
