### ISSUE TITLE
WebChat continues to say "sending"

### ISSUE THREAD

**Issue by ldaponte** [Microsoft/BotFramework-WebChat#1894]
WebChat continues to say "sending" even after I get a response from the bot.  Is this a known issue or is there something I'm doing or not doing to "close" the sending event?  The back end is Node.js V3.16.  Everything seems to be working fine, just expect the sending status to change to sent or a time stamp.
![image](https://user-images.githubusercontent.com/4205680/56046480-a7bec480-5d43-11e9-9e9a-cb579b0595fb.png)

**Comment by corinagum** [comment]
Hi @Idaponte, this is generally not a Web Chat issue. Please see @EricDahlvang's comment: https://github.com/Microsoft/BotFramework-WebChat/issues/465#issuecomment-468000346
