### ISSUE TITLE
[ReactWebChat] Markdown Base64 Images not getting rendered 

### ISSUE THREAD

**Issue by denscollo** [microsoft/BotFramework-WebChat#1896]
## Version
v4.3.0

## Describe the bug
Marked down base64 encoded images not getting rendered. Instead shows the image caption. 
We tested it on Azure Portal and HTML Sites (using also the example) and it works perfectly. When trying this approach on a React-App, using ReactWebChat, the images are not getting rendered.

### Bot with Markdown Base64 image on Azure Portal Web Chat
![imagen](https://user-images.githubusercontent.com/27219455/56064741-5e717380-5d49-11e9-8f64-1027156c0885.png)

### Bot with MarkdownBase64 Image using ReactWebChat (on Chrome and Mozilla Firefox)
![imagen](https://user-images.githubusercontent.com/27219455/56064796-7812bb00-5d49-11e9-8d02-39e1242efda6.png)

**Comment by corinagum** [comment]
@denscollo, thanks for filing this issue! If you have the time to do a PR with the fix, please feel free to do so! We appreciate your help.

**Comment by corinagum** [comment]
Investigate for 4.4

**Comment by corinagum** [comment]
@denscollo, could you tell me what format the data uri was in? 

[synk](https://snyk.io/vuln/npm:markdown-it:20160912) and the [markdown-it security page](https://github.com/markdown-it/markdown-it/blob/master/docs/security.md) indicate that only pngs, gifs, and jpgs are allowed in `markdown-it`.

**Comment by ParadoxARG** [comment]
Hi @corinagum, sorry for the delay. We were using pngs for our tests.
