### ISSUE TITLE
auto-scroll can stop working

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#190]
When I connect to the Bot Framework's TestBot (an internal tool used for feature testing), and I send it the 'runall' command, auto-scroll in the client will quickly fail. I have to manually scroll to keep up with its output.

**Comment by billba** [comment]
Yeah, I think @danmarshall broke autoscroll.

**Comment by danmarshall** [comment]
runall is the test I used to test autoscroll, and it works for me, even in a mobile browser. @eanders-MS are you seeing this in the emulator or standalone webchat?

**Comment by eanders-MS** [comment]
This was in standalone webchat. Same behavior in both, actually.

**Comment by eanders-MS** [comment]
I'm seeing it in Chrome on Win10.

**Comment by eanders-MS** [comment]
And I'm no longer able to repro!

**Comment by billba** [comment]
I was able to easily reproduce this by running "run all" and then resizing the window while stuff came in. I'm not sure this is a terribly important case, but I think @danmarshall's code is meant to handle it.

**Comment by billba** [comment]
But the real problem here is that "runall" sends several videos that autoPlay, which (who knew?) scrolls them into view, turning autoscroll off. I think that's actually a reasonable behavior, which is good because I don't know how we'd possibly fix it. So I'm going to close this issue.
