### ISSUE TITLE
Start connection in Chat.tsx should happen in componentDidMount, not in constructor

### ISSUE THREAD

**Issue by Maarten88** [Microsoft/BotFramework-WebChat#191]
I am making a public website to promote my bot, with the Chat component on it. The site uses React and redux, so I could nicely add the WebChat components to my sourcecode and integrate in in the design without using the iframe.

My site is isomorphic, meaning it renders the first request on the server. Using the Chat component this way results in an error because the component tries to start the connection in the constructor, which in the server-side case is inside node, which doesn't work.

I think the connection should be opened in componentDidMount, together with setting the subscriptions. I moved the code in my version, now the Chat component has no problems running on the server.

**Comment by billba** [comment]
Makes sense. Go ahead and submit a PR.

I think the only thing that needs to move is `props.botConnection.start()`, yes?

**Comment by Maarten88** [comment]
I think initializing the related subscriptions should move too. They are cleared in componentWillUnmount, so they should be initialized in componentDidMount (says my instinct for symmetry, without having tested the scenario's).
