### ISSUE TITLE
Buttons in Send Box appear cut off

### ISSUE THREAD

**Issue by shotamakino** [Microsoft/BotFramework-WebChat#1923]
The send box contains icon buttons that appear cut off:

<img width="396" alt="Screen Shot 2019-04-23 at 1 43 49 PM" src="https://user-images.githubusercontent.com/45368165/56614500-0569d100-65ce-11e9-8c5f-6304038e2be6.png">

The culprit is ROOT_CSS defined in BotFramework-WebChat/packages/component/src/SendBox/Assets/*

Please fix this to take on at least 40px for the height (or anything really that fixes the style)

**Comment by tdurnford** [comment]
What version of Web Chat are you using - latest or master? Also, can you include your Web Chat related code including your custom CSS? It's unlikely, but are there any console errors?

Thanks

**Comment by shotamakino** [comment]
Hi thank you for the quick reply. My code is a duplicate of the minimizable-web-chat [sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat) 

It is using the latest Web Chat package. No other custom CSS done besides those in the sample.
