### ISSUE TITLE
Scroll event is not triggering every time a message is received

### ISSUE THREAD

**Issue by keshavnagpal** [microsoft/BotFramework-WebChat#1926]
here is a video to explain the issue
https://www.loom.com/share/f22dd7020a0a4c5ea53c3a88be87ffee
(pass: webchat)

i'm using master/webchat-es5 (dated 25-Apr-2019) 

Update:
We implemented our own solution as a workaround for this, but it might not be as reliable as a fix in webchat library, pasting the implementation below:

```
var messageListSelector = '#chat-interface ul[role="list"][aria-live="polite"]';
var scrollControl = false;
When action.type === 'DIRECT_LINE/POST_ACTIVITY'
{
scrollControl = true;
}

When action.type === 'DIRECT_LINE/INCOMING_ACTIVITY'
{
if (scrollControl) {
        $(messageListSelector).parent().animate({ scrollTop: $(messageListSelector).height() }, 1000);
    }
    $('#chat-interface input[data-id="webchat-sendbox-input"]').focus();
}
//if user scroll up
$(document).ready(function(){
    $(messageListSelector).bind('mousewheel DOMMouseScroll', function(event){
        event.stopPropagation();
        scrollControl = false;
        var scrollPos = $(messageListSelector).parent().scrollTop();
        var elemHeight = $(messageListSelector).height();
        var srollSkew = elemHeight - scrollPos;
        if (srollSkew > 600 && srollSkew < 636) {
            scrollControl = true;
        }
    });
});
```

**Comment by tdurnford** [comment]
@keshavnagpal the video link you shared is private. Can you please change the privacy settings on it so we can see the issue. 

This seems to be related to https://github.com/Microsoft/BotFramework-WebChat/issues/1031.

**Comment by corinagum** [comment]
For confirmation, is this occurring in IE11?

**Comment by keshavnagpal** [comment]
@tdurnford I had provided the pass in the post, just removed it for simplicity, video is public now.

@corinagum strangely this doesn't occur in ie11 but occurring in chrome (i have Version 73.0.3683.103 if that helps)

**Comment by corinagum** [comment]
Repro steps:
1. receive an adaptive card from the bot
1. receive suggested actions from the bot
1. click on a button from the adaptive card

**Comment by compulim** [comment]
Investigating if it is because the scrollable container resized while the content is changing. This could be tricky to fix.

**Comment by Keshav-GravityILabs** [comment]
Hi, I tried master/webchat-es5.js
The issue seems to be still there
have a look at the video, is this fix supposed to come to master/webchat-es5 after some time?
https://www.loom.com/share/e137632b98ce442b8db0ab2c84bb8ab7

**Comment by tdurnford** [comment]
This bug has been fixed and will be available in our next release in July. If you need these changes immediately, please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Comment by Keshav-GravityILabs** [comment]
Thanks a lot @tdurnford
