### ISSUE TITLE
Missing token or secret

### ISSUE THREAD

**Issue by keshavnagpal** [microsoft/BotFramework-WebChat#1935]
Hi,
I'm not sure whether this is a directline issue or webchat but i'm getting the following error
```
{
  "error": {
    "code": "BadArgument",
    "message": "Missing token or secret"
  }
}
```
even after i'm providing the correct secret (that i've verified from azure)

I'm using master/webchat-es5.js (dated 24-Apr-2019)

To give more context to how i'm using is
I'm running the bot in my local
using ngrok and setting the url to bot channel registration i did on azure
using the secret from the bot channel registration i'm building the webchat 

in ngrok i'm getting following error (OPTIONS /api/messages  405 Method Not Allowed)

Here is the screenshot of all the action.type i'm getting back from webchat

![image](https://user-images.githubusercontent.com/10372931/56877062-15b7fb00-6a69-11e9-92b0-948419969c74.png)

But after some time (if I leave it for 10mins ) it starts working, it is happening every time

**Comment by compulim** [comment]
I think this is related to the usage of Bot Builder SDK. I think the bot might not have CORS enabled, thus, ngrok is saying OPTIONS 405)

**Comment by keshavnagpal** [comment]
I'm not able to find a reason for this

> But after some time (if I leave it for 10mins ) it starts working, it is happening every time

**Comment by tdurnford** [comment]
@keshavnagpal 

Are you just passing your secret into the WebChat renderer? If not, can you add code snippets for how you are requesting your directline token? Also, can you add code snippets for how you are rendering Web Chat?

**Comment by keshavnagpal** [comment]
@tdurnford 
I'm just passing my secret into webchat, have a look at the snippet below, i hope it covers the information you are looking for:

```
var cookieVal = checkCookieByName(chatBotConversationCookieName);
var directlineObj;
if (cookieVal) {
    directlineObj = window.WebChat.createDirectLine({
        secret: mySecret, 
        conversationId: String(cookieVal),
        webSocket: false
    });
} else {
    directlineObj = window.WebChat.createDirectLine({
        secret: mySecret,
        webSocket: false
    });
}
window.WebChat.renderWebChat
({
                    directLine: directlineObj,
                    // Browser Speech
                    webSpeechPonyfillFactory: window.WebChat.createBrowserWebSpeechPonyfillFactory(),

                     userID: CustomUserID,
                     store: store,
                     styleOptions: styleOptions,
                     locale: "en-AU",
                     sendTypingIndicator: false,
                     renderMarkdown: markdownIt.render.bind(markdownIt)

}, document.getElementById('chat-interface'));
```

**Comment by tdurnford** [comment]
Can you add the code snippets where you are setting the cookie and creating your custom store, as well?

**Comment by vincec-msft** [comment]
Looking at the Direct Line logs I see that DL posted to the bot's endpoint (the ngrok URL) and got back an HTTP 404 with a response text saying that the tunnel could not be found. Direct Line caches metadata about the bot (including the endpoint) so changes may not be immediately visible. This jives with the "wait 10 minutes and it starts to work" observations. The cache time is 30 minutes so you'd see this behavior for 15 minutes, on average.

**Comment by keshavnagpal** [comment]
@tdurnford 

```
function checkCookieByName(name) {
    var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
    if (match) {
        return match[2];
    } else {
        return false;
    }
}
// this is taken from documentation but i removed the lambda expression in order for this to work in IE, 
var store = window.WebChat.createStore({}, function (_ref) {
    var dispatch = _ref.dispatch;
    return function (next) {
        return function (action) {
            if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
                action = window.simpleUpdateIn(action, ['payload', 'activity', 'channelData', 'userInfo'], function () {
                    return userInfo; //custom key value pairs 
                });
                var _event = createNewEvent('webchatoutgoingactivity');
                _event.data = action.payload.activity;
                window.dispatchEvent(_event);
            }
            console.log(action.type);
            return next(action);
        };
    };
});
```

@vincec-msft Thanks for the information, this could be an explanation but is this recently introduced? Because before i never got any delay.

**Comment by vincec-msft** [comment]
The caching is not new. If you were creating new bots then they would be read immediately because they're not in the cache. But existing bot records have been cached for as long as I know.

* https://www.martinfowler.com/bliki/TwoHardThings.html

**Comment by tdurnford** [comment]
@keshavnagpal 

I'm not able to reproduce your error. Does your bot work in Test in Web Chat on the Azure Portal or any other channel when you connect with ngrok?

**Comment by Keshav-GravityILabs** [comment]
@tdurnford Yes it works on azure portal "Test in Webchat" tab.

**Comment by keshavnagpal** [comment]
@tdurnford  yes it is working fine in "Test in WebChat" tab on azure when I connect via ngrok

**Comment by tdurnford** [comment]
@keshavnagpal 

We had an issue that came through a couple days ago that shared some similarities with what you're experiencing. Do you have any firewalls configured between your bot and Web Chat? Also, are you using a Web Chat or a DirectLine secret?

**Comment by keshavnagpal** [comment]
@tdurnford 
I'm not sure about the firewall configuration, I didn't separately configure anything related to it (will it be there by default?)
I'm using DirectLine Secret

**Comment by tdurnford** [comment]
The firewall would be configured on your network. 

Also, if you wouldn't mind sharing the bot id and conversation ids that have been effected, I can take a closer look at the logs.

**Comment by keshavnagpal** [comment]
**Observation**

I've noticed that this delay doesn't occur if i first update the ngrok url on azure and then build/run the app in my local machine

It happens only when i've built/ran the code in local then ran ngrok then updated the url on azure, after that even if i rebuild , refresh or do anything else, i'll have to wait for a while.

**Comment by tdurnford** [comment]
This seems to be related to https://github.com/microsoft/botframework-sdk/issues/4043

**Comment by tdurnford** [comment]
It looks like you are correct. You have to change the bots messaging endpoint while the bot is not running otherwise it will not update correctly. Thank you for your help in diagnosing this issue.

**Comment by felcos** [comment]
> Hi, I'm not sure whether this is a directline issue or webchat but i'm getting the following error
> 
> ```
> {
>   "error": {
>     "code": "BadArgument",
>     "message": "Missing token or secret"
>   }
> }
> ```
> 
> even after i'm providing the correct secret (that i've verified from azure)
> 
> I'm using master/webchat-es5.js (dated 24-Apr-2019)
> 
> To give more context to how i'm using is I'm running the bot in my local using ngrok and setting the url to bot channel registration i did on azure using the secret from the bot channel registration i'm building the webchat
> 
> in ngrok i'm getting following error (OPTIONS /api/messages 405 Method Not Allowed)
> 
> Here is the screenshot of all the action.type i'm getting back from webchat
> 
> ![image](https://user-images.githubusercontent.com/10372931/56877062-15b7fb00-6a69-11e9-92b0-948419969c74.png)
> 
> But after some time (if I leave it for 10mins ) it starts working, it is happening every time





To update the application service
If you have an existing App Service (web app) resource for your bot and the bot is a user-assigned managed identity app, you may need to update the bot's app service:

Go to the App Service blade of the bot web application.
Under Settings, select Identity.
On the Identity sheet, select the User Assigned tab and Add (+).
On the Add user-assigned managed identity blade:
Select your subscription.

Under User-assigned managed identities, select the bot's managed identity. If the managed identity was automatically generated, it will get the same name as the bot.

Select Add to use this identity for the bot.

**Comment by vincec-msft** [comment]
@felcos , please open a new issue. Posting on a 4 year old, closed issue is not likely to get much attention. Thanks.
