### ISSUE TITLE
`npm run watch` fails on embed

### ISSUE THREAD

**Issue by corinagum** [Microsoft/BotFramework-WebChat#1937]
![image](https://user-images.githubusercontent.com/14900841/56925127-72281400-6a83-11e9-9999-be51e91734e0.png)

`concurrently` needs to be installed

**Comment by corinagum** [comment]
Forgot to mention: If anyone is running into this problem, the temporary workaround is to globally install `concurrently` on your machine.

`npm i concurrently`

**Comment by compulim** [comment]
Sorry forgot to associate the PR to this issue.

Fixed in #1940.
