### ISSUE TITLE
The carousal card does not stop at correct left.

### ISSUE THREAD

**Issue by PrashantSoniHarman** [Microsoft/BotFramework-WebChat#1941]
I am loading around 10 cards in carousal,  on click of next ("Right Arrow") button, it scrolls and shows next card, however it does more scrolling than needed towards left resulting to text trimming. And, only half of the card is visible. 

This is due to a CSS property set, as mention in the image. 

Please refer to the attached image.

![adaptive_Card_carousal_issue](https://user-images.githubusercontent.com/32177830/56951299-0f06b200-6b55-11e9-884d-e54350aa8da1.png)

This is on web channel, Bot is rendered with botchat.css and botchat.js
https://cdn.botframework.com/botframework-webchat/latest/botchat.css
https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js

The adaptive card version is 1.1.2

**Comment by corinagum** [comment]
Hi @PrashantSoniHarman, it looks like you are using v3 of Web Chat, which is in sunset right now. We prioritize security fixes for v3 but not other UI issues or bugs. If you are able to bump to v4, I strongly recommend doing so. We have a migration guide and several samples to help you get started on our README. Thank you! :)
