### ISSUE TITLE
Postback action writes to the chat window

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#195]
The postback action should not display anything in the chat window. This is what imBack is for.

**Comment by billba** [comment]
This was working and then I broke it. I'm special that way.

**Comment by billba** [comment]
a test case!

**Comment by mcsee** [comment]
Please do add a Test Case.
We detected the bug in our Regression Bot which has no functionality but to display all available controls

**Comment by mcsee** [comment]
@billba Bug is still open

whenever a user presses an imback button the value is echoed in the window
can you check it out again ?

**Comment by billba** [comment]
@mcsee that is correct behavior for imback

**Comment by mcsee** [comment]
sorry. button specified as postBack	

document states
'postBack	Text of message which client will post to bot. Client applications will not display this message.'

but on webchat echo of the value field is shown instead of title

**Comment by mcsee** [comment]
Sorry. apparently our old version was cached in chrome

Keep the bug open until the test case is added by  @palindromed
