### ISSUE TITLE
The action button size is not align with adaptive card designer

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-WebChat#1964]
## Version
v4.4.0

## Describe the bug
The action button style is not align with adaptive card designer.

## To Reproduce
What I see in the designer:
![image](https://user-images.githubusercontent.com/16643193/57190182-4658d280-6f4a-11e9-8869-393692dc5da5.png)

What I see in emulator:
![image](https://user-images.githubusercontent.com/16643193/57190185-507ad100-6f4a-11e9-951b-61171cf49c55.png)

Here is the adaptive card I use:
```
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "items": [
            {
              "type": "Image",
              "url": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX182_CR0,0,182,268_AL_.jpg",
              "size": "Medium"
            }
          ]
        },
        {
          "type": "Column",
          "items": [
            {
              "type": "TextBlock",
              "size": "Large",
              "weight": "Bolder",
              "text": "Avengers: Endgame"
            },
            {
              "type": "TextBlock",
              "text": "Action, Adventure, Fantasy"
            },
            {
              "type": "TextBlock",
              "text": "9.1/10"
            }
          ]
        }
      ]
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos' actions and restore order to the universe.",
          "wrap": true
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "View",
      "url": "https://www.imdb.com/title/tt4154796/"
    },
    {
      "type": "Action.OpenUrl",
      "title": "Showtimes",
      "url": "https://www.imdb.com/showtimes/title/tt4154796?date=2019-04-29&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=11468689-c6cf-4171-acbb-3b9e94cd223b&pf_rd_r=73CWJHCH4NX7T5BQVSNC&pf_rd_s=center-2&pf_rd_t=15021&pf_rd_i=tt4154796&ref_=tt_wbr_sh"
    },
    {
      "type": "Action.OpenUrl",
      "title": "Trailers",
      "url": "https://www.imdb.com/video/imdb/vi2163260441?playlistId=tt4154796&ref_=tt_ov_vi"
    },
    {
      "type": "Action.OpenUrl",
      "title": "Trivia",
      "url": "https://www.imdb.com/title/tt4154796/trivia?ref_=tt_ql_2"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```
## Expected behavior
Keep emulator card display the same as adaptive card designer.

[bug]

**Comment by corinagum** [comment]
I sent a message to a rep of the Adaptive Cards team asking that they update their site with our new hostconfig. I haven't heard anything back yet, but I will continue to check-in and report back here. :)

**Comment by DingmaomaoBJTU** [comment]
Thank you so much!~

**Comment by corinagum** [comment]
I got a response from the Adaptive Card team :) Web Chat is free to do a PR to their repo with the updated host config. Since Adaptive Cards' v.next has a lot of new changes, updating the file will not be trivial. We're keeping this for the 4.5 milestone, but I will work on this at a later date when I can delegate more time to it.

I would still super love to have another Adaptive Cards on Web Chat pass. @DesignPolice, what do you think?

**Comment by vikramdadwal** [comment]
Is this fixed ? Riased a similer issue in SO .. 
https://stackoverflow.com/q/56298444/746795

**Comment by corinagum** [comment]
I have made the PR for this fix on the Adaptive Cards repo: https://github.com/microsoft/AdaptiveCards/pull/3040

Since AdaptiveCards is owned by a different team, we're not privy to their PR review schedule, so I'm not sure how quickly this will be merged in, or when their next release is planned for. I will keep this issue open for tracking when that PR is merged into Adaptive Cards, after which I will close this as resolved. At the moment, there is no action item for the Web Chat team.

**Comment by corinagum** [comment]
Awesome! Adaptive Cards just merged my PR, so we can expect the designer to be updated with Web Chat's designs by their next release. Closing this issue as resolved. Thanks for your patience everyone.

**Comment by vikramdadwal** [comment]
Great. So when can we expect the same ?

**Comment by corinagum** [comment]
You would have to ask Adaptive Cards when their next release is. Unfortunately I don't have that information.

**Comment by nith-co** [comment]
- 

1. @ @

**Comment by nikheelneelay** [comment]
Hi, is there a sample code on how to use these changes?
