### ISSUE TITLE
Sample Customizing Speech UI browser support

### ISSUE THREAD

**Issue by erkkil** [microsoft/BotFramework-WebChat#1968]
Hi, 

I have build version from the customizing Speech UI sample (13.customization-speech-ui).
It works fine with my Mac on Chrome. However with Firefox and Safari (both on Mac) there is "Speech recognition is not supported" error in console and app stops running.

Is there limitations with browsers when using this sample and cognitive speech services in general?

**Comment by corinagum** [comment]
Hi @erkkil, 

If you take a look at [caniuse.com](https://caniuse.com/#search=speech%20recognition), neither of these browsers support Speech Recognition. Unfortunately, this means that sample 13 is not supported in either browser. 

Hope that helps!

**Comment by erkkil** [comment]
Hi,
Thanks for reply. 
Just to clarify this issue.. Is this sample using WebSpeechRecognition or CognitiveServices (Azure Speech service) based speech recognition?
I thought that caniuse.com tells webspeech based speech recognition support?

**Comment by corinagum** [comment]
Sample `13` uses Cognitive Services Speech Services recognition. You can take a look at sample `06.d` to see an example of web speech, and combine the work of both samples if you want to use Web Speech.

**Comment by erkkil** [comment]
Actually I don't want to use webspeech because of the limited browser support.
I would prefer to use Cognitive Services speech recognition if it has wider browser support.

**Comment by erkkil** [comment]
Hi @corinagum 
Coming back to this once more.
I run test with Microsoft Cognitive Services Speech SDK with their sample.
That demo seems to work also with Safari.
Is there any possibility to develop sample 13 so that e.g. Safari is supported?

**Comment by corinagum** [comment]
@erkkil, Ah, I see my confusion. Thanks for being patient with me. :) Still wetting my toes when it comes to speech.

From what you've shown me, it looks like there's a discrepancy between Web Chat's use of Cognitive Speech Services and the demos available for Cognitive Speech Services. This needs further investigation so I have re-opened this issue and will discuss with the team. Hopefully we can come back very shortly with a focus and a plan. Thanks for filing this issue!

**Comment by corinagum** [comment]
hi @erkkil, could you provide the exact error message that you are receiving? A screencap or copy-paste of the text would be great. Thank you!

**Comment by erkkil** [comment]
hi @corinagum,

Here is the error taken from Safari Javascript console after clicking the microphone button

<img width="1261" alt="webchat-speech-error" src="https://user-images.githubusercontent.com/6783309/58068339-a9c54000-7b99-11e9-919e-2cf53795feff.png">

**Comment by compulim** [comment]
I am now fixing this.

There are two problems here:

- The original sample was not using Cognitive Services because of bad code
- It partly work on Safari because Safari blocks WebRTC if it is not synchronously initiated thru user gesture (click -> record works, but not click -> fetch/setTimeout -> record)
