### ISSUE TITLE
Bot border radius style option

### ISSUE THREAD

**Issue by artemvalmus** [microsoft/BotFramework-WebChat#1977]
I need to change the border radius of the bot avatar, but do not see this property here - https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/defaultStyleSetOptions.js

Would it be possible to add it?

It was possible in older versions with styleSet which is stated to be non-recommended way of overriding styles.

**Comment by corinagum** [comment]
Hi @artemvalmus, just fyi, the last time I checked you are able to affect border-radius with styleSet. If you're having trouble with this let me know.

As for changing the border radius within styleSetOptions, you are right in that this is not (yet) a feature. I will put this issue up for discussion with the team to see if we want to implement the option. :)

(Also, if you have the bandwidth to do the PR yourself, we are more than happy to do a review!)

**Comment by compulim** [comment]
Like this idea!

Plus, we should build a sample to use `clip-path`, probably in `styleSet`, to clip the avatar as an [Octocat](https://www.bing.com/images/search?q=octocat). Fun 2-hour project.

**Comment by compulim** [comment]
This can be done with our latest customizable per-message avatar.

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/k.per-message-avatar/
