### ISSUE TITLE
Multi-line input textarea overflows container when words can't be broken

### ISSUE THREAD

**Issue by abishekreddy** [microsoft/BotFramework-WebChat#1980]
## Screenshots

![image](https://user-images.githubusercontent.com/24618556/57568906-3e49d880-740b-11e9-984e-233b387c378e.png)

## Version

Using the CDN.

## Describe the bug

Multi-line input textbox overflows parent container if words can't be broken when the styleoOption `sendBoxWrapText` is set to `true`,

**Comment by DesignPolice** [comment]
I think it should just wrap... with either a long URL or wildly long names? 

just mimic the behavior of Teams chat.
m

**Comment by DesignPolice** [comment]
![Screen Shot 2019-05-13 at 11 53 03 AM](https://user-images.githubusercontent.com/45223620/57646563-ba602f80-7575-11e9-9f89-7cd6191f4039.png)
