### ISSUE TITLE
Markdown should support links to sip protocol

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#199]
We should support the sip protocol markdown such as ```[call me](sip:danmar@microsoft.com)```

Related to https://github.com/Microsoft/BotBuilder/issues/1103

**Comment by eanders-MS** [comment]
We're restricting the protocol to `http` or `https`, but perhaps just open it up to any protocol?

**Comment by danmarshall** [comment]
Not *any* but we should add sip.

**Comment by eanders-MS** [comment]
Bots may want to deep link into apps, especially on mobile. I think we should open it up to any protocol.

**Comment by danmarshall** [comment]
actually it could be a config where the host may specify?

**Comment by billba** [comment]
Agree with Eric. This is basic mobile functionality.

**Comment by danmarshall** [comment]
Security-wise I think there should at least be a gating mechanism, where as the host of the HTML page, I could say "don't allow ftp links" or some such.

**Comment by eanders-MS** [comment]
How about an optional link handler to Chat? Defaults to window.open in new tab.
