### ISSUE TITLE
Adaptive Cards multiline input uses monospace instead of assigned font family

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#1990]
## Screenshots
![image](https://user-images.githubusercontent.com/14900841/57807397-f205dd80-7715-11e9-8d39-0738b2bb65ed.png)
![image](https://user-images.githubusercontent.com/14900841/57807484-1bbf0480-7716-11e9-949c-b3a995218cae.png)

## Version
v4 latest

## To Reproduce
1. Go to https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/
2. Type 'card inputs'
3. Note that the multiline input (placeholder text says 'Comments') is the only input that does not use default font, instead it is using monospace.

## Expected behavior
As seen on https://adaptivecards.io/designer/, the multi-line input should have the same font as the other inputs

**Comment by compulim** [comment]
I just checked that user agent (browser) use monospace font, not us. But we should use styles to override that.

![image](https://user-images.githubusercontent.com/1622400/57876158-82512a80-77c9-11e9-978a-b43e6d072366.png)

**Comment by corinagum** [comment]
The weird part though is that Adaptive Cards has it styled with the rest of the inputs. Not sure why Web Chat isn't doing the same.

**Comment by corinagum** [comment]
Hoping to get this fixed in tandem with #1964
