### ISSUE TITLE
Android WebView download a file result in page navigation

### ISSUE THREAD

**Issue by joseali93** [microsoft/BotFramework-WebChat#1997]
[Question]

Hello, I'm new to bot development, implement a bot using bot framework in typescript and adaptive cards, it's already published in azure, in the bot emulator and a web chat page work correctly. The problem I have to download files in a native android application is a test app and there are interactions but when you download an item in the mobile application appears black and I can not go back

in the mobile application I'm using a webview to embed the iframe

**Comment by compulim** [comment]
https://stackoverflow.com/questions/10069050/download-file-inside-webview

@joseali93 are you looking for something like this?

**Comment by v-kydela** [comment]
@joseali93 - Are you still working on this?

**Comment by joseali93** [comment]
i use the example of @compulim  i make a interceptor ( or something like that) for android, and  handle the external url of the webview
