### ISSUE TITLE
File upload issue: Odd behavior after rupload of three images at once

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#200]
This is an odd one. If I upload three images at once, I can no longer upload three images at once until I upload fewer than three at once, then all returns to normal.

Video of it:
http://recordit.co/ouauf8e0R8

**Comment by billba** [comment]
This is an entertaining one. We actually don't fire the second onChange event. So I tentatively think what is happening is that, if you select the same files as the first time, there is no *change*.

**Comment by billba** [comment]
This apparently won't work for IE < 11 but I can live with that.
