### ISSUE TITLE
Customization option to hide avatars

### ISSUE THREAD

**Issue by adaddeo** [microsoft/BotFramework-WebChat#2000]
## Feature Request

**Is your feature request related to a problem? Please describe.**
To preserve real estate in the chat window we'd prefer to hide avatars completely (and do something similar to the "user highlighting" sample).

**Describe the suggestion or request in detail**
A customization option to hide avatars completely. 

**Describe alternatives you have considered**
Using idiosyncratic styling to achieve the same result.

[Enhancement]

**Comment by compulim** [comment]
Avatar only show up if you set the `botAvatarInitials` or `userAvatarInitials`. By default, they are not set.
