### ISSUE TITLE
Enable to get embed code and secret for Web Chat channel

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/BotFramework-WebChat#2006]
## Screenshots
![image](https://user-images.githubusercontent.com/32375467/58034710-d2dbc700-7aec-11e9-8afd-cccae7e0d27c.png)

![image](https://user-images.githubusercontent.com/32375467/58034718-d4a58a80-7aec-11e9-9eee-2cc2e28ba2f0.png)

## Version
No sure, I haven't used it yet. 

## Describe the bug
Please refer to the screenshots attached. In azure portal I am looking at 'Bot Channel registration' resource, and Channels setting. I clicked on 'Edit' for Web Chat channel to grab the secret & embed code I need but, it doesn't show any settings on the page. From the 2nd screenshot if i click on 'get bot embed codes' takes me to same page. 

## Expected behavior
I should be able to grab all the settings I need from azure.

[Bug]

**Comment by corinagum** [comment]
This is definitely odd. I'm unfortunately not reproducing this when I try a new Bot Channels Registration. 

- Could you check the console to see if there are any errors reported? If there are, please take a screenshot and share that here. 
- Could you also let me know what browser you're trying this on? I will try to reproduce again when I hear back from you. Thank you!

**Comment by compulim** [comment]
@rjgmall88 did you delete the default site it comes with?

I just tried to create a new Bot Channel Registration and the "Default site" exist, so I am guessing you might accidentally deleted it.

Bot Channel Registration will come with a "Default site". If you deleted it, it will turn blank like your first screenshot. But you can re-create the site by clicking on "+ Add new site".

**Comment by rjgmail88** [comment]
Hi @compulim, Adding the new site worked. I can see setting now. Out of curiosity how can we use this site ?

**Comment by compulim** [comment]
Good to know it fixed.

I am unsure why it come up with this name. You can think about "site" as a separate container with isolated conversation. So you cannot use a secret from one site to retrieve conversation from another site.

As you see there are options below the site, these options are also specific to the site. For example, in Direct Line channel, you can set whether to opt-in enhanced security or not.
