### ISSUE TITLE
Documents are not processed by the channel

### ISSUE THREAD

**Issue by reyesrico** [Microsoft/BotFramework-WebChat#201]
If the bot sends a document of any file, the channel does not support to send the document, only is sending the type of the file.

![img_1543](https://cloud.githubusercontent.com/assets/10733155/20950592/75598898-bbd5-11e6-9bdb-fbd0799be720.PNG)

**Comment by billba** [comment]
I don't believe this is true. WebChat does send the actual file. It just doesn't *show* it unless it recognizes it. The bot should be able to access the file as a message attachment. Please let me know if your bot cannot access the uploaded file.

**Comment by eanders-MS** [comment]
I think he means the other direction. The bot can send a file to the client. This can be reproed from testbot with the actions command and then clicking the Download File button.

**Comment by eanders-MS** [comment]
The user should be able to open this document sent from the bot:
![image](https://cloud.githubusercontent.com/assets/12176807/20980644/36b6167e-bc66-11e6-9413-016da0720951.png)

Perhaps, if the doc can't be rendered in the chat window, it should be downloaded. Following that, it seems that even docs that can be rendered (e.g. images) should be able to be downloaded as well.

**Comment by billba** [comment]
I think images are handled with a right-click Save operation. I'd hate to put a "download" link next to every image - most of the time it would be distracting and unwelcome.

For non-images all we've got is a URL anyway, so we could easily just make it a live link, which again they could right-click to download (or click to jump to). What would the UX be? Maybe just highlight "File"? I don't want to show the whole URL because it would be ugly.

**Comment by eanders-MS** [comment]
@kevkor. Maybe make this portion of the message clickable, taking user to the attachment's url:
![image](https://cloud.githubusercontent.com/assets/12176807/20983374/14c311ec-bc71-11e6-9295-f6daf5365237.png)

**Comment by billba** [comment]
@kevkor Yeah I'll try that and a few variations and see what seems most usable.

**Comment by danmarshall** [comment]
I'm thinking that it would be cool to show an icon. @kevkor ?

**Comment by eanders-MS** [comment]
Bumping this thread (we received another support email about it), and adding @jecristi for design input.

**Comment by danmarshall** [comment]
@jecristi did we have a design for this, which depicted a file as a card?

**Comment by eanders-MS** [comment]
As a simple solution we could display the filename of the attachment and make it clickable for download (and generate a filename for it if missing).

**Comment by jecristi** [comment]
Hi Dan,

I don’t believe we have designs for this yet.




Jeremy Cristiano
—

UX Designer
Microsoft | FUSE Labs

**Comment by danmarshall** [comment]
@jecristi can we get the design from you?

**Comment by danmarshall** [comment]
Fixed by #602
