### ISSUE TITLE
Text to Speech is reading markdowns

### ISSUE THREAD

**Issue by keshavnagpal** [microsoft/BotFramework-WebChat#2010]
## Version
![image](https://user-images.githubusercontent.com/10372931/58073157-8614f080-7bbf-11e9-8575-0874a301db39.png)

## Describe the bug
Text to speech is reading the markdowns like 
- URL
- horizontal line
- (previously it used to read ** bold text ** asterisk as well but I recently checked that it is fixed now)

I can see that the markdowns are not rendered as text.
URL -> goes to href and only the text is present inside the tag
horizontal line gets rendered as <hr>

![image](https://user-images.githubusercontent.com/10372931/58073390-09cedd00-7bc0-11e9-9d13-9242d23d52d6.png)

## To Reproduce
1. add markdowns to the messages
formatting used in code:
- URL " `[text to be displayed](https://url.com)` "
- Horizontal line " `\r\n     __________     \r\n` "

## Expected behavior
it shouldn't read the markdown text

## Other related information
Whenever there is a message sent along with the card it only reads the message and skips the card.
When the card is sent without any message it reads the card aloud.
is this the expected behaviour?
for example if I send a message like this:
![image](https://user-images.githubusercontent.com/10372931/58075166-a1362f00-7bc4-11e9-8a0d-f8e0597d2337.png)
it skips reading the card and only reads aloud "Fetching Details".
In the c# backend I tried changing the `Speak `attribute of the` Activity reply` (reply.Speak="something else")
but it doesn't speak the text defined in reply.Speak.
[Bug]

**Update**
I noticed this occurs only when we are using underscores for horizontal lines
when I replaced them with asterisks it is working as expected 

But the URL is still an issue

**Comment by corinagum** [comment]
This is a duplicate issue of #2001. Please feel free to add your comments over there.
