### ISSUE TITLE
Module not found: Can't resolve 'mime/types/other.json'

### ISSUE THREAD

**Issue by Deucem** [microsoft/BotFramework-WebChat#2019]
## Version
Latest - "botframework-webchat": "^4.4.1"

## Describe the bug

npm install botframework-webchat, attempt to use:

import { DirectLine } from 'botframework-directlinejs';
import ReactWebChat from 'botframework-webchat';

and error message appears:

./node_modules/botframework-webchat-core/lib/utils/mime-wrapper.js
Module not found: Can't resolve 'mime/types/other.json'

This happens in brand new "create-react-app" and next.js projects.

## To Reproduce

As above, create new react app using create-react-app, npm install botframework-webchat, import components required, start react "npm run start" 

## Expected behavior

The webchat works and renders

## Additional context

[Bug]

**Comment by Deucem** [comment]
I've noticed fix #1998, so i npm install botframework-webchat@master, the problem still persists.

@tonyanziano

**Comment by tonyanziano** [comment]
@Deucem can you check inside of your `node_modules` folder and see what version of Web Chat you have installed? You shouldn't be seeing the error for `Can't resolve 'mime/types/other.json'` because the code that was trying to require the `.json` files [no longer exists](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/core/src/utils/mime-wrapper.js#L40).

This leads me to believe that you are still using an older version of Web Chat before the fix went in.

**Comment by Deucem** [comment]
Ok yes that works, I nuked my node_modules folder and install the master branch and it came to live. Do you have an ETA on when this will be pushed to NPM, without having to have a dependency on the master branch? this is a pretty major breaking change that basically renders the webchat for react unusable.

**Comment by Deucem** [comment]
Never mind, appears it was a local issue, the normal npm install botframework-webchat works just fine.

**Comment by tonyanziano** [comment]
Glad to hear it!

**Comment by compulim** [comment]
I am seeing this too today. 🤦‍♂️

I believe `mime` bumped this breaking change (`2.3.1` -> `2.4.3`) and now our `4.4.1` is broken by default. Will let you guys know when we decided to publish `4.4.2` with Tony's fix to lock down on their version.

On the other hand, we modified `npm install botframework-webchat@master`. #2025 is the work to update our instructions.

**Comment by compulim** [comment]
## Work to do

Bump to `4.4.2` with Tony's fix.

**Comment by RoSchoe** [comment]
Hi is there an hotfix or workaround for that?

**Comment by jusso-dev** [comment]
It works for me @RoSchoe, if you need a hotfix, change the mime-wrapper.js to reflect this file https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/core/src/utils/mime-wrapper.js#L40

**Comment by RoSchoe** [comment]
well done @jusso-dev , this solved my problem - thank you

**Comment by corinagum** [comment]
Testing the patch on a local build, hopefully for a release today.

**Comment by compulim** [comment]
Released on NPM as [4.4.2](https://www.npmjs.com/package/botframework-webchat/v/4.4.2) just now. Release on CDN is pending but since we burn-in packages, shouldn't be much different.

Thanks for reporting, @deucem. And thanks for workaround-ing the problem, @jusso-dev and @RoSchoe.
