### ISSUE TITLE
Username is not passed from webchat HTML to bot

### ISSUE THREAD

**Issue by chinnivyshnavi** [microsoft/BotFramework-WebChat#2021]
Hello, I am trying to send a username from html to chatbot. Code used for the same is as follows

```<!DOCTYPE html>
<html>
  <style>
html, body { height: 100% }
 body { margin: 0 }

 #webchat {
   height: 100%;
   width: 80%;
   margin-left: 10%;
 }
</style>
  <body>
    <div id="webchat" role="main"></div>
    <script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
    <script>

      window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ token: 'MY_TOKEN' }),
        userID: '1234',
        username: 'Chinni',
        locale: 'en-US',
        botAvatarInitials: 'WC',
        userAvatarInitials: 'WW'
      }, document.getElementById('webchat'));
    </script>
  </body>
</html>
```
I am trying to extract the username as from:Role in the chatbot

`await turnContext.SendActivityAsync(MessageFactory.Text(turnContext.Activity.From.Role), cancellationToken);`

Am I extracting in a correct way? Is it possible to get the name ??

**Comment by corinagum** [comment]
Hi @chinnivyshnavi, from your HTML it looks like you are hardcoding the username to be 'Chinni', but you also mention that you are trying to retrieve the username from the turnContext. Could you clarify which one you intend on using?

**Comment by chinnivyshnavi** [comment]
Hi @corinagum i want the name 'chinni' to be sent to the bot and displayed in the conversation. I hardcoded the 'chinni' name to check whether the name can be passed or not temporarily. If this works i will change the code to dynamically send the username. Thanks.

**Comment by saurav2107** [comment]
@chinnivyshnavi I guess you need to use:

await turnContext.SendActivityAsync(MessageFactory.Text(turnContext.Activity.From.Name), cancellationToken);

to get username in the code

**Comment by corinagum** [comment]
@saurav2107, thanks for the help! Closing as solved. :)
