### ISSUE TITLE
V3 to V4 Migration Roadblocks. 

### ISSUE THREAD

**Issue by jithinsarath** [microsoft/BotFramework-WebChat#2023]
We are in process of migrating our bot, written in C# .Net to C# .Net Core. We were able to convert most of our work, but have hit a wall while dealing with Webchat.js.
We forked botchat.js to include following features. Now that the webchat.js is minified, we are unable to make these minor changes to the code, without rolling out a forked version (and having to implement all of the other good bits - token handling, o365 auth etc.)

We have been through the migration guide and the open/closed issues about the migration

Note: Our bot is accessible via it's own website, and is not embedded.

1. The below snippet reads the userid from the cookie. If there is no user id, it initializes by sending a hello through code. The response is captured by "CaptureActivityText" which then shows a custom login page, if the user is not authenticated. 
> var userId = getCookie('UserId');
      if (userId) { }
    else { this.props.sendMessage("hello"); }

>CaptureActivityText(activity.text, activity.attachments);

As it stands today, we are unable to get this added to V4. 

2. Avoid sending duplicate messages
>if (state.activities.find(function (a) { return a.id === action.activity.id; }))
return state; // don't allow duplicate messages 

3. Block user typing in the text box when the request is being process in the server
>$(".wc-shellinput").attr("disabled", "disabled"); 

Any help in the above issues - especially the first one is greatly appreciated.

**Comment by compulim** [comment]
@corinagum please add more.

1. There is a programmatic way to post activity, doable.
2. Is it about the bot sending duplicated activity or Web Chat? And why would that happen?
3. There is a way to disable the UI via props, never use jQuery or DOM in Web Chat
   - But I believe, conversation is always asynchronous and interrupt-able, that's how human works. The bot should be able to handle such scenario to make great UX

**Comment by corinagum** [comment]
1 & 2: You are able to programmatically filter and send activities on the client side. Please see sample 15.d
3: You can use `styleOptions` to disable the input. Please see sample 05.c
