### ISSUE TITLE
Update instructions to use MyGet for dev build

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2025]
## Feature Request

And optionally, deprecate `master` dist-tag.

### Package history

Package history at [MyGet](https://botbuilder.myget.org/feed/botframework-webchat/package/npm/botframework-webchat).

### `.npmrc`

```
registry=https://botbuilder.myget.org/F/botframework-webchat/npm/
```

### Rough draft

To use dev build,

1. Create/modify `.npmrc` locally and set `registry`
1. Run `npm install botframework-webchat --save`
1. Remove your changes in step 1 to reduce impact on your `package-lock.

@corinagum please verify these steps with a few things.

1. Look at `package-lcok.json` to make sure we have minimal impact
1. Remove `node_modules`, keep `package-lock.json`, then do `npm install` again
   - This mimic what the user would do on a fresh clone
   - Make sure `npm install` is grabbing the right version by drilling into `node_modules` folder seeing the `package.json` file inside
1. Same as step 2, but instead of `npm install`, run` npm ci`
   - Should be the same
1. Wirte up guides to reverse it back to production version
   1. (I didn't try the following steps)
   1. Run `npm install botframework-webchat --save`
   1. Make sure everything in `package-lock.json` is pointing to npmjs.org, and *not a single package* is point to myget.org
   1. Make sure it grab the 4.4.1 (production, not dev build)
      - Drill into `node_modules` folder to see
      - Don't forget to look at `botframework-webchat-core` and other packages
   1. Find the string "myget.org" in `package-lock.json`, make sure no package is affected if the user reverted, super important

**Comment by corinagum** [comment]
I want to confirm with the team whether or not we want to make Web Chat a scoped package. Doing this would allow our users to point to myget for the Web Chat project without having to change the entire project registry to myget. (For example, without scoped packages, changing the registry means that react-scripts, a non-dependency of Web Chat, would also be pointing to myget).

Taking a look at the other BotBuilder projects, it looks like they are **not** using scope, meaning that we would be the frontier runners in trying this out.

[npm scope documentation](https://docs.npmjs.com/misc/scope#associating-a-scope-with-a-registry)

@compulim @cwhitten, thoughts?

**Comment by cwhitten** [comment]
I'm all for it - but we should connect with the larger framework team on what this scope would be. can we go ahead and cut documentation on how to do this today (no ideal) and start a discussion on creating a bot framework scopes organization?

**Comment by stevengum** [comment]
If I understand correctly, an example flow to the user might look like this:

```bash
# Add scope and scope's registry
npm config set @botframework:registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/

# Retrieve botbuilder from that scope
npm i @botframework/botbuilder

# Install packages from the npm registry
npm i botframework-webchat botbuilder-dialogs
```

Is this correct?

If we publish our packages with an actual scope (there have been discussions around this) then if someone wanted to scope to our daily feeds they might do the following?

```bash
# Add scope and scope's registry
npm config set @botframework-dailies:registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/

# We've scoped all of our packages to @botframework
# Retrieve @botframework/webchat from regular registry
npm i @botframework/webchat

# Install packages from the dailies
npm i @botframework-dailies/@botframework/botbuilder @botframework-dailies/@botframework/botbuilder-dialogs
```

**Comment by corinagum** [comment]
@cwhitten in our 1:1 yesterday you mentioned the concern of wanting to mix and match botframework distributions between MyGet and npmjs. 

Originally my thought process was that we would have two different scopes, for example @botframework and @botframework-dailies, but after looking into it I believe this would add way too much complication, and therefore we should keep all our packages under the same scope.

If both packages are part of the same scope, it would still be possible with Steven's information above to specify different registries on a case-by-case basis:
- We can change the registry for a specific scope; a scope can only have ONE active registry
- If we want to install a scoped package from a different registry, we have to use npm i <package> --registry <registry URL>

This issue is supposed to be closed once my above PR is in, but I will reopen a new issue to continue this conversation.

**Comment by cwhitten** [comment]
That sounds good to me @corinagum
