### ISSUE TITLE
React version of Chat bot not working with SharePoint SPFX in IE 11

### ISSUE THREAD

**Issue by anomepani** [microsoft/BotFramework-WebChat#2030]
### React version of Chatbot not working with SharePoint SPFX in IE 11

React version of Chatbot not working with SharePoint SPFX in IE 11

## Screenshots
![Chatbot_Console](https://user-images.githubusercontent.com/2988295/58310128-801f4980-7e23-11e9-8e9e-2ebff73962fc.png)
![SPFX chatbot Render Error](https://user-images.githubusercontent.com/2988295/58310141-89101b00-7e23-11e9-8419-e6b3c4f3bda9.png)

## Version
Used NPM Version in Spfx package
  "botframework-directlinejs": "^0.11.4",
    "botframework-webchat": "^4.4.1"
Also attached package.json file 
```node version: 8.15.1```
[package.txt](https://github.com/microsoft/BotFramework-WebChat/files/3215524/package.txt)

## Describe the bug
I have integrated React ChatBot with SPFX Extension but it giving error and not working in IE11.
Getting Error like  
- Render Error: Please check the console or contact the Bot Developer
- `Network Error 12030 Connection with server Terminated` 
-  sign, Array.findIndex, includes not defined
-  The object doesn't support property or iterator
-  Unable to get property or method error of undefined

## To Reproduce

1. Deploy Spfx Solution on Sharepoint Online Modern page.
2. Open Chatbot app in IE11 in Sharepoint Online Modern
3. In the console, it returns an error and in chat dialog, it showing error as well.
4. See error as attached screenshot

## Expected behavior
Same chatbot app working in Window 10 Edge Browser and Latest Chrome and FireFox browser but not working with IE 11.

[Bug]

**Comment by corinagum** [comment]
React will not work on Internet Explorer without using polyfills. Please verify the polyfills on your app are sufficient for Internet Explorer 11.
