### ISSUE TITLE
Need to increase the timeout for TypingAnimation

### ISSUE THREAD

**Issue by mathurvarun84** [microsoft/BotFramework-WebChat#2031]
@compulim: Please see "How to fix" below, https://github.com/microsoft/BotFramework-WebChat/issues/2031#issuecomment-510964209.

**Feature request**

I need to increase the timeout of the typing animation shown by the bot. Currently, the bot typing animation disappears after 2 sec or so. I need to increase to 6 sec. I tried following the approach of setting SendTimeout explicitly but it doesn't seem to work.

```js
  window.WebChat.renderWebChat({
                directLine: window.WebChat.createDirectLine({
                    token: params['s'],
                    userID: params['username'],
                    user: {id: params['userid']},          
                }),
                store, username: params['username'],
                userID: params['userid'], **sendTimeout: 60000**,
                styleSet,
                sendTypingIndicator: true,
            },
            document.getElementById("webchat")
        );
```

Any idea of how can I Increase the timeout for typing Animation.

(Edited by @compulim for code formatting)

**Comment by corinagum** [comment]
Hi @mathurvarun84, the typing indicator is not currently customizable. After speaking with the team, we are interested in enabling users to modify the duration. This has been added to our backlog. Thank you!

**Comment by marq47** [comment]
Hi!
We need this feature too.
Thanks for your work on it.

**Comment by Tosters** [comment]
Hi,
This would be very nice feature to have. Looking forward to it.

**Comment by luchenko** [comment]
Hi 
i changed this value (3e3) => (6e5)
search this  text :  ofType("Show_Typing").delay(3e3) 
in this file 
https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js


works for me

**Comment by compulim** [comment]
## How to fix

### Implementation

- Today, we use saga to control how long to show typing
   - "How long" is a question on UI, not back end. Thus, the better design is to move it away from saga
- Tomorrow
   - Use `debounce` in UI to control how long to show typing
   - Move typing indicator into send box
      - This will greatly reduce code complexity
   - Add `typingIndicatorTimeout` to `styleOptions`

### Tests

- Basic test
   - Default value
   - Non-default value
   - New activity from bot come in and it should immediately remove typing indicator
- Corner cases
   - After the typing indicator "faded away", setting `styleOptions.typingIndicatorTimeout` to a bigger value should bring it back

**Comment by tdurnford** [comment]
https://github.com/microsoft/BotFramework-WebChat/pull/2321 Added a `typingAnimationDuration` option to the default style options - default is 5000 milliseconds.
