### ISSUE TITLE
Tool tip for Hero Cards with long text

### ISSUE THREAD

**Issue by Souvik04** [microsoft/BotFramework-WebChat#2032]
🚨 The issue tracker is not for implementation questions 🚨

When the suggested question in the form of Hero Cards are too long, the text gets truncated followed by 3 dots to accommodate in a line. Is it possible to have tool tip for showing the full text?
I am using React Webchat from one of the samples.

**Comment by corinagum** [comment]
https://stackoverflow.com/questions/56336231/tool-tip-for-long-texts-in-hero-cards
