### ISSUE TITLE
[Bot Framework V4] [Directline] [Bot Channel] There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotFramework-WebChat#2045]
### [GitHub issues](https://github.com/Microsoft/botframework-webchat/issues) should be

Facing the below issue intermittently:

 [Bot Framework V4] [Directline] [Bot Channel] There was an error sending this message to your bot: HTTP status code GatewayTimeout

## Screenshots
![image](https://user-images.githubusercontent.com/10174566/58668104-c1fd3380-82ec-11e9-9235-6db2471ad55a.png)

## Version
1. Using CDN (Webchat Latest)
2. Version 4.4.4

## Additional context

[Bug]

**Comment by corinagum** [comment]
@vikramdadwal, please fill out the rest of the information of the template. Feel free to leave another comment when you're done and I'll be happy to reopen this issue.
