### ISSUE TITLE
thumbnailCard title too long will be ellipsis

### ISSUE THREAD

**Issue by NoDirective** [microsoft/BotFramework-WebChat#2046]
I used thumbnailCard with long title.
The Text will be ellipsis if the text in title is too long.
Is there any options to change  thumbnailCard title style for this case

[Edit by corinagum - Adding more detail from below]
---
The title of thumbnailCard  is showed with ellipsis. 
And in Devtools , I could see all text of the title .
Is there any options to change thumbnailCard title style In web chat .
So I could see the all of them , no by ellipsis.

![image](https://user-images.githubusercontent.com/44224924/58771300-4ce07580-85ee-11e9-8228-efb9fdf3aa63.png)

![image](https://user-images.githubusercontent.com/44224924/58771314-5bc72800-85ee-11e9-8ba2-f669102133fa.png)

```
let buttons = [];
            let button1 = {};
            button1.type = 'imBack';
            button1.title = "one";
            button1.value = "one";
            buttons.push(button1);

            let button2 = {};
            button2.type = 'imBack';
            button2.title = "two";
            button2.value = "two";
            buttons.push(button2);

            let button3 = {};
            button3.type = 'imBack';
            button3.title = "three";
            button3.value = "three";
            buttons.push(button3);

            await dialogContext.context.sendActivity({ attachments: [CardFactory.thumbnailCard("abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890", '', [], buttons)] });
```

**Comment by corinagum** [comment]
Hi @NoDirective, unfortunately it looks like titles have a [max length of 20](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/choices/channel.ts#L98) in the Bot Framework SDK. Allowing Web Chat to change the styling of the title would not increase the allowable text. As it stands, this is not a feature our team will be implementing in the immediate future.

**Comment by NoDirective** [comment]
Hi @corinagum 
Thank you for your answer.
I am sorry that I did not describe my question clearly. 
The title of thumbnailCard  is showed with ellipsis. 
And in Devtools , I could see all text of the title .
Is there any options to change thumbnailCard title style for this case.
So I could see the all of them , no by ellipsis.



![image](https://user-images.githubusercontent.com/44224924/58771300-4ce07580-85ee-11e9-8228-efb9fdf3aa63.png)

![image](https://user-images.githubusercontent.com/44224924/58771314-5bc72800-85ee-11e9-8ba2-f669102133fa.png)

**Comment by corinagum** [comment]
@NoDirective,. thanks for the extra detail!
It turns out the max character length is completely arbitrary and does not apply to this situation. :) sorry for my incorrect statement above. 

Since there is no character limit, the details you have provided appear reasonable. I'm going to edit your original message with the details you provided and add this to our Backlog for future triage.
