### ISSUE TITLE
There is no user object and way to send additional data/properties from directline javascript client to bot

### ISSUE THREAD

**Issue by PrashantSoniHarman** [microsoft/BotFramework-WebChat#2047]
### [GitHub issues]  
There is no user object and way to send additional data/properties from directline javascript client to bot when creating bot connection with window.WebChat.renderWebChat.

Also, while using the old library and creating bot app with "BotChat.App", the user object and additional properties are not sent inside activity.

## Version
Bot framework SDK 4.4.3
New Directline Javascript library
<script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
Old
 <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js">

## Describe the bug
We were using following direct line JS for integrating bot on the web.
```
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js"></script>

BotChat.App({
        directLine: { secret: direct_line_secret },
        **user: { id: 'userid', properties: {'prop1': ''},  'name':'name1'},**
        bot: { id: 'botid' },
        resize: 'detect'
      }, document.getElementById("botDiv"));

Ref - [https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/01.c.getting-started-migration](url)

When we migrated to bot framework SDK 4.4.3, we are unable to get "user" object and additional properties we were sending back to bot API handler.

The new direct line javascript upgrade does not have a way to send additional properties or data.
Can you please suggest
```
  (async function () {
     const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
     const { token } = await res.json();

     window.WebChat.renderWebChat({
       directLine: window.WebChat.createDirectLine({ token })
     }, document.getElementById('webchat'));
   })();
```
## To Reproduce
Steps to reproduce the behavior:
1. Integrate bot with directline javascript library on html page
2. User bot sdk 4.4.3, create .net core console app bot
3. Send additional properties and user object inside Bot.App javascript libarary
4. Try reading data from context.Acitivity.From

There are two properties in this userID and userName both are string, there is no way to send additional JSON property from the client or web portal.

## Expected behavior
There should be a way to send additional properties/data when creating a bot connection or sending post activity from a javascript client.


[Bug]

**Comment by EricDahlvang** [comment]
Hi @PrashantSoniHarman 

This sample demonstrates using ChannelData for additional properties: https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/15.a.backchannel-piggyback-on-outgoing-activities/index.html

This WebChat V4 solution should work for your scenario.

```js
        // We are adding a new middleware to customize the behavior of DIRECT_LINE/POST_ACTIVITY.
        const store = window.WebChat.createStore(
          {},
          ({ dispatch }) => next => action => {
            if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
              // The channelData submitted here is very similar to HTTP cookies and vulnerable to forgery attack.
              // Make sure you use signature to protect it and verify the signature on the bot side.
              // To minimize unexpected behaviors, we recommend to treat the "action" object as if it is immutable.
              // We use simple-update-in package to update "action" with partial deep cloning.
              action = window.simpleUpdateIn(action, ['payload', 'activity', 'channelData', 'email'], () => 'johndoe@example.com');
            }
            return next(action);
          }
        );
        window.WebChat.renderWebChat({
          directLine: window.WebChat.createDirectLine({ token }),
          // We will use a custom version of Redux store, which we added middleware to handle backchannel messages.
          store
        }, document.getElementById('webchat'));
```

**Comment by dvaibhav181** [comment]
Hi, I am not able to get window.simpleUpdateIn function. I have added simple-update-in @2.2.1 package in my code. I am trying to use it in .ts file and did import from package. Refer below:

import {  } from 'simple-update-in';
.
.
.
if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
       action = window.simpleUpdateIn(action, ['payload', 'activity', 'channelData', 'alias'], () => this.userAlias);
}
return next(action);

Error: (TS) Property simpleUpdateIn does not exist on type 'Window'. 

Notice 'W' in window, I am not sure why it;d doing that. Any pointers?

**Comment by corinagum** [comment]
It sounds like you're using import, which would mean you need to import the package to your js file. if you are importing the package via script, you should reference simpleUpdateIn through the browser.
