### ISSUE TITLE
Cognitive Speech Service does not always work when integrated with BOT. The BOT does not always speak out is the issue.

### ISSUE THREAD

**Issue by shmisra** [microsoft/BotFramework-WebChat#2048]
The below code takes Microphone input converts to TEXT. It then also speaks out the TEXT. Many a times the BOT does not speak out. What's the reason behing that? The issue can be reproduced in any browser. 

<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Cognitive Services Speech Services using JavaScript</title>
    

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
    <style>
      html, body { height: 100% }
      body { margin: 0 }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function () {
        // In this demo, we are using Direct Line token from MockBot.
        // To talk to your bot, you should use the token exchanged using your Direct Line secret.
        // You should never put the Direct Line secret in the browser or client app.
        // https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication

        const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
        const { token } = await res.json();

        // To run this demo, you can either use our authorization token, or provide your own subscription key thru ?s=BING_SPEECH_SUBSCRIPTION_KEY
        const searchParams = new URLSearchParams(window.location.search);
        const subscriptionKey = 'YOUR SPEECH SERVICE KEY';
        let webSpeechPonyfillFactory;

        if (subscriptionKey) {
          // In case you are using your own subscription key, please note that client should always authenticate against your server
          // to avoid exposing the subscription key to any part of your client code.
          webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
            region: 'westus',
            subscriptionKey
          });
        } else {
          const res = await fetch('https://webchat-mockbot.azurewebsites.net/speechservices/token', { method: 'POST' });
          const { region, token: authorizationToken } = await res.json();

          webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({ authorizationToken, region });
        }

        // Pass a Web Speech ponyfill factory to renderWebChat.
        // You can also use your own speech engine given it is compliant to W3C Web Speech API, https://w3c.github.io/speech-api/.
        // For implementor, look at createBrowserWebSpeechPonyfill.js for details.
        window.WebChat.renderWebChat({
          directLine: window.WebChat.createDirectLine({ token }),
          webSpeechPonyfillFactory
        }, document.getElementById('webchat'));

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>

**Comment by corinagum** [comment]
@shmisra, we recently resolved a bug that was preventing queued messages from being spoken by the bot. You can take a look at the content of that discussion and fix over at https://github.com/microsoft/BotFramework-WebChat/issues/1736. This fix will be available for the 4.5 release. 

If this is not your issue, please provide any console errors you may be seeing and reproduction steps, and even a video if you think that helps. In that case I will reopen this issue and relabel it as a bug.
