### ISSUE TITLE
OnMembersAdded not thrown when entering Web Chat in AzurePortal

### ISSUE THREAD

**Issue by nk111** [microsoft/BotFramework-WebChat#2049]
## Screenshots

![image](https://user-images.githubusercontent.com/155322/58703889-714c1000-83aa-11e9-8aaa-83a1cdd4b26b.png)

## Describe the bug
The official CoreBot project template has a welcome message implemented which should be sent in OnMembersAddedAsync. When using the "Test in Web Chat" feature in the Azure portal this event is not thrown. Reason is that the recipient.id equals the membersAdded.id in the first conversationUpdate message being sent (see attached screen shot).  

## To Reproduce
1. Go to the Channel registration of your bot in Azure portal
2. Click on "Test in Web Chat"
3. You wont see any welcome message sent in OnMembersAddedAsync

## Expected behavior
Configured welcome message should be displayed.

## Additional context

[Bug]

**Comment by nk111** [comment]
For reference: This is the reason why the event is not triggered if recipient.id equals the added members id. 

![image](https://user-images.githubusercontent.com/155322/58704710-3dbeb500-83ad-11e9-99f0-5f6aa4f9602d.png)

So the question is why does web chat sends the bot id as membersAdded in the first conversation update when entering web chat? When i send the first message a correct conversationUpdate is sent with my id as memberAdded. But this makes it complicated to test the real dialog flow.

**Comment by cwhitten** [comment]
@nk111 the Bot Framework protocol sends two ConversationUpdates, one for the Bot when it enters the conversation and one for the User after they have sent their first message. This is not governed by WebChat, but built-in to the protocol events themselves itself. As a group we are discussion how to change this behavior for a better user experience, but this is what we have in place today.

**Comment by corinagum** [comment]
@nk111, Web Chat has it's own recommended method for providing a welcome message, which you can take a look at on https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event, our welcome message sample.

**Comment by nk111** [comment]
Thanks for the heads up. But this doesn't solve the problem in the Azure
portal. I doubt this implementation sends this action?? Instead it sends
this first somewhat weird conversation update where the the recipient
equals the sender. I'd still call this a bug (on the portal side).

Corina <notifications@github.com> schrieb am Fr., 31. Mai 2019, 21:18:

**Comment by corinagum** [comment]
@nk111, unfortunately these scenarios follow current protocol and there are no changes imminent. 
If you want to add a suggestion on how to improve implementation, I recommend filing an issue on https://github.com/Microsoft/BotFramework-Services/issues for ABS or Connector Services, or a DCR on the BotBuilder sdk repo https://github.com/microsoft/botframework-sdk/issues

**Comment by naukhez** [comment]
Hi,

unfortunately I am also facing the same issue. Do you have an resolution?
@nk111

**Comment by pagoru** [comment]
I'm in the same situation... and I don't know what to do.
Works fine on the local machine, but not on the azure server.

> @nk111, Web Chat has it's own recommended method for providing a welcome message, which you can take a look at on https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event, our welcome message sample.

The link is down...

**Comment by corinagum** [comment]
we have documentation on [welcome messages](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md#tokens-user-ids-and-iframes). Could you go through these docs and verify your implementation? Please let me know your results.

**Comment by pagoru** [comment]
> we have documentation on [welcome messages](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md#tokens-user-ids-and-iframes). Could you go through these docs and verify your implementation? Please let me know your results.

Yeah, now works fine, but it's a little bit tricky. I'm currently working on a port from v3 to v4.
