### ISSUE TITLE
Bot is not speaking all the time

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-WebChat#2051]
From Meenakshi Balekar in ICM 124058492

Meenakshi reported a bot that does not speak despite knowing that the bot is hitting the correct endpoint for text to speech. Please refer to ICM 124058492 for additional details but continue conversation and tracking here.

**Comment by corinagum** [comment]
I tested out the bot provided on this IcM and had trouble with speech in Chrome, but it worked well for all prompts in Edge. 
mebaleka, I'm wondering if this is related to #1736. I will need go investigate this further.

**Comment by corinagum** [comment]
This fix was added recently by @compulim #2035. We want the customer to be able to test with latest bits to ensure their problem will be fixed, but right now we are not releasing master to CDN. Will follow up with team at our next triage.

**Comment by corinagum** [comment]
Fix is verified in #2035. It will be officially released for 4.5 in July. If you need this fix immediately, please cherry-pick the above PR into a locally hosted version of Web Chat.
