### ISSUE TITLE
OAuthCards  not working with Web Chat channel

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/BotFramework-WebChat#2053]
I have configured web chat channel and added iframe code on our website. I noticed OAuthCards not working with Web Chat channel.

Also, can i utilize existing Virtual Assistant Service Application  Default.htm page to initiate Web Chat with OAuthCards. Any example?

**Comment by darrenj** [comment]
Transferring to webchat team for assistance

**Comment by tdurnford** [comment]
As @darrenj mentioned, the iFrame currently uses Web Chat v3 which does not support OAuth Cards. However, the development team is beginning the process of switch clients using embedded Web Chat from v3 to v4, so this issue should resolve itself with time. Please take a look at the [documentation](https://github.com/Microsoft/BotFramework-WebChat/tree/master/packages/embed) for more details regarding embedded Web Chat.

If you need an immediate fix, I would recommend switching to Web Chat v4. Please feel free to peruse our [samples](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples), which provide a lot of ideas and foundation for getting started and customizing your version of Web Chat v4.
