### ISSUE TITLE
WebChat v4 : Framework is unable to load source maps for the React Components available in BotFramework-WebChat-Component package

### ISSUE THREAD

**Issue by cmevawala** [microsoft/BotFramework-WebChat#2058]
## Screenshots

![image](https://user-images.githubusercontent.com/3982352/59024704-187bec00-8870-11e9-91aa-70614612cd10.png)

## Version

WebChat as an NPM package. 

## Describe the bug

When a developer wants to debug a React components using Playground Project it should display the original source code inside the browser console instead of Babelified Code.

**No Console Errors**

## To Reproduce

1. Go to 'Playground Package'
2. Run  'npm start'
3. Press 'F12 and Search for BasicWebChat.js'
4. You will see that instead of Original Source it displays Babelified Code

## Expected behavior
Expected : When a developer Search for React Component it should display actual Source Code.

**Comment by cmevawala** [comment]
Tagging @mathurvarun84, @gturbahn1, @corinagum

**Comment by cmevawala** [comment]
@hannadrehman : Please let me know if you can help me out here. I saw that you also faced the similiar issue while working on this repo: https://github.com/hannadrehman/react-monorepo

**Comment by corinagum** [comment]
Let me reproduce this and get back to you. Thanks for filing.

**Comment by cmevawala** [comment]
This working now after pointing to webchat.instrumented.js. Hence closing this issue
