### ISSUE TITLE
Adaptive card render error

### ISSUE THREAD

**Issue by saurabhgupta1090** [microsoft/BotFramework-WebChat#2066]
Previously i am using webchat v3 in client side and sdk v3 in server side. it is working fine and i am able to load all adepative card content. Now i am using webchat v4 from client side for same directline secret but now adaptive card is not rendering giving error as "Adaptive card render error".Please let me know how the fix that issue.

Thanks

**Comment by corinagum** [comment]
Hi @saurabhgupta1090, could you provide a json file of you Adaptive Card data?

**Comment by tdurnford** [comment]
@saurabhgupta1090 Are you still having an issue with this? If so, would you mind adding the JSON you are using for your adaptive card along with the code you are using to send the card?

**Comment by saurabhgupta1090** [comment]
Thanks for all showing interest in this issue.
I resolved this issue now.
