### ISSUE TITLE
Web Chat throwing 'adaptiveCard.validate is not a function' error

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-WebChat#2068]
## Screenshots
![image](https://user-images.githubusercontent.com/17039790/59242356-11324680-8bc0-11e9-81a4-1c6c3fc5bf67.png)

## Version
Version: 0.0.0-0
Local build from master branch

## Describe the bug
In the most resent release of AdaptiveCards - v1.2 - the developers removed the validate function from the renderer.  Web Chat updated the AdaptiveCards dependency in PR https://github.com/microsoft/BotFramework-WebChat/pull/2064 to v1.2; however, the [AdaptiveCardRenderer](https://github.com/microsoft/BotFramework-WebChat/blob/4f21f0bf5e5d2cfa0e5304bc6c37c9c95357fc29/packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardRenderer.js#L120) component still uses the validate function. As a result, Web Chat is throwing an  'adaptiveCard.validate is not a function' error.

> The CardElement.validate() and Action.validate() methods have been REMOVED, replaced with CardObject.validateProperties() and CardObject.internalValidateProperties(context: ValidationContext). Custom elements and actions now must override internalValidateProperties and add validation failures as appropriate to the context object passed as a parameter using its addFailure method. Be sure to always call super.internalValidateProperties(context) in your override.

https://www.npmjs.com/package/adaptivecards#breaking-changes

In addition to reconfiguring the AdaptiveCardRenderer component, AdaptiveCard tests should be added to prevent errors like this in the future. 

## To Reproduce
Send an AdaptiveCard to Web Chat

```javascript
const card = CardFactory.adaptiveCard({
  "type": "AdaptiveCard",
  "body": [
      {
          "type": "TextBlock",
          "text": "AdaptiveCard"
      }
  ],
  "actions": [
      {
          "type": "Action.OpenUrl",
          "title": "Action.OpenUrl",
          "url": "https://microsoft.com"
      }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.1"
});

await context.sendActivity({ attachments: [card]});
```

[Bug]

**Comment by tdurnford** [comment]
It looks like AdaptiveCards also removed the speak property from the TextBlock class in v1.2, and it is still being used in the [AdaptiveCardBuilder](https://github.com/microsoft/BotFramework-WebChat/blob/fd7cead33870d3bf5c3c43a4e217e5a56ed033ae/packages/bundle/src/adaptiveCards/Attachment/AdaptiveCardBuilder.ts#L92) component. Web Chat throws a "Property 'speak' does not exist on type 'TextBlock'" error during build.

![image](https://user-images.githubusercontent.com/17039790/59310633-e1388100-8c5b-11e9-9330-d6b0ac26170e.png)

**Comment by corinagum** [comment]
THANK YOU for all the research @tdurnford!!!
