### ISSUE TITLE
Let developer filter hyperlinks (and other content?)

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#207]
Provide a way for the developer to filter links in messages. Some options:
- Developer could provide a custom hyperlink click handler to handle navigation
- Developer could provide a handler to filter out unwanted content (including but not limited to hyperlinks).

For tracking, the idea began here: https://github.com/Microsoft/BotFramework-WebChat/issues/199

**Comment by billba** [comment]
I say wait until someone asks for this. I don't want to spend time adding configuration for hypothetical scenarios.

**Comment by sgellock** [comment]
agree with @billba feedback.
