### ISSUE TITLE
Mobile scrolling momentum

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#208]
Since the autoscroll (dock to bottom) is managing the scroll position, it seems this is interfering with native "momentum" on mobile.

**Comment by billba** [comment]
Is it the autoscrolling, or the handling of the scroll event?

**Comment by danmarshall** [comment]
not sure :) will have to see when working on it

**Comment by sgellock** [comment]
we switched to a new component so this issue no longer applies.
