### ISSUE TITLE
The image/files are always sent to the another/wrong webchat window

### ISSUE THREAD

**Issue by huajunzhao** [microsoft/BotFramework-WebChat#2084]
## Screenshots

![image](https://user-images.githubusercontent.com/3183325/59598149-18140880-912e-11e9-8015-ef992f07c2ec.png)

## To Reproduce

We have embedded two same webchat in html file based on the V3 source code in the same webpage.
1. Run the sample code from samples/fullwindows/index.html (with a little change which has 2 webchat window, the index.html is attached.)
1. Go to 'http://localhost:8000/samples/fullwindow/'
2. Click on "button1" or "button2" to upload the images/files
3. You will see the strange behavior that the images may be always to the same webchat window. This is not expected. In my screenshot, it always shown in right chat window.
4. But if you type the message and send, it works correctly.

## Expected behavior

Please help check in your side and fix it accordingly.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Unfortunately v3 of Web Chat is in sunset mode right now and we're not performing maintenance that doesn't fall under security issues for v3. 

Could you try out your bot on a basic v4 web page made by following our sample 01.a? This is just to test if your errors are persisting to v4 of Web Chat. If so, we'll be able to investigate the problem and file this as a bug. Otherwise, my immediate fix recommendation would be to use v4 through CDN or MyGet until we get v4 available via embed, which will hopefully be in the upcoming weeks.

**Comment by huajunzhao** [comment]
@corinagum Thanks for your response.

We have the online production environment which is highly depending on V3. I understand V3 is in unset mode. but could you please help us confirm if this is a bug in V3(I think it's easily reproduce by following the above steps) or something is wrong while we use it then we can use apply any quick workaround?

Regarding your suggestion to use V4, yeah, we've already started investigate how to migrate from V3 to V4, however, there's some APIs/interface changes. we need to change much code and then perform more testing before go live.  Hope you can understand our concerns.

Let me know if you have any questions.

**Comment by huajunzhao** [comment]
@corinagum  While test in the V4 01.a sample index.html as below

 <body>
    <div id="webchat" role="main"></div>
    <div id="webchat2" role="main"></div>
    <script>
      (async function () {
        // In this demo, we are using Direct Line token from MockBot.
        // To talk to your bot, you should use the token exchanged using your Direct Line secret.
        // You should never put the Direct Line secret in the browser or client app.
        // https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication

        const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
        const { token } = await res.json();

        window.WebChat.renderWebChat({
          directLine: window.WebChat.createDirectLine({ token })
        }, document.getElementById('webchat'));

        window.WebChat.renderWebChat({
          directLine: window.WebChat.createDirectLine({ token })
        }, document.getElementById('webchat2'));

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>

Two webchat windows seems use the same conversation id, then two webchat windows have the same message/images while sending.

![image](https://user-images.githubusercontent.com/3183325/59648890-2bb58280-91b3-11e9-9c51-aa152b8573a1.png)

Do you know how to use the different conversation id while initializing the webchat?


In v3 sample code. if I embed 2 webchat in the sample/fullwindow index.html code. they have the different conversation id.

<body>
    <div id="BotChatGoesHere"></div>
    <div id="BotChatGoesHere2"></div>
    <script src="../../botchat.js"></script>
    <script>
      const params = BotChat.queryParams(location.search);

      const user = {
        id: new Date().valueOf().toString(),
        name: 'Guest'
      };

      const bot = {
        id: 'chatbot-sea-int',
        name: 'xiaoyun'
      };

      window['botchatDebug'] = true;

      BotChat.App({
        bot: bot,
        locale: 'en-us',
        resize: 'window',
        // sendTyping: true,    // defaults to false. set to true to send 'typing' activities to bot (and other users) when user is typing
        user: user,
        // locale: 'es-es', // override locale to Spanish

        directLine: {
          secret: 'xxxxx',
        }
      }, document.getElementById('BotChatGoesHere'));

      BotChat.App({
        bot: bot,
        locale: 'en-us',
        resize: 'window',
        // sendTyping: true,    // defaults to false. set to true to send 'typing' activities to bot (and other users) when user is typing
        user: user,
        // locale: 'es-es', // override locale to Spanish

        directLine: {
          secret: 'xxxx',
        }
      }, document.getElementById('BotChatGoesHere2'));

    </script>
  </body>

Please comment

**Comment by tdurnford** [comment]
You need to use different tokens for each instance of Web Chat; otherwise, each chat window will reference the same conversation. The conversation id is baked into the token.

**Comment by tdurnford** [comment]
@huajunzhao I was able to reproduce the error in v3. It does look like when you send an attachment in the second instance of Web Chat v3, the attachment gets sent in first instance. Unfortunately, as @corinagum, Web Chat v3 is in sunset and we're not performing maintenance that doesn't fall under security issues at this time. 

Everything works as expected in Web Chat v4  if you use two different tokens.

![image](https://user-images.githubusercontent.com/17039790/59712615-6e328b80-91c2-11e9-91c3-c1a6afa1c4b8.png)


Hope this helps!
