### ISSUE TITLE
[Question] Preview webchat.js

### ISSUE THREAD

**Issue by tiagodenoronha** [microsoft/BotFramework-WebChat#2091]
Good morning,

Keep in mind that my experience with JS, TS and such is very limited, to this might sound like a very strange question :)

Imagine if we have just pushed a PR for a new language and we want to test it in the WebChat.
How can we build the repository in order to (locally) test the changes we introduced?

I saw that we have an explanation [here](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits) but imagining I'm only developing the bot and I only want to use the minimal JS WebChat, how can I use these instructions to get the latest changes?

Am I mixing things up?
Is there any way I can contribute with more documentation on the subject in case anyone else faces the same issue as me?

[Question]

**Comment by tdurnford** [comment]
If you want to build and run Web Chat locally, I would recommend taking a look at the [Contributing](https://github.com/microsoft/BotFramework-WebChat/blob/master/.github/CONTRIBUTING.md) read me - it includes details on how to build the project. Once it's built, you can serve the project files by running `npx serve`, and then you can change the link for the CDN in your HTML page file 
 from https://cdn.botframework.com/botframework-webchat/master/webchat.js to http://localhost:5000/packages/bundle/dist/webchat.js to see the changes.

**Comment by corinagum** [comment]
@tiagodenoronha we welcome community Pull Requests! Please check out the contributing page and note that we have some hoops to jump through (like signing the SLA) before we can accept your Pull Request. Look forward to seeing your contributions. :)

**Comment by tiagodenoronha** [comment]
Hmm... shouldn't building the project be somewhere else besides contributing.md?
Asking because it's a bit hard to find :D
@corinagum already had the pleasure to contribute to the repo!

**Comment by corinagum** [comment]
@tiagodenoronha haha that's right, I'm not so good at context-switching. Sorry for forgetting!

Our main concern with the contributing file is that our root README.md is already extremely large, so we try to divide it up into different contexts when possible. That being said, if you have improvement suggestions, feel free create a PR with those changes - this will open the discussion on how to improve our documentation. :)

Please keep in mind that while our root README is very cluttered, right now only our root README.md and SAMPLE.md files are being transferred onto the Microsoft Docs official site. Let me know if you have other questions.
