### ISSUE TITLE
Adaptive cards don't render the Image dimensions

### ISSUE THREAD

**Issue by harischristodoulidis** [microsoft/BotFramework-WebChat#2092]
The IImage interface defined in https://github.com/Microsoft/AdaptiveCards/blob/master/source/nodejs/adaptivecards/src/schema.ts:
inherits the properties of ICardElement

```
export interface IImage extends ICardElement {
	type: 'Image';
	altText?: string;
	selectAction?: IAction;
	size?: Size;
	style?: ImageStyle;
	url: string;
}
```

```
export interface ICardElement {
	id?: string;
	speak?: string;
	horizontalAlignment?: HorizontalAlignment;
	spacing?: Spacing;
	separator?: boolean;
	height?: 'auto' | 'stretch';
	[propName: string]: any;
}
```
ICardElement has a height property which can be 'auto' or 'stretch'
It does not have a width property

e.g. I take a json which has a column with this Image item:
```
{
  type: 'Column',
  style: 'default',
  items: [
    {
      type: 'Image',
      horizontalAlignment: 'Right',
      url:
        'http://cdn.onlinewebfonts.com/svg/img_286083.png',
      size: 'Small',
      width: '16px',
      height: '16px',
      altText: '',
    },
  ],
  width: 'auto',
},
```

The width and height of the Images are not rendered. The image is displayed with the default dimensions.

Can you please help?

**Comment by tdurnford** [comment]
Setting the image height and width in an AdaptiveCard seems to working fine in Web Chat. What channel are you using, and what version of AdaptiveCards are you using? Try removing the size attribute from image element. 

**AdaptiveCard**
```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                        {
                            "type": "Image",
                            "url": "http://cdn.onlinewebfonts.com/svg/img_286083.png",
                            "width": "50px",
                            "height": "50px",
                            "altText": ""
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Screenshot**

![image](https://user-images.githubusercontent.com/17039790/59782719-739bde80-9273-11e9-9a74-9866fd65d094.png)

**Comment by harischristodoulidis** [comment]
I deleted the size attribute but it still does not work. I used your json also. The version I am using is 1.0 also.

**Comment by tdurnford** [comment]
What channel are you using? Can you add screenshots and the code you are using to send the AdaptiveCard?

**Comment by tdurnford** [comment]
The image height and width properties were just added to AdaptiveCards in one of their most recent releases - v1.1. Web Chat v4 is currently the only channel that supports the most recent release of AdaptiveCards, so if you try to set those properties in any other channel (Web Chat v3, Test in Web Chat in the Azure Portal, Teams, Skype, Messenger, etc.), they will be ignored by the client's card rendered.  Other channels should hopefully be updated in the near future, but in the meantime, they do not support attributes new to AdaptiveCards.

Closing this issue as AdaptiveCards v1.2 and image height and width are supported in Web Chat v4.
