### ISSUE TITLE
Custom adaptiveCardHostConfig not working using ReactWebChat

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotFramework-WebChat#2102]
Please find the issue in stackoverflow at: https://stackoverflow.com/questions/56298444/action-button-renders-as-full-width-of-the-card

Please check the Update 1 section.

**Comment by corinagum** [comment]
This bug has been fixed and will be available in our next release in July. If you need these changes immediately, please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Comment by tdurnford** [comment]
@vikramdadwal 

As @corinagum mentioned, this fix should be available in the next release.  I apologize for not mentioning that in the other [issue](https://github.com/microsoft/BotFramework-WebChat/issues/2034) regarding this problem.

![image](https://user-images.githubusercontent.com/17039790/59878855-33fdf100-935e-11e9-975a-d15cd9044579.png)

**Comment by vikramdadwal** [comment]
@corinagum @tdurnford  is this now available in the latest v4.5.0 ?

**Comment by corinagum** [comment]
yes, 4.5 was released last week.
