### ISSUE TITLE
[Chat pane]: Timestamp does not get updated in real time for the messages

### ISSUE THREAD

**Issue by jftian** [microsoft/BotFramework-WebChat#2103]
## Screenshots

![message-timestamp-error](https://user-images.githubusercontent.com/41656922/59868072-bd082e80-9344-11e9-8396-cbdeddd52900.png)

## Version
4.3.0

## Describe the bug
As the screenshot shows, the message timestamps are not updated correctly.

## To Reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/07.a.customization-timestamp-grouping/ 
2. Click on 'Don't group'
3. Keep your browser idle for a few minutes

## Expected behavior

Timestamp should get updated in real time for the messages sent by user in chat pane

## Additional context

Our product is using the botframework-webchat and getting the same error.
![canvas_timestamp2](https://user-images.githubusercontent.com/41656922/59868555-02792b80-9346-11e9-9fb8-51a2d33a18b0.JPG)

[Bug]

**Comment by corinagum** [comment]
This bug has been fixed in #2090 and will be available in our next release in July. If you need these changes immediately, please see our documentation on pointing to our MyGet feed for latest bits.

**Comment by jftian** [comment]
> This bug has been fixed in #2090 and will be available in our next release in July. If you need these changes immediately, please see our documentation on pointing to our MyGet feed for latest bits.

Thanks Corina.
