### ISSUE TITLE
AdaptiveCardHostConfig is not being passed to CommonCard component as a prop

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-WebChat#2106]
## Screenshots

![image](https://user-images.githubusercontent.com/17039790/59886110-99f47380-9372-11e9-8e5b-73858fce9f36.png)

## Version
Local build: 0.0.0-0

## Describe the bug
Rich Cards that are built on top of the CommonCard Component - AnimationCards, AudioCards, SignInCards, and VideoCards - are not passing the AdaptiveCardHostConfig as prop to CommonCard. Web Chat is raising a "The prop \`adaptiveCardHostConfig\` is marked as required in \`CommonCard\`, but its value is \`undefined\`." warning as a result. 

## To Reproduce

Send one of the cards mentioned above as an attachment to Web Chat. 

```javascript
await context.sendActivity({ attachments: [
  CardFactory.animationCard(
     'Microsoft Bot Framework',
      [ { url: 'https://i.giphy.com/Ki55RUbOV5njy.gif' }],
      [],
      { subtitle: 'Animation Card' });
  ] 
});
```

[Bug]

**Comment by corinagum** [comment]
Assigning to self until @tdurnford is back in org. He claimed this one!
