### ISSUE TITLE
In '06.d.speech-web-browser' sample: TTS (Text-to-Speech) only speaks the first message

### ISSUE THREAD

**Issue by AviralGarg1993** [microsoft/BotFramework-WebChat#2113]
## Screenshots

![image](https://user-images.githubusercontent.com/12901566/59958220-d8b02980-9457-11e9-97a0-7c652c1893b4.png)

## Version

WebChat version

## To Reproduce

1. Create an echo bot with bot sending 1+ sendActivities in one turn.
2. Use `06.d.speech-web-browser` [Microsoft-webChat sample](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/06.d.speech-web-browser) for front-end.
3. The bot would only speak the first message. (in my case: the one circled in red in the image above)

This much information should be sufficient. Otherwise, let me know and I can provide more info.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
This bug has been fixed and will be available in our next release in July. If you need these changes immediately, please see our documentation on pointing to our MyGet feed for latest bits.

https://github.com/microsoft/BotFramework-WebChat/issues/1736
