### ISSUE TITLE
Passing existing conversation ID and Secret to DirectLine API results in a new conversation

### ISSUE THREAD

**Issue by artemvalmus** [microsoft/BotFramework-WebChat#2116]
What we need is to connect to the existing conversation using the DirectLine Secret and the conversation ID. 

According to the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0) we use [https://directline.botframework.com/v3/directline/conversations](https://directline.botframework.com/v3/directline/conversations) endpoint and pass the conversation ID like the following: https://directline.botframework.com/v3/directline/conversations/7ESOvfEbZMfKJT26XOiACN-h. 

But the token returned has **another conversation ID** in the payload and passing this token into `createDirectLine` from the `botframework-webchat` library (v 4.3.0) results in a new conversation. 

Is this an expected behavior? How do we reconnect to the existing conversation?

**Comment by tdurnford** [comment]
This appears to be working fine using a Web Chat Secret. If you are using a DirectLine Secret, you, unfortunately, have to have Enhanced Authentication disabled.

```javascript
let { conversationId } = session Storage;


let token;
if (conversationId) {
  const res = await fetch(`https://directline.botframework.com/v3/directline/conversations/${conversationId}`, { 
    method: 'GET',
    headers: {
      'Authorization': `Bearer <WEB_CHAT_SECRET>`,
    },
  });

  let { token: directLineToken } = await res.json();
  token = directLineToken;

} else {
  const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', { 
    method: 'POST',
    headers: {
      'Authorization': `Bearer <WEB_CHAT_SECRET>`,
    }
  });

  let { token: directLineToken, conversationId } = await res.json();
  token = directLineToken;
  sessionStorage.conversationId = conversationId;

}
```

Note, for simplicity I'm saving the conversationId in session storage and requesting on the client side; however,  its best to manage your tokens on the server side instead.
