### ISSUE TITLE
Clean up README.md

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2129]
## Describe the bug

Things to clean up in `README.md` and `CHANGELOG.md` before release. Please add to this list if something come up in your mind.

Since the clean up could be big and potentially conflicting with all incoming PRs, so make it just before release will ease our burden on merging PRs.

- [x] `*`: Microsoft organization name change
   - `https://github.com/Microsoft/BotFramework-WebChat` should become `https://github.com/microsoft/BotFramework-WebChat`
   - Our organization name changed to lowercase
- [x] `CHANGELOG.md`: "Update Japanese locale to" or "Update Japanese to"
   - We have mixed use of "Update XXX locale to", and "Update XXX to"
- Typo for `CHANGELOG.md`
   - [x] `sip` to `SIP` or `sip:`
   - [x] "AdaptiveCards" to "Adaptive Cards"
- Typo for `19.a/README.md` line 138
   - [x] Add a note for PROXY_BOT_URL
      - "To enable this feature, add `PROXY_BOT_URL=http://localhost:3978` to `/web/.env`"
      - This note can be found in other samples (19.b and 20.a)

### Addendum for typos for `CHANGELOG.md`

-  Fix [#1980](https://github.com/Microsoft/BotFramework-WebChat/issues/1980). Changed `sendBoxTextArea` styles to break words longer than the `<textarea>`, by [@tdurnford](https://github.com/tdurnford) in PR [#1986](https://github.com/Microsoft/BotFramework-WebChat/pull/1986)
-  Fix [#1429](https://github.com/Microsoft/BotFramework-WebChat/issues/1429). Changed Markdown-It options to render newline characters correctly, by [@tdurnford](https://github.com/tdurnford) in PR [#1988](https://github.com/Microsoft/BotFramework-WebChat/pull/1988)

[Bug]

**Comment by corinagum** [comment]
This issue is almost ready to go - just waiting for 2 more PR's to be merged in.

**Comment by corinagum** [comment]
Not sure what your fix is for #1429 (last item)
