### ISSUE TITLE
Initiate conversation from Javascript

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotFramework-WebChat#213]
Hi, 

My bot application requires the username to start the chat conversation. Currently, I am sending it through chat window. Is there a way, I can change the botchat.js to accept the username and send it as a message before starting the formal conversation ?  

Could you provide more documentation of the type script and javascript code ?

**Comment by danmarshall** [comment]
Yes, you can pass userid and username through the url:
https://github.com/Microsoft/BotFramework-WebChat/blob/master/public/index.html#L37

**Comment by kanwal019** [comment]
@danmarshall  Can I add the conversation name in the similar manner ?

**Comment by billba** [comment]
@kanwal019 WebCht doesn't have a concept of "'conversation name"

**Comment by danmarshall** [comment]
@kanwal019 you do have the option of changing the titleBar of the control, through the string localization: https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Strings.ts#L21

@billba I suppose it would be good to document how someone may pass in their localized string table (without doing their own build)

**Comment by billba** [comment]
@danmarshall currently you can't pass in a localized string table without doing your own build. Interesting idea though.

**Comment by billba** [comment]
@kanwal019 The bot won't have access to the username until WebChat sends a message (at which point you can access it in the `from` field in the message). If you'd like to proactively send a message to the bot before the formal conversation begins, you can send a postBack message (a message that is not shown by the control).

In your web page, after you create the botConnection, do this: 

`
botConnection.postActivity({
    type: 'message',
    text: 'username',
    from: user
}).subscribe();
`

Your bot should look for a message with the text 'username'. In the future there will be a somewhat better way to go about this, but this works.

Please let me know if all the above information solves your problem so that I can close this issue.

**Comment by kanwal019** [comment]
Thank You @billba, I was talking about the conversation id that is displayed in JSON request in emulator. I hope it will help the channel recognize the conversation as a user can have multiple.

The postback message provided got an ajax 403 error, as displayed below.
![capture](https://cloud.githubusercontent.com/assets/15017434/21080989/bb4ccb4c-bfe2-11e6-9620-542198d22674.PNG)

However, passing the username as shown in (https://github.com/Microsoft/BotFramework-WebChat/blob/master/public/index.html#L37), worked for me. I will really help a lot, if I am able to generate and pass a conversation name/id in the same manner.

Thank You very much again :+1:

**Comment by billba** [comment]
Ah yes. The problem there is that the DirectLine must be started first (by calling `start()`), and that currently happens in the WebChat. I need to think through the lifecycle here a bit.

The conversationId is generated when you start the conversation, and is made available to the bot in the `conversationId` field in the message.

**Comment by danmarshall** [comment]
Also @kanwal019 just so you are aware of other options, you can copy the content of the [index.html](https://github.com/Microsoft/BotFramework-WebChat/blob/master/public/index.html) and server it from your own web server, and populate the username etc. on the server side, instead of a URL param.

**Comment by billba** [comment]
I have removed the `start()` method from DirectLine, and the need to call it. The postBack code I supplied above should now work correctly.

**Comment by billba** [comment]
Closing this as I think this addresses all your issues. Please let me know if there's something I'm missing.

**Comment by danmarshall** [comment]
@billba it looks like we lost some history of the ability to pass username via url since the public folder has been removed. Can we add documentation to the readme on how to pass additional parameters?

**Comment by billba** [comment]
It's all there. The public folder is now the samples folder.

**Comment by canaanites** [comment]
@billba when I do this

`botConnection.postActivity({ type: 'message', text: 'Hello', from: { id: 'agent'} }).subscribe();`

My bot sends the message 'hello' and then replies to it with 'Hi, how can I help you?'. At this point, it seems like the bot is talking to itself. How can I disable the response from the bot?

I thought maybe if I change the from-id to bot (`from: { id: 'bot'}`), it would work, but it didn't.

it would be great if we can do something like this:

```
botConnection.postActivity({
        type: "message",
        text: text,
        value: value,
        from: from,
        locale: locale,
        **reply: false**
    })
```

**Comment by canaanites** [comment]
I have fixed it by modifying my bot's code:

```
if (context.request.type === 'message' && context.request.from.id !== 'agent') {
         return new RootTopic(context).onReceive(context);
    }
```

**Comment by billba** [comment]
@canaanites that works, but best practice is to send an activity with type `event` so that you can clearly differentiate it from your `message` activities.

**Comment by canaanites** [comment]
@billba I have tried this, but it didn't work:

My Bot code:

```
if (context.request.type === 'event') {
        console.log('#####', context.request.text, context.request.value);
        context.reply(`Agent:  ${context.request.text}`);
        return;
    }
```

WebChat:

```
botConnection.postActivity({
        type: 'event',
        text: 'Hello there',
        value: 'greeting',
        from: {id: 'agent', name: 'agent'},
    }).subscribe();
```

Am I missing something? I didn't get the console log message. It seems like the bot was not able to receive the `event`
