### ISSUE TITLE
Sample: simpler SSO approach for always-authenticated conversation

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2133]
## Feature Request

> Including @cwhitten and @darrenj.

**Is your feature request related to a problem? Please describe.**

The current SSO sample handles the most flexible case of SSO, hybrid conversation with anonymous and authenticated chats.

For Intranet scenario, we could simplify it by forcing the end-user to authenticate before a conversation can be started (or, before the end-user land on the page).

**Describe the suggestion or request in detail**

- Simplifies the current SSO sample
- Detects whether we have a valid OAuth access token
   - If yes, continue and send it to the bot on start
   - If no, redirect the user to OAuth provider
- When the user land on the page, they must be authenticated
   - On conversation start, we will send the bot the OAuth access token

**Describe alternatives you have considered**

- Using IIS authentication
   - This approach does not support OAuth but a [handful of limited authentication providers](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to): Microsoft, Google, Twitter, Facebook, and Azure AD
   - In this approach, the conversation will be always-authenticated
- Using refresh token to eliminate popups
   - Because of the privilege granted by refresh token, it need to be handled in a very secure way (only servers are allowed to store the token, browsers should not store the token)
   - This will negate the simplicity of the sample

[Enhancement]

**Comment by djpirra** [comment]
I also think this would be very appreciated for an Enterprise level implementation.
Does this work cross channel? Authentication would remain active if I chat either on Web or Teams for example?

**Comment by darrenj** [comment]
@compulim Thanks - this sounds good but how were you planning to retrieve/source the oauth access token? The goal is to have silent retrieval (if your on the intranet) - i.e. no auth prompts at all.

IIS only using Azure AD is fine as it's an enterprise scenario so you may want to consider that option especially if it enables silent retrieval (no auth prompts)

**Comment by corinagum** [comment]
(Triage notes: I believe this is a current work item for @compulim, but not designated for the 4.5 release. I'm going to add it to 4.6 with the intention that it will be merged in asap after 4.5. @compulim please correct me if I'm wrong)

**Comment by compulim** [comment]
@djpirra Yes or no. No, the approach mentioned here is different than Teams. But yes, you can write a bot that do authentication differently depends on the client (Teams or Web Chat). But I am not sure if the bot could hold a conversation that appears on both Teams and Web Chat at the same time, for the same user.

The reason why we are doing differently is because some OAuth providers do not allow multiple OAuth redirect URIs. And without the support of multiple redirect URIs, you can only authenticate the user via 
the web app, or the bot, but not both.

This work is actually based on one of the newest sample (19.a). We are technically approaching the problem the same way, minus the sign-in/out UI button and single-page application support. Thus, it makes the code simpler, by trading off UI components and UX story.

**Comment by compulim** [comment]
@darrenj Yes, this is for silent retrieval, no UI parts. That means, this is same as [Azure Web App authentication](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization), with multiple redirect took place before it finally land on the page.

But instead of doing it on the server, we are doing in on the HTML + JavaScript side. The token is being saved on `sessionStorage` and validated on every page refresh.

Doing it this way, we can support wide range of OAuth providers, e.g. GitHub and LinkedIn, which are not on the IIS list of authentication providers.

If needed, we can easily reduce this sample into another new sample that use Azure Web App authentication provider:

1. Instead of retrieving access token thru `sessionStorage`, we fetch it from `/.auth/me`, which is defined in [Azure Web App authentication](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to#retrieve-tokens-in-app-code)

Or in a more secure case, if the access token can never live inside the browser, we still could:

1. Retrieve the access token [thru HTTP headers injected by Azure Web App](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-how-to#retrieve-tokens-in-app-code)
2. On the server code, create a new Direct Line conversation (with generated token)
3. Use Bot Builder SDK on the web server to save the token to conversation state
4. Pass the Direct Line token thru `.cshtml` or other technologies and start Web Chat with it

**Comment by compulim** [comment]
@darrenj although the PR is not in yet, I have a working demo at http://webchat-sample-sso-intranet.azurewebsites.net. Please take a look and see if the silent retrieval here is what you are looking for. 😉

**Comment by darrenj** [comment]
Yes! From a quick test this is exactly what we were after :-)
