### ISSUE TITLE
Issues with MockBot  - 502 

### ISSUE THREAD

**Issue by mattmazzola** [microsoft/BotFramework-WebChat#2136]
## Screenshots

Not really applicable as there seem to be authentication errors and the bot not sending is side affect of that.
![image](https://user-images.githubusercontent.com/2856501/60408160-a054cd80-9b72-11e9-8566-04c47f8d2e8e.png)

Ironically the actual code returns is 502 Bad Gateway, but the JSON error message says 404. That might help indicate problem.
![image](https://user-images.githubusercontent.com/2856501/60408227-e1e57880-9b72-11e9-8db0-5e6e6a8fe784.png)

## Version

I had cloned the repo and was playing around with samples and everything was working fine. Then sometime around Saturday afternoon, they all stopped working. Tried various samples on my own repo, botframework-webchat, botframework-sampoles, and finally I thought I would use the deployed version to minimize error.

## Describe the bug

The MockBot does not work:
https://microsoft.github.io/BotFramework-WebChat/03.a.host-with-react/

I seems to get 2 different errors. Sometimes it says "Token or secret required" Even though the token request is sucessful. Othertimes it seems to get token, create conversation, but fail to send activity.

I'm guessing whichever service the bot is hosted on is just down or needs to be reset.

## To Reproduce

1. Go to 'https://microsoft.github.io/BotFramework-WebChat/03.a.host-with-react/'
2. Type your message: 'testing'

## Expected behavior
Bot should reply (I think it's the echo bot that replies with "You said: 'testing'"

## Additional context
Activity is not send, bot never replies

**Comment by corinagum** [comment]
Hi @mattmazzola, Thanks for filing this issue. I checked Mock Bot just now and unfortunately it seems intermittent -- I was able to converse with the bot just now without problems. 

We'll keep an eye on Mock Bot today. If anyone else is noticing this please feel free to leave a comment on this issue.

**Comment by mattmazzola** [comment]
Hmm, well good that it works now but bad that it's intermittent.

I guess, ideally it would become more stable, in future is there an easy way I can tell the health of this MockBot / directline service to isolate errors?

If we're developing bots and they starts failing, trying to diagnose if it's our code or the service is going to be confusing. Is there some specific URL I can put in the browser and if that GET request also fails then I know it's the service that's down instead of and error in my code?

**Comment by corinagum** [comment]
I took a look at Mock Bot on Azure Portal which revealed that the bot may have run out of funding over the weekend, and explains why you were unable to connect to Mock Bot. It looks like funds were just recently added and that's why everything is back online. 

Since Mock Bot is a personally-owned bot by @compulim, I would recommend writing your own locally-running bot and testing against that if reliability is of strong importance to your developer story. @compulim please feel free to add any insight.

**Comment by compulim** [comment]
Thanks for reporting, @mattmazzola.

This time, it's not about Azure funding. It is about bad settings, i.e. `https://yourbot.com/api/messages` vs. `https://yourbot.com/api/messages/`.

I have fixed it about 12 hours ago so it should be fixed by now. 😉

**Comment by mattmazzola** [comment]
Hmm, that makes it sounds like it's not an intermittent thing.

Are you saying these steps happened:
1. the bot was working
2. the setting changed over the weekend which put it in a broken state
2. then you corrected the setting 12 hours ago which is why we're seeing it work correctly now?
