### ISSUE TITLE
Feature: Make thumbnail of upload image into channelData

### ISSUE THREAD

**Issue by handsomeyao77** [microsoft/BotFramework-WebChat#2138]
[Edit by corinagum]: this issue has a workaround. Please see @EricDahlvang's comment at the bottom of this thread: 
> @handsomeyao77 Please see the workaround described here: [microsoft/botbuilder-dotnet#2143 (comment)](https://github.com/microsoft/botbuilder-dotnet/issues/2143#issuecomment-508830039)

--------
## Original comment:
Hi team,
I get an frequency error, the pictures can't be rendered in chat window, it's broken.

![image](https://user-images.githubusercontent.com/7311188/60490293-d4e29980-9cd8-11e9-8711-77788f54fcd2.png)

I view this picture src attribute in html:  
 src="https://bcdirectlineauseast.blob.core.windows.net/at27055/LSfhGXesbMy-original"

I think this is invalidate, because the right src in html is:
 src="https://directline.botframework.com/attachments/F7RM2rUmRwUI1uS3WxU8LF-0/0000113/0/win10-gbi-19.jpg?t=ew0KICAiYWxnIjogIlJTMjU2IiwNCiAgImtpZCI6ICJBT08tZXhGd2puR3lDTEJhOTgwVkxOME1tUTgiLA0KICAieDV0IjogIkFPTy1leEZ3am5HeUNMQmE5ODBWTE4wTW1ROCIsDQogICJ0eXAiOiAiSldUIg0KfQ.ew0KICAiYm90IjogImNoYXRib3Qtc2VhLWludCIsDQogICJzaXRlIjogImd0amo3anhFVWFjIiwNCiAgImNvbnYiOiAiRjdSTTJyVW1Sd1VJMXVTM1d4VThMRi0wLTAwMDAxMTMiLA0KICAibmJmIjogMTU2MjA0OTY3OSwNCiAgImV4cCI6IDE1NjIwNTE0NzksDQogICJpc3MiOiAiaHR0cHM6Ly9kaXJlY3RsaW5lLmJvdGZyYW1ld29yay5jb20vIiwNCiAgImF1ZCI6ICJodHRwczovL2RpcmVjdGxpbmUuYm90ZnJhbWV3b3JrLmNvbS8iDQp9.LKtl-Od1isNFau_40g1SMD4YAF6_qrI7sxC9qRXqWru5UJBzCSHfLWMKlzZbNk3yUMvagSbk2ThXkLxihuWeDIR3wMPVllsz7ubEiaIRqRuRhYtb3I8HpPiERmij1G4SSEar4ZOw1B7B5ugMK3bEf_0o1Ir4B6GNtOU0v6yMzbl52FZUzHjMVeHxDeLUdLF1m79YKWH5zaa74pX_yrXz0BQnahFlXRemAyL8IdKOuOHU7e9j4Zzag6Ca7Ump3xbBa9BCvAzrp_i28zlE7oM8qCzaShLX1iVNWLMcS0-YYGODedlILEOdnn3TCWdJGkPtFidNsQNI0q81fjBwsixOWg"

The webchat version is V3.

We have multiple chat dialog in the same time, if we switch between these dialog, the image message in chat window often broken.

![image](https://user-images.githubusercontent.com/7311188/60490834-e7110780-9cd9-11e9-9810-22911c4b4606.png)

## To Reproduce

1. Create more than 2 chat dialog
2. Chatting with any one(Dialog1), send text or image to him/her
3. Then switch to another one(Dialog2), send text or image  to him/her
4. Now switch back to 2# (Dialog1), the image which your sent is broken in chat window.

Please kindly help me on this issue, thanks very much!

**Comment by tdurnford** [comment]
Seems related to https://github.com/microsoft/BotFramework-WebChat/issues/2084

**Comment by tdurnford** [comment]
Unfortunately v3 of Web Chat is in sunset mode right now and we're not performing maintenance that doesn't fall under security issues for v3.

Could you try out your bot on a basic v4 web page made by following our sample 01.a? This is just to test if your errors are persisting to v4 of Web Chat. If so, we'll be able to investigate the problem and file this as a bug. Otherwise, my immediate fix recommendation would be to use v4 through CDN or MyGet until we get v4 available via embed, which will hopefully be in the upcoming weeks.

**Comment by handsomeyao77** [comment]
@tdurnford , thanks your quickly response.

I try to upgrade webchat version to V4, it seems this error still exists:

![image](https://user-images.githubusercontent.com/7311188/60574619-7981db80-9dac-11e9-94a2-38014309dfef.png)


Besides, the image can't be show  as itself size, it looks like limited in 480px*240 px.

**Comment by tdurnford** [comment]
@handsomeyao77 I'm having a difficult time reproducing this issue. Can you share the files you are uploading? It looks like you are sending a text file and a png. Also, double check the file size. Direct Line limits attachments to 4MB.

**Comment by tdurnford** [comment]
@handsomeyao77 I was able to reproduce the error. The issue only occurs if you pass the Direct Line secret to Direct Line instead of exchanging it for a token first. Try using the code snippet below to test your bot. 

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>WebChat</title>
  <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
  <style>
    html, body { height: 100% }
    body { 
      margin: 0;
      }
    #webchat {
      height: 100%;
    }
  </style>
</head>
<body>
  <div id="webchat" role="main"></div>
  <script>
    (async function() {
      const webChatSecret = '<DIRECT_LINE_SECRET>';
      const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', { 
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${webChatSecret}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ user: { id: 'dl_user_123' }})
      });
      const { token } = await res.json();
      const directLine = window.WebChat.createDirectLine({ token });
      window.WebChat.renderWebChat({
        directLine,
      }, document.getElementById('webchat'));
    })().catch(err => console.log(err));
  
  </script>
</body>
```

Thank you @stevkan for recommending this fix.

**Comment by handsomeyao77** [comment]
@tdurnford , thanks your solution.
I used token instead secret to init DirectLine, just like the sample your provided

![image](https://user-images.githubusercontent.com/7311188/60647938-73096780-9e71-11e9-8ab3-98d4d56a188b.png)

Unfortunately,  it occurs again, the image src attribute in html is: https://bcdirectlineeasia2.blob.core.windows.net/at27104/8RLaaFI7rYl-original

![image](https://user-images.githubusercontent.com/7311188/60648136-e4491a80-9e71-11e9-9b18-98f6f5914e6e.png)

**Comment by handsomeyao77** [comment]
@tdurnford , this bug is really urgent for me, could you give me more helps?

**Comment by EricDahlvang** [comment]
@handsomeyao77  Please see the workaround described here: https://github.com/microsoft/botbuilder-dotnet/issues/2143#issuecomment-508830039

**Comment by handsomeyao77** [comment]
@EricDahlvang , thank you!

I read [microsoft/botbuilder-donet#2143](https://github.com/microsoft/botbuilder-dotnet/issues/2143) related info, this is different from our scenario.

Some times we upload image successfully:
![image](https://user-images.githubusercontent.com/7311188/60780476-2f647580-a171-11e9-90a1-1e8e045c921d.png)

But if I refresh our bot page or switch to other same host page  , the image gets broken, the request URL is invalid.
![image](https://user-images.githubusercontent.com/7311188/60780530-78b4c500-a171-11e9-9789-31fcbf16d501.png)

We save the images in our storage too, but we can't render images in chat window, all the messages in chat window are from bot-framework service. 
We have to provide other page to show the images to user. It's not convenient to us to process huge business cases in short time.

**Comment by EricDahlvang** [comment]
Hi @handsomeyao77 

The best solution to workaround what you are experiencing is to create a thumbnail of the uploaded file and add it to channelData, then set the contentUrl to that channelData in DIRECT_LINE/INCOMING_ACTIVITY as demonstrated in the linked example.

**Comment by handsomeyao77** [comment]
Hi@EricDahlvang , thanks your response.

I am trying the workaround your mentioned: create a downscale image then add to channelData.

Now, I am using this sample [React-web-Chat-Redux](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/14.customization-piping-to-redux) to create a listener to listen upload file event.

But I found that this sample has two ReactWebChats component.

One in App.js, the other in webchat.js.
![image](https://user-images.githubusercontent.com/7311188/60937003-9d3fa700-a301-11e9-84d9-aa92d754ddf4.png)
![image](https://user-images.githubusercontent.com/7311188/60937031-b34d6780-a301-11e9-82cb-5e3a3fa1f161.png)

Why do we have to init two WebChats? We only one WebChat in our page.

**Comment by tdurnford** [comment]
There is really just one instance of the `ReactWebChat` component in the project. The component created in the WebChat.js file acts a container for the `ReactWebChat` component imported from the BotFramework-WebChat dependency. All of the logic in this file is responsible for creating the DirectLine Connection and the Custom Store Middleware. In theory, all of this code could be moved to the App.js file, but that wouldn't be the best design for larger scale apps. 

The App.js file imports the component created in WebChat.js - the one that is acting as a container - and adds it to the App. The `ReactWebChat` component in this file is different from the `ReactWebChat` component in the WebChat.js file and should probably be renamed to just `WebChat` or `WebChatContainer`  to avoid confusion. If you would like, you change the component name in the App.js file in your project to help clarify the difference.

**App.js**
```javascript
import { connect } from 'react-redux';
import React from 'react';

import WebChatContainer from './WebChat';

class App extends React.Component {
  render() {
    const { props: {
      backgroundColor,
      dispatch
    } } = this;

    return (
      <div id="app" style={{ backgroundColor }}>
        <WebChatContainer appDispatch={ dispatch } />
      </div>
    )
  }
}

export default connect(
  ({ backgroundColor }) => ({ backgroundColor })
)(App)
```

Hope this helps!

**Comment by handsomeyao77** [comment]
Hi @EricDahlvang, here are some summaries what i met share to you.

#1. Create a listener.

![image](https://user-images.githubusercontent.com/7311188/60952810-882d3d00-a32e-11e9-9127-7e90e2994cd4.png)

#2. Listener implement .
export default function(dispatch) {
    return () => next => action => {
      if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
         if (action.payload.activity && action.payload.activity.attachments) {
           const downscaledImages = Promise.all(
             action.payload.activity.attachments.map(
               ({ contentType, contentUrl }) => /^image\//.test(contentType) ? downscaleImage(contentUrl, contentType, 480) : null
             )
           );
           console.log(downscaledImages);
           (action.payload.activity.channelData || (action.payload.activity.channelData = {})).thumbnails = downscaledImages;
         }
       } else if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') {
         const activity = action.payload.activity;
 
         if (activity && activity.attachments && activity.channelData && activity.channelData.thumbnails) {
           action.payload.activity.attachments = activity.attachments.map((attachment, index) => ({
             ...attachment,
             contentUrl: activity.channelData.thumbnails[index] || attachment.contentUrl
           }));
           console.log(activity.attachments);
         }
       }
       return next(action);
    };
 }

#3. Upload an image, render in chat window successfully, the contentUrl is correct.
![image](https://user-images.githubusercontent.com/7311188/60952894-bb6fcc00-a32e-11e9-9b84-4796e576e162.png)

We can alert this image width and height in listener.
![image](https://user-images.githubusercontent.com/7311188/60953221-52d51f00-a32f-11e9-88b0-c8be4398bf33.png)

![image](https://user-images.githubusercontent.com/7311188/60953230-5799d300-a32f-11e9-98b5-3ad4e3d74eb8.png)

![image](https://user-images.githubusercontent.com/7311188/60952943-cd516f00-a32e-11e9-92f0-9601cd892bb9.png)

#4. But if i refresh the page, the contentUrl is invalid, so image broken, I think this is the root cause. 
![image](https://user-images.githubusercontent.com/7311188/60953009-ef4af180-a32e-11e9-88ca-afc4eb8abcb6.png)

![image](https://user-images.githubusercontent.com/7311188/60953025-f540d280-a32e-11e9-9a7a-79ed1c4611f7.png)

**Comment by handsomeyao77** [comment]
Append some related functions:

    async function downscaleImage(imageURL, contentType, maxSize) {
      const image = document.createElement('img');
      const imageLoadPromise = eventToPromise(image, 'load');

      image.src = imageURL;
      alert(image.src);
      await imageLoadPromise;

      const canvas = document.createElement('canvas');

      canvas.height = image.height > image.width ? maxSize : ~~(image.height / image.width * maxSize);
      canvas.width = image.width > image.height ? maxSize : ~~(image.width / image.height * maxSize);
      alert(canvas.height);
      alert(canvas.width);
      canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height);

      const dataURL = canvas.toDataURL(contentType);

      return dataURL;
    }
    function eventToPromise(target, name) {
      return new Promise((resolve, reject) => {
      const handler = event => {
         target.removeEventListener(name, handler);
         resolve(event);
      };
    }
      target.addEventListener(name, handler);
      });
 }

**Comment by handsomeyao77** [comment]
@tdurnford  Thanks your explanation, it really helps me a lot.

**Comment by compulim** [comment]
@cwhitten We talked about making thumbnail in Web Chat via `<canvas>`.

Could you give me some suggestions in this topic? E.g. do we need to use Web Worker if available?

**Comment by cwhitten** [comment]
We're going to defer the logic into a WebWorker on browsers that support it - if the client is on a browser that does not fully support the isolation to run inside a WebWorker we will run the same logic on the main thread. cc @compulim

**Comment by handsomeyao77** [comment]
Hi team, 

Thanks for your workaround: https://github.com/microsoft/BotFramework-WebChat/issues/2138#issuecomment-509316793, we fixed the image broken after refresh issue.

But, we  encountered the other image related error:
Image src is a default placeholder:
![image](https://user-images.githubusercontent.com/7311188/62109344-a90a0200-b2de-11e9-92eb-7b27292e4fd0.png)

just like this : https://github.com/microsoft/BotFramework-WebChat/issues/2152.

The new issue is different from the old one, should I open a new issue on GitHub?

**Comment by aamalhot** [comment]
Hi Team,
We are facing the same default placeholder issue. Do we have any ETA for the fix? Also, please share any known issues/ limitations once the fix is deployed.

Thanks!

**Comment by compulim** [comment]
The PR #2206 for this issue is pending for review.

It will generate thumbnails and save it as part of the activity (i.e. channelData). The downscaling is verified to work in IE11 and all modern browsers including Safari.
