### ISSUE TITLE
sendTypingIndicator is true but the gif animation of typing Indicator does not show for the bot

### ISSUE THREAD

**Issue by jchen706** [microsoft/BotFramework-WebChat#2141]
![image](https://user-images.githubusercontent.com/32785168/60548454-1f234500-9cf0-11e9-854a-9493d6676f0a.png)

**Comment by jchen706** [comment]
Above is what i Have

**Comment by jchen706** [comment]
![image](https://user-images.githubusercontent.com/32785168/60548658-9c4eba00-9cf0-11e9-95a6-7ac073670126.png)
![image](https://user-images.githubusercontent.com/32785168/60548708-c0120000-9cf0-11e9-81da-5d97980797a9.png)

**Comment by jchen706** [comment]
Above is the console from the browser output.

**Comment by tdurnford** [comment]
The typing indicator prop is intended to notify the bot when the user is typing. Basically it just sends a typing activity to the bot when the user is typing a message. I'm not entirely sure if it's supposed to display the typing animation or not.  If you want to display a typing indicator when the bot is sending a message, you have to send a typing activity from the bot.

```javascript 
this.onMessage(async (context, next) => {

  await context.sendActivity({ type: ActivityTypes.Typing });
  await timeout(3000)
  await context.sendActivity(`You said: '${context.activity.text}.'`);
  await next();
});

....

const timeout = ms => 
    new Promise(resolve => setTimeout(resolve, ms));
 ```

**Comment by corinagum** [comment]
https://microsoft.github.io/BotFramework-WebChat/07.b.customization-send-typing-indicator/

typing indicator from user sample is working as expected.

**Comment by jchen706** [comment]
Thanks,
For anyone in the future for reference in C# .NET Core with Bot Framework, 

ITypingActivity replyActivity = Activity.CreateTypingActivity();
await turnContext.SendActivityAsync((Activity) replyActivity);
await Task.Delay(3000);
