### ISSUE TITLE
Magic code is still required for authentication despite using token and OAuthCard.

### ISSUE THREAD

**Issue by as09033** [microsoft/BotFramework-WebChat#2142]
I have been following [this comment](https://github.com/microsoft/botframework-sdk/issues/4632#issuecomment-441957719) to remove the requirement for the magic code when users authenticate to my bot, however despite following each of these steps the magic code is still required.

In order to implement the authentication I followed [18. Bot Authentication](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication). Everything seems to be working fine except that it requires users to enter the magic code each time they want to log in. 

In order to exchange the secret for a directline token, I followed [this page](https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/). I can see that my bot is now using a token rather than a secret. In the instructions, it said to enable _Enhanced authentication options_ (on the Azure portal) in order to leverage no magic code. However I was experiencing another issue before and [this thread](https://github.com/microsoft/BotFramework-WebChat/issues/2120) helped me to fix it - the solution was to disable _Enhanced authentication options_. So now this is disabled because re-enabling it causes my previous issue to return.

Any idea on what I can do to fix this?

## Controller
```csharp
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using MyBot.Models;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MyBot.Controllers
{
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var secret = {SECRET};
            HttpClient client = new HttpClient();
            HttpRequestMessage request = new HttpRequestMessage(
                HttpMethod.Post,
                $" https://directline.botframework.com/v3/directline/tokens/generate");

            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", secret);

            var userId = $"dl_{Guid.NewGuid()}";
            request.Content = new StringContent(
                new { User = new { Id = userId } }),
                Encoding.UTF8,
                "application/json");

            var response = await client.SendAsync(request);
            string token = String.Empty;

            if (response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync();
                token = JsonConvert.DeserializeObject<DirectLineToken>(body).token;
            }

            var config = new ChatConfig()
            {
                Token = token,
                UserId = userId,
            };

            return View(config);
        }
    }
}
```

## View Page
```html
@model MyBot.Models.ChatConfig

<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>My Bot</title>

    <script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
    
    <style>
        html, body { height: 100% }
        body { margin: 0 }
        #webchat { height: 100%; width: 100%; }
    </style>

</head>
<body>
    <div id="webchat" role="main"></div>
    <script>
        (async function() {
            const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
                if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
                    dispatch({
                        type: 'WEB_CHAT/SEND_EVENT',
                        payload: {
                            name: 'webchat/join',
                            value: { language: window.navigator.language }
                        }
                    });
                }

                return next(action);
            });

            window.WebChat.renderWebChat({
                directLine: window.WebChat.createDirectLine({ token: `@Model.Token` }),
                userId: `@Model.UserId`,
                store
            }, document.getElementById('webchat'));

            window.addEventListener('botonloadmessage', ({ data }) => {
                console.log(`Received an activity of type "${data.type}":`);
                console.log(data);
            });

            document.querySelector('#webchat > *').focus();
        }) ().catch(err => console.error(err));

    </script>
</body>
</html>
```

The authentication part of my code is essentially identical to the one provided in [18. Bot Authentication](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/18.bot-authentication).

**Comment by tdurnford** [comment]
@as09033 Removing the user id is only a temporary solution. The BotFramework Development team fixed the user id issue and will deploy the update in the next few weeks - hopefully, sooner. 

Going forward, Direct Line conversations initialized with a token that has a user id will send one conversation update event that has bot the bot id and user id. Thus, sending the backchannel welcome event in the store middleware in this token scenario won't be necessary since the conversation update should trigger the welcome message before the user messages the bot.  

Hope this helps!

**Comment by as09033** [comment]
Thanks for the response! Do you perhaps have a bug# that I can use to track this issue so that I'll know when it's deployed?

**Comment by tdurnford** [comment]
The fix should be deployed
