### ISSUE TITLE
How does someone using Windows Speech Recognition use the Azure V4 webchat UI?

### ISSUE THREAD

**Issue by guybark** [microsoft/BotFramework-WebChat#2143]
🚨 The issue tracker is not for implementation questions 🚨

I've just tried using Windows Speech Recognition (WSR) at the V4 webchat UI. I can use speech to move keyboard focus into the edit field fine, but I've not found any way to dictate a phrase into the field. Is this possible with WSR, or is it expected that I somehow enable the microphone button at the webchat UI and turn on the webchat's native support for speech input in order to dictate my question?

**Comment by guybark** [comment]
Based on what I've found on the web, WSR apparently doesn't work for inserting text in an edit field hosted in Edge. I wonder if that's true. In theory I can copy dictated text from (say) notepad into Edge, but a simpler path for me seems to be to use Chrome instead. I can seem to insert dictated text into the edit fields there ok.

**Comment by corinagum** [comment]
Hey @guybark, do you by chance have [Microsoft Insider's Edge](https://www.microsoftedgeinsider.com/en-us/)? Could you give that a go and see what happens?
