### ISSUE TITLE
Narrator does not speak timestamp of the activity

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2150]
## Describe the bug
The timestamp was removed from aria label, meaning that the Narrator will not inform the user how recently the activity was spoken. This was done because a bug was causing Narrator to not update the timestamp over time, but the preferred method would be to fix the timestamp updating in the label, or add the absolute time to the label (so that it will always say when it was said, and not need to be updated)
## To Reproduce

1. Open Narrator
2. Open Mock Bot
3. Type "Hello"
4. Note that Narrator does not mention any timestamp when speaking the activities in the transcript.

## Expected behavior
Narrator should speak the timestamp.

## Additional context
Related to https://github.com/microsoft/BotFramework-WebChat/pull/2018 

My question is, if we put the absolute time in the aria label, (@compulim's suggestion), do we also need to update the written timestamp to be absolute time instead of relative? To me these are conveying different types of the same information, but ultimately gives a different experience for the narrator-user and the non-narrator user. Any thoughts on this would be appreciated.

[Bug]

**Comment by cimbis** [comment]
I'm now investigating whether or not it is possible to make screen reader not read the timestamp.

I stumbled upon https://github.com/microsoft/BotFramework-WebChat/pull/2018 and the current issue.

@corinagum could you elaborate on the decision to return to initial behaviour (reading timestamps)?

In my opinion timestamps are irrelevant as long as screen reader is able to read messages in proper order, therefore I'd like to be able to choose whether or not timestamps are read out aloud.

**Comment by corinagum** [comment]
The general rule for accessibility is that 'any information available to a sighted user must also be available to a user without sight'. Within our team we have a11y compliance rules that we must follow, and this is one of the main principals that we adhere to.

Because of this, I don't see timestamps becoming optional as something we will implement. Ultimately, I also wouldn't recommend this for accessibility reasons. I realize it's a lot of work, but your alternative would be to rewrite the transcript and remove the screenreader pushes you don't want. 🙂
