### ISSUE TITLE
Image Upload returns default placeholder from directline

### ISSUE THREAD

**Issue by gsegares** [microsoft/BotFramework-WebChat#2152]
## Version
4.4

## Describe the bug
Directline is returning a default placeholder after uploading an image, causing the image to break in the webchat ui.

## To Reproduce
Use the Web Chat to upload an image using directline:
1. Setup the bot using the WebChat react component and directline.
2. Click on upload and select an image.
3. The image is uploaded but after it's sent to directline it returns an activity message with the wrong image url, which breaks the image displayed in the chat.
4. See error here https://www.screencast.com/t/VHdbgjQiTnr
5. The bot is able to process the correct image url from the back-end, you can see the bot responding in the video attached.
6. Also tested in Azure Web Chat and it works there, seems that the issue doesn't occur when using WebSockets but all of our projects use DirectLine API so we really need a fix ASAP.
7. See the image attached with the requests detail.
![File Upload Issue - BF](https://user-images.githubusercontent.com/2272565/60314767-edd90b00-99b7-11e9-81e4-3ca97f242834.png)

## Expected behavior
After we upload the image we shouldn't get an activity message from directline with a default placeholder, it should keep the valid url so it doesn't break image displayed in the webchat ui.

[bug]

**Comment by cwhitten** [comment]
The WebChat team is tracking this work on https://github.com/microsoft/BotFramework-WebChat/issues/2138 - we'll keep this open as a duplicate until #2138 is resolved.

**Comment by corinagum** [comment]
Closing as resolved :)
