### ISSUE TITLE
Add new `sendTypingIndicator` action dispatcher

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2157]
## Feature Request

**Is your feature request related to a problem? Please describe.**

No.

**Describe the suggestion or request in detail**

Today, we have multiple send actions:

- `sendEvent`
- `sendFiles`
- `sendMessage`

But we don't have `sendTypingIndicator`, we should add one.

But unfortunately, we already used `BasicWebChat.props.sendTypingIndicator` as a `true`/`false` value to indicate if we should send typing indicator to the bot.

We need a better plan to rename it to `shouldSendTypingIndicator` or find a better way for the action dispatcher.

**Describe alternatives you have considered**

**Additional context**

[Enhancement]

**Comment by tdurnford** [comment]
Right now, it looks like we are using `postActivity` to send a typing indicator to the bot. We could add one called `postTypingActivity` or `sendTypingActivity`. @corinagum @compulim  thoughts?

**Comment by tdurnford** [comment]
I think we settled on using `emitTypingIndicator`. Reassigning to @compulim since this falls in line with his work on migrating to React Hooks.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-WebChat/pull/2364
