### ISSUE TITLE
Write more tests for post-4.5 release

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2158]
## Feature Request

**Is your feature request related to a problem? Please describe.**
No

**Describe the suggestion or request in detail**
The following issues (mostly speech-related) should have more tests written:

- [x] #2016
- [x] #2087
- [x] ~#2096~
   - Not trivial to test `aria-label`
- [x] #2118

Also, the `mockWebSpeech.js` file needs more coverage in these areas:

- [x] Web Chat should select voice based on language
- [x] Web Chat should set `SpeechRecognition.lang` based on language
- Unhappy paths
   - [x] Bird tweets
   - [x] User denied access to microphone
   - [x] Unrecognizable voice (a.k.a. `no-match`)
   - [x] Network error or wrong credentials
- [x] Abort while recognizing, then restart microphone again (regression of #2240)
- TBD

## Speech tests around consecutive activities with different `inputHint`

> Note that 1st and 2nd activity could sometimes have a slight delay between them, ~1 second.

| 1st activity | 2nd activity | Should turn on microphone if via keyboard | Should turn on microphone if via microphone |
| - | - | - | - |
| Accepting input | Accepting input | No | No |
| Accepting input | Expecting input | No | Yes |
| Accepting input | Ignoring input | No | No |
| |
| Expecting input | Accepting input | No | Yes |
| Expecting input | Expecting input | No | Yes |
| Expecting input | Ignoring input | No | No (explicitly turn it off) |
| |
| Ignoring input | Accepting input | No | No |
| Ignoring input | Expecting input | No | Yes |
| Ignoring input | Ignoring input | No | No |

## Reliability issues

- [x] `suggested-actions command should show suggested actions with images`
   - After `emptycard` was sent, we didn't wait until suggested actions show up
   - Today, we use `minNumActivitiesShown` to test, but this cannot be used to test empty card or suggested actions
   - Use `suggestedActionsShowed` condition to wait until suggested actions show up before taking the snapshot

**Describe alternatives you have considered**
N/A

[Enhancement]

**Comment by compulim** [comment]
Reopening, we still have the input hint need to be tested.
