### ISSUE TITLE
NVDA focus is not moving to all the ‘chat messages’ in the chat box, while navigating using NVDA browser mode. 

### ISSUE THREAD

**Issue by maggi1129** [microsoft/BotFramework-WebChat#2163]
NVDA focus is not moving to all the ‘chat messages’ in the chat box, while navigating using NVDA browser mode. 

Voiceover focus is not moving to all the ‘chat messages’ in the chat box, while navigating using Voiceover swipe(right/left) method.

**Comment by corinagum** [comment]
Please update your post by following our bug template that provides the format to questions for us to be able to assist with your bug.

**Comment by compulim** [comment]
@maggi1129 we need more information about the bug, could you answer those questions in the bug template?

**Comment by maggi1129** [comment]
Sure, let me post it in a proper template by eod today
