### ISSUE TITLE
Role for 'New Messages' control or any other buttons in the chat messages are not narrated in narrator scan mode. 

### ISSUE THREAD

**Issue by maggi1129** [microsoft/BotFramework-WebChat#2164]
New Messages is not read as new messages button.

For any other button such as Yes/No/Signin, narrator doesn't read the role (button) and only reads the name of the button.

**Comment by maggi1129** [comment]
Same applies to download controls

**Comment by corinagum** [comment]
Please update your post by following our bug template that provides the format to questions for us to be able to assist with your bug.

**Comment by compulim** [comment]
@maggi1129 we need more information about the bug, could you answer those questions in the bug template?
