### ISSUE TITLE
Allow dev to try out speech in "Test in Web Chat" blade without a speech token

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2171]
@vishwacsena could you chime in here or over email? I am unsure how it can be secured in Emulator, but I know it is doable in Azure Portal.

**Comment by cwhitten** [comment]
Closing this as it's not a WebChat issue, but a ABS Portal issue. @bwamie and @tonyanziano did the work to consume the new speech token in the Emulator. @bwamie can you cut an action item in the Portal project to allow testing of Speech in the "Test in WebChat" blade?
