### ISSUE TITLE
Design: Send box v.Next

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2175]
Today's send box is hybrid. It works with 2 types of input at the same time, keyboard and microphone.

Thinking how will it look/feel if the type of the send box is fixed to one. And the user click on a button to switch between 2 modes.

So at a time, the user can only use one type of input.

Also, developer can add additional type of inputs or customize send box by building their own input.

**Comment by corinagum** [comment]
#1839
