### ISSUE TITLE
Will Angular support be added?

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotFramework-WebChat#2189]
## Feature Request
Will full angular support be added v7+?

**Comment by tdurnford** [comment]
Take a look at the  [Integrating Web Chat using Angular 6+](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.b.host-with-angular) Sample. Looking at the `package.json` file, I'm fairly certain it's built using Angular 7.

**Comment by corinagum** [comment]
@omarsourour is our resident Angular expert. Omar, do you have any thoughts on updating the sample to use Angular 7?
