### ISSUE TITLE
Not getting typing indicator on the chat window

### ISSUE THREAD

**Issue by siddiq-rehman** [Microsoft/BotFramework-WebChat#219]

**Comment by siddiq-rehman** [comment]
![image](https://cloud.githubusercontent.com/assets/22259730/21038923/c9b5df00-bdff-11e6-9c55-9ce58823cbe5.png)

**Comment by billba** [comment]
For reasons I don't entirely understand and/or endorse, The 'typing' indicator only transmitted through WebSocket. I recently pulled in WebSocket support but it's not quite ready for prime time, so it's off by default. You can experiment with turning it on. You will then see a very ugly TYPING indicator. See issue #35.

**Comment by siddiq-rehman** [comment]
Could you please help me out how can I turn it ON? Thanks in advanace

**Comment by billba** [comment]
sorry, yes. DirectLine now has an optional "webSocket" parameter. it currently defaults to false. set it to true.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
