### ISSUE TITLE
Suggested Actions Styleoptions for Cursor on Hover

### ISSUE THREAD

**Issue by Hatzman91** [microsoft/BotFramework-WebChat#2204]
It would be really nice if the Cursor on Hover over Suggested Actions could be customized

**Comment by corinagum** [comment]
Could you elaborate on your request? My first reaction is to say that the cursor is typically left alone on web apps, but perhaps you're thinking of a feature I haven't thought of. Do you have screencaps or a video of what you are looking for?

**Comment by Hatzman91** [comment]
We customized our webchat to have the CD of our website, and we have an hover effect for our buttons, and it feels weird when the suggested actions don't have the pointer cursor

Our Buttons with pointer:
![image](https://user-images.githubusercontent.com/26482488/61612166-04445080-ac5e-11e9-82ce-9931e706094a.png)

Suggested actoins (sadly) without:
![image](https://user-images.githubusercontent.com/26482488/61612306-73ba4000-ac5e-11e9-97fe-7cbd995c57e1.png)

Thanks for your time!

**Comment by corinagum** [comment]
Removing the pointer is a conscious decision on the part of the Web Chat team, as detailed here: 
 https://github.com/microsoft/BotFramework-WebChat/issues/1767

Please note that this is also a simple css change and your app can make the adjustment by using idiosyncratic styling from our [samples](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples).

**Comment by Hatzman91** [comment]
Ok, then we will do that, thank you!
