### ISSUE TITLE
Several Adaptive Cards on Mock Bot need fixing

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2205]
#2198  Screenshots
N/A

## Describe the bug
The following adaptive cards throw errors when run in basic Web Chat:
- card breakfast
![image](https://user-images.githubusercontent.com/14900841/61565305-771ab500-aa2d-11e9-8fd3-50be09801aee.png)

- card markdown
![image](https://user-images.githubusercontent.com/14900841/61565344-99143780-aa2d-11e9-9226-b1b92e3b213a.png)

- card sportsclub
![image](https://user-images.githubusercontent.com/14900841/61565358-a29d9f80-aa2d-11e9-9614-379e61c1ea4b.png)

## To Reproduce

Use the above commands on Mock bot

[Bug]

NOTE: we should also test all of Mock Bot's Adaptive Cards

**Comment by tdurnford** [comment]
PR https://github.com/compulim/BotFramework-MockBot/pull/20 should fix the ID issues in Mock Bot's Adaptive Cards and the table in the markdown card. The list items not wrapping probably will have to be fixed in Web Chat.

**Comment by corinagum** [comment]
Approved and merged. Should we keep this open for tracking the list item issue?

**Comment by tdurnford** [comment]
The text block overflowing the container appears to be an issue with Adaptive Cards. I opened an issue in their GitHub Repo https://github.com/microsoft/AdaptiveCards/issues/3311
