### ISSUE TITLE
There are bubble border color and other style settings that are not working

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotFramework-WebChat#2207]
The border color and border width are not working         

bubbleBackground: '#353535',
          bubbleBorderWidth: 0,
          bubbleBorderStyle: 'none',
          bubbleFromUserBorderWidth: 5,
          bubbleBorderColor: 'green',
          bubbleBorderRadius: 0,
          bubbleFromUserBorderColor: 'black',
          bubbleFromUserTextColor: 'white',
          bubbleTextColor: 'white',
          sendBoxTextColor: 'white',
          bubbleFromUserBackground: '#353535',

**Comment by compulim** [comment]
Can you fill out the bug form? What versions of Web Chat are you using?

**Comment by xtianus79** [comment]
@compulim is new and is not in 4.5 yet. What version is current?

**Comment by compulim** [comment]
Current production version is 4.5, which was released 11 days ago.

`bubbleBorderWidth` is in #2137, which is merged 4 days ago, and is in the development build of 4.6.

**Comment by premaarya** [comment]
Late october is so late ... wish it was earlier we have a production release coming up...

**Comment by corinagum** [comment]
If you need these changes immediately, please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Comment by alokraj68** [comment]
Is it working now?
Cannot set `bubbleFromUserBorderColor: 'rgb(89,101,109)'` in style options. 
Only the default `#e6e6e6` is working.
Using **4.5.3** version of the webchat.

**Comment by narik1989** [comment]
i am using in the below mentioned way and it is working fine. I am also using 4.5.3 only. 

bubbleFromUserBackground: 'rgba(0, 255, 0, .1)',
