### ISSUE TITLE
Design changes that would be necessary for minimal design and mobile i.e. scroll bar adjustments

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotFramework-WebChat#2215]
## Feature Request

Just my first impressions of styling the bot per the documentation... The controls should be true to the intended css functionality meaning, changing by a single whole number is not always ideal as a user may want to use 10, 0, 0, 10 for example.  

Also, the scroll bar needs the ability to be adjusted, especially on mobile.  Having a thinner scroll bar may be ideal for may various applications.  On a mobile device a scroll bar is not necessary as touch panning up and down is very efficient.  Mobile does not mean only phone.  

As well, opacity adjustments or blur for text boxes may be desirable. I have not fully vetted out the rgba so I am not entirely sure how that works.  

Other than that it isn't too bad for making design adjustments but I would have to do more testing.

**Comment by corinagum** [comment]
You're going to have to be more specific regarding your first request. what whole numbers are you interested in changing that you are unable to change right now?

Your other requests should be adjustable via [idiosyncratic styling](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.b.idiosyncratic-manual-styling). If you try this sample out and still have trouble, feel free to let us know.

**Comment by xtianus79** [comment]
@corinagum the whole numbers in css are the border radious in a complete square/rectangle format i.e. 10, 10, 10, 10 is written shorthand as 10.  but if I want the right and bottom left only it would be something like 10, 0, 0, 10.  

I will try the idiosyncratic styling to see if i can create what you're referring to.

**Comment by xtianus79** [comment]
@corinagum 
So I have added the idiosyncratic styling and it's a little confusing on the context of the object and what each part is doing per se.  I will include my code below.  It works 

One question I have is when you use the idiosyncratic styling you cannot use the styloptions(preferred) override method as it seems to not work in coordination with the styleset(non-preferred) method.  Is this the case? 

Also, what is the different from the const variable setup to the specific file override... meaning, if I edit the const in styleset is that the exact same thing as editing the styleoptions method? i.e. the defaultstyleoptions.js method way of doing things

Lastly, if I edit the specific files beyond changing the names of those files i.e. root to base for example, would that cause a breaking change even if I create a css class inside of the specific file of per se root.js?  
I think so I just want to confirm. 

If it is not advisable and code could break should I do a pull request to have edits in place for the scroll bar styling through webkit? 

here is the code below 

```
        const styleSet = window.WebChat.createStyleSet({
          rootHeight: '100%',
          botAvatarInitials: 'BF',
          userAvatarInitials: 'CH',
          backgroundColor: '#131313',
          bubbleBackground: '#353535',
          bubbleBorderWidth: 0,
          bubbleBorderStyle: 'none',
          bubbleFromUserBorderWidth: 5,
          bubbleBorderColor: 'green',
          bubbleBorderRadius: 0,
          bubbleFromUserBorderColor: 'black',
          bubbleFromUserTextColor: 'white',
          bubbleTextColor: 'white',
          sendBoxTextColor: 'white',
          bubbleFromUserBackground: '#353535',
          sendBoxBackground: '#131313',
          sendBoxBorderTop: 'solid 0px #E6E6E6',
         });

        const styleOptions = {
          rootHeight: '100%',
          botAvatarInitials: 'BF',
          userAvatarInitials: 'CH',
          backgroundColor: '#131313',
          bubbleBackground: '#353535',
          bubbleBorderWidth: 0,
          bubbleBorderStyle: 'none',
          bubbleFromUserBorderWidth: 5,
          bubbleBorderColor: 'green',
          bubbleBorderRadius: 0,
          bubbleFromUserBorderColor: 'black',
          bubbleFromUserTextColor: 'white',
          bubbleTextColor: 'white',
          sendBoxTextColor: 'white',
          bubbleFromUserBackground: '#353535',
          sendBoxBackground: '#131313',
          sendBoxBorderTop: 'solid 0px #E6E6E6',



        }

        


        styleSet.textContent = Object.assign(
          {},
          styleSet.textContent,
          {
            // fontFamily: '\'Comic Sans MS\', \'Arial\', sans-serif',
            // fontWeight: 'bold',
            // cursor: 'crosshair',
          }
        );

        styleSet.root = Object.assign(
          {},
          styleSet.root,
          {
            // background: 'red',
            // cursor: 'crosshair',

            /* width */
            ' ::-webkit-scrollbar': {
              width: '3px'
            },

            /* Track */
            ' ::-webkit-scrollbar-track': {
              background: '#353535' 
            },

            /* Handle */
            ' ::-webkit-scrollbar-thumb': {
              background: '#131313' 
            },

            /* Handle on hover */
            ' ::-webkit-scrollbar-thumb:hover': {
              background: 'red' 
            }           

          }
        );
```

here is a screenshot of the final product

<img width="608" alt="bot-styling-example" src="https://user-images.githubusercontent.com/8476336/61759857-9734d600-ad97-11e9-95c9-71a2c426c012.png">

**Comment by corinagum** [comment]
Changing the border radius worked fine for me:
![image](https://user-images.githubusercontent.com/14900841/61893562-373b4e00-aec3-11e9-864e-e258b779a994.png)
This is my styleOptions change: `bubbleBorderRadius: '10px 25px',`

Idiosyncratic styling by nature should override your styleoptions changes if they are conflicting. @compulim, do you have input on this?
I'm inclined to say that scrollbar styling is not something we will be adding to Web Chat, but perhaps team members have a different opinion.

It sounds like you are deving off a fork of v4, which unfortunately we don't support. However, v4 of Web Chat is intended to be customizable without forking, which is supported. :) editing styleoptions is one of the ways we provide users with the ability to customize without having to make changes to the Web Chat code itself.

Glad to see you got the changes you were looking for. Closing this issue :)
I believe what you are saying about changing the files and component names is correct and this would be considered breaking changes.

Questions for the team - 
- Do we want to enable scrollbar adjustments to the app? Since scrollbar css is very browser specific my understanding is that this would be unnecessary.

**Comment by xtianus79** [comment]
@corinagum thanks for the tips. From what I see the styleset does override styleoptions... but at the core they are the same and use the same properties to change things. What's different is when you choose to edit a component right?  I'll give a code sample below. 

So am I correct in saying until you choose to edit a component everything is the same? i.e. root or i am groot.  Meaning there would be no conflict.  

Lastly, let me make this argument for the adjusting of the toolbar.  because of the bots smaller incorporation into a website or especially a mobile site the scroll bar on the side is very unsightly. Now, for example, Visual studio code does the scroll bar awesome.  It has opacity and it goes and gets larger upon hovering over the area.  That is a very ideal case because it covers every scenario of usage and looks very nice all around. 

Also, chromium is pretty much the core browsing experience for about what 80 90% of the web?  I production, because of Angular and React we have had force our business into using chrome.  So, just web percentage alone I think it is a fair argument to include webkit changes for additional styling.
