### ISSUE TITLE
Replace relative time with absolute time

### ISSUE THREAD

**Issue by Keyan-Wang** [microsoft/BotFramework-WebChat#2217]
Hello, I want to know, how to show local time in timestamps.

![image](https://user-images.githubusercontent.com/34529222/61693915-fd533600-ad62-11e9-90d4-669fd4697d28.png)

For example, I want to show 09:11:24 to replace xx mins ago.

Any ideas?

**Comment by corinagum** [comment]
@Keyan-Wang, Thank you for posting this question! Unfortunately right now it is not possible to change what time is displayed. However, I think this is a good feature request. I will bring it up with our team. 

To anyone who might be looking for this feature, please feel free to add your +1 to this thread. Thank you.

**Comment by saurav2107** [comment]
It was one of my clients requirement, we managed to get the timestamp in webchat v3, but once we migrated to webchat v4, it was gone, I had very hard time convincing my client its not available in v4.

**Comment by cwhitten** [comment]
To maintain v3 parity we'll support this by providing a style option for format the time, initially with an `absolute` or `relative` enum
