### ISSUE TITLE
Ability to use Neural TTS in createCognitiveServicesSpeechServicesPonyfillFactory  

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/BotFramework-WebChat#2221]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to use the [Neural TTS](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices) to give a more human voice to my Bot

**Describe the suggestion or request in detail**

If I could tap into all the voice fonts from the "createCognitiveServicesSpeechServicesPonyfillFactory" function I can change the voice type easily.

**Comment by corinagum** [comment]
@Adityagrao, thanks for filing this. My understanding is that voice font is already available. Could you provide a little more detail on what you are looking for?

@compulim, your expertise here would be great! :D

**Comment by tdurnford** [comment]
I believe you can select the voice font with locale prop. https://github.com/microsoft/BotFramework-WebChat/issues/1529#issuecomment-486876115

**Comment by Adityagrao** [comment]
@corinagum this is my code, while I can add the locale, I can't change the TTS voice to en-US-JessaNeural 

and in this sample, if I put in the locale as "en-US-JessaNeural" and "Microsoft Server Speech Text to Speech Voice (en-US, JessaNeural)" the Speech Service stops working, I tried this with both westus and westus2 region
``` ts
window.WebChat.renderWebChat(
            {
                directLine: directLine,
                locale: "en-US",
                styleSet,
                webSpeechPonyfillFactory: await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({ subscriptionKey: 'Key', region: "westus2", textNormalization: 'lexical' }),
                store
            },
```

**Comment by corinagum** [comment]
After speaking with @compulim, it looks like this is a work item for the web-speech-cognitive-services project, issue linked: https://github.com/compulim/web-speech-cognitive-services/issues/32

Until that packages is bumped, Web Chat will be unable to select the particular voice font. We hope to have this fix in for the next release, due in October! :) Please head over to the issue linked for tracking. I will close this issue. Thanks!
