### ISSUE TITLE
ES5 library throws TypeError in IE11

### ISSUE THREAD

**Issue by jcoenen** [microsoft/BotFramework-WebChat#2222]
## Screenshots

![image](https://user-images.githubusercontent.com/101447/61795232-86608080-ade8-11e9-9d05-f18636e895f7.png)

![image](https://user-images.githubusercontent.com/101447/61795371-e6572700-ade8-11e9-8c82-19d735019fed.png)

## Version
![image](https://user-images.githubusercontent.com/101447/61795448-0a1a6d00-ade9-11e9-92c8-37f145210e87.png)

![image](https://user-images.githubusercontent.com/101447/61795477-17cff280-ade9-11e9-8394-a8513a5e8e06.png)

Using DirectLine

## Describe the bug
Our bot stopped working in IE11.   It works fine in Edge and Chrome, but IE11 we get the javascript errors above.   I get this using our bot code and your MockBot code.   Just started happening last week so not sure if its an issue with some recent change to the library (didnt' see any major checkins) or this version of IE11 which was also recently rolled out to our enterprise.

## To Reproduce

1. Go to your MockBot example https://microsoft.github.io/BotFramework-WebChat/01.b.getting-started-es5-bundle/   using IE version 11.557.17763.0
2. Type "help"
3. See javascript errors

## Expected behavior

Bot to respond with adaptive cards.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
This seems related to https://github.com/microsoft/BotFramework-WebChat/issues/2187

**Comment by corinagum** [comment]
Closing as dupe. This will be fixed in a patch coming out asap.
