### ISSUE TITLE
Ability to send "From Properties" via Web Chat

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/BotFramework-WebChat#2223]
## Feature Request
**Is your feature request related to a problem? Please describe.**

This feature has already been available in DirectlineJs, was expecting the same to work with Webchat 

I am trying this with the Angular Code [here](https://stackblitz.com/github/omarsourour/ng-webchat-example) 

Replace code with 

```ts

import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";

/**
 * Declares the WebChat property on the window object.
 */
declare global {
    interface Window {
        WebChat: any;
    }
}

window.WebChat = window.WebChat || {};

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.scss"]
})
export class AppComponent implements OnInit {
    @ViewChild("botWindow") botWindowElement: ElementRef;

    public ngOnInit(): void {
        const directLine = window.WebChat.createDirectLine({
            secret: "KEY", 
            webSocket: false 
        });

        window.WebChat.renderWebChat(
            {
                directLine: directLine,
                userID: "aditya",
                username: "Aditya Rao",
                from : { id: 'userid', name: 'username', xyz: "this is a test" }
            },
            this.botWindowElement.nativeElement
        );

        directLine
            .postActivity({
                from: { id: "aditya.rao", name: "Aditya Rao", xyz: "this is a test"},
                name: "requestWelcomeDialog",
                type: "event",
                value: "token"
            })
            .subscribe(
                id => console.log(`Posted activity, assigned ID ${id}`),
                error => console.log(`Error posting activity ${error}`)
            );
    }
}

```

Expectation is 
![image](https://user-images.githubusercontent.com/11465032/61878329-7216a380-af0e-11e9-935c-34e94d8c7660.png)

whereas all I get for Properties is   {{role: "user" }}

**Comment by tdurnford** [comment]
It looks like Web Chat creates the activity's `from` attribute in the [post activity saga](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/core/src/sagas/postActivitySaga.js), so you wouldn't be able to add additional properties with the current configuration. However, you can [piggyback data](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.a.backchannel-piggyback-on-outgoing-activities) on every outgoing activity through channel data. 

We could consider adding a `userProperties` prop to the Web Chat API that would map to properties in the `from` attribute.

**Comment by corinagum** [comment]
@tdurnford my understanding is that piggybacking is the established workaround. @compulim, thoughts?
