### ISSUE TITLE
Input.Date fields ignore preset values

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-WebChat#2225]
## Screenshots

Expected:

![image](https://user-images.githubusercontent.com/41968495/61909712-bb9fc800-aee7-11e9-8978-2a46b21bbbb8.png)

Actual:

![image](https://user-images.githubusercontent.com/41968495/61909693-b3478d00-aee7-11e9-9404-bed9757c2b5d.png)

## Version

```html
<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
```

## Describe the bug

`Input.Date` fields in Adaptive Cards have a `value` property that is supposed to specify the input's initial value. While the property works in Microsoft Teams, it seems to be ignored in Web Chat.

## To Reproduce

```json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "Input.Date",
      "id": "id-date12",
      "value": "12/13/14"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}
```

## Additional Context

The `value` properties of other input fields seem to work correctly.

[Bug]

**Comment by corinagum** [comment]
![image](https://user-images.githubusercontent.com/14900841/61910925-d3c51680-aeea-11e9-9d5e-832c5f7ca8bd.png)
It looks like it's not respected on Adaptive Cards either.

I think this is related to https://github.com/microsoft/BotFramework-WebChat/issues/2192

I would file this with Adaptive Cards.

**Comment by v-kydela** [comment]
After some further investigation, I have discovered that the `value` property does work if you provide the date in the format `yyyy-mm-dd`. It does not work in the format `mm/dd/yy`, though that seems to be a Web Chat specific problem.

I have also discovered another bug while testing this. The `placeholder` property does not work in `Input.Date` though it does work in `Input.Text`. The `placeholder` property works for both input types in Microsoft Teams.

**Comment by compulim** [comment]
This is HTML issue.

1. If the `value` attribute is not in the format of `yyyy-mm-dd`, Chrome/Edge will not be able to parse it. Not Adaptive Cards or Web Chat issue.
2. According to [HTML Living Standard for date input](https://html.spec.whatwg.org/multipage/input.html#date-state-(type%3Ddate)), `placeholder` attribute is not supported. Excerpt below:

![image](https://user-images.githubusercontent.com/1622400/61914791-99fa0d00-aef6-11e9-9019-81cad8c463c3.png)

**Comment by tdurnford** [comment]
Looks like @corinagum opened an issue for the date input placeholder issue in the Adaptive Cards repo already https://github.com/microsoft/AdaptiveCards/issues/2255
