### ISSUE TITLE
Setting empty string to language will throw an exception

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2231]
When using playground, the `language` prop passed to Web Chat is empty string instead of `undefined`, which caused Web Chat throw an exception.

**Comment by cwhitten** [comment]
Today WebChat will blow up if `language = ""`, it should not blow up/

**Comment by compulim** [comment]
@corinagum did we fixed this in #2226?

https://github.com/microsoft/BotFramework-WebChat/commit/f5b8db54380cf0059bc0fc55fc580a2aebba0cee#diff-d77ef25d8b6a6b71d83356cce84eb046R148

**Comment by corinagum** [comment]
@compulim haha I thought you said that was a partial fix but I'm not sure what else needs to be done. One of us should test this on the Playground and report back
