### ISSUE TITLE
New Angular 7, 8, 9 Library for the bot framework It would be nice to have the webchat CDN available as a local library

### ISSUE THREAD

**Issue by xtianus79** [microsoft/BotFramework-WebChat#2244]
I am requesting the CDN be a local library that could be installed via Angular, web, react, or any other javascript implementation that needs it -- like jquery.

First, I wanted to provide link to the Angular 6, 7, 8 library plugin.  
Would appreciate feedback

[GitHub](https://github.com/xtianus79/ngx-microsoft-bot-framework)
[Demo](https://xtianus79.github.io/ngx-microsoft-bot-framework/)
[npm](https://www.npmjs.com/package/ngx-microsoft-bot-framework)

## Feature Request

I am requesting that the webchat CDN be a local library.  This is very important for enterprise applications that may require something like a Nexus repository that requires all dependencies be locally installed to the application. 

Specifically, to this library I wouldn't have to make the end user using the library call the cdn in their index.html

Also, the versioning can be better controlled in the app environment.  As explained previously, an enterprise application may have frozen dependencies so if you make someone use a CDN you are asking for the latest webchat code that may break an application. 

Lastly, as the npm webchat package is specifically for React, which is great and all if you're making a React application, it is not agnostic to other javascript environments.  

I can do this, if it is not something you all want to do but I feel this is something that should be handled on your end and maintained through versioning.  

Thanks

**Comment by compulim** [comment]
You can download the JS file from https://cdn.botframework.com/botframework-webchat/4.5.0/webchat.js and including it in your enterprise applications.

BTW, our CDN retention policy follows NPM standard. Once it is on our CDN, we will never change it. Similar to NPM, we might unpublish it due to security issues.

If you are worried about the integrity of the file, you should consider including subresource integrity in your `<script>` tag.

**Comment by xtianus79** [comment]
@compulim oH!!! so you guys do have versions of the javascript webchat library.  Is there a repo or something to watch the versioning?  I never saw this in any documentation.  Ok so this is good. I will package this and publish this to npm.

**Comment by compulim** [comment]
If you look at our NPM version page here, https://www.npmjs.com/package/botframework-webchat?activeTab=versions, you can copy the version number and replace it in the URL of https://cdn.botframework.com/botframework-webchat/x.y.z/webchat.js.

**Comment by compulim** [comment]
We have just release 4.5.1 and have included the link to the bundle on CDN, plus the SRI hash. Hope it help.

https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.5.1
