### ISSUE TITLE
Remove download link from user uploaded attachments

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2248]
Attachments sent from the user would not have any working links to download the content again.

Also note MP3 files may get rendered as `<audio>`.

**Comment by narik1989** [comment]
Hi,

I am using the above mentioned version (4.5.3). The download link is removed for all the attachments except .txt file extensions. Am i missing something in the config? 

![attachment](https://user-images.githubusercontent.com/33231617/67264749-9eb86800-f4c9-11e9-8146-5e78fddbc840.png)


Thanks
Kiran
