### ISSUE TITLE
Height of textbox and button in Adaptive Card is incorrect in IE11

### ISSUE THREAD

**Issue by xinfli** [microsoft/BotFramework-WebChat#2263]
The height of textbox and button in Adaptive Card is incorrect in IE11.

## Screenshots

![WebChat_AdaptiveCard_Height_Problem_IE11](https://user-images.githubusercontent.com/1798198/62360483-2751e880-b519-11e9-861f-36d81d58cc63.png)

## Version

Found in v4.4.2, but still exists after updated to newest version 4.5.1

## Additional context

Found a workaround from #1836, it can be fixed with "`$(".ac-pushButton").css("flex-basis", "");`"

**Comment by compulim** [comment]
I think this is Adaptive Card problem.

If you use IE11 and browse to https://www.adaptivecards.io/visualizer/index.html, you will see the button are squeezed as well.

![image](https://user-images.githubusercontent.com/1622400/62389207-1357b800-b514-11e9-96b4-bc6fbed6a55a.png)

I have submitted a bug to Adaptive Card team, https://github.com/microsoft/AdaptiveCards/issues/3301. Please track the issue over there.

Once they have fixed it, we will bump Adaptive Card in Web Chat.

**Comment by daveta** [comment]
Hi @compulim, FYI: it seems like the dependent issue is now closed.

**Comment by tsuwandy** [comment]
@compulim, could you bump Adaptive Card in Web Chat and close this issue after?  See previous issue, the bug on AdaptiveCards side was closed.

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/65466490-d58c5700-de13-11e9-9ab0-e70b0fc19b2c.png)

Their production build is still 1.2.0.

**Comment by stevengum** [comment]
This has been fixed! https://github.com/microsoft/AdaptiveCards/issues/3301#issuecomment-535278549:

![Cool-release-bot](https://user-images.githubusercontent.com/14935595/66245760-b370bf80-e6c4-11e9-8570-b3943dc8767f.png)

**Comment by tonyanziano** [comment]
We will be bumping `AdaptiveCards` in our R7 release. @compulim

**Comment by compulim** [comment]
We bumped to `adaptivecards@1.2.3` in #2532, will verify in IE11.

**Comment by corinagum** [comment]
Verification currently blocked by #2559

**Comment by corinagum** [comment]
Confirmed this as fixed :)

**Comment by Lancelot301** [comment]
Hi , I am Trying to create an Adaptive card with two input fields one is a date and another one is choiceSet, It is working fine in designer 
like this:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/114400426/192264555-50bb1792-2ccd-4d44-84c8-1a7fcaa42961.png">

but in webchat there is a mismatch in height of both the element. Can we explicitly set the height of input element? If yes then how?

Any suggestions or reference would be very helpful

Thanks in Advance!
