### ISSUE TITLE
Adaptive Cards' Action Set does not work on Web Chat

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2268]
## Version
4.5.1

## Describe the bug

Adaptive Cards with action sets are not rendered in Web Chat
## To Reproduce

```
{"schema":" http://adaptivecards.io/schemas/adaptive-card.json","version":"1.2","type":"AdaptiveCard","speak":null,"body":[{"type":"TextBlock","text":"Area Zenith","weight":"Bolder","separator":false,"columns":null,"spacing":null},{"type":"ColumnSet","text":null,"weight":null,"separator":true,"columns":[{"type":"Column","width":1,"items":[{"type":"TextBlock","text":"Tiepido di gamberi e calamari","altText":null,"url":null,"size":null,"id":null,"horizontalAlignment":null,"isSubtle":false,"actions":null,"weight":null},{"type":"Image","text":null,"altText":null,"url":"https://areazenith01.scm.azurewebsites.net/dev/api/files/wwwroot/wwwroot/images/Items/ItemDefault.jpeg","size":"Medium","id":null,"horizontalAlignment":null,"isSubtle":false,"actions":null,"weight":null}],"verticalContentAlignment":null},{"type":"Column","width":1,"items":[{"type":"TextBlock","text":"₹ 14.00","altText":null,"url":null,"size":null,"id":null,"horizontalAlignment":"right","isSubtle":true,"actions":null,"weight":null},{"type":"ActionSet","text":null,"altText":null,"url":null,"size":null,"id":null,"horizontalAlignment":null,"isSubtle":false,"actions":[{"type":"Action.Submit","title":"Delete","data":{"action":"DELETE_2449769"}}],"weight":null}],"verticalContentAlignment":"Bottom"}],"spacing":null},{"type":"ColumnSet","text":null,"weight":null,"separator":false,"columns":[{"type":"Column","width":1,"items":[{"type":"TextBlock","text":"Total","altText":null,"url":null,"size":"Medium","id":null,"horizontalAlignment":null,"isSubtle":true,"actions":null,"weight":null}],"verticalContentAlignment":null},{"type":"Column","width":1,"items":[{"type":"TextBlock","text":"₹ 14.00","altText":null,"url":null,"size":"Medium","id":null,"horizontalAlignment":"Right","isSubtle":false,"actions":null,"weight":"Bolder"}],"verticalContentAlignment":null}],"spacing":"Medium"}]}
```
## Expected behavior

![image](https://user-images.githubusercontent.com/14900841/62482844-1dbfbf00-b76b-11e9-8000-93a7ec32cde5.png)

## Additional context

[Bug]

**Comment by tdurnford** [comment]
This seems to be related to https://github.com/microsoft/BotFramework-Services/issues/87 and appears to work correctly in Web Chat with the [workaround](https://github.com/microsoft/BotFramework-Services/issues/87#issuecomment-500662897) mentioned in the thread. This should be resolved when the Direct Line Connector Service's Adaptive Cards dependency is updated to v1.2.

![image](https://user-images.githubusercontent.com/17039790/62483924-be16e300-b76d-11e9-8964-b1a1aa10b651.png)

**Comment by corinagum** [comment]
Closing this issue since it's external to Web Chat. Please use the above link for tracking. :)

**Comment by Bhushangholap** [comment]
Workaround mentioned in above link is not working for below json for ActionSet :
Json :
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "I'm trained to help you:",
            "wrap": true,
            "weight": "Bolder"
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Submit",
                            "title": "Retrieve a CMS number for an entity",
                            "data": "Retrieve a CMS number for an entity",
                            "wrap": true            
                        },
                        {
                            "type": "Action.Submit",
                            "title": "Update data on a Legal Entity",
                            "value":"Update data on a Legal Entity",
                            "data":"Update data on a Legal Entity",
                            "wrap": true
                        },
                         {
                            "type": "Action.Submit",
                            "title": "Report workflow related issues",
                            "value":"Report workflow related issues",
                            "data":"Report workflow related issues",
                            "wrap": true
                        },
                        {
                            "type": "Action.Submit",
                            "title": "Open a ticket for all other legal entity Business queries",
                            "value":"Open a ticket for all other legal entity Business queries",
                            "data":"Open a ticket for all other legal entity Business queries",
                            "wrap": true
                        },
                        {
                            "type": "Action.Submit",
                            "title": "FAQ's related to LEM/Englobe",
                            "value":"FAQ's related to LEM/Englobe",
                            "data":"FAQ's related to LEM/Englobe",
                            "wrap": true
                        }
                        
                    ]
                }
            ]
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "  "
                    
                },
                {
                    "type": "TextBlock",
                    "text": "Type Cancel to exit LEM help and talk about something else."
                    
                }
            ]
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Cancel",
                    "data": "Cancel"
                }
            ]
        }
    ]
}
==================
I have applied workaround however it gives me weird output :
![image](https://user-images.githubusercontent.com/24426300/62774556-aff4f980-bac2-11e9-920f-607f8ff98b1b.png)

**Comment by tdurnford** [comment]
@Bhushangholap  It seems to work fine with Adaptive Cards Action Sets.

**Screenshot**
![image](https://user-images.githubusercontent.com/17039790/62786885-5f58ae80-ba78-11e9-8c51-eb83e379ee00.png)

**Bot Framework SDK v4 (Node)**
```javascript
const card = CardFactory.adaptiveCard({
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
  {
  "type": "TextBlock",
  "text": "I'm trained to help you:",
  "wrap": true,
  "weight": "Bolder"
  },
  {
  "type": "Container",
  "items": [
  {
  "type": "ActionSet",
  "actions": [
  {
  "type": "Action.Submit",
  "title": "Retrieve a CMS number for an entity",
  "data": "Retrieve a CMS number for an entity",
  "wrap": true
  },
  {
  "type": "Action.Submit",
  "title": "Update data on a Legal Entity",
  "value":"Update data on a Legal Entity",
  "data":"Update data on a Legal Entity",
  "wrap": true
  },
  {
  "type": "Action.Submit",
  "title": "Report workflow related issues",
  "value":"Report workflow related issues",
  "data":"Report workflow related issues",
  "wrap": true
  },
  {
  "type": "Action.Submit",
  "title": "Open a ticket for all other legal entity Business queries",
  "value":"Open a ticket for all other legal entity Business queries",
  "data":"Open a ticket for all other legal entity Business queries",
  "wrap": true
  },
  {
  "type": "Action.Submit",
  "title": "FAQ's related to LEM/Englobe",
  "value":"FAQ's related to LEM/Englobe",
  "data":"FAQ's related to LEM/Englobe",
  "wrap": true
  }
  
                  ]
              }
          ]
      },
      {
          "type": "Container",
          "items": [
              {
                  "type": "TextBlock",
                  "text": "  "
                  
              },
              {
                  "type": "TextBlock",
                  "text": "Type Cancel to exit LEM help and talk about something else."
                  
              }
          ]
      },
      {
          "type": "ActionSet",
          "actions": [
              {
                  "type": "Action.Submit",
                  "title": "Cancel",
                  "data": "Cancel"
              }
          ]
      }
  ]
  });
card.contentType = 'application/vnd.microsoft.card.custom';
await context.sendActivity({ attachments: [card] });


```

**Comment by Bhushangholap** [comment]
this is directline client :
<!DOCTYPE html>
<html>
   <body>
      <div id="webchat" role="main">
      <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
      <script>
	   const attachmentMiddleware = () => next => card => {
  if (card.attachment.contentType === 'application/vnd.microsoft.card.custom'){
    card.attachment.contentType = 'application/vnd.microsoft.card.adaptive'
  }
  return next(card)
};

         window.WebChat.renderWebChat(
            {
               directLine: window.WebChat.createDirectLine({
                  token: 'SECRET'
               }),
			    attachmentMiddleware, 
               userID: 'YOUR_USER_ID',
               username: 'Web Chat User',
               locale: 'en-US',
               botAvatarInitials: 'WC',
               userAvatarInitials: 'WW'
			   
			},
			document.getElementById('webchat')
         );
      </script>
	  </div>
   </body>
</html>

**Comment by arman-g** [comment]
It seems the issue still exist in v4.10.1
