### ISSUE TITLE
Webchat cdn issue?

### ISSUE THREAD

**Issue by Joombalaya** [microsoft/BotFramework-WebChat#2271]
## Screenshots

![image](https://user-images.githubusercontent.com/8886779/62496914-02bb7200-b7a0-11e9-9f0a-5ce24ceb5fc1.png)

## Version

https://cdn.botframework.com/botframework-webchat/latest/webchat.js

## Describe the bug

crashes after I send my first response to the server. Server is successfully getting message and sending back. Only using the example code to run. Was running fine but started crashing at around 4PM CST

## To Reproduce

1. Go to https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.a.getting-started-full-bundle
2. Copy repo
3. open html

## Expected behavior

should load the the chat on start. Any message sent will crash the app.

## Additional context

[Bug]

**Comment by compulim** [comment]
@Joombalaya we copied the HTML file and hosted locally on our box. Nothing seems wrong, we can chat with the bot.

Could you give us more details on this?

**Comment by Joombalaya** [comment]
@compulim I went ahead and recloned the sample. The only thing I do differently than the sample is use https://directline.botframework.com/v3/directline/tokens/generate and put in my secret from azure channels directline page. I am getting a token back successfully and the page initially loads fine, but crashes after I send one message through.

**Comment by corinagum** [comment]
This sounds like your app is crashing and you need to implement those fixes. Since the logs are not producing errors, I believe this is related to your app and not to Web Chat or your bot. `internalValidateProperties` is not within the scope of Web Chat so we will not be able to help you.

**Comment by tdurnford** [comment]
@Joombalaya 

Here is an example of how you should generate your Direct Line token. Note, this is only for simplicity, and you should never expose your secret to the client.

```javascript
(async function () {
  // Note, for the simplicity of this example, we are generating the Direct Line token on client side;
  // however, this is not a recommended practice and you should create and manage your tokens from the server. 
  // You should never put the Direct Line secret in the browser or client app.
  // https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication
  const secret = '<DIRECT_LINE_SECRET> | <WEB_CHAT_SECRET>';
  const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', { 
    body: JSON.stringify({ user: { id: 'dl_user_id', name: 'username' }}),
    headers: {
      Authorization: `Bearer ${secret}`,
      'Content-type': 'application/json'
    },
    method: 'POST',
  });
  const { token } = await res.json();

  window.WebChat.renderWebChat({
    directLine: window.WebChat.createDirectLine({ token })
  }, document.getElementById('webchat'));

  document.querySelector('#webchat > *').focus();
})().catch(err => console.error(err));
```

**Comment by Joombalaya** [comment]
> This sounds like your app is crashing and you need to implement those fixes. Since the logs are not producing errors, I believe this is related to your app and not to Web Chat or your bot. `internalValidateProperties` is not within the scope of Web Chat so we will not be able to help you.

Look at the console error log. That is happening in YOUR CDN. I only mentioned that MY SERVER logs don't show errors. YOUR CDN shows errors. That was to illustrate that MY SERVER is not having issues.

**Comment by compulim** [comment]
Did you add any code to the page? In the console log, we are seeing something weird.

![image](https://user-images.githubusercontent.com/1622400/62567338-d5be9c00-b83f-11e9-982d-6e40d6bcafee.png)

**Comment by Joombalaya** [comment]
That's is a line that says console.log("FOCUSED"); was put in to show when an element gained focus to trip a conversation, but I have tried the same things with ONLY the sample code with nothing else added. I have also tried the example solution that was provided and got the same errors.

**Comment by compulim** [comment]
Trying our best to help.

`internalValidateProperties` is something from Adaptive Cards. Is your message triggering any response from Adaptive Cards? AFAIK, [this line is failing](https://github.com/microsoft/AdaptiveCards/blob/705e1a5a1e5e29a4aad4c14feb1b3144de91e775/source/nodejs/adaptivecards/src/card-elements.ts#L2251).

If your bot respond with an Adaptive Cards, could you attach it here?

**Comment by Joombalaya** [comment]
return CardFactory.adaptiveCard({
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.0",
                "body": [ 
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "items":[
                                    {
                                        "type": "TextBlock",
                                        "text": "Owner Number"
                                    }
                                ]
                            },
                            {
                                "type": "Column",
                                "items":[
                                    {
                                        "type": "TextBlock",
                                        "text": ":"
                                    }
                                ]
                            },
                            {
                                "type": "Column",
                                "items":[
                                    {
                                        "type": "TextBlock",
                                        "text": Values.input1
                                    }
                                ]
                            }
                        ]
                    }
                ]        
        })

this is the card it returns. 
looks like the second card in this photo:
![image](https://user-images.githubusercontent.com/8886779/62568527-052ad400-b853-11e9-9ad0-1d77abe3fb0b.png)

**Comment by tdurnford** [comment]
Can you please try your bot with this Adaptive Card?

```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Please enter the following information"
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "Owner Number:",
                            "weight": "Bolder",
                            "height": "stretch"
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "Input.Text",
                            "id": "text_input",
                            "title": "New Input.Toggle",
                            "placeholder": "Enter Comment"
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/17039790/62572846-8715ff80-b849-11e9-9637-51ad29d3bb05.png)

**Comment by Joombalaya** [comment]
@tdurnford Same behavior. Works in Azure "Test in Web Chat" sn:
![image](https://user-images.githubusercontent.com/8886779/62573591-ff85bc00-b85b-11e9-8cff-0f100ab77247.png)

Still loads initially in browser and then crashes after first thing is passed back.

**Comment by Joombalaya** [comment]
quick correction. The card I was sending was actually. 
{
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.0",
            "body": [ 
                {
                    "type":"TextBlock",
                    "textFormat":"xml",
                    "text":"Please enter the following information",
                },
                {
                    "type":"TextBlock",
                    "text":" "
                },
                {
                    "type":"TextBlock",
                    "text":" "
                },
                {
                "type": "ColumnSet",
                "columns": [
                    {
                        "type": "Column",
                        "items":[
                            {
                                "type":"TextBlock",
                                "text":"Owner Number"
                            }
                        ],
                    },
                    {
                        "type": "Column",
                        "items":[
                            {
                                "type":"TextBlock",
                                "text":":"
                            }
                        ],
                    },
                    {
                        "type": "Column",
                        "items":[
                            {
                                "type":"Input.Text",
                                "id": "input1",
                                "width": 10,
                                "placeholder": " enter comment",
                                "maxLength": 10
                            }
                        ]
                    },
                    {
                        "type":"TextBlock",
                        "text":" "
                    },
                ]                   
            }],
            "actions":[
                {
                    "type":"Action.Submit",
                    "title": "Submit"
                }
            ]
        }
@tdurnford went ahead and replaced this with your snippet and it does work in browser. As far as I can tell, the only difference is textFormat: xml and the schema url is down lower. Would these be causes for errors?

**Comment by tdurnford** [comment]
I don't believe Text Blocks in Adaptive Cards have a text format field, so that would like cause the renderer to fail. Take a look at the schema documentation. https://adaptivecards.io/explorer/TextBlock.html

**Comment by Joombalaya** [comment]
@tdurnford I think I conflated this doc https://docs.microsoft.com/en-us/javascript/api/botframework-schema/activity?view=botbuilder-ts-latest with valid fields for cards.  So removing that makes sense. So I made the changes to my original card so that it wouldn't have that field plus I moved the schema line and removed a width field in a Input.Text field cause the docs don't show that it has that field. I ended up with this: 

{           
            "type": "AdaptiveCard",
            "version": "1.0",
            "body": [ 
                {
                    "type":"TextBlock",                    
                    "text":"Please enter the following information",
                },
                {
                    "type":"TextBlock",
                    "text":" "
                },
                {
                    "type":"TextBlock",
                    "text":" "
                },
                {
                "type": "ColumnSet",
                "columns": [
                    {
                        "type": "Column",
                        "items":[
                            {
                                "type":"TextBlock",
                                "text":"Owner Number"
                            }
                        ],
                    },
                    {
                        "type": "Column",
                        "items":[
                            {
                                "type":"TextBlock",
                                "text":":"
                            }
                        ],
                    },
                    {
                        "type": "Column",
                        "items":[
                            {
                                "type":"Input.Text",
                                "id": "input1",                            
                                "placeholder": " enter comment",
                                "maxLength": 10
                            }
                        ]
                    },
                    {
                        "type":"TextBlock",
                        "text":" "
                    },
                ]                   
            }],
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "actions":[
                {
                    "type":"Action.Submit",
                    "title": "Submit"
                }
            ]
        }

and that still crashes. Is there anything with adaptive cards I am missing here or doing incorrectly here?

**Comment by tdurnford** [comment]
@Joombalaya I can't see anything wrong with it on the surface, but I'm not an Adaptive Cards expert. I would recommend you build your cards with the [Adaptive Cards Designer](https://adaptivecards.io/designer/) so you know they will render correctly in Web Chat.

**Comment by compulim** [comment]
@Joombalaya do you think it is caused by the extra commas in some of the lines?

For example, 3 lines up of the `$schema`, there is an extra comma. And there are multiple in the JSON. Could you run it thru a JSON validator and see?
