### ISSUE TITLE
Cognitive Services: default voice changed

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2282]
## Version

`master`

## Describe the bug

The default voice used in Cognitive Services changed. This is probably because we now sort the voice list, and the other voice come up on the top.

## To Reproduce

1. Go to https://webchat-playground.azurewebites.net/
2. Click on microphone, say something

## Expected behavior

Web Chat should speak back bot's response with a female voice. Instead, it is speaking out using a male voice.

## Additional context

There is no default voice for Cognitive Services. Voice is required to specify on every SSML.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup#choose-a-voice-for-text-to-speech

[Bug]

**Comment by corinagum** [comment]
I think we can go ahead and close this issue. No one has posted bugs asking about the problem and there hasn't been any customer activity on this issue. Since there is a way to change the default voice, I don't think a 'fix' is necessary.

**Comment by alokraj68** [comment]
Hi! same issue here, Voice changed to a male voice in 4.6 from the female voice it had before.

**Comment by alokraj68** [comment]
For time being we can use the following workaround to set the old default voice.

```
    var selectVoice = function selectVoice(voices, activity) {
        return voices.find(({ name }) => /ZiraRUS/iu.test(name));
    };

  var webChatOptions = {
        directLine: directLine,
       webSpeechPonyfillFactory,
      selectVoice: selectVoice,
       };
```

Let this help people who have this issue right now.

**Comment by corinagum** [comment]
Yes. For those looking for more detail, please see our sample https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.g.select-voice
