### ISSUE TITLE
Select voice based on gender or content of activity

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2292]
## Feature Request

Ability select voice based on gender or content of activity, and also by providing custom voice model name.

This select voice predicate today is based on activity locale, UI language, and browser language only. It currently lives in [`component/src/Activity/Speak.js`](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/component/src/Activity/Speak.js).

```js
selectVoice: voices => {
  voices = [].slice.call(voices);

  return (
    voices.find(({ lang }) => lang === activity.locale) ||
    voices.find(({ lang }) => lang === language) ||
    voices.find(({ lang }) => lang === window.navigator.language) ||
    voices.find(({ lang }) => lang === 'en-US') ||
    voices[0]
  );
}
```

[Enhancement]

**Comment by iMicknl** [comment]
@compulim will this also include support for [Custom Voice](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-voice-create-voice) or is it already possible to choose a custom voice model.

**Comment by compulim** [comment]
Oh right, thanks for reminding me.

Custom Voice support is recently added (last week) to the adapter, but Web Chat did not provide a way to use it yet. This work should also allows developers to select voice by simply providing the model name.

BTW, you can [try out our Web Speech API adapter](https://compulim.github.io/web-speech-cognitive-services) for Custom Voice font support. You would need to specify both "Deployment ID" and "Voice URI" (a.k.a. custom voice model name). 😉
