### ISSUE TITLE
Slow Response time on long running tab sessions (likely a websocket reconnection problem)

### ISSUE THREAD

**Issue by kevmojay** [microsoft/BotFramework-WebChat#2294]
## Version

Forked from 1.45.0

## Describe the bug

We are finding that occasionally the bot takes a very long time to respond (somewhere around a minute.

We did some investigative work and we have a running theory.

The most reliable way for us to reproduce it is to open a chrome tab with the webchat, have your computer go to sleep for a few minutes (about 5) re-open it and resume the chat.

Our investigations points to the problem having to do with websocket connections. We feel like when the websocket is lost, it takes about a minute before it reconnects. The gotcha is that we have reports of users experiencing this while using the bot. But this report also had a very long running tab.

Perhaps there is some logic around destroying the websocket after some time. I have a Chrome performance recording but for now i will include some of the screenshots from that recording.

<img width="1680" alt="Screen Shot 2019-07-30 at 5 38 21 PM" src="https://user-images.githubusercontent.com/11466536/62796394-00059900-ba8e-11e9-8f50-19de087ab009.png">
<img width="1680" alt="Screen Shot 2019-07-30 at 5 33 47 PM" src="https://user-images.githubusercontent.com/11466536/62796397-0267f300-ba8e-11e9-8660-1a8965bceb0a.png">

The first screenshot is to show that a function call is made to destroy the websocket and later it reconnects.
The second is to show the timeline it took before making that call.

I am curious if I can get a description of the websocket logic. Is there a timeframe that it will close?

## To Reproduce

(Only tried on MacOS Chrome both up to date)
1. Go to webchat.mazda.carlabs.com
2. send a few random messages
3. have your computer go to sleep while the tab is still open for about 5 minutes
4. message the bot again and it might take a minute or so to respond.

## Expected behavior

Webchat should reconnect to the websocket as quickly as possible.

[Bug]

**Comment by compulim** [comment]
Love your technical deepness and curiosity, and excellent explanation. So I am wearing my technical hat to give you as much details as I could.

- Web Socket doesn't work across sleeps I believe, including switching apps on iPhone, they will get killed
   - Today, Web Socket doesn't have a good connection detection algorithm
- [DirectLineJS](https://github.com/microsoft/BotFramework-DirectLineJS) is responsible for the connectivity, but currently, the resume/end conversation is quite broken in Web Socket story, we are planning to work on it during this sprint (4.6, releasing mid-to-late October)
- Server-Sent Event is a better protocol for dealing with intermittent connectivity and better power consumption as well, despite it is half-duplex (we use Web Socket in half-duplex fashion today)
   - We don't support SSE on our servers yet, no plan either 😥
   - We tried something experimental in a hackathon project, building a WS -> SSE bridge, and it looks quite promising to me
- After DirectLineJS rework is done, you don't need to bump Web Chat. You can use newer version of DirectLineJS in older version of Web Chat, including Web Chat v3 (`0.*.*`)

Will talk to the team. This bug will serve as a vote to our Direct Line rework. 👍

**Comment by kevmojay** [comment]
@compulim Thank you for the response!

**Comment by corinagum** [comment]
Adding blocked tag since this would propagate from a DLJS change first.

**Comment by compulim** [comment]
This work hasn't been approved. Please keep an eyes out for update from @Kaiqb.

**Comment by Kaiqb** [comment]
I am not able to repro the behavior using the website (webchat.mazda.carlabs.com) that was mentioned in the issue. I am not sure whether the site works or not. For now, I am going to close this issue but if this is still causing problems, feel free to re-open.
