### ISSUE TITLE
Embed: some browsers/polyfills broke URLSearchParams.toString

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2297]
> Copied from ticket 9537.

## Screenshots

In embed, when we call something similar to `new URLSearchParams({ abc: 123 }).toString()`, it returns `"object Object"` instead of `"abc=123"`.

## Version

4.3.0 (latest production of embed as of now)

## Describe the bug

When "Test in Web Chat" blade is opened, the URL it is pointing to become "/config?%5Bobject+Object%5D=".

It seems related to this part of code, https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/src/urlBuilder.js#L8.

## To Reproduce

1. Open "Test in Web Chat" from Azure Portal

## Expected behavior

Web Chat show correctly. But instead, it shows "Trouble connecting Contact the site administrator".

## Additional context

Asking customer of specific browsers they are using. Seems browser-related issue.

[Bug]

**Comment by corinagum** [comment]
Closing issue as resolved on IcM
