### ISSUE TITLE
sending postActivity type "event" from webchat V4

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2302]
i want to send a post activity to get a welcome message/ other message using activity type as "Event" on webchat v4. please suggest me the syntax with example to do this.

**Comment by compulim** [comment]
**Please do not post questions on GitHub. And please fill out our template.**

This sample should might your need, https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.c.programmatic-post-activity.

**Comment by alokraj68** [comment]
This method is showing the message to the user. in V3 it never did. Is that a bug?

Is there a way to make it like how it was in v3
