### ISSUE TITLE
No option to change font size in defaultStyleOptions.js

### ISSUE THREAD

**Issue by Cam-ster** [microsoft/BotFramework-WebChat#2306]
I am trying to change the font size of my chat's messages (both from the user and the bot) but there does not seem to be any option to do so in the styleOptions.

I have seen a way to change the font size using the window.WebChat.createStyleSet method. 

However, my bot will be used on IE11 as well of modern browsers, and this way is not supported on IE11.

**Comment by Cam-ster** [comment]
I was able to find a work around for this:

.bubble {
    font-size: 24px !important;
}

**Comment by corinagum** [comment]
Hi @Cam-ster, you can set your font-size in either the body of your HTML or in the root container of Web Chat. The intent here is that Web Chat will inherit whatever font size is set by the parent and calculate the small font from there. However, `connectivityStatus`, perhaps mistakenly, does have a setable font  in `defaultStyleOptions` which might lead to further confusion. 

@compulim, @cwhitten, should we update `defaultStyleOptions` to calculate the connectivity status font based off the inherited font? I think adding a comment inside `defaultStyleOptions` explaining that the font size is inherited is also warranted here.

**Comment by hcyang** [comment]
Hi @stevkan, since you were assigned to this issue, any updates? Thanks.

**Comment by tdurnford** [comment]
@hcyang 

The `connectivityTextSize` should be updated to 75% in PR #2384

https://github.com/microsoft/BotFramework-WebChat/pull/2384/files#diff-59602d7073278fd31a720eee0c05c565R133

**Comment by alokraj68** [comment]
How about changing the font size of the send text box? In V3 it was 14 px in V4 it is 13 px. Should we use manual CSS override for the time being?

**Comment by corinagum** [comment]
Yep, font size can be assigned to the parent container of Web Chat, and the entire app will inherit that and calculate the smaller font size based on that.
