### ISSUE TITLE
webchat.botframework.com service not working as expected

### ISSUE THREAD

**Issue by andhdo** [microsoft/BotFramework-WebChat#2309]
I'm trying to follow the steps to publish the bot using webchat, and accepting conditions to publish; 

The component has an authentication procedure to expose the component. 
Then i'm planning to embed idinside an iframe as azure porta suggest, and using the code that it generates inside the portal.

After the configuration, the result is not the expected and instead it shows the mime type of a card (see the images below).

## Screenshots

![image](https://user-images.githubusercontent.com/2402081/62961037-8225f280-bdeb-11e9-8d6c-d704364cdf3d.png)

![image](https://user-images.githubusercontent.com/2402081/62960857-1c396b00-bdeb-11e9-9b09-aea72a460493.png)

## Version
i'm using the embedding webchat as iframe option that portal.azure.com suggest:

https://webchat.botframework.com/embed/

## Describe the bug
oauth card not working for this public site. 

## Expected behavior
that redirects to authentication  site

## Additional context

[Bug]

**Comment by compulim** [comment]
Currently, OAuth card is not working in webchat.botframework.com. You will need to use the latest version of Web Chat. We are working to bump the version of Web Chat in IFRAME.

Please refer to [this section](https://github.com/microsoft/BotFramework-WebChat#how-to-use) to adding Web Chat to your page directly.
