### ISSUE TITLE
webchat V4 browser compatibilty

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2314]
i have downloaded the latest webchat V4 using the link  :- "https://cdn.botframework.com/botframework-webchat/latest/webchat.js". i want to use this webchat on IE , edge and safari also but i am not getting the webchat on all these browsers. can you please tell me the browser compatibility and how to achieve it.
![Screenshot (328)](https://user-images.githubusercontent.com/34365788/62998711-04fd8a80-be8a-11e9-8768-266b6736ec14.png)

**Comment by compulim** [comment]
This question is answered in [this section of `README.md`](https://github.com/microsoft/botframework-webchat#browser-compatibility).

All modern browsers and IE11 are supported. We use "minus 2 versions" rule for modern browser. For example, today's Chrome is 76, we will support 74+. Same for other modern browsers.

For IE11, you will need to use a different bundle, which include special features required to make Web Chat works with IE11. Please refer to our `README.md` on IE11.
