### ISSUE TITLE
Sample: Render location via Google Maps

### ISSUE THREAD

**Issue by danmarshall** [microsoft/BotFramework-WebChat#232]
This is found in the [entities](https://github.com/Microsoft/BotFramework-WebChat/blob/ea94dfccf97018e240494857cbacfdae4b7b7021/src/BotConnection.ts#L149)

example data:
```
    {
      "type": "message",
      "id": "AK1DnrDyAeo|000000000000000019",
      "timestamp": "2016-12-13T21:43:02.4423226Z",
      "channelId": "webchat",
      "from": {
        "id": "TestBotV3",
        "name": "_TestBotV3 "
      },
      "conversation": {
        "id": "AK1DnrDyAeo"
      },
      "text": "Here it is a location: ",
      "attachments": [],
      "entities": [
        {
          "type": "Place",
          "geo": {
            "elevation": 113.531,
            "latitude": 47.64451613,
            "longitude": -122.13681221,
            "type": "GeoCoordinates",
            "name": "Microsoft - The Commons"
          },
          "name": "Microsoft - The Commons"
        }
      ],
      "replyToId": "AK1DnrDyAeo|000000000000000018"
    }
```

(Below is added by @compulim)

## Goals

- Create an activity middleware that will render `entities` in the activity, in addition to standard text or attachment
   - When the activity is rendered, convert/translate `entities` into an additional `attachments`, so we can easily handle render
   - Translate to attachment is recommended because it may not be trivial to mixed rendering of `attachments` and `entities`
- Create an attachment middleware that will render the new attachment using Google Map, Bing Map, or OpenStreetMap as a static image
   - The developers are required to provide their API key for corresponding service
   - We could add a fullscreen button/link that will navigate to the API provider in a new tab
      - When doing navigation, consider using the new `cardActionMiddleware`
- Bundle two middleware together as a function
   - `createMiddleware({ provider: 'google', key: 'a1b2c3d' }) => { activityMiddleware: ..., attachmentMiddleware: ... }`

**Comment by billba** [comment]
We'll need a spec for this one. What is expected, a map? I assume that means using Google or Bing Maps, and that would require an API key.

One possible approach would be to optionally pass such a key as part of Chat Props. Alternatively we could inject in a function which knows how to render a map. The WebChat channel could use the Bing Maps API and its own key.

**Comment by compulim** [comment]
Will write up a sample on how to do this in v4, as a code snippet.
