### ISSUE TITLE
The SendBox should have a notification component to manage ConnectivityStatus and TypingIndicator components

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-WebChat#2323]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The `TypingIndicator` component sits on top of the  `ConnectivityStatus` component in the`BasicSendBox`. At the moment, it is possible for Web Chat to display these two components on the screen at the same time which would clutter the `SendBox`.  Instead of stacking these components, they should behave like the `Timestamp` and `SendStatus` components and share the same space. However, the `ConnectivityStatus` debounces updating the component to display each status for a minimum of 400 ms. This makes it difficult to determine when each component should have ownership over the space.

**Describe the suggestion or request in detail**
The `TypingIndicator` and the `ConnectivityStatus` components should be encapsulated and managed in a `NotificationCenter` component where each child has a certain priority to determine which one Web Chat should render on the screen.

```javascript
<NotificationCenter>
  <ConnectivityStatus />
  <TypingIndicator />
</NotificationCenter>
```

**Describe alternatives you have considered**

Yea, no.

[Enhancement]

**Comment by corinagum** [comment]
This kind of goes hand in hand with the very general 'redesign the sendbox' issue we have: #2211, #1839

**Comment by corinagum** [comment]
Also, this has some a11y considerations I would like to look into, so lmk when you get to this item

**Comment by corinagum** [comment]
New idea discussed by me, @compulim, and @tdurnford:

What if we made a new Toast component, that would allow us to stack notifications, suggested actions, and send typing indicator (and other notifications that the user may want to implement) so that they are no longer a part of the send box (improves simplicity) and allows for a new section of Web Chat that we could call "Status and notifications" or something?

**Comment by compulim** [comment]
Done.
