### ISSUE TITLE
Hiding secret key in JS or HTML

### ISSUE THREAD

**Issue by sreeharikm** [microsoft/BotFramework-WebChat#2325]
Hi,

I am integrating the web chat UI of the Azure bot into a web page using iframe. What is the best practice to hide the secret key from view source. I tried the token method, by generating the token using token api, from a JS file, but still the secret key is exposed over the JS and anyone can open the JS and read it. Is there any better mechanism to hide this - is it possible to restrict the generate token API to allow only certain domains?

Thanks
Sreehari

**Comment by compulim** [comment]
We are not on the services side. But AFAIK, the services team does not have any solution better than asking the developer to host the API token server themselves.

Please feel free to post the question to http://github.com/microsoft/botframework-services and see if they have a better solution.
