### ISSUE TITLE
Sending questions with trailing spaces using enter fails to trim(). - fix included

### ISSUE THREAD

**Issue by jimmyjames177414** [microsoft/BotFramework-WebChat#2328]
## Screenshots
Network call sending trailing spaces:
![image](https://user-images.githubusercontent.com/5471548/63199104-5e101e80-c042-11e9-8746-73e3d758d545.png)

webchat.js needs .trim() added to the following:
![image](https://user-images.githubusercontent.com/5471548/63197487-95300100-c03d-11e9-8182-33ddb7a3db31.png)

webchat-es5.js needs .trim() added to the following:
![image](https://user-images.githubusercontent.com/5471548/63197505-9fea9600-c03d-11e9-84a3-fe0d1183b2cd.png)

## Version
This issue can be found on the following CDN's as of 8/16/2019:
https://cdn.botframework.com/botframework-webchat/master/webchat.js
https://cdn.botframework.com/botframework-webchat/master/webchat-es5.js

https://cdn.botframework.com/botframework-webchat/latest/webchat.js
https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js

## Describe the bug
When sending text with trailing spaces, such as "what is AI  ", and then clicking enter to submit, the trailing spaces are not stripped and the network call sends the trailing white spaces as shown above.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to the textbox and type 'Jim is cool  '
2. Press Enter key
3. Check network call and see that what is sent is the string 'Jim is cool  '

## Expected behaviour
When submitting a question using the enter key, the question should be stripped of trailing white spaces (the same way the click to submit works).

## Additional context
I have attached the two scripts with the fix:
[space fix.zip](https://github.com/microsoft/BotFramework-WebChat/files/3511180/space.fix.zip)

As a special request, could you send a text to (219) 310- 5041 when this bug is fixed? This is a high priority fix for our product.

[Bug]

**Comment by tdurnford** [comment]
@jimmyjames177414 Can you test with latest CDN? Master uses Web Chat v4.3.1 and is no longer updated. 

https://cdn.botframework.com/botframework-webchat/latest/webchat.js
https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js

**Comment by jimmyjames177414** [comment]
@tdurnford I just tested both CDS you suggested and both have the issue.

**Comment by corinagum** [comment]
@jimmyjames177414 Thanks for reporting this issue! If you are able, it would be amazing if you could file an issue with the fix in our repository, and we will prioritize verifying your changes to merge in. 
I am adding this issue to our Triage and we will get the fix added into our code. I think the .js files you have provided are a good workaround to users in the meantime.

This fix will likely be available in our next release in late October. If you need these changes immediately (once the fix is in), please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Comment by jimmyjames177414** [comment]
Sounds great! Consider it done.

**Comment by tdurnford** [comment]
Would it be better to fix this in [`submitSendBoxSaga`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/core/src/sagas/submitSendBoxSaga.js)?

```javascript
function* submitSendBox() {
  yield takeEvery(SUBMIT_SEND_BOX, function*({ payload: { method } }) {
    const sendBoxValue = yield select(sendBoxValueSelector);

    if (sendBoxValue) {
      yield put(sendMessage(sendBoxValue.trim(), method));
      yield put(setSendBox(''));
    }
  });
}
```

@compulim @corinagum

**Comment by jimmyjames177414** [comment]
Sounds good!

**Comment by tdurnford** [comment]
If we are trimming the `sendBoxValue` in the `submitSendBoxSaga`, we should consider removing `            setSendBox(sendBoxValue.trim())` from the [`SendButton`](https://github.com/microsoft/BotFramework-WebChat/blob/007d5dcb3179b04ff0af7e313a6cf89c7e1deb4d/packages/component/src/SendBox/SendButton.js#L13) and [`TextBox`](https://github.com/microsoft/BotFramework-WebChat/blob/007d5dcb3179b04ff0af7e313a6cf89c7e1deb4d/packages/component/src/SendBox/TextBox.js#L34) components. Seems redundant.
