### ISSUE TITLE
Fix prop types

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2336]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/63305397-82b30300-c29b-11e9-9d83-83bdddad62c9.png)

## Version

`master`

## Describe the bug

Probably related to recent merge of PRs.

## To Reproduce

1. Open any web page that host Web Chat
1. Open <kbd>F12</kbd> and check the console

## Expected behavior

No warnings or errors in the console.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
@compulim I'm not able to reproduce this error, and everything looks already with the `typingIndicator` style set and `hideScrollToEndButton` default style options.. My branch is up-to-date and everything builds successfully. Can you try rebuilding your fork and see if the issue persists?

**Comment by compulim** [comment]
@tdurnford Will do.

**Comment by compulim** [comment]
Yap, looks like it is not an issue after I pull everything.
