### ISSUE TITLE
Convert BasicWebChat to React Hooks

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2345]
## Feature Request
Related to: https://github.com/microsoft/BotFramework-WebChat/pull/2322

`BasicWebChat` component has not yet been converted to Hooks. This issue is for tracking that work. :)

**Comment by compulim** [comment]
Will fix in #2364.

**Comment by compulim** [comment]
All hooks are merged and 100% of production code internally use hooks instead of HOC. 🎉🙌🏻🍾🥂
