### ISSUE TITLE
Investigate errors prop on AdaptiveCardAttachment

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2346]
It looks like `errors` is not being used. Need some investigations on why. So feel free to open a new bug to track this investigation outside of this PR, because it sounds at least T-shirt size M to me.

_Originally posted by @compulim in https://github.com/microsoft/BotFramework-WebChat/pull/2322/files_

**Comment by cwhitten** [comment]
Closing due to lack of detail.
