### ISSUE TITLE
StyleOptions parameter to customize color of Markdown link

### ISSUE THREAD

**Issue by iwasn** [microsoft/BotFramework-WebChat#2347]
The default css for markdown links are conflicting with our custom css that we're specifying for the bubble colors. We would like to request a new styleOptions parameter to also customize the color of markdown links to get around this issue.

Thanks!

**Comment by tdurnford** [comment]
Web Chat uses the [Markdown-it](https://www.npmjs.com/package/markdown-it) npm package to render markdown strings into HTML, and I don't believe there would be a simple way to add markdown style options to the existing default style options. However, Markdown-it does wrap the rendered HTML in a div with a `markdown` class label, so you can use generic css  in your project to style different elements.

```css
.markdown a {
    color: red;
}
```

![image](https://user-images.githubusercontent.com/17039790/63569239-6f1ecb00-c52d-11e9-8f8a-b37185ad6589.png)


If you wanted to try to make the changes through the parser, you can create your own render markdown function and pass it as a prop to Web Chat. It looks like there is a [markdown-it-style](https://www.npmjs.com/package/markdown-it-style) plugin you can add to the parser to add custom styles.

```javascript
const MarkdownIt = require('markdown-it');
var MarkdowStyle = require('markdown-it-style);

const markdownIt = new MarkdownIt({ html: false, linkify: true, typographer: true });
markdownIt .use(markdownStyle, { 'a': 'color: red;' });

const renderMarkdown = text => markdownIt.render(text);

 ...

window.WebChat.renderWebChat({
  directLine: window.WebChat.createDirectLine({ token }),
  renderMarkdown
}, document.getElementById('webchat'));
```

Hope this helps!

**Comment by corinagum** [comment]
Closing as resolved. Please feel free add more comments here if you have any :)
