### ISSUE TITLE
Timestamp locale does not change when updating language on-the-fly

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2360]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/63751943-2cc6f800-c865-11e9-83bc-06f71293695b.png)

## Version

`master`

## Describe the bug

When `locale` prop is updated on-the-fly, the timestamp doesn't change accordingly.

## To Reproduce

1. Go to playground
2. Send some messages
3. Change the language to another one

## Expected behavior

Timestamp is immediately localized in another language.

Actual, it is kept the same until page refresh.

## Additional context

Playground is currently broke, change line 246 like below.

![image](https://user-images.githubusercontent.com/1622400/63752052-5ed85a00-c865-11e9-9827-c1990194c6e3.png)

[Bug]

**Comment by mohmed-elkhodry** [comment]
I face the same issue on version 4.15.2 
is there any updates regarding this issue in this version ?
