### ISSUE TITLE
Adaptive Card buttons are wonky on Mac Chrome

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2365]
## Screenshots

![image](https://user-images.githubusercontent.com/14900841/63814845-2da06e00-c8e7-11e9-99e4-7f4ca385bf26.png)

## Version

4.5.3

## Describe the bug
  - Adaptive Card buttons show as having a gradient that looks bad. Interestingly, when you set the background color manually to `.ac-pushButton` will remove the gradient. We're still not sure why this is happening.

## To Reproduce

1. Open Mock Bot in Chrome on a Mac. 
1. Type help
1. Note that the buttons have a gradient background.

## Expected behavior

Adaptive Card buttons should show as plain white.

## Additional context

[Bug]

**Comment by compulim** [comment]
I think we should file this bug to Adaptive Card and ask them to set `appearance: none` (also for vendor prefix if needed, i.e. `-webkit-appearance: none`).

**Comment by compulim** [comment]
Filed an issue to Adaptive Card team, https://github.com/microsoft/AdaptiveCards/issues/3411.

**Comment by corinagum** [comment]
It looks like this is a won't fix from AC team, but as a workaround we will add `appearance: none` to `ac-pushButton` in `AdaptiveCardRenderer.js`
