### ISSUE TITLE
How can we display code inside the chat attachment ?

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotFramework-WebChat#237]
Is there any way we can display code inside the webchat. For example - A html code when displayed is displayed as a normal text. How can I make it displayed as a code ?

**Comment by billba** [comment]
WebChat supports Markdown, so you can put it inside backquotes, e.g. \`hello\` => `hello`

**Comment by kanwal019** [comment]
@billba What if I had to send the code as a message from bot. Should markup help in this case ?

**Comment by billba** [comment]
Yes I am talking about sending messages from the bot.
