### ISSUE TITLE
Sample 21 MockBot is broken

### ISSUE THREAD

**Issue by GewoonMaarten** [microsoft/BotFramework-WebChat#2373]
When I tried [the link in de readme from sample 21.customization-plain-ui](https://microsoft.github.io/BotFramework-WebChat/21.customization-plain-ui/) it tried to get some js files that don't exist.

See console errors 👇
```
GET https://microsoft.github.io/BotFramework-WebChat/19.customization-plain-ui/static/js/2.6b7e9811.chunk.js net::ERR_ABORTED 404 (Not Found)
manifest.json:1 GET https://microsoft.github.io/BotFramework-WebChat/19.customization-plain-ui/manifest.json 404 (Not Found)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
```

**Comment by corinagum** [comment]
@GewoonMaarten Your trying to use sample 21, but it looks like the directory that's building is sample 19. Did you run `npm run build` in sample 21 directory?

**Comment by GewoonMaarten** [comment]
I did. Seems like the "homepage" key in the package.json is wrong. It is https://microsoft.github.io/BotFramework-WebChat/19.customization-plain-ui/ but should be https://microsoft.github.io/BotFramework-WebChat/21.customization-plain-ui/

**Comment by corinagum** [comment]
Thanks for filing! :)
