### ISSUE TITLE
reset the conversation without browser reload

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2376]
Hello,

i am having one **custom button** on webchat V3 and webchat V4 clicking on button will **refresh the browser** and **new conversation ID** is generating. Is it possible that without **refreshing the browser** the bot will get **reset** and **new conversation id** will generate while clicking on **custom button**?

please, help me to find the solution.

**Comment by tdurnford** [comment]
@Bradrajkumar 
Ideally, you would be able to reset the Web Chat store to restart the conversation; however, this is not currently supported Web Chat v4.5.2. The Development Team is currently working to add this functionality, and it should be available in our next release towards the end of October. For more details, take a look at https://github.com/microsoft/BotFramework-WebChat/issues/1846.

**Comment by Bradrajkumar** [comment]
rightnow i am using webchat v3 and want to implement it. may i get the code snippet to do this. i want it using javascript/jquery.

**Comment by mrk1989** [comment]
There is new notice?
