### ISSUE TITLE
German localization needs to be updated 

### ISSUE THREAD

**Issue by HRViolation** [microsoft/BotFramework-WebChat#2386]
Technically these are three bugs, but so closely related and small they would likely be fixed together. Modify this bug and/or create another if necessary.

Repro:
Change browser settings to a Non-English language
Open Azure Dev Portal
In Azure Dev Portal Settings change the language settings to the same Non-English language
Create a Web Bot
Test chatting with a bot.

Issue 1:
"Just now" is not localized

Issue 2:
"A minute ago" incurs a localization cost because it does not follow the pattern of "X minute (s) ago".

Issue 3:
The timing message "X minute (s) ago" is not localized.

**Comment by tdurnford** [comment]
Are you seeing this issue in the Test in Web Chat blade in the Bot Channels Registration in the Azure Portal or in Web Chat on your own web page?

**Comment by corinagum** [comment]
What language are you changing to? If the language is not represented in our [Localization folder](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/component/src/Localization), the language will default to English.

**Comment by HRViolation** [comment]
This is in the Azure Dev Portal itself.

Chrome Browser and Azure language settings are set to German.

**Comment by corinagum** [comment]
@HRViolation thanks for reporting this. Taking a look at the [German localization file](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Localization/de-DE.js), we are indeed in need of an update. Are you a fluent speaker and able to do a Pull Request to update the file for us? If not, do you know any fluent speakers that could help out? 

If so, please feel free to take a look at the [Arabic localization pull request](https://github.com/microsoft/BotFramework-WebChat/pull/2369) that we received recently for information on what files to touch when creating a localization update. If you have any questions please feel free to post them here. 

Thank you!

**Comment by compulim** [comment]
Closing as German is now officially translated by Microsoft internal team.
