### ISSUE TITLE
Tax and Total should be omitted from Receipt Card if not supplied

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/BotFramework-WebChat#239]
Via https://github.com/Microsoft/BotBuilder/issues/1733

**Comment by siddiq-rehman** [comment]
You can put a conditional loop in attachment.tsx at the point  case:"application/vnd.microsoft.card.receipt",

    You can write a if conditional loop which checks whether tax and total are present then render difffernt type of card like,


if(!attachment.content.tax && !attachment.content.total)
            return (
                <div className='wc-card receipt'>
                    <table>
                        <thead>
                            <tr>
                                <th colSpan={ 2 }>{ attachment.content.title }</th>
                            </tr>
                            { attachment.content.facts && attachment.content.facts.map(fact => <tr><th>{ fact.key }</th><th>{ fact.value }</th></tr>) }
                        </thead>
                        <tbody>{ attachment.content.items && attachment.content.items.map(item =>
                            <tr>
                                <td>{ item.image && imageWithOnLoad(item.image.url) }<span>{ item.title }</span></td>
                                <td>{ item.price }</td>
                            </tr>) }
                        </tbody>
                    </table>
                </div>
            );
