### ISSUE TITLE
How can I package to generate a webchat.js file?

### ISSUE THREAD

**Issue by Fuyuwei-Fxx** [microsoft/BotFramework-WebChat#2390]
🚨 The issue tracker is not for implementation questions 🚨

[How can I package to generate a webchat.js file? for example https://cdn.botframework.com/botframework-webchat/latest/webchat.js]

**Comment by tsuwandy** [comment]
@compulim, is this something you could help with?

**Comment by compulim** [comment]
@Fuyuwei-Fxx You can follow the instructions at https://github.com/microsoft/BotFramework-WebChat/blob/master/.github/CONTRIBUTING.md to build a CDN bundle (i.e. `webchat.js`).

Thanks!
