### ISSUE TITLE
Cognitive Services Speech Permanently Disabled After Clicking Action Button 

### ISSUE THREAD

**Issue by batesiiic** [microsoft/BotFramework-WebChat#2397]
## Describe the bug

When using Cognitive Services speech, having the microphone open then clicking an action button (from a card, confirm prompt, etc) will permanently disable the micorphone. This requires the user to reload the page to get it back. 

## To Reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/06.f.hybrid-speech/
2. Tell the bot "help"
3. Enable the microphone by clicking the microphone icon
4. Click one of the buttons displayed by the bot
-> Error: the microphone is now off but the icon is disabled and can't be opened again

## Expected behavior

The microphone should either re-open or close (probably depending on input hint of the next bot response?) and allow for it to be re-opened.

[Bug]

**Comment by corinagum** [comment]
This issue should be fixed in the next release of Web Chat. Could you try out Web Chat's latest bits to see if this resolves your issue? Please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

Please let us know your results and feel free to elaborate on pain points.

**Comment by batesiiic** [comment]
Thanks for the quick response. I'm having a bit of trouble getting this set up because we're not actually hosting a full site but rather just a single page that gets pulled into a xamarin web view. To do this we're just statically hosting the chat html that is pointing to the webchat CDN. I was going to try and get the Angular example going but it explicitly says that it doesn't support pulling in packages with the latest without going through several more steps.

Out of curiosity, does  https://cdn.botframework.com/botframework-webchat/master/webchat.js point to the latest (same as the myget feed)? If so, we tried this and it certainly behaves better than before but had some other oddities that I can go into more detail about if this is in fact the same as the myget latest bits.

**Comment by corinagum** [comment]
Hi @batesiiic. Our MyGet feed contains our latest bits, and reflects the current changes available. This includes unreleased features and bug fixes. Our CDN is our latest official release, which was last patched in early August. 

Right now the MyGet feed is the only way to test the latest features that include the Speech fix. If you prefer to wait for the official release, 4.6 is currently scheduled for the end of October.

For reference (I should have linked this above), this is the Pull Request that has the microphone fixes: https://github.com/microsoft/BotFramework-WebChat/issues/2240

I am going to close this question as answered, but if you try out the MyGet feed bits and run into further issues, please feel free to comment here and I will re-open. Thank you!

**Comment by batesiiic** [comment]
@corinagum I was able to put together a simple react page to test this and it behaves exactly as we'd hoped. Thanks for the help.
