### ISSUE TITLE
Adding allowfullscreen and frameborder attributes to YouTubeContent iframe 

### ISSUE THREAD

**Issue by urker** [microsoft/BotFramework-WebChat#2398]
Hello ,

I was wondering is there a way to add allowfullscreen and frameborder attributes to iframe that is used to play youtube videos programmatically  by defining new styleset for youtube content . Reason is youtube videos can't be expanded  to full screen mode as by default iframe that is wrapping youtube video doesn't have these attributes.
I saw that in webchat component library there is styleset for YouTubeContent , can this be used or is there any other way to customize  iframe for youtube content .

**Comment by tdurnford** [comment]
It looks like we would need to add the allow `allowFullScreen` prop to the iframe. We would probably have to add it to the Vimeo Attachment as well. @corinagum @compulim Do we want to enable this behavior by default or make it part of the default style options?

```diff
const YouTubeContent = ({ alt, autoPlay, embedID, loop, styleSet }) => {
  const search = new URLSearchParams({
    autoplay: autoPlay ? 1 : 0,
    loop: loop ? 1 : 0,
    modestbranding: 1
  }).toString();

  return (
    <iframe
+     allowFullScreen={true}
      aria-label={alt}
      className={styleSet.youTubeContent}
      src={`https://youtube.com/embed/${embedID}?${search}`}
    />
  );
};

```

https://github.com/microsoft/BotFramework-WebChat/blob/928217408c853e261cd3fcba69604228e72a3bdb/packages/component/src/Attachment/YouTubeContent.js#L15

**Comment by tdurnford** [comment]
@urker I opened a PR to add full screen capabilities for YouTube and Vimeo videos. That feature should be available in the next release. Also you should be able to add a border to the iframe by modifying the style set. 

```javascript
const styles = window.WebChat.createStyleSet();
const styleSet = {
  ...styles,
  youTubeContent: {
    ...styles.youTubeContent,
    border: 'solid 5px red'
  }
}
```
