### ISSUE TITLE
Only get one reply then nothing.

### ISSUE THREAD

**Issue by nmunday** [Microsoft/BotFramework-WebChat#240]
I created a test echo bot. Works on Skype, works in console app using direct line. When I try the webchat control I get one reply echoed. But underneath the reply it says 'Could not send'. Then after that I get no more replies no matter what I type. See below

![image](https://cloud.githubusercontent.com/assets/7116951/21409253/151a162c-c78e-11e6-9017-ed50e8035a30.png)

Nick

**Comment by billba** [comment]
That is certainly an unusual situation. The error message is telling us that the activity.id of that message is null, which should never happen for a message sent from the bot, as the framework should have assigned it an id. Have you tried your bot in the emulator? Have you tried [turning on debug messages](https://github.com/Microsoft/BotFramework-WebChat/#to-see-webchat-logging)? It would be helpful to examine the contents of that message.

**Comment by nmunday** [comment]
@billba thanks for the quick response. I changed the bot to return the activity id that it received. Below is the screenshot, as you can see it is not null. I have tried the emulator and that works! I will try turning on debug.  

![image](https://cloud.githubusercontent.com/assets/7116951/21410210/cf2b724a-c793-11e6-96f4-220e82cec9ba.png)

**Comment by nmunday** [comment]
Just to clarify. The emulator was connected to a local copy of the bot. Not to the one running in Azure.

Nick

**Comment by billba** [comment]
That is the id of the message it *received*, but the problem is the id of the message it is *sending*. This won't be visible to the bot as it is assigned after the bot sends it. It will only be visible to the control.

**Comment by nmunday** [comment]
I am going to close this issue. The bot that is failing is my attempt to get a bot running under .NET Core 1.1 so I could not use BotBuilder C# package. I generated my own API using AutoRest and Swagger. Probably something I have messed up or missed. Right now I am rebuilding the Bot on .NET 4.6 so I will be able to use the BotBuilder SDK.

Regards,

Nick Munday

**Comment by billba** [comment]
Yup, bots don't work under .NET Core yet.
