### ISSUE TITLE
Can't set userAvatarBackgroundColor

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2430]
The userAvatarBackgroundColor is not reflecting to the set color. It stays blue. The same is true for bot avatar background color.
Using CDN: https://cdn.botframework.com/botframework-webchat/latest/webchat.js

![Capture](https://user-images.githubusercontent.com/22778273/65795487-3cb15080-e11f-11e9-89aa-c0a4a475ba9b.PNG)
`styleOptions: {

	  botAvatarImage: "https://static.crozdesk.com/web_app_library/providers/logos/000/003/155/original/chatbots-builder-1510149769-logo.png?1510149769",
	  botAvatarInitials: "BF",
	  botAvatarBackgroundColor: "#17a2b8",
	  bubbleBackground: "#F0F0F0",
	  bubbleTextColor: "Black",
	  bubbleBorderRadius: 10,

	  bubbleFromUserBorderRadius: 10,
	  bubbleFromUserBackground: "#6699FF",
	  bubbleFromUserTextColor: "White",
	  userAvatarBackgroundColor: "#19194d",
	  userAvatarInitials: "You",
	  //userAvatarImage: "https://github.com/compulim.png?size=64",
	}`

**Comment by tdurnford** [comment]
The `userAvatarBackgroundColor` style option was adding in PR #2384 which will be include in our v4.6 release towards the end of October. If you need an immediate solution, please take a look at our documentation on using the [Latest Bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

**Comment by arman-g** [comment]
Thank you!
