### ISSUE TITLE
WebChat Channel Stopped working suddenly for all our bots from yesterday.

### ISSUE THREAD

**Issue by laxmanj8666** [microsoft/BotFramework-WebChat#2437]
We have WebChat channel in azure for our bots, starting yesterday afternoon. The webChats stopped responding. Everything was working fine but suddenly stooped working.

## Screenshots

<img width="892" alt="Screen Shot 2019-10-02 at 9 43 37 AM" src="https://user-images.githubusercontent.com/3451844/66054864-3f82bb80-e4fa-11e9-923d-edeb7c00c487.png">
<img width="847" alt="Screen Shot 2019-10-02 at 9 43 53 AM" src="https://user-images.githubusercontent.com/3451844/66054888-47426000-e4fa-11e9-808f-fcb6007d1df7.png">
<img width="837" alt="Screen Shot 2019-10-02 at 9 44 16 AM" src="https://user-images.githubusercontent.com/3451844/66054897-4b6e7d80-e4fa-11e9-9fe7-d8af27c1cfb9.png">

## Version

1. Using via https://webchat.botframework.com/embed/ginabeta?s=Secret Key not working.
2. As a React Component = Not working. 

All these were working prior.

## Describe the bug

We have WebChat channel in azure for our bots, starting yesterday afternoon. The webChats stopped responding. Everything was working fine but suddenly stooped working.
 I can see the message on Web App logs, but they are getting displayed back to web chat.

## To Reproduce

https://webchat.botframework.com/embed/ginabeta?s=YOUR_SECRET_HERE
or React component and try to replicate the Bot secret key on the web chat.

## Expected behavior

Behaviour before it stopped working 
![Screen Shot 2019-10-02 at 9 55 33 AM](https://user-images.githubusercontent.com/3451844/66055201-cf286a00-e4fa-11e9-9194-0417e350a78b.png)

## Additional context

[Bug]

**Comment by laxmanj8666** [comment]
If I change ID from Webchat secret to direct line secret it started to work.

**Comment by CoHealer** [comment]
@stevkan, can you please confirm this should have been closed?

**Comment by stevkan** [comment]
@laxmanj8666, reopening to confirm you don't need anymore help? The webchat secret should work and if it still is not, then that is an issue that we should try and resolve.

Please let me know if you require further assistance on this.

Thanks!
Steve.

**Comment by stevengum** [comment]
@laxmanj8666 if you need any more assistance please open a new issue. I'm going to close this issue as it sounds like it has been fixed.
