### ISSUE TITLE
Return custom html for an activity

### ISSUE THREAD

**Issue by kanwal019** [Microsoft/BotFramework-WebChat#244]
Can we return custom html instead of the react elements to display the activity from the bot or the user ?

```
if (!this.props.text || this.props.text === '')
	            return null;
	        switch (this.props.format) {
	            case "plain":
	                return this.renderPlainText();
	            case "xml":
	                return this.renderXml();
	            default:
	                return this.renderMarkdown();
```

Is it possible to render HTML with addition to these ?

**Comment by billba** [comment]
I'm not sure exactly what you're after here. Direct Line only returns these three text types so the lack of HTML isn't a limitation of the client.

Also, what is called "xml" here is really just a strict subset of HTML, but right now (as you may have noticed) we don't actually support that. There is some ongoing discussion about whether Direct Line will ever send that format.

**Comment by kanwal019** [comment]
@billba If I send this text from the bot application `<div style='color=red;'>Wrong Input</div>`, It is displayed as a text in the chat window, but I need to display the text inside the `<div>` i.e. Wrong Input, with the style applied to the div. 

Is there any possible way that I will be able to achieve this ?

**Comment by billba** [comment]
@kanwal019 As currently conceived WebChat will not let through raw HTML, any more than any other chat client (e.g. Facebook Messenger, Skype, Slack) would. You can of course choose to fork the repo and add this capability.

**Comment by billba** [comment]
Closing this as out of scope for the current product.
