### ISSUE TITLE
Cherry-pick for 4.5.3

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2448]
## Background

Bump to 4.5.3 with cherry-picked fixes.

We would love to focus on 3 areas: accessibility fix, thumbnail URL, speech parity work.

## Pull requests

- Accessibility fix
   - [x] #2423 
- Thumbnail URL
   - [x] #2206
   - [x] #2262
   - [x] #2433
- Speech work
   - We will skip speech work in this patch release
   - [x] ~#2338~
   - [x] ~#2241~
   - [x] ~#2246~
   - [x] ~#2300~
   - [x] ~#2320~
   - [x] ~#2408~
   - [x] ~#2429~
   - [x] ~#2445~
   - [x] ~Bump to `web-speech-cognitive-services@4.0.1-master.556e2aa`~
      - This is because `event-target-shim` brought in earlier builds, will break bundle under IE11

## Extra things to look at

We have some bad bugs and if they break, we should triage to see if they should include in 4.5.3.

- (Layout) Check receipt card rendering
   - We might need to cherry-pick #2417 for a fix
- (Performance) Wasted render by connectivity status
   - We might need to cherry-pick #2419 for a fix

**Comment by corinagum** [comment]
Closing as resolved: https://github.com/microsoft/BotFramework-WebChat/pull/2455
