### ISSUE TITLE
Web Chat embed page does not work on IE11

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/BotFramework-WebChat#2449]
## Version

Default version that is used in Azure Portal --> Bot Service --> Test in Webchat

## Describe the bug

Webchat Embed page does not work on IE11. The message box doesnt appear.

## To Reproduce

1. Go to Azure Portal --> Open a Web App Bot that you have created
2. Click on Test in Webchat
3. Notice that the message box is missing and we cannot type anything

## Expected behavior

Expect WebChat to work the same as other browsers.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
The Test in Web Chat blade in Azure is throwing an "ajaxExtended call failed" error in IE 11. 

![image](https://user-images.githubusercontent.com/17039790/66326732-5cdecd80-e8de-11e9-8f91-76780ad17e04.png)

I tried navigating to [https://webchat.botframework.com/embed/b/gemini?s=<WEB_CHAT_SECRET>&b=<BOT_ID>]() to see if the error would replicated, and Web Chat threw a "'Promise' is undefined" error. We are probably missing a polyfill. 

![image](https://user-images.githubusercontent.com/17039790/66326842-944d7a00-e8de-11e9-93e3-5067b65c4aae.png)

@p-nagpal Thank you for reporting this issue. The Development team will continue to investigate this issue.

**Comment by cwhitten** [comment]
This will be addressed in 4.6/Ignite with https://github.com/microsoft/BotFramework-WebChat/pull/2315. Please reach out if this needs to be addressed sooner.

**Comment by tdurnford** [comment]
@cwhitten will Test in Web Chat be bumped to v4.6 after Ignite?

**Comment by cwhitten** [comment]
It will also need to be bumped

**Comment by corinagum** [comment]
I'm going to close this issue since the PR is already in master bits.

**Comment by pdemro** [comment]
> 
> 
> This will be addressed in 4.6/Ignite with #2315. Please reach out if this needs to be addressed sooner.

@cwhitten Is it possible to pull this fix from NPM or elsewhere before Ignite?

**Comment by corinagum** [comment]
Please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

You can also follow the build directions on CONTRIBUTING.md to build your own temporary bundle of the latest bits.

**Comment by lelgouacem** [comment]
> This will be addressed in 4.6/Ignite with #2315. Please reach out if this needs to be addressed sooner.

Has this been addressed? We checked out chat in IE this morning and do not see any fix from when we deployed on Friday.

**Comment by corinagum** [comment]
@lelgouacem, I checked out Internet Explorer and it looks like the embed page is not working. However since the error messages are different I am going to open a new issue to track further progress.
