### ISSUE TITLE
A11y_VirtualAgentBots_Virtual Agent Home_Chat Dialog_AI4W: Certain ARIA roles must contain particular children (.css-ljhy6a)

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/BotFramework-WebChat#2456]
**Issue**
Certain ARIA roles must contain particular children (aria-required-children) 

**Element path**
.css-ljhy6a 

**Snippet**
ul aria-live="polite" class="css-ljhy6a css-7c9av6" role="list"></ul

**How to fix**
Fix any of the following:
- Required ARIA child role not present: listitem 

**Environment**
Chrome version 76.0.3809.132 This accessibility issue was found using Accessibility Insights for Web 2.8.2 (axe-core 3.2.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).

**Comment by cwhitten** [comment]
Thank you the issue. However, we are in the midst of an internal a11y audit to meet WCAG 2.1. The mechanisms to open, track, and address issues uncovered during the audit is a different process. I will close this for now.
