### ISSUE TITLE
InputHint - acceptingInput - for a single message activity turns on microphone, while its said only 'expectingInput' will turn on microphone

### ISSUE THREAD

**Issue by ManjulaMalaiarasan** [microsoft/BotFramework-WebChat#2457]
## Version
Webchat version :  "4.4.2-0" -  npm package

## Describe the bug
when a single message activity is sent with inputHint set to acceptingInput, the microphone is turned on automatically on the webchat and listening to user on latest Chrome browser. 
Currently only way to keep the microphone off is to set the inputHint to ignoring input. 

It is expected that acceptingInput hint should not turn on the microphone. 

## Expected behavior

For a single message activity,  acceptingInput inputHint should not turn on the microphone. 
for multiple consecutive activities the behavior is defined here https://github.com/microsoft/BotFramework-WebChat/issues/2158

**Comment by corinagum** [comment]
@compulim I believe you are currently investigating this problem, is that correct?

**Comment by corinagum** [comment]
@ManjulaMalaiarasan thanks for reporting this issue. However I notice that you are using an older version of Web Chat. Could you test this out using Web Chat's latest, and see if the issue is still being reproduced? Please let us know your findings here. Thank you!

**Comment by ManjulaMalaiarasan** [comment]
@corinagum Just tested with version 4.5.4. The inputHints work correctly for single and multiple activities and the issue is not reproducible. Thank you. I guess the recommendation would be to update my webchat then.
