### ISSUE TITLE
[Tracking] Update webSpeechPonyFillFactory signature to accept a promise for region

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-WebChat#2459]
This issue is to track the need to update the `webSpeechPonyFillFactory` signature so that we can provide a promise that returns both the `region` and `authorizationToken` together.

This will be necessary once the BF speech service resources are scaled up to more datacenters outside of `westus`. Currently, the region is hardcoded in the Emulator.

See PR https://github.com/microsoft/BotFramework-Emulator/pull/1878/files for context.

**Comment by bwamie** [comment]
It would be great if it accepts a `speechAuthenticationToken` promise which actually has both the token and region so that we don't have to hardcode the region or to only pass it once..
