### ISSUE TITLE
A11y_VirtualAgentBots_VirtualAgentHome_ChatDialog_Usability: Unnecessary "Tab" navigation provided for the <(left) and >(right) buttons that appears for the list of stores.

### ISSUE THREAD

**Issue by Vividha-Khandelwal** [microsoft/BotFramework-WebChat#2463]
"Check out Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier."

Environment Details:
Application Name: Virtual Agent Bot
 Browser Version: Microsoft Edge 44.18362.267.0, Google chrome Version 76.0.3809.100 (Official Build) (64-bit)
Windows Version: Windows10

Repro Steps: 
1. Home page should open for Virtual Agent Bots.
2. Navigate to main content area chat dialog,  the left side of the screen.
3. Select "Store Hours" button and Bot would give list of stores.

Actual: 
Unnecessary "Tab" navigation provided for the <(left) and >(right) buttons that appears for the list of stores.
The "Tab" focus moves to left and right buttons for the navigation but they themselves are accessed after complete navigation of the store list. No action is performed on both the buttons present.

Expected: 
<(left) and >(right) buttons should not receive unnecessary "Tab" navigation when user is not able to perform action on these buttons.

User Impact: 
If there is no functionality available on interacting with the control and the control is in the enable state then the user will keep interacting with it and this will lead into confusion.
 
[5239320_A11y_VirtualAgentBots_VirtualAgentHome_ChatDialog_Usability.pptx](https://github.com/microsoft/BotFramework-WebChat/files/3716015/5239320_A11y_VirtualAgentBots_VirtualAgentHome_ChatDialog_Usability.pptx)

**Comment by cwhitten** [comment]
Thank you the issue. However, we are in the midst of an internal a11y audit to meet WCAG 2.1. The mechanisms to open, track, and address issues uncovered during the audit is a different process. I will close this for now.
