### ISSUE TITLE
A way to override Localisation

### ISSUE THREAD

**Issue by Hatzman91** [microsoft/BotFramework-WebChat#2467]
## Feature Request

I have found no way to override the localisation for example the "Type your message" in the SendBox. Because in the German version we want to use a more polite form of language.

![image](https://user-images.githubusercontent.com/26482488/66750037-a6ee2300-ee8b-11e9-8321-35e3e35770ab.png)

We want there to have "Verfassen Sie eine Nachricht".

Thanks :)

**Comment by tdurnford** [comment]
This a duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/1833 which is being tracked with https://github.com/microsoft/BotFramework-WebChat/issues/1839.

**Comment by corinagum** [comment]
Closing as a duplicate.
