### ISSUE TITLE
Cognitive Speech Services sample closes the microphone before human can speak.

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2469]
> Note: customer-reported label is accurate, and I'm just bringing the comment to a newly filed bug.

Originally brought to our attention by @alokraj68 on issue https://github.com/microsoft/BotFramework-WebChat/issues/1848

## Screenshots
![microphone](https://user-images.githubusercontent.com/14900841/66769708-a1ccac00-ee6a-11e9-902d-36702b3b9bf1.gif)

Note that when clicked, the microphone almost immediately disables.

## Version

latest bits (4.5.4/master)

## Describe the bug

When clicked, the microphone button appears to enable speech detection very briefly, but not long enough for a user to say anything, then immediately disables. There is no apparent way to keep speech detection open longer. Holding down the microphone button does not change behavior.

## To Reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/06.c.cognitive-services-speech-services-js/
2. Click on the microphone button
3. Attempt to say 'help'
4. Notice that the microphone almost immediately closes.
5. Note that there are no console errors.

## Expected behavior
Speech detection should be available long enough for the user to say something.

## Additional context
I am assigning this bug to @compulim for investigation.

[Bug]

**Comment by alokraj68** [comment]
Hi, to add up, 
am doing `speechServicesPonyfill.speechSynthesis.cancel();` to stop the speech when the user is clicking a button. after sometime when the user try to resume speech I want to clear any pre-existing ones in the queue and activate speech recognizer. But once this cancel is called, after some seconds I get this Log message and the mic becomes not responding.

**Comment by corinagum** [comment]
Hi @alokraj68, thanks for your patience! 

I'm sorry to say that the issue I filed above was a dev error on my part. Our team's bot's speech token had expired which is why I was unable to use speech with Web Chat. 

However, I investigated your issue using Web Chat's latest bits (and a non-expired token!) and I believe the issue you are reporting is fixed, meaning that the fix will be available after our release at the beginning of November.

Could you try your scenario using Web Chat's latest bits? Please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).

I am going to close this issue because the bug I filed and what you are experiencing are different. However I am still happy to investigate this with you. After you test MyGet bits, if you are still having problems, could you please: 
1. File a new issue
1. Include a video reproducing your error, and also provide your console errors

If testing on latest bits fixes your problem, please feel free to leave a comment on this thread and I will see your update. Thank you!

**Comment by alokraj68** [comment]
> Hi @alokraj68, thanks for your patience!
> 
> I'm sorry to say that the issue I filed above was a dev error on my part. Our team's bot's speech token had expired which is why I was unable to use speech with Web Chat.
> 
> However, I investigated your issue using Web Chat's latest bits (and a non-expired token!) and I believe the issue you are reporting is fixed, meaning that the fix will be available after our release at the beginning of November.
> 
> Could you try your scenario using Web Chat's latest bits? Please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).
> 
> I am going to close this issue because the bug I filed and what you are experiencing are different. However I am still happy to investigate this with you. After you test MyGet bits, if you are still having problems, could you please:
> 
> 1. File a new issue
> 2. Include a video reproducing your error, and also provide your console errors
> 
> If testing on latest bits fixes your problem, please feel free to leave a comment on this thread and I will see your update. Thank you!

Hi,
I could see the latest bits documentation. But is it available for CDN? its only telling how I can install it, but not how I can consume the same.

**Comment by alokraj68** [comment]
> Hi @alokraj68, thanks for your patience!
> 
> I'm sorry to say that the issue I filed above was a dev error on my part. Our team's bot's speech token had expired which is why I was unable to use speech with Web Chat.
> 
> However, I investigated your issue using Web Chat's latest bits (and a non-expired token!) and I believe the issue you are reporting is fixed, meaning that the fix will be available after our release at the beginning of November.
> 
> Could you try your scenario using Web Chat's latest bits? Please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).
> 
> I am going to close this issue because the bug I filed and what you are experiencing are different. However I am still happy to investigate this with you. After you test MyGet bits, if you are still having problems, could you please:
> 
> 1. File a new issue
> 2. Include a video reproducing your error, and also provide your console errors
> 
> If testing on latest bits fixes your problem, please feel free to leave a comment on this thread and I will see your update. Thank you!

Hi,

I tired out the latest bits and the issue is not coming in it. but I am not able to cancel the pending speech. The speech synthesis is working for every message after I give the cancel. Is the clear all method missing for speech synthesis?

Expected: Speech synthesis should not speak out once the cancel or stop is called.

Actual: It continued to work for every subsequent messages. Also, the pending queue is also played.

**Comment by alokraj68** [comment]
@corinagum, the issue I was saying is still there in 4.6 Version. 

> > Hi @alokraj68, thanks for your patience!
> > I'm sorry to say that the issue I filed above was a dev error on my part. Our team's bot's speech token had expired which is why I was unable to use speech with Web Chat.
> > However, I investigated your issue using Web Chat's latest bits (and a non-expired token!) and I believe the issue you are reporting is fixed, meaning that the fix will be available after our release at the beginning of November.
> > Could you try your scenario using Web Chat's latest bits? Please see our documentation on pointing to our MyGet feed for [latest bits](https://github.com/microsoft/BotFramework-WebChat#how-to-test-with-web-chats-latest-bits).
> > I am going to close this issue because the bug I filed and what you are experiencing are different. However I am still happy to investigate this with you. After you test MyGet bits, if you are still having problems, could you please:
> > 
> > 1. File a new issue
> > 2. Include a video reproducing your error, and also provide your console errors
> > 
> > If testing on latest bits fixes your problem, please feel free to leave a comment on this thread and I will see your update. Thank you!
> 
> Hi @corinagum ,
> 
> I tired out the latest bits and the issue is not coming in it. but I am not able to cancel the pending speech. The speech synthesis is working for every message after I give the cancel. Is the clear all method missing for speech synthesis?
> 
> Expected: Speech synthesis should not speak out once the cancel or stop is called.
> 
> Actual: It continued to work for every subsequent messages. Also, the pending queue is also played.

**Comment by corinagum** [comment]
@alokraj68, unfortunately I am not able to reproduce your issue on latest bits using one of our speech samples.

**Comment by alokraj68** [comment]
Hi, I will open this as a new issue since it seems different from this one. #2568
