### ISSUE TITLE
Custom voice is not being supported

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2471]
## Version
4.5.2

## Describe the bug
i have added all fields defined in the documentation,but the custom voice is not playing.

## To Reproduce

selectVoice: () => ({ voiceURI: 'BlaBla' }),
            webSpeechPonyfillFactory: await this.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
                region: 'westus2',
                speechSynthesisDeploymentId: 'e123sdf3423c',
                subscriptionKey: 'sdf24232dsff'
            })

**Comment by tdurnford** [comment]
This looks like a duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/2424 which should be resolved in our next release towards the end of the month.

**Comment by corinagum** [comment]
Closing as duplicate.
