### ISSUE TITLE
Customizable Timestamp font

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2476]
##Overview
For fixing the font issue inside the bot, the suggested solution was to change the parameters in .body of the parent component. But that messes up the Timestamp font size. Fontsize attribute is something which is needed in all aspects of the bot.
!
![Capture](https://user-images.githubusercontent.com/11289456/66917930-eeb3ac80-f03b-11e9-81dd-ebaeac5121e3.PNG)

**Comment by corinagum** [comment]
Hi @prashanthsridhar, in `defaultStyleOptions.js` there is the option called `fontSizeSmall` that you can change to fit your needs. The default value is 80%. Please note that this will affect other fonts, for example the connectivity status font as well.
