### ISSUE TITLE
Add a sample to consume latest bits

### ISSUE THREAD

**Issue by alokraj68** [microsoft/BotFramework-WebChat#2479]
## Feature Request

1. Consuming the latest bits in non NPM environments like via a CDN.
2. Consuming the latest bots in NPM environments.

1. A sample to show how we can try the latest bits of web chat using pure HTML CDN
2. A sample to show how we can try the latest bits of web chat to use in NPM environments.

The CDN link to webchat latest bits will let people use it to do quick testing.

**Comment by corinagum** [comment]
Hi @alokraj68, unfortunately we do not have a CDN of our master bits at this time. One option available to our customers is to clone Web Chat, build it, and use the `webchat.js` file under `packages/bundle/dist/` add that file as your script.

Please take a look at our `CONTRIBUTING.md` to see how to build Web Chat.

**Comment by corinagum** [comment]
Our daily build of Web Chat, including the bundled `webchat*.js` files, is now available on our releases page: https://github.com/microsoft/BotFramework-WebChat/releases/tag/daily

**Comment by alokraj68** [comment]
Thanks @corinagum That's a great move
