### ISSUE TITLE
Support alternative audio input source (Bluetooth adapter)

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2481]
> This issue is currently blocked by https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/96.

## Feature Request

Some browsers may not select the correct audio input source for speech recognition. For Cognitive Services, it support alternative audio input source by specifying the device ID (`navigator.mediaDevices.enumerateDevices`).

## Implementation details

- Passing custom `audioConfig` is already supported in the Cognitive Services adapter
   - (No code modifications needed, just referencing them here)
   - https://github.com/compulim/web-speech-cognitive-services/blob/master/packages/component/src/SpeechServices/SpeechToText/createSpeechRecognitionPonyfill.js#L92
   - https://github.com/compulim/web-speech-cognitive-services/blob/master/packages/component/src/SpeechServices.js#L17
- Building the Web Speech ponyfill factory with specific device
   - Modify https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/bundle/src/createCognitiveServicesSpeechServicesPonyfillFactory.js#L18
   - Around line 19, you will need to pass your `audioConfig` object. And it will hit [`SpeechServices.js:17`](https://github.com/compulim/web-speech-cognitive-services/blob/master/packages/component/src/SpeechServices.js#L17), then hit [`createSpeechRecognitionPonyfill:92`](https://github.com/compulim/web-speech-cognitive-services/blob/master/packages/component/src/SpeechServices/SpeechToText/createSpeechRecognitionPonyfill.js#L92)
   - Modify line 4, so the host of Web Chat can specify an `audioConfig` object
- Build a sample to show capability to select different `audioConfig` on-the-fly
   - Use `AudioConfig.fromMicrophoneInput(deviceId)` to create the `AudioConfig` object with a specific device, https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioConfig.ts#L38

[Enhancement]

**Comment by corinagum** [comment]
Sample: https://github.com/corinagum/audioconfig-to-ponyfill-webchat
PR incoming, though changes will not be usable until Speech SDK bug is fixed.

**Comment by compulim** [comment]
This is going to be fixed in Speech Services SDK of `@>=1.10.0`. For version `@<=1.9.1`, it didn't fix yet.

**Comment by compulim** [comment]
Re-opening until we bump SDK to 1.10.0.
