### ISSUE TITLE
Infinite loop when pressing the image upload button

### ISSUE THREAD

**Issue by jash101** [Microsoft/BotFramework-WebChat#249]
When the import/upload button besides the text input field is pressed, an infinite loop is initialised, disabling the user to escape the browse window.

**Comment by billba** [comment]
I'm sorry, I can't reproduce that on Safari or Chrome on my Mac. What loop exactly are you seeing go infinite? This button is really just an `<input type="file">` and none of our code is executed until the user selects a file.

**Comment by billba** [comment]
Closing for lack of reply. Happy to reopen this if I get a reproduceable case.
