### ISSUE TITLE
Invalid formats of DateTime fields are not defined in TemplateUsage: NotUnderstood 

### ISSUE THREAD

**Issue by hassidchen** [microsoft/BotFramework-WebChat#2502]
## Screenshots

![image](https://user-images.githubusercontent.com/57063922/67634763-ac565f00-f8c8-11e9-87d5-4a7f291b0d80.png)

## Version
link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css"

## Describe the bug

There are some invalid formats of DateTime that are not defined in TemplateUsage: NotUnderstood which makes the chat-bot crash.
Example:  "nd Oct 11:22 PM(UTC)".
If you will type "2nd Oct 11:22 PM(UTC)", the TemplateUsage will be: NotUnderstood, and the chat-bot will not crash.

## To Reproduce

1. Connect to the bot
2. Start Bot Framework Emulator or deploy web chat to a website
3. When inserting a DateTime field, type: "nd Oct 11:22 PM(UTC)"
4. See an error in Web Chat

## Expected behavior

The TemplateUsage should be "NotUnderstood" for all DateTime that is in invalid formats

[Bug]

**Comment by dmvtech** [comment]
Are you using LUIS or [Microsoft.Recognizers.Text](https://github.com/microsoft/Recognizers-Text/)? What language is your bot written in?

**Comment by hassidchen** [comment]
I am using LUIS, and the bot is written in C#.

**Comment by CoHealer** [comment]
@hassidchen do you still require assistance or shall we consider the issue resolved?

**Comment by dmvtech** [comment]
Closing as no action at this point. Please reopen as needed.
