### ISSUE TITLE
Host sample 23.a.hybrid-react-npm

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2510]
## Version

`master`

## Describe the bug

Sample `23.a.hybrid-react-npm` was added in PR #2509 but it lacked of hosting. We should host it.

That means, user reaching to https://microsoft.github.io/BotFramework-WebChat/samples/23.a.hybrid-react-npm will see the demo. We have hosted other `create-react-app` based samples. Look at `lerna.json` to get started.

## Expected behavior

A hosted demo of the sample.

[Bug]

**Comment by tdurnford** [comment]
Sample 17.b.clear-after-idle also needs to be hosted
