### ISSUE TITLE
Adaptive cards do not work with minimal bundle

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotFramework-WebChat#2529]
## Screenshots
![image](https://user-images.githubusercontent.com/10174566/67975944-51777d00-fbd2-11e9-932f-26ff421004a1.png)

## Version
4.6.0

## Describe the bug
After updating to 4.6.0 version the Adaptive card stopped working. 

**NOTE:**: Things are working fine when moved back to 4.5.3.

## Additional context

[Bug]

**Comment by compulim** [comment]
Are you using `/4.6.0/webchat.js` or `npm install botframework-webchat` to load Web Chat?

Are you loading with `webchat.js` or `webchat-minimal.js`?

**Comment by vikramdadwal** [comment]
The issue occurs when using `webchat-minimal.js` version of webchat. Things are working fine with `webchat.js`.

**Comment by tdurnford** [comment]
The [Minimal Bundle](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.a.getting-started-minimal-bundle#description) does NOT include Adaptive Cards, Cognitive Services, or Markdown-It dependencies.

**Comment by oswaldozapata** [comment]
I am using https://cdn.botframework.com/botframework-webchat/4.14.1/webchat-minimal.js and adaptive cards does not works, for markdown we can use markdown-It but for adaptive cards there is not any documentation talking about how to support adaptive cards while using webchat-minimal.js, so, can we get working adaptive cards using minimal version or should we change to use the full version webchat.js instead?

**Comment by corinagum** [comment]
@oswaldozapata my recommendation is to use the full bundle. Which packages are you focused on not using?
