### ISSUE TITLE
suggestedActionBoarderWidth not working as expected in 4.6.0

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotFramework-WebChat#2531]
## Screenshots
![image](https://user-images.githubusercontent.com/10174566/67991298-02434380-fbf6-11e9-9d32-7e80b5dde0ca.png)

![image](https://user-images.githubusercontent.com/10174566/67991315-07a08e00-fbf6-11e9-83ca-d69e271f228f.png)

## Version
4.6.0

## Describe the bug
We were using  suggestedActionBorder: `solid 1px #c6c6c6`, property earlier and the suggested action Border was displaying with thin border as shown above with 4.5.3.
But with new property of "suggestedActionBoarderWidth" we are not able to get the required thickness. As you can see the Border thickness has increased now as shown above with 4.6.0. We are using `suggestedActionBoarderWidth: 0`. Please assist.

## Additional context

[Bug]

**Comment by corinagum** [comment]
@vikramdadwal based off of your submission, it looks like `suggestedAction*Border*Width` is misspelled.

Spelled correctly, the prop functions as expected: 

```
        const styleOptions = {
          bubbleBackground: 'rgba(0, 0, 255, .1)',
          bubbleFromUserBackground: 'rgba(0, 255, 0, .1)',
          suggestedActionBorderWidth: 5
        };
```
![image](https://user-images.githubusercontent.com/14900841/67992740-27868080-fbfb-11e9-8579-1350b55a3ca6.png)

**Comment by tdurnford** [comment]
It looks like `suggestedActionBorderWidth` is misspelled in the default style options. It's fine everywhere else.

**Comment by vikramdadwal** [comment]
@tdurnford  My bad, its working fine.
