### ISSUE TITLE
I'm using Direct line channel with webchat-es5.js but still does not work on IE 11

### ISSUE THREAD

**Issue by waleedabuyahia** [microsoft/BotFramework-WebChat#2558]
Below is my HTML
<!DOCTYPE html>
<html>
<head>
    <title>My Company Name Chatbot</title>
    <link href="ChatBootStyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div id="webchat" role="main" style="min-height:850px;min-width:500px;width:100%; white-space:normal;height:850px;" ></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <script>
       

        const styleSet = window.WebChat.createStyleSet({
            botAvatarInitials: 'Roze',
            userAvatarInitials: 'BP',
            rootHeight: '100%',
            hideUploadButton: true,
            rootWidth: '50%',
            bubbleFromUserBackground: 'rgba(0, 255, 0, .1)'
           
        });

        styleSet.textContent = {
            ...styleSet.textContent,
            fontFamily: "'Comic Sans MS', 'Arial', sans-serif",
            fontWeight: 'bold'
        };

         window.WebChat.renderWebChat(
             {
                
               directLine: window.WebChat.createDirectLine({
                   secret: 'MyKey'
               }),
                 sendTypingIndicator: true,
               
                 styleSet
            },
            document.getElementById('webchat')
         );
    </script>
</body>
</html>

**Comment by tdurnford** [comment]
IE 11 does not support the spread operator. Use `Object.assign` instead.

```javascript
styleSet.textContent = Object.assign(styleSet.textContent, {
    fontFamily: "'Comic Sans MS', 'Arial', sans-serif",
    fontWeight: 'bold'
});
```

**Comment by waleedabuyahia** [comment]
I have changed it to Object.Assign but still it is not working.

<!DOCTYPE html>
<html>
<head>
    <title>XXXXXChatbot</title>
    <link href="ChatBootStyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div id="webchat" role="main" style="min-height:850px;min-width:500px;width:100%; white-space:normal;height:850px;" ></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <script>
       

        const styleSet = window.WebChat.createStyleSet({
            botAvatarInitials: 'Roze',
            userAvatarInitials: 'BP',
            rootHeight: '100%',
            hideUploadButton: true,
            rootWidth: '50%',
            bubbleFromUserBackground: 'rgba(0, 255, 0, .1)'
           
        });

        styleSet.textContent = Object.assign(styleSet.textContent, {
            fontFamily: "'Comic Sans MS', 'Arial', sans-serif",
            fontWeight: 'bold'
        });


         window.WebChat.renderWebChat(
             {
                
               directLine: window.WebChat.createDirectLine({
                   secret: 'XXXXXX'
               }),
                 sendTypingIndicator: true,
               
                 styleSet
            },
            document.getElementById('webchat')
         );
    </script>
</body>
</html>

**Comment by waleedabuyahia** [comment]
Same result: 

<!DOCTYPE html>
<html>
<head>
    <title>Chatbot</title>
    <link href="ChatBootStyleSheet.css" rel="stylesheet" />
</head>
<body>
    <div id="webchat" role="main" style="min-height:850px;min-width:500px;width:100%; white-space:normal;height:850px;" ></div>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <script>
       

        const styleSet = window.WebChat.createStyleSet({
            botAvatarInitials: 'Roze',
            userAvatarInitials: 'BP',
            rootHeight: '100%',
            hideUploadButton: true,
            rootWidth: '50%',
            bubbleFromUserBackground: 'rgba(0, 255, 0, .1)'
           
        });

        styleSet.textContent = Object.assign(styleSet.textContent, {
            fontFamily: "'Comic Sans MS', 'Arial', sans-serif",
            fontWeight: 'bold'
        });


         window.WebChat.renderWebChat(
             {
                
               directLine: window.WebChat.createDirectLine({
                   secret: 'Key'
               }),
                 sendTypingIndicator: true,
               
                 styleSet: styleSet
            },
            document.getElementById('webchat')
         );
    </script>
</body>
</html>

**Comment by waleedabuyahia** [comment]
I'm getting the following error:

![image](https://user-images.githubusercontent.com/31237675/68232735-bfa1b280-ffcb-11e9-95bc-c4727e09ca2e.png)

**Comment by tdurnford** [comment]
This works fine for me.

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Full-featured bundle with ES5 polyfills</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }
      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      const styleSet = window.WebChat.createStyleSet({
        botAvatarInitials: 'Roze',
        userAvatarInitials: 'BP',
        rootHeight: '100%',
        hideUploadButton: true,
        rootWidth: '50%',
        bubbleFromUserBackground: 'rgba(0, 255, 0, .1)'
      });

      styleSet.textContent = Object.assign(styleSet.textContent, {
          fontFamily: "'Comic Sans MS', 'Arial', sans-serif",
          fontWeight: 'bold'
      });

      window.WebChat.renderWebChat(
        {
          directLine: window.WebChat.createDirectLine({
            secret: '<WEB_CHAT_SECRET>'
          }),
          styleSet: styleSet
        },
        document.getElementById('webchat')
      );

      document.querySelector('#webchat > *').focus();
    </script>
  </body>
</html>
```

**Comment by waleedabuyahia** [comment]
It might be some setting in my explorer. do you have any idea which settings I have to check?

**Comment by waleedabuyahia** [comment]
I found the issue, My IE was set to use IE compatibility, once I disable it it is working fine now.
