### ISSUE TITLE
WebChat Not Working for IE11 with New Error

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/BotFramework-WebChat#2561]
## Screenshots

Attached.

## Version

Latest. See attached code.

## Describe the bug

On IE11 we are implementing the changes recommended in #1760. However, we are getting an error that nobody has reported yet

uncaught at anynymous SecurityError
SCRIPT5022: SecurityError
webchat-es5.js (1,123143)

## To Reproduce

I am attaching sample HTM file.

## Expected behavior

No error. It works correctly in Chrome.

## Additional context

[Bug]

**Comment by dkonyayev** [comment]
<img width="394" alt="webchat-error" src="https://user-images.githubusercontent.com/15344498/68245234-95a8ba00-ffe4-11e9-8a71-9ed58fd7ec9d.PNG">

Sample Code:
<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <script src="https://unpkg.com/markdown-it@8.4.2/dist/markdown-it.min.js"></script>
    <script src="https://unpkg.com/simple-update-in/dist/simple-update-in.production.min.js"></script>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
    <style>

        html, body {
            height: 100%
        }

        body {
            margin: 0
        }

        #webchat {
            border-left: solid 2px #007abc;
            border-right: solid 2px #007abc;
            border-bottom: solid 2px #007abc;
            border-top: solid 50px #007abc;
            height: 89%;
            width: 98%;
            border-radius: 5px;
        }
    </style>


</head>
<body>
    <div id="webchat" role="main"></div>
    
    <script>
        function piggybackMiddleware(store) {
            return function (next) {
                return function (action) {
                    if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
                        // The channelData submitted here is very similar to HTTP cookies and vulnerable to forgery attack.
                        // Make sure you use signature to protect it and verify the signature on the bot side.
                        // To minimize unexpected behaviors, we recommend to treat the "action" object as if it is immutable.
                        // We use simple-update-in package to update "action" with partial deep cloning.
                        action = window.simpleUpdateIn(action, ['payload', 'activity', 'channelData', 'email'], function () { return 'johndoe@example.com' });
                    }
                    return next(action);
                }
            }
        }


        try {
                        var userId = uuidv4();

                        console.log("Invoking bot application with userId: " + userId);


                        const markdownIt = window.markdownit({ html: true, linkify: true, typographer: true });
                        const groupTimestamp = 100000;
                        const styleOptions = {
                            hideUploadButton: true,
                            paddingRegualar: 10,
                            paddingWide: 20,

                            bubbleFromUserTextColor: '#333333',
                            bubbleFromUserBackground: '#e7e7eb',
                            bubbleTextColor: '#787c7f',
                            bubbleBackground: '#ddeef9',
                            bubbleBorderRadius: 4,
                            bubbleFromUserBorderRadius: 4,
                            avatarSize: 40,
                            botAvatarSize: 40,
                            userAvatarBackgroundColor: '#FFFFFF',
                            botAvatarBackgroundColor: '#FFFFFF',
                            botAvatarImage: 'https://image.flaticon.com/icons/svg/206/206864.svg',
                            botAvatarInitials: 'BF',
                            userAvatarImage: 'https://cdn3.iconfinder.com/data/icons/flat-pro-user-management-set-4/32/user-profile-512.png',
                            userAvatarInitials: 'NA',
                            sendBoxButtonColor: '#0061a0',
                            sendBoxBorderTop: 'solid 1px #007abc',
                            subtle: 'none',
                        };

                        const store = window.WebChat.createStore(
                            {},
                            piggybackMiddleware
                        );

                        
                        window.WebChat.renderWebChat(
                            {
                                directLine: window.WebChat.createDirectLine({ "token": "<token>" }),
                                renderMarkdown: markdownIt.render.bind(markdownIt),
                                groupTimestamp: groupTimestamp,
                                styleOptions: styleOptions,
                                userID: userId,
                                store: store
                            },
                            document.getElementById('webchat')
                        );

                        store.dispatch({
                            type: 'WEB_CHAT/SET_SEND_BOX',
                            payload: { text: 'channel-data' }
                        });

                        document.querySelector('#webchat > *').focus();
        }
        catch (e) {
            console.log("Unknown error occured while getting the meta data for the selected entity" + e);
        }

        function uuidv4() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

    </script>
</body>
</html>

**Comment by compulim** [comment]
Will look at this later today or tomorrow.

Before jumping into it, can you try restarting IE11? Also make sure `iexplore.exe` in Task Manager is gone.

I remember when we do development on IE11 for a few times, we saw "SecurityError" and it mysteriously gone after restarting IE11.

BTW, thanks for the code, it looks complete and easy-to-host on our side. 😉

**Comment by dkonyayev** [comment]
I restarted the IE11 and it seems to be working now. My goal with this code was to post an event to trigger bot greeting message. That doesn't work, but I will open a separate case for this.
