### ISSUE TITLE
How to withdraw the wrong message?

### ISSUE THREAD

**Issue by handsomeyao77** [microsoft/BotFramework-WebChat#2563]
Hi Team,

Does the WebChat have an api to withdraw the message if sending by mistake?

Or is there a workaround for this scenario?

Expected: the message sent in 2mins can be recalled.

Thanks.

**Comment by corinagum** [comment]
Hi @handsomeyao77, 

There is no way to withdraw a message already sent to the bot in Web Chat. If desired, you can programmatically remove a message from the UI by using activity middleware (take a look at our samples) to add new buttons/UI that will delete an activity from the screen. At the moment deleting or modifying activities is not supported in Web Chat/DirectLine, but is an [item in our Backlog](https://github.com/microsoft/BotFramework-WebChat/issues/2426).

This would mean that if you do implement the UI to delete a message, it would disappear from the transcript, but still have been sent to the bot and will not be redacted.
