### ISSUE TITLE
Add lists (<ul> elements) to defaultStyleOptions

### ISSUE THREAD

**Issue by bpz** [microsoft/BotFramework-WebChat#2564]
## Feature Request

We have a chatbot that displays some **Adaptive Cards** which uses bullets inside them; they look like this using the [card designer](https://adaptivecards.io/designer/):

![image](https://user-images.githubusercontent.com/4050508/68462947-efd89380-020d-11ea-844f-dd317be32959.png)

where the json of the card is:
```json
{
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "Card Title",
            "size": "Large",
            "weight": "Bolder",
            "id": "Title"
        },
        {
            "type": "TextBlock",
            "text": "- This is the first element\n- This is the second element",
            "size": "default",
            "wrap": true,
            "id": "Body"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

And in several channels they look pretty similar.

However, when using WebChat, the resulting html produced by the channel translates the bullets to `<ul>` elements with a fixed style that includes a left padding but no right one. As a result of that, part of the text of the elements of the list are hidded behind the card margin.

![image](https://user-images.githubusercontent.com/4050508/68465751-5a400280-0213-11ea-864a-2c01685d4c89.png)

### What we've done

To fix that, we are editing our CSS even if we know it's not a recomended practice as it's referencing a class name. 

```CSS
div.ac-textBlock>ul>li {
    padding-right: 40px;
}
```
Explanation: this is adding a right padding to the `<li>` elements inside `<ul>` elements that are inside block text in adaptive cards.

### Suggestion

I think it could be a good idea to make the `<ul>` elements have their own params in defaultStyleOptions, so they can have an editable style and therefore avoid this situation.

**Comment by corinagum** [comment]
Hi @bpz, are you using Adaptive Cards for your lists? This is my assumption based of your 'Card Title' above. This is technically an Adaptive Cards issue, and is not controlled by Web Chat. 

I was able to use Fact Sets in AC to create custom bullets, like so:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "FactSet",
      "facts": [
        {
          "title": "•",
          "value": "Value 1"
        },
        {
          "title": "•",
          "value": "Value 2"
        },
        {
          "title": "•",
          "value": "Value 3"
        },
        {
          "title": "•",
          "value": "Value 5"
        }
      ]
    }
  ]
}
```

Could you share how you're editing your CSS? Have you had any problems with this method?

**Comment by compulim** [comment]
I think having the text clipped is bad. We should look at why Web Chat bubble clipped the content of an AC card with bullets.

On the other hand, unfortuantely, Adaptive Cards offer no CSS support. So, the only way is to customize AC Host Config and pass it to Web Chat.

**Comment by bpz** [comment]
Hi, @compulim 

The clipping is happening when displaying several cards like the one I mentioned in a carrousel. So the size of the cards is reduced and you can notice this padding issue. You have it at any card size, but with a smaller card you can notice it easier.

![image](https://user-images.githubusercontent.com/4050508/68465751-5a400280-0213-11ea-864a-2c01685d4c89.png)

**Comment by bpz** [comment]
After editing my first comment and adding more info in another comment, I don't really know what can be the solution to this issue, or wheter if it can be solved by Adaptive Cards' or by WebChat.

**Comment by tdurnford** [comment]
It looks like @bpz is using markdown to create the unordered lists, so I think it would have to be a customization to the [Markdown-it](https://github.com/markdown-it/markdown-it) renderer used by both Web Chat and Adaptive Cards. I don't see a great way to do this through style options.

**Comment by corinagum** [comment]
@bpz is using a fact set in Adaptive Cards a viable workaround for you, instead of using Markdown in the Adaptive Cards? It looks like AC has some inconsistencies in rendering markdown so you may want to avoid the AC/Markdown combo altogether. 

I'm going to remove the Investigate label and keep this in the Backlog as a discussion item, but as of right now I don't see this becoming an action item for Web Chat.

**Comment by bpz** [comment]
I understand, @corinagum

For our case, the FactSet is not a solution as that would imply knowing first how many items would have the card text, but I can see it can be a solution for other scenarios.

**Comment by cwhitten** [comment]
Hello. As stated earlier in the thread, we have no known means to support this scenario. Closing.
