### ISSUE TITLE
Need audible equivalent for typing indicator sent by bot

### ISSUE THREAD

**Issue by mmalaiarasan-conga** [microsoft/BotFramework-WebChat#2567]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently when a user uses speech input method - webchat speaks the response sent from the bot. But the typing indicator is not marked a speakable activity and it is ignored when a bot sends a typing indicator to user in a voice conversation.  

**Describe the suggestion or request in detail**

For a speech enabled conversation, instead of ignoring incoming typing indicators from bot, there can be a customizable audible equivalent (some music) that can be played to user until the typing indicator is turned off. 

**Describe alternatives you have considered**
Tried sending an audio attachment from bot instead of typing indicators in case of a voice conversation. But the purpose is not solved because of the UI and the fact that the audio does not stop on the next incoming message from bot. 

**Additional context**

if we want to use webchat to have a true voice conversation without the user having to look at the screen, this is absolutely necessary. 

[Enhancement]

**Comment by corinagum** [comment]
I think there are a number of workarounds you can consider without needing wait for a Web Chat update.

1. On the bot side, send an audible typing indicator *with* the typing activity or as a part of the group. On a high level:
   - Send an activity with the speak property set to "Please wait, calculating"
   - Send  the typing activity
   - Repeat as necessary until bot's final response is ready
You could also try out whether or not a speak property on a typing activity will work, though I suspect it will not.
2. On the client side, use Web Chat's middleware samples to create a wrapper around a typing activity. This wrapper will play the designated sound, and will repeat whenever a new typing activity is received. Alternatively, you can add logic that will only play the sound on the first received typing indicator in a group.

I can see this being implemented as a sample for Web Chat, but as it is I don't think this is something that our team would immediately incorporate into the main project. I will add this as a sample request to our backlog, and if any customers are inclined, please feel free to give a stab at this (and share here!)

**Comment by ManjulaMalaiarasan** [comment]
@corinagum thank you for the response, 
- speak property on typing indicator is ignored. 
- send a msg activity with speak text like 'please wait' - will not work efficiently since sometimes typing indicators show up just for a second, while sometimes up to a few tens of seconds and sending the text and reading it aloud for smaller indication will only delay our actual response. 
- I am trying to write a wrapper over typing indicators and not very successful so for. 

Having a sample for this will be very useful

Thank you

**Comment by cwhitten** [comment]
Hello. We'll close this as we have no plans to implement a sample that demonstrates this.  See https://github.com/microsoft/BotFramework-WebChat/issues/2567#issuecomment-550577922 for detail on how to achieve this.
