### ISSUE TITLE
Need an alternative way to Send Text to the Text Bot and Submit

### ISSUE THREAD

**Issue by Adityagrao** [microsoft/BotFramework-WebChat#2569]
## Feature Request

I am using an external form to get the user input and sending that text to the Webchat Textbox and submitting the data 

I want a way to trigger the submit button (Enter button) after the form data is loaded to the text box 

I am using  
`document.getElementsByClassName("css-16qahhi css-n2zczk css-4ix4a1 css-1fe8kfc")[0][0].setAttribute("value", "1231231hjnh")`
and 
`document.getElementsByClassName("css-16qahhi css-n2zczk css-4ix4a1 css-1fe8kfc")[0][0].value= "1231231hjnh"`

to Set the attribute value in the HTML and show the value in the textbox 

### Issues facing 

- I am not able to submit the data to the chat window 

- After sending that text data, even if I click on the text and hit enter, the data is not submitted, it only works if I append more data and then hit Enter.

**Comment by tdurnford** [comment]
You can create a custom store and dispatch a set send box action to Web Chat's Redux Store. For more details take a look at the code snippet below and the [Custom Redux Actons](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/11.customization-redux-actions) Web Chat sample. 
```javascript
const store = window.WebChat.createStore();

function onClick() {
  store.dispatch({
    type: 'WEB_CHAT/SET_SEND_BOX',
    payload: {
      text: 'Hello World!'
    }
  });
}

(async function() {
const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
const { token } = await res.json();

window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token }),
    store
  },
  document.getElementById('webchat')
);
```

**Comment by Adityagrao** [comment]
@tdurnford , I could do the same with my approach also, my issue is with submitting to the BOT

**Comment by Adityagrao** [comment]
@tdurnford , My issue is submitting to the Bot, I was able to send the message to the text box via my approach also

**Comment by tdurnford** [comment]
You can use the `'WEB_CHAT/SEND_MESSAGE'` action instead of the `'WEB_CHAT/SET_SEND_BOX'` action.
