### ISSUE TITLE
WebChat Not Displaying UTF-8 Characters

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/BotFramework-WebChat#2570]
## Screenshots

see attached
<img width="230" alt="webchat-error-01" src="https://user-images.githubusercontent.com/15344498/68400888-c6086980-0146-11ea-9d96-5d3d73456e15.PNG">

## Version

Latest

## Describe the bug

Our Bot is multi-lingual and user can switch between English and Spanish. However, the Webchat control does not display special characters correctly.

Our <head> does contain the following meta-tags
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

## To Reproduce

Have BotFramework respond with message containing special characters. For example "Ahora estás en el menú principal."

## Expected behavior

Characters are properly displayed.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Hi @dkonyayev, unfortunately I am not able to reproduce your problem: 

![image](https://user-images.githubusercontent.com/14900841/68413777-c5220880-0143-11ea-889d-2e28ca03aab3.png)

Could you provide details of your activity to see if we can figure out what the problem is? Please also share your Web Chat app's code so we can take a look at that as well.

**Comment by dkonyayev** [comment]
@corinagum Thanks, we figured out the issue. We are loading bot responses from JSON file and did not specify correct encoding, so our responses contained incorrect characters even before they got to WebChat.

**Comment by corinagum** [comment]
Great, thanks for reporting back. Glad you figured it out. :)

**Comment by rvallireply** [comment]
Hello,
I have the same problem, how did you solve this? how/where do you specify the encoding for the json?
thanks

**Comment by dkonyayev** [comment]
In our case we load our bot expressions from JSON file, and we were reading that JSON file with incorrect encoding. Had nothing to do with bot. However, the web page where webchat is hosted must have meta tags for UTF8

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

**Comment by rvallireply** [comment]
I set those meta in head, but nothing changes. The question marks appears anyway.
Like you we have bot responses in JSON files, we have two languages too, one is english and the other italian with accented letters. How/where do we correct the encoding?

**Comment by dkonyayev** [comment]
Here's roughly what I am doing. The encoding part is what we were missing.

using (var stream = GetType().Assembly.GetManifestResourceStream(resource))
                {
                    using (var reader = new StreamReader(stream, **Encoding.GetEncoding("iso-8859-1"))**)
                    {
                        json = reader.ReadToEnd();

                      
                    }
                }

**Comment by rvallireply** [comment]
that's actually quite unrelated with our code...thanks anyway

**Comment by jane-bolton** [comment]
For anyone coming across this issue now, encoding the JSON in VS2019 solved the issue for me: [Japanese character in AdaptiveCard Bot Framework V4](https://stackoverflow.com/questions/56320701/japanese-character-in-adaptivecard-bot-framework-v4). I was having trouble with Spanish, but encoding as Codepage 65001 did the trick. It works in the Bot Emulator as well as in Direct Line / Web Chat.

![image](https://user-images.githubusercontent.com/69269995/114570429-70899380-9c3b-11eb-9792-fb23149bc686.png)
