### ISSUE TITLE
DirectLine instance remains active after end() called

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#258]
I'm wondering now best to shutdown a BotChat.DirectLine instance. When I call botConnection.end(), it will continue to try sending failed messages. I'm using this in polling mode, so I can't say what else might be active in a websocket scenario.

**Comment by eanders-MS** [comment]
It also continues to poll after end() is called.

**Comment by billba** [comment]
Thanks. I think I know what's missing.

**Comment by billba** [comment]
To be clear, calling end() is the right thing to do to shut down a DirectLine instance.
