### ISSUE TITLE
Bot name or users name not shown bellow messages

### ISSUE THREAD

**Issue by alokraj68** [microsoft/BotFramework-WebChat#2581]
## Version
Latest version From CDN 4.6

## Describe the bug

In V3 the time stamp indicator had a prefix showing The bot name for the message and user name for messages from the user. This seems omitted in V4. Now only the time Relative or non-relative is shown.

## To Reproduce

1. Go to any web chat
2. Send a message
3. See the behavior of timestamp.

## Expected behavior

The bot name and user names should be prefixed before the time stamp. There should also be an option through default options to control this behavior.

## Additional context

This a V3 to V4 upgrade issue.

[Bug]

**Comment by tdurnford** [comment]
Duplicate https://github.com/microsoft/BotFramework-WebChat/issues/2555
