### ISSUE TITLE
Ability to set voice with Web Speech API in webSpeechPonyfillFactory

### ISSUE THREAD

**Issue by pradeeprajendran** [microsoft/BotFramework-WebChat#2592]
Can we have an updated webSpeechPonyfillFactoryto allow us to set lang, pitch, voice, etc? 

I am using example  https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.f.hybrid-speech **however** I am using WebSpeechAPI for speechSynthesis as well

**Comment by axelsrz** [comment]
@corinagum can you take a look at this?

**Comment by compulim** [comment]
@pradeeprajendran you should use SSML to set the `lang`, `pitch`, `rate`, and `volume`. You can refer to this [Speech Synthesis Markup Language article](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup) on how to set it up. You should pass it as `speak` property to the activity sent from the bot.

For `voice`, you can refer to this [select voice sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.g.select-voice).
