### ISSUE TITLE
sendTimeOut not respected

### ISSUE THREAD

**Issue by leolorenzoluis** [microsoft/BotFramework-WebChat#2594]
## Screenshots
<img width="850" alt="Screen Shot 2019-11-13 at 10 41 04 PM" src="https://user-images.githubusercontent.com/15150044/68825029-bf0db980-0666-11ea-99c1-cbc15e8ffb2c.png">

## Version
4.6.0

## Describe the bug
When I upload an attachment and network is slow. The send time out is not respected. I explicitly cloned and build from tag 4.6.0 and explicitly change timeouts from 20000 to 30000, but for some reason it is still being cancelled out by the client ~20 seconds

## To Reproduce

1. Throttle network to make it slower
2. Upload attachment regardless if it's 4MB.
3. Watch network on client and see it being cancelled at ~20 every time.

## Expected behavior

It should respect the sendtimeout that is stored in the state

## Additional context

https://github.com/microsoft/BotFramework-DirectLineJS/blob/6ffe60a09a5a6311a55f5feaa783b23362f04a63/src/directLine.ts#L367

Is there a way to populate this as a config? Pass in the sendTimeOut property to the DirectJS?
https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/bundle/src/createDirectLine.js#L23

I envision something like this
```
directLine: window.WebChat.createDirectLine({
              timeout: 30000,
              domain: 'url
            })
```

**Comment by tdurnford** [comment]
@leolorenzoluis Where did you change the timeout value? It looks like you can set the `sendTimeout` value already through Web Chat's props.

```javascript
window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token }),
    sendTimeout: 30000
  },
  document.getElementById('webchat')
);
```

**Comment by compulim** [comment]
BTW, #1265 is the bug to bring another timeout value just for file upload.

**Comment by leolorenzoluis** [comment]
@tdurnford This is when initializing WebChat with DirectLine. The sendTimeout is not used when calling DirectLine. I think this should be configurable by the devs.

**Comment by leolorenzoluis** [comment]
@compulim I think that's 120 seconds vs 20 seconds is subjective. We have to consider when clients have a slow bandwidth. 120 seconds is not enough if it's in a dial up connection or in a very slow environment. There's two timeout places that are watche. One in webchat an one in directline. `sendTimeout` is only used in webchat but not propagated in DirectLine which does the ajax calls to the DirectLine.

**Comment by compulim** [comment]
We added new `styleOptions.sendTimeout` and `styleOptions.sendTimeoutForAttachments`. You can look at it here, https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/defaultStyleOptions.js#L118.

IMO, DirectLineJS should use browser timeout, i.e. 120s most of the time.
