### ISSUE TITLE
ChannelData Is Empty on Server Side

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/BotFramework-WebChat#2600]
## Screenshots

n/a

## Version

lastest

## Describe the bug

We are posting an event via DirectLine with channeldata. However, the channel data is empty on the bot side. I feel like I am missing something very basic but I cannot figure out what it is.

## To Reproduce

CLIENT-SIDE
```
      // create directLine variable
                    var dl = window.WebChat.createDirectLine({ "token": tokenResponse });

                    // render webchat control
                    window.WebChat.renderWebChat(
                        {
                            directLine: dl,
                            renderMarkdown: markdownIt.render.bind(markdownIt),
                            groupTimestamp: groupTimestamp,
                            styleOptions: styleOptions,
                            userID: userId
                        },
                        document.getElementById('webchat')
                    );

                    // post activity to start conversation and trigger welcome message
                    var activity = {
                        from: {
                            id: userId
                        },
                        name: 'startConversation',
                        type: 'event',
                        value: '',
                        channelData: {
                            "personId": userId,
                            "environment": window.location.host,
                            "usercontext": payloadUserContext,
                            
                        }
                    };
                    dl.postActivity(activity).subscribe(function (id) {
                        if (console) {
                            console.log('"trigger requestWelcomeDialog" sent');
                        }
                    });
```

SERVER-SIDE
``` 
   public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default)
        {
            _logger.LogDebug(turnContext.Activity.ChannelData); // always empty
        }
```
## Expected behavior

turnContext.Activity.ChannelData should contain object with data.

## Additional context

[Bug]

**Comment by dkonyayev** [comment]
Any input?

**Comment by axelsrz** [comment]
@compulim could you take a look at this one?

**Comment by stevkan** [comment]
Consider using Web Chat's store to update an activity when posted, as demonstrated in the [15.a.backchannel-piggyback-on-outgoing-activities](https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/15.a.backchannel-piggyback-on-outgoing-activities/index.html) sample.

_**Please note:** There are security considerations when posting potentially sensitive data from the page to the bot.  As mentioned [here](https://github.com/microsoft/BotFramework-WebChat/blob/c577bf70ee70b1f3ea8ffb9c514e11766228373f/samples/15.a.backchannel-piggyback-on-outgoing-activities/index.html#L45), this can open you up to forgery attacks._

To send data back to the bot from the page, first add this script to your page:

```html
<!-- We are using simple-update-in package to simplify demo code. -->
<script src="https://unpkg.com/simple-update-in/dist/simple-update-in.production.min.js"></script>
```

Next, create the Web Chat store and filter on the action type for `DIRECT_LINE/POST_ACTIVITY` actions and pass in your data:

```js
const store = window.WebChat.createStore( {}, ( { dispatch } ) => next => async action => {
  if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
    // Mocking data to be sent
    const userId = 'xyz789';
    const payloadUserContext = action.payload;

    action = window.simpleUpdateIn(
      action,
      ['payload', 'activity', 'channelData'],
      () => ({
        'personId': userId,
        'environment': window.location.host,
        'userContext': payloadUserContext
      })
    )
  }
  return next ( action );
} );
```

Lastly, pass the store as a property in `renderWebChat()`:

```js
window.WebChat.renderWebChat({
  directLine: window.WebChat.createDirectLine({ token }),
  store
}, document.getElementById('webchat'));
```

This does append the data to every outgoing message from the page to the bot. You will need to alter the code to fit your needs, if you only want the data sent with specific activities.
Hope of help!

**Comment by tdurnford** [comment]
@dkonyayev It looks like you are trying to trigger a Welcome message from the bot. I would recommend looking at the [Backchannel Welcome Message Sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.d.backchannel-send-welcome-event) which shows how to trigger welcome message with custom data from the client. I would also recommend looking at https://github.com/microsoft/BotFramework-WebChat/issues/2120#issuecomment-516056614 for more details on how to properly trigger a welcome message from Web Chat.

**Comment by dkonyayev** [comment]
So I did a little more testing. I start to get channel data after the bot sends at least 1 message back to the client. In my code I check for channeldata in OnMembersAddedAsync function, which in turn is activated by DirectLine.PostActivity (as per another example on GitHub). In this function I determine if I know who the user is (based on channeldata information), or if I need to ask them for their name. 

Here's my entire code which you can run as a test.

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"></script>
    <script src="https://unpkg.com/markdown-it@8.4.2/dist/markdown-it.min.js"></script>
    <script src="https://unpkg.com/simple-update-in/dist/simple-update-in.production.min.js"></script>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
    <style>


        html, body {
            height: 100%
        }

        body {
            margin: 0
        }

        #webchat {
            border-left: solid 2px #007abc;
            border-right: solid 2px #007abc;
            border-bottom: solid 2px #007abc;
            border-top: solid 50px #007abc;
            height: 89%;
            width: 98%;
            border-radius: 5px;
        }
    </style>


</head>
<body>
    <div id="webchat" role="main"></div>

    <script>

        try {
            // get unique userId
            var userId = uuidv4();


            console.log("Invoking bot application with userId: " + userId);

            //console.log(image);
            // setup webchat options
            const markdownIt = window.markdownit({ html: true, linkify: true, typographer: true });
            const groupTimestamp = false;
            const styleOptions = {
                hideUploadButton: true,
                paddingRegualar: 10,
                paddingWide: 20,

                bubbleFromUserTextColor: '#333333',
                bubbleFromUserBackground: '#e7e7eb',
                bubbleTextColor: '#787c7f',
                bubbleBackground: '#ddeef9',
                bubbleBorderRadius: 4,
                bubbleFromUserBorderRadius: 4,
                avatarSize: 40,
                botAvatarSize: 40,
                userAvatarBackgroundColor: '#FFFFFF',
                botAvatarBackgroundColor: '#FFFFFF',
                botAvatarImage: 'https://image.flaticon.com/icons/svg/206/206864.svg',
                botAvatarInitials: 'BF',
                userAvatarInitials: 'NA',
                sendBoxButtonColor: '#0061a0',
                sendBoxBorderTop: 'solid 1px #007abc',
                subtle: 'none',
            };

            // create directLine variable
            var dl = window.WebChat.createDirectLine({ "token": <token> });

            const store = window.WebChat.createStore({}, ({ dispatch }) => next => async action => {
                if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
                    // Mocking data to be sent
                    const userId = 'xyz789';
                    const payloadUserContext = "some payload conext";

                    action = window.simpleUpdateIn(
                        action,
                        ['payload', 'activity', 'channelData'],
                        () => ({
                            'personId': userId,
                            'environment': window.location.host,
                            'userContext': "Store user context"
                        })
                    )
                }
                return next(action);
            });

            // render webchat control
            window.WebChat.renderWebChat(
                {
                    directLine: dl,
                    renderMarkdown: markdownIt.render.bind(markdownIt),
                    groupTimestamp: groupTimestamp,
                    styleOptions: styleOptions,
                    userID: userId,
                    store
                },
                document.getElementById('webchat')
            );

            // post activity to start conversation and trigger welcome message
            var activity = {
                from: {
                    id: userId
                },
                name: 'startConversation',
                //type: 'event',
                type: 'event',
                value: '',
                channelData: {
                    "personId": userId,
                    "environment": window.location.host,
                    "userContext": "directline user context",

                }
            };
            dl.postActivity(activity).subscribe(function (id) {
                if (console) {
                    console.log('"trigger requestWelcomeDialog" sent');
                }
            });
            
            // set focus on webchat control
            document.querySelector('#webchat > *').focus();

            appLoaded = true;
        }
        catch (e) {
            console.log("Unknown error occured while getting the meta data for the selected entity" + e);
        }

        function IsJsonString(str) {
            try {
                JSON.parse(str);
            } catch (e) {
                return false;
            }
            return true;
        }

        function uuidv4() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

    </script>
</body>
</html>

**Comment by tdurnford** [comment]
The backchannel welcome event you are sending with the `postActivity` method will trigger the `onEvent` handler in the bot not `onMembersAdded`.

**Comment by dkonyayev** [comment]
Ok, I see it now. IT was confusing because Emulator and DirectLine trigger events differently. I moved my welcome code into OnEvent, and for specific Event Name I process user context.
