### ISSUE TITLE
OnMembersAddedAsync method is not getting triggered when someone is added to a chat in the Web Chat channel

### ISSUE THREAD

**Issue by getangar** [microsoft/BotFramework-WebChat#2601]
## Version
4.6.2

## Describe the bug
I followed the MS Tutorial: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk and what I have seen is that while in the Web Chat Test & Bot Framework Emulator everything works as expected, once published to Azure, the OnMembersAddedAsync method is not triggered when someone is added to a chat in the Web Chat channel

## To Reproduce

1. In VS 2019 create a new EchoBot "sample"
2. Compile and test it with Bot Framework Emulator
3. Publish the project in Azure as described here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk
4. Test it with Web Chat Test => OK
5. Create an HTML file (or if you prefer a .NET/.NET Core web app) and add the iFrame to reach the Chat:

<iframe id="iFrameChat" style="height:480px; width:402px" src="https://webchat.botframework.com/embed/NTTDATABot-BotRegistration?s=YOUR_SECRET_HERE"></iframe>

6. Publish the web app in Azure if you want (but it's not necessary)
7. Open the HTML in a Browser, the chat is loaded but nothing happens until you type something (the OnMembersAddedAsync is not triggered)
8. One you type something and press enter, the OnMessageActivityAsync is triggered producing an unexpected behavior

## Expected behavior

You expect that once you reach the Bot App, the first method triggered of your project is OnMembersAddedAsync (where I put the welcome message btw).
## Additional context

[Bug]

**Comment by tdurnford** [comment]
@getangar Please take a look at https://github.com/microsoft/BotFramework-WebChat/issues/2120#issuecomment-516056614 for details on how to properly trigger a Welcome Message in Web Chat.
