### ISSUE TITLE
Minimizable sample should not reconnect

### ISSUE THREAD

**Issue by karimkhadro96** [microsoft/BotFramework-WebChat#2609]
Direct line reconnects to the bot framework after minimiz and maximiz the bot window in the browser 

- The impact : 
 The user will receive a welcome message after every time he changes the window size

- Test environment:
 1- Download the [minimizable web chat example](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat) 
 2- Then update web chat from 4.5.1 to 4.6.0
 3- After reciving the welcome message from the bot click on minimz button then click on maximiz button

- Please find below the screenshot attached for reference.
  First connection 
![2019-11-18_15h40_47](https://user-images.githubusercontent.com/57905880/69062035-998fff80-0a1a-11ea-9b6e-d94806412ba6.png)

 After minimiz and maximiz the window 

![2019-11-18_15h40_02](https://user-images.githubusercontent.com/57905880/69062990-fdff8e80-0a1b-11ea-813d-7e45a714421b.png)
 

Web chat version 4.6.0

**Comment by cwhitten** [comment]
@corinagum can you please take a look at this?

**Comment by tdurnford** [comment]
The sample dispatches a backcahnnel welcome event on each `DIRECT_LINE/CONNECT_FULFILLED` action which is triggered each time the chat window is expanded. We should add a state variable to track if the backchannel welcome event has already been triggered before we send it to the bot.

**Comment by corinagum** [comment]
I'll try to patch this up tonight.

**Comment by corinagum** [comment]
@compulim told me he's going to be making changes to this sample over the next week for ic3 work, so I will reassign this to him.

**Comment by compulim** [comment]
Will work on this later today.

**Comment by compulim** [comment]
@karimkhadro96 we are fixing it in #2758.

This is not an ideal fix. I opened a discussion issue #2750 and resolving it would unblock the ideal fix.

As #2750 described, we can't mount/unmount Web Chat without connect/disconnect Direct Line. So currently, we can only hide Web Chat but not releasing the memory.

There are few hacks, but I would prefer to resolve the bug in an ideal way.
