### ISSUE TITLE
Embed Code Confusion

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-WebChat#2610]
Reading through
https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/README.md#how-to-use

It is not clearly stated how to use the Gemini embed link (although it is mentioned):
https://webchat.botframework.com/embed/b/gemini?s=YourWebchatSecret&b=YourBotHandle

[Bug]

**Comment by compulim** [comment]
After a few round of discussions, I think we are going to hide this URL and ask everyone to use the embed URL from Azure Portal, which is not ready until around EOY.

**Comment by corinagum** [comment]
Resolved by #2627
