### ISSUE TITLE
Hosted Webchat in Iframe & VA template does not trigger welcome message

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-WebChat#2625]
## Version
Embedding via IFrame

## Describe the bug
When connecting to a bot using the Virtual Assistant template, the welcome message is not displayed until the user sends some input. 

The VA is looking for the MembersAdded event to send the welcome message.

## To Reproduce
Use the IFrame to connect to a bot using the virtual assistant template and the welcome message will not be displayed until the user sends input.

## Expected behavior
Expect the welcome message to be displayed without interaction.  This was working with a previous version of the template, but the team says they now rely on the SDK to do the initial event processing.

[Bug]

**Comment by corinagum** [comment]
Please see the information on welcome messages as described by @tdurnford here: https://github.com/microsoft/BotFramework-WebChat/issues/2120#issuecomment-516056614
