### ISSUE TITLE
Insecure Randomness

### ISSUE THREAD

**Issue by Jenny-ma123** [microsoft/BotFramework-WebChat#2629]
Can we implement the more secure implementation?

**Current Insecure   implementation**
Math.random

**More  secure implementation**
/* Assume that window.cryto.getRandomValues is available   */     function secureMathRandom() {       return   window.crypto.getRandomValues(new Uint32Array(1))[0] / 4294967295;     }

**Reference   URL**
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

**Current Insecure   implementation**
Random rnd = new Random();     

**More  secure implementation**

 rnd.setSeed(seed); | SecureRandom   random = new SecureRandom();           byte bytes[] = new   byte[20];           random.nextBytes(bytes) | 

**Reference   URL**
https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html

**Comment by corinagum** [comment]
It would be great if you could fill out the Bug template, which will provide us the information we need to address your concern.

Could you elaborate on what this is in reference to? Please also link JavaScript documentation since this is a JS repo. Thank you!

**Comment by compulim** [comment]
We included a library called [`math-random`](https://npmjs.com/package/math-random) that do secure random if the browser support P/RNG.

The only production code which use `random()` is `packages/core/src/utils/uniqueID.js`. And we already secured it using `math-random`.

We have insecure random but they are used in sample (19 and 22) and test harness. So they do not impose any security risks on Web Chat itself.

Please let us know by opening a new issue if you observe any of our code is using insecure random.

Thanks!
