### ISSUE TITLE
Timestamp format across browsers

### ISSUE THREAD

**Issue by narik1989** [microsoft/BotFramework-WebChat#2630]
Hi,

I am using bot framework 4.6.0. I created a sample chat application. In the time stamp config i have set it as absolute. In chrome the format is working fine. In IE there is a comma missing in between the date and time. Also can the time be configurable between 12 hour and 24 hour format?

Please find screenshot attached below for both the browsers

![Chrome](https://user-images.githubusercontent.com/33231617/69403834-9ef29000-0d21-11ea-9bc3-40e1c15bf5b7.png)
![IE_11](https://user-images.githubusercontent.com/33231617/69403835-9f8b2680-0d21-11ea-8893-83a333512c1a.png)

Thanks
Kiran

**Comment by corinagum** [comment]
This is a browser difference, not anything that Web Chat renders. Web Chat simply passes in the timestamp and the browser decides how to render it. We don't have control over the comma. 

If anything, I would recommend looking into creating a middleware where you can manually format the timestamp string.

**Comment by tdurnford** [comment]
@narik1989 Web Chat uses the [`Intl.DateTimeFormat`]() method to generate the Absolute Timestamp, and it appears to have different behaviors across browsers. 

Web Chat currently doesn't support custom timestamps at the moment; however, there is a [feature request](https://github.com/microsoft/BotFramework-WebChat/issues/1571) to add a timestamp middleware which would allow developers to create their own timestamps. Please feel free to leave a +1 on the issue.
