### ISSUE TITLE
Webchat deletes '0' from the beginning of a string

### ISSUE THREAD

**Issue by cessareoo** [microsoft/BotFramework-WebChat#2638]
When we type a string of number which the initial character is a zero, depending of string characters number, in the process of send the string to backend, is eliminated the initial zero.
[Bug]

**Comment by corinagum** [comment]
Please fill out our bug report form and include the requested information such as reproduction steps and Web Chat version so that we can help you with this bug.

**Comment by cesarmoralesona** [comment]
webchat version is the latest and Microsoft bot framework too. for example when is typed 01249790120

**Comment by nt-7** [comment]
I cannot reproduce it although I typed 01249790120 using the following Web Chat sample and some browsers like Firefox, Chrome...
https://microsoft.github.io/BotFramework-WebChat/01.a.getting-started-full-bundle/
![image](https://user-images.githubusercontent.com/20683785/69909661-ebd11780-1441-11ea-8b0e-8eb5aa040b15.png)

As @corinagum said, please fill out their bug report form such as reproduction steps to clarify this issue.

**Comment by tracyboehrer** [comment]
Is this still an issue?  We can't reproduce.

**Comment by vishwacsena** [comment]
@cessareoo we are unable to reproduce the issue. Can you please take a look and provide us detailed repro steps if you can continue to reproduce this issue on the latest webchat?

**Comment by cessareoo** [comment]
No, in the last webchat we don't have the problem
