### ISSUE TITLE
`aria-hidden` is expecting boolean, but passed as string

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2639]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/69626338-4bbc5e00-0ffd-11ea-9bfc-b0c5f0f75f3b.png)

## Version

`master`

## Describe the bug

In [`CarouselFilmStrip.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Activity/CarouselFilmStrip.js) line 134, it is passing string `"true"` to `<Bubble>`.

![image](https://user-images.githubusercontent.com/1622400/69631799-216d9f00-1003-11ea-90ff-1ad3426e80b2.png)

But in [`Bubble.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Activity/Bubble.js), it is expecting boolean.

![image](https://user-images.githubusercontent.com/1622400/69631841-2e8a8e00-1003-11ea-8837-117cca67350f.png)

This is causing a React warning in console.

## To Reproduce

1. Go to 'playground
1. Type `layout carousel`
1. Open console log and check for warnings

## Expected behavior

No warnings.

## Additional context

[Bug]

**Comment by corinagum** [comment]
🤦🏻‍♀️
