### ISSUE TITLE
Race condition: "Taking longer than usual to connect"

### ISSUE THREAD

**Issue by Curiousite** [microsoft/BotFramework-WebChat#2655]
## Version
NPM: "botframework-webchat": "^4.6.0"
>botframework-webchat:bundle:variant = full
>botframework-webchat:bundle:version = 4.6.0
>botframework-webchat:core:version = 4.6.0
>botframework-webchat:ui:version = 4.6.0

## Describe the bug
When Web-chat loses connection to the server but connection is reestablished within 15 seconds (before the "Taking longer than usual to connect" message is shown) then the message will appear after the chat is connected again and never disappear. 

The error appears to originate from a call to "sleep" within detectSlowConnectionSaga.js, where the RECONNECT_FULFILLED status in connectivitystatus.js is overwritten by CONNECT_STILL_PENDING, hence showing the message.

## Steps to reproduce
1. Establish a connection
2. Go offline
3. Reconnect within 15 seconds

## Expected behavior
The slow-connection-warning-message should not appear after 15 seconds if connection is already reestablished.

**Comment by cwhitten** [comment]
Hi @Curiousite. Thank you for the issue and the contribution! We'll review the pull request soon. See #2656 for updates.

**Comment by compulim** [comment]
I have repro-ed the issue in test and found the main cause in this code instead, `detectSlowConnectionSaga.js`.

The code did not take account into `RECONNECT_FULFILLED` or `RECONNECT_REJECTED`.

I am working on a proper fix and test case.

```diff
export default function* detectSlowConnectionSaga() {
  for (;;) {
    yield take([CONNECT_PENDING, RECONNECT_PENDING]);

    const connectivityRace = yield race({
-     fulfilled: take(CONNECT_FULFILLED),
+     fulfilled: take([CONNECT_FULFILLED, RECONNECT_FULFILLED]),
-     rejected: take(CONNECT_REJECTED),
+     rejected: take([CONNECT_REJECTED, RECONNECT_REJECTED]),
      slow: call(() => sleep(SLOW_CONNECTION_AFTER))
    });

    if ('slow' in connectivityRace) {
      yield put({ type: CONNECT_STILL_PENDING });
    }
  }
}
```
