### ISSUE TITLE
getUserMedia Support on network address

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-WebChat#2668]
## Screenshots
![UserMedia](https://user-images.githubusercontent.com/13004779/70193787-17a80380-16b5-11ea-99fd-2be41c9c55ce.png)

![network address](https://user-images.githubusercontent.com/13004779/70194019-e3811280-16b5-11ea-9ebf-98eec980800c.png)

## Version
Master Branch Latest Bits

## Describe the bug
Directline Speech icon click works fine on localhost whereas on the network URL served it breaks

## Steps to reproduce
1. Go to https://github.com/compulim/webchat-bugbash-dlspeech#create-azure-speech-resource
2. Follow steps in this repo
3. Once you serve it as a webapp we get a localhost URL and a network URL.
4. The Speech functionality fails with the error attached in the screenshot when u open the network URL it is served on

## Expected behavior
Clicking the speech icon does not generate the console error and converts the speech to text in the input box

[Bug]

**Comment by compulim** [comment]
Is it because microphone access to the browser is blocked?

**Comment by corinagum** [comment]
I am able to repro, and no my browser had microphone permissions.

**Comment by compulim** [comment]
Is it because http vs https?

Browser don't offer media recording capability when web page is served over HTTP instead of HTTPS.

**Comment by corinagum** [comment]
@gabog, @srinaath is a team member xD Removing tags

**Comment by cwhitten** [comment]
note to fixer: if for some reason getUserMedia fails we should not show the microphone button in the control
