### ISSUE TITLE
[Tracking] DLSpeech: Emulator is not supported

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2683]
> If you would want to prioritize this feature work, please vote and optionally, provide a user story.

## Feature Request

Currently, Emulator only support Direct Line protocol. We are planning to add Direct Line Speech protocol to Emulator.

[Enhancement]

**Comment by corinagum** [comment]
https://github.com/microsoft/BotFramework-Emulator/pull/2079

Closing as resolved
