### ISSUE TITLE
[DLS] OAuth card SignIn button doesn't work

### ISSUE THREAD

**Issue by lzc850612** [microsoft/BotFramework-WebChat#2693]
currently when a bot enables speech channel, the OAuthCard that renders comes with a SignInLink that's retrieved on the bot side. When clicking on SignIn button it only opens up a blank page. I checked the network trace and the SignInLink is returned so WebChat should open the SignIn page.

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Setup a bot with DLS enabled. Create a dialog in it that uses an OAuthPrompt
2. Talk to the bot using webchat for DLS. make sure the OAuthCard shows up.
3. Click on the SignIn button

## Expected behavior

the browser opens up a new tab which allows user to sign in

## Actual behavior

the browser opens up a new tab with blank page.

## Additional context

[Bug]

**Comment by compulim** [comment]
@lzc850612 Could you finish up the repro steps?

**Comment by lzc850612** [comment]
> @lzc850612 Could you finish up the repro steps? @corinagum may help you with this bug and she need more information.

Done. @corinagum feel free to ping me for a repro.

**Comment by f33n3y** [comment]
Hello, 
I'm experiencing a similar issue to the one detailed above. Is there an update on this issue?
We also have the following console error which appears after clicking the oauth card to sign in:
![image](https://user-images.githubusercontent.com/10567052/84511499-839ba200-acbe-11ea-870e-df39537d7f3d.png)

**Comment by stevengum** [comment]
The error stems from the return type issue identified in https://github.com/microsoft/BotFramework-WebChat/issues/3439

**Comment by stevengum** [comment]
Temporarily assigning to myself...
