### ISSUE TITLE
Adaptive media does not start after play button click - Safari browser

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2697]
## Screenshots

After adaptive media load:
![Inkedpre-play](https://user-images.githubusercontent.com/22778273/70458213-7d561000-1a66-11ea-9e63-cb1a2266d2f1.jpg)

After play button clicked:
![Inkedafter-button-click](https://user-images.githubusercontent.com/22778273/70458264-9ced3880-1a66-11ea-897a-76701a201055.jpg)

## Version

CDN v4.6.0
iPhone

## Describe the bug

After clicking the play button of an adaptive media (video) the media control's action panel appears on the box and the default play button switches to pause but the actual video does not start playing.

## Steps to reproduce

1. Use web chat with adaptive media
2. Click on the play button of the video.
3. The video action controls appear on the box but video does not start.

## Expected behavior

The video should start and take the full screen.

## Additional context

In the provided screenshot 2 if I click on full screen action icon then the video will take the full screen and start playing. 

## AdaptiveCard Json
```
{
  "type": "AdaptiveCard",
  "version": "1.1",
  "body": [
    {
      "type": "TextBlock",
      "size": "large",
      "isSubtle": true,
      "text": "Orientation Video"
    },
    {
      "type": "Media",
      "id": "orientationVideo",
      "sources": [
        {
          "mimeType": "video/mp4",
          "url": "some video url"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "data": {
        "CardType": "OrientationVideoCard",
        "ModelType": "System.String",
        "ActionTitle": "Done"
      },
      "title": "Done"
    }
  ]
}
```

**Comment by tdurnford** [comment]
@arman-g Can you please add the JSON for your Adaptive Card?

**Comment by arman-g** [comment]
> @arman-g Can you please add the JSON for your Adaptive Card?

Added, thanks.

**Comment by tdurnford** [comment]
@arman-g Where is your video hosted - YouTube, Vimeo, self-hosted?

**Comment by arman-g** [comment]
It is self hosted.

**Comment by arman-g** [comment]
@tdurnford just curios how do you use YouTube in a adaptive media?

**Comment by tdurnford** [comment]
@arman-g When I reproduce your issue it looks like the video is taking a long time to load. If you let the chat sit for a couple of minutes, does the video start to play? I'll need to investigate further if this is a Web Chat, Adaptive Card, or video hosting issue.

 I'm not sure if Adaptive Cards supports YouTube Media; however, Web Chat supports Video Cards that support both YouTube and Vimeo Videos. Take a look at the code snippet below. 

**Bot Framework SDK v4.6 (Node)**
```javascript
await context.sendActivity({
  type: 'message',
  attachments: [{
    contentType: 'video/mp4',
    contentUrl: 'https://www.youtube.com/watch?v=rIJRFHDr1QE',
    name: 'Vision Keynote Highlights // Microsoft Build 2019'
  }]
});
```

**Comment by arman-g** [comment]
@tdurnford on desktop using chrome, edge or firefox it works as excepted. Starts playing as soon the overlay play button is clicked. The problem happens on iPhone and I am not sure if this is a safari problem or iPhone. One think for sure, on iPhone when you play a video it automaticly goes to full screen. I think it has something to do with this. I mean maybe in order for this to work on iPhone when the overlay play button is clicked it should also make it full screen. I acspect this to be handeled by the framework but just giving my two cents whati it is worth :). In my case if you click on the full screen action button, or pause and play button right after the overlay play button click, it will start playing with out waiting 1 or two minutes as in your tests.

Thanks for the sample!

**Comment by arman-g** [comment]
@tdurnford My farther test shows that this happens on Safari browser only. So this is not a iPhone issue but Safari.

**Comment by cwhitten** [comment]
@arman-g we can't reproduce this behavior. Is it possible the video is loading very slowly in your environment?

**Comment by arman-g** [comment]
Hi @cwhitten, I don't think it is related to the video loading. The problem can only be reproduced on iPhone and safari on IOS.

- On iPhone, when the play button is tapped we get the screen that I provided in the below image. Video will start only if I tap on full screen icon or tap on pause and play again.

- On Safair on IOS, when play button is clicked we get similar screen like the image provided below. Video will start playing if I click the full screen icon or click pause and play icon again.

![Inked70458264-9ced3880-1a66-11ea-897a-76701a201055_LI](https://user-images.githubusercontent.com/22778273/72173876-58b6c600-338d-11ea-9983-db9f78c1c0f4.jpg)

**Comment by corinagum** [comment]
Hi @arman-g, I'm not reproducing your scenario unfortunately. When I press the play button, the video goes into fullscreen mode but immediately starts playing. This is on both Safari and Chrome. My understanding is that your video doesn't play unless you tap twice, is that correct?

![ezgif-5-2b7b0a9585fa](https://user-images.githubusercontent.com/14900841/72279894-fad3e980-35eb-11ea-98b4-ba3382f6a0e5.gif)


I'm hoping another customer has run into your issue so that we can get more data.

**Comment by tdurnford** [comment]
@corinagum The [Mock Bot Video](https://github.com/compulim/BotFramework-MockBot/blob/ae401cbc791e344221360ae92e8aa5e5dba4e3f7/src/commands/Video.ts#L38) command is a video card. This issue is related to videos in Adaptive Cards. I'm working on trying to repro the issue outside the scope of Web Chat to see if it's an issue with Adaptive Cards.

**Comment by tdurnford** [comment]
@arman-g This appears to be an issue with Adaptive Cards - not Web Chat. I've opened an issue in the Adaptive Cards Repo and you can track the progress of the issue [here](https://github.com/microsoft/AdaptiveCards/issues/3723). Thanks for reporting the issue!
