### ISSUE TITLE
Android: playback of audio muted when recording is ending

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2702]
## Version

`master`

## Describe the bug

This applies to Android 10 and is platform-specific. It also applies to any web apps which is not using Web Chat.

In Chrome or Edge on Android 10, speech synthesis could be interrupted by speech recognition. For example, when speech recognition stopped and speech synthesis start immediately, the synthesis could be muted for 1-2 seconds.

## Steps to reproduce

1. Go to https://addpipe.com/simple-recorderjs-demo/
1. Record an audio clip of 10 seconds
1. Click play
1. While playing the audio clip, click record again

## Expected behavior

No stuttering when record start or end.

Instead, the playback is temporarily muted for 1-2 seconds when record start. After the mute, both playback and recording appears normally.

## Additional context

This could be fixed by simultaneously playback and record at the same time and persisted. The microphone button would be a "soft" click. And the underlying audio subsystem always start playback and record regardless of whether it is currently synthesizing or recognizing.

[Bug]

**Comment by corinagum** [comment]
Needs prioritization

**Comment by corinagum** [comment]
Need to re-confirm bug - might be fixed in latest Android.

**Comment by compulim** [comment]
It seems the issue is no longer repro on latest build of Android 10.
