### ISSUE TITLE
iOS Safari: Timestamp font size on carousel layout is larger than font size on stacked layout

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-WebChat#2703]
## Screenshots

![img](https://user-images.githubusercontent.com/17039790/70558005-dd1ceb80-1b38-11ea-8b47-6af23f55030c.png)

## Version
Local build from Master

## Steps to reproduce

1. Open Web Chat on iOS Safari
1. Send `layout single` and `layout double` twice to Mock Bot
1. The timestamp on the `layout double` response should be larger than the other timestamps

## Expected behavior
Stylistically, there should be no difference between the timestamps. 

[Bug]

**Comment by cmevawala** [comment]
+1

**Comment by corinagum** [comment]
No longer getting a repro on this one :) Closing
