### ISSUE TITLE
Support more action types

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#271]
We support a few action types in [BotConnection.ts](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/BotConnection.ts#L19) and [History.tsx](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L55)

There are a few more ActionTypes in the SDKs ( [CSharp](https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Connector/ActionTypes.cs#L9) | [Node](https://github.com/Microsoft/BotBuilder/blob/master/Node/core/src/cards/CardAction.ts#L75) ) that have yet to be implemented:
* call
* playAudio
* playVideo
* showImage
* downloadFile

Some of these seem reasonable.

**Comment by billba** [comment]
Sounds great. Need specs!

**Comment by eanders-MS** [comment]
I think they should all just open the URL in a new tab.

**Comment by danmarshall** [comment]
In #318 it appears that they are opening in the same tab.

**Comment by eanders-MS** [comment]
Are you certain? They opened in a new tab for me in local testing.
