### ISSUE TITLE
Remove copy-and-paste code in `SuggestedActions.js`

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2714]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/70671551-4122db00-1c31-11ea-8508-2d71a1e00ee8.png)

## Version

`master` (4.7.0 RC)

## Describe the bug

The highlighted code in [`SuggestedActions.js`](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/component/src/SendBox/SuggestedActions.js) should not be copy-and-paste.

If there are any discrepancies between these versions, the container could get re-created, and breaking AT `aria-live="polite"` because of new DOM.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Working on this, will goal it for R8
