### ISSUE TITLE
[IC3] Customizable timestamp

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2720]
> VSTS #1660782

## Feature Request

Ability to customize timestamp based on:

- End-user: "Me 12:34 AM"
- Bot: "Bot 12:45 AM"
- End-user: "Send failed, retry"

Retry functionality can be customized by the developer and re-built different.

## Implementation

Probably, the signature will be

```js
function renderTimestamp(activity) {
  // We can check activity.from.role === 'user' or 'bot'
  // 
}
```

[Enhancement]

**Comment by corinagum** [comment]
is this for sample? If so, related to: https://github.com/microsoft/BotFramework-WebChat/issues/1571
