### ISSUE TITLE
UserId of Bot User

### ISSUE THREAD

**Issue by whatdis2** [Microsoft/BotFramework-WebChat#273]
This is more of a question rather than an issue. I am using this framework because I wanted to change the styling of the default WebChat. Currently I think I do not have the correct version of: 'webpacked/botchat.js' which is not included in the package; I ended up downloading it from [here](https://botchattest.herokuapp.com/).
1) Currently using the DirectLine with MVC C#, the sample mentions that I shall be able to get the userid, username by inputting it as a parameter like so: 

```
var params = {
    t: 'mytoken',
    botname: 'theBotname',
    userid: 'theUserId',
    username: 'theUsername'
};
```
How I get it back from within the Activity class (inside the controller)?  Tried: `message.From.Id + "-" + message.From.Name + "-" + message.Recipient.Id + "-" + message.Recipient.Name`.

**Comment by billba** [comment]
You need to build the project yourself, as described in the repo README. That version you downloaded is somewhat out of date.

If you are using the provided samples/index.html, you can either specify the user id/name in the query string, or alter the javascript on the page to pass it directly to BotChat.App. Then it should be available in message.From.

**Comment by billba** [comment]
Closing this are there are no open issues. Please let me know if you have trouble getting this to work, however.
