### ISSUE TITLE
customizable scroll bar -need a way to specify css class for scroll or override the existing one

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2736]
## Feature Request

Need a way to incorporate custom scroll in webchat. The regular one looks dull and pulls away from the design of the app.

**Comment by corinagum** [comment]
I think we've already decided this as a no-op: https://github.com/microsoft/BotFramework-WebChat/issues/2215. I'll leave this issue open for now to see if team members want to chime in with a different opinion.

Could you elaborate on why you're unable to make these css changes in the root of the app?

**Comment by prashanthsridhar** [comment]
Hi @corinagum ,i have added the custom scroll class in the root app and in the component where webchat is embeded. It is not reflected in the chat window.

**Comment by corinagum** [comment]
Embeded versions of Web Chat are not style-able, save a few options like `username`. Please try using a CDN or npm package version of Web Chat if you want to make stylistic changes. 

To see what kind of customizations you can make, please take a look at [Customizing Web Chat](https://github.com/microsoft/BotFramework-WebChat#customize-web-chat-ui)
