### ISSUE TITLE
Stop the bot from talking when needed.

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2744]
## Feature Request

Imagine a scenario when the voice assistant is speaking and the chat window is closed. The voice should stop as soon as the window is closed. Currently in webchat, i have not been able to implement the hard stop. We found a workaround in botchat by using : 
`BotChat.Speech.SpeechSynthesizer.stopSpeaking();`

Is there such a solution in webChat. If not i think this would be a valuable addition to the feature set.

**Comment by corinagum** [comment]
BotChat is the object for v3 of Web Chat. Are you using v3 or v4? If v3, that version has reached sunset and is no longer supported beyond security fixes.

**Comment by compulim** [comment]
You can call `useShouldSpeakIncomingActivity` hook to stop the synthesis.

```js
useShouldSpeakIncomingActivity(): [boolean, (value: boolean) => void]
```

Full documentation at https://github.com/microsoft/BotFramework-WebChat/blob/master/HOOKS.md#useshouldspeakincomingactivity.

**Comment by prashanthsridhar** [comment]
Hi @compulim ,i am using webchat in angular, is there a way to stop in angular?
