### ISSUE TITLE
Show suggested actions horizontally with line-break

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#2745]
Stacking the suggested actions takes up to much real estate. Most efficient way to show multiple suggested actions is horizontally with line-breaks with the option (nice to have) to align right, middle or center.
Good example sceenshot is in https://github.com/microsoft/BotFramework-WebChat/pull/2596

![](https://user-images.githubusercontent.com/4937124/70055231-713b0000-15d9-11ea-9bae-e7831c5d3219.png)

**Comment by compulim** [comment]
Looks like a suggestion for a new suggested actions layout. We have "carousel" and "stacked" today. This one is "flow" layout.

**Comment by keshansandeepa** [comment]
@compulim  Any Update regarding this ? , 
In stacked option can't we make it align left  ? so suggestions  all wrap like this ?? 
<img width="386" alt="Screenshot 2020-01-01 at 14 07 16" src="https://user-images.githubusercontent.com/28889041/71654094-c93e6100-2d55-11ea-9a2e-ffc8a7a309e8.png">

**Comment by gtejeda** [comment]
+1 on the need for flow layout (or a workaround please)

**Comment by HesselWellema** [comment]
Adding a 'flow' layout in stead of carousel will also allow for styling on :hover of a suggested action resulting in a more pleasant user experience.

**Comment by compulim** [comment]
Looks like quite some votes.

Will bring this one up on our next planning meeting. Next vehicle is May, then Aug.

**Comment by kushalbhabra** [comment]
Can we have also have a option for suggested actions to stay relative just below the last message from bot. 

Currently the suggested actions are sticky and take up permanent space if user scrolls up.

Could you suggest a fix for this?

**Comment by kavyashreeh22** [comment]
https://github.com/microsoft/BotFramework-WebChat/issues/2745#issuecomment-570126555

is this feature introduced?

**Comment by SeanDarlingBiomni** [comment]
Is there any plans to introduce this feature? It is quite common to see in other chat components. The webchat component currently has terrible UX if there are too many suggested actions but this feature would solve it! Thanks.

**Comment by sam-sam-med** [comment]
would it be possible to also add the ability to configure, if the text of the buttons get too long, be able to word wrap?

**Comment by keshansandeepa** [comment]
@sam-sam-med  You can do it from Css trick for right now

**Comment by sam-sam-med** [comment]
@keshansandeepa I was hoping there be something out-of-the-box that can do this without having to use custom css.  the custom css is sort of like a workaround to get the text to word wrap.

**Comment by corinagum** [comment]
@sam-sam-med Could you file a new `feature-request` and add that link to this conversation? I think button word wrap is a good option to have, but due to time limitations I'm not sure compulim would be able to add that to this change.

**Comment by HesselWellema** [comment]
Hi team. What  happened with this feature  request? Do you still plan to implement it or should I stick with custom css for now?

**Comment by sam-sam-med** [comment]
hi @corinagum , how do I file a new `feature-request` ?  i've never done one on github before.  thank you.

**Comment by corinagum** [comment]
@HesselWellema this item is still high priority on our list. It has been moved to our next milestone.

@sam-sam-med Please see the GitHub tutorial: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/creating-an-issue

**Comment by sam-sam-med** [comment]
hi @corinagum , thank you for the link to the info on creating an issue.  i have just created [issue 3562](https://github.com/microsoft/BotFramework-WebChat/issues/3562).

**Comment by HesselWellema** [comment]
Good luck with this one @compulim 👍
