### ISSUE TITLE
[IC3] New message indicator

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2757]
> VSTS #1660777

## Feature Request

User story:
1. Chat as normal
1. The end-user scroll somewhere up
   - The new message indicator should *not* show up
1. The bot/agent send a new message
   - The new message indicator will show up
1. Clicking on the new message indicator, or scrolling to bottom, will dismiss the indicator
   - The indicator only show up when the user is not at the bottom and a new message come in

[Enhancement]

**Comment by gsoper78** [comment]
Is this a duplicate of #1657 ?
