### ISSUE TITLE
How to increase the listening time in speech feature in webchat js

### ISSUE THREAD

**Issue by manjunathangv** [microsoft/BotFramework-WebChat#2760]
I'm using below https://cdn.botframework.com/botframework-webchat/4.6.0/webchat-es5.js.

when user clicks on speech icon, starts speaking its stop listening when user leaves gap more than a second.

Is it possible to increase the listening time.

Please find the below code.

```js
window.WebChat.renderWebChat({
    directLine: window.WebChat.createDirectLine({ token: '******************************' }),
    userID: id,
    username: id,
    locale: 'en-US',
    styleOptions: styleOptions,
    store: store,
    webSpeechPonyfillFactory: window.WebChat.createBrowserWebSpeechPonyfillFactory()
  }, document.getElementById('webchat'));
```

Thanks in advance.

**Comment by prashanthsridhar** [comment]
https://github.com/microsoft/BotFramework-WebChat/issues/2468 
apparently it is not possible.

**Comment by corinagum** [comment]
Closing as duplicate.
