### ISSUE TITLE
multiple calls to directline/conversations

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2761]
## Screenshots
![image](https://user-images.githubusercontent.com/11289456/71087264-c2461900-21c1-11ea-84e0-3b65c6214728.png)

![image](https://user-images.githubusercontent.com/11289456/71087338-f4577b00-21c1-11ea-8e21-3b752872edcd.png)

## Version
CDN 4.7

## Describe the bug
There are multple calls being made to directline/conversation

## Steps to reproduce

`

       window.WebChat.renderWebChat(
      {

        userID: sessionStorage.getItem('email'),
        username: sessionStorage.getItem('username'),
        locale: 'en-GB',
        

        directLine: directLine,

        styleOptions,
        groupTimestamp,
        selectVoice: () => ({ voiceURI: 'Custom Voice' }),
        webSpeechPonyfillFactory: options => {
          var { SpeechGrammarList, SpeechRecognition } = speechToTextPonyfillFactory(options);
          var { speechSynthesis, SpeechSynthesisUtterance } = textToSpeechPonyfillFactory(options);
          return {
            SpeechGrammarList,
            SpeechRecognition,
            speechSynthesis,
            SpeechSynthesisUtterance
          };
        }
      },
      this.botWindowElement.nativeElement
    );

`
## Expected behavior
Ideally one call should be made

## Additional context
We are using an angular app . 

[Bug]

**Comment by cwhitten** [comment]
hi @prashanthsridhar - thanks for opening the issue. we'll do some investigation on our end and report back.

**Comment by compulim** [comment]
I believe this is correct behavior.

We have 2 modes in Direct Line: (short) polling and Web Socket.

Looks like you are connected via our polling mechanism, thus, there will be a poll call every second.

When you call `createDirectLine`, if you did not set `webSocket: false` explicitly, it should start as a Web Socket connection.

p.s. Direct Line does not support long polling.

**Comment by prashanthsridhar** [comment]
@compulim , thank you for the quick response.
