### ISSUE TITLE
Hook to customize channelData

### ISSUE THREAD

**Issue by samazadi** [microsoft/BotFramework-WebChat#2763]
## Feature Request

I think we should be able to customize the channelData via a simple hook. We pass custom data via the channelData for our messages. I want to be able to easily mutate the channelData both on a per message basis and on init. 

**Is your feature request related to a problem? Please describe.**

We rely on channelData to determine our vendor and other information on the client. I want to use hooks similarly to the plain web chat sample, but can't find an elegant way to mutate the channelData without deviating from the hooks design. 

**Describe the suggestion or request in detail**

Similar to other hooks, but we're able to update the channelData on per message and global level.

**Describe alternatives you have considered**

Moving away from hooks and using BotFramework-DirectLineJS methods.

[Enhancement]

**Comment by compulim** [comment]
Interesting idea!

**Comment by tdurnford** [comment]
We don't currently have a way to modify channel data with hooks, but you can add a store middleware to the [Customization Plain UI](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/21.customization-plain-ui) sample that adds custom channel data by passing a custom store as a prop to the `Composer` component. For more details, take a look at the [Piggyback Data](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/15.a.backchannel-piggyback-on-outgoing-activities) Web Chat Sample.

```javascript
export default () => {
  ...

  const store = useMemo(() => createStore({}, () => next => action => {
    if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
      action = simpleUpdateIn(
        action,
        ['payload', 'activity', 'channelData', 'email'],
        () => 'johndoe@example.com'
      );
    }
  }), []);

  ...

  return (
    <React.Fragment>

      ...

      {!!directLine && (
        <Components.Composer directLine={directLine} store={store}>
          <PlainWebChat />
        </Components.Composer>
      )}
    </React.Fragment>
  );
};
```

Adding a `useChannelData` hook would be an interesting design change.

**Comment by samazadi** [comment]
Thanks for that example, I was able to test it out and it accomplished customizing our channelData.

**Comment by vishwacsena** [comment]
Let's close this one and file a different tracking issue for the feature request.

**Comment by cwhitten** [comment]
closing, see https://github.com/microsoft/BotFramework-WebChat/issues/2793 for the feature request
