### ISSUE TITLE
WebChat rating star feedback interactive UI

### ISSUE THREAD

**Issue by shunyh** [microsoft/BotFramework-WebChat#2770]
## Feature Request

WebChat rating feedback interactive UI

Hi team,

We want to improve our service and try to get feedback from the customer. Then we have a survey card to the customer as below:

![image](https://user-images.githubusercontent.com/7311188/71334096-976c1400-2577-11ea-9811-43e8e421223e.png)

But there is a little imperfect, this is a static picture, nothing will be changed after clicking the stars. I  hope it will highlight when the mouse hovers on the target star, and it will keep the highlight always if the customer takes action on it.

So, is there a workaround for this scenario? Just like this: https://github.com/microsoft/AdaptiveCards/issues/3054

![image](https://user-images.githubusercontent.com/7311188/71334333-ac957280-2578-11ea-8a05-f7c8f4e71314.png)

I would appreciate if you have any insights.

**Comment by tdurnford** [comment]
If you want a more custom and interactive card experience, I would recommend creating your own card attachment using React. Take a look at the [Card Customization](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/10.a.customization-card-components) Web Chat sample, which shows how to create your own interactive cards using the `attachmentMiddleware`.

**Comment by shunyh** [comment]
@tdurnford Thanks for getting back to me.

Should I create a ticket to the AdaptiveCard team on GitHub? I have seen the plan for developing this new feature on [their websites](https://portal.productboard.com/adaptivecards/1-adaptive-cards-features/tabs/5-roadmap)

![image](https://user-images.githubusercontent.com/7311188/71390452-6e14bc00-263b-11ea-9698-28620cd8d9a7.png)

**Comment by tdurnford** [comment]
Since a rating control is already on their road map and there is an open issue for the design change request, I don't think it's necessary to open another ticket in the Adaptive Cards repo.

**Comment by srinaath** [comment]
Closing it as feature is being tracked in https://github.com/microsoft/AdaptiveCards/issues/3691
