### ISSUE TITLE
Phone number auto detection and rendering as a hyperlink

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#2780]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Currently webchat does not detect phone numbers in a message and relies on a browser auto detection which might be a browser configuration setting. It also not consistent from browser to browser.

**Describe the suggestion or request in detail**

A better solution and It will be desired to have auto detection on webchat which will detect a phone number and convert it to a hyperlink.
This could be a setting option giving the developer to control it. 

**Describe alternatives you have considered**

None

[Enhancement]

**Comment by cwhitten** [comment]
Hi @arman-g. If we added auto-detection to WebChat's core logic and did what you suggested, what would the hyperlink link to? Keep in mind the need to support desktop browsers and mobile environments.

We have the activity middleware mechanism to allow consumers to consume and render activities in any way they would wish, and as its designed this would be the way to support what you are looking to do: write your own phone number detection algorithm and run it inside the activity middleware pipeline.

**Comment by arman-g** [comment]
@cwhitten I was just thinking about using middleware for this. Thanks for confirming this.
In general would be good to have it as a build in setting option.
For example (321) 789-4623 would be rendered to `<a href="tel:3217894623"></a>`

**Comment by arman-g** [comment]
@cwhitten I can't find how to effect the rendering of the message from activity middleware. I don't think it is even possible to effect the rendering of the html unless it is just a simple text change. If I change (321) 789-4623 to <a href="tel:3217894623">(321) 789-4623</a> it shows error under emulator.

**Comment by tdurnford** [comment]
Web Chat uses the [Markdown-it]() npm package to render markdown into HTML which by default supports the tel protocol. However, Web Chat also uses the [sanitize-html]() npm package to sanitize the resulting HTML from the markdown renderer, and we currently don't have the tel protocol listed as an allowed schema. As a result, the sanitizer removes the link.

There are two options to enable the tel protocol in Web Chat and remedy this issue:

### Option 1
Add the tel protocol to the list of allowed schema's 

```javascript
const SANITIZE_HTML_OPTIONS = {
  ...
  allowedSchemes: ['data', 'http', 'https', 'ftp', 'mailto', 'sip', 'tel'],
  ...
};
```
https://github.com/microsoft/BotFramework-WebChat/blob/f3275bc58f0c938bb0c910b3cd72be8e499012fc/packages/bundle/src/renderMarkdown.js#L7

### Option 2
Developers can currently pass their own markdown renderer to Web Chat that does not sanitize the HTML.

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/10.0.0/markdown-it.js"></script>
<script>
  (async function() {
    const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
    const { token } = await res.json();

    const markdownIt = window.markdownit();

    window.WebChat.renderWebChat(
      {
        directLine: window.WebChat.createDirectLine({ token }),
        renderMarkdown: text => markdownIt.render(text)
      },
      document.getElementById('webchat')
    );

    document.querySelector('#webchat > *').focus();
  })().catch(err => console.error(err));
</script>
```

### Result
#### Bot Framework SDK v4 (Node)
```javascript
context.sendActivity("[(505)503-4455](tel:(505)503-4455));
```

#### Screenshots
![image](https://user-images.githubusercontent.com/17039790/71604472-1a144680-2b17-11ea-8617-c5b4602e8cf1.png)

![image](https://user-images.githubusercontent.com/17039790/71604474-1b457380-2b17-11ea-9c14-76ba581f188a.png)

**Comment by arman-g** [comment]
@tdurnford thank you for the information. I am using the CDN and not sure if I can add 'tel' to sanitize options. Can this option be added in the next release of the webchat?

**Comment by tdurnford** [comment]
The tel protocol would have to be added the ‘allowedSchema’ in a PR.

**Comment by cwhitten** [comment]
@tdurnford that makes sense to me - seems `tel` may have been an oversight in the original list.
