### ISSUE TITLE
DLS samples not working

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2781]
Using latest release, but also tested locally in latest bits. 

Both DLS samples below fail: (also tested locally)
https://microsoft.github.io/BotFramework-WebChat/01.d.getting-started-es5-direct-line-speech/
https://microsoft.github.io/BotFramework-WebChat/06.i.direct-line-speech/

Error: 
![image](https://user-images.githubusercontent.com/14900841/71608191-29ee5380-2b34-11ea-94c1-1c523d82be5f.png)

**Comment by tdurnford** [comment]
Can you check using the latest bits? I think the CDN is pointing to v4.5.3.

**Comment by corinagum** [comment]
I did?

**Comment by tdurnford** [comment]
Nevermind....

**Comment by corinagum** [comment]
This bug will be fixed once the CDN is reverted to 4.7.1

**Comment by corinagum** [comment]
4.7.1 has been redeployed to CDN and I confirmed these samples as working again.
