### ISSUE TITLE
How can I add Button Hover Effect to Suggestions and to adaptive cards

### ISSUE THREAD

**Issue by keshansandeepa** [microsoft/BotFramework-WebChat#2784]
<img width="405" alt="Screenshot 2019-12-31 at 13 30 57" src="https://user-images.githubusercontent.com/28889041/71614469-d3375700-2bd1-11ea-864f-24126cb4e457.png">
How can i add hover and active effects to the adaptive cards and suggestions  buttons. I'm using React for building web chat

**Comment by keshansandeepa** [comment]
.ac-pushButton{
    border-radius: 20px;
}
.ac-pushButton:hover{
    background-color: #008AF9;
    color: #fff;

    border-color:#008AF9!important;
}

.ac-pushButton:active{
    background-color: #00498e !important;
    color:#ffffff!important;
}

mm, I did some trick using css , but can't i  get a direct styles from js file ?

**Comment by stevkan** [comment]
Hi @keshansandeepa,

Presently, there are no styling options available via Web Chat for adding a hover effect to buttons. The method you have selected is your best option, at this time.

Please feel free to create a new issue as a feature request, if you feel this would benefit the greater community.
