### ISSUE TITLE
Need to voice out welcome card

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2785]
## Version
4.7 CDN

## Describe the bug
i understand that there has to be voice input to invoke the synthesizer,but if we need the data in the welcome card to be spoken out there must be a way to initialize this.

## Additional context
Using webchat in an angular app.

[Bug]

**Comment by tdurnford** [comment]
If you want to Web Chat to speak the contents of a rich card, you will have to set the `speak` property in the activity to what you want to be spoken - Web Chat does not convert rich cards to speech. See https://github.com/microsoft/BotFramework-WebChat/issues/1863 for details.

```javascript
await context.sendActivity({
    attachments: [ getWelcomeCard() ],
    speak: 'Web Chat should speak this'
});
```

Also, if you want Web Chat to speak an incoming activity without having to have the user speak first, you can set the `speak` property in activity's `channelData` to `true`. https://github.com/microsoft/BotFramework-WebChat/issues/2181#issuecomment-518413590 provides more detail on this behavior. 

```javascript
await context.sendActivity({
    attachments: [ getWelcomeCard() ],
    speak: 'Web Chat should speak this'
    channelData: { speak: true }
});
```
