### ISSUE TITLE
How to Customize Suggested Actions Layout  

### ISSUE THREAD

**Issue by keshansandeepa** [microsoft/BotFramework-WebChat#2789]
Hi, 
I just wondering is there any method to customize the suggested actions container.
Right now my Suggested Actions Layout look like this .  

<img width="364" alt="Screenshot 2020-01-01 at 14 04 48" src="https://user-images.githubusercontent.com/28889041/71639628-bd906300-2c9f-11ea-8f9f-7376cf09fe84.png">

But i need to customize like this . Any method to implement ?

<img width="386" alt="Screenshot 2020-01-01 at 14 07 16" src="https://user-images.githubusercontent.com/28889041/71639637-152ece80-2ca0-11ea-9d0c-9867b2054d8d.png">

**Comment by mdrichardson** [comment]
@keshansandeepa I recommend reviewing the [styling sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.b.idiosyncratic-manual-styling/). Your `styleOptions` can modify the following for suggested actions:

```css
  suggestedActionBackground: 'White',
  suggestedActionBorderColor: undefined, // defaults to accent
  suggestedActionBorderStyle: 'solid',
  suggestedActionBorderWidth: 2,
  suggestedActionBorderRadius: 0,
  suggestedActionImageHeight: 20,
  suggestedActionTextColor: null,
  suggestedActionDisabledBackground: undefined, // defaults to suggestedActionBackground
  suggestedActionDisabledBorder: null,
  suggestedActionDisabledBorderColor: '#E6E6E6',
  suggestedActionDisabledBorderStyle: 'solid',
  suggestedActionDisabledBorderWidth: 2,
  suggestedActionDisabledTextColor: undefined, // defaults to subtle
  suggestedActionHeight: 40,
```

**Comment by keshansandeepa** [comment]
@mdrichardson 
I want to edit position of suggestions bar , Currently its all centered , but i need to add justifiy-end make a right align , mm, do you have any solution for that ?

**Comment by mdrichardson** [comment]
@keshansandeepa Using `suggestedActionLayout: 'stacked'` should get you pretty close (although there's currently a bug, so it doesn't work right now). Beyond that you'd need to either:

1. Make custom CSS edits. The css class names may change in the future, so I don't necessarily recommend this. Or
2. Build and customize WebChat, then include it in your site, or
3. [Submit this as a feature request](https://github.com/microsoft/BotFramework-WebChat/issues/new?assignees=&labels=Enhancement%2C+Pending%2C+customer-reported%2C+Bot+Services&template=feature_request.md&title=)

**Comment by mdrichardson** [comment]
@keshansandeepa In case you didn't see...it's a known bug and it's actually fixed in a version that isn't live on the CDN yet.

**Comment by keshansandeepa** [comment]
@mdrichardson  In React Version , That bug was fixed,  I just tried css trick for now . But within one month, i will try to  implement style version, lets see , thanks for the reply :)

**Comment by MrDBC** [comment]
> @keshansandeepa I recommend reviewing the [styling sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.b.idiosyncratic-manual-styling/) or the [branding sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.a.branding-webchat-styling). Your `styleOptions` can modify the following for suggested actions:
> 
> ```js
>   suggestedActionBackground: 'White',
>   suggestedActionBorder: undefined, // split into 3, null
>   suggestedActionBorderColor: undefined, // defaults to accent
>   suggestedActionBorderRadius: 0,
>   suggestedActionBorderStyle: 'solid',
>   suggestedActionBorderWidth: 2,
>   suggestedActionDisabledBackground: undefined, // defaults to suggestedActionBackground
>   suggestedActionDisabledBorder: null,
>   suggestedActionDisabledBorderColor: '#E6E6E6',
>   suggestedActionDisabledBorderStyle: 'solid',
>   suggestedActionDisabledBorderWidth: 2,
>   suggestedActionDisabledTextColor: undefined, // defaults to subtle
>   suggestedActionHeight: 40,
>   suggestedActionImageHeight: 20,
>   suggestedActionLayout: 'carousel', // either "carousel" or "stacked"
>   suggestedActionTextColor: null,
> ```


suggestedActionBackground: '"rgba(94, 183, 223, 1)", isnt not working why?
Only the border properties are working
