### ISSUE TITLE
suggestedActionLayout: 'stacked' not working

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotFramework-WebChat#2792]
## Screenshots

![image](https://user-images.githubusercontent.com/40401643/71686861-44e9df00-2d51-11ea-850e-d0e2c0599474.png)

![image](https://user-images.githubusercontent.com/40401643/71686865-46b3a280-2d51-11ea-9921-ef92b437bfa7.png)

![image](https://user-images.githubusercontent.com/40401643/71686868-4915fc80-2d51-11ea-9b03-93ef42ac8682.png)

## Version

latest

## Describe the bug

suggestedActionLayout: 'stacked' doesn't work and actions remain in Carousel.

## Steps to reproduce

1. Use the Suggested Actions sample
2. Use the branding sample and add `suggestedActionLayout: 'stacked'`

## Expected behavior

Suggested Actions to be stacked

## Additional context

Per @corinagum, possibly related to: https://github.com/microsoft/BotFramework-WebChat/issues/2779

[Bug]

**Comment by mdrichardson** [comment]
I don't have permissions to remove labels :(

**Comment by tdurnford** [comment]
@mdrichardson what version of Web Char are you using? The stacked suggested action layout was introduced in v4.6, but the latest cdn is currently pointing to v4.5.3 due to an issue with DirectLineJs. This will probably be resolved after we rerelease v4.7.1.

**Comment by mdrichardson** [comment]
@tdurnford Gotcha. What's the easiest way to test the lastest? I was using cdn's "latest"

**Comment by tdurnford** [comment]
You can add this code snippet to the script in the HTML file
```javascript
[].forEach.call(document.getElementsByTagName('meta'), ({ content, name }) => console.log(`${name}: ${content}`));

```
The resulting console log should look like this:
![image](https://user-images.githubusercontent.com/17039790/71706304-e21c3600-2d98-11ea-924b-e045a221f9e3.png)

**Comment by corinagum** [comment]
*facepalm* this has to be it

**Comment by tdurnford** [comment]
The stacked suggested actions layout is working fine using the latest bits. This issue will be resolved after we rerelease v4.7.1.

![image](https://user-images.githubusercontent.com/17039790/71706873-18a78000-2d9c-11ea-993b-ca8873b07ab1.png)

**Comment by MedvidekPu** [comment]
Hey, I am currently facing the same issue as  

const styleOptions = {
    // Suggested actions
    suggestedActionTextColor: 'black',
    suggestedActionBorder: `solid 2px #009682`,
    suggestedActionHeight: 40,
    suggestedActionLayout: 'stacked',
};

doesn't stack the cards on top of each other, is there a way to update my Webchat version or how can I manage to make it work please?

**Comment by MedvidekPu** [comment]
> Hey, I am currently facing the same issue as
> 
> const styleOptions = {
> // Suggested actions
> suggestedActionTextColor: 'black',
> suggestedActionBorder: `solid 2px #009682`,
> suggestedActionHeight: 40,
> suggestedActionLayout: 'stacked',
> };
> 
> doesn't stack the cards on top of each other, is there a way to update my Webchat version or how can I manage to make it work please?

solved by adding <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script> to the HEAD of the page
