### ISSUE TITLE
Update README.md for minimizable sample

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2811]
## Version

`master` (this is related to sample, unrelated to production code)

## Describe the bug

We updated the code for minimizable sample, but the README.md is not in sync.

## Steps to reproduce

Look at `README.md` at https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat, and compare with `index.html`.

## Expected behavior

The `README.md` should align with the code in `index.html`.

## Additional context

[Bug]

**Comment by sharat9211** [comment]
Looks like a straightforward issue, can I take it up?

**Comment by corinagum** [comment]
@sharat9211 absolutely!! We would love your contribution. :D Feel free to leave comments if you have any questions for us.

**Comment by sharat9211** [comment]
I went through the code & Readme and I am thinking, we need to explain the code contained in two files MinimizableWebChat.js and WebChat.js or just WebChat.js
