### ISSUE TITLE
Missing padding between bot avatar and bot bubble

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2812]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/72291461-42ff0600-3604-11ea-8790-85607f20d1d0.png)

## Version

```
<meta name="botframework-directlinespeech:version" content="4.7.1">
<meta name="botframework-webchat:bundle:variant" content="full-es5">
<meta name="botframework-webchat:bundle:version" content="4.7.1">
<meta name="botframework-webchat:core:version" content="4.7.1">
<meta name="botframework-webchat:ui:version" content="4.7.1">
```

## Describe the bug

Showing avatar for bot side only, the padding between the bot avatar and bot bubble is missing.

## Steps to reproduce

1. Host Web Chat using `packages/embed` and add `&v=4.7`

## Expected behavior

There should be padding between bot avatar and its bubble.

## Additional context

Also seems to repro on 4.6.0, but not 4.5.2.

[Bug]

**Comment by tdurnford** [comment]
@compulim Can you add the image url you are using? I can't get this repro in v4.6.0 or v4.7.1. 

![image](https://user-images.githubusercontent.com/17039790/72460428-a19dbe80-3781-11ea-8217-f81ea315b4a0.png)

**Comment by corinagum** [comment]
@tdurnford did you try this on embed?

**Comment by tdurnford** [comment]
@corinagum I don’t believe you can set style options for embedded.

**Comment by tdurnford** [comment]
@compulim Can you explain how to set the bot avatar through embedded? It's not included in the [embedded](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/embed) docs.

**Comment by compulim** [comment]
This should be fixed by now.

@tdurnford you can't set it in embed. Original plan, style options can be part of query parameters, thus we design style options to be super-flat-and-primitive.
