### ISSUE TITLE
"Send welcome event" sample  is blocked by CORS policy when deployed in Azure as a web app

### ISSUE THREAD

**Issue by Rykimaruh** [microsoft/BotFramework-WebChat#2817]
Hello,

I am trying to test out the "Send welcome event" sample by deploying it on a web app in Azure and I get the following error: 

> favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)

>webchat-mockbot.azurewebsites.net/directline/token:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

>(index): Access to fetch at 'https://webchat-mockbot.azurewebsites.net/directline/token' from origin 'https://o365botpop.azurewebsites.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

>(index):58 TypeError: Failed to fetch

This works fine when running locally on my computer...

Any ideas how to solve this issue?

I am aware I had this issue before, but I dropped it and now I'm picking it up again to see if I can finally finish solving something on my end with this "solution". It was issue #1821 which is closed.

Here is the attached file just in case 
[BotTest.txt](https://github.com/microsoft/BotFramework-WebChat/files/4065328/BotTest.txt)

**Comment by compulim** [comment]
@Rykimaruh you will need to host a bot yourself.

Our MockBot (the bot behind all samples), will only hand out Direct Line tokens for our hosted samples. If you are hosting Web Chat on your site, you will need to host your own bot as well.

**Comment by Rykimaruh** [comment]
is there a documentation to doing this?

**Comment by kdubious** [comment]
In Azure, edit the App Service, API > CORS and add your custom domain
