### ISSUE TITLE
[Embed package] Pass userid to token generation logic

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/BotFramework-WebChat#2818]
## Version
4.7.1

## Describe the bug

The logic in Embed package should pass in userid (included in query parameters) to create conversation/token generation. Today the userid and username is passed as query parameter but not included in the token. 

Could you help to enhance embed\src to include this?

[Bug]

**Comment by tdurnford** [comment]
@p-nagpal You can currently generate a DirectLine token that includes a user id and a username and pass that to the iFrame as a url parameter. Take a look at the [Generating a DirectLine Token](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#generate-token) and [Embedded Web Chat](https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/embed#what-url-parameters-are-supported) documentation for more details. 

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: iFrame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      html,
      body {
        height: 100%;
      }
      body {
        margin: 0;
      }
    </style>
  </head>
  <body>
    <script>
      (async function() {
       // Note, for the simplicity of this example, we are generating the Direct Line token on client side;
       // however, this is not a recommended practice and you should create and manage your tokens from the server.
       // You should never put the Direct Line secret in the browser or client app.
        const secret = '<DIRECT_LINE_SECRET>';
        const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate', {
            body: JSON.stringify({ user: { id: 'dl_user_id', name: 'username' } }),
            headers: {
              Authorization: `Bearer ${secret}`,
              'Content-type': 'application/json'
            },
            method: 'POST'
        });
        const { token } = await res.json();

        const iframe = document.createElement('iframe');
        iframe.src = `https://webchat.botframework.com/embed/<YOUR_BOT_ID>?t=${token}`;
        iframe.style = 'min-width: 400px; width: 100%; min-height: 500px';
        document.body.appendChild(iframe);

      })().catch(err => console.error(err));
    </script>
  </body>
</html>
```

**Comment by tdurnford** [comment]
Unintentionally closed. Opened by Microsoft internal.

**Comment by compulim** [comment]
I think @timenick is working on this.

**Comment by cwhitten** [comment]
Moving to R12 as the PR is in draft state and incomplete
