### ISSUE TITLE
v3 is not building because of incompatible @types/node/repl.d.ts with TypeScript 2.7

### ISSUE THREAD

**Issue by kagJacky** [microsoft/BotFramework-WebChat#2823]
We are using 
"name": "botframework-webchat",
"version": "0.11.4",

It used to build successfully. After the holiday, there is a bug occur when we run "npm i" under this folder:  src\websites\BotFramework\BotFramework-WebChat>

The error is:
> botframework-webchat@0.11.4 prepublish C:\VSTSAgent\_work\327\s\src\websites\BotFramework\BotFramework-WebChat
> tsc && npm run build-css && webpack --progress --config webpack.production.config.js

node_modules/@types/node/repl.d.ts(356,36): error TS1005: '=' expected.
node_modules/@types/node/repl.d.ts(362,36): error TS1005: '=' expected.
node_modules/@types/node/util.d.ts(21,30): error TS1005: '=' expected.
node_modules/@types/node/util.d.ts(183,30): error TS1005: '=' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! botframework-webchat@0.11.4 prepublish: `tsc && npm run build-css && webpack --progress --config webpack.produc
tion.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the botframework-webchat@0.11.4 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Toronto\AppData\Roaming\npm-cache\_logs\2020-01-16T19_03_50_835Z-debug.log

**Comment by compulim** [comment]
We need to add @types/node@11.13.0 to package.json.

**Comment by kagJacky** [comment]
Thanks compulim!
