### ISSUE TITLE
ESLint doesn't report error on CI pipeline

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2826]
## Version

`master`

## Describe the bug

ESLint running on Azure DevOps does not catch any code problems.

## Steps to reproduce

1. Submit a PR with code problems that would trigger ESLint
1. Monitor the Azure DevOps pipeline

## Expected behavior

The CI pipeline should fail.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Closing this as resolved.
