### ISSUE TITLE
hi is it possible personality chat add and run off line in bot framework V4 in C# through text file??

### ISSUE THREAD

**Issue by Tamoormughal** [microsoft/BotFramework-WebChat#2829]

**Comment by Virtual-Josh** [comment]
Hi @Tamoormughal,

I'm happy to help, but I don't understand your question. Can you provide more information/context so I can better understand your question?

**Comment by Tamoormughal** [comment]
I want to run personality chat off line instead off service call ...

**Comment by Virtual-Josh** [comment]
What do you mean personality chat? If you're using our documentation can you link me to it?

**Comment by Tamoormughal** [comment]
https://www.microsoft.com/en-us/research/project/personality-chat/

**Comment by Virtual-Josh** [comment]
@Tamoormughal  

We don't support any offline scenarios for bots so this isn't something we can support.
