### ISSUE TITLE
typescript can't import botframework-webchat with module set to amd

### ISSUE THREAD

**Issue by hailiu2586** [Microsoft/BotFramework-WebChat#283]
```
import * as webchat from "botframework-webchat";

```
this results in can't find module error when compiling with typescript 2.1.5

here is my tsconfig.json

```
{
    "compileOnSave": true,  
    "compilerOptions": {
        "module": "amd",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "rootDir": "../",
        "outDir": "../../built/",
        "sourceMap": true,
        "jsx": "react"
    },
    "include": [
        "**/*.ts",
        "**/*.tsx"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}

**Comment by billba** [comment]
are you using the npm package?

**Comment by hailiu2586** [comment]
yes, here is the entry in my package.json

```
    "botframework-webchat": "^0.4.3",

**Comment by billba** [comment]
The thing that jumps out at me as that you are excluding node_modules but that is where the WebChat files are coming from. This may not be helpful, but instead of includes and excludes I usually just use files. TypeScript will bring in all the dependencies as needed, so often it's enough to list just one file.

**Comment by hailiu2586** [comment]
after updating my tsconfig.json to below

```
{
    "compileOnSave": true,  
    "compilerOptions": {
        "module": "amd",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "rootDir": "../",
        "outDir": "../../built/",
        "sourceMap": true,
        "jsx": "react"
    },
    "files": ["./*.ts", "./views/**/*.ts"]
}
```

I still have error on unresolved 'botframework-webchat' module. However, I was able workaround this by
1) add below directly in my .tsx file
```
///<reference path="../node_modules/botframework-webchat/botchat.d.ts"/>
```
2) wrap the botchat.d.ts with 
```
declare module 'botframework-webchat' {
...
}
```

now my ts project builds fine. Odd that typescript 2.1.5 is not picking up botchat.d.ts from the package.json in botframework-webchat.

**Comment by billba** [comment]
I would happily accept a pull request to update the botchat.d.ts to add amd compatibility. It is strange that TypeScript isn't seeing the file at all - that seems to work with commonjs clients. It's a stumper.

**Comment by hailiu2586** [comment]
pull request created :-)

**Comment by danmarshall** [comment]
@hailiu2586 do you still need this functionality?
