### ISSUE TITLE
Adaptive card rendering issue in the newest version, when customization is applied.

### ISSUE THREAD

**Issue by Antti-Leskinen** [microsoft/BotFramework-WebChat#2834]
## Screenshots
Old version:
![image](https://user-images.githubusercontent.com/59018989/72723096-8c150400-3b88-11ea-8ffc-217e7dc6f4a2.png)

New version:
![image](https://user-images.githubusercontent.com/59018989/72723138-a51db500-3b88-11ea-8453-0579c5cb9558.png)

## Version

All the versions are NPM packages. Using React:
Old version:
Botframework-webchat 4.4.2. Where the adaptive cards package is 1.1.3

New version:
Botframework-webchat 4.7.1. Where the adaptive cards package is 1.2.3

## Describe the bug

Using react with create react app and using Javascript to manipulate the DOM  to change the adaptive card behaviour.
The current flow that is working in the old version is:
- the adaptive card button is clicked. The clicked button is disabled and the color is changed to green.
- if there are any other buttons in the adaptive card then disable them and change the color to grey.
- if the current adaptive card contains any radio buttons, checkboxes or any other kind of input elements disable them also.
- This allows the user to see a history of what the user has clicked by showing the clicked buttons as green and everything else as grey. The other benefit is that the buttons can only be clicked once (same applies to other html elements like radiobuttons). The default is that the adaptive card buttons can be clicked multiple times.

How this is achieved:
- For the current button being clicked we check if the "event.target" contains the button class and then the current button is disabled and a css class is added to make the button green.
- Another function checks all the buttons using normal for loop and the button class. The button is disabled and a css class is added to the button to make it grey.
- In order to achieve the above a normal click event listener using javascript is created and a function is applied to it. This function handles the card button click.
- The functions are called inside the store (create a new store like in the minimizablewebchat sample) to make them repeat after every activity.

New version problems:
- In the new version this does not work at all. The buttons keep the original state. Even the radio buttons and other elements are not disabled. 
- During my investigation it seems to sometimes work for less than a second until it reverts to the original state and it does it for all the adaptive cards at the same time while the old version seemed to have only modified the current adaptive card instead of every card. 
- Moreover the actual button in the adaptive card is no longer recognized by “event.target” while every other element is recognized. We need this in order to track the currently selected button. This is probably one of the reason why the custom code does not work anymore. 
- I am not allowed to show actual code.

## Steps to reproduce

0. Creating an adaptive card in the bot. Can you create an adaptive card somehow on your side?
1. Create a react app (for example use the minimzable webchat sample (the old version that is still on the readme.md instead of the new version that is in the code currently but not reflected in the readme file) in webhat directory in here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat).
2. create button listener using javascript and apply a custom function to the listener that contains something like "console.log(event.target)". Can also try to disable the target or add a class with a color and see that it is not applied.
3. Notice that in the new version clicking adaptive card button does not show in the browser console but clicking everything else in the chat does show. In the old version the button click showed in the console.
4. This means there is no point doing anything else for the adaptive card since it does not get recognized.
5. You can still try to "document.queryselectorall" to disable the button and if I remember correctly it disables all the buttons and this means the buttons cant be clicked at all.

## Expected behavior

The adaptive card buttons and other html elements like radiobutton should disable when prompted by the DOM. Now it seems to go back to default state for every card after something is changed.

Is there another way to do this other than manipulating the DOM with JavaScript? I have not figured out any other way. Kind of like the "styleset" options to modify the look of the chat to ensure the changes are kept between versions.

## Additional context

- The bug seems to appears when the adaptive cards npm package version changes to 1.2.0 or above.  
- Something seems to have changed in the rendering of the adaptive card in version 1.2.0.
- When the version is 1.1.3 like it is in webchat 4.4.2 it works correctly.
- This happens when the botframework-webchat package is updated from 4.4.2 to any other above version like 4.5.2.
- This is currently a blocker since the bot uses adaptive cards heavily and this problem prevents the updating of the botframework-webchat npm package.
- This bug can be reproduced by the CDN version also using just JavaScript.
- We are using the minimizablewebchat.js sample, but it should not matter in this case since it can be reproduced from CDN version.
- Using Healthcare bot. There is a free pricing tier available on Azure.

[Bug]

**Comment by Virtual-Josh** [comment]
@stevkan can you provide an update on this ticket? Thanks.

**Comment by stevkan** [comment]
I was able to repro the issue using an "on click" event listener. The issue appeared when Adaptive Card, version 1.2.0 or greater, was used whereas version 1.1.3 did not produce the issue. I tested Web Chat version 4.4.2 and 4.7.1.

I decided to test the issue by visiting the Adaptive Cards [Designer](https://adaptivecards.io/designer/). I selected "Preview Mode", opened the developer's console, created an "on click" event listener and, again, was unable to get any buttons to return the `event.target` object, though other elements on the card and page did so. Also tried other "host apps", other than "Bot Framework WebChat", with the same result ("Windows Notifications", "Cortana Skills").

I believe this issue is specific to the Adaptive Cards package and not Web Chat, and would suggest you create an issue on the Adaptive Cards repo [here](https://github.com/microsoft/AdaptiveCards/issues/new/choose).

I'm going to close this as resolved. If you have new information regarding this that further suggests this is a Web Chat issue, please feel free to reopen and comment.
