### ISSUE TITLE
Dynamically Set Avatar on a Per Message Basis

### ISSUE THREAD

**Issue by 01** [microsoft/BotFramework-WebChat#2836]
**Is your feature request related to a problem? Please describe.**

I am looking for a way to dynamically set the avatar for a message. Currently have implemented a multi user chat functionality but not able to determine course for dynamically setting avatar. Using react but seems current implementation is locked into "bot" and "not bot"

**Comment by tdurnford** [comment]
@01 You are correct, Web Chat currently only supports setting the avatar for the user and the bot, and there currently isn't a way to set the avatar on a per message basis. However, you can use the activity middleware to customize how the activity is rendered and add your own avatar for each activity. I would recommend looking at the [Reaction Button](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/d.reaction-buttons) Sample for more details on using the middleware.

**Comment by tdurnford** [comment]
@01 https://github.com/microsoft/BotFramework-WebChat/issues/2857 is tracking this Enhancement.

**Comment by 01** [comment]
@tdurnford fantastic very excited for this feature thank for the update

**Comment by amt-work** [comment]
@tdurnford Just to be clear, I want a feature like this as well to make it appear as if a message is coming from a specific bot. So when a message comes in from the bot I can change the avatar for that message and then the future messages until I want to change it again, but it will preserve the avatar for all previously sent messages. Will this be possible with this feature?

**Comment by abhikumarbb16** [comment]
Please post solution if you have found it.
