### ISSUE TITLE
timestampClassName is marked as required in SendStatus

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#2852]
## Screenshots

![image](https://user-images.githubusercontent.com/14900841/73037148-c984c600-3e02-11ea-8fc7-1553e44ca55c.png)

## Version

latest bits

## Describe the bug
`timestampClassName` is listed as a required prop in `SendStatus`.

## Steps to reproduce

1. Open Mock Bot
1. type `carousel`
1. See failed prop type error in console

## Expected behavior

[Bug]

**Comment by compulim** [comment]
This is obsoleted after we done the "customizable activity status" feature.
