### ISSUE TITLE
Code: Move <BasicWebChat> to functional component

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2860]
## Feature Request

Today, our `<BasicWebChat>` is still using class component. We should consider moving to functional component.

This is also related to #2859.

[Enhancement]

**Comment by tdurnford** [comment]
I think @corinagum is doing this in her RTL PR

**Comment by corinagum** [comment]
Yep, will be done in RTL

**Comment by compulim** [comment]
This is done in recent RTL PR #2890.
