### ISSUE TITLE
Upload photos and documents from client side (User)

### ISSUE THREAD

**Issue by Lipa9963** [Microsoft/BotFramework-WebChat#287]
i use the webChat To implement my Client side in my bot. so the user can go to my URL and start talk to the bot.

During the conversation my user need to send to me (to the BOT) any image.
I am faced with two problems 
1 )  Some photos send to the BOT successfully And some we get the error "couldn`t send retry" but the retry not help.
2) in Microsoft Edge when you try to add image : the folder open and then you can choose the image.. but after you choose Other folder opens Again and again and We can not go on. #

**Comment by billba** [comment]
Can you provide examples for 1)?

**Comment by Lipa9963** [comment]
Hi
I'm still trying to figure out when it happens and when it does not,
I will update as soon as I realize.

Regarding the 2 , i think it`s a bug in Microsoft Edge?  because in Chrome
it works fine.
Thanks

**Comment by Lipa9963** [comment]
ok, i found one case for example.
attaching two pictures, one of them "success.jpg" the user  can upload it
and send to the Bot. The second "failure.jpg" the user can not upload and
send to the Bot.
 Please let me know if you understand what the story.
Thanks

**Comment by billba** [comment]
I had no trouble uploading the "failure" image you provided in either Safari or Chrome, when using my standard test bot.

**Comment by danmarshall** [comment]
I was able to repro in Edge. Will investigate.

**Comment by danmarshall** [comment]
It's a known bug in Edge https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8282613/
reported as fixed, but clearly, it is not fixed :(

**Comment by danmarshall** [comment]
This seems to be happening again.
