### ISSUE TITLE
WebSocket Connection Error in GraphBot SPFx Extension 

### ISSUE THREAD

**Issue by uppalapraveen** [microsoft/BotFramework-WebChat#2872]
## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Describe the bug

I have the Microsoft GraphBot extention running in the SPFx site.
I am facing an issue with WebSocket
here is the issue in console error
**WebSocket connection to wss://directline.botframework.com/v3/directline/conversations/conversation-id/stream-watermark' failed: Error during WebSocket handshake: Unexpected response code: 403** 

After the error in console we are losing the conversation history. Its throwing an error in directLine.ts file at line: 682. **const ws = new WebSocket(this.streamUrl);**

Please help me out to resolve it. I have search all but no results.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by dmvtech** [comment]
@uppalapraveen Can you try disabling websockets. 
```
[...]
window.WebChat.renderWebChat(
    {
      directLine: botConnection,
      userID: 'YOUR_USER_ID',
      username: 'Web Chat User',
      locale: 'en-US',
      webSocket: false // ADD THIS !!!!
    },
    document.getElementById('webchat'),
[...]
```

See more info here:
https://stackoverflow.com/questions/59983223/sporadic-timeouts-from-directline-endpoint/59993344#59993344

**Comment by cwhitten** [comment]
@uppalapraveen can you also verify that your token/credentials are correct? This is what we would expect when you receive a 403

**Comment by dmvtech** [comment]
hi @uppalapraveen Have you been able to confirm token/credentials or any other updates?

**Comment by dmvtech** [comment]
Hi @uppalapraveen We haven't heard back from you in some time. If you are still having this problem, please reopen the issue and address the questions we have posed. Thanks, and have a great day!

**Comment by uppalapraveen** [comment]
Thanks for the support Dana V...!

I have resolved the issue in other way by enabling the WebSocket as true.
Storing the conversation history in local storage and retrieving it back on some click events.

Its working for me perfectly..!
