### ISSUE TITLE
would there be any release of the react source version code anytime soon ?

### ISSUE THREAD

**Issue by moxched** [microsoft/BotFramework-WebChat#2873]
🚨 The issue tracker is not for implementation questions 🚨

[Question]

**Comment by tonyanziano** [comment]
@moxched can you please clarify what you mean?

Do you mean the source code of React, the library?

**Comment by moxched** [comment]
yes the available options i find them insufficient and it would be nice not to have rewrite the whole ReactWebChat

**Comment by cwhitten** [comment]
@moxched what options do you find missing? Are you using the ReactWebChat component with the DirectLine channel?

**Comment by daveta** [comment]
Hi @moxched , please reopen if you have more details.
Thanks! -Dave

**Comment by moxched** [comment]
hi @cwhitten  about the options, updating the ReactWebChat without rerendering the whole component, for instance i need to hide the send box when an button action is demanded i managed to do so through javascript css change and the option activityMiddleware but it would be great not having to depend on javascript to do so just instruct my component to rerender its behavior if one of the style Option input is changed
