### ISSUE TITLE
Tear down bundle size

### ISSUE THREAD

**Issue by crisvilares** [microsoft/BotFramework-WebChat#2874]
Hi devs... We're facing some performance issues because of the big bundle-size of the botframework-webchat bundle. Is there any possibility to tear it down to the essential features? Or is there maybe a bundle available with just the minimal features on npm? Thx for your answer.

**Comment by corinagum** [comment]
Hi @crisvilares, please take a look at this reponse: 
https://github.com/microsoft/BotFramework-WebChat/issues/2841

**Comment by cwhitten** [comment]
Closing, see #2841 for on-going discussion and suggestions
