### ISSUE TITLE
minimizable-web-chat changing voice when Minimize and then Maximize 

### ISSUE THREAD

**Issue by pastapure** [microsoft/BotFramework-WebChat#2875]
I am using minimizable-web-chat sample and added **createCognitiveServicesSpeechServicesPonyfillFactory()** function and also I implemented implemented **speechSynthesis.getVoices = function (){...}** with I set always female voice which I want in my apllication and it is working fine. but while speaking when I minimize chat and then maximize I getting different voice and also it changing gender for voice.

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by tdurnford** [comment]
@pastapure Can you please add code snippets for your `selectVoice` function and the code you added to the Minimizable Web Chat sample for `createCognitiveServicesSpeechServicesPonyfillFactory`?

**Comment by pastapure** [comment]
Thanks for your quick response, 

**see below code used in WebChat.js**

```
componentDidMount() 
  {
          !this.props.token && this.props.onFetchToken();    
          !this.props.token && this.fetchSpeechPonyfill() ;   
  }

  fetchspeechOptions ()
  {
    return options => {
      const ponyfill =this.state.webSpeechPonyfill(options);
      var speechSynthesisUtterance = ponyfill.SpeechSynthesisUtterance;
      var speechSynthesis = ponyfill.speechSynthesis;
      speechSynthesis.getVoices = function () {
          return [
              { 
                lang: 'en-US', 
                gender: 'Female', 
                voiceURI: 'Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)' }
          ];
      }
      return {
          SpeechGrammarList: ponyfill.SpeechGrammarList,
          SpeechRecognition: ponyfill.SpeechRecognition,
          speechSynthesis: speechSynthesis,
          SpeechSynthesisUtterance: speechSynthesisUtterance
      }
    };
  }


async fetchSpeechPonyfill() 
  {
     const webSpeechPonyfill= await createCognitiveServicesSpeechServicesPonyfillFactory({
      authorizationToken:this.fetchSpeechServicesToken() , 
      region: 'eastus'
    });

    this.setState(() => ({webSpeechPonyfill}));

    const webSpeechPonyfillHybrid=this.fetchspeechOptions();

    this.setState(() => ({webSpeechPonyfillHybrid}));
  }

```
// in render() 
```
 <ReactWebChat
              directLine={this.createDirectLine(token)}
              store={store}
              styleSet={styleSet}
              webSpeechPonyfillFactory={this.state.webSpeechPonyfillHybrid }
              groupTimestamp={false} 
              />
```

**and In MinimizableWebChat.js used below code.**

```
else if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') 
      {
       
        if (action.payload.activity.from.role === 'bot') {
          this.setState(() => ({ newMessage: true }));
          this.state.store.dispatch(startSpeakingActivity());
      }

```

**Comment by tdurnford** [comment]
It looks like you are using an old version of the Minimizable Sample. What version of Web Chat are you using?

**Comment by pastapure** [comment]
**using bellow version** but I have to resolve that voice issue and continue with the same version

"name": "sample-customization-minimizable-web-chat",
  "version": "0.1.0",
  "private": true,
  "homepage": "https://microsoft.github.io/BotFramework-WebChat/12.customization-minimizable-web-chat/",
"dependencies": {
    "botframework-webchat": "~4.5.1",
     "memoize-one": "^5.0.2",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-scripts": "^3.0.1"
  },

**Comment by tdurnford** [comment]
@pastapure It looks like select voice works with the latest version of Web Chat and the most recent sample.  I recommend that you work from the most up to date [Minimizable](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat) Sample. Take a look at the code snippet below for help getting started. 

```jsx
  const handleRequestSpeechToken = useCallback(async () => {
    const res = await fetch('https://webchat-mockbot.azurewebsites.net/speechservices/token', { method: 'POST' });
    const { token } = await res.json();

    return token;
  });

  const selectVoice = useCallback((voices, activity) => { 
    return activity.locale === 'zh-HK'
      ? voices.find(({ name }) => /TracyRUS/iu.test(name))
      : voices.find(({ name }) => /JessaNeural/iu.test(name)) ||
        voices.find(({ name }) => /Jessa/iu.test(name))
  }, []);

  const webSpeechPonyfillFactory = useMemo(() => createCognitiveServicesSpeechServicesPonyfillFactory({
    authorizationToken: handleRequestSpeechToken(),
    region: 'westus2'
  }), []);

...

  return (
    <div className="minimizable-web-chat">
      ...
      {loaded && (
        <div className={classNames(side === 'left' ? 'chat-box left' : 'chat-box right', minimized ? 'hide' : '')}>
          ....
          <WebChat
            className="react-web-chat"
            onFetchToken={handleFetchToken}
            selectVoice={selectVoice}
            store={store}
            styleSet={styleSet}
            token={token}
            webSpeechPonyfillFactory={webSpeechPonyfillFactory}
          />
        </div>
      )}
    </div>
```

**Comment by pastapure** [comment]
Thank you very much dear ! its working fine...
