### ISSUE TITLE
Network errors when posting messages

### ISSUE THREAD

**Issue by stephaneey** [Microsoft/BotFramework-WebChat#288]
Hi,

When using the webchat control (this one or the online one), one encounter network errors when posting new messages that need more time than the allocated time (5 seconds by default). Here is a trace of a debugging session:

history action Object {type: "Send_Message", activity: Object}
botchat.js:21793 history action Object {type: "Send_Message_Try", clientActivityId: "1484323244757.3722033363586965.0"}
botchat.js:21793 postActivity Object {type: "message", text: "blabla", from: Object, locale: "fr", timestamp: "2017-01-13T16:00:59.202Z"…}
botchat.js:21793 history action Object {type: "Show_Typing", activity: Object}
botchat.js:21793 history action Object {type: null}
botchat.js:21793 history action Object {type: "Receive_Message", activity: Object}
botchat.js:21793 history action Object {type: "Clear_Typing", id: "BbmRWIVGy2xKWuy4cd3EBX|9n6SgL8Iwm"}
botchat.js:21793 history action Object {type: null}
botchat.js:21793 history action Object {type: "Send_Message_Succeed", clientActivityId: "1484323244757.3722033363586965.0", id: "retry"}
botchat.js:21793 history action Object {type: null}
botchat.js:21793 history action Object {type: "Receive_Sent_Message", activity: Object}activity: Objecttype: "Receive_Sent_Message"proto: Object

and here is a screenshot of the network traffic:

![webchat1](https://cloud.githubusercontent.com/assets/2558877/22067703/a8c92858-dd92-11e6-8984-21434776336c.png)

When increasing the timeout value, I don't see such behavior anymore.

Best Regards

**Comment by billba** [comment]
Thank you for this report. Turns out (who knew?) that the node SDK is asynchronous but the C# SDK is synchronous. Direct Line gives the bot 15 seconds to respond, so I have increased the timeout to 20 seconds in the next release to be safe.
