### ISSUE TITLE
Narrow formatting of card responses in embedded version

### ISSUE THREAD

**Issue by gsoper78** [microsoft/BotFramework-WebChat#2885]
We're embedding https://webchat.botframework.com/embed/ in a mobile app and I'm observing that card responses are formatted unnecessarily narrowly compared to returned answers. The following screenshot should illustrate my point:

![webchat botframework com_embed_CivicaConferenceApp-Bot_s=jHBNXGn94l0 RjR1uvEaNdZYQfAzrG1dOVffZJMPRNESIImobKdAeJg(iPhone X)](https://user-images.githubusercontent.com/36729859/73945128-ba664380-48eb-11ea-90db-c8fc5022f7a5.png)

To reproduce this in Chrome, enter Developer Tools, set the device to iPhone X and then ask a question which yields a card with suggested questions. These questions should be reasonable long e.g. "Reasonably long test question 1" and be associated with long answers as per the screenshot.

This behaviour means that card suggestions are often truncated and therefore ambigious (as per the screenshot). If the cards were formatted to the same width as the answers, this ambiguity would often be removed.

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by corinagum** [comment]
Hi @gsoper78, 
Based on your screencaps, you are using the deprecated v3 of Web Chat which is no longer supported beyond security fixes. 

I recommend you migrate to v4, where you can use the CDN or npm package of Web Chat to customize your Adaptive Card hostconfig to wrap button title text in the card. Please see the following: https://github.com/microsoft/AdaptiveCards/issues/3416

Please note that embedding (v4) does not allow for the same level of customization that you are looking for. https://github.com/microsoft/BotFramework-WebChat#customize-web-chat-ui

**Comment by corinagum** [comment]
I have added this question to the Web Chat FAQ list regarding changing the length of button title in Adaptive Cards. Closing this issue as answered.
