### ISSUE TITLE
Add groupAvatar to styleOptions

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#2901]
When a bot needs to share a large chunk of information, I like to send it in short messages (with a typing indicator) to feed the information to the user in a gentle, natural way.

Currently I am able to not show the timestamp with every message. The Avatar however is shown with every message in one turn. It would be better if it is shown only with the last message of the bot.

Example:

![image](https://user-images.githubusercontent.com/23032884/74428447-4c74cb80-4e59-11ea-8646-ed10b3cdefad.png)

**Comment by stevkan** [comment]
Hi @HesselWellema, this is possible largely by manipulating the DOM directly. I should warn you that this is not recommended as future changes in Web Chat could result in changes to the surrounding Web Chat elements.

For this to work, you will be using Web Chat's `styleOptions` and `activityMiddleware`.

As you can see below, `styleOptions` is used to preserve the location and shape of the avatar space. I don't want to hide it as it will not be accessible to the code that comes after. Therefore, I will pass empty initials so the avatar renders and then set the color to transparent.

```js
const styleOptions = {
  botAvatarInitials: ' ',
  botAvatarBackgroundColor: 'transparent',
  userAvatarInitials: ' ',
  userAvatarBackgroundColor: 'transparent'
}
```

For the `activityMiddleware`, I am using this only for tracking when new activities arrive and from whom. I need to filter the activity by sender and then select the element that is carrying the most recent activity, via `querySelectorAll`, and then match on the last item in the collection. I pass in the html that will render my avatar by replacing the transparent "placeholder" with the new. It's necessary to wrap it in a new `div` that has styling allowing the avatar to be set at the bottom of a transcript activity (for cards, and the like). All of this is copied back into the original avatar element overwriting it in the process. In this way, we have inserted the necessary div, avatar code, and styling into Web Chat.

Note the `setTimeout` placed within the `activityMiddleware`. Without it, Web Chat renders too fast for the middleware to keep up and can't perform the above updates. The timeout is set to 300 ms. Any shorter and the middleware performs the updates badly or not at all, in my testing.

```js
const activityMiddleware = () => next => card => {
  const { activity: { from, from: { role } } } = card;
  setTimeout(() => {
    if (role === 'user') {
      const listItems = document.querySelectorAll( '.from-user.avatar' );
      const listLen = listItems.length - 1;
      let avatarHTML = listItems[ listLen ];
      let wrapperDiv = avatarHTML
      wrapperDiv.innerHTML = '<div aria-hidden="true" class="css-1gu5p96 from-user avatar" style="margin: 0 0 20px 10px"><div class="css-1tdb3h1 image" style="height: 40px; width: 40px; background-color: black; border-radius: 20px;"><img alt="" src="./me40.jpg"></div></div>'
      let parent = avatarHTML.parentElement;
      wrapperDiv.outerHTML = `<div style="display:flex; align-items:flex-end">${ avatarHTML.innerHTML }</div>`
      avatarHTML = wrapperDiv;
    } 
    // else
    if (role === 'bot') {
      const listItems = document.querySelectorAll( 'div:not(.from-user).avatar' );
      const listLen = listItems.length - 1;
      let avatarHTML = listItems[ listLen ];
      let wrapperDiv = avatarHTML
      wrapperDiv.innerHTML = '<div aria-hidden="true" class="css-1gu5p96 avatar" style="margin: 0 10px 20px 0"><div class="css-1tdb3h1 image" style="height: 40px; width: 40px; background-color: black; border-radius: 20px"><img alt="" src="./bot40.jpg"></div></div>'
      let parent = avatarHTML.parentElement;
      wrapperDiv.outerHTML = `<div style="display:flex; align-items:flex-end">${ avatarHTML.innerHTML}</div>`
      avatarHTML = wrapperDiv;
    }
  }, 300);

  return next(card)
}
```

Lastly, pass the `styleOptions` and middleware into the renderer.

```js
window.ReactDOM.render(
  <ReactWebChat
    activityMiddleware={activityMiddleware}
    directLine={ window.WebChat.createDirectLine({ token }) }
    styleOptions={styleOptions}
  />,
  document.getElementById('webchat')
);
```

![avatarGrouping](https://user-images.githubusercontent.com/18403946/74492013-4e9f5000-4e82-11ea-98c2-9023b4bdb177.gif)

Hope of help!

**Comment by HesselWellema** [comment]
Hi @stevkan,
Thank you! This looks pretty straightforward and  fun to implement.
One short question if you allow me: classes like "css-1gu5p96" look random to me. How are they created?
