### ISSUE TITLE
Is there a possibility to send a conversationUpdate activity using webChat?

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-WebChat#2909]
I know I can send messages and events using webchat's store dispatch() method.
Is there a possibility to send conversationUpdate activity?

Any documentation available related to the webChat store features?

**Comment by tdurnford** [comment]
Take a look at https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md
