### ISSUE TITLE
Test: Change timeout to 20s from 60s to fail faster

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2910]
## Feature Request

Most tests right now finish within 10 seconds and the maximum time is 13 seconds.

I think it make sense to lower it from 60s to 20s. So, if a test failed waiting for some elements, it will fail at 20s. If multiple tests are failing, we will see the result 3x faster.

![image](https://user-images.githubusercontent.com/1622400/74600992-b950b700-504d-11ea-8850-b6d06c48698f.png)

[Enhancement]

**Comment by corinagum** [comment]
As long as it doesn't cause more timeouts.. :/

**Comment by corinagum** [comment]
Closing this as resolved.
