### ISSUE TITLE
Adaptive card rendered in webchat V4 needs to remove or update

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2911]
hi Team,

hope you are doing good. i need a feature to use in web chat for adaptive card.
here is the summary:-
1. user said "want to give feedback".
2. bot rendered an adaptive card in web chat for getting input from user.
3. user filled the values and clicked on submit.
4. now here what i am doing is like bot sending another new adaptive card with same values user have entered and asking for if you want to update some value and then final submit.
5. here in this situation i am rendering the same adaptive card twice with some extra parameter.
6. as in teams there is a functionality for updating the same adaptive card but in web chat i don't have any options.
7. i want to know how could i make it done in single adaptive card.

**Thought Process:-**
---------------------------
**"My thought process is like if i will be able to send some custom values from bot side to render in adaptive card as a hidden value while rendering into web chat. onclick of 1st submit i will be preparing for sending the new adaptive card but before rendering the another adaptive card in web chat, i will check for the existing adaptive card with existing hidden value, if it is present then remove the existing card and render new adaptive card."**

if in anyways it is possible please do let me know at the earliest, any code snippet will be truly appriciated.
**FYI**
 i am not using react web chat.

thanks:-
Brad.

**Comment by tdurnford** [comment]
@Bradrajkumar Direct Line does not support currently support updating or deleting an Activity in the conversation. Take a look at https://github.com/microsoft/BotFramework-WebChat/issues/2426 for more details.
