### ISSUE TITLE
simple-update-In.production.min.js stops working.

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2920]
hi Team,

i am very curious to know that all of a sudden this cdn link stops working and it is showing some kind of message while opening in browser.
here is the attached image: -
![Screenshot (22)](https://user-images.githubusercontent.com/34365788/74813270-2056c000-531b-11ea-879d-26472f42edfc.png)

even the example in github is giving 404 not found error for mockbot.
please help me out with this as soon as possible.

**Comment by carlosscastro** [comment]
@tdurnford could you please take a look?

**Comment by tdurnford** [comment]
@Bradrajkumar It appears to be working fine. Can you please check again and let me know if you are still experiencing the same behavior..

### Screenshot
![image](https://user-images.githubusercontent.com/17039790/74865049-63a63400-5305-11ea-986b-d33efc218541.png)

### Additional context
https://unpkg.com/simple-update-in/dist/simple-update-in.production.min.js

**Comment by Bradrajkumar** [comment]
no thank you @tdurnford it starts working after 5 mins when i raised the issue.
