### ISSUE TITLE
Update README and clarify userID generation

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-WebChat#2921]
## Describe the bug
I have spoken to some people who faced the same problem where there user state was shared, because they just used the example from [README.md](https://github.com/microsoft/BotFramework-WebChat/blob/master/README.md#integrate-with-javascript). This example already states that `userID` is an optional parameter, however it doesn't clearly state that sharing user state is a security risk. Many people use `YOUR_USER_ID` as a token..

[Example SO question](https://stackoverflow.com/questions/60275061/azure-bot-authentication-from-different-machines/60296589)

Could we possibly make this more clear?

**Comment by corinagum** [comment]
@iMicknl, thanks for the suggestion. I agree that this seems to be a common pain point so we should make the information readily available. 

For now, I'm going to add this to our FAQ list, and I've assigned the issue to myself. This won't be a part of our current milestone, but hopefully I can get the docs updated soon!
