### ISSUE TITLE
Z-index not working when deployed on to a dynamics web portal

### ISSUE THREAD

**Issue by vksantoshsunny** [microsoft/BotFramework-WebChat#2924]
## Screenshots

![image](https://user-images.githubusercontent.com/26269568/74877600-95cd9980-53ca-11ea-93f1-176e043e3102.png)

As per the screenshot the chat component is not on top of the footer. I have checked the z-index if thee are any and none of the components on the dynamics 365 portal have a z-index. Not sure how the bot component end up behind the other components.

**Comment by compulim** [comment]
Web Chat don't use `z-index`. We are a component and we are forbidden to use something that cannot be scoped in the container, e.g. `z-index` and `tabindex` are both forbidden to us.
