### ISSUE TITLE
Speech service is giving error

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#2925]
hi team,

i don't know why this unexpected behavior i am facing in speech service.
here is the screenshot for the same:- 
![Screenshot (23)](https://user-images.githubusercontent.com/34365788/74902859-5785a980-53cd-11ea-9d90-625d15b0ba4b.png)
clicking on mic is giving this error on chrome in normal mode and in incognito mode and on edge also. 
i am using the es5 bundle of webchat.js file. Even also the speech service link on git hub for checking on mockbot is also giving 404 error. request you to look into it and help me out with it at the earliest.

**Comment by prashanthsridhar** [comment]
Have you used this
`this.audioConfig = this.speechSDK.AudioConfig.fromDefaultMicrophoneInput();`

**Comment by Bradrajkumar** [comment]
here is the code snippet i am using : -

![Screenshot (24)](https://user-images.githubusercontent.com/34365788/74906072-eb5b7380-53d5-11ea-9a75-a604c878c0f6.png)

**Comment by prashanthsridhar** [comment]
i had a similar problem but then i realized my system mic was faulty. Check if the mic is properly setup.
This might be the issue.

**Comment by stevkan** [comment]
@Bradrajkumar, did the suggestion from @prashanthsridhar fix your issue?

To be clear, the `AudioSourceErrorEvent` error is produced from within Cognitive Services Speech which Web Chat utilizes, but does not own. It seems to suggest, as mentioned in the attached image, a device error on your machine.

**Comment by Bradrajkumar** [comment]
I got it ... my bad.... I was using faulty microphone.
