### ISSUE TITLE
Sending the ChannelData with postActivity method from JavaScript

### ISSUE THREAD

**Issue by v-madhal** [microsoft/BotFramework-WebChat#2927]
Hi,
I am using the Bot WebChat V3 version in my project. I am getting an exception in of of my scenario where BOT receives the ChannelData as null from the webchat framework from the JavaScript file. After doing a lot of analysis, I came to know that WebChat is not sending the channel specific data to the bot framework and hence the scenario is failing.

So I simply want to get existing ChannelData from the previous request and attach it to postActivity method and send it to BOT Post method in MessageController.

```js
const botConnection = new BotChat.DirectLine({ token: <secret added here> });

BotChat.App({
        botConnection: botConnection,
          user: { name: 'TestUser', id: '@userId'},
        bot: { id: 'botid' },
          resize: 'detect',
          showUploadButton :false
        }, document.getElementById("bot"));

botConnection.postActivity({ type: "message", from: { name: 'TestUser', id: '@userId'}, name: "handleButtonClick" }).subscribe(function (id) { console.log("Button click activity invoked") });
```

(Edited by @compulim for code formatting)

**Comment by dmvtech** [comment]
Closing this for now. Working with @v-madhal through email.
