### ISSUE TITLE
Normal https://webchat.botframework.com stopped working in IE 10. syntax error webchat-es5.js

### ISSUE THREAD

**Issue by nvikey** [microsoft/BotFramework-WebChat#2940]
I am using sdk v4 bot embedded in sharepoint 2016 page using iframe webchat https://webchat.botframework.com/embed/.......... url. It stopped working in IE 10. I remember it worked before 3 weeks. Please help as we put the bot in production.

**Comment by dmvtech** [comment]
Are there errors in the browsers developer tools console? If so, can you please share those?

**Comment by nvikey** [comment]
The error was one line.
Syntax error at webchat-es5.js

**Comment by nvikey** [comment]
Please help. I checked below code too. It still did not work. My production bot is impacted. I want to work in IE 10.


<!DOCTYPE html>
<html>
   <head>
      <meta http-equiv="X-UA-Compatible" content="IE=10">
      <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"/>
	  <script src="https://cdn.botframework.com/botframework-webchat/4.2.0/webchat-es5.js"/>
   </head>
   <body>
      <div id="webchat" role="main"></div>
      <script>
         window.WebChat.renderWebChat(
            {
               directLine: window.WebChat.createDirectLine({
                  token: ''
               }),
            },
            document.getElementById('webchat')
         );
      </script>
   </body>
</html>

**Comment by ksuchy** [comment]
Running into the same issue. Getting similar syntax error / exception in console logs as nvikey. Please help as this is impacting production.

**Comment by nvikey** [comment]
I got to know something from F12 -> Network in IE browser. 

All urls from botframework.com like conversations, acitivity, js and css files are getting redirected to something called gateway.zscloud.net. I donno what it it is or is it related to bot?

If it is some proxy, does botframework.com support request from such proxies?

![redirect2](https://user-images.githubusercontent.com/30201557/75447571-a9ab6980-598f-11ea-9fda-cf80c848af72.PNG)
![redirect1](https://user-images.githubusercontent.com/30201557/75447580-aca65a00-598f-11ea-8da1-daa9356a22b9.PNG)

**Comment by dmvtech** [comment]
Webchat is not supported with IE10. Per Bill's answer [here](https://stackoverflow.com/questions/60378733/normal-https-webchat-botframework-com-stopped-working-in-ie-10-syntax-error-w), you can try and host your own build of webchat (es5) and to see if you can remedy/workaround the issue. Additionally, you can message @p-nagpal to put your bot in as an exclusion to see if that would remedy the issue.

Does it work without issue in IE11?

**Comment by nvikey** [comment]
Yes, webchat iframe works without issue in IE 11. 

Other channels like directline channel does not work for us, because conversation & other cdn files from botframework domain are not working with zscaler proxy in our organization. Does botframework urls support zscaler proxy?

![redirect2](https://user-images.githubusercontent.com/30201557/75547895-f5bee280-5a51-11ea-902e-8a23d3d76492.PNG)

**Comment by dmvtech** [comment]
There are no specific implementations around zscalar. You can try hosting your own webchat instead of using the CDN. 

As IE10 is not supported, I am closing this issue.
