### ISSUE TITLE
Typing indicator should not show up on oneself

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2942]
Probably related to recent typing indicator PR #2912.

## Version

`master` as of today.

## Describe the bug

When `sendTyping` is set to `true`, the typing indicator should not show up for oneself.

## Steps to reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/05.custom-components/b.send-typing-indicator/
1. Type something

## Expected behavior

The typing indicator should not show up.

Today, the typing indicator show up.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
@compulim I don't believe there is an issue with the typing indicator. The `echo typing` command makes Mock Bot echo typing activities sent from the user, so the typing activities that are being displayed are for the bot - not the user. If you set `sendTypingIndicator` to true and don't send the the `echo typing` command, the typing indicator is not displayed when the user types.

It should be noted that `sendTypingIndicator` has been removed and the [Send Typing Indicator](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/b.send-typing-indicator) sample should be updated to use `styleOptions.sendTyping`.
