### ISSUE TITLE
Azure Gov WebChat: Cognitive Speech API points to commercial

### ISSUE THREAD

**Issue by AngryVirginian** [microsoft/BotFramework-WebChat#2969]
## Screenshots

![image](https://user-images.githubusercontent.com/28601813/75733722-06768f00-5cc4-11ea-9839-f064cd6b2a9b.png)

## Version

4.7.1 (through NPM)

## Describe the bug

The bot is hosted in Microsoft Azure Government (MAG). Cognitive Speech API in webchat always points to the commercial endpoint.  E.g., wss://virginia.stt.speech.**microsoft.com** instead of wss://virginia.stt.speech.**azure.us** as stated in [this link](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/sovereign-clouds#azure-government-united-states). This is regardless of using "virginia" or "usgovvirginia" as the region parameter when constructing webSpeechPonyfillFactory.

## Steps to reproduce

1. Obtain an authorization token from https://virginia.api.cognitive.microsoft.us/sts/v1.0/issuetoken
2. Use the token to construct webSpeechPonyfillFactory
`
     let webSpeechPonyfillFactory = await 
     window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
                  region: 'virginia',
                  authorizationToken: [token]
              });
`
3. Render the webchat
`
     window.WebChat.renderWebChat({
                  directLine: directLineConnection,
                  webSpeechPonyfillFactory,
                  styleOptions
              }, document.getElementById('webchat'));
              document.querySelector('#webchat > *').focus();
`
4. Click the microphone button on the webchat.
5. Check the F12 tool.  Will see error similar to below

webchat.js:2 WebSocket connection to 'wss://virginia.stt.speech.microsoft.com/speech/recognition/conversation/cog…eDgZQpkgwBxsstyCZPdzuuAOLA&X-ConnectionId=5E0ACF9313A64E9BB689DE97C939CC44' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

## Expected behavior

Speech data is successfully transported from webchat to Cognitive Speech API in MAG.

**Comment by corinagum** [comment]
@AngryVirginian, could you share your `directLineConnection` code? Does it have `domain` assigned?

**Comment by corinagum** [comment]
@p-nagpal is there a rep from the service side who could help with Azure Gov issues?

**Comment by p-nagpal** [comment]
We have opened [this issue](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/154)  to get advice from cognitive-services-speech-sdk-js about the STT endpoints.

**Comment by p-nagpal** [comment]
@compulim , could you help add the FromHost solution to WebChat (see the [related speech SDK issue](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/154))

**Comment by compulim** [comment]
Start working on it now.

Will implement the `fromHost` solution.
