### ISSUE TITLE
Large file size of botchat.js

### ISSUE THREAD

**Issue by McGern** [Microsoft/BotFramework-WebChat#297]
Hi,

Thanks for opening this code up for us to use.

Just wondering about the end file size of botchat.js. It is coming out around 478kb (168 gzipped), which seems quite large given the built files are only ~74kb. I am assuming (given my limited knowledge of the setup) that the rest it taken up by react and tslib?

Is this the smallest the file will get, or are there some additional developer tools still in this release?

Thanks,
Jarrod

**Comment by billba** [comment]
There are no extraneous libraries in there. You can see all the culprits in package.json -- react, rxjs, redux, and some smaller connector libraries. 

If you're already building a react app, you shouldn't use botchat.js. Instead, link in the built files so you don't double up on the react libraries

**Comment by McGern** [comment]
Thanks for the reply. Unfortunately, I cannot guarantee that react will be installed as this webchat may be a 3rd party website.

**Comment by billba** [comment]
Some good news coming. Looks like I'll be able to chop out > 100k by only including the parts of rxjs we actually use. I'll continue to look for ways to chop this down.

**Comment by billba** [comment]
As promised, down to 336k in the production (`npm run prepublish`) build, which is respectable. This will be in Friday's release.

Closing this issue -- I don't know of any other places to cut!

**Comment by McGern** [comment]
Wow. Thanks for doing that, I hadn't expected a response so quickly.
