### ISSUE TITLE
#2842 isn't fixed

### ISSUE THREAD

**Issue by asvishnyakov** [microsoft/BotFramework-WebChat#2971]
I can't reopen issue in this repository, so I just will create new one. Everything described in #2842 is still be actual, no changes in packages deployment

**Comment by corinagum** [comment]
Thanks for letting us know, @asvishnyakov. I have reopened the original issue and will close this one as a duplicate. 

@CoHealer, I assigned @stevkan to the #2842; FYI.

**Comment by CoHealer** [comment]
Ack, thx @corinagum
