### ISSUE TITLE
mic not getting turned off automatically

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#2975]
## Version

Using webchat.js 4.7.0
Using it in angular

## Describe the bug

Mic should get turned off after 5-10s of no input. That was happening till February. Now it just keeps the mic on.

## Steps to reproduce

Click on mic , it just does'nt turn off

## Expected behavior

mic turns off after 5s of no input

**Comment by stevkan** [comment]
Has anything changed in the project regardless of how small, recently? I just tested an angular app I have that has web chat and speech integrated into it and it is working normally.

Can you post the speech and directline components so I can see how you are implementing?

**Comment by prashanthsridhar** [comment]
Hi @stevkan , there are no changes as such. I verified it with a sample project using 4.7 and 4.8,the issue still exists

**Comment by stevkan** [comment]
@prashanthsridhar, are you able to post any of your code (see the above requests)? There isn't much I can do without something to reference.

**Comment by congysu** [comment]
close this for now due to lack of activities recently.
