### ISSUE TITLE
Do not see a Greet message in WebChat control 

### ISSUE THREAD

**Issue by AnandChitale** [Microsoft/BotFramework-WebChat#298]
Cretaed a bot and deployed it to azure.
Enabled Web Chat for the bot.

But when a hit the url for bot in browser , there is no greet message from bot as described in documentation.
![greet](https://cloud.githubusercontent.com/assets/24295647/22236037/1103b59c-e229-11e6-81e6-6fc62d12f414.png)

**Comment by billba** [comment]
That is an image from the previous WebChat. We now recommend that your bot give its own greeting, that way it can be customized (and localized) to your needs.

**Comment by danmarshall** [comment]
@AnandChitale when you are getting the Embed code from the BotFramework dev portal, please be sure to check the "Enable Preview" checkbox to see this latest WebChat control.
