### ISSUE TITLE
RFC: Update to CSS BEM system

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2988]
## Feature Request

Update to CSS BEM system.

### Proposed CSS

```css
.webchat__sendBox {
}

.webchat__sendBox .webchat__sendBox__envelopeButton {
}

.webchat__sendBox .webchat__sendBox__envelopeButton:focus,
.webchat__sendBox .webchat__sendBox__envelopeButton:hover {
}

.webchat__sendBox .webchat__sendBox__textInput {
}

.webchat__sendBox .webchat__sendBox__textInput.webchat__sendBox__textInput--multiline {
}

.webchat__sendBox .webchat__sendBox__uploadFileInput:focus + .webchat__sendBox__uploadButton,
.webchat__sendBox .webchat__sendBox__uploadFileInput:hover + .webchat__sendBox__uploadButton {
}
```

### Notes

- Block name is always prefixed with `webchat__`
   - For example, block name for send box is `webchat__sendBox`
- Use `camelCasing`
- No more `.parent > .child`
   - Only 1 level deep
   - 90% of rules should be either one of the following:
      - `.webchat__block`
      - `.webchat__block .webchat__block__element`
      - `.webchat__block .webchat__block__element:hover`
      - `.webchat__block .webchat__block__element.webchat__block__element--modifier`
      - `.webchat__block .webchat__block__element.webchat__block__element--modifier:hover`
   - Okay to have `.parent input[type="file"].fileInput:hover + .buttonOverlay`
      - This is used for hiding the default appearance of `<input type="file">` and build a custom appearance out of it, *mainly used for stealing `:focus` and `:hover`*
      - `.webchat__block .webchat__block__fileInput:hover + .webchat__block__buttonOverlay`
- Use pseudo class (`:hover`) instead of modifier as much as possible (`--hover`)
- This will resolve the CSS insertion points feature (#2389)
- Do not use CSS query selector for `min-width`, `max-width`
   - Web Chat is component inside a web page, we don't control/know/care about the size of hosting page
   - We can use `print` or `screen`

### Written in Glamor

```js
css({
  '.webchat__sendBox': {
    '& .webchat__sendBox__envelopeButton': {
      '&:focus, &:hover': {
      }
    },

    '& .webchat__sendBox__textInput': {
      '&.webchat__sendBox__textInput--multiline': {
      }
    },

    '& .webchat__sendBox__uploadFileInput': {
      '&:focus, &:hover': {
        '& + .webchat__sendBox__uploadButton': {
        }
      }
    }
  }
});
```

[Enhancement]

**Comment by corinagum** [comment]
This has been implemented.
