### ISSUE TITLE
[Accessibility][Screen Reader] [NVDA] - Screen reader reads all the dialog from the beginning on any state update

### ISSUE THREAD

**Issue by Valentyn-Chornovol** [microsoft/BotFramework-WebChat#2997]
![sreenreader](https://user-images.githubusercontent.com/62014745/76325300-d34d8480-62ef-11ea-947a-b689481d30c6.gif)

**Actual result:**
The screen reader reads all the dialog from the beginning on any state update.

**Expected result:**
The screen reader will read the latest message.

**Repro Steps:**
1. Turn on NVDA.
2. Open https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/ in Chrome.
3. Type and send a message.

**Comment by compulim** [comment]
Dupe of #3047.

This is related to a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1067257 and an NVDA bug.
