### ISSUE TITLE
[Accessibility][Screen Reader] [NVDA] - Screen reader ignores "File", "New Messages" and "Send" buttons on hover

### ISSUE THREAD

**Issue by Valentyn-Chornovol** [microsoft/BotFramework-WebChat#2999]
![sreenreader](https://user-images.githubusercontent.com/62014745/76327464-b5cdea00-62f2-11ea-84b1-b8f6467e2b21.gif)

**Actual result:**
The screen reader ignores "File", "New Messages" and "Send" buttons on hover.

**Expected result:**
The screen reader will read "File", "New Messages" and "Send" buttons on hover.

**Repro Steps:**
1. Turn on NVDA.
2. Open https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/ in Chrome.
3. Hover the cursor on "File", "New Messages" and "Send" buttons.

**Comment by compulim** [comment]
Dupe of #3048.
