### ISSUE TITLE
[Accessibility][Screen Reader][JAWS] - Not working correctly with the webchat

### ISSUE THREAD

**Issue by omega1119** [microsoft/BotFramework-WebChat#3000]
## Version

OS : WIN 10
Browser : Chrome
Tools: JAWS
Webchat Version : "4.8.0"

## Describe the bug

The issue we are having is that the AT users in our organisation all use JAWS and unfortunately it doesn't look like it is currently supported

https://github.com/microsoft/BotFramework-WebChat/issues/2237#issuecomment-570383572

additionally it's not possible for our users to use the other suggested screen readers.

When our AT users interact with the webchat, JAWS reads all the messages in the chat in order from start to finish, with no way to select individual chat responses. 

Additionally to link to this issue

https://github.com/microsoft/BotFramework-WebChat/issues/2996

being able to navigate the utterances in the chat window is very much needed. 

Is support for JAWS something that we can expect in the future?

Thanks

**Comment by compulim** [comment]
This is fixed in #3287.
