### ISSUE TITLE
CSS forces WebChat to fill entire web page

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#302]
When we first created our CSS the assumption was that WebChat would always be IFRAMEd, so this makes sense. But now it's clear that most folks can just include the .css and .js from the CDN and call BotChat.App() to create a chat inline, with no IFRAME required. When you do this, the WebChat fills the entire page, not just the DIV that it's in.

**Comment by billba** [comment]
As a workaround, I'm currently adding this after including botchat.css:

```
<style>
    .wc-chatview-panel {
        width: 320px;
        height: 500px;
        position: relative;
    }
</style>
```

**Comment by danmarshall** [comment]
wouldn't this prevent the Iframed version from taking the entire window?

**Comment by danmarshall** [comment]
In practice there are still some issues with this... The CSS rules on the rest of the page spill into the web chat control. For example, H1 H2 H3 type sizes in markdown.
