### ISSUE TITLE
Startup errors (unexpected token and babel related)

### ISSUE THREAD

**Issue by asifshiraz** [microsoft/BotFramework-WebChat#3020]
## Screenshots

![image](https://user-images.githubusercontent.com/7054246/76700255-b87a6780-6683-11ea-89f0-b40921af66b1.png)

## Version

Latest master branch from repository

## Describe the bug

Running npm start gives multiple errors.
1. Unexpected token in Avatar.js
2. Unexpected token in AdaptiveCardsComposer.js
3. Some babel related errors that I don't understand... also a warning that node modules missing, even though I ran npm install before execution.

## Steps to reproduce

1. Clone latest rep
2. Add "npm install --save-dev serve" (per a previous issue discussion)
3. Run npm install
4. Run npm start
5. See error

## Expected behavior

Application should start

[Bug]

**Comment by compulim** [comment]
Since Web Chat is a monorepo, between step 3 and 4, you need to run `npm run bootstrap`.

**Comment by corinagum** [comment]
Closing as answered
