### ISSUE TITLE
User message displaying(shortly) above bot message

### ISSUE THREAD

**Issue by uppalapraveen** [microsoft/BotFramework-WebChat#3023]
Here are the screenshot link.

https://user-images.githubusercontent.com/18583823/56056255-0bd88d00-5d32-11e9-9454-49436d950741.png

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

User messages are displayed at the top while they are sent. We are using WebChat (https://cdn.botframework.com/botframework-webchat/latest/webchat.js)

@corinagum There is a ticket which you have closed based on  @Slayouth comments.
here is the issue link https://github.com/microsoft/BotFramework-WebChat/issues/1890
Could you please help me out with solution of this issue.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by cwhitten** [comment]
hello @uppalapraveen. Please refer to the following issue for tracking: https://github.com/microsoft/BotFramework-WebChat/issues/2991

We are prioritizing this fix against our backlog and will update that issue when we schedule the work. Closing this as a duplicate.
