### ISSUE TITLE
Wrong link attribute

### ISSUE THREAD

**Issue by osavoskin** [microsoft/BotFramework-WebChat#3026]
https://github.com/microsoft/BotFramework-WebChat/blob/31291d588e782bdef63d8f37ae01e81ea54cfd87/packages/bundle/src/renderMarkdown.js#L75

Should not be 'rel' here?

**Comment by compulim** [comment]
You are right.

Correct: `<a href="..." rel="nooopener noreferrer">`

Wrong: `<a href="..." target="nooopener noreferrer">`
