### ISSUE TITLE
Bot will only speak when spoken to

### ISSUE THREAD

**Issue by jbgh2** [microsoft/BotFramework-WebChat#3029]
## Version

Browser version:
meta name="botframework-directlinespeech:version" content="4.8.0"
meta name="botframework-webchat:bundle:variant" content="full"
meta name="botframework-webchat:bundle:version" content="4.8.0"
meta name="botframework-webchat:core:version" content="4.8.0"
meta name="botframework-webchat:ui:version" content="4.8.0"

Using SpeechService added via:

    (async function() {
      const token  = '{{ dl_token }}'

      // Create the ponyfill factory function, which can be called to create a concrete implementation of the ponyfill.
      const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
        textNormalization: 'lexical',
        authorizationToken: '{{ sp_token }}',
        region: '{{ region }}'
      });

      // Pass a Web Speech ponyfill factory to renderWebChat.
      // You can also use your own speech engine given it is compliant to W3C Web Speech API: https://w3c.github.io/speech-api/.
      // For implementor, look at createBrowserWebSpeechPonyfill.js for details.
      window.WebChat.renderWebChat(
        {
          directLine: window.WebChat.createDirectLine({ token }),
          webSpeechPonyfillFactory,
          userID: 'prt-{{ user_id }}',
          username: 'Student',
          locale: 'en-US',
        },
        document.getElementById('webchat')
      );

      document.querySelector('#webchat > *').focus();
    })().catch(err => console.error(err));
</script>

Tokens etc. are generated in a Django app and added via a template hence the {{ variable }} statements.

The system uses both LUIS and Speech Services.

Bot is written in C# and all outputs have a spoken component.

## Describe the bug

Bot will only respond with speech if the input is spoken, even if the user speaks first (#2474), subsequent input must be audio for the bot to respond with audio.
Written input, or input from a card, only results in text output, even if the user has spoken earlier in the conversation.

## Steps to reproduce

1. Create a speech enabled webchat channel following https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/c.cognitive-speech-services-with-lexical-result

2. Create a bot and generate all Messages using:

        protected static IActivity Speak(string message, string textToShow = null, string language = "en-US", string voice = "JessaRUS")
        {
            var activity = MessageFactory.Text(textToShow ?? message);
            string body = @"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='en-US'>" +
                           $"<voice name='Microsoft Server Speech Text to Speech Voice ({language}, {voice})'>" +
                            $"{message}" + "</voice></speak>";

            activity.Speak = body;
            return activity;
        }

3. Run bot 
4. Type in input to bot, notice the output is not spoken
5. Speak to bot, notice the output is spoken

## Expected behavior

Output of bot is spoken when Speak property of body is set, regardless of mode of input.

## Additional context

I have found #2474 but the bot still will only speak after spoken input even if I get the user to speak first. ie. I ask them to press the button and talk then the next response is spoken but if the input after that is written then the output is not spoken.

[Bug]

**Comment by rosenjcb** [comment]
This is default behavior. I've managed [to trigger the bot to speak according](https://github.com/microsoft/BotFramework-WebChat/issues/3028) to a scenario through the [Microsoft Healthcare Bot](https://docs.microsoft.com/en-us/healthbot/quickstart-createyourfirstscenario) platform.

I have a feeling you'll need to write a dialog for the bot in C#. Can you link your entire Bot class in your C# project?

**Comment by jbgh2** [comment]
My bot is a bit large to post but is made up of dialogs that look like this:

        private async Task<DialogTurnResult> PromptForInputStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            await OutputStepNameToUser(stepContext, cancellationToken);

            return await stepContext.PromptAsync(nameof(TextPrompt),
                new PromptOptions
                {
                    Prompt = this.promptMessage.GetMessageActivity(),
                }, cancellationToken);
        }

Where GetMessageActivity() is:

        public Activity GetMessageActivity()
        {
            var activity = MessageFactory.Text(this.textToShow);

            if (this.spokenMessage != null)
            {
                string body = @$"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='{this.language}'>" +
                               $"<voice name='{this.language}-{this.voice}'>" +
                                $"{this.spokenMessage}" + "</voice></speak>";

                activity.Speak = body;
            }
            return activity;
        }

It's all using code from the samples. What other messages do I need to send?

**Comment by jbgh2** [comment]
I've tried adding a 'WEB_CHAT/START_SPEAKING' message in after every SEND_MESSAGE like this:

      const store = window.WebChat.createStore(
        {},
        ({ dispatch }) => next => action => {
          //console.log(action.type);
          if (action.type === "WEB_CHAT/SEND_MESSAGE") {
            console.log("Sending WEB_CHAT/START_SPEAKING")
            dispatch({
              type: 'WEB_CHAT/START_SPEAKING',
              payload: {
                value: 'webchat/start_speaking',
              }
            });
          }
          return next(action);
        }
      );

But it doesn't work. Is that the right approach?

**Comment by rosenjcb** [comment]
> My bot is a bit large to post but is made up of dialogs that look like this:
> 
> ```
>     private async Task<DialogTurnResult> PromptForInputStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
>     {
>         await OutputStepNameToUser(stepContext, cancellationToken);
> 
>         return await stepContext.PromptAsync(nameof(TextPrompt),
>             new PromptOptions
>             {
>                 Prompt = this.promptMessage.GetMessageActivity(),
>             }, cancellationToken);
>     }
> ```
> 
> Where GetMessageActivity() is:
> 
> ```
>     public Activity GetMessageActivity()
>     {
>         var activity = MessageFactory.Text(this.textToShow);
> 
>         if (this.spokenMessage != null)
>         {
>             string body = @$"<speak version='1.0' xmlns='https://www.w3.org/2001/10/synthesis' xml:lang='{this.language}'>" +
>                            $"<voice name='{this.language}-{this.voice}'>" +
>                             $"{this.spokenMessage}" + "</voice></speak>";
> 
>             activity.Speak = body;
>         }
>         return activity;
>     }
> ```
> 
> It's all using code from the samples. What other messages do I need to send?

This looks correct. I've played around with the WaterfallDialog and it's cumbersome. So what you're showing me is the Dialog class but in the Bot class itself, you'll have a method like `OnMembersAddedAsync()` where you can override it like this to start the conversation off with the bot speaking: 
 
```
        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(MessageFactory.Text("Need help finding something on this page?"));
            await base.OnMembersAddedAsync(membersAdded, turnContext, cancellationToken);
        }
```

You might even be able to to start the dialog itself by calling 
``` 
await _dialog.RunAsync(turnContext, _conversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
``` 
where `_dialog` is a concrete implementation of the `Microsoft.Bot.Builder.Dialogs.Dialog` abstract class.  

Refer to the BotBuilder samples ([this](https://github.com/microsoft/BotBuilder-Samples/blob/24ea48e3fda23d3d8f3707282aba2e33924249c9/experimental/language-generation/csharp_dotnetcore/05.a.multi-turn-prompt-with-language-fallback/Bots/DialogBot.cs) one in particular) for more detailed code.

Quite frankly, this was all too much of a hassle for me (having to hardcode my bot's interactions in C# functions), so I went with what we use already in my team: the Microsoft Healthcare Bot. There you can script scenarios and adding a prompt step is as easy as drag and dropping the prompt icon into the scenario. Enough of the sales pitch though.

**Comment by rosenjcb** [comment]
> I've tried adding a 'WEB_CHAT/START_SPEAKING' message in after every SEND_MESSAGE like this:
> 
> ```
>   const store = window.WebChat.createStore(
>     {},
>     ({ dispatch }) => next => action => {
>       //console.log(action.type);
>       if (action.type === "WEB_CHAT/SEND_MESSAGE") {
>         console.log("Sending WEB_CHAT/START_SPEAKING")
>         dispatch({
>           type: 'WEB_CHAT/START_SPEAKING',
>           payload: {
>             value: 'webchat/start_speaking',
>           }
>         });
>       }
>       return next(action);
>     }
>   );
> ```
> 
> But it doesn't work. Is that the right approach?

So depending on where it fails, you have a few options. First of all, `WEB_CHAT/SEND_MESSAGE` looks like it's when the user sends a message. Just have the webchat connect to the bot and enable that `console.log(action.type)` and see what kind of events are outputted. In particular, I use `DIRECT_LINE/CONNECT_FULFILLED` because I want to trigger the scenario only when the user successfully connects to the bot over websocket. Once you can verify that is triggering, you can make sure your dispatch is actually being sent. Refresh your webchat page and access the network tab in your browser (for here I'll use Chrome as an example): Ctrl-Shift-I -> Network -> click on 'WS' and look at the result that isn't `sockjs-node` or something similar. You should see a websocket stream with messages from the client and bot itself. Check to make sure that your payload is being sent through activities like so:

![image](https://user-images.githubusercontent.com/8102129/77022687-8a2cae80-6947-11ea-8ab5-b97fe5a0aca6.png)

I'll try to explain more tomorrow if all these efforts fail.

**Comment by jbgh2** [comment]
Yep, I have all that connection and member joining goodness. The bot does communicate correctly but the problem is that if you don't use speech input you don't speech output (see #2474). There is a passing reference (https://github.com/microsoft/BotFramework-WebChat/issues/2474#issuecomment-543299098) to sending a redux message (WEB_CHAT/START_SPEAKING) which is what I'm trying to do. 

Enabling the logging gives output like this:

(index):226 WEB_CHAT/SET_SEND_BOX
(index):226 WEB_CHAT/STOP_SPEAKING
(index):226 WEB_CHAT/STOP_DICTATE
(index):226 WEB_CHAT/SUBMIT_SEND_BOX
(index):226 WEB_CHAT/SEND_MESSAGE
(index):237 Sending WEB_CHAT/START_SPEAKING
(index):226 WEB_CHAT/START_SPEAKING
(index):226 DIRECT_LINE/POST_ACTIVITY
(index):226 WEB_CHAT/SET_SEND_BOX
(index):226 DIRECT_LINE/POST_ACTIVITY_PENDING
(index):226 WEB_CHAT/SET_SUGGESTED_ACTIONS
(index):226 WEB_CHAT/STOP_DICTATE
(index):226 WEB_CHAT/STOP_SPEAKING
(index):226 DIRECT_LINE/INCOMING_ACTIVITY
(index):226 WEB_CHAT/SET_SUGGESTED_ACTIONS
(index):226 DIRECT_LINE/INCOMING_ACTIVITY
(index):226 WEB_CHAT/SET_SUGGESTED_ACTIONS
(index):226 DIRECT_LINE/INCOMING_ACTIVITY
(index):226 DIRECT_LINE/POST_ACTIVITY_FULFILLED
(index):226 WEB_CHAT/SET_SUGGESTED_ACTIONS

When you type into the input box you can see that speaking and dictating are disabled.
I'm trying to send a message at the right time to re-enable it 

Thanks for your help :)

**Comment by rosenjcb** [comment]
@jbgh2 Well at this point I'm going to assume all this works well through the Bot Framework Emulator and that you're really just struggling with the webchat client. Based on the reference, it looks like there are issues with the speech capabilities. It looks like someone from the Microsoft team has assigned themselves to your ticket, so good luck!

**Comment by jbgh2** [comment]
@rosenjcb thank you for your time!

**Comment by stevkan** [comment]
@jbgh2, as you already know from the above conversation, the user must have clicked and provided speech input before the bot's text response is spoken back to the user. This requirement extends from the browser and, unfortunately, there is no work-around at this time.

As you are also aware, future development (issue #2211) looks to mitigate this browser requirement with respect to Web Chat. But, at this time there is no specific ETA. Development has been pushed out to R9, however you should consider this as "subject to change".

With regards to the "WEB_CHAT" speech actions you reference further up (for example, 'START_SPEAKING'), these provide a means of responding to specific actions when the user has provided speech input. For example, you may need some page event to fire when the user starts speaking or you want to send an event back to the bot when the user has stopped speaking. In and of themselves, these speech actions do not start or stop the browser speaking any user or bot text.

As you have already commented on the above linked issue, I am going to close this as answered.

**Comment by NereaCabiedasMoreno** [comment]
**Hello, I am trying to change the voice of my bot, to a neural voice, I use Direct Line Speech, but the only thing that achieves is that I use the neural voice for the piece of text that is between the two voice tags voice**

 this.onMessage(async(context, next) => {
                console.log('Running dialog with Message Activity.');
                const speakText =
                    `<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="es-ES">
                    <voice name="es-ES-ElviraNeural">
                    Fragmento de un escrito con unidad temática, que queda diferenciado del resto de fragmentos por un punto 
                    </voice>
                </speak>`;
                await context.sendActivity(MessageFactory.text(speakText));
                await this.dialog.run(context, this.dialogState);
                await next();
            });
