### ISSUE TITLE
Can't specify different production slot endpoint in webchat setup

### ISSUE THREAD

**Issue by jbgh2** [microsoft/BotFramework-WebChat#3030]
I have an App Service with multiple production slots.
I can't find a way to specify which slot to use, either when generating a token or when setting up the RenderWebChat.

**Comment by compulim** [comment]
This is related to hosting the services. Web Chat is the UI component.

Please post it to [botframework-services](https://github.com/microsoft/botframework-services).

**Comment by jbgh2** [comment]
This is a webchat issue: how do you specify the target endpoint in WebChat?
