### ISSUE TITLE
Can this library be used for creating a view of conversation transcript (given a list of activity JSONs)?

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotFramework-WebChat#3032]
We have been storing all the activities (as JSON) of each conversation taken place between our bot and users into our data store. And we have a requirement where we want to build a view that can replay a user's conversation. 

We are not sure if the BotFramework-WebChat library can be used (without giving any bot secret or token) to create this view provided the set of activities JSONs.

We looked at the [presentation mode sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization/e.presentation-mode) which is close to our requirement but can set of activities be provided to create the view and can secret/token be avoided?

Need you help.

**Comment by stevkan** [comment]
@bhushanvadgave, thank you for your patience. I've been researching some potential solutions for you, but before I present those I have a couple questions.

How are users accessing their conversation history? Reading the above suggests to me they are clicking a link on a page which would open a "presentation mode" styled view. Or, is this to be a function of a current conversation with a bot (i.e. "show my conversation history for 12/12/19")?

Is some form of authentication being used to differentiate one user from another?

**Comment by bhushanvadgave** [comment]
@stevkan Conversation replaying capability is not meant to be used by end-users (bot users) but it is used by special (admin) users through a web app (built with ReactJS) that requires the users to authenticate themselves.
Since the web app already has an API that fetches the latest activity JSONs for a conversation ID, it now just needs to have a view that shows the conversation messages (like they appear for end-user in his/her webchat window).

**Comment by cwhitten** [comment]
@bhushanvadgave your scenario appears to be an advanced implementation of the WebChat control that go beyond the scope of our supported samples and documentation. However, I'd guide you to peek into the [Bot Framework Emulator's](https://github.com/Microsoft/BotFramework-Emulator) source code to see how it loads data into the chat control based off of a transcript. It is also React-based and could give you a model to structure your solution after. Instructions on running the development build of the Emulator is [here](https://github.com/microsoft/BotFramework-Emulator/blob/master/CONTRIBUTING.md#how-to-build-from-source).

I'd recommend using StackOverflow for ongoing questions. Closing this for now.
