### ISSUE TITLE
Loading chat history slowly if there are too many images

### ISSUE THREAD

**Issue by shunyh** [microsoft/BotFramework-WebChat#3035]
Hi Team,

I got a performance issue that loading chat history slowly if the customer sent too many images to the bot.

I want to confirm which size is the limitation of the Webchat history would cause this loading 
 performance issue?

If we know the limitation we could remind the customer to create a new session and end the current one.

**Comment by v-kydela** [comment]
@shunyh - It sounds like you're describing a situation where more images lead to slower performance. Can you explain what you mean when you say "limitation"?

**Comment by shunyh** [comment]
@v-kydela 

Thank you quickly reply.

What I want to know is how many images or how many text messages are sent will lead to load chat history slowly?

For example:
The performance of loading history will be slower if the total files size of the chat history more than 10M.
The **10M** is the limitation.

**Comment by v-kydela** [comment]
Hello @shunyh - thank you for the clarification.

I think you will have to judge for yourself what threshold/cutoff/limit you want to use. There doesn't seem to be any such limitation coded into Web Chat or Direct Line. My expectation is that the more bytes you have, the slower they will load.

Does this resolve your issue?

**Comment by shunyh** [comment]
@v-kydela 
Thanks for the updated information.

It seems that the WebChat does not have such a flag to control the loading performance, it requires us to do some related configurations.

Thanks for your help again, @v-kydela

**Comment by v-kydela** [comment]
@shunyh - Glad I could help. Closing now.
