### ISSUE TITLE
Add Backgroundcolor for SendBoxButton to defaultStyleOptions

### ISSUE THREAD

**Issue by psaeuerl** [microsoft/BotFramework-WebChat#3038]
Feature Request

My requirement is to set the BackgroundColor of the sendBoxButton.
Currently, the defaultStyleOptions.js does not support this and i had to fall back to using css selectors.
defaultStyleOptions.js seems to be the natural place for this.

Current solution:
`    #webchat > div > div > div.main > div > button{
        background-color: aqua;
    }`

Desired solution:
`
        const styleOptions = {
            sendBoxButtonsendBoxBackgroundColor: "aqua"
        };
`

**Comment by congysu** [comment]
@compulim can you please take a look on this issue?  thanks.

**Comment by tdurnford** [comment]
@congysu You can currently accomplish this by overriding the `sendBoxButton` styles set. Take a look at the code snippet below and the [Manual Styling](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization/b.idiosyncratic-manual-styles) Web Chat Sample for more details.

@compulim @corinagum @cwhitten What are your thoughts on adding `sendBoxButtonsBackgroundColor` to the default style option and having it default to the `sendBoxBackground` if it's `undefined`?

### Web Chat v4
```javascript
const styleSet = window.WebChat.createStyleSet();
styleSet.sendBoxButton = {
  ...styleSet.sendBoxButton,
  backgroundColor: 'aqua',
};

window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token }),
    styleSet,
  },
  document.getElementById('webchat')
);
```

### Screenshot
![image](https://user-images.githubusercontent.com/17039790/78207587-59786900-745f-11ea-8715-cdba6d7802f3.png)

**Comment by psaeuerl** [comment]
Thank you for your reply!

Our UX Designer also requested to have a change in the send button when hovering.
Do you recommend implementing this via css or via the idosyncratic manual styling (overriding createstylesets)?
Which one is less likely to break?

**Comment by tdurnford** [comment]
I'd recommend the idosyncratic manual styling - it is the least likely to break of the two options.

**Comment by psaeuerl** [comment]
Thanks!

**Comment by CHuijsman** [comment]
> @tdurnford I don't see a problem adding this style option

We are also interested in style options for the sendboxbutton background and on hover effect. Besides we were wondering if an option like sendboximage can be added for full user experience customization

**Comment by corinagum** [comment]
@CHuijsman This customization is available by creating your own sendboxbutton component. Please take a look at [customizing the UI](https://github.com/microsoft/BotFramework-WebChat#customizing-the-web-chat-ui).

**Comment by felixvanleeuwen** [comment]
@corinagum None of the example specify how to pass a custom renderer. I've been digging through some javascript files in the NPM packages to try to find out how this would be possible (`FullReactWebChat.js` in `botframework-webchat` & `BasicWebChat.js` 
 in `botframework-webchat-component`).
It looks like the only control we have over this part of the UI is what we can send down to it through the `styleOptions` object.

Am I missing something or is it not possible without forking the repo?

**Comment by corinagum** [comment]
https://github.com/microsoft/BotFramework-WebChat/issues/3526#issuecomment-705199136 Listed in our FAQ
