### ISSUE TITLE
Where is webpacked/botchat.js ?

### ISSUE THREAD

**Issue by TOuhrouche** [Microsoft/BotFramework-WebChat#306]
Hi,
I am trying to use the bot chat UI within my non-react website. The documentation mentions `webpacked/botchat.js` but this file does not exist. I tried building the code but still nothing. 

Thanks.

**Comment by billba** [comment]
Sorry, it's in the root now. I'll update the docs.

**Comment by TOuhrouche** [comment]
Oh great! Let me try that one and see if it works

**Comment by billba** [comment]
Closing this as I can't seem to find any mention of the `webpacked` directory in the current docs, but let me know if it's still there somewhere.
