### ISSUE TITLE
Chat persistence in new tab

### ISSUE THREAD

**Issue by uppalapraveen** [microsoft/BotFramework-WebChat#3060]
## Version

we are using the webchat CDN here is the link:
https://cdn.botframework.com/botframework-webchat/latest/webchat.js

## Steps to reproduce

1. Open the webchat and start chatting with it.
2. Now the chat persistence exist there.
3. Open the same application in new tab with same user.
4. Now the chat persistence(chat history) is not visible.

## Expected behavior

chat persistence(chat history) should remain same if same user opens the application in new tab or new window unless user clears the chat history forcefully.

## Additional context

To crackdown the issue. I have tried to store the conversation history in browser local storage. when user opens new tab, I am appending the conversation to the div. where I am loosing the click action for the buttons.
I guess this is no the good practice.

[Bug]

**Comment by compulim** [comment]
Can you fill out the form?

**Comment by uppalapraveen** [comment]
@compulim what form do I need to fill out ??? Please elaborate

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/77971588-ec6ca400-72a3-11ea-8674-500f971aab7d.png)

The bug form.

**Comment by uppalapraveen** [comment]
@compulim I have updated the bug form. looking for the resolution.

**Comment by uppalapraveen** [comment]
Got the solution here is the link
https://blog.getbizzy.io/persisting-chat-history-of-bot-framework-bots-across-a-user-session-using-javascript-58ee8d2738b3
