### ISSUE TITLE
Sample: comprehensive avatar page is broken

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3062]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/78030133-7bb29f80-7316-11ea-86dc-7c6134fed8c1.png)

## Version

`master`

## Describe the bug

https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/05.custom-components/k.per-message-avatar/comprehensive.html#L125

```diff
- <script type="text/babel" data-presets="es2015.react,stage-3">
+ <script type="text/babel" data-presets="es2015,react,stage-3">
```

Please also search for other files.

## Steps to reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/05.custom-components/k.per-message-avatar/comprehensive.html

## Expected behavior

Sample can be loaded correctly.

## Additional context

[Bug]

**Comment by GewoonMaarten** [comment]
I wanted to pick this issue up, but it appears that it was already fixed. 

I build `master` and the sample worked fine. I looked for other lines like this one `<script type="text/babel" data-presets="es2015.react,stage-3">` with the search pattern `es2015[^,]react[^,]stage-3` and `es2015[^,]react`  but couldn't find any.

**Comment by corinagum** [comment]
@GewoonMaarten thanks for letting us know! Closing as resolved.
