### ISSUE TITLE
In adaptive card speak property is not working

### ISSUE THREAD

**Issue by saikiran521** [microsoft/BotFramework-WebChat#3063]
Using adaptive cards 1.0 added speak tag before the body as below

{
    "type": "AdaptiveCard",
    "version": "1.0",
    "speak":"<s>testing speech</s>",
    "body": [
        {
}]
}

while returning from the dialog passing ssml as below

var response = MessageFactory.Attachment(attachment, ssml: card.Speak, inputHint: InputHints.ExpectingInput);
await stepContext.Context.SendActivityAsync(response);

but not able to hear the text when adaptive card in webchat.

Please help me in this if anyone faced same issue and got the solution.

Thanks in advance

**Comment by manish-95** [comment]
Hi @saikiran521  
Please try setting the speak property to true in your channelData as follows:
`response.ChannelData = new{speak=true};`
Please let me know if it works for you.

**Comment by jbgh2** [comment]
This maybe related to known problem that the WebChat bot will only use synthesized voices if you speak to it first. See #2211 for proposed solution.

**Comment by cleemullins** [comment]
@jbgh2 We've a design and spec, and the engineering workstream looks to land in early July (as part of our R10 release).
