### ISSUE TITLE
Inlined chat UI crashes on Safari

### ISSUE THREAD

**Issue by TOuhrouche** [Microsoft/BotFramework-WebChat#307]
I have managed to use the bot UI on my non-react website and looks awesome! However, I am facing an issue whenever I try to bring the bot up in Safari :(
I get the following error on the console:
`SYNTAX_ERR: DOM Exception 12: An invalid or illegal string was specified.`  This error occurs in `botchat.js` at:
```
                // timeout and responseType can be set once the XHR is open
                xhr.timeout = request.timeout;
                xhr.responseType = request.responseType;  <=== ERROR here: line 28726
```

**Comment by billba** [comment]
I use Safari almost exclusively and have never seen this error. Can you provide more info that might help me reproduce?

**Comment by TOuhrouche** [comment]
Thanks for the super fast answer. I am unfortunately not sure where to start. 
All I did is use the botchat.js I built locally (production configuration) and use that as follow:

```
    // In my knockout view model
    function startBot() {
        return $.ajax({
            url: "api/bot/token",
            dataType: "json",
            error: function (xhr, textStatus, errorThrown) {
            },
            success: function (data) {
                var token = JSON.parse(data);
                BotChat.App({
                    directLine: {
                        token: token
                    },
                    user: { id: 'You', name: 'You' },
                    bot: { id: '<my_bot_id>', name: '@Dunker' },
                }, document.getElementById("bot-window-content"));
            }
        });
    }
```
Note that this perfectly works without any warnings or errors on Chrome.

**Comment by TOuhrouche** [comment]
I did another test by embedding the chat UI via an IFRAME and I can confirm that the problem is still there.
`SYNTAX_ERR: DOM Exception 12: An invalid or illegal string was specified.` @botchat.js line 32 (minified)

**Comment by billba** [comment]
Current Safari version is 10.0.2. I'm willing to make an effort to work on somewhat older versions, but 5.1.7 is crazy old. I'm going to close this issue, but feel free to update if you're seeing this on more recent versions.

**Comment by TOuhrouche** [comment]
Agreed :) I am using that version as it is the latest one available for Windows. I will give the chat UI a go on a much more recent Safari and will let you know how it goes.
