### ISSUE TITLE
Webchat Speech Services in Spanish

### ISSUE THREAD

**Issue by gtejeda** [microsoft/BotFramework-WebChat#3072]
🚨 The issue tracker is not for implementation questions 🚨

Greetings guys,
I managed to connect my bot to speech services, however, I'm trying to get it to recognize and speak Spanish, but it is still sending en-US to cognitive services (sample url: 
wss://eastus.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=en-US&format=detailed&Authorization=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJyZW.........)

If I set chrome as spanish, then it understands me in spanish perfectly, but speech-to-text still reads it a very weird spanish with a strong english accent (I hope that makes sense), but I need to get spanish in recognition and speech-to-text.

Any help would be greatly appreciated,
Thanks,
Geo

Here's my final renderchat (excluded tokens to both speech and directline for brevity, but it is working, just in the wrong language.

```js
window.WebChat.renderWebChat(
                {
                    directLine: window.WebChat.createDirectLine({ token }),
                                store,
                                selectVoice: (voices, activity) =>
                                  activity.locale === 'es-ES'
                                    ? voices.find(({ name }) => /TracyRUS/iu.test(name))
                                    : voices.find(({ name }) => /JessaNeural/iu.test(name)) ||
                                      voices.find(({ name }) => /Jessa/iu.test(name)),
                                webSpeechPonyfillFactory
                },
                document.getElementById('webchat')
            );
```

(Edited by @compulim for code formatting)

**Comment by gtejeda** [comment]
I managed to get the voice speaking proper spanish now, 

When I speak to the microphone, it is still recognizing only english, so all I need to do is overwrite browser locale, so that spanish is properly understood, instead of english and that's it :D :D 

anybody?

**Comment by compulim** [comment]
@gtejeda you should set the `locale` prop when calling `renderWebChat`.

For example, I am setting it to `zh-HK` and both speech recognition and synthesis is done in Cantonese (my native oral language in Hong Kong).

```js
window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token }),
    locale: 'zh-HK',
    webSpeechPonyfillFactory
  },
  document.getElementById('webchat')
);
```

I also verify the network traffic send to Cognitive Services is using correct locale. The network trace below is for STT (speech-to-text, a.k.a. speech recognition).

![image](https://user-images.githubusercontent.com/1622400/78402348-44aaeb00-75af-11ea-9525-d6593b61ba93.png)

**Comment by gtejeda** [comment]
WOW @compulim, I had seen this very sample in the docs, tried it and it didn't work... it appears I tested it incorrectly, because I simply added it and it worked perfectly now.
🤦‍♂ 

Really appreciate your work guys,
keep up the good job!
G
