### ISSUE TITLE
Placeholder of input text box

### ISSUE THREAD

**Issue by narik1989** [microsoft/BotFramework-WebChat#3073]
Is it possible to change the default placeholder text in sendbox to a custom text of my choice like the screenshot attached?

Thanks in advance.

![image](https://user-images.githubusercontent.com/33231617/78357545-47b5d380-75cf-11ea-873d-00c2ec81ebd7.png)

**Comment by compulim** [comment]
Yes, please look at our docs on how to override strings here, https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/LOCALIZATION.md#overriding-localization-strings.

Excerpt:

```js
window.WebChat.renderWebChat(
  {
    locale: 'en-US',

    overrideLocalizedStrings: (strings, language) => ({
      ...strings,
      TEXT_INPUT_PLACEHOLDER: 'What is on your mind?'
    }),

    overrideLocalizedStrings: {
      TEXT_INPUT_PLACEHOLDER: 'What is on your mind?'
    }
  },
  document.getElementById('webchat')
);
```
