### ISSUE TITLE
customize 'Sending' message displayed when user sends a question to bot

### ISSUE THREAD

**Issue by pkrishnagithub** [microsoft/BotFramework-WebChat#3091]
need an idea how to customize this or would like an enhancement in node_modules\botframework-webchat-component\lib\Activity\SendStatus.js

at var localizedSending = (0, _Localize.localize)('Sending', language);
[SendStatus.txt](https://github.com/microsoft/BotFramework-WebChat/files/4444375/SendStatus.txt)

**Comment by stevkan** [comment]
@pkrishnagithub, there is a sample that already demonstrates how you can changes like this. The sample is [05.custom-components/g.activity-status](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/g.activity-status/) and should meet your needs.

Please note, at this time, the "Try the MockBot" link is broken, but should be fixed before too long.

I'm closing this issue as resolved.
