### ISSUE TITLE
Adaptive Card with hyperlink is not rendered correctly on SharePoint

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/BotFramework-WebChat#3093]
On the bot emulator /webchat it is being rendered correctly, but on SharePoint integration it appears all as text:

![image](https://user-images.githubusercontent.com/24475275/78673214-1c3e2c00-78e2-11ea-8764-8368bd56e1ee.png)

I send the card as using MessageFactory.Attachment(..)
and the same issue appear also for the QnAMakerDialog class, when the answer contains formated hyper link [text](link)

This is my adaptive card I send as response:
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "speak": "",
  "body": [
    {
      "type": "TextBlock",
      "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. [test link](https://www.google.com)",
      "isSubtle": true,
      "wrap": true
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Click here to try again",
      "data": "check invoice",
      "text": "check invoice",
      "style": "positive"
    },
    {
      "type": "Action.Submit",
      "title": "Click here to start over",
      "data": "start over",
      "text": "start over",
      "style": "destructive"
    }
  ]
}

So it seems to work well on bot emulator or webchat, but not on SharePoint.
Any known issues or workarounds?
If I send this as a text, it works on SharePoint too (using MessageFactory.Text("...[text](link)")

**Comment by compulim** [comment]
@tamerin-tech can you use Web Chat v4?

The transcript you are showing is using Web Chat v3 and it's on maintenance mode.

**Comment by tamerin-tech** [comment]
I cannot change it. I found a workaround by adding a middleware that replaces the formatting 
`[text](url)`
 to 
`<a href="url">text</a>`
and now it renders fine. Closing issue
