### ISSUE TITLE
Not able to edit Adaptive cards css(button orientation,title color) in React.js

### ISSUE THREAD

**Issue by thomas023** [microsoft/BotFramework-WebChat#3104]
I'm creating a Bot application using React js and botframework-webchat. I want to change the title color and button orientation of adaptive cards. But i;m unable to do so. Every title in adaptive card is classified into a common class called p and button orientation is also not changing. Heard that i could try it using adaptive card hostconfig in npm but as i'm new to react i don't know how. How can i solve this problem. 

botframework-webchat version : 4.7.1
React version : 6.14.4

**Comment by v-kydela** [comment]
Hi @thomas023 

When you say button orientation, do you mean you want the buttons do display horizontally? Did you follow the instructions here? https://github.com/microsoft/BotFramework-WebChat/issues/2034

I also found a more recent post that implies that you don't need to provide a whole new host config, and it seems to work: https://stackoverflow.com/questions/59382809/adaptivecards-hostconfig-integration

**Comment by thomas023** [comment]
Hi @v-kydela Yes I want to change the placement of button from vertical to horizontal. And change the color of the Title text.

**Comment by v-kydela** [comment]
@thomas023 - Did you follow the instructions?

**Comment by compulim** [comment]
1. Changing action orientation, https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#actionsconfig
1. I am unsure which host config rule to use, please look at the host config documentation to see
   - If there is not such rule, please file one to AC team, at https://github.com/microsoft/adaptivecards/issues

### Changing action orientation

![image](https://user-images.githubusercontent.com/1622400/79596512-923a5400-8095-11ea-9b86-f189a5c9c206.png)
