### ISSUE TITLE
OAuth adaptive card for calendar skill is causing an issue. Throwing render error

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#3119]
## Screenshots

![image](https://user-images.githubusercontent.com/11289456/79835418-5290a680-83cc-11ea-92dd-0f471156462b.png)

## Version

CDN
4.8.0 js
Using it an angular app

## Describe the bug

trying to invoke calendar skill.
Usually the login OAuth card pops up,but now that card is not being rendered. Cannot use the chat window after the error pops up 

## Steps to reproduce

Try invoking calendar skill 

## Expected behavior

card is rendered

**Comment by compulim** [comment]
Can you open F12 developer tools and see if there are any console logs?

**Comment by prashanthsridhar** [comment]
Thank you for quick response :)
