### ISSUE TITLE
WebSocket StatusCode 101 Switching Protocols when send event on direct line speech channel

### ISSUE THREAD

**Issue by BeeMaia** [microsoft/BotFramework-WebChat#3125]
## Version  

latest version on CDN or npm 3.8.1 inside reactjs

## Describe the bug

I have a problem inside a reactjs application that use **direct line speech channel** but I can reproduce running the sample [https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech), when I try to send event from webchat it's not working, in the network tab of browser I can see that the request stuck pending and WebSocket StatusCode is 101: Switching Protocols.

## To Reproduce

 -  Copy code from 03.speech/a.direct-line-speech sample into Web Chat enabled page
 -  Apply this changes:
![immagine](https://user-images.githubusercontent.com/22744022/80087158-0758ce00-855b-11ea-9dee-a43754fff364.png)
 -  Run bot and navigate to page
 -  Observe network tab of browser, the request stuck pending 
![immagine](https://user-images.githubusercontent.com/22744022/80086987-c2349c00-855a-11ea-8414-3b5957634e5a.png)

## Expected behavior

Able to send event to bot on direct line speech channel

[Bug]

**Comment by tonyanziano** [comment]
Hi @BeeMaia , what web browser, and what version of the browser are you currently using when experiencing this issue?
