### ISSUE TITLE
Direct Line JS or Web Socket connection Status

### ISSUE THREAD

**Issue by narik1989** [microsoft/BotFramework-WebChat#3126]
Not sure if this the right place to ask the question. but please forgive me if it is wrong. Please find my question below.

1. I create a directling connection  

- var dl = window.WebChat.createDirectLine({ token, webscoket: true });

2. using the above directline connection i render a webchat

- window.WebChat.renderWebChat({
                directLine: dl
            }, document.getElementById('webchat'));
3. Chat is initialized successfully.

Now i want to know if there is hook to monitor directline status or web socket status. Because if the internet is down. I want to know and let the user know that the connection between bot and the client is not longer valid and start a new conversation or reconnect to the old one. Either way is there a possiblity to know the directline or web socket connection status if it is broken. 

Thanks in advance

**Comment by tonyanziano** [comment]
Hi @narik1989 ,

This can be accomplished by using the following sample to add a custom middleware to Web Chat's Redux store.

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/j.redux-actions

Then you can listen for incoming Redux actions -- in your case it would be the [`UPDATE_CONNECTION_STATUS` activity](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/core/src/actions/updateConnectionStatus.js) -- and display content to the user accordingly.

In the future, for product behavior, how-to, or general understanding questions, please use Stackoverflow.  

https://stackoverflow.com/search?q=bot+framework
