### ISSUE TITLE
Custom properties in outgoing activity.from 

### ISSUE THREAD

**Issue by yapalex** [microsoft/BotFramework-WebChat#3127]
I am trying to send an activity from the our react webchat client to our hosted bot on azure. The activity is a event, and has custom props in activiy.from that we use to initialize the connection and tell the bot where to start. 

I want to use the store to do this, but when I send the activity this way, it strips the from property completly from the object.

```
  if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
            dispatch({
              type: 'WEB_CHAT/SEND_EVENT',
              payload: {
                name: 'initConversation',
                value: {                              
                }                
              },
              from: {
                id: 'ioaisjdoijoasjd',
                name: 'AAFC React Client',
                welcome: 'StartAt: softwareproduct',
                language: 'EN' 
              }
            });
```
However, if I bypass the store and use the directline object, it works perfectly fine.
```
directLine.postActivity({
        from: {
          id: '8793147287394879283794879283749827394',
          name: 'webclient',
          welcome: 'StartAt: softwareproduct',
          language: 'EN'            
        },
        type: 'event',
        name: 'initConversation',
        value: '',})
          .subscribe(function (id) {      
            console.log('conversation initiated: ');
          }, function (ex) {
              
              console.log('An error occurred while initiating the conversation: ');
              console.log(ex);
          });
```

I also tried using simple-add-in and piggy back on outgoing event, following this example: [link](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/b.piggyback-on-outgoing-activities)

Does this work as intending ? Is there another way to populate fields? The event is still sent and is properly received by the bot, just missing the from property.

Is my approach wrong? is there another way of accomplish this using the store and not directline?

[Bug]

**Comment by tonyanziano** [comment]
@stevkan can you take a look at this please?

**Comment by compulim** [comment]
The content supported in `from` field is very limited:

- https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#from
- https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#Channel-account

Translate the spec to TypeScript:

```ts
type From = {
  id: string;
  name?: string;
  aadObjectId?: string; // Web Chat don't support AAD Object ID
  role?: string; // either 'bot' or 'user'
};
```

Web Chat sanitize the `from` field according to spec, and it is a correct behavior. But DLJS and the Direct Line channel lack of sanitization, thus, they did not remove extra fields from the `from` field.

You should use `channelData` to keep custom data.
