### ISSUE TITLE
Is there a way to connect the client WebChat to a websocket directly? 

### ISSUE THREAD

**Issue by rosenjcb** [microsoft/BotFramework-WebChat#3142]
We have infrastructure that connects to our bot via a websocket. We use this so our mobile platforms can connect without the use of a direct line (and actually we want a layer between the bot itself and the client, so that certain scenarios can only be entered according to our rules). Is there a way to configure the JS webchat to connect directly to a websocket url? That means no directline. 

EDIT: this may be better placed in the [BotFramework-DirectLineJS](https://github.com/microsoft/BotFramework-DirectLineJS/issues) issues section.

**Comment by cleemullins** [comment]
@v-kydela Could you dive in here?

**Comment by v-kydela** [comment]
Hi @rosenjcb 

Can you explain why this issue would be better placed in the BotFramework-DirectLineJS repo even though you don't want to use Direct Line? Are you using the DirectLineJS library for something?

**Comment by rosenjcb** [comment]
@v-kydela Now that I think about it, there might not be a point asking in the other repo. The entry point for a webchat instance pivots on the `createDirectLine()` function, so I thought their repo might be a more appropriate place to ask about getting around the DirectLine token.

Either way, you're right that I want to get around using DirectLine altogether.

**Comment by v-kydela** [comment]
@rosenjcb 

I believe `createDirectLine` does create an object to communicate with Direct Line using DirectLineJS, but I think you can still use it even if you don't want to go through the actual Direct Line servers. You can set the `domain` property of the [argument](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-webchat-overview#web-chat-api-reference) to specify your own endpoint, and you can set the `webSocket` property to true.

You might be interested in [offline-directline](https://github.com/ryanvolum/offline-directline). While the examples use Web Chat v3, it still works fine in v4. Even if you don't want to use it, the source code might help you implement your own alternative Direct Line solution.

**Comment by rosenjcb** [comment]
@v-kydela 

Thank you for the references. At this point, I think there are two options for a possible integration with `BotFramework-WebChat`

1.) Create a hosted directLine source that works with websockets only (`offline-directline` uses REST only so we can only use it as a reference)
2.) Fork `Botframework-WebChat` and get the client to accept either a directLine or websocket url. 

Any suggestions on what would be easier? I think choice one has the easiest route, mostly because we don't have to get dirty in forking the existing webchat client. Any other tips that could help us figure this out?

**Comment by v-kydela** [comment]
@rosenjcb 

My understanding is that WebSockets are [already built into](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation#response) Direct Line and Web Chat. Try using the `webSocket` and `streamUrl` of the `createDirectLine` argument: https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/API.md

**Comment by rosenjcb** [comment]
@v-kydela 
I don't think it's as simple as that. You can feed in `streamUrl` and `webSocket` args but it will fail immediately. First, it'll try to POST to the directline domain but it'll fail with a 403 error. If you change the domain to something local (e.g. the top level domain of the websocket I'm trying to connect to), then it'll then make POST requests to `/conversations` `/conversations/:id/activities` et cetera. I was hoping that setting `websocket` to `true` would prevent the bot from attempting POST requests (even when supplied with a `streamUrl`) but that has been unsuccessful so far.

**Comment by v-kydela** [comment]
@rosenjcb - I have a few questions to make sure I understand correctly

1. You mentioned having an infrastructure that connects to your bot via a WebSocket. You also said you want a layer between the bot itself and the client. Are the infrastructure and the layer the same thing?
2. If your infrastructure is itself running on a server, couldn't it connect to the bot using HTTP/HTTPS and still achieve two-way real-time communication? What advantage do you get from WebSockets when connecting two servers?
3. While it would be possible to have your infrastructure connect to the bot using WebSockets and the client using HTTP/HTTPS or vice versa, you've chosen to use WebSockets for both. Is that correct?
4. I think Web Chat is currently using WebSockets only to receive messages and not to send them, which is probably why you were having problems. Do you want to connect to Web Chat using two-way WebSockets or just one-way?

**Comment by rosenjcb** [comment]
@v-kydela 

No problem, I can help clarify!

1.) They're the same thing. Basically the architecture looks like this: Client (Android, iOS, Web) <-> Middleware <-> Bot Service. Basically a client will send messages over websocket to the middleware service and that middleware will talk to bot service to create new conversations and manage existing ones. We do this to simplify the request that the client has to make to start a healthbot scenario and also to  manage the interaction between the client and the bot service (again, we don't want clients to simply start whatever scenarios they want).

2.) I unfortunately don't get to choose the infrastructure. I'm just given a websocket url and asked to talk through it. Though, to be honest, I'm not sure why the BotFramework uses two different protocols for managing a conversation. I understand why the architecture allows for websocket for receiving messages (avoids endless polling for updates) but I don't understand why you'd keep the POST method for sending messages. Wouldn't it be simpler to just talk through one protocol or the other?

3.) I'd have to look at the source further, but it's likely that as soon as a scenario is started, everything defaults to websocket (for both sending and receiving).

4.) I want two way communication via websockets, that's correct.

**Comment by v-kydela** [comment]
@rosenjcb - Thank you for the information. It sounds like you're using the word "middleware" differently from how we use it, but it sounds like that's what you're calling your infrastructure so I'll do the same.

Based on your answers, I'm worried that you're conflating two different things. You answered questions 2 and 3 as though I was asking about the difference between sending and receiving, when really I was asking about the difference between middleware-bot communications and middleware-client communications. Your middleware can presumably send messages to and receive messages from the bot, and it can also send messages to and receive messages from the client. Can you verify that you understand the difference between the question of using WebSockets for middleware-bot communications versus middleware-client communications and the question of using WebSockets for sending messages versus receiving messages?

**Comment by rosenjcb** [comment]
@v-kydela 

Apologies: I didn't like my use of the word "middleware" either. To be honest, I googled it just to make sure I wasn't flubbing it up but the definition seems to be fluid in the industry (it's a curse of business jargon). 

Yes, I do understand the difference. 

>Can you verify that you understand the difference between the question of using WebSockets for middleware-bot communications versus middleware-client communications and the question of using WebSockets for sending messages versus receiving messages?

Yes and I'll explain here:


>using WebSockets for middleware-bot communications 

Our middleware service makes the require REST calls and connects to the generated websocket url. This is how it communicates to the bot (both sending and receiving). 

>middleware-client communications and the question of using WebSockets for sending messages versus receiving messages

The clients connecting to the middleware service do both sending and receiving over websocket as well.

**Comment by v-kydela** [comment]
@rosenjcb - I don't think you'll need to host a Direct Line source and I don't think you'll need to fork Web Chat. I can think of two avenues to explore, though both would involve some extensive examination of the source code on your end.

1. You could create your own alternative DirectLineJS object that you could pass to Web Chat's `directLine` parameter. This object would need to expose all of the functionality that Web Chat uses, like a `postActivity` function.
2. You could try using Redux middleware to intercept all the actions that would normally activate Direct Line functionality and have them access your infrastructure instead.

**Comment by rosenjcb** [comment]
@v-kydela I noticed that the directLine object contains functions yesterday. I'll try writing an alternative DirectLineJS object that does everything through websocket.

**Comment by v-kydela** [comment]
@rosenjcb - Sounds good. Would you consider this issue resolved?

**Comment by rosenjcb** [comment]
@v-kydela 

Sure, if I run into any problems I'll be open a new ticket but this looks self explanatory now.
