### ISSUE TITLE
Direct Line Speech throw "actions of null" error when bot is on unsupported region

### ISSUE THREAD

**Issue by Hari-c4** [microsoft/BotFramework-WebChat#3145]
I was using this [example](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech) to implement directline speech in webchat. Here is the script I used

```
<div id="webchat"></div>
    <script>
        (async function () {
            const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
                if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
                    dispatch({
                        type: 'WEB_CHAT/SEND_EVENT',
                        payload: {
                            name: 'webchat/join',
                            value: 'name'
                        }
                    });
                }
                return next(action);
            });

            const adapters = await window.WebChat.createDirectLineSpeechAdapters({
                fetchCredentials: {
                    region: 'region',
                    subscriptionKey: 'key'
                }
            });


            window.WebChat.renderWebChat(
                {

                    ...adapters, store
                },
                document.getElementById('webchat')
            );

            document.querySelector('#webchat > *').focus();
        })().catch(err => console.error(err));
    </script>
```

seems like "...adapters" is not supported in Edge or IE, How can I change it so that it will be working in Edge and IE ?

**Comment by compulim** [comment]
The sample code we provided is for latest version of JavaScript. Both Edge and IE11 do not support the latest syntax. You will need to transpile it down to the version you need (IE11 support up to ES5).

There are multiple ways to do it, we are outlining two popular choices here:

1. For development, you can use `@babel/standalone` to transpile on-the-fly
   - This is strictly used for development purpose only
   - You can refer to https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/e.host-with-react, this sample do two things:
      - Use `@babel/standalone` to transpile on-the-fly (this is the part you need)
      - Host Web Chat using React (this is optional)
1. For development and production, you should use Webpack + Babel to precompile your website
   - Babel is for transpiling: convert newer syntax of JavaScript code to older syntax of JavaScript code
      - IE11 support up to ES5 only, so you should target ES5
   - Webpack is for bundling: merge multiple `*.js` files into a single `app.js` file
      - While doing the bundling, Webpack can be configured to load the file through Babel, a.k.a. loader. This means "transpiling while bundling".

**Comment by Hari-c4** [comment]
@compulim I'm embedding webchat with directline speech. So I chose the second option. Here is my updated code

```
<!DOCTYPE html>
<html lang="en-US">

<head>
    <title>Web Chat: Send welcome event</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.21.1/babel.min.js"></script>
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            margin: 0;
        }

        #webchat {
            height: 100%;
            width: 100%;
        }
    </style>
</head>

<body>
    <div id="webchat"></div>
    <script type="text/babel">

        (async function () {


            const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
                if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
                    dispatch({
                        type: 'WEB_CHAT/SEND_EVENT',
                        payload: {
                            name: 'webchat/join',
                            value: ' name '
                        }
                    });
                }

                return next(action);
            });

            const adapters = await window.WebChat.createDirectLineSpeechAdapters({
                fetchCredentials: {
                    region: 'region',
                    subscriptionKey: 'key'
                }
            });

            console.log(adapters);

            window.WebChat.renderWebChat(
                {

                    // Object.assign({}, adapters),store
                    ...adapters, store
                },
                document.getElementById('webchat')
            );

            document.querySelector('#webchat > *').focus();
        })().catch(err => console.error(err));
    </script>
</body>

</html>
```
 It was working fine in all browsers till yesterday. Today when I check I see this error.
![issue-webchat](https://user-images.githubusercontent.com/56388643/81258024-5cfca280-9052-11ea-9756-a7e330acdec8.JPG)
I haven't published or made any changes in bot yesterday. Bot is working fine in Azure portal and also in emulator.

**Comment by compulim** [comment]
@Hari-c4 I tried your code with my bot's region + subscription key and it works normally.

I am searching through the code for potential `'actions' of null` error.

Could it be related to a malformed Adaptive Cards or suggested actions?

**Comment by Hari-c4** [comment]
@compulim  Thanks for the quick response. Directline webchat without speech is also working fine for me. Issue happens when I use directline speech. Here is the working code for directline webchat

```
<div id="webchat"></div>
    <script>
        (async function () {
            const res = await fetch('https://directline.botframework.com/v3/directline/tokens/generate',
                {
                    method: 'POST',
                    headers: { Authorization: 'Bearer secret' }
                });
            const { token } = await res.json();
            const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
                if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
                    dispatch({
                        type: 'WEB_CHAT/SEND_EVENT',
                        payload: {
                            name: 'webchat/join',
                            value: 'username'
                        }
                    });
                }

                return next(action);
            });

            

            window.WebChat.renderWebChat(
                {

                    
                    directLine: window.WebChat.createDirectLine({ token }),
                    store
                },
                document.getElementById('webchat')
            );

            document.querySelector('#webchat > *').focus();
        })().catch(err => console.error(err));
    </script>
```

If it is working for you, can you tell me your speech resource's region ? Mine is central India.

**Comment by compulim** [comment]
Mine is `westus2`.

**Comment by Hari-c4** [comment]
@compulim I changed my speech resource to one in `westus2 `region. Its working now!

**Comment by compulim** [comment]
Good to know!

Let me rename this bug so we don't surface a hard-to-guess error message.

**Comment by BeeMaia** [comment]
Hi,
today we have same problem with **westeurope** region but we are unable to change the region of service.
Until saturday I'm sure that it works, any help?

Thanks

**Comment by Hari-c4** [comment]
> Hi,
> today we have same problem with **westeurope** region but we are unable to change the region of service.
> ![immagine](https://user-images.githubusercontent.com/22744022/81547425-1ec9f080-937c-11ea-92c8-47602a4436b5.png)
> We use the npm package.
> Until saturday I'm sure that it works, any help?
> 
> Thanks

I'm also facing this issue again, I have raised a support request from Azure. Will keep you updated, if i get to resolve this.

**Comment by Hari-c4** [comment]
Hi,
For me this issue was resolved without making any changes in code or configuration. I believe this issue was from the speech API side. It got resolved 3 to 4 days after reporting and it never occurred again.
