### ISSUE TITLE
Mockbot isn't working for full bundle

### ISSUE THREAD

**Issue by ericchansen** [microsoft/BotFramework-WebChat#3149]
## Screenshots

Not necessary.

## Version

Version doesn't matter.

## Describe the bug

I don't think Mockbot is working.

## Steps to reproduce

1. Go to https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/a.full-bundle
1. Click on [Try out Mockbot](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle)
1. A page opens and nothing appears

## Expected behavior

I imagine I should see a bot interface.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
@ericchansen Thanks for reporting. It looks like the CDN URL is set incorrectly.

```diff
- <script crossorigin="anonymous" src="/webchat.js"></script>
+ <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
```

https://github.com/microsoft/BotFramework-WebChat/blob/6462ef4caccb5b77c5dd858df98911f86638f8aa/samples/01.getting-started/a.full-bundle/index.html#L11
