### ISSUE TITLE
Cursor issue with clickable widgets on Bot UI WebChat v4

### ISSUE THREAD

**Issue by MamadouABah** [microsoft/BotFramework-WebChat#3157]
When you hover over the menus, links or any clickable controls, you don't see the cursor showing as pointer, it shows the default standard arrow. That is bad user experience we need fix for our production Bot.

**Comment by compulim** [comment]
This is by-design.

Please see the discussion here, https://github.com/microsoft/BotFramework-WebChat/issues/1767.

**Comment by MamadouABah** [comment]
Seems that this behavior was and still is supported in Webchat v3
