### ISSUE TITLE
how to send an end event beforeunload?

### ISSUE THREAD

**Issue by zp1112** [microsoft/BotFramework-WebChat#3158]
I want to send an end event like this:
```js
window.addEventListener('unload',() => {
    store.dispatch({
        type: 'WEB_CHAT/SEND_EVENT',
        payload: {
          name: 'EndOfConversation'
        }
      });
});
```
but it didn't work for me. As i know,unload will block xhr request,is there other way to resolve this problem?

**Comment by compulim** [comment]
Hi @zp1112.

Although [W3C HTML standard on page unload](https://html.spec.whatwg.org/multipage/browsing-the-web.html#unloading-documents) does not specifically disable network traffic, as you observed, browser may opt to disable network traffic after these unload event, maybe due to privacy concern.

You can consider sending heartbeat/ping to the bot. But they could still be false positive due to network interruption.

I think there are no reliable ways to send any network traffic after the user decided to close the browser.

**Comment by stevkan** [comment]
@zp1112, I have found the following to work for me. Place it in your page where the Web Chat store is accessible. In my case, I'm persisting conversations which is how I'm able to see the posted message in Web Chat.

I can't say that it will work in every situation for every browser or version (I'm using Chrome and have run successfully on a multitude of versions), but it's a jumping off point, at least. @compulim could speak more to that, if more is needed to be said than what he posted above.

```js
window.addEventListener( 'sendMessageActivity', ( { data } ) => {
  store.dispatch( {
    type: 'WEB_CHAT/SEND_MESSAGE',
    payload: {
      text: data
    }
} );

window.onbeforeunload = function() {
  const eventSendMessage = new Event( 'sendMessageActivity' );
  eventSendMessage.data = 'User left conversation';
  window.dispatchEvent( eventSendMessage );
}
```

**Message received by bot**
```
File Transcript Activity >> {
  direction: 'incoming',
  activity: {
    callerId: 'urn:botframework:azure',
    channelData: {
      clientActivityID: '15898261515331cqv08r1lb5',
      clientTimestamp: '2020-05-18T18:22:31.533Z'
    },
    channelId: 'directline',
    conversation: { id: 'JmXdzwRkQtE6ekG53YK95p-o' },
    from: {
      id: 'dl_15898261456610.9zj0c8ysgp',
      name: 'Lord Voldemort',
      role: 'user'
    },
    id: 'JmXdzwRkQtE6ekG53YK95p-o|0000003',
    locale: 'en-US',
    rawTimestamp: '2020-05-18T18:22:31.5733129Z',
    recipient: { id: 'b***g@QaeuoeEamLg', name: 'R***e Bot' },  
    serviceUrl: 'https://directline.botframework.com/',
    text: 'User left conversation',         <============ Text sent from Web Chat
    textFormat: 'plain',
    timestamp: 2020-05-18T18:22:31.573Z,
    type: 'message'
  }
}
```

**Web Chat activity**

![image](https://user-images.githubusercontent.com/18403946/82246665-f735d380-98f9-11ea-9139-e2d7957053c2.png)

Hope of help!!

**Comment by stevkan** [comment]
Closing again as resolved.

**Comment by zp1112** [comment]
@stevkan Thanks! It works!

**Comment by leijae** [comment]
this method doesn't work. yes the message is added to the chat window, but newest version of chrome disables the request. "Send failure" is the result.
