### ISSUE TITLE
Override the timestamp format in the webchat

### ISSUE THREAD

**Issue by UncleZen** [microsoft/BotFramework-WebChat#3160]
I have posted a question to SO: https://stackoverflow.com/questions/61775075/override-the-timestamp-format-in-the-webchat.

But since, I have not gotten an answer yet, I am posting it here too:
When setting the timestamp format to 'absolute', the webchat with locale set to fr-FR prints the time portion of the timestamp using the 'short' time format of globalizejs library as 8:36 AM. See: https://github.com/globalizejs/globalize/blob/master/doc/api/date/date-formatter.md.

Can I override the time format to display the time in 24-hour notation, i.e. instead of 8:36 AM to print 8h 36?

Web Chat is integrated into a webpage using JavaScript (not React): v. 4.8.1, https://cdn.botframework.com/botframework-webchat/latest/webchat.js

![webchat_time_format_issue](https://user-images.githubusercontent.com/485880/82067537-dcb3ee00-969e-11ea-84c3-dcd93effbfd3.png)

**Comment by stevkan** [comment]
Hi @UncleZen, as this is a "how to" question, I will respond to you over in SO. I'm going to close this in the mean time, but if it needs to be re-opened for some reason, we can.

**Comment by UncleZen** [comment]
Thanks @stevkan!
