### ISSUE TITLE
Text wrapped or partially wrapped in curly braces do not render

### ISSUE THREAD

**Issue by stevkan** [microsoft/BotFramework-WebChat#3165]
## Screenshots

![image](https://user-images.githubusercontent.com/18403946/82255395-64049a00-9909-11ea-8e08-dc2f6933fed6.png)

![image](https://user-images.githubusercontent.com/18403946/82255414-6c5cd500-9909-11ea-87b6-0395e91f0465.png)

## Version

CDN 4.9.0

## Describe the bug

If the text sent from the bot to the user is fully wrapped or partially wrapped in curly braces, then the text is not rendered.

For partially wrapped text, this only applies if it is NOT the first word(s) in the text. If it is the first word(s), then that text will render. However, any other wrapped words will not.

This is not reproducible using v4.8.0

## Steps to reproduce

1. Ensure Web Chat v4.9.0 is loaded
1. Program bot to send a message that contains text wrapped in curly braces
1. Connect to Web Chat and receive message from bot
1. Observe wrapped text is missing

## Expected behavior

Any text wrapped in curly braces should fully render as intended by the bot

## Additional context

From bot: `await stepContext.context.sendActivity('{Text sent by} the {bot}')`

[Bug]

**Comment by tonyanziano** [comment]
I was able to reproduce this using `https://cdn.botframework.com/botframework-webchat/latest/webchat.js`:



![image](https://user-images.githubusercontent.com/3452012/92530296-f8f51100-f1e0-11ea-93d6-e1c590d284a9.png)

Bot code:

```javascript
this.onMessage(async (context, next) => {
      const textWithBraces = 'Here is a message wrapped in curly braces: {Hello world!}';
      const textWithoutBraces = 'Here is a message without curly braces: Hello world!';

      await context.sendActivity(MessageFactory.text(textWithBraces, textWithBraces));
      await context.sendActivity(MessageFactory.text(textWithoutBraces, textWithoutBraces));

      await next();
});
```

**Comment by cwhitten** [comment]
@stevkan did this come from a customer?

**Comment by stevkan** [comment]
@cwhitten, no, I believe I was helping a customer with another issue when I stumbled across this. However, in doing a quick search, I see what looks like a similar issue filed by a Cx in the Emulator repo, #[2192](https://github.com/microsoft/BotFramework-Emulator/issues/2192).

**Comment by chrimc62** [comment]
This is a very annoying bug that has been reported by me and others--is it really that hard to fix?  No one can generate output with curly braces.

**Comment by compulim** [comment]
It only affect the very last curly braces.

We added a feature to Markdown-It to support accessibility by adding a syntax using curly braces, in #3022. The feature is designed to add `aria-*` attributes to make the activity content more accessible, especially for anchors.

Unfortunately, it also impact the last curly braces on the line. For example:

```
abc {xyz}
```

Will become

```
<p xyz="">abc</p>
```

When we import/use the [`markdown-it-attrs`](https://www.npmjs.com/package/markdown-it-attrs) package, we should scope it down to `/^aria-/iu`.

**Comment by compulim** [comment]
First, look at [`markdown-it-attrs`](https://www.npmjs.com/package/markdown-it-attrs):

![image](https://user-images.githubusercontent.com/1622400/110704673-2596df00-81aa-11eb-8e3e-9cb9b9f129e5.png)

Use RegExp to filter to allow only `/^aria-/iu/.

Add tests:

- `aria-xyz` will be added
- `data-abc` will NOT be added
