### ISSUE TITLE
scroll bar position issue

### ISSUE THREAD

**Issue by ras232** [microsoft/BotFramework-WebChat#3167]
Hi All,
I am facing issue in scrollbar position.
In my webchat i am loading 5 adaptive cards as attachments and i set the attachment layout as List type. 
now when the message is loading the scrollbar is moving to bottom. so to view the cards i need to scroll up.
i want to set the scrollbar to the 1st card or starting of the new response.
Please suggest how to do that.

**Comment by v-kydela** [comment]
Hello @ras232 

Can you give us some information about how you're coding your Web Chat page? Are you using React/Node.js for example?

**Comment by ras232** [comment]
i am using js implementation
<script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>

<script>
      (async function() {
        
window.WebChat.renderWebChat(
          {
            directLine: window.WebChat.createDirectLine({ token })            
          },
          document.getElementById('webchat')
        );

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>

**Comment by v-kydela** [comment]
Thank you, @ras232 (You can edit your own comments and [format code blocks using three backticks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks): ```` ``` ````)

I have a few more questions.

1. Is your bot able to send the attachments as part of the same activity?
1. Would it be desirable for you to send the attachments as a [carousel](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-add-media-attachments#send-a-carousel-of-cards)?

**Comment by ras232** [comment]
Hi Kyle,Thank you for your quick response.
   
   - Is your bot able to send the attachments as part of the same activity?  -> yes
   - Would it be desirable for you to send the attachments as a carousel?  ->  we have search functionality in the bot. For user's query it will hit api and prepare cards as per the api response and attach these cards as attachment to the response. we are using carousel now but looking for List format because against the search query might have 50, 60,80 or 100 records present in database and message attachment limit is 250kb, so we cant show all results in one go. so we thought of adding "SHOW MORE" functionality as a work around for this to show all records against tht search group by group. When user will hit SHOW MORE the system will return next set of data against that query. Now if we are using List format,  with show more click  next set of result will just append to existing list. this is to enhance visual. For this i need, when a response to a message is loading the scroll bar should position at the ever 1st response(1st attachment in-case of a list layout) but now it is going to the end. so to view the 1st card i need to scroll up..again when  i am hitting show more i am just lost not able to trace from where the next result set is starting. 

Hope i am able to make u understand my requirement.
    On Wednesday, 20 May, 2020, 12:22:09 am IST, Kyle Delaney <notifications@github.com> wrote:  
 
 


Thank you, @ras232 (You can edit your own comments and format code blocks using three backticks: ```)

I have a few more questions.
   
   - Is your bot able to send the attachments as part of the same activity?
   - Would it be desirable for you to send the attachments as a carousel?

**Comment by v-kydela** [comment]
Hello @ras232 

It doesn't look like Web Chat provides any options for you to customize the scrolling behavior. You might be interested in this issue: https://github.com/microsoft/BotFramework-WebChat/issues/2884

Since you're just using the Web Chat CDN rather than using Node or making your own React app, I'm guessing you won't want to try any advanced techniques to get your desired behavior. Web Chat automatically scrolls to the bottom when a new message appears and the transcript is already at the bottom. You might be able to find a way to override that behavior by looking into the source code. Or you could prevent the auto-scrolling by having your middleware scroll up one pixel before it displays the new message, and that would prevent the auto-scrolling. Then you'd have to write code that determines where the top of the first message is and scrolls to that.

**Comment by stevkan** [comment]
Per @v-kydela request, closing as resolved.
