### ISSUE TITLE
tweak the build of webchat to get webchat.js with least size.

### ISSUE THREAD

**Issue by mounikac16** [microsoft/BotFramework-WebChat#3168]
Can you provide a way for tweaking the build of the webchat to reduce the size of the build file to as minimum as possible. The bundle should support adaptive cards and cognitive services like speech-to-text are not required.

**Comment by benbrown** [comment]
Thanks for the request, @mounikac16.

@compulim can you comment on this request? what type of options exist for building the webchat?

**Comment by compulim** [comment]
Today, we have a minimal bundle which is about 460 KB after gzip. It does not include Markdown, Adaptive Cards, and Cognitive Services.

You can use this sample to get started with the minimal bundle, https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/b.minimal-bundle.

You can use [Webpack Visualizer](https://chrisbateman.github.io/webpack-visualizer/) to study our build by dropping in [the `stats.json` from the daily build](https://github.com/microsoft/BotFramework-WebChat/releases/tag/daily). Things top of my head:

- The localization work take up about 15%
   - 5% for globalize
   - 5% for database
   - 5% for an internal Markdown engine used during localization
- RxJS is taking up about 10%
- We parse JWT token without verification
   - The JWT library included unused cryptographic library, about 4%

Please suggests anything that we can address immediately. 😉

**Comment by tracyboehrer** [comment]
@compulim William, can you describe the new gzip capabilities?  Maybe this will help the customer.

**Comment by compulim** [comment]
Thanks @tracyboehrer for the tips.

Starting from Web Chat 4.9.0, we have updated the CDN (and its deployment script). It will serve gzipped bits if the browser support it (i.e. sending the `Accept-Encoding: gzip` header, which most browsers do.)

The URL is still the same, https://cdn.botframework.com/botframework-webchat/4.9.0/webchat.js. And it is a CDN service provided by Azure, serving customers from geo-closest location to reduce latency as much as possible.

The file size is down from ~2.7 MB to ~670 kB for full bundle.

As a UI widget, 670 kB is "not small". And I do hope someone could jump in and help us on reducing our dependencies.

**Comment by a-b-r-o-w-n** [comment]
@mounikac16 The options for reducing the bundle size are outlined in the documentation. If you require further optimization, our suggestion is to use the npm package with a bundler that supports tree-shaking.
