### ISSUE TITLE
[Directline] Sorry message in bot script

### ISSUE THREAD

**Issue by Sandeepmahala** [microsoft/BotFramework-WebChat#3169]
We have a bot running on directline channel. It throws an error message intermittently as below

![image](https://user-images.githubusercontent.com/24646692/82554837-48f18e80-9b84-11ea-9557-782ab62915a3.png)

We have located this error message to _SEND_FAILED_KEY_ in our bot script files. These script files we are generating from a [React solution on GitHub](https://github.com/Microsoft/BotFramework-WebChat) and then pushing the scripts in our web solution.

Version of react solution - 4.5.3-0

**Observations**:

- Request sent to Bot is responded and even logged in conversation logs but response in not rendered in webapp, instead the sorry message

- Subsequent messages are not received by Bot

**Comment by compulim** [comment]
It could possibly be one of the followings:

- The message failed to deliver to the bot
   - Browser not able to deliver to the service and the bot
      - Can you open Developer Tools and investigate the traffic of "POST https://directline.botframework.com/conversations/..." and see if the HTTP request is success or not?
      - If this failed, it could means either the service, or the bot, is failing to respond on time
      - See screenshot below for a successful deliver case
   - The service not able to deliver to the bot
      - Can you check the log on your bot?
- The bot failed to respond on time (< 20s, configurable)
   - Can you check the log on your bot?

#### Browser successfully delivered the message to the service and the bot

![image](https://user-images.githubusercontent.com/1622400/82585701-4f174900-9b4b-11ea-80f3-2c06a85f64e3.png)

Circled are things to check.

**Comment by Sandeepmahala** [comment]
@compulim we are getting below POST traffic details for failed messages
![image](https://user-images.githubusercontent.com/24646692/82903104-15e13d80-9f7e-11ea-9605-bc7f0190b3f5.png)
What's more quizzing is that, we can see the question in our bot conversation logs (custom logging we do), but the the script file is triggering send failed key.

**Comment by vishwacsena** [comment]
@compulim can you take a look?

**Comment by compulim** [comment]
Hi @Sandeepmahala,

There are few key criteria for Web Chat to consider the message successfully sent out, and all criteria must met within 20 seconds.

![image](https://user-images.githubusercontent.com/1622400/86168925-b1aa2000-bacd-11ea-9865-8389d9276761.png)

The `POST /activities` call must return as 200.

![image](https://user-images.githubusercontent.com/1622400/86169024-d9998380-bacd-11ea-923c-7d79d1f329ca.png)

The `POST /activities` call has a `channelData.clientActivityID`, for instance it is `159...hmf` here.

When you look at the Web Socket `/stream`, you should see the message sent out from the user, appear here.

![image](https://user-images.githubusercontent.com/1622400/86169225-25e4c380-bace-11ea-848e-37c1f5364416.png)

So, there are 2 criteria:
- The `POST /activities` call return 200
- The outgoing message, but echoed back through the `/stream` Web Socket connection, with same `channelData.clientActivityID`

If both criteria met within 20 seconds, Web Chat will consider the activity sent successfully and turn the message status into "Sent at 1 minute ago".

Can you verify both traffic on your side?

**Comment by kanika-jain** [comment]
It seems that in case of a network issue (even for a second) bot is not able to re-connect and we are getting sorry messages for all the utterances.

I referred below article:
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-4.0#http-get

There are 2 ways to receive bot activities:
1. via WebSocket
2. via HTTP GET

Earlier, I was using HTTP GET and in case of a network glitch I was getting "Sorry messages" for all the user queries even after network is back because bot was unable to re-connect.

Now, I am using WebSocket and able to resolve the issue.
