### ISSUE TITLE
Hamburger menu in Webchat

### ISSUE THREAD

**Issue by amistry79** [microsoft/BotFramework-WebChat#3171]
We would like to add the Hamburger menu into WebChat Directline channel. How can we achieve this in WebChat? This will be the static menu available next to input button of webchat.

![image](https://user-images.githubusercontent.com/3864971/82658397-8b7aa000-9c44-11ea-8749-fe29feaa9796.png)

**Comment by gabog** [comment]
@amistry79, thank you for opening this issue.  For product behavior, how-to, or general understanding questions, please use Stackoverflow.  

https://stackoverflow.com/search?q=bot+framework
