### ISSUE TITLE
Webchat userID value passing problem from webpage to bot. Botbuilder V4

### ISSUE THREAD

**Issue by shanugit** [microsoft/BotFramework-WebChat#3173]
Hi Team,

I am integrating one chatbot to my web application and i did it according to the webchat integration docs - https://github.com/microsoft/BotFramework-WebChat#integrate-with-javascript.

It was working fine and i was able to receive the userID value in the following object - stepContext.context.activity.from.id

Now i am getting conversation Id in that object and the userID value is not present in the context object.

Following is the library i have used for the integration - https://cdn.botframework.com/botframework-webchat/latest/webchat.js

Which version of the webchat library i need to use to get the value? Please let me know if i am doing anything wrong in the integration process.

Warm Regards,
Suman

**Comment by stevkan** [comment]
Hi @shanugit, can you please list which version of Web Chat you are using? You can get the version by pasting this into your browser's dev console:

`[].map.call( document.head.querySelectorAll( 'meta[name^="botframework-"]' ), function ( meta ) { return meta.outerHTML; } )`

Can you also include your Web Chat code (hiding any secrets/tokens)? Lastly, can you tell me what the user / bot interaction is when you are seeing these values come thru?

**Comment by shanugit** [comment]
Hi @stevkan   following is the version of the web chat -

 ["<meta name="botframework-directlinespeech:version" content="4.9.0">", "<meta name="botframework-webchat:bundle:variant" content="full">", "<meta name="botframework-webchat:bundle:version" content="4.9.0">", "<meta name="botframework-webchat:core:version" content="4.9.0">", "<meta name="botframework-webchat:ui:version" content="4.9.0">"] 

This is my code snippet for integration - 
<!DOCTYPE html>
<html>
   <body>
      <div id="webchat" role="main"></div>
      <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
      <script>
         window.WebChat.renderWebChat(
            {
               directLine: window.WebChat.createDirectLine({
                  token: "temp_token_here"
               }),
               userID: 'user_id'
            },
            document.getElementById('webchat')
         );</script>
      </script>
   </body>
</html>

The first activity in the bot is to send one conversation update (from bot to user). Can I get the userId field in that activity? 

After that activity when the user starting the chat, i am getting the user information as expected from the front end to my bot.

**Comment by shunyh** [comment]
@shanugit 

Just do a debug by bot-emulator, and I can get the User info from conversation update activity:

![image](https://user-images.githubusercontent.com/7311188/82991543-6b762280-a030-11ea-818f-c77593df937b.png)

The difference is the first activity is from the client(bot-emulator) to bot-service instead of from bot to the user.

Hope helps.

**Comment by shanugit** [comment]
@shunyh  -

For the bot emulator i am also getting the same activity. It have the conversation Id and name.

But when i am sending conversation update for the first time (from bot to user) i am looking for the userId from the font end integration code (from user to bot).

After user starts the chat, its having the userID and name parameter in the activity.

My requirement is to get the userId in the first conversation update activity from End User to Bot.

**Comment by stevkan** [comment]
@shanugit, thank you for your patience. Per the Web Chat [docs](https://github.com/microsoft/BotFramework-WebChat/blob/88f96f4ece58dcf802b8344388db901977c44b0a/docs/ACTIVITYTYPES.md#what-activity-types-does-web-chat-support), conversationUpdate is only "sent between the bot and the channel. The channel does not send these events to Web Chat." So, unfortunately, there is no way to append user details to a conversationUpdate that is received by the bot.

I think the closest you are going to get is to use the method suggested in the [04.api/a.welcome-event](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event) sample. In this scenario, when Web Chat connects, an event is sent to the bot (that includes the user details) which your bot can then act upon, as shown here:

```js
activity: {
  callerId: 'urn:botframework:azure',
  channelData: {
    clientActivityID: '1591229855361xmy8kkisn4a',
    clientTimestamp: '2020-06-04T00:17:35.362Z'
  },
  channelId: 'directline',
  conversation: { id: 'I82YTEOX9W6DDnGtDErzL2-f' },
  entities: [ [Object] ],
  from: {
    id: 'dl_15912298546410.ina72gfrvh',
    name: 'Seamus',
    role: 'user'
  },
  id: 'I82YTEOX9W6DDnGtDErzL2-f|0000000',
  locale: 'en-US',
  name: 'webchat/join',
  rawTimestamp: '2020-06-04T00:17:35.4406139Z',
  recipient: { id: 'mybot@QaeuoeEamLg', name: 'My Bot' },  
  serviceUrl: 'https://directline.botframework.com/',
  timestamp: 2020-06-04T00:17:35.440Z,
  type: 'event',
  value: {
    language: 'en-US'
  }
}
```

Closing this as resolved.
