### ISSUE TITLE
TypeError on console using CDN, Angular and Cognitive Speech Services (o.finally is not a function)

### ISSUE THREAD

**Issue by palancana** [microsoft/BotFramework-WebChat#3175]
## Screenshots

![Screenshot 2020-05-27 at 17 14 32](https://user-images.githubusercontent.com/9049420/83023275-bb0f1b00-a03d-11ea-920a-a132e53d4770.png)

## Version

Using latest CDN with Angular. Happens in Chrome and Firefox as well.
`<script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>`
```
<meta name="botframework-directlinespeech:version" content="4.9.0">
<meta name="botframework-webchat:bundle:variant" content="full">
<meta name="botframework-webchat:bundle:version" content="4.9.0">
<meta name="botframework-webchat:core:version" content="4.9.0">
<meta name="botframework-webchat:ui:version" content="4.9.0">"
```
## Describe the bug

I'm using Cognitive Speech Services. When tapping on the microphone, the error in the capture above appears. When the mic button is pressed again, the same error happens. The STT and TTS, despite the console error, works. 

## Steps to reproduce

My code, removing keys is similar to this:

```ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';

declare global {
  interface Window {
    WebChat: any;
  }
}

window.WebChat = window.WebChat || {};

@Component({
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.scss'],
})
export class ChatComponent implements OnInit {

  @ViewChild('botWindow') botWindowElement: ElementRef;

  constructor() {}

  async ngOnInit() {

    const directLine = window.WebChat.createDirectLine({
      domain: 'DIRECTLINE_API',
      secret: 'SECRET',
      webSocket: false,
    });

    async function fetchCredentials() {
      const res = await fetch('https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issuetoken', {
        method: 'POST',
        headers: { 'Ocp-Apim-Subscription-Key': 'SECRET' },
        redirect: 'follow',
      });

      if (res.ok) {
        return {
          authorizationToken: await res.text(),
          region: 'westeurope',
        };
      } else {
        throw new Error('Failed to retrieve authorization token for Cognitive Services.');
      }
    }

    const webSpeechPonyfillFactory = await window.WebChat.createCognitiveServicesSpeechServicesPonyfillFactory({
      credentials: fetchCredentials,
    });

    window.WebChat.renderWebChat(
      {
        directLine,
        userID: 'USER_ID',
        username: 'USERNAME',
        selectVoice: (voices, activity) => {
          console.log(voices);
          return voices.find(({ name }) => /AriaNeural/iu.test(name));
        },
        webSpeechPonyfillFactory,
        sendTypingIndicator: false,
        styleOptions: {
          hideUploadButton: true,
        },
      },
      this.botWindowElement.nativeElement
    );

  }
};
```

## Expected behavior

No error should appear on the web console. 

## Next steps

Can anyone help me find the issue? I don't see why it displays the error message if SST and TTS are working. Also, if there is a link to a CDN without an uglified and minified version of the framework, maybe the error description will be more specific.

**Comment by compulim** [comment]
Thanks for reporting.

We will need to repro on our side. The `o.finally` should be `new Promise(...).finally`.

@palancana can you do me one quick favor? While you are in Angular, can you type the following code in console and see what it reported?

```
new Promise(() => {}).finally
```

When I run it in Chrome, I am seeing the following screenshot:

![image](https://user-images.githubusercontent.com/1622400/83293985-671d4700-a1a1-11ea-836d-f0ffa81b531f.png)

Wonder if Angular de-polyfilled it, because `Promise.finally` is in browser for quite some time.

![image](https://user-images.githubusercontent.com/1622400/83294061-84521580-a1a1-11ea-932b-b87249c53283.png)

**Comment by palancana** [comment]
Yes! That's the thing! 

When I run `new Promise(() => {}).finally` in the console in my Angular application, I receive `undefined`. By some strange reason, the polyfill was not getting loaded on my project. I found a way to forcefully add it, and now it's working! 🎉 

So, as it looks like I'm the only one having this issue and if it can't be reproduced in another Angular project, we can close this issue as solved. 

Thanks for your fast reply!!

**Comment by palancana** [comment]
@compulim, I forked the hosting with Angular repository recommended on the [samples](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/f.host-with-angular) and after adding Cognitive Speech Services, it doesn't have the error I was having on my project. So yeah, I assume we can close this issue! 

Thanks again!
