### ISSUE TITLE
Show first text-bubble at the top of chatbox

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#3185]
The rendering of messages in the chatbot start at the bottom. Especially with multiple answers sent by the bot (eg a welcome menu), reading these answers feels 'unnatural' to some of the users I spoke with. This is especially the case for the first messages sent by the bot. As soon as the chatwindow fills up, the 'pain' becomes less.

Is there a way to show the first messages at the  top?

**Comment by compulim** [comment]
Currently we don't have any style options to do it.

You can consider going through [idiosyncratic styling route](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization/b.idiosyncratic-manual-styles) and set the CSS of following element to `flex-grow: 0`, it will make bubbles goes from top of the page.

Please do note that the idiosyncratic route has its weaknesses. You can read more about it from the sample.

![image](https://user-images.githubusercontent.com/1622400/83437820-43523f00-a3f5-11ea-9a10-0956963cdc75.png)

**Comment by HesselWellema** [comment]
thank you @compulim. I will give it a go. I understand the weaknesses of this route

**Comment by compulim** [comment]
Thanks @HesselWellema.

BTW, when I wrote this `<div>`, I think someone will actually ask this question. Finally. 😁

I am always excited to see how developers turn Web Chat up-side-down and snap it into pieces. 😉

**Comment by HesselWellema** [comment]
No luck this time. I added some custom css in stead of the idiosyncratic styling. As a result, the sendbox (.main) moved to the top 😕. I am working from the minimizable webchat sample (react implementation).

**Comment by compulim** [comment]
On my screenshot, the send box is at below. Can you confirm you modify the correct `<div>`? It should be the previous sibling of `<ul>`.

**Comment by HesselWellema** [comment]
![image](https://user-images.githubusercontent.com/23032884/83442760-00ba5200-a449-11ea-9cde-dba659248b39.png)

**Comment by compulim** [comment]
When I try to modify the "minimizable" sample, it works, https://microsoft.github.io/BotFramework-WebChat/06.recomposing-ui/a.minimizable-web-chat/.

![image](https://user-images.githubusercontent.com/1622400/83444053-a6e16a00-a3ff-11ea-8472-7a6a2015eaa6.png)

**Comment by HesselWellema** [comment]
Ok. So just adding it in css or teh DevTools does not do the trick 😉 I really need to use this createStyleset approach. I will do that. Thanks for your time and help 👍

**Comment by HesselWellema** [comment]
@compulim . Would you mind sharing the code you used to modify the "minimizable" sample like you mentioned above? I checked all customizable elements that are customizable via  idiosyncratic styling but wasn't able to find one to customize the flex-grow property of the css-mfy564 class.
