### ISSUE TITLE
[Accessibility] Text read repetitively on Android Chrome and TalkBack

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3201]
## Version

`master`

## Describe the bug

This is related to a bug on Android Chrome.

https://issuetracker.google.com/issues/157888765

## Steps to reproduce

(Please see the Issue Tracker bug)

## Expected behavior

When reading the transcript, TalkBack should only talk once for every entry.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Same with Internet Explorer and iOS

**Comment by corinagum** [comment]
I believe this one might be fixed - needs repro and hopefully close.
