### ISSUE TITLE
Update docs.microsoft.com for Direct Line App Service Extension

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3207]
## Feature Request

- Update https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0
   - You can copy sample code from https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/i.protocol-direct-line-app-service-extension
- Typo in page title, "WebChat" should be "Web Chat"
- First version to support DL ASE in Web Chat are
   - `botframework-directlinejs@0.12.0`
   - `botframework-webchat@4.9.1` (TBD)

[Enhancement]

**Comment by DDEfromOR** [comment]
Closed with https://github.com/MicrosoftDocs/bot-docs-pr/pull/2187
