### ISSUE TITLE
Microphone not turning on, even though the input hint is expectingInput - related to #3357

### ISSUE THREAD

**Issue by manish-95** [microsoft/BotFramework-WebChat#3209]
## Version

**Version**: 4.8.0
**Source**: CDN

## Describe the bug

In my Bot code, I am setting the speak property to true with each activity in the ChannelData as `activity.ChannelData = new {speak = true};`
Although this is enabling the Text to Speech output on WebChat even if the interaction with the Bot was via text and not speech , the microphone does not get turned on in case of a Prompt with inputHint as "expectingInput".

## Steps to reproduce

1. Set the relevant activity ChannelData properties for the activity used for the Prompt.
2. Set the inputHint for the Prompt Activity to "expectingInput".
3. Type a message into the Bot window which replies with a prompt.
4. TTS output is heard , but microphone does not get turned on.

## Expected behavior

Since the inputHint is set as expectingInput, and the speak property is set to true, WebChat must turn on the microphone to enable user Input by voice.

[Bug]

**Comment by a-b-r-o-w-n** [comment]
@manish-95 The `inputHint` attribute exists on the activity, not the channel data. Try setting it on the activity instead.

If this does not work, please let us know and we will track this issue as a bug.

**Comment by manish-95** [comment]
@a-b-r-o-w-n Hi, As mentioned in the repro steps, the inputHint is indeed set in the Activity, not the ChannelData. The ChannelData property for speak is to get the Bot to use TTS and voice out the message. Since the inputHint was set in Activity properties, the issue still holds good.

**Comment by a-b-r-o-w-n** [comment]
Sorry I missed that. We have work on our roadmap for the next couple of releases to polish the speech UX. We will address this as part of that effort. Thanks for the report.

**Comment by manish-95** [comment]
Thank you. I know that in previous releases, the mic would only get activated if the previous interaction was via speech input. Will there be an update in this behaviour, to consider the inputHint and channelData properties, while handling the activation of the mic ?
 I would be very interested in that feature since it is something that we've been sorely missing in our use-case of the Bot Framework.

**Comment by corinagum** [comment]
For consideration in future releases

**Comment by corinagum** [comment]
Related to #3357 - dev should verify fix for both in same PR

**Comment by amal-khalaf** [comment]
I tried reproing the issue on webchat 4.10 and 4.11 it is no longer reproing

@manish-95 could you try upgrading and see if this will fix the mic enablement issue.?

**Comment by amal-khalaf** [comment]
Closing as issue is not repro-ing on latest webchat  4.11
