### ISSUE TITLE
Rich Cards and buttons not appearing properly in Web Chat

### ISSUE THREAD

**Issue by AnithaJothi** [Microsoft/BotFramework-WebChat#321]
Hi, I am trying to display 4 Hero Cards (Rich cards) in a plain web chat channel. They seem appear properly in the emulator, however they don't appear as cards in web chat! Instead they appear as a series of text and images! Any help is much appreciated!

Emulator screenshot
![image](https://cloud.githubusercontent.com/assets/25479670/22540654/573e79be-e947-11e6-8acb-0c88ab835b81.png)

Web Chat screenshot
![image](https://cloud.githubusercontent.com/assets/25479670/22540662/6c35c39a-e947-11e6-95d4-b4734441f6ef.png)

Also buttons are appearing as plain texts!! And hene the clicks don't function either

Additional info - I am using the embedded chat control. Have embedded the iframe in to my own HTML. And I am using the C# Bot Framework. 
Please help and guide me!! :-)

**Comment by billba** [comment]
It looks like you are using the "classic" WebChat control. It can't handle richer messages. When you register your WebChat channel make sure the "preview" option is selected.

**Comment by AnithaJothi** [comment]
Hello, I am still facing the above issue. Any other reason that this could happen? I tried republishing but that didnt seem to work.
Any help is much appreciated!
Thanks!

**Comment by billba** [comment]
We removed the welcome text, as it is now easy to have your bot create its own custom welcome text by catching the 'conversationUpdate' activity. The bot image will come back in a future update. The fact that you don't see these are signs that you are running the current WebChat, which is good.

Next question: is your bot using the latest version of BotBuilder?

**Comment by billba** [comment]
Closing for lack of response. Feel free to let us know if you are still experiencing this. The more data you can give, the better.

**Comment by AnithaJothi** [comment]
Apologize the delayed response. I redeployed again and now i am able to see the Rich cards.  Appreciate your quick repsonse!

**Comment by AnithaJothi** [comment]
Hello! I am using a customized version of the open source web chat control available on git for my bot. I try to catch the "conversationUpdate" activity and display a welcome message in my bot. I send it as a Hero card with some text and an image. This works fine in the emulator and appears before any user action. However once i deploy it, the welcome message card gets displayed only after the user types in some text and not proactively. I see the same behavior in Classic web chat control as well as my cloned customized webchat.

My code snippet below
else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
                IConversationUpdateActivity update = message;
                using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, message))
                {
                    var client = scope.Resolve<IConnectorClient>();
                    ConnectorClient connector = new ConnectorClient(new Uri(message.ServiceUrl));
                    if (update.MembersAdded.Any())
                    {
                        var replyNow = message.CreateReply();
                        foreach (var newMember in update.MembersAdded)
                        {
                            if (newMember.Id != message.Recipient.Id)
                            {
                                List<CardImage> cardImages = new List<CardImage>();
                                string strCurrentURL = this.Url.Request.RequestUri.AbsoluteUri.Replace(@"/api/messages", "");
                                string imageURL = String.Format(@"{0}/{1}", strCurrentURL, "Images/icon_Hamilton_1.png");
                                cardImages.Add(new CardImage(url: imageURL));
                                string subtitle = "";
                                subtitle = @"Hamilton is Pershing's bot capable of interacting with investors to help them figure out their investment strategy and provide Digital Advice." + "  \n" + "Say 'Hi' to chat!";
                                HeroCard plCard = new HeroCard()
                                {
                                    Title = "Hamilton",
                                    Subtitle = subtitle,
                                    Images = cardImages,
                                    Buttons = null
                                };
                                Attachment plAttachment = plCard.ToAttachment();
                                List<Attachment> alist = new List<Attachment>();
                                alist.Add(plAttachment);
                                replyNow.Attachments = alist;
                                connector.Conversations.ReplyToActivityAsync(replyNow);                                
                            }
                        }
                    }
                }               
            }

I seem to be kind of stuck here and any help or debugging tips are much appreciated please!

**Comment by billba** [comment]
I can confirm that my sample bot, running live and not in the Emulator, receives `converasationUpdate` activities. I don't know the C# SDK so I can't comment on the your code specifically, but keep in mind that Emulator will supply different values than production Direct Line. I would recommend simplifying your code to just reply to all conversationUpdate messages and work up from there.

**Comment by billba** [comment]
@AnithaJothi did you make any progress on this?
