### ISSUE TITLE
https://webchat-sample-obo.azurewebsites.net/ is no longer available

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-WebChat#3214]
## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Go to https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/e.sso-on-behalf-of-authentication
1. Click on 'Try out MockBot'

## Additional context

[Bug]

**Comment by compulim** [comment]
@tdurnford can you take a look at this?

(Side note: if you need to re/build your CI/CD pipeline, our MockBot v2 is using GitHub Actions to deploy to Azure Web Apps via a mechanism called "ZipDeploy". I am okay if you have a different mechanism. 😉)
