### ISSUE TITLE
SSO - Cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-WebChat#3215]
## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Describe the bug

This line https://github.com/microsoft/BotFramework-WebChat/blob/270a1d41653c7253fbe87c8e881d04e5ce0cb365/samples/07.advanced-web-chat-apps/e.sso-on-behalf-of-authentication/rest-api/src/utils/createHTMLWithPostMessage.js#L2 should be window.postMessage (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage)

## Steps to reproduce

1. Setup this sample https://github.com/microsoft/BotFramework-WebChat/blob/270a1d41653c7253fbe87c8e881d04e5ce0cb365/samples/07.advanced-web-chat-apps/e.sso-on-behalf-of-authentication
1. See error

## Additional context

[Bug]

**Comment by compulim** [comment]
@tdurnford this one is also for you. 😉

**Comment by corinagum** [comment]
discussion: What is scope/schedule?
