### ISSUE TITLE
minimizable-web-chat sample does not persist conversation state

### ISSUE THREAD

**Issue by samaea** [microsoft/BotFramework-WebChat#3218]
Hi all,

Issue:- In the sample [minimizable-web-chat](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat#completed-code) it states that the "conversation state is preserved". However, upon refreshing the page the conversation history is lost and a new conversation id is generated each time.

Expectation:- For the conversation state to persist upon refreshing the page or navigating to another page which has this sample embedded into it.

**Comment by samaea** [comment]
FYI @corinagum  :)

**Comment by corinagum** [comment]
@samaea Thanks for filing. As we discussed in chat, I am adding this to our investigation list as a sample bug. We'll use this issue for future updates.

**Comment by corinagum** [comment]
@compulim I believe you did the refactor for this one. Do you have insight?

**Comment by samaea** [comment]
Got this working by leveraging the code snippet here https://github.com/microsoft/BotFramework-WebChat/issues/2396#issuecomment-530931579 and @tdurnford's amazing help! 

1. Navigate to the MinimizableWebChat file:- https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/06.recomposing-ui/a.minimizable-web-chat/src/MinimizableWebChat.js

1. Replace 

`  const handleFetchToken = useCallback(async () => {
    if (!token) {
      const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
      const { token } = await res.json();

      setToken(token);
    }
  }, [setToken, token]);`

with 

`  const handleFetchToken = useCallback(async () => {
	  let { conversationId } = sessionStorage;
	  if(!token){
		  alert(conversationId);
	if (conversationId) {
		alert("Found existing");
      const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST', headers: {'conversationId': `${conversationId}`}});
      const { token } = await res.json();
		      setToken(token);
    }else{
	  const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
      const { token, conversationId } = await res.json();
		      setToken(token);
	  sessionStorage.conversationId = conversationId;
		
	}

	  }
	

  }, [setToken, token]);`

The above example assumes that the endpoint https://webchat-mockbot.azurewebsites.net/directline/token is capable of resuming a conversation as documented here:- https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0.

**Comment by corinagum** [comment]
Thanks @samaea and @tdurnford :) Assigning back to myself for the fix.

**Comment by samaea** [comment]
Sorry, just fixed the code rendering snippet issue :)
