### ISSUE TITLE
How to Securely Integrate WebChat/Directline in SharePoint Online

### ISSUE THREAD

**Issue by lakshyanits** [microsoft/BotFramework-WebChat#3221]
Trying to deploy a bot developed in MS bot framework v4.0 on SharePoint online page. Users need to login to SharePoint to access the bot, therefore, can't add an authentication at bot level as users have to login twice that will result in poor user experience.

Integration is done with the help of token fetched by calling Web Chat Bot connector API with Web Chat channel 'Security Key'. Followed Option 1 in the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0)

Additionally, we don't have any in-premises resource or SharePoint Add-in.

**Issue**

SharePoint being a client-side app poses a threat of channel 'Security Key' being exposed i.e. it can be fetched in browser's developer tools and can be used to integrate our bot on their website.

**I have already Tried**

1. Minify the javascript and add it to the web part, it makes it difficult to read 'Security Key' but not impossible.
2. Single Sigh-On(SSO), SSO is not possible without an OAutCard at bot level, so trying to avoid it.
3. Create a trigger/ function app to hide bot connector rest call and only expose token but it requires some additional cost on resources.
4. I did not find a way to pass SharePoint logged in user context or token from SharePoint to the bot.

**Expectation**

1. To secure channel 'Security Key' so that it can't be accessed in the developer tool. or
2. Find a way to pass SharePoint logged in user context or token from SharePoint to the bot and validate the same at the bot end. or
3. Hide the rest call to bot connector API through a free trigger in SharePoint online.

Open to any other solution or suggestion as well.

**Comment by compulim** [comment]
For token exchange (option 1), the operation should be done on the server, not in the browser. When it's done on the server, the secret only live in the server and never get exposed.

We are not expert on SharePoint. For user identity on SharePoint, regardless it is Web Chat or other add-in, you can start from this documentation, https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-user-identity-and-properties-in-sharepoint.

**Comment by srinaath** [comment]
Closing it for inactivity
