### ISSUE TITLE
reassignment of a const variable 

### ISSUE THREAD

**Issue by laghim** [microsoft/BotFramework-WebChat#3227]
## Screenshots
![image](https://user-images.githubusercontent.com/22259701/84109363-32c04b00-aa2b-11ea-8fb1-038cae542480.png)

## Describe the bug

Hi, just wanted to point out a small issue in ___tests__/clockSkew.js_. 
There is a const defined variable "activityObservers" which is then reassigned. See screenshot.
Thanks!

[Bug]

**Comment by a-b-r-o-w-n** [comment]
@laghim thanks for the issue report. Would you be open to submitting a PR fixing this?

**Comment by laghim** [comment]
hi @a-b-r-o-w-n, sure I will open a PR and fix this. thanks!
