### ISSUE TITLE
Configure a Chat-bot to speak (TTS), before it is spoken to

### ISSUE THREAD

**Issue by nfreear** [microsoft/BotFramework-WebChat#3228]
Hi,

Note, we're a Microsoft '_AI for Accessibility_'-sponsored project (_ADMINS_).

We're developing a speech-enabled Chat-bot, using a hybrid '`ponyfill`' -- Azure Cognitive services for speech recognition (STT), and Directline (browser) for synthesis (TTS).

## Screenshots

`n/a`

## Version

We're using the latest build of `webchat.js` via CDN (currently _4.9.0_) (https://cdn.botframework.com/botframework-webchat/latest/webchat.js), targeting mobile and desktop evergreen browsers.

We are __not__ using _React_, or an `<iframe>`-based embed.

## Describe the bug

We'd like the Bot to speak/synthesise introductory text, before the user first responds (Bot says: "_Hi, I’m a virtual assistant here to help you get the right support for your studies ..._").

Is this possible?

(_So, I think this is a documentation/ configuration bug and/or a feature request._)

## Expected behavior

 1. When user visits the Chat-bot page in their browser, they are prompted to give permission to use their microphone,

 2. The Chat-bot then speaks (TTS) "_Hi, I’m a virtual assistant here to help you ...  ... Is this correct?_",

 3. The Bot then waits for the user to either press the "_microphone_" button and say "_Yes_" or "_No_" or to type or click the "_Yes_" or "_No_" button?

Currently, the Chat-bot only speaks/ synthesises after the first "Yes"/"No"
response from the user.

## Additional context

Thank you,

Nick.

[Bug] [Enhancement] [Speech]

----

**Comment by a-b-r-o-w-n** [comment]
@compulim Is this possible today or is there a workaround?

**Comment by compulim** [comment]
It's not possible today. Most browsers block media playback until the user click/tap/type on the page. So we will need to have a splash screen for user to "unmute" the browser. You can find the code to "prime" the browser by searching in our codebase for the keyword `prime`. And you will need to test it on all (7) browsers that support media playback separately, as the behavior varies between browsers.

Setting speech as default input is a feature we planned for #2211. Once speech is set as input mode, all in/out will be through speaker + microphone. The feature is not planned for R10 (August).

**Comment by nfreear** [comment]
Hi @compulim and @a-b-r-o-w-n,

Thank you for the quick responses. I've started looking into the [`prime`](https://github.com/microsoft/BotFramework-WebChat/search?q=prime&unscoped_q=prime)-related code.

Yours,

Nick
