### ISSUE TITLE
None of the “sha384” hashes in the integrity attribute match the content of the subresource.

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3238]
## Screenshots

![img](https://user-images.githubusercontent.com/22778273/84420002-43f58d00-abce-11ea-85bf-e5d92b609da9.png)

## Version

CDN 4.9.1

## Describe the bug

Under error console it shows error with message 
"Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.botframework.com/botframework-webchat/4.9.1/webchat.js' with computed SHA-256 integrity '/uKEj+TXU//TeP3tqa81MmH9ap2xVN1bogUjrvCTr/M='. The resource has been blocked".

## Steps to reproduce

1. Add WebChat CDN 4.9.1 to the host application.
2. Run the application.
3. Observe the error under browser console.

## Additional context

CDN 4.9.0 does not have this error.

## Source Code

```
<script crossorigin="anonymous"
          integrity="sha384-MCSAp6/JY4zv0hrJhg231zdTCnIjyefitzXr46hE8XDzGGZSiEn7ClIOAEhQj6tP"
          src="https://cdn.botframework.com/botframework-webchat/4.9.1/webchat.js"></script>

<script crossorigin="anonymous"
          integrity="sha384-7GOIvwVvb++zeyLdIJlXOit8VaYsDJFo0VWa1hgXnVsUnidOjkGlNYOZfuBaepS5"
          src="https://cdn.botframework.com/botframework-webchat/4.9.1/webchat-es5.js"></script>
```

[Bug]

**Comment by compulim** [comment]
Will update them, thanks for reporting.

**Comment by compulim** [comment]
I have updated the SHA384 at https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.9.1.

We recently updated our bundle to be served gzipped. May be we didn't `gunzip` before calculating the SHA384.

I have updated the deployment steps and it should work correctly in the future.

**Comment by arman-g** [comment]
@compulim thank you, yes it works now but I see another error under the console and I am not sure if I need to open another issue for this or not.

![img](https://user-images.githubusercontent.com/22778273/84423915-1b709180-abd4-11ea-9e2f-c16f95814a2b.png)

**Comment by compulim** [comment]
Can you open this one on [`botframework-directlinejs`](https://github.com/microsoft/BotFramework-DirectLineJS)? I think this is related to the chat adapter, than Web Chat.

**Comment by arman-g** [comment]
@compulim sure, here is the issue #287
