### ISSUE TITLE
OC: Text-to-emoji (Jul 15)

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3249]
## Description

Convert `:)` into 😀 while typing (a.k.a. on-the-fly).

## Investigations

- Find out what common native/web apps on the market support this feature
   - Include 1-2 Microsoft products (no more than 40% of the scenarios we studied)
   - Include 3-5 products in total
- Document out how they behave
   - How to undo the automatic emoji conversion?
      - <kbd>CTRL</kbd> + <kbd>Z</kbd>
      - <kbd>BKSP</kbd>
   - How they works when copy-and-pasting `:)` into the box?
   - How they behave in gray areas (when emoji conversion should be disabled)?
      - Do they requires spaces around the emoji?
         - Type <kbd>A</kbd><kbd>B</kbd><kbd>C</kbd><kbd>:</kbd><kbd>)</kbd>, will they convert to "ABC😀", or does it requires a space between <kbd>C</kbd> and <kbd>:</kbd>?
   - What emoji text do they support?
      - E.g. do they support `:)` and `(:` at the same time?

## Goals

- Support <kbd>CTRL</kbd> + <kbd>Z</kbd> for undo
   - Try to use OS undo capability as much as possible, otherwise, we might conflict
   - Verify if other apps also support using <kbd>BKSP</kbd> key to undo
   - Test:
      1. Focus on the text box, type `:)`, it converted to 😀
      1. Blur the focus
      1. Focus on the text box again, press <kbd>CTRL</kbd> + <kbd>Z</kbd>, it should undo
- Need to make sure we don't convert unneeded `:)`
   - Verify behavior from other apps to see what scenario we should not convert
   - Type/paste `stream.forEach(System.out::println);`, it should not convert `::println` into `:😋rintln`
- Options
   - Disable this feature (either by a flag, or emptying out the conversion table)
   - Override the emoji conversion table
- We should only ship culture neutral emojis
- Make sure the work is componentized and can be carried forward when we implement #2211
- Make sure it works with both `<input>` and `<textarea>` (we have two controls today)
- Sample
   - E.g. type `spa`, it convert to ♨
      - The word is chosen instead of symbols, because we want to see how the feature behave in words, like `space`, `spatula` or `asparagus`

## Non-goals

- Emoji panel
   - OS already provided an emoji panel
- Any overlapping panel to select emojis
- Turning our text box into `contenteditable` box
- Only support OS-based Unicode emojis
   - Non-Unicode emojis requires us to turn the text box into `contenteditable` box

**Comment by corinagum** [comment]
Need to consider the fact that Ctrl Z would not be available for mobile, therefore backspace may make more sense. I'll start data collecting

**Comment by corinagum** [comment]
|                       | Teams            | Skype                     | Slack                                      | WhatsApp   | Messenger              |
|-----------------------|------------------|---------------------------|--------------------------------------------|------------|------------------------|
| Undo autocorrect      | Ctrl + Z (buggy) | No                        | Ctrl + Delete; Deletes emoji or shows text | Backspace  | No                     |
| Copy/Paste            | No               | Converts after send       | Yes                                        | No         | Converts after send    |
| Undo after blur       | Yes              | N/A (converts after send) | Deletes emoji                              | Yes        | No                     |
| `:)`                  | Yes              | Yes                       | converts to `:)` emoji                     | No (`:-)`) | Yes                    |
| `(:`                  | No               | No                        | Yes                                        | No         | converts to `:)` emoji |
| spaces required?      | No               | No                        | Yes                                        | No         | Yes                    |
| Disable feature       | No               | No                        | No                                         | No         | No                     |
| Add list of own emoji | No               | No                        | Yes                                        | No         | No                     |

**Comment by corinagum** [comment]
Base emoji autocorrect set will be based off the following list: https://support.microsoft.com/en-us/office/autocorrect-emojis-in-documents-and-email-601cad94-1a54-41e2-8cf8-4b09a6eadfe1

Confirmed with IC3 team

**Comment by compulim** [comment]
Added clarifications above, copied here:

> - How they behave in gray areas (when emoji conversion should be disabled)?
>    - Do they requires spaces around the emoji?
>       - Type <kbd>A</kbd><kbd>B</kbd><kbd>C</kbd><kbd>:</kbd><kbd>)</kbd>, will they convert to "ABC😀", or does it requires a space between <kbd>C</kbd> and <kbd>:</kbd>?
> - Need to make sure we don't convert unneeded `:)`
>    - Verify behavior from other apps to see what scenario we should not convert
>    - Type/paste `stream.forEach(System.out::println);`, it should not convert `::println` into `:😋rintln`

**Comment by corinagum** [comment]
Note on accessibility:
|                 | Chrome/NVDA | Edge/Narrator | Chrome/Narrator |                                         |
|-----------------|-------------|---------------|-----------------|-----------------------------------------|
| hi              | ❌           | ❌             | ❌               |                                         |
| hi[space]       | ✔           | ✔             | ✔               |                                         |
| :)              | ❌           | ❌             | ❌               |                                         |
| :)[space]       | ❌           | ✔             | ✔               |                                         |
| [C&P]hi         | ❌           | ❌             | ❌               |                                         |
| [C&P]hi[space]  | ❌           | ✔             | ✔               |                                         |
| [C&P]:)[space]  | ❌           | ✔             | ✔               |                                         |
| [Emoji panel]:) | ❌           | ❌             | ❌               | (all combos read on selection in panel) |
