### ISSUE TITLE
Create a new bundle without speech features and reduce the size for bundle

### ISSUE THREAD

**Issue by lorenz-haenggi-axa** [microsoft/BotFramework-WebChat#3256]
## Feature Request

**Is your feature request related to a problem? Please describe.**
we are using the newest Bundle version 4.9.1 of the Webchat because we have to customize the chat due to our branding restrictions. We are using own webcomponents with react.
Therefore we cant use the CDN Bundle.

We build using npm and deploy on our axa.ch website. The generated bundle is **now "compressed" > 570KB**. Our Analytics, SEO and UC teams removed our bot from the website due to this heavy size. For sure we are also using other features too. But the webchat is far too big.

**Issue:** if we wanted to use the minimal CDN bundle we have to rewrite all the code and cant use our webcomponents built for this.

We are frustrated because the bundle is too big for an extensive use with own web-components. The library is great, but too big and it contains features which could be an add-on

The biggest issue is for our customer. Due to this size we are not allowed to use the chat on our most important pages and this is bad for the customer that want digital help.

**Describe the suggestion or request in detail**
Question: could you do a new bundle without the speech features because this library is using a lot of space. And introduce a plugin-architecture to be able to add new features if needed.

create a new bundle without speech library dependency and and allow to add speech as an add-on.

alternative solution: use the CDN minimal javascript version and we have to rewrite the whole code again. If we are not successful with styling we have to build our own webchat just using directline API.
Which I believe is not the idea of the inventor of this webhat library

[Enhancement]
![axa ch-ADA-webchat-size](https://user-images.githubusercontent.com/62747378/84574022-4f021600-ada4-11ea-8c27-13ec96d687a2.PNG)
![axa ch-ADA-webchat-example](https://user-images.githubusercontent.com/62747378/84574025-51647000-ada4-11ea-800a-6a1b000952fd.PNG)

**Comment by vishwacsena** [comment]
@compulim can you take a look and comment?

**Comment by compulim** [comment]
What's your target size for gzipped JS? Our minimal bundle is 521 kB gzipped. Have you consider using code-splitting to load Web Chat on-demand?

We published `stats.json`. You can use [Webpack Visualizer](https://chrisbateman.github.io/webpack-visualizer/) to see what's inside.

Web Chat is huge because we are a very complicated UI with huge customization options. You can consider rebuilding the UI by using our APIs and hooks. That would save you lots of time on business logics.

Breakdown for a numerous big contributors:

- Required
   - DirectLineJS
      - The version of RxJS we use is huge (2.5% + 2.0% + 2.4%)
   - Markdown-It for internal use (2.3%)
      - We use Markdown-It for some localized strings with hyperlinks
   - Localization strings (2.3% + 2.3%)
      - We currently bundle 43 languages
- Optional
   - Adaptive Cards (3.5% + 2.8%)
   - Cognitive Services Speech Services (8.3%)
   - Markdown + HTML sanitizer (1.8% + 5.3% + 0.2%)
      - The huge part (5.3%) goes to CSS sanitizer, `postcss`, which we don't exactly using it

**Comment by lorenz-haenggi-axa** [comment]
hi @compulim  - thanks for the detailed feedback about our topic.
to your questions
- I was told that it should be ~200K

i checked our stats.json and I see the following split:
- all "blue circles" are from webchat component 
- all "red circles" are cognitive libraries and adaptive cards 

![image](https://user-images.githubusercontent.com/62747378/85017087-3494b780-b16b-11ea-8ad5-a757085b8453.png)

here I have calculated the optinmizations without speech and the % part of webchat.js inside our component
![image](https://user-images.githubusercontent.com/62747378/85017961-a3bedb80-b16c-11ea-97dc-3ecbfb78df89.png)

question
- how would you propose us to solve this issue? any options beside today?
- shall we fork the library and remove speech, built and test it?
- shall we start using directline API only?
- are we able to remove the optional libs just with customizing webpack? I am not sure

thanks for a valuable input

**Comment by lorenz-haenggi-axa** [comment]
we also saw that the total size of the library is now 180KB larger between version 4.6 and 4.9. we have upgraded now to your latest version

**Comment by compulim** [comment]
Can you switch to the minimal bundle (webchat-minimal.js), that entrypoint skipped loading Cognitive Services and Adaptive Card and will not add to your bundle size.

IIRC, you are using `npm install` to use Web Chat. Can you try out this?

```diff
- import ReactWebChat from 'botframework-webchat';
+ import ReactWebChat from 'botframework-webchat/lib/index-minimal';
```

This will use the minimal bundle: no Cognitive Services, no Adaptive Cards, no Direct Line Speech.

Let's check the bundle size after these and see if it works in your case.

**Comment by lorenz-haenggi-axa** [comment]
Dear @compulim 

thanks - we have tested it and there is no difference
I integrated 2 calls and 2 were not possible (different files)
`
import { connectToWebChat } from "botframework-webchat-component";
import { createStore, createDirectLine } from "botframework-webchat/lib/index-minimal";
import ReactWebChat from 'botframework-webchat/lib/index-minimal';


import { DirectLine } from "botframework-directlinejs";
import { DirectLine } from "botframework-directlinejs";
`

is there an issue with the "botframework-directlinejs"  and still importing all?
i will try to generate a stats.json

**Comment by lorenz-haenggi-axa** [comment]
here is our size chart
![image](https://user-images.githubusercontent.com/62747378/86397960-1a97c080-bca5-11ea-9347-e411a12ef5a2.png)

and the details
![image](https://user-images.githubusercontent.com/62747378/86398021-369b6200-bca5-11ea-91d2-4da506326b67.png)

there is no much difference

**Comment by compulim** [comment]
Could you investigate why Cognitive Services is still there when importing `index-minimal`?

In [our Webpack.config.js](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/bundle/webpack.config.js#L10), we build `webchat-minimal.js` out of `index-minimal.ts`. And when I look at [our `stats.json`](https://github.com/microsoft/BotFramework-WebChat/releases/download/daily/stats.json), I am not seeing Cognitive Services.

![image](https://user-images.githubusercontent.com/1622400/86401746-9a9b3780-bc5f-11ea-8547-898c3fdb1aa4.png)

- Red crosses: DirectLineJS-related
- Purple cross: Markdown-It (used for localization, we could replace with a smaller lib, if any)
- Yellow crosses: Localization and internationalization

**Comment by lorenz-haenggi-axa** [comment]
here is our webpack.config.js

(had to zip it to upload)
[webpack.config.zip](https://github.com/microsoft/BotFramework-WebChat/files/4870628/webpack.config.zip)

**Comment by compulim** [comment]
Let me try to build a new `create-react-app` project and see if I can repro it.

**Comment by lolo8304** [comment]
Do you need our webpack configurations json?

**Comment by lorenz-haenggi-axa** [comment]
here is our webpack.config.js

[webpack.config.zip](https://github.com/microsoft/BotFramework-WebChat/files/4973273/webpack.config.zip)

**Comment by compulim** [comment]
I am being tightened up on a new feature and hope to get something done this week. 🙇🏻‍♂️

**Comment by daveta** [comment]
Hi @lorenz-haenggi-axa : fyi, this is still on the radar.

**Comment by compulim** [comment]
I created a minimal Webpack + Web Chat repo here to see how things work, without too much emissions, https://github.com/compulim/webchat-bundle-size-webpack.

By switching this line of code, [`src/index.js:3`](https://github.com/compulim/webchat-bundle-size-webpack/blob/main/src/index.js#L3), I am able to switching between a full build and minimal build. For instance, full build include speech support and Adaptive Cards. While the minimal build include only minimal experience.

I am seeing Speech SDK being loaded when full bundle is selected, which produced a 11.8 MiB file.

![image](https://user-images.githubusercontent.com/1622400/90682774-5ae1dc80-e21a-11ea-90f1-09652ec51669.png)

But when minimal bundle is selected, it produced a 
[stats.zip](https://github.com/microsoft/BotFramework-WebChat/files/5098918/stats.zip)

file size of 8.27 MiB only.

![image](https://user-images.githubusercontent.com/1622400/90682805-6503db00-e21a-11ea-851e-434178bcc1f8.png)

This is based on Web Chat 4.10.0, which was released yesterday.

I have attached the `stats.json` files for both build.

@lorenz-haenggi-axa could you study this and see why it differ in your build?

**Comment by lolo8304** [comment]
Thx @compulim - I will talk with our web pack specialist to see how we can fix our build. 

This is great news.  And i will also use the newest version.

**Comment by compulim** [comment]
Thanks @lolo8304.

**Comment by LucaMele** [comment]
Hello @compulim, I have not red all the inputs and saw in detail your webpack build but have one question: Is your build export which have smaller size compatible with IE11?

**Comment by lorenz-haenggi-axa** [comment]
hi @compulim  - we are working on the topic in this next sprint and would like to ask you if you have a short feedback to the question of @LucaMele ? he is one of our FE mastermind

**Comment by compulim** [comment]
Good to know, @lorenz-haenggi-axa.

Yes, everything need to be imported from `/lib/index-minimal`, otherwise, it will import the full version.

Let me know if you have any suggestions on reducing the package size. We love to make Web Chat smaller while maintaining a healthy feature set.
