### ISSUE TITLE
Facing Issue while establishing a connection with Web Chat 4 with SPFx 

### ISSUE THREAD

**Issue by Siri311** [microsoft/BotFramework-WebChat#3257]
###Description
Created a SPFx web part using react and did the npm install like below
npm install --save botframework-webchat
npm install --save botframework-directlinejs

After the imported required things and then 
```
var botConnection = new DirectLine({
      domain:'<domain>',
      secret: "<secret key>"
    });
var user = {id:this.props.context.pageContext.user.Eamil, name: this.props.context.pageContext.user.displayName}

return (<div style={{height:400}}>
      
      <RenderWebChat directline = {botConnection} user={user} />
      
      </div>
    );
```
### Error Details 
```
createStore.ts:16 TypeError: Cannot read property 'connectionStatus$' of undefined
    at connectionStatusToNotification$ (connectionStatusToNotificationSaga.js:24)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at next (redux-saga-core.esm.js:1157)
    at proc (redux-saga-core.esm.js:1108)
    at redux-saga-core.esm.js:585
    at immediately (redux-saga-core.esm.js:56)
    at runForkEffect (redux-saga-core.esm.js:584)
    at runEffect (redux-saga-core.esm.js:1204)
```

Thanks in advance

**Comment by vishwacsena** [comment]
@Siri311 can you clarify what version you are on? 

@compulim can you take a look and comment?

**Comment by dmvtech** [comment]
Is this just a typo in this post, or is this incorrect in your code as well?
id:this.props.context.pageContext.user.**_Eamil_**

Aside from that, this is essentially what I have setup and working:
```
  public render(): React.ReactElement<IBotWebPartProps> {
    //Current User information from Context
    var user = { id: this.props.context.pageContext.user.email, name: this.props.context.pageContext.user.displayName };
    const { directLink, store } = this.state;


    return (
      <div className={styles.botFrameworkChat} style={{ height: 500 }}>
        <ReactWebChat directLine={directLink} store={store} userID={user.id} username={user.name} />
      </div>
    );
  }
```

**Comment by Siri311** [comment]
###Version Details 
###Package.json --File (dependencies)
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@pnp/common": "^1.3.11",
    "@pnp/logging": "^1.3.11",
    "@pnp/odata": "^1.3.11",
    "@pnp/sp": "^1.3.11",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@types/webpack-env": "1.13.1",
    "botframework-directlinejs": "^0.12.0",
    "botframework-webchat": "^4.8.0",
    "office-ui-fabric-react": "6.189.2",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "xhr2": "^0.2.0"

**Comment by Siri311** [comment]
### Code 
 constructor(props) {
    super(props);
    this.state = {
      directLine: createDirectLine({
        domain:'<>',
        secret: "<>",
        webSocket:true
      }),
      store:createStore({},function(_ref){
        const dispatch = _ref.dispatch;
        return function (next) {
        return function (action) {
            if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') {
                
            }
            if (action.type === 'DIRECT_LINE/DISCONNECT_FULFILLED') {
                //console.log('store: direct line disconnected');
            }

            if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
                console.log('store: direct line connected');
            }

            return next(action);
        };
    };
      })
    };
  }

public render(): React.ReactElement<IReactBotProps> {
this.user = {id:this.props.context.pageContext.user.email, name:this.props.context.pageContext.user.displayName}
    return (      
      <ReactWebChat directline = {this.state.directLine} store={this.state.store} userID={this.user.id} userName={this.user.name} />
      
    );
}
![Failed ConnectionStatusNotification](https://user-images.githubusercontent.com/40290737/84780026-b74e3300-b002-11ea-804d-7a949a993611.png)
![Failed CreateStore](https://user-images.githubusercontent.com/40290737/84780030-b7e6c980-b002-11ea-9cb2-e4ddc59cee8a.png)


###Error Details
TypeError: Cannot read property 'connectionStatus$' of undefined
    at connectionStatusToNotification$ (connectionStatusToNotificationSaga.js:24)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at next (redux-saga-core.esm.js:1157)
    at proc (redux-saga-core.esm.js:1108)
    at redux-saga-core.esm.js:585
    at immediately (redux-saga-core.esm.js:56)
    at runForkEffect (redux-saga-core.esm.js:584)
    at runEffect (redux-saga-core.esm.js:1204)


Still facing same issue. Please find the attached screenshots. Failed in the middle ware( createStore.ts, connectionStatusNotification.js)

**Comment by Siri311** [comment]
###Missed ReactWebChat in above comment

<ReactWebChat directline = {this.state.directLine} store={this.state.store} userId={this.user.id} userName={this.user.name} />

**Comment by compulim** [comment]
Can you check if `this.state.directLine` is undefined or an object?

`connectionStatus$` is retrieved from an object created through `createDirectLine` function.

**Comment by Siri311** [comment]
![directLineObject](https://user-images.githubusercontent.com/40290737/84808087-cbeff280-b025-11ea-820a-c86c8fcbb49a.png)

this.state.directLine is a object, please find the attached screenshot.

**Comment by compulim** [comment]
There is a typo:

```diff
- <ReactWebChat directline = {this.state.directLine} ...
+ <ReactWebChat directLine = {this.state.directLine} ...
```

**Comment by Siri311** [comment]
Thanks for the quick response. Issue Resolved.
Thank You William Wong.

It is not working In IE browser. is there any way to make it work in IE browser.

Thanks in Advance.

**Comment by compulim** [comment]
Can you look at this issue, https://github.com/microsoft/BotFramework-WebChat/issues/2511?

As you are on NPM, your code should already target ES5/IE11. Maybe you are missing a few polyfills, as outlined in #2511. (Please vote on the issue if it resolve your problem 😉)

For the article you referenced: to make sample code shorter and easier to read, they are written to be as lean as possible. Thus, we prefer to use latest syntax from latest ES revisions. And developers "downgrade" or transpile them to ES versions they need.

**Comment by dmvtech** [comment]
Closing as the main issue is resolved and you have steps needed to get working in IE11.
