### ISSUE TITLE
Google Chrome : Refused to get unsafe header "x-ms-bot-id"

### ISSUE THREAD

**Issue by venkatx5** [microsoft/BotFramework-WebChat#3260]
The webchat.js CDN reference throws error in Google chrome (Version 83.0.4103.97 (Official Build) (64-bit))
Error: 
**Refused to get unsafe header "x-ms-bot-id"**

## Screenshots
![image](https://user-images.githubusercontent.com/11777507/84910324-5ee76600-b0d4-11ea-8c3f-aeae9252dc51.png)

## Version
https://cdn.botframework.com/botframework-webchat/latest/webchat.js
Adding as direct reference on the page.
<script type="text/javascript" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js?v=1" crossorigin="anonymous"></script>

meta name="botframework-directlinespeech:version" content="4.9.1"
meta name="botframework-webchat:bundle:variant" content="full"
meta name="botframework-webchat:bundle:version" content="4.9.1"
meta name="botframework-webchat:core:version" content="4.9.1"
meta name="botframework-webchat:ui:version" content="4.9.1"

## Describe the bug
When trying to access the Chatbot, it logs error on console as 
Refused to get unsafe header "x-ms-bot-id"

## Steps to reproduce

1. Provide direct reference to webchat.js CDN.
2. Open the chatbot on Google Chrome.

## Expected behavior

No error should be logged in Console.

## Additional context

[Bug]

**Comment by venkatx5** [comment]
meta name="botframework-directlinespeech:version" content="4.9.1"
meta name="botframework-webchat:bundle:variant" content="full"
meta name="botframework-webchat:bundle:version" content="4.9.1"
meta name="botframework-webchat:core:version" content="4.9.1"
meta name="botframework-webchat:ui:version" content="4.9.1"

**Comment by dmvtech** [comment]
Related: https://github.com/microsoft/BotFramework-DirectLineJS/issues/287

**Comment by vishwacsena** [comment]
Closing as dupe. If the investigation for microsoft/BotFramework-DirectLineJS#287 leads us to believe the issue to be in webchat, then we will transfer that issue over here.
