### ISSUE TITLE
Sample: avatar comprehensive demo is not working

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3261]
## Screenshots

![image](https://user-images.githubusercontent.com/1622400/84960120-aca0a600-b0b5-11ea-9aae-10dced6e1e1d.png)

## Version

`master`

## Describe the bug

Navigate to https://microsoft.github.io/BotFramework-WebChat/05.custom-components/k.per-message-avatar/comprehensive.html. The page throw a JavaScript error.

Typo at https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/05.custom-components/k.per-message-avatar/comprehensive.html#L125.

```diff
- <script type="text/babel" data-presets="es2015.react,stage-3">
+ <script type="text/babel" data-presets="es2015,react,stage-3">
```

## Steps to reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/05.custom-components/k.per-message-avatar/comprehensive.html

## Expected behavior

It should show the demo properly.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Fixed in https://github.com/microsoft/BotFramework-WebChat/pull/3262
