### ISSUE TITLE
Mic not highlighted

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#3265]
## Screenshots
![image](https://user-images.githubusercontent.com/11289456/85153069-5ed19c80-b273-11ea-87e9-08ad84f48dbe.png)

## Version
4.9.1 CDN

## Describe the bug

The mic generally turns red when listening. It was doing that in 4.8.0 but now it is not.

## Steps to reproduce
click on mic icon 

## Expected behavior

mic turns red
![image](https://user-images.githubusercontent.com/11289456/85153562-f9ca7680-b273-11ea-9e48-780a2b70db66.png)

## Additional context

Implemented in an angular project

[Bug]

**Comment by srinaath** [comment]
@corinagum could you take a look at this issue if its a regression?

**Comment by corinagum** [comment]
Hmmm I'm repro-ing this problem but not consistently.

- mix between CDN and npm 
- different samples behave differently
- same samples behave differently across browsers
- red will show once but not after a repeat usage

Investigating further

**Comment by corinagum** [comment]
This is due to a styling specificity regression - fix will be up shortly.
