### ISSUE TITLE
directline connection role and name not getting in BOT conversationUpdate.

### ISSUE THREAD

**Issue by Dsencha** [microsoft/BotFramework-WebChat#3269]
For reference below - DirectLine Connection code 

(async function() {

           window.WebChat.renderWebChat(

        {

	directLine: window.WebChat.createDirectLine({

              secret: “My KEY”

           }),

           userID : "myid",

           username: "myName"

        },

        document.getElementById('chat_converse')

      );

      document.querySelector('#chat_converse > *').focus();

    })().catch(err => console.error(err));

Once Connected. We will have below objects in BOT.

{
  "type": "conversationUpdate",
  "id": "ERqgImAulq3",
  "timestamp": "2020-06-18T07:07:03.448Z",
  "serviceUrl": "https://directline.botframework.com/",
  "channelId": "directline",
  "from": {
    "id": "AicCk0YN2Ap9n2Ev1ovbuc-k"
  },
  "conversation": {
    "id": "AicCk0YN2Ap9n2Ev1ovbuc-k"
  },
  "recipient": {
    "id": "BotName@xp113vQdWDM",
    "name": "BotName"
  },
  "membersAdded": [
    {
      "id": "BotName@xp113vQdWDM",
      "name": "BotName"
    }
  ]
}

From -  section we should get id, name, role. In the "from" object name and role key is missing and id is present but with auto generated id not actual user id ** myid.

**Comment by mdrichardson** [comment]
I'm closing this here because I'll be assisting you at [your duplicate StackOverflow post](https://stackoverflow.com/questions/62513653/directline-connection-role-and-name-not-getting-in-bot-conversationupdate), which is the more-appropriate place for this.
