### ISSUE TITLE
Taking longer than usual to connect. After adding store Web Chat API Reference.

### ISSUE THREAD

**Issue by grimz11** [microsoft/BotFramework-WebChat#3272]
Hello guys, I hope you all are doing well.
I'm having a problem when using the store Web Chat API. This won't happen if I remove it on the <b>ReactWebChat</b> component. I used the Npm package of <b>"botframework-webchat v4.9.0"</b>. If you might ask why I used the store, I want the <b>action.type</b> functionality of <b>createStore</b>.

<b>Here's my implementation of the store:</b>
```typescript
  const store = createStore({}, () => (next: any) => (action: any) => {
    const toggleSendBoxEvent: any = new Event('ToggleSendBoxEvent');
    if (action.type === 'DIRECT_LINE/CONNECT_FULFILLING' && cookies.get('conversationToken') !== '')
      cookies.set('conversationToken', action.payload.directLine.token);
    if (action.type === 'DIRECT_LINE/POST_ACTIVITY_FULFILLED' || action.type === 'WEB_CHAT/SET_SUGGESTED_ACTIONS') {
      toggleSendBoxEvent.data = 'none';
      toggleSendBoxEvent.suggestedActionsArray = action.payload.suggestedActions;
      window.dispatchEvent(toggleSendBoxEvent);
    } else {
      toggleSendBoxEvent.data = 'flex';
      window.dispatchEvent(toggleSendBoxEvent);
    }
    return next(action);
  });

  window.addEventListener('ToggleSendBoxEvent', async ({ data, suggestedActionsArray }: any) => {
    const sendBoxesElement: HTMLCollection = document.getElementsByClassName('main');
    var send_Box;
    var itemsSendBox: any = sendBoxesElement;
    for (var sendBox of itemsSendBox) {
      send_Box = sendBox;
    }
    if (send_Box) send_Box.setAttribute('style', `display:${data}`);
    // Set the width of the suggested actions base on their count
    var suggestedActionsCount;
    if (suggestedActionsArray) suggestedActionsCount = suggestedActionsArray.length;
    if (suggestedActionsCount > 4) {
      const suggestedActionsElement = document.getElementsByClassName('css-y5o52s');
      var itemsSuggestedActions: any = suggestedActionsElement;
      if (await itemsSuggestedActions) {
        for (var item of itemsSuggestedActions) {
          item.children[0].style.width = '150px';
        }
      }
    }
```
<b>For the ReactWebChat component:</b>
```javascript
      <ReactWebChat
        directLine={directLine}
        store={store}
        userID={id}
        username={tokenAuth}
        className={'chat_bot'}
        locale="en-Us"
        styleOptions={{
          accent: '#348FFC',
          typingAnimationHeight: 20,
          typingAnimationWidth: 100,
          backgroundColor: 'rgb(237, 237, 237)',
          bubbleFromUserTextColor: '#fff',
          bubbleFromUserBackground: '#348FFC',
          bubbleFromUserBorderRadius: 5,
          bubbleBorderRadius: 5,
          suggestedActionBorderColor: '#348FFC',
          suggestedActionBackground: '#348FFC',
          suggestedActionTextColor: '#fff',
          cardEmphasisBackgroundColor: 'Red',
          suggestedActionBorderRadius: 5,
          avatarSize: 30,
          paddingRegular: 15,
          rootHeight: '650px',
          rootWidth: '40%',
          hideScrollToEndButton: true,
          sendBoxHeight: 80,
          hideUploadButton: true,
        }}
      />
```

<b>My directline:</b>
```javascript
const conversationToken = cookies.get('conversationToken') || `${DIRECTLINE_SECRET}`;
const directLine = useMemo(() => createDirectLine({ token: `${conversationToken }` }), []);
```

<b>And the result:</b>
![image](https://user-images.githubusercontent.com/53614600/85352885-92dde380-b539-11ea-82a5-e6faa7f72beb.png)

There's no error in the console. It's just that the conversation endpoint in my network is red. I can't find this issue anywhere on the Web. So, I'm sorry for asking it here. But maybe this is an issue on the <b>Botframework</b> itself.

It works just fine if I remove the store in <b>ReactWebChat</b> component.
![image](https://user-images.githubusercontent.com/53614600/85356597-ed7b3d80-b541-11ea-906d-2bbb241775b5.png)

**Comment by stevkan** [comment]
It looks like you are building this with TypeScript, yes? Are you able to post more of your code, in particular, whichever file(s) house the web chat components? I would like to see how your code is laid out. As it is, the JS implementation of the same works for me without delay.

**Comment by grimz11** [comment]
> It looks like you are building this with TypeScript, yes? Are you able to post more of your code, in particular, whichever file(s) house the web chat components? I would like to see how your code is laid out. As it is, the JS implementation of the same works for me without delay.

@stevkan 
This works fine until yesterday I haven't changed any of my codes and then suddenly this happens. I also created another service on my azure to make sure that I have a brand new  Free Tier messaging.

**Comment by stevkan** [comment]
Before we dig much deeper, can you try using v4.9.1 of Web Chat and see if the updated package makes any difference?

**Comment by grimz11** [comment]
@stevkan, I got it working from the <a src="https://stackoverflow.com/questions/56848336/how-to-close-and-restart-bot-conversation-from-ui">link</a> here. So, what I did is instead of calling the createStore directly I created a state to set the store. But the fact that it was working just fine and then it didn't. Anyways, my problem is done now. Thanks.
