### ISSUE TITLE
Change send button icon

### ISSUE THREAD

**Issue by david-minaya** [microsoft/BotFramework-WebChat#3274]
There is any way of change the send button icon using the `styleOptions`?

**Comment by v-kydela** [comment]
Hi @david-minaya 

It looks like [`styleOptions`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/Styles/defaultStyleOptions.js#L80-L83) does provide a way of changing the send button's color:

```js
  sendBoxButtonColor: undefined, // defaults to subtle
  sendBoxButtonColorOnDisabled: '#CCC',
  sendBoxButtonColorOnFocus: '#333',
  sendBoxButtonColorOnHover: '#333',
```

Does this resolve your issue?

**Comment by david-minaya** [comment]
No, I need to change the icon for another

**Comment by srinaath** [comment]
@david-minaya , thank you for opening this issue.  For product behavior, how-to, or general understanding questions, please use Stackoverflow.  

https://stackoverflow.com/search?q=bot+framework
