### ISSUE TITLE
How can i clear the chat inputbox after sending the message in botframework webchat?

### ISSUE THREAD

**Issue by thomas023** [microsoft/BotFramework-WebChat#3288]
Hi, im working on a bot application using react js and botframework webchat. The thing is that i want to clear the text input box (from where msgs are sent) after sending the message which is selected from the suggestion. What i mean is that if i type "My designation" the suggestion popup will come and if i click on one suggestion the message will be sent, but what i wrote in the input field will be there i want to clear that. If i type something and send its fine but the problem is when i select something from the suggestion. Everything else is fine. How can i achieve that. Any help would be really appreciated.

Her's my code ;

    ``import React from 'react';
      import { DirectLine, ConnectionStatus } from 'botframework-directlinejs';
      import ReactWebChat from 'botframework-webchat';
      import './ChatComponent.css';

     var val;
     var apiParameters = [];
     var currentFocus = -1;
     export default class extends React.Component {
      constructor(props) {
      super(props);
   
      this.state = {
        token: '',
        conversationId: '',
        directLine: {},
        view: false,
        feedBack: null,
        value: '',
        popupContent: '',
        storeValue: '',
        suggestions: [],
        suggestionCallback: '',
        suggestionTypedText: "",
        typingChecking: "false",
        
       };
       this.handleTokenGeneration = this.handleTokenGeneration.bind(this);
       this.handleChange = this.handleChange.bind(this);
       this.handleSaveFeedback = this.handleSaveFeedback.bind(this);
       this.handleSuggestion = this.handleSuggestion.bind(this);
       this.handleClose = this.handleClose.bind(this);
       this.handleSuggestionClick = this.handleSuggestionClick.bind(this);
        this.handleKeyDown = this.handleKeyDown.bind(this);
   
        this.moveHighlight = this.moveHighlight.bind(this);
  
        this.getSuggestionHtml = this.getSuggestionHtml.bind(this);
       }

       getSuggestionHtml(suggestion) {
       const lowerCaseSuggestion = suggestion.toLowerCase();
        return {
        __html: lowerCaseSuggestion.includes(this.state.suggestionTypedText) ? lowerCaseSuggestion
            .replace(this.state.suggestionTypedText, `<b>${this.state.suggestionTypedText}</b>`) : lowerCaseSuggestion
       };
      }
      handleTokenGeneration = async () => {
      console.log("11111");
      const response = await fetch(`api/TokenGenerationService/GetToken`);
      const data = await response.json();
      this.setState({ token: data.categoryObject.token, conversationId: data.categoryObject.conversationId });
      this.state.directLine = new DirectLine({ token: this.state.token });
       this.setState({ view: true });
       this.setState({ typingChecking: "true" });

       console.log("conversationId");
      };
     async handleSuggestion(val, store) {

      if (val === "") {
        this.setState({
            suggestions: []
        });
       }
      else {
          apiParameters = [];
          var valuess = null;
          const response = await fetch(`api/TokenGenerationService/GetAzureSearch?myparam1=${val}`);
          const data = await response.json();
          var values = ["Hello", "yes", "no", "exit", "Welcome", "Thank You", "Approve", "Apply leave", "Reject", "Absence Balance", "Leave Balance", "Upcoming Holidays", "Apply Comp-Off", "Approve Leave", "Raise Incident Tickets", "Project Allocation Info", "Reporting Manager Change", "Reporting Manager Approval", "Approve Isolve Tickets", "My Manager", "My Account Manager", "Generate Salary Certificate", "Isolve Ticket Status", "Internal Job Posting", "My Designation", "My Joining Date", "RM Approval", "RM Change", "Resource Allocation", "ESettlement Approval", "SO Approval", "Cash advance Approval", "Purchase Request Approval", "Referral status", "HR Ticket", "Platinum Support"];
        valuess = values.filter(s =>
            s.toLocaleLowerCase().startsWith(val.toLowerCase())
        );
        valuess = valuess.concat(data.az_search);
        this.setState({
            suggestions: valuess,
            suggestionCallback: store,
            suggestionTypedText: val.toLowerCase()
        });

        var totCount = data.az_search;
        console.log("kkkkkk" + totCount);

        var myNode = document.getElementById('Suggestion1');
  
       }

      }
      getSuggestionCss(index) {
      var HIGHLIGHTED_CSS = "HIGHLIGHTED_CSS";
      var SUGGESTION_CSS = "SUGGESTION_CSS";
      console.log("jioouu" + this.state.highlightedIndex);
       return index === this.state.highlightedIndex ? HIGHLIGHTED_CSS : SUGGESTION_CSS;
      }

      moveHighlight(event, direction) {
      event.preventDefault();
   
       const { suggestions, highlightedIndex=-1 } = this.state;
      if (!suggestions.length) return;
      let newIndex = (highlightedIndex + direction + suggestions.length) % suggestions.length;
      console.log("lokkkk" + direction)
      if (newIndex !== highlightedIndex) {
        console.log("kkkkkkkkkkkkkkkkkkk")
        this.setState({
            highlightedIndex: newIndex,
        });
         }
       }
       keyDownHandlers = {
    
       ArrowDown(event) {
     
        this.moveHighlight(event, 1);
        },
        ArrowUp(event) {
       
        this.moveHighlight(event, -1);
       },
       Enter(event) {
        const { suggestions } = this.state;
        if (!suggestions.length) {
            // menu is closed so there is no selection to accept -> do nothing
            return
        }
        event.preventDefault()
        this.applySuggestion(suggestions[this.state.highlightedIndex]);
        },
      }

       handleKeyDown(event) 
       if (this.keyDownHandlers[event.key])
        this.keyDownHandlers[event.key].call(this, event)
      }
 

      async handleSuggestionClick(event) {
     await this.applySuggestion(event.currentTarget.textContent);
       }

      async applySuggestion(newValue) {
      await this.setState({ typingChecking: "false", suggestions: [], highlightedIndex: 0 });
      this.state.suggestionCallback.dispatch({
         type: 'WEB_CHAT/SEND_MESSAGE',
         payload: {
            text: newValue,
        }
      });
      await this.setState({ typingChecking: "true" });
      }

      handleClose(elmnt) {
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt !== x[i]) {
            x[i].parentNode.removeChild(x[i]);
         }
      }

      }

     async componentDidMount() {
  
     try {

        await this.handleTokenGeneration();
      

        const store =
            window.WebChat.createStore(
                {},
                ({ getState }) => next => action => {
                    this.state.directLine.connectionStatus$
                        .subscribe(connectionStatus => {
                           
                            //console.log("connect" + connectionStatus);
                            //console.log("LOP" + ConnectionStatus.ExpiredToken);
                            if (connectionStatus === ConnectionStatus.ExpiredToken) {
                                console.log("expired");
                            }

                            if (action.type === 'WEB_CHAT/SET_SEND_BOX') {
                                const val = action.payload.text;
                                if (this.state.typingChecking === "true") {
                                    this.setState({
                                        highlightedIndex: -1,
                                    });
                                    console.log(this.state.typingChecking);
                                    this.handleSuggestion(val, store);
                                }
                            }

                            if (action.type === 'DIRECT_LINE/DISCONNECT_FULFILLED') {
                                console.log("final" + connectionStatus);
                                console.log("finalexpired" + ConnectionStatus.ExpiredToken);
                                console.log("final");
                                this.handleTokenGeneration();
                                // fetch('api/TokenGenerationService/GetToken').then(conversation => 
        this.state.directLine.reconnect(conversation))
                            }
                        });

                    return next(action)
                }
            );

        this.setState({ storeValue: store });

    } catch (error) {
        console.log("error in fetching token");
        console.log(error);
    }

      this.state.directLine.activity$
        .filter(activity => activity.type === 'message')
        .subscribe(function (activity)
        {
            //console.log("oooooooooooooooooooooo");
        }
           // message => console.log("received message ", message.text)
        );
     }

    handleSaveFeedback(ans) {

      var userID = "U92656";
      var feedbackmsg = this.state.value;
      var feedbacktype = this.state.feedBack;
      var convId = this.state.conversationId;
      fetch('api/Feedback/SaveFeedback',
        {
            method: "POST",
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ Uid: userID, FeedbackMessage: feedbackmsg, Convid: convId, FeedbackType: feedbacktype })
        }).
        then(response => response.text())
        .then(data => {
            
            console.log(data.getResult);
        });
  
      this.setState({ value: '' });
     }
     feedback(ans) {
     this.setState({ feedBack: ans });

     if (ans === "Send") {
        this.handleSaveFeedback(ans);
     }
     else if (ans === "Yes") {
        this.setState({ popupContent: "How was your experience?" });
        // console.log(this.state.value)
       }
      else if (ans === "No") {
        this.setState({ popupContent: "What went wrong?" });
        // console.log(this.state.value)
        }
       }

      handleChange = (event) => {
      this.setState({ value: event.target.value });
      }

      render() {

      if (!this.state.view) {
        return <div />
        } else {
        const filteredSuggestions = this.state.suggestions.filter(
            suggestion =>
                suggestion.toLowerCase().indexOf(this.state.suggestionTypedText.toLowerCase()) > -1
        );

        return (
            <div className="react-container webchat" >
                <div  onKeyDown={this.handleKeyDown.bind(this)}>
                    <div >

                <ReactWebChat  directLine={this.state.directLine} webSocket={true} store={this.state.storeValue} sendTypingIndicator={true} />

                    </div>
                    </div>

                <div className="SuggestionParent" id="Suggestion1">

                    {this.state.suggestions.map((suggestion, index)=> (
                        <div className={this.getSuggestionCss(index)} key={index}  onClick={this.handleSuggestionClick} >
                            {suggestion
                                .toLowerCase()
                                .startsWith(this.state.suggestionTypedText) ? (
                                    <div>

                                        <b>{this.state.suggestionTypedText}</b>
                                        {suggestion
                                            .toLowerCase()
                                            .replace(this.state.suggestionTypedText, "")}
                                    </div>
                                ) : (
                                    <div dangerouslySetInnerHTML={this.getSuggestionHtml(suggestion)} />
                                )}
                        </div>
                    ))}
                </div>

                <footer className="chat-footer" >
                 

                    <div className="foot-footer">
                        Was I helpful ?
                        <span className="feedback" onClick={() => this.feedback("Yes")} >Yes</span><span>|</span><span className="feedback" onClick={() => this.feedback("No")}>No</span>

                        {
                            this.state.feedBack === "Yes" || this.state.feedBack === "No" ?
                                (
                                    <div className="dialog" id="myform">
                                        <div id="textfeedback">
                                            <span id="closeFeedback" onClick={() => this.feedback("Close")}>X</span>
                                            <p>{this.state.popupContent}</p>
                                            <input type="text" id="feedbacktxtbox" required name="textfeedback" placeholder="Pleasure to hear from u!"
                                                onChange={this.handleChange}
                                                value={this.state.value} />
                                            <button type="button" id="btnfeedback" onClick={() => this.feedback("Send")}>send</button>
                                        </div>
                                    </div>
                                ) : null
                        }

                    </div>
                </footer>
                
           
            
            </div>

        );
    }
    }

    }``

**Comment by scheyal** [comment]
@thomas023 , thank you for opening this issue.  

For product behavior, how-to, or general understanding questions, please use Stackoverflow. 
https://stackoverflow.com/search?q=bot+framework
