### ISSUE TITLE
Support locale at StartConversation

### ISSUE THREAD

**Issue by timenick** [microsoft/BotFramework-WebChat#3296]
##Issue
Original issue: microsoft/botframework-obi#75

This issue tracks a frequently requested feature to allow a user locale when starting new conversations. The user locale is needed so that bots can send a properly localized Greeting Message to users.

##Proposed change
 WebChat - update the protocol to support locale and userId aligned with DirectLineJS

Tracking DirectLineJS issue: https://github.com/microsoft/BotFramework-DirectLineJS/issues/292

**Comment by compulim** [comment]
Thanks @timenick. We will implement the `startConversation.locale` options.

## Work items

### Adding `locale` option

Update `createDirectLine` to accept and pass `locale` option.

```
  const directLine = window.WebChat.createDirectLine({
+   locale: 'en-US',
    token
  });
```
