### ISSUE TITLE
Add timestamps back in

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#33]
I removed timestamps to make it simpler to move to Activities + Redux. Now that they're there, they can come back.

But it's worth talking about how we want them to work first.

**Comment by billba** [comment]
a very simple version is back in. Awaiting your feedback and/or styles.

**Comment by eanders-MS** [comment]
Noticed an issue: When the text of a sent message is really short, the chat bubble resizes abruptly when the timestamp disappears.
