### ISSUE TITLE
in the Latest commit the webpacked folder is missing?

### ISSUE THREAD

**Issue by Lipa9963** [Microsoft/BotFramework-WebChat#330]

**Comment by billba** [comment]
`botchat.js` in the root now

**Comment by Lipa9963** [comment]
I still can not find it there ..
Am i missing something?

Thanks

**Comment by billba** [comment]
The repo no longer includes built files. You have three options:
1. Clone the repo and build it yourself. Only do this if you need to make code or styling changes.
2. `npm install botframework-webchat`. Do this if you want to include WebChat as part of a larger React application.
3. Grab the binaries from the CDN, e.g. `<script src="https://unpkg.com/botframework-webchat/botchat.js[@version]"/>`
