### ISSUE TITLE
Upload button distorted in the Latest commit

### ISSUE THREAD

**Issue by Lipa9963** [Microsoft/BotFramework-WebChat#331]
![capture](https://cloud.githubusercontent.com/assets/23163741/22620457/4cd180be-eb15-11e6-94cb-b1c0bf9fb549.PNG)

**Comment by billba** [comment]
in which browser?

**Comment by Lipa9963** [comment]
Chrome

On Feb 4, 2017 11:07 PM, "Bill Barnes" <notifications@github.com> wrote:

in which browser?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotFramework-WebChat/issues/331#issuecomment-277477997>,
or mute the thread

**Comment by danmarshall** [comment]
We've had a style sheet update, please clear your browser cache

**Comment by danmarshall** [comment]
Hi @Lipa9963 - I'm going to close this issue for now, as I am confident that clearing your browser cache will fix it. Please feel free to re-open this issue if that does not resolve it, thanks.
