### ISSUE TITLE
ReceiptCard is not displaying the ReceiptItem -> quantity field.

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-WebChat#3310]
## Version
4.9.0

## Describe the bug
When using the ReceiptCard , Emulator is not displaying the ReceiptItem -> quantity field. 

## To Reproduce
using the ReceiptCard with ReceiptItem with quantity 

## Expected behavior
It should display the ReceiptItem with quantity 

## Screenshots
![image](https://user-images.githubusercontent.com/16264167/87663922-1928c680-c782-11ea-9c11-8a4e7f8ab924.png)

[bug]

**Comment by compulim** [comment]
@corinagum Could you take a look at this?

@rvinothrajendran Could you try out Adaptive Cards? Because it could make your card more expressive.

**Comment by rvinothrajendran** [comment]
@compulim Yes you are correct,  This issue I found in while preparing the bot tutorial  ☹

**Comment by corinagum** [comment]
Thanks for reporting this. This is an error in Web Chat where not all ReceiptItem properties are utilized. Looks like both `quantity` and `text` are missing. 

![image](https://user-images.githubusercontent.com/14900841/87835084-fe695700-c840-11ea-896f-d736a3560824.png)

**Comment by EricDahlvang** [comment]
@corinagum  would you please provide a status update for this issue.

**Comment by corinagum** [comment]
This is on our TBD list for R11. Fairly confident it will be scoped to that milestone.

**Comment by compulim** [comment]
We will triage it in R11.
