### ISSUE TITLE
DirectLine connection issue in 4.9.2.

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#3314]
Hi Team,

This issue occurs in 4.9.2. I had to go back to 4.9.1 to solve it:

I still have one bot in production using the bundle on https://cdn.botframework.com/botframework-webchat/latest/webchat.js"
This morning the bot stopped responding at
`window.WebChat.renderWebChat({
        directLine: window.WebChat.createDirectLine({ token }),
      }, document.getElementById('webchat')); `
No errormessages in the console. (except the Refused to get unsafe header "x-ms-bot-id")
 I checked the bot itself (Test in Webchat in Azure Portal) and there is was responsive.

**Additional info**
According to the network tool of the devtools, this call remains pending (errorcode: 101, type: websocket

GET wss://directline.botframework.com/v3/directline/conversations/<conversationID>/stream?watermark=-&t=<token> HTTP/1.1
Host: directline.botframework.com
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Upgrade: websocket
Origin: <myDomain>
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7
Sec-WebSocket-Key: <key>
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

**Comment by compulim** [comment]
The Web Socket (`wss`) call is expected to be pending. This is because the Web Socket connection is open-and-receiving. If the Web Socket call is finished, that means the connection is closed.

I am not seeing any issues on my side when running Web Chat 4.9.2 with DL over Web Socket.

When running normally:

- wss://.../stream should be kept pending
   - When a new message is received from bot, you should see a packet from this Web Socket connection
   - When a message is sent to the bot, you should see a packet too
- When you send a message, you should see `POST` call to /.../activities

When you are saying the bot is not responding, what is your observation?

I am including a screen recording of what a normal connection via Direct Line over Web Socket is. This is tested on 4.9.2.

![recording (32)](https://user-images.githubusercontent.com/1622400/87821859-614cf500-c825-11ea-9b06-f3acb578f5b7.gif)

**Comment by HesselWellema** [comment]
Hi, I did a check just now on https://cdn.botframework.com/botframework-webchat/latest/webchat.js and the directline connection still doesn't work.
When I use https://cdn.botframework.com/botframework-webchat/4.9.1/webchat.js everything is fine.

So I'm good for now. Maybe something is wrong with CDN? I am on CET and first noticed this issue around 0900 CET. Update of the CDN or something?

**Comment by compulim** [comment]
Web Chat 4.9.2 was released around this time.

When you say the bot does not respond, do you see any JavaScript errors?

If your bot is public-facing, can you share the URL so we can look at?

**Comment by HesselWellema** [comment]
Hi,
No errors next to the webchat.js:2 Refused to get unsafe header "x-ms-bot-id" and a warning about a cookie associated with a cross-site resource. 
But I do know what caused it:

I use a store to have the chat start at the top of the box. That breaks the rendering of the webchat in 4.9.2 I guess. I will need to find a solution for that. Until that time I will stay on 4.9.1 (which already is great):

      if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
        let element = document.getElementsByClassName('css-mfy564')[1];
        element.style.flexGrow = "0";
        element.style.marginTop = "30px"`

**Comment by munozemilio** [comment]
@compulim any updates on this?

**Comment by compulim** [comment]
@HesselWellema the `css-mfy564` is a hash based on the CSS content, thus, it is very unstable.

If you would want to change the CSS, you can refer to this sample, https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization/b.idiosyncratic-manual-styles. This is more stable, but not perfect yet.

We change DOM from time to time, for example, to fix accessibility issues. Relying on CSS class name is risky (until #2988 and #2389 are done).

And there are upcoming huge DOM/CSS change in R10/4.10.0 too.

**Comment by HesselWellema** [comment]
Tnx. I knew this could and would happen when I decided to change the css this way.
Since the change I need to implement can only be implemented this way, I will  stay at 4.9.1 for now.
