### ISSUE TITLE
React Native: Investigate visual regression test on mobile devices

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3317]
## Progress

- Trying out BrowserStack App Automate
   - Send [Expo Client](https://expo.io/tools) to BrowserStack as base app
      - Official APK is working
      - No official IPA, only official `.tgz` and it is only good for iOS Simulator
- Build our own IPA
- BrowserStack to start an app through intent activation or launch by URL
   - Appium has some capabilities used to start the app through activation, but looks like it doesn't work
   - Appium also has some commands to start the app through activation, also doesn't seems to work
   - Also, we are testing the command for APK only, didn't test IPA yet
   - We need this to launch the app by `exp://127.0.0.1:12345`
- Trying out using App Center to build IPA without Xcode
   - App Center is currently have some issues on build (timeout)
- Appium may not capable of running an app through URL
   - https://github.com/appium/appium-ios-driver/blob/master/lib/commands/general.js#L231
- Appium can run Android apps through intent activation
   - https://github.com/appium/appium-adb/pull/475/files
- For Android, some would suggest using Appium/JSONWP via `await client.url('exp://<ip>:<port>')`

### Minimum goal

1. A new React Native app
   - Showing "Hello, World!" and a button called "Translate"
   - When the button is clicked, it turn "Hello, World!" into "Aloha!"
1. Two hosted real devices
   - Android 10
   - iPhone with latest version of iOS
1. Test code using [Jest](https://jestjs.io/)
   1. Take a screenshot after the app started (in PNG format)
   1. Click the button
   1. Take a screenshot again

Run the test code using command-line, `jest`.

### Better

- React Native app deployed to the hosted service can be updated rather frequently and quickly (< 1 minute for the first test to run)
- Compare which services are better (speed to run, parallelism, etc)

## References

- https://reactnative.dev/docs/testing-overview#end-to-end-tests
- https://github.com/americanexpress/jest-image-snapshot

**Comment by corinagum** [comment]
Closing as resolved
