### ISSUE TITLE
Message problems in Safari

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotFramework-WebChat#333]
older messages are getting repeated and sometimes the answers provided to questions are not getting recognized.
The iframe widget on safari seems to have problems. Will this browser be supported?

(The preview Webchat channel provided by the botframework.)

**Comment by billba** [comment]
I do all my development and most of my testing on Safari. I've never seen these problems. So:

1. Can you provide a reproducible case?
2. Are you only seeing these problems on Safari and not other browsers?

**Comment by danmarshall** [comment]
Hi @ubreddy, if you see a repeated message, can you open your browser's dev tools and try to find the html elements of the repeated messages. Each has a "data-activity-id" attribute. If the values match, then maybe there is a bug in our rendering. If they don't match, maybe it could be a bug in DirectLine or your bot.

**Comment by ubreddy** [comment]
looks like this got fixed now. I dont see these errors coming up in Safari. Wish I had taken a snapshot earlier. If it repeats again will do. Uday 

    On Monday, 6 February 2017 11:57 PM, Dan Marshall <notifications@github.com> wrote:
 

 Hi @ubreddy, if you see a repeated message, can you open your browser's dev tools and try to find the html elements of the repeated messages. Each has a "data-activity-id" attribute. If the values match, then maybe there is a bug in our rendering. If they don't match, maybe it could be a bug in DirectLine or your bot.—

**Comment by billba** [comment]
The WebChat channel lags behind this repo by about a week. 

We haven't made any fixes that would have changed basic message behavior. I'd still like to know which OS and version of Safari you are using.

**Comment by ubreddy** [comment]
tried this from Apple iOS 10.0.2 on ipad Uday 

    On Tuesday, 7 February 2017 8:16 PM, Bill Barnes <notifications@github.com> wrote:
 

 The WebChat channel lags behind this repo by about a week.We haven't made any fixes that would have changed basic message behavior. I'd still like to know which OS and version of Safari you are using.—

**Comment by billba** [comment]
Weird. I frequently test on my iPad and I haven't seen these problems you describe.  Could be a problem with your bot, or some edge case that doesn't show up very often. I will close for now, but please let us know if you see it again and can get us some data to work with.
