### ISSUE TITLE
Support tap action on Hero Card

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#335]
The HeroCard itself can be assigned a tap action. WebChat does not currently listen for a tap at the card level.

**Comment by sgomaram** [comment]
@eanders-MS Do you have any idea.. when it can be fixed and made available for us ?

**Comment by billba** [comment]
Also Thumbnail, Receipt, and individual Receipt items.

**Comment by billba** [comment]
Implemented in #336

**Comment by alextsui-act** [comment]
Tap to open URL in webchat does not work in both Hero or ThumbnailCard.   It works in Skype.  But I need for webchat

**Comment by billba** [comment]
Works in current build but that build is not yet running in the WebChat channel.

**Comment by alextsui-act** [comment]
Thanks, Bill.  Do you know when it will be live for WebChat?
