### ISSUE TITLE
Adaptive Cards not rendering Uncaught 'length' of undefined

### ISSUE THREAD

**Issue by karrimrabibiomni** [microsoft/BotFramework-WebChat#3353]
## Screenshots
![image](https://user-images.githubusercontent.com/65707695/88072511-055bd680-cb6d-11ea-9e65-919d1dee68c0.png)

here is the adaptive card the bot has sent:

```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"body": [
		{
			"type": "Container",
			"items": [
				{
					"type": "TextBlock",
					"text": "Web Chat Does not like cards",
					"weight": "bolder",
					"size": "medium"
				}
			]
		}
	],
	"actions": []
}
```

## Version
4.9.2 via npm

```html
<iframe src="https://localhost:44374/connect/checksession" style="visibility: hidden; position: absolute; display: none; width: 0px; height: 0px;"></iframe>

<meta name="botframework-directlinespeech:version" content="4.9.2">
<meta name="botframework-webchat:bundle:variant" content="full">
<meta name="botframework-webchat:bundle:version" content="4.9.2">
<meta name="botframework-webchat:core:version" content="4.9.2">
<meta name="botframework-webchat:ui:version" content="4.9.2">"
```

## Describe the bug

When the card render attempts to render any adaptive card we get an uncaught exception due to  _adaptiveCard$validat.failures being undefined in the AdaptiveCardRenderer.js. displaying just text from the bot works fine and same bot using 4.9.1 works fine.

```js
 var _adaptiveCard$validat = adaptiveCard.validateProperties(),
        failures = _adaptiveCard$validat.failures;
```

## Steps to reproduce

1. Open Webchat iframe page 
2. Get your bot to send the chat an adaptive card as a welcome
3. Page blows up

## Expected behavior

Render the Adaptive card without throwing exceptions

## Additional context

(Edited by @compulim for code formatting)

[Bug]

**Comment by compulim** [comment]
Thanks @karrimrabibiomni. Based from your investigations, I think you should be correct, but unfortunately, the card didn't throw an error on our side.

Do you have a card JSON that will repro the problem?

Attached below show the card being sent from the bot but the UI didn't blow up (yet).

![image](https://user-images.githubusercontent.com/1622400/88570945-c48f1200-cff1-11ea-9918-edea5482232b.png)

**Comment by karrimrabibiomni** [comment]
have retested a week on and web chat is now working as expected.
