### ISSUE TITLE
Blocker symbol on mic | unable to give voice input related to #3209

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-WebChat#3357]
## Screenshots
![image](https://user-images.githubusercontent.com/11289456/88099193-74125180-cbb8-11ea-9e0e-4f7f068a5c95.png)

## Version

4.9.1 cdn . using it in an angular project

## Describe the bug

if a message has inputHint as expectingInput and we click in the message input box before the message is voiced out. We get a blocker symbol and cannot give voice input any further.

## Steps to reproduce

1. input with voice a message which will trigger a response with inputHint as expectingInput
2.Wait for voice to start
3.click on the input message box before the full message is voiced out

## Expected behavior
The mic is not blocked out

## Additional context
using custom speech and custom voice but i do not think that this information is relevant to this bug.

[Bug]

**Comment by munozemilio** [comment]
@compulim could you please take a look at this one?

**Comment by compulim** [comment]
@prashanthsridhar Are you using DLSpeech or regular Direct Line?

For a quick favor, can you try your bot outside of Angular?

**Comment by prashanthsridhar** [comment]
Hi @compulim ,we are using regular directLine. i did try it in a stand alone angular app,the issue exists. If you need me to test outside angular,it will take some time as i am currently out of office for a few days.

**Comment by compulim** [comment]
Yes, please.

I tried to search our codebase for the keyword `cursor`, which is used in CSS to change the mouse cursor). But we couldn't find any references. 🤔

**Comment by compulim** [comment]
@prashanthsridhar we are eagerly waiting for your investigation.

**Comment by prashanthsridhar** [comment]
Hi @compulim sorry for the delay,the issue exists outside angular as well. The blocker symbol does not turn up but the mic is still deactivated.
Deactivated after following  the above mentioned steps:
![WhatsApp Image 2020-08-11 at 00 38 13](https://user-images.githubusercontent.com/11289456/89820751-1f387a00-db6b-11ea-8a1e-ba9a7de8d37f.jpeg)

Normal mic state:
![WhatsApp Image 2020-08-11 at 00 38 59](https://user-images.githubusercontent.com/11289456/89820764-23649780-db6b-11ea-9078-ad2f89eeca62.jpeg)

**Comment by prashanthsridhar** [comment]
Hi @compulim , i hope my findings were useful,any luck on reproducing this?

**Comment by prashanthsridhar** [comment]
@munozemilio i see that the status is still waiting for customer. Please do the needful.

**Comment by compulim** [comment]
Thanks for the ping.

Will continue my investigation later this week. We are working on a security fix for 4.10.1 currently. 💪🏻

**Comment by compulim** [comment]
I am working on this today.

**Comment by amal-khalaf** [comment]
I tried reproing the issue on webchat 4.10 and 4.11 it is no longer reproing

@prashanthsridhar could you try upgrading and see if this will fix the mic enablement issue.?

**Comment by amal-khalaf** [comment]
Closing as issue is not repro-ing on latest webchat  4.11
