### ISSUE TITLE
AdaptiveCards: Input.Text strips linebreaks

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-WebChat#3358]
## Version
4.9.0

## Describe the bug
Adaptive Cards with `Input.Text` controls strip line-breaks when `multiline = true`.  I've verified that both the designer at adaptivecards.io and Teams preserve the line-breaks.

## To Reproduce
Create a simple adaptive card with a multiline input control and use emulator to send your bot the text. The line-breaks are missing.

[bug]

**Comment by compulim** [comment]
@Stevenic do you have a sample card JSON that fail?

I assembled a card by myself with `isMultiline` set to `true` and it's working in 4.9.2.

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "This example uses [Adaptive Card Templating](https://docs.microsoft.com/en-us/adaptive-cards/templating/)",
                    "size": "Medium",
                    "wrap": true
                }
            ],
            "style": "good",
            "bleed": true
        },
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text",
            "isMultiline": true,
            "id": "value",
            "value": "First line.\nSecond line.\n\nThird line after an empty line."
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```

![image](https://user-images.githubusercontent.com/1622400/88573539-c2c74d80-cff5-11ea-8917-a6987356200c.png)

**Comment by corinagum** [comment]
Closing this issue as no repro. If @Stevenic or another user is able to provide JSON that reproduces this issue please post that here and let's reopen.
