### ISSUE TITLE
Webchat Voice is not working in iPhone Emulator

### ISSUE THREAD

**Issue by collegewap** [microsoft/BotFramework-WebChat#3362]
Webchat sample: https://microsoft.github.io/BotFramework-WebChat/03.speech/b.cognitive-speech-services-js/

## Screenshots

![image](https://user-images.githubusercontent.com/9767383/88528070-c372da80-d01b-11ea-9f2b-ed7795f4c8b0.png)

## Version
4.9.2

## Describe the bug

Was trying to triage an issue in the bot where the bot does not speak. When I tried to replicate in an emulator, on the press of the Mic button, nothing happens. So I checked the behavior in the [sample bot](https://microsoft.github.io/BotFramework-WebChat/03.speech/b.cognitive-speech-services-js/) and could see the same behavior there as well. I get the error shown in the screenshot. Tried in XCODE emulator as well, got the same issue.
How am I supposed to debug the issue, if the voice option doesn't work in emulator? 

[Bug]

**Comment by mdrichardson** [comment]
@collegewap You'll need to test directly on an iPhone. Per the [iPhone Simulator docs](https://developer.apple.com/library/archive/documentation/IDEs/Conceptual/iOS_Simulator_Guide/TestingontheiOSSimulator/TestingontheiOSSimulator.html#//apple_ref/doc/uid/TP40012848-CH4-SW1):

> ### Hardware Differences
> Though most of the functionality of devices can be simulated in Simulator, some hardware features must be tested directly on a device. The hardware features that are not simulated as of iOS 8.2 are:

> * Motion support (accelerometer and gyroscope) are unsupported.
> * **Audio and video input (camera and microphone) are unsupported.**
