### ISSUE TITLE
We need an option to to “unsanitized” html if we want to skip sanitizeHTML in our requirement.

### ISSUE THREAD

**Issue by sanjayror** [microsoft/BotFramework-WebChat#3363]
## Feature Request

We are having an issue in File Upload Control in bot framework,  We had custom modified “webchat.js”  Including commented line of code to fix the issue with custom UI file upload control but due to a needed upgrade we had to upgrade our library to a new version.  but after that we getting html render instead of file control.

but our earlier webchat.js works fine with this change
// return sanitizeHTML(html, SANITIZE_HTML_OPTIONS); 

We need an option to to “unsanitized” html if we want to skip sanitizeHTML in our requirement.

**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/15170372/88539433-dc38bb80-d02e-11ea-8c3d-4f1301ab8c3b.png)

![image](https://user-images.githubusercontent.com/15170372/88539479-f4a8d600-d02e-11ea-8b05-7e3f3c67780a.png)

We found solution somewhere :
 The change is to remove the code that “sanitizes” the returned response for allowed HTML.  This is in file BotFramework-WebChat\packages\bundle\src\renderMarkdown.js
 The code is about lines 84-86. We comment out the line in green and return the “unsanitized” html. 
const html = customMarkdownIt.render(markdown);
return html;
// return sanitizeHTML(html, SANITIZE_HTML_OPTIONS); 

Please help us to solve this asap.

**Comment by compulim** [comment]
If you would like to send unsanitized HTML, please use a custom Markdown engine.

You can follow this sample to bring your own Markdown engine, https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/h.minimal-markdown.
