### ISSUE TITLE
Append onChange on TextBox

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/BotFramework-WebChat#3364]
## Feature Request

**Describe the suggestion or request in detail**
Our project would like to resize the textarea on TextBox when the user type so much they get a scrollbar.
For this it would be nice if the onChange would use a custom event handler after the one it has defined.
In this event handler we'd be able to set the height of the textarea based on its scroll height.

**Comment by compulim** [comment]
I think you can use the `useSendBoxValue` hook to subscribe to the change.

But on the other side, you can set `sendBoxMaxValue` to a higher value to allow the text box to grow.

![image](https://user-images.githubusercontent.com/1622400/88574731-9f050700-cff7-11ea-9adb-5384da06530c.png)

![image](https://user-images.githubusercontent.com/1622400/88574676-8694ec80-cff7-11ea-98af-383cbcd0f4c0.png)

**Comment by felixvanleeuwen** [comment]
That was easy!
Thanks for the help stranger 👍
