### ISSUE TITLE
Add style option to center textarea

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/BotFramework-WebChat#3368]
## Feature Request
When using the following style options:
```
sendBoxTextWrap: true,
sendBoxHeight: 55,
```
you get a textarea instead of an input for user input.
This textarea alligns with the top.
There's also a div behind it, probably for accessibility, with the same dimensions.

Current:
![image](https://user-images.githubusercontent.com/64589372/88889974-36a96600-d241-11ea-95fd-2b868be14f7e.png)
Desired:
![image](https://user-images.githubusercontent.com/64589372/88890010-44f78200-d241-11ea-9e88-c3d59be31696.png)

**Comment by compulim** [comment]
The `<div>` is a doppelganger and use for auto-resizing the `<textarea>`.

Are there any specific options you want to customize? We will rework the send box in #2211.

**Comment by felixvanleeuwen** [comment]
I want the textarea to be in the vertical center of the sendbox.
This is how we've implemented our textarea in V3:
![image](https://user-images.githubusercontent.com/64589372/88900752-22b93080-d250-11ea-947e-a86dd368c3b5.png)
In V4 the textarea doesn't scale out from the center:
![image](https://user-images.githubusercontent.com/64589372/88900919-6875f900-d250-11ea-9dd5-4b2154bba06a.png)

**Comment by felixvanleeuwen** [comment]
Just to get a field ```sendBoxCenterInput: true``` in styleOptions.
The default behavior should be to have it render as it does currently.
When set to true the textarea becomes centered vertically in the sendBox area.

**Comment by compulim** [comment]
I think we should center it by default. 😉

**Comment by felixvanleeuwen** [comment]
Awesome!

**Comment by compulim** [comment]
Some preliminary study on the layout here. You can study the code to understand how the doppelganger work.

https://compulim.github.io/playpen-textarea-doppelganger/

Still need to clean up the CSS a bit. Feel free to file PR over there for suggestions.

Will eventually move the JS/CSS there back to this repository.

**Comment by compulim** [comment]
I cleaned up the CSS over there. Need help from someone who can help copying the styles here.

**Comment by peterinnesmsft** [comment]
Added to backlog - will look to prioritize for an upcoming release.

**Comment by felixvanleeuwen** [comment]
Writing a whole bunch of 'k's in our current chat:
![image](https://user-images.githubusercontent.com/64589372/90492426-77f6ac80-e141-11ea-8d19-4c8ce83501da.png)
In our V4 implementation:
![image](https://user-images.githubusercontent.com/64589372/90492523-92c92100-e141-11ea-96d3-a89925ad9730.png)
In the playpen:
![image](https://user-images.githubusercontent.com/64589372/90492909-fe12f300-e141-11ea-9a48-753b666d86ef.png)

Setting "word-break", "overflow-wrap" on the textarea through chrome dev tools yielded no positive results.

**Comment by compulim** [comment]
The icon of send box button is not centered vertically. It is filed as #3672.
