### ISSUE TITLE
How can we generate webchat.js by yourself

### ISSUE THREAD

**Issue by sanjayror** [microsoft/BotFramework-WebChat#3369]
🚨 The issue tracker is not for implementation questions 🚨

[Question]

I downloaded https://github.com/microsoft/BotFramework-WebChat  on my local PC.
I done some modification in code.

How to run this download project ?
How can we generate webchat.js by yourself ?

**Comment by compulim** [comment]
Given you have install all dependencies, etc.

```js
set NODE_ENV=production
npm run build
```

Then you can get the bundle from `/packages/bundle/dist/` folder. 😉

If you are making small style changes, I would strongly recommend looking at [our samples](https://microsoft.github.io/BotFramework-WebChat) to see how things work.

**Comment by sanjayror** [comment]
Hii,
When I run [npm run build] then I'm getting this error

![image](https://user-images.githubusercontent.com/15170372/89054959-3e6b2680-d377-11ea-8c69-44138caa529e.png)

Full logs attach here..
[2020-07-31T15_53_31_848Z-debug.log](https://github.com/microsoft/BotFramework-WebChat/files/5007943/2020-07-31T15_53_31_848Z-debug.log)
