### ISSUE TITLE
[Direct Line Speech] Investigate supporting sovereign cloud

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3377]
## Feature Request

In Direct Line Speech [`packages/directlinespeech/src/createAdapters.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/directlinespeech/src/createAdapters.js#L37), I think in addition of `region`, we need to support hostname.

Code excerpt of today:

```js
const { authorizationToken, directLineToken, region, subscriptionKey } = await resolveFunctionOrReturnValue(
  fetchCredentials
);
```

[Enhancement]

**Comment by corinagum** [comment]
Assigning to @trrwilson per @nisheetjain

**Comment by corinagum** [comment]
Closing as dupe of #3666 Please take conversation over there.
