### ISSUE TITLE
Numbering reset in markup. No way to enforce my own numbering.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-WebChat#3382]
Declarative markup in composer has  **- 3. …**, it renders in the bot as **1. ...**. If I add \ in front of 3. It shows up as **\3.**  I want it to show as 3. …

Workaround - drop the '.'
Desired - what I want :)

**Comment by compulim** [comment]
This is because the message is being rendered through Markdown. You can set `textFormat` to `plain` to disable Markdown rendering.
