### ISSUE TITLE
 sso-for-enterprise project in .NET SDK

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-WebChat#3385]
hi,
I have gone through below documentation for sso login project and i found that it is implemented using NodeJS sdk

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/b.sso-for-enterprise

Do we have similar sample project for .NET SDK ?

Thanks.....

🚨 The issue tracker is not for implementation questions 🚨

[Question]

**Comment by daveta** [comment]
Hi @madbeher : Web Chat is a front end written in node.js.  We're not sure what you're requesting here.
