### ISSUE TITLE
sso-for-enterprise demo bot not giving response for any question asked

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-WebChat#3386]
Hi,

I have gone through below documentation for sso sample project. In the documentation there is is mock out link provided to
try the demo bot which is already hosted as mentioned in the documentation but after trying that demo link I found that login
functionality is working but bot is not responding for any question asked. I tried asking same question as mentioned in the documentation. Am I missing something which is required to run this demo bot link.

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/b.sso-for-enterprise

https://webchat-samples-ssoenterprise.azurewebsites.net/

<img width="520" alt="demobot things to tryout" src="https://user-images.githubusercontent.com/36945600/89534681-f6cf1980-d812-11ea-9490-1bbeb30730ba.PNG">
<img width="913" alt="DemoBotError" src="https://user-images.githubusercontent.com/36945600/89534777-18300580-d813-11ea-93e6-c5cfef98d5ee.PNG">

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by anusharavindrar** [comment]
@madbeher, I am able to repro the issue with the MockBot on my end. Have you tried running the sample?
I will investigate the issue further and try running the sample as well & update the thread accordingly.

**Comment by madbeher** [comment]
Hi ,

I tried using   sample project in my local machine by following github documentation  but facing the same error.

**Comment by madbeher** [comment]
Hi,

The sample project I tried in my local machine login button working but bot is not working.

thanks...

**Comment by madbeher** [comment]
Can anyone help me with above issue.

Thanks...

**Comment by anusharavindrar** [comment]
@madbeher, thanks for the above information. I am currently working on this and will update the thread with my findings.

**Comment by ismendes** [comment]
@anusharavindrar I could unblock them. This is not actually an error. It’s just that the Bearer token in Azure portal is called Secret key. You can close this, I believe. Thanks for your help.
