### ISSUE TITLE
Tap action on hero card not working in web chat

### ISSUE THREAD

**Issue by AnithaJothi** [Microsoft/BotFramework-WebChat#339]
Hi, I am trying to display 4 Hero Cards (Rich cards) in a plain web chat channel. I am using the classic version of the default Web Chat control with the "Preview" option enabled. I wish to have only images to my cards and clicking on the images should return me specific values.  I have added tap action to the Hero cards as given below.
CardAction plButton = new CardAction()
                            {
                                Value = dSubOption.text,
                                Type = "imBack",
                                //Type = "postBack",
                                Title = dSubOption.text
                            };
HeroCard plCard = new HeroCard()
                            {
                                Title = "",
                                Subtitle = "",
                                Images = cardImages1,
                                Tap = plButton
                            };

However I see that the Tap action on the hero card does not respond to tap. Any help is much appreciated!

Note - I am using the C# SDK, Microsoft bot builder version - 3.5.2

**Comment by billba** [comment]
Works in the current build, will be deployed to channel soon, or use the current build directly via CDN or building yourself.
