### ISSUE TITLE
URL from QnA service has _blank in it which causes link to open in new tab. Directline bot

### ISSUE THREAD

**Issue by InfoZone** [microsoft/BotFramework-WebChat#3391]
🚨 The issue tracker is not for implementation questions 🚨

[Question]
We have a direcline bot that when a question is asked, we call QnA service that will return a few links. now the links  when clicked, opens in a new tab. can this be prevented?

I think this is injected by the webchat.js file
https://cdn.botframework.com/botframework-webchat/latest/webchat.js

![image](https://user-images.githubusercontent.com/17723426/89648963-520b1580-d8c0-11ea-80cb-56d4a2b3aa47.png)

**Comment by compulim** [comment]
#2892 is the feature work to selectively choose which link to open in a new window or not. But until that feature is done, all links are designed to open in a new window.

I will close this as dupe, please track the progress of #2892.
