### ISSUE TITLE
Bump Adaptive Cards to 2.*

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3392]
## Feature Request

https://www.npmjs.com/package/adaptivecards

There are a few breaking changes we will need to modify code on our side to support them.

Adaptive Cards renderer 2.1 is using schema of **1.3**, not **2.x**.

### Ping service team

Service team may need to update their service code or dependencies to make sure their parser/stringifier support AC schema 1.3.

Today, when a bot send AC JSON to Direct Line channel, the channel parse, then restringify it. Then, they send it to Web Chat.

When we bump to AC 2.*, if the service is not ready for AC with schema 1.3, it may not be very meaningful (other than accessibility fixes).

[Enhancement]

**Comment by corinagum** [comment]
@Jeffders @p-nagpal FYI.

**Comment by corinagum** [comment]
This bump will fix the bug brought up in #3111 (reference: https://github.com/microsoft/AdaptiveCards/issues/3829)
