### ISSUE TITLE
Speech not working in web chat for GOV cloud due to wrong endpoint

### ISSUE THREAD

**Issue by msbotdev19** [microsoft/BotFramework-WebChat#3398]
## Screenshots
Below is the screenshot of Firefox web console
![image](https://user-images.githubusercontent.com/60222720/89809994-01aee480-db5a-11ea-9118-5ea75e1dd236.png)

## Version
What version of Web Chat are you using? **4.9.2** [This one](https://cdn.botframework.com/botframework-webchat/latest/webchat.js)
Are you using the CDN? **Yes**

## Describe the bug
We are developing a bot hosted on Azure gov cloud and the sample web chat is working fine except the speech. When we click on the mic icon in web chat, it throws an error "Firefox can’t establish a connection to the server at wss://usgovvirginia.stt.speech.microsoft.com" which I believe is wrong/incorrect endpoint for azure gov speech resource as per [this article](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/sovereign-clouds).

## Steps to reproduce
1. Configure the sample js Web Chat with appropriate secret and speech key.
2. Run the Web Chat on Firefox.
3. Open Firefox' web console (dev tools).
4. Click on mic icon to see the error in web console.

## Expected behavior
Web Chat must take speech input and bot should respond accordingly.

[Bug]

**Comment by compulim** [comment]
Looks like you are using `region` instead of `speechRecognitionHostname` or `speechSynthesisHostname` for sovereign cloud.

Please follow the documentation here for specifying endpoint for sovereign cloud, https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/SPEECH.md#using-sovereign-cloud.

**Comment by msbotdev19** [comment]
Thanks! that helped
