### ISSUE TITLE
Web chat not displaying Typing indicator

### ISSUE THREAD

**Issue by AnithaJothi** [Microsoft/BotFramework-WebChat#340]
Hi, I am trying to display the "Typing" indicator in my webchat.
Below is the code snippet

Activity isTypingReply = activity.CreateReply();
isTypingReply.Type = ActivityTypes.Typing;
isTypingReply.Text = null;
await connector.Conversations.ReplyToActivityAsync(isTypingReply);

This displays a "TYPING" indicator in the emulator (see screenshot below)
![image](https://cloud.githubusercontent.com/assets/25479670/22974310/b6bd0db4-f3a7-11e6-868f-578c5ba94a37.png)

However, when i publish the same, the typing indicator does not appear (see screenshot below)
![image](https://cloud.githubusercontent.com/assets/25479670/22974358/ead4452c-f3a7-11e6-9f26-1bd165e2aa0d.png)

Any help is much appreciated!!
Note - Am using the classic web chat control with Preview option enabled. Am building using the Bot Builder C# SDK - bot builder version - 3.5.2

**Comment by billba** [comment]
the Typing indicator only shows when using WebSockets, and the channel does not yet enable WebSockets. you'd need to use the current build directly via CDN or building yourself.

**Comment by JobaDiniz** [comment]
Using directline + javascript client, connecting with `websockets=false` it does not show typing indicator, but why not?

**Comment by billba** [comment]
That is a reasonable question. @dandriscoll?

**Comment by tinuCoder** [comment]
I am facing the same issue and tried searching a lot of soln on the same but unfortunately nothing helped.

I have a built a custom chat window using cshtml and javascript. I am sending Typing activity from my bot solution. This piece of code is working with "webchat" and "emulator" but it is not working with my designed page.

when i am setting webSocket = true my directline calls are failing. PFB

        BotChat.App({
            botConnection: botapp.botConnection,
            user: botapp.user,
            bot: bot,
            resize: 'detect',
            directLine: {
                secret: '.......................gc.cwA.gzs.DgekX5............................',
            webSocket:true
        }
        }, document.getElementById("divbot"));

Please help me out on the issue.

Thanks in advance. Appreciate you for taking out time this.

**Comment by tinuCoder** [comment]
When i enable the socket it thows following error and nothing works.


![image](https://user-images.githubusercontent.com/25457761/37251056-38b85740-2522-11e8-9f14-9a58ed3a310b.png)

**Comment by billba** [comment]
You need to pass either directLine or botConnection but not both.
