### ISSUE TITLE
Using Bot middleware concept - User text status is not updated

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-WebChat#3400]
## Screenshots

![image](https://user-images.githubusercontent.com/16264167/89850142-95f36880-dba7-11ea-8abb-2aacb0f5ed4d.png)

## Version

 Bot emulator 4.9

## Describe the bug

Rights side(image) working fine but not sure in which bot emulator version (last year December 2019) . the same code try to run bot emulator 4.9(Left side(image))  application its working fine & but the status showing as failed in the emulator.

## Steps to reproduce

I have tried the same code with Middleware in 4.7 emulator version ( here my sample code: https://github.com/rvinothrajendran/BotTutorialSample/tree/master/Python_tutorial/03-Middleware)

## Expected behavior
Status to be update

**Comment by jwiley84** [comment]
Assigning to myself until Dana's permissions are fixed

**Comment by dmvtech** [comment]
@rvinothrajendran In the emulator, Can you share the additional information? I'm guessing it is showing an error in the right pane of emulator.

Also, your bot is sending the username in your `on_members_added_activity`, but I don't see that in the screen shot. Is that happening at all?

If you remove the middleware and just have the bot echo, does it work without error?

**Comment by rvinothrajendran** [comment]
here the right side info.


![1](https://user-images.githubusercontent.com/16264167/90206853-583e4c00-de02-11ea-94b6-84ea137434e1.png)


If you remove the middleware and just have the bot echo, does it work without error? -> removed middleware and  on_members_added_activity function also -> Its showing an error

**Comment by dmvtech** [comment]
I played with this a bit, but I wasn't able to find how to remedy your code. 

What I did do, was take our Python [echo sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/02.echo-bot), and modify it to work.

Just import the middleware and set the adapter to use it (create middleware1.py of course):
```
from middleware1 import Middleware1

# Create adapter.
# See https://aka.ms/about-bot-adapter to learn more about how bots work.
SETTINGS = BotFrameworkAdapterSettings(CONFIG.APP_ID, CONFIG.APP_PASSWORD)
ADAPTER = BotFrameworkAdapter(SETTINGS)
ADAPTER.use(Middleware1())
```

I'll poke around a bit more to see if I can figure out the exact cause, but I would suggest seeing if you can go with the approach that we do in our sample.

**Comment by rvinothrajendran** [comment]
I have checked the both code only difference in the app.py file.
I used old way of coding and echo sample used a new way. old way of coding style was working fine in old emulator ( ref the Screenshots)

**Comment by dmvtech** [comment]
Thanks @rvinothrajendran Just so I'm clear; did you try the new way and have it work?

**Comment by rvinothrajendran** [comment]
@dmvtech yes

**Comment by dmvtech** [comment]
Ok, are you ok to go ahead with the new code/way? Is this resolved for you? I don't know what has changed, but likely there was a bunch of fixes/changes/etc that happened somewhere.

**Comment by rvinothrajendran** [comment]
yes  , better we can close this issue
