### ISSUE TITLE
protocol-direct-line-app-service-extension readme seems to be incomplete with broken links

### ISSUE THREAD

**Issue by SunilMiracle** [microsoft/BotFramework-WebChat#3401]
## Screenshots
![image](https://user-images.githubusercontent.com/35075619/89864634-434f8780-db7a-11ea-9564-b3f7fc475d86.png)

## Version
Web chat version:   CDN: "https://cdn.botframework.com/botframework-webchat/latest/webchat-minimal.js"

Git link: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/i.protocol-direct-line-app-service-extension

## Describe the bug
The Readme for **Sample - Getting Started with Direct Line App Service Extension protocol** has some broken links and seems to have incomplete information.

In the below instructions for the index.html file:
"The index.html page has the following main goals:
To import the Web Chat bundle CDN script
**Obtain a Direct Line ASE-specific token**
 i) The token should have an issuer and audience of https://directlineextension.botframework.com/
 ii) The token should be generated from the Direct Line ASE-specific API at https://yourbot/.bot/v3/directline/tokens/generate
Render using the Direct Line ASE chat adapter"

**Doubts / Issues** (I assume the documentation is missing information because the mock bot sample works fine. All doubts are in the form of questions below).

1) **Obtain a Direct Line ASE-specific token** has a link which is broken. 
**The link appears to be a link just below the bullets points.**

2) The token should be generated from "https://yourbot/.bot/v3/directline/tokens/generate"
As per the documentation, logic to generate the JSON web token with **iss** and **aud** fields both set to "https://directlineextension.botframework.com/" should be in our bot code. 

**Should the endpoint be "api/token/directlinease" or ".bot/v3/directline/tokens/generate"?**

**Are there any other fields which should be added to the JSON payload?**

**https://directlineextension.botframework.com/** appears to be broken as well unless its hosted in a private server or not meant to be reachable.

**If this is the case what should be the **secret key** for JSON web token?** 

Also, documentation says nothing about how the "ASE secret" is used in this token creation? 
**Shouldn't the secret be used in some way to create the token?**

The sample code works fine, but some information on the above would be helpful.

3) In "Render using the Direct Line ASE chat adapter"
the bot endpoint is https://webchat-mockbot2.azurewebsites.net/.bot/v3/directline. 
**What logic should be linked to this endpoint?**

It would be great if the **webchat-mockbot** bot code is also added to github so that one can refer for the code to create the necessary api services  or please provide some additional information for generating the token from ASE secret.

**Comment by jwiley84** [comment]
Thanks for bringing this to our attention! I'll fix the links tonight, and give the instructions a review for readability!
