### ISSUE TITLE
Need help for SSO via OAuth sample in C#

### ISSUE THREAD

**Issue by sathishkumar2292** [microsoft/BotFramework-WebChat#3403]
I am belongs to C# background, But I sae the SSO OAuth login example is available on NodeJS, So can anybody please provide the example in C# 
It would be helpful for me.

### The [Sample tag](https://github.com/microsoft/botframework-Webchat/issues?q=is%3Aissue+is%3Aopen+label%3ASample) also lists examples and implementations that have already been requested.

**Is your feature request related to a problem? Please describe.**

**Describe the suggestion or request in detail**

**Describe alternatives you have considered**

**Additional context**

[Enhancement]

**Comment by jwiley84** [comment]
The C# version of SSO is handled through the parent bot/skill bot pattnern: 

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml

The sample showing this is here: 
https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/sso-with-skills
