### ISSUE TITLE
Unable to view PDF File inline for Bot Framework

### ISSUE THREAD

**Issue by 007-fr** [microsoft/BotFramework-WebChat#3404]
Hello Bot Framework support, 

I am trying to get a pdf to display inline for the Direct Line Channel of a Bot. I used the following code below, but only received a link to the file.  
![image](https://user-images.githubusercontent.com/66075770/89337173-8be1df00-d668-11ea-97ef-7ecb6804de0b.png)

Screenshot is from Bot Framework Emulator.
![image](https://user-images.githubusercontent.com/66075770/89338178-2db5fb80-d66a-11ea-8733-58c873821a58.png)

**Comment by compulim** [comment]
FYI, out of my experience, [`pdf.js`](https://mozilla.github.io/pdf.js/) can be used to generate PDF previews inside a browser. But it is quite resource intensive, requires modern browsers (Web Workers), and may not work perfectly with some fonts. It is the PDF reader engine behind Firefox.

You can try build one based from our [custom attachment renderer sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/e.card-components).

**Comment by compulim** [comment]
This is not an action item to Web Chat due to resources.
