### ISSUE TITLE
Directline speech - web socket ends with 200 response

### ISSUE THREAD

**Issue by collegewap** [microsoft/BotFramework-WebChat#3407]
## Screenshots

![image](https://user-images.githubusercontent.com/9767383/89983327-f90ef900-dc94-11ea-8e8e-217c7a29e1f1.png)

![image](https://user-images.githubusercontent.com/9767383/89983367-0b893280-dc95-11ea-8a2c-17073722dd46.png)

## Version

4.9.1

## Describe the bug

I have enabled directline speech in our bot by using the following example and I am getting the error "Error during WebSocket handshake: Unexpected response code: 200". I tried both the options of passing token and passing the subscription key and facing the same issue.

https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech

Note: [Cognitive speech ](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/b.cognitive-speech-services-js) approach works fine.

What could be the possible cause for this?

**Comment by Zerryth** [comment]
> I have enabled directline speech in our bot

@collegewap it seems like there might be something wrong with how you configured directline speech for your bot, as for a first test, I just simply did the following successfully:

## **Test with the Read-Made Mockbot Sample** 
(mockbot is the bot that the webchat sample talks to, whose code is separate from the `03.speech/a.direct-line-speech` sample)
- `git clone https://github.com/microsoft/BotFramework-WebChat.git`
- `npx serve`
- Navigate to `http://localhost:5000/`
- Click the microphone icon and verbally say "hello"
- Mockbot replies back with audio

![image](https://user-images.githubusercontent.com/35248895/90067991-c967ed00-dca4-11ea-8bdc-35c27825e31d.png)


No idea how you got the error that you did, as you didn't provide repro steps as to what you did exactly to set up your bot...
___

## **Setting up a bot configured to DirectLineSpeech**
This is just setting up an echo bot with DLS to enable speaking to your bot. It can be succinctly summarized as 
1. Set up a bot in Azure that has Direct Line Speech channel enabled
2. Run sample `03.speech/a.direct-line-speech` (`npx serve`) and speak to your DLS-enabled bot

<details>
    <summary>Get a fresh clone of Echo Bot and Test Locally</summary>

- `git clone https://github.com/microsoft/BotBuilder-Samples.git`
- Navigate to [02.echo-bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/02.echo-bot)
- Verify that you can chat with the bot locally (`npm i`, `npm start`, open [Bot Framework Emulator](https://github.com/Microsoft/BotFramework-Emulator/releases) and just type a message and receive an echo--it's currently just a plain Echo Bot with no speech enabled yet)
</details>

<details>
    <summary>Deploy your bot to Azure</summary>

- You can deploy your bot many ways, however one way is via [zip-deployment using AZ CLI](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=javascript)
- Once your bot is deployed to Azure, verify that it's working when you go to Bot Channels Registration > Test in Web Chat:
    
![image](https://user-images.githubusercontent.com/35248895/90069217-d8e83580-dca6-11ea-90e3-f3ce898059de.png)
- Note: I had just edited my bot before deploying to say "Speech Echo" so it's obvious that I deployed the right bot properly
- Additionally make sure once you have your Bot's AppId and Password, to have it in your `.env` file that's deployed to Azure (might need to redploy, depending on the order that you did things, which you can do so easily using `az webapp deployment source config-zip --resource-group "<resource-group-name>" --name "<name-of-web-app>" --src "<project-zip-path>"`)

</details>

<details>
    <summary>Provision Speech cognitive service</summary>

 - [Search the Marketplace for "Speech" and create a Speech cognitive service](https://ms.portal.azure.com/#blade/Microsoft_Azure_Marketplace/MarketplaceOffersBlade/selectedMenuItemId/CognitiveServices_MP/dontDiscardJourney/true/launchingContext/%7B%22source%22%3A%22Resources%20Microsoft.CognitiveServices%2Faccounts%22%7D)
- Save one of the keys, which you'll use in your WebChat later
</details>

<details>
    <summary>Enable DirectLine Speech Channel</summary>

- In Azure, go to your App Service > Configuration under "Settings" on the left-hand side > For "Web sockets" select "on" > Save:
     - ![image](https://user-images.githubusercontent.com/35248895/90070181-4cd70d80-dca8-11ea-8b26-e4f797aa7e6a.png)

- Once again in Azure, go to Bot Channels Registration > Channels > Direct Line Speech
- Select the Speech cognitive service you created earlier (I believe you can only link one speech service to one bot at a time, fyi) > Save
- Bot Channels Registration > Settings > check Enable Streaming Endpoint > Save
![image](https://user-images.githubusercontent.com/35248895/90071291-274b0380-dcaa-11ea-8b22-98743e325f82.png)

</details>

<details>
    <summary>Run sample 03.speech/a.direct-line-speech and talk to the DLS-enabled bot.</summary>

- Add your Speech cognitive service key and region to the HTML file for sample 3a

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Using Direct Line Speech</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Direct Line Speech adapter set is only available in full bundle -->
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>

  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {
        const adapters = await window.WebChat.createDirectLineSpeechAdapters({
          fetchCredentials: {
            region: 'xxxxx',
            subscriptionKey: '89exxxxxxxxxxxxxxxxxxxxxxxxxxxx2'
          }
        });

        console.log(adapters);

        // Pass the set of adapters to Web Chat.
        window.WebChat.renderWebChat(
          {
            ...adapters
          },
          document.getElementById('webchat')
        );

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>

```

- `npx serve`
- Navigate to `localhost:5000`, click the microphone, speak to the bot

![image](https://user-images.githubusercontent.com/35248895/90072186-d0462e00-dcab-11ea-8589-74af8fa58a8b.png)

The bot speaks back!
</details>

___

If you follow the steps above, which are similar to [this tutorial on enabling speech in your bot](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk) (they use C#), then you should be able to run sample 3a just fine

**Comment by Zerryth** [comment]
Hmm, looking around there does seem to be some issue on the other layers regarding DLS.
https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221#issuecomment-673020344

What kind of browser and OS are you using @collegewap ?

**Comment by collegewap** [comment]
@Zerryth

The bot is working fine (Tried example 1a). If I try the [speech services ](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/b.cognitive-speech-services-js) also, it works fine. I made sure that all the steps to enable directline speech are done correctly. Still facing the issue.

I am using Windows 10+ Chrome. Tried in Firefox as well. Same error. I tried https://compulim.github.io/webchat-loader/ with the mock bot and getting the same error.

**Comment by Zerryth** [comment]
Hmm...

@collegewap ok, I think what we need now here is painfully explicit step-by-step of what you're doing, just so that we can get a repro of your issue. 

Please provide exact repro steps of at least one thing you're doing to get your error, so that we could hopefully get it too and dig down to a resolution

**Comment by collegewap** [comment]
Here are the steps I am doing:

1. Open https://compulim.github.io/webchat-loader/
2. Select "MockBot (Direct Line Speech)"
3. Clear the generated token
4. Choose "east us 2" as the region.
5. Provide my speech key and click on "Generate Token".
6. Click on "Open Web Chat in a new window"
7. Click on the mic button and I would see the above-mentioned error.
![image](https://user-images.githubusercontent.com/9767383/90095581-b6115c00-dd4e-11ea-86e9-b171ab4b0526.png)


My setup:

![image](https://user-images.githubusercontent.com/9767383/90096083-06d58480-dd50-11ea-86cd-1bc1cc42aa15.png)


![image](https://user-images.githubusercontent.com/9767383/90096572-4355b000-dd51-11ea-9a81-50371848885b.png)


![image](https://user-images.githubusercontent.com/9767383/90096708-a5aeb080-dd51-11ea-9b0f-5ff1e1fed104.png)

And about 3a, we have an endpoint that generates the token. Also, I have tried the example given by you in https://github.com/microsoft/BotFramework-WebChat/issues/3407#issuecomment-673130903, by passing the speech key and getting the same error.

**Comment by collegewap** [comment]
@Zerryth We followed the same steps in another instance and it worked fine. Not sure what is the issue with this specific bot instance. Thanks for your help.
