### ISSUE TITLE
How to reduce size of my custom build of webchat.js currently the size is too heavy

### ISSUE THREAD

**Issue by sanjayror** [microsoft/BotFramework-WebChat#3408]
How to reduce size of my custom build of webchat.js

I cloned the https://github.com/microsoft/BotFramework-WebChat/ 

## Steps to reproduce

**Prep the repo by running**
1). npm ci
2). npm install
3). Run npm run bootstrap
4). Run npm run build

but the size is too heavy webchat-es5.js size is 22.1 MB and webchat.js size is 21.3 MB.

there size should be less then 3 MB

Please help how to reduce size of these files. Should I need to change any settings ??

Thanks in advance

**Comment by collegewap** [comment]
Try running the following command. The size would be around 2.8MB. If you serve the js from a CDN, the gzipped size would be around 700kb

``npm run publish``

**Comment by sanjayror** [comment]
Hi @collegewap 

Thanks for quick response 

I tried with npm run publish, but showing this error (npm ERR! missing script : publish) 

![image](https://user-images.githubusercontent.com/15170372/89989870-2a8cc200-dc9f-11ea-97ae-5b95bf453fc5.png)

error logs : [Uploading 2020-08-12T07_30_52_479Z-debug.log…]()

Thanks in advance

**Comment by sanjayror** [comment]
> Try running the following command. The size would be around 2.8MB. If you serve the js from a CDN, the gzipped size would be around 700kb
> 
> `npm run publish`
> 
> You can see what contributes to bundle size here: http://cdn.botframework.com/botframework-webchat/master/stats.html

Hi @collegewap 
Thanks for quick response

I tried with npm run publish, but showing this error (npm ERR! missing script : publish)

![image](https://user-images.githubusercontent.com/15170372/89992640-2d89b180-dca3-11ea-981b-f62d61c1ace4.png)


complete error log: 
[2020-08-12T07_30_52_479Z-debug.log](https://github.com/microsoft/BotFramework-WebChat/files/5061449/2020-08-12T07_30_52_479Z-debug.log)

**Comment by collegewap** [comment]
You can add the following script to package.json

``"publish": "SET NODE_ENV=production&& lerna run --ignore playground --stream build",``

Btw, it is not advised to clone the repo. It is recommended to make use of the [CDN bundle ](https://cdn.botframework.com/botframework-webchat/latest/webchat.js)and use [examples](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples) to customize the bot.

**Comment by sanjayror** [comment]
> You can add the following script to package.json
> 
> `"publish": "SET NODE_ENV=production&& lerna run --ignore playground --stream build",`
> 
> Btw, it is not advised to clone the repo. It is recommended to make use of the [CDN bundle ](https://cdn.botframework.com/botframework-webchat/latest/webchat.js)and use [examples](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples) to customize the bot.

Hi @collegewap 
Thanks for quick reply

I tried with npm run publish but still the webchat.js size around 21 MB.

you can see the size in dist folder
![image](https://user-images.githubusercontent.com/15170372/90043410-b3305000-dce9-11ea-8178-8287098d06f6.png)

here is my package.json file
![image](https://user-images.githubusercontent.com/15170372/90043450-c2170280-dce9-11ea-989d-50bc7d68772a.png)

Thanks for your kind support

**Comment by compulim** [comment]
Please refer to this doc on how to build production bits, https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/BUILD_SCRIPTS.md#implementations.

**Comment by sanjayror** [comment]
Hi @compulim 

Thanks for your quick response !!

**I tried but the size of webchat.js is still 21 MB**

thanks for sharing this link : https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/BUILD_SCRIPTS.md#implementations.

I took help from here :
![image](https://user-images.githubusercontent.com/15170372/90271609-b6f2dc80-de79-11ea-9b50-369f69b8a304.png)

**I check bot-framework every files and node_env=production is set  everywhere.**

![image](https://user-images.githubusercontent.com/15170372/90271323-40ee7580-de79-11ea-97ee-6526ff5c1a62.png)

![image](https://user-images.githubusercontent.com/15170372/90271408-67acac00-de79-11ea-8f59-9ceb6acae310.png)

![image](https://user-images.githubusercontent.com/15170372/90271469-7eeb9980-de79-11ea-9301-2727385ca32b.png)


@compulim 

**It's look like my webchat.js is not minified.**

![image](https://user-images.githubusercontent.com/15170372/90272491-21584c80-de7b-11ea-996d-2d978f3e9ee0.png)

**looks like the similar issue #1811** 

![image](https://user-images.githubusercontent.com/15170372/90272748-75fbc780-de7b-11ea-90ca-e1bda153ce18.png)

please help me what should I do next !!

Thanks for help

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/90277540-a8290d00-de1a-11ea-9b34-de4a472e8687.png)

We are not seeing any problems here.

Can you check if your environment variables were set correctly?

After your env is set, run

```sh
node -e console.log(process.env.node_env || process.env.NODE_ENV)
```

It should display `production`. This means the env is correctly set.

**Comment by sanjayror** [comment]
Thanks @compulim now my webchat.js size is 3.2 MB  👍 😊 

![image](https://user-images.githubusercontent.com/15170372/90282516-1fe35000-de8c-11ea-93fb-642cafe4056b.png)

Thanks for all your efforts.
