### ISSUE TITLE
sending and receiving events from webchat in Bot Composer

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-WebChat#3409]
Hi,

I am able to dispatch an event (with custom name) from webchat and capture it in bot composer using 'Event received ' trigger
as shown in below screenshot.

<img width="386" alt="Eventreceived" src="https://user-images.githubusercontent.com/36945600/90017329-ffb76380-dcc8-11ea-96c5-ea30579766b3.PNG">

But how can I post or send an event activity from bot composer to webchat?

🚨 The issue tracker is not for implementation questions 🚨

[Question]

**Comment by v-kydela** [comment]
@madbeher - Have you tried using [Send a response](https://docs.microsoft.com/en-us/composer/how-to-send-messages#the-user-scenario) with an activity [structured response template](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template) with "event" as the `type` property?

**Comment by madbeher** [comment]
we tried using the solution you mentioned and it is working for us.  Thanks for providing quick solution.

**Comment by v-kydela** [comment]
@madbeher - You're welcome, glad to hear it

**Comment by LiorArmiev** [comment]
> Hi,
> 
> I am able to dispatch an event (with custom name) from webchat and capture it in bot composer using 'Event received ' trigger
> as shown in below screenshot.
> 
> <img alt="Eventreceived" width="386" src="https://user-images.githubusercontent.com/36945600/90017329-ffb76380-dcc8-11ea-96c5-ea30579766b3.PNG">
> 
> But how can I post or send an event activity from bot composer to webchat?
> 
> 🚨 The issue tracker is not for implementation questions 🚨
> 
> [Question]

Hi, can you help me with one question, 
does this 'event recived' is like the proactive message? if not do you know how to create proactive alerts with the Composer?

**Comment by zuercher8353** [comment]
@madbeher Would you be willing to give some insights off how you achieved to send an event activity from bot composer to webchat? If possible could you share to send the response message you created and the code you used to  catch the event in the webchat?

**Comment by felix-gonzalez** [comment]
Hello @zuercher8353 , 
  I'm testing it with:

[Activity
  type = event
  name = WEB_CHAT/SEND_EVENT
  value = welcome
]

in a "send response" body in composer and I catch it on webchat side with:

       const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {

		      console.log(" Action  " + action.type);

          if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY' && action.payload.activity.type === 'event'){
            console.log('Event received from backend :' + action.payload.activity.value);
          }
         return next(action);
       });

**Comment by iliosana** [comment]
@felix-gonzalez's solution worked for me. But I had to enter the code in the Composer _Send a Response_ **_code editor_** for it to work. To do so, you first need to click on **_Show code_**, see picture below.
![sendResponse1](https://user-images.githubusercontent.com/95961035/184816163-5883e002-dfa1-44ae-a0bd-633f6bc8357b.JPG)

![sendResponse2](https://user-images.githubusercontent.com/95961035/184816104-9b8e2b8f-4986-462d-9ae8-5ad4aeef600b.JPG)
