### ISSUE TITLE
Web Chat - Content display - Questions

### ISSUE THREAD

**Issue by AnithaJothi** [Microsoft/BotFramework-WebChat#341]
I am using the classic Web Chat control with the preview option enabled for my Bot. My bot is built using c# Bot framework SDK with bot builder version 3.5.2.
I need to know how to implement the below
1. I use Rich Cards (Hero card) in my bot (shown below). Need to know how to change the colour and/or font of the text that get displayed in rich card buttons
![image](https://cloud.githubusercontent.com/assets/25479670/22975042/1ccce630-f3ab-11e6-90f1-08f51f0c0b1b.png)

2. Add separate images/icons representing the bot as well as the user. As of now the web chat displays only the names of the bot and the user (Screenshot below)
![image](https://cloud.githubusercontent.com/assets/25479670/22975156/9a7fc6ce-f3ab-11e6-8a1c-ecdc6cfec5ab.png)

Any help is much appreciated please!

**Comment by billba** [comment]
Neither of this are currently supported. You'd need to clone this repo and alter the code yourself.
