### ISSUE TITLE
Directline speech stops working if user clicks on the Mic during recognition

### ISSUE THREAD

**Issue by collegewap** [microsoft/BotFramework-WebChat#3411]
## Screenshots

![image](https://user-images.githubusercontent.com/9767383/90147661-0d8be800-dda0-11ea-88b2-4d7144d61d70.png)

## Version
4.9.2

## Steps to reproduce

1. Go to https://compulim.github.io/webchat-loader/
2. Select "MockBot (Direct Line Speech)"
3. Click on "Open Web Chat in a new window"
4. Speak something
5. Before the bot responds, click on Mic again
6. The screen would be hung showing "Starting.."

The issue is replicable in some other scenarios as well. I am unable to mention the exact steps. If you play around the mic button, it gets hung.

## Expected behavior

Webchat should not get hung.

[Bug]

**Comment by carlosscastro** [comment]
Thanks for reporting. We'll investigate and prioritize during our planning and update as necessary. Thanks!

**Comment by carlosscastro** [comment]
@compulim if possible please add to the R11 investigate backlog.

**Comment by collegewap** [comment]
Happens in mock bot also.

Steps to replicate:
1. Open [3a](https://microsoft.github.io/BotFramework-WebChat/03.speech/a.direct-line-speech/)
1. Say hello
1. After bot speaks, click on Mic and don't say anything
1. Now I get the second message
1. After the bot finishes speaking, click on Mic.
1. It will get hung on "Starting..."

This happens more often in my custom bot

![image](https://user-images.githubusercontent.com/9767383/90253227-70dc4f80-de5e-11ea-8637-b6dadca015ab.png)

**Comment by peterinnesmsft** [comment]
@compulim is there any update on this one? Outside of SLA, so if we could prioritize a response, that would be great.

**Comment by peterinnesmsft** [comment]
@collegewap we will investigate and handle this issue as part of our next upcoming release cycle.

**Comment by compulim** [comment]
Sorry for late response. I am starting to investigate and will post my investigation notes here.

**Comment by compulim** [comment]
## Minimal repro

- Connect using DLSpeech to any bots
   - For example, /samples/01.getting-started/d.es5-direct-line-speech/index.html
- After connected, click on microphone button and remain silent
   - This should trigger `InitialSilenceTimeout` event on the service side
- The bot will say "Unknown command: ''. Type help to learn more."
- Click on microphone button again
- Expected: the microphone can be turned on again
- Actual: it just say "Starting..." and hung there

**Comment by cwhitten** [comment]
Moving from R11 with the understanding that we won't have enough lead time to integrate a drop of the speech sdk

**Comment by edwgj** [comment]
Hi, another bug is reproduced here:

> 1. Go to [https://compulim.github.io/webchat-loader/](https://compulim.github.io/webchat-loader/) 

> 2. Select "MockBot (Direct Line Speech)"

> 3. Click on "Open Web Chat in a new window"

> 4. Type help

> 5. The bot sends cards with lots of options, click on Mic again

> 6. The bot is listening, click on any card option

> 7. Web chat UI disappear, the screen gets blank

**Comment by corinagum** [comment]
This is related to #3575. Keeping this issue open to ensure we verify fixed behavior post-bump.

**Comment by compulim** [comment]
This seems fixed in Speech SDK 1.15.0.
