### ISSUE TITLE
Adaptive card Action.ShowCard not showing arrow

### ISSUE THREAD

**Issue by naveenkumarreddym** [microsoft/BotFramework-WebChat#3412]
Missing downward arrow on the Action.ShowCard as shown in the adaptive cards document 

## Screenshots

![image](https://user-images.githubusercontent.com/51904323/90157785-c9064980-ddab-11ea-8c24-2d3fbf304641.png)
![image](https://user-images.githubusercontent.com/51904323/90157861-e20efa80-ddab-11ea-9d4a-8a41061c9989.png)

## Version
1.2 and above
## Describe the bug

Document showing different card and same is not working

## Steps to reproduce

In the Adaptive card designer add Action.ShowCard 
Cannot see the downward arrow.

## Expected behavior

**Comment by v-kydela** [comment]
Thank you for the feedback, @naveenkumarreddym 

It looks like you're having issues with the Adaptive Cards designer which is supported by the Adaptive Cards team. This is the Web Chat repo where we handle Web Chat issues. Do you think your issue would be better suited for the Adaptive Cards repo? https://github.com/microsoft/AdaptiveCards

**Comment by naveenkumarreddym** [comment]
Moved to Adaptive cards
