### ISSUE TITLE
Adaptive card version not being considered

### ISSUE THREAD

**Issue by naveenkumarreddym** [microsoft/BotFramework-WebChat#3413]
We are sending the adaptive card payload by specifying the version as below. But we are still seeing the style not getting applied to the Submit button

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "body": [
    {
      "size": "Medium",
      "weight": "Bolder",
      "text": "**********",
      "type": "TextBlock"
    },
    {
      "size": "Medium",
      "weight": "Bolder",
      "text": "System: ",
      "type": "TextBlock"
    },
    {
      "text": "Not showing positive style\n\n",
      "type": "TextBlock",
      "wrap": true
    }
  ],
  "version": "1.2",
  "actions": [
    {
      "style": "positive",
      "type": "Action.ShowCard",
      "title": "Send reply",
      "card": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "body": [
          {
            "size": "small",
            "text": "Send message",
            "type": "TextBlock"
          },
          {
            "isMultiline": true,
            "id": "reply_message",
            "placeholder": "Type messages",
            "type": "Input.Text"
          }
        ],
        "actions": [
          {
            "data": {
              "action_handler": "************",
              "table": "**********"
            },
            "type": "Action.Submit",
            "title": "Send"
          }
        ],
        "version": "1.2"
      }
    },
    {
      "type": "Action.OpenUrl",
      "title": "*************",
      "url": "***********"
    }
  ]
}
```

## Screenshots
In MS Teams app (positive style not applied)
![image](https://user-images.githubusercontent.com/51904323/90158825-23ec7080-ddad-11ea-81c6-6367fc056215.png)

Same in designer (positive style applied)

![image](https://user-images.githubusercontent.com/51904323/90159350-e3412700-ddad-11ea-959e-7b749ac05ebf.png)

## Version
1.1 is not applying style and 1.2 is applying style. But we are passing version as 1.2 as part of content

**Comment by v-kydela** [comment]
Thank you for the feedback, @naveenkumarreddym

It looks like you're having issues with Adaptive Cards in MS Teams. This is the Web Chat repo where we handle Web Chat issues. Do you think your issue would be better suited for the Adaptive Cards repo? https://github.com/microsoft/AdaptiveCards

You can also submit Teams feedback through the Teams app directly.

**Comment by naveenkumarreddym** [comment]
Moved to Adaptive Cards
