### ISSUE TITLE
Sample list is broken

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/BotFramework-WebChat#3416]
![image](https://user-images.githubusercontent.com/64589372/90373189-d05e7900-e071-11ea-9fe6-f9930176948d.png)
On github now

**Comment by peterinnesmsft** [comment]
Looks to be an issue in the updated markdown which is causing the list to render incorrectly.

**Comment by peterinnesmsft** [comment]
@felixvanleeuwen I have submitted a PR to fix this - please see the link above to track status on resolution of this issue.
