### ISSUE TITLE
Microphone does not turn off after no recognized sound - related to #3666

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-WebChat#3421]
## Screenshots
N/A
## Version
Tested on 4.10.0, 4.9.2, 4.9.1, and 4.9.0,

## Describe the bug

On speech bot, if user doesn't say anything after pressing the microphone button, the microphone does not eventually turn off. 

## Steps to reproduce

1. Press microphone button
1. Wait several seconds
1. Note that the sendbox continues to say 'Listening...' and the microphone button remains red

## Expected behavior

The microphone should turn off after several seconds of no sound

## Additional context

Note: kind of an edge case - what is priority on this one?
Would this be fixed with #2211? 

[Bug]

**Comment by compulim** [comment]
Will see if this will be auto-fixed in #3575 (bump Speech SDK).

If not fixed in newer version of Speech SDK, we will need to estimate the cost of this fix.

**Comment by cwhitten** [comment]
Anticipating that https://github.com/microsoft/BotFramework-WebChat/issues/3411 will address this

**Comment by compulim** [comment]
This seems fixed in Speech SDK 1.15.0.
