### ISSUE TITLE
CDN integrity hashing is not correct.

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3423]
## Screenshots
![img](https://user-images.githubusercontent.com/22778273/90585968-e90e8200-e18a-11ea-98f2-d4b6c19d71e0.png)

## Version

CDN 4.10.0

## Describe the bug

Please correct the CDN integrity attributes' hashing values.

**Comment by corinagum** [comment]
Thank you. The hash values have been updated. https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.10.0
