### ISSUE TITLE
DirectLine Speech (DLS): username and userID is not being sent to bot

### ISSUE THREAD

**Issue by collegewap** [microsoft/BotFramework-WebChat#3426]
### DLS

![image](https://user-images.githubusercontent.com/9767383/90604588-b44a0b80-e21a-11ea-8193-5cb9d3caebdd.png)
When the user types a message
![image](https://user-images.githubusercontent.com/9767383/90604702-dcd20580-e21a-11ea-9dca-35fa06ac90fe.png)

When the user speaks, 'from' field itself is not present

![image](https://user-images.githubusercontent.com/9767383/90604983-52d66c80-e21b-11ea-9883-ae92d9c30291.png)

### Speech services 

![image](https://user-images.githubusercontent.com/9767383/90605330-ced0b480-e21b-11ea-8a5e-0ba1642dd53a.png)

Not sure why userID is not taken, but it works fine in my custom bot.

## Version

4.10.10

## Describe the bug

In the example [3a direct-line-speech](https://microsoft.github.io/BotFramework-WebChat/03.speech/a.direct-line-speech/), if we add username and userID while calling renderWebChat, they are not passed as on to the bot as "from id" and "from name".

However, passing the username value works fine in [3b cognitive-speech-services](https://microsoft.github.io/BotFramework-WebChat/03.speech/b.cognitive-speech-services-js/).

## Expected behavior
Webchat should pass the userID and username parameters to the bot in DLS method so that they can be used for analytics and reporting.

[Bug]

**Comment by compulim** [comment]
@collegewap `userID` and `username` works differently in DLSpeech. I believe forcibly passing it to DLSpeech channel may not work.

For the missing "role", we will investigate.

**Comment by collegewap** [comment]
@compulim Could you please let me know how do I pass `userID` and `username` to DLSpeech and capture it in the bot side? I didn't find any related documents.

**Comment by compulim** [comment]
To pass user ID to a DLSpeech bot, you will need to pass it thru `createAdapters()`, for example:

```js
const adapters = await window.WebChat.createDirectLineSpeechAdapters({
  fetchCredentials,
  userID: 'u-12345'
});
```

However, `username` is not supported by DLSpeech channel.

We will update our docs to show how to set a custom user ID.

**Comment by compulim** [comment]
One more note on the `from` field.

According to the spec, the `from` field should not be sent to the service. It is up to the bot to find out the role of the sender based on `from.id`.

> The `role` field indicates whether entity behind the account is a user or bot. This field is intended for use in the Transcript format [16] to distinguish between activities sent by users and activities sent by bots. The value of the `role` field is a string.
>
> `A7511`: Senders SHOULD NOT include this field. Receivers SHOULD ignore this field.
