### ISSUE TITLE
Ability to customize avatar image in conversation

### ISSUE THREAD

**Issue by CHuijsman** [microsoft/BotFramework-WebChat#3427]
## Feature Request
**Is your feature request related to a problem? Please describe.**
User experience is one of the most important KPI’s for our entire website and thus for our product. This includes the ease at which users can read the information the chatbot provides them with. In our Web Chat V3 application we adjusted the source code, so we can show the avatar image only when it is the last message of the bot. This creates a more clean window and thereby less chaos for the user. In Web Chat V4, there is the styleoption to add an avatar image next to the card but no customization option. Either the avatar is shown for every message or there is no avatar at all. We would like to have a setting or ability, where we can only show the avatar for the last bot message send.

**Describe the suggestion or request in detail**
There are two solutions what will work: Either a new setting for the styleoptions which enables the option to only show the avatar for the last bot-message or a middleware option that allows us to indivudually style activities.

**Describe alternatives you have considered**
We already tried to adjust the avatar styling with the use of middleware. We removed the image element and set the image background equal too the chat background. However, we were not able to rerender the avatars.

**Comment by lauren-mills** [comment]
Hi, we have added this to the backlog and will evaluate it for a future release.

**Comment by corinagum** [comment]
This feature was implemented and released in 4.10.0. Please see the Activity Grouping PR: https://github.com/microsoft/BotFramework-WebChat/pull/3365
