### ISSUE TITLE
Dispatched event, postBack, or messageBack + activityMiddleware causes fatal error

### ISSUE THREAD

**Issue by stevkan** [microsoft/BotFramework-WebChat#3434]
## Screenshots
![image](https://user-images.githubusercontent.com/18403946/90941691-b7362f00-e3c7-11ea-87e4-19139ac92e26.png)

## Version
CDN: v4.10.0

## Describe the bug
Error occurs when `store.dispatch()` is used to send a `SEND_EVENT`, `SEND_POST_BACK`, or `SEND_MESSAGE_BACK` activity and `activityMiddleware` is also utilized.

## Steps to reproduce
1. Run the [05.custom-components/c.user-highlighting](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/c.user-highlighting) MockBot located in the sample.
1. Type "herocard" into the send box
1. Click the "postBack" button
1. See error

## Expected behavior
No error should occur with dispatch and activityMiddleware functioning, as expected.

[Bug]

**Comment by tdurnford** [comment]
@stevkan I believe this is due to a breaking change in Web Chat v4.10. Take a look the [Breaking Changes](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md#change-in-general-middleware-design) in the Change Log for more details. 

@compulim Can you please weigh in.

**Comment by stevkan** [comment]
@tdurnford, thanks for the info. That did seem to fix it. Originally, I had a different implementation that, with v.4.10.0, was failing. I went to the samples and updated according to those which, as you can see, still wasn't working. Late on a Friday, I hadn't thought to check the change log.

**Comment by tdurnford** [comment]
I'm going to reopen this since the sample is still breaking.

**Comment by stevkan** [comment]
@tdurnford, good call on re-opening. Just tested the sample referenced above, again, and yes it is still broken.

The readme shows the below code which, presumably, MockBot still uses as it also breaks when calling the hero card and clicking the `postBack` button.

```js
const activityMiddleware = () => next => card => {
    return children => (
        <div  className={card.activity.from.role === 'user' ? 'highlightedActivity--user' : 'highlightedActivity--bot'} >
            {next(card)(children)}
        </div>
    );
};
```

**Comment by corinagum** [comment]
Needs prioritization
