### ISSUE TITLE
suggestedActionsStackedMaxHeight Style Option

### ISSUE THREAD

**Issue by SeanDarlingBiomni** [microsoft/BotFramework-WebChat#3435]
## Feature Request

suggestedActionsStackedHeight is a good recent addition to the style options. It would be better to have suggestedActionsStackedMaxHeight which sets the maximum height of the suggested actions area but leaves it only growing to fit it's contents when that would be less than the max height.

**Is your feature request related to a problem? Please describe.**

Currently the webchat component looks broken when there are too many suggested actions. If we do not use suggestedActionsStackedHeight then the suggested actions takes up too much space in the interface. If we do use suggestedActionsStackedHeight then it can be set to a sensible limit but now it is a problem when there are not enough suggested actions, because there is too much empty space.

suggestedActionsStackedMaxHeight would allow the suggested action area to resize dynamically and work in both cases.

**Describe the suggestion or request in detail**

Please add a suggestedActionsStackedMaxHeight or similar setting that makes the suggested actions area only take up as much space as is needed to fit it's suggested actions or it's defined max height (whichever is lowest).

[Enhancement]

**Comment by lauren-mills** [comment]
We will put this on the backlog and evaluate it for an upcoming release. Thanks!

**Comment by corinagum** [comment]
@SeanDarlingBiomni This issue was fixed in PR https://github.com/microsoft/BotFramework-WebChat/pull/3456
You can update to 4.10.1 (or 4.11, latest) to see this change in Web Chat. Sorry for the delayed close.
