### ISSUE TITLE
BotFramework-WebChat Version 4.10.0 doesn't support adaptive card version 1.3

### ISSUE THREAD

**Issue by Tartua** [microsoft/BotFramework-WebChat#3440]
Microsoft has recently updated to adaptive card version 1.3 to add validation to the cards.

Here is the message that is displayed in the webchat.
{
  "message": "The specified card version (1.3) is not supported. The maximum supported card version is 1.2"
}

Currently versions on site:
meta name="botframework-directlinespeech:version" content="4.10.0"
meta name="botframework-webchat:bundle:variant" content="full"
meta name="botframework-webchat:bundle:version" content="4.10.0"
meta name="botframework-webchat:core:version" content="4.10.0"
meta name="botframework-webchat:ui:version" content="4.10.0"

Please assist

**Comment by compulim** [comment]
We will bump to Adaptive Cards 2.x library, which is on 1.3 schema, in R11.

**Comment by compulim** [comment]
@Tartua we already have an issue #3392 for bumping Adaptive Cards in Web Chat. I will close this one as dupe.
