### ISSUE TITLE
Suggested Actions container height is not flexible

### ISSUE THREAD

**Issue by kmkaliraj** [microsoft/BotFramework-WebChat#3444]
I tried using the new style options to set height and overflow for the suggested actions container. It's always fixed height whereas we want it to be flexible so that max-height is what we want to set. The height should fit the content if the container have few buttons and doesn't overflow
styleOptions={{
              botAvatarInitials: true,
              userAvatarInitials: true,
              suggestedActionBackground: 'White',
              suggestedActionBorder: 0,
              suggestedActionBorderRadius: 4,
              suggestedActionBorderStyle: 'solid',
              suggestedActionBorderWidth: 1,
              suggestedActionHeight: 32,
              suggestedActionLayout: 'stacked',
              suggestedActionsStackedHeight: '50vh',
              suggestedActionsStackedOverflow: 'auto'
            }}

## Screenshots
![stacked actions](https://user-images.githubusercontent.com/23566351/91791439-00586100-ebc8-11ea-936f-16a4012b1540.gif)

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by corinagum** [comment]
Thanks for catching this bug. I'm adding it to our TBD list.
