### ISSUE TITLE
http://www.linkedin.com/in/studentAnnouncement

### ISSUE THREAD

**Issue by KAU-KING-ABDULAZIZ** [microsoft/BotFramework-WebChat#3451]
## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by corinagum** [comment]
This appears to be spam. If you need to report a bug, please fill out the provided report/reproduction steps.
