### ISSUE TITLE
Duplicate welcome messages when the chat is initialized from directline channel. 

### ISSUE THREAD

**Issue by sandeepreddy0987** [microsoft/BotFramework-WebChat#3452]
![image](https://user-images.githubusercontent.com/33647692/92149702-9b755480-eddb-11ea-8986-20c321bf9d47.png)

## Describe the bug
Our bot is built in bot composer and deployed to azure bot channel. Using a direct line channel we are connecting it to the chatbot in our cross-platform mobile application (xamarin, C#). we are using a secret key for conversation.
we are using the syncfusion sfchat package for the user interface of the bot.
we are facing 2 issues here
1)Duplicate welcome messages after every time we start the app( shown in the attached image)
2) we have yes or no choices for all our questions. They are not shown after a few questions(after 5th question options are not displayed to select).

please let me know if I can change anything in the bot composer or service class to fix these issues. Thanks

**Comment by v-kydela** [comment]
@sandeepreddy0987 - Are you still working on this?

**Comment by sandeepreddy0987** [comment]
yes, I can still see the issue with the duplicate welcome message. @v-kydela if it is possible to contact me in teams or skype, I can show you the issue.

**Comment by v-kydela** [comment]
@sandeepreddy0987 - I can see the issue just fine in your screenshot, thank you. I just need to see the relevant code in order to help you fix it. Can you show me the code that handles welcome messages both on the bot side and the client side?

**Comment by sandeepreddy0987** [comment]
Below is the code for welcome dialog in bot composer. please let me know if anything required.
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "$designer": {
      "name": "deploymentbot",
      "id": "Z15R6G"
    }
  },
  "autoEndDialog": true,
  "defaultResultProperty": "dialog.result",
  "recognizer": "deploymentbot.lu",
  "triggers": [
    {
      "$kind": "Microsoft.OnConversationUpdateActivity",
      "$designer": {
        "id": "376720",
        "name": "Welcome message"
      },
      "actions": [
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "L3nUbK"
          },
          "activity": "${SendActivity_L3nUbK()}"
        },
        {
          "$kind": "Microsoft.ChoiceInput",
          "$designer": {
            "id": "thjABi"
          },
          "defaultLocale": "en-us",
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": true,
          "allowInterruptions": false,
          "prompt": "${ChoiceInput_Prompt_thjABi()}",
          "choiceOptions": {
            "includeNumbers": true,
            "inlineOrMore": ", or ",
            "inlineOr": " or ",
            "inlineSeparator": ", "
          },
          "style": "auto",
          "choices": [
            "Calculate my Risk",
            "Covid FAQ"
          ],
          "property": "user.option",
          "outputFormat": "value",
          "recognizerOptions": {
            "recognizeOrdinals": true,
            "recognizeNumbers": true
          }
        },
        {
          "$kind": "Microsoft.IfCondition",
          "$designer": {
            "id": "EhwZfu"
          },
          "condition": "user.option=='Calculate my Risk'",
          "actions": [
            {
              "$kind": "Microsoft.BeginDialog",
              "$designer": {
                "id": "VZ7HJZ"
              },
              "activityProcessed": true,
              "dialog": "Riskassessment"
            }
          ],
          "elseActions": [
            {
              "$kind": "Microsoft.SendActivity",
              "$designer": {
                "id": "6TvEQG"
              },
              "activity": "${SendActivity_6TvEQG()}"
            }
          ]
        },
        {
          "$kind": "Microsoft.EndDialog",
          "$designer": {
            "id": "vacaJH"
          }
        }
      ],
      "runOnce": false
    },
    {
      "$kind": "Microsoft.OnUnknownIntent",
      "$designer": {
        "id": "777383"
      },
      "actions": [
        {
          "$kind": "Microsoft.QnAMakerDialog",
          "$designer": {
            "id": "284337",
            "name": "Connect to QnA Knowledgebase"
          },
          "knowledgeBaseId": "=settings.qna.knowledgebaseid",
          "endpointKey": "=settings.qna.endpointkey",
          "hostname": "=settings.qna.hostname",
          "noAnswer": "Sorry, I did not find an answer.",
          "threshold": 0.3,
          "activeLearningCardTitle": "Did you mean:",
          "cardNoMatchText": "None of the above.",
          "cardNoMatchResponse": "Thanks for the feedback.",
          "top": 3
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "$designer": {
        "id": "G58Gpk",
        "name": "Risk"
      },
      "intent": "Risk",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "$designer": {
            "id": "HBU3rU"
          },
          "activityProcessed": true,
          "dialog": "Riskassessment"
        }
      ]
    }
  ],
  "$schema": "https://raw.githubusercontent.com/microsoft/BotFramework-Composer/stable/Composer/packages/server/schemas/sdk.schema",
  "generator": "deploymentbot.lg",
  "id": "deploymentbot"
}

**Comment by v-kydela** [comment]
@sandeepreddy0987 - Now that you've provided that JSON, I can see the problem. Please refer to any Composer sample to see the correct way to send a welcome message:

![image](https://user-images.githubusercontent.com/41968495/92534154-ef6fa700-f1e8-11ea-9c03-a7a51ce6524e.png)

Depending on how your Direct Line client is configured, your bot may receive one or two conversation updates when a new conversation is created. If your bot receives two conversation updates then it will send two welcome messages using the code you've posted here. However, if you respond to conversation updates correctly by checking the `membersAdded` property then your bot will only respond to the conversation update once.

Does this resolve your issue?

**Comment by sandeepreddy0987** [comment]
Thank you @v-kydela. There is a bug in calling the method in app. we have fixed it. Issue resolved
