### ISSUE TITLE
Send an activity of type "event" from React WebChat

### ISSUE THREAD

**Issue by harimadhavk** [microsoft/BotFramework-WebChat#3454]
Is it possible to send an activity from the React WebChat as below. This is to inform the bot with additional payload as an one time activity for the particular conversation.

{
    "type": "event",
    "name": "userInformation",
    "from": {
        "id": "postman-client",
        "name": "postman-client"
    },
    "value": {
        "sender":"emulator",
        "auditorId": "123456",
        "auditorEmail": "test@gmail.com",
        "countryId": "911",
        "language": "en-US",
        "deviceModel": "Samsung SM-A510F",
        "deviceId": "2fe5cd99f05c3703",
        "localTime": "2020-09-02T15:58:48.862+03:00[Europe/Moscow]",
        "timeZone": "GMT+03:00"
    }
}

**Comment by GeoffCoxMSFT** [comment]
harimadhavk, thank you for opening this issue.  For product behavior, how-to, or general understanding questions, please use Stackoverflow.
