### ISSUE TITLE
Display conversation from a static blob or activity json 

### ISSUE THREAD

**Issue by harimadhavk** [microsoft/BotFramework-WebChat#3455]
🚨 The issue tracker is not for implementation questions 🚨

We have a requirement to show the conversation between a user and an bot as a view only mode. The bot is storing the conversation information as Blob in Azure Blob storage. 

Is it possible to display the data as read only using the React WebChat component or which portion of code can i strip to display the chat log (Activity JSON eg 
`"[{"type":"message","id":"Cv8Zu2uEUt0EaTAMOKlGNc-c|0000009","timestamp":"2020-09-07T05:18:25.0740991Z","serviceUrl":"https://directline.botframework.com/","channelId":"directline","from":{"id":"dl_a75740l7a","name":""},"conversation":{"id":"Cv8Zu2uEUt0EaTAMOKlGNc-c"},"recipient":{"id":"test@8U3KvbiLxS8","name":"test"},"textFormat":"plain","locale":"en-US","text":"👎","channelData":{"clientActivityID":"","clientTimestamp":"2020-09-07T05:18:25.496Z"}}]")`

Or is this is even a valid use case for the component ?

**Comment by GeoffCoxMSFT** [comment]
harimadhavk, thank you for opening this issue.  For product behavior, how-to, or general understanding questions, please use Stackoverflow. Asking a question there can help you determine if this is possible.
