### ISSUE TITLE
Release of 4.10.1

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3460]
# Checklist

## Build

1. [x] ~Bump MockBot to Bot Framework SDK release 4.10.3~
   - ~https://www.npmjs.com/package/botbuilder/v/4.10.3~
   - We are not bumping for patch release
1. Bump `botframework-directlinejs`
   - Bump `botframework-streaming` dependency to `4.10.3` (Is this the correct version? Need to ask Steven.)
   - Bump version to `0.13.1`, PR is #XXX
   - Wait for release on NPM
1. [x] Bump `botframework-directlinejs@0.13.1` dependency in Web Chat
1. [x] Bump to `4.10.1`
   - [x] Update `CHANGELOG.md` to mark specific changes in `4.10.1`
   - [x] Run `npm version --no-git-tag-version 4.10.1`
   - [x] Merged into `master`, the PR number is #3461
   - Commit is `c5afaef`
   - Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - Pipeline name is `BotFramework-WebChat-daily`
   - The build number is [`164890`](https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=164890&view=results) and commit is `c5afaef`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] Manual testing on major browsers using `webchat-release-testing`
   - [x] Chrome 85.0.4183.102
   - [x] Edge (Anaheim) 85.0.564.51
   - [x] Edge (UWP) 44.20206.1000.0
   - [x] Firefox 80.0.1
   - [x] IE11 11.450.19041.0 (11.0.205 KB4571687)
   - [x] macOS Safari 13.1.1 (15609.2.9.1.2)
      - DLSpeech: Web Socket connection to `westus2.convai.speech.microsoft.com` closed instantly after connected, it also repro on previous versions of Web Chat (failed on 4.9.0, 4.8.1)
         - https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221
   - [x] iOS Safari 13.6.1
      - DLSpeech: Web Socket connection close instantly after connected, also repro on 4.9.2 and 4.8.1, very similar to macOS issue
         - https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221
   - [x] Android Chrome 85.0.4183.81
1. [x] Test specific fixes related to `4.10.1` and previous releases
   - [x] (N/A) ~(Look at [`CHANGELOG.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md) and list out PRs that were not covered with automated tests)~

## Release

1. [x] Make sure you are on `master` ~or `qfe`~ branch, run `git status` to check
1. [x] `git pull`
1. [x] Verify `/package.json`, `/package-lock.json`, and `CHANGELOG.md` has a version of `4.10.1`
1. [x] `git log`
   - Verify the latest commit is `c5afaef`
1. [x] `git tag v4.10.1`
1. [x] `git push -u upstream v4.10.1`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [x] Subresource Integrity can be generated by
      - From CDN: `curl -H 'Accept-Encoding: gzip' https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js | gunzip - | openssl dgst -sha384 -binary | openssl base64 -A`
      - From local: `cat webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [x] Attach assets including 3 JS files, `stats.json` and 4 tarballs
      - You can copy the artifacts from `webchat-release-testing/drops`
      - Tarballs download from npmjs
         ```
         curl -L -o botframework-directlinespeech-sdk-4.10.1.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.10.1.tgz
         curl -L -o botframework-webchat-4.10.1.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.10.1.tgz
         curl -L -o botframework-webchat-core-4.10.1.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.10.1.tgz
         curl -L -o botframework-webchat-component-4.10.1.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.10.1.tgz
         ```
1. [x] Kick off release to NPM
   - Release name is `[[PROD]]Push-WebChat-to-npmjs`
   - The build number is `164890`, release number is `27` and commit is `c5afaef`
   - [x] Retain the build indefinitely
1. [x] Kick off release to CDN
   1. [x] Prepare the email for approval
   - Release name is `[[PROD]]Push-WebChat-to-Prod-CDN-with-approval`
   - The build number is `164890`, release number is `2485` and commit is `c5afaef`
   - Script build number is `131156` (this shouldn't change between releases)
   1. [x] Send reminder email to approvers
   - [x] Retain the build indefinitely

## Post-release check

- [x] Test using `webchat-release-testing`
   - [x] Clone https://github.com/corinagum/WebChat-release-testing/
   - [x] `01.create-react-app`
      1. [x] Nuke `01.create-react-app/node_modules`
      1. [x] `npm install botframework-webchat@4.10.1` (just install the bundle package)
   - [x] Others
      -  Using script tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.10.1, with subresource integrity
         ```
         <script
            crossorigin="anonymous"
            integrity="sha384-"
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"
         ></script>
         ```

## Notification to interested parties

- [x] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/328
- [ ] Notify related parties for the following fixes
   - [x] SDK team
   - [x] Pooja
   - [ ] M365 team
   
# Changelog

### Breaking changes

-  To support Content Security Policy, [`glamor`](https://npmjs.com/package/glamor) is being replaced by [`create-emotion`](https://npmjs.com/package/create-emotion). The CSS hash and rule name is being prefixed with `webchat--css` with a random value.

### Fixed

-  Fixes [#3431](https://github.com/microsoft/BotFramework-WebChat/issues/3431). Removed delay of first activity with `replyToId` pointing to a missing activity, by [@compulim](https://github.com/compulim) in PR [#3450](https://github.com/microsoft/BotFramework-WebChat/pull/3450)

### Changed

-  Support Content Security Policy, in PR [#3443](https://github.com/microsoft/BotFramework-WebChat/pull/3443) by [@compulim](https://github.com/compulim)
   -  Moved from [`glamor@2.20.40`](https://npmjs.com/package/glamor) to [`create-emotion@10.0.27`](https://npmjs.com/package/create-emotion)
   -  Inlined assets are now using `blob:` scheme, instead of `data:` scheme
   -  Detect Web Worker support by loading a dummy Web Worker, instead of checking `window.MessagePort` and `window.Worker`
   -  Data URI used in image of attachments will be converted to URL with scheme of `blob:`
   -  Bumped dependencies
      -  [`react-film@3.0.0`](https://npmjs.com/package/react-film)
      -  [`react-scroll-to-bottom@4.0.0`](https://npmjs.com/package/react-scroll-to-bottom)
-  Bumped all dependencies to the latest versions, by [@corinagum](https://github.com/corinagum) in PR [#3380](https://github.com/microsoft/BotFramework-WebChat/pull/3380), [#3442](https://github.com/microsoft/BotFramework-WebChat/pull/3442)
   -  Development dependencies
      -  Root package
         -  [`@babel/plugin-proposal-class-properties@7.10.4`](https://npmjs.com/package/@babel/plugin-proposal-class-properties)
         -  [`@babel/plugin-proposal-object-rest-spread@7.11.0`](https://npmjs.com/package/@babel/plugin-proposal-object-rest-spread)
         -  [`@babel/plugin-transform-runtime@7.11.0`](https://npmjs.com/package/@babel/plugin-transform-runtime)
         -  [`@babel/preset-env@7.11.0`](https://npmjs.com/package/@babel/preset-env)
         -  [`@babel/preset-react@7.10.4`](https://npmjs.com/package/@babel/preset-react)
         -  [`@babel/preset-typescript@7.10.4`](https://npmjs.com/package/@babel/preset-typescript)
         -  [`@babel/runtime@7.11.2`](https://npmjs.com/package/@babel/runtime)
         -  [`babel-jest@26.4.0`](https://npmjs.com/package/babel-jest)
         -  [`concurrently@5.3.0`](https://npmjs.com/package/concurrently)
         -  [`core-js@3.6.5`](https://npmjs.com/package/core-js)
         -  [`global-agent@2.1.12`](https://npmjs.com/package/global-agent)
         -  [`husky@4.2.5`](https://npmjs.com/package/husky)
         -  [`jest@26.2.2`](https://npmjs.com/package/jest)
         -  [`jest-image-snapshot@4.1.0`](https://npmjs.com/package/jest-image-snapshot)
         -  [`jest-junit@11.1.0`](https://npmjs.com/package/jest-junit)
         -  [`jest-trx-results-processor@2.0.3`](https://npmjs.com/package/jest-trx-results-processor)
         -  [`lerna@3.22.1`](https://npmjs.com/package/lerna)
         -  [`lint-staged@10.2.13`](https://npmjs.com/package/lint-staged)
         -  [`prettier@2.0.5`](https://npmjs.com/package/prettier)
         -  [`serve@11.3.2`](https://npmjs.com/package/serve)
         -  [`serve-handler@6.1.3`](https://npmjs.com/package/serve-handler)
         -  Removed unused package [`@azure/storage-blob@12.1.0`](https://npmjs.com/package/@azure/storage-blob)
      -  Other packages
         -  [`@babel/cli@7.10.5`](https://npmjs.com/package/@babel/cli)
         -  [`@babel/core@7.11.0`](https://npmjs.com/package/@babel/core)
         -  [`@babel/plugin-proposal-class-properties@7.10.4`](https://npmjs.com/package/@babel/plugin-proposal-class-properties)
         -  [`@babel/plugin-proposal-object-rest-spread@7.11.0`](https://npmjs.com/package/@babel/plugin-proposal-object-rest-spread)
         -  [`@babel/plugin-transform-runtime@7.11.0`](https://npmjs.com/package/@babel/plugin-transform-runtime)
         -  [`@babel/preset-env@7.11.0`](https://npmjs.com/package/@babel/preset-env)
         -  [`@babel/preset-react@7.10.4`](https://npmjs.com/package/@babel/preset-react)
         -  [`@babel/preset-typescript@7.10.4`](https://npmjs.com/package/@babel/preset-typescript)
         -  [`@types/node@14.6.0`](https://npmjs.com/package/@types/node)
         -  [`@types/react@16.9.47`](https://npmjs.com/package/@types/react)
         -  [`@typescript-eslint/eslint-plugin@3.10.1`](https://npmjs.com/package/@typescript-eslint/eslint-plugin)
         -  [`@typescript-eslint/parser@3.10.1`](https://npmjs.com/package/@typescript-eslint/parser)
         -  [`babel-jest@26.2.2`](https://npmjs.com/package/babel-jest)
         -  [`concurrently@5.3.0`](https://npmjs.com/package/concurrently)
         -  [`copy-webpack-plugin@6.0.3`](https://npmjs.com/package/copy-webpack-plugin)
         -  [`core-js@3.6.5`](https://npmjs.com/package/core-js)
         -  [`cross-env@7.0.2`](https://npmjs.com/package/cross-env)
         -  [`css-loader@4.2.0`](https://npmjs.com/package/css-loader)
         -  [`eslint-plugin-prettier@3.1.4`](https://npmjs.com/package/eslint-plugin-prettier)
         -  [`eslint-plugin-react-hooks@4.1.0`](https://npmjs.com/package/eslint-plugin-react-hooks)
         -  [`eslint-plugin-react@7.20.6`](https://npmjs.com/package/eslint-plugin-react)
         -  [`eslint@7.7.0`](https://npmjs.com/package/eslint)
         -  [`global-agent@2.1.12`](https://npmjs.com/package/global-agent)
         -  [`globalize-compiler@1.1.1`](https://npmjs.com/package/globalize-compiler)
         -  [`html-webpack-plugin@4.3.0`](https://npmjs.com/package/html-webpack-plugin)
         -  [`http-proxy-middleware@1.0.5`](https://npmjs.com/package/http-proxy-middleware)
         -  [`jest@26.2.2`](https://npmjs.com/package/jest)
         -  [`node-dev@5.2.0`](https://npmjs.com/package/node-dev)
         -  [`prettier@2.1.1`](https://npmjs.com/package/prettier)
         -  [`pug@3.0.0`](https://npmjs.com/package/pug)
         -  [`serve@11.3.2`](https://npmjs.com/package/serve)
         -  [`simple-update-in@2.2.0`](https://npmjs.com/package/simple-update-in)
         -  [`source-map-loader@1.0.2`](https://npmjs.com/package/source-map-loader)
         -  [`terser-webpack-plugin@4.1.0`](https://npmjs.com/package/terser-webpack-plugin)
         -  [`typescript@4.0.2`](https://npmjs.com/package/typescript)
         -  [`webpack-cli@3.3.12`](https://npmjs.com/package/webpack-cli)
         -  [`webpack-stats-plugin@0.3.2`](https://npmjs.com/package/webpack-stats-plugin)
         -  [`webpack@4.44.1`](https://npmjs.com/package/webpack)
   -  Production dependencies
      -  [`@babel/plugin-proposal-async-generator-functions@7.10.5`](https://npmjs.com/package/@babel/plugin-proposal-async-generator-functions)
      -  [`@babel/runtime@7.11.2`](https://npmjs.com/package/@babel/runtime)
      -  [`@babel/standalone@7.11.0`](https://npmjs.com/package/@babel/standalone)
      -  [`abort-controller-es5@1.2.0`](https://npmjs.com/package/abort-controller-es5)
      -  [`botframework-directlinejs@0.13.0`](https://npmjs.com/package/botframework-directlinejs)
      -  [`core-js@3.6.5`](https://npmjs.com/package/core-js)
      -  [`event-iterator@2.0.0`](https://npmjs.com/package/event-iterator)
      -  [`event-target-shim-es5@1.2.0`](https://npmjs.com/package/event-target-shim-es5)
      -  [`expect@25.5.0`](https://npmjs.com/package/expect)
      -  [`globalize@1.5.0`](https://npmjs.com/package/globalize)
      -  [`markdown-it-attrs-es5@1.2.0`](https://npmjs.com/package/markdown-it-attrs-es5)
      -  [`markdown-it-attrs@3.0.3`](https://npmjs.com/package/markdown-it-attrs)
      -  [`markdown-it@11.0.0`](https://npmjs.com/package/markdown-it)
      -  [`math-random@2.0.1`](https://npmjs.com/package/math-random)
      -  [`memoize-one@5.1.1`](https://npmjs.com/package/memoize-one)
      -  [`mime@2.4.6`](https://npmjs.com/package/mime)
      -  [`on-error-resume-next@1.1.0`](https://npmjs.com/package/on-error-resume-next)
      -  [`p-defer@3.0.0`](https://npmjs.com/package/p-defer)
      -  [`p-defer-es5@1.2.1`](https://npmjs.com/package/p-defer-es5)
      -  [`react-say@2.0.2-master.ee7cd76`](https://npmjs.com/package/react-say)
      -  [`react-scroll-to-bottom@3.0.1-master.9e2b9d8`](https://npmjs.com/package/react-scroll-to-bottom)
      -  [`sanitize-html@1.27.4`](https://npmjs.com/package/sanitize-html)
      -  [`simple-update-in@2.2.0`](https://npmjs.com/package/simple-update-in)
      -  [`url-search-params-polyfill@8.1.0`](https://npmjs.com/package/url-search-params-polyfill)
      -  [`web-speech-cognitive-services@7.0.2-master.6004e4b`](https://npmjs.com/package/web-speech-cognitive-services)
      -  [`whatwg-fetch@3.4.0`](https://npmjs.com/package/whatwg-fetch)

### Samples

-  Added Content Security Policy sample, by [@compulim](https://github.com/compulim), in PR [#3443](https://github.com/microsoft/BotFramework-WebChat/pull/3443)
-  Update `create-react-app`-based samples to resolve `p-defer` as peer dependency, by [@compulim](https://github.com/compulim), in PR [#3457](https://github.com/microsoft/BotFramework-WebChat/pull/3457)
-  Bump [`encoding@0.1.13`](https://npmjs.com/package/encoding) in [`06.recomposing-ui/c.smart-display`](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/c.smart-display), by [@compulim](https://github.com/compulim), in PR [#3458](https://github.com/microsoft/BotFramework-WebChat/pull/3458)

**Comment by corinagum** [comment]
Closing as complete
