### ISSUE TITLE
[Edge UWP] Scroll-to-bottom is losing stickiness sometimes - related to #3597

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3463]
## Screenshots

(Will add)

## Version

`4.9.2`, `4.10.0`, `4.10.1`

## Describe the bug

On Edge UWP (44.20206.1000.0), we are seeing the transcript may lose stickiness when new messages coming in too fast or the messages are too long.

We also repro on `4.9.2` and `4.10.0`, which we already tested and didn't spot the issues at the time. May be related to browser testing, more verifications is required.

## Steps to reproduce

1. Go to https://corinagum.github.io/WebChat-release-testing
1. Click on `01`
1. Click the "Send all commands" button

## Expected behavior

The transcript should keep its stickiness throughout the test.

## Additional context

[Bug]

**Comment by corinagum** [comment]
related to #2884, #3653

**Comment by compulim** [comment]
Does not repro when typing very quickly in Edge Legacy or following the repro steps. It always stick to bottom.

https://user-images.githubusercontent.com/1622400/105697086-f6a60180-5eb8-11eb-955e-e7fce35150b5.mp4

![image](https://user-images.githubusercontent.com/1622400/105697169-11787600-5eb9-11eb-9002-5ecdb4d4a230.png)

**Comment by mihaiManea89** [comment]
Does reproduce when using Chrome/Edge with zoomed out view (80%-90%).
We developed our own BF4 webchat starting from this sample: https://microsoft.github.io/BotFramework-WebChat/06.recomposing-ui/a.minimizable-web-chat/
In the mock bot page, if you type "card bingsports" multiple times (10-20 times), the webchat starts to lose stickiness. 

Could you please confirm this is a problem regarding botframework-webchat or the minimizable wrapper?
