### ISSUE TITLE
Update README.md to surface recent feature highlights

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3468]
## Feature Request

Add a new section in README.md so we can tell developers what features we shipped and how to leverage them. Especially on CSP because it is a security feature, promoting it will help reduce attacks.

- Add Content Security Policy

[Enhancement]

**Comment by corinagum** [comment]
Is this for the 'Version notes' section? Or somewhere else?

**Comment by compulim** [comment]
Version note looks good.

**Comment by corinagum** [comment]
Updated our release checklist with this item: https://github.com/microsoft/BotFramework-WebChat/issues/3417
