### ISSUE TITLE
Activity Status not being rendered when adding reactions as per sample

### ISSUE THREAD

**Issue by nathanlindorff** [microsoft/BotFramework-WebChat#3473]
Adding reaction buttons as per https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/d.reaction-buttons/ results in the Activity Status (eg "5 minutes ago") not being rendered. Running the demo page associated with the sample shows the same issue (See screenshot)

I came across the issue while upgrading an older webchat from version 4.5 to 4.10. In the debugging I did for that the renderActivityStatus and renderAvatar functions are not being passed through as properties to the StackedLayout.

I realised after that that the sample had also changed, but the updated sample also displays the same issue. 

### From https://microsoft.github.io/BotFramework-WebChat/05.custom-components/d.reaction-buttons/
![image](https://user-images.githubusercontent.com/899380/92833566-5628d680-f41c-11ea-80a2-dbea6d8f3bb5.png)

### Debug screenshots from the bot i'm upgrading:
Props from StackedLayout bot message without reactions
![image](https://user-images.githubusercontent.com/899380/92835708-e8ca7500-f41e-11ea-95da-76309861e027.png) ![image](https://user-images.githubusercontent.com/899380/92835768-faac1800-f41e-11ea-9a70-0a31551e401c.png)

Props from StackedLayout bot message with reactions
![image](https://user-images.githubusercontent.com/899380/92835929-2e873d80-f41f-11ea-9bb4-59be206b6d3e.png) ![image](https://user-images.githubusercontent.com/899380/92835992-3fd04a00-f41f-11ea-8d71-d4c5ab56fc1b.png)

I haven't had a chance to update the code to match the updated reaction sample, but as stated the outcome (the missing status) is the same on the demo page.

```
class ThumbActivity extends React.Component<any> {
   public handleDownvoteButton = () => this.props.postActivity({ type: 'messageReaction', reactionsAdded: [{ activityID: this.props.activityID, helpful: -1 }] })
   public handleUpvoteButton = () => this.props.postActivity({ type: 'messageReaction', reactionsAdded: [{ activityID: this.props.activityID, helpful: 1 }] })

   public render() {
      const { props } = this

      return (
         <div style={thumbActivityStyle}>
            <div style={childActivityStyle}>{props.children}</div>
            <ul style={thumbsButtonBarStyle}>
               <li style={thumbsButtonListItemStyle}>
                  <button style={thumbButtonStyle} onClick={this.handleUpvoteButton}>👍</button>
               </li>
               <li style={thumbsButtonListItemStyle}>
                  <button style={thumbButtonStyle} onClick={this.handleDownvoteButton}>👎</button>
               </li>
            </ul>
         </div>
      )
   }
}

const ConnectedThumbActivity = (window as any).WebChat.connectToWebChat(
   ({ postActivity }) => ({ postActivity })
)(props => <ThumbActivity {...props} />)

export const thumbsMiddleware = () => next => card => {
   const allowReaction: boolean = card.activity.channelData && card.activity.channelData.allowReaction
   if (card.activity.from.role === 'bot' && allowReaction) {
      return children => (
         <ConnectedThumbActivity activityID={card.activity.id}>
            {next(card)(children)}
         </ConnectedThumbActivity>
      )
   } else {
      return next(card)
   }
}
```

I will update the code to use the new recommended syntax, but it appears based on the new sample that it will still be an issue. 

## Version

Version: 4.10 (Upgrading from 4.5)
Using NPM package
Embeded in iFrame

## Describe the bug

When adding middleware to add reactions, the Activity Status and Avatar are not rendered.

## Steps to reproduce

1. See description and screenshots

## Expected behavior

Expect message to render as per normal, with additional reaction elements.

[Bug]

**Comment by nathanlindorff** [comment]
I can confirm that after converting the React Component to use the new style the same issue occurs

![image](https://user-images.githubusercontent.com/899380/92843472-1c5dcd00-f428-11ea-9ab2-f6b8d4e61a42.png) ![image](https://user-images.githubusercontent.com/899380/92843563-3a2b3200-f428-11ea-8226-f7052ab145b4.png)

**Comment by nathanlindorff** [comment]
Dropping back to 4.9.2 everything has started working as expected again. I suspect the issue may have something to do with the breaking changes mentioned in [4.10.0 release notes](https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.10.0) given the mention of StackedLayout, but our code makes no direct reference to them.

**Comment by corinagum** [comment]
Thanks for filing this issue, @nathanlindorff. I'm adding it to our Investigate list for R11, for which the planning meeting is happening today.

**Comment by corinagum** [comment]
Quick update: I'm still investigating the cause of this issue. My initial assumption was that it would be a sample fix, but that is incorrect. This most likely won't make the R11 release.

Note that this also affects the user highlighting sample.

**Comment by nathanlindorff** [comment]
@corinagum It may actually end up being a sample/documentation change. A colleague was having the same issue on a similar project and wasn't keen on dropping back a version. After a bit of digging into the webchat code, and looking through some other samples, It appears that the middleware/renderer for StackedLayout has changed from requiring one argument (children) to two (renderAttachment, props).

As a result, spreading the children seems to have fixed the issue in my colleague's instance.

eg

```
export const myActivityMiddleware = () => (next: any) => (card: any) => {
    if (card.activity.from.role === 'bot') {
        return (children: any) => (
            <MyActivityDecorator>
                {next(card)(children)}
            </MyActivityDecorator>
        );
    }
    return next(card);
};
```

Causes the issue, but 

```
export const myActivityMiddleware = () => (next: any) => (card: any) => {
    if (card.activity.from.role === 'bot') {
        return (...children: any) => (
            <MyActivityDecorator>
                {next(card)(...children)}
            </MyActivityDecorator>
        );
    }
    return next(card);
};
```
Appears to resolve the issue.

I'm not familiar enough with the internals of the framework to be 100% sure thats the issue. I've also not had a chance to try it in the code I reported the issue on, but hopefully that helps.

**Comment by corinagum** [comment]
@nathanlindorff thanks for the info! 

You're right, since my last update I figured out that this **is** a quick sample update from when our middleware format changed. I definitely plan on getting the fix in R12. In the meantime, check out the middleware design change for more info: https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md#breaking-changes-1 Hope that helps you out, and sorry I haven't gotten the fix in yet.
