### ISSUE TITLE
Unable to generate token from secret, throws a 403 forbidden error

### ISSUE THREAD

**Issue by naser-baig-au4** [microsoft/BotFramework-WebChat#3474]
Hi there,

I am trying to connect my React webchat client to my local bot and as per [this tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0), I made a GET request in this format:

````
requestGET https://webchat.botframework.com/api/tokens
Authorization: BotConnector YOUR_SECRET_HERE
````
It doesn't process my request and throws a 403 forbidden error. The secret I am supplying is from WebChat channel. I also tried DirectLine channel secret (even added my localhost in the trusted origins) but it's the same story.

The bot works fine in the emulator though and I am able to get a token when I make a request from postman.

Any help would really be appreciated.

Thank you

**Comment by stevkan** [comment]
@naser-baig-au4,

The `api/tokens` endpoint is a [Direct Line API 1.1](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-1-1-authentication?view=azure-bot-service-4.0) protocol which returns a string. 

As such, I believe you are errantly passing in the string version of the token, including the surrounding quotes. Use `JSON.parse()` on the token to get a correctly formatted token. Doing so should allow you to pass in and successfully create the Direct Line object and, thus, connect Web Chat to your bot.

That being said, the recommended protocol to use is [Direct Line API 3.0](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0) which will return the token as a JSON value (i.e. containing no surrounding quotes).

I'm closing this as resolved. If the issue persists, please feel free to re-open.

**Comment by naser-baig-au4** [comment]
> As such, I believe you are errantly passing in the string version of the token, including the surrounding quotes. Use `JSON.parse()` on the token to get a correctly formatted token. 

Hi @stevkan,

Thank you for the reply. I don't have any issues parsing the token. I am unable to fetch the resource for the token as I am greeted with a 403 forbidden error.

> That being said, the recommended protocol to use is [Direct Line API 3.0](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0) which will return the token as a JSON value (i.e. containing no surrounding quotes).

Also tried with the 3.0 protocol and it's the same story.

Perhaps this screenshot might help:

![Screenshot 2020-09-12 12 39 36](https://user-images.githubusercontent.com/56202963/92989906-5648d500-f4f5-11ea-9a8e-cd4a538b6d36.png)

**Comment by naser-baig-au4** [comment]
Could somebody please open this issue again?

**Comment by stevkan** [comment]
@naser-baig-au4, can you verify the actual value of the token being passed in either by console logging, setting break points, or some other? My concern is that, while the steps you are performing are correct the value, itself, may still be formatted wrong.

**Comment by naser-baig-au4** [comment]
> 
> 
> @naser-baig-au4, can you verify the actual value of the token being passed in either by console logging, setting break points, or some other? My concern is that, while the steps you are performing are correct the value, itself, may still be formatted wrong.

@stevkan, please check the screenshot above. I am unable to generate the token in the first place, let alone properly pass it to webchat via directline.

**Comment by stevkan** [comment]
@naser-baig-au4, apologies. You stated you "don't have any issues parsing the token". I took that to mean you were actually receiving one. I'll take another peak at the process and get back to you.

**Comment by naser-baig-au4** [comment]
> 
> 
> @naser-baig-au4, apologies. You stated you "don't have any issues parsing the token". I took that to mean you were actually receiving one. I'll take another peak at the process and get back to you.

No worries. Please take your time :)

**Comment by stevkan** [comment]
@naser-baig-au4, I'm still not encountering the same issue you are. Could you post you web chat code (hiding any secrets or keys) so I can attempt a repro?

**Comment by naser-baig-au4** [comment]
> 
> 
> @naser-baig-au4, I'm still not encountering the same issue you are. Could you post you web chat code (hiding any secrets or keys) so I can attempt a repro?

Hey @stevkan,

I have used [this sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat) as a starting point and just made the change in the URL to the directline URL mentioned above. Everything else is the same.

I have an update for you. I was able to connect to my bot locally using [offline directline](https://www.npmjs.com/package/offline-directline). Is it possible that I am getting this error because I have just deployed my bot and not published it yet?

**Comment by stevkan** [comment]
@naser-baig-au4, thank you for your patience.

> I have an update for you. I was able to connect to my bot locally using offline directline. Is it possible that I am getting this error because I have just deployed my bot and not published it yet?

No, you can run a bot locally and connect to outside services as long as you use a service like ngrok and also have a bot registration created on Azure. Ngrok, and other similar options, provide a tunnel between your local host machine and your bot registration / service running on Azure. 

Do you have a bot registered on Azure, as described in the steps shown in [this doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0)?

Also, did you ever try the Direct Line API 3.0 set up, referenced previously?

**Comment by stevkan** [comment]
Closing due to a lack of activity. If the issue persists or you have new information to provide, please feel free to reopen.
