### ISSUE TITLE
BotFramework-WebChat - Customize Suggestion Buttons user experience

### ISSUE THREAD

**Issue by anandk95** [microsoft/BotFramework-WebChat#3477]
I would like to have a customizable suggestion butons. The Suggested buttons appear scroll-able, but i would like to have them stacked over one another, because during scrolling person may accidentally click on buttons, which is a design flaw. so, can you please help me with this situation or point me in the direction where i can look for answers.
 
<img width="288" alt="Capture" src="https://user-images.githubusercontent.com/37825454/93049101-f16cb680-f67d-11ea-8b25-5c28e7f325ee.PNG">

**Comment by tdurnford** [comment]
@anandk95 You should be able to set the `suggestedActionLayout` to `'stacked'` in the style options. Please take a look at the [Branding Web Chat Styling]() sample for help using the style options.

### Web Chat v4 
```js
const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
const { token } = await res.json();
const styleOptions = {
    suggestedActionLayout: 'stacked'
};

window.WebChat.renderWebChat(
    {
        directLine: window.WebChat.createDirectLine({ token }),
        styleOptions
    },
    document.getElementById('webchat')
);
```

### Additional Context

https://github.com/microsoft/BotFramework-WebChat/blob/1559ab52158e1b3d0e523d1c2b8b66c462e0494c/packages/component/src/Styles/defaultStyleOptions.js#L115

**Comment by anandk95** [comment]
Thank you, It was very much helpful.
