### ISSUE TITLE
Unable to generate token from secret, throws a 403 forbidden error

### ISSUE THREAD

**Issue by naser-baig-au4** [microsoft/BotFramework-WebChat#3478]
This is a follow up issue for [this previous issue](https://github.com/microsoft/BotFramework-WebChat/issues/3474) that was closed abruptly.

> As such, I believe you are errantly passing in the string version of the token, including the surrounding quotes. Use `JSON.parse()` on the token to get a correctly formatted token. 

Hi @stevkan,

Thank you for the reply. I don't have any issues parsing the token. I am unable to fetch the resource for the token as I am greeted with a 403 forbidden error.

> That being said, the recommended protocol to use is [Direct Line API 3.0](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0) which will return the token as a JSON value (i.e. containing no surrounding quotes).

Also tried with the 3.0 protocol and it's the same story.

Perhaps this screenshot might help:

![Screenshot 2020-09-12 12 39 36](https://user-images.githubusercontent.com/56202963/92989906-5648d500-f4f5-11ea-9a8e-cd4a538b6d36.png)

_Originally posted by @naser-baig-au4 in https://github.com/microsoft/BotFramework-WebChat/issues/3474#issuecomment-691431769_

**Comment by stevkan** [comment]
Hi @naser-baig-au4, I am going to close this in favor of re-opening the [original issue](https://github.com/microsoft/BotFramework-WebChat/issues/3474) you filed in order to better maintain the conversation's continuity.
