### ISSUE TITLE
a.minimizable-web-chat.  README.md not consistent with source code

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#3482]
handleFetchToken  in the README.md is showing an effort to implement reconnecting to an existing conversation. It is not finalized however. The actual sourcecode lacks this support completely.

I would really appreciate a working sample that shows how to reconnect to an existing conversation (leveraging local or sessionStorage) since implementing it has shown to be really hard  (for me that is).

**Comment by corinagum** [comment]
To reduce complication, the sample is not intended to provide reconnection code, and instead is provided in a separate article, linked in Further Reading.

I'm not sure what you mean about how the readme is not consistent with the source code. We address the topic here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat#reconnecting-to-a-conversation Could you elaborate?

**Comment by HesselWellema** [comment]
Annexample. This part in the README.md is nog in the code:

f (conversationId) {
      const res = await fetch(`https://directline.botframework.com/v3/directline/conversations/${conversationId}`, {
        method: 'GET',
        headers: {
          'Authorization':
        }
      })
    }
