### ISSUE TITLE
Consider supporting AdaptiveCards with schema 1.3

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3487]
## Feature Request
Currently WebChat does not support AdaptiveCards with schema 1.3

Consider supporting AdaptiveCards with schema 1.3. AdaptiveCards have some updates to Input.Text in [schema ](https://adaptivecards.io/explorer/Input.Text.html)1.3 that provide input validation on the client side (errorMessage, isRequired, label etc). I am sure many are waiting for this feature to come to WebChat.

**Comment by tsuwandy** [comment]
@corinagum, is this something you could take a look at?

**Comment by tsuwandy** [comment]
@arman-g, this will be handled in the upcoming release.  Thanks!

**Comment by corinagum** [comment]
We are placing this on our backlog due to time constraints for R11.

**Comment by corinagum** [comment]
@Jeffders @p-nagpal FYI.

**Comment by compulim** [comment]
When implementing this one, fix `useParseAdaptiveCardJSON` by finding/using a newer signature to parse Adaptive Cards.

Inside `useParseAdaptiveCardJSON.js`:

```js
const card = new AdaptiveCard();
const errors = [];

// TODO: [P3] #3487 Move from "onParseError" to "card.parse(json, errors)"
AdaptiveCard.onParseError = error => errors.push(error);

card.parse(content);
```

**Comment by sam-sam-med** [comment]
for adaptive card version 1.3 support, when will this be made available to the community?  thank you.

**Comment by VMey** [comment]
@corinagum can we get an update on when this will be available?

**Comment by corinagum** [comment]
@VMey Web Chat's action item of bumping AC is completed, (PR #3630) with the intent of releasing it for our R12 milestone (approx. March 8th). However, this issue (3487) is intended to track the Bot Service changes that would need to be made (not part of our open-source content). 

I am communicating with the team members who are heading this part of the update and will add a comment here when there is more information available. Thanks everyone for your patience; I know this is an exciting bump!

@arturl @p-nagpal FYI.

**Comment by corinagum** [comment]
Assigned to @Kaiqb for visibility, tracking with the service team

**Comment by corinagum** [comment]
Closing this as resolved. The service has begun 1.3 schema support rollout, and should be available worldwide within a week or so. Adaptive Cards 2.x and the 1.3 schema will be supported in our next release, March 8th.
