### ISSUE TITLE
Assistive technologies start reading Bot message with "Bot undefined said"

### ISSUE THREAD

**Issue by agriniex** [microsoft/BotFramework-WebChat#3489]
When using assistive technologies, announcer reads bot message as "Bot _undefined_ said: {message}". Previously this was just "Bot said:  {message}".

It seems like this issue was introduced after 4.9.2 version of botframework-webchat. 

Reproduced on 
- Chrome using NVDA screen reader on Windows
- Chrome using VoiceOver screen reader on MacOS 

In React example demo: 
https://microsoft.github.io/BotFramework-WebChat/01.getting-started/e.host-with-react/

**Comment by corinagum** [comment]
Can you update to 4.10.1 and see if the problem persists?

**Comment by corinagum** [comment]
I'm getting the `undefined` as explained above. I'll investigate further.

**Comment by agriniex** [comment]
I was able to reproduce this issue with version 4.10.0 of botframework-webchat.
