### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by gordonthompson** [Microsoft/BotFramework-WebChat#349]
The sample code in the ReadMe is wrong.

     <script src="https://unpkg.com/botframework-webchat/botchat.js"/>

should be

      <script src="https://unpkg.com/botframework-webchat/botchat.js"></script>

(only foxed me for an hour that one!) ;-)

**Comment by billba** [comment]
Fixed as part of #348, thanks! And sorry for the lost hour.

**Comment by gordonthompson** [comment]
Not your fault it was an hour, its been a loooong day 😅

Tah

On 24 Feb 2017 8:47 pm, "Bill Barnes" <notifications@github.com> wrote:

Fixed as part of #348
<https://github.com/Microsoft/BotFramework-WebChat/pull/348>, thanks! And
sorry for the lost hour.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BotFramework-WebChat/issues/349#issuecomment-282400350>,
or mute the thread
