### ISSUE TITLE
Adaptive cards input focus and Webchat scrolling issue (IE11) - Potentially related to #3463

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3492]
## Screenshot
![IMG1](https://user-images.githubusercontent.com/22778273/93937547-d385fe00-fcdc-11ea-8555-95763751228f.png)

## Version

WebChat CDN 4.10.1
IE 11
Firefox 80.1.1

## Describe the bug

Setting the focus at the first input box of an adaptive card does not scroll the chat conversation all the way to the bottom. It stops at the focused input box. This does not happen in Chrome and the new Edge browsers.

## Steps to reproduce

1. Render an adaptive card with an input box in a WebChat.
2. On the client, add code to focus the input box.
3. Run the WebChat and go to the input box.
4. See that WebChat did not scroll all the way to the end.

## Expected behavior

WebChat should scroll all the way to the bottom as it does in Chrome and new Edge browsers.

## Client Code
```
    if (action.type === 'WEB_CHAT/SET_SUGGESTED_ACTIONS') {
      const query = '*div.ac-adaptiveCard:not(.disabled)';
      const acList = $(query);
      if (acList.length > 0) {
        const ac = acList[acList.length - 1];
        if (ac !== this.adaptiveCard) {
          if (this.adaptiveCard != undefined) {
            this.changeAdaptiveCardStatus(false);
          }
          this.adaptiveCard = ac;
          const textInputs = $(ac).find('.ac-textInput').first();
          if (textInputs.length > 0) {
            textInputs[0].focus();
          }
        }
      }
    }
```

**Comment by tdurnford** [comment]
@compulim Can you take a look at this?

**Comment by ninggao** [comment]
@compulim Can you take a look at this please?

**Comment by lzc850612** [comment]
@arman-g the team is prioritizing on this item.

**Comment by corinagum** [comment]
1. Does this need design input? Possible to fix in IE11?
2. Potentially related to #3463

**Comment by cwhitten** [comment]
We'd like someone from the support engineering staff to investigate browser behavior for this issue

**Comment by stevkan** [comment]
@arman-g, I'm unable to repro the issue in either Chrome, FireFox, or IE. Initially, it wasn't working until I realized you appear to be using jQuery. When I included the jQuery CDN script, it started working. The only exception is in Chrome / FireFox, neither appreciated `this.adaptiveCard` being used. I switched it to `let adaptiveCard = {}` (and commented out `this.changeAdaptiveCard(false)`, as I don't have the code for it) and they too started working.

Presumably, IE is suppressing some of the errors, but is still able to run the code as it neither complains about `this.adaptiveCard` nor `this.changeAdaptiveCard(false)`.

Can you double check you are including the jQuery CDN?

**IE screen shot:**
![adaptiveCardInputFocus](https://user-images.githubusercontent.com/18403946/109059303-f5731a80-7698-11eb-8d7c-7b6049e4ef76.gif)

**Comment by arman-g** [comment]
Hi @stevkan I am not sure if you fully understand the issue I am talking in this tread so let me try to explain it again. The issue is not about having able to focus the input box (I am able to put the focus on the input box) but in some browsers (IE and Firefox) the adaptive card is not fully visible (not scrolled to the bottom). Please see the image provided below (Firefox - left, Edge - right).
The code is the same for both browsers, on Firefox the addaptive card is not fully scrolled down (after putting focus on the input box) so that the entire adaptive card can be fully seen. On the other hand the issue is no present on the Edge browser.
You can see the issue [here ](https://lascchatbotclientcicd.azurewebsites.net/traffic)using Firefox and chromium based browsers side by side.

![IMG3](https://user-images.githubusercontent.com/22778273/109071435-93baac80-76a8-11eb-8b54-7221a7e9d6d0.png)

**Comment by stevkan** [comment]
Thank you for your patience while I continued to look into this more. And, yes, I wasn't fully understanding the issue. Your clarification is appreciated. I was able to repro the issue and I believe it is tied to two lines of code, both handling focus:

Yours:
`const textInputs = $( ac ).find( '.ac-textInput' ).first();`

Web Chat's:
`document.querySelector('#webchat > *').focus();`

As an activity with an adaptive card comes thru, both are competing for applying focus once it renders. Sometimes your code is applied first and other times it is applied second which is resulting in the transcript window either scrolling all the way down or stopping shortly after the card's input field. The simple solution is to wrap your code in a time out with a delay of about 300 ms. You can adjust the delay as needed, but keep in mind that reducing to ~50 ms or less and you will start to experience the issue again. Going longer than ~500 ms and the card might appear to move on its own separate from the other scroll action.

```js
if ( action.type === 'WEB_CHAT/SET_SUGGESTED_ACTIONS' ) {
  setTimeout(() => {
    const query = '*div.ac-adaptiveCard:not(.disabled)';
    const acList = $( query );
    let adaptiveCard = {};;
    if ( acList.length > 0 ) {
      const ac = acList[ acList.length - 1 ];
      if ( ac !== adaptiveCard ) {
        if ( adaptiveCard != undefined ) {
          // this.changeAdaptiveCardStatus( false );
        }
        adaptiveCard = ac;
        const textInputs = $( ac ).find( '.ac-textInput' ).first();
        if ( textInputs.length > 0 ) {
          textInputs[ 0 ].focus();
        }
      }
    }
  }, 400);
}
```

Testing resolved the issue when run in the different browsers.

**Comment by corinagum** [comment]
Closing as resolved. :)
