### ISSUE TITLE
Missing: need to set 'username' in 'createDirectLineSpeechAdapters' function

### ISSUE THREAD

**Issue by nfreear** [microsoft/BotFramework-WebChat#3495]
## Screenshots

(_n/a_)

## Version

 * WebChat version __4.10.1__, via CDN (_and local copy of compiled JS_).

```
https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js
```

## Steps to reproduce

  1. Call the [`createDirectLineSpeechAdapters()` as documented](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/DIRECT_LINE_SPEECH.md#render-web-chat-using-direct-line-speech-adapters);
  2. See that the `userID` and `username` set in `renderWebChat()` are now being ignored;
  3. Note that it's possible to set `userID` and `username` in the [`create()` function](https://github.com/microsoft/BotFramework-WebChat/blob/v4.10.1/packages/directlinespeech/src/createAdapters.js#L30-L31);
  4. Observe that though the `userID` is present and used in message payloads, the `username` is not;
  5. See the warning: ['_Custom "userId" and "username" are currently not supported and are ignored._'](https://github.com/microsoft/BotFramework-WebChat/blob/v4.10.1/packages/directlinespeech/src/createAdapters.js#L99-L103) (only half correct, [the `userID` is supported](https://github.com/microsoft/BotFramework-WebChat/blob/v4.10.1/packages/directlinespeech/src/createAdapters.js#L133-L134));
  6. Note that [`Conversation_From_Id` is present in the speech SDK](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/v1.13.1/src/sdk/PropertyId.ts#L308), but `Conversation_From_Name` or equivalent is not.

## Expected behavior

If `createDirectLineSpeechAdapters` and a Direct Line Speech channel for a Bot is now the preferred way of integrating server-based speech synthesis and recognition, then it needs to support the setting of both the `userID` and `username` properties, to provide parity with those properties set via `renderWebChat()`

## Additional context

We're developing a Web-based Chatbot for the Microsoft-funded _AI for accessibility_ "_ADMINS_" project.

Thanks,

Nick

_The Open University, UK._

[Bug]

**Comment by tdurnford** [comment]
@stevkan Can you repro this?

**Comment by stevkan** [comment]
@nfreear, attempting a repro. Will have a response shortly.

**Comment by stevkan** [comment]
@nfreear, I’m still repro’ing and will have a response later today.

For clarity, per your Expected Behavior comments, using Direct Line Speech isn’t necessarily the preferred or recommended method. Rather, it is the recommended method for developers that don’t require making many speech customizations and would benefit from a largely simplified implementation.

**Comment by stevkan** [comment]
@nfreear, I have been unable to repro this issue. Can you provide more details of the specific code you are using?

**Comment by stevkan** [comment]
@nfreear, thank you for your patience. I'm still trying to determine what is intended behavior or not. I hope to have a response to you within the next day or two.

**Comment by stevkan** [comment]
@nfreear, as you noted, `userID` is used by DL Speech internally by assigning `Conversation_From_Id`, however there is no matching/available property in DL Speech that could be applied to `username`. Because properties are propagated by DL Speech when the adapter is created, there is no way to include `username` as a property in `renderWebChat()`.

**Comment by stevkan** [comment]
@nfreear, additionally, though `userID` and `username` exist in the `create()` method of createAdapter.js, they exist primarily to catch either properties being passed into the adapter when using `createDirectLineSpeechAdapters()`. Hence, the console message stating 'Custom "userId" and "username" are currently not supported and are ignored.'

That being said, `userID` is technically accessible allowing someone to overwrite the id that is assigned by DL Speech. However, this isn't the intent as it should be inaccessible; this should be considered a bug in Web Chat.

With regards to making either properties available in `renderWebChat()`, there already is a "TODO" related to this (reference [here](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/directlinespeech/src/DirectLineSpeech.js#L72)). I have created an issue in the Web Chat repo, #3538, for better tracking that you can reference.

Please feel free to add your support for the feature request as that will help drive development.
