### ISSUE TITLE
Web chat event are not working after page refresh

### ISSUE THREAD

**Issue by srinutamada** [microsoft/BotFramework-WebChat#3496]
I am using web chat and implemented chat persistence by doing DOM manipulation.

I am able to show previous history on page refresh or navigating the different pages. But if user click on events like button which were present in the history then those event are not working. Even I extended my logic to trigger click events and event then send message is not working.

I see no errors. So, let me know if my approach is right or not and if there is any way to implement chat persistent.

Note: Our approach is working fine in .NET web application but the same is not in Salesforce.

**Comment by tdurnford** [comment]
@stevkan Can you repro this?

**Comment by srinutamada** [comment]
The issue is resolved. I removed DOM manipulation from the logic and used DirectLine properties by setting 
conversationId: <previous conversation id> and DirectLine:false.

I tested and it worked like a charm.
