### ISSUE TITLE
Support "typing" activity

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#35]
Needs some speccing.

**Comment by billba** [comment]
In lieu of a good test bot, we temporarily show the typing activity whenever a text message ends in "//typing".

**Comment by billba** [comment]
Right now we just show TYPING. Can you whip up an animated GIF instead?

**Comment by billba** [comment]
We only get these via WebSocket so we can put this off until after the next milestone.

**Comment by billba** [comment]
Now that we have WebSocket support, we should make this look better.

**Comment by billba** [comment]
Pretty!

**Comment by danmarshall** [comment]
Thanks to @jecristi
