### ISSUE TITLE
Problem creating conversation

### ISSUE THREAD

**Issue by mohit-jcc** [Microsoft/BotFramework-WebChat#350]
I've hosted a node bot on Azure and when using the webchat channel interface it works perfectly fine. 
However when I'm using the directline-webchat, the chat interface appears but there is no response from the bot. This is the error shown in the console : 
`POST https://directline.botframework.com/v3/directline/conversations 403 (Forbidden)`
How do I interpret this error ?

**Comment by danmarshall** [comment]
How are you generating your token?

**Comment by mohit-jcc** [comment]
This piece of code does the work : 
```

 <script>
            var params = {};
            location
                .search
                .substring(1)
                .split("&")
                .forEach(function (pair) {
                    var p = pair.split("=");
                    params[p[0]] = decodeURIComponent(p[1]);
                });

            var user = {
                id: params.userid || 'userid',
                name: params.username || 'You',
                token: params.usertoken || null
            };
            
            var bot = {
                id: params['botid'] || 'botid',
                name: params["botname"] || 'botname'
            };


            BotChat.App({
                directLine: {
                    secret: params['s'],
                    token: params['t'],
                    domain: params['domain'],
                    webSocket: params['webSocket']
                },
                user: user,
                bot: bot
            }, document.getElementById("BotChatGoesHere"));
        </script>
```

**Comment by danmarshall** [comment]
Sorry, I mean how are you generating the token itself?

**Comment by mohit-jcc** [comment]
@danmarshall I am not using any token, just loading this html with the directline secret s as a url param.

**Comment by billba** [comment]
@mohit-jcc what is your status on this? The errors you are getting indicate a problem with your credentials.

**Comment by mohit-jcc** [comment]
@billba I dont think came across any cred/token other than the directline secret im using currently.  Could you please elaborate?

**Comment by billba** [comment]
When you register a Direct Line channel you get a secret. A secret is a long-lived token. You can optionally generate a short-lived token from that secret. Either a secret or a token can authenticate a bot session. If you provide a token, then WebChat will fetch new tokens every 15 minutes to make sure they don't expire.

A 403 generally indicates an expired token.

It's hard for us to debug your problem. You can test to see if your secret is valid using [botchattest](https://botchattest.herokuapp.com). If it works there, you most likely have a problem with your WebChat code. If it doesn't, you most likely have a problem with your secret.

**Comment by billba** [comment]
Closing due to lack of response on the part of OP.

**Comment by gavandivya** [comment]
Is this problem solved? I need urgent help. Facing the same problem
