### ISSUE TITLE
Typing indicator is out of its place on IE

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3503]
## Screenshots

![IMG2](https://user-images.githubusercontent.com/22778273/94197687-fba36780-fe6a-11ea-9e5c-9152a9c429bd.png)

## Version

WebChat CDN v4.10.1
IE 11

## Describe the bug

When WebChat action buttons has their text set to wrap in IE the typing indicator shows out op its place (please see the image above).

## Steps to reproduce

1. In WebChat, set button text to wrap.
1. Run WebChat in IE and resize it so the button text wraps.
1. Click on the buttons and perceed a few dialogs.
1. See the typing indicator out of its place.

## Expected behavior

The typing indicator always should appear at the bottom left corner of the WebChat.

## CSS

```css
// Allow button text to wrap
button > div:first-child {
  text-overflow: inherit !important;
  white-space: normal !important;
}
```

## JS
```js
this.directLine = this.webChat.createDirectLine({
          secret: this.settings.webChatSecret,
          webSocket: true// window.navigator.userAgent.indexOf('Trident/') === -1 // False if IE
});
```

**Comment by arman-g** [comment]
@corinagum this is not a question but a bug report. I posted an image that shows clearly what the issue is. Not sure why you would remove the "Bug" label, any explanation how is this not a bug but a question?

**Comment by corinagum** [comment]
I was unable to repro on IE11 with the CSS and repro steps you provided.

**Comment by arman-g** [comment]
@corinagum I am not sure what you have tried but I am providing you with the url below so you can observe the behavior.

1. Open the url in IE 11
2. Resize the browser so the button text starts to wrap.
3. Click on buttons to iterate through dialogs.
4. Observe the typing indicator location.

https://lascchatbotclientcicd.azurewebsites.net/lacc

Please let me know if you see the issue now.

**Comment by stevkan** [comment]
Hi @arman-g, I am able to repro the issue. Testing the different versions, it looks like it was introduced with v4.8.0. Can you share the code you are using for sending the typing activity and is this in JS or C#? I'm getting slightly different results when I switch between sending a typing activity vs. using the `ShowTypingMiddleware()` middleware package.

Also, when inspecting the HTML for the link you provided, it looks like it loads both the `webchat-es5.js` and `webchat.js` packages. Is there a reason for this?

**Comment by arman-g** [comment]
Hi @stevkan, the code for sending typing activity is in C# using Microsoft.Bot.Builder v4.10.3 Nuget package.
```
await turnContext.SendActivityAsync(Activity.CreateTypingActivity(), cancellationToken);
```

I am using webchat-es5.js and webchat.js to support IE and all other modern browsers each browser selecting the one they need. I now I can have only es5 version od webchat.
I just did a test and commented out the webchat.js leaving only webchat-es5.js and the issue is still there.

I remember that the typing indicator was moved out from send box around v4.8.0. This change should be causing the problem. Moving out was a right decision since hiding the send box was hiding the typing indicator too. But now it introduced another problem I think.

**Comment by stevkan** [comment]
@arman-g, thank you for your patience while I continue to look into this. I'm currently testing to see if there is a workaround for this or if a correction to the SDK is the only solution. Please let me know if you have any questions in the mean time.

**Comment by stevkan** [comment]
@arman-g, updating to let you know that I am still looking into a workaround. I have been discussing this with a colleague and am waiting on a response to a couple questions.

**Comment by stevkan** [comment]
@arman-g, thank you for your patience. I'm still researching a workaround. It's not looking promising at this moment, but I still have a couple ideas to try out. I will keep you updated.

**Comment by stevkan** [comment]
@arman-g, I was able to come up with a workaround that appears to work when testing. If you add the below to the CSS for the page, it will force the typing indicator to always display in the bottom left corner. Setting the `bottom` value to `15px` places it about in line with the chat bubble's status element. Naturally, you can adjust to fit your needs.

```css
.webchat__typingIndicator {
  position: absolute;
  bottom: 15px;
}
```

![positionTypingIndicator-IE](https://user-images.githubusercontent.com/18403946/98293645-86e04480-1f63-11eb-9e6e-67d94a05325d.gif)

**Comment by arman-g** [comment]
Hi @stevkan, thank you for the workaround. I definitely will give this a try. Will this be addressed in the future releases?

**Comment by stevkan** [comment]
There is no ETA at this time. You can track what items have been added or updated via the [change log](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md) as new releases occur.

Closing this as resolved. If the issue persists, please feel free to re-open.
