### ISSUE TITLE
Optimize a.minimizable-web-chat sample

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#3509]
With user experience metrics like Largest Contentful Paint (LCP) becoming a ranking factor for SEO the size of the webchat bundle is becoming important for my customers that rely on high rankings in search engines like Bing and Google.

The minimizable web chat sample is a great starting point for most use cases but from a performance perspective it seems not the best approach. After building, the vendor chunk is large and (according to  Lighthouse) blocking the primary thread.

I tried to lazy-load the MinimizableWebChat (in app.js) and the WebChat component (in minimizable webchat) but the impact on performance is minimal.  

I also tried to first paint a dumb button and replace the button with the minimizable webchat component onclick. This has great effects on performance but feels like a workaround.

is there a way to rewrite\design this example with a better performance in mind?

Currently the bundle sizes of the sample are (after gzip): 

-   700.17 KB (-37.42 KB)  build\static\js\2.e9e19104.chunk.js
-   39.86 KB               build\static\js\4.26c74a4c.chunk.js
-   3.31 KB (+3.14 KB)     build\static\css\3.74a6da16.chunk.css
-   1.57 KB (+51 B)        build\static\js\runtime-main.e2b8f082.js
-   1.19 KB (+712 B)       build\static\js\3.87b251f5.chunk.js
-   613 B (-912 B)         build\static\js\main.5a5dc9f1.chunk.js
-   507 B                  build\static\js\5.6e35fd8c.chunk.js
-   302 B (-3.19 KB)       build\static\css\main.8bb6d794.chunk.css
-   173 B                  build\static\css\5.768c25ae.chunk.css

Wrt the largest bundle, almost 45% seems to remain unused.

**Comment by ninggao** [comment]
@compulim Can you take a look at this please?

**Comment by HesselWellema** [comment]
I concluded this is more a packaging issue and not related to this sample or webchat itself. Any suggestions wrt tree-shaking and webpack configuration that will help to minimize these bundles are more than welcome.
