### ISSUE TITLE
Problem getting activities

### ISSUE THREAD

**Issue by mohit-jcc** [Microsoft/BotFramework-WebChat#351]
I've hosted a node bot on Azure and when using the webchat channel interface it works perfectly fine. 
However when I'm using the directline-webchat, the chat interface appears but there is no response from the bot. This is the error shown in the console : 
`GET https://directline.botframework.com/v3/directline/conversations/KiS5dbsMbj5FEa3u7wgkSc/activities?watermark=1 net::ERR_NETWORK_CHANGED`
How do I interpret this error ?

**Comment by billba** [comment]
Closing as not a WebChat bug.
