### ISSUE TITLE
can be add a vitual keyboard to write in the bot 

### ISSUE THREAD

**Issue by prakanshurockss** [microsoft/BotFramework-WebChat#3510]
## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by prakanshurockss** [comment]
virtual keyboard

**Comment by ninggao** [comment]
@prakanshurockss Could you please describe more on the virtual keyboard scenarios that you want? In order to consider this as a new feature request, we would need more details.

**Comment by cwhitten** [comment]
@prakanshurockss we'll be closing this as we haven't heard from you. Please create a new ticket if you are still having issues.
