### ISSUE TITLE
Speech  Refresh token issue

### ISSUE THREAD

**Issue by SanjuJayakumarNair** [microsoft/BotFramework-WebChat#3518]
I Have implemented the speech using the sample provided  "https://microsoft.github.io/BotFramework-WebChat/03.speech/b.cognitive-speech-services-js/". and updated the credentials  like below 
   credentials: {

                             authorizationToken: SpeechToken,

                             region: '',   // provided the region

                             token: SpeechToken
 
                        } 
Still the refresh token is not working as expected. could you provide any links for reference.

**Comment by stevkan** [comment]
@SanjuJayakumarNair, did you set up your Web Chat instance like it is demonstrated in the [03.speech/b.cognitive-speech-services-js](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/b.cognitive-speech-services-js#completed-code) doc?

The `authorizationToken` and `region` properties are passed into `createCognitiveServicesSpeechServicesPonyfillFactory()` which is used for creating the `webSpeechPonyfillFactory` object.

Both the `token` and `webSpeechPonyfillFactory` properties are then passed into `window.WebChat.renderWebChat()`.

**Comment by stevkan** [comment]
Closing due to a lack of activity. If the issue persists or you have additional questions or details to provide, please feel free to reopen.
