### ISSUE TITLE
Is CONTRIBUTING.md still up to date?

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/BotFramework-WebChat#3529]
Tried following the steps but ran into some errors during npm start:
```
botframework-webchat: [webpack] ERROR in ../component/lib/Localization/getLocaleString.js
botframework-webchat: [webpack] Module not found: Error: Can't resolve '../Utils/PrecompiledGlobalize' in '<mypath>\BotFramework-WebChat\packages\component\lib\Localization'
botframework-webchat: [webpack]  @ ../component/lib/Localization/getLocaleString.js 8:51-91
botframework-webchat: [webpack]  @ ../component/lib/Localization/Localize.js
botframework-webchat: [webpack]  @ ../component/lib/index.js
botframework-webchat: [webpack]  @ ./lib/index-minimal.js
botframework-webchat: [webpack]
botframework-webchat: [webpack] ERROR in ../component/lib/Composer.js
botframework-webchat: [webpack] Module not found: Error: Can't resolve './Utils/PrecompiledGlobalize' in '<mypath>\BotFramework-WebChat\packages\component\lib'
botframework-webchat: [webpack]  @ ../component/lib/Composer.js 48:51-90
botframework-webchat: [webpack]  @ ../component/lib/index.js
botframework-webchat: [webpack]  @ ./lib/index-minimal.js
```
Is this a bug or is this something on my end?

I noticed the build pipeline is red on the current master.
Are this and that the same issue?

## Screenshots
N.A.
## Version
0c21c2df21246877bb58e4c80c1deee0fb4db6ab
## Describe the bug
`npm start` throws errors
## Steps to reproduce
1. Fork and clone repo
2. Run `npm ci`
3. Run `npm run bootstrap`
4. Run `npm start`
## Expected behavior
Can go to `localhost:5001/simple.html` and see a test.
## Additional context

[Bug]

**Comment by corinagum** [comment]
Looks like something on your end. I just did a fresh clone and ran into no problems. @stevkan can you support?

**Comment by stevkan** [comment]
@felixvanleeuwen, I can't confirm your specific error but when I follow those specific steps shown above, I get a whole host of errors. However, if I run the following steps, having added `npm run build`, I still get a number of warnings, but the SDK does appear to build and run. Serving `webchat.js` from "http://localhost:5000" seemingly works without error.

Can you try these steps, as a possible workaround, and let me know if it works?

1. Clone a fresh copy of the repo
2. Run `npm install`
3. Run `npm ci`
4. Run `npm run bootstrap`
5. Run `npm run build`
6. Run `npm start`

@corinagum, as mentioned above, I'm getting a host of errors when I follow the "Steps to reproduce". Attached are some of the screenshots I was able to grab before the output ran off the console. Thoughts?

![image](https://user-images.githubusercontent.com/18403946/95636020-e9b4ed80-0a42-11eb-8400-f79f735de364.png)
![image](https://user-images.githubusercontent.com/18403946/95635934-ad818d00-0a42-11eb-80a2-4258be66deb3.png)
![image](https://user-images.githubusercontent.com/18403946/95635939-b1151400-0a42-11eb-82da-9a22497cb4e4.png)
![image](https://user-images.githubusercontent.com/18403946/95635878-84f99300-0a42-11eb-9b1a-d178f77f6718.png)

**Comment by felixvanleeuwen** [comment]
@stevkan I tried the extra commands and it is working 👍

**Comment by compulim** [comment]
Looks like it's working.
