### ISSUE TITLE
Continue previous conversation

### ISSUE THREAD

**Issue by baconstrudel** [Microsoft/BotFramework-WebChat#353]
Is there an easy way to reconnect to an existing conversation?

**Comment by TheTobias** [comment]
Assuming the changes to DirectLineJS are made that would still mean one would have to store the conversation history and insert the history of the conversation before connecting back to the conversation to receive new messages.

**Comment by billba** [comment]
@TheTobias Yes. Direct Line is not meant to be a full-fledged messaging system like e.g. Skype, Slack, or Facebook Messenger. It does not have an identity system nor message storage. It is just a simple protocol for exchanging messages with a bot. The more you want your client to work like a full-fledged messaging system, the more work you will have to do yourself.

**Comment by sgellock** [comment]
The team doesn't believe it will address this issue at this time.
