### ISSUE TITLE
Limit on conversational history

### ISSUE THREAD

**Issue by billba** [microsoft/BotFramework-WebChat#355]
Right now WebChat will add new activities to the history until we run out of memory. Aside from memory considerations there is incremental performance cost for each activity added because although we are very efficient about caching activities, we still loop through them and run logic for each one every time an activity is added or changed (or when the chat is resized). This will show up sooner on slower devices.

I propose adding a new property called something like `{ maxHistory: number }` to `ChatProps` and I further propose that it have a reasonably high default (I'm thinking 1000) to stop websites from accidentally shooting themselves in the foot.

Once the size of the history reaches the limit, the addition of each new activity will be accompanied by the elimination of the oldest activity (multidenominational services will be performed). Since we already reconstitute the whole array of activities every time one is added, this operation will not result in any performance degradation, and the overall performance will be improved.

**Comment by TheTobias** [comment]
I would like to see this coupled with some logic to insert older messages. If you choose to set the maxHistory to a number smaller than what people might want to look at there should be a way to get older activities from an archive.

**Comment by billba** [comment]
@TheTobias how would that work?

If you're proposing backfilling the history with older messages, that would mean increasing the history size, and the whole point of this feature is to let the developer to limit the history size to keep performance snappy. So viewing older messages would have to happen elsewhere. So what we're really talking about is a link to an external URL.  Both archiving and display would have to be implemented entirely by the bot developer, because the bot framework does not archive messages.

Here's an idea: bot can provide a 'pinned' first message for when we exceed the history limit. This could be any valid message, but would most commonly just be text pointing them at a URL which shows the conversation history.

**Comment by TheTobias** [comment]
I am very new to typescript and not too familiar with react components so maybe I am missing something here.
I want to add old message divs to the DOM so the user can read old messages like they could with other clients that archive messages. If I store the history server side I can add some javascript to the index.html that can add divs with old messages to the .wc-message-group-content div.

**Comment by billba** [comment]
@TheTobias again, the point is that old messages fill up memory and/or clog up performance. So you either have them, or you don't. If you want users to see old messages, why limit the history size? And if you want to limit history size, why let users see old messages?

I think you have confused this feature (which is all about performance) with the "resume conversation" feature, which could certainly benefit from the ability to reload the conversation with archived messages.

**Comment by compulim** [comment]
We will limit the number of visible activities to 1,000 by default. And it will be configurable by the user.

We don't have a plan to limit the number of activities kept in the memory because we don't see big performance hit over the memory yet.

**Comment by corinagum** [comment]
Related to #1118
