### ISSUE TITLE
ActivityMiddleware loops through activities in reverse

### ISSUE THREAD

**Issue by felixvanleeuwen** [microsoft/BotFramework-WebChat#3556]
## Screenshots
![image](https://user-images.githubusercontent.com/64589372/96988363-876cea00-1524-11eb-8b85-82fac994cbe0.png)

## Version
4.10.1
```
<meta name="botframework-directlinespeech:version" content="4.10.1">
<meta name="botframework-webchat:bundle:variant" content="full">
<meta name="botframework-webchat:bundle:version" content="4.10.1">
<meta name="botframework-webchat:core:version" content="4.10.1">
<meta name="botframework-webchat:ui:version" content="4.10.1">
```

## Describe the bug
Activities pass through the middleware in the opposite order that they arrived in.

## Steps to reproduce
1. Send an activity to the frontend.
2. 1st Activity passes through activity middleware.
3. Send another activity to the frontend.
4. 2nd Activity passes through activity middleware.
5. 1st Activity passes through activity middleware.

## Expected behavior
1. Send an activity to the frontend.
2. 1st Activity passes through activity middleware.
3. Send another activity to the frontend.
4. 2nd Activity passes through activity middleware.

-or-

1. Send an activity to the frontend.
2. 1st Activity passes through activity middleware.
3. Send another activity to the frontend.
4. 1st Activity passes through activity middleware.
5. 2nd Activity passes through activity middleware.

Preferably the latter.

[Bug]

**Comment by felixvanleeuwen** [comment]
The code we use is proprietary.
I'm going to clone one of the examples and try to get it to work there.
This might take some time to prioritize but I'll post back once I have it.

**Comment by felixvanleeuwen** [comment]
That was easy!
I took one of the samples and added an `activityMiddleware` that prints the activity ID.

Here's the result:
![image](https://user-images.githubusercontent.com/64589372/97149379-f9d00b00-176c-11eb-8280-a797194b85ce.png)

And the code:
```
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Incoming activity to JavaScript event</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }

      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {

        const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
        const { token } = await res.json();

        const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
          if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') {
            const event = new Event('webchatincomingactivity');

            event.data = action.payload.activity;
            window.dispatchEvent(event);
          }

          return next(action);
        });
		
		const middleware = function() {
			return () => (next) => (card) => {
				console.log('Custom activityMiddleware');
				console.log('card.activity.id: ' + card.activity.id);
				return next(card);
			}
		}

        window.WebChat.renderWebChat(
          {
            directLine: window.WebChat.createDirectLine({ token }),
			activityMiddleware: middleware(),
            store
          },
          document.getElementById('webchat')
        );

        window.addEventListener('webchatincomingactivity', ({ data }) => {
          console.log(`Received an activity of type "${data.type}":`);
          console.log(data);
        });

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>
```

**Comment by stevkan** [comment]
@felixvanleeuwen, the descending order of displayed activities is expected behavior. It is used in some of the rendering of grouped components.

If you want the activities to display in an ascending order, as a product of the activity middleware, you can utilize the following code to achieve this:

```js
const activityMiddleware = () => next => card => children => {
  const render = next( card );
  if ( render ) {
    const { activity } = render( children ).props;
    if ( activity ) {
      console.log( 'Middleware Activity ', activity );
      return next( card )( children );
    }
  }
};
```

![image](https://user-images.githubusercontent.com/18403946/97249767-c370ab00-17c1-11eb-8df9-eae2774e7b42.png)

As this should resolve your issue, I am going to close this as resolved. If the issue persists or you have additional details to provide, please feel free to re-open.

**Comment by felixvanleeuwen** [comment]
Thanks for the info
