### ISSUE TITLE
Herocards, Thumbnail cards are not markdown compliant

### ISSUE THREAD

**Issue by stephaneey** [Microsoft/BotFramework-WebChat#356]
Hi,

As indicated in the title, these objects are not markdown compliant which makes them unsuable with text content. Any clue whether markdown language will be supported?

Thanks

**Comment by billba** [comment]
Can you explain what you mean by "markdown compliant?"

**Comment by stephaneey** [comment]
Well, I'm referring to this https://blogs.msdn.microsoft.com/jamiedalton/2016/08/22/bot-framework-markdown-support-by-channel/. So markdown is used to have rich text. While it works fine with regular text messages, it's totally ignored by thumbnail & herocards which make them unusable to show text content

**Comment by billba** [comment]
Well I think it's hyperbolic to call them "unusable" since people use Hero and Thumbnail cards all the time. However it sounds like, for your application, you require Markdown in the various text fields of those cards. Unfortunately this is not supported by the underlying framework.

**Comment by stephaneey** [comment]
that's why I said "unusable to present text content". In my scenario I had to return several KB articles (short ones) in a carousel but of course, for that kind of requirements, this is indeed unusable. If you think of exposing the webchat to a mobile device, just putting links all the time isn't a great user experience, showing the few first lines of text (well formated) is much better but clearly, not ok "as is".

**Comment by billba** [comment]
Yes, if you require presenting rich text in cards, you will not be able to accomplish that using bots today with ours or any other framework/channel. However it's reasonable to expect that over time channels will become richer in capability, and that the Bot Framework and WebChat will follow their lead.

**Comment by stephaneey** [comment]
ok a bit disappointing but thanks for your fast answer 👍

**Comment by Laul0** [comment]
Some years after... I was in the same case than you… I wrote a little post about that and a solution to display MD into this kind of Card: [Display Markdown to your Bot Framework Hero and Thumbnail Cards 💡](https://blog.lsonline.fr/2019/04/10/display-markdown-to-your-bot-framework-hero-and-thumbnail-cards/)
