### ISSUE TITLE
Strikethrough (<s>) is removed on sanitize

### ISSUE THREAD

**Issue by wvpm** [microsoft/BotFramework-WebChat#3565]
## Version
https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js

## Describe the bug
When sending markdown text `"~~test~~"` to the customer from the bot without a textFormat property in the activity (so it defaults to markdown), the WebChat shows "test" instead of "~~test~~".

## Additional context
Based on https://github.com/microsoft/BotFramework-WebChat/blob/bbbaeb9c2c46ec61ad109c2dbce46099f87efeba/packages/bundle/src/renderMarkdown.js, I concluded that markdown-it is used to render the markdown. Note that `strike` is allowed as an html tag whilst `s` is not. According to https://github.com/markdown-it/markdown-it/blob/master/test/fixtures/markdown-it/strikethrough.txt markdown-it converts strikethrough into `s`. This is subsequently sanitized, which explains the behaviour I experience.

I would recommend added `s` to the allowed html tag list.

[Bug]

**Comment by corinagum** [comment]
wow, interesting that we added `<strike>` but not `<s>`. Thanks for the catch! Putting this on our potential list for R12, for which planning will happen in the next few weeks.
