### ISSUE TITLE
Bump to Cognitive Services Speech SDK 1.14.0 or higher - related to #3666

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3575]
### Remove workaround

When we bump to 1.13.1, we hit an issue, https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/256.

The issue is because the Speech SDK dropped `webkitAudioContext`. But macOS/iOS is still using vendor prefix for Web Audio.

We temporarily hacked the code. When we bump to 1.14.0, it should have the issue fixed. We will need to remove those monkeypatches.

### Resolve ticket 205727392

This ticket 205727392, is related to [a bug](https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/211) in <= 1.13.1 (`listenOnce` cannot be called more than once).

It was fixed in Speech SDK (https://github.com/microsoft/cognitive-services-speech-sdk-js/pull/244) and shipped in 1.14.0.

[Enhancement]

**Comment by cwhitten** [comment]
Closing in lieu of https://github.com/microsoft/BotFramework-WebChat/issues/3666 as a dupe
