### ISSUE TITLE
[Forms and Validations-Intelligent Support Experience-Credit Request]: All the form elements of chat bot messages are not associated with their respective labels.

### ISSUE THREAD

**Issue by Amit8527510735** [microsoft/BotFramework-WebChat#3580]
**Note:**
Issue is observed for all the form fields of Iris chat bot

**User Impact:** 
Users who rely on screen readers will face difficulty in filling the inputs of the chat bot messages if form elements are not associated with their respective labels.

**Test Environment:**
OS : Windows 10 2004 (OS Build 19041.450)
Browser: New Edge 84.0.522.63, Chrome 84.0.4147.135
URL: https://servicesuat.microsoft.com/#/time/timeentry
Tools used: Accessibility Insights for Web (AI)

**Repro Steps:**
Step 1: Open the above URL in Edge/Chrome browser with valid credentials and turn on NVDA/JAWS.
Step 2: Select 'Bot' control from the header section of the page.
Step 3: Enter 'Credit Request' in Type your message edit field and press enter to send the message to Iris Bot.
Step 4: Choose 'Yes/No' option from "Will this be rebilled?" reply back of Iris Bot.
Step 5: Now Iris Bot asks for the Sales Order Number.
Step 6: Reply back with Order Number 'C.6908020210'.
Step 7: Run  Accessibility Insights for Web (AI) and verify whether all the form elements of chat bot messages are  associated with their respective labels.

**Actual:**
All the form elements of chat bot messages are not associated with their respective labels.

Ex: Screen reader is announcing as 'Spin button editable blank' when its focus is over 'Total Number of Hours to be Billed' spin edit field.

**Expected:**
Ensure all the form elements of chat bot messages are associated with their respective labels.

Ex: Screen reader should announce label information as 'Total Number of Hours to be Billed Spin button editable' when its focus is over 'Total Number of Hours to be Billed' spin edit field.
Ensure that,the form fields with asterisk mark(Mandatory fields) should be narrated as required along with the label information.

**Other Instances:**
1.Create a support ticket
Navigation: Start Over -> Hi -> Would you like me to create a support ticket for you? - > Yes ->Navigate over "Justification" edit field to verify the label mapping.
Please refer attachment: <MAS 3.3.2_Create support ticket.png>
2.Supplier Purchase Order Update
Navigation: Start Over -> Supplier PO Update -> Supplier Purchase Order Update - > 99000794 ->Select any button from 'Please select the purchase order line item to modify' -> Navigate over edit fields of 'Please enter the below details to create Supplier PO Update Request' message.
Please refer attachment: <MAS 3.3.2_Supplier PO Update.png>
3. Time Transfer:
Navigation: Enter time transfer in type your message edit field->provide Engagement ID as 'C.6908035600'->C.6908035600.001000.
Please refer the attachment<MAS 3.3.2_Time transfer>

**MAS Reference:**
[MAS 3.3.2 - Labels or Instructions](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b4b95a70d-258c-474a-820e-5c8b79d5c0bf%7d
) 
![MAS 3 3 2_Create support ticket](https://user-images.githubusercontent.com/53263029/97970921-44dec380-1de8-11eb-8f56-068680879779.png)
![MAS 3 3 2_Form elements example with code snippet](https://user-images.githubusercontent.com/53263029/97971015-69d33680-1de8-11eb-864b-dcbd1ea819be.png)
![MAS 3 3 2_Form elements labels](https://user-images.githubusercontent.com/53263029/97971091-896a5f00-1de8-11eb-9f49-0e507d60a5e1.png)
![MAS 3 3 2_Supplier PO Update](https://user-images.githubusercontent.com/53263029/97971139-98511180-1de8-11eb-82e7-7dbd719fc3ae.png)
![MAS 3 3 2_Time transfer_Edit fields](https://user-images.githubusercontent.com/53263029/97971174-a4d56a00-1de8-11eb-9f7a-655f9920be62.png)

**WCAG Reference:**

https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html

https://www.w3.org/WAI/WCAG21/Techniques/html/H44

**Comment by compulim** [comment]
@anusharavindrar this issue belongs to [Adaptive Card team](https://github.com/microsoft/adaptivecards). In this case, the bot sent an Adaptive Cards and Web Chat use the AC renderer. But their renderer has accessibility issues.

Please send this issue to their team. Thanks!
