### ISSUE TITLE
[Webchat modification required] : https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/l.disable-adaptive-cards

### ISSUE THREAD

**Issue by MeenakshiBalekar** [microsoft/BotFramework-WebChat#3582]
I was working on one repro and encountered that the : https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/l.disable-adaptive-cards has an extra line of code added on line 205 :               disabled={disabled}

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Go to https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/05.custom-components/l.disable-adaptive-cards/index.html
1. try to run the sample
1. we will see error 
1. post removing code from line 205 : disabled={disabled}
It will work 

It do not work with the code where we have  disabled={disabled} added under the ReactWebChat

## Expected behavior

provide a response 

## Additional context

[Bug]

**Comment by corinagum** [comment]
Thanks for filing this issue. I will add this to the R11 milestone for investigation.
