### ISSUE TITLE
Links in Azure chat bot adaptive cards given aria-label="undefined"

### ISSUE THREAD

**Issue by Amit8527510735** [microsoft/BotFramework-WebChat#3591]
**Accessibility 161215:** Links in Azure chat bot adaptive cards given aria-label="undefined"

Product name, version, and build: Azure Chat Bot, Edge/Chrome v.86

**OS version and build:** Windows 10

**AT version and build (if applicable):** JAWS 2020, NVDA 2020.3

Does this repro with other AT? (If applicable) Yes, Narrator and NVDA

**Share access to the environment (if applicable):** 

**Prerequisite (if any)** 

**Description**
When accessing the customer's chat experience, some of the adaptive cards are given a URL. When navigating to that URL with a screen reader, the label is "undefined"

R**epro steps**
1. Open URL to environment in Chrome/edge
2. Open JAWS or NVDA
3. in ZIP code edit field, type 97478 and press Enter
4. Tab to service and select "additional services"
5. 
6. Tab to "go to facility detail" link

**Screenshots** N/A

**Actual results**
When the screen reader lands on the link, the label is read as Undefined. 

**12. Expected Results**
When the AT lands on the link, it should read 'go to facility detail page'

WCAG Reference Link:
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

**Source Code:**

**Comment by Amit8527510735** [comment]
#A11yMAS;#Accessibility;#MAS1.3.1;#HCL;A11yeDAD;#HCL_BotFramework_WebChat;

**Comment by compulim** [comment]
@Amit8527510735 This is possibly a bug on Adaptive Cards team.

Trying to follow your steps (ZIP code = 97478, service type = "Additional Services") but couldn't repro.

![image](https://user-images.githubusercontent.com/1622400/98303881-c31ba100-1f73-11eb-8f67-185be91e2c78.png)

For issues related to Adaptive Cards, please use this tool and copy-and-paste the Adaptive Card there. If it repro, it's a bug on the Adaptive Cards project.

https://adaptivecards.io/designer/

**Comment by compulim** [comment]
Investigations completed, unassigning myself.

**Comment by corinagum** [comment]
Closing this issue. Please keep an eye on #3392 for updates.

**Comment by kattepalli** [comment]
#A11ySev2;
