### ISSUE TITLE
Unable to open pdf in new tab of browser from Microsoft web chat bot framework.

### ISSUE THREAD

**Issue by rajgohel** [microsoft/BotFramework-WebChat#3600]
I am unable to open pdf in a new tab of browser by passing URL using Attachment in Web chat bot framework. My code snippet as below.
```
Attachment attachment = new Attachment();
attachment.ContentType = "application/pdf";
attachment.ContentUrl = DocUrl;
attachment.Name = "Name";
var response = helper.CreateResponseWithSuggestions(valueDataState.suggessionReply, attachment);
await turnContext.SendActivityAsync(response).ConfigureAwait(false);
```
-----In helper------
```
public Activity CreateResponseWithSuggestions(Activity SuggestionsActivity, Attachment attachment)
{
     var response = SuggestionsActivity;
     response.Attachments = new List<Attachment>() { attachment };
     return response;
}
```

**Comment by stevkan** [comment]
As a matching issue was posted on SO that already has some activity, I am going to close this in favor of the other.

**Comment by rajgohel** [comment]
I have sent attachment with card from bot to my web application it contains some text messages by clicking on that text i want to open pdf in new tab of browser. My code gives me hyperlink but by clicking on that it navigates to new blank tab in browser it not redirect to "ContentUrl" which i have passed from bot.
