### ISSUE TITLE
[Screen Reader-Intelligent Support Experience-Feedback]: JAWS is announcing as "Attachment" while navigating using cursor mode over the button controls of 'Feedback'.

### ISSUE THREAD

**Issue by Amit8527510735** [microsoft/BotFramework-WebChat#3619]
**Note:**
Issue is observed with JAWS through out Iris chat window while navigating in cursor mode.

**User Impact:** 
Screen reader users who navigate using JAWS cursor mode will be confused if JAWS is narrating as "Attachment" while navigating over the button controls of 'Feedback' instead of reading as button.

**Product name, version, and build:** Intelligent Support Experience/Chrome v.84
**OS :** Windows 10 2004 (OS Build 19041.450)
**Browser:** Chrome 84.0.4147.135
**URL:** https://servicesuat.microsoft.com/#/time/timeentry
**Screen Readers:**  JAWS 2020.2004.13.400

**Does this repro with other AT? (If applicable): Yes**, JAWS

**AT version and build (if applicable):** JAWS 2020.2004.13.400

**Prerequisite (if any):** NA

**Repro Steps:**
Step 1: Open the above URL in Chrome browser with valid credentials and turn on JAWS.
Step 2: Navigate to 'Bot' button in header section and press Enter
Step 3: Iris dialog will open 
Step 4: Enter 'Feedback' in type your message edit field and press enter to send the message.
Step 5: Enable JAWS cursor mode and navigate over the button controls of 'Feedback' using arrow keys.
Step 6: Verify the announcement of JAWS screen reader while navigating over the button controls of 'Feedback' in cursor mode.

**Screenshots:** 
![MAS 4 2 1_Button reading as Attachment](https://user-images.githubusercontent.com/53263029/100317172-e5886380-2fe1-11eb-81ca-0b567c70e831.png)
![MAS 4 2 1_Time Transfer](https://user-images.githubusercontent.com/53263029/100317177-e7eabd80-2fe1-11eb-9e9b-28910f565cb4.png)
![MAS 4 2 1_Credit Request](https://user-images.githubusercontent.com/53263029/100317182-e91bea80-2fe1-11eb-91ea-34630491693d.png)

**Actual:**
JAWS is announcing as "Attachment" while navigating using cursor mode over the button controls of 'Feedback'.
Ex: JAWS is narrating as 'i dont like something attachment'

**Expected:**
JAWS should narrate the correct role and description when focus comes to the buttons present in Feedback message card while navigating using cursor mode.
Ex: JAWS should narrate as 'i dont like something button'

**Other instances where this issue repros:**
1. Credit Request
Navigation: Start Over -> Bot Response -> Yes -> C.6908020210 -> Credit request screen
2. Time Transfer
Navigation: Start Over -> Bot response -> C.6908035600 -> Bot Response -> C.6908035600.001000 -> Time Transfer screen will be opened
Please refer attachment(MAS 4.2.1_Credit Request.png & MAS 4.2.1_Time Transfer.png)

**WCAG Reference Link:**
https://www.w3.org/WAI/WCAG21/Understanding/

**Comment by Amit8527510735** [comment]
#Accessibility;#WCAG4.2.1;#HCL;#HCL_BotFramework_WebChat

**Comment by corinagum** [comment]
@Amit8527510735 Thanks for filing this issue. It looks like the images were not attached with the comment. Could you add those? Thank you.

**Comment by Amit8527510735** [comment]
@corinagum i have added screenshot in the comment.

**Comment by corinagum** [comment]
Quick update: I don't yet have JAWS on my machine but will look into this as soon as I am able.

**Comment by amal-khalaf** [comment]
hi @Amit8527510735  the link provided in the initial issue description is not working 
i get a System down error - could you provide a working link
![image](https://user-images.githubusercontent.com/28356655/104503509-027af500-5596-11eb-8ce9-1ae9a3394c05.png)

**Comment by Amit8527510735** [comment]
@amal-khalaf : Can you please share alias who needs access to the link.

**Comment by amal-khalaf** [comment]
@Amit8527510735 my alias is amkhalaf

**Comment by amal-khalaf** [comment]
Hi @Amit8527510735 any updates on this?

**Comment by Amit8527510735** [comment]
@amal-khalaf Shared your alias they will provide on it .

**Comment by Amit8527510735** [comment]
Closing the bug as still environment access pending at CSEO team and bug became in OUT of SLA. Will create new bug once CSEO team grant access to amal-khalaf.

**Comment by Amit8527510735** [comment]
Access provided to @amal-khalaf created new bug(https://github.com/microsoft/BotFramework-WebChat/issues/3700) for the same due to SLA
