### ISSUE TITLE
[Screen Readers-Intelligent Support Experience-Rate your Experience]: Talkback focus is not sequential on invoking any of the Star rating buttons in 'Rate your Experience' section while navigating using right swipe

### ISSUE THREAD

**Issue by Amit8527510735** [microsoft/BotFramework-WebChat#3620]
**User Impact:** 
Screen Reader dependent users who navigate using Talkback right swipe are misguided as Talkback focus is not sequential on invoking any of the Star rating buttons in 'Rate your Experience' section while navigating using right swipe

 **Product name, version, and build:** Intelligent Support Experience/Chrome v.83
Device: Android
OS : Version 10
Browser: Chrome version 83.0.4103.106
URL: https://servicesuat.microsoft.com/#/time/timeentry
Screen Readers: Talkback

**Does this repro with other AT? (If applicable)**: NA

**AT version and build (if applicable):** NA
 
**Repro Steps:**
Step 1: Enable Talkback & Open the above URL in Chrome browser with valid credentials
Step 2: Select 'Bot' control from the header section of the page.
Step 3: Say 'Hi' to Iris chat bot.
Step 4: 'Would you like me to create a support ticket for you?' response comes back.
Step 5: Choose 'No' to reply back.
Step 6: Reply with 'No' for 'Is there anything else that I can help you with?' response from chat bot.
Step 7:Navigate over the star rating buttons of 'Rate your experience!' message using right swipe and double tap on any of the Star rating buttons & verify Talkback behavior.
 
**Screenshots:** 
![image](https://user-images.githubusercontent.com/53263029/100317783-e79ef200-2fe2-11eb-8021-e346a1f2c97d.png)

**Actual Result:**
Talkback focus is not sequential on invoking any of the Star rating buttons in 'Rate your Experience' section while navigating using right swipe.
Observation: On invoking any of the Star rating buttons, Talkback focus is moving to Email edit field.
 
**Expected Result:**
Talkback focus should stay on the selected Star rating button on invoking any of Star rating buttons in 'Rate your Experience' section while navigating using right swipe.
Ex: If 1 Star button is invoked, Talkback focus should stay on 1 Star button and should narrate as "1 Star button selected".
 
**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence

**Comment by Amit8527510735** [comment]
#Accessibility;#WCAG1.3.2;#HCL;#HCL_BotFramework_WebChat

**Comment by corinagum** [comment]
Thank you for filing this issue. @compulim could you test this on Android?

**Comment by tonyanziano** [comment]
@compulim please provide an update.

**Comment by compulim** [comment]
This is an Adaptive Card issue. Web Chat uses Adaptive Card library to render the content. And the accessibility in the content seems broken.

Can you repro it on https://adaptivecards.io/designer/?

**Comment by Amit8527510735** [comment]
@compulim  So you are telling this is external to Adaptive Card team? We need to route this to Adaptive Card team ?

**Comment by amal-khalaf** [comment]
hi @Amit8527510735  the link provided in the initial issue description is not working 
i get a System down error - could you provide a working link so i can repro
![image](https://user-images.githubusercontent.com/28356655/104503509-027af500-5596-11eb-8ce9-1ae9a3394c05.png)

**Comment by corinagum** [comment]
@Amit8527510735, additionally if the AC designer shows the same problems (from @compulim's comment), that would mean the issues needs to be rerouted to Adaptive Cards.

**Comment by Amit8527510735** [comment]
@corinagum / @amal-khalaf : Can you please share alias who needs access to the link.

**Comment by amal-khalaf** [comment]
@Amit8527510735 my alias is amkhalaf

**Comment by Amit8527510735** [comment]
@amal-khalaf  Shared your alias CSEO team will provide access on it .

**Comment by Amit8527510735** [comment]
Closing the bug as still environment access pending at CSEO team and bug became in OUT of SLA. Will create new bug once CSEO team grant access to amal-khalaf.
