### ISSUE TITLE
hideUploadButton not hiding buttong when set to true

### ISSUE THREAD

**Issue by DennyWithAnE** [microsoft/BotFramework-WebChat#3624]
## Screenshots
`      const styleOptions = {
        hideUploadButton: true,
        bubbleBackground: "white",
        bubbleBorderStyle: "solid",
        bubbleBorderRadius: "10px",
        bubbleFromUserBackground: "#5ce9ff",
        bubbleFromUserBorderRadius: "10px",
        groupTimeStamp: 3000,
        emojiSet: true,
        timestampFormat: 'relative',
        timestampColor: "red",  
      };
`

## Version

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

Tried to implement the hideUploadButton through the git repo's tutorial but it seems like the upload button is still showing despite me setting the option to true in my styleOption.
## Additional context

[Bug]

**Comment by corinagum** [comment]
Hi @DennyWithAnE, our hide upload button sample appears to be working. It looks like this is an implementation issue. 
Link: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization/f.hide-upload-button

@stevkan could you or another support engineer help out? Thanks.

**Comment by DennyWithAnE** [comment]
Thanks for the clarification on the issue!
