### ISSUE TITLE
Direct Line App Service Extension Websocket error 500

### ISSUE THREAD

**Issue by chung-ting** [microsoft/BotFramework-WebChat#3627]
## Describe the bug

I implemented the  Direct Line App Service Extension(Node.js version) according to the official website suggestion, but I encountered some problems during the implementation. (https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/i.protocol-direct-line-app-service-extension)

I successfully got the token, but encountered a websocket error when establishing a connection

Error message from Chrome[F12]: 
webchat-minimal.js:2 WebSocket connection to 'wss://chatbot-nodejs-bot-channel.azurewebsites.net/.bot/v3/directline/conversations/connect?token=undefined' failed: Error during WebSocket handshake: Unexpected response code: 500

[Bug]

**Comment by corinagum** [comment]
> Issue was due to WebSockets being disabled in the bot's web.config with a slight hiccup afterwards due to 'always on' not being set on the bot, causing it to need a nudge to wake up.

Due to the above, I am changing this from Bug to Question.

- [x] Remove `Support` label / change to `Question`
- [ ] Add this topic to FAQ
- [ ] Mock Bot token feedback TBDiscussed here
   - Note: we already have an action item regarding token documentation at: https://github.com/microsoft/BotFramework-WebChat/issues/2343

**Comment by taicchoumsft** [comment]
@corinagum  any updates on this?

**Comment by corinagum** [comment]
@taicchoumsft thanks for the ping. I messaged the reporting developer via Teams for a response, since I can't seem to find his GitHub handle. Also added this to the R12 milestone so the action item doesn't fall through the cracks.

**Comment by corinagum** [comment]
@DDEfromOR do you have feedback for the token issue? Feel free to close this and address it at #2343 instead.
