### ISSUE TITLE
Reaction buttons example and activity id

### ISSUE THREAD

**Issue by martinoss** [microsoft/BotFramework-WebChat#3632]
## Version

4.11

## Describe the bug

First, I'm not sure if this is the best category for my input.

In the sample for [reaction buttons](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/05.custom-components/d.reaction-buttons) the activityId is passed in the MessageReaction object which does not seem to be part of the [specification](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#messagereaction-object) [bot builder implementation](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/MessageReaction.cs).

Also, MessageRection.cs has a type property for the reaction which is not used in the sample to populate the reaction.

## Steps to reproduce

See implementation in the sample

```
const handleUpvoteButton = useCallback(() => {
    postActivity({
      type: 'messageReaction',
      reactionsAdded: [{ activityID, helpful: 1 }]
    });
}, [activityID, postActivity]);
```

## Expected behavior

Shoudn't the activityid be transported via the `replyToId` activity property and the reaction in the type of "MessageReaction"?

Like this:

```
    const addMessageReaction = (helpful: boolean) => {
        props.postActivity({
            type: 'messageReaction',
            reactionsAdded: [{ type: (helpful ? "ThumbsUp" : "ThumbsDown") }],
            replyToId: props.activityId
        });
    }
```

This way, it would be easier to handle the reactions out of the box with c# bot builder sdk:

![image](https://user-images.githubusercontent.com/2587942/101788468-6c6c2e80-3b00-11eb-8670-b30520566862.png)

[Bug]

**Comment by corinagum** [comment]
Thanks for bringing this up. I recall the same thought occurring to me in the past but I failed to follow-up. Your suggestion makes sense to me, and of course we don't enforce any of the code suggestions we make in our samples, so you are free to follow your example code. 🙂

I will bring this up as team discussion to reach a consensus to decide if we want to update the sample.

**Comment by tonyanziano** [comment]
We will look to prioritize this in the upcoming release.

**Comment by compulim** [comment]
Assigning to Post R12.

I think the last time we discussed was to fix this shortly after we ship R12. Please correct me if I am wrong.

**Comment by corinagum** [comment]
Originally filed by @5Heinzelmann:

> https://microsoft.github.io/BotFramework-WebChat/05.custom-components/d.reaction-buttons/
> 
> ## Screenshots
> ![Screenshot](https://camo.githubusercontent.com/992e55ac0421722ce6996fb0f66a6ac13cb33ca3b12bf651f0987d1ea6db37eb/68747470733a2f2f692e696d6775722e636f6d2f4a7450514f6a392e706e67)
> 
> ## Steps to reproduce
> 1. Go to https://microsoft.github.io/BotFramework-WebChat/05.custom-components/d.reaction-buttons/
> 2. Text Hi
> 3. Text Help
> 4. Wait a few seconds
> 5. See error
> 
> ## Expected behavior
> Bot answers with default help text and shows reaction buttons in front of each bot message.
> 
> ## Additional context
> Same for Chrome and Firefox (I used chrome for Screenshot)
> 
> [Bug]
