### ISSUE TITLE
How to avoid OAuth card on unauthorized site? I am using Webchat/DirectLine and using OAuth card and login automatically in background

### ISSUE THREAD

**Issue by selvaduraiece** [microsoft/BotFramework-WebChat#3642]
Hi Team,

I have hosted webchat using Static website which comes along with the bot framework.  I have already configured SSO as well. 
I have added an OAuth card in the 'ConvesationUpdateActivity' once user clicks on Login button and gets authenticated and then proceeds further.
![image](https://user-images.githubusercontent.com/40558980/102324445-e0e31980-3fa7-11eb-9a96-eca9b93563d2.png)
**Is there way to minimize this login click?** 
Users are much concerned about this login with in a chat window
If not possible at least login first and then show the chat window? something like below?
![image](https://user-images.githubusercontent.com/40558980/102325677-6ddaa280-3fa9-11eb-87c5-a98ef4fd083a.png)

Is there any possibilities of triggering an event to do the login?

**Comment by stevkan** [comment]
@selvaduraiece,

If I'm understanding correctly, you have SSO built into the hosting page and now you would like to do the same for Web Chat so user's don't receive the 'Login' button. Am I correct?

If so, please look over the Web Chat [SSO samples](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps), in particular [sso-on-behalf-of-authentication](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/e.sso-on-behalf-of-authentication), to see if one matches your needs.

**Comment by selvaduraiece** [comment]
No, SSO is not built on hosting page. It is just a static page. I wanna do login without button click. May b somewhere in background also fine.(using activity/making APIcall)

**Comment by selvaduraiece** [comment]
Hi, Any update on this?

**Comment by selvaduraiece** [comment]
@stevkan @peterinnesmsft @taicchoumsft - Team any update on this? If needed, I can even raise a support ticket for the same. It would be great help if I could get some resolution. UAT is about to happen.

**Comment by stevkan** [comment]
@selvaduraiece, there is no way to log in a customer automatically without the user initiating / approving the process at some point, whether that is a button on the page, as part of the conversation with the bot, or having logged in on the same device in another app.

**Comment by selvaduraiece** [comment]
Hi can you help me with example for logging in as a part of conversation?

**Comment by stevkan** [comment]
There are two samples already available in the BotBuilder-Samples repo, [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication) and [24.bot-authentication-msgraph](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/24.bot-authentication-msgraph). These are the JS examples, but they are also available in dotnet and Python. Both demonstrate how an authenticated login is setup for use in a conversation with a bot.

This doc, [Add authentication to a bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp), discusses the steps from beginning to end on how to configure all the necessary services. There are a number of relevant links to be found there, as well.
