### ISSUE TITLE
BackChannel Mechanism and  DirectLine Speech - Unable to subscribe to events sent by the bot

### ISSUE THREAD

**Issue by priyababu** [microsoft/BotFramework-WebChat#3643]
**Facing issues with backChannel event handling through directLine speech channel.**
  
Unable to subscribe to the events/activities sent by the Bot. The code snippet is included and the problem area is highlighted with red box. I get a runtime error, “TypeError: adapters.directLine.activity$.filter is not a function”.
 
As per our login flow, the client should listen for the ‘loginRedirect’ event from the Bot.
The backchannel implementation worked fine when connected to a directline channel without speech. 
 
Think this could be due to the mutability state of the directline object. Not sure if the directline object returned by createDirectLineSpeechAdapters  is mutable.
I believe there will be an option available to subscribe to events sent by the bot through directLine Speech channel. Need help with resolving this issue.
 
![Screen Shot 2020-12-17 at 3 25 55 PM](https://user-images.githubusercontent.com/11216332/102645604-54ac3000-4128-11eb-8bfb-cb3c69c09485.png)

 
Runtime error that is thrown due the above code segment:

![Screen Shot 2020-12-18 at 11 59 27 AM](https://user-images.githubusercontent.com/11216332/102645701-7d342a00-4128-11eb-945a-c4d25abe16c5.png)

**Comment by compulim** [comment]
In DLJS, we are using RxJS 5, thus, you have access to RxJS functionality including `filter` operators.

In DLSpeech SDK, we are using ES Observable, which is drafted by TC39 and becoming a JavaScript standard. It don't offer any operators like `filter`.

If you are interested to use RxJS in DLSpeech SDK, you can read more at https://rxjs.dev/api/index/function/from.

**Comment by priyababu** [comment]
I tried subscribing to the DLSpeech channel to listen to events sent by Bot, as suggested by @compulim. Error was resolved but the Webchat is not responding to any activity sent by the bot. Looks like I am missing something. Need help with listening to events sent by bot through DirectLineSpeech channel. @compulim can you share a client side code snippet that subscribes/observes to the events sent by the Bot.
