### ISSUE TITLE
WebChat Send Box takes up entire iFrame in iOS

### ISSUE THREAD

**Issue by akamwand** [microsoft/BotFramework-WebChat#3647]
## Screenshots

![image](https://user-images.githubusercontent.com/65671760/102855642-a71c7380-43ea-11eb-8b0c-edeef37329d5.png)
![image](https://user-images.githubusercontent.com/65671760/102855731-c74c3280-43ea-11eb-8827-51962cd455b1.png)

## Version

Running latest WebChat V4

## Describe the bug

The webChat window should dynamically resize to HTML iFrame element on mobile iOS viewports, however, I am seeing the Send Message area blowing up to nearly the full iFrame height on iOS viewports.

To add some important context here : I am using an iFrame element within Wix and embedding my bot HTML code into the iFrame element. The webChat window resizing works like a charm for desktop viewports, but for mobile and specifically iOS viewports, the webChat window blows the send box up to nearly the full height of the iFrame. I thought by specifying both the width and height of the body and webChat window in HTML, the iFrame element within Wix would display the webChat window with those precise width and height yet it does not.

I may be running into this Open issue here but I was unsure if this is the root cause:  iOS handling of any iFrame element (https://github.com/microsoft/BotFramework-WebChat/issues/2044#issuecomment-503655312) 

What leaves me puzzled is that I tested passing my bot to the Wix iFrame element using the iFrame HTML code from the Web Chat Channel from my Bot Service and that re-sized the webChat window exactly how I needed it to in mobile iOS Safari. This, unfortunately, does not allow any styling however. If there was somehow a way to package the Direct Line webChat HTML into an iFrame with specified width/height , that would be perfect but I could not seem to find that solution anywhere in regards to webChat.

## Expected behavior

webChat window should dynamically resize to HTML iFrame element on mobile iOS viewports.

[Bug]

**Comment by stevkan** [comment]
The issue is occurring because you are passing defined values to `height` and `width` in "#webchat>*". If you leave those two values set at 100%, the issue goes away. Can you please reset those two values and try again?

```js
<style>
  html,
  body {
    height: 300px;
    width: 400px;
  }

  #webchat>* {
    height: 100%;
    width: 100%;
  }
</style>
```

**Comment by akamwand** [comment]
Thank you for the suggestion, I tried it out but unfortunately I get the same result where the send box takes up the full height of the iframe that I am placing my HTML in. The screenshot below is with your style changes implemented. 
![image](https://user-images.githubusercontent.com/65671760/102956239-6467a380-449d-11eb-9bf8-13cb2f92a6b4.png)


I have also attached the screenshot below, where I take my Web Chat provided iFrame, and then place that into another iFrame element on my Wix site. There's unfortunately no way around the iframe-within-an-iframe aspect for Wix integration at the moment. I'm curious as to why the webchat is responsive, like in the below screenshot, when I specify the iFrame width/height, but not responsive when I specify the #webchat width/height in the V4 styling framework. 

`<iframe src='https://webchat.botframework.com/embed/mybot='key'  style='border:none; min-width: 300px; width: 100%; height: 100%; overflow:hidden'></iframe>`

![image](https://user-images.githubusercontent.com/65671760/102956493-e48e0900-449d-11eb-843c-dc0495dc0d09.png)

**Comment by stevkan** [comment]
I believe it just comes down to the nature of an iframe element. As Mozilla defines it [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe),

> The HTML Inline Frame element (<iframe>) represents a nested browsing context, embedding another HTML page into the current one.

The iframe element has its own context and, therefore, needs its width and height to be defined within the hosting document. Setting the Web Chat instance's width and height only leaves it, I think, in a sort of unbound state. However, if you set the iframe properties, that then allows the Web Chat properties a boundary to be defined against.

**Comment by akamwand** [comment]
I was finally able to get the desired WebChat view. I did have control over the width and height for the iFrame element that contained my WebChat html code, that remained the same as the parent iFrame element does not allow me to use % sizing for responsive design and only px sizing. 

It appears that the WebChat window will fill it's container element entirely only if all the elements in WebChat are styled responsively using %. Even if I set the exact width and height of the WebChat window to the same width and height of the iFrame element, the WebChat will not scale down when specifying size in px.

Below is the working code and a screenshot of my desired output.

`<!DOCTYPE html>
<html>
   <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
            html{
                height: 100%;
                width: 100%;
                margin: 0;
                padding: 0;
            }
            body{
                height: 100%;
                width: 100%;
                margin: 0;
                padding: 0;
            }
            #webchat {
                height: 100%;
                width: 100%;
            }
            </style>
   </head>
   
   <body>
      <div id="webchat" role="main"></div>
        <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
        <script>
            // "styleSet" is a set of CSS rules which are generated from "styleOptions"
            const styleOptions = {
                sendBoxTextWrap: true,
                bubbleBackground: 'rgba(0, 0, 0, 0.11)',
                bubbleFromUserBackground: 'rgba(159, 0, 0, 1)',
                bubbleBorderColor: 'Black',
                bubbleFromUserBorderColor: 'Black',
                bubbleTextColor: 'Black',
                bubbleFromUserTextColor: 'White',
                botAvatarImage: 'https://i.postimg.cc/c4fmbMf7/bot.png',
                userAvatarImage: 'https://i.postimg.cc/nVR28PDJ/user.png',
                botAvatarInitials: ' ',
                userAvatarInitials: ' ',
                botAvatarBackgroundColor: 'White',
                userAvatarBackgroundColor: 'White',
                hideUploadButton: true,
                emojiSet: true,
                }
                window.WebChat.renderWebChat(
                {
                    locale: 'en-US',
                    overrideLocalizedStrings: (strings, language) => ({
                        ...strings,
                        TEXT_INPUT_PLACEHOLDER: 'Ask Away'
                    }),
                    directLine: window.WebChat.createDirectLine({
                        secret: 'secret'
                    }),
                    // Passing 'styleSet' when rendering Web Chat
                    styleOptions
                },
                document.getElementById('webchat')
                );
        </script>
    </body>
</html>`

![image](https://user-images.githubusercontent.com/65671760/103327304-95a21f80-4a19-11eb-9997-37293614a530.png)

**Comment by stevkan** [comment]
I think the only way you are going to get the kind of control you are seeking, assuming Wix allows this, is to construct your own Web Chat iframe instance. Rather than pass in the pre-generated Web Chat iframe control, pass in a normal HTML page + Web Chat component into the iframe element. In this way, you will have full control of the CSS in both the hosting page and in the embedded page.

**Hosting page:** The `container` element is used only for general styling of the hosting page. Note I can use both "px" or "%" on the `iframe` width/height.
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    html, body {
      height: 100%;
      width: 100%;
      margin: 0;
      background-color: #343A40;
    }

    .container {
      display: flex;
      justify-content: flex-start;
      align-items: flex-end;
      height: 100%;
      width: 100%;
    }

    iframe {
      border: transparent;
      border-radius: 18px;
      height: 800px;
      width: 40%;
      margin: 0 5px 0 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <iframe src='basic.html'></iframe>
  </div>
</body>
</html>
```

**Embedded "iframe" page:** Note that, because it's an actual page, I can use both "px" or "%" on the Web Chat component width/height.
```html
<!DOCTYPE html>
<html lang="en-US">

  <head>
    <title>Web Chat: Full-featured bundle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <script crossorigin="anonymous" src="https://unpkg.com/@babel/standalone@7.8.7/babel.min.js"></script>
    <script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/4.11.0/webchat.js"></script>
    <style>
      html,
      body {
        height: 100%;
        width: 100%;
        margin: 0;
        background-color: rgb(52, 5, 139);
      }

      #webchat {
        height: 600px;
        width: 75%;
        margin-left: 20px;
      }

      #webchat>* {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>

  <body>
    <div id="webchat" role="main"></div>
    <script type="text/babel" data-presets="es2015,react,stage-3">
      ( async function () {

        const res = await fetch( 'http://localhost:3500/directline/conversations', { method: 'POST' } );
        const { token } = await res.json();
        
        const directLine = window.WebChat.createDirectLine( {
          token
        } )

        window.WebChat.renderWebChat(
          {
            directLine: directLine,
          },
          document.getElementById( 'webchat' )
        );
        document.querySelector( '#webchat > *' ).focus();
      } )().catch( err => console.error( err ) );

    </script>
  </body>
</html>
```

In the pic below, you can see the iframe element is set to `height: 800px` and `width: 40%` while the Web Chat component is set to `height: 600px` and `width: 75%`. Web Chat is positioned at the top of the iframe element because I haven't yet applied any styling to bring it down.

![image](https://user-images.githubusercontent.com/18403946/103374415-67115c80-4a8c-11eb-9231-e7b0b63f450b.png)

**Comment by SSSTREDDD** [comment]
I also have this issue on IOS only. The proposed solution does not solve the problem.
