### ISSUE TITLE
AD SSO setup

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-WebChat#3652]
I have searched a lot and the information available for SSO for Active Directory using the Web Channel is very difficult to find / consume. I did manage to find the Samples posted here:
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps

My questions are based on the assumption of a WebChat implementation on a basic page with no authentication whatsoever:

- Is the only current possible way to receive an access token is to have an interaction between the user & https://login.microsoftonline.com and use the provided access token in the callback?
- Is there no way to get an "underwater" scenario just like Teams using Api's?

**Comment by stevkan** [comment]
@cxbuilders, did you look over Web Chat sample [b.sso-for-enterprise](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/07.advanced-web-chat-apps/b.sso-for-enterprise)? From what I can tell, this _should_ do what you are looking for.

**Comment by stevkan** [comment]
Closing as resolved.
