### ISSUE TITLE
Cannot Link Telemetry to ReactWebChat Component

### ISSUE THREAD

**Issue by ivanELEC** [microsoft/BotFramework-WebChat#3654]
## Version

Botframework-webchat version 4.11.0 - NPM 

## Describe the bug

I am using the ReactWebChat component to render a bot in a React App, I want to apply telemetry to the web chat so that I can have app insights, I was trying to find out how to implement this via [this link](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/k.telemetry-application-insights), but could only find how to do this via the renderWebChat function:

As you know, when you use the ReactWebChat component, the Web Chat is rendered via functions within the botframework-webchat node module and referenced node modules, it's effectively a black box for developers, only allowing us to configure it via the properties denoted in [this documentation](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/API.md), however I can't see an onTelemetry function here. Is it the case that ReactWebChat cannot use telemetry? Or is this just something missed out in the documentation?

**Comment by stevkan** [comment]
To use the `ReactWebChat` version, you simply need to include the necessary React CDN packages and then call the `ReactDOM.render()` method instead of `renderWebChat()`. Once set up, I can see the relevant traffic in App Insights.

![image](https://user-images.githubusercontent.com/18403946/103810323-edd7b380-500f-11eb-81a6-aceb01a16ea5.png)

See the attached file for a complete example. 
[basic-telemetry-app-insights.zip](https://github.com/microsoft/BotFramework-WebChat/files/5777683/basic-telemetry-app-insights.zip)

It does look like the documentation needs to be updated to include the `onTelemetry` property.

**Comment by stevkan** [comment]
Closing as resolved.

**Comment by ivanELEC** [comment]
Is there a method to do this using purely npm packages (using applicationinsights) instead of CDN bundles?
We are running this react app via a node project (create-react-app template) and I can't add this function into my component due to not being able to reference the dependencies.

**Comment by ivanELEC** [comment]
Could this ticket be re-opened for the question above or should I make a new ticket? Since using CDN bundles for applying application insights may be a security/factoring risk for us.

**Comment by stevkan** [comment]
Using the [BotBuilder-ApplicationInsights](https://www.npmjs.com/package/botbuilder-applicationinsights) NPM package _should_ give you access to the same functionality. However, configuring for use in Web Chat will likely require some tinkering. The instructions on the NPM page won't directly apply as they are specific to writing code for a bot. Unfortunately, I haven't tested this kind of setup, yet.

**Comment by ivanELEC** [comment]
Hello Steven, 

Thanks, I ended up succeeding by using the Microsoft Application Insight SDK: 
https://www.npmjs.com/package/@microsoft/applicationinsights-web

I initialised the appInsights object:
```
//initialize telemetry app insights and set static records
  let appInsights = new ApplicationInsights({
    config: {
      instrumentationKey: props.appInsightIKey,
      extensions: [reactAI],
    },
  });
  //load application insights
  appInsights.loadAppInsights();
```

Once I have my direct line I populate the appInsight objects context properties so that the logs are traceable: 
```
if (appInsights.context) {
                //add userId and conversationID to appInsights and save to state
                appInsights.context.application.ver = "1.0";
                appInsights.context.session.acquisitionDate = Date.now();
                appInsights.context.session.id = directLinev2.botConversationId;
                appInsights.context.user.accountId = props.userId;
              }
```

then I use the handleTelemetry function that's in the example provided: 
```
//function for generating telemetry
  const handleTelemetry = (event) => {
    const {
      data,
      dimensions,
      duration,
      error,
      fatal,
      level,
      name,
      type,
    } = event;
    const fullName = `webchatui:${name}`;

    console.group(`onTelemetry ("${type}")`);
    console.log({ name, data, dimensions, duration, error });
    console.groupEnd();

    if (type === "event") {
      const appInsightsData =
        typeof data === "number" || typeof data === "string"
          ? { [name]: data }
          : Object.entries(data || {}).reduce(
              (data, [key, value]) => ({ ...data, [`${name}:${key}`]: value }),
              {}
            );

      appInsights.trackEvent({
        name: fullName,
        properties: {
          ...dimensions,
          ...appInsightsData,
          "webchat:level": level,
        },
      });
    } else if (type === "exception") {
      appInsights.trackException({ exception: error });
    } else if (type === "timingstart") {
      appInsights.startTrackEvent(fullName);
    } else if (type === "timingend") {
      appInsights.stopTrackEvent(fullName, { ...dimensions });
    }
  };
```

This allows me to add onTelemetry to the ReactWebChat like you indicated: 
```
<ReactWebChat
                    adaptiveCardsHostConfig={properties.adaptiveCardsHostConfig}
                    directLine={directLinev2}
                    userId={`dl_${props.userId}`}
                    styleOptions={styleOptions}
                    onTelemetry={handleTelemetry}
                    webSpeechPonyfillFactory={botPonyfill}
                    className="novaWebChat2"
                  />
```

This worked for me

**Comment by ivanELEC** [comment]
Update that I forgot to include here 

> Hello Steven,
> 
> Thanks, I ended up succeeding by using the Microsoft Application Insight SDK:
> https://www.npmjs.com/package/@microsoft/applicationinsights-web
> 
> I initialised the appInsights object:
> 
> ```
> //initialize telemetry app insights and set static records
>   let appInsights = new ApplicationInsights({
>     config: {
>       instrumentationKey: props.appInsightIKey,
>       extensions: [reactAI],
>     },
>   });
>   //load application insights
>   appInsights.loadAppInsights();
> ```
> 
> Once I have my direct line I populate the appInsight objects context properties so that the logs are traceable:
> 
> ```
> if (appInsights.context) {
>                 //add userId and conversationID to appInsights and save to state
>                 appInsights.context.application.ver = "1.0";
>                 appInsights.context.session.acquisitionDate = Date.now();
>                 appInsights.context.session.id = directLinev2.botConversationId;
>                 appInsights.context.user.accountId = props.userId;
>               }
> ```
> 
> then I use the handleTelemetry function that's in the example provided:
> 
> ```
> //function for generating telemetry
>   const handleTelemetry = (event) => {
>     const {
>       data,
>       dimensions,
>       duration,
>       error,
>       fatal,
>       level,
>       name,
>       type,
>     } = event;
>     const fullName = `webchatui:${name}`;
> 
>     console.group(`onTelemetry ("${type}")`);
>     console.log({ name, data, dimensions, duration, error });
>     console.groupEnd();
> 
>     if (type === "event") {
>       const appInsightsData =
>         typeof data === "number" || typeof data === "string"
>           ? { [name]: data }
>           : Object.entries(data || {}).reduce(
>               (data, [key, value]) => ({ ...data, [`${name}:${key}`]: value }),
>               {}
>             );
> 
>       appInsights.trackEvent({
>         name: fullName,
>         properties: {
>           ...dimensions,
>           ...appInsightsData,
>           "webchat:level": level,
>         },
>       });
>     } else if (type === "exception") {
>       appInsights.trackException({ exception: error });
>     } else if (type === "timingstart") {
>       appInsights.startTrackEvent(fullName);
>     } else if (type === "timingend") {
>       appInsights.stopTrackEvent(fullName, { ...dimensions });
>     }
>   };
> ```
> 
> This allows me to add onTelemetry to the ReactWebChat like you indicated:
> 
> ```
> <ReactWebChat
>                     adaptiveCardsHostConfig={properties.adaptiveCardsHostConfig}
>                     directLine={directLinev2}
>                     userId={`dl_${props.userId}`}
>                     styleOptions={styleOptions}
>                     onTelemetry={handleTelemetry}
>                     webSpeechPonyfillFactory={botPonyfill}
>                     className="novaWebChat2"
>                   />
> ```
> 
> This worked for me

The handleTelemetry part I did was wrong and following your example more worked - not making a telemetryInitializer function like you did meant that the context values weren't being set, looks more like this

```
const telemetryInitializer = () => {
        //const { content: webChatUIVersion } =
        //  document.querySelector( 'head meta[name="botframework-webchat:ui:version"]' ) || {};

       // appInsights.properties.context.application.ver = webChatUIVersion;
        appInsights.properties.context.session.acquisitionDate = Date.now();
        appInsights.properties.context.session.id = conversationID;
        appInsights.properties.context.user.accountId = userID;
      };

     // aisdk.queue ? aisdk.queue.push( telemetryInitializer ) : telemetryInitializer(); moved to before track event
      
      const handleTelemetry = event => {
        const { data, dimensions, duration, error, fatal, level, name, type } = event;
        const fullName = `webchatui:${ name }`;

        console.group( `onTelemetry ("${ type }")` );
        console.log( { name, data, dimensions, duration, error } );
        console.groupEnd();

        if ( type === 'event' ) {
          // "event.data" could be a non-negative finite number, a string, or a map with multiple values.
          // When we track them on Application Insights, we will prefix them for categorization.
          const appInsightsData =
            typeof data === 'number' || typeof data === 'string'
              ? { [ name ]: data }
              : Object.entries( data || {} ).reduce(
                ( data, [ key, value ] ) => ( { ...data, [ `${ name }:${ key }` ]: value } ),
                {}
              );
          telemetryInitializer();
          appInsights.trackEvent( {
            name: fullName,
            properties: {
              ...dimensions,
              ...appInsightsData,
              'webchat:level': level
            }
          } );
        } else if ( type === 'exception' ) {
          appInsights.trackException( { exception: error } );
        } else if ( type === 'timingstart' ) {
          appInsights.startTrackEvent( fullName );
        } else if ( type === 'timingend' ) {
          // Application Insights modify the "dimensions" argument. We need to clone it to prevent it from being modified.
          appInsights.stopTrackEvent( fullName, { ...dimensions } );
        }
      };
```
