### ISSUE TITLE
bug: The WebChat container's role should not always be 'complementary' [screen reader accessibility]

### ISSUE THREAD

**Issue by nfreear** [microsoft/BotFramework-WebChat#3658]
Hi,

 * Relates to :~ #3655.

## Version

* WebChat.js version :~ 4.10.1;
* JS :~ https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js;

## Describe the bug

Sometimes a Chat-bot will be _additional_ content on the Web-page, set apart from the `main` content. However, other times a Chat-bot will be the only or main focus of the Web-page.

In these cases `role=complementary` is not appropriate, and will confuse screen reader users, who may rely on landmark roles for navigation.

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior

Give implementors / developers the option to modify the container-role via [defaultStyleOptions.js](https://github.com/microsoft/BotFramework-WebChat/blob/v4.11.0/packages/component/src/Styles/defaultStyleOptions.js):

```js
   containerRole: 'complementary', // WAI-ARIA landmark role. Suggestions: 'complementary' or 'region'. Defaults to 'complementary'.
```

The value would be used in :~ https://github.com/microsoft/BotFramework-WebChat/blob/v4.11.0/packages/component/src/BasicWebChat.js#L71;

For example, `role={containerRole}`:

```js
  return (
    <AccessKeySinkSurface ... ... >
      <TypeFocusSinkBox
        className={sinkClassName}
        disabled={disabled}
        ref={transcriptFocusRef}
        role={containerRole}
        sendFocusRef={sendBoxFocusRef}
      >
        // ...
      </TypeFocusSinkBox>
    </AccessKeySinkSurface>
  );
```

Please let me know what you think of this proposal.

Yours,

Nick

## Additional context

[Bug]

**Comment by gabog** [comment]
Hi @compulim, can you review this issue?

**Comment by nfreear** [comment]
Hi @compulim,

I'm working on a fix based on my proposal above ...  hopefully have a pull-request to follow ;).

Nick

**Comment by corinagum** [comment]
Assigning to @nfreear. In the future, please provide repro steps as requested in the template.

**Comment by compulim** [comment]
I think it is better to put `role` attribute on the `<ReactWebChat>`, for example:

```html
<ReactWebChat directLine={...} role="region" />
```

My arguments:
- We do have `dir` attribute too, it is not using style options
- It seems more natural and intuitive

For composition version of Web Chat, it will be on the `<BasicWebChat>` component.

```html
<Composer directLine={...}>
  <BasicWebChat role="region" />
</Composer>
```

**Comment by nfreear** [comment]
Hi @compulim,

Thanks for the suggestion -- accepted.

Can I check my understanding? You're saying use the `role` in [`ReactWebChat.js`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/component/src/ReactWebChat.js#L17):

```js
  <BasicWebChat className={className} role={containerRole} />
```

Is that correct?

Thanks,

Nick

**Comment by nfreear** [comment]
Hi @compulim & @corinagum,

I have a question in my previous comment ... @compulim Are you able to answer so I can complete PR #3669, and get it reviewed please?

Thanks,

Nick

**Comment by compulim** [comment]
It will become:

```js
const ReactWebChat = ({ className, role, ...composerProps }) => (
  <Composer {...composerProps}>
    <BasicWebChat className={className} role={role} />
  </Composer>
);
```

When end-developer render Web Chat, their call will looks like:

```
ReactDOM.render(
  <ReactWebChat
    className="my-chat-ui"
    directLine={...}
    role="region"
  />
);
```
