### ISSUE TITLE
Need Web Chat JS

### ISSUE THREAD

**Issue by AlavudeenRafiq** [Microsoft/BotFramework-WebChat#366]
I am able to create my Web Chat window(without using Iframe) by using the minified Web Chat JS(https://unpkg.com/botframework-webchat@0.10.0/botchat.js) and Web Chat CSS(https://unpkg.com/botframework-webchat@0.10.0/botchat.css).

But in-order to customize my Web Chat window (For E.g.: to add  buttons), I need un-minified JS. 

So, kindly guide me to get the required JS to customize my Web Chat window.

**Comment by billba** [comment]
Simply follow the instructions in the README to [build](https://github.com/Microsoft/BotFramework-WebChat#building-webchat) and [alter](https://github.com/Microsoft/BotFramework-WebChat#customizing-webchat).
