### ISSUE TITLE
Webchat V4 Adaptive carousel cards are not displaying in proper format

### ISSUE THREAD

**Issue by vpysaran** [microsoft/BotFramework-WebChat#3660]
In Webchat v4 we are using adaptive card to display data in table format with carousel, on each card displaying 5 records but cards are rendering side by side as below.
Issue screenshot:
![image](https://user-images.githubusercontent.com/18364383/103980461-f19d3e80-51a5-11eb-9300-8cb16dddca31.png)
We want to display as below
Expected result:
![image](https://user-images.githubusercontent.com/18364383/103980238-82274f00-51a5-11eb-87cf-f693c4a131f1.png)

**Comment by gabog** [comment]
Hi @compulim, can you review this issue?

**Comment by compulim** [comment]
Depends on the width of the chat UI, the carousel flipper will show up when the space become tighter.

If you want to force it to show as a vertical stack, you can set the `attachmentLayout` to `stacked` when you send the activity. You can find the `attachmentLayout` in [this article](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#activity-object).
