### ISSUE TITLE
(R) is getting automatically converted to Registered Symbol

### ISSUE THREAD

**Issue by Monomoy88** [microsoft/BotFramework-WebChat#3665]
## Version
4.10.1

## Problem

Conversation of my bot is driven by QnAMaker.
As per business requirement at certain stage bot response must include D(R)O7 character sequence.
In QnA maker I'm able to store it in same way but (R) is getting converted to registered symbol in bot conversation like this - D®O7.
This is undesirable to our client.

In C# code I can't notice any conversion of character sequence but in webchat I'm not able to restrict this auto conversion. How can I handle this scenario?

**Comment by dmvtech** [comment]
Hi @Monomoy88 I am looking into this to see what alternatives are available.

**Comment by dmvtech** [comment]
Hi @Monomoy88 You need to escape the parenthesis in the answer. Like so:
`D\(R\)O7`

See more info here:
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/reference-markdown-format#supported-markdown-format

**Comment by Monomoy88** [comment]
Thanks it resolved.
