### ISSUE TITLE
MS Teams 'End of Conversation' activity

### ISSUE THREAD

**Issue by selvaduraiece** [microsoft/BotFramework-WebChat#3675]
Hi Team,

I have a built bot using Bot composer. After specific time I am ending the conversation using 'End of Conversation' activity. I can achieve the same using Webchat but unfortunately I am not able to do the same with 'MS Teams'

Can u help me with the same?
 If 'End of Conversation' activity is not supported in MS teams, is there any work around to achieve the same?

**Comment by v-kydela** [comment]
Thank you for the question, @selvaduraiece. The Bot Framework doesn't really have a concept of "ending a conversation" that's consistent across channels. Each channel has its own idea of what a conversation is, how to end it, and even whether or not it can be ended. Teams is an example of a channel with conversations that cannot be ended. That is to say, a Teams conversation lasts forever.

If you have more questions, please follow the advice in blurb you saw when making your issue:

> # 🚨 The issue tracker is not for implementation questions 🚨
> 
> # Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/master/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.
> 
> 
> 
> This repo focuses on the development of Web Chat, a client/channel for Bot Framework. If you have questions on implementation or about other features of Bot Framework, please see the below list to direct your questions to the correct repo or site.
> 
> | Topic                       | Description                                                  | Link                                                    |
> | --------------------------- | ------------------------------------------------------------ | ------------------------------------------------------- |
> | Web Chat 'How to' Questions | Ask implementation questions about Web Chat                  | https://stackoverflow.com/questions/tagged/web-chat     |
> | Bot Framework Questions     | Ask implementation questions related to the BotFramework SDK | https://stackoverflow.com/questions/tagged/botframework |

Please note this part of the Technical Support Guide in particular:

> The question is **NOT** related to Web Chat if:
> 
> 1. You are not using Web Chat
>    1. Does the project use Microsoft Teams or another channel for your bot? If yes, you will probably not find helpful information here
