### ISSUE TITLE
Sign out not working with direct line speech adapters

### ISSUE THREAD

**Issue by ObsidianDelta** [microsoft/BotFramework-WebChat#3677]
## Version

4.11.0 CDN

## Describe the bug

Our bot uses oauth cards to sign in and out our users. When we use just the direct line i.e: 

```js
 <script>
        (async function () {
           const res = await fetch('@settings.TokenURL', { method: 'POST' });
           const { token } = await res.json();

            window.WebChat.renderWebChat(
                {
                   
                    directLine: window.WebChat.createDirectLine({ token })
                },
                document.getElementById('webchat')
            );

            document.querySelector('#webchat > *').focus();
        })().catch(err => console.error(err));

    </script>
```

... every thing is fine ... but when we use direct line speech we get an error

```js
<script>
        (async function () {

           const adapters = await window.WebChat.createDirectLineSpeechAdapters({
                    fetchCredentials: {
                    region: 'westus2',
                    subscriptionKey: '<Our Cognitive Service Speech Key>'
               }
            });

            window.WebChat.renderWebChat(
                {
                    ...adapters
                
                },
                document.getElementById('webchat')
            );

            document.querySelector('#webchat > *').focus();
        })().catch(err => console.error(err));

    </script>
```

The error we get is as follows: 

`<img width="1917" alt="DirectLineSpeechError" src="https://user-images.githubusercontent.com/31521018/105133034-4ef89000-5ac2-11eb-910b-f323666b8530.png">`

As you can see in addition to getting errors for : `https://api.botframework.com/api/usertoken/GetToken?userId=<Guid>%7C0000&connectionName=BotOAuthConnection2&channelId=directlinespeech`

We get errors for making this calls as well: `https://api.botframework.com/api/usertoken/SignOut?userId=<Guid>%7C0000&connectionName=BotOAuthConnection2&channelId=directlinespeech`

## Steps to reproduce

1. Create a bot with login and logout capabilities
2. Implement direct line speech capability
3. Try to logout 

## Expected behavior

We expect it the sign out behavior to be exactly the same as when we use just the direct line without the speech. 

## Additional context

Also with direct line speech we are get "Magic Numbers" when trying to login. We also use Azure AD2 B2C for login. 

[Bug]

**Comment by corinagum** [comment]
Magic numbers is required for DLS. @Zerryth could you investigate?

**Comment by ObsidianDelta** [comment]
Thanks @corinagum for the quick reply. I am fine with magic numbers ... just need to get the sign out working. Thanks.

**Comment by Zerryth** [comment]
@ObsidianDelta, just in case there's an issue on the SDK end, which language is the bot built in? JS?

**Comment by ObsidianDelta** [comment]
@Zerryth We have built the bot in C#.

**Comment by Zerryth** [comment]
Hmm...I'm experiencing an error as well plugging in:
1. [C# sample 18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/18.bot-authentication) (bot)
2. [Web Chat sample 03.speech/a.direct-line-speech](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/03.speech/a.direct-line-speech) (Web Chat to talk to bot)

It's the same as you, where talking to "regular" DirectLine works fine, however trying to use DLS, it throws.

I'm experience a different issue than you with regards to the error, however.
Sometimes the mic closes immediately after clicking it. Other times the mic stays on forever, after throwing 
![image](https://user-images.githubusercontent.com/35248895/105394302-42635d00-5bd2-11eb-99c2-5427e317e66d.png)

![image](https://user-images.githubusercontent.com/35248895/105394404-5f982b80-5bd2-11eb-8dd4-4f02838427b6.png)

I'll dig further into what's happening here and update you.

**Comment by Zerryth** [comment]
I managed to repro the behavior you reported, where signing in is possible, however signing out breaks.
So I'm still trying to get a hold of and confirm with someone on the team who owns DLS or auth, however I believe DLS does not actually support `OAuthPrompt`. (I mean if you think about it, in a speech scenario it would be difficult for someone to verbally sign in -- however I do see how it breaks regardless if the mic is used or not, even if we're typing/clicking the responses to the bot when DLS is enabled)

Once I'll let you know once we confirm one way or another

**Comment by Zerryth** [comment]
Chiming in here again -- I have *still* not received any responses from the people I've reached out to, trying to confirm whether or not Direct Line Speech actually supports OAuthPrompt.

Additionally, this seems to be more of service issue with Direct Line Speech rather than an issue with Web Chat or the Bot Framework SDK, because ultimately if DLS doesn't support OAuthPrompt, then it wouldn't work in Web Chat or any other channel (like Teams) for example.

**Comment by corinagum** [comment]
@Zerryth thanks for the update. I'm closing this as a non-Web Chat issue. If we get pushback from the service team we can always re-open.
