### ISSUE TITLE
Allow ponyfilling window.open

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#368]
Right now we call `window.open(url)` for card actions. The default in most browsers is to open the url in a new tab, but some might like to open it in a new window, etc.

My proposal is to add `urlTarget?:string` and `urlTitle?:string` to `ChatProps`. If supplied we'd pass them as the second and third parameter to `window.open`.

**Comment by danmarshall** [comment]
is it Title or "specs"
https://www.w3schools.com/jsref/met_win_open.asp

**Comment by billba** [comment]
I was going by the TypeScript, but even then I got it wrong:

```typescript
Window.open(url?: string, target?: string, features?: string, replace?: boolean): Window
```

**Comment by corinagum** [comment]
Related to #1504
