### ISSUE TITLE
Handoff to a human agent

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3680]
I can't figure out how to implement handoff to a human agent with webchat channel. We have a bot service that is in Azure which using a Webchat channel. We like to have a live agent engagement if user question cannot be answered by the bot. Is this possible to do with webchat?

What I am thinking to do is create an agent hub (web based) for live agent with a webhook endpoint which will get requests and show a queue of conversations waiting to be handled by a live agent. When an agent clicks on a request the agent hub will lunch the Webchat and add the agent to the existing conversation. For this I should be able to add the agent to the existing conversation by sending some kind of a webchat built-in event. I can't find anything how to add a user to an existing conversation within WebChat.
Or are there better ways of handling handoff to a live agent?

**Comment by arturl** [comment]
@arman-g, take a look here: http://aka.ms/bfhandoff where we describe the recommended patterns and refer to examples on GitHub. The [LivePerson sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonProxyBot) might be of interest to you. You can use it a model for your own agent hub.

**Comment by arman-g** [comment]
> @arman-g, take a look here: http://aka.ms/bfhandoff where we describe the recommended patterns and refer to examples on GitHub. The [LivePerson sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/handoff-library/csharp_dotnetcore/samples/LivePersonProxyBot) might be of interest to you. You can use it a model for your own agent hub.

Thank you for your response. I have seen all these examples and honestly it is very difficult to understand what is going on. I think it would be good to have more detailed explanation of key components (what they do and why they needed) so one can build on their solution. For example in the proxy example you provided there is a reference to the connector which is a different project. Do we need it in proxy approach? how about bot as an agent etc?
Anyway, again thank you for your time. I guess I have to figure it out myself or suggest my client to use different frameworks for human handoff since bot framework clearly not matured enough for this.

**Comment by arturl** [comment]
@arman-g, the different project is needed because it is a reusable component. If you have specific questions I can answer, either here or email me directly at arturl (is my alias in microsoft.com)

**Comment by anjukv** [comment]
@arman-g , did you figure out the solution?
I'm also stuck at the exact same issue.
I've my own agent hub, but how can he join the conversation and how to raise the built-in event
