### ISSUE TITLE
long URLs are not clipped in a narrow webchat

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#369]
![image](https://cloud.githubusercontent.com/assets/11507384/23818531/eec9576a-05b0-11e7-916b-734d76deeea1.png)
Also, visited links are purple.  Might want to pick another color?

**Comment by photodesignch** [comment]
I've tried with markdown syntax and pure html linkage with varies of window sizes. I can not repro hyperlink into the chatbox, and return message from server is breaking words evently at end of the chat bubble. I can not reproduce the same situation and looks like it's been fixed.
