### ISSUE TITLE
"Enter a new answer here" not returning new answer or saving new answer suggestion

### ISSUE THREAD

**Issue by akamwand** [microsoft/BotFramework-WebChat#3690]
I was unable to find the answer to this problem in StackOverflow or in MS Documents for Web Chat.

The issue I am facing is that I have only 2-3 questions out of around 200 QnA pairs that are not suggesting the correct answer passage when I go to 'inspect' the answer.

I manually enter the answer passage I want in the "Enter a new answer here" field, and then select Save and Train after the new answer passage is selected. When I test QnA with the same question, not only does the new answer passage not come up as the answer for the question, but the new answer passage is not even saved when I go to 'inspect' the same question.

I have tried entering in specific QnA pairs with multiple variations of the question/answer pair that I am needing confirmed, but nothing in regards to word type or case sensitivity returns the correct answer for these 2-3 questions. I have also located all QnA pairs with vaguely-related question phrasing, and removed those QnA pairs entirely in order to get a correct answer return but that did not work either.

Not sure if anyone else has had a similar issue, or if I am mis-understanding the intended usage of the "Enter a new answer here" field. I'm unable to ask this question to MS either without purchasing an Azure support plan.

I am not implementing QnA maker with dedicated code, just using the Direct Line Channel and custom styling options.

**Comment by stevkan** [comment]
This is an issue with the Qna Maker service and not with Web Chat. You can find assistance by posting your question in their [Customer Feedback & Ideas for Cognitive Services](https://feedback.azure.com/forums/932041-cognitive-services) forum without need of an Azure Support Plan.
