### ISSUE TITLE
Embedding webchat on serviceNow

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/BotFramework-WebChat#3695]
Hi All,

i am trying to embed latest  JavaScript or react webchat on Service Now. i am facing one unresolved issue in JavaScript webchat. please see below screenshot.
 
![image](https://user-images.githubusercontent.com/34365788/106492656-2fa82c80-64de-11eb-95b7-3983823b15d4.png)

**FYI**
i am following this link properly :- https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/a.full-bundle

Similarly for React WebChat also i am getting issue which you can see on screenshot.

issue 1:-
![image](https://user-images.githubusercontent.com/34365788/106493202-d7255f00-64de-11eb-9534-f8b2227dc61e.png)

**Comment by stevkan** [comment]
@Bradrajkumar, how are you embedding the page? I don't know too much about Service Now, but I know one method of embedding is to configure an iFrame component. Is this how you are attempting this?

**Comment by Virtual-Josh** [comment]
@corinagum Is this ticket going to be in R12?

**Comment by corinagum** [comment]
@Virtual-Josh no, it is not scheduled as an action item. Since it is stale, I am closing this issue.
