### ISSUE TITLE
Change username in conversation

### ISSUE THREAD

**Issue by ap-teammobile** [Microsoft/BotFramework-WebChat#371]
This is probably more a Question than an Issue:
I developing a Node.js Azure Bot with a customized WebChat. I'm asking for the users name in the middle of the conversation, want to change it, and want the Webchat to display the updated Username.

Can't figure out, how to do that. Updating the sessions Data doesn't work (in Webchat and Emulator). Any suggestions? Thanks!

**Comment by billba** [comment]
The short answer is that WebChat isn't really designed for this, but you could certainly alter the code to make this happen.

The model is that the user name is passed as a property to WebChat during creation. We use that name when sending messages and when for displaying the sender's name under the message. You'd need to communicate the change from the server to client (probably using the [backchannel](https://github.com/Microsoft/BotFramework-WebChat#the-backchannel)) and change the display to use the new name. I don't recommend changing the underlying username as sent to Direct Line as I'm worried it might break the bot state mechanism.

To understand our current approach, it helps to think of WebChat as compared to other channels like Facebook Messenger, or Skype. There the user's identity is established and unchangeable by the bot. However I understand that WebChat will frequently be used in situations where the user is initially unknown or anonymous. I'll ponder this scenario but I suspect a change would require protocol support.
