### ISSUE TITLE
Bold is not applying for a text in Choice Prompt - BOT Framework

### ISSUE THREAD

**Issue by Ramesh-Pachunuri** [microsoft/BotFramework-WebChat#3724]
We have various prompts in BOT Framework and trying to apply the bold for text by using double asterisk symbols (**) and it is applying for all prompts except for Choice Prompt. How can we apply the same bold text style for Choice Prompt as well?

It is reddening like blow:

![image](https://user-images.githubusercontent.com/69036193/107926582-e7881000-6f9b-11eb-9fb2-967831076e2c.png)

This bold is working as expected in BOT Framework Emulator but not in Web Chat.

**Comment by v-kydela** [comment]
Thank you for the question, @Ramesh-Pachunuri 

That doesn't look like any choice prompt I've ever seen. What list style are you using? Can you provide the code you're using to instantiate and begin the choice prompt, as well as screenshots of the messages displayed in Emulator and Web Chat?

**Comment by Ramesh-Pachunuri** [comment]
@v-kydela  We have 5 style sheets found [here ](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/liststyle?view=botbuilder-ts-latest)and I am using HeroCard but the bold is applying in emulator but not in webchat. I tried with remaining 4 styles as well but none of them are working properly.
In Web Chat :
![image](https://user-images.githubusercontent.com/69036193/107995013-d7a41680-7003-11eb-90ce-a99315dc17d0.png)
In Emulator:
![image](https://user-images.githubusercontent.com/69036193/107995581-86e0ed80-7004-11eb-96e8-226b1fd3ba68.png)

**Comment by v-kydela** [comment]
@Ramesh-Pachunuri - Thank you for the screenshots. It looks like Web Chat isn't rendering Markdown in the text of a hero card, but it's strange that it would work in Emulator since Emulator uses Web Chat. Can you provide the code I asked for so we can try reproducing the problem on our end? A minimal example would be best.

**Comment by Ramesh-Pachunuri** [comment]
@v-kydela 
![image](https://user-images.githubusercontent.com/69036193/107997007-cf4dda80-7007-11eb-8953-add164baefe0.png)
In GetPromptOptions I am applying HeroCard style.
![image](https://user-images.githubusercontent.com/69036193/107997086-f6a4a780-7007-11eb-9e6d-0c1d4279eccf.png)

**Comment by v-kydela** [comment]
@Ramesh-Pachunuri - Please provide code as text and not screenshots

**Comment by Ramesh-Pachunuri** [comment]
@v-kydela 
internal async Task<DialogTurnResult> SeverityStepAsync(
            WaterfallStepContext stepContext,
            CancellationToken cancellationToken)
        {
            var botSession = stepContext.Options as BotSession;

            if (botSession.Incident.Severity == null)
            {
                var msg = ConfigStringResolver.Instance.GetConfigString("AskSeverity");
                var option1 = ConfigStringResolver.Instance.GetConfigString("Severity3Msg");
                var option2 = ConfigStringResolver.Instance.GetConfigString("Severity2Msg");

                this.Logger.LogBotMessage(botSession, msg);
                return await stepContext.PromptAsync(
                    nameof(ChoicePrompt),
                    PromptBuilder.GetPromptOptions(
                        stepContext.Context.Activity, msg, option1, option2),
                    cancellationToken);
            }

            return await stepContext.NextAsync(botSession, cancellationToken);
        }

**GetPromptOptions method to apply style sheet.**

public static PromptOptions GetPromptOptions(
            Activity activity,
            string replyMsg,
            string option1,
            string option2,
            ListStyle style = ListStyle.HeroCard)
        {
            var choices = GetChoiceList(option1, option2);
            return CreatePromptOptions(activity, replyMsg, choices, style);
        }

**Comment by Ramesh-Pachunuri** [comment]
@v-kydela Yes, we are reading the text from JSON file as a string. Sure I will try your suggestion as well. But if the bold is applying in emulator then it should also apply for Web Chat as well right? Why only having an issue with Web Chat?

**Comment by v-kydela** [comment]
@Ramesh-Pachunuri - It's possible to add components to or remove components from Web Chat. There are a few different Web Chat "bundles" which have different components. Not all Web Chat implementations have Markdown, and not all Web Chat implementations have cards. Can you provide your HTML so we can see how your Web Chat is configured?

It's worth noting that Markdown not working in cards [has been a problem in the past](https://github.com/microsoft/BotFramework-WebChat/issues/356), but it should work now. I should have asked this earlier, but can you render Markdown in normal activity text outside of a card? The fact that it's in a card may be a red herring, so we should determine that.

**Comment by compulim** [comment]
@v-kydlea if it can show Adaptive Card and hero card, it must be full bundle, which includes Markdown.

**Comment by Ramesh-Pachunuri** [comment]
@v-kydela :  Please let me know if you have the availability to discuss on teams?

**Comment by corinagum** [comment]
@v-kydela correct, AC can be added like in the Markdown sample. I think compulim was just pointing out that it's not available by default.

**Comment by v-kydela** [comment]
@Ramesh-Pachunuri - Are you still working on this?

**Comment by Ramesh-Pachunuri** [comment]
@v-kydela : I fixed the issue by moving the text out of the card.

**Comment by sahilquo** [comment]
Can you please share the sample code which fixes this issue?

**Comment by sahilquo** [comment]
Can you please share the sample code which fixes this issue?
