### ISSUE TITLE
Dynamically Update StyleSet

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-WebChat#3727]
It would be great if the Styleset could be updated dynamically after the webchat has been initialized. This allows for behavior like changing the BotIcon and enabling the attachment Icon when agent handoff is initialized.

Currently I use a event from the bot that gets picked up in the middleware and ads a handoff class to the chat container. Then CSS is used to switch bot icon and toggle attachment visibility by targeting that class.

Having the possibility to run something like webChat.update({styleSet}) without the need to reinitialize would be great.

**Comment by compulim** [comment]
It can be dynamically update. Just call `renderWebChat` again.

Since this is actually `ReactDOM.render` behind the scene, please make sure for props that don't need to change, such as `directLine` prop, should retain its original value (i.e. reference equal).

**Comment by cxbuilders** [comment]
@compulim Updating the styleOptions.hideUploadButton and calling renderWebchat again has no effect at all.

**Comment by cxbuilders** [comment]
@compulim nevermind, styleOptions is checked on reference as well, so when passing in a new object to styleOptions it gets parsed. Thanks for the help
