### ISSUE TITLE
Outgoing text is rendered as Markdown

### ISSUE THREAD

**Issue by maba4891** [Microsoft/BotFramework-WebChat#374]
Hi,

in my node.js bot I provide a simple builder.Prompts.text to ask the user for a date (I know that Prompts.time exists but since it does not seem to work with German dates yet I use Prompts.text for now and parse the date with the datejs module).

The problem is that if the user enters the date in a German format (e.g. "12. Februar 2017") and presses enter he sees "1. Februar 2017" as his input. The same is true for other dates (e.g. "20. August 2016") which are printed in a similar way like "1. August 2016". This also happens when I provide a date with a dot as an input to any other type of prompt.

Somehow the dot seems to be the problem here, 12 Februar 2017 works just fine (as does 12.2.2017). This problem seems to be only affecting the Emulator and the WebChat, on Skype and Facebook Messenger everything seems to be fine.

The funny thing is also that internally the right date is saved (even in the Emulator and WebChat), e.g. 12. Februar 2017 even if 1. Februar 2017 is printed (I save the input in session.userData). So it seems the problem is just the way the input is printed.

Any clue what is happening here?

Originally posted at https://github.com/Microsoft/BotBuilder/issues/2409 but moved to WebChat

**Comment by billba** [comment]
Weird. This has nothing to do with `Prompts` - it happens whenever you enter text in any context. I have changed the title of this issue accordingly.

This is almost certainly a bug in our Markdown parser.

**Comment by billba** [comment]
I realized what is happening. Markdown considers any text of the form "number. text" to be a numbered list. It will actually ignore the number and just start a `<ul>`.

I think this means we need to treat outgoing text as plain text, but we should run this up the flagpole.

**Comment by billba** [comment]
Let's treat outgoing text as plain text. We could certainly add `textFormat` as a prop to `Chat`, defaulting to 'plain', but I would hate to add a proliferation of options when no one is asking for it.

**Comment by billba** [comment]
Fixed by https://github.com/Microsoft/BotFramework-WebChat/pull/377

**Comment by alok-kumar** [comment]
I am using latest botchat CDN but unable to render HTML with iFrame in output. Example: Expected output is "Domestic travel related document</br><iframe src='https://onedrive.live.com/embed?resid=SDFSFSDSDF%211062' width='200' height='346' frameborder='0' scrolling='no'></iframe>"

But it is getting converted to "<p>Domestic travel related document&lt;/br&gt;&lt;iframe src=‘<a href="https://onedrive.live.com/embed?resid=SDFSFSDSDF%211062" target="_blank">https://onedrive.live.com/embed?resid=SDFSFSDSDF%211062</a>’ width=‘200’ height=‘346’ frameborder=‘0’ scrolling=‘no’&gt;&lt;/iframe&gt;</p>". 

Any help would be much appreciated. Thanks in advance.
