### ISSUE TITLE
Types definition for Typescript

### ISSUE THREAD

**Issue by hrazmsft** [microsoft/BotFramework-WebChat#3752]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Yes, there is no good type definition for this library. All the types are just `any`.

**Describe the suggestion or request in detail**

Please generate appropriate type definition for Typescript.

**Additional context**

![image](https://user-images.githubusercontent.com/66222191/108845662-5ee62100-75e6-11eb-900a-08e154f7e37e.png)

**Comment by corinagum** [comment]
This is related to #2100, which I am working on right now! 

This request increases the scope of adding types, so I'll keep this and add to our backlog. Thank you!

**Comment by hrazmsft** [comment]
@corinagum do you have any update?

**Comment by corinagum** [comment]
#2100 is complete, which doesn't fully cover the scope you are requesting. Right now the extra scope in this issue is not scheduled, unfortunately. #3856 is being addressed by compulim for the next milestone.

**Comment by hrazmsft** [comment]
I see thank you!
