### ISSUE TITLE
Update prop enterkeyhint for TextInput component

### ISSUE THREAD

**Issue by bertrod** [microsoft/BotFramework-WebChat#3762]
It seems the TextInput component is producing a warning when using the prop enterkeyhint for react >17. This is a known issue and it would be nice to get rid off the warning. It's just about updating the case of the prop to become enterKeyHint

https://github.com/necolas/react-native-web/issues/1778

**Comment by congysu** [comment]
@compulim could you please take a look at this?  Thanks.

**Comment by compulim** [comment]
We need to find a solution for this.

In React 16.8.6 (which we use as base version), it use `enterkeyhint` and doesn't accept `enterKeyHint`.

In higher version of React 16, it use `enterKeyHint` and not accepting `enterkeyhint`.

**Comment by corinagum** [comment]
I have added this to our list of bugs for fix consideration during R13.

**Comment by compulim** [comment]
This is already fixed in #3703 with the introduction of `useEnterKeyHint` hook.
