### ISSUE TITLE
CreateDirectLineAppServiceExtension is not working SharePoint web part

### ISSUE THREAD

**Issue by gourav-madan** [microsoft/BotFramework-WebChat#3771]
I have clone the repository from 
[Sharepoint React bot sample](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-bot-framework-secure) 

And trying to integrate DirectLineAppServiceExtension instead of DirectLine and did the below changes:
1) Changed the code in BotFrameworkChatv4.tsx
![image](https://user-images.githubusercontent.com/57317108/109626089-1be7f880-7b66-11eb-9788-9e50d8a25569.png)

2) I get the reference of above changes from my previous reported bug because the the same issue was coming in minimizable react app. Please find the below link for more details.
https://github.com/microsoft/BotFramework-WebChat/issues/3674

3) Error ScreenShot:
![image](https://user-images.githubusercontent.com/57317108/109626924-17700f80-7b67-11eb-80c6-b3e03d4bff59.png)

Please let me know how to make Bot working on Sharepoint website using directlineappserviceextension.

**Comment by compulim** [comment]
The code you show is wrong on using `useEffect` and `useState` with an async function.

It would allows `directLine` state to be `undefined` and pass it to `<ReactWebChat>`. And that's what the error message is talking about: "The prop directLine is marked as required, but its value is undefined".

Instead, you should wait until `directLine` state is completely initialized, before passing it to `<ReactWebChat>`. I.e. wait until `setDirectLine` function is called.
