### ISSUE TITLE
DirectLineSpeech doesn't let me configure key properties for the conversation.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-WebChat#3775]
## Version
4.12

## Describe the bug
I need to be able to 
* set the **user.id**, **user.name** and **additional metadata** 
* set the **conversation.id**, **conversation.name** and **additional metadata**
* set the **channelData**

The whole point is that DirectLineSpeech enables **my** web page to talk to **my** bot.  I need control over the metadata I send to my bot. 

## Steps to reproduce
I am only able to set the **user.id**, **not** the **user.name** or custom properties.
I am **not** able to set the **conversation.id** or **other conversation properties.**
I am **not** able to to use ChannelData to send my own data.

## Expected behavior
That I can actually use the activity protocol the way it was designed to be used.

## Additional context

[Bug]

**Comment by corinagum** [comment]
Extra info for anyone dealing with the same problems:

- user.id and user.name can be set as seen below:
```
const adapters = await window.WebChat.createDirectLineSpeechAdapters({
  fetchCredentials: ...,
  userID: 'u-12345',
  username: 'user'
});
```
- per @compulim, conversation.id/name cannot be set
- Here's the work item for setting channelData: https://github.com/microsoft/BotFramework-WebChat/issues/2680

I'll keep updating as discussion is ongoing.

**Comment by Kaiqb** [comment]
Re: `conversation` properties, Direct Line Speech does not support it.

**Comment by corinagum** [comment]
Consolidating: closing in favor of #2680 - please track this work over there.
