### ISSUE TITLE
Webchat not populating localTimestamp and localTimezone properties 

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-WebChat#3788]
## Describe the bug
Customer wants to know the following which we do not have an answer for:

I would like to know the reason why localTimezone and localTimestamp in Activity (Microsoft.Bot.Schema.Activity) are always empty when running as App Service. When we run on emulator on our local Mac machine, it always has a valid timestamp and timezone

## Steps to reproduce
Confirmed that localTimestamp is not populated from webchat when bot is published in Azure. I am not sure how customer is accessing localTimezone property as the IMessageActivity interface that we use does not implement that property but the generic Activity does have a localTimezone property.

## Additional context

[Bug]

**Comment by Kaiqb** [comment]
From Eric: 
I’m not sure how to redirect this.  I looked into it a little, and looks like we are not setting localTimestamp or localTimezone from webchat or directlinejs:
 
LocalTimestamp field is empty:
https://github.com/microsoft/BotFramework-DirectLineJS/issues/248
 
Emulator is setting localTimestamp here:
https://github.com/microsoft/BotFramework-Emulator/blob/main/packages/app/main/src/server/state/conversation.ts#L534
 
Should we re-open this DL-JS issue, or do you have a different recommendation for this?

**Comment by EricDahlvang** [comment]
@corinagum it is the latter  (when the activity arrives at the bot, these fields are not populated)

**Comment by corinagum** [comment]
This is not just DLJS but would need to be added to any chat adapter.

**Comment by compulim** [comment]
When working on this, please also fix #2588.

**Comment by compulim** [comment]
Working on this now.

[Activity spec](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#activity-object):

| Property | Type | Description |
| -- | -- | -- |
| localTimestamp | string | Date and time that the message was sent in the local time zone, expressed in&nbsp;ISO-8601&nbsp;format. |
| localTimezone | string | Contains the name of the local timezone of the message, expressed in IANA Time Zone database format. For example, America/Los_Angeles. |

### `localTimestamp`

(TBC)

### `localTimezone`

`new Intl.DateTimeFormat().resolvedOptions().timeZone` will get the local timezone.

![image](https://user-images.githubusercontent.com/1622400/118872585-8d9a2d80-b89d-11eb-8636-4e9c5c708fc5.png)

**Comment by compulim** [comment]
Even though Web Chat send out an activity to ABS with `localTimestamp`. The bot developer will need to retrieve them using `rawLocalTimestamp`.

Activity received on the bot side, after Web Chat sent out an activity with time zone of Japan.

```json
{
  "type": "message",
  "id": "3HIorx83j1xAJSLl4II4sK-o|0000000",
  "timestamp": "2021-05-20T01:23:50.933Z",
  "localTimestamp": "2021-05-20T01:23:51.000Z",
  "localTimezone": "Asia/Tokyo",
  "serviceUrl": "https://directline.botframework.com/",
  "channelId": "directline",
  "from": {
    "id": "dl_2793ad24dffe05f3fdf13cc683dd69ba",
    "name": ""
  },
  "conversation": {
    "id": "3HIorx83j1xAJSLl4II4sK-o"
  },
  "recipient": {
    "id": "webchat-mockbot@WYDIyKwAZCw",
    "name": "webchat-mockbot"
  },
  "textFormat": "plain",
  "locale": "en-US",
  "text": "dump-activity",
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true
    }
  ],
  "channelData": {
    "clientActivityID": "1621473831109mux9a3motu",
    "clientTimestamp": "2021-05-20T01:23:51.109Z"
  },
  "rawTimestamp": "2021-05-20T01:23:50.9334271Z",
  "rawLocalTimestamp": "2021-05-20T10:23:51+09:00",
  "callerId": "urn:botframework:azure"
}
```

**Comment by HiroClubLabs** [comment]
Thank you.

What do we need to upgrade to take an advantage of the localtimestamp feature?

Thanks,
Hiro


Sent with BlackBerry Work
(www.blackberry.com)


From: William Wong ***@***.******@***.***>>
Date: Wednesday, May 19, 2021, 6:33 PM
To: microsoft/BotFramework-WebChat ***@***.******@***.***>>
Cc: Yamaguchi.Hiro ***@***.******@***.***>>, Manual ***@***.******@***.***>>
Subject: Re: [microsoft/BotFramework-WebChat] Webchat not populating localTimestamp and localTimezone properties (#3788)

ATTENTION: This e-mail came from an external source. Do not open attachments or click on links from unknown or unexpected emails.


Even though Web Chat send out an activity to ABS with localTimestamp. The bot developer will need to retrieve them using rawLocalTimestamp.

Activity received on the bot side, after Web Chat sent out an activity with time zone of Japan.

{
  "type": "message",
  "id": "3HIorx83j1xAJSLl4II4sK-o|0000000",
  "timestamp": "2021-05-20T01:23:50.933Z",
  "localTimestamp": "2021-05-20T01:23:51.000Z",
  "localTimezone": "Asia/Tokyo",
  "serviceUrl": "https://directline.botframework.com/",
  "channelId": "directline",
  "from": {
    "id": "dl_2793ad24dffe05f3fdf13cc683dd69ba",
    "name": ""
  },
  "conversation": {
    "id": "3HIorx83j1xAJSLl4II4sK-o"
  },
  "recipient": {
    "id": "webchat-mockbot@WYDIyKwAZCw",
    "name": "webchat-mockbot"
  },
  "textFormat": "plain",
  "locale": "en-US",
  "text": "dump-activity",
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true
    }
  ],
  "channelData": {
    "clientActivityID": "1621473831109mux9a3motu",
    "clientTimestamp": "2021-05-20T01:23:51.109Z"
  },
  "rawTimestamp": "2021-05-20T01:23:50.9334271Z",
  "rawLocalTimestamp": "2021-05-20T10:23:51+09:00",
  "callerId": "urn:botframework:azure"
}

-
