### ISSUE TITLE
When the version 4.12 will be available in cdn webchat js

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/BotFramework-WebChat#3793]
[Question]

When the version 4.12 will be available in CDN webchat JS:

I have referred to the fixes related to accessibility in PR #3703 which are merged to master some days back. 
I want to know when these changes will be available in the CDN URL below:

https://cdn.botframework.com/botframework-webchat/latest/webchat.js

As per my understanding we don't need to do any change to update to this version from client-side implementation - correct me if i am wrong.

**Comment by corinagum** [comment]
4.12 is released and can be used by locking down the Web Chat version, which is our recommendation for public bots.

**Comment by SSanjeevi** [comment]
Am using it as an html JS file reference with this CDN URL: https://cdn.botframework.com/botframework-webchat/latest/webchat.js

do we have similar URL for 4.12?

**Comment by corinagum** [comment]
https://cdn.botframework.com/botframework-webchat/4.12.0/webchat.js
