### ISSUE TITLE
Keyboard Navigation Broken 4.12+ for React

### ISSUE THREAD

**Issue by nephinj** [microsoft/BotFramework-WebChat#3799]
Since upgrading to version 4.12.0 and 4.12.1 users can no longer seem to tab into links or card buttons in the chat.  

## Screenshots
Tab on Answer
![image](https://user-images.githubusercontent.com/2805536/111379193-38f9ec80-8679-11eb-9fee-6253c431f6eb.png)

Next Shift-Tab
![image](https://user-images.githubusercontent.com/2805536/111473451-6ee2b380-8701-11eb-83c5-1ca5c9f957e4.png)

## Version
4.12.0 and 4.12.1

## Describe the bug
Starting in the search box and hitting Shift-Tab twice takes you to the transcript, hitting Shift-Tab again takes you to the answer with a dashed border and then hitting it a forth time it jumps out of the conversation window to the minimize button.

## Steps to reproduce
1. Go to https://microsoft.github.io/BotFramework-WebChat/06.recomposing-ui/a.minimizable-web-chat/
2. Click on search box
3. Type help and press Enter
4. Hit Shift-Tab three times to get to the answer
5. Hit Shift-Tab again

## Expected behavior
Expected behavior after hitting Shift-Tab beyond the dashed answer is that it goes to the buttons inside the response and then to the next question/answer pair.  Disabled users don't seem to have a way to get to buttons or links in the answer or previous question answer pairs.  

Tried various combinations of Tab and Up/Down keys but nothing seems to work.

[Bug][Area: Accessibility]

**Comment by corinagum** [comment]
Looks like you may have been missed pressing enter on the focused card to enter into interactable content.

https://github.com/microsoft/BotFramework-WebChat/issues/3783#issuecomment-794260933
#3703 

This is a feature change. Please see the above for more details. Our root README also goes into release details.
