### ISSUE TITLE
Sample Bot: Custom-components: Reaction-buttons is broken

### ISSUE THREAD

**Issue by 5Heinzelmann** [microsoft/BotFramework-WebChat#3800]
https://microsoft.github.io/BotFramework-WebChat/05.custom-components/d.reaction-buttons/ 

## Screenshots

![Screenshot](https://i.imgur.com/JtPQOj9.png)

## Steps to reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/05.custom-components/d.reaction-buttons/  
1. Text Hi
2. Text Help
3. Wait a few seconds
1. See error

## Expected behavior

Bot answers with default help text and shows reaction buttons in front of each bot message.

## Additional context

Same for Chrome and Firefox (I used chrome for Screenshot)

[Bug]

**Comment by corinagum** [comment]
Thanks for filing this bug. We did make recent changes to that sample, so we'll need to investigate what went wrong.

@compulim should we roll back this sample? Then one of us can further investigate when there's a little more time.

**Comment by corinagum** [comment]
@5Heinzelmann 
Here's a link to a previous iteration of the sample code: https://github.com/microsoft/BotFramework-WebChat/blob/7e27ab3c32055a4b3984b28c2938caec0ac14805/samples/05.custom-components/d.reaction-buttons/index.html

If you need to implement this immediately, this is a slightly outdated but working version of the sample.

**Comment by 5Heinzelmann** [comment]
@corinagum Thanks for providing the link to the sample code

**Comment by corinagum** [comment]
#3632 is still open and in need of validation, so I'm closing this as a duplicate in favor of that issue. I will copy over the screencap @5Heinzelmann provided for further clarity.
