### ISSUE TITLE
How to tab to recent activity after a recent activity message received after clicking on a button with space bar

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/BotFramework-WebChat#3801]
[Question]
How to tab to recent activity after a recent activity message received after clicking on a button with space bar?

Is there a feature to activate the next message with action buttons on clicking any of the button using tab and space?

**Comment by corinagum** [comment]
Please look at our documentation on transcript navigation:
https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/ACCESSIBILITY.md#user-story-2


- The 'New message' button will appear when the user is scrolled up in the transcript and a new activity comes from the bot. 
- Press <kbd>ESCAPE</kbd> to exit focus from inside the Adaptive Card and return focus to the attachment container. Alternatively, if the user is focused on the last interactable element in the card, they can press <kbd>TAB</kbd>.
- To navigate to the 'New message' button, press <kbd>TAB</kbd> once more. Focus is now on the 'New messages' button.
- Press <kbd>Enter</kbd>. This will bring transcript focus to the most recent activity.

**Comment by SSanjeevi** [comment]
Thanks for the info, but am asking on the android mobile using gestures, how to achieve it.
