### ISSUE TITLE
After recent webchat JS changes- Date fields no longer render in webchat

### ISSUE THREAD

**Issue by 007-fr** [microsoft/BotFramework-WebChat#3803]
Hello WebChat team, 

After the changes made to webchat.js by the BotFramework team a few days ago, date inputs no longer show up in the Bot. There are a ton of other issues we are facing as well, but we have been able to work around majority of them.

![image](https://user-images.githubusercontent.com/66075770/111812600-a93d8380-88ae-11eb-82db-01b4541ba59b.png)

Below is what I currently see in the web chat: I do not have an image before the webchat change 

![image](https://user-images.githubusercontent.com/66075770/111810923-e7d23e80-88ac-11eb-9fea-98e5f0253080.png)

Below is a screenshot of what it looks like emulator. Emulator still works.
![image](https://user-images.githubusercontent.com/66075770/111811535-83fc4580-88ad-11eb-98fe-a1475efbb3fa.png)

Here is the text from my Adaptive card: 

{
    "type": "AdaptiveCard",
    "id": "WhatWeekJsonCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "More Information needed"
        },
        {
            "type": "TextBlock",
            "text": "What week do you need this data for? ",
            "wrap": true
        },
		 {
            "type": "TextBlock",
            "text": "**Note: only Saturdays are available for this data, please only Select a Saturday** ",
            "wrap": true
        },
        {
            "type": "Input.Date",
            "id": "DateWeek",
            "isRequired": true,
            "errorMessage": "Please select a date to continue"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "speak": "${speechText}"
}

**Comment by 007-fr** [comment]
The card above is for Week. The card below is for Day. 

{
    "type": "AdaptiveCard",
    "id": "WhatDayJsonCard",
    "body": [
        {
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "More Information needed"
        },
        {
            "type": "TextBlock",
            "text": "What day do you need this data for?",
            "wrap": true
        },
        {
            "type": "Input.Date",
            "id": "DayDate",
            "isRequired": true,
            "errorMessage": "Please select a date to continue"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "speak": "${speechText}"
}

**Comment by corinagum** [comment]
Could you test these two cards on the Adaptive Card designer and see if the issue persists?

**Comment by corinagum** [comment]
Also please feel free to post about the other bugs you are facing. If they are all related to adaptive cards, please add comments to this thread. Otherwise please file new bugs. 🙂

**Comment by 007-fr** [comment]
yes, 4.12.1. 

The expected results after a user clicks on Day from the Adaptive Card, would be an adaptive card that asks the user to select the date. In this card, it has a submit button, a datefield input and a couple text blocks. It's the card show below. "Choose What Day adaptive card"

![image](https://user-images.githubusercontent.com/66075770/111825366-c62d8300-88bd-11eb-9a1a-b791aeb5653a.png)



If a user clicks on day in the webchat, it shows an empty bubble instead of displaying the Choose What Day adaptive card above. 
![image](https://user-images.githubusercontent.com/66075770/111825659-1a386780-88be-11eb-8922-882f32e679d6.png)

**Comment by corinagum** [comment]
This is what I see when I test in development mode.
![image](https://user-images.githubusercontent.com/14900841/111832150-a55d3180-88ad-11eb-906b-deae992bc67f.png)
Running this card in the Adaptive Cards designer similarly has a warning when pasted in, but doesn't throw on validation error.

This has to do with an incorrectly formatted Adaptive Card. I see there is the `isRequired` prop, which requires both an `errorMessage` (present) and a `label` (not present).

Info and fix: 
https://github.com/microsoft/BotFramework-WebChat/pull/3778#issuecomment-791716537

**Comment by 007-fr** [comment]
That fixed the issue. Thanks Corinagum! Is that The Bot Framework Emulator you are debugging in? Any documentation on how to set that up?

**Comment by corinagum** [comment]
Oh, our team has a bot that's published in development mode so that error messages are displayed as the big red box. This is good to have for companies with public bots, to test changes before it's deployed publicly:
https://github.com/microsoft/BotFramework-WebChat/blob/8061f6835f1a94a7da1284188f816ceb1b7abd36/packages/README.md#flavors

**Comment by 007-fr** [comment]
Cool. Thanks!
