### ISSUE TITLE
Accessibility issue for dynamic placing focus on new message in mobile after adaptive button is clicked

### ISSUE THREAD

**Issue by tanuj01** [microsoft/BotFramework-WebChat#3807]
Is there a way enabled in BotFramework to place the focus on the new message once the button is clicked from adaptive card. Currently, using gestures in mobile user can double tap on a button and then in order to go the new message user has to swipe right multiple times to reach to that message ?

This issue is linked to - @ #3804

**Comment by corinagum** [comment]
@tanuj01 Currently, there is no way to jump to the new message button and/or latest message without swiping. 

The following link is an analysis of current behavior when reviewed with the accessibility team, reviewing MAS compliance: https://github.com/microsoft/BotFramework-WebChat/issues/3759#issuecomment-797085374

#3798 is an issue filed to make some tweak improvements to mobile behavior, but at this time adding a button or automatically focusing on the latest message is not on our roadmap.

**Comment by venkatx5** [comment]
Will this work when user navigate between cards via up/down key?

**Comment by SSanjeevi** [comment]
When we do so this won't trigger. This will trigger and happen only when new messages arrives
