### ISSUE TITLE
Markdown not supported within a Card attachment

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotFramework-WebChat#381]
I was [advised to open this here](https://github.com/Microsoft/BotFramework-Emulator/issues/122#issuecomment-286959960).

I realize this bug might sound like a dupe of #356 however in that bug it's [stated that the `text` property *will* support markdown](https://github.com/Microsoft/BotFramework-WebChat/issues/356#issuecomment-284157698), but that's not what I'm seeing.

**OS**: Windows
**OS Version**: 10.15042.3
**Emulator Version**: 3.5.25
**SDK**: C# v3.5.5

The following response from a bot:
```
"attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "title": "[GeekTrainer](https://github.com/GeekTrainer)",
        "subtitle": "[Click to view](https://github.com/GeekTrainer)",
        "text": "[Click to view](https://github.com/GeekTrainer)",
        "images": [
          {
            "url": "https://avatars2.githubusercontent.com/u/6109729?v=3"
          }
        ]
      }
    }
```
results in the markdown-written `text`, `subtitle`, and `title` fields rendered as plain text in the emulator:
![like this](https://content.screencast.com/users/bc3tech/folders/Snagit/media/74485c44-45de-42a2-a61a-4ec1b3415e1f/03.15.2017-13.59.png)

The same is also true of HeroCard attachments:
```
"attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "[GeekTrainer](https://github.com/GeekTrainer)",
        "subtitle": "[Click to view](https://github.com/GeekTrainer)",
        "text": "[Click to view](https://github.com/GeekTrainer)",
        "images": [
          {
            "url": "https://avatars2.githubusercontent.com/u/6109729?v=3"
          }
        ]
      }
    }
```
![like this](https://content.screencast.com/users/bc3tech/folders/Snagit/media/97d5c258-e674-410a-a522-c75b39513ed9/03.15.2017-14.00.png)

**Comment by billba** [comment]
Ah, see we do support markdown on the `text` field of *messages*, but not the `text` field of attachments.

**Comment by brandonh-msft** [comment]
@billba so... why was this closed?

**Comment by billba** [comment]
It's correct behavior. WebChat is correctly rendering the protocol specification.
