### ISSUE TITLE
Speech to text issue in Safari

### ISSUE THREAD

**Issue by enriconatella** [microsoft/BotFramework-WebChat#3823]
**Screenshots**
<img src="https://user-images.githubusercontent.com/24227373/112985913-1e3b7380-9161-11eb-9142-b6168b70dcce.jpg" width="500" height="500">

**Version**
Using the latest version of webchat.js (referred directly from CDN)
iOS: latest version

**Describe the bug**
The bug is only present in iOS Safari browser.
When a user taps the microphone and the last bot message contains a choice button, the microphone is not re-enabled and is stuck in "Starting...". From that moment on, there is no way for the microphone to work.

**Steps to reproduce**
- Enable Speech To Text (basic recognition)
- Tap the microphone
- Allow to access the microphone
- Say something
- Wait for the bot response (with a choice button)
- The microphone is not anymore re-enabled

**Expected behavior**
The microphone should be re-enabled or the user should be able to re-enabled it by pressing the microphone button.

**Additional context**
There is no error in the console browser.

[Bug]

**Comment by corinagum** [comment]
@enriconatella, do you have `inputHintExpecting` enabled on the bot's activity with the choice buttons?

**Comment by enriconatella** [comment]
@corinagum yes, in fact in all other devices is working fine (Android and web browsers).

![ExpectingInput](https://user-images.githubusercontent.com/24227373/113048481-dfc6a880-91a2-11eb-960d-0adca1adb350.jpg)

**Comment by corinagum** [comment]
Ok thanks. Let me work on a repro - we're working on the latest Web Chat release right now, but I'll get back to you asap.

**Comment by corinagum** [comment]
@enriconatella sorry I haven't gotten to this issue yet. Would you be able to provide your activity(ies) (with no personal information) as .json? This would speed up the process for me :)

**Comment by enriconatella** [comment]
@corinagum here it is the json of the last bot activity:

```json
{
    "activities": [
        {
            "type": "message",
            "id": "6DuhF2C3ayVmIsJnyfLnK-h|0000013",
            "timestamp": "2021-04-08T05:57:22.5315975Z",
            "channelId": "directline",
            "from": {
                "id": "p0tier1bot01",
                "name": "p0tier1bot01"
            },
            "conversation": {
                "id": "6DuhF2C3ayVmIsJnyfLnK-h"
            },
            "locale": "it-IT",
            "text": " C'è qualcos'altro che posso fare per te? 🤗",
            "speak": " C'è qualcos'altro che posso fare per te? 🤗",
            "inputHint": "expectingInput",
            "suggestedActions": {
                "actions": [
                    {
                        "type": "imBack",
                        "title": "Sì, grazie!",
                        "value": "sì, grazie!"
                    },
                    {
                        "type": "imBack",
                        "title": "No, grazie!",
                        "value": "no, grazie!"
                    }
                ]
            },
            "attachments": [],
            "entities": [],
            "replyToId": "6DuhF2C3ayVmIsJnyfLnK-h|0000006",
            "DNU": false,
            "EndConversation": false,
            "ClientData": "",
            "NodeType": "",
            "Node_QuestionType": "ChoiceSuggestion",
            "MainScenarioName": "Informazioni - Carta di Credito - Costi",
            "CurrentScenario": "End Dialog",
            "StartScenario": false,
            "ActiveNodeStep": 2,
            "SessionId": "949a8027e5304e568125fc2ee54c9e68",
            "Node_ID": "00000000-0000-0000-0000-000000000000"
        }
    ],
    "watermark": "13"
}
```

**Comment by corinagum** [comment]
@enriconatella sorry for the delay in getting back to you. 

I was able to resolve this issue by adding the `to: []` field within `suggestedActions`, which is required. Could you try that and see if your issue is resolved?

Note: When I tried this I deleted everything after `entities` from your JSON.
