### ISSUE TITLE
Bot Icon not displaying in Web-Chat

### ISSUE THREAD

**Issue by mn-invia** [microsoft/BotFramework-WebChat#3839]
Hi,

I have created a Bot and Published it successfully and it's functioning well. I have uploaded a Custom ICON (PNG file which is less than 30KB, as per the Specs) under the Bot Profile. I can see my ICON uploaded onto the Bot profile, But the ICON is NOT DISPLAYED during the Web-Chat.

OS: Windows 10 PRO
Browser: Google Chrome
**Microsoft Composer details:**
Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

I need some help as we are planning to launch it NEXT WEEK. Any help would be much appreciated. If you need any further details....Kindly let me know ASAP and I can provide you the required details. Many Thanks & Best Regards.

**Comment by stevkan** [comment]
Closing as resolved.
