### ISSUE TITLE
Is it possible to add checkboxes for each carousel item in the chatbot instead of buttons.

### ISSUE THREAD

**Issue by ravi2808** [Microsoft/BotFramework-WebChat#385]
I search for an item using the bot. Then I will post the results in a carousel. Then if the user selects particular item from the bot, then I need to look for the details for the selected item.

So is this possible with default options provided or Do I need to customize ?

As far as I see there are only buttons available to be used in the __Carousel__ card.

**Comment by billba** [comment]
I'm afraid not. WebChat exists only to support Bot Framework functionality, and this feature exceeds what it currently enables. However keep an eye out for future releases, as features are always being added.

**Comment by ravi2808** [comment]
so even if I use Direct line channel, I can only style the UI but cannot add controls. Is this right ?

**Comment by billba** [comment]
You can send any controls you want via the `channelData` field in a message. You can then customize WebChat to interpret those controls.
