### ISSUE TITLE
Adaptive Card Localization Problem for Date in WebChat

### ISSUE THREAD

**Issue by formore5points** [microsoft/BotFramework-WebChat#3852]
Hello everyone, I give the link to the topic that I previously opened in the /BotFramework-Composer section. 

You can review it in more detail here: https://github.com/microsoft/BotFramework-Composer/issues/6586

My problem is that there is a calendar in the adaptive card and I am trying to get the person to choose a date from here. But I observe this date as null on webchat. Actually, I think it is relevant to the platform being worked on, regardless of webchat and emulator. When I run my bot on a platform with the local language setting en-US, for example Edge, there is no problem, but when I try it with Firefox, the browser's local language setting is tr-Tr, my bot does not work. You can view screenshots below or read the previous location. 

I will be grateful if you could help me.

Adaptive Card:

![1](https://user-images.githubusercontent.com/50989796/114831895-8f705d00-9dd6-11eb-9d4e-36f6e25450f1.png)

Value is null:

![2](https://user-images.githubusercontent.com/50989796/114831929-97c89800-9dd6-11eb-9e2b-b8ca6690de5e.png)

Composer View:

![3](https://user-images.githubusercontent.com/50989796/114831976-a3b45a00-9dd6-11eb-9e96-af54617c02df.png)

**Comment by v-kydela** [comment]
Thank you for the report, @formore5points. Please post text instead of just screenshots so that we can attempt to reproduce the problem. Thank you.

**Comment by GeoffCoxMSFT** [comment]
@v-kydela If you have time, it might be good to try the calendar action and verify that the dates work. That way when the customer replies with the action text we can debug quickly.

**Comment by v-kydela** [comment]
@GeoffCoxMSFT - Thanks, but I don't know that we'll be able to debug at all if the customer is unresponsive

@formore5points - Are you still working on this?

**Comment by formore5points** [comment]
@v-kydela Hello, yes I was working but I solved this one with using activity. In no way, I could not get input using date time. Value part was empty due to localization problem. That's why I give the input I want to get as a response in the last part of the dialog and capture it by using activity from turn.activity. I hope that has been revealing. Thank you so much.

![1](https://user-images.githubusercontent.com/50989796/115866709-b962f880-a442-11eb-83c7-24ab4a802bfc.png)

**Comment by v-kydela** [comment]
@formore5points - I'm glad you got your issue resolved
