### ISSUE TITLE
Unable to import createDirectLine, createStore in Typescript with v4.13

### ISSUE THREAD

**Issue by schemburkar** [microsoft/BotFramework-WebChat#3856]
## Screenshots

file `lib\index.d.ts` from version v4.13.0 (left) vs v4.11.0 (right)

![image](https://user-images.githubusercontent.com/3159347/115137239-94394900-a042-11eb-9484-aa2b0fdba429.png)

## Version

NPM: v4.13.0

## Describe the bug

The issue is present in the npm package `botframework-webchat` used in a react website (`https://github.com/microsoft/BotFramework-WebChat/tree/master/packages/bundle/src`)

The output lib folder contains a `index.d.ts` that is created using the new `src\index.tsx` and not `src\index.ts`. This is probably an issue with webpack output configuration in v4.13

Due to this the following line fails to compile in ts/vscode
```
import ReactWebChat, { createDirectLine, createStore } from 'botframework-webchat';
```
![image](https://user-images.githubusercontent.com/3159347/115137373-61438500-a043-11eb-83b6-df3be997636d.png)

explicitly referencing lib/index.js does not work and is unable to recognize the exports.

Considering this work in v4.11.0, I would consider this a regression introduced in v4.13

## Steps to reproduce

1. Create react app using create react app
1. Add package botframework-webchat v 4.13.0
1. Import createDirectLine, createStore from 'botframework-webchat';
1. See error

## Expected behavior

The bundled package should support importing createDirectLine, createStore from 'botframework-webchat'

The above code works in v4.11.0. 

## Additional context

Suggest to rename the `src\index.tsx` added as part of PR #3818, creating a correct webpack output
The react samples in `https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/g.hybrid-react-npm/packages/chat-component` have not been updated to v4.13 else they would showcase similar issues.

**Comment by corinagum** [comment]
@schemburkar thanks for filing this bug. I'm adding to our list of R14 candidates.

**Comment by warunacds** [comment]
I know a fix for this issue is added R14, but for recording purposes, I want to mention here I'm having the same issue. By downgrading to 4.11.0 it will work on a typescript project.

**Comment by corinagum** [comment]
Related: #3908, #3909

@compulim I'm wondering if this has to do with comments on `core/index.tsx` 

Marking this as P0 for immediate discussion
