### ISSUE TITLE
Pressed card button unselected if StyleOptions set in Minimizable bot sample

### ISSUE THREAD

**Issue by ryub3n** [microsoft/BotFramework-WebChat#3895]
## Version

4.13.0

## Describe the bug

In the minimizable bot sample if you select a card button, minimize and open the bot again the selected button is unselected if StyleOptions is set.
Without StyleOptions the buttons do remain selected even after minimizing and reopening the bot.

## Steps to reproduce

1. Add the below StyleOptions to the minimizable bot sample
![image](https://user-images.githubusercontent.com/24279903/118634646-646f9380-b7f0-11eb-8b1b-25dca332f4d6.png)
2. Select a card button e.g. 'Show Video Card', it returns the card and the button remains selected.
3. Minimize the bot and reopen it to see the button has been unselected.

## Screenshots
Without StyleOptions
![image](https://user-images.githubusercontent.com/24279903/118634117-ced40400-b7ef-11eb-8feb-8d5078154fab.png)

With StyleOptions
![image](https://user-images.githubusercontent.com/24279903/118633954-a64c0a00-b7ef-11eb-929e-be5ce946ec17.png)

## Expected behavior

The buttons that were selected should still show as selected when reopened even if we add StyleOptions.

**Comment by ninggao** [comment]
@stevkan Could you please take a look at this one?

**Comment by stevkan** [comment]
@ryub3n, please try wrapping styleOptions in `useMemo()` and passing that in as property into `createStyleSet()`. This is what appeared to work for me. Your code should look something like the below:

**MinimizableWebChat.js**
```js
const styleOptions = useMemo(
  () => {
    return {
      primaryFont: 'Arial',
      timestampColor: '#1b1a19',
      hideUploadButton: true,
      botAvatarInitials: null,
      userAvatarImage: null,
      userAvatarInitial: null,
      botAvatarImage: null,
    }
  }, []
)

const styleSet = useMemo(
  () =>
    createStyleSet({
      backgroundColor: 'Transparent',
      ...styleOptions
    }),
  [styleOptions]
);

[ ... ]

<WebChat
  className="react-web-chat"
  onFetchToken={handleFetchToken}
  store={store}
  styleSet={styleSet}
  token={token}
/>
```

**WebChat.js** - `styleSet` is passed in to the WebChat function component
```js
<ReactWebChat
  className={`${className || ''} web-chat`}
  directLine={directLine}
  store={store}
  styleSet={styleSet}
/>
```

**Comment by ryub3n** [comment]
@stevkan - This works but there's another problem. hideUploadButton isn't passed to StyleSet ([Ref](https://github.com/microsoft/BotFramework-WebChat/blob/3f3f9ba05af7a09ae68425da622f14418d4a13b6/packages/component/src/BasicSendBox.js#L49)) I guess because the upload button is showing up even though I've set it to true in StyleOptions.

**Comment by stevkan** [comment]
You are right. I missed that small detail. It's a bit of an oddity, but passing `styleOptions` into both `styleSet` as well as an individual Web Chat property appears to work.

**MinimizableWebChat.js**
```js
const styleSet = useMemo(
  () =>
    createStyleSet({
      backgroundColor: 'Transparent',
      ...styleOptions
    }),
  [styleOptions]
);

[ ... ]

<WebChat
  className="react-web-chat"
  onFetchToken={handleFetchToken}
  store={store}
  styleSet={styleSet}
  styleOptions={styleOptions}
  token={token}
/>
```

**WebChat.js** - `styleSet` and `styleOptions` are read from the WebChat function component and passed into the ReactWebChat component.
```js
<ReactWebChat
  className={`${className || ''} web-chat`}
  directLine={directLine}
  store={store}
  styleSet={styleSet}
  styleOption={styleOptions}
/>
```
```

**Comment by ryub3n** [comment]
I tried that but then the original issue i.e. the pressed button one still exists.

**Comment by stevkan** [comment]
If you are able to do so, could you zip your project up into a file and post it here (or you can email it to me, if that makes you more comfortable)? Just remove any secrets/keys listed anywhere.

**Comment by ryub3n** [comment]
My bad, it's working now. I missed the empty dependencies array for the styleOptions useMemo 😅.

**Comment by corinagum** [comment]
Closing as resolved
