### ISSUE TITLE
Suggested Action navigation arrow is not working when Screen/display resolution is 125% in Windows 10 system

### ISSUE THREAD

**Issue by Swedhab3893** [microsoft/BotFramework-WebChat#3941]
**Version**

Latest es5 Version :  [link](https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js)

**Browser**
 
Chrome (Version 91.0.4472.77 (Official Build) (64-bit))

**Description about the Bug**

In Windows system, for the display resolution 125%, when we click on the slider it is not moving to the right after the 9th button. At the same time if the machine's display resolution is 150% its scrolling properly.

_Please find the attached SS when the display resolution is 125%:_

![ScreenResolution125Percentage](https://user-images.githubusercontent.com/85665824/121474326-8fa96500-c9e1-11eb-9fab-1db3cbef93bd.png)

_Please find the attached SS when the display resolution is 150%:_

![ScreenResolution150Percentage](https://user-images.githubusercontent.com/85665824/121474359-9a63fa00-c9e1-11eb-9fa4-5b3d006a791d.png)

.

**Comment by compulim** [comment]
@Swedhab3893 thanks for reporting.

We are currently a week from our next release and this bug couldn't make into our schedule. We will look into this one in our next release. Development should start in early July.

**Comment by hcyang** [comment]
Hi, @compulim, please create a backlog (work item) for R15 and maybe close this issue. Thanks.

**Comment by OEvgeny** [comment]
Closing due to improvements made in this area.
