### ISSUE TITLE
NPM Tags for Webchat are incorrect

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-WebChat#3948]
Looking at WebChat in NPM, the tags are incorrectly used. 

Consider using the same tags used by the JS SDK. 

![image](https://user-images.githubusercontent.com/1165321/122267659-0508b000-ce90-11eb-877b-01728c3f7eee.png)

**Comment by compulim** [comment]
Will follow tags used by JS SDK.

![image](https://user-images.githubusercontent.com/1622400/122290386-879d6980-cea8-11eb-97f5-6c87d2deed1f.png)

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/163117647-59f45642-1533-43d2-a0db-b80185cc1486.png)

Finally, we just start releasing development build with the dist-tag of `main` again.
