### ISSUE TITLE
implementing custom cardActionMiddleware to ReactWebChat does not replace the default, but instead append to it.

### ISSUE THREAD

**Issue by matthijsgg** [microsoft/BotFramework-WebChat#3954]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

## Version

- Web Chat version 4.13.0
- embedded through <iframe> (but problem also occurs when not in iframe)

## Describe the bug

My team wants Adaptive Cards with an Action.OpenUrl that navigate to a website in the same domain to open with 
`_parent` (we use an iframe). 

When adding a cardActionMiddleware to ReactWebChat 
`
<ReactWebChat directLine = {this.directLine } cardActionMiddleware = createCustomCardActionMiddleware />
`

where createCustomCardActionMiddleware
```
export default function createCustomCardActionMiddleware {
        return (dispatch: any) => (next: { (arg0: Action): void; }) => (card: Action) => {
	        switch (card.cardAction.type) {
		        case 'openUrl':
                                window.open(card.cardAction.value, Helper.getTargetForUrl(card.cardAction.value), 'noopener,noreferrer');
			        break;
		        default:
			        break;
	        }
	        return next(card);
        };
}
```

Where Helper.getTargetForUrl is either `_blank` or `_parent` based on some logic.
We expected that this would replace the default cardActionMiddleware. However, clicking the button on the AdaptiveCard now activates 2 window.open() events. One always has a `_blank` target, and the other one is either `_blank` or `_parent` based on the url.
I think the unexpected window is opened by `createDefaultCardActionMiddleware()` in createCoreMiddleware.js, which has a hard-coded target `_blank`. 

We would like to be able to either implement custom CardActoinMiddleware that overrides the default cardActionMiddleware instead of override, or be able to change the target in createCoreMiddleware.js.

## Steps to reproduce

1. Add custom CardActionMiddleware to ReactWebChat that contains a window.open() function,
2. Send an AdaptiveCard with a button with an Action.OpenUrl,
3. Click the button,
4. Browser opens 2 windows instead of 1.

## Expected behavior

After clicking the button, only the custom CardActionMiddleware is executed.

## Additional context

[Bug]

**Comment by compulim** [comment]
In your code, after you handled the action, you should not call `next(card)`. It is for "invoking the next middleware", which in your case, you want to prevent the next (default) middleware from performing.

```diff
  export default function createCustomCardActionMiddleware {
          return (dispatch: any) => (next: { (arg0: Action): void; }) => (card: Action) => {
  	        switch (card.cardAction.type) {
  		        case 'openUrl':
                                  window.open(card.cardAction.value, Helper.getTargetForUrl(card.cardAction.value), 'noopener,noreferrer');
  			        break;
  		        default:
+               	        return next(card);
- 			        break;
  	        }
- 	        return next(card);
          };
  }
```
