### ISSUE TITLE
Development builds not published on NPM on @main tag

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-WebChat#3955]
## Version

n.a.

## Describe the bug

`npm install botframework-webchat@main` results in `npm ERR! notarget No matching version found for botframework-webchat@main.`.

It seems that main isn't published on NPM, where master still is but on a very old version. https://www.npmjs.com/package/botframework-webchat. The existence of `@main` tag is published in the README.

## Steps to reproduce

1. Run npm install botframework-webchat@main

## Additional context

I am facing https://github.com/microsoft/BotFramework-WebChat/issues/3856 while creating a custom Power BI Visual. I will try to revert to 4.11.0 for the time being, however in development I would like to use the latest main build.

Installing it directly via NPM install with git notation doesn't work for monorepo's, as far as I know.

[Bug]

**Comment by iMicknl** [comment]
Possible related to https://github.com/microsoft/BotFramework-WebChat/issues/3948, however in that case the READM.md should be changed to mention @next instead of @main.

**Comment by alopix** [comment]
The README instructions not working basically blocks using with React 17 as mentioned in issue #4034 :(

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/163117647-59f45642-1533-43d2-a0db-b80185cc1486.png)

Finally, we just start releasing development build with the dist-tag of `main` again.

You can now run `npm install botframework-webchat@main` to install the latest dev build based from `main` branch.

Please note that this build may not be as stable as production version as there are some cases that our automated tests can't catch, e.g. browsers other than Chromium, screen reader, etc.

If you encounter any issues, please file us an issue. 😉

**Comment by iMicknl** [comment]
Thanks @compulim, much appreciated :)

**Comment by compulim** [comment]
Thanks for your patience and appreciation. 🥲
