### ISSUE TITLE
Bot hang on starting mode on clicking on microphone after some time interval

### ISSUE THREAD

**Issue by jayarau** [microsoft/BotFramework-WebChat#3962]
"botframework-webchat": "4.12.0",

**Issue:** Bot hang on starting mode on clicking on microphone after some time interval with inactivity.
I also observed this same issue in [directline-speech sample](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/d.es5-direct-line-speech/) provided.

**Expected Behaviour:** Bot should not hang on starting mode, it should listen activity and send it.

please find below screenshots for reference:
![image](https://user-images.githubusercontent.com/73291456/123076854-2260ef80-d437-11eb-9dfe-cce08030b15d.png)

screenshot of sample:
![image](https://user-images.githubusercontent.com/73291456/123076936-39074680-d437-11eb-98f8-ddb9c98e43ad.png)

Can you please help on this.

**Comment by stevkan** [comment]
@jayarau, can you include the code you are using for running Web Chat? I will attempt a repro but would like to try with your code, as well.

**Comment by jayarau** [comment]
Hi @stevkan , Please find below code we are using for running webchat.

We are using webchat version 4.12.0. and browser is chrome.

`import * as React from "react";
import {ApplicationCustomizerContext} from '@microsoft/sp-application-base';
import ReactWebChat, {Components,  createDirectLineSpeechAdapters, createStore } from "botframework-webchat";
import { AadTokenProvider } from '@microsoft/sp-http';
import updateIn from 'simple-update-in';
import { environment } from "../../environment/environment";
import { Logger, LogLevel } from "@pnp/logging";
import hostConfig from '../DesktopCompanion-PABot/adaptivecardHostConfig';


const EmployeeImg: any = require('../Images/Employee.png');

export interface IReactFooterProps {
  upn: string;
  aadToken: string;
  userTimeZoneName: string;
  dContext: ApplicationCustomizerContext;
    
}
let notificationParams: any;
let connector: any;
export default class ReactFooter extends React.Component<IReactFooterProps,{adapters:{}}> {
  
    private token: string;
    private store: any;
    public adaptersObj:any;
    
     
    constructor(props: IReactFooterProps) {
      super(props);
    this.state={adapters:{}};}
    async createchat(props:IReactFooterProps){
      
      this.store = createStore(
            { },            
            function(dispatch) {
              return function(next) {  
               
                return async function(action) {
                  try {

                      if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
                       props.dContext.aadTokenProviderFactory.getTokenProvider() 
                       .then((tokenProvider: AadTokenProvider): Promise<string> => {
                         // retrieve access token for the enterprise API secured with Azure AD
                         return tokenProvider.getToken(`${environment.resource}`);
                       })
                       .then((accessToken: string) :any => {
                        props.aadToken= accessToken;
                        
                        if((window as any).notificationParams!=undefined){
                          notificationParams=(window as any).notificationParams;
                        }else{
                          notificationParams=null;
                        }
                        if(action.meta.method=="speech"){
                        action = updateIn(action, ['payload',  'channelData', 'AADUserToken'], () =>props.aadToken); 
                        action = updateIn(action, ['payload', 'channelData', 'UserTimeZoneName'], () =>props.userTimeZoneName);
                        action = updateIn(action, ['payload', 'channelData', 'notificationParams'], () =>notificationParams);
                        }
                         else{
                          action = updateIn(action, ['payload',  'channelData', 'AADUserToken'], () =>props.aadToken); 
                          action = updateIn(action, ['payload', 'channelData', 'UserTimeZoneName'], () =>props.userTimeZoneName);
                          action = updateIn(action, ['payload', 'channelData', 'notificationParams'], () =>notificationParams);
                          
                          action = updateIn(action, ['payload', 'activity', 'channelData', 'AADUserToken'], () =>props.aadToken); 
                          action = updateIn(action, ['payload', 'activity', 'channelData', 'UserTimeZoneName'], () =>props.userTimeZoneName);
                          action = updateIn(action, ['payload', 'activity', 'channelData', 'notificationParams'], () =>notificationParams); 
                         }
                        
                        (window as any).notificationParams=null;
                        return next(action);
                      }).catch(err=>{console.log(err);
                        Logger.log({
                          message: "Token Generation issue for bot using AAdTokenProvider",
                          level: LogLevel.Error,
                          data: err
                        });
                        alert("Bot Session Expired!");
                            window.location.reload();
                      }) 
                        
                        
                    
                      }
                      // else if(action.type==){}
                      else{return next(action); }
                    
                    } catch (error) {
                      console.log("Exception Occured:",error);
                       this.setState({ adapters: this.adaptersObj})
                    }
                } 
              }
             
              
            }
          );
        
        // }        
    }
    public async componentDidMount() {
      
      await createDirectLineSpeechAdapters({
        fetchCredentials:{
          region:'westeurope',
          subscriptionKey:'6a98522cfe194ad1a09d8ca6b44d693b'}
        }).then((adapters)=>{
        this.setState({ adapters: adapters})
        
        let data={
          type: 'message',
          channelData: { AADUserToken:  this.props.aadToken },
            text: 'WELCOME_IGNORE',
            from: {id:this.props.upn},
        };
        connector=adapters.directLine.dialogServiceConnector
        connector.sendActivityAsync(JSON.stringify(data))
    
      
      })
     
      }
    // public async getAdapter(){
    //   const adapters=await createDirectLineSpeechAdapters({
    //     fetchCredentials:{
    //       region:'westeurope',
    //       subscriptionKey:'6a98522cfe194ad1a09d8ca6b44d693b'}
    //     });
    //   return adapters;
    // }
  
  // attachmentMiddleware = () => next => ({ activity, attachment, ...others }) => {
  //           const { activities } = this.store.getState();
  //           const messageActivities = activities.filter(activity => activity.type === 'message');
  //           const recentBotMessage = messageActivities.pop() === activity;
  //           switch (attachment.contentType) {
  //             case 'application/vnd.microsoft.card.adaptive':
               
  //               return (     
  //               <Components.AdaptiveCardContent actionPerformedClassName="card__action--performed"
  //               content={attachment.content}
  //               disabled={!recentBotMessage}/>      
  //               );
  
  //             default:
  //               return next({ activity, attachment, ...others });
  //           }
  //         };
    adaptiveCardHostConfig =hostConfig;
    
    public render() : JSX.Element{
      this.createchat(this.props)
      if(this.state.adapters.hasOwnProperty('directLine')){
        return (
          <ReactWebChat   {...this.state.adapters} store={this.store} adaptiveCardsHostConfig={this.adaptiveCardHostConfig} 
          styleOptions={{
          bubbleBackground: '#0184D7',
          bubbleTextColor:'#FFFFFF',
          bubbleBorderRadius:5,            
          bubbleFromUserBackground: '#e8e8e8',            
          bubbleFromUserBorderRadius:5,       
          
          botAvatarInitials:'BOT',
          userAvatarImage: EmployeeImg,
          userAvatarInitials:'User',          
          microphoneButtonColorOnDictate:"#ffffff",
          hideUploadButton:true}}/>
      );
      }else{
        return(<div>Rendering...</div>)
      }
        
    }
}`

**Comment by jayarau** [comment]
Hi @stevkan , We are using webchat version 4.12.0. and Chrome browser.

Please find code below we are using for running webchat:

```
import * as React from "react";
import {ApplicationCustomizerContext} from '@microsoft/sp-application-base';
import ReactWebChat, {Components,  createDirectLineSpeechAdapters, createStore } from "botframework-webchat";
import { AadTokenProvider } from '@microsoft/sp-http';
import updateIn from 'simple-update-in';
import { environment } from "../../environment/environment";
import { Logger, LogLevel } from "@pnp/logging";
import hostConfig from '../DesktopCompanion-PABot/adaptivecardHostConfig';
const EmployeeImg: any = require('../Images/Employee.png');
export interface IReactFooterProps {
upn: string;
aadToken: string;
userTimeZoneName: string;
dContext: ApplicationCustomizerContext;
}
let notificationParams: any;
let connector: any;
export default class ReactFooter extends React.Component<IReactFooterProps,{adapters:{}}> {
private token: string;
private store: any;
public adaptersObj:any;
constructor(props: IReactFooterProps) {
super(props);
this.state={adapters:{}};}
async createchat(props:IReactFooterProps){
this.store = createStore(
{ },            
function(dispatch) {
return function(next) {  
return async function(action) {
try {
if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
props.dContext.aadTokenProviderFactory.getTokenProvider() 
.then((tokenProvider: AadTokenProvider): Promise
<string>
=> {
// retrieve access token for the enterprise API secured with Azure AD
return tokenProvider.getToken(`${environment.resource}`);
})
.then((accessToken: string) :any => {
props.aadToken= accessToken;
if((window as any).notificationParams!=undefined){
notificationParams=(window as any).notificationParams;
}else{
notificationParams=null;
}
if(action.meta.method=="speech"){
action = updateIn(action, ['payload',  'channelData', 'AADUserToken'], () =>props.aadToken); 
action = updateIn(action, ['payload', 'channelData', 'UserTimeZoneName'], () =>props.userTimeZoneName);
action = updateIn(action, ['payload', 'channelData', 'notificationParams'], () =>notificationParams);
}
else{
action = updateIn(action, ['payload',  'channelData', 'AADUserToken'], () =>props.aadToken); 
action = updateIn(action, ['payload', 'channelData', 'UserTimeZoneName'], () =>props.userTimeZoneName);
action = updateIn(action, ['payload', 'channelData', 'notificationParams'], () =>notificationParams);
action = updateIn(action, ['payload', 'activity', 'channelData', 'AADUserToken'], () =>props.aadToken); 
action = updateIn(action, ['payload', 'activity', 'channelData', 'UserTimeZoneName'], () =>props.userTimeZoneName);
action = updateIn(action, ['payload', 'activity', 'channelData', 'notificationParams'], () =>notificationParams); 
}
(window as any).notificationParams=null;
return next(action);
}).catch(err=>{console.log(err);
Logger.log({
message: "Token Generation issue for bot using AAdTokenProvider",
level: LogLevel.Error,
data: err
});
alert("Bot Session Expired!");
window.location.reload();
}) 
}
// else if(action.type==){}
else{return next(action); }
} catch (error) {
console.log("Exception Occured:",error);
this.setState({ adapters: this.adaptersObj})
}
} 
}
}
);
// }        
}
public async componentDidMount() {
await createDirectLineSpeechAdapters({
fetchCredentials:{
region:<--Region-->,
subscriptionKey:<--subscription key-->}
}).then((adapters)=>{
this.setState({ adapters: adapters})
let data={
type: 'message',
channelData: { AADUserToken:  this.props.aadToken },
text: 'WELCOME_IGNORE',
from: {id:this.props.upn},
};
connector=adapters.directLine.dialogServiceConnector
connector.sendActivityAsync(JSON.stringify(data))
})
}
// attachmentMiddleware = () => next => ({ activity, attachment, ...others }) => {
//           const { activities } = this.store.getState();
//           const messageActivities = activities.filter(activity => activity.type === 'message');
//           const recentBotMessage = messageActivities.pop() === activity;
//           switch (attachment.contentType) {
//             case 'application/vnd.microsoft.card.adaptive':
//               return (     
//               <Components.AdaptiveCardContent actionPerformedClassName="card__action--performed"
//               content={attachment.content}
//               disabled={!recentBotMessage}/>      
//               );
//             default:
//               return next({ activity, attachment, ...others });
//           }
//         };
adaptiveCardHostConfig =hostConfig;
public render() : JSX.Element{
this.createchat(this.props)
if(this.state.adapters.hasOwnProperty('directLine')){
return (
<ReactWebChat   {...this.state.adapters} store={this.store} adaptiveCardsHostConfig={this.adaptiveCardHostConfig} 
styleOptions={{
bubbleBackground: '#0184D7',
bubbleTextColor:'#FFFFFF',
bubbleBorderRadius:5,            
bubbleFromUserBackground: '#e8e8e8',            
bubbleFromUserBorderRadius:5,       
botAvatarInitials:'BOT',
userAvatarImage: EmployeeImg,
userAvatarInitials:'User',          
microphoneButtonColorOnDictate:"#ffffff",
hideUploadButton:true}}/>
);
}else{
return(
<div>Rendering...</div>
)
}
}
}
```

**Comment by jayarau** [comment]
Just to add, we are getting below error in console:
![image](https://user-images.githubusercontent.com/73291456/123403135-16effe80-d5c6-11eb-9b7e-ededef3f91e5.png)

**Comment by jayarau** [comment]
Hi @stevkan , can we have any update on this.

**Comment by compulim** [comment]
I have tested it and didn't repro on 4.13:

1. Navigate to the [Direct Line Speech sample](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/d.es5-direct-line-speech/)
2. Click the microphone button
3. Stay silent for ~10 seconds
4. The bot should say "Unknown command: ''"
5. Click the microphone button again
6. Say "Hello, World!"

EXPECT: The bot recognize "hello world" and responded to it.

**Comment by compulim** [comment]
@stevkan the customer do mention it repro in our samples. You should have tried it out.

**Comment by stevkan** [comment]
@jayarau, if I understand the issue correctly, Web Chat is hanging after you had already started a conversation, stepped away for a period of time, then returned to continue the conversation. Under these circumstances, I am able to repro the issue.

What I am finding is that, when a conversation is started but then there is at least 15 mins of no further conversation, Web Chat fails to make a successful connection. The following error occurs precisely at 15 mins. Attempting to continue the conversation results in 'Starting' being displayed.

![image](https://user-images.githubusercontent.com/18403946/124798128-df5b4d80-df07-11eb-8b49-31588431d848.png)

@compulim, thoughts on this?

**Comment by stevkan** [comment]
@compulim, I'll see if I can get more details from Fiddler, but that won't be until later today, at the earliest.

**Comment by jayarau** [comment]
Hi @stevkan, Yes We are facing exact same issue.

> @jayarau, if I understand the issue correctly, Web Chat is hanging after you had already started a conversation, stepped away for a period of time, then returned to continue the conversation. Under these circumstances, I am able to repro the issue.
> 
> What I am finding is that, when a conversation is started but then there is at least 15 mins of no further conversation, Web Chat fails to make a successful connection. The following error occurs precisely at 15 mins. Attempting to continue the conversation results in 'Starting' being displayed.
> 
> ![image](https://user-images.githubusercontent.com/18403946/124798128-df5b4d80-df07-11eb-8b49-31588431d848.png)
> 
> @compulim, thoughts on this?

**Comment by stevkan** [comment]
Did some digging with Fiddler and am seeing the following:

- DL Speech (the host URL "westus2.convai.speech.microsoft.com", in my case) closes the web socket connection if the idle time is greater than 300000 ms (i.e., 5 mins).
![image](https://user-images.githubusercontent.com/18403946/124989213-c0d28080-dff3-11eb-807f-4b1274fb7504.png)

- The connection is reopened almost immediately following the previous closure.
**Request Header**
![image](https://user-images.githubusercontent.com/18403946/124989470-055e1c00-dff4-11eb-8614-b22027d333cc.png)
**Response Header**
![image](https://user-images.githubusercontent.com/18403946/124989584-1e66cd00-dff4-11eb-8d49-8e67d1cac8d8.png)

- In total, this occurs three times beginning with the last user input.
- After the third time (i.e., after 15 mins), the connection is closed again with the next immediate call to the service returning "401 Unauthorized"
**Request Header**
![image](https://user-images.githubusercontent.com/18403946/124989647-34748d80-dff4-11eb-8d77-828a78e8af51.png)
**Response Header**
![image](https://user-images.githubusercontent.com/18403946/124989707-46eec700-dff4-11eb-830b-27ed42a4aca0.png)

The "401 Unauthorized" suggests the token is expired. The Cognitive Services docs on [Authentication](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text#authentication) state the issued bearer token is only valid for 10 minutes. The [docs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text#authentication) go on to say that a new token can be requested at any time, but they suggest using the current token for 9 mins. Then request a new token.

Can you try adjusting your service call for generating a token to run every 9 minutes replacing the old with the new and see what affect that has?

**Comment by jayarau** [comment]
Hi @stevkan, As per your suggestion, we are generating adapters every 9 minutes, and its solving issue. i.e. bot is not hanging on starting mode.
But I observed below point:
1.  After generating new adapters , though we are sending valid AAD Token in request, getting popup to sign in to service on sending any utterance.
We are debugging it to get exact cause.

**Comment by stevkan** [comment]
@jayarau, I'm glad the above solution fixed the initial problem. I will go ahead and close this issue as resolved.

For the new problem, as this is different from the above, if the problem persists please open a new issue to track it.

That being said, I'm not certain to this but I suspect that with the adapter being recreated the context is getting lost. Thus, the new adapter doesn't know that the sign-in already occurred. Just a suspicion, at this point, but possibly worth looking into.
