### ISSUE TITLE
WinForms Chat App

### ISSUE THREAD

**Issue by larsontim12** [Microsoft/BotFramework-WebChat#398]
I know this is for the web but I was wondering if there is any samples of how I could integrate a bot into a winforms application.  It would need to use direct line and be in house not hosted externally.

Thoughts?

**Comment by danmarshall** [comment]
Well you might use a webView to host the html page containing the WebChat. Then are you saying you want to run your own DirectLine protocol server inside your network?

**Comment by billba** [comment]
Sorry I don't have any samples for you. There is a .Net Direct Line nuget package but at this time you'd have to build your own UX.
