### ISSUE TITLE
CDN Link Is Not Working

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#3985]
## Screenshots

![IMG](https://user-images.githubusercontent.com/22778273/125327156-a6e8b480-e2f7-11eb-9fff-367e5f3c38a2.png)

## Version

WebChat v4.14.0

## Describe the bug

The latest version v4.14.0 of WebChat CDN link is not working and shows an error.

## Steps to reproduce

1. Go to 'https://cdn.botframework.com/botframework-webchat/4.14.0/webchat-es5.js'
2. Observe the error

## Expected behavior

The CDN link spouse to load the file.

[Bug]

**Comment by hcyang** [comment]
Hi @compulim, please take a look and respond. Thanks.

**Comment by compulim** [comment]
We are in the progress of rolling out 4.14.0 to CDN. It should be available later today.

Thanks!

**Comment by compulim** [comment]
4.14.0 is on CDN now. :)

CDN bits are often lag behind the NPM by a business day because deployment to CDN has more time constraints than NPM.

Sorry about the inconveniences.

**Comment by arman-g** [comment]
@compulim thank you!
