### ISSUE TITLE
[A11y] [OC] The focus moves to entire script and then the sent chat message

### ISSUE THREAD

**Issue by charliewang95** [microsoft/BotFramework-WebChat#3988]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

## Version

4.13.0

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Describe the bug

Reported by Omnichannel C+E a11y team:

Actual:
On tab or shift tab  navigation to the sent or received message  the focus moves to entire script and then the sent chat message
Expected:
The chat section should receive only one tab , the focus from edit should move to the chat sent rather than the entire script 
User Impact:
keyboard users will not know the proper order of navigation

## Steps to reproduce

1. Hit URL: https://ocqe0705.crm.dynamics.com/main.aspx?appid=ba271ede-29e0-eb11-bacb-000d3a9cea16 and log in with appropriate credentials .
2. Tab to Omnichannel customer app and hit enter
3. Hit URL Tryit Editor v3.6 (w3schools.com) and pate the code and click on start chat
4. Tab to accept button and press enter.
5. tab to the new conversation screen and tab to edit field and type a message in Spanish and press enter.
6. shift tab to the sent message.

## Expected behavior

The chat section should receive only one tab , the focus from edit should move to the chat sent rather than the entire script

## Additional context

[OC bug link](https://dynamicscrm.visualstudio.com/OneCRM/_queries/edit/2333218/?triage=true)

[Bug]

**Comment by charliewang95** [comment]
Please triage this and see if this is by design and corresponding to standard

**Comment by compulim** [comment]
Thanks @charliewang95.

It's a technical barrier as some browsers does not support `inert` attribute yet. Thus, we need to have the "End of transcript" terminator. And the end-user need to press <kbd>SHIFT</kbd> + <kbd>TAB</kbd> one more time to focus on the message. It's inevitable until all of our supported browsers have the `inert` attribute.

We consulted our accessibility team and they are okay with this.

The technical explanation is documented here, https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/ACCESSIBILITY.md#hiding-focusable-elements-in-the-transcript.

**Comment by compulim** [comment]
Closing as by-design.
