### ISSUE TITLE
[OC] Adaptive Cards are not rendering on Conversation Control

### ISSUE THREAD

**Issue by ericwei0909** [microsoft/BotFramework-WebChat#3989]
## Screenshots
On Conversation Control, it shows like this
![image](https://user-images.githubusercontent.com/9732538/125869516-f77d0147-09c7-47ce-a5d6-57384a50de60.png)
Error in Console:
![image](https://user-images.githubusercontent.com/9732538/125869573-70e1637f-471b-4cbd-b3b7-f2d1cb5d9788.png)
Adaptive Card data:
![image](https://user-images.githubusercontent.com/9732538/125869588-f20cab41-b2be-49f8-89aa-f07950770273.png)

## Version

"adaptivecards": "^1.2.5",
"botframework-webchat": "^4.13.0",
"botframework-webchat-api": "^4.13.0",
"botframework-webchat-chat-adapter": "0.0.3-main.462d48f",
"botframework-webchat-component": "^4.13.0",
"botframework-webchat-core": "^4.13.0"

## Describe the bug

Adaptive cards are not rendering on Conversation Control.

**Comment by ericwei0909** [comment]
The code to generate adaptive card.

import { Components } from "botframework-webchat";
import React from "react";
import { isSmartAssistActivity } from "ConversationControl/API/WebChatSDK/ActivityUtils";
import { Constants } from "ConversationControl/API/Constants/Constants";

// eslint-disable-next-line max-len
// Implementation is based on https://github.com/microsoft/BotFramework-WebChat/blob/95ab4e61b1ef4de8d326dcdefa98911efbcff7ac/packages/bundle/src/adaptiveCards/createAdaptiveCardsAttachmentMiddleware.js
// and example https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/05.custom-components/l.disable-adaptive-cards/index.html
// It is needed to support disabled adaptive cards

export const AdaptiveCardContent = ({ activity, attachment }) => {
	const disableCard = !isSmartAssistActivity(activity);
	const content = attachment.content;

	return attachment.contentType === Constants.AdaptiveCardTypes.Hero ? (
		<Components.HeroCardContent content={content} disabled={disableCard}/>
	) : attachment.contentType === Constants.AdaptiveCardTypes.Adaptive ? (
		<Components.AdaptiveCardContent content={content} disabled={disableCard} />
	) : attachment.contentType === Constants.AdaptiveCardTypes.Animation ? (
		<Components.AnimationCardContent content={content} disabled={disableCard} />
	) : attachment.contentType === Constants.AdaptiveCardTypes.Audio ? (
		<Components.AudioCardContent content={content} disabled={disableCard} />
	) : attachment.contentType === Constants.AdaptiveCardTypes.OAuth ? (
		<Components.OAuthCardContent content={content} disabled={disableCard} />
	) : attachment.contentType === Constants.AdaptiveCardTypes.Receipt ? (
		<Components.ReceiptCardContent content={content} disabled={disableCard}/>
	) : attachment.contentType === Constants.AdaptiveCardTypes.SignIn ? (
		<Components.SignInCardContent content={content} disabled={disableCard} />
	) : attachment.contentType === Constants.AdaptiveCardTypes.Thumbnail ? (
		<Components.ThumbnailCardContent content={content} disabled={disableCard} />
	) : attachment.contentType === Constants.AdaptiveCardTypes.Video ? (
		<Components.VideoCardContent content={content} disabled={disableCard} />
	) : null;
};

**Comment by ericwei0909** [comment]
I updated the webchat version to 4.14.0.

In console, it shows error - "Error: This hook can only be used on component that is decendants of <ComposerWithAdaptiveCards>"
![image](https://user-images.githubusercontent.com/9732538/125889185-9fa5eade-ccba-4dc8-80fd-63189b83ebd7.png)

**Comment by cwhitten** [comment]
> I updated the webchat version to 4.14.0.
> 
> In console, it shows error - Error: This hook can only be used on component that is decendants of
> 
> ![image](https://user-images.githubusercontent.com/9732538/125889185-9fa5eade-ccba-4dc8-80fd-63189b83ebd7.png)

**Comment by ericwei0909** [comment]
I have tested with old version and it works fine.

"botframework-webchat": "4.9.2-master.8696a8e"

![image](https://user-images.githubusercontent.com/9732538/126229162-eab8325d-425b-464a-9270-c36c53fc84a0.png)

**Comment by compulim** [comment]
Can you dump the Adaptive Cards as a JSON and attach it here?

**Comment by ericwei0909** [comment]
The adaptive card JSON is attached below.

{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0",
  "type": "AdaptiveCard",
  "speak": "Your flight is confirmed for you and 3 other passengers from Seattle to Amsterdam on Friday, October 10 8:30 AM",
  "body": [
    {
      "type": "TextBlock",
      "text": "Passengers",
      "weight": "bolder",
      "isSubtle": false
    },
    {
      "type": "TextBlock",
      "text": "Mae Gibbs",
      "separator": true
    },
    {
      "type": "TextBlock",
      "text": "2 Stops",
      "weight": "bolder",
      "spacing": "medium"
    },
    {
      "type": "TextBlock",
      "text": "Sat, Feb 1 8:30 AM",
      "weight": "bolder",
      "spacing": "none"
    },
    {
      "type": "ColumnSet",
      "separator": true,
      "columns": [
        {
          "type": "Column",
          "width": 1,
          "items": [
            {
              "type": "TextBlock",
              "text": "Seattle"
            },
            {
              "type": "TextBlock",
              "size": "extraLarge",
              "text": "SEA",
              "spacing": "none"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "text": " "
            },
            {
              "type": "Image",
              "url": "http://adaptivecards.io/content/airplane.png",
              "size": "small",
              "spacing": "none"
            }
          ]
        },
        {
          "type": "Column",
          "width": 1,
          "items": [
            {
              "type": "TextBlock",
              "horizontalAlignment": "right",
              "text": "Amsterdam"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "right",
              "size": "extraLarge",
              "text": "AMS",
              "spacing": "none"
            }
          ]
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": "Non-Stop",
      "weight": "bolder",
      "spacing": "medium"
    },
    {
      "type": "TextBlock",
      "text": "Tue, Feb 18 9:50 PM",
      "weight": "bolder",
      "spacing": "none"
    },
    {
      "type": "ColumnSet",
      "separator": true,
      "columns": [
        {
          "type": "Column",
          "width": 1,
          "items": [
            {
              "type": "TextBlock",
              "text": "Amsterdam"
            },
            {
              "type": "TextBlock",
              "size": "extraLarge",
              "text": "AMS",
              "spacing": "none"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "text": " "
            },
            {
              "type": "Image",
              "url": "http://adaptivecards.io/content/airplane.png",
              "size": "small",
              "spacing": "none"
            }
          ]
        },
        {
          "type": "Column",
          "width": 1,
          "items": [
            {
              "type": "TextBlock",
              "horizontalAlignment": "right",
              "text": "Seattle"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "right",
              "size": "extraLarge",
              "text": "SEA",
              "spacing": "none"
            }
          ]
        }
      ]
    },
    {
      "type": "ColumnSet",
      "spacing": "medium",
      "columns": [
        {
          "type": "Column",
          "width": "1",
          "items": [
            {
              "type": "TextBlock",
              "text": "Total",
              "size": "medium"
            }
          ]
        },
        {
          "type": "Column",
          "width": 1,
          "items": [
            {
              "type": "TextBlock",
              "horizontalAlignment": "right",
              "text": "$4,032.54",
              "size": "medium",
              "weight": "bolder"
            }
          ]
        }
      ]
    }
  ]
}

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/126404700-f53281c4-0929-4898-9b7b-c8fcb70c8932.png)

I tried your JSON with Web Chat 4.14.0 and it is working as expected.

Do you think it could be related to some customization code done on the OC side?

**Comment by ericwei0909** [comment]
I find the issue in our code. Thanks!
