### ISSUE TITLE
What is the latest list of supported languages by webchat? Is Spanish Mexico and Spanish Spain supported?

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/BotFramework-WebChat#3992]
[Question]

What is the latest list of supported languages by webchat?

Is Spanish Mexico and Spanish Spain supported?

We have a requirement to develop bot in Spanish, based on availability of LUIS - they decided to use Spanish Mexico, but in the list given here it doesn't contain Spanish Mexico, that's why needed to confirm.

https://github.com/microsoft/BotFramework-WebChat/blob/31d0b69ccee674174634d8da10ff7670ffdfc5e9/docs/LOCALIZATION.md

**Comment by stevkan** [comment]
@SSanjeevi, thank you for your patience while I looked into this. Spanish Mexico (es-MX) is not one of the supported languages in Web Chat, unfortunately. In cases where a locale, region, country, etc., is not supported, Web Chat will fallback to the language only. For instance, 'es-MX' should fallback to 'es'.

To be clear, 'es-MX' will still be passed from client to bot as the locale. It is only the localization of Web Chat components that will fallback. For example, the send box placeholder message 'Type your message' or the message sent text that reads 'Just now' or '_x_ minutes ago'.

Regarding any broken links in the LOCALIZATION.md file linked above (apologies for that), all the referenced files can now be found under [/api/src](https://github.com/microsoft/BotFramework-WebChat/tree/main/packages/api/src).

I'm closing this as this should answer your question. If you find you need additional help regarding this topic, please feel free to reopen.
