### ISSUE TITLE
Add Skype URI support

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotFramework-WebChat#400]
Currently an openURL button with a Skype URI as the value, does nothing.
Add support for Skype and Skype for Business URIs.

**Comment by billba** [comment]
At the moment I believe all links are being sanitized. @eanders-MS where did we land with this?

**Comment by eanders-MS** [comment]
We're only allowing http and https links currently. I thought we fixed this but apparently not. I think we should allow any kind of protocol.

**Comment by eanders-MS** [comment]
Wait, I spoke too soon. The code to filter links still exists but isn't being called. The link should make it to the UI as clickable. The problem must be elsewhere.

**Comment by DL-LiveTiles** [comment]
@eanders-MS I only tested on the emulator and the bot framework test window (version 3).

**Comment by eanders-MS** [comment]
Looking over the emulator code, I see it does filter external links to http/https. It should be straight forward to fix.

**Comment by eanders-MS** [comment]
A fix has been made to the emulator and should be available in the next release. PR: https://github.com/Microsoft/BotFramework-Emulator/pull/144

**Comment by billba** [comment]
@eanders-MS is this just an Emulator problem or is there also a WebChat issue?

**Comment by eanders-MS** [comment]
I think its just an Emulator problem. Will go ahead and close this out.
