### ISSUE TITLE
Responding to adaptive card input events

### ISSUE THREAD

**Issue by KarlPurk** [microsoft/BotFramework-WebChat#4004]
Hi.  Is there an API that I can use to respond to adaptive card input events.  For example if a user toggles a checkbox in an adaptive card I'd like to respond to this event with some custom logic (send an API request).  I took a look at the card action middleware but it looks like the toggling of a checkbox is not captured.

**Comment by compulim** [comment]
This is not supported as [Adaptive Cards](https://github.com/microsoft/adaptivecards) do not have APIs to control its surface.

You can file a feature request to their repo.

**Comment by KarlPurk** [comment]
@compulim the ability to react to toggle changes is already supported in Adaptive Cards but doesn't appear to be surfaced in WebChat.  

If I render the card using the Adaptive Cards library directly I can use the `onInputValueChanged` method to capture this event.  Here's a working example of this:

```js
import * as AdaptiveCards from "adaptivecards"

const card = {
  type: "AdaptiveCard",
  $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
  version: "1.3",
  body: [
    {
      type: "Input.Toggle",
      title: "Toggle Me",
    },
  ],
}

const adaptiveCard = new AdaptiveCards.AdaptiveCard()

adaptiveCard.onInputValueChanged = function (value) {
  console.log("Toggle has been changed", value)
}

adaptiveCard.parse(card)

document.body.appendChild(adaptiveCard.render())
```

Is it possible for me to hook into this event using WebChat?

**Comment by KarlPurk** [comment]
@compulim @stevkan I think this was closed prematurely.  Can someone please review the message above?
