### ISSUE TITLE
How to make timestamp persistent for the old messages too.

### ISSUE THREAD

**Issue by ravi2808** [Microsoft/BotFramework-WebChat#403]
When we chat with bot, only the latest message is having the timestamp. Timestamp for the previous messages is fading out. Also, how to show the timestamp for user messages too ?

**Comment by billba** [comment]
The current visual design groups messages. If there is a pause of five minutes or more between messages, that's a new group. We only show the timestamp of the last message in a group (other apps like Google Hangouts behave similarly). We do show the timestamp for a user message while it's the last message, but bots typically respond immediately, in which case you don't see them very long.

We are working on a new visual design, and this is part of it. The tracking issue is #33. In the meantime you can customize by altering the code in `WrappedActivity`.
