### ISSUE TITLE
[Usable - Bot Webchat - Add Typing indicator GIF]: While typing any message there is typing indicator symbol appears which can confuse the end users

### ISSUE THREAD

**Issue by KattaBhargav** [microsoft/BotFramework-WebChat#4031]
User Experience:
If user is typing any message there is typing indicator is visible on the screen then the user can get confuse.

Repro Steps:
1. Open URL: https://microsoft.github.io/BotFramework-WebChat/05.custom-components/b.send-typing-indicator/
2. Web chat bundle will open.
3. Navigate on the web chat bot and Type "sendTypingIndicator" in the send box
4. Typing indicator GIF appears on chat window.
5. Check and verify that step 3-4 are accessible and MAS compliant.

Actual Result:
While typing any message there is typing indicator symbol appears.

Expected Result:
While typing any message there should not be any typing indicator symbol appears on the screen.

Test Environment:
OS: Win 10 21H1
Build: OS Build 19043.1147
Browser: Edge Chromium Version 94.0.972.2 (Official build) dev (64-bit)
#URL: https://microsoft.github.io/BotFramework-WebChat/05.custom-components/b.send-typing-indicator/

**Comment by KattaBhargav** [comment]
#A11yUsable;#A11ySev4;#HCL;#Accessibility;#Win10-Edge(Chromium);#E2E-HCL-BotFrameworkWebChat-Aug21;

**Comment by compulim** [comment]
The sample is demonstrating the bot's typing by mirroring user's typing. In other words, when the user types, the bot will send a typing indicator at the same time.

This is not a production issue, but we should update the sample to make it less confusing. Probably a separate button on the page to ask the bot to send a typing indicator (instead of mirroring).

**Comment by v-shikch** [comment]
As verified issue on URL: Web Chat: Full-featured bundle (microsoft.github.io) on Browser: Edge Chromium Version 96.0.1028.0 (Official build) dev (64-bit), here issue is fixed. Hence closing the bug.

**Comment by compulim** [comment]
Thanks @v-shikch. Appreciated.
