### ISSUE TITLE
Throwing error from webchat js when clicking multiple times on microphone input (Direct line speech channel)

### ISSUE THREAD

**Issue by sreejithrkknd** [microsoft/BotFramework-WebChat#4042]
When no input is given to the mic I am sending a message to the user to input something but when that message comes to the direct line speech does not stop dictating the event and its starts the speaking event then the bot is crashing.

The following are the errors I am getting

webchat.js:2 Error: Failed to stop recognition while the current one is ongoing and is not abortable.
    at webchat.js:2
    at oa (webchat.js:2)
    at Ra (webchat.js:2)
    at l (webchat.js:2)
    at p (webchat.js:2)
    at MessagePort.D.port1.onmessage (webchat.js:2)

**Comment by sreejithrkknd** [comment]
If I didn't give any response to the bot via mic I was sending a message to the user to input something this was causing the issue. so

**Comment by mohmed-elkhodry** [comment]
Did you mean you are sending message activity with ("inputHint":"expectingInput") 
and as mic open causes the issue ?
