### ISSUE TITLE
Is the latest version of WebChat stopped sending the "locale" to the bot registration channel

### ISSUE THREAD

**Issue by arman-g** [microsoft/BotFramework-WebChat#4043]
For some reason the locale is not being passed to the bot from webchat. 
1. Is there a new implementation of directline or something in the new version?

If I specify locale in renderWebChat and not in directline's "conversationStartProperty" as shown [here](https://github.com/microsoft/BotFramework-WebChat/blob/31d0b69ccee674174634d8da10ff7670ffdfc5e9/packages/embed/src/setups/version4.js#L11), than the locale is not passed to the bot.

Although the [documentation](https://github.com/microsoft/BotFramework-DirectLineJS/blob/master/README.md) says that the locale in the directline is optional, if I don't specify it will not be passed to the bot.

2. So if we need to specify locale in the Direct Line then do we have to specify it in renderer? It seems it has no impact.
![IMG1](https://user-images.githubusercontent.com/22778273/131902946-00cc92ec-708a-4536-baee-10fb0f899791.png)

## Screenshot

![IMG](https://user-images.githubusercontent.com/22778273/131896719-da60411d-59c4-45d9-ad93-3ec9a42cdd85.png)

**Comment by compulim** [comment]
The [`conversationStartProperties` is an option for DirectLineJS](https://github.com/microsoft/BotFramework-directlinejs#create-a-directline-object), not Web Chat. 😅

You would specify it like:

```js
renderWebChat(
  {
    directLine: createDirectLine({
      conversationStartProperties: {
        locale: 'ja-JP'
      },
      token: '...'
    }
  },
  document.getElementById('webchat')
);
```

It is an optional parameter for the Direct Line protocol to send a property bag to the bot before conversation start.

**Comment by arman-g** [comment]
@compulim the reason I am asking this question is because I was not passing the locale in the conversationStartProperties under direct line but only specifying it under renderWebchat function and it was it was being passed to the bot. Recently it stopped passing  locale to the bot, unless I specify it under direct line. So my question is did something change in webchat recently that my old setup stop working?

**Comment by arman-g** [comment]
@compulim so for clarification, we still need to specify the local for web chat regardless direct line right?

**Comment by compulim** [comment]
IIRC, the `locale` was never passed to the bot from Web Chat. The `conversationStartProperties` was a feature ask to fill a missing gap.

Yes, you still need to pass `locale` to Web Chat.

**Comment by arman-g** [comment]
Ok, got it. Thank you!
