### ISSUE TITLE
npm install (technically tsc) fails when trying to build

### ISSUE THREAD

**Issue by adamtuliper** [Microsoft/BotFramework-WebChat#405]
I seem to have an issue building the latest. I've tried on three different developer machines - all fail in same place when tsc runs. Running tsc at cmd prompt by itself yields same issue. Any thoughts?

> botframework-webchat@0.10.4 prepublish .\BotFramework-WebChat
>  tsc && npm run build-css && webpack --config webpack.production.config.js
> 
> src/MessagePane.tsx(53,80): error TS2339: Property 'map' does not exist on type '{ actions: CardAction[]; to?: string[]; }'.
> src/MessagePane.tsx(72,42): error TS2339: Property 'length' does not exist on type '{ actions: CardAction[]; to?: string[]; }'.

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! botframework-webchat@0.10.4 prepublish: `tsc && npm run build-css && webpack --config webpack.production.config.js`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the botframework-webchat@0.10.4 prepublish script 'tsc && npm run build-css && webpack --config webpack.production.config.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the botframework-webchat package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     tsc && npm run build-css && webpack --config webpack.production.config.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs botframework-webchat
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls botframework-webchat
> npm ERR! There is likely additional logging output above.
>

**Comment by danmarshall** [comment]
Hi @adamtuliper looks like you're between the builds - You've got the latest version of DirectLineJs which is a little ahead of the WebChat. Thanks for your PR!

**Comment by buluttokat** [comment]
I had the same issue with botframework-webchat@0.11.0 prepublish. npm was downloading DirectLineJs 0.9.9 because of the dependency string "botframework-directlinejs": "^0.9.8" in package.json. Fixing the version to 0.9.8 by removing "^" solved the issue for me.
