### ISSUE TITLE
Show first text bubble at top of chat-box

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#4054]
The rendering of messages in webchat starts at the bottom. and messages move up while new ones are added.
 
Especially with multiple answers sent by the bot (eg a welcome menu), reading the text messages this feels unnatural and confusing for users. 

It is just hard to read a list with messages when the message your eyes are focused on is moving up all the time. (just try it)

People are used to read a page top-down. Especially during the first impression of the chatbot it makes sense to support users by showing the first number messages top down.

Is there a way to show the first bubble on top of the chatbox? It would improve the UI and succesrates of my chatbots a lot

![image](https://user-images.githubusercontent.com/23032884/133994703-81907e23-e42f-415c-b020-7910f406d2f0.png)

**Comment by stevkan** [comment]
@HesselWellema, I'll defer to @compulim regarding the priority of this as a feature request. Adding a toggleable option in Web Chat's `StyleOptions` could be a consideration.

Looking at a number of other chat apps, such as Facebook Messenger, WhatsApp, Teams, Discord, and Slack, all but Messenger display the conversation initially at the bottom with the conversation history moving up the frame. Only Messenger starts at the top of that group. Regardless, once the visible frame is filled with conversation, all chat apps look the same with the most recent message at the bottom and the conversation history moving upward.

That being said, if you want the chat to initially start at the top of the frame building downwards until the frame is filled up, then you can include the below bit of code in the `<style></style>` section of your Web Chat's hosting page. I haven't tested this in depth so I don't know what other consequences might arise from using this, but it worked when I implemented it. You will want to test different scenarios to be sure it functions how you wish.

```css
div .webchat__basic-transcript__scrollable {
  display: block !important
}
```

Please keep in mind that altering Web Chat's DOM directly goes against best practices. I recognize that this may be the only means of achieving this (presently), so there may be no other choice. Just be aware that future releases of Web Chat may result in a breaking change as components, classes, and/or features may change. This could result in a disrupted user experience should this happen.

**Comment by HesselWellema** [comment]
Tnx for the suggestion @stevkan, I will give it a go.

**Comment by compulim** [comment]
The correct CSS should be:

```css
.webchat__basic-transcript__filler {
  display: none;
}
```

(The "filler" is a component to fill the rest of the page and push messages down to the bottom.)

**Comment by HesselWellema** [comment]
I will close this one. Thanks for your help.
