### ISSUE TITLE
Is there any size limit for uploading attachment in webChat in bot framework, because when uploading above 4mb size attachments gets timeout issue?

### ISSUE THREAD

**Issue by satyanarayana7** [microsoft/BotFramework-WebChat#4086]
Is there any thing to do with App service or azure bot price tier upgrade? will it allow attachment above 4mb size to upload. Currently when uploading any attachment above 4mb size, the attachment is getting timeout issue and not reaching to Bot only. In Bot Emulator there is not attachment size issue, but when it published to app service , attachments above 4mb are getting failed.

**Comment by MikeCardiff** [comment]
There is a 4mb size limit imposed by the DirectLine channel. The only way around this is to bypass DirectLine when uploading an image.

Emulator uses it's own channel and does not go through DirectLine so does not have the same limit.

See this sample for an idea of a workaround by uploading to Azure Blob instead: https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/07.advanced-web-chat-apps/a.upload-to-azure-storage

Not sure if there are any better alternatives. Would be good to know if there are any!
