### ISSUE TITLE
TextContent Color and FontSize not working with updated version

### ISSUE THREAD

**Issue by RebeccaAxelro** [microsoft/BotFramework-WebChat#4087]
I have upgraded the BotFramework webchat from 4.12.0 to 4.14.1.
I am now receiving an error that color and fontSize doesn't work under TextConent. What changed and how can I change the color and fontSize![Screenshot 2021-11-23 122359](https://user-images.githubusercontent.com/36717212/143073803-533ce785-bf30-4a99-b7cb-2c595e18b52e.png)

**Comment by stevkan** [comment]
@RebeccaAxelro, unfortunately, I am not able to repro the issue using v4.14.1. Can you verify:

- The CDN points to the 'latest' release and not another build (like 'main' or something else)? You can also run the following code in the developer's console of your browser to check the reported version:

```js
[].map.call( document.head.querySelectorAll( 'meta[name^="botframework-"]' ), function ( meta ) { return meta.outerHTML; } )
```

- You are passing 'styleSet' into the Web Chat component as a property. It's doubtful you aren't, but always worth checking for typos and the like. It should read `styleSet: styleSet` for vanilla-JS Web Chat and `styleSet={styleSet}` for the react flavor.

Also, is my own context, is there anything special about the hosting page? For instance, is this a React or Angular build, is it being used in another client such as WordPress or Microsoft Dynamics OmniChannel, or something else?

**Comment by stevkan** [comment]
Closing due to lack of response.
