### ISSUE TITLE
Adaptive Card -media player is not supporting,unable to hear voice in IPhone Safari/chrome browser

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/BotFramework-WebChat#4088]
Hi could you please help me out if there any known issues in IOS Safari browser while playing a audio using adaptive card media url inside a chatbot(bot framework v4). I am not able to hear the voice while playing audio in IOS safari.
Below is the code :
     var pronunciationPlayBack = new AdaptiveMedia()
                            {
                                Type = "Media",
                                Sources = new List<AdaptiveMediaSource>()
                                             {
                                                new AdaptiveMediaSource()
                                                {
                                                     Url = pronunciationUrl,
                                                     MimeType = "audio/mpeg"
                                                }

                                }

                            };

**Comment by amoyalan20** [comment]
Any updates on this issue?

**Comment by benbrown** [comment]
@amoyalan20 Can you tell us more about what you are doing with this card?

Is the problem that the embedded media does not play?

Are you also using text to speech?

Can you send the JSON of the adaptive card itself?

**Comment by amoyalan20** [comment]
**JSON of the adaptive card**
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Media",
      "sources": [
        {
          "mimeType": "audio/mpeg",
          "url": "https:..."
        }
      ]
    }
  ]
}
![image](https://user-images.githubusercontent.com/73281779/145042179-6ce279de-8698-404c-a787-77d6d669d4a4.png)
**Not able to hear the audio while its playing in ios mobile device.**

**Comment by benbrown** [comment]
@amoyalan20 can you inspect the embedded media in the browser and see if it is valid?

Does this card play in a desktop browser?

Is this directly in the mobile browser, or in an app?

**Comment by amoyalan20** [comment]
@benbrown  This card was integrated inside bot and was able to hear the audio in desktop browser.
The issue is only with the iPhone safari/chrome browsers but the same which is working in MAC and in iPad.

**Comment by amoyalan20** [comment]
is there any updates?

**Comment by amoyalan20** [comment]
@benbrown  any updates on this issue?

**Comment by carlosscastro** [comment]
@benbrown do you have updates on this front? Let me know if you need help coming up with a plan to prioritize / move this forward.

**Comment by benbrown** [comment]
We need @compulim to weigh in here.

**Comment by msomanathan** [comment]
@compulim Could you please provide updates to this issue? Thanks!
