### ISSUE TITLE
[Accessibility] [Omnichannel] A11Y_Post survey link opens a new window/tab without warning the user

### ISSUE THREAD

**Issue by kevinlin98z** [microsoft/BotFramework-WebChat#4091]
Copied from [Bug 2535908](https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/2535908): A11Y_Post survey link open a new window/tab without warning the user.

Environment Details:
Application Name: Microsoft Dynamics 365 Omnichannel Online Chat – CRA Online Chat Agent
#URL: [Omnichannel Agent Dashboard](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2forgf84480f6.crm10.dynamics.com%2fmain.aspx?appid%3D34316207-9a30-ec11-b6e6-000d3a9d1020&data=04%7c01%7cv-rojad%40microsoft.com%7c40f3e6a05a7d4b84155708d9b3e0364b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637738597844030186%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=5vzWeN6JqhUT9UU%2BGpgIuMAQXOjQxozMHOsXr9Uf4tE%3D&reserved=0)
Windows Version: Win10
Chromium edge Version 98.0.1089.1 (Official build) dev (64-bit)

## Repro Steps:
1. Start Narrator/jaws.
2. Hit the URL "Omnichannel Agent Dashboard" and login with appropriate credentials
3. Tab to Omnichannel Administration app and hit enter
4. Tab to "chat" menu item and hit enter, select a chat and tab to code snippet under general settings.
5. Open url "aka.ms/omniwidget" and paste the code from code snippet .
6. Tab to the Let's chat button and initiate a conversation 
7. Hit URL: Omnichannel Agent Dashboard and log in with appropriate credentials in another browser as an agent.
8. Tab till accept button in the new chat dialog and press enter.
9. Again go to the Let's chat button and close the conversation .
10. Post survey link will come. Tab to the link and press enter.
11. Verify whether Post survey link open a new window/tab without warning the user or not.

## Actual Result:
Post survey link opens a new window/tab without warning the user. Screen reader is not reading that a new page/tab is opening.

## Expected Result:
User should get a warning for the post survey link opening a new window/tab. 'Post survey' link has target="_blank" attribute. The request is to add any html feature (span, div, alt, etc) to indicate to screen reader that a new page/tab will be opened.

## User Impact:
Screen reader user will be confused if the link will open in a new window/tab without warning the user.

## Screenshots
Survey link comes as message:
![image](https://user-images.githubusercontent.com/13504205/145495659-93b4f8a2-06a7-4188-aacd-1ada19de1f13.png)

Link opens in new tab when clicked: (screen reader does not warn about the new tab upon this action)
![image](https://user-images.githubusercontent.com/13504205/145495755-67c1186d-08e7-469b-956b-3cce1fc10085.png)

## Additional Context
Note: see attached video in the bug copied above for more clarity

**Comment by compulim** [comment]
Could you let us know which version of Web Chat is using on Omnichannel?

> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`

We have added a feature to show the "Open in new windows" icon and it will by read by screen reader. This feature is done in 4.13.0 (released 2021 April), [changelog here](https://github.com/microsoft/BotFramework-WebChat/blob/main/CHANGELOG.md#4130---2021-04-05)

When the feature is on, you should see:

- An icon indicating open in new window
- Invisible screen reader text indicating "Opens in a new window; external." ([code here](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/api/src/localization/en-US.json#L86))

The screenshot below shows the feature using Web Chat 4.14.1 (small print on bottom right corner).

![image](https://user-images.githubusercontent.com/1622400/153646972-0c1bf1e8-3e5f-4ef2-b313-2a06ca61cd84.png)

**Comment by kevinlin98z** [comment]
@compulim current version of webchat being used is 4.14.1
![image](https://user-images.githubusercontent.com/13504205/153966557-c1fd2371-b408-44fb-ba79-670460c7a8a8.png)

"Open in new window" icon is still not present within the link as part of the message sent
![image](https://user-images.githubusercontent.com/13504205/153966676-fff7f49c-fad8-45c4-b1a6-b246bdf950fd.png)

**Comment by compulim** [comment]
I talked to Edward/Edgar and we found that the JSON file is not always reflecting the actual version of Web Chat loaded.

It will be more accurate if you can look at the DOM tree like below:

![image](https://user-images.githubusercontent.com/1622400/154300810-57ac9324-2f6b-40b5-adad-bb2adbdc027e.png)

If Web Chat is not hosted in an IFRAME, you can run the following code to grab the actual version:

`[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`

**Comment by compulim** [comment]
Worked with Edgar offline. This is because Omnichannel is not using Web Chat to render the text content. Thus, the "Open in new window" icon is not displayed.
