### ISSUE TITLE
[Accessibility] [Omnichannel] after minimize the chat widget , Screen reader doesnt read new messages when the chat is launch again

### ISSUE THREAD

**Issue by elopezanaya** [microsoft/BotFramework-WebChat#4098]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

Environment Details:
Application Name: Microsoft Dynamics 365 Omnichannel Online Chat – CRA Online Chat Agent
#URL: Omnichannel Agent Dashboard
Windows Version: Win10
Chromium edge Version 98.0.1089.1 (Official build) dev (64-bit)

## Describe the bug

When the user tabs to the minimized chat window and opens it after hearing that a message has been received, the screen reader does not automatically start reading the messages they received.

## Steps to reproduce

1. Start Narrator/jaws.
2. Hit the URL "Omnichannel Agent Dashboard" and login with appropriate credentials
3. Tab to Omnichannel Administration app and hit enter
4. Tab to "chat" menu item and hit enter, select a chat and tab to code snippet under general settings.
5. Open url "aka.ms/omniwidget" and paste the code from code snippet .
6. Tab to the Let's chat button and initiate a conversation, after that minimize the chat window
7. Hit URL: Omnichannel Agent Dashboard and log in with appropriate credentials in another browser as an agent.
8. Tab till accept button in the new chat dialog and press enter.
9. From the agent chat, reply the message from the customer
10. From the customer side, open the chat
11. Narrator should start to read the new messages send by the agent.

## Expected behavior

Narrator should start to read the new messages send by the agent.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
@compulim  Any updates on this issue?

**Comment by carlosscastro** [comment]
@compulim could you please pick up this issue? Thanks

**Comment by msomanathan** [comment]
@compulim Could you please provide an update to this issue?

**Comment by compulim** [comment]
I need more technical details here, will ping Edward/Charlie internally.

**Comment by compulim** [comment]
When the chat widget is minimized, Omnichannel is adding "display: none" to hide Web Chat.

Thus, all new incoming messages are not narrated.
