### ISSUE TITLE
[Accessibility] [Omnichannel]  Screen reader is not notifying the user when the agent is typing

### ISSUE THREAD

**Issue by elopezanaya** [microsoft/BotFramework-WebChat#4099]
Environment Details:
Application Name: Microsoft Dynamics 365 Omnichannel Online Chat – CRA Online Chat Agent
#URL: Omnichannel Agent Dashboard
Windows Version: Win10
Chromium edge Version 98.0.1089.1 (Official build) dev (64-bit)

## Describe the bug

When the user tabs to the minimized chat window and opens it after hearing that a message has been received, the screen reader does not automatically start reading the messages they received.

## Steps to reproduce

1. Start Narrator/jaws.
2. Hit the URL "Omnichannel Agent Dashboard" and login with appropriate credentials
3. Tab to Omnichannel Administration app and hit enter
4. Tab to "chat" menu item and hit enter, select a chat and tab to code snippet under general settings.
5. Open url "aka.ms/omniwidget" and paste the code from code snippet .
6. Tab to the Let's chat button and initiate a conversation
7. Hit URL: Omnichannel Agent Dashboard and log in with appropriate credentials in another browser as an agent.
8. Tab till accept button in the new chat dialog and press enter.
9. From the agent chat, reply the message from the customer
10. Narrator should notify the user that the agent is typing.

## Expected behavior

Narrator should start to read the new messages send by the agent.

## Additional context

[Bug]

**Comment by tdurnford** [comment]
@compulim  Any updates on this issue?

**Comment by carlosscastro** [comment]
@compulim could you please update this issue?

**Comment by msomanathan** [comment]
@compulim Could you please provide an update to this issue?

**Comment by compulim** [comment]
This is a new feature and will be triaged.
