### ISSUE TITLE
Profile concept for group messaging 

### ISSUE THREAD

**Issue by jecristi** [microsoft/BotFramework-WebChat#410]
![inital and multiple name proposal](https://cloud.githubusercontent.com/assets/16601819/24629535/302a9ece-186e-11e7-9350-f5428c54406b.png)

This designs would be used for group messaging for users with one or two names. If there is one name it uses the first letter, if there is two names it uses the first letter of each name. If there are users with the same initials, then the same letters would be used, but they would be assigned different colors.

Hex values:
E81123, DA3B01, CA5010, 10893E, 038387, 0078D7, 721481, 9A0089, BF0077, 767676, 2B2B2B

**Comment by jrmcdona** [comment]
@danmarshall when do you think Group chat will be supported in Webchat?   By group I am meaning one more users with the bot orchestrating the messages.     I know this was enabled in Skype recently.   Thanks

**Comment by danmarshall** [comment]
Hi @jrmcdona, DirectLine already supports it, but the scenario still requires you to do a few things on your own, such as inviting others, and the UI described above where you san see the icon/avatar for the others.

**Comment by sgellock** [comment]
consider doing the initial work

**Comment by cwhitten** [comment]
No roadmap plans to implement this. Closing.
