### ISSUE TITLE
Clicking on button should scroll to bottom of feed

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/BotFramework-WebChat#411]
When user clicks on a button in the feed and they've scrolled up a bit, the new output from the bot isn't visible without manually scrolling down

The ui should scroll to the bottom when a button click results in more output

**Comment by billba** [comment]
What do other channels do?

**Comment by danmarshall** [comment]
@reyesrico - can you provide behavior per channel?

**Comment by LarsLiden** [comment]
I think most jump to the bottom (just confirmed on Facebook)

**Comment by reyesrico** [comment]
**Web Version**
Channel      Scroll automatically to feed?   Notes
Telegram      No                                           Every click appears a response below with msgs counter.
Slack            No                                           Every click  appears a summary of the msgs below.
Skype           No                                           Every click appears a "typing" activity below. 
Facebook     Yes                                           Every click scroll downs automatically.
Teams          Yes                                           Every click scroll downs automatically.

**Comment by danmarshall** [comment]
Thanks @reyesrico . @jecristi - can you weigh in from the design side?

**Comment by danmarshall** [comment]
So this may also be related - what if you are scrolled up to an older message in your stream, and then the bot responded with a message to you. Should the interaction model be:

- Toast (x new messages below)
- Scroll you to the bottom (which may or may not be annoying, if you took the time to scroll upwards to get to a particular message)

**Comment by LarsLiden** [comment]
Wonder if there's a way to differentiate:

1) If user clicks on a button, always scroll to bottom to see new result
2) If bot posts an unsolicited response, don't scroll to the bottom

Case 1 occurs *much *more frequently than Case 2 in my experience

**Comment by reyesrico** [comment]
@LarsLiden  In case #2 I suggest to have a space or icon that can show that there are pending messages to read below.

**Comment by LarsLiden** [comment]
I like that.  So'd we'd have:

1) If user clicks on a button, always scroll to bottom to see new result
2) If bot posts an unsolicited response, don't scroll to the bottom but
show icon that there's a new message

**Comment by LarsLiden** [comment]
There's actually a 3rd condition.  Namely when you scroll up and they type something it also stays scrolled up even after you submit new text to the bot.  Seems like to should jump to the bottom on this one too as the user just submitted new content to the bot

**Comment by danmarshall** [comment]
We have implemented this feature. Yay! But, it has caused an issue on mobile devices which makes the device keyboard appear when the textbox gets focus. Perhaps it should be an optional behavior.

**Comment by billba** [comment]
I believe this would benefit from a holistic analysis. Native chat clients have sophisticated integration of keyboard, focus & scroll behavior. We may be limited in what we can accomplish, but let's not rush into adding an option when the answer might be to have better heuristics.

**Comment by macrozone** [comment]
@danmarshall this is annoying if you use a lot of buttons. Is there an option to turn this off?

**Comment by macrozone** [comment]
I added an option in a PR to disable this: https://github.com/Microsoft/BotFramework-WebChat/pull/456

**Comment by danmarshall** [comment]
@macrozone which of these 2 features are you referring to?:
* Scrolling to the bottom
* Focusing the textbox

**Comment by macrozone** [comment]
@danmarshall: i am referring to focusing the textbox, which opens the keyboard on ios. That makes it really hard to read all options if you have several buttons / options

**Comment by kalykodu** [comment]
@danmarshall  can you please help me . I am trying to achieve the same.

**Comment by nupurkamble** [comment]
@billba 

> Clicking on button should scroll to bottom of feed
has this problem been solved ? my bot is deployed using directline. and the bot does not scroll automatically to the bottom.

**Comment by nupurkamble** [comment]
@LarsLiden 

> If user clicks on a button, always scroll to bottom to see new result

has this issue been solved ?
my bot is deployed using backchannel. and the bot does not scroll automatically to the bottom every time a button on richcard is clicked.

**Comment by photodesignch** [comment]
@nupurkamble This issue has been raised. We were discussing for the solution. It will be fixed soon.

**Comment by reyesrico** [comment]
@LarsLiden merge has been done. The autoscroll will be triggered when there is any action from the user. Can you please confirm?
