### ISSUE TITLE
Issue with adaptive card in teams use by Bot

### ISSUE THREAD

**Issue by rohan081296** [microsoft/BotFramework-WebChat#4111]
I have created chatbot with bot composer and published it on azure and enabled teams channel too.

I have used adaptive card in chatbot. When I click on button in adaptive card in teams, it is showing message "Your response was sent to the app".

When I check same with web chat, It is not showing any message like this.

Ideally, I don't want this type of message when click on button in adaptive cards.

`{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.3",
"body": [
{
"type": "TextBlock",
},
{
"type": "Input.ChoiceSet",
"id": "myChoiceData",
"style": "expanded",
"value": "Product Data",
"placeholder": "Product Data",
"choices": [
{
"title": "Product Data",
"value": "Product Data"
},
{
"title": "Customer Data",
"value": "Customer Data"
},
{
"title": "All/Others",
"value": "All/Others"
}
]
}
],
"actions": [
{
"type": "Action.Submit",
"title": "OK"
}
]
}`

![image](https://user-images.githubusercontent.com/96237252/149771370-8ab21477-8928-4b80-ae97-08e797fd6bd7.png)

**Comment by anishprasad01** [comment]
These types of helper toast messages are a Teams feature, and are not controlled by the bot. That is why they appear only in Teams and not in web chat. They have nothing to do with the bot code or adaptive card JSON you have written. At this time, there is no way for you as a bot developer to remove them.

**Comment by rohan081296** [comment]
Ok @anishprasad01 . Thank you for your response.
