### ISSUE TITLE
The microphone immediately turns off when the user says something incomprehensible for the bot

### ISSUE THREAD

**Issue by KamilaWhocares** [microsoft/BotFramework-WebChat#4127]
## Version

4.14.1

## Describe the bug

When the user clicks the mic and then says some incomprehensible words that the bot can't recognize, the mic just turns off without waiting for further input and without throwing any errors.

## Steps to reproduce

1. Go to https://microsoft.github.io/BotFramework-WebChat/03.speech/g.hybrid-speech/
2. Click on the microphone button
3. Say something incomprehensible
3. Notice how the mic turns off, no input is being sent and no error is being thrown in the console

## Expected behavior

Maybe some sort of SpeechRecognition error could be thrown just like the SpeechRecognitionErrorEvent is thrown when the user clicks the mic button and does not say anything for a few seconds or maybe this event could be treated as if the user didn't say anything and the bot could wait for a few more seconds for some further input before the mic is turned off.

[Bug]

**Comment by stevkan** [comment]
Unfortunately, I am unable to repro the issue when visiting the site. When speaking gibberish, the speech service makes a best guess at what the words are, entering the words, and the speaking them. Can you verify that you have allowed your microphone access to the site? The location of the setting may vary between browsers, but in Edge it is located to the left of the address bar as well as in settings.

![image](https://user-images.githubusercontent.com/18403946/151583122-e46c1b06-d2ef-402f-8cda-760e0c4ca873.png)

If that is not the cause, can you open the browser's developer console and see if any errors are being logged. If so, can you provide them?

**Comment by KamilaWhocares** [comment]
Hi,

first of all, sorry for such a late reply.

I have allowed my microphone. I am able to have a perfectly fine
conversation with a bot until I speak something incomprehensible for the
bot like, for example "chrząszcz" (which is a word from my native tongue),
then the mic turns off without throwing any error. The problem occurs, I am
pretty sure of that, I even managed to capture it on the video I've
attached, so you can check it out if you'd like.
In the first part of the video I show that the mic waits for a few seconds
and then throws an error if there was no input from the user, then I show
normal behavior when I say "hi" to the bot and at the end I say polish word
"chrząszcz" after which the mic turns off silently without any error.
I get it that sometimes the bot doesn't know what I'm saying, but as I
suggested in my issue, maybe it could throw an error or wait a few more
seconds for further input if that is the case.

Thank you for your time,
Kamila
 Web Chat_ Hybrid speech engine using JavaScript...
<https://drive.google.com/file/d/1Jmh7vUYvvrkayHSfhacuAaOqJEaD9_0p/view?usp=drive_web>

PS. If for some reason you can't play my video, let me know if there is any
other way for me to show my issue.


pt., 28 sty 2022 o 17:24 Steven Kanberg ***@***.***>
napisał(a):

**Comment by stevkan** [comment]
@KamilaWhocares, I am still unable to repro the issue. I even repeated 'chrząszcz' (as best I could), and Web Chat always tried to identify the correct word with guesses like: Schultz, show host, and trust. So, at this moment, I don't know why this wouldn't be working for you.

Can you verify for me the version of Web Chat the page is loading for you? It should be 4.14.1. If you see something different, you may need to clear your browser's cache, history, etc. It may be worth trying that anyhow.

You can get the version by running the below code in the browser's console window.
```js
[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')
```

Also, could you tell me which browser you use, the version, and the locale it is set to?

**Comment by KamilaWhocares** [comment]
To be honest this problem does not seem to be that rare in my experience. I've been able to successfully trigger this behavior multiple times. I've been also working on a more customized bot using this library and not only me, but a few of my colleagues have also observed this issue with other words, even English ones.

The Web Chat's version is 4.14.1. I use Chrome 97 and my locales are en-US, en and pl.

Here  are two screenshots of me checking these things:
a) from console:
![image](https://user-images.githubusercontent.com/53226152/152822933-7e460537-32a7-4618-88e1-1e2b7525d0bd.png)
b) from chrome://settings/languages:
![image](https://user-images.githubusercontent.com/53226152/152823290-20e51797-1973-45f6-8565-f7939ccade99.png)

**Comment by stevkan** [comment]
@KamilaWhocares, I'm looking into whether the number of language included in the settings is somehow confusing the speech feature. It's just an idea at this point, but I will let you know what I find on this point and any additional ideas I may have.
As an aside, if you remove the additional language and use just the English (United States), does it work?

**Comment by stevkan** [comment]
@KamilaWhocares, thank you for your patience. Unfortunately, I simply am unable to repro the issue. I checked a couple more areas I thought _might_ be the cause and would result in what you are experiencing, but nothing has panned out. Out of curiosity, does this occur when you use other browsers or test on another device?

@compulim, do you have any thoughts you could add here that might assist?

**Comment by stevkan** [comment]
@KamilaWhocares, is there any chance you are running behind a firewall or proxy? If so, there is a possibility that they may be blocking or stripping part of the post to Cognitive Services. Additionally, if so, can you try testing on a system that is not blocked (at your home, for example)?
