### ISSUE TITLE
[Supporting the platform-AskHR Virtual Assistant]: In High Contrast Black mode, emojis are not clearly visible in the 'Feedback' section present in the page.

### ISSUE THREAD

**Issue by KattaBhargav** [microsoft/BotFramework-WebChat#4137]
**User Experience:**
Color sensitive users who rely on high contrast modes(Black) are getting impacted as emojis are not clearly visible in the 'Feedback' section present in the page.

Note: User credentials should NOT be included in the bug.

**Prerequisite**:
Go to Ease of Accessibility settings-> Navigate to 'Turn high contrast On or off' in system settings -> Toggle On the 'Turn on high contrast' button -> Choose High Contrast Black/White themes.(Edge Browser).

**Repro Steps:​**
1. Open the above URL in the Edge Browser using valid credentials. 
2. 'AskHR Virtual Assistant' Home page gets opened.
3. Select Benefits--> Laya-->Select Yes. Now observe emojis present in the Feedback section in High Contrast Black modes
4. Verify whether while navigating in High Contrast Black mode, emojis are clearly visible in the 'Feedback' section or not.

**Actual Result:**
While navigating in High Contrast Black mode, emojis are not clearly visible in the 'Feedback' section present in the page.

**Expected Result:**
While navigating in High Contrast Black mode, emojis should clearly visible in the 'Feedback' section present in the page.

**MAS reference:**
[WCAG4.3.1 – No Disruption of Accessibility Features](https://microsoft.sharepoint.com/:w:/s/accessibility/EcT3cDhDfMZDqff9c9gAv9ABdRhxyVsppMsK-WDlXMpxug?e=VxkwcO&isSPOFile=1) 

**Reference Links:**

- [Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-poyad%40microsoft.com%7cc11478591b5a474f6d9d08d7199726c0%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637006009300301864&sdata=ZTWYamT1yE7yko5QU35ZJLf/5ZydtDeGAKrQGUiugJs%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.
- External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this [Link](https://microsoft.sharepoint.com/teams/ceacc/SitePages/External-Bug-process.aspx). “HCL Staff should not log any third party external bugs. Should be routed to edad team”.
- Please reach out to [C&AI Teams channel](https://nam06.safelinks.protection.outlook.com/?url=https://teams.microsoft.com/l/team/19%253a3cd071821b694f11b054d878453cd75f%2540thread.skype/conversations?groupId%3D30e3f968-15dd-4da2-bd8e-85f27e4af2c3%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=02%7c01%7cv-dhti%40microsoft.com%7cf90880a914be401871f108d763233116%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637086876782361405&sdata=/ULS%2BbeqMjysCoiWHvFgAbSnuFJqxO3wtpHmlidPjbU%3D&reserved=0) for any process related queries.

**Test Environment:** 
OS: Windows 10 version 21H1 (OS Build 19043.1110)
Browser: New Edge Version 98.0.1100.3 (Official build) (64-bit)
URL: [AskHR Virtual Assistant (azureedge.net)](https://askhrvauat.azureedge.net/?botorigin=hrweb)

**Comment by KattaBhargav** [comment]
#A11yMAS;#A11ySev2;#HCL;#WCAG4.3.1;#Accessibility;#Win10-Edge(Chromium);#BotFrameworkWebChat-Aug21;#Benchmark;#CSEO:BUG8005236;#Firstparty:CSEO;#Regressed:02-09-22;#Regression;

**Comment by compulim** [comment]
It seems to be an issue on the OS/browser side.

Unlike Teams, Web Chat do not render emoji using custom graphics. We relies solely on OS/browser to show the emoji.

In this case, when running under high contrast mode, I believe Edge should render the emoji in monochrome, to match the style from the OS.

Under high-contrast mode, the following is the Emoji Panel under Windows 11. It render emojis in monochrome.

![image](https://user-images.githubusercontent.com/1622400/153651625-94a27183-bbcd-46c0-a2c5-d25f10162da6.png)

This is how it looks when rendering emoji in Web Chat.

![image](https://user-images.githubusercontent.com/1622400/153651094-df23e49b-ebea-4f69-a578-cb9567668a37.png)

This is how it looks when rendering emoji on Bing.com.

![image](https://user-images.githubusercontent.com/1622400/153651848-04a41729-fe9f-4e19-8590-d2115b66897f.png)

I have tested Chrome, Edge, and Firefox, all of them did not taking high-contrast into account when rendering emojis.

**Comment by axelsrz** [comment]
Issue seems to be resolved from the BF side, closing thread. If problem persists, please open a new one.
