### ISSUE TITLE
ARIA complementary region values are inconsistent: Omnichannel Agent Dashboard

### ISSUE THREAD

**Issue by karthsMicrosoft** [microsoft/BotFramework-WebChat#4140]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

**Environment Details:**
Application Name: Microsoft Dynamics 365 Omnichannel Online Chat – CRA Online Chat Agent
#URL: Omnichannel Agent Dashboard
Windows Version: Win10
Microsoft Edge: Version 93.0.933.1 (Official build) dev (64-bit)
Chrome : Version 91.0.4472.124 (Official Build) (64-bit)
OS :21H1 19043.1052(64 bit)

**Repro Steps:**
1.Start jaws/NVDA/Narrator.
2.Hit the Omnichannel Agent Dashboard url and login with appropriate credentials
3.Tab to Omnichannel Administration app and hit enter
4.Tab to "chat" menu item and hit enter, select a chat and tab to code snippet under general settings.
5.Open url "aka.ms/omniwidget" and paste the code from code snippet .
6.Tab to the conversation button and initiate a conversation 
7.Hit Omnichannel Agent Dashboard url and log in with appropriate credentials in another browser as an agent.
8.Tab till accept button in the new chat dialog and press enter.
9.A JAWS/NVDA/Narrator  user will pull-up the Regions list.
10.Verify whether the all the transcript information under complementary region will be available or not.

**User Impact:**
Screen reader users will not able to understand the whole information if the transcript under complementary regions are not available every time 
MAS Reference:
[MAS 1.3.1 – Info and Relationships](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/CELA/Official_Microsoft_Accessibility_Standards/MAS%201.3.1%20%E2%80%93%20Info%20and%20Relationships%20.docx?d=w97358e8843674121bf9df0c6597d03b7&csf=1&web=1&e=yKDvRP)

"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

**Actual Result:**
The ARIA complementary region has an inconsistent behavior. At times we can use regions to navigate to the Communication panel transcript and we can read all the conversation.
This information is not available every time, most of the time the transcript is not available in the Complementary information region

**Expected Result:**
Consistent complementary region values are expected. Having all the transcript available in the complementary region improves the user experience as it offers quick reading and navigation, and it removes the extra verbosity encountered when navigating directly within the transcript area in the panel.

**Additional context**
[Bug]
![2539947_Repro attachment_NVDA+Chrome config](https://user-images.githubusercontent.com/99693139/153960885-abb99ff9-5434-43d5-9558-adced4ddc2d6.png)
![2539947_Repro attachment_JAWS+Chrome config](https://user-images.githubusercontent.com/99693139/153960887-3d8697c8-9c42-4cf8-b8fc-33c8fc5eca9e.png)
<img width="242" alt="Expected behaviour" src="https://user-images.githubusercontent.com/99693139/153960889-b98329dd-8669-432d-b17c-2c03790f3717.png">
![2539947_Repro attachment_NVDA+Chrome config2](https://user-images.githubusercontent.com/99693139/153960891-6e326c06-30e7-4e1d-9b51-7e5b48bf6cf2.png)

**Comment by johnataylor** [comment]
@compulim any update on this

**Comment by compulim** [comment]
@karthsMicrosoft we have improved the accessibility on our chat history in our recent 4.15 release, could you bump and see if the problem is resolved?
