### ISSUE TITLE
Avatars and Decorating with activityMiddleware do not play well together

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#4144]
I am struggling with this for some time now (see also [this SO question)](https://stackoverflow.com/questions/71021910/webchat-unable-to-render-new-elements-using-activitymiddleware-in-combication-w). I reproduced the issue using the samples so hopefully you guys can shed some light on this.

The problem: Avatars are not shown as soon as you use activity middleware for decorating. 

To reproduce:

step 1. Clone the [sample with the password input](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/05.custom-components/f.password-input).
step 2 Add this code to the index.html
````
     const styleOptions = {
          botAvatarInitials: 'WC',
        };
````
and pass styleOptions={styleOptions} in ReactWebChat
```
                window.ReactDOM.render(
          <ReactWebChat
            activityMiddleware={activityMiddleware}
            directLine={window.WebChat.createDirectLine({ token })}
            store={store}
            styleOptions={styleOptions}
          />,
          document.getElementById('webchat')
        );
```
Step 3. Send 'sample:password-input' to the the mock bot. The password input form is shown but no avatar
Step 4. Send 'Hi' to mock-bot. The avatar is shown with the response.

For some reason, avatars are not shown when I decorate based on an evetn sent by the bot-code. This used to work before 4.14. Should I use a workaround?

**Comment by stevkan** [comment]
@HesselWellema, thanks for bringing this to our attention. I will attempt a repro of this and let you know what I find.

**Comment by HesselWellema** [comment]
@stevkan need some help with repro?

**Comment by stevkan** [comment]
@HesselWellema, thank you for your patience. I am unable to repro the issue using the [message reactions](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/05.custom-components/d.reaction-buttons) Web Chat sample coupled with avatar initials. As you can see in the image below, they display side by side:

![image](https://user-images.githubusercontent.com/18403946/156040988-0111f07f-0d90-46be-b7fa-359b637e7606.png)

Can you post the Web Chat code (minus keys/secrets) you are using that produces the issue? Also, the link you provided for SO suggests that is a React project. Is that the case here, as well?

As for the SO link, I'll take a peak there and see if I can provide any feedback. It may be the same underlying issue as here. But, I will know more once you provide any code and I can look the two over.

**Comment by HesselWellema** [comment]
Hi @stevkan. My apologies. I used my own botcode for the repo. I assumed this would not make any difference but it did. In my botcode the bot sends an event before sending a message.

```
    await context.sendActivity({ name: 'typingIndicator', type: 'event' }); 
   await  context.sendActivity('message');

```
I think this messes things up in webchat.

**Comment by compulim** [comment]
@HesselWellema this is expected behavior. We should add more docs in this area.

Activity middleware is designed to customize everything on that particular row, edge-to-edge. This including ability to customize avatar, attachments, send status and timestamp.

For customization, there are 3 distinct feature a middleware could do: decorating (a.k.a. add stuff), replacing, and removing.

In @stevkan sample (up/down vote buttons), the middleware is used for "decorating" the existing rendering. In other words, it is adding stuff next to the default render from Web Chat. Thus, we are keeping the current avatar, bubble, and timestamp.

In password input sample, it is used to replacing the default render. The default render is "not to render anything" (a.k.a. "void"). And this sample shows a middleware to replace "void" with a new rendering.

The activity middleware can be used to customize the *complete outlook* of a message, such as "system messages" in Dynamics 365 Omnichannel (circled below).

![image](https://user-images.githubusercontent.com/1622400/157754874-124d46a0-b620-404e-9524-acc7896b0565.png)

If you would want to only modify the content, you should try out the attachment middleware.

BTW, I am testing the password input sample on 4.9.0 and this is same behavior as before.

![image](https://user-images.githubusercontent.com/1622400/157752739-870da39d-a159-47df-85f9-681082808db3.png)

It will be great if you can share your design and we can suggest what kind of customization or middleware you would need to achieve that design.

**Comment by HesselWellema** [comment]
Tnx @compulim. The 'design' I am using in 4.9.0 that I am struggling to use in more recent version:

### Botcode (Nodejs)
The bot sends an event to ask the webchat client to render an element. In my case a typing indicator just before sending a text-reply. But it could also be a new inputform (calendar. slidebar etcetera). 

`await context.sendActivity({ name: 'typingIndicator', type: 'event' });`

### Webchat code (React project)
In 4.9.0, I use activity middleware to render a typing indicator as soon as requested by the bot. I know there are ways to do this via styleoptions but I don't like the result so much.

```
  const activityMiddleware = () => next => ({ activity, nextVisibleActivity, ...otherArgs }) => {
    // first remove existing typing indicators
    let elements = document.getElementsByClassName('typing-indicator');
    for (var i = 0; i < elements.length; i++) {
      elements[i].style.display = 'none'
    }
    // if typing indicator event from bot, return one to be rendered
    if (activity.name === 'typingIndicator') {
      return () => <TypingIndicator activity={activity} nextVisibleActivity={nextVisibleActivity} />;
    }
    else {
      return next({ activity, nextVisibleActivity, ...otherArgs });
    }
  };
```

### typingindicator.js

```
import React from 'react';
import './TypingIndicator.css';

const TypingIndicator = () => {
    return (
      <div className="typing-indicator">
      <span></span>
      <span></span>
      <span></span>
      </div>
    );
  };
  export default TypingIndicator
```

### typingindicator.css

```
.typing-indicator {
    background-color: transparent;
    height: 35px;
    width: 60px!important;
    border-radius: 20px;
    padding:10px;
    margin-left: 65px;
}

 .typing-indicator span {
    line-height: 35px;
    display:inline-block;
    vertical-align: middle;
    height: 10px;
    width: 10px;
    margin: 0 1px;
    background-color: #9E9EA1;
    border-radius: 50%!important;
    opacity: 0.4;
    animation: bounce 0.7s linear infinite;
}

.typing-indicator span:nth-child(1)
{
    animation-delay: 0.1s;
}

.typing-indicator span:nth-child(2)
{
    animation-delay: 0.2s;
}

.typing-indicator span:nth-child(3)
{
    animation-delay: 0.1s;
}

@keyframes bounce {
    30% { transform: translateY(-4px); }
    60% { transform: translateY(0px); }
    80% { transform: translateY(4px); }
    100% { transform: translateY(0px); opacity: 0.5;  }
  }
```

**Comment by HesselWellema** [comment]
I did some more digging. The problem I am experiencing (not showing Avatar) has to do with the timing of the sending of the event from the bot. I will need to work on that to solve this. I will close this issue

**Comment by stevkan** [comment]
@HesselWellema, that is great that you found a workable solution. I have come across instances in the past, when working with incoming activities coming into the store, that adding a timeout of 50-200 ms fixed the issue I was facing. I didn't think about that in this case (i.e. timing, whether that be from a timeout of adjusting the order of operations).

I see you closed and re-opened the issue. Did you mean to re-open?

**Comment by HesselWellema** [comment]
Nope. Wanted you give you the honour to close it.

**Comment by stevkan** [comment]
If you are able and willing, would you mind posting the actual solution for anyone else that comes along and is facing a similar challenge? If no, let me know and I'll close the issue straight-away. :)

**Comment by HesselWellema** [comment]
The problem was caused by the order in which I sent activities from the bot to webchat.
I was used to send:

1. typing-indicator event
2. message event
3. typing-indicator event
4. message event

The activity middleware would see the typing indicator event and replace the default render ('void') with a new rendering (my typing indicator). 
My assumption is that the next event (the message) will be rendered without an avatar because webchat is already under the assumption that an avatar has been rendered.

To bypass this behavior my solution was to send

1. message event
2. typing-indicator event
3. message event

From a Ux perspective not such a bad idea and the problem does not occur
