### ISSUE TITLE
Cannot clone project due to filename too long

### ISSUE THREAD

**Issue by muminasaad** [microsoft/BotFramework-WebChat#4170]
The following file path is making an error on windows devices

__tests__/__image_snapshots__/html/transcript-navigation-focus-attachment-screen-reader-primary-action-windows-narrator-js-transcript-navigation-with-windows-narrator-should-focus-inside-the-attachment-when-do-primary-action-is-performed-1-snap.png

filename too long on Windows

## Screenshots

![image](https://user-images.githubusercontent.com/5983341/154574291-6a53fc3f-620b-4459-ace0-0ba52a9b9ca6.png)

## Steps to reproduce

1. git clone https://github.com/microsoft/BotFramework-WebChat.git on windows on C:\ directly

## Expected behavior

Repo to be cloned

[Bug]

**Comment by stevkan** [comment]
@muminasaad, I'm not able to repro this issue. There are some options available that enable long file names to not produce an error. I'm looking into what those were that I perhaps enabled that you are maybe missing. When I identify what those are I'll post an update.

**Comment by muminasaad** [comment]
@stevkan 

The maximum number of chars for a file path is 255-260 characters on normal cases as the following docs, to enable long paths  the user expected to edit register and it may or may not work which means it is not ideal to have this long file names, so it is more logical to fix the file name.

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

**Comment by stevkan** [comment]
@muminasaad, I'm also reaching out to the principal dev of Web Chat to get his thoughts on how to get around this. I'll update you when I hear from him, as well.

**Comment by stevkan** [comment]
@compulim, assigning to you for tracking purposes.

**Comment by compulim** [comment]
I am working to resolve this in #4188.
