### ISSUE TITLE
webchat is not Loading

### ISSUE THREAD

**Issue by brijeshpankhaniya** [microsoft/BotFramework-WebChat#4196]
hello  everyone,
I am using the microsoft BotFramwork-webchat. I use the following webchat CDN 
https://cdn.botframework.com/botframework-webchat/latest/webchat.js".

but I get the error while Load the webchat Component. It throws error from today itself. I working as expected before.

here is the snippet of error. 
![image](https://user-images.githubusercontent.com/50993814/156712110-4aecd1b3-a13e-40fe-bf71-2712e1c91d8a.png)

in network Tab the webchat Conversations request is Canceled.
![image](https://user-images.githubusercontent.com/50993814/156712301-e8520511-d368-463e-a583-3a02408bcc14.png)

the component look like this:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/50993814/156712454-60460213-5336-4120-9123-feec08a8824b.png)

waiting for any solution.
thanks in advance.

**Comment by DainHeart** [comment]
Any update on this? We are having the exact same issue.

**Comment by compulim** [comment]
We are investigating the issue. Could you switch from `latest` to `4.14.1` in the meanwhile?

**Comment by brijeshpankhaniya** [comment]
@compulim are you asking for change the webchat CDN to 4.14.1 ?

**Comment by compulim** [comment]
There is an issue when rendering Web Chat to a detached node. Detached node means the node does not belong to the HTML document.

Let's say:

```js
const container = document.createElement('div');

window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token })
  },
  container
);

document.body.append(container);
```

The code above would fail because Web Chat is being rendered to a detached node.

The issue will be resolved when Web Chat is being rendered on an attached DOM node.

```js
const container = document.querySelector('#webchat');

window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token })
  },
  container
);
```

In the meanwhile, please either downgrade it back to 4.14.1 and wait for a patch. Or render Web Chat to an attached DOM node.

**Comment by brijeshpankhaniya** [comment]
hey @compulim it is really help full for me. working fine after downgrade version. thank for helping.

**Comment by brijeshpankhaniya** [comment]
> Any update on this? We are having the exact same issue.
@DainHeart  please check solution by @compulim  it working fine for me.

**Comment by ceby-gannetflemming** [comment]
This is affecting us as well.
