### ISSUE TITLE
Black frames (solid and thin dashed) appears when click on free space inside webchat

### ISSUE THREAD

**Issue by Oli5an** [microsoft/BotFramework-WebChat#4208]
## "Style Bug": Web Chat with Undesirable Styles = Black Frames
![Bug - see the two blue arrows](https://user-images.githubusercontent.com/102161651/159513581-704da578-4684-471f-afab-ff683662a5f6.PNG)

## Version of webchat.js
4.15.1
(Using CDN)

## Description of the "style bug"

The MS bot framework is embedded into a frontend app where the web chat contains adaptive cards. There you click on free space inside the webchat und the "frames" (see blue arrows in the screenshot/attachment) appears. A solid one around the web chat (see 1. on screenshot) and a thin dashed one around the adaptive card (see 2. on screenshot). There are no console errors because I it is only a "style bug" and no error. But I don't want to see these "frames" and searching for a way to avoid them. In release 4.11.0 this kind of problem didn't exist. 

I would be so grateful if somebody has a hint for me: 
1. Question: Which kind of styling is it? Respectively, which style option in css is needed to be chosen?
2. Question: Which class is needed to be taken?

Many thanks in Advance.

**Comment by Oli5an** [comment]
Small correction.

**Comment by compulim** [comment]
This is by design and is required to meet accessibility requirement as specified by WAI-ARIA guideline.

The chat history could contain focusable element, such as Adaptive Cards or other interactive messages. Under WAI-ARIA guideline, the chat history needs to be focusable (darker borders) and allow end-user to put the focus on a specific message (dashed borders).

**Comment by namit008** [comment]
@compulim It is possible we can hide it or change colour of it.

**Comment by developerwill** [comment]
I've found a simple solution and it's !important!

[class*="webchat__basic-transcript"] {
    border: none !important;
    outline: none !important;
}

Hope this helps :)
