### ISSUE TITLE
List of WebChat Supported Browsers?

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-WebChat#422]
What browsers & versions are officially supported by BotBuilder-WebChat?

**Comment by billba** [comment]
This is an excellent question. Unfortunately I have no answers. I would greatly appreciate someone who can do the work to figure this list out and a way to keep it up to date.

**Comment by danmarshall** [comment]
Basically I would say it comes down to our biggest dependencies, React and RxJs which both support IE9+.

**Comment by billba** [comment]
@danmarshall That's just one version of one browser. And there are other issues, including what polyfills we include and also some CSS stuff.

**Comment by danmarshall** [comment]
I agree it's a funny way to specify the level of support.
https://facebook.github.io/react/docs/react-dom.html
https://github.com/ReactiveX/rxjs/issues/733
Yet it seems to be the way our constituents define it :)

**Comment by billba** [comment]
I bet you a dollar we don't work on IE9 :-)

**Comment by danmarshall** [comment]
Using the [F12 emulation tools in IE](https://msdn.microsoft.com/library/dn255001(v=vs.85).aspx) I changed the document mode & user-agent string to IE9. I did notice a few minor rendering bugs in some spots, but overall seemed to work well :)

If there are any IE9 customers we can file bugs on a case-by-case basis.

**Comment by nwhitmont** [comment]
Is WebChat iframe tested with Firefox?  User reports problems sending messages via WebChat iframe in Firefox and IE. 

Relates to: 
https://github.com/Microsoft/BotBuilder/issues/3181

**Comment by danmarshall** [comment]
@nwhitmont - not yet. We are working to use a robust testing service which will test against many platform/browser combinations, stay tuned.

**Comment by nwhitmont** [comment]
relates to https://github.com/Microsoft/BotFramework-WebChat/issues/613

**Comment by nwhitmont** [comment]
relates to https://github.com/Microsoft/BotBuilder/issues/3181

**Comment by nwhitmont** [comment]
@danmarshall I'm guessing you mean [Sauce Labs](https://saucelabs.com/) or [BrowserStack](https://www.browserstack.com/)? I have worked with BrowserStack extensively, let me know if you want any help setting up test automation.

**Comment by compulim** [comment]
I think we are IE11 and modern browsers >= last 2 versions. If anything not working in this combo, please file a bug, we will fix it.

**Comment by nmssalman** [comment]
Internet Explorer and Edge have errors while chat system. specially javascript not working
