### ISSUE TITLE
Passing additional API-Key to window.WebChat.renderWebChat

### ISSUE THREAD

**Issue by nroth-zur** [microsoft/BotFramework-WebChat#4220]
We have a working Bot that uses the DirectLine AppService Extensions v3. So the following **pseudo-code** works perfectly fine:

    const secret = <Directline Secret>;
    const userId = "dl_test";

    const { token } = fetch("https://<our-domain>.azurewebsites.net/.bot/v3/directline/tokens/generate",
            { headers: {
                        authorization: "Bearer ${secret}"
                        },
                        method: "POST",
                        body: JSON.stringify({
                            user: {
                                id: userId
                            }
                        })
            }
            );

    window.WebChat.renderWebChat(
        {
        directLine: await window.WebChat.createDirectLineAppServiceExtension({
            domain: 'https://<our-domain>.azurewebsites.net/.bot/v3/directline',
            token
        }),
        userID: userId,
        username: "Test User"
        },
        document.getElementById('webchat')
    );

Note that in reality we are not exposing our secret in the frontend, this is just for illustration.

Now we want to access the chatbot through our API-Gateway. For this we need to pass an additional header in the requests. For the token generation this works just fine. **But how do we pass an additional header in the window.WebChat.renderWebChat component?** The end result should be something like this:

    const secret = <Directline Secret>;
    const userId = "dl_test";

    const { token } = fetch("https://<our-gateway-domain>/tokens/generate",
            { headers: {
                        authorization: "Bearer ${secret}",
                        apikey: <Our API Key>   # <---- this works
                        },
                        method: "POST",
                        body: JSON.stringify({
                            user: {
                                id: userId
                            }
                        })
            }
            );

    window.WebChat.renderWebChat(
        {
        directLine: await window.WebChat.createDirectLineAppServiceExtension({
            domain: 'https://<our-gateway-domain>',
            token
        }),
        userID: userId,
        username: "Test User",
        apikey: <Our API Key> # <---- this does not work
        },
        document.getElementById('webchat')
    );

Do we have to re-write one or more of the components? I looked in the samples but did not see anything similar.

**Comment by compulim** [comment]
You will need to fork out the [DirectLineJS repo](https://github.com/microsoft/BotFramework-DirectLineJS) which includes the DL ASE chat adapter. Then, modify it to add a new HTTP header, and pass the new chat adapter back to Web Chat via the `directLine` prop.

**Comment by nroth-zur** [comment]
Ah, thanks! We will take a look and direct any additional questions to the DirectLine Repo.

**Comment by amoo12** [comment]
Hello,
will it be possible to make this request a feature? this is a typical use case in the Azure architecture where we expose services through APIM or an API gateway that requires an additional secret to be passed in the request header.
