### ISSUE TITLE
Input type and control component 

### ISSUE THREAD

**Issue by dshamak-dev** [microsoft/BotFramework-WebChat#4221]
Is there a way to change or pass custom component instead default  input, or at least set custom props to it?

![image](https://user-images.githubusercontent.com/63905053/160423461-0b4d172f-6019-4711-93b8-e727520b5de2.png)

**Comment by compulim** [comment]
Currently, there is no easy way to customize the send box. #2211 is the feature request for this work.

However, you can disable the send box and rebuild it using composition mode. There is a sample about how to start with composition mode, https://github.com/microsoft/BotFramework-WebChat/blob/main/samples/04.api/m.enable-composition-mode/README.md.

**Comment by tdurnford** [comment]
Closing in favor of https://github.com/microsoft/BotFramework-WebChat/issues/2211
