### ISSUE TITLE
Bot Framework/Webchat UI supports for adaptive card 1.5

### ISSUE THREAD

**Issue by nandkishor76** [microsoft/BotFramework-WebChat#4226]
Bot Framework/Webchat UI supports adaptive cards version 1.3, however latest version available for adaptive cards is 1.5. 

Can you please suggest timeline when 1.4 or 1.5 will be supported for Bots?

**Comment by munozemilio** [comment]
Reply from WebChat owner:
Web Chat 4.15.1 included Adaptive Cards SDK 2.10, which is an engine capable of handling AC schema 1.5.
However, AC SDK 2.10 decided to turn 1.5 off, unless the dev explicitly turn it on. So, AC SDK 2.10 default to 1.4.
Web Chat do have an option to turn it on explicitly, called styleOptions.adaptiveCardsParserMaxVersion.
When the next release of Web Chat (say, 4.16.x) released, we will probably bump to the next version of AC SDK.
So if AC SDK 2.11 is out, it will probably has AC schema 1.6 and default to 1.5. Then, it will by default turned on in Web Chat 4.16.x.



But if AC SDK 2.11 is late, then, it probably won't come unless the web devs manually turn it on.

**Comment by compulim** [comment]
Thanks @munozemilio, I have created a FAQ here, https://github.com/microsoft/BotFramework-WebChat/issues/4234.

**Comment by lakshmikanth27** [comment]
@munozemilio when will the SDK 2.11 on SC will release ? I know as of now webchat version is still 4.15.2
