### ISSUE TITLE
Can I distinguish requests coming from different Sites?

### ISSUE THREAD

**Issue by tewari-d** [microsoft/BotFramework-WebChat#4228]
I am have enabled the webchat channel for my teams bot. There I have the option to create multiple sites for usage across different scenarios.

For example, I have created a site to embed my bot in one of the PowerBI dashboards (let's call it A) and another one created for another PowerBI dashboard (B). Now my requirement is to distinguish A and B inside my bot code so that I can display site specific content in the bot.

Any way I can do this ? Inside debugging I see that the channelData captures 'webchat' in both cases, there are other objects as well (having some ids) but their contents are not static, they keep on changing as soon as the web page is refreshed or closed. 

Is there any property that can help in distinguishing the sites which I am missing ? or any workaround to resolve my problem ?

For reference, my issue is somewhat similar to [1763](https://github.com/Microsoft/BotFramework-WebChat/issues/1763), but I am not able to understand the possible solution using secrets mentioned by @hansmbakker. Also tagging @Stevenic for help.

**Comment by hansmbakker** [comment]
It's a long time ago that I used this framework, I'm sorry but I cannot help here

**Comment by tewari-d** [comment]
@hansmbakker , thanks for your comment. If by any chance you know anyone who could help us, please tag them here. I am a bit new to the community and don't know the people or teams associated. Thanks in advance!

**Comment by tewari-d** [comment]
Thanks @stevkan, It did help us and we were able to solve our issue. Thanks a ton for the prompt response  🙇‍♂️ 😃 .
