### ISSUE TITLE
Hosting On IIS7

### ISSUE THREAD

**Issue by IanBoggs** [Microsoft/BotFramework-WebChat#423]
Hi,

not sure if this is the right place to ask or not.

I'm trying to host the web chat client internally on an IIS7 machine. I'm using the code from /samples/fullwindow/index.html in order to display.

The web site works fine when I run it under IIS Express from Visual Studio 2015 (by pressing run). THe web site loads up and the chat control displays fine. However, if I deploy the project to IIS 7 (which is my Windows 7 PC) I have a problem. The box displays but the blue 'Chat' bar at the top and the typing box at the bottom do not appear.

Is there any particular setting required in IIS in order for it to work correctly ?

**Comment by danmarshall** [comment]
Can you try in a different browser, also try clearing your browser cache to retrieve the latest CSS.

**Comment by billba** [comment]
Closing due to lack of response on the part of OP. Also not a WebChat bug.
