### ISSUE TITLE
Bot is sharing session response

### ISSUE THREAD

**Issue by nehapop** [Microsoft/BotFramework-WebChat#427]
I have integrated bot on my website using nodejs SDK and I have injected the webchat on my page using "Easy: In your non-React website, run WebChat inline" method from here : https://github.com/Microsoft/BotFramework-WebChat

But the problem is, when more than 1 person is talking with bot in-parallel. In this scenario bot is taking the input from user 1 and validating that from database after that if user 2 is is giving some wrong info then also bot is going to further steps and replying user 2 with the inputs given through bot to user 1.

I am using waterfall model and as we are receiving inputs from bot using "args.response", I'm not understanding why it is sharing the session.

**Comment by billba** [comment]
This sounds like a question for StackOverflow, so please ask there. I'm going to close this issue, but as a  parting thought I'm going to speculate that you are using the same user id when creating the WebChat, and  that your bot is storing info in userData.
