### ISSUE TITLE
make changes in dom element

### ISSUE THREAD

**Issue by mohmed-elkhodry** [microsoft/BotFramework-WebChat#4290]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

## Screenshots

![Screenshot (42)](https://user-images.githubusercontent.com/43173916/167844756-e6f6f0ef-040d-47ba-b9ba-45c657f57b9d.png)
after send any message it return as select
![Screenshot (43)](https://user-images.githubusercontent.com/43173916/167844631-a19a0d89-9093-4aa3-8cff-225b51b71d1b.png)

## Version

4.7.1
## Describe the bug

how to make dom customization

## Steps to reproduce

when I manipulate DOM and make changes (such as change select into radio buttons)
all changes disapear when new message send

**Comment by stevkan** [comment]
@mohmed-elkhodry, can you share the code you are using to make the DOM changes? Generally, my experience has been that a refresh of the page will reset any changes to DOM elements that were updated in the Web Chat component. As long as a refresh of the page isn't occurring, this should be doable.

**Comment by mohmed-elkhodry** [comment]
> @mohmed-elkhodry, can you share the code you are using to make the DOM changes? Generally, my experience has been that a refresh of the page will reset any changes to DOM elements that were updated in the Web Chat component. As long as a refresh of the page isn't occurring, this should be doable.

Thanks for your help 
I've caught the error
