### ISSUE TITLE
[Screen Readers-Ask HR Virtual Assistant]: Screen readers(NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

### ISSUE THREAD

**Issue by KattaBhargav** [microsoft/BotFramework-WebChat#4293]
### PWD Impact:
Screen reader users are getting impacted if Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window. 

### Test Environment:

OS: Windows 10 version 21H1 (OS Build 19043.1110)
Browser: New Edge Version 92.0.902.62 (Official build) (64-bit)/Chrome Version 92.0.4515.107 (Official Build) (64-bit)
URL: [AskHR Virtual Assistant (azureedge.net)](https://askhrvadev.azureedge.net/?botOrigin=ec)
Tools: NVDA 2021.1/JAWS 2021.2105.53 ILM 

### Repro Steps:
Step 1: Enable Screen readers (NVDA/JAWS) and open the above URL in the Chrome/Edge Browser using valid credentials.
Step 2: 'AskHR Virtual Assistant' Home page gets opened.
Step 3: Navigate to the list items suggestions using down arrow key and select Benefits verify the screen readers (NVDA/JAWS) behavior upon invoking the suggestion questionnaire button present in the “Ask HR Virtual Assistant” chat window. 

### Actual Result:
Screen readers (NVDA/JAWS) are narrating the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

Ex: NVDA/JAWS narrating as "Suggested Actions Container: Is empty………………………………complementary landmark form landmark form landmark message input box edit type your message blank Suggested Actions Container: Has content Press Alt+ Shift + A to select Laya Pension (Mercer)Well being program ESPP other benefits None of these/ask a different question "

### Expected Result:
Screen readers(NVDA/JAWS) shouldn't narrate the suggestion invoked by the user multiple times upon invoking the Suggested Questionnaire button present in the “Ask HR Virtual Assistant” chat window.

Ex: NVDA/JAWS should narrate as "Select an option to continue this conversation Suggested Actions Container: Has content  Press Alt+ Shift + A to select 6 list items button Laya, button Pension(Mercer), button Well being program, button  ESPP, button  other benefits, button None of these/ask a different question"

### MAS Reference:
[MAS 4.2.1 – Object Information](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7bEEE97BBD-9990-48A0-8B03-6EA775581AA8%7d&file=MAS%204.2.1%20%E2%80%93%20Object%20Information.docx&wdLOR=cBC823FF2-F30B-4029-A49F-90FCC0AB9FEB&action=default&mobileredirect=true)

**Comment by KattaBhargav** [comment]
#A11yMAS;#A11ySev2;#HCL;#WCAG4.2.1;#Accessibility;#Win10-Edge(Chromium);#BotFrameworkWebChat-Aug21;#Benchmark;#CSEO:BUG8007103;#Firstparty:CSEO;

**Comment by KattaBhargav** [comment]
Bug copied from CSEO team Bug id:-[BUG 8007103](https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/8007103)

**Comment by axelsrz** [comment]
@compulim could you take a look at this one?

**Comment by compulim** [comment]
We have removed the "suggested actions container: is empty" as we converge the suggested actions live region into chat history live region twin.

**Comment by compulim** [comment]
Reopen to pending verify.

**Comment by mishraadi** [comment]
Verified the issue on OS: Windows 11 version 22H2 (OS Build 22621.1000)
Browser: Microsoft Edge Version 104.0.1271.2 (Official build) dev (64-bit)
URL: [AskHR Virtual Assistant (azureedge.net)](https://askhrvadev.azureedge.net/?botOrigin=ec)
Tools: NVDA
and the issue doesn't repro anymore. Proper expected information is announced. So, closing it.
