### ISSUE TITLE
[Screen readers-AskHR Virtual Assistant]: Screen readers(NVDA/JAWS) focus narrating twice for content in chat window present in the page, while navigating using down arrow key

### ISSUE THREAD

**Issue by KattaBhargav** [microsoft/BotFramework-WebChat#4294]
### PWD Impact:
Visually challenged users who rely on screen readers will be impacted as screen readers(NVDA/JAWS) focus narrating twice for content present in chat window in the page, while navigating using down arrow key 

### Test Environment:
OS: Windows 10 version 21H1 (OS Build 19043.1110)
Browser: New Edge Version 92.0.902.62 (Official build) (64-bit)/Chrome Version 92.0.4515.107 (Official Build) (64-bit)
URL: [AskHR Virtual Assistant (azureedge.net)](https://askhrvadev.azureedge.net/?botOrigin=ec)
Tools: NVDA 2021.1/JAWS 2021.2105.53 ILM 

### Repro Steps:
Step 1: Enable Screen readers (NVDA/JAWS) and Open the above URL in the Chrome/Edge Browser using valid credentials.
Step 2: 'AskHR Virtual Assistant' Home page gets opened.
Step 3:  Now navigate through the page by using down arrow key to chat window and verify Screen Readers(NVDA/JAWS) behavior. 

### Actual Result:
Screen readers(NVDA/JAWS) focus narrating twice for content present in chat window in the page, while navigating using down arrow key.
**Observation:** Screen readers(NVDA/JAWS) are narrating as 'Bot said: Hi RamonABC,I am the AskHR Virtual Assistant. I’m in beta (which means I’m new and still learning). I can help you with a variety of topics from the menu below, or you can type in your own question.  Currently I provide information relevant only to employees in Ireland. If I can’t help you I’ll make sure your question gets to an AskHR advisor who can. How can I help you today? Sent at September 27 at 7:11 PM…………………..' 

### Expected Result:

Screen readers(NVDA/JAWS) focus shouldn't narrate twice for content present in chat window in the page, while navigating using down arrow key.

### MAS Reference:
[MAS 1.3.2 – Meaningful Sequence](https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7b889A51B3-CAA2-4419-87D4-09BFAD2E8379%7d&file=MAS%201.3.2%20%E2%80%93%20Meaningful%20Sequence%20.docx&wdLOR=cE46C6224-661F-4808-8CF1-053E77173597&action=default&mobileredirect=true)
### WCAG Reference:
https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html

**Comment by KattaBhargav** [comment]
#A11yMAS;#A11ySev3;#HCL;#WCAG1.3.2;#Accessibility;#Win10-Edge(Chromium);#BotFrameworkWebChat-Aug21;#Benchmark;#CSEO:BUG7997959;#Firstparty:CSEO;

**Comment by KattaBhargav** [comment]
Bug copied from CSEO team Bug id:-[BUG 7997959](https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/7997959)

**Comment by axelsrz** [comment]
assigning @compulim

**Comment by compulim** [comment]
Reopen to pend for verification.

**Comment by compulim** [comment]
This is done in PR #4323. Testers did not verify it on time, so we assume this is fixed properly.

**Comment by Kirank915** [comment]
Verified the issue and now the issue is fixed
