### ISSUE TITLE
[Screen Readers-Ask HR Bot-Ask HR Virtual Assistant]: NVDA is not narrating proper information if user invokes the Suggested questionnaire buttons from the list present in the page.

### ISSUE THREAD

**Issue by KattaBhargav** [microsoft/BotFramework-WebChat#4296]
### PWD Impact:
Screen reader users are getting impacted if once the user invokes the suggested questionnaire buttons in the page and screen reader is not narrating the invoked button information.

### Test Environment:
OS: WIN10 1909 (OS Build 18363.836)
Browser: New Edge Version 83.0.478.37 (Official build) (64-bit)
URL: [https://microsoft.sharepoint.com/teams/HR_Web_Dev_Site/SitePages/AskHRBotTest.aspx](https://microsoft.sharepoint.com/teams/HR_Web_Dev_Site/SitePages/AskHRBotTest.aspx?xsdata=MDV8MDF8fGUwOGNmNzIxMWMwMDRlNmFlMDA0MDhkYTNjYzAzZjJmfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2Mzc4ODkwOTM2MTc4MzYwMzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2TjJRd1lqVXpZell0TWpBNVlTMDBNVGhqTFdFM09XUXRNMlJqWVdOaU4yUTJORFUyWDJNd1lqazJZalZrTFROaE1EQXROR1l6WVMwNVpXRXhMVFZoTVdZell6RTNZVEZoWTBCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=bkFwYTdYNWp3dnEzcmp2aW1aaTJiQXZnTVhpMWtzVFNuOEdFWm5kR0p0Yz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-kbhargav%40microsoft.com)
Screen Reader: NVDA 2019.3.1

### Repro Steps:
Step 1: Enable NVDA and open the above URL in New Edge browser.
Step 2: Navigate to the “Ask HR Bot” Button in browse mode and invoke it.
Step 3: Chat window of “ASK HR Bot” is displayed on the screen.
Step 4: Verify the screen reader behavior upon invoking the Suggested questionnaire button in the page.

### Actual Result:
NVDA is not narrating proper information if user invokes the Suggested questionnaire buttons from the list present in the page.
**Ex:** NVDA is narrating the previous information of what Bot Said  which is already present upon invoking the "As a Generic Question" button in the chat box.

### Expected Result:
NVDA should narrate the proper information if user invokes the  Suggested questionnaire button from the list present at the bottom of the chat box.
**Ex:** Once user invokes “Ask a Generic Question” suggestion button then NVDA should narrate as Puneet Said Ask a Generic Question then with next Down arrow NVDA should narrate the suggestion provided from BOT .
**Ensure that:** If user ask a different question like “Leave/Time Away” then many suggestions appear on the screen NVDA should also narrate the information of the suggestions correctly while navigating in NVDA browse

### MAS Reference:
[MAS 4.2.1 - Object Information (33A)](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7Ba12f3779-bdf1-40c2-bbcc-0e314ea94858%7D&xsdata=MDV8MDF8fDEzODRhOWY4ODJjYTRmZTdlMDA0MDhkYTNjYzAzZjJmfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2Mzc4ODkwOTM2MTc4MzYwMzZ8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2TjJRd1lqVXpZell0TWpBNVlTMDBNVGhqTFdFM09XUXRNMlJqWVdOaU4yUTJORFUyWDJNd1lqazJZalZrTFROaE1EQXROR1l6WVMwNVpXRXhMVFZoTVdZell6RTNZVEZoWTBCMWJuRXVaMkpzTG5Od1lXTmxjdz09fHw%3D&sdata=L3AvUi9LRGF6Y09wS1V0Y2JnY1FmbmtxVVJPSllRcXhZYTgzM1RMTHZMYz0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-kbhargav%40microsoft.com)

**Comment by KattaBhargav** [comment]
#A11yMAS;#A11ySev3;#HCL;#WCAG4.2.1;#Accessibility;#Win10-Edge(Chromium);#BotFrameworkWebChat-Aug21;#Benchmark;#CSEO:BUG5837853;#Firstparty:CSEO;

**Comment by kattepalli** [comment]
The correct test URL is:- https://askhrvadev.azureedge.net/?botOrigin=ec

**Comment by axelsrz** [comment]
assigning @compulim

**Comment by compulim** [comment]
We will move suggested actions into our new live region twin section.

**Comment by compulim** [comment]
Reopen to pending verify.
