### ISSUE TITLE
WebChat 4.15.1 has backward compatibility issues with groupActivityMiddleware

### ISSUE THREAD

**Issue by elopezanaya** [microsoft/BotFramework-WebChat#4312]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

## Version

4.15.1 
> To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
>
> `[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`
>
> If you are using Web Chat outside of a browser, please specify your hosting environment. For example, React Native on iOS, Cordova on Android, SharePoint, PowerApps, etc.

## Describe the bug

when using 4.15.1  in LCW we have detected multiple issues with groupActivityMiddleware , the issue is not present for previous versions

## Steps to reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Additional context

[Bug]

**Comment by compulim** [comment]
Please elaborate more, preferably with code snippets showing before and after.

**Comment by charliewang95** [comment]
Seeing below error with 4.15.1 and groupActivityMiddleware ![image](https://user-images.githubusercontent.com/14852927/173723806-5481647c-71a0-439c-849c-5a50462ea129.png)

**Comment by charliewang95** [comment]
Our implementation:

/******
 * GroupActivitiesMiddleware
 * 
 * This middleware controls which messages are grouped together regarding to timestamps. It does the following processing:
 * 1. Distinguishes different messages by sender name and whether it is a system message
 ******/

import { Constants } from "../../../../../common/Constants";

function bin<T>(items: T[], grouping: (last: T, current: T) => boolean): T[][] {
    let lastBin: T[];
    const bins: T[][] = [];
    let lastItem: T;
    if (items.length > 0) {
        items.forEach(item => {
            if (lastItem && grouping(lastItem, item)) {
                lastBin.push(item);
            } else {
                lastBin = [item];
                bins.push(lastBin);
            }
            lastItem = item;
        });
    }
    return bins;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any
export const groupActivitiesMiddleware = () => (next: any) => (args: any) => {
    const {
        activities
    } = args;

    if (activities != null && activities.length > 0) {
        const { status } = next({ activities });
        return {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            sender: bin(activities, (x: any, y: any) => {
                const roleX = (x.channelData && x.channelData.tags) ? x.channelData.tags.includes(Constants.systemMessageTag) ? Constants.systemMessageTag : x.from.name : x.from.name;
                const roleY = (y.channelData && y.channelData.tags) ? y.channelData.tags.includes(Constants.systemMessageTag) ? Constants.systemMessageTag : y.from.name : y.from.name;
                return roleX === roleY;
            }),
            status
        };
    }
    else {
        return () => false;
    }
};

**Comment by compulim** [comment]
Working on this now. Confirmed it does not repro on 4.14.0 and repro on 4.15.0 (and probably more recent versions).

![image](https://user-images.githubusercontent.com/1622400/182706724-6f788069-30a8-4cc9-b1b9-fac7a4204884.png)

**Comment by compulim** [comment]
The error is caused by an invalid result was returned by the `groupActivityMiddleware`.

In the code snippet by @charliewang95, it may return `() => false`, which does not conform to the return type of `{ sender: [][], status: [][] }`.

In 4.14.0, Web Chat tolerated the invalid return value. However, in 4.15, Web Chat did not tolerate and threw exceptions.
