### ISSUE TITLE
User message styling lost when reconnecting to a conversation

### ISSUE THREAD

**Issue by DaveM77** [microsoft/BotFramework-WebChat#4331]
# Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

## Version

botframework-webchat NPM package version 4.15.2
Microsoft.Bot.Connector.DirectLine .NET assembly version 3.0.2.0

## Describe the bug

We have created a chatbot based on the React web chat component as per the sample [06.recomposing-ui/a.minimizable-web-chat](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/06.recomposing-ui/a.minimizable-web-chat) that obtains tokens from a token service that uses the DirectLineClient from Microsoft.Bot.Connector.DirectLine to provide a token. When reconnecting the web chat UI to an existing conversation by using a token generated by passing a conversation ID to the DirectLineClient, all old messages are styled as being from the bot even if they are user messages, eg

![HistoricMessagesAsBot](https://user-images.githubusercontent.com/31725506/176164926-751db3d8-b6bd-4988-a6c5-8268717d3cc3.JPG)

Expected
![HistoricMessagesAsUser](https://user-images.githubusercontent.com/31725506/176164832-2e621bb4-5110-44d8-a66d-01c5210de0c1.JPG)

## Steps to reproduce

1. Open the web chat UI and send some messages
1. Reconnect to the conversation above using a DirectLine token generated using the same conversation ID
1. Scroll up to old user messages 

## Expected behavior

Historic user messages should retain the user message styling specified in the StyleSet passed to the ReactWebChat component.

## Additional context

[Bug]

**Comment by stevkan** [comment]
@DaveM77, are you able to provide a copy of your web chat project or, if not, an example project that repros the issue? Having this would help in determining an exact cause.

**Comment by DaveM77** [comment]
@stevkan sure, whats the best way to get it to you?

**Comment by DaveM77** [comment]
@stevkan, sent it to the email address associated with your GitHub account

**Comment by stevkan** [comment]
@DaveM77 - Thank you for your patience. I haven't seen the email come through. Perhaps the file size is too big? Are you able to zip the project (minus any keys/secrets) and attach it here?

**Comment by stevkan** [comment]
@DaveM77, thank you for attaching the file. I'll take a look at this and see what I find.

**Comment by stevkan** [comment]
@DaveM77 - Just a minor update that I'm still looking into this. I had some initial trouble running your project locally, but I was able to get around it. I'll keep you updated.

**Comment by stevkan** [comment]
@DaveM77 - FYI, I need to connect with one of the WC developers regarding this issue. As soon as I am able to do that, I will reach back out to you.

**Comment by stevkan** [comment]
@DaveM77 - As you probably know, after the page is refreshed the `activity.from.role` property in each activity is getting altered. Any activity that previously read as 'user' is getting changed to 'bot'. I don't fully understand why, yet. But I will continue to look into it.

As a workaround in the meantime, you can update the 'DIRECT_LINE/INCOMING_ACTIVITY' store filter to detect if the `activity.from.id` belongs to the bot as that property isn't being affected. If the activity is not coming from the bot, then set the `activity.from.role` to 'user'. Or if you would rather use another property, you can do so as long as it differentiates between the bot and the user.

In my tests, this worked just fine. But obviously you should test for yourself.

**Comment by DaveM77** [comment]
@stevkan That's great, it works for us. Thanks for your assistance with this.
