### ISSUE TITLE
Different webchat results in different browsers

### ISSUE THREAD

**Issue by pvanaarde** [Microsoft/BotFramework-WebChat#434]
Hi,

I have implemented the ExcelBot example as available [here](https://github.com/microsoftgraph/botframework-csharp-excelbot-rest-sample).
Depending on which browser I use, the behaviour of the webchat is different, as per the below screenshot. On the left is using Edge (incorrect behaviour), and the right is using Chrome, which has the expected behaviour.
![capture](https://cloud.githubusercontent.com/assets/26129757/25260463/b8796916-268f-11e7-8cb7-94f1f43cec17.PNG)

When debugging using the bot emulator I am unable to reproduce this. Additionally, using Edge I am able to access other workbooks in the same OneDrive location.

Any help would be appreciated.
Thanks,
Pieter

**Comment by billba** [comment]
Wow that is unexpected!

**Comment by danmarshall** [comment]
Hi @pvanaarde can you:
* Tell us your version of Edge
* Open F12 tools in Edge and catch the network trace of the message which causes the error
* Repeat the above for Chrome
* Paste the JSON for the messages here

**Comment by compulim** [comment]
Close because of inactivity.
