### ISSUE TITLE
[Programmatic Access - BOT Framework - Web Chat > Navigation]: Elements with an ARIA role that require child roles does not contained by them.

### ISSUE THREAD

**Issue by vibhor12345678** [microsoft/BotFramework-WebChat#4342]
### User Experience:
Screen reader user will get confuse with the control type of the control if require aria child role is not defined for child control appearing under the parent control.

### Repro Steps:
1. Open URL: [Web Chat: Full-featured bundle (microsoft.github.io)](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/)
2. Web chat bundle will open.
3. Navigate on the web chat bot.
4. Verify the issue.

### Actual Result:
Elements with an ARIA role that require child roles does not contained by them.

### Expected Result:
Ensures elements with an ARIA role that require child roles contain them.

### Issue: 
Ensures elements with an ARIA role that require child roles contain them (aria-required-children - https://accessibilityinsights.io/info-examples/web/aria-required-children)

### Target application: 
Web Chat: Full-featured bundle - https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/

### Element path: 
.webchat--css-ujbzv-1l95nvm

### Snippet: 
<section aria-roledescription="chat history" class="webchat--css-ujbzv-1l95nvm webchat__basic-transcript__transcript" role="feed"></section>

### How to fix: 
Fix any of the following:
  Required ARIA child role not present: article

### MAS Reference:
[MAS1.3.1- Info & Relationships](https://aka.ms/MAS1.3.1)

Reference Links
[Accessibility Insights](https://accessibilityinsights.io/)! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

### Test Environment:
**Url:** [Web Chat: Full-featured bundle (microsoft.github.io)](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/)
**Browser:** Chrome version 103.0.5060.114 (Official Build) (64-bit)
**OS:** Windows 11 version 21H2 (OS Build 22000.975)

**Comment by vibhor12345678** [comment]
#A11yMAS;#A11ySev2;#HCL;#MAS1.3.1;#Accessibility;#Win11-Chrome;#BotFrameworkWebChat-Jul22;

**Comment by compulim** [comment]
This is fixed in #4420 and will be released as 4.15.5.
