### ISSUE TITLE
Remove file content response

### ISSUE THREAD

**Issue by jmcglory-its** [microsoft/BotFramework-WebChat#4345]
When a user uploads a file and its posted to directLine as an attachment. There seems no way to remove the response message which is just the name of the file.

In my application this response message is unwanted and I would like to hide it. I have tried to subscribe to the post and within the subscribe I look for element of class .webchat__filecontent and find its closest parent and delete it, but this doesnt always work. I have been looking for a middleware or setting to remove this but have not found anything

A middleware that allows to process or discard messages received from the bot should allow me to hide this. I have been looking at the middleware hooks but found nothing suitable.

` uploadFile = (files, category) => 
directLine.postActivity({
        from: { id: 'USER_ID' },
        type: "message",
        channelId: "DirectLine",
        attachments: files,
        name: "FilePickerResponse",
        value: {
          action: "UploadFiles",
          category: category ?? "no-category"
        }
      }).subscribe(x => {
          let elements = document.querySelector(".webchat__fileContent")
           if(elements != null) {
            let closest = elements.closest(".webchat__basic-transcript__activity-box");
            if(closest){
              closest.innerHTML = "";
//This does not work in all cases on all browsers
            }
           }
      });`

**Comment by stevkan** [comment]
@jmcglory-its - You should be able to mitigate this in the bot as that is where the response is coming from. Can you tell me how your bot is handling attachments that are sent it?

**Comment by jmcglory-its** [comment]
Hi,

Thanks for response and apologies as I have now realised this is the outgoing text from my bot front end and to prevent the message I just needed to send with text: ""
