### ISSUE TITLE
Rendering Issue with Backchannel sample

### ISSUE THREAD

**Issue by ryanvolum** [Microsoft/BotFramework-WebChat#435]
Cloned repo and ran backchannel sample. Seeing rendering issue in entry bar (see image)
![image](https://cloud.githubusercontent.com/assets/3891951/25297069/77c6d834-26a0-11e7-96a6-aed6a2f11497.png)

**Comment by danmarshall** [comment]
is your browser caching CSS? try clearing your browser cache / incognito

**Comment by ryanvolum** [comment]
and there you have it :) thanks for the quick response, Dan
