### ISSUE TITLE
Improper Placement of Images (.PNG) in Webchat

### ISSUE THREAD

**Issue by stevengum97** [Microsoft/BotFramework-WebChat#437]
As indicated in the screen cap below, there is an image placement issue when using the WebChat UI.

![webchatui_cap_placement](https://cloud.githubusercontent.com/assets/14935595/25357283/1c86e118-28f2-11e7-86ae-6465fd95f665.png)

**Comment by reyesrico** [comment]
@stevengum97 are you still having the same issue? I tried to recreate your response using the same _.png_ file and this is how it looks now:

![image](https://user-images.githubusercontent.com/10733155/32470967-d7aef018-c30f-11e7-8ed2-9ceb8b344b0a.png)

It seems that the _image_ position was fixed after upgrading the cards rendering as **adaptive cards**. 

If you still have more comments, please reopen the issue. Thank you.
