### ISSUE TITLE
Webchat event when user socket connection breaks

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotFramework-WebChat#438]
Not sure if this is the right place to ask the question or should have raised this issue on DirectlineJs repo.

Does Directline/Webchat send any event/notification to the bot when socket connection breaks (when user closes browser or network failure)?

**Comment by billba** [comment]
By definition, this is not something that WebChat (or DirectLineJS) *could* send to the bot. However the Direct Line service could detect that the connection has been broken and notify the bot. What say you, @dandriscoll?

**Comment by billba** [comment]
Closing this issue as it pertains to the back end system.

**Comment by ankitbko** [comment]
@billba Umm.. I am really looking forward for a solution to this. It is a critical problem in human handoff scenario where agent chat window is web channel. Do we have a workaround or expected timeline for this?

**Comment by billba** [comment]
Got it, but this is not the right forum to pursue it as this is for issues with WebChat, of which this is not one. Hey @dandriscoll where *should* @ankitbko file an issue having to do with the back end?
