### ISSUE TITLE
New "Bot Channel Registration" resources can't be created, use "Azure Bot" resources instead

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-WebChat#4383]
## Screenshots

n/a

## Version

n/a

## Describe the bug

Azure Bot Service removed the ability to create new **Bot Channel Registration** resources a while ago. All instructions that suggest or recommend creating such a resource should recommend an **Azure Bot** resource instead.

## Steps to reproduce

1. See first note under [Setup Azure Bot Services](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/07.advanced-web-chat-apps/b.sso-for-enterprise#setup-azure-bot-services) in the **Single sign-on demo for enterprise apps using OAuth** README.

## Expected behavior

We should not direct users to do something that will always fail.

## Additional context

See the note under [Create the bot resource](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0&tabs=userassigned#create-the-resource) in the Bot Framework SDK docs in the **Use the Azure portal to Create an Azure Bot resource** quickstart.

[Bug]

**Comment by JonathanFingold** [comment]
Note: I don't have permissions to remove the two labels.

**Comment by compulim** [comment]
Thanks @JonathanFingold.
