### ISSUE TITLE
SendMessage fails after custom sendEvent dispatched from the Bot

### ISSUE THREAD

**Issue by pauldmps** [microsoft/BotFramework-WebChat#4396]
### Is it an issue related to Adaptive Cards?

- [ ] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest), Platform: Windows, Platform: macOS

### Which area does this issue affect?

Send box

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

Step 1: The "Thumbs up/down buttons are rendered as a react component as an  attachment":
![image](https://user-images.githubusercontent.com/6829986/185574932-5fd6b9c2-05f1-4b18-83ea-3c21ad0e34ed.png)

Step 2: Click on any of the buttons. We send a custom event to the backend to store which button the user clicked. The event is sent successfully and there is echoback with the same event in the WS connection.
![image](https://user-images.githubusercontent.com/6829986/185575168-eaba20ee-0d42-4e34-b1e8-b990730dad02.png)

Step 3: Click on any of the suggested action buttons or just type and send any text in the Send box:
![image](https://user-images.githubusercontent.com/6829986/185575680-111cf57e-719d-4fab-82bf-6d217192fc20.png)

### Do you see any errors in console log?

index.js:1 botframework-webchat: Failed to post activity to chat adapter. Error: timeout
    at postActivitySaga.ts:115:1

### How to reproduce the issue?

1. Send a custom event from an attachment using hooks.useSendEvent. 
2. Send any message by either typing a message in the send box or by clicking on one of the suggested actions.
 

### What is the expected and actual behavior?

Expected:
The message fails to send. No API call is made to the directLine API endpoint in the Network tab.
Actual:
The message should be sent successfully.

**Comment by stevkan** [comment]
@pauldmps - Thank you for your patience. I'll be taking a look at this and attempting a repro. I will get back to you either with additional questions or my findings.

**Comment by stevkan** [comment]
@pauldmps, I am having some difficulty repro'ing the issue. I suspect I'm not implementing the same as you. Are you able to share your Web Chat code or a basic repro that I can then use? This would help take some of the guesswork out.

Also, if you could post the bit of bot code that handles the incoming custom event from the client, that would also be helpful.

**Comment by tracyboehrer** [comment]
Closing pending repro steps.
