### ISSUE TITLE
Incorrect message displayed when token expires

### ISSUE THREAD

**Issue by axnserv** [Microsoft/BotFramework-WebChat#441]
When token expires the Web Chat control displays “You do not have permission to view this directory or page”. It should tell user what actually happened and prompt to refresh the page to get a fresh token instead.

**Comment by billba** [comment]
Closing as this is actually a problem with the WebChat channel and not the control (in other words, there is nothing that can be done in this repo to solve this problem). @danmarshall I believe this is an open issue elsewhere, true?

**Comment by danmarshall** [comment]
@billba true
