### ISSUE TITLE
Chatbot voice reiterated 

### ISSUE THREAD

**Issue by tannguyen0241** [microsoft/BotFramework-WebChat#4413]
### I have a question

I have problem with feature voice chat, chatbot when response answer chatbot always repeat twice voice reiterated, below is my code.
What I can do in this case?
Thank you everyone.
Platform: React Js
Browser: Chrome
![image](https://user-images.githubusercontent.com/35026123/189801874-ae350fa7-8d58-4c40-9482-d9ba0c0d4dcf.png)
![image](https://user-images.githubusercontent.com/35026123/189801936-8690752c-faf7-4bc2-8241-70cf7e1840a3.png)

**Comment by stevkan** [comment]
@tannguyen0241

Can you tell me which version of Node, React, and Web Chat you are using?
Does this occur with every activity received by the bot or only in one/some cases?
Does this occur regardless of the language used or only when English or Vietnamese is used?

Also, are you able to include the code from your bot that generates the response activities?

**Comment by tannguyen0241** [comment]
### Question 1:

Version:
- botframework-webchat: ^4.15.4-main.20220811.d4b4fef.
- react: ^18.2.0.
- node: v16.13.0.
### Question 2:
- Every activity.
### Question 3:
-  Currently, I only use Vietnamese and English but both of this give reiterated response
### Question 4:
- Do you want means this ?
![image](https://user-images.githubusercontent.com/35026123/190049297-7abc4c0e-c8fd-4604-8d8c-b49021d90f11.png)
### FYI
I check network after I said then I see two request FetchSpeechData
![image](https://user-images.githubusercontent.com/35026123/190051541-d6861ed5-a7da-4f4c-9d47-6d92d3fba2ec.png)

**Comment by tannguyen0241** [comment]
I try deploy chat bot then voice not reiterated, I think able problem with debug mode.
