### ISSUE TITLE
How to use WebChat in ReactJS?

### ISSUE THREAD

**Issue by baodv1001** [microsoft/BotFramework-WebChat#4438]
### I have a question

I'm new to BotFramework-WebChat and I want to test my Bot (it works well in "Test in Web Chat" in Azure Bot - figure 1) in my web app using ReactJS. But it always warning "**Taking longer than usual to connect.**" (figure 2).

![image](https://user-images.githubusercontent.com/55795855/193377135-310481c1-8a3f-44d3-b7a1-1c6290f54e61.png)

![image](https://user-images.githubusercontent.com/55795855/193377154-879de4b0-441b-47c2-90c2-e38d8a26ee65.png)

After checked network tab in developer-tools, I saw that it has a request to https://directline.botframework.com/v3/directline/conversations but got error:

![image](https://user-images.githubusercontent.com/55795855/193377214-bdbe0f74-ab1f-4dd9-8a60-fd2e20180039.png)

Here is my code:
```
const Chatbot = (props) => {
  const directLine = useMemo(
    () =>
      createDirectLine({
        token: "DIRECT_LINE_TOKEN",
      }),
    []
  );

  return <ReactWebChat directLine={directLine} />;
};
```

Any wrong here?

**Comment by stevkan** [comment]
@baodv1001 - Please verify that "Always On" is enabled in your bot's app service resource. You can find this setting under Configuration => General settings. If you're experiencing this issue after a period of inactivity, this is likely why as the app service will go to "sleep" while waiting.

Looking at the bit of code you provided, I don't see anything that is jumping out at me. 

If the above isn't the source of the problem, try comparing your setup against the provided samples in this repo. There are several that are built as React projects. For instance, look at the [ChatComponent.js](https://github.com/microsoft/BotFramework-WebChat/blob/main/samples/01.getting-started/g.hybrid-react-npm/packages/chat-component/src/ChatComponent.js) file in the "01.getting-started/g.hybrid-react-npm" sample.

You can also try this setup which is what I use in a React project of my own. You will need to make a few changes. For instance, I call on a locally-run token server to get my DirectLine token.

```js
import React, { useState, useEffect, useCallback } from 'react';
import ReactWebChat, {
  createDirectLine,
  createStore,
} from 'botframework-webchat';
import { ConnectionStatus } from 'botframework-directlinejs';

const WebChat = props => {
  const [loading, setLoading] = useState(true);
  const [userID, setUserID] = useState('dl_abc123');
  const [username, setUsername] = useState('Bobby');
  const [store, setStore] = useState(null);
  const [directLine, setDirectLine] = useState(null);

  const webChatStore = createStore({}, ({ dispatch }) => next => action => {
    connectionStatusChanged(directLine.connectionStatus$);
    if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
      dispatch({
        type: 'WEB_CHAT/SEND_EVENT',
        payload: {
          name: 'webchat/join',
        },
      });
    }

    if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') {
      console.log('INCOMING ACTIVITY ', action.payload.activity);
    }
    return next(action);
  });

  const fetchToken = useCallback(async () => {
    const res = await fetch('http://localhost:3500/directline/token', { method: 'POST' });
    const { token } = await res.json();
    await setDirectLine(await createDirectLine({ token }));
    setLoading(false);
  }, [setDirectLine]);

  const connectionStatusChanged = connectionStatus => {
    switch (connectionStatus.value) {
      case ConnectionStatus.Online:
        console.log('Connected')
    }
  };

  useEffect(() => {
    if (loading === false) {
      setStore(webChatStore);
    }
    if (loading === true) {
      fetchToken();
    }
  }, []);

  return loading === false && !!directLine ? (
    <ReactWebChat
      directLine={directLine}
      userID={userID}
      username={username}
      store={store}
    />
  ) : (
    <div>Loading...</div>
  );
};

export default WebChat;
```

**Comment by stevkan** [comment]
Closing this as resolved.
