### ISSUE TITLE
Wrong German (de-DE) translation for KEYBOARD_HELP_CHAT_HISTORY_LEAVE_MESSAGE_HEADER

### ISSUE THREAD

**Issue by Jakob-vdH** [microsoft/BotFramework-WebChat#4442]
### Is it an issue related to Adaptive Cards?

- [ ] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

![image](https://user-images.githubusercontent.com/19874459/194026205-227c0062-4f3b-4163-8329-f07982894116.png)

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest), Browser: Firefox (latest), Browser: Safari (latest), Browser: IE Mode (latest), Platform: Windows, Platform: macOS, Platform: iOS/iPadOS, Platform: Android

### Which area does this issue affect?

Others/unrelated

### Is this an accessibility issue?

- [X] Yes, this is an accessibility issue.

### Please describe the bug

The current German translation in the [Keyboard help screen](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#ux-keyboard-help-screen) for the [`KEYBOARD_HELP_CHAT_HISTORY_LEAVE_MESSAGE_HEADER`](https://github.com/microsoft/BotFramework-WebChat/blob/v4.15.4/packages/api/src/localization/de-DE.json#L52) string ("Leave message") is "Nachricht hinterlassen" which means something like "leave the message behind" in English. The "correct" German translation would be "Nachricht verlassen". 

### How to reproduce the issue?

1. Open a Webchat instance in a browser or a html page with the language set to German (de-DE).
2. Click on the Webchat
3. Press Shift+Tab (on Windows) to get to the Keyboard help screen
4. Now the Keyboard help screen is shown with its German translations

### What is the expected and actual behavior?

Expected:
The German translation for `KEYBOARD_HELP_CHAT_HISTORY_LEAVE_MESSAGE_HEADER` is "Nachricht verlassen".
Actual:
The German translation for `KEYBOARD_HELP_CHAT_HISTORY_LEAVE_MESSAGE_HEADER` is "Nachricht hinterlassen".

**Comment by stevkan** [comment]
@LiweiMa - It looks like you manage the localization files that are used in Web Chat for translation (ref file [de-DE.json](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/api/src/localization/de-DE.json#L52) and automated updates shown [here](https://github.com/microsoft/BotFramework-WebChat/commits/f4652230765131dd94af4aef20ea805e6f316098/packages/api/src/localization/de-DE.json)).

Can you please review the customer's issue checking the current translation for accuracy?

**Comment by LiweiMa** [comment]
@stevkan Can you provide us the context of this string, is it a noun or the verb?

**Comment by compulim** [comment]
While focusing on the chat history, when <kbd>ESCAPE</kbd> key is pressed, the focus will goes back to the "text box in send bar" below.

The first screenshot show when the focus is on the chat history.

![image](https://user-images.githubusercontent.com/1622400/196527615-8aec5743-6b93-4cdd-bc38-c8c7ee1159f8.png)

The second screenshot show when <kbd>ESCAPE</kbd> key is pressed, the focus is being sent back to the text box.

![image](https://user-images.githubusercontent.com/1622400/196527783-e7cc5638-2fc8-44ee-b472-a36be424f703.png)

@LiweiMa I am not sure if the English one is good either, it said "Leave message". Please feel  free to suggest or update. Or let  me know if I should ask our designer for a better one. 😉

**Comment by LiweiMa** [comment]
@compulim There is no "Leave message" in above two screenshots, so I still confused and dont know what "leave message" here means. Anyway, can you add comment(context) in the English json file? and we will pick up the change and review the translation for all languages.

**Comment by LiweiMa** [comment]
@compulim We revisit your response internally, it clears my confusion, and we think "Type your message" would be better in this case. Can you update the English string and we can pick up from there. Let us know.

**Comment by compulim** [comment]
Action items:
- Designer: Consider "Chat history" -> "Chat history control"
- Designer: "Leave message" -> "Move to text box" or "Leave chat history control"
- Developer: Update the comments for "Leave message" to be more precise about "this is only for keyboard help screen"

**Comment by compulim** [comment]
Reply from designer:

- "Leave message" -> "Exit message" or "Exit focused section"
- "Chat history" leave as-is
