### ISSUE TITLE
Sending context with actions

### ISSUE THREAD

**Issue by sharmadine** [Microsoft/BotFramework-WebChat#446]
Sending context with actions - SKYPE

It can be useful to send context back to your bot (e.g. a request ID) without showing this information to the user in a message. To do this you can append hidden XML to the visible string shown to the user, which is only seen by your bot.

**Visible message &lt;context hiddenId='10'/&gt;**

How to achieve the same behavior in WebChat | Emulator?

**Comment by billba** [comment]
WebChat doesn't support this behavior.

**Comment by sharmadine** [comment]
Any alternative to achieve this behavior?

**Comment by billba** [comment]
You can write some client code and use the backchannel to communicate with the bot.
