### ISSUE TITLE
SSO with intranet sample and the template Enterprise Assistant Bot (Root Bot, People Bot, Calendar Bot) not working

### ISSUE THREAD

**Issue by nghivo** [microsoft/BotFramework-WebChat#4463]
### Is it an issue related to Adaptive Cards?

- [X] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

IFRAME

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Attachment: OAuth card

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

Dear Team,
We attempted to use the sample provided at https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/07.advanced-web-chat-apps/c.sso-for-intranet for our situation: SSO from our intranet with the Enterprise Assistant Bot template found at https://docs.microsoft.com/en-us/composer/templates/enterprise-assistant-overview,
Our three bots—Root, People, and Calendar—can currently communicate via an Exchange Token and OAuth from Azure AD.

The OAuth Card continued to appear when we tried to ask for persons or the calendar. The OAuth Card shouldn't be displayed.

Regards and thanks

Nghi

### Do you see any errors in console log?

No error

### How to reproduce the issue?

1. Copy the html file from the sample
2. Replace with our Direct Line token

### What is the expected and actual behavior?

Expected: should be seamless for OAth with Azure AD for SSO

Actual: still show the OAuth card to login

**Comment by ramfattah** [comment]
Thank you @nghivo, we are investigating.

**Comment by nghivo** [comment]
Hi @ramfattah ,
Hope that there is any progress on the investigation.

**Comment by ramfattah** [comment]
Hi @nghivo,

As QnA service is deprecated, I can't seem to run the [Enterprise Assistant Bot](https://github.com/microsoft/botframework-components/tree/main/generators/generator-bot-enterprise-assistant) from my local machine.
![image](https://user-images.githubusercontent.com/38049078/198399263-4b4a699f-cf8e-440f-9d11-ba8717222dba.png)


Discussing this internally for the next steps. 
Thanks for your patience.

**Comment by ramfattah** [comment]
Hi @nghivo,

As QnA service is deprecated, I'm not able to run the [Enterprise Assistant Bot](https://github.com/microsoft/botframework-components/tree/main/generators/generator-bot-enterprise-assistant) from my local machine.
![image](https://user-images.githubusercontent.com/38049078/198399263-4b4a699f-cf8e-440f-9d11-ba8717222dba.png)


Discussing this internally for the next steps. 
Thanks for your patience.

**Comment by nghivo** [comment]
Hi @ramfattah ,
We can close this issue as it is resolved with support from Shanghai team.

Thanks.
