### ISSUE TITLE
webchat supports HTML markdown?there is raw data coming in the response , would like to know if webchat supports HTML markdown?

### ISSUE THREAD

**Issue by phani12365** [microsoft/BotFramework-WebChat#4465]

**Comment by nt-7** [comment]
Web Chat disable HTML markdown by default.
https://github.com/microsoft/BotFramework-WebChat/blob/39be6e1ec1140b7094c8faf05cd5f85313dfa215/packages/bundle/src/renderMarkdown.ts#L97

**Comment by stevkan** [comment]
@nt-7, as is mentioned in this [issue](https://github.com/microsoft/BotFramework-WebChat/issues/3363#issuecomment-664543083), you can pass in your own markdown renderer, including any options you wish.

If you wish for HTML to be rendered, you can do the following. Just be aware that you are effectively overriding the default options passed in by Web Chat. Therefore, you will want to be sure to include **ALL** the options you want.

In the `<head>` of Web Chat's hosting page, include:
```js
<script crossorigin="anonymous" src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>
<script crossorigin="anonymous" src="https://unpkg.com/markdown-it@8.4.2/dist/markdown-it.min.js"></script>
```

At the top of your Web Chat code, add:
```js
const markdownIt = window.markdownit({ html: true });
```

In Web Chat's rendering component, pass in:
```js
window.WebChat.renderWebChat(
  {
    directLine: window.WebChat.createDirectLine({ token }),
    renderMarkdown: markdownIt.render.bind(markdownIt)
  })
```

The bot's message and Web Chat's rendering with HTML and markdown:
```js
await stepContext.context.sendActivity(`<div>Hi</div> **Every** _plan_ is different, once you log into your secure portal...`)
```

![image](https://user-images.githubusercontent.com/18403946/197860370-b9caf085-7a0b-4828-befb-75b8f0467a26.png)

As this _should_ resolve your issue, I am going to close this. If the issue persists, please feel free to re-open.
