### ISSUE TITLE
External Link icon is prefixed instead of suffixed when using a PVA bot

### ISSUE THREAD

**Issue by ryub3n** [microsoft/BotFramework-WebChat#4466]
### Is it an issue related to Adaptive Cards?

- [ ] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/24279903/197225626-383db96a-d2fe-4415-9248-7a4e8d22f530.png">

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

SharePoint

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Chat history

### Is this an accessibility issue?

- [X] Yes, this is an accessibility issue.

### Please describe the bug

External Link icon is prefixed instead of suffixed when using PVA 

### How to reproduce the issue?

1. Host a PVA bot on a webpage (I hosted it on SharePoint using the SP Framework)
2. Trigger a response from the bot that contains links
3. Observe that the link has a prefixed external link icon

### What is the expected and actual behavior?

Expected: External link icon should be suffixed

Actual: External link icon is prefixed

**Comment by compulim** [comment]
We have some tests that verify the "open in new window" icon is appended to the link. Such as:

- [`/__tests__/html/markdown.rel.html`](https://github.com/microsoft/BotFramework-WebChat/blob/main/__tests__/html/markdown.rel.html)
   - The image snapshot of the test is here, [`markdown-rel-js-markdown-must-have-rel-noopener-noreferrer-1-snap.png`](https://github.com/microsoft/BotFramework-WebChat/blob/main/__tests__/__image_snapshots__/html/markdown-rel-js-markdown-must-have-rel-noopener-noreferrer-1-snap.png)

This is the DOM tree generated by the test and the icon is appended correctly.

![image](https://user-images.githubusercontent.com/1622400/198818508-98ce5119-1dcd-4a5a-b254-77c82e49724a.png)

We are not seeing anything wrong here.
   
On your side, did you spot any CSS styles that may interfere the position of the icon?

**Comment by ryub3n** [comment]
@compulim , yes, I've figured out when this happens.
If you bold the text then the link icon appears before the text.

Also if you don't add the protocol i.e. https:// then the link icon doesn't show up.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/24279903/199487212-3dc86226-fe20-41d0-8a84-a2058d489abb.png">


<img width="1142" alt="image" src="https://user-images.githubusercontent.com/24279903/199483716-1c75570c-d32f-4845-994e-8be04b48ab1a.png">

**Comment by johnataylor** [comment]
@compulim can you clarify whether this is an issue in the product code or the application?

**Comment by tdurnford** [comment]
This is most likely an issue with [markdown-it](https://www.npmjs.com/package/markdown-it)

**Comment by tdurnford** [comment]
We are using the a custom [markdown-it](https://www.npmjs.com/package/markdown-it) to postfix the link text with the icon. However, it does not look like we have any logic to handle styled text. 

https://github.com/microsoft/BotFramework-WebChat/blob/359ce8ec7863e4bb5dadb397be4274e11b5fa9bd/packages/bundle/src/renderMarkdown.ts#L128

**Comment by axelsrz** [comment]
Closing this one due to inactivity, if further problems are encountered, please submit a new issue
