### ISSUE TITLE
Suggested Action Layout option doesn't work

### ISSUE THREAD

**Issue by ryub3n** [microsoft/BotFramework-WebChat#4467]
### Is it an issue related to Adaptive Cards?

- [ ] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

<img width="532" alt="image" src="https://user-images.githubusercontent.com/24279903/197757051-8f0b97e2-2721-4ce8-a9d8-1c60f58858e6.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/24279903/197757159-d2e25bbb-1ef0-4d11-b8c2-0c7c68f1e9de.png">

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

SharePoint

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Suggested action

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

Suggested Action Layout option doesn't work. And the other options don't work too.

### How to reproduce the issue?

1. Create a bot with default options
2. Set the **suggestionActionLayout** to 'stacked' and run it.
3. View error

### What is the expected and actual behavior?

Expected: It should accept the values 'stacked, 'carousel', etc.

Actual: Doesn't work

**Comment by compulim** [comment]
We have tests that verify this style options, such as, https://github.com/microsoft/BotFramework-WebChat/blob/main/__tests__/html/accessibility.suggestedActions.stackedLayout.ariaAttributes.html.

Do you think it is related to bad type definitions instead?

**Comment by compulim** [comment]
Here is another test that have screenshots, showing stacked layout of suggested actions:

- [`/__tests__/html/suggestedActions.stacked.buttonTextWrap.html`](https://github.com/microsoft/BotFramework-WebChat/blob/main/__tests__/html/suggestedActions.stacked.buttonTextWrap.html)
   - [`suggested-actions-stacked-button-text-wrap-js-when-false-should-ignore-max-height-1-snap.png`](https://github.com/microsoft/BotFramework-WebChat/blob/main/__tests__/__image_snapshots__/html/suggested-actions-stacked-button-text-wrap-js-when-false-should-ignore-max-height-1-snap.png)

**Comment by ryub3n** [comment]
@compulim , I did see those and feel it's due to bad type definitions. Btw, I'm using Composer... not sure if that makes a difference.

**Comment by compulim** [comment]
Not related to Composer... Composer is a bot development and your problem is in the area of web development.

Let me check if we did a mistake in our typing.

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/200414942-cd2c0cfb-13a6-4838-8c06-5c5467894253.png)

Looks like our typing for `suggestedActionLayout` is correct. It is not flagged as an error.

I have a repro repository here, could you spot any differences?

https://github.com/compulim/experiment-webchat-typing/blob/main/src/ui/Chat.tsx

**Comment by ryub3n** [comment]
> Not related to Composer... Composer is a bot development and your problem is in the area of web development.
> 
> Let me check if we did a mistake in our typing.

I meant the [Composer](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/api/src/hooks/Composer.tsx) component not Bot Framework Composer.

**Comment by compulim** [comment]
Oh sorry. 😅

Let me check again. I think very unlikely because they should share the same type. (It is probably a bug if they don't share the same type.)

**Comment by compulim** [comment]
![image](https://user-images.githubusercontent.com/1622400/200495837-a456c3af-c034-4c98-b88e-24c3573cccb0.png)

I am using `<Composer>` and it still works.

I hovered over the `suggestedActionLayout` and it show the typing correctly.

**Comment by ryub3n** [comment]
The error shows only when I pass the value using a variable.
Now I wonder if I'm doing something wrong.

Just this Layout is breaking.
![styleOpts](https://user-images.githubusercontent.com/24279903/200512155-f367a498-18fd-4c3e-aa4e-5a8c0ae2c37d.png)

Other options work fine.
![styleOpts2](https://user-images.githubusercontent.com/24279903/200512164-2fcc1a68-2e5b-48d5-a2f1-fc57b568b49f.png)

**Comment by johnataylor** [comment]
@ryub3n closing, please re-open if you are still having trouble
