### ISSUE TITLE
Sending proactive event message

### ISSUE THREAD

**Issue by mehdikalhori** [Microsoft/BotFramework-WebChat#447]
I need to use Backchannel to send events to client.
I defined a listener on the client as mentioned in the document:

        botConnection.activity$
            .filter(activity => activity.type === "event" && activity.name === "myAct")
            .subscribe(activity => myActivity(activity.value))

and for sending event in the response of a message on the bot side, I can do it by:

       session.send({type: 'event', name:'myAct', value:'Test'});

and for sending normal messages in proactive mode, I do it by:

       var bot = new builder.UniversalBot(connector);
       bot.send(new builder.Message().address(address).text(message));

My question is how can I send **proactive** **event** **message**?!

**Comment by mehdikalhori** [comment]
I found the solution from https://github.com/ryanvolum/backChannelBot :
    var msg = new builder.Message().address(address);
    msg.data.type = "event";
    msg.data.name = eventName;
    msg.data.value = value;
    bot.send(msg);

**Comment by billba** [comment]
Great!
