### ISSUE TITLE
Adaptive card are not showing in webchat where as showing in MS Teams

### ISSUE THREAD

**Issue by Aiswarya1794** [microsoft/BotFramework-WebChat#4503]
### Is it an issue related to Adaptive Cards?

- [X] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

Adaptive card version  : 2.7.3

Adaptive card in Teams  

![FeedbackCardInTeams](https://user-images.githubusercontent.com/109646037/201611082-aba1dd3f-652d-480a-8501-7f5ec5b0a055.png)

Adaptive card in Webchat

![FeedbackCardInWebchat](https://user-images.githubusercontent.com/109646037/201611128-9d2a522d-81e8-4ada-8137-029d680aaeec.png)

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest)

### Which area does this issue affect?

Attachment: Adaptive Card

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

We are using the below code to display the adaptive card in Webchat and Teams.
Its working correctly in Teams and in Webchat its displaying as a line.

```js 
public static Attachment GetUserRatingAndFeedbackCard(string agentName)
{
    var cardBody = new List<AdaptiveElement>()
    {
        new AdaptiveChoiceSetInput
        {
            Style = AdaptiveChoiceInputStyle.Expanded,
            Wrap = true,
            Id = "Rating",
            Type = AdaptiveChoiceSetInput.TypeName,
            IsMultiSelect = false,
            Label = $"Hoe was de chatervaring met {agentName}",
            Choices =  new List<AdaptiveChoice>()
            {
                new AdaptiveChoice() { Title = "😀  Uitstekend" , Value = "Rating : Excellent" },
                new AdaptiveChoice() { Title = "🙂  Goed" , Value = "Rating : Good" },
                new AdaptiveChoice() { Title = "😐  Ok" , Value = "Rating : Ok" },
                new AdaptiveChoice() { Title = "🙁  Arm" , Value = "Rating : Poor" },
                new AdaptiveChoice() { Title = "🙁  Heel slecht" , Value = "Rating : VeryBad" },
            }
        },
        new AdaptiveActionSet()
        {
            Actions = new List<AdaptiveAction>()
            {
                
                new AdaptiveShowCardAction()
                {
                    Title = "Aanvullende feedback toevoegen",
                    Card = GetUserRatingAndFeedbackAdaptiveCard()
                }
            }
        }
    };

    return GetAttachment(AdaptiveCard.ContentType, GetAdaptiveCard(cardBody));
}

public static AdaptiveCard GetUserRatingAndFeedbackAdaptiveCard()
{
    var cardBody = new List<AdaptiveElement>()
    {
        new AdaptiveTextInput()
        {
            IsMultiline= true,
            Placeholder=ResourceString.PlaceholderText,
            Type=AdaptiveTextInput.TypeName,
            IsRequired = false,
            MaxLength = 250,
            Id= $"comment"
        },
        new AdaptiveActionSet()
        {
            Actions = new List<AdaptiveAction>()
            {
                new AdaptiveSubmitAction()
                {
                    Title = ResourceString.SubmitButtonText,
                    Data = new JObject
                    {
                        {"msteams",new JObject
                            {
                                { "type", "messageBack"},
                                { "displayText", "Einreichen" },
                                { "text", "Einreichen" }
                            }
                        }
                    }
                }
            }
        }

    };

    return GetAdaptiveCard(cardBody);
}

```

### How to reproduce the issue?

1. Call the adaptive card from Bot project

### What is the expected and actual behavior?

Expected: Adaptive card should be displayed same as how it works in Teams

Actual: Webchat displays adaptive card as white line

**Comment by ramfattah** [comment]
Thanks @Aiswarya1794, we are investigating.

**Comment by ramfattah** [comment]
Hi @Aiswarya1794, 

I was able to reproduce using Adaptive Card version 1.6:
![image](https://user-images.githubusercontent.com/38049078/202070321-6a87e116-de80-485b-bca2-42aff6f491d3.png)

Reverting back to 1.5 solved the issue:

#

Could you please try to set the Adaptive Card Schema Version less than 1.6 to see if that addresses this issue:
```cs
 AdaptiveCard card = new AdaptiveCard(new AdaptiveSchemaVersion(1,5));

```

**Comment by Aiswarya1794** [comment]
@ramfattah ,

I have updated the code as below,

![image](https://user-images.githubusercontent.com/109646037/202208802-119260a1-77a2-42f1-9293-f7c988354567.png)

Still in webchat , its not displaying the full adaptive card

**Comment by tracyboehrer** [comment]
Closing to inactivity after work-around.
