### ISSUE TITLE
Webchat not rendering a conversation when the same conversation is being rendered multiple times

### ISSUE THREAD

**Issue by antoniobriones** [microsoft/BotFramework-WebChat#4505]
### Is it an issue related to Adaptive Cards?

- [ ] Yes, this is an Adaptive Card issue but it is specific to Web Chat.

### Do you have any screenshots?

![image](https://user-images.githubusercontent.com/50162129/202013920-5980a9cd-d114-4d26-ac44-2daf141190b3.png)

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Others/unrelated

### Is this an accessibility issue?

- [ ] Yes, this is an accessibility issue.

### Please describe the bug

- Start a conversation with a bot by making a POST to https://directline.botframework.com/v3/directline/conversations
- Use that token to render the webchat 4 or more times in the same page:
-  var store = window.WebChat.createStore({}, ({ dispatch }) => (next) => (action) => {
                    //console.log(action);
                    handleWebChatAction(action, dispatch);
                    return next(action);
                });
                window.WebChat.renderWebChat(
                    {
                        directLine: window.WebChat.createDirectLine({
                            token: token,
                        }),
                        styleSet: getBotStyleSet(),
                        sendTypingIndicator: true,
                        store,
                        styleOptions: getBotStyleOptions(),
                    },
                    document.getElementById(ctrl.widgetId + "-container")
                );`
- Most of the times 3 of the 4 webchat instances will load successfully, the fourth will not (see attachment).
- Sometimes the 4 of them load as expected, and sometimes more than 1 of them fail to load
- Failing to load means that the webchat component does not render anything
- I've compared all events generated by directline and there's no difference between the one where the widget fails to load and the others. In fact, all of them at some point generate DIRECT_LINE/UPDATE_CONNECTION_STATUS with status = 2 (online)

### Do you see any errors in console log?

No

### How to reproduce the issue?

- Start a conversation with a bot by making a POST to https://directline.botframework.com/v3/directline/conversations
- Use that token to render the webchat 4 or more times in the same page:
- ` var store = window.WebChat.createStore({}, ({ dispatch }) => (next) => (action) => {
                    //console.log(action);
                    handleWebChatAction(action, dispatch);
                    return next(action);
                });
                window.WebChat.renderWebChat(
                    {
                        directLine: window.WebChat.createDirectLine({
                            token: token,
                        }),
                        styleSet: getBotStyleSet(),
                        sendTypingIndicator: true,
                        store,
                        styleOptions: getBotStyleOptions(),
                    },
                    document.getElementById(ctrl.widgetId + "-container")
                );`

### What is the expected and actual behavior?

Expected:
The 4 instances of the chat in the page should load (or there should be some indicator that it's failed so that the developer can handle it)

Actual:
Not all instances load correctly and there's no indication to handle it

**Comment by stevkan** [comment]
@antoniobriones - Opening multiple instances of the same Web Chat conversation is not a supported scenario. Web Chat is intended for use in single 1:1 conversation instance between a bot and a user. As I note in this related [post](https://github.com/microsoft/BotFramework-WebChat/issues/4462#issuecomment-1282807344), Web Chat can be configured to persist a conversation across multiple web pages. However, there should still only ever be one instance of a Web Chat conversation running at a time.

There is no error message for this because you are attempting to use Web Chat in a manner outside of its design.

**Comment by antoniobriones** [comment]
@stevkan thanks, we´ll implement a mechanism to block the same conversation from being rendered concurrently.
