### ISSUE TITLE
Focusing send message box after rendering the webchat

### ISSUE THREAD

**Issue by antoniobriones** [microsoft/BotFramework-WebChat#4507]
### I have a question

Hi, 

I'm using this code to render the webchat:

window.WebChat.renderWebChat(.... (using the js bundle).

I don't see any option to make the webchat focus the send message box after starting the conversation. To comply with accessibility guidelines, we need to focus the send message box, is that possible?

**Comment by compulim** [comment]
You need to move the focus manually.

You should also be aware that, moving focus could be violating ARIA if you move it without user acknowledgement. That's why we didn't offer this feature.
