### ISSUE TITLE
Will the custom WebChat support adaptive cards soon?

### ISSUE THREAD

**Issue by rylengel** [Microsoft/BotFramework-WebChat#458]
I recognize this is a brand new feature, but are you working on implementing the adaptive card schema? I might piece together my own implementation but it would help to know if this is coming down the pipeline.

Thanks!

**Comment by GeekTrainer** [comment]
I'd say "keep your eyes open". :-)

**Comment by danmarshall** [comment]
Adaptive cards code has been merged into master, so you can grab the code and build your own WebChat. The NPM package will be coming soon.
