### ISSUE TITLE
Cosmos DB Trigger is not working after upgrading WebJobs.Extensions.CosmosDB and WebJobs.Extensions.Storage to latest version

### ISSUE THREAD

**Issue by Aiswarya1794** [microsoft/BotFramework-WebChat#4584]
### I have a question

Error is showed after upgrading Cosmos DB and storage in web jobs extension . We have upgraded the project to .NET 6 and upgraded azure functions sdk to latest version.

![image](https://user-images.githubusercontent.com/109646037/208839367-c37dadfa-f04c-4fcd-afe2-d984c10bbeae.png)

**Comment by johnataylor** [comment]
Please can you verify that you have filed this issue against the right area?
This is specifically for the WebChat component.

**Comment by dmvtech** [comment]
This doesn't appear to be related to Bot Framework or Webchat. If it is, please supply additional information on how it is related to a bot and WebChat.
