### ISSUE TITLE
webchat bot is embedded in PowerApps through iframe but error encountered is "webchat.botframework.com refused to connect."

### ISSUE THREAD

**Issue by wkrubon** [microsoft/BotFramework-WebChat#4585]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

PowerApps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest)

### Which area does this issue affect?

Others or unrelated

### Please describe the bug

We embedded the chatbot in our powerapps canvas app using iframe and it was working properly till yesterday. Suddenly we are getting this error "webchat.botframework.com refused to connect."

### How to reproduce the issue?

1. Navigate to ...
2. Click on ...
3. Type "..." in the send box

### What do you expect?

Chatbot should open in canvas app

### What actually happened?

**Error**
webchat.botframework.com refused to connect.

**Comment by anishprasad01** [comment]
Hi @wkrubon,

This issue appears to have been caused by an unexpected change to server-side CORS settings. The change has since been reverted and the issue has been fixed.
