### ISSUE TITLE
Display button title (instead of value) in chat window with imBack

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotFramework-WebChat#459]
I understood that button of postBack type (when clicked) sends the value of the button to the bot without displaying it on chat window AND button with imBack does the same but displays the button value as on chat window.
With my webchat I wanted it to work like "When imBack button is clicked button value should be sent as message but button title should be displayed on chat window". This same thing is done on Skype and Facebook messenger channels.
Can anyone guide me for the changes required for this?

**Comment by kalykodu** [comment]
I have a similar use case. Can you update if you found any solution?

**Comment by pupipipu** [comment]
I have a similar use case too. Would you mind providing a pointer on how to achieve this? If possible I might be able to help implementing too.

**Comment by pupipipu** [comment]
If you guys still need the imback returning button title, I modified the webchat (v0.10.7) to do just that. Link below:
[https://www.npmjs.com/package/botframework-webchat-modified](url)

When I have the time I'll modify the main source (latest version) to add the options to return button title/value and created a pull request :)

**Comment by corinagum** [comment]
Related to messageBack #1402
