### ISSUE TITLE
How to pass additional query string in Webchat channel

### ISSUE THREAD

**Issue by Vijayalakshmi-R1** [microsoft/BotFramework-WebChat#4628]
Hi Team,

We are using Bot framework sdk v4 enabled webchat channel. We are able to get username & userid in the Bot. 

'https://webchat.botframework.com/embed/TestBPAFinnBot?s=YOUR_SECRET_HERE&userid=USER_EMAIL_ID&username=USER_NAME' 

Now we want to pass additional query string in the endpoint (for example inputdata=Contract) and use it in Bot for our logic.
But we are not able to get/ view this value in turnContext (IConversationUpdateActivity).

'https://webchat.botframework.com/embed/TestBPAFinnBot?s=YOUR_SECRET_HERE&userid=USER_EMAIL_ID&username=USER_NAME&inputdata=TEXT'

Kindly help.

**Comment by stevkan** [comment]
@Vijayalakshmi-R1 - Unfortunately, it isn't possible to send other properties via the query string as that list is fairly limited and specific? There is a way to send it via the `conversationUpdate` activity but it would require changing how Web Chat is implemented as it's not able to be done from the iframe embed. Is this a possibility?

**Comment by stevkan** [comment]
Closing due to lack of response.
