### ISSUE TITLE
A11y_Live Chat Widget - Version 2_Live Chat_Customerchatwindow_High Contrast: In desert high contrast theme "Close" button in keyboard controls popup is not visible.

### ISSUE THREAD

**Issue by pgopinadhu** [microsoft/BotFramework-WebChat#4629]
### User Impact:
High contrast theme users may find difficulties if close is button is not visible
### Pre-requisites:
1.Go To Setting and Tab till Accessibility press enter
2.Tab till contrast theme and press enter
### Repro Steps:
1.Hit the URL: [React App (azureedge.net)](https://msft-lcw-trial.azureedge.net/lcwsandbox/v1/index.html) and press enter
2.Turn on Desert high contrast theme 
3.Tab till "Script" field and paste the code 
Script : <script id="Microsoft_Omnichannel_LCWidget"  
src="https://elastorageredmond.blob.core.windows.net/elopez-dev/v2/v2scripts/LiveChatBootstrapper.js"  
data-app-id="e82e1eec-9c06-4121-8905-1113dc77edda" data-lcw-version="ppe"  
data-org-id="2ef66d93-e33c-443a-adbb-bf19627d339b"  
data-org-url="https://unq2ef66d93e33c443aadbbbf19627d3-crm10.oc.crmlivetie.com"></script>
4.Tab till load button and press enter
5.Tab till "Live Chat" button and press enter
6.Tab till  keyboard control close button
7.Check whether the  Close button is visible in Desert mode or not.
### Actual:
In desert high contrast theme "Close" button in keyboard controls is not visible.
### Note:
The issue only reproducible with Desert theme
### Expected:
In desert high contrast theme close button in keyboard controls should be visible

### Recommendation:
[Accessibility - MAS Problems and Suggested Fixes - Reviewed Items (sharepoint.com)](https://microsoft.sharepoint.com/sites/accessibility/Lists/MASProblemsAndSuggestedFixes/Reviewed%20Items.aspx?xsdata=MDV8MDF8fGUxOWQ4Njg3MjM5YzQ0ODVjNDZiMDhkYWJiZTZiYmJjfDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDF8MHw2MzgwMjg4OTY4OTI5MjkxMzF8R29vZHxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVGs2Wm1Ka056RXdNRFV3WlRrNU5HRXhNMkkzTWpobE16TXpOekJtTmpOa1pURkFkR2h5WldGa0xuWXl8fA%3D%3D&sdata=NDdhbFc2MjdQSk4wTlVvTDJPZEpiWW4zMnFyWjNKOVZzK3VwdGJYYS9RRT0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2cv-akashth%40microsoft.com&OR=Teams-HL&CT=1667295819544&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjEwMTQwNjMwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)
### MAS Reference:
[MAS 4.3.3 – User Preferences](https://aka.ms/MAS4.3.3)
### Environment Details:
#URL: [React App (azureedge.net)](https://msft-lcw-trial.azureedge.net/lcwsandbox/v1/index.html)
Omnichannel URL: https://org81387200.crm10.dynamics.com/main.aspx?forceUCI=1&appid=3f7a6f66-3851-ed11-9562-000d3a57d99d 
Application Name: Live Chat Widget - Version 2
Edge Version 107.0.1418.52 (Official build) (64-bit)

### OS Details:
Edition Windows 11 Pro Version 22H2
Installed on ‎27-‎09-‎2022
OS build 22621.819
Experience Windows Feature Experience Pack 1000.22636.1000.0

**Comment by pgopinadhu** [comment]
#A11yMAS;#A11ySev2;#HCL;#MAS4.3.1;#Accessibility;#Win11-Edge(Chromium);#BotFrameworkWebChat-Jul22;

**Comment by elopezanaya** [comment]
is this different from an already closed bug  =>  https://github.com/microsoft/BotFramework-WebChat/issues/4559 ? ,

**Comment by johnataylor** [comment]
this be addressed with https://github.com/microsoft/BotFramework-WebChat/pull/4619
with the fix available in the next release
