### ISSUE TITLE
Webchat not working for Indian Language - Tamil

### ISSUE THREAD

**Issue by apvarana** [microsoft/BotFramework-WebChat#4639]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which area does this issue affect?

Telemetry

### Please describe the bug

We want the bot to support tamil language which is supported by LUIS and QnAMaker (ta-IN is the locale), But it is not working with webchat.js. This however works in bot framework emulator.

### Do you see any errors in console log?

```js
None
```

### How to reproduce the issue?

1. Navigate to bot ( hosted on website using webchat)
2. Click on bot and open
3. Select the specific language
4. In message box it shows text in english only
We added this is javascript

if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED' && langchoice === "ta-IN") {                    dispatch({                        type: 'WEB_CHAT/START_SPEAKING',                        payload: {                            text: 'வண்ணகம்'                        }                    });                }

### What do you expect?

![image](https://user-images.githubusercontent.com/55237782/218656851-c54c51aa-a959-4f47-897e-1669492ea4cc.png)
In the message box we expect the Tamil langauge

### What actually happened?

It shows "Type your Message" in english , This how ever works for Japanese and Hindi languages.

**Comment by compulim** [comment]
Tamil (`ta`) is not officially supported by our localization team. I will ping them to see if they will expand their work into Tamil.

In the meanwhile, community contributions are welcomed. You can refer to our [`LOCALIZATION.md`](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/LOCALIZATION.md) and see how you can contribute.

**Comment by amol-tcsteg** [comment]
Hi

> Tamil (`ta`) is not officially supported by our localization team. I will ping them to see if they will expand their work into Tamil.
> 
> In the meanwhile, community contributions are welcomed. You can refer to our [`LOCALIZATION.md`](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/LOCALIZATION.md) and see how you can contribute.

Hi @compulim , 
Can you please confirm whether the team will expand their work to include Tamil?

**Comment by compulim** [comment]
I talked to the localization team.

Although we do support Tamil in some Microsoft products, Tamil is currently not planned for Web Chat.

That also means, we are open for community-contributed localization for Tamil. 😉
