### ISSUE TITLE
How to send event from Bot to webchat?

### ISSUE THREAD

**Issue by zxr90** [Microsoft/BotFramework-WebChat#464]
From the backchannel app example,

```
const createEvent = (eventName, value, address) => {
    var msg = new builder.Message().address(address);
    msg.data.type = "event";
    msg.data.name = eventName;
    msg.data.value = value;
    return msg;
}
```
An event was created and sent back to the webchat. However when i was trying out this example, msg.data is a Protected property and cannot be assigned any value. If so, how do i send event from bot to webchat?

**Comment by zxr90** [comment]
any updates on this?

**Comment by danmarshall** [comment]
Hi @zxr90 since this issue is in the SDK on the server-side of your bot, I am going to close it. Can you please file this issue at https://github.com/Microsoft/BotBuilder

**Comment by danmarshall** [comment]
@zxr90 you may also want to ask on StackOverflow

**Comment by zxr90** [comment]
okay, thank you!
