### ISSUE TITLE
How to Refresh WebChat Token

### ISSUE THREAD

**Issue by OmShrivastava** [Microsoft/BotFramework-WebChat#466]
Hi I am using Webchat in my web site application
I am generated Token using WebChat Secret, **Not using DirectLine**

I am not able to find API and process to Refresh token after 30 min for my Webchat
due to this chat session is expired after 30 min and stop responding

If I regenerate token with secret my conversation data will lost

**Comment by billba** [comment]
Please see the [Direct Line API docs](https://docs.botframework.com/en-us/restapi/directline3/).

**Comment by billba** [comment]
@OmShrivastava did this answer your question?

**Comment by OmShrivastava** [comment]
yes your response helped me to resolved issue 

**I am generating token for my web-chat using below URL**
https://webchat.botframework.com/api/conversations

**and refreshing with direct-line it's working**
https://directline.botframework.com/v3/directline/tokens/refresh
