### ISSUE TITLE
Getting console error in using WebChat in portal

### ISSUE THREAD

**Issue by dkulkarni-ms** [microsoft/BotFramework-WebChat#4691]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Telemetry

### Please describe the bug

We are trying to use Azure Bot Service to create a chatbot and using Webchat to integrate in Portal. However when we integrate in Azure portal, we see console errors related to Cors policy. We have enabled the origin in WebApp Service still getting this Cors policy issue. How can this be fixed? Bot loads fine and works fine. Its only that error messages in console needs to be addressed. Also we are using Iframe to show the out of box webchat. 

![image](https://user-images.githubusercontent.com/67392055/229979341-0421c359-1539-483e-9e96-32b56813dc0e.png)

### Do you see any errors in console log?

```js
Yes uploaded the screenshot above.
```

### How to reproduce the issue?

1. Navigate to ...
2. Click on ...
3. Type "..." in the send box

### What do you expect?

Either fix or way to work around this issue and not see the errors in console logs

### What actually happened?

As explained above, errors in console logs

**Comment by stevkan** [comment]
> using Webchat to integrate in Portal

Can you explain what you mean by this statement? Do you mean you have simply created an Azure Web App to host the iframe page? Or are you trying to do something else?

And, for the above, can you explain how you are trying to implement or code this?

**Comment by mrk1989** [comment]
The error exaplain too.. you have to add your domain in section CORS.
