### ISSUE TITLE
Auto scroll not working on Adaptive Card with expandable part

### ISSUE THREAD

**Issue by duanekord** [Microsoft/BotFramework-WebChat#470]
I have an adaptive card with three buttons. The 'Support Option' button opens another card that gives the user two more buttons to choose from.

Unfortunately when I click on the button - the card opens below but my window does not scroll down automatically to show the rest of the card.  I have to scroll down to see the rest of my card. On the reverse, if I am scrolled to the bottom of the card and then collapse the showCard button my window auto scrolls perfectly.

If your card expands it is my opinion that the screen should scroll to the bottom of the card.  

Scrolled all the way down and 'Support Options' button is collapsed.  Looks Good.
![image](https://cloud.githubusercontent.com/assets/14949544/26253973/ec813848-3c69-11e7-8a71-035eeecb0073.png)

Button is pressed but does not scroll down to include the new adaptive card.
![image](https://cloud.githubusercontent.com/assets/14949544/26254077/33b7fd32-3c6a-11e7-9ea2-0392f348c22c.png)

This is how I would expect it to look on button press-
![image](https://cloud.githubusercontent.com/assets/14949544/26254224/a674c1a2-3c6a-11e7-933e-0b93b8e91ba9.png)

**Comment by ankitbko** [comment]
Any update on this?

**Comment by baki32** [comment]
Hi,
we faced similar issue - here's jQuery workaround:

```javascript

//document.ready
$(function(){
            $("body").on("click", "button.expandable", function(){
                var messageWrapper = $(this).parents(".wc-message-wrapper");
                adjustScroll(messageWrapper);
            });

        });

function adjustScroll(el) {
            var topHeight = $(".wc-header")[0].scrollHeight;
            var container = $('.wc-message-groups:first'),
              containerHeight = container[0].scrollHeight,
              scrollTo = $(el);
            var scrollToHeight = scrollTo[0].scrollHeight;
            container.scrollTop(0);
            var childPos = scrollTo.offset(),
              parentPos = scrollTo.parent().offset();

            var childOffset = {
                top: childPos.top - parentPos.top,
                left: childPos.left - parentPos.left
            }

            var heightToSubtract = scrollToHeight < containerHeight ? scrollToHeight : containerHeight;
            var srollTop = (childPos.top + scrollTo[0].scrollHeight) - topHeight;
            var messageTop = $('.wc-console').offset().top - topHeight;
            container.scrollTop((srollTop - messageTop) + $('.wc-suggested-actions').outerHeight());
        }
```

Not perfect but at least something..

**Comment by yodobrin** [comment]
added the below short js to address any new responses from the bot and scroll to the last one. (part of a direct-line implementation)
window.addEventListener('DOMNodeInserted', function (e) {
            if (e.target.className == 'ac-container') {
                setTimeout(function () {
                    try {
                        e.target.scrollIntoView();
                    }
                    catch (e) {
                        console.log(e);
                    }
                }, 300);
            }
        });

**Comment by sgellock** [comment]
we need to validate whether this is fixed in the current bits or not and then based on that, decided if there is an issue here to address

**Comment by compulim** [comment]
It repro in v4.

### Repro steps

- Navigate to https://microsoft.github.io/BotFramework-WebChat/full-bundle/
- Type `card inputs inputs`
- On the first card, click on "Show Card" button

**Comment by compulim** [comment]
Tested `card richmessage` in v4, then click "Set Due Date", which will expand the Adaptive Card.

It works, probably because we bumped the scroll to bottom component recently.
