### ISSUE TITLE
[Visual Requirements - BOT Framework - Web Chat > Adaptive Card inputs]: Place holder value is not defined for the 'Time picker' control. 

### ISSUE THREAD

**Issue by KattaBhargav** [microsoft/BotFramework-WebChat#4724]
### User Experience:
Visual users will be impacted if there is no place holder for the control. Person having limited cognitive abilities and dyslexia person cannot easily understand the purpose of the elements if there is no place holder.

### Note
User credentials should NOT be included in the bug.

### Repro Steps:

1. Launch URL: https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/ on edge dev.
2. Web chat page opens.
3. Press 4-tab keys to reach 'Type your message' field. Enter the "card input" keyword on it. Press 1-tab key to reach the 'send' button and activate it with the enter key.
4. Press 2-shift tabs and 1-down arrow to reach the received card.
5. Verify whether in place holder value is defined for time picker or not.

### Actual Result:
Place holder value is not defined for the 'Time picker' control. 

### Expected Result:
Place holder value should be defined for the 'Time picker' control. 
Place holder value as 'Time picker' should be defined.

### MAS Reference:
[MAS 3.3.2 – Labels or Instructions](https://aka.ms/MAS3.3.2)

### Reference Links:

- [Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-poyad%40microsoft.com%7cc11478591b5a474f6d9d08d7199726c0%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637006009300301864&sdata=ZTWYamT1yE7yko5QU35ZJLf/5ZydtDeGAKrQGUiugJs%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

- External Bug Process: If this bug belongs to the external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information, please use this [link](https://microsoft.sharepoint.com/teams/cea11y/SitePages/External-Bug-Process.aspx). “HCL Staff should not log any third-party external bugs. Should be routed to edad team”.

- Please reach out to the [C&AI Teams channel](https://nam06.safelinks.protection.outlook.com/?url=https://teams.microsoft.com/l/team/19%253a3cd071821b694f11b054d878453cd75f%2540thread.skype/conversations?groupId%3D30e3f968-15dd-4da2-bd8e-85f27e4af2c3%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=02%7c01%7cv-dhti%40microsoft.com%7cf90880a914be401871f108d763233116%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637086876782361405&sdata=/ULS%2BbeqMjysCoiWHvFgAbSnuFJqxO3wtpHmlidPjbU%3D&reserved=0) for any process-related queries.

### Test Environment:

- OS: Windows 11 Enterprise 22H2 (OS build: 22621.1555)
- Browser: Edge Version 114.0.1807.6 (Official build) dev (64-bit)
- URL: [Web Chat: Full-featured bundle (microsoft.github.io)](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/)
- Matrix: Edge dev+ Narrator.

**Comment by KattaBhargav** [comment]
#A11yMAS;#A11ySev3;#HCL;#MAS3.3.2;#Accessibility;#Benchmark;#Win11-Edge(Chromium);#BotFrameworkWebChat-Apr23;

**Comment by raviraushanweb** [comment]
![image](https://github.com/microsoft/BotFramework-WebChat/assets/41154960/26dad5da-211f-4208-ae16-0b8dfee9d9d7)

It is the correct placeholder for the time picker. What change are you expecting?

**Comment by compulim** [comment]
According to [MDN `<input placeholder>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#placeholder), placeholder text is not supported by time picker. It is only supported by `text`, `search`, `url`, tel`, `email`, `password`, and `number` only.

Despite we already set `placeholder` in the `<input type="time">`, browser did not show it. I think this is correct behavior.

![image](https://github.com/microsoft/BotFramework-WebChat/assets/1622400/15ff9554-1b6f-4e9b-adb4-04e01b6e8a2a)
