### ISSUE TITLE
Send Box becomes unresponsive on toggling ReactWebChat full bundle component

### ISSUE THREAD

**Issue by cpendery** [microsoft/BotFramework-WebChat#4745]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest)

### Which area does this issue affect?

Send box

### Please describe the bug

When the `<ReactWebChat/>` (full bundle) component is rendered once, hidden, and then re-rendered the send box becomes unresponsive.

### How to reproduce the issue?

1) Use this minimum reproducible example: https://github.com/cpendery/bot-framework-toggle-failure-example
2) Toggle the WebChat component on
3) Send a message to the bot
4) Toggle the WebChat component off
5) Toggle the WebChat component on
6) Attempt to send a message

### What do you expect?

I'd expect to be able to render the ReactWebChat component multiple times using the same store/direct line token in a toggle manner without it becoming unresponsive.

### What actually happened?

When toggling the ReactWebChat component, the send box becomes unresponsive.

**Comment by ramfattah** [comment]
Investigating.

**Comment by ramfattah** [comment]
Hi @cpendery, 

Looks like this issue might be related to #4300

There are two possible solution:
1. **Downgrade React**: Downgrading react to 17.02 solved this issue from my end.
    1. Open terminal and navigate to root project
    2. Run `npm i react@17.0.2 react-dom@17.0.2`
    3. Change `index.tsx` code the following:
          ```js
          import React from "react";
          import ReactDOM from "react-dom";
          import App from "./App";
          
          const rootElement = document.getElementById("root");
          
          ReactDOM.render(
            <React.StrictMode>
              <App />
            </React.StrictMode>,
            rootElement
          );
          ```
    4. Run `npm start`

2. **Await Future Resolution**: I will inform the WebChat development team about this issue so they can begin devising a solution.

**Comment by ramfattah** [comment]
Thank you @stevkan the help.  🚀
