### ISSUE TITLE
Prepublish not running on forked 

### ISSUE THREAD

**Issue by ravievontech** [Microsoft/BotFramework-WebChat#475]
i forked this package and customized. I pushed the changes to my forked repo. When i use my forked repo in my package json file, i can see the package being installed in my node_modules. However prepublish  script not fired. I cant see generated botchat.js and css file. Can you help me in this?

**Comment by danmarshall** [comment]
Hello, what error message do you see?

**Comment by billba** [comment]
`botchat.js` will not be built if you are including WebChat as a dependency. This is correct, as you wouldn't be using the bundled file. However you will still need the css files, and so you're correct that it's a problem that they aren't being built. @danmarshall we may need to check them in.

**Comment by danmarshall** [comment]
I'm still trying to understand this scenario. Is this about **prepublish** ? [Prepublish runs in 2 cases](https://docs.npmjs.com/misc/scripts): 
* when installing with `npm install`
* when publishing to a registry

@ravievontech - are you publishing your package?

**Comment by ravievontech** [comment]
@billba  thanks for your reply. Yeah i figured it. Your comments helped a lot. @danmarshall: thanks i got the issue. When i see my dependency fork in node_modules, i don't see build folder there. Looks like i have to check in build folder to use it as a dependency.

**Comment by billba** [comment]
@ravievontech please see my updated comment above

**Comment by ravievontech** [comment]
@billba thanks, i did same in my forked one.
