### ISSUE TITLE
Not able to customize the typing animation

### ISSUE THREAD

**Issue by SanKumar0632** [microsoft/BotFramework-WebChat#4806]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Customization: Branding

### Please describe the bug

In issue #2213 it is mentioned that we can customize the typing animation using the typingAnimationBackgroundImage attribute in StyleOptions, but when I try to give the image path as value to this attribute, the typing animation disappears completely.

### How to reproduce the issue?

1. Navigate to ...
2. Click on ...
3. Type "..." in the send box

### What do you expect?

I expect our gif to be the typing indicator of the bot.

### What actually happened?

The native typing indicator disappears completely when we try to customize it.

**Comment by ramfattah** [comment]
Hi @SanKumar0632, I'm looking into this.

**Comment by SanKumar0632** [comment]
Thank you for your response, I was able to customize the typing gif using [this](https://github.com/microsoft/BotFramework-WebChat/issues/1831#issuecomment-1177548232). Still, there should be a simpler way of doing this as follows:
`typingAnimationBackgroundImage : 'GifOrImagePath'`

**Comment by ramfattah** [comment]
Thanks @SanKumar0632, 

Indeed the typing indicator can be customized using the `styleOptions` property. 

Example in a react component:
```js
import React, { useEffect, useState } from 'react';
import ReactWebChat, { createDirectLine } from 'botframework-webchat';
import axios from 'axios';

const WebChat = () => {
  const [token, setToken] = useState(null);

  useEffect(() => {
    axios.post('http://localhost:3001/directline/conversations')
      .then(response => {
        setToken(response.data.data.token);
      })
      .catch(err => console.error(err));
  }, []);

  const styleOptions = {
    typingAnimationDuration: 5000, 
    typingAnimationHeight: 200,
    typingAnimationWidth: 200,
    typingAnimationBackgroundImage: `url('https://media.tenor.com/hlKEXPvlX48AAAAC/loading-loader.gif')` 
  };

  const directLine = token ? createDirectLine({ token }) : null;
  
  return directLine ? <ReactWebChat directLine={directLine} styleOptions={styleOptions} /> : <div>Loading...</div>;
}

export default WebChat;

```
