### ISSUE TITLE
Is it possible to change the IBotConnection after the control has been initially rendered?

### ISSUE THREAD

**Issue by jamesemann** [Microsoft/BotFramework-WebChat#482]
Is it possible to change the IBotConnection after the control has been initially rendered?

Scenario: I have a list of conversations that I'd like to switch between in my React app.  I've created a custom IBotConnection to pull conversation history from persistent store, this is is bound to the Chat control using the botConnection attribute.  

- If I create another instance and rebind it seems to still be bound to the first IBotConnection

` var connection = new HistoricalChatConnection(this.state.activeConversation.id);`
`<Chat user={user} bot={bot} botConnection={connection} />`

- I could just update the IBotConnection instance and pass it my new conversation details, but I would get unwanted conversation history.

I hope that is clear, just looking for guidance really. If I'm doing something completely wrong - and there's a good chance - please tell me :-)

**Comment by billba** [comment]
No. A better idea is to create multiple instances of Chat and switch between them.

**Comment by jamesemann** [comment]
Thanks for the info.
