### ISSUE TITLE
Any styling options for the typing indicator that involves making it rounder?

### ISSUE THREAD

**Issue by samy-rashed03** [microsoft/BotFramework-WebChat#4822]
### I have a question

So I'm looking at the defaultStyleOptions.js file, the only styling options I found in relation to the typing indicator whenever the user is waiting for a response, are these

typingAnimationBackgroundImage: null,
  typingAnimationDuration: 5000,
  typingAnimationHeight: 20,
  typingAnimationWidth: 64,

If there's a way to perhaps rounden the border of the animation, it would be appreciated

**Comment by ramfattah** [comment]
Hi @samy-rashed03, I'm looking into this.

**Comment by ramfattah** [comment]
@samy-rashed03, 

Hmm looks like a styling option specific to round corners of the typing indicator is not available in [defaultStyleOptions.ts](https://github.com/microsoft/BotFramework-WebChat/blob/2c2d9f209d0ead61fa2a47af3db74c79c3e75b30/packages/api/src/defaultStyleOptions.ts#L4).

Perhaps you could use the following css to round the corners:
```css
.webchat__typingIndicator {
    border-radius: 25px !important;
}
```

Example in HTML header section:
```html
  <style>
    html,
    body {
      height: 100%;
    }

    body {
      margin: 0;
    }

    #root {
      height: 100%;
      /* width: 33%; */
    }

    .webchat__typingIndicator {
      border-radius: 25px !important;
    }
  </style>

```

Typing indicator style output:
![Screenshot 2023-08-09 at 2 13 25 PM](https://github.com/microsoft/BotFramework-WebChat/assets/38049078/40eb1e13-1e66-4680-a44e-f6cba21e9f8a)

**Comment by samy-rashed03** [comment]
> @samy-rashed03,
> 
> Hmm looks like a styling option specific to round corners of the typing indicator is not available in [defaultStyleOptions.ts](https://github.com/microsoft/BotFramework-WebChat/blob/2c2d9f209d0ead61fa2a47af3db74c79c3e75b30/packages/api/src/defaultStyleOptions.ts#L4).
> 
> Perhaps you could use the following css to round the corners:
> 
> ```css
> .webchat__typingIndicator {
>     border-radius: 25px !important;
> }
> ```
> 
> Example in HTML header section:
> 
> ```
>   <style>
>     html,
>     body {
>       height: 100%;
>     }
> 
>     body {
>       margin: 0;
>     }
> 
>     #root {
>       height: 100%;
>       /* width: 33%; */
>     }
> 
>     .webchat__typingIndicator {
>       border-radius: 25px !important;
>     }
>   </style>
> ```
> 
> Typing indicator style output: ![Screenshot 2023-08-09 at 2 13 25 PM](https://user-images.githubusercontent.com/38049078/259550750-40eb1e13-1e66-4680-a44e-f6cba21e9f8a.png)

It worked!! Thanks a lot!!!!!
