### ISSUE TITLE
Speech is not working in IE 11 & partially working in MS Edge

### ISSUE THREAD

**Issue by PrasenjitSaha** [Microsoft/BotFramework-WebChat#483]
Hi, I have downloaded code from https://github.com/Microsoft/BotFramework-WebChat/tree/speech 
I am using "**cognitive_speech_api**" key to enable speech feature. 

1. But speech is working in Chrome. 
2. In Edge, it is working partially, after speech recognition it is showing in text message writing bar not in body. So, need to click post button. 
3. It is not working in IE 11

**Comment by shahidkhuram** [comment]
(#3) Lack of support for IE11 is a currently a known limitation. The WebChat uses the following Speech SDK which depends on navigator.getUserMedia  https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript 

I can't reproduce (#2) is this a consistent issue for you or sporadic? Speech recognition relies on a websocket connection to cognitive speech, looking at the last few messages on that websocket connection when you hit this might help us figure out the issue.

**Comment by PrasenjitSaha** [comment]
@shahidkhuram thank you for your reply.
Actually I have downloaded **MS BOT Webchat** code from https://github.com/Microsoft/BotFramework-WebChat/tree/speech. Speech is working in Chrome but not in Edge completely.

**Comment by shahidkhuram** [comment]
I understand your scenario, please see the 2nd paragraph in my previous response with the question for you:
>> I can't reproduce (#2) is this a consistent issue for you or sporadic? ...

**Comment by PrasenjitSaha** [comment]
this a consistent issue in edge
________________________________________

**Comment by danmarshall** [comment]
@PrasenjitSaha are you still experiencing this issue?

**Comment by debajitmukherjee** [comment]
@danmarshall  The getUserMedia is now supported by IOS11 Safari, But in the webchat it's not working. Our issue in IOS11 Safari is the following
1) mic icon is appearing.
2) On click of the mic icon it's asking for the access of microphone and then nothing happens.

The Speech recognition is working in following browsers
1) Desktop - Chrome, Edge, FireFox
2) Android Mobile  - Chrome, FireFox

**Comment by mrPrateek95** [comment]
@danmarshall Is there any plan to support Speech in IE11?

**Comment by compulim** [comment]
@debajitmukherjee we tested it works in Safari on iOS 11.3 and 11.4. But it is not working on Chrome/Edge on iOS 11.3 or 11.4. This is because WebView component on iOS does not support WebRTC.

@mrPrateek95 since WebRTC and WebSpeech is not supported by IE11. There are no ways we could do to enable that. I am sorry.

@PrasenjitSaha since we reworked on some speech code. If Edge is still repro-ing your issue "need to press ENTER after speech are recognized". Please file a bug to us.
