### ISSUE TITLE
"iconUrl" property not found in "activity.from" when receiving a message from bot

### ISSUE THREAD

**Issue by CabuxaMapache** [Microsoft/BotFramework-WebChat#485]
I'm using DirectLine channel to test my bot. I followed example ["Easy: In your non-React website, run WebChat inline"](https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-webchat-inline)
When the bot send a message there is no property "iconUrl" in activity.from property. However, if the user sends a message, the property is present and has the value set during App initialization. My code:

> BotChat.App({
	directLine: {
		token: '_XXXXX',
		webSocket: false
	},
	user: {
		id: 'User',
		name: 'user name',
		iconUrl: '[url to my image]'
	},
	bot: {
		id: 'myBotId',
		name: 'myBotName',
		iconUrl: '[url to my image]'
	},
	resize: 'detect'
}, document.getElementById("bot"));

**Comment by billba** [comment]
This is correct behavior. Only the `id` and `name` are sent to the bot.

The icon URL's are currently ignored and may go away entirely.

**Comment by CabuxaMapache** [comment]
Uummm not sure about this...i'm talking about the bot response. How can i show the bot icon in the webchat?

**Comment by billba** [comment]
This feature is not yet implemented. Feel free to contribute to the discussion about how it should be implemented in https://github.com/Microsoft/BotFramework-WebChat/issues/43

**Comment by billba** [comment]
Also, just for future reference, please be clearer in your issue report. It sounds like your issue was that your wanted to show the bot icon, but that information is nowhere to be found in the title or body of your report.
