### ISSUE TITLE
Text unintendedly gets converted to emoji 

### ISSUE THREAD

**Issue by dassabya15** [microsoft/BotFramework-WebChat#4858]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest), Browser: Chrome (latest), Platform: Windows, Platform: macOS, Platform: iOS/iPadOS, Platform: Android

### Which area does this issue affect?

Send box

### Please describe the bug

Entries in WebChat that resemble emoticons are being converted to emoticons, even if that's not the intention. For example, 17:00 gets converted into 17<Smile Emoji>0. 

### How to reproduce the issue?

1. Type 17:00 on the send box

### What do you expect?

17:00

(More generally, the time should be shown instead of being converted to an emoji)

### What actually happened?

Text gets converted to emoji

![d283deaa-6186-4f4a-ae48-dce602695413](https://github.com/microsoft/BotFramework-WebChat/assets/50560124/2b5d656e-b486-4361-a98c-e47ed13bb876)

![fce3522c-e6a9-41be-9fcd-777d1309addb](https://github.com/microsoft/BotFramework-WebChat/assets/50560124/ec08a707-e68b-40d9-947c-004be35cf997)

**Comment by ramfattah** [comment]
Thanks @dassabya15, i'm looking into this.

**Comment by ramfattah** [comment]
Thanks for reporting this @dassabya15.

It appears I'm able to reproduce this issue using WebChat sample [k.direct-line-token](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/01.getting-started/k.direct-line-token)


https://github.com/microsoft/BotFramework-WebChat/assets/38049078/dcef6a48-ebec-4005-8bf8-8d8e4cf2f2d0

**Comment by ramfattah** [comment]
@dassabya15, I'll discuss this internally with the engineers and report back.

Thanks.

**Comment by ramfattah** [comment]
Hi @dassabya15, pressing `CTRL` and  `Z` reverts the emoji back to ascii characters.
