### ISSUE TITLE
Citation may not need to use protocol "cite:"

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#4869]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Development build

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Others or unrelated

### Which browsers and platforms do the issue happened?

Others or unrelated

### Which area does this issue affect?

Chat history

### Please describe the bug

Today, citations must be a IRI using protocol `cite:`. This restriction should be lifted.

Instead, a citation should only be a Schema.org `Claim` in the `entities` array, with an `@id` for an IRI.

### How to reproduce the issue?

1. Handcraft an activity with a citation using protocol `abc:`
2. Start conversation
3. Click on the citation

### What do you expect?

The citation modal dialog show show.

### What actually happened?

The citation modal dialog is not shown.

**Comment by compulim** [comment]
We probably need to lockdown on a specific protocol prefix because browser could use other protocols to launch native apps.

**Comment by mamun-131** [comment]
what should be the JSON structure into turn_context.send_activity to activate pop up modal citation?
