### ISSUE TITLE
Botframework-webchat react upload an attatchment

### ISSUE THREAD

**Issue by jerry75916** [microsoft/BotFramework-WebChat#4891]
### I have a question

Hello,

I use Botframework-webchat and create a react18 project from url below

[https://github.com/microsoft/BotFramework-WebChat/tree/master/samples](url)

I use the sample demo from

[https://microsoft.github.io/BotFramework-WebChat/01.getting-started/b.minimal-bundle/](url)

It can upload file and click download link from the responsed file(newfile.png).
![newfile](https://github.com/microsoft/BotFramework-WebChat/assets/101940444/b02af5ad-3ec7-4b98-a4a0-31d6150810a9)

but in my code below i don't known how to handle it to response my file url(i already upload my file to my blob container)
![upload](https://github.com/microsoft/BotFramework-WebChat/assets/101940444/5abf1d4a-4918-4f8f-a2a9-ccbe1b88527a)
and i also don't known how to use the dispatchs and meanings

Could somebody help me handle this and explain how to use dispatchs in React18 BotFramework-WebChat  thanks.

**Comment by dmvtech** [comment]
If you use [this sample](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/15.handling-attachments), how does it behave?

**Comment by dmvtech** [comment]
Closing due to lack of response.
