### ISSUE TITLE
Getting "Network interruption occurred. Reconnecting" issue in the Bot framework chatbot

### ISSUE THREAD

**Issue by asing61** [microsoft/BotFramework-WebChat#4942]
### I have a question

Hi Team,
 
We have got an issue with the chatbot built in Bot framework, .NET 7.0 runtime stack.
We have built a chatbot in .NET and hooked the bot with Reactjs web page. Chatbot is working as expected while interacting but when we put chatbot in idle state for 4 to 5 minutes we get a flash message which comes for a fraction of seconds and then it automatically restart the conversation. We have implement SSO in the chatbot where after successful login, we display the welcome message in the chatbot. So the issue is when we put the chatbot idle for 4-5 minutes it flashes a message "Network interruption occurred. Reconnecting" and then it display the welcome message again. Please refer the screenshot attached.

Please let us know if any other details needed from our end.
![MicrosoftTeams-image (3)](https://github.com/microsoft/BotFramework-WebChat/assets/149570306/49e74566-9054-44eb-83bc-327f2baf691f)
![MicrosoftTeams-image (4)](https://github.com/microsoft/BotFramework-WebChat/assets/149570306/63070a5d-962f-4b34-ba01-1c60a9126280)

**Comment by stevkan** [comment]
@asing61 - Thank you for your patience. Are you still experiencing an issue with this?

If so, are you using the [DirectLine App Service Extension](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension?view=azure-bot-service-4.0)?

**Comment by stevkan** [comment]
Closing as duplicate ICM (#[447524851](https://portal.microsofticm.com/imp/v3/incidents/incident/447524851/summary)) was created by the customer.

Additionally, this issue has already been identified and addressed in ICM #[423648058](https://portal.microsofticm.com/imp/v3/incidents/incident/423648058/summary) with the below workaround solutions available:

> It’s a real websocket disconnection happens between app service and Directline ASE. Hence the reconnection is necessary and considered as a new connection. There are several ways resolve this issue as below.
>
> - Dev team is preparing a DL ASE v2.0 which is a different design, which fixed this issue. The DL ASE v2.0 will be public after around 4 months. Before that, we are discussing whether we can share a beta version with you before the public release.
> - Using DirectLine without ASE which is good because the design is different. Let’s discuss about the details in the meeting.
> - In the Bot app, send a quick response to the question like “working” to complete the event. Then using another method to send the real answer in another activity like proactive message.
