### ISSUE TITLE
Intervall Max Turn Count

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/BotFramework-WebChat#4949]
### I have a question

We have a chatbot which is developed with the Botframework Composer. We ask, inside a concersation the user to say yes or no. We show two suggested actions "yes" and "no". If the user leaves the chat open, then after 120 sec (?) the question will be automatically answered by the botframework. It seems after 120 seconds. If I set the "max turn count" property to 3, then every 120 seconds the question is repeated. then after 3 times it will break the conversation.

My question is, are the 120 seconds configurable in any settings or via any function?

Regards
Andreas

**Comment by dmvtech** [comment]
The bot should not respond on the user's behalf. At least not typically. Unless that is something you have developed into your bot. And there is nothing in webchat (at least in the basic webchat sample) that should be doing the same.

 Does the issue reproduce with a bot sample like this one?:
 https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/08.suggested-actions
 
 Does the issue happen in `Test in Web Chat` (azure portal blade)

**Comment by andreas-sommer-engenious** [comment]
It happens in two independent chatbots developed with Composer. Maybe this is a specialty of the AdaptiveDialog class. It has not been implemented which could explain this behavior.

**Comment by dmvtech** [comment]
For the asking the question portion; is this a confirmation prompt or a multi-choice prompt?

**Comment by andreas-sommer-engenious** [comment]
It is a multi-choice prompt

**Comment by dmvtech** [comment]
This behavior is not reproducible (with the basic webchat at least. Nor in multi choice prompt). If this behavior is not implemented in the bot, then it has to be in webchat. Are you able to share your webchat code? Or are you using a specific webchat sample?

**Comment by dmvtech** [comment]
Closing due to lack of response.
