### ISSUE TITLE
How to use Javascript SDK for Bing Speech API in webchat?

### ISSUE THREAD

**Issue by mohit-jcc** [Microsoft/BotFramework-WebChat#496]
I'm trying to have speech input in the WebChat using Javascript WebSocket method as explained here : https://docs.microsoft.com/en-in/azure/cognitive-services/speech/getstarted/getstartedjswebsockets

This documentation suggests using the JS SDK to have run time speech recognition that requires a UI element to start audio input. For speech input, it's important to have a microphone element in the UI that the users can tap before providing audio input.

Wondering if there's an out-of-the-box solution to have such speech controls in the UI or is there a better way to include speech capability in WebChat?

Thanks

**Comment by GeekTrainer** [comment]
It's currently on the speech branch. We're evaluating it now, and trying to determine the best way to incorporate it into the control. It's coming soon. :-)

**Comment by danmarshall** [comment]
The speech branch has been merged to master, and you will see a microphone icon when speech is configured. Please see https://github.com/Microsoft/BotFramework-WebChat#enabling-speech-capabilities
