### ISSUE TITLE
BotFramework-WebChat is not support in SPFX Extension (Application Customizer)

### ISSUE THREAD

**Issue by Hasnii501** [microsoft/BotFramework-WebChat#4975]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

SharePoint

### Which area does this issue affect?

Development experience

### What is the public URL for the website?

https://github.com/Hasnii501/app-extension.git

### Please describe the bug

I am using SharePoint SPFX extension. When I try to use the chatbot framework, it fails to build the package.

### Do you see any errors in console log?

```js
Error - [webpack] 'dist':
./node_modules/micromark-util-decode-numeric-character-reference/index.js 23:11
Module parse failed: Identifier directly after number (23:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   code > 126 && code < 160 ||
|   // Lone high surrogates and low surrogates.
>   code > 55_295 && code < 57_344 ||
|   // Noncharacters.
|   code > 64_975 && code < 65_008 || /* eslint-disable no-bitwise */
 @ ./node_modules/mdast-util-from-markdown/lib/index.js 138:0-97 1061:14-45
 @ ./node_modules/mdast-util-from-markdown/index.js
 @ ./node_modules/botframework-webchat/lib/markdown/private/iterateLinkDefinitions.js
 @ ./node_modules/botframework-webchat/lib/markdown/renderMarkdown.js
 @ ./node_modules/botframework-webchat/lib/index.js
 @ ./lib/extensions/henkelChatbotCustomizer/renderer/Chatbot.js
 @ ./lib/extensions/henkelChatbotCustomizer/HenkelChatbotCustomizerApplicationCustomizer.js
./node_modules/micromark-util-sanitize-uri/index.js 86:22
Module parse failed: Identifier directly after number (86:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     // Astral.
>     else if (code > 55_295 && code < 57_344) {
|       const next = value.charCodeAt(index + 1)
|
 @ ./node_modules/micromark/lib/compile.js 44:0-55 770:10-21 781:10-21 1089:8-19 1105:22-33
 @ ./node_modules/micromark/index.js
 @ ./node_modules/mdast-util-from-markdown/lib/index.js
 @ ./node_modules/mdast-util-from-markdown/index.js
 @ ./node_modules/botframework-webchat/lib/markdown/private/iterateLinkDefinitions.js
 @ ./node_modules/botframework-webchat/lib/markdown/renderMarkdown.js
 @ ./node_modules/botframework-webchat/lib/index.js
 @ ./lib/extensions/henkelChatbotCustomizer/renderer/Chatbot.js
 @ ./lib/extensions/henkelChatbotCustomizer/HenkelChatbotCustomizerApplicationCustomizer.js
./node_modules/htmlparser2/lib/esm/index.js 48:9
Module parse failed: Unexpected token (48:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * They should probably be removed eventually.
|  */
> export * as ElementType from "domelementtype";
| import { getFeed } from "domutils";
| export { getFeed } from "domutils";
 @ ./node_modules/sanitize-html/index.js 1:19-41
 @ ./node_modules/botframework-webchat/lib/markdown/renderMarkdown.js
 @ ./node_modules/botframework-webchat/lib/index.js
 @ ./lib/extensions/henkelChatbotCustomizer/renderer/Chatbot.js
 @ ./lib/extensions/henkelChatbotCustomizer/HenkelChatbotCustomizerApplicationCustomizer.js
```

### How to reproduce the issue?

1. Create new extension of SharePoint Framework (Application Customizer)
2. Add chatbot framework code in file and install the package for example "botframework-webchat": "^4.9.1"
3. Call the chatbot file and use the code in extension
4. Build the project.

### What do you expect?

The project should build sucessfully

### What actually happened?

Build Failed with error mentioned.

### Do you have any screenshots or recordings to repro the issue?

![image](https://github.com/microsoft/BotFramework-WebChat/assets/119679419/090e5d31-25b7-4336-afd9-522cf9807cbd)

### Additional context

Below is my Package.JSON

```
{
  "name": "chatbot-extension-v-1",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "tslib": "2.3.1",
    "@microsoft/sp-core-library": "1.15.2",
    "@microsoft/decorators": "1.15.2",
    "@microsoft/sp-dialog": "1.15.2",
    "botframework-webchat": "^4.9.1",
    "@microsoft/sp-application-base": "1.15.2"
  },
  "devDependencies": {
    "@microsoft/rush-stack-compiler-4.5": "0.2.2",
    "@rushstack/eslint-config": "2.5.1",
    "@microsoft/eslint-plugin-spfx": "1.15.2",
    "@microsoft/eslint-config-spfx": "1.15.2",
    "@microsoft/sp-build-web": "1.15.2",
    "@types/webpack-env": "~1.15.2",
    "ajv": "^6.12.5",
    "gulp": "4.0.2",
    "typescript": "4.5.5",
    "@microsoft/sp-module-interfaces": "1.15.2"
  }
}
```

**Comment by compulim** [comment]
Looks like SharePoint Framework (SPFx) is using an outdated version of toolchain that doesn't support compiling ES Modules and newer code under `/node_modules/` folder.

Today, increasing number of packages are ESM-only. For example, the `mdast`-family package which we are using in Web Chat are ESM-only. These packages expect the package user to either use an ESM-compatible host (e.g. Node.js > 12) or ESM-compatible bundler (e.g. ESBuild, tsup, Webpack 5, etc.)

In SPFx dependencies under https://www.npmjs.com/package/@microsoft/gulp-core-build-webpack?activeTab=code. They are using `webpack@4.47.0`. Despite 4.47.0 is released recently, it's a major version behind the current one and is 3 years behind the current version.

Could you file an issue to their repo and ask them to update their toolchain?

To workaround their issue, you can try either:

1. (Recommended) Compile your package using ESBuild/tsup before using SPFx to compile the final bundle
2. Overriding their Webpack configuration to include compiling stuff under `/node_modules/`
