### ISSUE TITLE
ConversationUpdate Activity Event issue 

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotFramework-WebChat#498]
System Information (Required)

SDK Language: .NET/C#

SDK Version: Latest
Channels : WebChat & Emulator

Development Environment: LOCALHOST

Issue Description

I have a simple bot created to send a welcome message with menu selection using adaptivecard as activity attachment. I'm using the ConversationUpdate event to send this welcome message. Now, once user click on any menu item it's always coming as "ConversationUpdate" activity type in the message controller in the API. Issue is with the webchat. Emulator working fine and its coming as "Message" activity type.

Expected Behavior

WebChat should send it as a AcivityType.Message Event when user reponds as the same way as it working in emulator

**Comment by DL-LiveTiles** [comment]
@sowsan We solved this by forking the project and adding a ConversationUpdate event using the back channel.
Detail here:
https://github.com/Microsoft/BotFramework-WebChat#the-backchannel
https://docs.botframework.com/en-us/restapi/directline3/

**Comment by sowsan** [comment]
Thank you , how can I test and verify it ?

**Comment by billba** [comment]
@sowsan I don't understand the issue. What do you mean hy "once user click on any menu item". What menu items do you mean?

**Comment by sowsan** [comment]
in the welcome message I'm sending an adapative card with few buttons (menu buttons). You can check the code that I have shared

**Comment by sowsan** [comment]
https://github.com/sowsan/Bot/tree/master/Bot-Demo/Bot-Demo

**Comment by billba** [comment]
@danmarshall @dandriscoll this sounds like a bug but I'm not sure whose fault it is, except that it's definitely not mine. IT'S NOT MY FAULT.

**Comment by danmarshall** [comment]
@sowsan does this behavior affect other channels as well?

**Comment by sowsan** [comment]
@dandriscoll I have tested it only with the emulator & webchat and issue is there only with webchat. There is an active thread going on here as well on the same : https://github.com/Microsoft/BotBuilder/issues/2919

**Comment by danmarshall** [comment]
@sowsan I am going to close this issue here in the WebChat repo since it is also being tracked in BotBuilder and is more related to DirectLine behavior than WebChat itself.
