### ISSUE TITLE
Presence of unnecessary role=complimentary can create unexpected behavior across various configurations.

### ISSUE THREAD

**Issue by cryptasian** [microsoft/BotFramework-WebChat#4983]
### Is it an issue related to Adaptive Cards?

No.

### What is the PWD impact?

The presence of an unnecessary ARIA attribute can create unexpected behavior across various configurations.

### Are there any code-based customization done to Web Chat?

No, I am using Web Chat without any customizations except "styleOptions".

### What version of Web Chat are you using?

Latest production

### Which area does this issue affect?

ARIA roles

### What is the public URL for the website?

https://edfinancial.com

### How to reproduce the issue?

This is feedback from the accessibility company Allyant who has been testing our website and has people who use screenreaders and other assistive technologies as a part of their testing team.

The presence of an unnecessary ARIA attribute can create unexpected behavior across various configurations.

![role-compliementary](https://github.com/microsoft/BotFramework-WebChat/assets/30207740/bf3aa04c-6ed4-4c0d-900e-426e2ade6bc0)

### What do you expect?

Remove the role=complementary attribute.

### What actually happened?

See other responses.

### WCAG reference

https://www.w3.org/WAI/WCAG22/Understanding/name-role-value

**Comment by compulim** [comment]
Role can be changed by web developers when rendering Web Chat, https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/component/src/BasicWebChat.tsx.

We will set it to complementary if the web developers did not pass a role.

If complementary role is not desirable in their case, please ask the web developers to change the role to what fit in their scenario.
