### ISSUE TITLE
Can a FormBuilder display list of strings instead of elements from a enum

### ISSUE THREAD

**Issue by amit6257** [Microsoft/BotFramework-WebChat#499]
I want the user to choose one or more items from a list. As of now I am able to use an Enum as the data source to get the options. But I want to use custom data to get the options. 
In a form at the run time, I would like to have a list of strings and ask user to chose one or more from that list. Also, at the OnCompletion method call, I would like to get the user selected value just as I would get that for an Enum.

Please let me know how to achieve that. Is it possible with FormBuilder ?
Are there any other UI controls that I can use to achieve same result?

**Comment by danmarshall** [comment]
Hi @amit6257 - are you referring to the C# SDK? If so, this question might be better for https://github.com/Microsoft/BotBuilder or StackOverflow. 

If you want to build custom UI, you might try looking at [Adaptive Cards](http://adaptivecards.io/)

**Comment by GeekTrainer** [comment]
Closing, as this appears to be a bot design issue, rather than a client issue.
