### ISSUE TITLE
Unnecessary ARIA attributes in transcript/conversation box.

### ISSUE THREAD

**Issue by cryptasian** [microsoft/BotFramework-WebChat#4993]
### Is it an issue related to Adaptive Cards?

No.

### Are there any code-based customization done to Web Chat?

No, I am using Web Chat without any customizations except "styleOptions".

### What version of Web Chat are you using?

Latest production

### Which area does this issue affect?

ARIA roles

### What is the public URL for the website?

https://edfinancial.com

### How to reproduce the issue?

This is feedback from the accessibility company Allyant who has been testing our website and has people who use screenreaders and other assistive technologies as a part of their testing team.

The presence of an unnecessary ARIA attribute can create unexpected behavior across various configurations.
![unnecessary-aria-article-role](https://github.com/microsoft/BotFramework-WebChat/assets/30207740/f8efc588-7ca1-4471-a0bb-321d90eea360)

### What do you expect?

The presence of an unnecessary ARIA attribute can create unexpected behavior across various configurations. Remove the role=article attribute from each element.

### What actually happened?

See other responses.

### WCAG reference

https://www.w3.org/WAI/WCAG22/Understanding/name-role-value

**Comment by compulim** [comment]
The message is of role "article". This is correct.

The chat history has a role of "feed", https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Feed_Role.

For items under the feed role, they must have role of "article".

For more information, you can read about the design here, https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/ACCESSIBILITY.md#using-rolefeed-and-rolearticle-to-represent-the-chat-history-and-activity.
