### ISSUE TITLE
It is difficult for screen reader users to identify when the button section ends and the next begins.

### ISSUE THREAD

**Issue by cryptasian** [microsoft/BotFramework-WebChat#4994]
### Is it an issue related to Adaptive Cards?

No.

### Are there any code-based customization done to Web Chat?

No, I am using Web Chat without any customizations except "styleOptions".

### What version of Web Chat are you using?

Latest production

### Which area does this issue affect?

Suggested action

### What is the public URL for the website?

https://edfinancial.com

### How to reproduce the issue?

This is feedback from the accessibility company Allyant who has been testing our website and has people who use screenreaders and other assistive technologies as a part of their testing team.
![button-section-start-end](https://github.com/microsoft/BotFramework-WebChat/assets/30207740/6e6c2db1-2ac9-43a7-a648-4076160e07a7)

### What do you expect?

Add role="group" and aria-label="Suggested actions" attributes describing the content within this region to the tag containing each section.

### What actually happened?

See other responses.

### WCAG reference

https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships

**Comment by compulim** [comment]
The suggested actions is a toolbar. It is correctly identified with `role="toolbar"`. We implement this pattern by following the APG, https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Feed_Role.
