### ISSUE TITLE
Unnecessary ARIA attributes in Keyboard Controls section.

### ISSUE THREAD

**Issue by cryptasian** [microsoft/BotFramework-WebChat#4995]
### Is it an issue related to Adaptive Cards?

No.

### Are there any code-based customization done to Web Chat?

No, I am using Web Chat without any customizations except "styleOptions".

### What version of Web Chat are you using?

Latest production

### Which area does this issue affect?

ARIA roles

### What is the public URL for the website?

https://edfinancial.com

### How to reproduce the issue?

This is feedback from the accessibility company Allyant who has been testing our website and has people who use screenreaders and other assistive technologies as a part of their testing team.

The presence of an unnecessary ARIA attribute can create unexpected behavior across various configurations.
![unnecessary-aria-dialog-role](https://github.com/microsoft/BotFramework-WebChat/assets/30207740/25445530-ee3b-4e85-811b-2f90f593abb8)

### What do you expect?

The presence of an unnecessary ARIA attribute can create unexpected behavior across various configurations. Remove the role=dialog and aria-labelledby attribute from each element.

### What actually happened?

See other responses.

### WCAG reference

https://www.w3.org/WAI/WCAG22/Understanding/name-role-value

**Comment by compulim** [comment]
The keyboard help screen is a modal. `role="dialog"` is a reasonable way to identify this modal. And the `aria-labelledby` is pointing to the title of the dialog.

We are following this APG when building the keyboard help screen, https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/.

Will be great if you can give more context on the issue.
