### ISSUE TITLE
IntegratedAuthenticationNotSupportedInChannel

### ISSUE THREAD

**Issue by m00ali** [microsoft/BotFramework-WebChat#4999]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

IFRAME

### Which hosting environment does this issue primarily affect?

PowerApps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest)

### Which area does this issue affect?

Others or unrelated

### Please describe the bug

I created a PVA chatbot using Microsoft co pilot. I am trying to integrate into my website but receiving this IntegratedAuthenticationNotSupportedInChannel. I tried the demo website but error exists,
Complete error is :
Sorry, something unexpected happened. We’re looking into it. Error code: IntegratedAuthenticationNotSupportedInChannel. Conversation ID: CF55ikdmQVs8epOR7Jr60i-eu. Time (UTC): 1/8/2024 10:54:59 AM.
![image](https://github.com/microsoft/BotFramework-WebChat/assets/139992020/3b2b5283-e2bb-4251-964a-1c0081a72378)

### How to reproduce the issue?

Access it here:
https://web.powerva.microsoft.com/environments/Default-a1e3cc4f-47e2-4e32-a7a1-5b14136b160b/bots/crb40_copilot1jEAPLy/canvas?__version__=2

### What do you expect?

Kindly provide solution.

### What actually happened?

I created a PVA chatbot using Microsoft co pilot. I am trying to integrate into my website but receiving this IntegratedAuthenticationNotSupportedInChannel. I tried the demo website but error exists,
Complete error is :
Sorry, something unexpected happened. We’re looking into it. Error code: IntegratedAuthenticationNotSupportedInChannel. Conversation ID: CF55ikdmQVs8epOR7Jr60i-eu. Time (UTC): 1/8/2024 10:54:59 AM.
![image](https://github.com/microsoft/BotFramework-WebChat/assets/139992020/3b2b5283-e2bb-4251-964a-1c0081a72378)

**Comment by tracyboehrer** [comment]
This is an error on the PVA side.  Check if any of the suggestions in this thread help, or if not posting a new thread in the PVA support community.  Try a search of 'IntegratedAuthenticationNotSupportedInChannel' in that forum as well.

https://powerusers.microsoft.com/t5/General/IntegratedAuthenticationNotSupportedInChannel/m-p/2160190
