### ISSUE TITLE
What visual customization will we allow?

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#50]

**Comment by billba** [comment]
(this is just a tracker - you can close this when we figure this out)

**Comment by kevkor** [comment]
![1-visual_customization](https://cloud.githubusercontent.com/assets/979837/19395691/cbd862f4-91f3-11e6-9242-52280de9906b.png)
![2-offline_connecting_state](https://cloud.githubusercontent.com/assets/979837/19395693/cbdf6ac2-91f3-11e6-8a48-ba533bf91dca.png)
![3-cards_samples](https://cloud.githubusercontent.com/assets/979837/19395690/cbd86be6-91f3-11e6-82c6-05c27dee8236.png)
![4-customize_the_scrollbar_webkit](https://cloud.githubusercontent.com/assets/979837/19395692/cbd93c6a-91f3-11e6-9902-1210cadd49f5.png)

**Comment by siddiq-rehman** [comment]
Hi, How do I add or change the bot icon?

**Comment by corinagum** [comment]
The only remaining work item is the avatar, which is being tracked #43
