### ISSUE TITLE
npm@5 install on mac doesnt work

### ISSUE THREAD

**Issue by hanselke** [Microsoft/BotFramework-WebChat#500]
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> botframework-webchat@0.10.6 prepublish /Users/hanselke/Infrastructure/BotFramework-WebChat
> tsc && npm run build-css && webpack --progress --config webpack.production.config.js

src/ActivityView.tsx(1,24): error TS2307: Cannot find module 'react'.
src/ActivityView.tsx(2,56): error TS2307: Cannot find module 'botframework-directlinejs'.
src/ActivityView.tsx(21,9): error TS2605: JSX element type 'Carousel' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Carousel'.
src/ActivityView.tsx(21,9): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
src/ActivityView.tsx(52,21): error TS2339: Property 'props' does not exist on type 'ActivityView'.
src/ActivityView.tsx(54,21): error TS2339: Property 'props' does not exist on type 'ActivityView'.
src/ActivityView.tsx(56,22): error TS2339: Property 'props' does not exist on type 'ActivityView'.
src/ActivityView.tsx(57,25): error TS2339: Property 'props' does not exist on type 'ActivityView'.
src/ActivityView.tsx(58,25): error TS2339: Property 'props' does not exist on type 'ActivityView'.
src/ActivityView.tsx(62,51): error TS2339: Property 'props' does not exist on type 'ActivityView'.
src/App.tsx(1,24): error TS2307: Cannot find module 'react'.
src/App.tsx(14,9): error TS2605: JSX element type 'Chat' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'Chat'.
src/Attachment.tsx(1,24): error TS2307: Cannot find module 'react'.
src/Attachment.tsx(3,40): error TS2307: Cannot find module 'botframework-directlinejs'.
src/Attachment.tsx(275,89): error TS7006: Parameter 'fact' implicitly has an 'any' type.
src/Attachment.tsx(275,95): error TS7006: Parameter 'i' implicitly has an 'any' type.
src/Attachment.tsx(277,92): error TS7006: Parameter 'item' implicitly has an 'any' type.
src/Attachment.tsx(277,98): error TS7006: Parameter 'i' implicitly has an 'any' type.
src/BotChat.ts(3,15): error TS2307: Cannot find module 'botframework-directlinejs'.
src/Carousel.tsx(1,24): error TS2307: Cannot find module 'react'.
src/Carousel.tsx(2,28): error TS2307: Cannot find module 'botframework-directlinejs'.
src/Carousel.tsx(26,28): error TS2339: Property 'props' does not exist on type 'Carousel'.
src/Carousel.tsx(26,52): error TS2339: Property 'props' does not exist on type 'Carousel'.
src/Carousel.tsx(51,17): error TS2605: JSX element type 'HScroll' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'HScroll'.
src/Carousel.tsx(51,17): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
src/Carousel.tsx(51,32): error TS7006: Parameter 'hscroll' implicitly has an 'any' type.
src/Carousel.tsx(56,21): error TS2605: JSX element type 'CarouselAttachments' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'CarouselAttachments'.
src/Carousel.tsx(56,53): error TS2339: Property 'props' does not exist on type 'Carousel'.
src/Carousel.tsx(73,49): error TS2339: Property 'props' does not exist on type 'CarouselAttachments'.
src/Carousel.tsx(75,24): error TS2339: Property 'props' does not exist on type 'CarouselAttachments'.
src/Carousel.tsx(75,47): error TS7006: Parameter 'attachment' implicitly has an 'any' type.
src/Carousel.tsx(75,59): error TS7006: Parameter 'index' implicitly has an 'any' type.
src/Chat.tsx(1,24): error TS2307: Cannot find module 'react'.
src/Chat.tsx(3,33): error TS2307: Cannot find module 'rxjs/BehaviorSubject'.
src/Chat.tsx(4,28): error TS2307: Cannot find module 'rxjs/Observable'.
src/Chat.tsx(5,30): error TS2307: Cannot find module 'rxjs/Subscription'.
src/Chat.tsx(7,114): error TS2307: Cannot find module 'botframework-directlinejs'.
src/Chat.tsx(112,36): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(113,57): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(114,20): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(117,18): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(120,81): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(120,103): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(120,152): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(122,87): error TS7006: Parameter 'connectionStatus' implicitly has an 'any' type.
src/Chat.tsx(127,13): error TS7006: Parameter 'activity' implicitly has an 'any' type.
src/Chat.tsx(128,13): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/Chat.tsx(131,18): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(132,54): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(132,87): error TS7006: Parameter 'activityOrID' implicitly has an 'any' type.
src/Chat.tsx(135,110): error TS7006: Parameter 'activity' implicitly has an 'any' type.
src/Chat.tsx(174,18): error TS2339: Property 'props' does not exist on type 'Chat'.
src/Chat.tsx(242,16): error TS7006: Parameter 'id' implicitly has an 'any' type.
src/Chat.tsx(244,8): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/FormattedText.tsx(2,24): error TS2307: Cannot find module 'react'.
src/HScroll.tsx(1,24): error TS2307: Cannot find module 'react'.
src/HScroll.tsx(3,28): error TS2307: Cannot find module 'rxjs/Observable'.
src/HScroll.tsx(4,30): error TS2307: Cannot find module 'rxjs/Subscription'.
src/HScroll.tsx(52,101): error TS7006: Parameter '_' implicitly has an 'any' type.
src/HScroll.tsx(57,73): error TS7006: Parameter '_' implicitly has an 'any' type.
src/HScroll.tsx(58,73): error TS7006: Parameter '_' implicitly has an 'any' type.
src/HScroll.tsx(59,21): error TS7006: Parameter 'delta' implicitly has an 'any' type.
src/HScroll.tsx(77,18): error TS2339: Property 'props' does not exist on type 'HScroll'.
src/HScroll.tsx(148,40): error TS2339: Property 'props' does not exist on type 'HScroll'.
src/HScroll.tsx(153,32): error TS2339: Property 'props' does not exist on type 'HScroll'.
src/HScroll.tsx(158,40): error TS2339: Property 'props' does not exist on type 'HScroll'.
src/History.tsx(1,24): error TS2307: Cannot find module 'react'.
src/History.tsx(2,58): error TS2307: Cannot find module 'botframework-directlinejs'.
src/History.tsx(41,18): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(52,41): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(57,18): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(77,9): error TS2605: JSX element type 'WrappedActivity' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'WrappedActivity'.
src/History.tsx(77,9): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
src/History.tsx(78,19): error TS7006: Parameter 'x' implicitly has an 'any' type.
src/History.tsx(101,14): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(102,21): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(108,18): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(109,22): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(111,40): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(114,32): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(114,54): error TS7006: Parameter 'activity' implicitly has an 'any' type.
src/History.tsx(114,64): error TS7006: Parameter 'index' implicitly has an 'any' type.
src/History.tsx(115,21): error TS2605: JSX element type 'WrappedActivity' is not a constructor function for JSX elements.
src/History.tsx(115,21): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
src/History.tsx(116,39): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(119,56): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(119,105): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(119,164): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(120,41): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(121,39): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(122,48): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(123,40): error TS7006: Parameter 'e' implicitly has an 'any' type.
src/History.tsx(128,34): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(131,25): error TS2605: JSX element type 'ActivityView' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'ActivityView'.
src/History.tsx(131,25): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
src/History.tsx(132,43): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(133,41): error TS2339: Property 'props' does not exist on type 'HistoryView'.
src/History.tsx(185,3): error TS2345: Argument of type 'typeof HistoryView' is not assignable to parameter of type 'Component<HistoryProps>'.
  Type 'typeof HistoryView' is not assignable to type 'StatelessComponent<HistoryProps>'.
    Type 'typeof HistoryView' provides no match for the signature '(props: HistoryProps & { children?: ReactNode; }, context?: any): ReactElement<any>'
src/History.tsx(228,22): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(230,41): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(233,41): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(238,32): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(240,52): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(240,80): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(245,26): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(246,33): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(246,92): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(247,41): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(247,74): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(251,26): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(255,19): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(256,18): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(261,18): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(265,42): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(265,108): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/History.tsx(272,32): error TS2339: Property 'props' does not exist on type 'WrappedActivity'.
src/MessagePane.tsx(1,24): error TS2307: Cannot find module 'react'.
src/MessagePane.tsx(2,53): error TS2307: Cannot find module 'botframework-directlinejs'.
src/MessagePane.tsx(23,13): error TS2605: JSX element type 'SuggestedActions' is not a constructor function for JSX elements.
  Property 'setState' is missing in type 'SuggestedActions'.
src/MessagePane.tsx(35,19): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(37,14): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(37,45): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(38,14): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(39,14): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(49,19): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(52,13): error TS2605: JSX element type 'HScroll' is not a constructor function for JSX elements.
src/MessagePane.tsx(52,13): error TS2607: JSX element class does not support attributes because it does not have a 'props' property
src/MessagePane.tsx(57,28): error TS2339: Property 'props' does not exist on type 'SuggestedActions'.
src/MessagePane.tsx(57,93): error TS7006: Parameter 'action' implicitly has an 'any' type.
src/MessagePane.tsx(57,101): error TS7006: Parameter 'index' implicitly has an 'any' type.
src/MessagePane.tsx(81,14): error TS4023: Exported variable 'MessagePane' has or is using name 'React.ComponentClass' from external module "/Users/hanselke/Infrastructure/BotFramework-WebChat/node_modules/@types/react-redux/node_modules/@types/react/index" but cannot be named.
src/Shell.tsx(1,24): error TS2307: Cannot find module 'react'.
src/Shell.tsx(3,22): error TS2307: Cannot find module 'botframework-directlinejs'.
src/Shell.tsx(27,18): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(28,18): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(28,41): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(43,14): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(49,18): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(65,38): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(66,46): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(68,44): error TS2339: Property 'props' does not exist on type 'ShellContainer'.
src/Shell.tsx(105,3): error TS2345: Argument of type 'typeof ShellContainer' is not assignable to parameter of type 'Component<Props>'.
  Type 'typeof ShellContainer' is not assignable to type 'StatelessComponent<Props>'.
    Type 'typeof ShellContainer' provides no match for the signature '(props: Props & { children?: ReactNode; }, context?: any): ReactElement<any>'
src/Store.ts(1,75): error TS2307: Cannot find module 'botframework-directlinejs'.
src/Store.ts(4,33): error TS2307: Cannot find module 'rxjs/BehaviorSubject'.
src/Store.ts(8,25): error TS2307: Cannot find module 'redux'.
src/Store.ts(36,17): error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
src/Store.ts(369,33): error TS2307: Cannot find module 'redux'.
src/Store.ts(370,22): error TS2307: Cannot find module 'redux-observable'.
src/Store.ts(371,28): error TS2307: Cannot find module 'rxjs/Observable'.
src/Store.ts(385,52): error TS7006: Parameter 'action$' implicitly has an 'any' type.
src/Store.ts(385,61): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/Store.ts(387,10): error TS7006: Parameter 'action' implicitly has an 'any' type.
src/Store.ts(393,55): error TS7006: Parameter 'action$' implicitly has an 'any' type.
src/Store.ts(393,64): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/Store.ts(395,14): error TS7006: Parameter 'action' implicitly has an 'any' type.
src/Store.ts(398,56): error TS7006: Parameter 'activity' implicitly has an 'any' type.
src/Store.ts(405,14): error TS7006: Parameter 'id' implicitly has an 'any' type.
src/Store.ts(406,16): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/Store.ts(409,57): error TS7006: Parameter 'action$' implicitly has an 'any' type.
src/Store.ts(411,10): error TS7006: Parameter 'action' implicitly has an 'any' type.
src/Store.ts(413,63): error TS7006: Parameter 'action$' implicitly has an 'any' type.
src/Store.ts(413,72): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/Store.ts(420,10): error TS7006: Parameter 'action' implicitly has an 'any' type.
src/Store.ts(427,51): error TS7006: Parameter 'action$' implicitly has an 'any' type.
src/Store.ts(430,10): error TS7006: Parameter 'action' implicitly has an 'any' type.
src/Store.ts(432,51): error TS7006: Parameter 'action$' implicitly has an 'any' type.
src/Store.ts(432,60): error TS7006: Parameter 'store' implicitly has an 'any' type.
src/Store.ts(434,10): error TS7006: Parameter '_' implicitly has an 'any' type.
src/Store.ts(435,13): error TS7006: Parameter 'state' implicitly has an 'any' type.
src/Store.ts(437,9): error TS7006: Parameter '_' implicitly has an 'any' type.
src/Store.ts(438,14): error TS7006: Parameter 'state' implicitly has an 'any' type.
src/Store.ts(443,14): error TS7006: Parameter '_' implicitly has an 'any' type.
src/Store.ts(444,16): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/Store.ts(449,73): error TS2307: Cannot find module 'redux'.
src/Store.ts(450,52): error TS2307: Cannot find module 'redux-observable'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botframework-webchat@0.10.6 prepublish: `tsc && npm run build-css && webpack --progress --config webpack.production.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the botframework-webchat@0.10.6 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by nwhitmont** [comment]
[NPM v5 Breaking Changes](http://blog.npmjs.org/post/161081169345/v500)

**Breaking Changes**

Existing npm caches will no longer be used: you will have to redownload any cached packages. There is no tool or intention to reuse old caches. (#15666)

npm install ./packages/subdir will now create a symlink instead of a regular installation. file://path/to/tarball.tgz will not change – only directories are symlinked. (#15900)

npm will now scold you if you capitalize its name. seriously it will fight you.

npm will --save by default now. Additionally, package-lock.json will be automatically created unless an npm-shrinkwrap.json exists. (#15666)

Git dependencies support semver through user/repo#semver:^1.2.3 (#15308) (#15666) (@sankethkatta)

Git dependencies with prepare scripts will have their devDependencies installed, and npm install run in their directory before being packed.

npm cache commands have been rewritten and don’t really work anything like they did before. (#15666)

--cache-min and --cache-max have been deprecated. (#15666)

Running npm while offline will no longer insist on retrying network requests. npm will now immediately fall back to cache if possible, or fail. (#15666)

package locks no longer exclude optionalDependencies that failed to build. This means package-lock.json and npm-shrinkwrap.json should now be cross-platform. (#15900)

If you generated your package lock against registry A, and you switch to registry B, npm will now try to install the packages from registry B, instead of A. If you want to use different registries for different packages, use scope-specific registries (npm config set @myscope:registry=https://myownregist.ry/packages/). Different registries for different unscoped packages are not supported anymore.

Shrinkwrap and package-lock no longer warn and exit without saving the lockfile.

Local tarballs can now only be installed if they have a file extensions .tar, .tar.gz, or .tgz.

A new loglevel, notice, has been added and set as default.

One binary to rule them all: ./cli.js has been removed in favor of ./bin/npm-cli.js. In case you were doing something with ./cli.js itself. (#12096) (@watilde)

Stub file removed (#16204) (@watilde)

The “extremely legacy” _token couchToken has been removed. (#12986)

**Comment by watilde** [comment]
I couldn't reproduce the original issue, but I got another issue.
Here is my debug.log: https://gist.github.com/watilde/efa7833a60a68a3bf39cfbc3dbd65d02

**Comment by danmarshall** [comment]
@watilde from your log it appears that the React typings aren't compiling. Can you tell us what version of @types/react and typescript were installed?

**Comment by eanders-MS** [comment]
I think there are two at play problems here:
1. WebChat's dependency criteria are too loose, allowing for minor revisions. This allows breaking changes in. When building from a clean directory, an incompatible version of @types/react/index.d.ts is downloaded (I can repro this locally). A few solutions exist: Use ~ semver operator, allowing only bugfix revisions. Or, use something like NPM ShrinkWrap.
2. In package.json, WebChat's test dependencies are co-mingled with its production dependencies. This pollutes the TypeScript "type space" with type definitions from NodeJS, which conflict with definitions coming from elsewhere. Solution: The test folder should have its own package.json.

**Comment by danmarshall** [comment]
As for 2, all test dependencies should be in devDependencies. I don't think they need a separate package.json, but I could be convincable.

**Comment by eanders-MS** [comment]
The problem is that `npm install` installs devDependencies, resulting in a broken build.

**Comment by danmarshall** [comment]
oic :-) 
Would it help to use the compiler option `--skipLibCheck` :Skip type checking of all declaration files (*.d.ts). ?
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by GeekTrainer** [comment]
If you set the version of TypeScript to 2.3, which is now done in the current version in GitHub, it should resolve this issue.

**Comment by danmarshall** [comment]
Version numbers in package.json must now be an exact match.
