### ISSUE TITLE
Text of clicked buttons not echoed to chat window

### ISSUE THREAD

**Issue by ITM3** [Microsoft/BotFramework-WebChat#502]
When a user clicks a button of a rich card sent by the bot in the webchat window, the text of the button on which the user clicked does not appear in the chat window as if the user would've typed it himself, unlike in messenger for example. 

The problem with this is that if the user scrolls up in the conversation, all he sees is text written by the bot and it makes it hard for him to see what choices he's made (what buttons were clicked), and therefore what bot's answers correspond to what choices.

In Messenger, bot asks the question:
![qmessenger](https://user-images.githubusercontent.com/29228349/27081163-257af90c-500d-11e7-9dfb-7ecb9631f30e.jpg)

In messenger, user clicks on a button, the text is displayed as if he would've typed it:
![amessenger](https://user-images.githubusercontent.com/29228349/27081324-da16d5c0-500d-11e7-9d76-6e9514937cb0.jpg)

In webchat, bot asks the question:
![qwc](https://user-images.githubusercontent.com/29228349/27081232-6c888508-500d-11e7-8fdd-2352b20764d6.jpg)

In webchat, user clicks on a button, the text is not displayed as if he would've typed it:
![awc](https://user-images.githubusercontent.com/29228349/27081358-fa5eddf0-500d-11e7-9c96-adcaedcfc931.jpg)

Thanks for your help!

**Comment by billba** [comment]
This depends on the action type of the button. If it's "imBack" then the text is displayed in the history. If it's "postBack" then it's sent to the bot silently. Not every messaging client supports both, but WebChat does.

This appears to be correct behavior so I'm closing this issue.

**Comment by ITM3** [comment]
Thank you, you are absolutely right, using imBack does exactly what you describe. Cheers!
