### ISSUE TITLE
TextBox ability to pass custom placeholder

### ISSUE THREAD

**Issue by asianswagstorm** [microsoft/BotFramework-WebChat#5098]
### Is your feature request related to a problem?

The placeholder is a static value of TEXT_INPUT_PLACEHOLDER, add new prop messagePlaceholder to BasicSendBox to allow customizable placeholder.

### Describe the suggestion or request in detail

add additional optional prop to BasicSendBox and the placeholder for TextBox will be the new placeholder or the default value.

**Comment by compulim** [comment]
You can do this through customizing our localized strings.

Please refer to this doc for details on overriding the placeholder text, https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/LOCALIZATION.md#overriding-localization-strings.
