### ISSUE TITLE
Get version release about webchat.js using Javascript

### ISSUE THREAD

**Issue by mrk1989** [microsoft/BotFramework-WebChat#5113]
Hi.
I download the file **`webchat.js`** from long time, should be 1 year. 
We noticed that the browsers change some settings or they release new functions and yours probably have to fixed some things or add new functions.

I noticed all release in this [page](https://github.com/microsoft/BotFramework-WebChat/releases).

Probably I have this version **`[v4.15.7]`** but I am not right.

There is a way for get the version of file `**webchat.js**` using Javascript???

This file set the variable `window.webChat` then I ask if I can use the function for have the exact number version about **webchat.js** .

Like `window.webchat.getVersionAboutThisFileBotFrameworkWebchat()` (it is a example)
Best Regards

**Comment by compulim** [comment]
Paste the following code in the F12 console. It will list out all the versions of Web Chat and its dependencies.

`[].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')`

This code snippet is documented in our bug template.
