### ISSUE TITLE
Seeking clarity on the current status and future of Bot Framework Webchat

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#5121]
### I have a question

For years, I've relied on the Bot Framework webchat to deploy chatbots for my customers. Its ease of implementation, flexibility, and exceptional support have always stood out. However, over the past few months, I've found myself pondering the current status of this product.

Expectations were set regarding the support for streaming answers from Large Language Models (LLMs), a highly anticipated enhancement. Yet, there's been a noticeable silence on this front for some time. Additionally, I've observed a rise in the number of reported bugs. Please don't misunderstand my point; I genuinely believe the team behind this product is doing fantastic work. My concern, however, is that it seems to be receiving less attention than it used to. Perhaps priorities have shifted to other initiatives? If that's the case, I believe it would be beneficial for us, the users, to be informed about what we can expect moving forward.

**Comment by compulim** [comment]
We are very actively working on this.

This work requires collaboration across multiple team and products. Multiple parts moving at the same time now:

- Bot Framework Spec: update schema to explain how to stream typing
- Bot SDK: APIs to stream typing
- Chat adapters: receive typing in an efficient manner over Direct Line and other custom protocols
- Web Chat: animate typing
- Other clients: actively working with other product groups to support this feature

Here is a video showing our internal prototype of Web Chat.

https://github.com/microsoft/BotFramework-WebChat/assets/1622400/2550127d-825e-4523-a471-dcab71613005

**Comment by HesselWellema** [comment]
Thanks a lot for the update @compulim ! Really good to hear about all the work going on behind the scenes. This clears up a lot of the fog for us and our customers. Appreciate it!

**Comment by anshumankmr** [comment]
Hi, @compulim  when can we expect this to be released?

**Comment by rliberoff** [comment]
Hi @compulim 

Do you know if the newest version 4.18.0 has this feature?

Thank you.

**Comment by HesselWellema** [comment]
@rliberoff It has. Just upgraded some implementations. Do pay attention to the way you create ad send the typing events from your bot. It is (at least in 4.17) not exactly like documented

**Comment by sohilbhalla** [comment]
Hello,

Is this streaming feature already available in the azure bot direct line? I have a bot integrated with my custom application using direct line web chat but I couldn't get the streaming responses from  the bot to the client. Can you share the sample code to achieve that ?
