### ISSUE TITLE
Autoscroll/notification when new message is received

### ISSUE THREAD

**Issue by rylengel** [Microsoft/BotFramework-WebChat#513]
Hi all,

I've got a request from my customer for if a user is reading some text previously in a conversation and the bot send a new message (or, user clicks a button from higher up in the canvas and bot sends a message replying to that), the chat canvas scrolls down to the new message. Is this meant to be the expected behavior of the autoscroll function in History.tsx? If this is not feasible, I was also thinking about a notification button appearing at the bottom of something like "New Messages" that when clicked would scroll back down to the bottom.

**Comment by danmarshall** [comment]
Thanks @rylengel that would be a good feature, it will go into our planning.

**Comment by rylengel** [comment]
Hey @danmarshall , I've got a similar request from my customer on this issue...some bot responses are very lengthy and require the user to scroll up in the chat canvas to read the beginning. They'd prefer to have the top of a new message displayed in the view rather than having to scroll.  Any advice on where I could tweak this behavior? I'm guessing something with the autoscroll() function in History.tsx?

**Comment by danmarshall** [comment]
@rylengel this may become tricky when there are multiple new messages. Which would be the correct message to scroll to?

**Comment by rylengel** [comment]
@danmarshall the first message in that sequence.

**Comment by danmarshall** [comment]
We don't have the "new messages" functionality yet of course, but yes I think you'd look at https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L74 and adjust the calculation to subtract the height of the last unread messages.

**Comment by ashishevontech** [comment]
@rylengel: the first message in that sequence. did you figure out this?

**Comment by sgellock** [comment]
implemented in v4
