### ISSUE TITLE
Build the project

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/BotFramework-WebChat#5139]
### I have a question

Is there a description or an documentation how to build the project?
I want to debug the project with my own Package.

regards
Andreas

**Comment by dmvtech** [comment]
Does this help?
https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/BUILD_SCRIPTS.md

**Comment by dmvtech** [comment]
Closing due to lack of response.
