### ISSUE TITLE
Simple Webchat for BotFramework - Using Node/Angular

### ISSUE THREAD

**Issue by bhanu2507** [Microsoft/BotFramework-WebChat#516]
https://github.com/bhanu2507/ngwebchat

**Comment by danmarshall** [comment]
@bhanu2507 Thank you for this example!

**Comment by ankurMalhotra** [comment]
How would you handle refreshing of the token?

**Comment by billba** [comment]
@ankurMalhotra WebChat refreshes the token for you automatically

**Comment by ankurMalhotra** [comment]
ok I see. Using the token instead of the secret would still not prevent other developers to copy the bot onto their page right? Recommendations on how to do that?

**Comment by bhanu2507** [comment]
Token is refreshed from DirectLine token generator everytime you load the chat window.
