### ISSUE TITLE
[Fluent UI] [iOS] Should not zoom when focusing on the send box

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#5169]
### Is your feature request related to a problem?

Web Chat is zoomed a bit (like 120%) when the Fluent UI send box is focused.

Will be great if iOS doesn't zoom.

### Describe the suggestion or request in detail

https://github.com/microsoft/BotFramework-WebChat/assets/1622400/042d2409-0366-4344-850e-6436282e5cfb

**Comment by OEvgeny** [comment]
@compulim there are two ways to solve the issue:
- Font size of the textarea should be greater than `16px` on mobile Safari
- The `maximum-scale=1` added to the meta tag, which will also disable pinch to zoom entirely

I can make a PR adjusting the `font-size` of input for Safari only
