### ISSUE TITLE
Enable auto-submit of selected file

### ISSUE THREAD

**Issue by giobb** [microsoft/BotFramework-WebChat#5193]
### I have a question

Hi,

We noticed that when uploading file, we now need to press Enter to submit it. It used to be that after selecting the file, it is uploaded rightaway. Is there a new option setting for this? We started noticing that "dot" in the clip icon after selecting the file, hinting that we need to do press a key to initiate the upload. 

![image](https://github.com/microsoft/BotFramework-WebChat/assets/15137038/268a69db-32a8-40ff-9519-4dcbaa8a850e)

**Comment by compulim** [comment]
This is a new feature in 4.17.0.

To opt-out of this new experience, please set `styleOptions.sendAttachmentOn` to `"attach"`. This will change the behavior and send the attachment when the end-user *attach* the file.

**Comment by giobb** [comment]
Works. Thanks so much @compulim.
