### ISSUE TITLE
How to display data in Table format with Webchat/Directline channel in Python bot

### ISSUE THREAD

**Issue by tanmoy007-ghosh** [microsoft/BotFramework-WebChat#5204]
### I have a question

How to display data in Table format with Webchat/Directline channel in Python bot

**Comment by OEvgeny** [comment]
WebChat uses adaptive cards for markup. Please refer to Adaptive Cards documentation: https://adaptivecards.io/explorer/Table.html

Alternatively, you could use `activityMiddleware` to adjust activities rendering for the specific data format you want to render.

Closing as this is not an issue on WebChat side
