### ISSUE TITLE
How to include citations in the chat response?

### ISSUE THREAD

**Issue by milind045** [microsoft/BotFramework-WebChat#5208]
### I have a question

Is there BotFramework documentation around how to bring these citations into a chat response? Screenshot is from https://microsoft.github.io/BotFramework-WebChat/02.branding-styling-and-customization/h.send-timeout/ but couldn't trace how it's implemented. Any pointers would be greatly appreciated!

![image](https://github.com/microsoft/BotFramework-WebChat/assets/26268728/564c47af-8711-401c-be76-987d05934a44)

**Comment by OEvgeny** [comment]
The screenshot is from our comprehensive tests suite. For citation, you may find helpful these tests located in `__tests__/html/citation.*`. [Here](https://github.com/microsoft/BotFramework-WebChat/blob/d62393e99684e6c6979a91fa0f16e7a919c4f47c/__tests__/html/citation.basic.html) is a basic test. And [here](https://github.com/microsoft/BotFramework-WebChat/blob/84e32c9c4b3ed5fd79c37bffcad6e6e3d8c7df25/__tests__/html/markdownRenderHTML/default.citationModal.html) is a test showing citation modal
