### ISSUE TITLE
Can't build the current build

### ISSUE THREAD

**Issue by photodesignch** [Microsoft/BotFramework-WebChat#522]
Hey guys,

The latest change currently won't make a successful build. "npm run build" command will have exceptions as following ::

> tsc && webpack --config webpack.production.config.js
 
../../src/Chat.tsx(122,9): error TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
  Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.
../../src/Chat.tsx(126,9): error TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! botframework-directlinejs@0.9.7 prepublish: `tsc && webpack --config webpack.production.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the botframework-directlinejs@0.9.7 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by billba** [comment]
Can you please report OS and npm versions

**Comment by photodesignch** [comment]
npm : 4.6.1
OS : Windows 10 ENterprise 1607
OS Build : 14393.1198
Node : 6.10.2

**Comment by danmarshall** [comment]
can't repro on 3 clean installs. Thanks
