### ISSUE TITLE
Unable to install 4.18.0

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#5221]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Development experience

### Which theme pack does this issue affect?

I did not test it on other theme packs

### Please describe the bug

Hi,

I did my prepations in the botcode and am now ready to use webchat to receive streaming answers via the typing event.
How do I install it.

Manual installing the version gives: npm ERR! notarget No matching version found for botframework-webchat@^4.18.0.
Using @latest gives me 4.17.0

any guidance much appreciated

### Do you see any errors in console log?

```js
npm ERR! notarget No matching version found for botframework-webchat@^4.18.0.
```

### How to reproduce the issue?

Try to install 4.18.0 in your development environment

### What do you expect?

webchat version 4.18.0

### What actually happened?

An error and no new version

**Comment by compulim** [comment]
![image](https://github.com/microsoft/BotFramework-WebChat/assets/1622400/63fd74fa-ca46-421e-add0-c0ef64777248)

4.18.0 is not out yet. We are still working on it.

**Comment by rliberoff** [comment]
Hi @compulim 

Do you know if the newest version 4.18.0 has this feature?

Thank you.
