### ISSUE TITLE
Live Streaming | second live stream is rendered on top of the first one,

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#5222]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Edge (latest)

### Which area does this issue affect?

Development experience

### Which theme pack does this issue affect?

I did not test it on other theme packs

### Please describe the bug

If an answer is streamed to the frontend, the first answer is rendered in chunks correctly. When  a second answer is send to webchat, it is rendered on top of the first one.

### Do you see any errors in console log?

```js
No
```

### How to reproduce the issue?

Use sample a.minimizable-web-chat
Update to latest version: npm install botframework-webchat@main

1. Send answer 1 to the webchat

```
{"channelData":{"streamSequence":1,"streamType":"streaming"},"type":"typing","text":"Typing an answer .."}
{"channelData":{"streamId":"c053d730-2fb9-11ef-9f75-136888712e32","streamType":"final"},"text":"Hello to you!","type":"message"}

```

2. Send answer 2 to the webchat

```
{"channelData":{"streamSequence":1,"streamType":"streaming"},"type":"typing","text":"Typing an answer .."}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":2,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":3,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":4,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a wonderful"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":5,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a wonderful day"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":6,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a wonderful day!"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamType":"final"},"text":"Farewell to you, have a wonderful day!","type":"message"}

```

### What do you expect?

I would expect the second answer to be rendered below the question is answers

### What actually happened?

It is rendered above the first answer

### Do you have any screenshots or recordings to repro the issue?

![image](https://github.com/microsoft/BotFramework-WebChat/assets/23032884/b075890a-864e-48a3-9cb4-285c5a763d76)

### Additional context

The events send to webchat from my bot. 

First answer stream

```
{"channelData":{"streamSequence":1,"streamType":"streaming"},"type":"typing","text":"Typing an answer .."}
{"channelData":{"streamId":"c053d730-2fb9-11ef-9f75-136888712e32","streamType":"final"},"text":"Hello to you!","type":"message"}
```

Second answer stream

```
{"channelData":{"streamSequence":1,"streamType":"streaming"},"type":"typing","text":"Typing an answer .."}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":2,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":3,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":4,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a wonderful"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":5,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a wonderful day"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamSequence":6,"streamType":"streaming"},"type":"typing","text":"Farewell to you, have a wonderful day!"}
{"channelData":{"streamId":"d2e36d70-2fb9-11ef-9f75-136888712e32","streamType":"final"},"text":"Farewell to you, have a wonderful day!","type":"message"}
```

**Comment by OEvgeny** [comment]
Adding timestamp to activities may help for now. Full conversation transcript would be helpful, so we could repro this with our tests suite.

**Comment by HesselWellema** [comment]
I will add timestamps and aee if that helps
Do you have an endpoint I can use to see make sure it is not my own botcode?

**Comment by OEvgeny** [comment]
We mostly use our tests to continuously check things. You can find related by searching for [streamId](https://github.com/search?q=repo%3Amicrosoft%2FBotFramework-WebChat%20streamId&type=code)

And here is an example bot from William: https://github.com/compulim/experiment-webchat-streamingbot

**Comment by HesselWellema** [comment]
Tx mate. Will keep you posted.

**Comment by HesselWellema** [comment]
I added timestamps. Still not ok.


Bot
```
{"type":"typing","id":"G9zqRneUmCX4MQ1NIxlUro-eu|7JrmOwAwbnH","timestamp":"2024-06-23T10:51:39.9730338Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"G9zqRneUmCX4MQ1NIxlUro-eu"},"locale":"nl-NL","text":"Typing an answer ..","channelData":{"streamSequence":1,"streamType":"streaming","timestamp":"2024-06-23T10:51:39.835Z"},"replyToId":"G9zqRneUmCX4MQ1NIxlUro-eu|0000005"}

```
User question: How much is 2 * 21. Only give the answer```

Bot event 1

```
{"type":"typing","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|ISt7TasNiXb","timestamp":"2024-06-23T10:53:39.162762Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"Typing an answer ..","channelData":{"streamSequence":1,"streamType":"streaming","timestamp":"2024-06-23T10:53:39.026Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000005"}
```

Bot event 2
```
{"type":"message","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000006","timestamp":"2024-06-23T10:53:39.3334534Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"42","channelData":{"streamId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|ISt7TasNiXb","streamType":"final","timestamp":"2024-06-23T10:53:39.202Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000005"}
```

Bot evenr 3
```
{"type":"message","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000007","timestamp":"2024-06-23T10:53:39.4750714Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"Stel gerust een vervolgvraag of klik op het huisje om opnieuw een dossier te kiezen.","inputHint":"acceptingInput","replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000005"}
```

User question:  What time it it? Answer in English 

Bot event 1
```
{"type":"typing","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|EoVg5w2gDnM","timestamp":"2024-06-23T10:56:38.6987624Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"Typing an answer ..","channelData":{"streamSequence":1,"streamType":"streaming","timestamp":"2024-06-23T10:56:38.584Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
```

Bot event 2
```
{"type":"typing","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|3zMZKfnMxvj","timestamp":"2024-06-23T10:56:39.5194385Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"It is currently 12","channelData":{"streamId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|EoVg5w2gDnM","streamSequence":2,"streamType":"streaming","timestamp":"2024-06-23T10:56:39.392Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
 ```
 
 Bot event 3
```
{"type":"typing","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|F6XxTvLGTnU","timestamp":"2024-06-23T10:56:39.6914206Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"It is currently 12:","channelData":{"streamId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|EoVg5w2gDnM","streamSequence":3,"streamType":"streaming","timestamp":"2024-06-23T10:56:39.527Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
```

 Bot event 4
```
{"type":"typing","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|AicK1PDGL2X","timestamp":"2024-06-23T10:56:39.874014Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"It is currently 12:39","channelData":{"streamId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|EoVg5w2gDnM","streamSequence":4,"streamType":"streaming","timestamp":"2024-06-23T10:56:39.717Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
```

Bot event 5
```
{"type":"typing","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|LhOUASFp8On","timestamp":"2024-06-23T10:56:40.0787362Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"It is currently 12:39.","channelData":{"streamId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|EoVg5w2gDnM","streamSequence":5,"streamType":"streaming","timestamp":"2024-06-23T10:56:39.926Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
```

Bot event 6
```
{"type":"message","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000009","timestamp":"2024-06-23T10:56:40.2810958Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"It is currently 12:39.","channelData":{"streamId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|EoVg5w2gDnM","streamType":"final","timestamp":"2024-06-23T10:56:40.106Z"},"replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
```

Bot event 7
```
{"type":"message","id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000010","timestamp":"2024-06-23T10:56:40.5052304Z","channelId":"directline","from":{"id":"bot4aamelegalauthenticatedstreaming","name":"Bot","role":"bot"},"conversation":{"id":"5hzRJ5kIZ3rLyJWEA1K7N2-eu"},"locale":"nl-NL","text":"Stel gerust een vervolgvraag of klik op het huisje om opnieuw een dossier te kiezen.","inputHint":"acceptingInput","replyToId":"5hzRJ5kIZ3rLyJWEA1K7N2-eu|0000008"}
```

![image](https://github.com/microsoft/BotFramework-WebChat/assets/23032884/1fdfd401-5b9a-4170-bd8b-50543ee3ae94)

**Comment by HesselWellema** [comment]
I also checked the [botcode](https://github.com/compulim/experiment-webchat-streamingbot/blob/main/packages/bot/src/bot.js) you  shared  and implemented it with no good result. There seems to be a mismatch between the botcode and the pullrequest wth the requirement of the events mentioned in the [pullrequest](https://github.com/microsoft/BotFramework-WebChat/pull/5141) 
Differences i noticed 
No streamType: 'streaming' in the botcode
No streamType: 'final'  in the botcode
The botcode is jus sending typing events
Also in the botcode there is this: 'willContinue' in context.adapter && context.adapter.willContinue(context); What is the purpose and do I also need it in my implementation

I would really appreciate your guidance because I feel we are almost there.

**Comment by OEvgeny** [comment]
@HesselWellema could you try the following:
- First typing activity, no `streamId`
- Every typing/message activity else, with `streamId` of the `firstActivity.id`

You should be able to start a completely new stream the same way: by sending a new typing activity with a fresh `id`. Looks like you're doing something similar, but maybe subsequent activity ids confuse WebChat.

I have a note to look [here](https://github.com/microsoft/BotFramework-WebChat/blob/main/packages/core/src/reducers/createActivitiesReducer.ts#L98) to debug this, but haven't got time yet due to other workstreams

**Comment by HesselWellema** [comment]
Did what you suggested but second answer is still on top (so before) the first answer. Reproducible on the [a.minimizable-web-chat ](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/06.recomposing-ui/a.minimizable-web-chat)sample.

please: If you have a sample of events that do render in the right order, I am interested. I should be able to create those in my bot code.

### My latest results based on two questions:

## Answer 1
the requests I send via await context.sendActivity(request);
```
{"channelData":{"streamSequence":1},"type":"typing","text":"Typing an answer .."}
{"channelData":{"streamId":"F3YgYHw44MhAEJTEDrltry-eu|DvzgnR1yzXB","streamSequence":2},"type":"typing","text":"42"}
```
typing events received in webchat
```
{
    "type": "typing",
    "id": "F3YgYHw44MhAEJTEDrltry-eu|DvzgnR1yzXB",
    "timestamp": "2024-06-25T07:18:50.5493476Z",
    "channelId": "directline",
    "from": {
        "id": "bot4aamelegalauthenticatedstreaming",
        "name": "Bot",
        "role": "bot"
    },
    "conversation": {
        "id": "F3YgYHw44MhAEJTEDrltry-eu"
    },
    "locale": "nl-nl",
    "text": "Typing an answer ..",
    "channelData": {
        "streamSequence": 1
    },
    "replyToId": "F3YgYHw44MhAEJTEDrltry-eu|0000009"
}

{
    "type": "typing",
    "id": "F3YgYHw44MhAEJTEDrltry-eu|BryxZrF6dPf",
    "timestamp": "2024-06-25T07:18:50.6805386Z",
    "channelId": "directline",
    "from": {
        "id": "bot4aamelegalauthenticatedstreaming",
        "name": "Bot",
        "role": "bot"
    },
    "conversation": {
        "id": "F3YgYHw44MhAEJTEDrltry-eu"
    },
    "locale": "nl-nl",
    "text": "42",
    "channelData": {
        "streamId": "F3YgYHw44MhAEJTEDrltry-eu|DvzgnR1yzXB",
        "streamSequence": 2
    },
    "replyToId": "F3YgYHw44MhAEJTEDrltry-eu|0000009"
}
```
## Answer 2 (which is rendered before answer 1

the requests I send via await context.sendActivity(request);
```
{"channelData":{"streamSequence":1},"type":"typing","text":"Typing an answer .."}
{"channelData":{"streamId":"F3YgYHw44MhAEJTEDrltry-eu|8X7OePylskP","streamSequence":2},"type":"typing","text":"1999"}
```
typing event received in webchat
```
{
    "type": "typing",
    "id": "F3YgYHw44MhAEJTEDrltry-eu|8X7OePylskP",
    "timestamp": "2024-06-25T07:21:24.0934264Z",
    "channelId": "directline",
    "from": {
        "id": "bot4aamelegalauthenticatedstreaming",
        "name": "Bot",
        "role": "bot"
    },
    "conversation": {
        "id": "F3YgYHw44MhAEJTEDrltry-eu"
    },
    "locale": "nl-nl",
    "text": "Typing an answer ..",
    "channelData": {
        "streamSequence": 1
    },
    "replyToId": "F3YgYHw44MhAEJTEDrltry-eu|0000017"
}

{
    "type": "typing",
    "id": "F3YgYHw44MhAEJTEDrltry-eu|CAyqP0Owhat",
    "timestamp": "2024-06-25T07:21:24.24051Z",
    "channelId": "directline",
    "from": {
        "id": "bot4aamelegalauthenticatedstreaming",
        "name": "Bot",
        "role": "bot"
    },
    "conversation": {
        "id": "F3YgYHw44MhAEJTEDrltry-eu"
    },
    "locale": "nl-nl",
    "text": "1999",
    "channelData": {
        "streamId": "F3YgYHw44MhAEJTEDrltry-eu|8X7OePylskP",
        "streamSequence": 2
    },
    "replyToId": "F3YgYHw44MhAEJTEDrltry-eu|0000017"
}
```

**Comment by HesselWellema** [comment]
According to ChatGPT:

The issue arises because the activities are sorted based on the sequenceId in the patchActivity and upsertActivityWithSort functions. The sequenceId is generated or assigned based on the streamSequence, timestamp, and the sequence of activities in the array.

Here is why the second message stream is shown before the first one:

Timestamp Difference: The second message stream (Answer 2) has timestamps that are slightly later than the first message stream (Answer 1). However, the timestamps alone do not determine the order since the sequence ID generation also plays a crucial role.

Stream Sequence Handling:

For Answer 1, the streamSequence values are 1 and 2.
For Answer 2, the streamSequence values are also 1 and 2.
Patch Activity Logic:

If the message does not have a sequence ID, the code assigns one using a combination of streamSequence, timestamp, and the position in the array.
Since streamSequence is present, the patchActivity function would try to place them in the order based on the streamSequence.
Insertion Order:

upsertActivityWithSort function uses sequenceId for insertion order. When activities are inserted, their sequenceId is compared and sorted.
If activities have the same streamSequence values but different timestamps, the logic might place them incorrectly if the sequenceId calculation is influenced by the current state of the array.

**Comment by HesselWellema** [comment]
A third answer is rendered between answer 1 and 2.
A fourth answer is rendered btween anders 3 and 4
Something is wrong with the ordering.

**Comment by LuisM000** [comment]
I'm experiencing the same issue. It seems to work for me if I send the messages in the following way:

**First chunk:**
```
{
  "channelData": {
    "streamSequence": 1,  
    "streamType": "streaming"
  },
  "type": "message"
}
```

**Subsequent chunks:**
```
{
  "channelData": {
    "streamId": "<activity ID of the first chunk>",
    "streamSequence": 2,  // Must be a monotonically increasing positive integer
    "streamType": "streaming"
  },
  "type": "typing"
}
```

**Final chunk:**
```
{
  "channelData": {
    "streamId": "<activity ID of the first chunk>",
    "streamType": "final"
  },
  "text": "A quick brown fox jumped over the lazy dogs.",
  "type": "typing"
}
```

Basically, compared to the PR [https://github.com/microsoft/BotFramework-WebChat/pull/5141](https://github.com/microsoft/BotFramework-WebChat/pull/5141), I am changing the initial message type to "message" and the final message type to "typing." With these changes, it is working for me.

**Comment by HesselWellema** [comment]
@LuisM000 tx. will  give this a try.

**Comment by HesselWellema** [comment]
@LuisM000 small addition. the typing events where flooding my transscriptlogger. I decided to ignore them them in the transcript logger and use type 'messsage' as final event. That also works.

**Comment by HesselWellema** [comment]
I will close the issue because my problem is solved.

**Comment by rliberoff** [comment]
Hi @compulim 

Do you know if the newest version 4.18.0 has this feature?

Thank you.
