### ISSUE TITLE
Live Streaming Response: timeout after 15 seconds

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#5247]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Latest production

### Which distribution are you using Web Chat from?

NPM

### Which hosting environment does this issue primarily affect?

Web apps

### Which area does this issue affect?

Protocol or service

### Which theme pack does this issue affect?

I did not test it on other theme packs

### Please describe the bug

After 15 seconds, the console shows a 502 bad gateway message.
The response in the netwerk tab is

{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot timed out"
  },
  "httpStatusCode": 504
}

This is an old issue but is becoming more annoying since the LLM answers tend to take a long time to arrive.

The functionality of the chatbot is not affected. The message is however annoying.

### Do you see any errors in console log?

```js
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot timed out"
  },
  "httpStatusCode": 504
}
```

### How to reproduce the issue?

It is reproducable with the minimizable webchat sample and a chatbot that is streaming answer.
Make sure you use one of the latest versions of webchat.
Every answer that takes more than 15 seconds to stream will show the error in the console.

### What do you expect?

I expect no error in console

### What actually happened?

An eror in the console

**Comment by compulim** [comment]
On the bot side, you should use [proactive messaging](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=javascript) to send the message.

Proactive messaging literally, tells Web Chat that the bot has received the message and the processing may take longer than 5 seconds.

Without proactive messaging, Web Chat did not know the bot has received the message and thus, we will show a timeout after 15-20 seconds.

**Comment by HesselWellema** [comment]
tx. I will implement  it like  you suggesed

**Comment by compulim** [comment]
Thank you @HesselWellema, you are always helpful.

FWIW, this is [the diagram of interactions](https://github.com/microsoft/BotFramework-WebChat/blob/main/docs/media/direct-line-sequence-diagram.png) between bot, service, and Web Chat.

If proactive is not used, it would block the few arrows I indicated below until 15-20 seconds later. 

Web Chat won't know if the bot received the message sent from the user or not. Thus, Web Chat would say "failed to send."

![image](https://github.com/user-attachments/assets/af96ae43-3fa6-42dc-9f95-285341b5cd84)

TBH, IMO, it would be helpful if ABS would return HTTP 4xx for the purple arrow on lower-right, if the bot respond too slow. It would prompt more bot developers to use proactive messaging and build a better box experience.
