### ISSUE TITLE
Web Chat Hosted Samples Maintainance

### ISSUE THREAD

**Issue by mndxt007** [microsoft/BotFramework-WebChat#5267]
### I have a question

I was wondering if someone can help fix the hosted samples of Web chat [BotFramework-WebChat/samples at 2dbeed3ab97709e89e94911191eb16938a747028 · microsoft/BotFramework-WebChat (github.com)](https://github.com/microsoft/BotFramework-WebChat/tree/2dbeed3ab97709e89e94911191eb16938a747028/samples#samples-list).
 
These great samples which I use to explain customers about how Bot in general works and the DL ASE. Unfortunately, it seems like it is no longer maintained. I'm specifically looking for 2 samples below:
 
[Web Chat: Full-featured bundle (microsoft.github.io)](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/) (seems like Bot secret expired)
[BotFramework-WebChat/samples/01.getting-started/i.protocol-direct-line-app-service-extension at main · microsoft/BotFramework-WebChat (github.com)](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/01.getting-started/i.protocol-direct-line-app-service-extension) - DNS failure

**Comment by stevkan** [comment]
@mndxt007 - Thank you for bringing this to our attention. Unfortunately, sometimes there is a delay between maintenance updates to the code and updates to the samples/docs. Thank you for your patience while we work to update these samples as soon as is possible.

@OEvgeny - Bringing to your attention.

**Comment by mndxt007** [comment]
@compulim It still seem to fail? Is it yet be merged?


[Web Chat: Full-featured bundle (microsoft.github.io)](https://microsoft.github.io/BotFramework-WebChat/01.getting-started/a.full-bundle/) (seems like Bot secret expired)
[BotFramework-WebChat/samples/01.getting-started/i.protocol-direct-line-app-service-extension at main · microsoft/BotFramework-WebChat (github.com)](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/01.getting-started/i.protocol-direct-line-app-service-extension) - DNS failure

**Comment by compulim** [comment]
Yes, still failing. The GH Pages action was not running for some time.

Now I am fixing some complex samples by upgrading it from `create-react-app` to `react-scripts` in #5291. But it will take some time...
