### ISSUE TITLE
When 4.19.0?

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#5271]
### I have a question

Hi team

I noticed the mention of 4.19.0 en the version notes about  informative messages. Straightforward implementation. Exactly what I need!

I modified some botcode and did an npm i @latest.

no 4.19 yet ;-(

What is you best guess wrt release week?

**Comment by stevkan** [comment]
@OEvgeny - Is there an ETA on when 4.19.0 might be published?

**Comment by compulim** [comment]
It's always difficult to discuss schedule. It should be around mid-September and unlikely after end of September.

**Comment by HesselWellema** [comment]
I will just wait. Development build also gives "Error: No renderer for activity of type "informative"
