### ISSUE TITLE
Webchat not working properly inside a shadow DOM

### ISSUE THREAD

**Issue by vasnakos** [microsoft/BotFramework-WebChat#5315]
### Is it an issue related to Adaptive Cards?

No

### Is this an accessibility issue?

No

### What version of Web Chat are you using?

Development build

### Which distribution are you using Web Chat from?

Bundle (webchat.js)

### Which hosting environment does this issue primarily affect?

Web apps

### Which browsers and platforms do the issue happened?

Browser: Chrome (latest), Browser: Firefox (latest)

### Which area does this issue affect?

Send box

### Which theme pack does this issue affect?

I did not test it on other theme packs

### What is the public URL for the website?

-

### Please describe the bug

As per the #5196 webchat now supports styling inside shadow DOMs. So, I tried to add a webchat inside a shadow DOM via the following code:
```
<body>
    <div id="webchat-host"></div>

    <script>
      const hostElement = document.getElementById('webchat-host');

      // Create a Shadow DOM
      const shadowRoot = hostElement.attachShadow({ mode: 'open' });

      // Create a container to hold the WebChat component inside the shadow DOM
      const webChatContainer = document.createElement('div');
      webChatContainer.id = 'webchat-container';
      webChatContainer.style.height = '500px'; // Define a height for the container
      webChatContainer.style.width = '100%'; // Define a width for the container

      // Attach the container to the Shadow DOM
      shadowRoot.appendChild(webChatContainer);

      // Initialize WebChat after the external script has loaded
      const initWebChat = () => {
        // Create DirectLine instance
        const directLine = window.WebChat.createDirectLine({
          token: 'YOUR_DIRECT_LINE_TOKEN'
        });

        // Render WebChat
        window.WebChat.renderWebChat(
          {
            directLine,
            styleOptions: {
              stylesRoot: shadowRoot,
            },
            serID: 'YOUR_USER_ID',
            username: 'User',
            locale: 'en-US',
          },
          webChatContainer // Render WebChat inside the container in Shadow DOM
        );

        // Scroll to the bottom of WebChat
        webChatContainer.querySelector('.webchat__basic-transcript').scrollTop =
          webChatContainer.scrollHeight;

        console.log('WebChat has been rendered inside Shadow DOM.');
      };

      // Check if WebChat script is already loaded
      if (window.WebChat) {
        initWebChat();
      } else {
        // Wait for WebChat to load, then initialize it
        const script = document.createElement('script');
        script.src =
          'YOUR_EXTERNAL_SCRIPT';
        script.onload = initWebChat;
        document.body.appendChild(script);
      }
    </script>
  </body>
```
and while the styles work perfectly, I face a different issue: click events on send box doesn't work. For instance I write something on the sendbox, click on the arrow (or press enter) but nothing happens. Same goes for the attachments icon - doesn't work.

BUT, if the second parameter of the `renderWebChat` method instead of `webChatContainer` is `shadowRoot` (render the webchat directly in the shadow root instead of a specific div inside the shadow root) then click events work as they should, but I miss any style I added based on the webChatContainer.

Seems like BasicSendBox Component doesn't hear for click events.

### Do you see any errors in console log?

```js
No errors.
```

### How to reproduce the issue?

1. Install latest development build (I did that locally)
2. Create an html file where it loads the latest build from above, and then create a shadow DOM with a div inside and try to render Webchat inside that div 
3. Type anything in the send box and try to send it - doesn't work

### What do you expect?

I would expect to be able to render webchat inside specific container which lives inside a shadow DOM

### What actually happened?

Click events on send box doesn't work (Cannot send messages, cannot attach files)

**Comment by OEvgeny** [comment]
Something to do with built-in React not handling events in shadow roots. As a workaround you could try including more modern version of React into the page via script tag. The 16.14.x and above should work. Recommend is v18.x.

**Comment by vasnakos** [comment]
What I actually did is to add something like:
```
const reactScript = document.createElement("script");
reactScript.src = "https://unpkg.com/react@18/umd/react.production.min.js";
shadowRoot.appendChild(reactScript);

const reactDomScript = document.createElement("script");
reactDomScript.src = "https://unpkg.com/react-dom@18/umd/react-dom.production.min.js";
shadowRoot.appendChild(reactDomScript);
```
and indeed it seems to be working. 
Thanks a lot 🎉

**Comment by vasnakos** [comment]
@OEvgeny thank you for your suggestion. It helped me a lot!

As I cannot include the whole react library to my client's project I ended up with just retargeting the events that may occur inside the shadowDOM. 
[Here's a link to a gist](https://gist.github.com/vasnakos/91aaccc88765d2346765b928e7b82559) that may help other that face the same issue.
