### ISSUE TITLE
When can we have the speech feature available in IFRAME

### ISSUE THREAD

**Issue by vivekcek** [Microsoft/BotFramework-WebChat#533]
Hi,

Now i am using Web chat with IFRAME. But i don't have speech feature available now.
When can i expect this. I am not planning to download web chat code and include in my site.

**Comment by GeekTrainer** [comment]
The current plan is to get that implemented soon.

**Comment by sgellock** [comment]
We only support this scenario using the npm version of WebChat.  The embedded IFRAME version is not supported at this time as it required a speech api key for the speech subscription to work, which is outside of the abilities of the simple embed scenario.
