### ISSUE TITLE
Cannot access the bot user data on backchannel post activity

### ISSUE THREAD

**Issue by DL-LiveTiles** [Microsoft/BotFramework-WebChat#536]
Hello,
We want to post a ConversationUpdate activity using the backchannel when the WebChat load.
The ConversationUpdate is triggered correctly using the code below, but the from.id received by the bot is different to what is sent and therefore the user bot data store is different.

I tried setting the user and from properties on both the bot connection and post method, but neither is working.

How can we access the same bot user data store on the ConversationUpdate event and BotChat App?
Note: The bot user data store available on ConversationUpdate and messages is the same for all other channels we have tried, so this seems like a WebChat issue.

`var user = {
    id: userId,
    name: "You"
};

var bot = {
    id: environment.botId,
    name: "Bot"
};

var botConnection = new BotChat.DirectLine({
    secret: environment.directLineSecret,
    user: user
});

console.log("Trigger conversation update");
botConnection
    .postActivity({ type: "ConversationUpdate", user: user, from: user })
    .subscribe(id => console.log("Conversation updated"));

console.log("Intialize BotChat App");
BotChat.App({
    botConnection: botConnection,
    bot: bot,
    user: user,
    resize: 'detect'
}, document.getElementById("BotChatGoesHere"));`

Thank you,

Douw

**Comment by billba** [comment]
ConversationUpdate is a synthetic activity sent by the bot framework connector. You shouldn't send it from the client. I would suggest sending an Event activity instead. That's how Backchannel works.

________________________________

**Comment by DL-LiveTiles** [comment]
The event activity does have access to the user bot data and I was able to trigger a "fake" conversation update using below:

WebChat:
`botConnection
    .postActivity({ type: "event", from: user, name: "ConversationUpdate", value: "" })
    .subscribe(id => console.log("Conversation updated"));` 

Bot 
`if (context.Activity.Type == ActivityTypes.Event)
            {
                IEventActivity eventActivity = context.Activity.AsEventActivity();
                if (eventActivity.Name == "ConversationUpdate")
...`

**Comment by billba** [comment]
Yup, that's the way we designed it. Glad it's working for you.

**Comment by tjoudeh** [comment]
Hello @billba, I wanted to check with you how I implemented this to make sure I'm doing it correctly, in my case, the webchat is receiving a query string param which contains a UUID for a user, then I need the bot to greet the user by name (Bot initiates the greeting), so I need to load the user profile from a certain repository to get firstname/lastname based on the UUID received. 
I ended up doing the below, my concern if is it ok to send `connector.Conversations.ReplyToActivityAsync(reply) ` when the activity type is an `Event`?

Here is the code I used in the Web Chat JavaScript:

```
function initBotChat(token) {

            var userId = getParameterByName('userid');

            if (!userId) {
                userId = generateId();
            }
            var userName = getParameterByName('username');
  
            if (!userName) {
                userName = 'You';
            }
            var user = {
                id: userId,
                name: userName
            };

            var bot = {
                id: "botid"
            };

            var botConnection = new BotChat.DirectLine({
                token: token,
                webSocket: false
            });

            postUserIdEventMessage(botConnection,user);

            BotChat.App({
                botConnection: botConnection,
                user: user,
                bot: bot,
                resize: 'detect',
                locale: 'de-DE',
                speechOptions: speechOptions,
            }, document.getElementById("bot"));

        }

        function postUserIdEventMessage(botConnection,user) {
            botConnection
                .postActivity({
                    from: user,
                    name: 'setUserIdEvent',
                    type: 'event',
                    value: ''
                })
                .subscribe(function (id) {
                    console.log('"triggerPostUserIdEvent" sent');
                });
        };
```

And here is the code I used in the `MessagesController` to send the Welcome message from the bot to user upon loading the Web Chat page:
```
private async Task HandleSystemMessage(Activity message)
        {
            await TelemetryLogger.TrackActivity(message);

            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {

            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }
            else if (message.Type == ActivityTypes.Event)
            {
                var eventActivity = message.AsEventActivity();

                if (eventActivity.Name == "setUserIdEvent")
                {
                    ConnectorClient connector = new ConnectorClient(new Uri(message.ServiceUrl));

                    var userId = message.From.Id;

                    TelemetryLogger.LogTraceTelemetry($"TriggerCustomEvent::From Controller::message.From.Id: {userId} message.Recipient.Id: {message.Recipient.Id}", SeverityLevel.Warning);

                    var userProfile = await GetUserProfileAsync(userId);

                    await UserProfileHelper.StoreUserProfileAsync(message, userProfile);

                    var welcomeMessages = GreetingHelper.FormatWelcomeMessages(userProfile);

                    foreach (var welcomeMessage in welcomeMessages)
                    {
                        var reply = message.CreateReply(welcomeMessage);

                        await connector.Conversations.ReplyToActivityAsync(reply);

                    }

                }
            }
        }
```

Let me know if you have any comments on this approach, please?

**Comment by billba** [comment]
First rule of programming: if it works, then it works.

I'm not very familiar with the C# SDK but from what I can tell this is the pattern I was espousing. My main feedback is that I'd use a `switch` statement instead of all those `if`/`else`s :-)

**Comment by UsamaAslam** [comment]
i am using below code to pass the value to bot ActivityTypes.ConversationUpdate but i am not able to get any value in bot under ActivityTypes.ConversationUpdate. Can you help me ? Don't able to pass the value.
Full address is local variable on html page that have value like in this i-e if i want to pass London to bot and in conversation start bot display London .

```
<script type="text/javascript">
        // for location of user....
        var fulladdress ='landon';
 
 alert(fulladdress);
         // for Bot  .......
        const speechOptions = {
            speechRecognizer: new CognitiveServices.SpeechRecognizer({ subscriptionKey: 'key' }),
            speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
                gender: CognitiveServices.SynthesisGender.Female,
                subscriptionKey: 'key',
                voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
            })
        };
      
        var model = {
            "userId": '_' + Math.random().toString(36).substr(2, 9),
            "userName": "User Name",
            "botId": "Chatbot Main Tree",
            "botIconUrl": "//bot-framework.azureedge.net/bot-icons-v1/bot-framework-default-8.png",
            "botName": "Chatbot Main Tree",
            "secret": "Direct Line Secret",
            "iconUrl": "//bot-framework.azureedge.net/bot-icons-v1/bot-framework-default-8.png",
            "directLineUrl": "https://webchat.botframework.com/v3/directline",
            "webSocketEnabled": "True"
        };

        var dl = new BotChat.DirectLine(
            {
                  secret: model.secret,
                  token: model.token,
                  domain: model.directLineUrl,
                  webSocket: true,
                  sendTyping: true
            });

        BotChat.App({
            botConnection: {
                botConnection: dl,
                postActivity: activity => dl.postActivity({
                    from: { id: 'userid', name: 'username' },
                    name: 'postLocationData',
                    text: 'I said my location is ' + fulladdress,
                    type: 'ConversationUpdate',
                    value: fulladdress,
                    channelData: fulladdress
                })
                    .subscribe(function (id) {
                        console.log(fulladdress);
                    })
            },
            sendTyping: true,
            user: { id: model.userId, name: model.userName },
            bot: { id: model.botId, name: model.botName },
            speechOptions: speechOptions,
            resize: 'window',
        }, document.getElementById("BotChatElement"));
</script>
```
