### ISSUE TITLE
Question about purpose Fluent theme

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-WebChat#5367]
### I have a question

Hi team,

just a small question.
I was in the middle of implementing support of drag and drop for file attachments in the sendbox.
Noticed you have something in the works in the Fluent Theme project.

What exactly is the goal of this Fluent Theme project?  You mention 'a native copilot experience'. Does that mean it is not just about look and feel?

**Comment by OEvgeny** [comment]
Currently it is mostly look and feel with some UX adjustments, and an example of how fully custom themes can be made possible for Web Chat. Please note that while the status of the fluent package is still experimental, we aim to provide the support as it is a part of Web Chat repo. The package is designed to be handy in any project which is using Fluent UI, or similar design system.
