### ISSUE TITLE
How can i make the Webchat Responsive

### ISSUE THREAD

**Issue by akasranjan005** [Microsoft/BotFramework-WebChat#537]
I have embedded the WebChat on my website, i want to make it responsive as the website requirements. Can i use bootstrap feature in order to achieve this or i will have to rewrite the css of webchat?

**Comment by billba** [comment]
Here is some information on WebChat responsiveness: https://github.com/Microsoft/BotFramework-WebChat#card-sizes--responsiveness

**Comment by akasranjan005** [comment]
But it does not make it mobile friendly, anything for making it mobile responsive just like bootstrap does by resizing the div based on the screen size?

**Comment by billba** [comment]
@danmarshall can you provide some guidance?

**Comment by billba** [comment]
A quick note: if you make the WebChat full screen it will resize with the screen size. Otherwise you need to work harder.

**Comment by akasranjan005** [comment]
i got the point of working harder :P , full screen also doesnt help as the carousel size and text size also needs to be increased as per device screen, 
Anyways thanks for giving us this platform.

**Comment by danmarshall** [comment]
Hi @akasranjan005, can we look at your issues one by one and just address each issue specifically? Also, is your WebChat in an iframe or directly in a div on your page?

**Comment by akasranjan005** [comment]
I am using it inside a div and not an iframe.
So, i need to write css for every component, like carousel, textbox, fontsize etc etc for various screen size

**Comment by danmarshall** [comment]
@akasranjan005 - perhaps you should be using a [mobile viewport meta tag](http://www.javascriptkit.com/dhtmltutors/cssmediaqueries3.shtml) in your page:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```
For an example, see https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/fullwindow/index.html#L20

**Comment by akasranjan005** [comment]
Thank you soo much 👍 
One more query, can i give a cross(X) button on the header of my chat window to minimize it (kind of).

:)
