### ISSUE TITLE
Outlook is not opening in BackChannel

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotFramework-WebChat#538]
I have deployed a bot using backchannel. I have written the following code for a bot. Email opens in Bot Emulator. but throws an error when the bot is working on the website.
Is there any way to solve this ?

            private async Task ConnectWithPractice(IDialogContext context)
        {
            List<CardAction> buttons = new List<CardAction>();
            CardAction button1 = new CardAction()
            {
                Value = "Connect with Call",
                Type = "imBack",
                Title = "Connect with Call"
            };
            CardAction button2 = new CardAction()
            {
                Value = "Connect with Email",
                Type = "imBack",
                Title = "Connect with Email"
            };
            buttons.Add(button1);
            buttons.Add(button2);
            var card = new HeroCard()
            {
                Title = "How would you like to connect ?",
                Buttons = buttons
            };
            var result=card.ToAttachment();
            var message = context.MakeMessage();
            message.Attachments.Add(result);
            await context.PostAsync(message);
            context.Wait(this.ConnectMail);
        }

        //opens outlook
        public async virtual Task ConnectMail(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
                var message = await result;
                if (message.Text.Equals("Connect with Email"))
                {
                    Outlook.Application oApp = new Outlook.Application();
                    Outlook._MailItem oMailItem = (Outlook._MailItem)oApp.CreateItem(Outlook.OlItemType.olMailItem);
                    oMailItem.To = "abc@xyz.com";
                    oMailItem.Subject = "Test";
                    oMailItem.Display(true);
                }
                else if(message.Text.Equals("Connect with Call"))
                {
                    List<CardAction> buttons = new List<CardAction>();
                    CardAction button1 = new CardAction()
                    {
                        Value = "tel:" + phone,
                        Type = "call",
                        Title = "Call: " + phone
                    };
                    buttons.Add(button1);
                    var card = new HeroCard()
                    {
                        Buttons = buttons
                    };
                    var temp = card.ToAttachment();
                    var res = context.MakeMessage();
                    res.Attachments.Add(temp);
                    await context.PostAsync(res);
                }
                context.Done(new object());
        }

**Comment by billba** [comment]
This looks to me like the bot itself is opening Outlook. Since the bot is running on the server, this will not work.

The simplest way to open email on the client is to use a "mailto:you@company.com" hyperlink.

**Comment by nupurkamble** [comment]
Okay I'll try that. @billba Thank you.
