### ISSUE TITLE
How to change - Say "hi" if you'd like to chat

### ISSUE THREAD

**Issue by pr3d1ction** [Microsoft/BotFramework-WebChat#540]
Hi folks,
We want to change the "welcome message" that appears next to the Bot Picture:

> Hi! I'm <Botname>. Say "hi" if you'd like to chat

How can we change this? Where is it coming from?

Thanks!

**Comment by photodesignch** [comment]
The conversational logic should be in your own bot.

**Comment by billba** [comment]
If you are seeing the bot picture and the "say Hi" text you are running the old version of WebChat. The modern version doesn't include a welcome message (as @photodesignch points out, you provide that with your bot).

@dandriscoll I thought we upgraded everyone to the new WebChat?

**Comment by pr3d1ction** [comment]
I just deactivated the preview versions in the webchat settings. 
Is this being to be deactivated then in the near future? I personally like it with the picture there at the start.

Is there also a plan to let the users just change the color of the upper blue border? I would like to avoid to republish for every new web chat bot. :) 

Thanks!

**Comment by billba** [comment]
The old version is going away. You can customize the border color and other display options by deploying this control (following the directions in the README) with a custom .CSS file. At the moment there is no way to customize the WebChat channel.
