### ISSUE TITLE
Getting bat gateway error when using Webchat only if when using the In your non-React website, run WebChat inline initialization and not when using the IFrame

### ISSUE THREAD

**Issue by marconsilva** [Microsoft/BotFramework-WebChat#541]
Hi guys, I'm having some problems with an integration of the WebChat Client Application on a webpage. When I'm using the IFrame all works well but I want to do some changes to the title bar of the webclient and the IFrame integration wont permit that, so I followed the steps in the readme to use the integration referenced as "Easy: In your non-React website, run WebChat inline".

my page code looks like this:
<!DOCTYPE html>
<html lang="en">
<head>
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.js"></script>
<link href="https://unpkg.com/botframework-webchat/botchat.css" rel="stylesheet" />
</head>
</head>
<body style="font-family:'Segoe UI'">
<div id="botInner" class="chatframe"></div>
<button type="button" id="botButton">Open Bot</button>
<script src="https://unpkg.com/botframework-webchat/botchat.js"></script>
<script>
        BotChat.App({
            directLine: { secret: '{MyBotKeyFromTheBotFrameworkDeveloperPortal}' },
            user: {id: 'you' },
            bot: {id: 'Bot' },
            resize: 'detect'
        }, document.getElementById("botInner"));
    </script>
</body>
</html>

if instead of using this I use this code below all works fine...

<!DOCTYPE html>
<html lang="en">
<head>
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.js"></script>
<link href="https://unpkg.com/botframework-webchat/botchat.css" rel="stylesheet" />
</head>
</head>
<body style="font-family:'Segoe UI'">
<div id="botInner" class="chatframe">
 <iframe style="height:100%;width:100%" src='https://webchat.botframework.com/embed/felixdemobot?s={TheSameKeyAsUsedOnTheCodeAbove}' id="felixFrame"></iframe>
</div>
<button type="button" id="botButton">Open Bot</button>
</body>
</html>

On the browser's Debugger window I see the errors as such:

HTTP502: BAD GATEWAY - The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request.
(XHR)POST - https://directline.botframework.com/v3/directline/conversations/7VmkWK627GSIvIRYukoaeY/activities

Using fiddler I can see some requests are OK other are not...

200 OK for -> OPTIONS /v3/directline/conversations HTTP/1.1
201 CREATED for the first ->POST /v3/directline/conversations HTTP/1.1
101 Switching Protocols for -> GET /v3/directline/conversations/G2i0C7SeoNM2ehRnv251wA/stream?watermark=-&t=eImksAp5358.dAA.RwAyAGkAMABDADcAUwBlAG8ATgBNADIAZQBoAFIAbgB2ADIANQAxAHcAQQA.14Jr9pLx0gE._-juptS9tV8.lWRaLIDEzJB8fVTPIcqwCUQEOZw0AgU-ttMdONtd0z8 HTTP/1.1

then every time I input text on the chatbot I get this:

request: POST https://directline.botframework.com/v3/directline/conversations/G2i0C7SeoNM2ehRnv251wA/activities HTTP/1.1
....

Response:
HTTP/1.1 502 Bad Gateway
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 117
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.0
Access-Control-Allow-Origin: *
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000
Date: Fri, 30 Jun 2017 11:22:22 GMT

{
  "error": {
    "code": "ServiceError",
    "message": "Failed to send activity: bot returned an error"
  }
}

Do any of you have some tips to how I could solve this?

**Comment by billba** [comment]
I'm not sure this is the problem, but your shouldn't be using the same secret. The WebChat *channel* requires a WebChat secret, but the WebChat *control* requires a Direct Line secret. Confusing, I know.

**Comment by marconsilva** [comment]
A bit... given that it is bottom line a WebChat as well :) non the less I generated a new DirectLine Secret and it didn't work as well... same behaviour...

**Comment by EricDahlvang** [comment]
This appears to be due to the difference between the iframed botchat.js and the cdn botchat.js.

https://webchat.botframework.com/scripts/adaptive/botchat.js <--iframe's botchat
https://unpkg.com/botframework-webchat/botchat.js <--cdn's botchat

Once the cdn botchat.js is updated to the latest version, there will be parity between the two and this error will no longer occur.

**Comment by danmarshall** [comment]
@marconsilva - the CDN version has been updated, can you make sure you have latest and see if the error still occurs?

**Comment by EricDahlvang** [comment]
After looking into this further, it seems like your bot code is expecting the "name" field to be present for the user.  The iframe'd version supplies this automatically.  Please try changing your unpkg version to something like this (include **name** for user and bot):

```js
<script> 
     BotChat.App(
          { directLine: 
               { secret: '{MyBotKeyFromTheBotFrameworkDeveloperPortal}' }, 
                   user: {id: 'you', name: 'you' }, 
                   bot: {id: 'Bot', name: 'bot' },
                   resize: 'detect' }, 
      document.getElementById("botInner")); 
</script>
```

**Comment by marconsilva** [comment]
That is correct Eric, thank you very much, it solved the issue!
Cheers
MS
