### ISSUE TITLE
[Bug] CDN version of botchat.js does not support Adaptive Cards

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-WebChat#545]
I tried to deploy webchat using the following example: [Easy: In your non-React website, run WebChat inline](https://github.com/Microsoft/BotFramework-WebChat#easy-in-your-non-react-website-run-webchat-inline) but in the CDN linked version, Adaptive Cards do not work. But Adaptive Card renders w/o errors in iframe provided by WebChat channel in bot dev portal.

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="https://unpkg.com/botframework-webchat/botchat.css" rel="stylesheet" />
  </head>
  <body>
    <div id="bot"/>
    <script src="https://unpkg.com/botframework-webchat/botchat.js"></script>
    <script>
      BotChat.App({
        directLine: { secret: direct_line_secret },
        user: { id: 'userid' },
        bot: { id: 'botid' },
        resize: 'detect'
      }, document.getElementById("bot"));
    </script>
  </body>
</html>
```
![webchat iframe vs directline webchat cdn js](https://user-images.githubusercontent.com/3075047/27802897-7a4699a4-5fdb-11e7-85bd-cf2a9ab42ba9.png)

**Comment by billba** [comment]
Correct. The channel is running a one-off version of WebChat with Adaptive Cards and Speech support. We are in the process of carefully migrating these features to the main branch.
