### ISSUE TITLE
attachment file in IE.

### ISSUE THREAD

**Issue by junpark12** [Microsoft/BotFramework-WebChat#547]
Hi I'm testing webchat inside html page.
when i try to upload image files to the page, following code handles the request.

private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
{
       try
       {
              var activity = await result as Activity;
              var attachment = activity.Attachments.First();    <--- issue line...

when i use chrome to upload file, i can successfully handle the request in this case, "activity.Attachments.Count" is "1". But when i use IE 11, the activity.Attachments.Count is "0".
Are there any workaround to upload attachments from IE?

Thanks.

**Comment by GeekTrainer** [comment]
Right now, this is the known behavior in IE 11. At the moment, we do not have an official browser support matrix. I have added this issue to the backlog, and we will determine next steps from there.

**Comment by danmarshall** [comment]
I'm going to re-open this and assign to myself  just that I might have a chance to see if there may be an easy fix or workaround.

**Comment by danmarshall** [comment]
@reyesrico - perhaps we can add multiple browser tests?

**Comment by reyesrico** [comment]
@GeekTrainer I tried to upload different number of uploads using IE 11 and using a C# bot and all of them are being processed successfully by Web Chat and Direct Line.  The only thing that I saw is that files that are bigger than 3MB are not being processed. Can you please take a look of the size of the files that you are uploading?

@danmarshall there is a new issue to cover: Web Chat using only IE 11 is showing couple of messages after uploading files.

**Comment by compulim** [comment]
Since we see files uploaded to C# bot successfully, I am closing this bug as no repro.
