### ISSUE TITLE
v0.10.6 this repo vs v0.10.7 on NPM?

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-WebChat#548]
Why does this repo master branch list WebChat at 0.10.6 when NPM is showing the latest version as 0.10.7?

This repo, package.json:
![0 10 6 botframework webchat package json at master microsoft botframework webchat](https://user-images.githubusercontent.com/3075047/27890302-b9e4bcc2-61a6-11e7-8f6e-22475f621062.png)

NPM:
![0 10 7 npm botframework webchat](https://user-images.githubusercontent.com/3075047/27890305-bf75dd1a-61a6-11e7-9fd7-58493b94f092.png)

**Comment by danmarshall** [comment]
It means that the version was bumped on @GeekTrainer 's local machine package.json when it was published, and this wasn't checked in.

**Comment by GeekTrainer** [comment]
This should now be resolved.
