### ISSUE TITLE
Loop carousel

### ISSUE THREAD

**Issue by ravi2808** [Microsoft/BotFramework-WebChat#550]
I need to loop through the carousel, If I click right arrow on last card, it should go to first and vice-versa

**Comment by danmarshall** [comment]
@jecristi thoughts?

**Comment by billba** [comment]
What do other channels do? The problem with looping is that you may not know you have wrapped around. @ravi2808 why do you "need" to loop through?

**Comment by danmarshall** [comment]
Hi @ravi2808 thank you for the feature request, but this is not something that we will take on at this time. Cheers
