### ISSUE TITLE
[Bug] Adaptive Cards > Error rendering quote chars in message.text

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-WebChat#553]
**Problem Description**
Testing newest build of [webchat 0.10.8](https://www.npmjs.com/package/botframework-webchat) via unpkg CDN link, there appears to be an error rendering `"` characters. Works fine in WebChat "Channel" iframe. see attached.

**Expected:**
`You can request the current weather forecast for CITY_NAME by typing: “what is the weather in Miami?”`

**Actual:**
`You can request the current weather forecast for CITY_NAME by typing: âwhat is the weather in Miami?€`

![direct line webchat vs iframe](https://user-images.githubusercontent.com/3075047/27926702-2f217dda-623e-11e7-83aa-9b30abeb69d2.png)

**Comment by nwhitmont** [comment]
@reyesrico The code used to trigger this error is:
```js
var defaultReplyHandler = function (session) {
    session.send(`Sorry, I did not understand ${session.message.text}`);
    session.endConversation('You can request the current weather forecast for CITY_NAME by typing: "what is the weather in Miami?"');
};
```

**Comment by reyesrico** [comment]
@nwhitmont make sure to set the charset=UTF-8 in the bot server and in the bot client:

- For the webserver (i.e. IIS, Azure, etc) set the Content-Type: text/html; charset=UTF-8 
- For the client (index.html) set the <meta charset="UTF-8" />inside the <head> tag.

**Comment by nwhitmont** [comment]
@reyesrico I set the encoding to utf-8 in the HTML meta tag but I'm still seeing special characters in place of quite chars. 

Example:
http://divefinder-node.azurewebsites.net/chat

Message JSON:
```js
{
  "type": "message",
  "text": "Hi! I'm Contoso Dive Finder!\n\nI'll help you schedule a scuba getaway!",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "size": "auto",
                "items": [
                  {
                    "type": "Image",
                    "size": "medium",
                    "url": "https://contososcuba.azurewebsites.net/assets/Contoso_logo.jpg"
                  }
                ]
              },
              {
                "type": "Column",
                "items": [
                  {
                    "type": "TextBlock",
                    "text": "Start with something like:",
                    "size": "large",
                    "weight": "bolder"
                  },
                  {
                    "type": "TextBlock",
                    "text": "'Where can I go scuba diving?'",
                    "separation": "none"
                  },
                  {
                    "type": "TextBlock",
                    "text": "or",
                    "separation": "none"
                  },
                  {
                    "type": "TextBlock",
                    "text": "'Show me some local wildlife.'",
                    "separation": "none"
                  },
                  {
                    "type": "TextBlock",
                    "text": "You can also 'restart' anytime.",
                    "separation": "none"
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
```
Actual:
![single quote char replaced with special chars - contoso dive finder](https://user-images.githubusercontent.com/3075047/28235582-aeffa9d6-68c5-11e7-89cd-8fbe983b7753.png)

**Comment by nwhitmont** [comment]
resolved

**Comment by sivanandh** [comment]
I also faced this issue, then I created the message with below formats in MS bot Code(app.js).

    var customMessage = new builder.Message(session)
            .text("I didn't quite get that. For us ......")
            .textFormat("plain")
            .textLocale("en-us");
        session.send(customMessage);

Refer Official URL for V3: [https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-message-create?view=azure-bot-service-3.0](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-message-create?view=azure-bot-service-3.0)
