### ISSUE TITLE
[Adaptive Cards] Different rendering of card Direct Line + unpkg/botchat.js vs WebChat channel iframe embed code

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-WebChat#554]
**Problem Description**
Testing new build of botframework-adaptive cards via unpkg CDN URL, the Adaptive Cards are rendered differently when using Direct Line + unpkg `botchat.js` vs iframe embed code provided by WebChat channel in Bot Portal channels page. 

**Demo**
- http://nils-luis-weather-bot.azurewebsites.net/directline
- http://nils-luis-weather-bot.azurewebsites.net/webchat

**Actual**
Cards look different depending on which WebChat is used. 
<img width="1335" alt="screen shot 2017-07-06 at 11 33 45 am" src="https://user-images.githubusercontent.com/3075047/27927179-cd956e58-623f-11e7-8457-6d53270fee45.png">

**Expected**
Adaptive Cards render the same across all WebChats.

**Comment by danmarshall** [comment]
The WebChat channel is part of the BotFramework and has a separate release cycle. We will try to get this updated soon.

**Comment by EricDahlvang** [comment]
This looks resolved:

![image](https://user-images.githubusercontent.com/11055362/30762830-6b160418-9f98-11e7-9060-599d56cabddb.png)

Someone can probably close this issue.
