### ISSUE TITLE
Webchat control custom build in ASP.NET website

### ISSUE THREAD

**Issue by rohantare** [Microsoft/BotFramework-WebChat#555]
I have ASP.NET website , which have webchat control. I have configured DirectLine channel. The styling works well, as i include botchat.css in my content folder. 
Now I need to include speech to text capabilities. I know there is separate branch which I need to download, build and refer.
The instructions say it is possible in REACT website. 

My question : How can i add speech to text build in my ASP.NET website?
looking forward for your response.

**Comment by danmarshall** [comment]
Please see the samples in the speech branch here: https://github.com/Microsoft/BotFramework-WebChat/blob/speech/samples/speech/index.html

**Comment by billba** [comment]
The client code will be the same whether you are using ASP.NET, Node, Rails, etc. For the most part your  web server won't be involved at all except for serving up the HTML + JS. However if you want your client to use the more secure Token approach then your server will have to generate that and provide it to the client. @danmarshall @GeekTrainer @dandriscoll we'll have to decide where sample code for that should live.

**Comment by Akhila9** [comment]
@rohantare Did you add speech to text build in your ASP.NET website

**Comment by danmarshall** [comment]
@rohantare I'm closing this issue for now. Please re-open if you continue to have this issue.
