### ISSUE TITLE
Internet Explorer compatibility

### ISSUE THREAD

**Issue by miscalencu** [Microsoft/BotFramework-WebChat#561]
Does The Backchannel (https://github.com/Microsoft/BotFramework-WebChat#the-backchannel) works in IE11? Because as soon as I added an event it stopped displaying the chat window and I have no console errors. But in other browsers (Chrome for ex.) everything is still OK.

**Comment by billba** [comment]
Can you give us some code?

________________________________

**Comment by miscalencu** [comment]
This code works perfectly in Chrome:

```
var user = { id: email, name: name };
var data = { name: name, email: email, phone: phone, country: country };
var botConnection = new BotChat.DirectLine({
	secret: secret
});
BotChat.App({
	botConnection: botConnection,
	user: user,
	bot: { id: botId },
	resize: 'detect'
}, document.getElementById("bot"));

botConnection.postActivity({ type: "event", name: "initializeBot", value: JSON.stringify(data), from: user }).subscribe(id => console.log("user initialization success"));
```
But in IE11 I cannot see the chat window. Plus, there is no error in the console.
If I remove the `subscribe` part, the chat will initialize, but the event will not be triggered. Again, no error in the console.

**Comment by miscalencu** [comment]
OK, I'm stupid. It turns out that I had an error in the console after all....
I changed:
`.subscribe(id => console.log("user initialization success"));`
with:
`.subscribe(function (id) { console.log("user initialization success"); })`
and everything is OK now.

Thanks for your help.

**Comment by billba** [comment]
No worries, I keep making that mistake with IE11 as well - I have to go back in time and write paleo-JS. Glad it's working for you now!
