### ISSUE TITLE
[Adaptive Cards] Expanded choice input is rendering as a dropdown rather than radio buttons

### ISSUE THREAD

**Issue by ryanlengel** [Microsoft/BotFramework-WebChat#573]
I'm building out adaptive cards with the .NET SDK and trying to have radio buttons rendered rather than dropdowns. If I switch between a ChoiceInputStyle of Compact or Expanded, both are returned as dropdowns in the webchat. Is this functionality available yet, or am I missing a property in the card?  Thanks!

![image](https://user-images.githubusercontent.com/2483151/28128457-a747024e-66e4-11e7-8cfa-21f3b7da16e3.png)

Sample ChoiceSet
`new ChoiceSet()
                            {
                                Id = "chatSatisfaction",
                                Style = ChoiceInputStyle.Expanded,
                                IsMultiSelect = false,
                                Choices = new List<Choice>()
                                {
                                    new Choice()
                                    {
                                        Title = "⭐",
                                        Value = "1"
                                    },
                                    new Choice()
                                    {
                                        Title = "⭐⭐",
                                        Value = "2"
                                    },
                                    new Choice()
                                    {
                                        Title = "⭐⭐⭐",
                                        Value = "3"
                                    },
                                    new Choice()
                                    {
                                        Title = "⭐⭐⭐⭐",
                                        Value = "4"
                                    },
                                    new Choice()
                                    {
                                        Title = "⭐⭐⭐⭐⭐",
                                        Value = "5"
                                    }
                                }
                            }`

**Comment by danmarshall** [comment]
Can you try your JSON in the [Adaptive Cards online visualizer](http://adaptivecards.io/visualizer/), do you see the radio buttons there?

**Comment by ryanlengel** [comment]
Yep! 
![image](https://user-images.githubusercontent.com/2483151/28132224-0d3f59fa-66f1-11e7-948b-a6e034f7b713.png)

`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "0.5",
    "body": [
        {
        "type": "Container",
        "separation": "none",
        "style":"normal",
        "items":[
            {
            "type": "TextBlock",
            "text": "We appreciate your feedback",
            "weight": "bolder",
            "size": "large"
            }
        ]
        },
        {
        "type": "Container",
        "separation" :"default",
        "style":"normal",
        "items":[
   {
      "type": "TextBlock",
      "text": "Did we resolve your issue?"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "issueResolved",
      "style": "expanded",
      "isMultiSelect": false,
      "value": "1",
      "choices": [
        {
          "title": "Yes, in **one** contact",
          "value": "1"
        },
        {
          "title": "Yes, after multiple contacts",
          "value": "2"
        },
        {
          "title": "No, did not resolve",
          "value": "3"
        }
      ]
    }, {
      "type": "TextBlock",
      "text": "How satisfied are you with this chat?"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "chatSatisfaction",
      "style": "expanded",
      "isMultiSelect": false,
      "value": "1",
      "choices": [
        {
          "title": "⭐" ,
          "value": "1"
        },
        {
          "title": "⭐⭐",
          "value": "2"
        },
        {
          "title": "⭐⭐⭐",
          "value": "3"
        },
                {
          "title": "⭐⭐⭐⭐",
          "value": "4"
        },
                {
          "title": "⭐⭐⭐⭐⭐",
          "value": "5"
        }
        
            ]  
    },
        {
      "type": "TextBlock",
      "wrap": true,
      "text": "Based upon this support experience, how likely are you to recommend your product or service to a friend or colleague?"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "likelyToRecommend",
      "style": "expanded",
      "isMultiSelect": false,
      "value": "1",
      "choices": [
        {
          "title": "⭐",
          "value": "1"
        },
        {
          "title": "⭐⭐",
          "value": "2"
        },
        {
          "title": "⭐⭐⭐",
          "value": "3"
        },
                {
          "title": "⭐⭐⭐⭐",
          "value": "4"
        },
                {
          "title": "⭐⭐⭐⭐⭐",
          "value": "5"
        }
        
            ]   
    },{
            "type": "TextBlock",
            "text": "Tell us more:"
        },
        {
            "type": "Input.Text",
            "id": "tellUsMore",
            "placeholder": "Enter your feedback here",
            "isMultiline": true
        }                  
      
]}],
        "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"        
        }
    ]
}`

**Comment by danmarshall** [comment]
can you paste your JSON here?

**Comment by ryanlengel** [comment]
```{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "0.5",
    "body": [
        {
        "type": "Container",
        "separation": "none",
        "style":"normal",
        "items":[
            {
            "type": "TextBlock",
            "text": "We appreciate your feedback",
            "weight": "bolder",
            "size": "large"
            }
        ]
        },
        {
        "type": "Container",
        "separation" :"strong",
        "style":"normal",
        "items":[
   {
      "type": "TextBlock",
      "text": "Did we resolve your issue?"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "issueResolved",
      "style": "expanded",
      "isMultiSelect": false,
      "choices": [
        {
          "title": "Yes, in **one** contact",
          "value": "1"
        },
        {
          "title": "Yes, after multiple contacts",
          "value": "2"
        },
        {
          "title": "No, did not resolve",
          "value": "3"
        }
      ]
    }, {
      "type": "TextBlock",
      "text": "How satisfied are you with this chat?"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "chatSatisfaction",
      "style": "expanded",
      "isMultiSelect": false,
      "choices": [
        {
          "title": "⭐" ,
          "value": "1"
        },
        {
          "title": "⭐⭐",
          "value": "2"
        },
        {
          "title": "⭐⭐⭐",
          "value": "3"
        },
                {
          "title": "⭐⭐⭐⭐",
          "value": "4"
        },
                {
          "title": "⭐⭐⭐⭐⭐",
          "value": "5"
        }
        
            ]  
    },
        {
      "type": "TextBlock",
      "wrap": true,
      "text": "Based upon this support experience, how likely are you to recommend your product or service to a friend or colleague?"
    },
    {
      "type": "Input.ChoiceSet",
      "id": "likelyToRecommend",
      "style": "expanded",
      "isMultiSelect": false,
      "choices": [
        {
          "title": "⭐",
          "value": "1"
        },
        {
          "title": "⭐⭐",
          "value": "2"
        },
        {
          "title": "⭐⭐⭐",
          "value": "3"
        },
                {
          "title": "⭐⭐⭐⭐",
          "value": "4"
        },
                {
          "title": "⭐⭐⭐⭐⭐",
          "value": "5"
        }
        
            ]   
    },{
            "type": "TextBlock",
            "text": "Tell us more:"
        },
        {
            "type": "Input.Text",
            "id": "tellUsMore",
            "placeholder": "Enter your feedback here",
            "isMultiline": true
        }                  
      
]}],
        "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"        
        }
    ]
} ```

**Comment by danmarshall** [comment]
Hi @ryanlengel , thanks for the JSON. I have verified that the behavior work correctly in the WebChat built from source of this repo, and that it is not working as you expect in the BotFramework hosted version of the WebChat. I will be updating the hosted version soon, thanks for your patience.

**Comment by ryanlengel** [comment]
@danmarshall that's odd. I'm using the webchat in this repo (latest now) and still getting the same issue. I'm building my card in .NET, maybe I should just convert the JSON for now? Could that make a difference?

**Comment by danmarshall** [comment]
@ryanlengel I would not think that it would make a difference, but it might be worth a shot... I used the JSON that you sent. How did you create it?

**Comment by ryanlengel** [comment]
I've just changed my code to use the .NET SDK & JSON, both render with dropdowns. Is https://botchattest.herokuapp.com/ up to date? They are dropdowns in that as well.

![image](https://user-images.githubusercontent.com/2483151/28197862-7d4d32f8-680e-11e7-89f2-c55940cbd202.png)

**Comment by danmarshall** [comment]
@ryanlengel can you try with the botchat.js from https://unpkg.com/botframework-webchat@0.11.0/botchat.js

**Comment by danmarshall** [comment]
@ryanlengel also, can you give me your bot ID?

**Comment by ryanlengel** [comment]
@danmarshall so it appears that an "expanded" style is not being parsed back to the botchat.js, but compact is. So the default behavior is to set it as compact.

**Setting style to Expanded**
![image](https://user-images.githubusercontent.com/2483151/28230719-11c5e20c-689d-11e7-9fc0-d500ed404dbc.png)

**Setting style to Compact**
![image](https://user-images.githubusercontent.com/2483151/28230881-73320cc8-689d-11e7-98dd-571b38f27bbd.png)

**Comment by danmarshall** [comment]
@ryanlengel so, this was indeed in the C# then?

**Comment by ryanlengel** [comment]
@danmarshall it seems so, should I file an issue on the adaptive cards repo then?

**Comment by danmarshall** [comment]
@ryanlengel yes, please!
