### ISSUE TITLE
Autoscroll not working when Markdown contains image

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#576]
Expecting that the last message is fully in view.

**Comment by danmarshall** [comment]
Actual result:
![image](https://user-images.githubusercontent.com/11507384/28224249-43bd57c8-6883-11e7-85a6-922769ef22b4.png)

Expected:
Bottom of message to be docked to the bottom, scrollbar at the bottom.

**Comment by billba** [comment]
This was working...

**Comment by danmarshall** [comment]
@billba - true: https://github.com/Microsoft/BotFramework-WebChat/blob/b6219c815068efc12ce898a7c0b0c55f3fa4be64/src/FormattedText.tsx#L228

No we are just _dangerously_ setting the html instead of creating a React component for every tag.

**Comment by billba** [comment]
Yup, `renderMarkdown` now just ignores `onImageLoad`.

**Comment by corinagum** [comment]
Bug verified in v4.

**Comment by compulim** [comment]
### Note to fixer

Try to use `setTimeout` to detect changes. Because, we now support customer rendered content, they may not go thru React or detected by `onLoad` event. We need something more robust even though it sounds a bit hacky.

**Comment by compulim** [comment]
Tested in v4 and is fixed.

A recent bump in our scroll to bottom component will stick to bottom with dynamically changing content.

Added a command `slow markdown` to MockBot for testing regression of this bug.
