### ISSUE TITLE
Bot - Webchat hosting on the own server

### ISSUE THREAD

**Issue by sathees3101** [Microsoft/BotFramework-WebChat#581]
Hello,
I have a question considering hosting the bot myself.
Well my real target is to change the styling of the bot. Since I cannot adapt the following css [https://webchat.botframework.com/css/adaptive/botchat.css]  I learned that I need to host the bot. I did develop a simple bot and test it on the emulator. Everything was fine.  Now I am struggling to host and run it on my server. 
I followed the steps recommended on the part “Easy: In your non-react.website” of the following link
[https://github.com/Microsoft/BotFramework-WebChat/blob/master/README.md]
I did download the rep. I have build it on the terminal.  And then I uploaded on my server. 
Now I have also uploaded my code on the server. Now I am not sure how to continue.

**Comment by danmarshall** [comment]
I believe you may want "[Easyish](https://github.com/Microsoft/BotFramework-WebChat#easyish-in-any-website-iframe-your-webchat-instance)" instead of "Easy" :-)

Please see the sample at https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/fullwindow/index.html

You can copy this index.html and upload it to your server. Then upload the js and css files that you have built.

**Comment by sathees3101** [comment]
Thanks!
I added my coded in the .vs folder. Afterwards I did build the project. Then I added botchat.js and botchat.css .I created an index.html and copied the code adapting the secret and the references to the .js and .css.
Now I get the chat window on my index.html. However I get the following error on the browser.
“Failed to load resource: the server responded with a status of 403. { "message": "The requested resource does not support http method 'GET'." }.  What can I do avoid this error?

**Comment by sathees3101** [comment]
Using the following link [https://botchattest.herokuapp.com/]() and entering my secret the bot works.

**Comment by danmarshall** [comment]
what is the URL that gives you a 403?

**Comment by sathees3101** [comment]
Failed to load resource: the server responded with a status of 403 (Forbidden)

directline.botframework.com/v3/directline/conversations

**Comment by danmarshall** [comment]
@sathees3101 that usually means that the secret or token is invalid.

**Comment by sathees3101** [comment]
hmmm...let me summarize what I did.
1. I have created a bot on bot portal.
2. I have downloaded the Bot Framework WebChat. I have added my code to the folder .vscode and then I have built the project. I have uploaded it to the folder https://myurl.com/bot/.
3. I have created  https://url.com/index.html (with the code you suggested in the beginning) adapting the secret and the link to css and js file.

4. Now I have the 403 forbidden error on the console of my browser.

Is there any mistake in my steps?

**Comment by danmarshall** [comment]
It seems ok, I think you just need to make sure that you copied/pasted the secret completely.

**Comment by premaarya** [comment]
I had same issue, needed to style the bot with our theme.. I was able to host the code after building it in azure website. I should ask which web server are you using to host the webchat code you customized.

**Comment by sathees3101** [comment]
I am using one (one.com) to host the my website and the webchat code

**Comment by compulim** [comment]
@sathees3101 I tried your site at https://botchattest.herokuapp.com/ and didn't spot any JS error or 403. Is it fixed?

**Comment by billba** [comment]
@compulim that's my generic test site. You would need @sathees3101's secret in order to test his bot.

**Comment by sathees3101** [comment]
Submitting my secret that I see on "direct line" I receive the following error  POST https://directline.botframework.com/v3/directline/conversations/809WUR9Q4bZAdcPxeQQFBK/activities 502 (Bad Gateway)

**Comment by danmarshall** [comment]
@sathees3101 502 from DirectLine means a 500 from the bot.

**Comment by compulim** [comment]
Since we did some refactoring work in Bot Emulator, it is possible to host bot locally.

I have some demo code running with Docker, you can find it at https://github.com/compulim/docker-bot.
