### ISSUE TITLE
Does internet explorer support bot deployed using backchannel?

### ISSUE THREAD

**Issue by nupurkamble** [Microsoft/BotFramework-WebChat#582]
I've deployed a bot written in c# using **backchannel**. It works fine on all the browsers including chrome, edge and mozilla firefox except for **internet explorer.** It just does not open. Is there a solution for this ?

This is the backchannel html code which I run.

    <html>
    <head>
    <meta charset="UTF-8" />
    <title>Bot Chat</title>
    <link href="botchat.css" rel="stylesheet" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-
     scalable=no" />
     </head>

      <body onload="postLoadMessage()">

     <div id="BotChatGoesHere"> 
      <script src="botchat.js"></script>
      <script>
        var params = BotChat.queryParams(location.search);
        var user = { id: userid };
        var bot = {
            id: bot,
        };
        window['botchatDebug'] = params['debug'] && params['debug'] === "true";

        var botConnection = new BotChat.DirectLine({
            secret: secretkey,
            token: params['t'],
            domain: params['domain'],
            webSocket: params['webSocket'] && params['webSocket'] === "true" 
        });

        BotChat.App({
            botConnection: botConnection,
            user: user,
            bot: bot
        }, document.getElementById("BotChatGoesHere"));

        const postLoadMessage = () => {
            botConnection
                .postActivity({type: "event", value: "" , from: {id: "me" }, name: "PageLoaded"})
                .subscribe(id => console.log("success"));
        }
    </script>
    </body>
    </html>

**Comment by billba** [comment]
IE does not support the "fat arrow" syntax for lambda functions. You'll need to translate to the "function" syntax, e.g.
    const postLoadMessage = function() { ... }

**Comment by mikeegee** [comment]
Hi,

Try this 
.subscribe(function (id) { console.log("success"); })
instead of
 .subscribe(id => console.log("success"));
