### ISSUE TITLE
Speech in React Component

### ISSUE THREAD

**Issue by arunredhu** [Microsoft/BotFramework-WebChat#583]
Hi,

I just implemented BotFramework-WebChat react component with custom build. I want to implement the speech functionality also. As I see it is available in the web-chat sourcebut I didn't find any way to implement this in react. I found there is no export for Cognitive service. Can you please suggest the best way to implement?

Thanks :)

**Comment by danmarshall** [comment]
@shahidkhuram can you provide a React-based example?

**Comment by compulim** [comment]
In our `<script src="...">` scenario, it works because the user would implicitly include 2 entrypoints like this:

```html
<script src="../../botchat.js"></script>
<script src="../../CognitiveServices.js"></script>
```

But in React scenario, our entrypoint is `BotChat.ts`. But unfortunately, `BotChat.js` does not export `CognitiveServices/SpeechRecognition.ts` and `CognitiveServices/SpeechSynthesis.ts`. Thus, `CognitiveServices/*` was not able to use under React.

**Comment by HernanCote** [comment]
Hello, any news for this? It is possible to implement the speech capabilities with a React component?

**Comment by compulim** [comment]
@HernanCote I think the current packaging approach is not correct and please bear with us that we need time to fix that. I think we should:
1. Publish `botframework-webchat` without `CognitiveServices.js`
2. Publish a new package `botframework-congitiveservices` for the `CognitiveServices.js` (or rename it to BingSpeech.js)

On top of that, I would also love to see some refactoring on `CognitiveServices.js`. For example, making the `CognitiveServices.js` to conform to Web Speech API. We are already using Web Speech API in Web Chat (via `BrowserSpeechRecognition` class) and I think it is easy to do that.

And then we can move to Lerna to package both `botframework-webchat` and `botframework-cognitiveservices` in the same GitHub repository.

**Comment by arunredhu** [comment]
Sorry for late reply, but I fixed it by myself to use of `CognitiveServices`. I used the local version of this package. I just clone this packge and added the following line in `Botchat.ts`

`export * from './CognitiveServices/lib';`

and then I make the local `npm` package by compiling it locally to use in my project.

After that I added this package to my project and  below is the implementation

```
import { Chat, SpeechSynthesizer, SpeechRecognizer, SynthesisGender, DirectLine } from 'botframework-webchat';

const speechOptions = {
    speechRecognizer: new SpeechRecognizer({ subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY' }),
    speechSynthesizer: new SpeechSynthesizer({
        gender: SynthesisGender.Female,
        subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY',
        voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
    })
};
```

I hope this could help you.

**Comment by compulim** [comment]
That's exactly what I was thinking, making another NPM package only for the Cognitive Services.

Wished we can do better to unblock you sooner.
