### ISSUE TITLE
Add API for setting focus

### ISSUE THREAD

**Issue by danmarshall** [microsoft/BotFramework-WebChat#587]
A page which is iframing the WebChat may want to set the focus on the input textbox.

**Comment by compulim** [comment]
The set focus API should be usable under 3 supported entrypoints:
* `<iframe>`, with a postMessage interface
* `<script type=".../botchat.js">` and then created thru `BotChat.App({})`
* Install [BotFramework-WebChat](https://www.npmjs.com/package/botframework-webchat) thru npm and then created using React `<Chat directLine=...>`

**Comment by danmarshall** [comment]
Yes. We don't need to provide the `<iframe>` version here.

**Comment by corinagum** [comment]
Added to Backlog because focus isn't serializable, so exposing it in an API is not trivial.
