### ISSUE TITLE
Any recommendation on passing thru user authentication from the main site to the bot web chat?

### ISSUE THREAD

**Issue by guangw** [Microsoft/BotFramework-WebChat#590]
botchat.js and botchat.css provides easy way to embed a bot web chat into a web site. The question is how we can prevent security issues by spoofing the javascript. We only allow certain type of users to access the bot and user auth is done in the server side of our main site. Users are logged in to our site and we do not want users to log in again from the bot dialog box which sample codes from bot framework are doing. Any help is welcome.

**Comment by billba** [comment]
This is a fairly sophisticated subject, and it depends a great deal on how your specific auth works. For instance, if a web page gets an auth token from the server, you can use the [Backchannel](https://github.com/Microsoft/BotFramework-WebChat/#the-backchannel) to send an auth token from the hosting web page to the bot.

The more you can say about your scenario, the more guidance we can give.

**Comment by guangw** [comment]
thanks for quick reply, @billba. Using backchannel sounds a way worth looking into.
