### ISSUE TITLE
WebChat thumbnail card title text size showing very big which is not looking good

### ISSUE THREAD

**Issue by amitgobare23** [Microsoft/BotFramework-WebChat#593]
![webchat](https://user-images.githubusercontent.com/25148394/28419462-9a49bca0-6d7c-11e7-92a0-0e7148d11a38.png)

**Comment by danmarshall** [comment]
Can you share your JSON?

**Comment by amitgobare23** [comment]
I am just using thumbnail card and displaying it....that's it....not using any JSON

**Comment by danmarshall** [comment]
Is there any markdown in your title field?

**Comment by amitgobare23** [comment]
my code for thumbnail is like this: 
new ThumbnailCard
			{
			Title = "Apple iPhone 7 Plus",
			Subtitle = "(Black, 128GB)",
			Text = "Rs. 70000.00",
			Images = new List<CardImage> { new CardImage("http://ecx.images-amazon.com/images/I/51qlxcCXNxL.jpg") },
			Buttons = new List<CardAction> { new CardAction(ActionTypes.OpenUrl, "Buy Now", value: "http://www.amazon.in/Apple-iPhone-Plus-Black-128GB/dp/B01LWNBCGM?tag=googinhydr18418-21&tag=googinkenshoo-21&ascsubtag=aab1db40-cf0e-445b-8f7e-e70b687f6bad")},
		
			}.ToAttachment(),

And and displaying as below:
if (message.Attachments.Count() > 1)
				{
					message.AttachmentLayout = AttachmentLayoutTypes.Carousel;
				}
				await context.PostAsync(message);

what is solution for this problem?

**Comment by danmarshall** [comment]
Are you using the Iframe version of WebChat, or are you using it in a `div` on your own page? When using it in a `div`, there might be cascading CSS styles.

**Comment by compulim** [comment]
Closed due to inactivity.
