### ISSUE TITLE
[Bug] Generated button HTML tag is missing type attribute

### ISSUE THREAD

**Issue by nwhitmont** [Microsoft/BotFramework-WebChat#594]
Missing `type="button"` attribute on HTML `<button></button>` tags generated for Adaptive Cards buttons causes button to fall-back to default type of `submit`.

Adaptive Cards users report that clicking on button without `type="button"` attribute causes "submit" action to unintentionally execute, and in some cases, causes page reload, which is undesirable. 

From MDN > <button> > Attributes > type:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
>submit: The button submits the form data to the server. **This is the default if the attribute is not specified**, or if the attribute is dynamically changed to an empty or invalid value.

Relates to: 
https://github.com/Microsoft/BotBuilder/issues/3146

**Comment by danmarshall** [comment]
Wow, good find Nils. Can you create this bug in the Adaptive Cards repo?

**Comment by nwhitmont** [comment]
sure, no problemo

**Comment by nwhitmont** [comment]
@danmarshall Fix is in for Adaptive Cards repo https://github.com/Microsoft/AdaptiveCards/issues/501

**Comment by danmarshall** [comment]
Thanks @nwhitmont Nils! I'm still working with @dclaux on this - we still have an outstanding work item to get the v0 branch to be backward compatible.
