### ISSUE TITLE
Not Able to send proactive message in React Component because of directlineJS re-initialization

### ISSUE THREAD

**Issue by ankitc1010** [Microsoft/BotFramework-WebChat#601]
I am trying to send a pro-active message using the React Webchat component. Following are the steps:
```
import React, { Component } from 'react'
import { Chat } from 'botframework-webchat';
import { DirectLine } from 'botframework-directlinejs'

const DIRECT_LINE_SECRET = "****"

class Webchat extends  Component {
  constructor(props) {
    super(props)
    this.directLine = new DirectLine({
        secret: DIRECT_LINE_SECRET
    })
  }
  componentDidMount() {
    this.directLine.postActivity({
        from: { id: 'id', name: "name"}, // required (from.name is optional)
        type: 'event',
        text: `Hey!`
    }).subscribe(
        id => console.log("Posted activity, assigned ID ", id),
        error => console.log("Error posting activity", error)
    );
  }
  render() {
    return (
      <div>
      <Chat directLine={this.directLine} user={{ id: ""  , name: profileObj.name , google_token_id : tokenId }} />
      </div>
    )
  }
}
```
I sent a backchannel message using the directline object to inform the chatbot server about the address of the webchat in order to send a pro-active message ( can be found in the componentDidMount method) .

But the conversation id changes for the directline property on the <Chat /> component, because it is reinitialized in the [Chat.tsx](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L120-L123)  file.

```
 const botConnection = this.props.directLine
            ? (this.botConnection = new DirectLine(this.props.directLine))
            : this.props.botConnection
            ;
```

And now because of this , the chatbot server is unable to reach the newly initialized WebChat Component.

**Comment by ankitc1010** [comment]
I overlooked the botConnection property. My bad.
This is the right way to do it I guess:
```
render() {
    return (
      <div>
      <Chat botConnection={this.directLine} user={{ id: ""  , name: profileObj.name , google_token_id : tokenId }} />
      </div>
    )
  }
```

Closing the issue.

**Comment by billba** [comment]
Even that simpler code still doesn't seem right. I think maybe you're trying to have your web page send a backchannel message to the bot before the user has typed a message, so that the bot can then send a proactive message to the right address. Is that correct? If so, that is a very common pattern.

**Comment by ankitc1010** [comment]
Yes. That's absolutely correct.

**Comment by billba** [comment]
Great, then that code is correct. I want to make sure you know that you don't need to do `class Webchat extends Component` unless you're doing so for other reasons.
