### ISSUE TITLE
HTML should be sanitized in messages

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#604]
A customer [reported](https://github.com/Microsoft/BotFramework-WebChat/issues/454#issuecomment-318731107) that a message containing HTML tags was being rendered:
```
the following html tag should not be enabled: <a href='http://example.com'>example</a>
```

**Comment by danmarshall** [comment]
1.	Sanitize the html to remove any scripting
2.	Whitelist to only the tags that we support
3.	Add “target=_blank” to hyperlinks.

**Comment by billba** [comment]
Do other chat clients allow any HTML at all in their markdown?

(Here I'm ignoring the "xml" message format, which supports just a handful of whitelisted tags.)

**Comment by danmarshall** [comment]
@billba no, they don't.

**Comment by billba** [comment]
Then rather than sanitize, I vote we strip HTML out entirely.  I think that's what we did before.

**Comment by danmarshall** [comment]
I agree personally, we are circulating the idea internally.

**Comment by eanders-MS** [comment]
HTML support in markdown varies widely from client to client. GitHub has pretty rich support for it. Telegram supports basic font formatting tags; Skype too.

**Comment by billba** [comment]
Oh okay, so what Dan said is not true. It is supported in some clients. That changes my opinion.

DAN WHY MUST YOU LIE SO

**Comment by danmarshall** [comment]
@reyesrico - can you create a matrix of which channels support HTML?

**Comment by reyesrico** [comment]
Channel | HTML Support
------------ | -------------
Slack | No
Facebook | No
GroupMe | No
Twillio (Web) | No
Kik | No
Telegram | No
Email | Yes

**Comment by nwhitmont** [comment]
@danmarshall What's the latest?

**Comment by billba** [comment]
@reyesrico I'm having trouble parsing this table. I think the actual question we are asking is "For each channel that supports Markdown, does it render embedded HTML in Markdown?"

**Comment by danmarshall** [comment]
@billba - I see. Yes I can just re-order the columns. And then put n/a in the HTML cell if markdown isn't supported on that channel.

**Comment by danmarshall** [comment]
Table has been updated.

**Comment by billba** [comment]
Much clearer, thanks!

**Comment by MathBunny** [comment]
Hello, how would I render a table then inside a WebChat? Is it possible? I previously used to render tables through my bot

**Comment by AmolPawarGitHub** [comment]
HTML in iframe webchat does not render.I have used HTML tags like table tags to show data in bot and now the output looks like a mess. What is the solution for this?

**Comment by corinagum** [comment]
Fixed in v4
