### ISSUE TITLE
Change speechSynthesizer voicename in Node js

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/BotFramework-WebChat#605]
I have created a bot in node js and it can now talk. How can I change its voce it JessaRUS for example? Is there a bot.set('speechOptions', speechOptions)? and set voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'? Thank you!

**Comment by danmarshall** [comment]
@shahidkhuram can you help?

**Comment by nwhitmont** [comment]
duplicate of: https://github.com/Microsoft/BotBuilder/issues/3231

**Comment by danmarshall** [comment]
@shahidkhuram ping :)

**Comment by shahidkhuram** [comment]
As Nils responded earlier, i think this is a dupe and should be closed. Let me know if there's a remaining issue.
