### ISSUE TITLE
Speech sample is downloading Google jquery code from non-secure URL

### ISSUE THREAD

**Issue by tiloc** [Microsoft/BotFramework-WebChat#607]
in samples/speech/index.html, there is a download of jquery code from Google at http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js

Unfortunately, if one hosts the webchat on a secure website, this leads to Chrome complaining about "unsafe scripts", and subsequently to a failure of the speech recognition.

I changed this to download from http**s**, which is also the URL that Google is giving in their docs. This resolves the issue.

**Comment by danmarshall** [comment]
Good catch @tiloc, would you mind sending the fix as a pull request?

**Comment by billba** [comment]
The ideal thing would be to get rid of jquery completely. It's only used in some commented-out code to make an HTTP call which can easily be done in modern browsers with `fetch`...

**Comment by compulim** [comment]
A quick search over `$.ajax` or `$.getJSON`, it only appears at [samples/speech/index.html:101](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/speech/index.html#L101).

@billba do you mean changing this call from `$.ajax` to `fetch`?

**Comment by billba** [comment]
@compulim that is what I'm proposing. Death to jQuery!

**Comment by tiloc** [comment]
@danmarshall it seems that @compulim is far more familiar with modern-day Javascript than I am. I propose he does the honors of fixing this.

**Comment by compulim** [comment]
Will take it.
