### ISSUE TITLE
Don't show the time-stamp if the messages received / sent   within 1 min difference.

### ISSUE THREAD

**Issue by iamgraviteja** [Microsoft/BotFramework-WebChat#608]
Is there a way to show the time-stamp on messages with time difference of 1 or more minutes as for the messages in iPhone

**Comment by billba** [comment]
At present that would be something you would have to customize yourself by changing the code in History.tsx, perhaps starting here: https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L214

**Comment by corinagum** [comment]
Fixed in v4, please check out our Sample called [timestamp-grouping](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/timestamp-grouping) for implementation!
