### ISSUE TITLE
ThumbnailCard image not displayed completely

### ISSUE THREAD

**Issue by 20112077** [Microsoft/BotFramework-WebChat#609]
Hi
I am sending a thumbnail card to the user. In the bot emulator it looks fine 
![botemulator](https://user-images.githubusercontent.com/9118855/28782510-9c3b6ede-760d-11e7-96da-a7fa717b4527.PNG)

But when open in the browser(at least in safari and chrome) with webchat.botframework.com/embed/... it is cut off on the right side.

![bildschirmfoto 2017-07-31 um 16 32 04](https://user-images.githubusercontent.com/9118855/28782589-e1aa72c6-760d-11e7-86df-0dce24532741.png)

How can I solve this?

**Comment by danmarshall** [comment]
Hello @20112077 can you provide the JSON and url to the image?

**Comment by 20112077** [comment]
@danmarshall, here is the json with the image link:
{
  "type": "message",
  "timestamp": "2017-07-31T17:59:36.209Z",
  "serviceUrl": "http://127.0.0.1:50678",
  "channelId": "emulator",
  "from": {
    "id": "b44a767caiihjm1hf",
    "name": "Bot"
  },
  "conversation": {
    "id": "9l06kid958583k2f"
  },
  "recipient": {
    "id": "default-user"
  },
  "membersAdded": [],
  "membersRemoved": [],
  "text": "",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.thumbnail",
      "content": {
        "title": "Hallo, ich bin Mr. Boie!",
        "text": "Ich kann dir helfen, deine Fluggastrechte zu nutzen und deine Entschädigung zu bekommen. Bitte gib deine Frage ein.",
        "images": [
          {
            "url": "https://data73.blob.core.windows.net/mr-boi/mrboie.png"
          }
        ],
        "buttons": []
      }
    }
  ],
  "entities": [],
  "replyToId": "738n2dg9a57mj8lcmc",
  "id": "la3d1cimnma1lcfi",
  "localTimestamp": "2017-07-31T19:59:36+02:00"
}

**Comment by punitganshani** [comment]
We faced similar issue when we window is resized. The card or the left/right buttons in carousel doesn't resize or shift

**Comment by starlord-daniel** [comment]
I've found that a margin-left of 10px is added to the css in the class .wc-card.thumbnail img

If this is removed, the image is displayed as intended.

**Comment by compulim** [comment]
Seems related to carousel measurement issue. Do you have the Web Chat opened initially pretty narrow?

**Comment by starlord-daniel** [comment]
@compulim Unfortunately, this issue appears all the time - regardless of the window size

**Comment by corinagum** [comment]
@compulim, please investigate this issue in v4

**Comment by compulim** [comment]
In v4, we moved to another carousel component and this is no longer an issue.

On the other hand, we are using [`object-fit: cover`](https://css-tricks.com/almanac/properties/o/object-fit/) strategy. So depends on the content, the left/right hand side might be clipped to center the image.
