### ISSUE TITLE
Broken layout and links are not showing up

### ISSUE THREAD

**Issue by Wedeo95** [Microsoft/BotFramework-WebChat#611]
The text layout on the BotFramework-Webchat is not the same as Test in QnA Maker. 

This is what's produced on the BotFramework-Webchat:

on time.\n\n options:\n\n* Direct Debit Variable\n* Credit Card Variable*\n* One off Credit Card payments*\n\nAlternative payment options:\n\n* Direct Debit For Home\n* Telephone banking\n* Internet banking\n* Automatic payment\n* Credit/Debit card*\n* New Zealand Post*\n* Cheque\n\n We do not accept cash payments, please do not send cash via post.\n\n *Payment processing fees will apply.

Some of the link does not show up on the chat. 

Question:
Do you card

Answer:
We do accept credit card. Click [here](https://www.google.co.nz/?gws_rd=ssl) to find out more.

Result on QnA Maker Test:
We do accept credit card. Click here to find out more.

**Comment by GeekTrainer** [comment]
Can you please post the full markdown so I can better see what's happening?

**Comment by Wedeo95** [comment]
You can pay your Genesis Energy bill in a number of ways and we offer prompt payment discounts for every bill that is paid in full and on time.\n\n Log into [My Account](https://myaccount.genesisenergy.co.nz/web/myaccount) for the following payment options:\n\n* Direct Debit Variable\n* Credit Card Variable*\n* One off Credit Card payments*\n\n[Alternative payment](https://www.genesisenergy.co.nz/for-home-pay-bill) options:\n\n* Direct Debit For Home\n* Telephone banking\n* Internet banking\n* Automatic payment\n* Credit/Debit card*\n* New Zealand Post*\n* Cheque\n\n We do not accept cash payments, please do not send cash via post.\n\n *Payment processing [fees](https://www.genesisenergy.co.nz/for-home-pay-bill) will apply.

For the broken link:

We do accept credit card. Click [here](https://www.genesisenergy.co.nz/web/genesis-energy/genesis-news-item/-/asset_publisher/o9jxxMpUYybi/content/pay-your-power-bill-with-my-account?_101_INSTANCE_o9jxxMpUYybi_read_more=true) to find out more.

**Comment by danmarshall** [comment]
Can you also add a screenshot?

**Comment by compulim** [comment]
I guess this is because we disabled HTML in Markdown.

**Comment by GeekTrainer** [comment]
Tagging @danmarshall 

I remember this issue with an update to QnA Maker somewhere along the way that caused the markdown being returned to be in a format that the parser we're using didn't like. I am 99% certain a PR was submitted for this and the issue resolved (I wrote the code), but I can't seem to find it in the history. Not sure if Dan has any better memory of this than I do.

**Comment by danmarshall** [comment]
@GeekTrainer I believe it was the regex here: https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/FormattedText.tsx#L64

We have unit tests around this, so if this case is getting through we can add a test for it.

**Comment by GeekTrainer** [comment]
@danmarshall I think you're right. In that case, we can just close this; the issue was opened in September. (I'll let you close it)
