### ISSUE TITLE
Webchat cross browser compatibility

### ISSUE THREAD

**Issue by Sonatina** [Microsoft/BotFramework-WebChat#613]
Hi Team,

Is webchat fully supported on FF/IE browser.  I've used webchat node.js code, it is working in google chrome but not able to submit input in chatbot window in FF/IE browser. 

Below is the screenshot 
![ui error](https://user-images.githubusercontent.com/24564494/28872767-3b310fc6-77a8-11e7-9ba9-da6f1b99eb90.png)

**Comment by nwhitmont** [comment]
relates to https://github.com/Microsoft/BotBuilder/issues/3181#issuecomment-319583379

**Comment by nwhitmont** [comment]
relates to https://github.com/Microsoft/BotBuilder/issues/3181

**Comment by danmarshall** [comment]
Hi @Sonatina - can you provide repro steps, and browser version? It works in my Firefox 54.

**Comment by nwhitmont** [comment]
Works fine for me on Firefox Developer Ed. 55.0b14 (64-bit) (macOS 10.12.6)

**Comment by SiddheshwarKore** [comment]
how about IE?doesnt work well in IE @danmarshall

**Comment by danmarshall** [comment]
Hello @SiddheshwarKore and @Sonatina - can you please give us details so that we can reproduce the error? It would be helpful if you can provide:
* Platform / os
* Browser type / version
* A URL to your chat if possible
* The message which reproduces the error condition
Thanks!

**Comment by danmarshall** [comment]
Hello all, from other similar issues I am going to guess that this issue may be caused when the WebChat is initialized while it is not displayed. The WebChat will need to be able to measure it's bounding rectangle at the time it is initialized. See https://github.com/Microsoft/BotFramework-WebChat/issues/515
