### ISSUE TITLE
Clicking on a Button should not open keyboard on mobile

### ISSUE THREAD

**Issue by macrozone** [Microsoft/BotFramework-WebChat#623]
https://github.com/Microsoft/BotFramework-WebChat/issues/411 leads to a (imho) huge usuability problem on mobile devices: clicking on a button opens the mobile keyboard, because the text-input gains focus.

This was mentioned in other issues, but i did not found an issue which describes exactly this problem, so i decided to open this new issue.

I did an attempt to disable this behaviour in https://github.com/Microsoft/BotFramework-WebChat/pull/456, but then you lose the scroll-to-bottom behaviour when you click a button.

I think the only acceptable way (from user perspective) is:

- clicking a button does not open keyboard
- clicking a button scrolls to bottom

**Comment by compulim** [comment]
@macrozone is it something like #363?

I am working on a fix to disable "force focus" on textbox, thus the mobile keyboard should not pop up as frequent.

**Comment by macrozone** [comment]
@compulim yes. Not as the original issue poster suggested, but exactly like you and @danmarshall described the problem.

I see that there are conflicting behaviours on mobile and on desktop. Desktop should keep focus on text-box as most as possible, while on mobile, focus on text-box should only be set when user actually taps in the text-box

**Comment by compulim** [comment]
@macrozone Could you try out my build at [compulim/BotFramework-WebChat/feat-focus](https://github.com/compulim/BotFramework-WebChat/tree/feat-focus)? I throw out all JS-based `focus()` code. And added one `focus()` for desktop (or device that have an always-on keyboard).

Or you could wait a couple days when I have my PR in master.

**Comment by macrozone** [comment]
@compulim i am on it, but i did not manage to install it directly from github. i try yarn link now

**Comment by compulim** [comment]
Great to hear it works, @macrozone.

There are some cross browser issues we need to fix before checking in the PR. Stay tuned.

In the meanwhile, please track #363. I will close this bug by duplicate.

**Comment by pratyushdhanuka** [comment]
I have found the solution to this by updating the botchat.js a little bit

around line 6951 in botchat.js
you will find this function

```
e.prototype.doCardAction = function (t, e) {
                    return this.props.setFocus(), this.props.onClickCardAction(), this.props.doCardAction(t, e)
},
```

here in setfocus() should not be triggered for mobile views
I had another function to check for mobile devices 
using 
[(https://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device-in-jquery)]
`    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
        return true;
    }`

and using this I updated the prototype.doAction method to 
`e.prototype.doCardAction = function (t, e) {
                    return !IsMobile() && this.props.setFocus(), this.props.onClickCardAction(), this.props.doCardAction(t, e)
                },`
