### ISSUE TITLE
carousel card height issue

### ISSUE THREAD

**Issue by Sonatina** [Microsoft/BotFramework-WebChat#629]
Hi, 
I need to reduce carousel card height so that it will well fit to chat window. I tried providing height property in the div but image and buttons inside carousel card  are not getting adjusted as per the carousel card height.

**Comment by danmarshall** [comment]
Hello, can you provide a sample JSON of the card, and a screenshot?

Generally, a Hero card will display all text that you provide. If you want to limit the display, you can use an [Adaptive Card](http://adaptivecards.io/), where you design and create your own layout constraints. For [TextBlock](http://adaptivecards.io/explorer/#TextBlock), there is a `maxlines` property that may be useful in your scenario.
