### ISSUE TITLE
CognitiveServices.js failing continuously, with verbose logging

### ISSUE THREAD

**Issue by eanders-MS** [Microsoft/BotFramework-WebChat#634]
Speech to text was working working earlier today for my bot, but I'm now seeing the following error in the Bot Framework Emulator's log stream. This log message quickly filled the log output window, freezing the emulator:
![image](https://user-images.githubusercontent.com/12176807/29199467-0916e6d6-7e02-11e7-8e10-4f9773e3ad42.png)

**Comment by eanders-MS** [comment]
This happened again after emulator restart. I believe these are the repro steps:
1. Connect to your bot with the emulator.
2. Use speech-to-text.
3. Wait for a long time, leaving the emulator open but idle (an hour or so).
4. Try to use speech again.

Result: You see the error above.
Expected: Speech-to-text operates without error.

**Comment by danmarshall** [comment]
@shahidkhuram @w-Yuan can you look into this?

**Comment by shahidkhuram** [comment]
@RaviPidaparthi any known issues in the speech JS SDK around connection timeout and re-initiation? Anything else you can think of that would fail start recognition with an InvalidOperation?

**Comment by compulim** [comment]
Seems fixed. Closed now.
