### ISSUE TITLE
My Bot is not receiving audio recorded by microphone icon.

### ISSUE THREAD

**Issue by mrctito** [Microsoft/BotFramework-WebChat#635]
My Bot is not receiving audio recorded by microphone icon.

When I press microphone icon and start to talk, the emulator imediatly translate what I am sayng to text and show it inside text writing box. Therefore, the bot emulator does not call my ApiController, as it should do.

Thus, my method "public async Task Post([FromBody]Activity activity)" is never called.

Thank you!

**Comment by compulim** [comment]
Closed due to inactivity.
