### ISSUE TITLE
Sending empty suggestedActions causes issues

### ISSUE THREAD

**Issue by michael-golfi** [Microsoft/BotFramework-WebChat#636]
Hi, I worked with @eanders-MS to figure this out. 

I'm writing a bot using REST endpoints and implemented my own connector in go. The messages don't render in the bot emulator webchat if there's an empty suggestedActions struct.

I didn't find any documents that state what fields are necessary or optional for sending messages... So I wasn't completely sure what was going on, there's a more detailed walkthrough of the issue already in Microsoft/BotFramework-Emulator#268.

So if I send this message, the struct for suggestedActions is effectively null but still present and as a result this seems to crash the Webchat. When I omit that struct things seem to work perfectly. There doesn't seem to be a meaningful log message associated with this either. The best I get is: `[err-client] Uncaught TypeError: Cannot read property 'length' of null C:\Users\migolfi\AppData\Local\botframework\app-3.5.31\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js`

```json
{
  "channelId": "emulator",
  "conversation": {
    "id": "dm96ggck03m4",
    "isGroup": false,
    "name": ""
  },
  "from": {
    "id": "default-bot",
    "name": "Bot"
  },
  "locale": "en-US",
  "localTimestamp": "2017-08-11T12:56:56.0157371-07:00",
  "recipient": {
    "id": "default-user",
    "name": "User"
  },
  "relatesTo": {
    "activityId": "h8cg3990l6fk",
    "bot": {
      "id": "default-bot",
      "name": "Bot"
    },
    "channelId": "emulator",
    "conversation": {
      "id": "dm96ggck03m4",
      "isGroup": false,
      "name": ""
    },
    "serviceUrl": "http://localhost:51129",
    "user": {
      "id": "default-user",
      "name": "User"
    }
  },
  "replyToId": "h8cg3990l6fk",
  "serviceUrl": "http://localhost:51129",
  "suggestedActions": {
    "to": null,
    "actions": null
  },
  "text": "Hello User!",
  "textFormat": "plain",
  "timestamp": "2017-08-11T19:56:56.0157371Z",
  "type": "message",
  "id": null
}
```

**Comment by danmarshall** [comment]
Hi @michael-golfi , can you eliminate the `suggestedActions` property, if the `to` is null, and the `actions` is null?

**Comment by michael-golfi** [comment]
Ya that's exactly what I did and it works now. But it wasn't clear from the docs or log that this field being present but unused would cause issues.

**Comment by eanders-MS** [comment]
The crash is happening in this code from MessagePane.tsx:
```js
function activityWithSuggestedActions(activities: Activity[]) {
    if (!activities || activities.length === 0)
        return;
    const lastActivity = activities[activities.length - 1];
    if (lastActivity.type === 'message'
        && lastActivity.suggestedActions
        && lastActivity.suggestedActions.actions.length > 0
    )
        return lastActivity;
}
```

`lastActivity.suggestedActions.actions` is assumed to be a valid array type, but it can be null. This is where I saw it fail in my repro case, but it's possible this isn't the only place in the codebase where this assumption is made.

**Comment by michael-golfi** [comment]
I was more wondering if it's possible to emit an error message when this stuff happens, I didn't notice anything obvious in the logs when I was crashing the emulator/webchat.

It also seems that once the webchat crashes, no further messages appear or work.

**Comment by billba** [comment]
@michael-golfi what we ought to be doing on unexpected errors like this is to (a) log the error and (b) recover from it. In other words, malformed data should not take down WebChat.

**Comment by eanders-MS** [comment]
It may be appropriate to validate incoming activities against a JSON schema representing what a well-formed Activity should look like.

**Comment by billba** [comment]
I'd still want to make the code as bulletproof as possible, and `catch()` any errors, at which point I'm not sure such validation would add anything.

**Comment by michael-golfi** [comment]
The schema seems to be already in place in [Direct Line](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts). The actions field on SuggestedAction is required but when it's null it seems to crash the webchat based on the condition check @eanders-MS posted.

In the type def below, suggestedActions is optional (intentional) but actions inside suggestedActions is required (in theory). But if I provide the example I gave above, the suggestedActions is allowed to have a null actions property which shouldn't be the case if I understand the scenario correctly. I also noticed that strict null checking is disabled in the tsconfig... Can the property be made non-null to avoid edge cases like this?

**Breaking Example**
```json
"suggestedActions": {
    "to": null,
    "actions": null
  }
```

**Message Interface**
```typescript
export interface Message extends IActivity {
    type: "message",
    text?: string,
    locale?: string,
    textFormat?: "plain" | "markdown" | "xml",
    attachmentLayout?: AttachmentLayout,
    attachments?: Attachment[],
    entities?: any[],
    suggestedActions?: { actions: CardAction[], to?: string[] },
    speak?: string,
    inputHint?: string,
    value?: object
}
```

**Comment by billba** [comment]
TypeScript is purely compile-time. Setting strict null checking won't change runtime behavior, which is what we're seeing here.

**Comment by danmarshall** [comment]
Agree that the code needs more bulletproofing. There may be an additional bug where we are not respecting the `to` field. In theory, this maybe a group conversation and the suggestedActions are presented to only specified users.

**Comment by corinagum** [comment]
Tracking on related issue #1103
