### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jessegoraya** [Microsoft/BotFramework-WebChat#638]
Hello,
I would like to make some changes to WebChat in order to make it work with the Grommet design component library.  I have cloned the WebChat git library and get the following error.

Does anyone have any ideas on how best to resolve this so that I can properly build the cloned project?

>npm install botframework-webchat

> botframework-webchat@0.11.1 prepublish C:\Users\jgora\OneDrive\Documents\BloomSky\BotFramework-WebChat
> tsc && npm run build-css && webpack --progress --config webpack.production.config.js

error TS5023: Unknown compiler option 'importHelpers'.
error TS5023: Unknown compiler option 'jsx'.
error TS5023: Unknown compiler option 'lib'.

npm ERR! addLocal Could not install C:\Users\jgora\OneDrive\Documents\BloomSky\BotFramework-WebChat
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "botframework-webchat"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! botframework-webchat@0.11.1 prepublish: `tsc && npm run build-css && webpack --progress --config webpack.production.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botframework-webchat@0.11.1 prepublish script 'tsc && npm run build-css && webpack --progress --config webpack.production.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the botframework-webchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && npm run build-css && webpack --progress --config webpack.production.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs botframework-webchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls botframework-webchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jgora\OneDrive\Documents\BloomSky\PatientTab\npm-debug.log

**Comment by compulim** [comment]
@jessegoraya Can you give us some version information?

What's your npm/node version? `npm --version` and `node --version` would help.

If you have a globally installed TypeScript, can you print it here too? (Run `tsc --version`)

**Comment by jessegoraya** [comment]
compulim thank you for your assistance.  Below is the information you requested.

npm version: 3.10.10
node version:  6.10.2
tsc version: TS6029: Version 1.5.3

**Comment by compulim** [comment]
I am not exactly sure, but TSC `1.5.3` seems a bit too old to me. Try latest one like `2.4.x`. 😉

**Comment by billba** [comment]
WebChat is currently locked to TypeScript 2.3.0. You probably need to build with that specific version.

Closing as not an issue with WebChat.
