### ISSUE TITLE
Typing indicater not coming in webchat

### ISSUE THREAD

**Issue by rachita0311** [Microsoft/BotFramework-WebChat#639]
I have a scenario in which I have to preserve my conversations in chat window. For this I have saved the conversation Id in local storage and set web socket = false. Setting web socket to false has stopped my typing indicator to come. 

```
   botConnection = new BotChat.DirectLine({
                secret: params['s'] || 'secretKey',
                token: params['t'],
                domain: params['domain'] || 'https://directline.botframework.com/v3/directline',
                webSocket: false,
                conversationId: conversationIdObj
            });
```

if I set websocket to true, the chat history goes away. Could anyone please help me know how to get typing indicator in such scenario

**Comment by billba** [comment]
I don't understand. Can you provide more details in a "when the user does this, I expect this, but instead this happens" format?

**Comment by rachita0311** [comment]
Basically the scenario is like when user writes something, the response from bot is taking time as it fetches data from database. During that time I want to show typing indicator gif playing. 
But as I have to maintain my chat history I have to send web socket as false. So my typing indicator is not working

**Comment by danmarshall** [comment]
Are you "toggling" the webSocket flag in the middle of a conversation? If so, you shouldn't. 

The "typing" feature requires webSocket to be true. It should be set to true when you initialize the WebChat control. There is no further interaction with the WebChat options.

**Comment by billba** [comment]
Yes, unfortunately 'typing' is only sent with webSockets. So for now you'll have to choose between one or the other.

**Comment by compulim** [comment]
@rachita0311 is your web history problem related to #365?

**Comment by telkomops** [comment]
Typing is sent with out without WebSockets.

**Comment by billba** [comment]
@telkomops your last comment confused me. To summarize, you want to maintain history so you are not using WebSockets, which means you are not getting the typing indicator. If this is correct, I'm afraid there is no workaround until the 'no history with websockets' bug is fixed.

**Comment by compulim** [comment]
@rachita0311 Typing in non-WebSocket is not supported on Direct Line, so we are not able to get the "typing" event. There are workaround mentioned by @EricDahvlang in #872.

And since DirectLineJS cannot be stopped/paused once it is up, we currently don't support switching DirectLine object on-the-fly. Even though we preserve the history, you will see multiple network requests done by DirectLineJS.

So I would suggest you to keep using WebSocket.

**Comment by keshavnagpal** [comment]
Hi @compulim 
Is there a way that we can get the chat history and keeping the webSocket: true
I've been trying to go through several threads on webchat and used conversationId to fetch the history but have to make the webSocket:false.
