### ISSUE TITLE
Provide Location

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#64]
WebChat might be able to provide the user's location if they so choose. This feature might be lower priority but just getting this on the books.

**Comment by amitbend** [comment]
Any update @danmarshall ?
This can be very helpful.

**Comment by danmarshall** [comment]
@amitbend no updates at this point.

**Comment by compulim** [comment]
@amitbend I am closing this because dupe of #987. Let's track it over there.

Stay tuned, it's pretty high on our radar now.
