### ISSUE TITLE
SuggestedActions pushes the top of the chat behind the header bar

### ISSUE THREAD

**Issue by MRowley1** [Microsoft/BotFramework-WebChat#640]
When the div for suggested actions buttons is present, the message group ~~content~~ div is displaced upwards but doesn't take into account the header being there. So the top part of the first message will be stuck behind it, even if the user scrolls to the very top. It returns to normal once the suggested actions have disappeared.

- [Before Suggested Actions, scrolled to top](https://user-images.githubusercontent.com/11547914/29302493-b79d8abe-81d8-11e7-9295-191d0685995a.png)

- [During Suggested Actions, scrolled to top (first line of top message is stuck behind the header)](https://user-images.githubusercontent.com/11547914/29302489-b79a1938-81d8-11e7-8bca-6a37712d8e12.png)

edited for clarity

message group in correct position
![](https://user-images.githubusercontent.com/11547914/29347529-6080088c-82a1-11e7-9dc3-10c888006ed5.png)

message group displaced by suggested actions, so the top is blocked by the header
![](https://user-images.githubusercontent.com/11547914/29347547-7b39afca-82a1-11e7-9ada-2e428ccc4b87.png)

**Comment by MRowley1** [comment]
For the record, the screenshots were taken in Chrome but the same issue occurs in IE.

**Comment by danmarshall** [comment]
Hi @MRowley1, yes the top of the message scrolls behind the header, the same as when you have many messages to be scrolled.We want the bottom message to be visible when suggested are displayed.

**Comment by MRowley1** [comment]
My point is that it's stuck behind the header, it's impossible to view the top of the first message while the suggested action bar is showing. That fourth image is as far up as you can scroll, the first line is completely obscured.

**Comment by shrikarch** [comment]
![image](https://user-images.githubusercontent.com/6672488/35065391-27fa9c66-fb9b-11e7-9c82-64e1235b85c0.png)

Not sure if the issue is only with the suggested actions. This is while trying a normal conversation. 
Although this screenshot is of the emulator, I am experiencing the same problem with WebChat.

**Comment by MRowley1** [comment]
I had noticed that on the emulator recently, but while the result looks pretty similar I get the feeling it's a different issue. That looks like an issue with calculating the actual available screen size, whereas this is specifically about the div being displaced by another on the webchat.
