### ISSUE TITLE
NPM 404 Error Upon Build

### ISSUE THREAD

**Issue by jessegoraya** [Microsoft/BotFramework-WebChat#641]
Cloned WebChat Repo through GitHub
In Node.JS navigated to the folder with the cloned repo and did a NPM Install
Received an error stating "Refusing to install package with name "botframework-webchat" under a package also called "botframework-webchat"
So I went to package.json and changed the name to "botframework-webchat-jgfork"
Try NPM install again and get the error below...

C:\Users\jgora\OneDrive\Documents\BloomSky\BotFramework-WebChat>npm install botframework-webchat-elu
npm ERR! code E404
npm ERR! 404 Not Found: botframework-webchat-elu@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jgora\AppData\Roaming\npm-cache\_logs\2017-08-15T11_40_27_730Z-debug.log

This looks it should be relatively easy to resolve but can't seem to resolve the issue.  Any ideas?

**Comment by billba** [comment]
when you say "did a NPM Install" do you mean you just typed "npm install"?

**Comment by jessegoraya** [comment]
That is correct.  I just typed `npm install`
