### ISSUE TITLE
Rearranging Web Chat Component parts layout

### ISSUE THREAD

**Issue by jessegoraya** [Microsoft/BotFramework-WebChat#646]
I have added the Web Chat component to my React site and it works great. However the component itself seems to be laid out incorrectly as it applies the styling of the overall parent design library (Grommet) but pieces of the component itself are laid out in disarray. See picture below.

Picture of Web Chat component within my React Site![web chat changes](https://user-images.githubusercontent.com/27831702/29561243-ca2ae7f6-8702-11e7-9672-534ce3476c0b.png)

Does anyone have ideas on how I can change the layout of the Web Chat component while keeping the overall styling of the parent Grommet design library? I'd prefer not to forking the web chat component since the functionality is what I need just need to re-arrange the layout/spacing which isn't to my liking.

**Comment by danmarshall** [comment]
Hi @jessegoraya you should be able to look at our css file to see how we do it, then apply similar css in your solution.  Will that work for you?

**Comment by jessegoraya** [comment]
@danmarshall thanks for reaching out.  So within the CSS I  can control things such as the placement of the buttons and the spacing?  If so that's great, I'll take a look at the CSS.

Once again thanks for the help.

**Comment by danmarshall** [comment]
@jessegoraya yes, I suggest that you start with our stylesheet as-is, then remove things that you don't want/need. That may be easiest.

**Comment by jessegoraya** [comment]
@danmarshall.  Thanks will do.
