### ISSUE TITLE
Is there a way to prevent autocorrections on a user defined list of words and phrases?

### ISSUE THREAD

**Issue by persianturtle** [Microsoft/BotFramework-WebChat#648]
I was hoping there could be an option that would accept a list of words and phrases to "add to dictionary."

```
BotChat.App({
        directLine: { secret: direct_line_secret },
        user: { id: 'userid' },
        bot: { id: 'botid' },
        resize: 'detect',
        dictionary: [
          'word or phrases here',
        ],
      }, document.getElementById("bot"));
```

**Comment by JasonSowers** [comment]
Could you explain a little more about your use case here?  
  
Is there an HTML 5 feature that does this?  The webchat control wouldn't have access to the OS autocorrect.

**Comment by persianturtle** [comment]
For completeness, my use case is the following:

Currently, using the out-of-the-box [webchat client](https://github.com/Microsoft/BotFramework-WebChat) & Chrome browser on Mac OS X, typing in words that are not recognized get a red line underneath.

<img width="170" alt="screen shot 2017-08-23 at 5 36 17 pm" src="https://user-images.githubusercontent.com/3474647/29639708-afc25eee-8829-11e7-9bc3-2be4e79092bb.png">

I'm glad to know that webchat isn't involved.

I'll explore ways to control this with HTML5/JavaScript.

Thank you for your quick response.

**Comment by persianturtle** [comment]
It looks like adding the following attributes to `.wc-textbox` does the trick nicely:

```
autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"
```

source:
https://stackoverflow.com/questions/254712/disable-spell-checking-on-html-textfields

**Comment by danmarshall** [comment]
Thanks @persianturtle. I don't suppose all developers will want this by default. You can also set this in source code [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Shell.tsx#L94) in your own build.
