### ISSUE TITLE
[botchat.js] Expose bundled Rx as global

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#653]
*This only relates to the CDN / Webpacked botchat.js*

If someone wants to use both WebChat and some additional RxJS on the page, they will need to re-download a copy of RxJS, even though it is already bundled.

Can we expose RxJS [the same way as Adaptive Cards](https://github.com/Microsoft/BotFramework-WebChat/blob/master/webpack.production.config.js#L39)?

**Comment by danmarshall** [comment]
@billba I've had 2 customers with this scenario. I know they can just rebundle their own way.

**Comment by billba** [comment]
Yay people who use RxJS!

I tend to think of the CDN/bundle as something to use atomically, where there isn't a client app. If they are building a client app, they are already creating their own bundle, and at that point it's a lot more efficient for them to pull WebChat into their build/bundle, and share a common instance of RxJS.
