### ISSUE TITLE
Should <br/> be rendered in Markdown mode in Emulator?

### ISSUE THREAD

**Issue by v-ducvo** [Microsoft/BotFramework-WebChat#658]
When textFormat is set to "markdown", the code converts br tags to "\n\r"...to keep things straight, XML tags should not be accepted when textFormat is set to "markdown". Here is where that replace happens in the code:

https://github.com/Microsoft/BotFramework-WebChat/blob/ac769d76121134c9280d70909ffaf1b0e1acaf48/src/FormattedText.tsx#L57

----

Also - a related issue is that multiple line breaks are being replaced with just one. Meaning, if I sent "<br/><br/>" or "\n\n" then I expect to see two line breaks. Right now, it doesn't matter how many line breaks I put in, I'm only getting 1 line break in the Emulator rendering.

**Comment by reyesrico** [comment]
Since all HTML tags are disabled (#606), Tag `<br/>` must not be rendered. Below you will find the fixing PR.

**Comment by v-ducvo** [comment]
Hi Carlos,

Thanks for notifying me about this update. I double checked the messaging currently in our docs and found that no action is needed at this time regarding this update. We are already stating that HTML is not supported in Markdown:

[cid:image001.jpg@01D362AF.6B9370E0]

Here’s a link to the topic:
https://docs.microsoft.com/en-us/bot-framework/portal-channel-inspector


Regards

Cash Vo (Aquent LLC)

**Comment by reyesrico** [comment]
@tjoudeh fortunately you can. Below you will see the current server content test where simulates a bot sending messages with different line breaks (you can use \n\n\n\n) and then are validated by the nightmare tests.

https://github.com/Microsoft/BotFramework-WebChat/blob/f3979f0290b10168e80ef88a0ed350a36ca80154/test/server_content.ts#L403

**Comment by tjoudeh** [comment]
Thank you, looks like this is part of the release [0.11.4](https://github.com/Microsoft/BotFramework-WebChat/releases/tag/v0.11.4) will update to this version and test it out.
