### ISSUE TITLE
How to use in react native app

### ISSUE THREAD

**Issue by karangarg45** [Microsoft/BotFramework-WebChat#666]
Is it possible to use this in react native app without using iframe?

**Comment by danmarshall** [comment]
Hi @karangarg45 if you are a React Native developer, please try it out and let us know :)

First, I can say that we aren't using the `react-native` compiler switch in [TypeScript's JSX](https://www.typescriptlang.org/docs/handbook/jsx.html).

Second, I don't know if React Native supports HTML tags. There seems to be Native elements like [`<ScrollView>`](https://facebook.github.io/react-native/docs/using-a-scrollview.html) that we don't have.

We are open to the community's input though! Would love to see someone making this work.

**Comment by karangarg45** [comment]
Hi @danmarshall i already trying integrating it with a react-native app.But i am getting some error and it's not working. I suspect it's because there is no such concept of dom in react-native and i am getting the error around react-dom library only.

**Comment by billba** [comment]
From what little I understand, a React Native version of WebChat would require substantial code differences from the Web version. It would be an interesting project, and I'd love to see what common code could be extracted out for use by both, but we have no plans to develop such a thing internally.

**Comment by diegorodriguesvieira** [comment]
@karangarg45 hey bro, just if you need it yet
this can help you

**Comment by Hirurgo** [comment]
@diegorodriguesvieira nice, thank you, but did't catch can we use this for voice interaction
