### ISSUE TITLE
Refactoring types and action factories from Chat.tsx into their own files

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#671]
Currently, [`test/history.ts`](../blob/master/test/history.js) is depending on [`Store.ts`](../blob/master/src/Store.ts), and is depending on [`Chat.tsx`](../blob/master/src/Chat.tsx). And that means our Mocha tests that target Redux, is also loading React code, before running the test in Node.js.

The [code in `Store.ts`](../blob/master/src/Store.ts#L2) that import [`Chat.tsx`](../blob/master/src/Chat.tsx) is attached below. It is loading some types and [action factories](../blob/master/src/Chat.tsx#L35).

```js
import { FormatOptions, ActivityOrID, konsole, sendMessage as sendChatMessage } from './Chat';
```

I think we should put an isolation between Redux and React code by refactoring out types and action factories into their own files.

**Comment by billba** [comment]
Makes sense. I favor:
* pulling `sendMessage`/`sendFiles` into Store.ts with all the other redux stuff
* putting `FormatOptions`, `ActivityOrId` and other types into a new Types.ts
* putting `konsole` into a new Konsole.ts (or Utilities.ts) file

**Comment by compulim** [comment]
That's what I am thinking too.

What do you think about splitting up `Store.ts` into `Actions.ts`, `ActionFactories.ts`, `Reducers.ts`, and `Store.ts`?

**Comment by danmarshall** [comment]
Perhaps `Actions.ts` might be `ReduxActions.ts` for disambiguity of BF buttons.

**Comment by compulim** [comment]
Or in its own folder, like `Redux/Store.ts`?

**Comment by billba** [comment]
I like the strategy of not creating more structure than is necessary. There's not really a problem having all the Redux stuff in one file. Makes its easy to jump around between actions and factories and reducers and epics. They're all pretty interrelated. So since it's not causing a problem... I say leave it as it is for now.

**Comment by compulim** [comment]
Done in #672.
