### ISSUE TITLE
Image size increases compare to original size in HeroCard on SharePoint

### ISSUE THREAD

**Issue by EnnamGopaulen** [Microsoft/BotFramework-WebChat#676]
Hello,

I have a carousel that display a set of choices with images using adaptive card. But the size of the images have increased compare to its original size (150px **x** 150px)

Note that it is on SharePoint in an iframe.

Find below code and picture:

```
exports.dispalyCarousel = function (session, options) {
    var cards = getCardsAttachments();

    var reply = new builder.Message(session)
        .attachmentLayout(builder.AttachmentLayout.carousel)
        .attachments(cards);

    session.send(reply);
};
```

Extract of code below:

```
function getCardsAttachments(session) {
    return [
        new builder.HeroCard(session)
            .title('Navision')
            .subtitle('Créer un client sur Navision')
            .images([
                builder.CardImage.create(session, 'url_to_the_image')
            ])
            .buttons([
                builder.CardAction.imBack(session, 'Navision', 'Navision')
            ]),
```

![img4](https://user-images.githubusercontent.com/24710468/30161941-bc31ee90-93e3-11e7-9f0f-4e34e87cbe69.png)

Thanks to help.

**Comment by danmarshall** [comment]
Hi @EnnamGopaulen - does this repro outside of SharePoint, in other browsers?

**Comment by EnnamGopaulen** [comment]
Hello @danmarshall, thanks for your reply.

Yes this repro outside of SharePoint in Chrome and Ms Edge.

**Comment by danmarshall** [comment]
OIC - yes this is a HeroCard, so it is meant to be full-width of the card. The card is meant to be responsive to the size of the chat. So, on a wide screen, you may expect to see your image even larger. 

If you want a smaller pic, try using ThumbnailCard instead. Otherwise, you may want to use an [AdaptiveCard](https://github.com/Microsoft/BotFramework-WebChat/blob/master/AdaptiveCards.md#create-and-send-an-adaptive-card-from-your-bot) for a custom size of your image.

**Comment by EnnamGopaulen** [comment]
Hello @danmarshall,

Please note that this was working fine when I was using the HeroCard before, I noticed that there is a max-height : 100% and width: 100% tag that has been added while inspecting. 

![image](https://user-images.githubusercontent.com/24710468/30366259-927a14c8-987b-11e7-8131-f7f5c079e577.png)

I will not be able to use the Thumbnail Card as I want the image to be the same size.

And only the Hero and Thumbnail Cards are supported for the Carousel AttachmentLayout mode.

Thanks

**Comment by danmarshall** [comment]
Hi @ac-vikram, Adaptive Cards do work in carousel layout mode.
