### ISSUE TITLE
wc-shellinput value does not change after programatically injecting new value

### ISSUE THREAD

**Issue by ramgesg** [Microsoft/BotFramework-WebChat#680]
`$(".wc-shellinput").prop({value: "Welcome"})` changes the display value of the text box but does not make changes in value of input class...

`<input class="wc-shellinput" type="text" placeholder="Type your message..." value="" autocomplete="off">`

**Comment by billba** [comment]
This is a React app, so it maintains DOM state internally and updates from there. Manipulating the DOM directly will have unexpected results. Don't do that.

**Comment by danmarshall** [comment]
Agree this is not a bug. But, it could be a feature request. @ramgesg can you provide a scenario where you would inject text on the user's behalf?

**Comment by ramgesg** [comment]
@dan, this is for injecting onselect value from autosuggest.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by danmarshall** [comment]
Related to #476

**Comment by danmarshall** [comment]
We can continue this conversation in #476

**Comment by mrPrateek95** [comment]
Not a clean method but you can use this.

//Fill the input field : Using a Hack. This might break after the next React update
//Source: https://github.com/facebook/react/issues/11488
var input = document.getElementsByClassName("wc-shellinput")[0];
var lastValue = input.value;
input.value = **YOUR TEXT**;
var event = new CustomEvent('input', { bubbles: true });
// hack React15
event.simulated = true;
// hack React16
var tracker = input._valueTracker;
if (tracker) {
tracker.setValue(lastValue);
}
input.dispatchEvent(event);

$(".wc-send:first").click();

**Comment by Snekha-Shivakumar** [comment]
@mrPrateek95  Thank you for this. But, it works in chrome and firefox and not in IE. Any idea on this?

**Comment by mrPrateek95** [comment]
@Snekha-Shivakumar What version of IE are you using? I have tested it on IE11. Seems to be working there.

**Comment by Snekha-Shivakumar** [comment]
@mrPrateek95  I'm also using IE11 and I'm using this piece of code for auto complete. Here is my code:

var availableTags = [
.........
.........
];
    $('body').on('click', '.ui-menu-item', function() {
        var input = document.getElementsByClassName("wc-shellinput")[0];
        var lastValue = input.value;
        input.value = $('input.wc-shellinput.ui-autocomplete-input').val();
        var event = new CustomEvent('input', { bubbles: true });
        // hack React15
        event.simulated = true;
        // hack React16
        var tracker = input._valueTracker;
        if (tracker) {
        tracker.setValue(lastValue);
    }
    input.dispatchEvent(event);

    $(".wc-send:first").click();
    });
    var autocompleteOpendedFirstTime = false;
    var acWidth = $('.wc-shellinput').width();

    $(".wc-shellinput").autocomplete({
      source: function(request, response) {
        var results = $.ui.autocomplete.filter(availableTags, request.term);
        response(results.slice(0, 7));
      },
      minLength: 3,
      fluid: true,
      resizable: false,
      width: acWidth,
      position: {
        my: "left bottom",
        at: "left top-5"
      },
      open: function() {
        var position = $(".ui-autocomplete").position(),
          left = position.left,
          top = position.top;
        if (!autocompleteOpendedFirstTime) {
          autocompleteOpendedFirstTime = true;
          top = top;
        }
        var _width = $('.wc-message-groups').width() - 30;
        $(".ui-autocomplete").css({
          left: left + "px",
          top: top + "px",
          width: _width + "px"
        });
      }
    }).keyup(function (e) {
        if(e.which === 13) {
            $(".ui-menu-item").hide();
        }            
    });

On typing in the input box, after 3 letters suggestions start showing up. On clicking any of the suggestion, the user response goes with what we have typed in the input box(3 letters). This happens only in IE.
Can you please tell me what went wrong?

**Comment by Snekha-Shivakumar** [comment]
@mrPrateek95 Yeah I found the issue. new CustomEvent() is not working in IE. Just added a polyfill before the custom event and it works fine now. Here is the polyfill:

        (function () {
            function CustomEvent ( event, params ) {
            params = params || { bubbles: false, cancelable: false, detail: undefined };
            var evt = document.createEvent( 'CustomEvent' );
            evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
            return evt;
            };
            CustomEvent.prototype = window.Event.prototype;
            window.CustomEvent = CustomEvent;
        })();

Thank you.

**Comment by mrPrateek95** [comment]
@Snekha-Shivakumar Checked on my client. I have also added this polyfill. Slipped my mind earlier.

**Comment by gideon-harpanahalli** [comment]
Hey @mrPrateek95, 
I am trying to autofill input field when user types a question partially clicks on a button to autocomplete the question. This solution seems to not work in this case. The text previously entered text is sent rather than the text which is added programatically. Any suggestions to resolve this?

Code:
        // Event listeners
        $(document).on("click focus", ".suggestion-box", function () {
            const selectedQuestion = $(this).text();
            const inputElement = $(".wc-shellinput")[0]; // Get the DOM element from the jQuery object
            inputElement.value = selectedQuestion; // Set the value directly to the DOM element

            // Create a new event 
            var event = new CustomEvent('input', { bubbles: true });
            event.simulated = true;
            var tracker = input._valueTracker;
            if (tracker) {
                tracker.setValue(selectedQuestion);
            }
            // Dispatch the event on the input element
            inputElement.dispatchEvent(inputEvent);
            $(".wc-send:first").click();
        });
