### ISSUE TITLE
Add ability to set breakpoints in Web Chat (browser)

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#684]
Action items:
* [ ] Enable inline source code on source map for our monolithic version `*.js`
* [ ] Add `*.js.map` to `package.json/files[]`
* [ ] Make sure our CDN copy have the `*.js.map` files in

**Comment by billba** [comment]
Oh cool, I didn't know you could do that.

**Comment by corinagum** [comment]
Fixed in v3, needs to be fixed in v4

**Comment by compulim** [comment]
This is done.
