### ISSUE TITLE
Problem when scrolling through suggested actions with Skype Webchat Control

### ISSUE THREAD

**Issue by fms-santos** [Microsoft/BotFramework-WebChat#686]
Hey,
With the updated **Skype Webchat Control SDK**, I'm unable to scroll through the suggested actions I have on my bot.

Basically, when I click the arrow (->)  button on the bottom right corner, nothing happens and I can not see all the other actions.

Anyone else having the same issue?

My HTML code:
```
<span class="skype-button bubble " data-bot-id="XXX" data-color="#B71C1C"></span>
<span class="skype-chat" data-color-message="#b6bec9"></span>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
```
![Screenshot](https://user-images.githubusercontent.com/16543301/30283682-9e052a60-9710-11e7-8a7a-e60a2014b7f0.png)

**Comment by billba** [comment]
This is not the repo for the Skype WebChat control.
