### ISSUE TITLE
Support SVG images

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#689]
There's no reason WebChat shouldn't support attachments of type `image/svg+xml`. We can upload and download them, but they are not rendered because they are not on the [whitelist](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Attachment.tsx#L310) for rendering.

**Comment by danmarshall** [comment]
Hey SVG is just HTML in disguise, you sneaky guy! 😝

**Comment by billba** [comment]
Every atom is a universe.

**Comment by billba** [comment]
Ah I did more research and it turns out SVG files can contain scripting etc. So there is a good reason not to render them. They are not safe. Closing with extreme prejudice.
