### ISSUE TITLE
SharePoint Framework (SPFX) integration not working since 0.9 version

### ISSUE THREAD

**Issue by trikem** [Microsoft/BotFramework-WebChat#692]
The same issue as here: #667 

Since upgrade from version 0.9 to 0.11.2 a SharePoint Web Part with embedded chat bot fails to open a web part properties sidepane with this error:
```
TypeError: Cannot read property 'offsetWidth' of null
    at HistoryView.componentDidUpdate (History.tsx:50)
```

A chatbot window is visible all the time. Opening a properties sidepane doesn't hide the chatbot window.
Steps to reproduce:
1. File History.tsx row 50 
`const maxContentWidth = (this.carouselActivity.messageDiv.offsetParent as HTMLElement).offsetWidth - paddedWidth;`
2. After clicking "show web part parameters" this.carouselActivity.messageDiv.offsetParent equals NULL and throws an error.

**Comment by compulim** [comment]
This is fixed in #1003. This is because Web Chat is initially set to `display: none` when mounting.

We recommend not to hide Web Chat using `display: none` or `hidden` attribute. Only use `opacity: 0` or `visibility: hidden` (soft hide).
