### ISSUE TITLE
Is it possible to populate clientActivityId in backchannel while sending an activity of type message?

### ISSUE THREAD

**Issue by ramgesg** [Microsoft/BotFramework-WebChat#693]
Trying to send a message with the backchannel approach, but the sent message is not reflecting in the web chat. tried with a previous message's clientActivityId (manually copy pasted)and it seems to be the key.

Is it possible to generate the clientActivityId?

**Comment by billba** [comment]
You don't need/want a clientActivityId for a backchannel message. Can you share the bot code?

**Comment by ramgesg** [comment]
`const postButtonMessage = (msg) => {
            botConnection
                .postActivity({
                    "type": "message",
                    "text": msg,
                    "from": {
                        "id": "userid",
                        "name": "username"
                    }
                })
                .subscribe(id => console.log(id));
        }`

This posts a message, but does not reflect in the chat windows. Guess that's how it is meant to be

**Comment by billba** [comment]
Yes, that is the whole point of the backchannel....
