### ISSUE TITLE
Style Not Being Applied to Chat Control

### ISSUE THREAD

**Issue by jessegoraya** [Microsoft/BotFramework-WebChat#694]
I'm trying to do a seemingly easy thing but without much luck. I have a React app that uses the Grommet UX framework. In the app, I use the WebChat component which I would like to style.

Per the suggestion in [Issue #646 ](https://github.com/Microsoft/BotFramework-WebChat/issues/646) I created my own style sheet custom.scss.  However my styles don't seem to be referenced in the app.  It does look like the Grommet styling is being applied but my changes for the web component won't be overridden.  

Does anyone have any suggestions?

Any help would be very much appreciated.

App.js

```
import  '../scss/custom.scss';
...
class PatientApp extends React.Component {
...
render
...
<Chat className='wc-app' directline='GUID_Entered_Here />
```

Custom.scss

```
@import 'elu.defaults.scss';
@import '~grommet/scss/grommet-core/index.scss';

body .wc-app, .wc-app button, .wc-app input, .wc-app textarea {
    font-family: 'Segoe UI', sans-serif;
    font-size: 15px;
    background-color: #2AD2C9;
}
```

**Comment by billba** [comment]
Your `.scss` file should be compiled into a `.css` file which would be included in the your `.html` file, not in your `app.js` file as you have here.

**Comment by jessegoraya** [comment]
@billba thank you for responding.  I didn't think the scss reference was a problem since I have a loader which handles compiling of the SCSS in my webpack.config.js.  Shown below:
```

     {
        test: /\.scss$/,

        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&' +
        'includePaths[]=' +
        (encodeURIComponent(
            path.resolve(process.cwd(), './node_modules')
        )) +
        '&includePaths[]=' +
        (encodeURIComponent(
                path.resolve( process.cwd(),
                    './node_modules/grommet/node_modules'))
        )
        +
        '&includePaths[]=' +
        (encodeURIComponent(
                path.resolve( process.cwd(),
                    '../scss/'))
        )
      },
```

**Comment by billba** [comment]
Ah, I haven't done that myself so I can't help debug it. Maybe someone else can.

**Comment by jessegoraya** [comment]
@billba Thanks for reviewing it.

**Comment by jessegoraya** [comment]
Solved!  I was able to resolve this issue by making the following changes, just in case anyone else has something similar in the future.

app.js: Changed custom.scss: Add Height and Width properties to .wc-chatview-panel so that the chat pane appears docked on the left side of the screen
