### ISSUE TITLE
Bug with Prompts.time

### ISSUE THREAD

**Issue by jschristophe** [Microsoft/BotFramework-WebChat#700]
Hello,

In french, with Webchat, Prompts.time doesn't work with Aujourd’hui but works well with Aujourd'hui.

(the difference is in the characters ’ ' )

Unfortunately, the first version (Aujourd’hui) is suggested by default on ios 11.

Could you fix this bug please ?

Thanks

**Comment by billba** [comment]
That sounds like an SDK problem to me. Please report this bug to https://github.com/microsoft/botbuilder. I'm closing this issue, but let me know if I have this wrong.
