### ISSUE TITLE
Request improvement to intercept and modify/cancel messages

### ISSUE THREAD

**Issue by jschristophe** [Microsoft/BotFramework-WebChat#701]
It would be great if we could intercept message sended from client to bot to modify or cancel them before there are sended to the bot.

Currently, I can only intercept message with directLine (directLine.activity$.subscribe(function (activity) { ... ) but I can't modify theses activities.

Can you tell me if this feature is already implemented. If no, have you planed to implement it ?

Thanks,

**Comment by billba** [comment]
You can do this with client middleware. Have a look [here](https://github.com/Microsoft/BotFramework-WebChat/issues/395#issuecomment-289681256).
