### ISSUE TITLE
Checking whether the bot is online before showing chat window

### ISSUE THREAD

**Issue by alyssaong1** [Microsoft/BotFramework-WebChat#703]
From a UX perspective, it is necessary to check if the bot is online & responding to messages before showing the actual webchat to the user. To achieve this, I am proposing the following:

- Create a directline object and subscribe to the activity$ (using the [botframework-directlinejs client library](https://github.com/Microsoft/BotFramework-DirectLineJS))
- Monitor the connection status and check if it goes into ConnectionStatus.Online
- If it does, then initialize BotChat.App 

Can someone confirm that this is a sound approach, or point me into a better direction? Thanks!

**Comment by billba** [comment]
That makes sense to me. Please report back here if this works out for you.

A question: what if WebChat had a visually distinct "connecting" mode? Would you still need to do this?

**Comment by alyssaong1** [comment]
Great, thanks Bill - will do. A visually distinct "connecting" mode is even better from a UX standpoint in my opinion... especially in cases where the bot is not set to "Always on" and may take a while to start up. If the connection succeeds, then the user can start the conversation with the bot, otherwise, the chat window could show some sort of "offline" or "unavailable" mode.

**Comment by alyssaong1** [comment]
@billba I did a quick test and it works: https://github.com/alyssaong1/WebchatStatus
Basically checked for a successful direct line connection, and also check that the bot doesn't respond with any errors before showing the webchat view. Main logic is in public/js/index.js.

Any suggestions/improvements welcome! Am thinking of doing an implementation of what you suggested re the visually distinct "connecting" mode... or is this already currently in the works for webchat?

**Comment by billba** [comment]
Glad to hear it works. I'm going to close this issue.

I wouldn't hold your breath on the "connecting" mode...
