### ISSUE TITLE
Unwanted autoscroll when polling

### ISSUE THREAD

**Issue by Paveltarno** [Microsoft/BotFramework-WebChat#707]
Hi,
love the component, keep up the good work [=

When web sockets are disabled, WebChat resorts to polling (every 1 sec by default).
The server sends activities repeatedly and WebChat "ignores" them if their `channelData.clientActivityId` is already present in one of the shown activities.
Problem is, if the user is waiting more then one second for a reply from the bot while scrolling up and the polling kicks in, the `History` component thinks the incoming messages are freshly submitted by the user and autoscrolls down. This results in a glitch behavior as the user can't scroll up for more the one second.
IMO the chat pane should autoscroll only when a new message is actually submitted (the send button was clicked)

**Comment by nicksav** [comment]
@Paveltarno Pavel, how did you implement the history loading?

Thanks
Nick

**Comment by Paveltarno** [comment]
@nicksav As I'm using a custom backend I'm currently leveraging the `watermark` property to specify the number of messages I wan't to fetch from the server. However, this is obviously not a good solution as the server sends redundant data over and over again. I'm waiting for #615 to change this.

**Comment by nicksav** [comment]
@Paveltarno Pavel , I am looking for a good developer to help us with the bot, are you open for new job opportunities? (remote). Sorry to write here, can't find your email anywhere...

**Comment by compulim** [comment]
@Paveltarno preserve history is top ask and is coming.

I think we need to rework the autoscrolling. We should better detect if the scrollbar is near bottom (~10px threshold). And if it is, then we do auto scroll. Otherwise, we show a "scroll to bottom" button.

**Comment by corinagum** [comment]
Fixed in v4
