### ISSUE TITLE
Sending additional fields through BotChat.App

### ISSUE THREAD

**Issue by alyssaong1** [Microsoft/BotFramework-WebChat#710]
The "User" object in the bot-framework-directlinejs package states userid as a mandatory field, with an optional name field. Let's say the user logs in through the website and we now want to identify the current user by their login id. Technically, because the typescript interface does not do excess checks, we can add an additional loginid field to the "User" object to be passed to the bot, like this:

```js
BotChat.App({ 
       directLine: { secret: 'YOUR DIRECT LINE SECRET HERE' },
       user: { id: '1236342', name: 'Testuser', loginid: 'alyssaong1' }, 
       bot: { id: 'botid' }, 
       resize: 'detect' 
}, document.getElementById("bot")); 
```

While this implementation works, is it something that is encouraged? I don't see any problems with it but is there a chance that the "User" interface will be excess checked in future versions?

Note that I would not change the userid to the login id as this would make the bot think it is a new user.

**Comment by danmarshall** [comment]
@dandriscoll - does DirectLine remove "extra" properties? 
@alyssaong1 - if not, you may have to maintain a lookup elsewhere.

**Comment by billba** [comment]
With Direct Line, as with any protocol, you should never assume that undocumented behavior will be preserved. What works today will not necessarily work tomorrow.

In this case you'd also be depending on undocumented behavior on the part of DirectLineJS, which happens to send the entire `user` object along with each message, but may be more careful in the future.

Two better, and documented, ways to pass information like this are:
1. sending an `event` message to the bot with the user's loginId
2. sending the loginId in the `channeData` field of each message

The latter is a better fit for what you're doing now.

**Comment by alyssaong1** [comment]
Noted, thank you Bill!
