### ISSUE TITLE
IFrame webchat do not render HTML

### ISSUE THREAD

**Issue by AmolPawarGitHub** [Microsoft/BotFramework-WebChat#711]
I have incorporated IFrame into our web application. And now I can see that HTML does not render in the IFrame webchat. I am using .net SDK with C# for my chatbot development

**Comment by danmarshall** [comment]
Hi @AmolPawarGitHub - the webchat.botframework.com hosted version of Web Chat does not support HTML. See [this post](https://blog.botframework.com/2017/09/07/html-not-supported-web-chat/
) for details, and instructions to enable it in your self hosted copy.
