### ISSUE TITLE
WebChat with direct line doesn't work flow conversation

### ISSUE THREAD

**Issue by SilvaLA59** [Microsoft/BotFramework-WebChat#712]
Guys, I have an Intent on my code that I'm using flow conversation and this flow woks fine on another channels, but on WebChat it's doing only the first step of my flow. Who knows what may be happening?

**Comment by danmarshall** [comment]
Can you please give more details on the symptom. Is the web chat blank, do you see a message "retry"?

**Comment by SilvaLA59** [comment]
This example has 4 steps(4 functions in waterfall) inside the array, follwing this example it works well, but if I chat using WebChat with direct line the flow is stoped in the fist step(first function) and doesn't do next function.

[https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-dialog-manage-conversation-flow](url)

**Comment by billba** [comment]
Hmmm I write waterfalls like this all the time and they work great with WebChat.

**Comment by SilvaLA59** [comment]
Maybe is something wrong in my HTML...

![sem titulo](https://user-images.githubusercontent.com/18683665/31139862-3d3a89f6-a849-11e7-99d4-505cedef59bb.jpg)

**Comment by billba** [comment]
You must provide a valid user.id (name is optional).

**Comment by SilvaLA59** [comment]
Thank you @billba , before set user.id is it working now.
