### ISSUE TITLE
Sometimes send typing not shown in Web Chat..

### ISSUE THREAD

**Issue by VishalWaman** [Microsoft/BotFramework-WebChat#714]
Sometimes send typing not shown in Web Chat..

We are using Nodejs version "3.8.3"

**Comment by billba** [comment]
Please provide more details. One sentence is not a bug report. Do you have a reproducible case? You mentioned Node - does that mean you are using the Node SDK? Can you provide your bot code? What browser and OS are you using? Does this happen in the Emulator? In other channels? Are you certain that the `typing` activity is being sent from your bot?

**Comment by telkomops** [comment]
can anyone throw some light, on  when, the "typing" or send Typing event is sent to Server via API or WebSockets . We have a scenario, where the typing event is being sent only when the user starts keying in and he has to press "space" to trigger a sendTyping Event.

**Comment by billba** [comment]
@telkomops If you have [enabled](https://github.com/Microsoft/BotFramework-WebChat#typing) WebChat to send `typing` activities to the bot, it will send the whenever the user is typing and it have not sent a `typing` activity for at least three seconds.
