### ISSUE TITLE
Passing own custom parameters via directline

### ISSUE THREAD

**Issue by pratyushdhanuka** [Microsoft/BotFramework-WebChat#721]
I have successfully integrated my non-reach website with direct-line approach,
the website is in C#
and I am getting the Microsoft.Bot.Connector.Activity object based on parameters I pass in Botchat.App() function.

But can we pass our own custom parameters in addition to above?

I was wondering if there is any way to pass a collection of additional Key-Value pairs along with the request,
which I receive inside the same Activity object (any property) and I can continue my bot functionality from there.

Also is there some document which can tell the mapping between Botchat.App parameters and Activity object

**Comment by pratyushdhanuka** [comment]
After playing a bit, I found out that JObject Properties in "Activity.From.Properties" can be populated with any additional key-object relation and later can be extracted in code.
Can we do same for Activity.Properties

**Comment by billba** [comment]
You can't count on the ability to add parameters to `Activity.from`, as a future revision of Direct Line may sanitize its input more carefully. Instead, you should pass custom data in `Activity.channelData`. [Here](https://github.com/Microsoft/BotFramework-WebChat/issues/395#issuecomment-289681256) is some sample code which shows how a web page can pass custom data with each activity sent to the bot.
