### ISSUE TITLE
Localization sync

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#725]
This issue is for tracking new strings that are newly added and requires translations.

Strings added:
* [ ] `uploadFile: "Upload file"`, used for aria-label on the upload button
* [ ] `speak: "Speak"`, used for aria-label on the microphone button when speech is enabled

**Comment by compulim** [comment]
@danmarshall do you know if we have a list of "translation owners" so we could send them requests?

**Comment by danmarshall** [comment]
I just @ mentioned the original authors, from the history :)

**Comment by compulim** [comment]
Looking from the commit history, I got the list.

| Language code  | Translator            |
| -------------- | --------------------- |
| cs-cz          | @msimecek             | 
| da-dk          | Thomas Skødt Andersen | 
| de-de          |                       | 
| el-gr          | @qdoop                | 
| es-es          | @SantiEspada          | 
| fr-fr          | @meulta               | 
| hu-hu          |                       | 
| it-it          | Maurizio Moriconi     | 
| ja-jp          | @bigplants            | 
| ko-kr          | @Eunji                | 
| lv-lv          |                       | 
| nb-no          | @taarskog             | 
| nl-nl          |                       | 
| pl-pl          |                       | 
| pt-br          | @rcarubbi             | 
| pt-pt          |                       | 
| ru-ru          |                       | 
| sv-se          |                       | 
| tr-tr          |                       | 
| zh-hans        | @Antimoney            | 
| zh-hant/zh-yue | @compulim             |

**Comment by peterblazejewicz** [comment]
You could folks add me for `pl-pl`. Thx!

**Comment by iMicknl** [comment]
You can add me for the `nl-nl`. 👍

**Comment by compulim** [comment]
I should make this a list on our README.md, people can sign up thru PR. Keeping this issue open until the work is finish.

**Comment by corinagum** [comment]
Tracking localization is available on LOCALIZATION.md
