### ISSUE TITLE
Parent Page refresh on user response in Microsoft BOT dotnet

### ISSUE THREAD

**Issue by raghuram321123** [Microsoft/BotFramework-WebChat#729]
Need help

I used a webchat in a default.aspx, I created a bot with DotNet to redirect to the user requested pages. 

Can we have a feature like Response.Redirect in the framework? If user sends input as a "Home", can i redirect page to "home.aspx" from "default.aspx" directly?

Thanks for the help in advance.

**Comment by danmarshall** [comment]
Hi @raghuram321123, you can open URLs in new browser tabs by sending a link in markdown, or an [openURL action](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-rich-card-attachments#process-events-within-rich-cards) from a button on a rich card.

You may also want to see the [backchannel example](https://github.com/Microsoft/BotFramework-WebChat#the-backchannel) on how to send custom events from your bot to the Web Chat control. From there you may need to implement your own sophisticated way of refreshing the parent page.
