### ISSUE TITLE
Can't build the current build

### ISSUE THREAD

**Issue by hguomin** [Microsoft/BotFramework-WebChat#732]
Hi Team,

I try to build web chat but got below errors, would you please help to check it? thanks.

Wrote 6 CSS files to /Users/guomin/Documents/Projects/microsoft/azure/ai/BotFramework-WebChat
src/Chat.tsx(137,9): error TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
  Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.
src/Chat.tsx(147,9): error TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! botframework-webchat@0.11.2 build: `npm run build-css && tsc && webpack --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the botframework-webchat@0.11.2 build script 'npm run build-css && tsc && webpack --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the botframework-webchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-css && tsc && webpack --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs botframework-webchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls botframework-webchat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/guomin/Documents/Projects/microsoft/azure/ai/BotFramework-WebChat/npm-debug.log

**Comment by hguomin** [comment]
the rxjs module is duplicated, _rxjs@5.4.3@rxjs and _rxjs@5.3.3@rxjs are in node_module folder, delete the _rxjs@5.4.3@rxjs folder fixed the build.

**Comment by danmarshall** [comment]
It may be that DirectLineJS, which [uses rxjs ^5.0.3](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/package.json#L23) is pulling in a later version. Web Chat is [specifically using 5.3.3](https://github.com/Microsoft/BotFramework-WebChat/blob/master/package.json#L42). We will need to find a way to reconcile these.

**Comment by danmarshall** [comment]
Since this is related to peerDependencies, I am going to close it and we can track progress in #598
