### ISSUE TITLE
Issue - Can't reject a completed promise

### ISSUE THREAD

**Issue by hguomin** [Microsoft/BotFramework-WebChat#733]
Hi team,

I built the current master code and run the speech example, but got following error when I click the mic button to start the speech process, would you please help to check it? thanks.

<img width="1410" alt="callstack" src="https://user-images.githubusercontent.com/5404322/31578130-80c16372-b14d-11e7-880f-2d9b2dde3df7.png">
<img width="1425" alt="2017-10-15 1 56 44" src="https://user-images.githubusercontent.com/5404322/31578133-8dfe3d9e-b14d-11e7-8b43-01ee2eb61151.png">

**Comment by danmarshall** [comment]
@shahidkhuram @w-Yuan will this get fixed by the upgrade to 0.6 ?

**Comment by compulim** [comment]
@hguomin Since we modified quite some code in speech part, can you retry with latest build (~0.13.0) and see if it repro? If it do, please submit the log here and we will reopen this one.

Thanks!
