### ISSUE TITLE
botchat fails with speechOptions

### ISSUE THREAD

**Issue by stuartri** [Microsoft/BotFramework-WebChat#741]
This is the error in the console in chrome. Its a 403, but I have upgraded the azure resource for Translator Speech API and the activity shows nothing has touched it.

I have removed the subscription key below.

-Stuart.

CognitiveServices.js:15 WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=**CUTFROMBUGREPORT**&X-ConnectionId=D605E755871545FFB6044902DD0B8D91' failed: Error during WebSocket handshake: Unexpected response code: 403
Open @ CognitiveServices.js:15
Open @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
on @ CognitiveServices.js:15
ContinueWithPromise @ CognitiveServices.js:15
FetchConnection @ CognitiveServices.js:15
FetchConnection @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
window.navigator.getUserMedia.t @ CognitiveServices.js:15

**Comment by sumanboltz** [comment]
In the "Speech" Branch, the file "BotFramework-WebChat/samples/speech/index.html"
refers to -> src="../../CognitiveServices.js" in the markup code. But can't find the "CognitiveServices.js" in the downloaded code. Should the markup be updated to Refer any different files ? can anyone confirm.

**Comment by stuartri** [comment]
that file is created when you build the solution. But you can find it here:
    <script src="https://cdn.botframework.com/botframework-webchat/latest/CognitiveServices.js"></script>

The above issue was due to the wrong resource type in azure, so not an issue any more.

**Comment by sumanboltz** [comment]
Got you , Agreed

**Comment by dileepkanta** [comment]
Hi @stuartri ,

I am also facing this issue, can you tell me how had you fixed it? 
Please check the log of Chrome. (Which is working fine previously)

CognitiveServices.js:15 WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=f16f3a8b385b49b896de19c613d494dc&X-ConnectionId=5B7D57B7A96B4AD3854B816209E65663' failed: Error during WebSocket handshake: Unexpected response code: 403
Open @ CognitiveServices.js:15
Open @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
on @ CognitiveServices.js:15
ContinueWithPromise @ CognitiveServices.js:15
FetchConnection @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15
ExecuteSuccessCallback @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
Resolve @ CognitiveServices.js:15
(anonymous) @ CognitiveServices.js:15

**Comment by hellowonders** [comment]
How to fix this issue ??

**Comment by SharmaBiswadev** [comment]
try to put this in your js file
<script src="https://cdn.botframework.com/botframework-webchat/latest/CognitiveServices.js"></script>

while getting 403 web socket connect issue,it solved mine
