### ISSUE TITLE
Speech recognition is broken

### ISSUE THREAD

**Issue by premaarya** [Microsoft/BotFramework-WebChat#744]
It was working fine .. today I see speech feature is broken ..getting the error below:
1. Socket closed  followed by 
2.  ....1a0aa622d726fd7eb05aaad8192ec.js:29 2017-10-20T18:09:06.731Z | t | eventId: 2CBE3ED83FC54AB4A05878F25EE00BA1 | eventTime: 2017-10-20T18:09:06.731Z | eventType: 3 | metadata: {} | eventName: RecognitionEndedEvent | requestId: 3B971F1040C547239DE590049587DD7B | audioSourceId: 442B0317453F4849BA412601A39F6631 | audioNodeId: A1118FB94CDB49448A40E0A318EFA35F | connectionId: 51318400D465434AA30AA3A821C2EB06 | authFetchEventId: B4E0B5CEA0ED45F0A4CAF5958FEFCE20 | serviceTag: a5ee944dd32e48ba8dee75ea04653cb1 | AudioSourceId: 442B0317453F4849BA412601A39F6631 | AudioNodeId: A1118FB94CDB49448A40E0A318EFA35F | AuthFetchEventId: B4E0B5CEA0ED45F0A4CAF5958FEFCE20 | ConnectionId: 51318400D465434AA30AA3A821C2EB06 | ServiceTag: a5ee944dd32e48ba8dee75ea04653cb1 | Status: <NULL> | Error: <NULL> | Name: RecognitionEndedEvent | RequestId: 3B971F1040C547239DE590049587DD7B | Metadata: {}
Am I missing anything ? I am using the 0.11.2 version with Bing Speech API key.

**Comment by premaarya** [comment]
looks like same error as #716

**Comment by danmarshall** [comment]
Hi @premaarya - #716 is closed, you can see [my comment on how to resolve it](https://github.com/Microsoft/BotFramework-WebChat/issues/716#issuecomment-335226932).
Was this error intermittent - or is it still happening?

**Comment by compulim** [comment]
@premaarya do you have luck trying speech out on Web Chat?

**Comment by premaarya** [comment]
It started working after few days on it's own .. :) @danmarshall.
