### ISSUE TITLE
Timestamp is not completely localizable

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#748]
The timestamp below a message always displays *username* followed by *time*, see [History.tsx](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx#L255). The string resource file only allows customization of the time portion, see [Strings.tsx](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Strings.ts#L33).

Expected: locale may specify *time* to precede *username*.

**Comment by compulim** [comment]
Should we include [`moment`](http://momentjs.com/)? Or are you aware of any better libraries for localization?

**Comment by compulim** [comment]
We should try out HTML Intl API.

**Comment by compulim** [comment]
Timestamp in v4 can now localizable.
