### ISSUE TITLE
Node.JS SDK Carousel Card in Cordova App - Slider not responding the first time, but works okay subsequently.

### ISSUE THREAD

**Issue by mitijain123** [Microsoft/BotFramework-WebChat#749]
I am Using NodeJs SDK:
Carousel Card works fine in web and mobile web, but when converted to Cordova App, the Carousel Card is not responding with touch when sliding the first time but sliding with touch works with subsequent carousel cards.

**Comment by danmarshall** [comment]
Hi @mitijain123 , our team does not test with Cordova. Sorry we don't have any clues to help you out. I can tell you that we are using the native functionality of the browser. We do not have any code at all which handles the touch sliding. Can you tell me, do you see the scroll buttons on either side of the carousel?

**Comment by mitijain123** [comment]
@danmarshall yes I can see the scroll buttons on either side of carousel

**Comment by danmarshall** [comment]
How about if you tap a sidescroll button instead of swipe?

**Comment by mitijain123** [comment]
Even tap on sidescroll button also not working

**Comment by danmarshall** [comment]
Can you repro in a browser, or is it only in Cordova?
Also, can you share the JSON of your cards.

**Comment by mitijain123** [comment]
Can you repro in a browser, or is it only in Cordova?
>> it is only in cordova

Also, can you share the JSON of your cards.
>> Please find the below json, I had removed domain names from the url.
{
  "type": "message",
  "attachmentLayout": "carousel",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Store",
        "subtitle": "November 15th, 5:30 AM",
        "text": " Singapore",
        "images": [
          {
            "url": "https://sdfds.com/hermes-mbs-v16.jpg"
          }
        ],
        "tap": {
          "type": "openUrl",
          "value": "https://sdfds.com/hermes-mbs-store",
          "title": "Click to open website in your browser"
        },
        "buttons": [
          {
            "type": "openUrl",
            "value": "https://sdfds.com/event-details/hermes-mbs-store",
            "title": "Tell Me More"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "sdffdsf America",
        "subtitle": "December 7th, 5:30 AM",
        "text": " Miami",
        "images": [
          {
            "url": "https://sdfds.com/Basel-Arts.jpg"
          }
        ],
        "tap": {
          "type": "openUrl",
          "value": "https://sdfds.com/art-basel-in-america",
          "title": "Click to open website in your browser"
        },
        "buttons": [
          {
            "type": "openUrl",
            "value": "https://sdfds.com/art-basel-in-america",
            "title": "Tell Me More"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Ghin",
        "subtitle": "December 29th, 1:30 AM",
        "text": " Singapore",
        "images": [
          {
            "url": "https://sdfds.com/waku1-v16.jpg"
          }
        ],
        "tap": {
          "type": "openUrl",
          "value": "https://sdfds.com/dinner-at-waku-ghin-by-ubs",
          "title": "Click to open website in your browser"
        },
        "buttons": [
          {
            "type": "openUrl",
            "value": "https://sdfds.com/dinner-at-waku-ghin-by-ubs",
            "title": "Tell Me More"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Milan",
        "subtitle": "March 1st, 12:30 AM",
        "text": " Milan",
        "images": [
          {
            "url": "https://sdfds.com/La-Traviata-Teatro-alla-Scala-Milan-v169.jpg"
          }
        ],
        "tap": {
          "type": "openUrl",
          "value": "https://sdfds.com/la-traviata-teatro-alla-scala-milan",
          "title": "Click to open website in your browser"
        },
        "buttons": [
          {
            "type": "openUrl",
            "value": "https://sdfds.com/la-traviata-teatro-alla-scala-milan",
            "title": "Tell Me More"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "title": "Hong Kong",
        "subtitle": "March 23rd, 3:30 PM",
        "text": " Hong Kong",
        "images": [
          {
            "url": "https://sdfds.com/Art-Basel-v169.jpg"
          }
        ],
        "tap": {
          "type": "openUrl",
          "value": "https://sdfds.com/art-basel-in-hong-kong",
          "title": "Click to open website in your browser"
        },
        "buttons": [
          {
            "type": "openUrl",
            "value": "https://sdfds.com/art-basel-in-hong-kong",
            "title": "Tell Me More"
          }
        ]
      }
    }
  ],
  "locale": "en-US",
  "localTimestamp": "2017-11-03T10:03:42+05:30",
  "from": {
    "id": "default-bot",
    "name": "Bot"
  },
  "recipient": {
    "id": "default-user"
  },
  "inputHint": "acceptingInput",
  "id": "al2bijhi8dfc",
  "replyToId": "33c590hb15i1",
  "channelId": "emulator",
  "timestamp": "2017-11-03T04:33:42.264Z",
  "conversation": {
    "id": "mbl74h91j7l8"
  }
}

**Comment by danmarshall** [comment]
Not sure what the debugging story is in Cordova. Can you capture `console.log()`?
If so, perhaps you can build your own Web Chat. Modify [this line](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/HScroll.tsx#L46) and log the values of `this.scrollDiv.scrollWidth` & `this.scrollDiv.offsetWidth`

**Comment by mitijain123** [comment]
This is the console.log values:
this.scrollDiv.scrollWidth: [Log] 1645 (botchat.js, line 34)
this.scrollDiv.offsetWidth: [Log] 329 (botchat.js, line 34)

**Comment by danmarshall** [comment]
ok - comment out [this line](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/HScroll.tsx#L50) to make the horizontal scrollbar visible. Then we will see if:
* the horizontal scrollbar is visible, and is correct
* swipe is working

**Comment by mitijain123** [comment]
I had commented the line but:

1. not able to see horizontal scrollbar
2. swipe is also not working

**Comment by danmarshall** [comment]
Ok, then the platform does not even have scrollbars, since it's mobile. Is that correct?
If so, can you please try to find a way to make scrollbars visible, like ugly ;) desktop scrollbars?

**Comment by mitijain123** [comment]
@danmarshall thanks for your time and support, I had found the issue it is the issue from my side, as the css which I had added for scrolling :
-webkit-overflow-scrolling: touch !important;

This is added for multiple hscroll div so it is not working for first time, I had changed it to add to only one div and it is working now, Thanks once again.

**Comment by danmarshall** [comment]
Great!
