### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Code1942** [Microsoft/BotFramework-WebChat#751]
npm ERR!  { Error: EPERM: operation not permitted, mkdir 'C:\Users\xxxxx\
AppData\Local\Temp\npm-5412-29d1c4c9\registry.npmjs.org\uc.micro'

Windows 7
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

**Comment by canaanites** [comment]
Did you try to open and run the console as an administrator?

**Comment by danmarshall** [comment]
This seems like an npm error, not a Web Chat error. Please re-open if you can provide more details regarding Web Chat.
