### ISSUE TITLE
BOT framework :isTyping not working suddenly  in Web Chat Channel  

### ISSUE THREAD

**Issue by Suneethae7** [Microsoft/BotFramework-WebChat#755]
typing working in emulator and direct line 

Web chat initial for some days its worked but now suddenly not working in Web Channel

**Code**:

public async Task<HttpResponseMessage> Post([FromBody]Activity activity, CancellationToken token)
        {

if (activity.Type == ActivityTypes.Message)
  {

using (var scope = DialogModule.BeginLifetimeScope(Conversation.Container, activity))
                {
  var connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                    Activity isTypingReply = activity.CreateReply();
                    isTypingReply.Type = ActivityTypes.Typing;
                    isTypingReply.Text = null;
                    await connector.Conversations.ReplyToActivityAsync(isTypingReply);

}
}
}

please let me know the fix

**Comment by Suneethae7** [comment]
please  help me on this

**Comment by compulim** [comment]
@Suneethae7 We tested and looks like it's not something on the Web Chat component side. We just added a new test (#807) to ensure we will show the typing indicator when the server instructed us to do so.
