### ISSUE TITLE
Hero cards in Web chat not working properly in IE 10 document mode

### ISSUE THREAD

**Issue by Harish-P** [Microsoft/BotFramework-WebChat#757]
Hello,

I am using hero card to display buttons in web chat channel, but its not behaving as expected, in  IE 10 document mode. when I click on button ot type the menu text its posting the same menu value twise.. and when i click on other button ,, its always sending the first button value along with selected menu item value.
Note: this issue is no seen in chrome or IE 11. only problem problem with IE 10 document mode.
Any help?

**Comment by compulim** [comment]
Sorry, but IE10 is not supported.
