### ISSUE TITLE
Is there now a way to change the branding or color without rebuilding and deploying an own instance of the webchat project?

### ISSUE THREAD

**Issue by pr3d1ction** [Microsoft/BotFramework-WebChat#761]
Hi all,
is there a way to adapt teh color/branding without deploying this project on my own?

We would just need to change the blue title bar...

Thanks!

**Comment by danmarshall** [comment]
Hi @pr3d1ction, no there currently is not. You would need to host your own version. We would like to add this feature but it is not currently planned.
