### ISSUE TITLE
Japanese translation is available in the strings file, but it is missing from the mapping

### ISSUE THREAD

**Issue by Andrea-Orimoto** [Microsoft/BotFramework-WebChat#764]
the mapping at the bottom of the strings file is missing ja

export const strings = (locale: string) => {
    if (locale.startsWith('da'))
        locale = 'da-dk';
    else if (locale.startsWith('de'))
        locale = 'de-de';
    else if (locale.startsWith('no') || locale.startsWith('nb') || locale.startsWith('nn'))
        locale = 'nb-no';
    else if (locale.startsWith('pl'))
        locale = 'pl-pl';
    else if (locale.startsWith('ru'))
        locale = 'ru-ru';
    else if (locale.startsWith('nl'))
        locale = 'nl-nl';
    else if (locale.startsWith('lv'))
        locale = 'lv-lv';
    else if (locale.startsWith('pt'))
        locale = 'pt-br';
    else if (locale.startsWith('fr'))
        locale = 'fr-fr';
    else if (locale.startsWith('es'))
        locale = 'es-es';
    else if (locale.startsWith('el'))
        locale = 'el-gr';
    else if (locale.startsWith('it'))
        locale = 'it-it';
    else if (locale === 'zh-hant' || locale === 'zh-hk' || locale === 'zh-mo' || locale === 'zh-tw')
        locale = 'zh-hant';
    else if (locale.startsWith('zh'))
        locale = 'zh-hans';
    else if (locale.startsWith('cs'))
        locale = 'cs-cz';
    else if (locale in localizedStrings === false)
        locale = 'en-us';

**Comment by billba** [comment]
I believe it is covered by the final case, because `'ja'` is in `localizedStrings`, therefore `locale` remains `'ja'`. Do you have reason to believe this doesn't work?

**Comment by Andrea-Orimoto** [comment]
Yes, we have a case where it is not working, even if we pass ja (will verify more and send you more info).

but what if you pass ja-jp? why is this one treated differently?

**Comment by billba** [comment]
Here I was just following the lead of the translator. If it's not right let's fix it.

**Comment by danmarshall** [comment]
I think the fix is to follow the pattern that's established.

**Comment by billba** [comment]
Sorry about this - I should have double checked before merging this change.
