### ISSUE TITLE
Webchat does not show text from HTTPS Response despite HTTP Code 200

### ISSUE THREAD

**Issue by holgerkyas** [Microsoft/BotFramework-WebChat#766]
Hello
I'm calling a remote https service via the bot emulator by typing a text into the webchat, here "Hello". The response is coming back correctly with HTTP code 200, but the webchat does not show the response. What did I miss?

Bot Emulator version is 3.5.33

Startup Log
[11:16:23] Emulator listening on http://[::]:63840 
[11:16:23] ngrok listening on https://08a7372a.ngrok.io 
[11:16:23] ngrok traffic inspector: http://localhost:4040 
[11:16:23] Will bypass ngrok for local addresses 
[11:16:23] Checking for new version... 
[11:16:25] Application is up to date. 

I added the screenshots and the json files from the webchat in the bot emulator.

REQUEST
![request](https://user-images.githubusercontent.com/11524496/32413882-c9a964ee-c21a-11e7-9185-cd832021f812.jpg)

RESPONSE
![response](https://user-images.githubusercontent.com/11524496/32413883-cd4e939e-c21a-11e7-9dde-189608d968c4.jpg)

REQUEST
{
  "type": "message",
  "text": "Hello",
  "from": {
    "id": "default-user",
    "name": "User"
  },
  "locale": "en-US",
  "textFormat": "plain",
  "timestamp": "2017-11-05T09:49:50.451Z",
  "channelData": {
    "clientActivityId": "1509875028121.6653353473116588.0"
  },
  "entities": [
    {
      "type": "ClientCapabilities",
      "requiresBotState": true,
      "supportsTts": true,
      "supportsListening": true
    }
  ],
  "id": "aiend6j0klk6",
  "channelId": "emulator",
  "localTimestamp": "2017-11-05T10:49:50+01:00",
  "recipient": {
    "id": "akd08b141n47chj3dc",
    "name": "Bot"
  },
  "conversation": {
    "id": "bc4lk7ell0d"
  },
  "serviceUrl": "https://242f7bb7.ngrok.io"
}

RESPONSE
{
  "type": "message",
  "from": {
    "id": "akd08b141n47chj3dc",
    "name": "Bot"
  },
  "conversation": {
    "id": "bc4lk7ell0d",
    "name": "Conversation Name"
  },
  "recipient": {
    "id": "default-user",
    "name": "User"
  },
  "channelData": {
    "clientActivityId": "1509875028121.6653353473116588.0"
  },
  "channelId": "emulator",
  "text": "I understood: Hello",
  "speak": "I understood: <break time=\"1s\"/>Hello<break time=\"1s\"/>",
  "inputHint": "expectingInput",
  "replyToId": "aiend6j0klk6"
}

thanks
Holger

**Comment by danmarshall** [comment]
Hi Holger, would you mind re-filing this issue over at the Emulator repo? https://github.com/Microsoft/BotFramework-Emulator

**Comment by holgerkyas** [comment]
Ok, just did.

**Comment by danmarshall** [comment]
Thanks!
