### ISSUE TITLE
sip protocol not working in webchat

### ISSUE THREAD

**Issue by avinash1611** [Microsoft/BotFramework-WebChat#772]
Hello All, 
Please help me to solve below issue. 

We are trying to give new skype conversation inside webchart in below format. When we clicking this link automatically added mailto: and goes to outlook page.  

 sip:abc@xyz.com

Find below sample code

```
 private async Task OnOptionSelected(IDialogContext context, IAwaitable<string> result)
        {
            var USSupport = "sip:abc@xyz.com";
            var APACSupport = "sip:davida@xyz.com";
            var Escalationupport = "sip:john.S@xyz.com";
            try
            {
                string optionSelected = await result;

                switch (optionSelected)
                {
                    case USCSupportOption:
                        await context.PostAsync("Click the Skype link {0}", USSupport);
                        break;
```

**Comment by reyesrico** [comment]
@avinash1611 the way to render different protocols is using markdown format:

`[friendly_name](sip:abc@xyz.com)`
- friendly_name can be the account or any other name.

From your example: 
```var USSupport = "[abc@xyz.com](sip:abc@xyz.com)";```

**Comment by avinash1611** [comment]
Many Thanks Carlos Reyes, Its started working.

P Avinash
Ent - IT | PLM | M - +91. 7348937098
