### ISSUE TITLE
Encode URL component correctly for Markdown images with title attribute

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#774]
`![Alt text](/path/to.png?oneTwoThree=1 2 3 "Tooltip goes here")`

Should have URL encoded correctly to

`<img src="/path/to.png?oneTwoThree=1%202%203" alt="Alt text" title="Tooltip goes here" />`

**Comment by billba** [comment]
You said what it should do but didn't say what it does do :-)
