### ISSUE TITLE
Speech-to-text Stop Bot from Speaking

### ISSUE THREAD

**Issue by CooperatorsDev** [Microsoft/BotFramework-WebChat#777]
Hi,

I am trying to stop the Bot from speaking then I want the mic to be open. I got this to work in the bot framework emulator but in Chrome/Edge the mic doesnt open up. 
To stop the Bot from talking I use .speak(' ') which works in the emulator and chrome/edge.
To open the mic up I use .inputHint(builder.InputHint.expectingInput); which works in the emulator but not in chrome/edge. 
indext.hmtl:
![image](https://user-images.githubusercontent.com/33524247/32618952-2a946644-c547-11e7-99a9-59e6298bbea8.png)

Node JS code snippet:
![image](https://user-images.githubusercontent.com/33524247/32618974-465a1cf2-c547-11e7-9593-aa008299ee9b.png)

Please let me know how I can fix this. Thanks in advance!

**Comment by danmarshall** [comment]
@shahidkhuram @w-Yuan is this supported?

**Comment by shahidkhuram** [comment]
Based on your description, it looks like the Cognitive service speech synthesis wrapper doesn't call onSpeakingFinished if the input is empty. I'd suggest debugging at the following spot to confirm:
https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/CognitiveServices/SpeechSynthesis.ts#L92-L94 

I think the emulator is currently using the browser speech synthesis option, which has a different implementation and might be calling onSpeakingFinished on empty input.

**Comment by CooperatorsDev** [comment]
![image](https://user-images.githubusercontent.com/33524247/33099654-932761d8-cedf-11e7-8aa7-73abc0621245.png)

I logged at a few different spots. Not sure what I need to change to make it call onSpeakingFinished if the input is empty.

**Comment by shahidkhuram** [comment]
From a quick look at what you shared, it looks like it should be in the exception handler, L2522 in your screenshot. 

I suspect this is because cognitive services TTS returns and empty audio stream because of empty ssml. Skipping playback on an empty audio stream (inspect top.data) would be ideal.

**Comment by CooperatorsDev** [comment]
![image](https://user-images.githubusercontent.com/33524247/33151541-7f390fa6-cfa6-11e7-84f5-0e46683ac1fb.png)

@shahidkhuram I added an if statement starting at L2515 (marked in red in the screenshot), this fixed my problem and now the mic opens up when speak(' '). I am not sure if this will affect other parts of the code, do you have any suggestions or is this fine?

**Comment by compulim** [comment]
Closed due to inactivity.
