### ISSUE TITLE
OpenUrl _self

### ISSUE THREAD

**Issue by awittman** [Microsoft/BotFramework-WebChat#780]
Current default is opening to a new tab. Can this be overridden to open in _self? Using Angular2 application and do not have a react setup. 

**Code :**

**List<CardAction> Page1 = new List<CardAction> { new CardAction(ActionTypes.OpenUrl, title: "Yes", value: WebConfigurationManager.AppSettings["LocalPage"]) };**

The chat is running in our application and I want to override the OpenUrl location and not sure how to achieve this easily.

**Comment by billba** [comment]
At the moment you would have to build your own custom version. Here's the relevant line: https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Chat.tsx#L246

This is the sort of option that would be a very appropriate property to pass in at the top level, but that functionality does not presently exist.
