### ISSUE TITLE
saveShellRef callback in Chat.ts throws Null Pointer Exception when re-render is triggered.

### ISSUE THREAD

**Issue by marrobins** [Microsoft/BotFramework-WebChat#782]
The Chat component breaks when embedded in a React app due to a Null Pointer Exception being thrown in the saveShellRef callback.

This happens when a re-render at the parent level is triggered, causing the Chat component to be unmounted, destroyed and a new instance mounted. When this occurs, `null` is passed to the old saveShellRef callback as argument and the NPE is thrown, causing the new component to stop functioning.

As per this React issue [0], ref callbacks _need_ to handle null arguments. During a re-render, the ref callback from the old component will be passed `null` and the ref callback from the new component instance will be passed the new ref instance. 
[0] https://github.com/facebook/react/issues/4533

**Comment by billba** [comment]
Want to file a PR?

**Comment by marrobins** [comment]
I've tested this PR (https://github.com/marrobins/BotFramework-WebChat/pull/1) in my codebase and it fixes the issue for me.

**Comment by compulim** [comment]
@marrobins Could you submit your PR to this repos? It would be great if you could also look at other `ref` calls.

React call `ref` with `null` when it is [unmounting the instance](https://reactjs.org/docs/refs-and-the-dom.html), so we are practically hitting this everywhere with `.getWrappedInstance()`.

> React will call the `ref` callback with the DOM element when the component mounts, and call it with `null` when it unmounts. `ref` callbacks are invoked before `componentDidMount` or `componentDidUpdate` lifecycle hooks.

**Comment by marrobins** [comment]
@billba @compulim I've submitted my PR to this repo: https://github.com/Microsoft/BotFramework-WebChat/pull/801

**Comment by compulim** [comment]
PR merged, closing this issue.
