### ISSUE TITLE
[AdaptiveCards] Date input missing date picker

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/BotFramework-WebChat#785]
I'm using an Adaptive Card to allow users to edit some fields during a conversation. Some fields are date type and it is working fine in emulator (I can select a date from the date picker).

However, when trying the same exact code published in my webchat (through directline with secret) the date fields appear simply as text fields without any picker.

It should work according this page, no? http://adaptivecards.io/visualizer/index.html?hostApp=WebChat%20(Bot%20Framework)

**Comment by danmarshall** [comment]
Hi @AndreMantas, which browser are you using? Implementation of HTML5 input controls varies between browsers. The Emulator is based on Chrome.

**Comment by AndreMantas** [comment]
Oh, my bad. I was testing randomly with firefox (and it was outdated). Works as expected now, thanks.

**Comment by danmarshall** [comment]
No, there is no validation provided by Web Chat. You should probably do this in your bot code.
