### ISSUE TITLE
Carousel prevents vertical touch scroll on iOS

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#787]
The chat can scroll vertically with touch. Carousel will scroll horizontally with touch, but will not allow vertical scrolling of the chat:
![image](https://user-images.githubusercontent.com/11507384/32910498-4620f036-cabe-11e7-913a-9d516f5cef5c.png)

**Comment by compulim** [comment]
Using CSS `touch-action: pan-x` on the carousel?

**Comment by Helene-Expertime** [comment]
+1

**Comment by davidjrh** [comment]
While the issue is closed, this fixed it for me:

`    body {
        -webkit-overflow-scrolling: touch;  
      }`

PS: I needed to set it at body level, trying to set it to whatever DIV element didn't work. Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

**Comment by corinagum** [comment]
@Support, could we get verification of repro on v4?

**Comment by cwhitten** [comment]
We cannot reproduce this on WebChat 4.3.3
