### ISSUE TITLE
Dynamically change language

### ISSUE THREAD

**Issue by aajadhav** [Microsoft/BotFramework-WebChat#788]
I am using webchat in multilingual site, where I want to set bot locale on language change, can any one guide me for implementing this.

Even after passing changes local it stays with initial set locale, I am using it in Angular 4.

**Comment by compulim** [comment]
It's currently not something we supported right now. But if you are okay to hack our component using React/Redux, you can send the following action to the Redux store and it will change the locale on-the-fly.

```
this.props.dispatch({ type: 'Set_Locale', locale: 'zh-hant' });
```

**Comment by billba** [comment]
Ouch that is a hack, alright.

The overarching issue is that `App` & `Chat` are not reactive - they are meant to be rendered once, and will not respond to changes in their properties. There are some good reasons why we might want to make them reactive, but it will require some architectural changes and might affect their APIs.

**Comment by compulim** [comment]
Agree, we need to think what APIs people would need and how we could surface them in 3 different ways:
* URL query parameters in `<iframe>`
* `BotChat.App()` options
* React props

**Comment by luccasmf** [comment]
If I'm using the IFRAME link i got from "channel creation" on azure, can I change its locale ? My bot is supposed to work on pt-br, but every interation (apart of LUIS) is in english :(

**Comment by compulim** [comment]
@luccasmf Not now, but it's an enhancement we should look at.

**Comment by compulim** [comment]
Web Chat v4 can now change language on-the-fly via React props. Try this [live demo](webchat-playground.azurewebsites.net/) and click "Start conversation with official MockBot". Then try changing the language drop down and see.
