### ISSUE TITLE
Error Building Web Chat

### ISSUE THREAD

**Issue by GINGO2397** [Microsoft/BotFramework-WebChat#791]
Hello,

Currently i am experiencing the following error when i try to build a custom web chat.

src/Attachment.tsx(310,14): error TS2678: Type '"image/svg+xml"' is not comparable to type '"image/png" | "image/jpg" | "image/jpeg" | "image/gif" | "audio/mpeg" | "audio/mp4" | "video/mp4"...'.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! botframework-webchat@0.11.3 prepublish: `tsc && npm run build-css && webpack --progress --config webpack.production.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the botframework-webchat@0.11.3 prepublish script 'tsc && npm run build-css && webpack --progress --config webpack.production.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the botframework-webchat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && npm run build-css && webpack --progress --config webpack.production.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs botframework-webchat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls botframework-webchat
npm ERR! There is likely additional logging output above.

Thanks in advance for your help and support.

**Comment by danmarshall** [comment]
This error should be fixed if you get [directlinejs version 0.9.13](https://github.com/Microsoft/BotFramework-WebChat/blob/master/package.json#L32):
> src/Attachment.tsx(310,14): error TS2678: Type '"image/svg+xml"' is not comparable to type '"image/png" | "image/jpg" | "image/jpeg" | "image/gif" | "audio/mpeg" | "audio/mp4" | "video/mp4"...'.

Can you delete the `botframework-directlinejs` folder from your node_modules folder and npm install again?

**Comment by GINGO2397** [comment]
After deleting the botframework-directlinejs folder from my node-modules folder, ocurred the same error.

**Comment by danmarshall** [comment]
you may need to also delete your package-lock.json. Then repeat the above.
OR it may be easier to clone to a new place on your disk.

**Comment by GINGO2397** [comment]
Thanks, it worked
