### ISSUE TITLE
Remove image upload button in Microsoft BotFramework iFrame

### ISSUE THREAD

**Issue by naveen-vijay** [Microsoft/BotFramework-WebChat#798]
Does the iframe embed has any configuration / support to disable the button ?

<img width="713" alt="botframework" src="https://user-images.githubusercontent.com/342580/33522750-964fc9e4-d7b9-11e7-8aac-edccb3d3c278.png">

**Comment by billba** [comment]
No but I think you could do that with styling.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Neloop** [comment]
+1 for this... We would like to have option (in normal js include of WebChat) to disable file upload using `ChatProps`. Our bot is simple one and having this button here is only confusing to users.

**Comment by compulim** [comment]
Coming in with PR #883, stay tuned.

**Comment by compulim** [comment]
Fixed in #883.
