### ISSUE TITLE
Don't update state with every change to text input

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#80]
That was a fun experiment, but it's super inefficient and buys us nothing.

**Comment by danmarshall** [comment]
So what's the alternative?

**Comment by billba** [comment]
Turn it into an uncontrolled component https://facebook.github.io/react/docs/forms.html

I'll try this today.

**Comment by billba** [comment]
(alternatively, leave it the way it is and have the other components be smarter about when they re-render)

**Comment by billba** [comment]
I chose the second route. With https://github.com/Microsoft/BotFramework-WebChat/pull/257 we now use react-redux to intelligently re-render Shell and History, which means changes in one won't unnecessarily re-render the other.
