### ISSUE TITLE
Uploaded images do not appear in Edge 40

### ISSUE THREAD

**Issue by danmarshall** [Microsoft/BotFramework-WebChat#800]
In the latest Edge browser from the Fall Creator's update, the MIME type of file.type is blank.
Compare the Chrome where the type is something like "image/png"
![image](https://user-images.githubusercontent.com/11507384/33582477-43cc0a78-d90a-11e7-83fe-8e80015a3291.png)

Perhaps Web Chat can compensate by taking a "best guess" of the type, from the file extension?
Not sure when this will be fixed in Edge.

**Comment by compulim** [comment]
It works for me on Edge 16/EdgeHTML 41 (RTM build). Tried JPEG and PNG.

Or is that something special about the PNG file you sent?

**Comment by danmarshall** [comment]
Yes, it seems fixed in 41.
