### ISSUE TITLE
Is it possible to integrate with other speech provider like google speech?

### ISSUE THREAD

**Issue by ryzam** [Microsoft/BotFramework-WebChat#808]
HI guys

Good work on speech features enable. Btw I'm looking an example to integrate with other speech providers like google speech, this is because current bing speech API only supports few languages.

**Comment by compulim** [comment]
Sounds like a good project. Someone need to look at [SpeechModule.ts](../blob/master/src/SpeechModule.ts) and implement `ISpeechRecognizer` using Google Cloud Speech.

I looked at their API but I am not aware of any client library that talk to browser directly.

Do you know if they have any examples using Google Cloud Speech with browser?

**Comment by khs3141** [comment]
Please refer to the following site.
https://gcpdemo.gridcell.io/

**Comment by compulim** [comment]
Web Chat v4 support speech engines that conform to standard W3C Web Speech API.

AFAIK, GCS has very similar API to W3C standard, and I believe Chrome use GCS if the selected voice font is an online-only font. Please look at [this line in this sample](https://github.com/Microsoft/BotFramework-WebChat/blob/master/samples/speech-cognitive-services-bing-speech/index.html#L75) to see how to integrate your speech engine with Web Chat.

**Comment by AndreMantas** [comment]
I also need to integrate webchat with google speech API (their recognition and synthesis is better at least for my language...).
**Where can I look for pointers on how to implement a ponyfill for easily integrate with renderWebChat and pass the webSpeechPonyfillFactory?**

I was able to use the samples to get it working (hybrid approach with microsoft cognitive services and browser capabilities) but now need to integrate with google speech API.

Thanks in advance.

**Comment by cmnisal** [comment]
Has anyone completed this Google Speech Integration with Webchat Speech?

**Comment by compulim** [comment]
As long as the service you are integrating conform with W3C Web Speech API standard, it should be fine.

The standard can be found at https://wicg.github.io/speech-api/.
