### ISSUE TITLE
src directory should be published in botframework-webchat package

### ISSUE THREAD

**Issue by billba** [Microsoft/BotFramework-WebChat#811]
When we switched from blacklist (`.npmignore`) to whitelist (`files` in `package.json`), the `src` folder got left out. The reason to have it there is to be able to debug using source maps.

**Comment by compulim** [comment]
I think we should keep the `/src` folder away, but enable inline source code in the source map files. So practically, source code in `.ts` files will be inlined directly in the `.js.map` files.

What do you think?

**Comment by billba** [comment]
Oh cool, show me how to do that and I'll make it so in DirectLineJS as well.

**Comment by compulim** [comment]
I didn't test it out, but you should able to get it by modifying `tsconfig.json`. Change `sourceMap: true` to `inlineSourceMap: true`. You can look up at options in TypeScript doc [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

After you recompile, you can verify `*.js.map` files will contains source code from the original `*.ts` files, in addition to those `AACA;AACA` VLQ + Base64 code.

**Comment by PiWiBardy** [comment]
hello i tried to remove sourcemap from the project, it's ok for the webchat project but i've the same issue with the adaptive cards project..

anyone is getting an idea?

**Comment by billba** [comment]
@PiWiBardy if you have made this work for Web Chat please submit a PR. Adaptive Cards is just one of many dependencies of Web Chat, and we have no control over how they run their project.
