### ISSUE TITLE
WebChat into a React Application

### ISSUE THREAD

**Issue by raghavendracs** [Microsoft/BotFramework-WebChat#812]
Hi,

I have a existing React Application into which I am thinking of inserting some "conversational" UI elements using the BotFramework. Problem I am having with this is since BotFramework-WebChat has a copy of react that it brings in as part of its node_modules this is conflicting with the copy of react that I am already importing in my application. Are there some suggestions of how I can get around this?

Thanks,

**Comment by billba** [comment]
Yes, please read [this](https://github.com/Microsoft/BotFramework-WebChat#medium-in-your-react-website-incorporate-the-web-chat-react-component) which talks about the right way to do this pattern.

**Comment by raghavendracs** [comment]
Which one exactly please? A little more pointed feedback would be more
helpful.

Thanks,

**Comment by billba** [comment]
I'm not sure what you mean when you say "which one". If you follow the indicated link you will get to a section of the README providing specific instructions about how to include Web Chat as a React component. Have you read that, and if so, what specific questions do you have?
