### ISSUE TITLE
[Feature] Group chat between two users and bot

### ISSUE THREAD

**Issue by jrmcdona** [microsoft/BotFramework-WebChat#814]
Hello,
Do you know when group chat would be enabled?   Would like our bot to orchestrate the conversation between our customer and our agents.

Thanks

**Comment by akasranjan005** [comment]
Hi @jrmcdona ,
If you publish your bot on skype, you will get this feature :) So you can close this issue.

**Comment by billba** [comment]
@akasranjan005 but this is a request for group chat in WebChat, so the fact that you can make this happen in Skype is neither here nor there.

**Comment by akasranjan005** [comment]
My bad, I would love to have this feature in WebChat. Since there was no feature label I made this comment, thanks for clarification @billba  :)

**Comment by jrmcdona** [comment]
@billba @akasranjan005  Would this essentially not create a group chat?
https://github.com/Microsoft/BotFramework-WebChat/issues/819

Seems like when the other user(or agent) opens up a conversation id, you then have a chat among two users and a bot.

**Comment by akasranjan005** [comment]
That's a nice workaround @jrmcdona  :)  As group conversation will require chat bubble of different users to be identified differently (say color of bubble or user pic before message). In this case it will be same for every agent and the customer will not know who he is talking to. What do you think @billba ?

**Comment by jrmcdona** [comment]
In my case I only have two users and a bot.  My users will be on two different websites.    I will have a customer website and an agent website.  I should be able to customized the WebChat react code and Avatar/username as needed.   In theory this seems doable and essentially is a group chat.  Not a group chat like slack, but a different form of it.

**Comment by billba** [comment]
In theory you can do this using the [Resume Conversation](https://github.com/Microsoft/BotFramework-DirectLineJS#resume-an-existing-conversation) feature. You would need a way to share the `conversationId` between the users.

**Comment by Kellym-Kainos** [comment]
Did anyone ever get a solution for this?

**Comment by corinagum** [comment]
To Do items related to this request:
* Create a sample that has multi-user conversation
  - if there are no problems, demo to team to discuss hidden pitfalls
  - if not, unfortunately we don't support it. Perhaps in the future

**Comment by biohazard999** [comment]
This would be absolutely amazing! 👏👍
Basically, I need exactly this functionality. 
For now, I think I have to dig into customizing the control.

**Comment by attozk** [comment]
+1

**Comment by biohazard999** [comment]
@attozk it wasn't that hard to implement after all:
Share the DL token between users and bot.
Use some trickery about username and initials (the initials portion could come from a bot middleware, but i implemented it by fetching the initials via http
Implement a middleware and do some basic css hacking, voliâ

`ChatWindow.tsx:`

```ts
import 'react-app-polyfill/ie11';
import * as React from 'react';
import * as ReactDOM from "react-dom";
import * as classNames from "classnames";
import { DirectLine, Activity } from 'botframework-directlinejs';
import ReactWebChat from 'botframework-webchat/lib';
import CroppedImage from "botframework-webchat-component/lib";
import { hooks } from "botframework-webchat-component/lib";
import createStore from 'botframework-webchat-core/lib/createStore';

interface AvatarProps{
    'aria-hidden': boolean | undefined,
    className: string | undefined,
    fromUser: string | undefined,
    initials: string | undefined,
    userName: string | undefined
}
const Avatar = ({ 'aria-hidden': ariaHidden, className, fromUser, initials, userName }: Partial<AvatarProps>) => {
    const [{ avatar: avatarStyleSet }] = hooks.useStyleSet();

    const image = undefined;

    if(image || initials)
    {
        return (                
            <div
                aria-hidden={ariaHidden}
                className={classNames.default(avatarStyleSet + '', { 'from-user': fromUser }, className + '')}
                title={userName}
            >
                {initials}
                {!!image && <CroppedImage alt="" className="image" height="100%" src={image} width="100%" />}
            </div>                
        );
    }
    return (<div></div>)
};

const renderAvatar = (element: any, userInitials: string) => {
    ReactDOM.render(
        Avatar({
            initials: userInitials
        }),
        element
    );
}

interface ChatUser
{
    id: string;
    initials: string | undefined;
    name: string;
}

const renderChatWindow = (element: Element, channelId: string, token:string, userID: string, userName:string, users: ChatUser[], activitiesString: string | undefined) => {
  
    const activityMiddleware = () => (next: any) => (card: any) => (children: any) => {
        let from = "";
        let isUser = false;
        let initials = "";

        const activity: Activity = card.activity;

        if (activity.from && activity.from.role && activity.from.name) {
            from = activity.from.name;

            const user = users.find(u => u.name === from);
            if(user && user.initials){
                initials = user.initials;
            } else if(user) {
                const name = user.name.replace(/[^a-zA-Z]/gi, '');
                if(name.length >= 2){
                    initials = name.slice(0,2).toLocaleUpperCase();
                }
            }else {
                initials = "BT";
            }

            if (activity.from.name !== userName) {
                activity.from.role = 'bot';
            } else {
                isUser = true;
            }
        }

        return (
            <div>
                <div style={{ float: isUser ? 'right' : 'left', padding: "0 0.5rem" }}>
                    <Avatar initials={initials} userName={from} />
                </div>{next(card)(children)}</div>
        )
    };

    ReactDOM.render(
        <ReactWebChat
            store={createStore({})}
            activityMiddleware={activityMiddleware}
            className="chat"
            username={userName}
            userID={userID}
            directLine={new DirectLine({
                token
            })}
            />,
        element
    );
}

export { renderChatWindow, renderAvatar };
```

**Comment by corinagum** [comment]
Closing, as this will not be supported by DLJS in the near future.
