### ISSUE TITLE
Spelling error in French locale for web chat control for the "Retry" option

### ISSUE THREAD

**Issue by jalamanac** [Microsoft/BotFramework-WebChat#817]
Hi

when using the web chat control with French language as the regional settings, and a message can't be delivered to the Bot Framework, the correct spelling should be : 
 "envoi impossible r**ée**ssayer" and not  "envoi impossible r**eé**ssayer"  (in English, the sentences is "couldn't send, retry")

**Comment by billba** [comment]
Thanks for the bug report - would you like to file a pull request for this correction? [Here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Strings.ts#L202) is the relevant line.

**Comment by jalamanac** [comment]
Hi
I'm pretty new to GitHub, how do you file a pull request? Does it mean I will do the correction myself?

**Comment by compulim** [comment]
Fixed in #818.
