### ISSUE TITLE
How to populate Activity.From.Properties ??

### ISSUE THREAD

**Issue by saravana13** [Microsoft/BotFramework-WebChat#824]
How to pass from properties from iframe as like we pass username and userid?

**Comment by billba** [comment]
Activity.from is automatically populated by the username and userid you provide.

**Comment by saravana13** [comment]
yeah but i need to populate activity.from.properties it ll always null

**Comment by billba** [comment]
I don't know what you mean by `activity.from.properties`. `activity.from` has two fields - `id` and `name`. You supply these as part of the DirectLine parameters when you create WebChat, and then WebChat applies them to every activity it sends.

**Comment by JulzB** [comment]
I think he needs to send more data besides the UserId and the name fields. I'm experimenting the same problem.

**Comment by compulim** [comment]
I think Direct Line filtered it.
