### ISSUE TITLE
Disable autofocus when first time open a control

### ISSUE THREAD

**Issue by nicksav** [Microsoft/BotFramework-WebChat#825]
Guys, looks like it might be already fixed, but I can't find where...
The issue is when opening on mobile, onload it make a focus on input text and bring the mobile keyboard.
Any way to disable such behavior and open Keyboard only when user clicks on text box?

Thanks
Nick

**Comment by corinagum** [comment]
Greedy focus has been fixed in v4. For v3, please track this issue at https://github.com/Microsoft/BotFramework-WebChat/issues/568
