### ISSUE TITLE
IE and Edge browser comparability issue with bot connection 

### ISSUE THREAD

**Issue by Rajeshnaiduk** [Microsoft/BotFramework-WebChat#826]
Hello ,

The below code is not working in Edge and IE browsers , where as working in chrome .Can some one help me to work in IE and Edge browsers . I am not getting any error bot chatbot box is appearing as blank in IE and Edge .

Note- In below code I didnt provide secret key.

looks like , after my research in below code operator  ... and => are not comparable with IE and Edge , looking for replacement of those operators or any other way to implement. Looking for help !! 

<!DOCTYPE html>
<html>
<head>
    <title>BOT Appplication</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="creative.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>

        window.onload = function () {

           var baseUrl = (window.location).href; // You can also use document.URL
           var Cid = baseUrl.substring(baseUrl.lastIndexOf('=') + 1);
   

           var vUserid = Math.random().toString(36).substr(2, 5);

            var model = {             
                "botId": "BOT",
                "botName": "BOT",
                "secret": "------------------------------------------------------------------"
            };
            var botConnection = new BotChat.DirectLine({secret: model.secret});

            BotChat.App({
                botConnection: {
                    ... botConnection,
                            postActivity: activity => {
                                if(activity.channelData==undefined || activity.channelData===null){
                                    activity.channelData={ };
                                }
                                activity.channelData.caseId = Cid;

                                
                            return botConnection.postActivity(activity);
                        }
        },
       
        user: { id: vUserid, name: "Rajesh"},
        bot: { id: model.botId, name: model.botName },
        resize: 'window',
        }, document.getElementById("botchatPane"));
        };
    </script>
</head>
<body id="myPage" style="background-image: url('Assets/header.jpg');">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div id="botchatPane" style="height:500px; width: 480px;  bottom: 1px; background: white; position: absolute; left:0; right:0; display: inline-block; margin-left: auto; margin-right: auto; border:1px solid #808080"></div>
        <table width="100%">
            <tr>
                <td>
                    <img style="margin-left:30px;" src="Assets/image.png" />
                </td>
                <td align="right">
                    <img style="margin-right:30px;" src="Assets/123.png" />
                </td>
            </tr>
            <tr>
                <td align="center"></td>
                <td align="right"></td>
            </tr>
        </table>
    </nav>
</body>
</html>

**Comment by billba** [comment]
Correct, IE doesn't support these modern JavaScript constructs. Here is a little about [...](https://stackoverflow.com/questions/32925460/object-spread-vs-object-assign) and [=>](http://es6-features.org/#ExpressionBodies).

Another approach is to continue to write your client code in modern JS and use TypeScript or Babel to transpire down to ES5.
