### ISSUE TITLE
How to authenticate users?

### ISSUE THREAD

**Issue by saravana13** [Microsoft/BotFramework-WebChat#827]
i am building a web chat bot using c# which is embedded into my application using iframe? Is there any way to pass the oauth2 authentication token from my main application to the bot? or something like if the user is logged into my main application i should not redirect user to login page or else redirect to login page and get token from there. Please suggest

**Comment by akasranjan005** [comment]
Hope this will help,
https://stackoverflow.com/questions/39080683/bot-framework-sign-in-card-how-get-auth-result

**Comment by compulim** [comment]
We recently added OAuthCard in [0.13.0](https://github.com/Microsoft/BotFramework-WebChat/releases/tag/v0.13.0).
