### ISSUE TITLE
Messages are repeated when user.id is not string

### ISSUE THREAD

**Issue by kpelckmans** [Microsoft/BotFramework-WebChat#828]
My bot sometimes repeats the message that the user is typing:
![data_science_consultant_-_belgium_-_hedera](https://user-images.githubusercontent.com/19192256/34483539-7bb12934-efbf-11e7-9474-13cfe69643fe.jpg)

Does anyone know what could be causing this repeat?

My code:
```
<div id="bot" style="height: 460px"/>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>
      var userId = (new Date()).getTime();
      BotChat.App({
        directLine: { secret: 'my secret here' },
        user: { id: userId, name: 'You' },
        bot: { id: 'my bot id' },
        resize: 'detect',
        sendTyping: false
      }, document.getElementById("bot"));
    </script>
```

**Comment by saravana13** [comment]
You found any fix? i am also facing this issue

**Comment by kushalbhabra** [comment]
This got resolved for me when I changed user.id from Integer to String.

**Comment by kpelckmans** [comment]
It worked! Thanks for the tip!

**Comment by billba** [comment]
We should be more robust about parameter types.
