### ISSUE TITLE
npm install fails on Windows 10 with python27 and/or VCBuild.exe missing

### ISSUE THREAD

**Issue by codepic** [Microsoft/BotFramework-WebChat#830]
## Symptoms

Running `npm install` leads to following errors:

```
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
```
and / or

```
Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studi
o 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\Username\source\repos\BotFramework-WebChat\node_modules\node
-sass\build\binding.sln]
```

## Potential fix

Running `npm install -g windows-build-tools` from an elevated PowerShell (run as Administrator)
And then running `npm config set msvs_version 2015 -g`

Sorted the issue for me.

Can someone verify?

**Comment by compulim** [comment]
This happen when running an old `node-scss` with a newer version of Node. Normally, `node-scss` will downloading official binaries for the combination. But in case the version combination is too different, `node-scss` will try to compile `LibSass` by itself thru `node-gyp` and Python. And it also requires Windows SDK and VC++.

**Comment by eanders-MS** [comment]
@codepic Thanks, your potential fix worked for me.
