### ISSUE TITLE
Browser hangs with multiple instances of WebChat

### ISSUE THREAD

**Issue by sreeharikm** [Microsoft/BotFramework-WebChat#831]
We are using DirectLine with WebChat (version 10.6). To support instant updates at the client side and to retrieve the chat history, we are using polling mode (passing webSocket=false in chat.html) with a polling interval of 1sec. But this is making the browser hung after some time. Is there a way to switch the mode to webSocket without reloading the chat.html? Or is there an option to change to polling frequency after some time (may be after loading the welcome message, change the frequency to 5sec)? Please share your thoughts.

•SDK Platform: .NET
•SDK Version: 3.5.5
•Active Channels: DirectLine

Thanks
 Sreehari

**Comment by billba** [comment]
The unhelpful high-level answer is that you want WebSocket + History. We are working on the best solution for this, please stay tuned.

Specifically, I haven't seen any other reports of a hung browser with a 1 sec polling interval, which is the default. Which browser are you using?

**Comment by sreeharikm** [comment]
@billba, the hung browser issue is happening when multiple chat pages are open in tabs (I am using Chrome). As a work around, we are increasing the polling interval for now. Kindly reply once you have a better solution.

**Comment by billba** [comment]
Can you say more about the hung browser issue? I think you are saying that you have multiple web pages open, each with an instance of WebChat. Are they all pointing at the same bot, or at different bots?

**Comment by sreeharikm** [comment]
I had the issue, when multiple chat.html instances were opened on different tabs. All instances were polling @1sec and pointing to the same bot.

**Comment by billba** [comment]
1. How many instances?
2. How was Web Chat implemented on the page? In an `iframe`, using `BotChat.App`, or as a component in a React app?
3. Can you specifically define "hung"? Was it the entire browser or just each instance? If the latter, were other elements non responsive, or was it just Web Chat itself?If the latter, was *it* non responsive, or did it just e.g. stop receiving messages?

**Comment by sreeharikm** [comment]
1. 4-5 instances.
2. Iframe.
3. Entire browser was hung, have to kill the process from task manager to use the browser again.

**Comment by billba** [comment]
Great, thanks for the data. I've renamed this issue to focus on the hanging problem.

**Comment by sreeharikm** [comment]
Thanks, kindly let me know once you have a solution for the polling mode/interval change option.

**Comment by corinagum** [comment]
Our eventual workaround is related planned updates to DirectLineJS, which will lower the resource requirements on the client machine. This can be tracked over at https://github.com/Microsoft/BotFramework-DirectLineJS/issues/88
