### ISSUE TITLE
Max Upload file size direcline.botframework.com

### ISSUE THREAD

**Issue by Polaris-BS** [Microsoft/BotFramework-WebChat#833]
I have the sames problemes .  I use the webview and the photo is superior at 10Mo. 

![image](https://user-images.githubusercontent.com/20790689/34687940-aec3c868-f4b0-11e7-8a3e-20f6e0ea309a.png)

My web.config is :  <requestLimits maxAllowedContentLength="4294967295" />

But has not effect. How to up the value for https://directline.botframework.com I have an error 500 and my bot has no responses

Conversation : G78mKAnIZVR8vcJvrStav4

Response :

`{
  "error": {
    "code": "ServiceError"
  }
}`

**Comment by JasonSowers** [comment]
please see this discussion [here](https://github.com/Microsoft/BotFramework-WebChat/issues/789)  The file size limit was 4MB last we heard according to the thread

**Comment by billba** [comment]
Yup no changes there.
