### ISSUE TITLE
Suggestion: Reactions to messages

### ISSUE THREAD

**Issue by M-Rowley** [Microsoft/BotFramework-WebChat#834]
With the addition of [IMessageReactionActivity](https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-activities#messagereaction) to the bot framework, are there any plans to implement some sort of functionality for this in the webchat?

It would be pretty useful for the user to be able to quickly thumbs up/thumbs down bot responses so that we can get a quick idea of where the bot's training or wording is lacking.

**Comment by corinagum** [comment]
Sorry for the late reply! We now have a sample that you can check out: [activity decorator button](https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/activity-decorator-button)
