### ISSUE TITLE
Feature Request: Date Selection, Preselection

### ISSUE THREAD

**Issue by telkomops** [Microsoft/BotFramework-WebChat#836]
Hi using adaptive cards on my chatbot ui, i have a Adaptive card of "type": "Input.Date".When the user opens up the date panel, i need to high light few dates based on custom logic. I have a specific scenario where input.date selection should be used to pre-filter input.time as part of the same card. 
Request if this is something that we can add as a feature.

**Comment by compulim** [comment]
Looks like it's a [feature request](https://github.com/Microsoft/AdaptiveCards/issues/994) on Adaptive Cards repo.
