### ISSUE TITLE
Adaptive Cards: Embed custom controls

### ISSUE THREAD

**Issue by telkomops** [Microsoft/BotFramework-WebChat#837]
Hi,
Is there a way to embed custom controls with in the Web Chat cards.
For e.g. The Web Chat cards can support any input control as prescribed by http://adaptive.io/schema.
I have a specific requirement to show a custom web control, the contents of the web-control are UI elements like calendar /maps with a pin. Looking for guidance on to accomodate it on Web Chat framework

**Comment by billba** [comment]
You could certainly embed arbitrary controls by customizing the code. You would essentially have to agree on a message format between your bot and WebChat to trigger those controls, and another to transmit the results.

**Comment by telkomops** [comment]
@billba , specifically looking for a way to add a custom calendar control. lets say i have an adaptive card getting rendered, what would be the right way to add a custom calendar to the `http://onefinestay.github.io/react-daterange-picker/`. Need help pointing me in the right direction..

**Comment by telkomops** [comment]
Few guidelines. Fork DirectLine, create your custom card spec. Implement the custom card spec in the Attachment View, for best experience wrap your custom control around adaptive container. 
For events triggered, invoke doCardAction from the custom control to keep the Action behavior the same. I will add details once i find a better approach for custom controls handling their own async calls

**Comment by compulim** [comment]
This is now doable in Web Chat v4 without forking the codebase. There are [some samples here](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples#customization) for adding/replacing activity/attachment, or decorating them.

**Comment by NikkiChristofi** [comment]
> This is now doable in Web Chat v4 without forking the codebase. There are [some samples here](https://github.com/Microsoft/BotFramework-WebChat/tree/preview/samples#customization) for adding/replacing activity/attachment, or decorating them.

Hi, I tried following this link but got a 404. Is there a current working link showing how to decorate an attachment whilst preserving the functionality? E.g. changing the background colour of an action button on an adaptive card without having to implement custom middleware that also has to deal with the submit/click action.

The only sample I can see is here: https://github.com/Microsoft/BotFramework-WebChat/tree/master/samples/10.a.customization-card-components which does not send anything back to the bot, just has a click through link.
