### ISSUE TITLE
Web Chat repeat last user command

### ISSUE THREAD

**Issue by nicksav** [Microsoft/BotFramework-WebChat#839]
Guys, started to see strange thing:
![image](https://user-images.githubusercontent.com/9266365/34808335-0170f5d8-f6da-11e7-932e-5051caf62e0d.png)

Any idea why?

**Comment by kushalbhabra** [comment]
This got resolved for me when I changed user.id from Integer to String.

**Comment by nicksav** [comment]
Perfect! Will try the same!
