### ISSUE TITLE
How is it ensured that user doesn't manipulate user id?

### ISSUE THREAD

**Issue by kushalbhabra** [Microsoft/BotFramework-WebChat#840]
I've hosted botchat.js in my website and i'm initializing bot with user id like shown below
`
var  user = { id: 'userid', name: 'name'};

BotChat.App({
   bot: bot,
   botConnection: botConnection,
   user: user
 }, document.getElementById('BotChatElement'));
`
Since this happens on client browser, how is it ensured that user doesn't manipulate the script in browser console, or host this code in his own site, use token captured on this page and pass different user id?

Not sure if this is an issue, maybe I'm missing something.

**Comment by ukphillips** [comment]
I agree with the concern above and would like to know what everyone's opinion is on this. Is the intention of that user identity to be for use when making requests downstream (as a trusted user), or is this just something nice to the bot can display some information about the user early on?

**Comment by billba** [comment]
In Web Chat `user` is indeed used just for visually attributing a message.

The Bot Framework uses `user.id` is used by is as a key for accessing user-specific data in a conversation. In other words, if you have users A, B, and C  in a single conversation with a pizzabot, and ask everyone to say what they want on their pizza, you can store each of their preferences separately.

Unlike full-fledged messaging systems, e.g. Skype or Facebook Messenger, Direct Line doesn't have an identity system. When you deploy Web Chat yourself (as opposed to using the Web Chat channel) you create and manage your own user identities. If you want a more secure notion of user identity, do something more secure like passing security tokens via the backchannel.

**Comment by compulim** [comment]
@kushalbhabra it is more like HTTP cookie. If the user have access to JS, they could modify the cookie.

I will do something like this (essentially, the same thing as you would handle user ID on a HTTP cookie):

1. Browser ask server to generate a new user ID
2. Server generate a new ID payload with SHA signature (to prevent modification)

On the server side, every time it read the user ID, it verify the SHA signature to make sure the user ID is not forged.
