### ISSUE TITLE
Webchat iFrame intermittently not loading, showing "The service is unavailable."

### ISSUE THREAD

**Issue by shriiitk** [Microsoft/BotFramework-WebChat#844]
I have embedded webchat in my page which sometimes doesn't load and show "The service is unavailable." message instead of chat window. If I check browser's dev console it says **503 - Service Unavailable**
The iFrame url( https://webchat.botframework.com/embed/omnibotdemo?s=<MY_SECRET>&username=<UNAME>&userid=<UID>___123213 ) when I open in new window also show the same error.
![screenshot_6](https://user-images.githubusercontent.com/2655584/35092357-217af1ea-fc65-11e7-947e-cb714c3371d6.png)

Are there outages going on? Is there a way to check service status or get more reliable server because its very important business functionality?

**Comment by shriiitk** [comment]
Sometimes getting the following errors when blank iFrame loads:
![screenshot_7](https://user-images.githubusercontent.com/2655584/35092489-9020c3a4-fc65-11e7-812d-36e109725585.png)

![screenshot_8](https://user-images.githubusercontent.com/2655584/35092532-b87ac0e8-fc65-11e7-8579-a5898125bc17.png)

**Comment by shriiitk** [comment]
I am continuously getting errors
![screenshot_9](https://user-images.githubusercontent.com/2655584/35093266-ec77436a-fc67-11e7-8ded-20320db90aae.png)

**Comment by stoconnor** [comment]
Managing custom state data will resolve these 503 errors. I was getting them too then set storage to CosmosDB and it resolved the issue. 

https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-state-azure-cosmosdb

**Comment by compulim** [comment]
The Bot State API is deprecated and migrate to Cosmos DB. Thanks @stoconnor for the answer.
