### ISSUE TITLE
Welcome message does not work in messenger but works on emulator

### ISSUE THREAD

**Issue by shariaretanvir** [Microsoft/BotFramework-WebChat#847]
I created a simple bot in **c#**. i added a **welcome message** which perfectly shown on emulator and also on azure test emulator. but when i publish it on **Facebook messenger**  welcome message doesn't appear. what should i do ?

**Comment by billba** [comment]
I'm sorry to hear about your problem, but this repo is for Web Chat, not general issues with building bots. I suggest filing this issue at the [BotBuilder](http://github.com/microsoft/botbuilder) repo.
