### ISSUE TITLE
Better inline documentation for the Store.ts

### ISSUE THREAD

**Issue by mxdi9i7** [Microsoft/BotFramework-WebChat#857]
I just had a little interaction with the codebase of this project yesturday. I think this project's inline documentation needs to be more complete and comprehensive. Sometimes there are couple lines of comments here and there explaining what the block of code does but most of the time there isn't anything that describes the code's feature.

Considering that this is a demo for people to begin exploring the botframework's webchat, I think it makes sense to add more inline docs to the code to make the codebase more friendly to beginners expecially the Store.ts where there's lots of pieces moving.

If this is something you guys would like I could submit a PR for more comprehensive inline docs

**Comment by billba** [comment]
I don't think this is true:

> this is a demo for people to begin exploring the botframework's webchat

Web Chat is not a demo. It is a real software product. Most developers who want to incorporate Web Chat into their web sites will not need to go into the codebase. I'm not saying the could shouldn't be clear, just pushing back on the notion that the Web Chat code itself is meant to be an educational experience for most bot developers. It is not.

That said, I'm certainly open to adding comments where the purpose of the code is not clear. But "comprehensive inline docs" sounds like overkill.

**Comment by mxdi9i7** [comment]
Oh well, understood, I'll submit a PR anyways and see what you guys think of it. but in my opinion web chat is a starting boilerplate for people who want to customize their web chat experience both in terms of style and behavior. Documentation would just be easier for developers who are looking to tweak the product and build it into something new

**Comment by billba** [comment]
I mostly agree with that. Web Chat is much more than boilerplate - it's a working product that meets almost everyone's needs out of the box. Some may wish to customize styling, which doesn't require any knowledge of the code. As for those developers who need to customize behavior - or contribute improvements back to the main project - it is obviously important that they understand what's going on. I look forward to seeing your PR.

**Comment by mxdi9i7** [comment]
I agree that it is a complete and awesome project that you guys have put together, the best solution existing actually, for almost any use case. for me though picking up typescript in a new project still takes some effort to get used to it. It'd be really helpful for me if there's more explanation in the README. 

For instance I'm having trouble subscribing/listening for store state change from a different component than the one fired the action. What is the common way to listen for state change in my case?

**Comment by billba** [comment]
Ha ha - I'm not trying to defend the project, it's just that you kept saying things I disagreed with :-)

It sounds like you are asking a generic Redux question, which is exactly the sort of thing that documentation should *not* try to answer.

StackOverflow would be a better place for questions like this. If you ask it there and paste the link here I'll answer it there.

I'm going to close this issue, but feel free to file PR(s) if you feel there are places that things could be better explained.
