### ISSUE TITLE
Prompt Choice and HeroCards use the same adaptive cards configuration

### ISSUE THREAD

**Issue by mxdi9i7** [Microsoft/BotFramework-WebChat#862]
I have 2 different types of multiple choice response, one uses the builder.Prompts.choice to receive a user prompted response. The other one uses the HeroCards to display a carousel of options where you can use the carousel arrows to navigate to different items. 

The problem is, both of which use the adaptive cards framework to render its style, which means if I attempt to change the styles in the config json file, it applies the style to both the carousel and the multiple choice buttons. Also the styles rendered are inline css that overrides any customization I attempted in the botchat.css.

I also tried removing the configuration json entirely, but adaptive cards component stops display after I did that.

My question is: Is there a way to customize the style for carousel and multiple choice buttons separately? It seems like they are both treated as adaptive cards and use the same set of configuration.

I also checked the documentation for adaptive cards configuration fields, but didn't find anything useful to solve my problem.

**Comment by billba** [comment]
All card types are rendered using Adaptive Cards so, yes, they all share a single style, for better or for worse.
