### ISSUE TITLE
Support for bot avatar

### ISSUE THREAD

**Issue by JobaDiniz** [Microsoft/BotFramework-WebChat#871]
Is there a way to show bot avatar like any other chat, example:

![image](https://user-images.githubusercontent.com/165290/36792637-d7baf9f8-1c79-11e8-8443-131b5cb0392c.png)

**Comment by compulim** [comment]
Currently it is not supported. But as a workaround, you should be able to hack into our CSS to add the avatar icon.

To enable avatar icon broadly, Direct Line will need to be updated to retrieve avatar icon from various sources (e.g. Skype, Slack, Facebook). And avatar icon also means we might want to support multi-party conversations

**Comment by MichaelBartlettGitHub** [comment]
Can someone leave some code for hacking the css in the IFRAME?  I have tried everything and I cannot get this to work.   I am trying to inject the style.

**Comment by bauhaux** [comment]
This basic UI feature seems to be sorely missing from the bot framework. There's also no direction on how, if possible, this is done in directline.

**Comment by compulim** [comment]
This is coming as a customization feature.

We talked about avatar long time ago, there are multiple things we need to handle:

* Direct Line API does not have a way to retrieve bot icon you saved on the bot channel registration
* Multi channel/user support means Web Chat may need to ask Skype for icons for some users
* If no icon is loaded, we need to use the user initial to generate an avatar icon, but then it may lack of customizability

We aimed big, but these issues are not easy to solve (e.g. multi channels). Now we are backtracking and just allow dev to put any icons.

Anyway, it's coming.

**Comment by peltemm** [comment]
i found this place a good alternative
.format-markdown{
        background-image: url(../../src/assets/img/svg/myAvatar.svg);
        background-repeat: no-repeat;
        background-position: left top;
        background-size: 30px 30px;  
    }
    .format-markdown>p {
        margin-bottom: 0px; 
        padding: 30px;      
    }

**Comment by Chitma** [comment]
I tried to change botchat.js and botchat.css, It works but the same image is being shown for user and bot. I just wanted it for bot. Since, minified botchat.js is tough to debug and modify, can anyone please guide me how do I add bot icon only for each bot message in webchat using Directline. bot image is constant and will be only hosted on webchat. 
@compulim

**Comment by corinagum** [comment]
Please refer to #882 for tracking.
