### ISSUE TITLE
Typing indicator is inconsistent between Web Socket and comet

### ISSUE THREAD

**Issue by m0ritzb** [microsoft/BotFramework-WebChat#872]
Hello,

I've developed a bot with node.js and used the emulator to test it during the development phase. 
Now I wanted to deploy the bot using Azure over the WebChat channel and show the chat window via Iframe on a website.
Everything works fine with the exception that the typing indicator shown by the emulator doesn't appear at all. The delays I used during which the typing indicator should be displayed work fine but the animation isn't shown at all.
Any information on why that may be or instructions to a workaround would be greatly appreciated!

Cheers, 
Moritz

**Comment by m0ritzb** [comment]
Do typing indicators require the use of the DirectLine WebSocket or is there a fix to achieve the display of the indicators with the use of the normal webchat channel and Iframe? 
Can anybody confirm either possibility?
Cheers

**Comment by compulim** [comment]
I think the typing indicator only send via WebSocket but not over HTTP. But I am not 100% sure about it. It should be something related to `BotConnection` provider. @m0ritzb do you have some time to investigate it?

**Comment by eanders-MS** [comment]
@compulim That's correct, typing indicator is only sent over WebSocket.

**Comment by compulim** [comment]
Is it the limitation on DirectLine API or our code?

**Comment by eanders-MS** [comment]
I think the idea behind this design was that typing indicators are ephemeral messages and should be delivered immediately rather than queued for delivery some time in the future.

**Comment by billba** [comment]
It's a nasty little chicken-and-egg situation. DL doesn't support message history with Websocket, so people are using Polling, which doesn't support typing because typing doesn't makes sense in a message history.

My preference would be to move both WebSocket and Polling customers over to an official (and orthogonal) approach to storing and retrieving history. And that approach would be smart enough to not show typing activities when displaying historical messages.

**Comment by compulim** [comment]
@EricDahlvang played around with the idea of sending typing indicator as a event activity in [https://github.com/Microsoft/BotBuilder/issues/4663].

Until DL support typing on polling, or we push everyone to WS. We can temporarily point people to Eric's code.
