### ISSUE TITLE
Webchat UI does not scale appropriately on iPhones

### ISSUE THREAD

**Issue by alexarg** [Microsoft/BotFramework-WebChat#880]
Webchat UI components do not scale well on iPhone devices: the message boxes are small, the font of the messages is tiny and the input box is very narrow, which makes it hard to interact with it using fingers.

This is what I see on iPhone 6 (the behavior on iPhone X is similar, but even worse):
![wrongresolutioniphone](https://user-images.githubusercontent.com/968199/37059582-b072788a-2142-11e8-9fd2-2bbd88cc3a95.png)

**Comment by danmarshall** [comment]
Is this in a native WebView. or an Iframe?

**Comment by danmarshall** [comment]
also, make sure you are using a mobile meta-tag: https://github.com/Microsoft/BotFramework-WebChat/issues/537#issuecomment-314180249

**Comment by alexarg** [comment]
This surfaces in a native WebView. meta-tag helped, thank you!

**Comment by compulim** [comment]
That's great. I will close this for now.
