### ISSUE TITLE
Display avatar on bot side

### ISSUE THREAD

**Issue by kesuke17** [Microsoft/BotFramework-WebChat#882]
I tested it as botchat.css as follows, but an icon is displayed on both the bot side and the user side.

------------------------------------------------------------------
.wc-message.wc-message-from-bot::before {
  content: url(xxxxxxxxxxxx.png);
  float:left;
}
------------------------------------------------------------------
Please let me know how to display the icon only on the bot side. 

（google translate）

**Comment by shikelong** [comment]
+1

**Comment by compulim** [comment]
We currently only support initials for bot avatar without deep customization. We need a sample, and that would probably involve modifying production code a bit to make the sample intuitive enough.

**Comment by compulim** [comment]
The work is done in PR #1486.

You can specify either/both bot/user side as initials and/or image.

**Comment by compulim** [comment]
The PR is being merged and it will be resolved by `@4.2.1-master.d35a7ac` and `>= @4.2.1`.

**Comment by YeisonsUarez** [comment]
In case someone is still looking for 
https://stackoverflow.com/questions/56474336/how-to-fix-issue-of-html-page-for-web-chat-bot-developed-in-c-sharp-using- sdk-v4
