### ISSUE TITLE
Sample: Add typeahead as hints in the message input field

### ISSUE THREAD

**Issue by anarchitect** [microsoft/BotFramework-WebChat#896]
Hi, can we add typeahead into message input field of the chat window?  Currently our chat box still needs lots of facilitation, such as type help, pop up what can the chatbot do etc.  If we can have typeahead in the chat message input field, and typeahead can give hints when user start to type, then it will help user type the expected utterance and help the bot-human communication more fluent.  

For example, if the bot can do "create defect, queue a build, search log" etc, when user type defect, the typeahead can display the best matched utterances, and user can intuitively select "create defect" or "check defect status".  In this case, the bot doesn't have to pop up a list of what they can do , and either they need a lot of help content developed.. Thoughts? thanks.

**Comment by compulim** [comment]
How about suggested actions?

![image](https://user-images.githubusercontent.com/1622400/37316048-342dc7e8-261a-11e8-8e3a-e03b3640c594.png)

**Comment by compulim** [comment]
Could be extension of sample #1091.
