### ISSUE TITLE
Store conversation data

### ISSUE THREAD

**Issue by saikatbh94** [Microsoft/BotFramework-WebChat#902]
Hi, I am using Bot framework to build a bot application, where I need to store the conversation data in a cosmos db or any other database so that at any point of time i can access those data and display them whenever necessary. I want to know where to put all the code snippets necessary for this step. I tried integrating it with redis-cli, but i could not find any relevant data or code explaining this. Please help me asap. 

I found this [code:](https://azure.microsoft.com/en-in/blog/bot-conversation-history-with-azure-cosmos-db/)

Please help me find all the fields that are used in this code segment.

**Comment by compulim** [comment]
Currently, there is no easy way to save conversation. There is a [PR](https://github.com/Microsoft/BotFramework-WebChat/pull/615) going on. It works, but the direction it is going is not very visionary, thus, we put it aside and back to the drawing board.

**Comment by corinagum** [comment]
Please refer to #365 for tracking.
