### ISSUE TITLE
The role of userId is not clear to me

### ISSUE THREAD

**Issue by Arash-Sabet** [Microsoft/BotFramework-WebChat#903]
Would someone please clarify the role of userid below for me? The question is that how the asp.net application will receive it?

`user: { id: 'userid' }`

**Comment by EricDahlvang** [comment]
Hi @Arash-Sabet 

user id is the identity of the user and will be received in the MessageController's Post method's Activity object's .From.Id property.

More information about user ids can be found here: https://docs.microsoft.com/en-us/bot-framework/bot-service-resources-identifiers-guide#channel-account

**Comment by Arash-Sabet** [comment]
Thanks @EricDahlvang for the clarification.
