### ISSUE TITLE
Rendering BOT in IEFrame giving errors

### ISSUE THREAD

**Issue by activex2000** [Microsoft/BotFramework-WebChat#905]
Hi,

I have a BOT which run perfectly fine in its own standalone browser but it start throwing error randomly when it is hosted inside IEFrame in Edge browser. 
![screenshot](https://user-images.githubusercontent.com/2207232/37546428-b60972f6-2964-11e8-97c4-4d1e54a01953.png)

**Comment by JasonSowers** [comment]
Could you please share the code you are using for your iFrame?  Please do not include your web chat secret token.

**Comment by Kartik1607** [comment]
Refer to solution here : https://github.com/Microsoft/BotFramework-WebChat/issues/916

**Comment by compulim** [comment]
Thanks @Kartik1607!
