### ISSUE TITLE
Clicking the suggested action button or Adaptive Card action button renders the payload/value instead of text in the webchat

### ISSUE THREAD

**Issue by surki01** [Microsoft/BotFramework-WebChat#907]
Hi,

We use suggested actions and adaptive cards with action buttons to show the data to the user. The payload behind these action buttons might contain IDs corresponding to the record.

For example, if I want to show the list of users as suggested actions, the title of the button would be "username" and payload would be "user_uuid". In this case, when the user clicks the suggested action button, we don't want to show the payload (user_uuid) instead show the title (username), but send the payload to the backend. Currently, we are using ImBack

Do we have any property/configuration that makes the decision of showing title vs payload?

**Comment by compulim** [comment]
I think you are talking about the code [here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/AdaptiveCardContainer.tsx#L111).

The current behavior for `SubmitAction` is, if the `action.data` is a `string`, then we will send it using `imBack` (visible to user), otherwise, we will send it using `postBack` (invisible to user).

**Comment by surki01** [comment]
@compulim Thanks for your reply.

I am looking for the behavior where we send the action Button payload to the backend, but show the title to the user. Is there any configuration available to do this?

**Comment by compulim** [comment]
There is no configuration for that, it's either `imBack` or `postBack`.

`imBack`: user will see what is sent to the server in `imBack`
`postBack`: user won't see anything

There is nothing like, send "A" but show "B". But you can always fork the code to hack it around.

**Comment by compulim** [comment]
I have added this as a enhancement in our upcoming work.
