### ISSUE TITLE
Failed to load custom bundled CSS using Webpack

### ISSUE THREAD

**Issue by jcjp** [Microsoft/BotFramework-WebChat#912]
I cloned this repository and edited some colors, however when I add it on my web page it does not render properly. It only displays like this: http://prntscr.com/iukss4, I already added the styles on my .angular-cli.json file but still it is not working.

But whenever I use npm install botframework-webchat directly on my application I am able to render the UI of the bot properly, but unable to edit this since it will always be coming from this repository.

**Comment by compulim** [comment]
Looks like your browser is not able to load your updated `botchat.css`.

**Comment by jcjp** [comment]
Here is what is being loaded on my webpage:

![image](https://user-images.githubusercontent.com/37642320/37814934-a555fc16-2ea7-11e8-9902-60fcbf74d752.png)

**Comment by jcjp** [comment]
@compulim you are correct that the CSS files needed are not loaded properly in Angular. Here is my configuration of my .angular-cli.json:

> "styles": [
>         "styles.css",
>         "../node_modules/botframework-webchat/botchat.css",
>         "../node_modules/botframework-webchat/botchat-fullwindow.css"
>       ],
>       "scripts": [
>         "../node_modules/botframework-webchat/botchat.js"
>       ]

Not sure what is wrong with my configuration.

**Comment by compulim** [comment]
Is the problem fixed now? Looks like your bundler isn't taking the CSS file in, or it scoped the CSS.

We are currently working on revamp of Web Chat, the CSS will be inlined in React components and provide CSS insertion points for devs to add rules to specific components.

**Comment by compulim** [comment]
Close due to inactivity.
