### ISSUE TITLE
Speech: Bing Speech throw error on close

### ISSUE THREAD

**Issue by deejay28** [Microsoft/BotFramework-WebChat#915]
Hi,

We are trying to integrated BING speech API with our webchat control. The code is working fine on chrome but it is giving error on Microsoft Edge. Hereby the error description:
![image](https://user-images.githubusercontent.com/26995972/37810687-8f92f4b4-2e7b-11e8-9998-e112fdb4d4d0.png)

 #506

**Comment by compulim** [comment]
Support: can you repro the issue using Web Chat and Bing Speech?

**Comment by corinagum** [comment]
Hi @deejay28, could you share some more information regarding this problem?
What is the conversation flow of the bot when this error occurs?
Does this problem still occur when run Incognito on Edge?
Are you using Embed or CDN? If CDN, what version are you using?

**Comment by corinagum** [comment]
Closing due to lack of response.
