### ISSUE TITLE
npm install error: webpack.production.config.js:5 “...config”, SyntaxError: Unexpected token ”... 

### ISSUE THREAD

**Issue by ttma1046** [Microsoft/BotFramework-WebChat#922]
I run npm install right after git clone:

NPM error:
···
BotFramework-WebChat-Demo\webpack.production.config.js:5
    ...config,
    
SyntaxError: Unexpected token '...'
···

Question: 

Which part of config/node packages handles the 'rest spread operator' in this webpack.production.config.js ??

Since I didn't see any ts config or any babel to handle this ?

**Comment by Alaiven** [comment]
Updating to the newest node.js version resolved the issue for me on Windows
