### ISSUE TITLE
Adaptive Cards: Column width is not set correctly

### ISSUE THREAD

**Issue by petrformanek** [Microsoft/BotFramework-WebChat#923]
Hello,
I'm playing with adaptive cards in web chat and I'm facing an issue with setting of column width. See code and screenshots.
It works well in the [visualizer](https://adaptivecards.io/visualizer/index.html?hostApp=Bot%20Framework%20WebChat).
Please can you fix the issue or help me to workaround it?

Sample code:
```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
          {
            "type": "Container",
            "items": [
              {
                "type": "TextBlock",
                "size": "large",
                "weight": "bolder",
                "text": "Welcome!",
                "separator": true
              },
              {
                "type": "ColumnSet",
                "columns": [
                  {
                    "type": "Column",
                    "width": "auto",
                    "items": [
                      {
                        "type": "Image",
                        "size": "small",
                        "url": "http://localhost:3978/img/oribot_logo.png"
                      }
                    ]
                  },
                  {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                      {
                        "type": "TextBlock",
                        "size": "medium",
                        "text": "I am Oribot"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "type": "TextBlock",
            "text": "I can help you with following questions:",
            "wrap": true
          }
        ],
        "actions": []
}
```

Emulator/WebChat result - incorrect result:
![image](https://user-images.githubusercontent.com/19287495/38036403-e87a3072-32a6-11e8-95ff-b93300064cc7.png)

Visualizer - correct result:
![image](https://user-images.githubusercontent.com/19287495/38036800-d65ce10e-32a7-11e8-86af-7e62f0468cd2.png)

**Comment by torynfarr** [comment]
I've been running into exactly the same thing. It seems like the AdaptiveCards v1.0.0 package doesn't handle the "width" property of columns correctly when loading and rendering an adaptive card from a JSON file. That, or it's the web chat channel itself. Either way, there's an easy work-around.

When you define your column width as auto, stretch, or as a numerical value... specify the same value, but using the size property.

`"columns": [
                  {
                    "type": "Column",
                    "width": "auto",
                    "size:": "auto",
`

**Comment by Kartik1607** [comment]
The bot emulator currently renders according to https://github.com/Microsoft/AdaptiveCards/issues/1255 issue. Also, make sure you are using latest webchat to use adaptive card 1.0 schema

**Comment by compulim** [comment]
@petrformanek I think Emulator v3 is using pretty old version of Web Chat. v4 is in the brew.

@torynfarr do you mean this is bug is on the AC side?

**Comment by compulim** [comment]
In v4, we have a clipping issue https://github.com/Microsoft/BotFramework-WebChat/issues/1338, and that might regress this bug.

**Comment by corinagum** [comment]
Hi everyone, sorry for the delay in checking on this issue. 
I was able to upload the above provided .json into a v4 Web Chat client, and I have confirmed that the Adaptive Card is rendering as expected:
![image](https://user-images.githubusercontent.com/14900841/51286974-45eff800-19aa-11e9-986f-df86d9ce6881.png)

In the case of this error showing on Emulator, the app is currently being updated to use the latest Web Chat, and that issue can be tracked here: https://github.com/Microsoft/BotFramework-Emulator/issues/1206
I strongly recommend updating (both Emulator and Web Chat) to v4. Please take a look at the samples if you want to learn more, or @ me and I am happy to help. :)
