### ISSUE TITLE
Injecting history

### ISSUE THREAD

**Issue by youtoofan** [Microsoft/BotFramework-WebChat#926]
Hi,

I have my backend pushing activity history to my webchat client when someone connects or reconnects.
In my javascript I have the following:

    var lastActivityId;

    const handleConversationHistory = function (activities) {

        if (activities.length <= 0)
            return;

        var container = document.createElement("div");
        container.className = "wc-message-group-content";

        $.each(activities,
            function (index, activity) {
                if (activity.type !== "event") {
                    if (activity.from.id === user.id) {
                        lastActivityId = ("0000000" + (parseInt(activity.id.substr(activity.id.length - 7)) + 1)).slice(-7);
                        const inner = fromMe.format(activity.id, activity.text, activity.from.name);
                        const fromMeElement = document.createElement("div");
                        fromMeElement.innerHTML = inner;

                        container.appendChild(fromMeElement.firstChild);
                    } else {
                        const temp = activity.replyToId.substr(0, activity.replyToId.indexOf('|')) + "|" + lastActivityId;
                        const innerAgain = fromBot.format(temp, activity.text, activity.from.name, new Date(activity.timestamp).toLocaleString());
                        const fromBotElement = document.createElement("div");
                        fromBotElement.innerHTML = innerAgain;

                        container.appendChild(fromBotElement.firstChild);
                    }
                }
            });

        document.getElementsByClassName("wc-message-group-content")[0].outerHTML = container.outerHTML;
    };`

At first sight, activities are inserted nicely into the chat window, and I see the entire history. 
But when I post another question to the bot, my question and the corresponding answer are added at the top of the history activities, not at the bottom. So they are in fact inserted at index 0, instead of history.length + 1. 

And for the moment I can only handle IActivity of type messageActivity, not yet Herocards or other types.

**Comment by JasonSowers** [comment]
I made a project a while back that injects chat history into the webchat control.  It may help you https://github.com/JasonSowers/ChatHistoryBot-Public

**Comment by compulim** [comment]
@youtoofan [Here](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/Store.ts#L361) is the code for appending messages. I think we just add it as-is and I didn't see any sorting code in [History.tsx](https://github.com/Microsoft/BotFramework-WebChat/blob/master/src/History.tsx).

BTW, we are planning to complete the preservation/restoration/continuation of history in the next phase. It will be more like @JasonSowers solution, a client-side solution.
