### ISSUE TITLE
Context.Done() in StartAsync Method leading to infinite loop of startAsync calls

### ISSUE THREAD

**Issue by GauravKatariya** [Microsoft/BotFramework-WebChat#927]
Microsoft.Bot.Builder version 3.14.1.1.
Here is brief snap of my code ..  
**MessageController** :- 
if (activity.Type == ActivityTypes.Message)
{  await Conversation.SendAsync(activity, () => new AdaDialog());   }

**AdaDialog()**:- 
public async Task StartAsync(IDialogContext context
{ await context.PostAsync("Hi");
  context.Done(this);
}

I am getting **infinite "Hi"** on bot chat window.
Please help me to understand what is causing this problem

**Comment by EricDahlvang** [comment]
This code is closing the dialog in the StartAsync method.  That is not the intended use of the StartAsync method, it is generally for setting up the dialog.

Please review the samples here: https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp  and https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples  there is also documentation here: https://docs.microsoft.com/en-us/azure/bot-service/ and the Bot Framework team blog here: https://blog.botframework.com/

If you have further questions about usage of the SDK, the best place to find answers is to ask the community on StackOverflow: https://stackoverflow.com/questions/tagged/botframework
