### ISSUE TITLE
Bot Framework Directline channel, Bot titile Logo and welcome message

### ISSUE THREAD

**Issue by padmavatierp** [Microsoft/BotFramework-WebChat#928]
I am using microsoft bot framework, everything is working fine, if i use iframe with direct line secret then its working fine, once i use custom UI for the same it doesn't show Bot icon and welcome message

**Comment by compulim** [comment]
@padmavatierp do you see anything from the console log? Can you tell us more about how you integrate your custom UI?

**Comment by compulim** [comment]
@padmavatierp The bot icon and welcome message was on very old build of Web Chat, we have removed them.
