### ISSUE TITLE
Who Use My websocket server?

### ISSUE THREAD

**Issue by ZeroTiem** [Microsoft/BotFramework-WebChat#931]
===============issue====================
Sorry I have a question
Setting webSocket = 'true'
But C# Web Api 2 IsWebSocketRequest Is False
HttpContext.Current.IsWebSocketRequest Is False
Who Use BotFramework-WebChat In My websocket server?

=================Url========================
Url:http://localhost:2805/Home/WebChat?domain=/api/TestWebSocket

==============html======================
BotChat.App({
            bot: bot,
            locale: params['locale'],
            resize: 'detect',
            // sendTyping: true,    // defaults to false. set to true to send 'typing' activities to bot (and other users) when user is typing
            user: user,
            // locale: 'es-es', // override locale to Spanish

            directLine: {
                domain: params['domain'],
                secret: params['s'],
                token: params['t'],
                webSocket: params['webSocket'] && params['webSocket'] === 'true' // defaults to true
                //webSocket: false // defaults to true
            }
        }, document.getElementById('BotChatGoesHere'));

**Comment by billba** [comment]
Despite its name, Direct Line is not a direct connection between your client and your bot. Instead, the client opens a Web Socket to the Direct Line service, which communicates with your bot via HTTP.
