### ISSUE TITLE
Chat history is lost after the page refresh or on the page navigation.

### ISSUE THREAD

**Issue by ghost** [Microsoft/BotFramework-WebChat#936]
We have implemented chatbot re-connection logic to preserve the chats on page refresh or on the page navigation. Its was working fine with old version of chatbot but with the current version its not working, Kindly help.

**Comment by canaanites** [comment]
Wanna share a snippet/gist of your code?

**Comment by slva007420** [comment]
JS code used for reconnection. 
{
            var directLine = new BotChat.DirectLine({
                token: sessionStorage.luisToken,
                conversationId: sessionStorage.conversationId,
            });
            //debugger;
            var botConnection = directLine;
            botConnection.connectionStatus$
                .subscribe(function (connectionStatus) {
                    switch (connectionStatus) {
                        case 2:
                            sessionStorage.streamUrl = botConnection.streamUrl;
                            sessionStorage.conversationId = botConnection.conversationId;
                            break;
                        case 3:
                            $.ajax({
                                url: ........,
                                dataType: "json",
                                type: "GET",
                                data: {
                                    token: sessionStorage.luisToken,
                                    streamUrl: sessionStorage.streamUrl,
                                    conversationId: sessionStorage.conversationId
                                },
                            }).done(function (reconnect) {
                                //debugger;
                                directLine.reconnect({
                                    token: reconnect.luisToken,
                                    streamUrl: reconnect.streamUrl,
                                    conversationId: reconnect.conversationId
                                });
                            });
                            break;
                    }
                });

            var user = {
                id: sessionStorage.botUserId,
                name: 'Me'
            };
            var bot = {
                id: params['botid'] || 'botid',
                name: ''
            };
            BotChat.App({
                botConnection: botConnection,
                user: user,
                bot: bot,
            }, document.getElementById("BotChatGoesHere"));
        }

**Comment by slva007420** [comment]
during the initial connection i will setup the session storage for sessionStorage as below
sessionStorage.luisToken = token;
sessionStorage.streamUrl = botConnection.streamUrl;
sessionStorage.conversationId = botConnection.conversationId;

**Comment by compulim** [comment]
@ghost we appreciate your effort.

Preservation/restoration/continuation history is big ask from the community. I have added this to our planning, it's coming. We need to re-architect Web Chat to support this feature without hacks.

**Comment by corinagum** [comment]
Please refer to #365 for tracking

**Comment by khmerforce** [comment]
@compulim hi compulim, are you still using working on storing the history so whenever the users reload the page, the conversation resume? Thanks!
