### ISSUE TITLE
Speech Locale doesn't work in Spanish recognition

### ISSUE THREAD

**Issue by tekh-ne** [Microsoft/BotFramework-WebChat#939]
I've been creating bots with Botframework to be used in Facebook messanger and web.

As web chat allows Speech recognition I wonder to promote it, but web chat only recognizes English. 

I've tried changing locale parameter to spanish but it does not work. 

Does someboy how to modify the html  code?  (I'm using the index.html  sample) Please correct my below code:

BotChat.App({
        bot: bot,
        locale: params['locale'],
        resize: 'detect',
        speechOptions: speechOptions,
        user: user,
        locale: 'es-es', // supposed to override locale to Spanish
		
		
Thanks in advance

**Comment by compulim** [comment]
I think you need to write it like this. I guess you should get an error with your code if you turn on JS strict mode.

```js
BotChat.App({
        bot: bot,
        locale: params['locale'] || 'es-es', // look at ?params=, or use ES-es by default
        resize: 'detect',
        speechOptions: speechOptions,
        user: user,
```

**Comment by compulim** [comment]
Sorry, I mistook it.

Your Cognitive Services code should looks something similar to

```js
var speechOptions = {
  speechRecognizer: new CognitiveServices.SpeechRecognizer({
    locale: 'es-ES',
    subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY' 
  }),

  speechSynthesizer: new CognitiveServices.SpeechSynthesizer({
    gender: CognitiveServices.SynthesisGender.Female,
    locale: 'es-ES',
    subscriptionKey: 'YOUR_COGNITIVE_SPEECH_API_KEY',
    voiceName: 'Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)'
  })
}
```
