### ISSUE TITLE
Animate messages as they come in

### ISSUE THREAD

**Issue by billba** [microsoft/BotFramework-WebChat#94]

**Comment by minaalfy** [comment]
I've been able to add entrance animation using the following steps
Add the CSS 
.wc-message-wrapper {
  animation-duration: 0.6s;
  animation-fill-mode: both;
  animation-name: zoomIn;
  transform-origin: bottom left;
}
.wrapper-from-me {
  transform-origin: bottom right
}
@keyframes zoomIn {
  from {
    opacity: 0;
    transform: scale3d(.3, .3, .3);
  }
  50% {
    opacity: 1;
  }
}


And to differentiate between entrance from right "messages from Bot" and other entrance from left "Messages from me"
you've to edit History.tsx line 273
To be 
<div data-activity-id={ this.props.activity.id } className={ wrapperClassName + ' wrapper-from-' + who} onClick={ this.props.onClickActivity }>
