### ISSUE TITLE
Sample: Add a privacy statement

### ISSUE THREAD

**Issue by sammydeprez** [microsoft/BotFramework-WebChat#941]
Is there anyway with the existing react component to easily add a line of text on the bottom of the component with a link to a Privacy Statement?

(Below is added by @compulim)

## Goals

- Explore how to add privacy statement before Web Chat is connected to Direct Line
   - Web Chat will only connect to Direct Line if the user consent
- Expand this sample as an alternative to minimizable UI sample (which is designed to reduce traffic to Direct Line)

**Comment by compulim** [comment]
Not easy to do it today, you need to fork.

We are planning on customizability and I added this to the list of ask. 😉

**Comment by corinagum** [comment]
@Support this would be a great sample.
