### ISSUE TITLE
Class attribute in message wrapper element may have conflicts with page styles

### ISSUE THREAD

**Issue by jpConversa** [Microsoft/BotFramework-WebChat#947]
https://github.com/Microsoft/BotFramework-WebChat/blob/15d3b354dda3dfc0621dcf1efa72e0b32d25b72b/src/History.tsx#L285}}

Is this class attribute needed? I do not see any incidence in the code and in some websites is generating a conflict because the styles of the page affect the style of the chat.

**Comment by compulim** [comment]
@jpConversa This one looks bad 😢. We didn't do a great job here.

I think we are not using class name in code, but only in CSS. If you don't see it there, it's okay to remove it.

We need to update our CSS to use more child selector instead of descendant selector.
