### ISSUE TITLE
Markdown rendering not working in hero cards

### ISSUE THREAD

**Issue by Alaiven** [Microsoft/BotFramework-WebChat#949]
I have some markdown in my 

> content.text

 property of the hero card, but the rendering doesn't seem to work... I don't know if this is an issue with the WebChat or AdaptiveCards as a whole

**Comment by christian-vorhemus** [comment]
Which version of WebChat are you using? I had similar issues with v0.12.1 but it's working fine again with the latest version (see https://cdn.botframework.com/botframework-webchat/latest/botchat.js)

**Comment by Alaiven** [comment]
I'm using the current version built from code. I also tried [botchattest](https://botchattest.herokuapp.com/)

**Comment by arashberlin** [comment]
@Alaiven same issue 

What version is used in the latest CDN?


Adaptive Cards with Markdown Url not rendering too.
I have build a fresh v0.12.1 version and with no luck.

I am working on a customized version, so the CDN version is useless for me.

Do I need to include the markdown-it to my web page?

**Comment by Alaiven** [comment]
Can anyone confirm that this is a bug and maybe propose a solution?

I'm attaching a screenshot from the current [botchattest](https://botchattest.herokuapp.com/), where you can see one of my bots displaying a Hero Card with some buttons. Markdown is not being rendered.

![markdown](https://user-images.githubusercontent.com/11237091/39693663-1991b060-51e5-11e8-988a-afd3fc8ee6c3.png)

**Comment by arashberlin** [comment]
Hi there,

I do have the same issue.  I downloaded the 0.13.1 version and compiled it and use the botchat.js in a HTML-Page for the "Web Chat"

Any idea how can I fix the issue?


-->When I use the [CDN](https://cdn.botframework.com/botframework-webchat/latest/botchat.js)  Markdown is OK

![image](https://user-images.githubusercontent.com/12381397/39694404-7e7fb45c-51e7-11e8-94f5-b37391c74cc5.png)


Here is the same page with CDN botchat.js

![image](https://user-images.githubusercontent.com/12381397/39694618-371f82b2-51e8-11e8-9a07-c0c4e12ee669.png)

**Comment by arashberlin** [comment]
@alavien:
Me too. I do have the problem when I build the code for the custom edition. Do you find any solution?

**Comment by Alaiven** [comment]
No :( It seems that AdaptiveCards library stopped accepting Markdowns. I hope it is a bug and not a feature...

**Comment by arashberlin** [comment]
found a solution [here](https://github.com/Microsoft/AdaptiveCards/issues/1421). It was deep in some posts.  You need to add the markdown-it.js before your custom  botchat.js

[related also to 972](https://github.com/Microsoft/BotFramework-WebChat/issues/972)


I don't know how to enable it in the emulator. In the Web Chat the rendering is now correct.

**Comment by compulim** [comment]
Note to fixer: in order to use Markdown in Adaptive Cards, user need to load `markdown-it.js`.

**Comment by compulim** [comment]
Will fix in PR #1034.

**Comment by compulim** [comment]
Web Chat [0.14.1](https://www.npmjs.com/package/botframework-webchat/v/0.14.1) is out with the fix #1034.
