### ISSUE TITLE
Take a picture instead of upload a file

### ISSUE THREAD

**Issue by Klervix** [microsoft/BotFramework-WebChat#951]
Hi there!

I would like to use the upload button (or add another one) to access the user's camera. The final goad is to get a picture from the user in order to create a kind of 'ID card'.
- Is there a simple way to change the upload button's action?
- Is there a way to send an image with another button (an API post with the conversation ID for example)?

Has anyone tried?

Thank you! :)

**Comment by corinagum** [comment]
@Support this would be a great sample

**Comment by compulim** [comment]
For this one, we need to have an inlined UI which use WebRTC to capture an image.

This feature could also help resolving #789.

**Comment by jbeltranluna** [comment]
Any updates on this? We would love to have the possibility of overriding the "upload-button" to launch a  barcode scanner within the bot

Thanks!

**Comment by corinagum** [comment]
No updates right now, but I have added the Help wanted label in case someone in the community wants to implement a sample. :)

**Comment by mkulgeorge** [comment]
Hi Team, 

Is the option to enable camera in the WebChat enabled?

Thanks,
George.

**Comment by corinagum** [comment]
Completed.
