### ISSUE TITLE
Formatting rules for codebase

### ISSUE THREAD

**Issue by enessoylu** [microsoft/BotFramework-WebChat#956]
Is there any plan to define code formatting rules? There is a great need of it IMHO. Integrating TSLint to the project would be great.

**Comment by compulim** [comment]
I am not a big fans of `prettier`. But we should do a better job here. Some points we discussed before:
* 2-space indent
* No trailing spaces
* Single empty line at end of file
* Bracelets are required for one-liner `if` statement
* Use `const`/`let` as much as possible
* Sorted `import` for better merging

There are more potentially controversary things that come up in my mind:
* Refactoring into multiple files
* Don't publish `*.ts` to NPM, but individual ES5/6 with source map (inlined or as `*.js.map`)
* Don't put `*.js` in the same folder as `*.ts`
* Ternary operator vs. simple `if`
* Coalesce using `||` vs. simple `if`
* Migrate from `nightmare` to `puppeteer` so we can run tests on Travis
  * Also do some cleanup, make it faster, etc
* Bumping versions

Some investigation areas:
* Move to other Observable from `rxjs` for smaller output

**Comment by billba** [comment]
If necessary I will die on the 4-space indent hill.

**Comment by compulim** [comment]
Okay, respect! Will keep that.

Bill, I have some big ambitions and we should talk after free up. 😉

**Comment by eanders-MS** [comment]
I am all about the 2-space indent these days.

**Comment by billba** [comment]
@eanders-MS we can't be friends anymore.

**Comment by cdagli** [comment]
@billba @eanders-MS What are your plans on that?

**Comment by compulim** [comment]
@corinagum do you think #1982 resolved this issue? If not, please write down what is left.
