### ISSUE TITLE
Encoding issue on message activity

### ISSUE THREAD

**Issue by electrobabe** [Microsoft/BotFramework-WebChat#957]
you have an encoding issue in your Web Chat inline implementation:
occurs when sending an Activity with text e.g. "ÜÖÄüöäß" (German Umlauts) and type="message" back through the framework API https://directline.botframework.com/

fun fact: the encoding of the buttons is FINE :smile: 
also texts in HeroCards are well encoded. just plain simple text has the wrong encoding

**Comment by VasiDeus** [comment]
Did you figure this out by chance? I am having the exact same issue.

**Comment by jvanderbiest** [comment]
You could fix it by adding the following tag to your <head> section
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

**Comment by compulim** [comment]
Support: can you see if it is still repro on CDN pre-release build? https://cdn.botframework.com/botframework-webchat/master/botchat.js.

**Comment by electrobabe** [comment]
@jvanderbiest works with the meta tag. thanks!
