### ISSUE TITLE
Unable to start new and clean conversation on other chat/browser

### ISSUE THREAD

**Issue by samvanlier** [Microsoft/BotFramework-WebChat#961]
Hi, I'm using webchat to make make a simple web interface for my bot. My bot has authentication using BotAuth to connect to an Azure Active Directory.
When I log in it works fine but when I start a new converstation on another device it contiues my conversation when it should be a new clean conversation.

I use this for getting my token and I get one but then I don't know why it does not work

```js
$.ajax({
            type: "POST",
            headers: {
                "Authorization": "Bearer " + secret
            },
            url: "https://directline.botframework.com/v3/directline/tokens/generate",
        }).done(function (response) {
            console.log(response)
            BotChat.App({
                directLine: {
                    token: response.token
                },
                user: { id: 'userid' },
                bot: { id: 'botid' },
                resize: 'detect'
            }, document.getElementById("bot"));
        });
```

**Comment by dmvtech** [comment]
Hi @samvanlier. Apologies that this was never answered. Please let me know if this is still an issue for you.

**Comment by dmvtech** [comment]
Closing since it doesn't seem to be a current problem. Please reopen if assistance still needed.
