### ISSUE TITLE
Web Chat React component - channelData

### ISSUE THREAD

**Issue by georgetroughton** [Microsoft/BotFramework-WebChat#967]
I basically have the same issue as -

https://github.com/Microsoft/BotFramework-WebChat/issues/395

I just need to know how to do this when using the React Web Chat component.

So, how to add custom channelData in React.

Cheers

**Comment by CalvinFengDatacom** [comment]
I got an answer yesterday, but how do I customize the ChannelData within typescript file? Should I modify the ActivityView.ts?

**Comment by compulim** [comment]
@georgetroughton the sample has been added to the issue #395.
