### ISSUE TITLE
Examples don't work in IE

### ISSUE THREAD

**Issue by pezholio** [Microsoft/BotFramework-WebChat#968]
Since the polyfills are no longer bundled with `botchat.js`, the examples no longer work in IE, which tripped me up as I missed the bit about polyfills in the Readme. I go around this by using feature detection, like so:

```
var script = document.createElement('script');
var src;

function check() {
  "use strict";

  try { eval("var foo = (x)=>x+1"); }
  catch (e) { return false; }
  return true;
}

if (check()) {
  src = './botchat.js';
} else {
  src = './botchat-es5.js';
}

script.src = src;
script.onload = function() {
  const params = BotChat.queryParams(location.search);

  const user = {
    id: params['userid'] || 'userid',
    name: params['username'] || 'username'
  };

  const bot = {
    id: params['botid'] || 'botid',
    name: params['botname'] || 'botname'
  };

  window['botchatDebug'] = params['debug'] && params['debug'] === 'true';

  BotChat.App({
    bot: bot,
    resize: 'window',
    user: user,
    showUploadButton: false,

    directLine: {
      secret: 'DIRECT_LINE_SECRET',
      token: 'DIRECT_LINE_TOKEN',
      webSocket: true
    }
  }, document.getElementById('chat'));
}

document.body.appendChild(script);
```

Not sure if this is the best solution, but it seems to work for me.

**Comment by compulim** [comment]
We pushed ES5 build to CDN, but it's not a production build yet. Our CI/CD has been reconfigured to push ES5 build from now on.

Currently, you can grab our development build of `botchat-es5.js` from our CDN [here](https://cdn.botframework.com/botframework-webchat/0.13.1-master.248c723/botchat-es5.js).

Thanks for reporting this.
