### ISSUE TITLE
Send box in speech listening mode don't auto scroll to far right

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#969]
Repro steps:
1. Resize Web Chat window to be as narrow as possible without clipping
2. Click on microphone button
3. Say a very long sentence, like, "A quick brown fox jumped over the lazy dogs"

Expected: when the intermediate result is shown, Web Chat should keep the latest words on the screen by scrolling right
Actual: we only show the first few words, clipped everything else

Investigations:
* We move caret with `selectionStart = selectionEnd = value.length`
  * This only works when the send box is focused
  * UX-wise, we stop listening when the send box is focused
* When speech start, turn <input> into a single-line <div>
  * Change the parent to be scrollable, and auto-scroll to far right

I think a better solution is provide multi-line support.

**Comment by corinagum** [comment]
Related to #124
