### ISSUE TITLE
Installation Failure on windows 10

### ISSUE THREAD

**Issue by prwani-microsoft** [Microsoft/BotFramework-WebChat#977]
[2018-05-11T10_36_09_562Z-debug.log](https://github.com/Microsoft/BotFramework-WebChat/files/1996261/2018-05-11T10_36_09_562Z-debug.log)

Error attached....

**Comment by compulim** [comment]
Background: `node-sass` is not pure JavaScript, it requires binaries, either precompiled or compile-on-install.

Node 10 updated its native API and `node-sass@4.7.2` does not have precompiled binaries against Node 10. So node-sass tries to compile the binaries itself and found your box does not have Python + Visual C++ + Windows SDK installed, thus, it failed.

You can either:

1. Install Python + Visual C++ + Windows SDK
2. Downgrade your Node
  * Reinstall with older Node
  * Use `nvm` (Node Version Manager)
3. Bump `node-sass` to `4.9.0`, our last bump was 6 months old (`4.7.2`)
