### ISSUE TITLE
ConversationalUpdate Incorrect userID

### ISSUE THREAD

**Issue by SpotOnCreative** [Microsoft/BotFramework-WebChat#979]
Hi everyone. I want my bot to be able to identify someone as a new, or returning person via the conversation update activity type in Bot framework.

I have this JS code hosted in an azure web app:

`<script>
      BotChat.App({
        directLine: { secret: 'XXXX' },
        user: { id: checkCookie() },
        bot: { id: 'BluePrism_Integration' },
        resize: 'detect'
      }, document.getElementById("bot"));
    </script>`

Now, this checkCookie() method for the userID field creates a new cookie where the ID is a GUID - then, whenever someone refreshes/reconnects to my bot I want the bot to use this uniqueID to check a table in Azure.

This uniqueID works (I use it elsewhere in my code), but whenever I use the message (of type Activity) to get the user ID, it doesn't correspond with the one used in the IFrame code - everytime the ConversationUpdate activity type is called it differs - yet the cookie GUID stays the same (I print it out to the console).

Here's my code:

```
        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
                // Ssay "Hello person x" or ask for some information

                if (message.MembersAdded.Any(o => o.Id == message.Recipient.Id))
                {
                    ConnectorClient connector = new ConnectorClient(new Uri(message.ServiceUrl));
                    Activity reply = message.CreateReply($"{JsonConvert.SerializeObject(message.From)} : I am your service provider virtual assistant. How can I help you today? ");
                    connector.Conversations.ReplyToActivityAsync(reply);
                }
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
```

I don't understand why the ID I give in my JS code doesn't correspond with the message.From.id userID field.

**Comment by EricDahlvang** [comment]
ConversationUpdate is sent by the direct line connector when someone (bot or user) joins the conversation.  However, when the connector sends the message it does not include the user.id from BotChat.  There's a workaround described here: https://github.com/Microsoft/BotBuilder/issues/4245#issuecomment-369311452  (Basically, do not rely on ConversationUpdate but send a 'welcome' event activity and respond to that from within the bot)

**Comment by SpotOnCreative** [comment]
This works! Thanks EricDahlvang.
