### ISSUE TITLE
uploadbutton does not get hidden and mic does not get displayed

### ISSUE THREAD

**Issue by sandtemp01** [Microsoft/BotFramework-WebChat#981]
Hi,

I am using latest version and still showUploadButton and listening does not seem to pass to javascript.
I have seen the code in https://cdn.botframework.com/botframework-webchat/latest/botchat.js which contains listening attribute in props
https://cdn.botframework.com/botframework-webchat/latest/botchat-es5.js does not exist.

Can someone see if following has any syntax or other error? 
The chat is working fine, but uploadbutton does not get hidden and mic does not get displayed

`<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
  </head>
  <body>
    <div id="bot"/>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>
      BotChat.App({
        directLine: { secret: "xxxxxx" },
        user: { id: 'xxxxxx' },
        //bot: { id: 'botid' },
        resize: 'detect',
		//showHeader: false,
		//chatTitle: 'helllo',
		showUploadButton: false,
		listening: true
		//sendTyping: false
      }, document.getElementById("bot"));
    </script>
  </body>
</html>
`

**Comment by Termindiego25** [comment]
I think you need style reference too:
```html
<link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />```
And maybe the microphone button is not showed because you need to add "speechOptions" attribute.
Can you check that? And please give the proper style to your code hahahaha

**Comment by sandtemp01** [comment]
Thanks for reply. The reference is already there. below is complete code.. 
```

<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
  </head>
  <body>
    <div id="bot"/>
    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>
      BotChat.App({
        directLine: { secret: "xxxxxx" },
        user: { id: 'xxxxxx' },
        //bot: { id: 'botid' },
        resize: 'detect',
		//showHeader: false,
		//chatTitle: 'helllo',
		showUploadButton: false,
		listening: true,
		//sendTyping: false
      }, document.getElementById("bot"));
    </script>
  </body>
</html>

```

**Comment by Termindiego25** [comment]
It is showing some error on browser console? Have you tried "speechOptions" attribute?

**Comment by sandtemp01** [comment]
Thanks.. adding speechoptions started showing me mic.. will test it more.

Do you see any reason, why following attributes are not working:
showUploadButton: false,
chatTitle: 'helllo',
sendTyping: false

**Comment by compulim** [comment]
Try the latest version, it was recently added.

There are few ways to get Web Chat:
- NPM
  - Latest production (`botframework-webchat`)
  - Latest development (`botframework-webchat@master`)
- CDN
  - Latest production (https://cdn.botframework.com/botframework-webchat/latest/botchat.js)
  - Latest development (https://cdn.botframework.com/botframework-webchat/0.13.1-master.248c723/botchat.js), see versions [here](https://www.npmjs.com/package/botframework-webchat?activeTab=versions)
- Embed iframe
  - Few months old, but very stable build, we don't bump too often
