### ISSUE TITLE
Discrepancy between Display Name and Status in web chat.

### ISSUE THREAD

**Issue by BillStrait** [Microsoft/BotFramework-WebChat#983]
If I create my bot under the name "Alice" and change the display name to "Bob" web chat will use "Bob" for the standard greeting, and "Alice" for the status. So it'll look like this:

Hi! I'm Bob. Say "hi" if you'd like to chat.
           Alice * Now

**Comment by Kartik1607** [comment]
What is your WebChat version?

**Comment by BillStrait** [comment]
I'm not sure what it was, I used the link provided by Azure. I refreshed the link the other day and the problem appears resolved. Thanks!
