### ISSUE TITLE
Keep timestamp on every messages

### ISSUE THREAD

**Issue by praveens3190** [Microsoft/BotFramework-WebChat#985]
For first message time stamp is showing but for second message, first messages time stamp was get clear .t
I want to show date and time for every message(send or receive) how to achieve this pls help.
![image](https://user-images.githubusercontent.com/30227071/40294448-448fc5c2-5cf3-11e8-9570-870d6aef0d76.png)
![image](https://user-images.githubusercontent.com/30227071/40294476-5f2ae1d2-5cf3-11e8-81a2-e79617f65cb1.png)

**Comment by Kartik1607** [comment]
Inside History.tsx you need to update

```ts
<WrappedActivity 
...
showTimestamp={ index === this.props.activities.length - 1 || (index + 1 < this.props.activities.length && suitableInterval(activity, this.props.activities[index + 1])) }
...
</WrappedActivity>
```

to 

```ts
<WrappedActivity 
...
showTimestamp=true
...
</WrappedActivity>
```

**Comment by compulim** [comment]
This feature is now in v4. And here you can find the [sample code](https://github.com/Microsoft/BotFramework-WebChat/blob/preview/samples/timestamp-grouping/index.html) to use this feature.

You can group it by:
- Do not group (show timestamp on every activity)
- Group by X milliseconds
- Do not show timestamp at all
