### ISSUE TITLE
Customization - Say "hi" if you'd like to chat

### ISSUE THREAD

**Issue by gimall** [Microsoft/BotFramework-WebChat#994]
I cannot find any section to customize "Say "hi" if you'd like to chat"

**Comment by Kartik1607** [comment]
You seem to be using an older version. In the current version, there is no such message.

**Comment by HorvatAntoine** [comment]
If i'm using the web embed version is there any solution ? As i can't just switch version.
I need to change the message for my users are non-english speakers.

**Comment by gimall** [comment]
It is incredible that there isn't an input to set this kind of message... I'm using the last version on Azure... I created the machine just a week ago...

**Comment by HorvatAntoine** [comment]
Ok i got something. I'm using a token to embed my bot. If i use the directline secret key in my GET request for the token, i get the "Say hi if you'd like to chat" and the bot icon on top of the iframe.
If i use the webchat secret key, having checked the "use preview version", i get nothing.

So if you don't wan't anything  to show up, and to possibly send your own welcome message, use the WebChat channel, as there is no "use preview version" for the DirectLine.

Hope that helps.

**Comment by gimall** [comment]
`
<script>
--
  |  
  | var defaultSendButtonColor = "#000000";
  | var url = window.location.href;
  | var botid = "XXXXXXXX";
  | var tokenOrSecret = "XXXXXXXX";
  | var tokenNeedsRenewal = "false";
  | var botHighlightColor = "#3e92d2";
  | var botAccentColor = "#dbdee1";
  | var botIconBorderColor = "#B3DBF2";
  | var userBackgroundColor = "#808c95";
  | var botBackgroundColor = "#eceff1";
  | var name = "XXXXXXXX";
  | var botIcon = "//bot-framework.azureedge.net/bot-icons-v1/XXXXXXXX.png";
  | **var welcomeMessage = "Hi! I'm " + name + ". Say \"hi\" if you'd like to chat";**
`

i

**Comment by HorvatAntoine** [comment]
I fought of modifying it with JS after page load. 
Something like that : 
document.getElementById("welcome-message").content-text="your welcome message"

**Comment by billba** [comment]
We removed this feature because it's simple to code your bot to send a welcome message in response to a `ConversationUpdate` message if that's the behavior you prefer.

**Comment by HorvatAntoine** [comment]
Yes i get that. but why does is still exist in directline then ?

**Comment by HorvatAntoine** [comment]
Well as i said i resolved this by switching to web chat channel.

**Comment by billba** [comment]
If you are seeing the welcome message it's because you didn't select the (now inaccurately named)  "preview" version of the web chat channel.

**Comment by HorvatAntoine** [comment]
Yes that is correct. That's how I got it fixed. Thanks.
